### ISSUE TITLE
cc1: error: unrecognized command line option "-Wjump-missed-init"

### ISSUE THREAD

**Issue by huanguan1978** [rakudo/rakudo#1]
parrot 2.3
rakudo-2010.04-0-gd952fc4 make error
cc1: error: unrecognized command line option "-Wjump-missed-init"
make: **\* [src/pmc/perl6_group.so] Error 1

**Comment by AlexDaniel** [comment]
Pretty sure that this issue is no longer relevant. We've never seen it for all these years because this issue tracker was hidden.

Anyway, thanks for the report.
