### ISSUE TITLE
«» with just one variable leaks a slip («$x»)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1204]
Code:
```perl6
my $x = ‘5 6 7 8’; dd «$x»
```
Result:
```
slip(IntStr.new(5, "5"), IntStr.new(6, "6"), IntStr.new(7, "7"), IntStr.new(8, "8"))
``` 

So that  ↑ gives a slip, but normally ↓ you get a plain List:
Code:
```perl6
my $x = ‘5 6 7 8’; dd «$x 1»
```
Result:
```
(IntStr.new(5, "5"), IntStr.new(6, "6"), IntStr.new(7, "7"), IntStr.new(8, "8"), IntStr.new(1, "1"))
```

IRC discussion: https://irclog.perlgeek.de/perl6/2017-10-24#i_15345542

**Comment by jstuder-gh** [comment]
I believe that this issue can be closed. There is now a commit in Rakudo that addresses this (ad684de383bb0c0ff051d7b0901583a9b5c2e398) and tests in the roast (4788582437aad792b2eac1c59fe73f433259e246).
