### ISSUE TITLE
Compound junction-assignement operators cause a hang

### ISSUE THREAD

**Issue by Grimy** [rakudo/rakudo#1205]
### How to reproduce

    $_ = 42; say $_ &= 3
 
### Expected behavior

Prints `all(42, 3)` or something similar. Maybe warn about the usage of `&=`.

### Actual behavior

perl6 hangs. This also happens with `|=` and `^=`.

### Version information

This is Rakudo version 2017.09 built on MoarVM version 2017.09.1
implementing Perl 6.c.

**Comment by vrurg** [comment]
Closed via 827aa6eebcec717e7db29b5bee1f7bb45671eabb
