### ISSUE TITLE
Rakudo is not building on Windows

### ISSUE THREAD

**Issue by lefth** [rakudo/rakudo#1208]
First, I installed MoarVM and NQP by checking out the master branch and running in each directory:

    perl Configure.pl --prefix="D:\rakudo" --make-install

To install rakudo, I tried the above command, then I tried it with `--backends=moar`, then without `--make-install` and running `gmake` separately. The result was the same. This is the part that failed:

> D:\rakudo\bin\nqp-m.bat --target=mbc --output=blib/Perl6/World.moarvm --encoding=utf8 \
>     src/Perl6/World.nqp
> While looking for 'Perl6/ModuleLoader.moarvm': no such file or directory
>    at src\vm\moar\ModuleLoader.nqp:51  (D:\rakudo\share\nqp\lib/ModuleLoader.moarvm:)
>  from src\vm\moar\ModuleLoader.nqp:41  (D:\rakudo\share\nqp\lib/ModuleLoader.moarvm:load_module)
>  from gen\moar\stage2\NQP.nqp:262  (D:\rakudo\share\nqp\lib\nqp.moarvm:load_module)
>  from gen\moar\stage2\NQP.nqp:2414  (D:\rakudo\share\nqp\lib\nqp.moarvm:statement_control:sym<use>)
>  from gen\moar\stage2\QRegex.nqp:1683  (D:\rakudo\share\nqp\lib/QRegex.moarvm:!reduce)
>  from gen\moar\stage2\QRegex.nqp:1629  (D:\rakudo\share\nqp\lib/QRegex.moarvm:!cursor_pass)
>  from <unknown>:1  (D:\rakudo\share\nqp\lib\nqp.moarvm:statement_control:sym<use>)
>  from gen\moar\stage2\QRegex.nqp:1721  (D:\rakudo\share\nqp\lib/QRegex.moarvm:!protoregex)
>  from <unknown>:1  (D:\rakudo\share\nqp\lib\nqp.moarvm:statement_control)
>  from gen\moar\stage2\NQP.nqp:952  (D:\rakudo\share\nqp\lib\nqp.moarvm:statement)
>  from <unknown>:1  (D:\rakudo\share\nqp\lib\nqp.moarvm:statementlist)
>  from gen\moar\stage2\NQP.nqp:919  (D:\rakudo\share\nqp\lib\nqp.moarvm:comp_unit)
>  from gen\moar\stage2\NQP.nqp:817  (D:\rakudo\share\nqp\lib\nqp.moarvm:TOP)
>  from gen\moar\stage2\QRegex.nqp:2330  (D:\rakudo\share\nqp\lib/QRegex.moarvm:parse)
>  from gen\moar\stage2\NQPHLL.nqp:1886  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:parse)
>  from gen\moar\stage2\NQPHLL.nqp:1802  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:execute_stage)
>  from gen\moar\stage2\NQPHLL.nqp:1835  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:run)
>  from gen\moar\stage2\NQPHLL.nqp:1838  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:)
>  from gen\moar\stage2\NQPHLL.nqp:1824  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:compile)
>  from gen\moar\stage2\NQPHLL.nqp:1524  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:eval)
>  from gen\moar\stage2\NQPHLL.nqp:1779  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:evalfiles)
>  from gen\moar\stage2\NQPHLL.nqp:1704  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:command_eval)
>  from gen\moar\stage2\NQPHLL.nqp:1630  (D:\rakudo\share\nqp\lib/NQPHLL.moarvm:command_line)
>  from gen\moar\stage2\NQP.nqp:4123  (D:\rakudo\share\nqp\lib\nqp.moarvm:MAIN)
>  from gen\moar\stage2\NQP.nqp:4118  (D:\rakudo\share\nqp\lib\nqp.moarvm:<mainline>)
>  from <unknown>:1  (D:\rakudo\share\nqp\lib\nqp.moarvm:<main>)
>  from <unknown>:1  (D:\rakudo\share\nqp\lib\nqp.moarvm:<entry>)
> makefile:448: recipe for target 'blib/Perl6/World.moarvm' failed
> gmake: *** [blib/Perl6/World.moarvm] Error 1

My toolchain is Strawberry Perl (v5.24.1). Windows 10.

Note: when I deleted the prefix directory and tried to build rakudo with `--gen-moar --gen-nqp`, I got the following error:

> src\io\asyncsocket.c: In function 'push_name_and_port':
> src\io\asyncsocket.c:484:5: error: unknown type name 'in_port_t'
>      in_port_t port;
>      ^
> makefile:578: recipe for target 'src\io\asyncsocket.o' failed
> gmake: *** [src\io\asyncsocket.o] Error 1
> The system cannot find the path specified.
> Cleaning up ...

**Comment by AlexDaniel** [comment]
FWIW another (probably different) build issue mentioned here: https://github.com/perl6/nqp/issues/377

**Comment by lefth** [comment]
I found I can build and install with no prefix:

    git clone https://github.com/rakudo/rakudo/ . && perl Configure.pl --gen-moar --gen-nqp --backends=moar && gmake && gmake install

**Comment by lefth** [comment]
And using that same source tree, I successfully built/installed to a prefix by running the configure/build commands again with a `--prefix` argument.

That doesn't solve the primary problem, though. I still can't build against the newest MoarVM and nqp.

**Comment by ugexe** [comment]
Do you are saying —prefix affects —gen-nqp=master / —gen-moar=master?

**Comment by lefth** [comment]
@ugexe No, it was an observation, but it was irrelevant. I was testing two checkouts in parallel. I just found the actual issue was in the first sentence of this post! This feels like the answer to a riddle--I had the wrong commit checked out (there is no "master" branch in the rakudo repository). I wasn't on a branch, but I think git still let me execute "git pull --rebase" without actually updating my files.
