### ISSUE TITLE
Uninitialized $_ and weird blowage (<a b c>[$_ xx 2] with 1)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1212]
Let's say you want to achieve something like this:
```perl6
say <a b c>[1 xx 2] # OUTPUT: «(b b)␤»
```

But using ``$_``:
```perl6
<a b c>[$_ xx 2] with 1
```
```
Use of Nil in string context
  in block  at -e line 1
Unable to call postcircumfix [ (Any) ] with a type object
Indexing requires a defined object
  in block <unit> at -e line 1
```
So not only ``$_`` is unitialized, but it is also trying to stringify something? Weird.

**Comment by W4anD0eR96** [comment]
FWIW

```
with 1 { <1 2 3>[$_ xx 2] } # OUTPUT (2 2)
```

**Comment by zoffixznet** [comment]
Looks like these are all from the same hive:
https://rt.perl.org/Ticket/Display.html?id=130575#ticket-history
https://rt.perl.org/Ticket/Display.html?id=132337#ticket-history
https://rt.perl.org/Ticket/Display.html?id=131548#ticket-history
https://rt.perl.org/Ticket/Display.html?id=132211#ticket-history
