### ISSUE TITLE
Improve "Return outside of routine" error

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1216]
UPDATE: Ignore OP; the [actual problem is a poor error](https://github.com/rakudo/rakudo/issues/1216#issuecomment-339953775)

--------

OP:

```
<Zoffix__> m: sub { 1.map: { return 42 } }()
<camelia> rakudo-moar 1251f771c: OUTPUT: «Attempt to return outside of any Routine␤  in block <unit> at <tmp> line 1␤␤»


<Zoffix__> bisect: sub { 1.map: { return 42 } }()
<bisectable6> Zoffix__, On both starting points (old=2015.12 new=f40babb) the exit code is 1 and the output is identical as well
<bisectable6> Zoffix__, Output on both points: «Attempt to return outside of any Routine␤  in block <unit> at /tmp/6LvcPFlvmv line 1␤»
```

**Comment by vendethiel** [comment]
Yes, that's normal.

The `map` is lazy, so it's not evaluated before trying to print it. But when it's trying to print it, it already exited the anonymous sub.

**Comment by lizmat** [comment]
Where is it printing??

**Comment by zoffixznet** [comment]
> The map is lazy, so it's not evaluated before trying to print it. But when it's trying to print it, it already exited the anonymous sub. Hence the error.

Oh right. That makes sense. But then, why does the second one here fail? The return is eagerly evaluated inside a sub:

```
<Zoffix__> m: sub { eager 1.map: { return 42 } }()
<camelia> rakudo-moar 4fca94743: ( no output )
<Zoffix__> m: sub { eager sub { 1.map: { return 42 } }() }()
<camelia> rakudo-moar 4fca94743: OUTPUT: «Attempt to return outside of any Routine␤  in sub  at <tmp> line 1␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by vendethiel** [comment]
> Where is it printing??

Sorry, I meant sinking. It's sinking because it's a top-level statement.

**Comment by jnthn** [comment]
> sub { eager sub { 1.map: { return 42 } }() }()

A `return` is bound to its immediately enclosing routine, so here it tries to return from the inner anonymous subroutine. The eager would have to be put inside of that inner sub.
