### ISSUE TITLE
Range.sum() on infinite Ranges

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#1224]
Here is current (at time of writing) implementation of Range.sum()
```perl6
method sum() is nodal {
    my ($start,$stop) = self.int-bounds || nextsame;
    my $elems = 0 max $stop - $start + 1;
    ($start + $stop) * $elems div 2;
}
```
If `int-bounds` fails, `nextsame` jumps to Any.sum()... which iterates the invocant and adds each iteration until `IterationEnd`. This means attempting to sum an infinite range will never terminate, eg. `(1..*).sum`.

Besides an infinite Range, the smallest Range I could find (on my machine) that would fail `int-bounds` is `(0 .. 1e309)`. I tried to sum that on my machine but gave up waiting after about 30 mins.

With that in mind... is there any reason why Range.sum() shouldn't just check `self.is-lazy` and if True, throw something like "Cannot sum infinite Range"

**Comment by colomon** [comment]
It is perfectly possible to have is-lazy means "**potentially** infinite".

**Comment by lizmat** [comment]
True, but in many places “is-lazy” is interpreted as “don’t go there”.  For instance, if we want to know the .elems

**Comment by zoffixznet** [comment]
>  I tried to sum that on my machine but gave up waiting after about 30 mins.

FWIW, the maximum is about 1e15, as afterwards the `1` added by `.succ` no longer fits into available precision:

```
$ perl6 -e '1e+15.succ.say'
1e+15
```

**Comment by 0racle** [comment]
With regards to the Exception text, rather than say `infinite`, it could say something similar to what `permutations` does...

    > (^21).permutations
    Cowardly refusing to permutate more than 20 elements, tried 21

**Comment by AlexDaniel** [comment]
What about returning ∞? Not saying that this is what has to be done, but why exception and not ∞?

**Comment by lizmat** [comment]
AFAIK, because we expect .elems to return something we can iterate upto without hanging indefinitely.

**Comment by AlexDaniel** [comment]
Sorry? I don't understand.

Why can't ``(1..*).sum`` return ``∞``? ``.elems`` has nothing to do with it, right?

**Comment by lizmat** [comment]
Ah, sorry, yes, *that* we could do  :-)

**Comment by zoffixznet** [comment]
> What about returning ∞? Not saying that this is what has to be done, but why exception and not ∞?

Thinking more a bit about that one, and I think exception might be a more uniform answer than `∞`

For example, sum of `-∞..∞` won't be `∞`. It could be a `NaN`, because `-∞ + ∞` is a `NaN` per IEEE, but that leaves `-∞^..^∞`, `-∞..^∞`, and `-∞^..∞`, which to my eye would result in `0`, `-∞`, and `∞` respectively. 

Also, things like `(0.1e0..1e16)` are not an infinite *Ranges* but *are* infinite lists when reified because of lack of precision to sequentially iterate a `Num`, leading to the same hanging issue the OP points out, which makes me feel reifying for .sum is not quite the right tool for the job:

```perl6
    (0.0e0..1e16).sum.say; # 500000000000000500000000000000
    (0.1e0..1e16).sum.say; # hangs
```

**Comment by AlexDaniel** [comment]
> -∞^..^∞, -∞..^∞, and -∞^..∞, which to my eye would result in 0, -∞, and ∞

I think these should be NaN, NaN and NaN. Just because it is up to but not including infinity doesn't make it something else than infinity.

**Comment by zoffixznet** [comment]
> I think these should be NaN, NaN and NaN. Just because it is up to but not including infinity doesn't make it something else than infinity. (like 1..^∞ is still ∞)

OK, agreed, because another way to write `-∞^..^∞` would be `-∞+1..∞-1` and it'd be weird if one form gave a `NaN` but another a `0`

**Comment by zoffixznet** [comment]
Some discussion on the dev channel: https://irclog.perlgeek.de/perl6-dev/2017-11-01#i_15387052

**Comment by FCO** [comment]
Maybe the response for (0..Inf).sum should be -1/12...
https://en.m.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_⋯
<https://en.m.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF>
Em qua, 1 de nov de 2017 às 14:23, Zoffix Znet <notifications@github.com>
escreveu:

**Comment by zoffixznet** [comment]
No it shouldn't. Inf + any number is Inf per IEEE. We're doing what's useful for programs running on computers, not to scratch an arbitrary pure mathematics itch.

**Comment by zoffixznet** [comment]
A few commits recently went in that address the hang, but don't address any of the special cases mentioned above and give wrong results for some of the ranges:

**NaNs are swallowed up and treated as numbers:**
```
<Zoffix__> m: say (NaN..Inf).sum
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «Inf␤»
<Zoffix__> m: say (NaN..-Inf).sum
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «0␤»
<Zoffix__> m: say (-Inf..NaN).sum
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «-Inf␤»
```

**Infinite sums for empty ranges:**
```
<Zoffix__> m: say (-Inf..-Inf).sum
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «-Inf␤»
<Zoffix__> m: say (Inf..Inf).sum
<camelia> rakudo-moar 8b24bf5cd: OUTPUT: «Inf␤»
```

**Comment by zoffixznet** [comment]
> Infinite sums for empty ranges:

Scratch that; I'd argue that's another, separate bug that Infs are treated as mathematical entities rather than IEEEs idea of Infs where all Inf are the of the same magnitude, so those Ranges should be empty, just as 1..1 is empty IMO. With some extra thinking to be done for excluded endpoints.

**Comment by 0racle** [comment]
I was going through old issues and noticed that this one looks ok to close. _Then_ I realised it was me who opened it, so I guess I'm qualified to make that call. 😄 

```raku
> $*RAKU.compiler
rakudo (2021.10)
> (1..*).sum
Inf
> (0 .. 1e309).sum;
Inf
```

**Comment by lizmat** [comment]
`(0 .. 1e309).sum` giving `Inf` feels like an issue to me.  Is it?

**Comment by MasterDuke17** [comment]
> `(0 .. 1e309).sum` giving `Inf` feels like an issue to me. Is it?

Isn't that just what happens when you do something with Nums that results in a value larger than it can represent? E.g., `say 1e308` prints `1e308`, but `say 1e308 + 1e308` prints `Inf` (and `say 1e309` prints `Inf`).

**Comment by lizmat** [comment]
Yeah, but it feels to be more natural to have it go to big integer logic?

**Comment by MasterDuke17** [comment]
> Yeah, but it feels to be more natural to have it go to big integer logic?

I don't think any other operations switch from Num to Int? In that example the user is explicitly asking for Num behavior by using the Num literal, right?

**Comment by lizmat** [comment]
I guess...  in which case we should close this issue?

**Comment by MasterDuke17** [comment]
I haven't checked all the other cases mentioned in the past comments, but if they're wrong they should probably get new issues. So yes, I think this particular issue can be closed.

**Comment by 0racle** [comment]
Yes, the original issue was that the `sum` would just hang... so that's now "fixed".

The issue with `(0 .. 1e309).sum` could be considered more of an LTA error.
