### ISSUE TITLE
Postfix hyper confusing: `>>(&func)`

### ISSUE THREAD

**Issue by TisonKun** [rakudo/rakudo#1228]
https://github.com/rakudo/rakudo/blob/23776247298f24fe374903e5239cdd61f173078a/src/Perl6/Actions.nqp#L7511-L7547

```
> [1,2,3]>>(&say)
1sub say (| is raw) { #`(Sub|140355192792552) ... }
2sub say (| is raw) { #`(Sub|140355192792552) ... }
3sub say (| is raw) { #`(Sub|140355192792552) ... }
```

I don't know even how this code can run, most of time it expects a postfix operator, so this code should die, shouldn't it?

**Comment by W4anD0eR96** [comment]
@zoffixznet

**Comment by W4anD0eR96** [comment]
Still reproduce on 2018.01

It seems

```
[1,2,3]>>(&say)
```

acts like

```
say(1, &say);
say(2, &say);
say(3, &say);
```
