### ISSUE TITLE
Unsure of method subparse, parameter %*opt 's behavior

### ISSUE THREAD

**Issue by TisonKun** [rakudo/rakudo#1243]
https://github.com/rakudo/rakudo/blob/f8e1a5faab0bdf3e7f25689b117522964c3303e4/src/core/Grammar.pm#L39-L58

```
grammar Number { rule TOP { <[A..Z]>+ } }
say Number.subparse("ABCDE", :pos(4));
# OUTPUT: ｢E｣
```
```
grammar Number { rule TOP { <[a..z]>+ } }
say Number.subparse("ABCDE", :i);
# OUTPUT: #<failed match>
```
Docs on the doc site says every adverb of regex matching can be applied.

https://docs.perl6.org/type/Grammar#method_subparse

However,

https://github.com/rakudo/rakudo/blob/f8e1a5faab0bdf3e7f25689b117522964c3303e4/src/core/Match.pm#L820-L828

seems not all of them.

Could anyone familiar with Grammar please tell me how `%*opt`  behavior?

@AlexDaniel @lizmat @TimToady @moritz

**Comment by jnthn** [comment]
The `:i` modifier affects the compilation of a regex/token/rule, and so cannot possibly be applied "from the outside". Same goes for `:s`, for example, and probably more.

**Comment by W4anD0eR96** [comment]
@jnthn I've tried some adverbs, seems `:pos`(alias `:to`) and `:orig` applied well, others make non-sense.

It's that implies what we could modify "from the outside" is no more than where we start to match and what we match?

Besides, I think that we can pass an adverb `:orig` to change what we match is out of encapsulation. The only way we pass parsing candidate ought to be by `\target`.
