### ISSUE TITLE
[Need] Recursively deal with pod-table

### ISSUE THREAD

**Issue by tisonkun** [rakudo/rakudo#1244]
## The Problem

Now we handle pod-table assuming all its rows contain raw string. However, users might want to embed pod code with pod-table, especially `C<>`. Can we recursively deal with pod table?

Below are code relevant IMO.

https://github.com/rakudo/rakudo/blob/d6cd0d2f53187c6b41a08e3d1e9b18aadf838f3f/src/Perl6/Actions.nqp#L1106-L1108
https://github.com/rakudo/rakudo/blob/d6cd0d2f53187c6b41a08e3d1e9b18aadf838f3f/src/Perl6/Actions.nqp#L1343-L1349
https://github.com/rakudo/rakudo/blob/ba718f4581a95e143147a47f26a2bc96e9b6b076/src/Perl6/Pod.nqp#L188

## Expected Behavior

Treat text in pod table raw as pod6 code.

## Actual Behavior

Raw string.

## Steps to Reproduce

```
=begin table
    $*ARGFILES        | An C<IO::CatHandle> that uses C<@*ARGS> as source
                      | files, if it contains any files, or C<$*IN> otherwise
    ------------------+--------------------------------------------
    @*ARGS            | B<Arguments> from the I<command line>.
    ------------------+--------------------------------------------
=end table

say $=pod;

```
```
[Pod::Block::Table
  $["\$*ARGFILES", "An C<IO::CatHandle> that uses C<\@*ARGS> as source files, if it contains any files, or C<\$*IN> otherwise"]
  $["\@*ARGS", "B<Arguments> from the I<command line>."]
]
```
## Environment
* Operating system: Mac OS X 10.12.6
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2017.10-125-g360eb2289 built on MoarVM version 2017.10-57-gd257df23
implementing Perl 6.c.
```

**Comment by W4anD0eR96** [comment]
#1893

**Comment by tbrowder** [comment]
I think this is a dup of another issue—will look later.

**Comment by TisonKun** [comment]
not sure if this a good design, but the result sounds  like a good news.

**Comment by TisonKun** [comment]
closed as no longer interested.

**Comment by AlexDaniel** [comment]
@tbrowder any news on this? Didn't we fix something like this recently?

**Comment by tbrowder** [comment]
Not fixed, but I think doable. Hard work, though.

**Comment by TisonKun** [comment]
@AlexDaniel reply here. I close issues because I myself am not interested in it any more.

You can open another issue and refer to this to continue the discussion. But I am also uninterested to re-close this issue...

**Comment by tisonkun** [comment]
As https://github.com/rakudo/rakudo/issues/1222#issuecomment-346952020, close this one. Please file another to continue the discussion if any.
