### ISSUE TITLE
Reserved characters in the source code cause segfaults (#򫳞)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1247]
Code:
```perl6
#򫳞
```
Result:
*Segmentation fault*

It does not happen reliably, use this bash snippet to reproduce:
```
while perl6 -e '#򫳞'; do echo $((++i)); done
```

The character in question is ``<reserved-ABCDE>`` (0x0ABCDE).

**Comment by lizmat** [comment]
FWIW, on MacOS no segv after more than 1100 iterations

**Comment by AlexDaniel** [comment]
![2017-11-12-211537_872x546_scrot](https://user-images.githubusercontent.com/5507503/32702367-e238abf8-c7ee-11e7-9566-b59b42767467.png)

**Comment by AlexDaniel** [comment]
There's a chance that it is already fixed in https://github.com/MoarVM/MoarVM/commit/11b12a268e2d2972ef3a62e3707f4ca9a306e09f (no bump yet).

**Comment by lizmat** [comment]
FWIW, I’ve had it run for multiple hours (141118 times).  No breakage on MacOS

**Comment by zoffixznet** [comment]
Can't repro on Bodhi Linux either. What perl6 version is the SEGV in?

**Comment by AlexDaniel** [comment]
This is Rakudo version 2017.10-176-g68b2891d9 built on MoarVM version 2017.10-57-gd257df23
implementing Perl 6.c.

**Comment by AlexDaniel** [comment]
As suspected, this no longer crashes. How do we test this? @samcv would it make sense to have a test file with every single unicode character… or something like that?

**Comment by samcv** [comment]
Yes that's correct it was fixed in https://github.com/MoarVM/MoarVM/commit/11b12a268e2d2972ef3a62e3707f4ca9a306e09f

We can just try accessing the Unicode property values for unassigned codepoints, though we actually already do this. Hmm. Will think about it.

**Comment by zoffixznet** [comment]
> Hmm. Will think about it.

@samcv ping. Any new ideas?

**Comment by samcv** [comment]
@zoffixznet I've actually been working on something like that. I was using it to test the database when I made large changes to ucd2c.pl to make sure nothing broke, but the end plan was to add it to roast.

I will work on getting it into roast.

**Comment by samcv** [comment]
Think you guys both noticed the PR i made but going to link it for completeness https://github.com/rakudo/rakudo/pull/1316
