### ISSUE TITLE
List.new creates unwanted containers

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1260]
[`List.new`](https://github.com/rakudo/rakudo/blob/4fca94743/src/core/List.pm#L342-L356) uses `**@items` to gather stuff to make a list out of, but that gives each item an own container, which produces a mutable `List`:

```
[14:04] <asdsdfgh> m: my $l := List.new: 42; say $l[0] = 42;
[14:04] <+camelia> rakudo-moar 8ccb60e39: OUTPUT: «42␤»
```

Instead, the method should probably just do something similar to what [`&infix:<,>` does](https://github.com/rakudo/rakudo/blob/4fca94743/src/core/List.pm#L1421-L1458)

**Comment by jnthn** [comment]
`**@items is raw` would also do it (and retain the mutability or lack thereof of the arguments)

**Comment by zoffixznet** [comment]
Fixed in https://github.com/rakudo/rakudo/commit/d80df073ad
