### ISSUE TITLE
t/04-nativecall/12-sizeof.t flaps

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1262]
~~Seems to be a regression between 2017.10 and 2017.11~~

See https://irclog.perlgeek.de/perl6-dev/2017-11-21#i_15479409

No more info *yet*.

**Comment by AlexDaniel** [comment]
Panic mode off, it's just a flapper.

**Comment by AlexDaniel** [comment]
OK, reproduced on non-i386 system. SEGV. More info coming :)

**Comment by AlexDaniel** [comment]
I golfed it to this, and now I'm stuck: https://gist.github.com/AlexDaniel/f7e43792ad2e4a29c3f13dfdf2453506

As always, you have to run it in a loop:
```bash
while perl6 t/04-nativecall/12-sizeof.t; do :; done
```

**Comment by ab5tract** [comment]
Can't reproduce on `aarch64` using Rakudo `v2024.04-79-g66c4acad2`. No flapping, no SEGV.
