### ISSUE TITLE
LTA building during network outages

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1265]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

I've been having Internet issues this week. I already have a rakudo checkout with both nqp and MoarVM checked out and built as well. 

I went to modify NQP and when I tried to build the normal way I usually built, it refused to continue after it failed to resolve github.com host:

```
2017.10.3 zoffix@VirtualBox~/CPANPRC/rakudo (master)$ perl Configure.pl --gen-moar --gen-nqp --backends=moar; make; make test; make install
ATTENTION: no --prefix supplied, building and installing to /home/zoffix/CPANPRC/rakudo/install
/home/zoffix/CPANPRC/rakudo/install/bin/nqp-m: 2: exec: ../install/bin/moar: not found
fatal: unable to access 'https://github.com/perl6/nqp.git/': Could not resolve host: github.com
Command failed (status 32768): git fetch
make: *** No rule to make target `m-all', needed by `all'.  Stop.
make: *** No rule to make target `m-test', needed by `test'.  Stop.
make: *** No rule to make target `m-install', needed by `install'.  Stop.
2017.10.3 zoffix@VirtualBox~/CPANPRC/rakudo (master)$ 
```

There's probably some way to build it offline, if you remove the `--gen-nqp` options, but I don't offhand know what it is, and it's really annoying that it completely refuses to proceed just because it failed to fetch (there weren't even any new commits since last fetch!).

It think if there's already a checkout, it should just proceed to build what it got in these situations, while issuing the same `ATTENTION: ` thing it does for `no --prefix`:

```perl6
ATTENTION: Command failed (status 32768): `git fetch`. Found an existing checkout, trying to build anyway.
```

This way if the network goes off I can still use my normal build procedure to build the perfectly usable checkout I already have.

**Comment by lizmat** [comment]
Closing this as `--gen-nqp` and `--gen-moar` imply needing network access.
