### ISSUE TITLE
LTA error with sock using already-bound port

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#1266]
```
start react whenever IO::Socket::Async.listen("localhost", 11111) { };
sleep 1;
react whenever IO::Socket::Async.listen("localhost", 11111) { };
CATCH { default { say .^name, ': ', .Str } }

# OUTPUT: «X::AdHoc+{X::Await::Died}: Unexplained error␤»
```
Please explain that error. :->

**Comment by zoffixznet** [comment]
I [fixed the cause](https://github.com/rakudo/rakudo/commit/3166400d91a7350b86cd02f4f302919a25073fd6) of the "Unexplained error" and [started a test for this ticket (currently todoed and still in need of proper message text specified)](https://github.com/rakudo/rakudo/commit/3166400d91a7350b86cd02f4f302919a25073fd6), but the newly explained error ain't very good either—just says "invalid argument"—so this needs further fixin'.

**Comment by dogbert17** [comment]
The behavior is now:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.10-57-gbfe2ad6 built on MoarVM version 2018.10-26-g318e1ec
    implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 gist.pl6 
    X::AdHoc+{X::React::Died}: address already in use

Should the message perhaps be: **port (<insert portnumber if possible>) already in use**
or something along those lines.

**Comment by ab5tract** [comment]
The error message now looks like this:

```
> ./rakudo-m issues/r1266.raku
X::AdHoc+{X::React::Died}: address already in use (address: localhost:11111)
```
