### ISSUE TITLE
Argless default for .classify()

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#1281]
I wanted just gonna submit a pull request, but I figured this should probably go through at least a least a little bikeshedding.

## The Problem

Currently, calling classify without argument __dies__.
```
> <A A A A B B B C C D>.classify()
Must specify something to classify with, a Callable, Hash or List
```
## Expected Behavior

My personal preference for default behavior is for objects to classify against themselve (ie. to classify against the block `{ $_ }`
```
 > <A A A A B B B C C D>.classify({ $_ })
{A => [A A A A], B => [B B B], C => [C C], D => [D]}
```
## Discussion points
I brought it up on #perl6 and discussions start [here](https://irclog.perlgeek.de/perl6/2017-11-29#i_15509218)

While comments were made on the usefulness of classifying an item against itself (eg. why not just use .Bag) the general consensus was that it was at least a sane default.

TimToady [suggested](https://irclog.perlgeek.de/perl6/2017-11-29#i_15509304) that _"classification by type might be a more reasonable default"_ ...
```
> quietly say <a 1 2.3 4+1i 1/2 3 4 z>.classify:{.WHAT}
{(ComplexStr) => [4+1i], (IntStr) => [1 3 4], (Str) => [a z], (RatStr) => [2.3 1/2]}
```
Personally I think this makes less sense as the default.  
If you take the example `<john paul george ringo>.classify({ .chars })`, you see that `classify` already acts on a `{ $_ }` block, it's just that currently you need to call an explicit method on `$_`.

Additionally, if `classify(*)` can be fixed...
```
> say <a 1 2.3 4+1i 1/2 3 4 z>.classify(*) 
Doesn't make sense to classify with itself
```
Then classifying by type becomes as simple as `.classify(*.WHAT)`

## Changes required
Very minimal change of setting the default for `$test`
```
multi method classify($test = {$_}, ...)
```
This will also allow us to get rid of at least one multi candidate, and it spectests clean.

**Comment by zoffixznet** [comment]
If we have to add anything at all, then `{$_}`, seems a reasonable default; makes more sense to me than classifying by type.

However, I'd argue for the opposite way: we should just remove [the two(?) routines](https://github.com/rakudo/rakudo/blob/4fca9474362f3362603ea79dd35fa0c7d3a1ef8d/src/core/Any.pm#L131-L136) that judge whether it makes sense to classify with self and just let the usual X::Multi::NoMatch error be the response for those cases. The `{$_}` or `*.self` as args are pretty short to write and are a lot more self-explanatory and I don't think classify routines are that oft-used to need much huffmanization.

We don't do `.map()` to mean `.map({$_})`; we don't do `.grep()` to mean `.grep(?*)`; this feels the same way: there's no strong and obvious default and we're adding something just to for the sake of adding it.


> Additionally, if classify(*) can be fixed...

IMO that should just be removed and let the regular multi dispatch error show up (same as, e.g., `say 42.map: *` does). 

> Then classifying by type becomes as simple as .classify(*.WHAT)

`*.WHAT` is just a `Whatever` type object. `.WHAT` is not a real method, so that doesn't create a `WhateverCode`. You'd, presumably, be hitting the same multi as `.classify(*)`

**Comment by 0racle** [comment]
We could default to `{$_}` and still get rid of those 2 candidates.

With regards to `map` and `grep`, my thinking is that it's an unfair comparison because they are semantically different. Firstly `map` and `grep` can be lazy, `classify` can never be lazy.

Additionally, if `map` defaulted to `{$_}` it'd almost be a no-op. Unlike `classify({$_})`, the data would come out the same way it went in. (Almost the same applies to `grep` with the exception of Falsey values).

**Comment by jnthn** [comment]
@0racle Do you have a practical example of when classifying on `{ $_ }` is useful? I don't see one right away, which makes it harder for me to see the value of making it the default.

**Comment by 0racle** [comment]
Well, not dying is pretty practical.

It's might also be fairly instructive/illuminating for a newbie to figure out what `classify` does if it has a sane default.

---
On a more selfish level, this came about because I'm writing a blog post on the differences between Python's `itertools.groupby` and Perl 6's `.classify`
```
>>> {k: list(g) for k, g in itertools.groupby('AAAABBBCCDAABBB')}
{'A': ['A', 'A'], 'B': ['B', 'B', 'B'], 'C': ['C', 'C'], 'D': ['D']}
>>> {k: list(g) for k, g in itertools.groupby(['john', 'paul', 'george', 'ringo'], len)}
{4: ['john', 'paul'], 6: ['george'], 5: ['ringo']}
```
They look like they do the same thing initially, but `groupby` is actually quite difference and has some interesting use cases that I'm writing about.

But when comparing the code, `<A A A A B B B C C D>.classify({ $_ })` just looked... _ugly_. This article will likely be viewed by some Python users, and I'd like to show Perl 6 in it's best light.

---

So that's my selfish reason, but to re-stress the point... I think (a) not dying, and (b) having a sane default, is better (and more practical) than the current situation.

**Comment by zoffixznet** [comment]
>  just looked... ugly

FWIW: Can also write it as `.classify: *.self`

**Comment by FCO** [comment]
Classify could be lazy if we add the possibility to it reduce/produce its
values.

For example:

^Inf .classify: * %% 2, :produce{[|$^a, $^b]}

Could return:

{True => [0]}, {True => [0], False => [1]}, {True => [0, 2], False => [1]},
...

Em qua, 29 de nov de 2017 às 22:40, 0racle <notifications@github.com>
escreveu:

**Comment by 0racle** [comment]
> Classify could be lazy if we add the possibility to it reduce/produce its values.
This is interesting, but ultimately a separate discussion to whether `classify` should have a default.

**Comment by 0racle** [comment]
The resistance to this has typically been "why would you want that". To look at it another way, is there any good reason anyone can provide for why this _should not_ be default (besides "why would you want that").

As [masak](https://irclog.perlgeek.de/perl6/2017-11-29#i_15509244) put it: _"why would you ever want to do [a thing that even remotely makes sense]?" usually doesn't hold up as a counterargument in the Perl world_

If the powers that be are intent on not giving `classify()` a default, could we at least make `.classify(*)` do the same as `.classify({$_})`. To quote masak again: _I think the error message "Doesn't make sense to classify with itself" could easily just be replaced by logic which carries out the thing. I don't really see why .classify should be the judge of what makes sense or not_

**Comment by lizmat** [comment]
I think masak’s point was from the time where there was no “classify-list” yet that could be applied to a hash of a previous .classify.  Thus, a .classify(*) could be used to set up an initial state to be later used by .classify-list.

I would be +1 in making .classify(*) be the same as .classify({$_}) after the 2017.12 release.

**Comment by zoffixznet** [comment]
> The resistance to this has typically been "why would you want that"

My reading is: *"would this default be something people would easily assume to be the default"*. We could make `.classify(*.uc.flip.substr(1,3).flip)` the default, but it'd be pointless because it's not an obvious default. Any "good practice" would recommend avoiding the non-obvious default, thus making whatever default we make useless and confusing.

This applies double to `.classify` because it's both a non-trivial routine and one that isn't frequently used. Also the proposed feature isn't something that's unavailable, so it's just an argument that we should reduce 4 characters of writing to zero.

> could we at least make .classify(*) do the same as .classify({$_})

That still makes the language inconsistent. We don't have `(*)` mean `({$_})` in things like `.map` or `.grep`. Making classify be different creates an inconsistency IMO.

----

Personally, I don't care two bits what some Python users you want to show this to think about it. I rather we have shorter docs, our codebase [fewer routines](https://github.com/rakudo/rakudo/blob/master/src/core/Array.pm#L833-L1157), and our users self-documenting code.

**Comment by lizmat** [comment]
> On 20 Dec 2017, at 12:49, Zoffix Znet <notifications@github.com> wrote:
> 
> The resistance to this has typically been "why would you want that"
> 
> My reading is: "would this default be something people would easily assume to be the default". We could make .classify(*.uc.flip.substr(1,3).flip) the default, but it'd be pointless because it's not an obvious default. Any "good practice" would recommend avoiding the non-obvious default, thus making whatever default we make useless and confusing.

Actually, I just realized there *is* a reason to have (*) be ({$_}): in the case of multi-level classify’s:

$ 6 'say ((1,2,3),(1,2,4),(1,2,5)).classify({$_})'
{1 => {2 => {3 => [(1 2 3)], 4 => [(1 2 4)], 5 => [(1 2 5)]}}}

I think in that case, it very much makes sense.


> This applies double to .classify because it's both a non-trivial routine and one that isn't frequently used. Also the proposed feature isn't something that's unavailable, so it's just an argument that we should reduce 4 characters of writing to zero.
> 
> could we at least make .classify(*) do the same as .classify({$_})
> 
> That still makes the language inconsistent. We don't have (*) mean ({$_}) in things like .map or .grep. Making classify be different creates an inconsistency IMO.

Personally, I wouldn’t be against that: it could well be that the value is a Proxy that has a FETCH with side-effects?


Liz

**Comment by zoffixznet** [comment]
> If we have to add anything at all, then {$_}, seems a reasonable default

I actually withdraw that comment. The discussion so far involved numbers and strings, but the `{$_}` classify has likely unwanted behaviour with non-value-type objects (each object behaves as its oen class with just it in it), and surprising behaviour when dealing with allomorphs (same as in sets, they're treated as entirely different from their non-allomorphic cousins)

**Comment by 0racle** [comment]
I reiterate that in lieu of a default, I'm happy with `.classify(*)` doing `.classify({$_})`. As lizmat highlighted, there are some legitimate use-cases for it. The current error message is problematic because it purports to tell the user they don't want something they may well indeed want.

The existence of the error message itself also implies that the we suspect people might try to use it that way. Rather than scolding them, why not just do the thing they likely wanted.

**Comment by smls** [comment]
> `.classify(*)` doing `.classify({$_})`.

I really do not think that's a good idea.

A `Whatever` value is **not** a `WhateverCode` representing the identity function

Making it act as if it was, for this method, opens up a can of worms with various other methods that accept `Callable`s or smartmatchables wanting to use it the same way, and conflicting with its current usage in the API.

The meaning of a `Whatever` value in the current Perl 6 setting API, is pretty consistently along the lines of "whatever there is"  / "however many there are" &ndash; as in, "no limit".  
I think it would be best to keep it that way.

The identity function is expressed as follows in Perl 6:

``` perl6
*.self
```

And I think that writing `.classify(*.self)`, as @zoffixznet suggested above, is perfectly reasonable - it's self-explanatory and still short and clean.

Should Perl 6 get an _even shorter_ way to express the identity function, maybe as a subroutine along the lines of Haskell's `id` function? I don't think there's a great need for it, but that's a separate discussion.

Just please don't start adding special-cased overloads to individual callback-accepting methods, without thinking this through.

**Comment by 0racle** [comment]
Oh, yeah... This issue. Seems I'm the only one who voiced support for changing anything here. I've accepted the current implementation and moved on.

The only valid use-case is multi-level classify as mentioned by lizmat, but it's probably a rare enough use-case that those who need it can just do `*.self`.

Unless there's any other reason to change, I'm happy to have this closed out.

**Comment by lizmat** [comment]
As requested by op.  Thanks all for the thoughts that have gone into this!

**Comment by jubilatious1** [comment]
> > just looked... ugly
> 
> FWIW: Can also write it as `.classify: *.self`

I like this, and I like the current behavior (Rakudo 2021.06). One small niggle with a LTA error message:

```
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.06.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.06.

To exit type 'exit' or '^D'
> <A A A A B B B C C D>.classify({ $_ })
{A => [A A A A], B => [B B B], C => [C C], D => [D]}
> <A A A A B B B C C D>.classify: *.self
{A => [A A A A], B => [B B B], C => [C C], D => [D]}
> <A A A A B B B C C D>.classify: *
Doesn't make sense to classify with itself
  in block <unit> at <unknown file> line 1

> <A A A A B B B C C D>.classify
Must specify something to classify with, a Callable, Hash or List
  in block <unit> at <unknown file> line 1

```

Can the error message _Doesn't make sense to classify with itself_ be changed  to something like:  

_Bare whatever-star not accepted for classify, try: *.self_
