### ISSUE TITLE
Passing named args without spaces between them silently fails in some cases

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1294]
If you're passing a named arg, separate it with a comma, and pass two more named args without separating them, things work as expected:

```
$ perl6 -e 'my $ber = 99; -> $ where .z: :z, :foo:bar($ber) {}(class { method z (:$foo, :$bar) { dd [$foo, $bar ]; True } } )'
[Bool::True, 99]
```

But if you merely replace the first arg with a positional arg, the named args appear to be silently ignored:

```
$ perl6 -e 'my $ber = 99; -> $ where .z: 42, :foo:bar($ber) {}(class { method z ($v?, :$foo, :$bar) { dd [$foo, $bar ]; True } } )'
[Bool::True, Any]

$ perl6 -v
This is Rakudo version 2017.10-3-gf40babb built on MoarVM version 2017.10
implementing Perl 6.c.
```

**Comment by JJ** [comment]
This now returns

```
Array element = [Bool::True, 99]
```

So I would say it's fixed, right?

**Comment by vrurg** [comment]
It seemingly is. Needs a test, I guess.

**Comment by lizmat** [comment]
Closing with https://github.com/Raku/roast/commit/7661a062fc
