### ISSUE TITLE
Another 'but'ting issue on Str and Enum

### ISSUE THREAD

**Issue by tisonkun** [rakudo/rakudo#1296]
```
use Test;

enum Day <Sun Mon Tue Wed Thu Fri Sat>;

{
    my $x # = <define-part>; # See below for values
    ok $x.does(Day),      'Can test with .does() for enum type';
    ok $x ~~ Day,         'Can smartmatch for enum type';
    ok $x ~~ Day::Mon,    'Can Smartmatch for enum value';
    my $check = 0;
    given $x {
        when Day::Mon { $check = 1 }
        when Day::Tue { $check = 2 }
    }
    is $check, 1,         'given/when with enum values';
    $check = 0;
    given $x {
        when Tue { $check = 1 }
        when Mon { $check = 2 }
    }
    is $check, 2,         'given/when with enum values';
}
```

1.  `<define-part>` is `'Today' but Day::Mon`, all fails
2.  `<define-part>` is `Day::Mon but 'Today'`, ok 1, 2, fails 3, 4, 5
3.  `<define-part>` is `'Day::Mon;`, all ok

Replace RT#124832 with this issue. ✓

**Comment by AlexDaniel** [comment]
This is an interesting ticket, and I like that it comes with tests.

**Comment by JJ** [comment]
I am not sure I understand the issue, but the code anyway fails due to the # in the middle of a sentence. I'll try and see what's the story behind and reverse it...

**Comment by JJ** [comment]
This behaves exactly the same now.

**Comment by tisonkun** [comment]
As https://github.com/rakudo/rakudo/issues/1222#issuecomment-346952020, close this one. Please file another to continue the discussion if any.
