### ISSUE TITLE
Warning in Failure.DESTROY sometimes warns about failures that *were* handled (sort-a)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1298]
Let's assume we have this code:
```perl6
for 1 { my $x = ‘boom’.Numeric; $=1 }
```
So we are turning ‘boom’ into a numeric, which of course returns a Failure. This Failure is then saved into a variable, and everything is OK. That's correct.

Now let's put more sweat into the same code:
```perl6
for ^1000 { my $x = ‘boom’.Numeric; $=1 }
```

Result:
```
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏boom' (indicated by ⏏)
  in block <unit> at -e line 1

WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏boom' (indicated by ⏏)
  in block <unit> at -e line 1

WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏boom' (indicated by ⏏)
  in block <unit> at -e line 1

WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏boom' (indicated by ⏏)

… and so on
```

Does it mean that Failures blow up when garbage collected?

**Comment by jnthn** [comment]
Yes, and this is an intended behavior, to detect `Failure`s that were never disarmed. Assigning them into a variable doesn't do that; calling `.so`, for example, would.

**Comment by AlexDaniel** [comment]
What would be an example of this detecting an error in someone's code? Asking for a friend.

**Comment by jnthn** [comment]
The original submission here is most likely a logic error if it showed up in a real program: why would one assign something into a variable and not use it?

**Comment by zoffixznet** [comment]
> Does it mean that Failures blow up when garbage collected?

No, it's a *warning*. A warning that you never handled a Failure object.

> What would be a practical example of this detecting an error in someone's code? Asking for a friend.

If you neither handled a Failure nor ever made it explode, the best case scenario is you have unused code, and the worst case scenario is your program is operating with erroneous data when it should've bailed out.

This isn't needless.

**Comment by zoffixznet** [comment]
> the best case scenario is you have unused code, and the worst case scenario is your program is operating with erroneous data when it should've bailed out.

OP is the example of the former and here's an example of the latter:

```
    sub load-customer-orders {
        Failure.new: "Customer canceled all the orders"
    }

    my $n-molds = load-customer-orders.elems;
    say "Making $n-molds molds for the widgets!";
    say "I sure hope the number is accurate. These are expensive!";

    for ^100 { $ = eager -1000..rand }

    # OUTPUT:
    # 2017.11.50 zoffix@VirtualBox~$ perl6 /tmp/z.p6
    # Making 1 molds for the widgets!!
    # I sure hope the number is accurate. These are expensive!
    # WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you # can mark it as handled by calling .Bool, .so, .not, or .defined methods. The # Failure was:
    # Customer canceled all the orders
    #   in block <unit> at /tmp/z.p6 line 5
    #
    # 2017.11.50 zoffix@VirtualBox~$
```

**Comment by zoffixznet** [comment]
A counter-point to the above is this case where more than one Failure is involved:

```
22:04 |   | e: use Test; for ^1000 { my $ = Failure.new < Failure.new; CATCH { default {} } }
-- | -- | --
22:04 | evalable6 | Zoffix, rakudo-moar 8ba3c86e7: OUTPUT: «WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it…»
22:04 |   | Zoffix, Full output: https://gist.github.com/06e558ac81c8f261ad2d9c5236b06cfa
```

The exlosion happens when `.Real` is called inside `<` op, but the explosion of the first Failure prevents the second Failure from ever exploding, resulting in warnings for failures that weren't technically left unhandled.

**Comment by zoffixznet** [comment]
Actually... opened this as a new ticket: https://github.com/rakudo/rakudo/issues/1502
