### ISSUE TITLE
[POD] pod parsing doesn’t seem to recognize unspace

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#1302]
I expected this to parse ok (using a backslash to continue a line):

    =begin table :caption<foo> \
      :bar<baz>
    a
    =end table

but I get this error:

===SORRY!=== Error while compiling /usr/local/people/tbrowde/mydata/tbrowde-home-bzr/perl6/p6-repo-scripts-and-tests/bad-pod-unspace.p6
Preceding context expects a term, but found infix = instead
at /usr/local/people/tbrowde/mydata/tbrowde-home-bzr/perl6/p6-repo-scripts-and-tests/bad-pod-unspace.p6:3
------> =begin table :caption<fo⏏o> \

See also RT #122343, quote

    There are several tests that are currently skipped in
    S02-lexical-conventions/unspace.t that cover the interaction of
    unspace and POD directives; all of them are currently skipped as
    parsefails.

**Comment by tbrowder** [comment]
Closed because I should have followed directions in documentation synopsis by using the ‘=‘ continuation character on the following line.

**Comment by zoffixznet** [comment]
> Closed because...

Sorry, do you mean this Issue should be closed?

**Comment by tbrowder** [comment]
Yes, please, my bad.
