### ISSUE TITLE
LTA Error when assigning to Range element

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1305]
Related to [RT#125964](https://rt.perl.org/Ticket/Display.html?id=125964#ticket-history) with possibly-similar [fix](https://github.com/rakudo/rakudo/commit/c9699ab):

It talks about assinging to `Str` that is nowhere to be found:
```
Zoffix │ m: my $a = 1..10; $a[42] = 21                                                                                                                           │
 camelia │ rakudo-moar 062c27f34: OUTPUT: «Cannot modify an immutable Str (Nil)␤  in block <unit> at <tmp> line 1␤␤»
```

By comparison, doing the same with a List gives this:

```
 Zoffix │ m: my $a = (1,); $a[42] = 21                                                                                                                            │
camelia │ rakudo-moar 062c27f34: OUTPUT: «Cannot modify an immutable List ((1))␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by jstuder-gh** [comment]
I believe this can be closed, since the error message was modified in commit 51e0aa0959797bbdb011efda877b3648cdd999a2.

**Comment by zoffixznet** [comment]
Could use a test in [rakudo's test suite](https://github.com/rakudo/rakudo/blob/master/t/05-messages/02-errors.t)

**Comment by jstuder-gh** [comment]
I hadn't really thought about it before now, but how should we test these error messages? I was planning to use throws-like and include a message, but do I want to use the literal ```'Cannot modify an immutable Range'```? If that is the case, then the spectest dictates the error message for all implementations, which may or may not be what we want.

Or should we leave messaging somewhat flexible, and just a test against the key issue that it didn't mention Range? Something like below: 

    :message(/ 'immutable Range' /)

**Comment by AlexDaniel** [comment]
> the spectest dictates the error message for all implementations

Which is why Zoffix++ suggested to write a [*rakudo* test](https://github.com/rakudo/rakudo/blob/master/t/05-messages/02-errors.t), not a roast test.

The test should be specific-enough to make sure that this change does not regress, and that the message is relatively sane. Rakudo tests do not guarantee anything, and can be changed at any time.
