### ISSUE TITLE
Frequent-ish SEQV in Perl 5 integration tests

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1308]
(I see status 11 and I assume all of those due to SEGV)

Got SEGVs thrice in a row this afternoon on my 24-core VM and now ran the first spectest on my 4-core home box and got similar crop of SEGVs.

All of these flopped on my 24-core VM but now on my home box looks like 100% reproduceable when running with `t/fudgeandrun t/spec/S01-perl-5-integration/basic.t` but refuses to SEGV with `./perl6 t/spec/S01-perl-5-integration/basic.rakudo.moar`

```
t/spec/S01-perl-5-integration/basic.rakudo.moar                 (Wstat: 11 Tests: 12 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 15 tests but ran 12.
t/spec/S01-perl-5-integration/method.rakudo.moar                (Wstat: 11 Tests: 10 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 13 tests but ran 10.
t/spec/S01-perl-5-integration/roundtrip.t                       (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 5 tests but ran 0.
Files=1231, Tests=75935, 556 wallclock secs (12.80 usr  2.36 sys + 1822.87 cusr 188.51 csys = 2026.54 CPU)
Result: FAIL
```

**Comment by zoffixznet** [comment]
I golfed this one down to this, running with latest Inline::Perl5:

```perl6
for ^1000 { EVAL('sub { shift->() }', :lang<Perl5>)({;}) }
```

I hunted the bug down to https://github.com/rakudo/rakudo/commit/83eac0e42352f43267100bdbbe1221091f6119df and specifically to @timo's commit https://github.com/MoarVM/MoarVM/commit/ba1fb954222810a87f0f5501290877fdcba6aa05


I played around with the code and discovered that commenting out [this portion](https://github.com/MoarVM/MoarVM/blob/509315503d8574257d04e8b109537f0810d958a4/src/jit/graph.c#L1849-L1865) avoid the bug (as is setting `MVM_JIT_DISABLE`). 

I then stuck a bunch of prints inside src/core/exceptions.c and it seems like after running a bunch of `run_handler`, the SEGV happens some time after [this branch is executed](https://github.com/MoarVM/MoarVM/blob/509315503d8574257d04e8b109537f0810d958a4/src/core/exceptions.c#L344-L345). 

Sticking prints right before and right after calls to `run_handler()`, the last print that occurs is `EXITING: MVM_exception_throwobj`.

Hope this info helps the fixage :)

**Comment by niner** [comment]
Got it to segfault in gdb:

Thread 1 "moar" received signal SIGSEGV, Segmentation fault.
0x00007fffefcc8f88 in return_retval (ax=1, sp=0x30cd560, retval=0x0) at p5helper.c:998
998             AV* const av = (AV*)SvRV(retval);
(gdb) bt
#0  0x00007fffefcc8f88 in return_retval (ax=1, sp=0x30cd560, retval=0x0) at p5helper.c:998
#1  0x00007fffefcc92e4 in post_callback (ax=1, sp=0x30cd560, items=1, args_rv=0x4b3aa18, err=0x0, retval=0x0) at p5helper.c:1027
#2  0x00007fffefccaa6d in p5_call_p6_callable (my_perl=0x4fb18c0, cv=0x4fd39d8) at p5helper.c:1171
#3  0x00007fffef1f9261 in Perl_pp_entersub (my_perl=0x4fb18c0) at pp_hot.c:4231
#4  0x00007fffef1f1076 in Perl_runops_standard (my_perl=0x4fb18c0) at run.c:41
#5  0x00007fffef16c306 in Perl_call_sv (my_perl=<optimized out>, sv=0x4b3a958, flags=<optimized out>) at perl.c:2848
#6  0x00007fffefcc7c92 in p5_call_code_ref (my_perl=0x4fb18c0, code_ref=0x4b3a958, len=1, args=0x1a17c60, count=0x43d1d10, err=0x43d1d70, type=0x43d1d90) at p5helper.c:738
#7  0x00007ffff77d1689 in dcCall_x64_sysv () from //home/nine/rakudo/install/lib/libmoar.so
#8  0x0000000000000000 in ?? ()

So it looks like when P5 code is calling back into P6 code, the P6 subs return value goes missing (retval is NULL). Note that callbacks go through good old fashioned dyncall code.

**Comment by zoffixznet** [comment]
I [reverted problematic JIT code](https://github.com/MoarVM/MoarVM/issues/765) and did the bumps. This is now resolved. No extra tests, since existing tests already cover this Issue.
