### ISSUE TITLE
t/spec/MISC/bug-coverage-stress.t is failing

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1312]
`t/spec/MISC/bug-coverage-stress.t` is part of the stresstest so maybe that's why it was unnoticed for a while. It should pass.

**Comment by zoffixznet** [comment]
Detailed output:

```
cpan@perlbuild4~/CPANPRC/rakudo (master)$ ./perl6 t/spec/MISC/bug-coverage-stress.t
1..5
    1..2
    ok 1 - program did not hang
    ok 2 - STDOUT
ok 1 - no deadlock while acquiring mutex
ok 2 - Supply.merge on signals does not crash
ok 3 - dir() does not produce wrong results under concurrent load
ok 4 - no issues when piping one Proc's STDOUT to another's STDIN
not ok 5 - supply inside sock does not hang
# Failed test 'supply inside sock does not hang'
# at /home/cpan/CPANPRC/rakudo/t/spec/packages/Test/Util.pm (Test::Util) line 111
#      got out: ""
# expected out: "pass"
# Looks like you failed 1 test of 5
cpan@perlbuild4~/CPANPRC/rakudo (master)$ 
```

Looks like the test we added ~1 month ago to test for a hang still doesn't hang, but doesn't run the stuff it's (probably) meant to run either.

**Comment by AlexDaniel** [comment]
> \<AlexDaniel\> bisect: old=2017.11 https://gist.githubusercontent.com/AlexDaniel/f32b24d06fbad86d5261db4094c80058/raw/bbe41510cf7620a0ea4371e31eb4fedf79c89a69/GH%25231312.p6
> \<bisectable6\> AlexDaniel, Successfully fetched the code from the provided URL.
> \<bisectable6\> AlexDaniel, Bisecting by exit code (old=2017.11 new=1fb5189). Old exit code: 0
> \<bisectable6\> AlexDaniel, bisect log: https://gist.github.com/6180dcb75e204be85b019cc64a23c8fb
> \<bisectable6\> AlexDaniel, (2017-11-25) https://github.com/rakudo/rakudo/commit/aa3c2c5b04224ec1cef9d27680de9251a5d32542

**Comment by zoffixznet** [comment]
Fixed in https://github.com/perl6/roast/commit/92cbeac33885c6e66447733caac6a4aeedb92dd0
