### ISSUE TITLE
Bad error when mistakenly using `substr` as `subst`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1314]
If you [typo `subst`](https://irclog.perlgeek.de/perl6-dev/2017-12-16#i_15586743) with regex matcher as `substr`, you get nonsensical error:

```
<Zoffix2> m: 'x'.substr: /x/, 'x'
<camelia> rakudo-moar 04eb1da6a: OUTPUT: «No such method '!cursor_start' for invocant of type 'Int'␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by AlexDaniel** [comment]
I've done that before. 👍

**Comment by lizmat** [comment]
At least temporarily fixed with 1da698ab04ea0325736 , tests needed.

**Comment by dwarring** [comment]
`subst` vs `substr` gets me everytime as well. How about just renaming the `subst` method to `replace`, or some such?

**Comment by lizmat** [comment]
Perhaps something to decide about for 6.d?

**Comment by AlexDaniel** [comment]
I agree. It has always surprised me how two things were named so similarly. `replace` is also perhaps more readable than `subst`.

**Comment by AlexDaniel** [comment]
So this is now closed but feel free to discuss more on https://github.com/perl6/6.d-prep/issues/3.
