### ISSUE TITLE
Postfix→Prefix optimization is too early

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1315]
See this: https://irclog.perlgeek.de/perl6-dev/2017-12-16#i_15587096

Rakudo commit: https://github.com/rakudo/rakudo/commit/d98ccea278d1adb23c51139f5572bce840ac6657

Hard to tell if this will affect anybody, but we probably want to either fix it or pull it out before the release.

**Comment by lizmat** [comment]
> On 16 Dec 2017, at 12:38, Aleks-Daniel Jakimenko-Aleksejev <notifications@github.com> wrote:
> 
> See this: https://irclog.perlgeek.de/perl6-dev/2017-12-16#i_15587096
> 
> d98ccea
> 
> Hard to tell if this will affect anybody, but we probably want to either fix or pull it out before the release.

Fix before the release seems unlikely

**Comment by AlexDaniel** [comment]
OK, reverted, no longer a blocker. Then we just need tests for the issue.

**Comment by AlexDaniel** [comment]
https://irclog.perlgeek.de/perl6-dev/2017-12-16#i_15587927
