### ISSUE TITLE
Failure in Inline::Perl5 tests

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1318]
Basically, ``zef install Inline::Perl5`` is failing with this:
```
# Failed test at t/eval_p6_in_p5.t line 9
# expected: '2'
#      got: (Any)
# Looks like you failed 1 test of 1
Use of uninitialized value in string eq at t/lib/TestPerl5Package.pm line 19.
# Failed test at t/perl5package.t line 14
Use of uninitialized value in string eq at t/lib/TestPerl5Package.pm line 19.
# Failed test at t/perl5package.t line 22
# Looks like you failed 2 tests of 8
```

IRC discussion: https://irclog.perlgeek.de/perl6-dev/2017-12-17#i_15590151

**Comment by niner** [comment]
Bisected it to MoarVM commit ba1fb954222810a87f0f5501290877fdcba6aa05
Author: Timo Paulssen <timonator@perpetuum-immobile.de>
Date:   Fri Dec 1 01:58:00 2017 +0100

    jit a few exception related ops
    
    those showed up causing bails in a simple given/when
    benchmark. After the noinline for lastexpayload was
    lifted, more functions got inlined causing the jit
    to not compile the inlining functions.

**Comment by AlexDaniel** [comment]
OK, false alarm. This seems to be the same issue as https://github.com/rakudo/rakudo/issues/1308.

See https://irclog.perlgeek.de/perl6-dev/2017-12-17#i_15590596

Further discussion here: https://github.com/MoarVM/MoarVM/issues/765
