### ISSUE TITLE
Add some `make blah` command to install Inline::Perl5

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1337]
`Inline::Perl5` is required by some spectests. On any fresh rakudo checkout, I go to [the release guide](https://github.com/rakudo/rakudo/blob/nom/docs/release_guide.pod) and copy-paste this chunk of bash commands to install Inline::Perl5

Would be sweet if there was some `make blah blah` command that installed that module. There's likely a zef-free way to install it, but OTOH, having zef isn't too bad a thing when trying to debug some bug that requires module installation.... Or perhaps there could be a `make mod-install Some::Module` command? Or something?

```
git clone https://github.com/ugexe/zef
export PATH=`pwd`/install/bin:$PATH
cd zef; perl6 -Ilib bin/zef install .
cd ..
export PATH=`pwd`/install/share/perl6/site/bin:$PATH
zef install Inline::Perl5
```

**Comment by zoffixznet** [comment]
I actually made [Z-Script](https://github.com/zoffixznet/rdev) that does All The Things™ for building our stack, including installation of `Inline::Perl5`, which is does automatically during init stage.

So… I no longer need this feature and haven't seen any interest for it from anyone else.

**Comment by niner** [comment]
Anyway  you don't actually need zef to install Inline::Perl5. This would do just as well:

git clone https://github.com/niner/Inline-Perl5.git
cd Inline-Perl5
perl6 configure.pl6
make install
