### ISSUE TITLE
Optimizer crash during precompilation: [...] symbol Method::NotFound

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1342]
There's probably ~~a bug in my module~~ *(something's wrong with `!new` method and how it's used)*, but the error at the very least doesn't tell where the problem is:

```bash
$ perl6 -v
This is Rakudo version 2017.12-11-g2a8287c built on MoarVM version 2017.12-1-g912f967
implementing Perl 6.c.

$ ONLINE_TESTING=1 perl6 t/00-basics.t                                                                                                                                             
===SORRY!===
Could not locate compile-time value for symbol Method::NotFound
```

Steps to repro:
```bash
cd $(mktemp -d) &&
git clone https://github.com/zoffixznet/perl6-WWW-P6lert . &&
git checkout e7a917013b1f89ff6a268c41731896311b74dd6c
ONLINE_TESTING=1 perl6 --ll-exception t/00-basics.t
```

Running with `--optimize=off` avoids the issue and precompiles the module. After that you need to `rm -fr lib/.precomp` to get it to trigger again.

**Comment by lizmat** [comment]
Could you try moving the my class X::Method::NotFound { … } stub from Mu.pm to core_prologue and see if that helps?

**Comment by zoffixznet** [comment]
Golfed it down to this; cause is presence of `role X`:

```
$ perl6 -e 'class Foo { role X {}; method z { Foo!z } }'
 ===SORRY!=== Could not locate compile-time value for symbol Method::NotFound
```

So looks like it's a dupe of [RT#130200](https://rt.perl.org/Ticket/Display.html?id=130200). Added this case to that ticket and closing this one.
