### ISSUE TITLE
Should `@foo := Seq:D` do PositionalBindFailover thing?

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1345]
You can bind to a `@-`sigiled parameter and trigger PositionalBindFailover behaviour, yet this is not present when binding to a `@-`sigiled variable.

Is this by design or is this simply an omission/NYI?

```
$ perl6 -e 'sub (@a) { dd @a }((1, 2).Seq);'
(1, 2)

$ perl6 -e 'my @a := (1, 2).Seq;'
Type check failed in binding; expected Positional but got Seq ($((1, 2).Seq))
  in block <unit> at -e line 1

$ perl6 -v
This is Rakudo version 2017.12-55-gb13a073 built on MoarVM version 2017.12-9-g05b4c79
implementing Perl 6.c.
```

**Comment by jnthn** [comment]
No, it's deliberate. Signature binding and simple binding (with `:=`) are different things. Arguably, `::=` could be more magical, but you can get the other behavior with `my (@a) := (1, 2).Seq`, which forces a signature bind to happen, so I think that's perhaps sufficient. Keeping `:=` something low-level and primitive is useful...*something* has to be. :-)

**Comment by zoffixznet** [comment]
Thanks!
