### ISSUE TITLE
Feature request: U+23E8 DECIMAL EXPONENT SYMBOL for scientific notation

### ISSUE THREAD

**Issue by clsn** [rakudo/rakudo#1347]
## The Problem
Just a small deficiency in awesome.

## Expected Behavior

It's such a great character, it's a shame more places don't use it.  It's right there in its name!

```
> 6.02⏨23
6.02e+23
>2.35⏨5
235000
```

It's so clear, placing the `10` in subscript position so the exponent looks like an _exponent_.  Even cooler would be to make that the normal output for floats, but that would probably break a lot of things. Might as well use Unicode for all it's worth.

## Actual Behavior

Doesn't do that.

**Comment by AlexDaniel** [comment]
Relevant wiki page: https://github.com/rakudo/rakudo/wiki/save-me-from-texas (you should probably add your proposal there as well).

**Comment by AlexDaniel** [comment]
#### “When an established math/compsci notation exists for a Perl 6 feature (and is represented in Unicode).”

I don't think it's well established. See this:

> Decimal Exponent Symbol is part of the Unicode Standard, e.g. 6.022⏨23. It is included as U+23E8 ⏨ DECIMAL EXPONENT SYMBOL to accommodate usage in the programming languages Algol 60 and Algol 68.

That does not sound like a widespread use to me.

#### “When a Perl 6 operator or syntax is basically ASCII art trying to paint a larger “glyph”, and there's a Unicode character for that exact glyph (not just resembling it, but specifically intended for it).”

No.

#### “When it is too hard to implement it in a module (e.g. it is so deep in the parser that trying to reimplement it in a module is completely unreasonable)”

I'm guessing that this should be implementable.

#### “When a particular sequence is often auto-corrected by software.”

No.


<br>
So my understanding is that it should be added to the wiki page, then we can reject the ticket for now. The best ones from the wiki page will get added eventually. Maybe.

**Comment by clsn** [comment]
Fair enough.  I just didn't know enough about the whole environment to pick the right place to post this.  *I* think it's a great idea (and shouldn't that be enough?  Why do you need to consult actual authorities and standards and all?  Isn't my opinion, on all matters, the most important in the world?), and of course it's a one-character change.  I was going to post a pull-request for it but then I came back and saw these comments.  I'll post it to the wiki page; close the ticket if you like.

**Comment by AlexDaniel** [comment]
I think the suggestion is great, but given the amount of proposals, we have to be selective. And there are other proposals that are probably more important. In any case, 👍 for the idea in general, we haven't seen this one yet :)

We try not to close tickets before they're moved elsewhere (so that things will not slip through the cracks), so the self-checkout lane with the appropriate button is right there once the wiki page is edited ;)

**Comment by clsn** [comment]
Made a PR just in case someone cares eventually, and added the idea to the wiki page.  Thanks!
