### ISSUE TITLE
Skip using a WhateverCode doesn't work

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#1349]
## The Problem

Using Seq.skip with a WhateverCode fails with an error

## Expected Behavior

    say (1..5).map({$_}).skip(*-3); # OUTPUT: «(3,4,5)␤» 

## Actual Behavior

    say (1..5).map({$_}).skip(*-3); # OUTPUT: «No such method 'Int' for invocant of type 'WhateverCode'␤» 

## Steps to Reproduce

See above

## Environment

Camelia on IRC

See discussion: https://irclog.perlgeek.de/perl6-dev/2017-12-29#i_15632951

**Comment by lizmat** [comment]
Will look at this tomorrow.  Slightly more complicated to fix than I initially thought

**Comment by lizmat** [comment]
how time flies: working on it now

**Comment by dogbert17** [comment]
Tests added in https://github.com/perl6/roast/commit/64381b9457
