### ISSUE TITLE
Vague unit-scope error msg for semi-colon at end of a header  [LTA]

### ISSUE THREAD

**Issue by clint-who** [rakudo/rakudo#1364]
## The Problem
Error reporter produces vague message when a semi-colon is erroneously placed at the end of the header in a subroutine definition.

Ex. 

sub seconds( $raw );
{ 
}

Error message:
"A unit-scoped sub definition is not allowed except on a MAIN sub;
Please use the block form."

## Environment
* Operating system: Kubuntu 17.04 64-bit
* Compiler version (`perl6 -v`):  Rakudo Star 2017.10 built on MoarVM 2017.10 implementing Perl 6.c

**Comment by zoffixznet** [comment]
Thanks! Now reads:
```
$ ./perl6 -e 'sub foo;'
===SORRY!=== Error while compiling -e
A unit-scoped sub definition is not allowed except on a MAIN sub;
Please use the block form. If you did not mean to declare a unit-scoped sub,
perhaps you accidentally placed a semicolon right after routine's definition?
at -e:1
------> sub foo;⏏<EOL>
```

**Comment by COMBORICO** [comment]
You're welcome, zoffix.  geekosaur got me to do it.  Ha.  One criticism -- I'd say "placed a semicolon after routine's header."  When you say "right after routine's definition", I think to look at the bottom of the body of the definition.  2 Cents.

**Comment by zoffixznet** [comment]
Since I've not seen "routine's header" in use as a term, I simply [removed](https://github.com/rakudo/rakudo/commit/5571d7f72ba0046a68df8f0f260d857bc50425f1) the `"right"` in `"right after"`. The piece of code the error shows along with the message should be sufficient to figure out the rest.
