### ISSUE TITLE
"42 < $a < 666" should be faster than "42 < $a && $a < 666", but is 2x as slow

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1368]
## The Problem
"42 < $a < 666" should be faster than "42 < $a && $a < 666", but is 2x as slow

## Expected Behavior

42 < $a < 666 should be faster

## Actual Behavior

42 < $a < 666 is twice as slow

## Steps to Reproduce

<lizmat>	m: my $a = 42; for ^1000000 { my $b = 42 < $a < 666 }; say now - INIT now
<+camelia>	rakudo-moar 7a4743be3: OUTPUT: «0.54265194␤»
<lizmat>	m: my $a = 42; for ^1000000 { my $b = 42 < $a && $a < 666 }; say now - INIT now
<+camelia>	rakudo-moar 7a4743be3: OUTPUT: «0.2490039␤»

## Environment
* Operating system:

Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

* Compiler version (`perl6 -v`): 

This is Rakudo version 2017.12-111-g8023d21 built on MoarVM version 2017.12-20-g5710340
implementing Perl 6.c.

**Comment by zoffixznet** [comment]
This is now fixed by https://github.com/rakudo/rakudo/commit/b77d87566f306ab48b15d8f83f76fb5ff0d82cd2

For OP code, the perf is now about the same:
```
$ ./perl6 -e 'my $a = 42; for ^1000000 { my $b = 42 < $a && $a < 666 }; say now - INIT now'
0.2635152
$ ./perl6 -e 'my $a = 42; for ^1000000 { my $b = 42 < $a < 666 }; say now - INIT now'                                                                                                                           
0.2624662
```

And with longer chains, the chained version has noticeable perf benefits:
```
$ ./perl6 -e 'my $a = 42; for ^10_000_000 { my $b = 42 < $a < 666 <= $a <= 666 }; say now - INIT now'                                                                                                           
2.4954557
$ ./perl6 -e 'my ./perl6 -e 'my $a = 42; for ^10_000_000 { my $b = 42 < $a && $a < 666 <= $a && $a <= 666 }; say now - INIT now'
2.58209932
```

I guess I'm gonna close this without a test, since we didn't yet have a solid per testing framework...
