### ISSUE TITLE
SEGV with QAST tree in core Actions

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1374]
While doing coercer stuff, spotted a SEGV:

```
$ ./perl6 -e 'class Foo {}; -> Foo() $x { $x.say }("42")'
Segmentation fault
```

Not sure what causes it exactly, but the only changes I made are all this commit: https://github.com/rakudo/rakudo/commit/8d34c4dfaa4ab6c312c7267f7658db4d4e821a50 in `segv-coercer-qast` branch.

Figure I report it since AFAIU any SEGV without NativeCall are bad.

**Comment by dogbert17** [comment]
Now it looks like this:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.10-57-gbfe2ad6 built on MoarVM version 2018.10-26-g318e1ec
    implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -e 'class Foo {}; -> Foo() $x { $x.say }("42")'
    No such method 'Foo' for invocant of type 'Str'
      in block <unit> at -e line 1

**Comment by zoffixznet** [comment]
> Now it looks like this:

That's correct behaviour. It's meant to error out like that.
