### ISSUE TITLE
Any.skip fails when trying to use a WhateverCode

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#1384]
Using camelia we get:

    m: say Any.skip(*-1)
    rakudo-moar 7230b7651: OUTPUT: «Cannot resolve caller tail(Any: Int); none of these signatures match:␤    (Any:D $: *%_)␤    (Any:D $: $n, *%_)␤  in block <unit> at <tmp> line 1

According to the docs this should supposedly work, see
https://docs.perl6.org/routine/skip#(Any)_method_skip

**Comment by zoffixznet** [comment]
Fixed in https://github.com/rakudo/rakudo/commit/44ff0a2a4c
