### ISSUE TITLE
/@foo/ is 163x slower than `.grep: contains` and 83x slower than `.contains: any @foo`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1385]
There are two issues:

1. `/@foo/` is ridiculously slow by comparison. Are the extra things it's doing that expensive, or can   
        we make it faster?
2. I would've expected the `Junction` version to be the same or even faster speed, especially   
        considering the 'APPLE' is the first to match and I'm fairly sure the `any` junction has a
       short-circuit in current implementation. Yet, it's twice slower below and with more iterations it
       comes out 3.6x slower. So perhaps that can be improved?

```
$ perl6 -e 'my @words = <APPLE BANANA WATERMELON>; for ^1_000 { my $ = @words.grep: {"this is the name of something APPLE".contains: $_} }; say now - INIT now'
0.04159666

$ perl6 -e 'my $words := any <APPLE BANANA WATERMELON>; for ^1_000 { my $ = "this is the name of something APPLE".contains: $words }; say now - INIT now'
0.0884047

$ perl6 -e 'my @words = <APPLE BANANA WATERMELON>; for ^1_000 { my $ = "this is the name of something APPLE" ~~ /@words/ }; say now - INIT now'
6.5918595

$ perl6 -v
This is Rakudo version 2017.12 built on MoarVM version 2017.12
implementing Perl 6.c.
```

**Comment by MasterDuke17** [comment]
https://rt.perl.org/Public/Bug/Display.html?id=127064 is related. I made `/@foo/` a little bit faster, but definitely more could be done. This is the sub that's doing all the work https://github.com/rakudo/rakudo/blob/master/src/core/Match.pm#L213-L394.

**Comment by zoffixznet** [comment]
Related: spelling out each item for `.contains`/`.starts-with` is a lot faster than using a Junction, because the Junction variant goes through Cool candidate that does the slurpy capture.

```
<Zoffix_> m: my $o = 'foos'; { for ^10000 { $o.starts-with: any <http:// https:// irc://>; Nil }; say now - ENTER now }
<camelia> rakudo-moar 916b41a21: OUTPUT: «0.3800602␤»
<Zoffix_> m: my $o = 'foos'; { for ^10000 { $o.starts-with('http://') or $o.starts-with('https://') or $o.starts-with('irc://'); Nil }; say now - ENTER now }
<camelia> rakudo-moar 916b41a21: OUTPUT: «0.0142966␤»
```

**Comment by lizmat** [comment]
Closing this as it was pre-newdisp.
