### ISSUE TITLE
[RFC] Remove `RAKUDO_MONKEY_BUSINESS` env var

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1386]
Spotted that we [poke into env hash, looking for RAKUDO_MONKEY_BUSINESS env var](https://github.com/rakudo/rakudo/blob/b6004362bf824b4d56bce8d2d6ea9508641c4641/src/Perl6/Actions.nqp#L634) when we try to figure out if monkey eval is enabled.

Briefly looking through the code, looks like this gets called every time we compile anything that cares about eval monkey.

Is this env var really needed? It's not documented and we already have two different ways to enable the eval monkey (including exporting the monkey from a module). 

However few, not looking at the env hash for that var will save on instructions called.

**Comment by lizmat** [comment]
FWIW, I have no recollection of the env var

**Comment by niner** [comment]
IIRC TimToady++ introduced it as a kind of "enable all monkey business" switch

**Comment by AlexDaniel** [comment]
Wasn't it just `use MONKEY` to enable all of the monkeyness?

**Comment by moritz** [comment]
For the record, none of the modules in the ecosystem use or even reference this env var. I'm fine with removing it.

**Comment by jnthn** [comment]
I thought we had a general design policy that all declarations that affect the language must appear in source files, not as environment variables. This breaks that policy, so I'd be happy to see it go.
