### ISSUE TITLE
Increment/Decrement on RatStr dies

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1387]
## The Problem

> my $a = <2.2>; dd $a; $a++; dd $a

## Expected Behavior

RatStr $a = RatStr.new(2.2, "2.2")
Rat $a = 3.2

## Actual Behavior

RatStr $a = RatStr.new(2.2, "2.2")
Type check failed in binding to parameter '$r'; expected Rat but got Int (16)

## Environment
This is Rakudo version 2017.12-169-gb600436 built on MoarVM version 2017.12.1-25-g1e2a3fb
implementing Perl 6.c.

**Comment by zoffixznet** [comment]
All allomorphs are affected. The non-RatStr lose their allomorphiness.

Looks like methods `succ` and `pred` need to be added to the allomorphs.

```
<Zoffix_> m: my $x = <2e0>; dd $x; $x++; dd $x
<camelia> rakudo-moar b6004362b: OUTPUT: «NumStr $x = NumStr.new(2e0, "2e0")␤Num $x = 3e0␤»
<Zoffix_> m: my $x = <2e0>; dd $x; --$x; dd $x
<camelia> rakudo-moar b6004362b: OUTPUT: «NumStr $x = NumStr.new(2e0, "2e0")␤Num $x = 1e0␤»
<Zoffix_> m: my $x = <2>; dd $x; --$x; dd $x
<camelia> rakudo-moar b6004362b: OUTPUT: «IntStr $x = IntStr.new(2, "2")␤Int $x = 1␤»
<Zoffix_> m: my $x = <2>; dd $x; $x++; dd $x
<camelia> rakudo-moar b6004362b: OUTPUT: «IntStr $x = IntStr.new(2, "2")␤Int $x = 3␤»
<Zoffix_> m: my $x = <2+1i >; dd $x; $x++; dd $x
<camelia> rakudo-moar b6004362b: OUTPUT: «ComplexStr $x = ComplexStr.new(<2+1i>, "2+1i")␤Complex $x = <3+1i>␤»
```

**Comment by lizmat** [comment]
For what it’s worth, I’m ok that changing an allomorph numerically breaks the allomorphism.

**Comment by zoffixznet** [comment]
Good point. Since our other math de-allomorphs too:

```
<Zoffix_> m: dd <2> + 1
<camelia> rakudo-moar b6004362b: OUTPUT: «3␤»
```

**Comment by lizmat** [comment]
But But But.  The problem isn't fixed  :-)

$ 6 'my $a = <2.2>; dd $a; $a++; dd $a'
RatStr $a = RatStr.new(2.2, "2.2")
Type check failed in binding to parameter '$r'; expected Rat but got Int (16)
  in block <unit> at -e line 1

**Comment by zoffixznet** [comment]
Perhaps you forgot to pull latest rakudo changes?

Seems to work on camelia and `$++` is [covered by the tests](https://github.com/perl6/roast/blob/master/S02-literals/allomorphic.t#L349-L355)

```
<Zoffix_> m: my $a = <2.2>; dd $a; $a++; dd $a
<camelia> rakudo-moar 31b3b7731: OUTPUT: «RatStr $a = RatStr.new(2.2, "2.2")␤Rat $a = 3.2␤»
```

**Comment by lizmat** [comment]
Argh, I was pulling in the wrong repo.  Saw "Already up to date", tried the code, and it failed.  Duh.

Sorry for the noise.  Thanks for taking care of it!
