### ISSUE TITLE
`enum Foo <x y z> does Bar` doesn't DWIM

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#1388]
## The Problem

Mixing in a role using `enum Foo <x y z> does Bar` doesn't work:

    > role Bar { method bar { say "bar: ", self } }; enum Foo <x y z> does Bar; my Foo $f = y; $f.bar;
    No such method 'bar' for invocant of type 'Foo'
      in block <unit> at <unknown file> line 1

The correct syntax, `enum Foo does Bar <x y z>` does work correctly:

    > role Bar { method bar { say "bar: ", self } }; enum Foo does Bar <x y z>; my Foo $f = y; $f.bar;
    bar: y

See also: https://irclog.perlgeek.de/perl6/2018-01-11#i_15679004

## Expected Behavior

It would be nice if this syntax would work and DWIM.  Alternatively, a syntax error during compilation would be better than the current behavior.

## Actual Behavior

It doesn't mixin the rol, and gives a runtime error when calling a method from the role.

## Steps to Reproduce

    > role Bar { method bar { say "bar: ", self } }; enum Foo <x y z> does Bar; my Foo $f = y; $f.bar;
    No such method 'bar' for invocant of type 'Foo'
      in block <unit> at <unknown file> line 1

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): 
This is Rakudo Star version 2017.10 built on MoarVM version 2017.10
implementing Perl 6.c.

**Comment by lizmat** [comment]
Feels to me this is unfixable, as the syntax **Is** valid:
```raku
 % raku -e 'dd enum Foo <x y z>'         
Map.new((:x(0),:y(1),:z(2)))
```
So, an `enum` has a value.  And if you postfix that with `does Bar`, you will be mixing in the `Bar` role on that return value.
```raku
% raku -e 'role Bar { }; dd enum Foo <x y z> does Bar'
Map+{Bar}.new((:x(0),:y(1),:z(2)))
```
That doesn't make much sense in this case, but there could be other cases where it could.

So closing this issuem
