### ISSUE TITLE
List.sink does not sink

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1393]
Currently, `List.sink` is a no-op. A [2015 commit](https://github.com/rakudo/rakudo/commit/6c97f3c12beb58c7ebffbf8f56bf48ee6305c833) claims making it do things throws setting parse into infiniloop.

```
<Zoffix_> m: gather { say "meow" }
<camelia> rakudo-moar 60566cfc4: OUTPUT: «meow␤»
<Zoffix_> m: gather { say "meow" }.sink
<camelia> rakudo-moar 60566cfc4: OUTPUT: «meow␤»
<Zoffix_> m: gather { say "meow" }.List
<camelia> rakudo-moar 60566cfc4: ( no output )
<Zoffix_> m: gather { say "meow" }.List.sink
<camelia> rakudo-moar 60566cfc4: ( no output )
<Zoffix_> m: sink gather { say "meow" }.List
<camelia> rakudo-moar 60566cfc4: ( no output )
```

**Comment by jnthn** [comment]
I think `sink` on a `List` is correctly a no-op; a `List` is a data structure that holds the elements. Consider something like:

```
sub foo() {
    my @foo := gather { loop { say "meow" } }.list;
    say @foo[^5];
    @foo
}
foo();
```

Where the `List` ends up as the return value. We'd then end up sinking it, resulting in a hang. There's surely a load of code out there with lists ending up as implicit return values and being sunk (especially given `Array` is a subclass of `List`, so if we change the behavior of `List` then we'd be changing it for `Array` too).
