### ISSUE TITLE
Malformed UTF-8 when IO::Socket::INET.new(:host('gtk-dlls.p6c.org'), :port(80)) on Windows

### ISSUE THREAD

**Issue by wukgdu** [rakudo/rakudo#1394]
## The Problem
    IO::Socket::INET.new(:host('gtk-dlls.p6c.org'), :port(80)) caused Malformed UTF-8 on Windows 10.
## Expected Behavior
Fedora 27
<pre>&gt; IO::Socket::INET.new(:host(&apos;gtk-dlls.p6c.org&apos;), :port(80));
IO::Socket::INET.new(host =&gt; &quot;gtk-dlls.p6c.org&quot;, port =&gt; 80, localhost =&gt; Str, localport =&gt; Int, backlog =&gt; Int, listening =&gt; Bool, family =&gt; 2, proto =&gt; 6, type =&gt; 1, encoding =&gt; &quot;utf8&quot;, nl-in =&gt; $[&quot;\n&quot;, &quot;\r\n&quot;], nl-out =&gt; &quot;\n&quot;)
</pre>
## Actual Behavior
Windows 10
<pre>&gt; IO::Socket::INET.new(:host('gtk-dlls.p6c.org'), :port(80));
Malformed UTF-8 at line 1 col 27 in block &lt;unit&gt; at &lt;unknown file&gt; line 1
</pre>

## Environment
* Compiler version (`perl6 -v`): 
This is Rakudo version 2017.12-176-g992b80557 built on MoarVM version 2017.12.1-30-ged7c1234f
implementing Perl 6.c.
(same for Fedora 27 and Windows 10)

**Comment by zoffixznet** [comment]
Does the same problem happen if you save the code into a file instead of running it from the REPL? How did you build your rakudo? What C compiler did you use?

I'm failing to reproduce this on Windows 10 on 2017.12-196-g99da4a5:

```
C:\rakudo>perl6 -e "say IO::Socket::INET.new(:host('gtk-dlls.p6c.org'), :port(80));"
IO::Socket::INET.new(host => "gtk-dlls.p6c.org", port => 80, localhost => Str, localport => Int, backlog => Int, listening => Bool, family => 2, proto => 6, type => 1, encoding => "utf8", nl-in => $["\n", "\r\n"], nl-out => "\n")

C:\rakudo>perl6

To exit type 'exit' or '^D'
> IO::Socket::INET.new(:host('gtk-dlls.p6c.org'), :port(80));
IO::Socket::INET.new(host => "gtk-dlls.p6c.org", port => 80, localhost => Str, localport => Int, backlog => Int, listening => Bool, family => 2, proto => 6, type => 1, encoding => "utf8", nl-in => $["\n", "\r\n"], nl-out => "\n")

C:\rakudo>perl6 -v
This is Rakudo version 2017.12-196-g99da4a5 built on MoarVM version 2017.12.1-30-ged7c123
implementing Perl 6.c.
```

**Comment by wukgdu** [comment]
Still failed in a file.
And gcc is with strawberry-perl-5.26.1.1-64bit.
<pre>
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Strawberry/c/bin/../libexec/gcc/x86_64-w64-mingw32/7.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-7.1.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-mpc=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-isl=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh, Built by strawberryperl.com project' CFLAGS='-O2 -pipe -fno-ident -I/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/lib -L/opt/build/prerequisites/x86_64-zlib-static/lib -L/opt/build/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 7.1.0 (x86_64-posix-seh, Built by strawberryperl.com project)
</pre>

Also failed with rakudo-star-2017.10-x86_64 (JIT) using REPL or file.
<hr>
<h4> I tried another Windows 10 virtual machine, it works. This should be my os's problem. </h4>
