### ISSUE TITLE
.ords.rotor(2=>-1,:partial) doesn't work

### ISSUE THREAD

**Issue by b2gills** [rakudo/rakudo#1397]
## The Problem

    > 'abc'.ords.rotor( 2=>-1, :partial )
    Cannot invoke this object (REPR: Uninstantiable; Callable)

    > dd 'abc'.ords.rotor( 2=>-1, :partial )
    (low-level Seq)

## Expected Behavior

    > 'abc'.ords.List.Seq.rotor( 2=>-1, :partial )
    ((97 98) (98 99) (99))

## Environment
* Operating system: Linux
* Compiler version: 2017.12-204-g1e8c976

**Comment by zoffixznet** [comment]
Test to cover the bug:

```perl-6
subtest '.rotor: 2 => -1, :partial obeys Iterator protocol' => {
    plan 2;

    my $iterends = 0;
    my $s := Seq.new: class :: does Iterator {
        method pull-one {
            return $++ if $++ < 3;
            $iterends++;
            IterationEnd
        }
    }.new;
    is-deeply $s.rotor(2 => -1, :partial), ((0, 1), (1, 2), (2,)).Seq,
        'got right result';
    is $iterends, 1, 'stopped pulling after receiving IterationEnd';
}
```
