### ISSUE TITLE
Sequence operator `...` leaks memory

### ISSUE THREAD

**Issue by smls** [rakudo/rakudo#1399]
The memory usage of the following two non-terminating programs remains reasonably constant:

``` Perl 6
.sink for 1..*;
```

``` Perl 6
.sink for 1 xx *;
```

But the following one continually increases its memory usage by several MB per second:

``` Perl 6
.sink for 1...*;
```

This is even though the `...` operator returns a `Seq`, which should discard already iterated items:

``` Perl 6
say (1...*).^name;  # Seq
```

...so the leak must be *inside* the operator's implementation.

(I think I've seen this reported before (RT? IRC?) but couldn't find it anymore.)

---

*This is Rakudo version 2017.10-4-g4fca94743 built on MoarVM version 2017.10
implementing Perl 6.c.*

**Comment by zoffixznet** [comment]
> (I think I've seen this reported before (RT? IRC?) but couldn't find it anymore.)

Perhaps this one: https://rt.perl.org/Ticket/Display.html?id=131829#ticket-history

**Comment by AlexDaniel** [comment]
If it's the same issue we can close that other RT ticket in favor of this one.

**Comment by dogbert17** [comment]
There's also https://rt.perl.org/Public/Bug/Display.html?id=126189

**Comment by ab5tract** [comment]
This issue remains as of:

```
> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-84-g774cc8641.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```
