### ISSUE TITLE
Consider removing the :caption key from table POD’s %config hash

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#1403]
# The Problem

The original Perl 6 POD design in S26 implies the :caption key for tables is special, and the current Pod::Block::Table class supports that interpretation by having a .caption attribute. Before 2017-12-11 Rakudo Perl 6 did not fill the table POD’s .caption attribute value, so renderers used the :caption key’s value in the table’s %config hash.  Ideally, the currently-redundant :caption key-value pair would be removed, but doing so would be a burden for existing POD renderers using that pair.

# Possible Solution

Deprecate use of the :caption key in the table POD’s %config hash, and remove it in some future Perl 6 version.

**Comment by lizmat** [comment]
Superseded by RakuDoc's handling, so closing
