### ISSUE TITLE
P6opaque: no such attribute '$!storage' on type … in a Hash when trying to bind a value

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1407]
The error happens when using CSS::Grammar module.

Code:
```
use CSS::Grammar::Actions # with https://github.com/p6-css/CSS-Grammar-p6 in your lib
```

Output (2017.12,`eeb3cc726ada^`):
```
(nothing)
```

Output (eeb3cc726ada, HEAD):
```
===SORRY!===
P6opaque: no such attribute '$!storage' on type CSSValue in a Hash when trying to bind a value
```

Seems to be our fault.

Bisectable points at (2018-01-15) https://github.com/rakudo/rakudo/commit/eeb3cc726adac4735c613f7dbbb85075528ac61d

That's all I know at this point, will add more info if I get any.

**Comment by AlexDaniel** [comment]
With ``-ll-exception``: https://gist.github.com/AlexDaniel/da5ec5b8fad3869785abf4659270c786

**Comment by zoffixznet** [comment]
Golfed to `enum CSSValue «:Map<foo>»; my %h = :42foo`

The `.find_symbol` in [the commit](https://github.com/rakudo/rakudo/commit/eeb3cc726adac4735c613f7dbbb85075528ac61d) needs to ensure the symbol it finds is the one from core. In the above code, the Map is an Enum value, not core Map
