### ISSUE TITLE
«$x» should leak a Slip?

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1409]
Code:
```perl6
my $cmd = ‘a’; multi sub getopt(@args) { say 42 }; getopt(« $cmd »)
```
Output (2015.12,`ad684de383bb^`):
```
42
```
Output (ad684de,HEAD):
```
Cannot resolve caller getopt(Str); none of these signatures match:
    (@args)
  in block <unit> at /tmp/t2ngYdxMno line 1
```

Because of that, Getopt::Advance module is currently [failing](https://github.com/araraloren/perl6-getopt-advance/blob/febbb0a2abeefe0c969b931c14c4025bcf5b89d6/t/06-cmd.t#L58).

Bisectable points at (2017-12-30) https://github.com/rakudo/rakudo/commit/ad684de383bb0c0ff051d7b0901583a9b5c2e398.

See https://github.com/rakudo/rakudo/issues/1204 for why the commit was made.

**Comment by zoffixznet** [comment]
+1 on reverting commit that broke it. Predictability that if you use a variable you'll always get a list is good.

**Comment by TimToady** [comment]
Seems like it might be an excellent place to use + for one-arg semantics.

**Comment by lizmat** [comment]
Would that unbreak the code in question?

**Comment by lizmat** [comment]
Or do you mean to use +@args in the “multi sub getopt()” code?

**Comment by jstuder-gh** [comment]
If we do decide that we want the interpolated one-arg ```« $cmd »``` to return a Positional, I think we should still remove the Slip but have it wrapped in a List. The List behaves better in examples like the zip example from IRC linked to in the issue.

However, it does seem odd to me that a literal in « » (e.g, ```« 42 »``` ) wouldn't return a List while the interpolated one-arg would. I would vote to either change the one-arg literal or leave the current behavior as is, FWIW.

**Comment by zoffixznet** [comment]
> we should still remove the Slip

Yeah, compared to old behaviour, the change would be to return a List rather than a Slip in all cases, including `<<$x>>`, which would always return a List, even if it ends up a single arg.

> I would vote to either change the one-arg 

We could try making `<<…>>` always return a List regardless of what inside. Though after release, as I imagine there's some amount of code of people using `$h<<blah>>` for single-key hash access.

> or leave the current behavior as is, 

-1 on that. It'd make result of `<<$x>>` unpredictable.

**Comment by TimToady** [comment]
I think it's okay for double angles to be "unpredictable" here, given that single-angle forms are already unpredictable in the sense of returning either singular or plural.  It might well be that someone writing <<$x>> in the future will be intending to have the double-angles decide singular vs plural for them, or they'll be wanting the double angles as a "shortcut" for val().  I don't think people should be relying on double angles to listify when single angles don't.

**Comment by zoffixznet** [comment]
> single-angle forms are already unpredictable in the sense of returning either singular or plural

They're predictable in as far as I can write `< ... >` and know just by looking at that whether that will give me a singular or plural.

With `«$x»`, I can't. I must examine the value of `$x` to see whether it contains whitespace to know the type of the result.

**Comment by zoffixznet** [comment]
PR sent: https://github.com/araraloren/perl6-getopt-advance/pull/4
