### ISSUE TITLE
supply/react “already vowed” regression

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1410]
This needs to be golfed, submitting the ticket to gather more info.

HTTP::Request::Supply tests are currently broken.

Bisectable points at (2018-01-15) https://github.com/rakudo/rakudo/commit/e5f412d69635d7940e4823c3178f27a1321b0be9

See the output https://gist.github.com/Whateverable/c86822fd96b58bbed92e079e6a0ec808

**Comment by zoffixznet** [comment]
Here's the golf. Looks like a race condition (may need to run the code a few times to trigger the error). 

```perl6
react whenever supply {
        my $b = Supplier::Preserving.new;
        whenever (1, 2, 3).Supply {
            when 1 {
                say "here";
                emit $b.Supply;
            }
            when 2 {
                say "there";
                $b.done;
            }
        }

        whenever (1, 2, 3).Supply {}
    } {
        start react whenever $_ { LAST done }
    }
```

**Comment by jnthn** [comment]
Tests in https://github.com/perl6/roast/commit/ccff418444
