### ISSUE TITLE
--> List:D[Int] is parsed as a coercer

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1411]
Code:
```perl6
my sub word-bytes(Int:D $word --> List:D[Int]) { }
```

Result:
```
¦«2017.12,3947a4c11a8^»:

¦«3947a4c,HEAD(cf15435)»:
===SORRY!=== Error while compiling /tmp/5eg7GB39hZ
Coercer is too complex. Only type objects, with optional type smileys, or empty parentheses, implying 'Any', are supported.
at /tmp/5eg7GB39hZ:1
------> b word-bytes(Int:D $word --> List:D[Int]⏏) { }
«exit code = 1»
```

[Net::IP::Parse](https://github.com/bradclawsie/Net-IP-Parse/blob/ad9b79879a032dbc510ac1b75b09cbc896e54b1d/lib/Net/IP/Parse.pm6#L91) tests are failing because of this.

Bisectable says (2018-01-04) https://github.com/rakudo/rakudo/commit/3947a4c11a807e820f1e43e2ed0793f9a9decbbc

Explanation:
> \<Zoffix\> AlexDaniel: the square brackets were ignored in the past, now it thinks it's a coercer. Both are bugs

In terms of the upcoming release, ignoring square brackets is better because we should not be creating “my module worked yesterday and now it fails to compile” problem. But fixing the issue is of course better.

**Comment by zoffixznet** [comment]
Fixed the crash. 

Opened the parametarization issue as https://github.com/rakudo/rakudo/issues/1412

Also opened a PR on that module, since Lists cannot be parametarized: https://github.com/bradclawsie/Net-IP-Parse/pull/5
