### ISSUE TITLE
Suspicious 3.5x perf loss in a loop when BEGIN/CHECK phasers used in outer scope

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1415]
Don't know much about how this works, but figured I'd file a ticket. I briefly scanned the produced ASTs and don't immediately see anything why the presence of BEGIN/CHECK phasers would slow down the loop so much. `INIT` phaser, by comparison does not seem to have this effect.

```
<Zoffix__> m: BEGIN {}; { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «1.8817401␤»
<Zoffix__> m: CHECK {}; { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «1.8960010␤»

<Zoffix__> m: { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «0.6750541␤»
<Zoffix__> m: {}; { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «0.5859839␤»
<Zoffix__> m: INIT {}; { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «0.640791␤»
```

**Comment by MasterDuke17** [comment]
These now all have roughly the same performance. The numbers have fluctuated kind of wildly (as can be seen here https://gist.github.com/Whateverable/2620b58081dcb413596d64b608d425aa), but the most recent performance improvement seems to have been around https://github.com/rakudo/rakudo/commit/152d3c5b4b6c67f81e39df7feddd57d371a2ae76.
