### ISSUE TITLE
my int $n; nqp::if($n,1) is 4.5x slower than non-native version

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1416]
Noticed this while debugging [RT#132718](https://rt.perl.org/Ticket/Display.html?id=132718#ticket-history):

```
<Zoffix__> m: use nqp; my int $n = 42;  { for ^30_000_000 { my $ = nqp::if($n,1) }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «10.1734608␤»
<Zoffix__> m: use nqp; my $n := 42;  { for ^30_000_000 { my $ = nqp::if($n,1) }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «2.2755669␤»
```

The same is not the case if we use `nqp::isne_i` op first:

```
<Zoffix__> m: use nqp; my int $n = 42;  { for ^30_000_000 { my $ = nqp::if(nqp::isne_i($n,0),1) }; say now - ENTER now }
<camelia> rakudo-moar a1fd0b732: OUTPUT: «2.2284175␤»
```

And we [actually perform this as an optimization](https://github.com/rakudo/rakudo/blob/a1fd0b732252c50f1d00a07ec460ee7e08e917bf/src/Perl6/Optimizer.nqp#L1329) in some cases (but not all)

The question is: why is it so much slower? Couldn't it be made faster by moving the optimization from the static optimizer further down to nqp/MoarVM?

-----

Update: This issue does not seem to affect `nqp::while`, so whatever it's doing should probably be done by `nqp::if`

```
<Zoffix__> m: use nqp; my int $i = 10_000_0000;  nqp::while($i, ($i = nqp::sub_i($i,1))); say now - INIT now
<camelia> rakudo-moar a1fd0b732: OUTPUT: «0.523931␤»
<Zoffix__> m: use nqp; my int $i = 10_000_0000;  nqp::while(nqp::isne_i($i,0), ($i = nqp::sub_i($i,1))); say now - INIT now
<camelia> rakudo-moar a1fd0b732: OUTPUT: «0.529644115␤»
```

----------

Update 2: the slowdown isn't present if you provide the `if` branch:
```
<Zoffix__> m: use nqp; my int $n = 42;  { for ^30_000_000 { my $ = nqp::if($n,1, 1) }; say now - ENTER now }
<camelia> rakudo-moar 14c28cae4: OUTPUT: «2.0954680␤»
```

**Comment by zoffixznet** [comment]
Best I can tell (by dumping the `@ins` [compiled by the op](https://github.com/perl6/nqp/blob/9222147e47eaac9768ab0e836717035f0798a01b/src/vm/moar/QAST/QASTOperationsMAST.nqp#L865)) the slowdown is due to the slow version using `getlexref_i` where in faster variants `getlex` gets used.

No idea whether that's normal and the issue should be just closed.

**Comment by niner** [comment]
From what I've found, getlex can be speshed and JITed to a very cheap instruction (just a couple of memory accesses) while getlexref_i always forces the current frame to the heap and allocates a new MVMNativeRef object.

**Comment by zoffixznet** [comment]
> getlex can be speshed and JITed to a very cheap instruction

FWIW, the large speed difference exists even with spesh disabled (tho it gets smaller).

I'm wondering whether `getlexref_i` can be turned *into* `getlex`? Any info on what these ops are for and what the differences are would be handy.

**Comment by zoffixznet** [comment]
> Any info on what these ops are for

Explained [here](https://irclog.perlgeek.de/moarvm/2018-01-21#i_15717659) and so yes, the obvserved behaviour makes sense, so I'm closing the issue.
