### ISSUE TITLE
Return type constraint check fails with parametrized role

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#1417]
## The Problem

```
role A[::RType] {
    method b(RType $foo --> Str) { "String" }
    method a(--> RType) { RType.new; }
}

class B {};

class C does A[B] {}

say C.b(B.new);
say C.a;
```

## Expected Behavior

Both `b` and `a` methods work.

## Actual Behavior

```
➜  ~ perl6 I_contain_code_above.pl6 
String
Died with X::TypeCheck::Return
  in method a at perl6.pl6 line 3
  in block <unit> at perl6.pl6 line 11
```
So it's ok to use role parameter everywhere, but setting it as a return constraint doesn't work.

## Steps to Reproduce

1)Run gist above.
2)???
3)Done.

As a quick one-liner, this code shows the issue too: ` role A[::Ret] { method a(--> Ret) { Ret.new } }; class B{}; class C does A[B] {}; say C.a;`.

## Environment
* Operating system: `Linux miskatonic 4.14.13_2 #1 SMP PREEMPT Mon Jan 15 01:41:56 UTC 2018 x86_64 GNU/Linux`
* Compiler version (`perl6 -v`): `This is Rakudo version 2017.12 built on MoarVM version 2017.12`

**Comment by TopherCooper** [comment]
See also #2595, a broader version of this problem.  Includes a workaround technique.

**Comment by FCO** [comment]
https://colabti.org/irclogger/irclogger_log/perl6?date=2019-01-14#l305
Em qui, 10 de jan de 2019 às 12:04, TopherCooper <notifications@github.com>
escreveu:

**Comment by FCO** [comment]
Sorry, I just saw the #2595
Em seg, 14 de jan de 2019 às 08:33, Fernando Oliveira <
fernandocorrea@gmail.com> escreveu:

**Comment by usev6** [comment]
This seems to work as expected nowadays:
```
$ ./rakudo-m -e 'role A[::RType] { method b(RType $foo --> Str) { "String" }; method a(--> RType) { RType.new; } }; class B {}; class C does A[B] {}; say C.b(B.new); say C.a'
String
B.new
```

According to ```bisectable6``` it has been fixed with https://github.com/rakudo/rakudo/commit/a302194442 (https://github.com/rakudo/rakudo/pull/5048).

A couple of tests have been added to roast with https://github.com/Raku/roast/commit/eedaf1471a.
I believe that they cover this bug report, so I'm closing this issue as resolved.
