### ISSUE TITLE
Sieve of Eratosthenes 42x slower than Perl 5

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1421]
Spotted this comparison being brought up [on reddit](https://www.reddit.com/r/perl/comments/7r1b33/an_open_letter_to_the_perl_community/dsxfif9/).

Perl 5 takes ~1.4s vs P6 that takes 60s

Perl 5 version:
```perl
use Time::HiRes qw(time);

sub sieve {
  my($n) = @_;
  my @composite;
  for (my $t = 3;  $t*$t <= $n;  $t += 2) {
     if (!$composite[$t]) {
        for (my $s = $t*$t;  $s <= $n;  $s += $t*2)
           { $composite[$s]++ }
     }
  }
  my @primes = (2);
  for (my $t = 3;  $t <= $n;  $t += 2) { 
     $composite[$t] || push @primes, $t;
  }
  \@primes;
}

my $N = 5000000;
my $start = time;
my $primes = sieve($N);
my $end = time;

print $primes->[-1], "\n";
printf "%.2fs\n", $end - $start;
```

Perl 6 version:
```perl-6
use v6;

sub sieve($n) {
  my @composite;
  my $t;
  loop ($t = 3;  $t*$t <= $n;  $t += 2) {
     if (!@composite[$t]) {
        loop (my $s = $t*$t;  $s <= $n;  $s += $t*2)
           { @composite[$s]++ }
     }
  }
  my @primes = (2);
  loop ($t = 3;  $t <= $n;  $t = $t + 2) { 
     @composite[$t] || push @primes, $t;
  }
  @primes;
}

my $N = 5000000;
my $start = time;
my @primes = sieve($N);
my $end = time;

print @primes[*-1], "\n";
printf "%.2fs\n", $end - $start;
```

**Comment by zoffixznet** [comment]
For comparison, here's a bare-bones NQP version that runs in 0.49s:

```perl-6
use nqp;

sub sieve(int $n) {
  my $c := nqp::list_i;
  my int $t = 1;
  nqp::while(
    nqp::stmts(
      ($t = nqp::add_i($t, 2)),
      nqp::isle_i(nqp::mul_i($t, $t), $n)),
    nqp::if(
      nqp::isfalse(nqp::atpos_i($c, $t)),
      nqp::stmts(
        (my int $s = nqp::sub_i(nqp::mul_i($t, $t),nqp::mul_i($t,2))),
        nqp::while(
          nqp::stmts(
            ($s = nqp::add_i($s, nqp::mul_i($t,2))),
            nqp::isle_i($s, $n)),
          nqp::bindpos_i($c, $s, nqp::add_i(1, nqp::atpos_i($c, $s)))))));
  my $p := nqp::list_i(2);
  ($t = 3);
  nqp::while(
    nqp::stmts(
      ($t = nqp::add_i($t, 2)),
      nqp::isle_i($t, $n)),
    nqp::atpos_i($c,$t) || nqp::push_i($p, $t));
  $p;
}

my int $N = 5000000;
my $primes := sieve($N);

print nqp::atpos_i($primes, nqp::elems($primes)-1), "\n";
printf "%.2fs\n", now - INIT now;
```

**Comment by cygx** [comment]
>  Also, merely typing arrays and variables with int chops down the run time to 19s

That's correct. However, it does not if you use `uint` instead. You will also see improvements if you declare `@composite` as

    my @composite := buf8.allocate($n);

whereas

    my int8 @composite[$n];

kills any performance gain...

**Comment by timo** [comment]
yes, native-shaped-array performance is really weak at the moment.

**Comment by lizmat** [comment]
FWIW, my version:

    sub sieve($n) {
        my buf8 $composite := buf8.allocate($n);
        my int $t = 3;
        while (my $q := $t * $t) <= $n {
            unless $composite[$t] {
                my int $t2 = $t + $t;
                my int $s  = $q - $t2;
                $composite[$s] = 1 while ($s = $s + $t2) <= $n;
            }
            $t = $t + 2;
        }
        my int @result = 2;
        $t = 1;
        @result.push($t) unless $composite[$t] while ($t = $t + 2) <= $n;
        @result
    }

The original version ran for 29.6 seconds, this version runs for 2.3 seconds for me.

**Comment by lizmat** [comment]
> On 20 Jan 2018, at 17:35, Elizabeth Mattijsen <liz@dijkmat.nl> wrote:
> 
> FWIW, my version:
> 
>    sub sieve($n) {
>        my buf8 $composite := buf8.allocate($n);
>        my int $t = 3;
>        while (my $q := $t * $t) <= $n {
>            unless $composite[$t] {
>                my int $t2 = $t + $t;
>                my int $s  = $q - $t2;
>                $composite[$s] = 1 while ($s = $s + $t2) <= $n;
>            }
>            $t = $t + 2;
>        }
>        my int @result = 2;
>        $t = 1;
>        @result.push($t) unless $composite[$t] while ($t = $t + 2) <= $n;
>        @result
>    }
> 
> The original version ran for 29.6 seconds, this version runs for 2.3 seconds for me.

Of note, postcircumfix:<[ ]> take 45% of CPU in this version and do *not* get OSR’d, according to —profile, at least.

**Comment by lizmat** [comment]
on HEAD, this version now runs at 4.8 seconds for me.  I'm not sure how I can explain that discrepancy.

**Comment by ab5tract** [comment]
We seem to have made some decent gains here:

```
> set-base; ./rakudo-m issues/r1421.raku
4999999
6.00s

> perl issues/r1421.pl
4999999
0.59s

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-84-g774cc8641.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```

Just one more order of magnitude to go! This is on an M2 Pro (arm64, so no JIT currently).

RakuAST is currently lagging, but the optimization story there is promising:

```
> set-rakuast; ./rakudo-m issues/r1421.raku
4999999
10.00s
```

**Comment by MasterDuke17** [comment]
A very rough overview of the timing over time https://gist.github.com/Whateverable/7b710bfdd4ec04296c9af6541a708ee9 (notice this is with a value 10x smaller). Here https://gist.github.com/Whateverable/4be57500c7f78aa78e08367cba9b9421 you can see the impact of the new-disp merge for the 2021.10 release.

**Comment by tbrowder** [comment]
I'm getting 2.00s

**Comment by lizmat** [comment]
2.00 is because `time` only has second granularity. With this version of sieve:
```raku
use v6.*;

sub sieve(int $n) {
    my buf8 $composite := buf8.allocate($n);
    my int $t = 3;
    while (my $q := $t * $t) <= $n {
        unless $composite[$t] {
            my int $t2 = $t + $t;
            my int $s  = $q - $t2;
            $composite[$s] = 1 while ($s = $s + $t2) <= $n;
        }
        $t = $t + 2;
    }
    my int @result = 2;
    $t = 1;
    @result.push($t) unless $composite[$t] while ($t = $t + 2) <= $n;
    @result
}

my $N = 5000000;
my $start = nano;
my $primes = sieve($N);
my $end = nano;

print $primes[*-1], "\n";
printf "%.2fs\n", ($end - $start) / 1000000000;
```
I get 0.80 on my Intel, and 0.87 with Perl 5.28.0 on that box

On a M1, I get 1.24s (Raku) vs 0.64s (Perl 5.30.3)

**Comment by lizmat** [comment]
Not sure why I originally used a `buf8` where an `int` array would make more sense.  This version clocks in at **.50** on Intel, and **0.95** on an M1:
```raku
use v6.*;

sub sieve(int $n) {
    my int @composite;
    @composite[$n - 1] = 0;

    my int $t = 3;
    while (my $q := $t * $t) <= $n {
        unless @composite[$t] {
            my int $t2 = $t + $t;
            my int $s  = $q - $t2;
            @composite[$s] = 1 while ($s = $s + $t2) <= $n;
        }
        $t = $t + 2;
    }
    my int @result = 2;
    $t = 1;
    @result.push($t) unless @composite[$t] while ($t = $t + 2) <= $n;
    @result
}

my $N = 5000000;
my $start = nano;
my $primes = sieve($N);
my $end = nano;

print $primes[*-1], "\n";
printf "%.2fs\n", ($end - $start) / 1000000000;
```
FWIW, an NQP version does not appear to go much faster.

**Comment by librasteve** [comment]
raku: 1.03s
perl: 0.66s

on M1

**Comment by pmichaud** [comment]
> raku: 1.03s
> perl: 0.66s

Wow.  As far as I'm concerned, this is an _amazing_ result.

Pm
