### ISSUE TITLE
“1” is whitespace according to uniprop

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1430]
Code:
```perl6
my $s = "1"; dd uniprop($s,"White_Space")
```

Result (…,2017.08,``64dd94c250c7^``):
```
Bool::False
```

Result (``64dd94c250c7``,2017.09,…):
```
Bool::True
```

This is an old regression so not a blocker.

**Comment by AlexDaniel** [comment]
That was fixed in this commit: https://github.com/MoarVM/MoarVM/commit/4e51615425c1ffa7d034b50a0aad6696378f8d26

I'm assuming that the roast test is missing though.

**Comment by zoffixznet** [comment]
https://github.com/perl6/roast/commit/144670d13b
