### ISSUE TITLE
illegal reflective access

### ISSUE THREAD

**Issue by bmusin** [rakudo/rakudo#1431]
## The Problem
perl-j on start shows
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.perl6.nqp.runtime.Ops (file:/home/bulat/Programs/perl6_play/share/nqp/runtime/nqp-runtime.jar) to field sun.management.RuntimeImpl.jvm
WARNING: Please consider reporting this to the maintainers of org.perl6.nqp.runtime.Ops
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
```
## Expected Behavior
Show no warnings.
## Actual Behavior
Shows warnings with above text.
## Environment
* Operating system: 
Linux asus 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v`): 
This is Rakudo version 2017.12-270-g90246e652 built on JVM
implementing Perl 6.c.

**Comment by peschwa** [comment]
According to some [research](https://stackoverflow.com/questions/46230413/jdk9-an-illegal-reflective-access-operation-has-occurred-org-python-core-pysys/46230678) this is JDK9-specific, which I unfortunately currently don't have available on my dev box.

**Comment by usev6** [comment]
I just found this old issue. The problem shouldn't exist anymore, since a workaround was added back in 2019 with https://github.com/Raku/nqp/pull/536.
