### ISSUE TITLE
misleading error message with ".=" and "sprintf"

### ISSUE THREAD

**Issue by kuerbis** [rakudo/rakudo#1437]
my Str $a = 'x'; $a .= sprintf( '%d', 20 ); say $a;

    # Your printf-style directives specify 0 arguments, but 2 arguments were supplied

perl6 -v
This is Rakudo version 2017.12-12-g1f99aa145 built on MoarVM version 2017.12-1-g912f9678
implementing Perl 6.c.

OpenSUSE Leap 42.3

**Comment by zoffixznet** [comment]
Can you suggest a better error?

**Comment by b2gills** [comment]
About the best way is to include the string that is in `$a` in the error.

**Comment by zoffixznet** [comment]
> About the best way is to include the string that is in $a in the error.

I guess. Just be sure to trim it down to a few dozen chars.

Sidenote: a year ago we had a discussion, key points of which were that including raw data in error messages was a security hazard (e.g. risk of spamming credit card numbers into some log file). Now, I notice that in more and more error messages we do precisely that.

**Comment by coke** [comment]
I don't recall that discussion, but that is definitely a concern.

Maybe the trick is to include as much data as possible into compile time errors, but not runtime ones.

**Comment by zoffixznet** [comment]
> I don't recall that discussion

Looks like it was [rather brief](https://irclog.perlgeek.de/perl6/2017-06-26#i_14788571)

**Comment by dolmen** [comment]
This is a case of a Perl 5 programmer discovering Perl 6. The mistake is to use `.=` instead of `~=`.

**Comment by dolmen** [comment]
Note that there exists valid cases of using `.=` on `Str` (e.g. `$a .= succ()`), so we can't just ban it.

**Comment by zoffixznet** [comment]
> This is the kind of mistake that should be caught at compile time as a warning,

Method calls are late-bound, so we can't do much about it at compile time, as we don't know what that method will really be by runtime.

> This issue doesn't look easy to resolve or good first issue.

Thanks. I removed the labels.

**Comment by ab5tract** [comment]
I would argue that this is Fine Enough. Unless we want to generalize some mechanism that reports wrongly fit parameter sets being passed to subroutines that have been called as methods, I don't see this being worth the effort.
