### ISSUE TITLE
Bag.pick is not working with arguments

### ISSUE THREAD

**Issue by lefth** [rakudo/rakudo#1438]
`Bag.pick` is throwing exceptions when used with arguments. With no argument, it works as expected:

```
> (bag 'a', 'b').pick
a
```

A nonempty bag does not work with the argument "1":
```
> (bag 'a', 'b').pick(1)
P6opaque: get_boxed_ref could not unbox for the representation '20' of type Scalar
```

However, it seems to work when the argument is greater than the number of elements in the bag:
```
> (bag 'a', 'b').pick(3)
(a b)
```

Rakudo version 2017.12 built on MoarVM version 2017.12-8-g3c1cea5cf

**Comment by lefth** [comment]
Looks like lizmat fixed this with https://github.com/rakudo/rakudo/commit/7361fe2b6d. It would still be nice to get this in the tests for basic `Bag` operation. Actually, I'm not sure there are any tests for `Bag` yet.

**Comment by lizmat** [comment]
There are quite a few Bag / Mix / Set tests, but please add one for this case.
