### ISSUE TITLE
Unreachable error message in contextualizer rule

### ISSUE THREAD

**Issue by jnthn** [rakudo/rakudo#1439]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

The only way to reach the `contextualizer` rule in the Perl 6 grammar is through `variable`. That path in `variable` does `<?{ !$*IN_DECL }>`. However, `contextualizer` has a `[ <?{ $*IN_DECL }> <.panic: "Cannot declare a contextualizer"> ]?`. This error is presently unreachable thanks to the assertion in `variable`. We may want to try removing the assertion in `variable` so that this error can be reached, since it seems it'd give a better message. However, I don't know if anything relies on that not blowing up.

**Comment by tbrowder** [comment]
So the "easy" part is something like removing it and running roast with fingers crossed?
