### ISSUE TITLE
Memory leak with NativeCall

### ISSUE THREAD

**Issue by Digicrat** [rakudo/rakudo#1440]
After some experimentation, I finally traced down a segfault I've been getting to a memory leak in the NativeCall interface.  I'm using it to facilitate testing of a 32-bit embedded (meaning no dynamic allocation) C library in an easier/more-comprehensive way than I could otherwise -- though this memory leak is preventing me from running the long-duration tests that I need to.

I'm currently running 2017.12.1 (commit c84ed2942d224e4cd524fa389e0603e4e4642f77) under a 32-bit Docker Ubuntu image (Also seen with 2017.10).  I can easily observe the memory leak using "docker stats".  At it's worst, with my full application, I'm seeing approximately 0.01 GiB of memory per second getting lost.  

Below is sample code that is able to reproduce the leak.  Note I also see the same leak with the Str replaced with an int32 in the callback below.  The leak also seems to exist when no callbacks are used in some cases, but is not as reliably reproduced in that scenario.

test_memleak.pl6:
```
use v6;
use NativeCall;

constant LIB_DTEST = 'libtestlib.so';

sub dtest_log_init(&dt_csv_log (Str)) is native(LIB_DTEST) {*};
sub test_cb() is native(LIB_DTEST) {*};

sub dt_csv_log(Str $data)
{
    prompt "dt_csv_log($data)";
}

sub MAIN()
{
    dtest_log_init(&dt_csv_log);

    while 1 {
        # prompt "Call test_cb()";
        test_cb();
    }
}
```

test_memleak.c:
```
#include <stdio.h>
void (*dtlf)(char* s);
void dtest_log_init(void (*fp)(char* s))
{
  printf("Assigning dtlf to fp=0x%x\n", (int)fp);
   dtlf = fp;
}
void test_cb(void)
{
  dtlf("test_cb");
}
```

The following is a snippet from my Dockerfile that installed perl6:
```
    && git clone https://github.com/rakudo/rakudo/ /root/rakudo \
    && echo 'export PATH="$HOME/rakudo/install/bin:$HOME/rakudo/install/share/perl6/site/bin:$PATH"' >> ~/.bashrc \
    && cd ~/rakudo && git checkout master && git pull \
    && git checkout $(git describe --abbrev=0 --tags) \
    && perl Configure.pl --gen-moar --gen-nqp --backends=moar \
    && make && make install \
```

**Comment by Digicrat** [comment]
To update, the issue is still present with 2018.01.

Interestingly, the time it takes before I get a segfault as a result of the memory leak varies even when my script is performing identical tasks.  I'd guess maybe 1/5 of the time it manages to execute significantly (2x-3x) longer than other times.

**Comment by AlexDaniel** [comment]
Can you retest now? There were some related improvements.

**Comment by Digicrat** [comment]
The leak may have slowed, but has not been eliminated.

**Comment by Digicrat** [comment]
I just rebuilt from HEAD and the issue is still present.  It's possible the leak may have slowed (or it could just be a coincidence that it took longer to crash this time), but it's definitely still there.

**Comment by ab5tract** [comment]
The provided code does not leak memory in `Rakudo™ v2024.04-79-g66c4acad2`.

Changing 

```
sub dt_csv_log(Str $data)
{
    prompt "dt_csv_log($data)";
}
```

to 

```
sub dt_csv_log(Str $data)
{
    dt_csv_log($data);
}
```

does, however, leak memory very quickly before getting hit with a `SIGKILL` from the OS (macOS).

Looking at the code, however, I think such a leak can only be expected under such circumstances. Closing this now as fixed.
