### ISSUE TITLE
We do need signal(SIGINT) supplies to work together somehow

### ISSUE THREAD

**Issue by melezhik** [rakudo/rakudo#1445]
## The Problem

Based on https://irclog.perlgeek.de/perl6/2018-01-26#i_15741001

In case there are more then one signal handlers ( matching certain SIGNAL ), looks only one is triggered ( first one ) 

## Expected Behavior

We need to ensure that all the signal handlers are triggered : 

```
$ perl6 -e 'signal(SIGINT).tap: { say "good bye one!"; exit(0)};  signal(SIGINT).tap: { say "good bye two!"; exit(0)}; sleep 1000'
^Cgood bye one! 
good bye two!
```

## Actual Behavior

The only first handler is triggered 

```
$ perl6 -e 'signal(SIGINT).tap: { say "good bye one!"; exit(0)};  signal(SIGINT).tap: { say "good bye two!"; exit(0)}; sleep 1000'
^Cgood bye one!
```

## Steps to Reproduce

See previous examples

## Environment

* Operating system: `Ubuntu 16.04.3 LTS \n \l`
* Compiler version (`perl6 -v`):  
```
This is Rakudo version 2017.06 built on MoarVM version 2017.06
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
FWIW, I think *all* are triggered if they would get the chance.  But if the first of the taps decides to `die` or `exit`, the other ones (most likely also wanting to perform cleanup) are not done anymore.

My suggestion would be that `signal` returns a special type of `Supply` on which taps are ensured to run all allways, even if one of the taps decides to call it a day.  This could probably be a generic functionality, not necessarily limited to `signal`.

**Comment by AlexDaniel** [comment]
I don't see any issue here. The programmer explicitly said that the program should `exit`, and that's what it does. Note that calling `exit` will prevent other things from running too, like `LEAVE` blocks. I think this ticket is rejectable, but instead of just rejecting this I recommend we move that issue to the doc repo in order to document how the intended behavior can be achieved.

So what is the intent here? You want *all* signal handlers to be processed before the program is exited?

**Comment by jnthn** [comment]
`exit` means `exit`. If you write multiple handlers, they are all triggered:

```$ perl6 -e 'signal(SIGINT).tap: { say "good bye one!" };  signal(SIGINT).tap: { say "good bye two!" }; sleep 1000'
^Cgood bye two!
good bye one!
^Cgood bye two!
good bye one!
```

But if you ask the process to exit, then that will happen. I suggest using `END` blocks and then installing one handler that exits on `SIGINT`, thus triggering those `END` blocks.

**Comment by melezhik** [comment]
IMHO The issue here is _someone else_ have `exit` or `die` code at signal handler, this spoil others signal handlers might exits in chain ... This seems confusing to me.

**Comment by AlexDaniel** [comment]
Relevant trap: https://docs.perl6.org/language/traps#LEAVE_phaser_and_exit. Perhaps its description can be extended to cover this as well.

**Comment by lizmat** [comment]
So basically we need to enforce that cleanups are done in END blocks *ALWAYS*.  And that signal handlers should only set a flag to indicate some cleanup is needed.

Having said that, *if* we have multiple taps on a `signal`, are we guaranteed that *all* will run even if the first does an `exit`?  From my understanding of the code, we are not.

**Comment by melezhik** [comment]
Yeah, and we are not lucky with `die` also:

```
$ perl6 -e 'CATCH { default { say "OK"} }; signal(SIGINT).tap: { say "good bye!"; die };  signal(SIGINT).tap: { say "good bye2!"; exit(0)}; sleep 1000'
^Cgood bye!
Unhandled exception in code scheduled on thread 5
Died
  in block  at -e line 1
```

**Comment by melezhik** [comment]
> So some handlers may not get the chance to set their flag before the associated END block is run.

that's the idea ...

**Comment by jnthn** [comment]
> Having said that, if we have multiple taps on a signal, are we guaranteed that all will run even if the first does an exit? From my understanding of the code, we are not.

No, and I can't see any way that we could reasonably do that.

**Comment by melezhik** [comment]
So if we could not ensure this by Perl6, all we can do is to agree (modules authors ) not to throw `die` or `exit` at signals handlers. Can we?

**Comment by melezhik** [comment]
and this one is also interesting ( no `exit` or `die` at all ):

```
$ perl6 -e 'signal(SIGINT).tap: { say "good bye!"; };  signal(SIGINT).tap: { say "good bye2!" }; sleep 1000'
^Cgood bye!
Unhandled exception in code scheduled on thread 3
Cannot resolve caller postcircumfix:<[ ]>(Mu, Int); none of these signatures match:
    (\SELF, Any:U $type, |c is raw)
    (\SELF, int $pos)
    (\SELF, int $pos, Mu \assignee)
    (\SELF, int $pos, Mu :$BIND! is raw)
    (\SELF, int $pos, :$delete!, *%other)
    (\SELF, int $pos, :$exists!, *%other)
    (\SELF, int $pos, :$kv!, *%other)
    (\SELF, int $pos, :$p!, *%other)
    (\SELF, int $pos, :$k!, *%other)
    (\SELF, int $pos, :$v!, *%other)
    (\SELF, Int:D $pos)
    (\SELF, Int:D $pos, Mu \assignee)
    (\SELF, Int:D $pos, Mu :$BIND! is raw)
    (\SELF, Int:D $pos, :$delete!, *%other)
    (\SELF, Int:D $pos, :$exists!, *%other)
    (\SELF, Int:D $pos, :$kv!, *%other)
    (\SELF, Int:D $pos, :$p!, *%other)
    (\SELF, Int:D $pos, :$k!, *%other)
    (\SELF, Int:D $pos, :$v!, *%other)
    (\SELF, Any:D \pos)
    (\SELF, Any:D \pos, Mu \assignee)
    (\SELF, Any:D \pos, Mu :$BIND! is raw)
    (\SELF, Any:D \pos, :$delete!, *%other)
    (\SELF, Any:D \pos, :$exists!, *%other)
    (\SELF, Any:D \pos, :$kv!, *%other)
    (\SELF, Any:D \pos, :$p!, *%other)
    (\SELF, Any:D \pos, :$k!, *%other)
    (\SELF, Any:D \pos, :$v!, *%other)
    (\SELF, Iterable:D \pos)
    (\SELF, Iterable:D \pos, Mu \val)
    (\SELF, Iterable:D \pos, :$BIND!)
    (\SELF, Iterable:D \pos, :$delete!, *%other)
    (\SELF, Iterable:D \pos, :$exists!, *%other)
    (\SELF, Iterable:D \pos, :$kv!, *%other)
    (\SELF, Iterable:D \pos, :$p!, *%other)
    (\SELF, Iterable:D \pos, :$k!, *%other)
    (\SELF, Iterable:D \pos, :$v!, *%other)
    (\SELF, Callable:D $block)
    (\SELF, Callable:D $block, Mu \assignee)
    (\SELF, Callable:D $block, :$BIND!)
    (\SELF, Callable:D $block, :$delete!, *%other)
    (\SELF, Callable:D $block, :$exists!, *%other)
    (\SELF, Callable:D $block, :$kv!, *%other)
    (\SELF, Callable:D $block, :$p!, *%other)
    (\SELF, Callable:D $block, :$k!, *%other)
    (\SELF, Callable:D $block, :$v!, *%other)
    (\SELF, Whatever:D)
    (\SELF, Whatever:D, Mu \assignee)
    (\SELF, Whatever:D, :$BIND!)
    (\SELF, Whatever:D, :$delete!, *%other)
    (\SELF, Whatever:D, :$exists!, *%other)
    (\SELF, Whatever:D, :$kv!, *%other)
    (\SELF, Whatever:D, :$p!, *%other)
    (\SELF, Whatever:D, :$k!, *%other)
    (\SELF, Whatever:D, :$v!, *%other)
    (\SELF, HyperWhatever:D, *%adv)
    (\SELF, HyperWhatever:D, Mu \assignee)
    (\SELF, :$BIND!)
    (\SELF, :$delete!, *%other)
    (\SELF, :$exists!, *%other)
    (\SELF, :$kv!, *%other)
    (\SELF, :$p!, *%other)
    (\SELF, :$k!, *%other)
    (\SELF, :$v!, *%other)
    (\SELF, *%other)

**Comment by jnthn** [comment]
I'd hope module authors would *in general* not be calling `exit`; it's by definition uncomposable. Ditto for `die` on a thread without anything in place to handle it (of course, much code on threads is run with `start` or bottoms out in a `react`, both of which propagate exceptions to places they can be more naturally handled).

**Comment by ab5tract** [comment]
Considering jnthn's position and the general logic of `exit`, the only reasonable resolution of this issue is stable in both `base` and `RakuAST`:

```
> set-base; r 'signal(SIGINT).tap: { say "good bye!"; };  signal(SIGINT).tap: { say "good bye2!" }; sleep 10'
^Cgood bye!
good bye2!
^Cgood bye!
good bye2!
^Cgood bye!
good bye2!
^Cgood bye!

> set-rakuast; r 'signal(SIGINT).tap: { say "good bye!"; };  signal(SIGINT).tap: { say "good bye2!" }; sleep 10'
^Cgood bye!
good bye2!
^Cgood bye!
good bye2!
^Cgood bye!
```
