### ISSUE TITLE
List.roundrobin does not work as a method on List objects.

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#1447]
List.roundrobin does not work as a method on List objects. See the following output:

- Working
<Xliff> m: say (roundrobin ((1, 2, 3), (4, 5), (6, 7, 8, 9)))
<camelia> rakudo-moar 1ee89b540: OUTPUT: «((1 4 6) (2 5 7) (3 8) (9))␤»

- Not working
<Xliff> m: ((1, 2, 3), (4, 5), (6, 7, 8, 9)).roundrobin.say
<camelia> rakudo-moar 1ee89b540: OUTPUT: «No such method 'roundrobin' for invocant of type 'List'␤  in block <unit> at <tmp> line 1␤␤»

I would expect, the output to be the same for both invocations listed above. As per the docs, roundrobin is listed as a method of List objects.

* Operating system: 

This has been tested under a 32-bit Linux VM, and reproduced on camelia in the #perl6 IRC channel.

* Compiler version (`perl6 -v`): 

```
This is Rakudo version 2017.10-4-g4fca94743 built on MoarVM version 2017.10
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
I'm -⅓ on making this a method and would propose the docs are simply fixed. 

Thematically this routine operates on a *a bunch of lists* so making it a method on *a list* is a bit outside of that, despite the subroutine using `+@` slurpy semantics.

**Comment by Xliff** [comment]
Would a fix on the docs simply involve a change of "method" to "sub"?

**Comment by zoffixznet** [comment]
Pretty much, plus signature change to `sub roundrobin(+list-of-lists)` or something along those lines.

**Comment by AlexDaniel** [comment]
> I'm −⅓ on making this a method and would propose the docs to be fixed instead.

I was convinced that we had a `.zip` method, but turns out that we don't (only for supplies but that's unrelated). So yeah, I'm not sure what is the justification for having it.

-⅔, I think this is rejectable once a ticket for docs is created (or if it's fixed right away).
