### ISSUE TITLE
SEGV if the path for MVM_COVERAGE_LOG is not writable

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1451]
```bash
MVM_COVERAGE_LOG=/anoethusntoahu perl6 -e 'say ‘hello’'
```
```
Segmentation fault
```

Obviously, no segfault should happen.

**Comment by dogbert17** [comment]
Perhaps a check that a file handle was indeed returned should be done after

https://github.com/MoarVM/MoarVM/blob/master/src/moar.c#L327
