### ISSUE TITLE
Please improve the class IO::Path routines copy() and move() 

### ISSUE THREAD

**Issue by kolikov** [rakudo/rakudo#1453]
## Methods copy and move expect only a file as their $to argument 
my $src   = IO::Path.new('/home/zz/file.gz');
my $dest  = IO::Path.new('/home/zz/tmp');
$src.move($dest);

## Actual Behavior
Failed to move '/home/zz/zz.tar.gz' to '/home/zz/tmp': Failed to move file: illegal operation on a directory.

## Expected Behavior
As a the good old 'cp' or 'mv'  commands in Linux (move/copy the file into the target directory), as IO::Path has methods to identify files from directories, Make the 'move' and 'copy' a multi sub with a signature test for a file on $from and directory for $to.

That would be BTA 👍 
Except if it breaks too much things ... or @zoffixznet 's heart  :-)

## Environment
* Operating system: Linux 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64
* Compiler version (`perl6 -v`): Rakudo version 2017.10 MoarVM version 2017.10  Perl 6.c.

**Comment by zoffixznet** [comment]
👍 Makes sense to me.

Would also mirror how Perl 5's core [File::Copy](https://metacpan.org/pod/File::Copy) behaves.

**Comment by zoffixznet** [comment]
> +1 Makes sense to me.

After the discussions on https://github.com/rakudo/rakudo/pull/2043 , IMO this should be an ecosystem module first

**Comment by doomvox** [comment]
This issue is still confusing people: 

https://stackoverflow.com/questions/71909580/move-function-does-not-work-in-raku-in-windows
