### ISSUE TITLE
LEAVE say now - ENTER now dies deeply

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1455]
## The Problem

LEAVE say now - ENTER now

dies with a strange error and a long stack trace deep in the nqp bowels.

## Expected Behavior

0.00123  # or some value like that

## Actual Behavior

$ 6l 'LEAVE say now - ENTER now'
Cannot reference undeclared local 'enter_result__1'
   at gen/moar/stage2/QAST.nqp:6157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_var)
 from gen/moar/stage2/QAST.nqp:6020  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5269  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:2904  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:handle_arg)
 from gen/moar/stage2/QAST.nqp:3001  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:1609  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_op)
 from gen/moar/stage2/QAST.nqp:5953  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:2904  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:handle_arg)
 from gen/moar/stage2/QAST.nqp:3001  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:1609  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_op)
 from gen/moar/stage2/QAST.nqp:5953  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:6492  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5909  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5526  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5505  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5454  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5153  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5918  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5862  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5153  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5918  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5526  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5505  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5454  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5269  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5153  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:2971  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:1609  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_op)
 from gen/moar/stage2/QAST.nqp:5953  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5269  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5909  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5526  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5505  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5454  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5269  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5297  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5269  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5157  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:4893  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:to_mast)
 from gen/moar/stage2/QAST.nqp:6639  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QAST.moarvm:to_mast)
 from gen/moar/stage2/NQPHLL.nqp:443  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:mast)
 from gen/moar/stage2/NQPHLL.nqp:1794  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1830  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1833  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1819  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1519  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1644  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1699  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1625  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<entry>)
## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.01-57-g4d2b54e built on MoarVM version 2018.01-49-g783a4f0

**Comment by jnthn** [comment]
Will be over-aggressive lexical to local lowering.
