### ISSUE TITLE
[RFC] make `:.foo` mean `:foo(.foo)`, as in `:foo($_.foo)`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1462]
Finding myself often writing something like

```perl-6
    Some::Other.new: :foo(.foo) :bar(.bar) :ber(.ber) with $obj
```

Would be neat to have it as

```perl-6
    Some::Other.new: :.foo :.bar :.ber with $obj
```

(tho not yet unsure how well these would play with stuff like `GLOBAL::.keys` that use the same symbols)

Anyone else frequents these constructs? Perhaps, there's a trick I'm overlooking?

**Comment by AlexDaniel** [comment]
> Anyone else frequents these constructs?

12 lines, 4 modules: https://gist.github.com/3db74087abeec7db9cded3f9bb48bacc

**Comment by zoffixznet** [comment]
In light of #1532 the colonpairs are an even larger beast than I thought when I opened this ticket.

Don't want to make it larger by my hand, so I'm gonna self-reject this. Will see if anyone else stumbles upon this idea in the future.
