### ISSUE TITLE
Missing error text when specifying more than one `--target`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1464]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

I'd expect it to say that I passed too many `--target`s, but it says instead it can't stringify stuff:

```bash
$ ./perl6 --target=parse --target=ast -e 'my $x; $x.=self'
Unhandled exception: cannot stringify this
   at gen/moar/stage2/NQPHLL.nqp:435  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:is_precomp_stage)
 from gen/moar/stage2/NQPHLL.nqp:1604  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/zoffix/R/rakudo/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/zoffix/R/rakudo/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/zoffix/R/rakudo/perl6.moarvm:<main>)
 from <unknown>:1  (/home/zoffix/R/rakudo/perl6.moarvm:<entry>)

$ ./perl6 -v
This is Rakudo version 2018.01-66-g72948e847 built on MoarVM version 2018.01-51-g7434f5e33
implementing Perl 6.c.
```

**Comment by tinmarino** [comment]
I would expect it to use the second value `--target=ast` because errors are always annoying no ?
I'm on it: easy task for a newcomer.
After that I would like to implement `-i`: it should not be too difficult, is it ?

**Comment by tbrowder** [comment]
On Wed, Feb 26, 2020 at 11:36 Tinmarino <notifications@github.com> wrote:

> I would expect it to use the second value --target=ast because errors are
> always annoying no ?
> I'm on it: easy task for a newcomer.
> After that I would like to implement -i: it should not be too difficult,
> is it ?
>

Well, good luck. If you do it successfully, please document how you
implemented it in some easy-to-find place. I want to add another run
argument myself, but I haven't yet found the place in the code to do it.

I think you're going to have to dig into nqp and maybe hll.

-Tom

**Comment by Altai-man** [comment]
>I would expect it to use the second value --target=ast because errors are always annoying no?

Raising an error is better than silently defaulting.

**Comment by tinmarino** [comment]
Fast comments are welcome
I just wrapped the critical string coercion in a try catch: I did not manage to check for types correctly (after 5h trying)
