### ISSUE TITLE
Postfix → Prefix ++/-- optimization

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1477]
There was an attempt at this, but we had to revert it: https://github.com/rakudo/rakudo/commit/d98ccea278d1adb23c51139f5572bce840ac6657

See https://github.com/rakudo/rakudo/issues/1315 for more info (there's also a test now).

The idea is that ``$a++`` can be turned into ``++$a`` and that gives some performance advantages (and also makes it conveniently unnecessary for us to use ++$a in core).

**Comment by zoffixznet** [comment]
Added an implementation in https://github.com/rakudo/rakudo/commit/971d17c43f35e09ad91dfc62b038552a6a344e67 but for mysterious reason it comes out slower, which I noted as Issue https://github.com/rakudo/rakudo/issues/1491

**Comment by zoffixznet** [comment]
Tests that it's NOT applied for custom ops added in https://github.com/perl6/roast/pull/386 but once https://github.com/rakudo/rakudo/issues/1491 is resolved and https://github.com/rakudo/rakudo/commit/971d17c43f35e09ad91dfc62b038552a6a344e67 is uncommented, could also use tests in rakudo's test suite that it *is* applied. I implemented [a QAST testing module](https://github.com/rakudo/rakudo/blob/master/t/packages/Test/Helpers/QAST.pm6) to help with that ([sample of its use](https://github.com/rakudo/rakudo/blob/master/t/08-performance/02-qast-rewrites.t))

**Comment by zoffixznet** [comment]
Some comments about that we shouldn't just not optimize custom ops, but rather have some policy users could enable/disable: https://irclog.perlgeek.de/perl6-dev/2018-02-07#i_15786958

**Comment by lizmat** [comment]
Closing as there is no discernible difference between prefix and postfix integer increment/decrement anymore:
```
% time raku -e 'my int $a;  $a++ for ^100000000'   
real	2.63s
user	2.62s
sys	0.02s
% time raku -e 'my int $a;  ++$a for ^100000000'
real	2.65s
user	2.64s
sys	0.02s
```
There still **is** a difference for `Int`:
```
% time raku -e 'my Int $a;  ++$a for ^10000000' 
real	1.04s
user	1.03s
sys	0.02s
% time raku -e 'my Int $a;  $a++ for ^10000000'
real	0.91s
user	0.91s
sys	0.02s
```
but one should use native `int`s for these cases 99% of the time anyway.
