### ISSUE TITLE
Missing serialize REPR function for BOOTException / LTA bug hunt

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1490]
One of our users spent 2 or more days debugging a problem with `Missing serialize REPR function for BOOTException` showing up when installing a module.

I knew the cause of this error (serializing an Exception object) but I couldn't repro it locally and even once that user gave me access to their box it took me about 3 hours to hunt it down to... [a `try` statement in one of the dependencies](https://github.com/zoffixznet/perl6-IRC-Client/blob/16230d8ee5a7275f3e7f87fa2ba0e8ed659acedd/lib/IRC/Client.pm6#L25-L28) that checks whether `Terminal::ANSIColor` can be `required`.

I don't know anything about serialization, but I'm opening this ticket in hopes the current situation can be improved. Is there a way to serialize exceptions? And if not, is there a way to serialize some dummy exception or make this error go away silently somehow? Maybe even resetting `$!` to Nil if it's set instead of serializing it?

**Comment by ab5tract** [comment]
This is not reproducible any more, either with or without `Terminal::ANSIColor` installed:

```
> raku issues/r1490.raku

> zef install Terminal::ANSIColor
All candidates are currently installed

> ./rakudo-m issues/r1490.raku

> ./rakudo-m -MTerminal::ANSIColor -e ''
===SORRY!=== Error while compiling -e
Could not find Terminal::ANSIColor in:

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-96-ge3ad75a69.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```
