### ISSUE TITLE
Failure.DESTROY warning sometimes warns when Failure was technically handled

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1502]
*Originally started in https://github.com/rakudo/rakudo/issues/1298 This problem was [spotted](https://irclog.perlgeek.de/perl6-dev/2018-02-08#i_15794851) in one of our tests.*

Usually Failure.DESTROY warning about unhandled Failures is good, but there is this edge case where more than one Failure is involved:

```
22:04 |   | e: use Test; for ^1000 { my $ = Failure.new < Failure.new; CATCH { default {} } }
-- | -- | --
22:04 | evalable6 | Zoffix, rakudo-moar 8ba3c86e7: OUTPUT: «WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it…»
22:04 |   | Zoffix, Full output: https://gist.github.com/06e558ac81c8f261ad2d9c5236b06cfa
```

The exlosion happens when `.Real` is called inside `<` op, but the explosion of the first Failure prevents the second Failure from ever exploding, resulting in warnings for failures that weren't technically left unhandled.

**Comment by ab5tract** [comment]
This is still happening as of:

```
> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-92-g24057e69c.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```
