### ISSUE TITLE
Procs that finish with non-zero exit code end up throwing, but SEGVs are totally OK

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1507]
Here's an example that works correctly:

Code:
```perl6
run ‘perl6’, ‘-e’, ‘exit 1’; say 42
```
Result:
```
The spawned command 'perl6' exited unsuccessfully (exit code: 1)
  in block <unit> at -e line 1
```

↑ This behavior is totally ok and is what we expect in such situations.

But this ↓ does not feel quite right:

Code:
```perl6
run ‘perl6’, ‘-e’, ‘use NativeCall; sub strdup(int64) is native(Str) {*}; strdup(0)’; say ‘https://goo.gl/mViBPW’
```

Output (the spawned process actually ends with a Segmentation fault):
> https://goo.gl/mViBPW

**Comment by lizmat** [comment]
```
% raku -e 'use NativeCall; sub strdup(int64) is native(Str) {*}; strdup(0)'
zsh: segmentation fault
```
This is really a NativeCall issue.  Or better a DIHWIDT.  So closing
