### ISSUE TITLE
Useless useless use warning in OO::Monitors

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1512]
When installing OO::Monitors module:
```
===> Testing: OO::Monitors:ver<1.1>
WARNINGS for /home/travis/.zef/store/oo-monitors.git/b9de07c277f0a9fa805bb18113788228f6acfd3b/t/condition.t:
Useless use of constant value not-empty in sink context (lines 15, 20)
Useless use of constant value not-full in sink context (lines 12, 22)
```

[According to @jnthn](https://github.com/jnthn/oo-monitors/issues/11#issuecomment-364749584):
> That'd be a Rakudo bug. The values in question are arguments to a macro, and the argument is used.

Corresponding module issue: https://github.com/jnthn/oo-monitors/issues/11

Actually, I've noticed this issue quite some time ago but shrugged it off because it's a warning and also because the code is using experimental macros, but we'd have to fix this anyway.

**Comment by zoffixznet** [comment]
Golf `use experimental :macros; macro z($) { quasi {} }; z $;`
