### ISSUE TITLE
Some easily reproducible leak

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1513]
```perl6
use Telemetry; use nqp; loop { nqp::force_gc(); say T<max-rss> }
```

≈92000 (≈90 MiB) at the start,  ≈268000 (≈262 MiB) after ≈20 minutes. That is ≈8.5 MiB/minute.

**Comment by lizmat** [comment]
> On 11 Feb 2018, at 11:38, Aleks-Daniel Jakimenko-Aleksejev <notifications@github.com> wrote:
> 
> use Telemetry; use nqp; loop { nqp::force_gc(); say T<max-rss> }
> ≈92000 (≈90 MiB) at the start, ≈268192 (≈262 MiB) after ≈20 minutes. That is 8.5 MiB/minute.

Additional data points:

- a 'say “foo”’ also leaks, but slower.
- a ‘nqp::getrusage’ instead of the 'say T<max-rss>’ does *NOT* leak

**Comment by niner** [comment]
> - a 'say “foo”’ also leaks, but slower.

I cannot reproduce that here on Linux with:
perl6 -e 'loop { say "foo" }' > /dev/null

top says shortly after starting:
  PID USER      PR  NI    VIRT    RES    SHR S   %CPU  %MEM     TIME+ COMMAND
 8378 nine      20   0  182576  87260  26288 R 100.33 0.265   0:56.63 moar
After ~ 15 minutes runtime:
 8378 nine      20   0  182576  87260  26288 R 100.00 0.265  15:51.27 moar

**Comment by lizmat** [comment]
> On 11 Feb 2018, at 12:28, niner <notifications@github.com> wrote:
> 
> > - a 'say “foo”’ also leaks, but slower.
> 
> I cannot reproduce that here on Linux with:
> perl6 -e 'loop { say "foo" }' > /dev/null
> 
> top says shortly after starting:
> PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
> 8378 nine 20 0 182576 87260 26288 R 100.33 0.265 0:56.63 moar
> After ~ 15 minutes runtime:
> 8378 nine 20 0 182576 87260 26288 R 100.00 0.265 15:51.27 moar 

And with the nqp::force_gc ??  The loop I meant only replaced the ‘say T<max-rss>’ bit  :-)

**Comment by niner** [comment]
> And with the nqp::force_gc ??  The loop I meant only replaced the ‘say
> T<max-rss>’ bit  :-)

Yes, with the nqp::force_gc it does indeed leak:

 9377 nine      20   0  184940  90456  26900 R 100.00 0.275   0:56.71 moar
 9377 nine      20   0  216428 122196  26964 R 100.00 0.371   7:40.73 moar                                                                                                                                 
 9377 nine      20   0  376180 285964  26964 R 100.00 0.868  40:23.12 moar

There doesn't appear to be an upper boundary:
 9377 nine      20   0  911496 821356  26964 R 100.33 2.493 148:10.90 moar

**Comment by ab5tract** [comment]
Looks like the patches from jnthn++ have been effective for some time.
