### ISSUE TITLE
SEGV when compiling rakudo with `$wantwant` debug var enabled

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1518]
On `2018.01-185-g00af9ce27`, tried to compile the compiler with [`$wantwant` debug var set to `1`](https://github.com/rakudo/rakudo/blob/00af9ce272fc59caaaf200ab1fa9c75decb2ed4d/src/Perl6/Actions.nqp#L8) and after dumping a bunch of output, the compile stage segfaulted:

```
Segmentation fault
make: *** [CORE.setting.moarvm] Error 139
The spawned command 'make' exited unsuccessfully (exit code: 2)
  in method re-make-rakudo at /home/zoffix/zscript/bin/../lib/RDev.pm6 (RDev) line 212
  in sub MAIN at /home/zoffix/zscript/bin/z line 13
  in block <unit> at /home/zoffix/zscript/bin/z line 141
```

After re-trying to compile, it segfaulted again.

**Comment by ab5tract** [comment]
Setting this value (and watching the abslutely unfathomable amount of info it produces scroll by) causes no issue as of `Rakudo™ v2024.04-92-g24057e69c`
