### ISSUE TITLE
Frequent segfaults when compiling moarvm

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1520]
This should be known, but I'm filing this ticket just to make sure everyone is aware.

For example, you can see this problem in CI logs: https://travis-ci.org/MoarVM/MoarVM/builds/340521536?utm_source=github_status&utm_medium=notification

**Comment by AlexDaniel** [comment]
Temporarily reverted the bump: https://github.com/rakudo/rakudo/commit/c83202db0a67fdf869bb21d3778110855d88c98d

**Comment by jnthn** [comment]
A workaround is to set `MVM_JIT_EXPR_DISABLE=1`, if wanting to test things with MoarVM HEAD. A recent change made an existing problem (that I already considered a blocker) show up more often. That's good in that it may well aid reproduction and debugging, and the revision bumps being manual gives us a little breathing space to decide how to proceed. As to the release, either a fix will land in time, or we'll default the expression JIT to disabled for the release (probably some days before, to allow testing).

**Comment by bdw** [comment]
If this is the same thing I was looking at, it is triggered by compilation of getlexstatic_o, specifically in the compilation of the branch that does the spesh logging, i.e. MVM_spesh_log_static.
However, it does so only when not setting MVM_SPESH_BLOCKING, making it impossible to bisect.

**Comment by bdw** [comment]
I've disabled the compilation of getlexstatic_o for the time being, so I'm not sure if this is still practically broken for you

**Comment by AlexDaniel** [comment]
OK there's no noticeable problem anymore, so removing the blocker. @bdw please close if you think that this is resolved fully.

**Comment by ab5tract** [comment]
This hasn't resurgaced in 6 years.
