### ISSUE TITLE
Backtrace.gist could be better

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1521]
From perl6/doc#1770 by @jimav, backtrace is apparently empty.

## The Problem

```
my $þor = sub { die "Something bad happened" };
try {
    $þor();
}
if ($!) {
    say $!.backtrace; 
}
```
prints: `Backtrace.new`

## Expected Behavior

Should print the backtrace, I guess. 

## Actual Behavior

The backtrace seems to be empty

## Steps to Reproduce

Run the program above

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
In the code you show, you're not printing it, you're gisting it. Seems to be set just fine if you print it:

```perl6
my $þor = sub { die "Something bad happened" };
try $þor();
$! and print $!.backtrace;
  # in sub  at ../z.p6 line 1
  # in block <unit> at ../z.p6 line 2
say '----';
$! and print $!.backtrace.full;
  # in method throw at SETTING::src/core/Exception.pm line 57
  # in sub die at SETTING::src/core/control.pm line 178
  # in sub  at ../z.p6 line 1
  # in code  at ../z.p6 line 2
  # in block <unit> at ../z.p6 line 3
```

**Comment by JJ** [comment]
That was my own example, but the original issue is here:
https://github.com/perl6/doc/issues/1770
I'll try to see if that fixes it. Thanks!

**Comment by JJ** [comment]
Now I see what's the problem. `say` prints `Backtrace.new`, `print` actually works. I guess that's a close, and I'll go back to the examples and fix them. Thanks!

**Comment by zoffixznet** [comment]
Maybe `Backtrace.gist` should include frames; e.g. `"Backtrace(3 frames)"`

Right now it looks to be going through `Mu.gist`, which just uses `.perl`

**Comment by JJ** [comment]
Yep, that would help, but anyway you've helped me solve the doc issue, so
thanks!
