### ISSUE TITLE
"does" loses "handles"

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#1524]
m: my $c = class C {has Int $.a handles * = 3}.new; say $c.is-prime; $c does role :: {}; $c.is-prime

## The Problem
"does" looses "handles"

## Expected Behavior
True
True

## Actual Behavior
True
No such method 'is-prime' for invocant of type 'C+{<anon|53096992>}'␤  in block <unit> at <tmp> line 1

## Steps to Reproduce
Just run:
m: my $c = class C {has Int $.a handles * = 3}.new; say $c.is-prime; $c does role :: {}; $c.is-prime

## Environment
Mac OS X High Sierra
This is Rakudo version 2017.11-33-gb285aaf35 built on MoarVM version 2017.11
and on Camelia

**Comment by usev6** [comment]
This seems to work nowadays:
```
$ ./rakudo-m -e 'my $c = class C { has Int $.a handles * = 3 }.new; say $c.is-prime; $c does role :: {}; say $c.is-prime'
True
True
```
