### ISSUE TITLE
Possibly new segmentation fault issue on rakudo HEAD

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1527]
This issue is created to gather more info about the issue. At this point it's unclear how critical it is, or what are the actual conditions to reproduce it. Please comment if you see something similar.

[@japhb just got](https://irclog.perlgeek.de/perl6-dev/2018-02-16#i_15823920) a segmentation fault when using zef:
> \<japhb\> Fresh build of latest rakudo segfaults during zef package install:
> \<japhb\> 216379 Segmentation fault      (core dumped) `zef --/tap-harness --/cached install URI File::Temp p6doc Terminal::ANSIColor Term::termios Debugger::UI::CommandLine JSON::Tiny DBIish Linenoise Inline::Perl5 Inline::Python IRC::Client OO::Monitors Grammar::Debugger App::Mi6 cro`
> \<japhb\> (I've not yet made any attempt to wittle that down, but it came after several recursions of the dependency search, right after this line:
> \<japhb\> ===> Searching for missing dependencies: Digest

HEAD is currently on https://github.com/rakudo/rakudo/commit/beaad7b979f99d07f546efa0d48b701e6372d9ae.

**Comment by japhb** [comment]
I believe this is now obsolete (I am no longer having segfault problems with my normal package set).

**Comment by AlexDaniel** [comment]
Hmm. OK.

**Comment by ugexe** [comment]
Was likely fixed by a revert in zef: github.com/ugexe/zef/commit/750abd2b4b2464b4f260e66ae2e122f7f4b62572

Seemed to be related to concurrent module loading / serialization ( which may not be thread safe according to a recent comment from nine ).
