### ISSUE TITLE
permutations(30) and count-only

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1528]
Code:
```perl6
say +permutations(30)
```

Result (2016.07.1):
```
265252859812191058636308480000000
```

Result (HEAD(beaad7b)):
```
Cowardly refusing to permutate more than 20 elements, tried 30
in block <unit> at /tmp/78oLs8E9NR line 1
```
Change bisected: (2016-09-09) https://github.com/rakudo/rakudo/commit/8a66833d9b8d05b89ea5c0069370a67ec7374b8c

Output on all 6c releases: https://gist.github.com/0c7ecedcd136277d8692e36560670121

Basically, this part:
https://github.com/rakudo/rakudo/blob/005714b6cb12c7eb3f6032368d5a1fe43e392bb9/src/core/Rakudo/Iterator.pm#L2343-L2347
is too early, and because of that it never gets to this:
https://github.com/rakudo/rakudo/blob/005714b6cb12c7eb3f6032368d5a1fe43e392bb9/src/core/Rakudo/Iterator.pm#L2433-L2436

Somewhat related: https://github.com/rakudo/rakudo/issues/1331

**Comment by taboege** [comment]
I'd question in general if the method should really fail because an argument is too big for an implementation detail to work. That's not tormenting the implementors enough.
