### ISSUE TITLE
Spectest sometimes gets stuck on t/spec/S07-hyperrace/basics.t

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1529]
Just keep running `t/spec/S07-hyperrace/basics.t` and it should hang. Maybe this only happens under load.

I believe it existed before but right now rakudo version is https://github.com/rakudo/rakudo/commit/beaad7b979f99d07f546efa0d48b701e6372d9ae.

**Comment by zoffixznet** [comment]
Don't know if related, but `t/spec/S17-supply/syntax.t` just hung during stresstest run. Couldn't repro by running it in a loop standalone both with and without system load.

**Comment by ab5tract** [comment]
These cases no longer appear to be an issue as of:

```
> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-92-g24057e69c.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```
