### ISSUE TITLE
/proc/…/status can no longer be read line by line

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1533]
Code:
```perl6
say “/proc/$*PID/status”.IO.open.get
```

Result (2015.12⌁2018.01,`359efef70^`):
```
Name:	moar
```
Result (359efef709d27da202119ee446647d9eaea70f0f,HEAD):
```
Nil
```

Bisectable points at: (2018-01-20) https://github.com/rakudo/rakudo/commit/359efef709d27da202119ee446647d9eaea70f0f

EOF detection goes all the way to moarvm, so I also tried it on rakudo-jvm and the behavior is identical (it is “broken” after the mentioned commit).

This breaks Linux::Process::SignalInfo module.

`/proc` is a virtual filesystem so I guess everything is possible, but I wasn't expecting EOFs in `status`. Is it wrong to be reading it like this, or is there any problem on our side?

As an extra data point, if you do something like `perl6 -e 'say get' < /proc/…/status` then you get Nil, but you'll get some actual data if you do `cat /proc/…/status | perl6 -e 'say get'`. That's not surprising at all but perhaps worth a mention.

**Comment by AlexDaniel** [comment]
Some discussion: https://irclog.perlgeek.de/perl6/2018-02-16#i_15826817

**Comment by zoffixznet** [comment]
This bug actually existed for a while, with `say “/proc/$*PID/status”.IO.open.eof` always returning `True`. The https://github.com/rakudo/rakudo/commit/359efef709d27da202119ee446647d9eaea70f0f merely exposed it.

I [fixed it on MoarVM](https://github.com/MoarVM/MoarVM/commit/8d94732aad54656651a16a43fe420dae63578a8c), but didn't managed to fix on JVM. I filed JVM portion as https://github.com/rakudo/rakudo/issues/1541

Coverage tests in https://github.com/perl6/roast/commit/3ac8e0b8ae2c5d750e1aa33370e4a7a55f468dc3
