### ISSUE TITLE
Some snippet that segfaults

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1540]
This issue was noticed in #1535. The code is most likely golfable to something smaller, but right now that's all I have:
https://gist.githubusercontent.com/AlexDaniel/cd2d622b2d628e36a55a5580c8a3e02e/raw/eeac5069d3beed8dc96c4402126a15371b7af372/golfable-segfault.p6

Result (2015.12,2016.01.1,2016.02):
```
(Any) =?= 4000 characters
```

Result (2016.03⌁2017.07):
```
«exit signal = SIGSEGV (11)»
```

Result (2017.08,2017.09):
```
(Any) =?= 4000 characters
```

Result (2017.10⌁2018.01,HEAD(6ec3d7c)):
```
«exit signal = SIGSEGV (11)»
```

According to bisectable:
* The first time it started to segfault was in (2016-03-02) https://github.com/rakudo/rakudo/commit/fdd37a9e0bef16eb3e4bb24ddd59247e379b5038
* Then it was fixed (?) in one of these commits: 4561c2696c098ee2c827ed98c6276b1b8e119332 48ce47e6fad4d4c5ddd71d300d082ee77ae2d4d6 9658dd98c9dd8ecbefc606a08357e59718e328c2
* Then it broke again after [better-sched merge](https://github.com/rakudo/rakudo/commit/61a77e60a7d936415503d8916fcc7546569e9135), but that is possibly unrelated to the underlying issue.

The code is not entirely right but it should not segfault either way.

**Comment by dogbert17** [comment]
gdb shows the following when running the example code above:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-gdb-m ~/scratch.pl6 
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.01.206.g.6.ec.3.d.7.ce.3 built on MoarVM version 2018.01.94.gc.7774.e.37.d,
    running on ubuntu (14.04.3.LTS.Trusty.Tahr) / linux (3.19.0.32.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib /home/dogbert/scratch.pl6
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
    [New Thread 0xb741eb40 (LWP 28796)]
    [New Thread 0xb4bd5b40 (LWP 28797)]
    [New Thread 0xb41ffb40 (LWP 28798)]
    [New Thread 0xb37ffb40 (LWP 28799)]
    [New Thread 0xb29feb40 (LWP 28800)]
    
    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0xb29feb40 (LWP 28800)]
    0xb7b8f58c in MVM_interp_run (tc=0xb426b8c0, initial_invoke=0xb7ba0e25 <thread_initial_invoke>, invoke_data=0xb426b548) at src/core/interp.c:5343
    5343	                if (obj && IS_CONCRETE(obj) && STABLE(obj)->container_spec)
    (gdb) bt
    #0  0xb7b8f58c in MVM_interp_run (tc=0xb426b8c0, initial_invoke=0xb7ba0e25 <thread_initial_invoke>, invoke_data=0xb426b548) at src/core/interp.c:5343
    #1  0xb7ba0f5f in start_thread (data=0xb426b548) at src/core/threads.c:85
    #2  0xb7899f72 in start_thread (arg=0xb29feb40) at pthread_create.c:312
    #3  0xb79e343e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
    (gdb) info threads
      Id   Target Id         Frame 
    * 6    Thread 0xb29feb40 (LWP 28800) "moar" 0xb7b8f58c in MVM_interp_run (tc=0xb426b8c0, initial_invoke=0xb7ba0e25 <thread_initial_invoke>, invoke_data=0xb426b548) at src/core/interp.c:5343
      5    Thread 0xb37ffb40 (LWP 28799) "moar" 0xb7fdccb0 in ?? ()
      4    Thread 0xb41ffb40 (LWP 28798) "moar" 0xb7fdccb0 in ?? ()
      3    Thread 0xb4bd5b40 (LWP 28797) "moar" MVM_BC_get_I64 (cur_op=0xb6046d2e "\a", offset=4) at src/core/interp.h:100
      2    Thread 0xb741eb40 (LWP 28796) "moar" 0xb7bde0d6 in bind_pos (tc=0x8095a68, st=0x807f198, root=0xb6247028, data=0xb6247038, index=589, value=..., kind=8) at src/6model/reprs/VMArray.c:373
      1    Thread 0xb7883940 (LWP 28792) "moar" 0xb7fdccb0 in ?? ()
    (gdb) l
    5338	                goto NEXT;
    5339	            OP(sp_decont): {
    5340	                MVMObject *obj = GET_REG(cur_op, 2).o;
    5341	                MVMRegister *r = &GET_REG(cur_op, 0);
    5342	                cur_op += 4;
    5343	                if (obj && IS_CONCRETE(obj) && STABLE(obj)->container_spec)
    5344	                    STABLE(obj)->container_spec->fetch(tc, obj, r);
    5345	                else
    5346	                    r->o = obj;
    5347	                goto NEXT;
    (gdb) p MVM_dump_backtrace(tc)
       at /home/dogbert/scratch.pl6:12  (<ephemeral file>:foo)
     from /home/dogbert/scratch.pl6:25  (<ephemeral file>:)
     from SETTING::src/core/Promise.pm:194  (./CORE.setting.moarvm:)
     from SETTING::src/core/ThreadPoolScheduler.pm:798  (./CORE.setting.moarvm:)
     from SETTING::src/core/ThreadPoolScheduler.pm:238  (./CORE.setting.moarvm:)
     from SETTING::src/core/ThreadPoolScheduler.pm:232  (./CORE.setting.moarvm:run-one)
     from SETTING::src/core/ThreadPoolScheduler.pm:270  (./CORE.setting.moarvm:)
     from SETTING::src/core/Thread.pm:54  (./CORE.setting.moarvm:THREAD-ENTRY)
    $1 = void
    (gdb)

**Comment by dogbert17** [comment]
Setting MVM_SPESH_DISABLE=1 makes the SEGV go away

**Comment by timo** [comment]
addressed in https://github.com/MoarVM/MoarVM/commit/720705d2533952891e18bd9d295164dd0fd27be0 - maybe we want to go through more spesh code to see if any optimizations are forgetting to check stuff like that.

**Comment by coke** [comment]
@vrurg  notes that the example given above completes with no issue for them, timo said it was fixed in 2018.

Closing ticket.
