### ISSUE TITLE
Booliness of Zero-Denominator Rationals

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1552]
Zero-denominator Rationals are a special beast: they can exist just fine, until you do something with them: in .Str or .Int views, they explode, but in .Num view they behave in IEEE fashion and produce a -Inf/NaN/+Inf, based on the numerator.

So the question is: are zero-denominator Rationals true or false? Currently, they return `True` (somewhat by accident; the check is `self != 0`). And that kinda makes sense: mathematically, all of them are undefined (and thus aren't zero), and in Num view none of them are zero. We can also say "All numerics that aren't zero are false".

However, were the check done as `self.Int != 0`, then we'd have an explosion and a softened version of an explosion (Failure) is False.

A bit more discussion: https://irclog.perlgeek.de/perl6-dev/2018-02-21#i_15843579

**Comment by MasterDuke17** [comment]
Fwiw, Rational.Bool as `$!numerator != 0`, `$!numerator != 0 && $!denominator != 0 `, and `nqp::p6bool(nqp::istrue($!denominator) && nqp::istrue($!numerator))` all pass spectest.

**Comment by zoffixznet** [comment]
Some discussion and a ruling to follow a "numerator == 0 is False; rest is True", with OK on inconsistency between `?NaN` an d `?NaN.Rat`: 
https://irclog.perlgeek.de/perl6-dev/2018-02-23#i_15851526
