### ISSUE TITLE
The Str "comb" method (Regex candidate) returns List instead of Seq

### ISSUE THREAD

**Issue by jstuder-gh** [rakudo/rakudo#1564]
https://irclog.perlgeek.de/perl6/2018-02-24#i_15854992

## The Problem
    say "".comb(/./).^name;

    # EXPECTED OUTPUT: «Seq␤»
    # ACTUAL OUTPUT: «List␤»

## Additional Info:
The ```Regex``` candidates of ```comb``` (on ```Str```) end up calling one of ```Str```'s ```match``` methods (with a combination of the ```:global``` and ```:as``` abverbs), which returns a ```List```.

I don't know if we also want ```:global``` matches to return ```Seqs``` as well or not (all ```Iterables``` returned from core classes should be ```Seq```?)

**Comment by jstuder-gh** [comment]
https://github.com/rakudo/rakudo/blob/master/src/core/Str.pm#L475

**Comment by zoffixznet** [comment]
> (all Iterables returned from core classes should be Seq?)

No, definitely not. `Seq`s aren't `Positional`, so you can't bind them to `@` vars and they're also one-shot `Iterables` and unless they [get cached](https://perl6.party/post/Perl-6-Seqs-Drugs-and-Rock-n-Roll#stashintothecache) they'll throw on attempt to iterate again, which can be confusing for new users:

```
<Zoffix___> m: say [.head, .tail] with ()
<camelia> rakudo-moar 7d72387bc: OUTPUT: «[(Any) (Any)]␤»

<Zoffix___> m: say [.head, .tail] with ().Seq
<camelia> rakudo-moar 7d72387bc: OUTPUT: «The iterator of this Seq is already in use/consumed by another Seq␤(you might solve this by adding .cache on usages of the Seq, or␤by assigning the Seq into an array)␤  in block <unit> at <tmp> line 1␤␤
```

I think a rule of thumb is return a `Seq` when `Seq`'s laziness and non-caching behaviour can be of benefit. If you already got a cached `List`, then there's no point in a `Seq`, unless (like in this case) one candidate has a beneficial `Seq`, while another already got a `List`, so it makes sense to unify the interface and coerce that `List` to a `Seq`, to maintain consistency.

**Comment by lizmat** [comment]
Ah, good point!   :-)  Was being too eager  👍

**Comment by AlexDaniel** [comment]
I'm adding a blocker label. Not so much because there's anything blocking the release technically, but because we should look into this change and how it affects the ecosystem.

**Comment by lizmat** [comment]
> On 5 Mar 2018, at 12:49, Aleks-Daniel Jakimenko-Aleksejev <notifications@github.com> wrote:
> I'm adding a blocker label. Not so much because there's anything blocking the release technically, but because we should look into this change and how it affects the ecosystem.

If it makes more sense to have .comb always return a List, then we should go for that.  But we should also realize that having .comb with a string being lazy on an IO::Handle is a good thing (at least in my book).

**Comment by AlexDaniel** [comment]
Yes, it is a good thing. And returning a Seq *consistently* is also good. We should just quantify the breakage and do a couple of PRs if needed. Generally, we should try to avoid doing things that make users report problems [like this](https://irclog.perlgeek.de/perl6-dev/2018-03-05#i_15884704), and If the ecosystem is in a really bad shape then we'd have to think again. The label is there to make sure I'll pay enough attention to this ticket :)

**Comment by zoffixznet** [comment]
> If it makes more sense to have .comb always return a List, then we should go for that. 

Doesn't make much sense to me. Non-caching behaviour is easy to see as desirable in many cases and `.comb` does currently have cases where it can produce values without needing to cache everything. Once `Cat` is done, the regex variant would be able to do the same.

Also, IIRC we already went through ecosystem upheaval in the fall out 2016 because we changed .comb to return a Seq sometimes. We'd have to go through that again if we revert that.

.comb returning a `List` in some cases is a bug to my eyes. If there's a huge ecosystem fallout, I say we just delay the change and offer users more time to update their code.

> realize that having .comb with a string being lazy on an IO::Handle 

Currently, .comb and .split on IO::Handle and IO::CatHandle always slurp; awaiting implementation of `Cat`

**Comment by AlexDaniel** [comment]
> say we just delay the change and offer users more time to update their code

Yes, that's also possible. But it'll be easier to talk about this once we have results from toaster.

If anyone is doing a PR to fix issues related to this change please link to this ticket.

**Comment by lizmat** [comment]
> On 5 Mar 2018, at 13:01, Zoffix Znet <notifications@github.com> wrote:
> Currently, .comb and .split on IO::Handle and IO::CatHandle always slurp; awaiting implementation of Cat

Correct.  I had mistaken it with the implementation of IO::Handle.words.

Having said that, Str.comb(|Int|Str)  *are* lazy  :-)

**Comment by zoffixznet** [comment]
Toast results are now avaiable and look OK: https://toast.perl6.party/

-----

App::Cpan6/Dist::Helper: User had locked deps to ancient version of JSON::Fast, which fail due to comb change (and have other bugs). Reported: https://github.com/scriptkitties/perl6-dist-helper/issues/34

**Comment by dogbert17** [comment]
Issue connected to [RT #131275](https://rt.perl.org/Ticket/Display.html?id=131275)

**Comment by AlexDaniel** [comment]
OK, so I looked at toaster output, and most of the fails there are unrelated to this change. In my view there's no problem with this issue, so no need for a blocker label anymore.

That said, please ping me if there's anything else I should know regarding this issue.
