### ISSUE TITLE
Need CStruct/NativeCall support for C "int" (and other currently-unsuported legacy C types)

### ISSUE THREAD

**Issue by jimav** [rakudo/rakudo#1569]
Prior discussion: https://github.com/perl6/doc/issues/1771

## The Problem: NativeCall and CStruct do not support C "int" (and several others).

As a consequence, some POSIX and other traditional C library routines can not be portably called using NativeCall.   For example, the POSIX `localtime()` uses `struct tm` in its interface, and that struct contains C "int" fields.  Since there is no portable way to read or write such a struct in P6, `localtime` can not be used by portable Perl6 programs.

The reason is that there is no Perl6 type which is <i>guaranteed</i> to match a C "int".  So there is no portable way to invoke a C routine which involves C "int"s in the interface.   Of course, it is possible to write non-portable code using <i>a priori</i> knowledge of what sizeof(int) is in C on the current platform (coding "int16", "int32", or "int64" as appropriate).  But such code will silently break when moved to a platform with differently-sized C legacy types.

Note: The C language does not define fixed sizes for the legacy types (short, int, long, long long, and unsigned versions thereof).  Instead, C99 specifies <i>minimum</i> sizes (e.g. 16 bits for "int").   They are supposed to be whatever is "most natural" or "efficient" on the platform.  Actual sizes vary in space and time; the only guarantee is that the sizes are fixed on a given "platform" (== hardware+compiler options).

<b>Current Status:</b> NativeCall currently documents support for <i>some</i> legacy C types: long, ulong, and longlong and ulonglong.  But it expressly disclaims support for "int", stating that Perl6 defines "int" independently of C and thus they might be different.   See https://docs.perl6.org/language/nativecall#Passing_and_Returning_Values

<b>Proposed Solutions:</b>

1. (My preference)  Officially guarantee that Perl6's "int" will always match C's "int" on a given platform, and define the missing "C-like" types similarly: short, ushort, unsigned (or uint), float, and double (we already have long, ulong, longlong, and ulonglong).

This would, IMO, provide the most obvious and simplest-to-document-and-understand solution.  P6's native "int" type is, as I understand it, supposed to be the largest "fast" native integer on the platform.  The same criteria, more or less, is suppoed to be used by C as well.  So making P6 and C always identical for these types eliminates a lot of conceptual complexity around NativeCall & CStruct.

2.  In the alternative, define some other P6 type, e.g. "cint", which <i>is</i> guaranteed to match a C "int".   For consistency define similarly-named P6 types for all other legacy C types (e.g. "cuint", "clong", "culong", "cshort", "cushort", "clonglong", "culonglong", "cfloat", and "cdouble") and deprecate the existing Perl6 names for C types ("long" etc.)

If this alternative is adopted, then to keep people from unknowingly writing non-portable code, a <i>compile time error</i> or warning should occur if a `CStruct` contains an `int` or any other type which does not have a guaranteed predictable mapping to a C type.

**Comment by abraxxa** [comment]
I was interested in this support for the Oracle database client using the OCI library but I wasn't involved in its development for quite some time and was able to convince my $work to migrate to PostgreSQL. 🥳

**Comment by lizmat** [comment]
Thanks for the feedback!

**Comment by abraxxa** [comment]
At the time when I started DBDish::Oracle there where only signed numeric datatypes available in Raku while OCI uses unsigned.
