### ISSUE TITLE
[JVM] Methods return containerized attribute values

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1572]
Originally spotted here: https://github.com/rakudo/rakudo/commit/d5baa036faafac7e1a3dc9203dcdfb7674151b22#commitcomment-27783688

On Moar, the returned value of methods that aren't `is rw` is not containerized, but on JVM it is:

```
<Zoffix_> r: use nqp; class Foo { has $.bar; method z { $!bar } }; dd nqp::iscont(Foo.new.z)
<camelia> rakudo-moar eb0649221: OUTPUT: «0␤»
<camelia> ..rakudo-jvm a92950fb4: OUTPUT: «1␤»

<Zoffix_> r: use nqp; class Foo { has $.bar; method z is rw { $!bar } }; dd nqp::iscont(Foo.new.z)
<camelia> rakudo-jvm a92950fb4, rakudo-moar eb0649221: OUTPUT: «1␤»
```

Same happens with plain variables:
```
<Zoffix_> r: use nqp; class Foo { has $.bar; method z { my $bar } }; dd nqp::iscont(Foo.new.z)
<camelia> rakudo-jvm a92950fb4: OUTPUT: «1␤»
<camelia> ..rakudo-moar eb0649221: OUTPUT: «0␤»

<Zoffix_> r: use nqp; class Foo { has $.bar; method z is rw { my $bar } }; dd nqp::iscont(Foo.new.z)
<camelia> rakudo-jvm a92950fb4, rakudo-moar eb0649221: OUTPUT: «1␤»
```

----

Note that there's a special circumstance—and I'm not quite sure if it's a bug or not. The `Proxy` returned from a method shows up as `iscont` even for non-`is rw` methods and and if the JVM fix is to merely to `nqp::decont` the value, it'd remove the `Proxy`.

```
<Zoffix_> r: use nqp; class Foo { method z { Proxy.new: :STORE{$^a, $^b;Nil}, :FETCH{$^a;Nil} } }; dd nqp::iscont(Foo.new.z)
<camelia> rakudo-jvm a92950fb4, rakudo-moar eb0649221: OUTPUT: «1␤»
```

**Comment by usev6** [comment]
It looks like this has been fixed in the meantime. On JVM the returned value of methods that aren't ```is rw``` is not containerized anymore:
```
$ ./perl6-j -e 'use nqp; class Foo { has $.bar; method z { $!bar } }; dd nqp::iscont(Foo.new.z)'
0
$ ./perl6-j -e 'use nqp; class Foo { has $.bar; method z { my $bar } }; dd nqp::iscont(Foo.new.z)'
0
```

I don't know which commit fixed it and I'm not patient enough to bisect this on the JVM backend.

Also, I'm not sure whether this merits a test (and if so, where it should go to: roast or rakudo).

**Comment by usev6** [comment]
No need to keep this issue open. All code snippets work as expected now.
