### ISSUE TITLE
Regression causing previously working script to fail

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#1573]
## The Problem
A script written for a Rosettacode task works reliably under 2017.11 but fails reliably under 2017.12 and later. 

See cut down script exhibiting behavior at https://gist.github.com/thundergnat/d7059671ff35fbf3aee851ffe0b24639 

Original (full script) at http://rosettacode.org/wiki/Rosetta_Code/List_authors_of_task_descriptions#Perl_6

## Expected Behavior
The script downloads task descriptions and finds the earliest revision for each task, then saves the information to a local JSON file. There are some 1200 or so tasks it checks. 

## Actual Behavior
After checking approximately 200 tasks, it faults with:

Too few positionals passed; expected 2 arguments but got 1
  in method get-proxy at *path/to/filenamehash* (HTTP::UserAgent) line 384 

and a backtrace.  See https://gist.github.com/thundergnat/258663ed12dcae0052e4c49495a41718

Change the compiler to 2017.11 and it runs to completion. Changing the versions of HTTP::UserAgent and/or JSON::Fast (which both also had updates in this time period) doesn't seem to affect it.

## Steps to Reproduce

Run https://gist.github.com/thundergnat/d7059671ff35fbf3aee851ffe0b24639 under Rakudo 2017.12 or later and it will fail after checking a little over 200 tasks. Always over 200, always less than 215.

See irc_logs starting: https://irclog.perlgeek.de/perl6/2018-02-26#i_15861557

AlexDaniel: 	thundergnat: see, I bisected it: https://gist.github.com/Whateverable/5fb5b791011b1d4c80dfed05e797f959
23:58 		thundergnat: so it's bad on f78fd7c17 but good on its parent
23:58 		thundergnat: can you file a ticket please?

## Environment
* Operating system: 
Linux Mint 18.3
* Compiler version (`perl6 -v`): 
works - Rakudo 2017.11
fails - Rakudo 2017.12, 2018.01, 2018.02.1

**Comment by zoffixznet** [comment]
MoarVM commits brought in with that version bump: https://github.com/MoarVM/MoarVM/compare/2017.11-20-gd23f5ca16...2017.11-27-gfac2999

**Comment by AlexDaniel** [comment]
I think it would help if this issue was golfed to a one-liner. Anyway, I added a blocker label because to me it looks like a serious stability issue.

**Comment by dogbert17** [comment]
Setting MVM_SPESH_INLINE_DISABLE=1 seems to resolve the problem.

**Comment by dogbert17** [comment]
Here's a golf attempt. Run with MVM_SPESH_NODELAY=1 and MVM_SPESH_BLOCKING=1

    use HTTP::UserAgent;
    my $client = HTTP::UserAgent.new;
    
    my $url = "http://rosettacode.org/mw/api.php?generator=categorymembers&formatversion=2&gcmtitle=Category%3AProgramming_Tasks&prop=title&action=query&gcmlimit=350&format=json&rawcontinue=";
    loop {
        my $response = $client.get("$url");
    }

**Comment by jnthn** [comment]
It golfs further to this:

```
$ MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 ./perl6-m -e 'class C { multi method m(Int $x) { samewith $x.Str }; multi method m(Str) { }; multi method call() { self.m(42) } }; C.call for ^10000'
```

**Comment by jnthn** [comment]
Fixed in https://github.com/rakudo/rakudo/commit/e12e305a6b and test at https://github.com/perl6/roast/commit/e6b0872ef7.
