### ISSUE TITLE
Assigning NativeCall return value to constant segfaults on calling the sub again

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#1576]
## The Problem
I have a module where I was exposing a set of a library's constants like this:
```perl6
use v6.c;
use NativeCall;
unit class Net::LibIDN2:ver<0.0.1>:auth<github:Kaiepi>;

sub idn2_check_version(Str --> Str) is native('idn2') { * }
method check_version(Str $version --> Str) { idn2_check_version($version) or '' }

constant IDN2_VERSION = idn2_check_version('');
```

## Expected Behavior
`IDN2_VERSION` should be the version of the library installed and calling `Net::LibIDN2.check_version` should return the version as well.

## Actual Behavior
The constant has the correct value, but MoarVM segfaults on calling the method. Removing the constants makes the method work. This doesn't seem to happen with code like this, so I figure `unit class` may be playing into it:
```perl6
use v6.c;
use NativeCall;

sub strlen(Str --> int32) is native('c') { * }

class Foo {
    method strlen(Str $str --> Int) { strlen($str) }
}

constant ZERO = strlen('');

sub MAIN { say Foo.strlen('ayy') }
```

## Steps to Reproduce

Install [Net::LibIDN2](https://github.com/Kaiepi/p6-Net-LibIDN2) and LibIDN2. Revert [this commit](https://github.com/Kaiepi/p6-Net-LibIDN2/commit/ccf588ba6cda85e4c2a33707e2980feef168760b). Call `Net::LibIDN2.check_version`.

## Environment
* Operating system:
OpenBSD morfent.kennel.qt 6.2 GENERIC.MP#5 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.02.1-47-g838782b7d built on MoarVM version 2018.02-22-g25677aeeb
implementing Perl 6.c.

**Comment by zoffixznet** [comment]
> so I figure unit class may be playing into it

IIRC native called routines are loaded on first use. I imagine what's happening is first use occurs during module's precomp and when you call it again after loading the precomped module that first use's loaded routine is missing, hence SEGV.

Golfed repro:

```
$ cat Foo.pm6
use NativeCall;
sub strlen(Str --> int32) is native is export {}
BEGIN strlen ''

$ perl6 -I. -MFoo -e 'strlen ""'
Segmentation fault (core dumped)
```

**Comment by zoffixznet** [comment]
I got a fix, which could use another set of eyes to look over it: https://github.com/rakudo/rakudo/pull/1577
