### ISSUE TITLE
Remove Range.clone-with-op

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1582]
Moved from https://github.com/perl6/doc/issues/1798

I propose we remove the unspecced, [unused](https://gist.github.com/Whateverable/13e744a734bc923629d7e7e749657e73) and, until-recently, undocumented `Range.clone-with-op` method because:

* It's an outlier to language features we offer—the same reasoning offered in the commit implementing it can be used for some other objects, like `DateTime`, yet we don't have `.clone-with-op` for them
* The majority of cases where this method would be useful are already covered by operators `+`, `-`, `/`, and `*` applied to `Range` objects
* The results with the many of the other Callables are bizarre, invalid ranges. If we're going to claim a DIHWIDT for 99% of method's usage, why implement it at all?

```perl6
    .say with ^Inf .clone-with-op: &substr, 1; # OUTPUT: ""..^"nf"
```

It also has two bugs in it:
```
$ perl6 -e 'with (0..Inf).clone-with-op: &[andthen], 42e0 {
      .say; .infinite.say; .pick.say; .elems.say }'
42e0..42e0
True
Nil
Cannot .elems a lazy list
  in block <unit> at -e line 1
```

```
$ perl6 -e '.say with (^Inf but 42).clone-with-op: &[+], 42'
P6opaque: no such attribute '$!is-int' on type Range+{<anon|61966880>} in a Range+{<anon|61966880>} when trying to bind a value
  in block <unit> at -e line 1
```

**Comment by jnthn** [comment]
See my comment at https://github.com/perl6/doc/issues/1798#issuecomment-369992374 (which woulda been better on this ticket, but this ticket didn't exist when I started writing the comment :-)).

**Comment by zoffixznet** [comment]
Tests to cover subclass explosions are in https://github.com/perl6/roast/commit/6607795a412b133e2c2e34fddee0a88bdc47d3c4
