### ISSUE TITLE
tools/install-dist.pl is a perl 6 script but has Prolog file extension

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1583]
See these commits:
* https://github.com/rakudo/rakudo/commit/ade7c4660f46a2b12425de24f66665af809826c2
* https://github.com/rakudo/rakudo/commit/98e575de00db42101d4879e43fe740a34791c418
* https://github.com/rakudo/rakudo/commit/b7df58f25ba47bd404b19005626b6b0058435ec1
* https://github.com/rakudo/rakudo/commit/efd0d6c0516373c1c7a368854b7bc5d43fe463a0

We are now consistently using `.pm6` for modules and `.p6` for scripts, except for [`tools/install-dist.pl`](https://github.com/rakudo/rakudo/blob/efd0d6c0516373c1c7a368854b7bc5d43fe463a0/tools/install-dist.pl) file which is a perl 6 script but confusingly it has a `.pl` extension.

Renaming it is easy, but I'm suspecting that changing it may break some things outside of the rakudo repo. Any ideas on what is affected exactly?

**Comment by niner** [comment]
Distro packages certainly reference the script. E.g. https://build.opensuse.org/package/view_file/devel:languages:perl6/rakudo/rakudo.spec?expand=1 line 50

**Comment by CurtTilmes** [comment]
Alpine distro uses it to install [zef](https://git.alpinelinux.org/cgit/aports/tree/testing/zef/APKBUILD)
but easy enough to update with next release.

**Comment by AlexDaniel** [comment]
@stmuk @robertlemmen @ugexe @nxadm `install-dist.pl` was just renamed to `install-dist.p6` in a PR for https://github.com/rakudo/rakudo/issues/2077 and that went unnoticed by me. Is this affecting you by any chance? I'd say we should leave the rename in there, but what exactly can break and what should we fix now?

**Comment by stmuk** [comment]
@AlexDaniel This shouldn't affect star since I use zef to install itself but I think there are upstream packagers who use it or at least some did ask on IRC about using it (maybe Debian/pkgsrc)?  It means packagers can install modules using base rakudo without zef

A quick search on http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-05#l340 suggests arch maybe use it as well?

Maybe we could revert this change but warn to stderr that the name will change?

**Comment by robertlemmen** [comment]
I think we also rename it during the installation into the package... 

in any case, we will pick up any new name when we pick up a new version. Is .p6 the common extension perl perl 6 though? I see mostly .pl6...

**Comment by AlexDaniel** [comment]
@robertlemmen That was discussed to death in https://github.com/perl6/doc/issues/778. Basically, the situation is that for perl 6 scripts:
* `.p6` is preferred
* `.pl6` is acceptable
* `.pl` is discouraged

**Comment by robertlemmen** [comment]
great!

**Comment by niner** [comment]
This means that I will have to update rakudo's spec file for openSUSE for the next release. Other than that we should be fine as the script is installed as /usr/share/perl6/bin/install-perl6-dist anyway and that is what is used in module .spec files.

**Comment by nxadm** [comment]
> Other extensions mentioned by the docs:
    >Source files generally use the .pm6 extension, and scripts or executables use the .p6. Test files use the .t extension. Files which contain documentation use the .pod6 extension.

The question is: should we have a .t6 extension?

**Comment by AlexDaniel** [comment]
It will be mentioned in the changelog, no alert needed.
