### ISSUE TITLE
NativeCall routine to load an external library without a symbol.

### ISSUE THREAD

**Issue by CurtTilmes** [rakudo/rakudo#1584]
See [NativeCall loading a library symbol I don't call](https://stackoverflow.com/questions/49036300/nativecall-loading-a-library-symbol-i-dont-call), if I call a NativeCall routine that requires another library to be loaded, we need some way to load it.

@jnthn ++ offered this hack that works:

    sub fake is native('library') {}
    try fake;

He noted that the path from Perl 6 down through NQP/MoarVM referenced the library and the symbol to be called, and we speculated that perhaps that path could be extended with an exposed mechanism to load a library without calling a symbol.

**Comment by lizmat** [comment]
This feels more like a problem-solving issue?

If this is still a problem that needs to be solved, perhaps create a new one for this?

In the mean time, closing this one
