### ISSUE TITLE
Easy way to pipe Procs

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1586]
[Proc](https://docs.perl6.org/type/Proc) documentation starts with an example on how to pipe things together:
```perl6
my $p1 = run 'echo', 'Hello, world', :out;
my $p2 = run 'cat', '-n', :in($p1.out), :out;
say $p2.out.get;
```
This is not too bad, but it's much more verbose than [pipelines in Julia](https://docs.julialang.org/en/stable/manual/running-external-programs/#Pipelines-1):
```Julia
run(pipeline(`cut -d: -f3 /etc/passwd`, `sort -n`, `tail -n5`))
```

So [why not](https://irclog.perlgeek.de/perl6/2018-03-03#i_15880673) to have something similar? We don't have a proper alternative to Julia's ``` `` ```, but I guess it does not stop us from having a `pipeline` routine that works on a list of lists?

**Comment by AlexDaniel** [comment]
Yeah, well, this should be moved to Raku/problem-solving, preferably by somebody who cares.

**Comment by FCO** [comment]
Can’t someone just use `shell` and `|`s? Or I got it wrong?

**Comment by niner** [comment]
Using `shell` invites all the problems of using `shell` often resulting in grave security issues.
Julia's pipelines are really nice, indeed. Just not that much nicer that I'd personally be motivated to work on this. Already using a high level language often eliminates the need for me to pipeline external commands. And for the relatively few cases, our existing mechanism is pretty straight forward. I'd much rather steal Julia's backticks as I really feel we left a huge opportunity out, to get things right.

**Comment by AlexDaniel** [comment]
@niner Yeah, it's OK to use the existing mechanism for those who know why that's better. But while I agree with what you say, I'm pretty sure that users will typically gravitate to a shorter alternative. And oh boy do we provide shorter alternatives. One is `qqx`, a feature that is meant to interpolate your variables and just throw the result into the shell. And even if you use `run`, you are provided with `«»` which does “shell quoting”, but no, not the type that [better shells](https://en.wikipedia.org/wiki/Friendly_interactive_shell#Bash/fish_translation_table) use. So it's not only that Raku left a huge opportunity to get things right, it also got things just flat out wrong. But then, I recall you implying that removing features is bad, so I doubt a holistic approach will work here.

On a brighter side, once RakuAST is in full gear, someone will be able to create a Raku critic that will either ban the usage of `«»` and `qqx`, or even be smart enough to detect when you have unquoted variables in `«»` (but will still ban `qqx`, heh).

**Comment by niner** [comment]
To be precise: what's bad is breaking existing code, not removing features per 
se. E.g. I can totally see us removing qqx in 6.e or later code, provided we 
have a real solution instead, but we'd keep it "working" in 6.c code.

This reminds me that I once implemented something rather similar to Julia's 
backticks for SQL strings for a lightning talk. It made `sql"select * from foo 
where foo = $foo"` safe:

```
class SQLValue {
    has $.str;
    method Str() {
        my $quoted = nqp::join("''", nqp::split("'", $.str.Str));
        "'" ~ $quoted ~ "'"
    }
}

multi sub infix:<~> (Str:D $str, SQLValue:D $val) is export {
    $str ~ $val.Str
}

sub prefix:<sql> (&block) is export {
    my $stringy = Str.^find_method("Stringy");
    my $handler = $stringy.wrap(sub ($self) {
        SQLValue.new(:str($self))
    });
    my $result = &block();
    $stringy.unwrap($handler);
    $result
};
```

**Comment by AlexDaniel** [comment]
There's never a talk about removing something in a way that will break it for code that `use`s previous versions.
