### ISSUE TITLE
Signals do not match host system (NativeCall kill issue)

### ISSUE THREAD

**Issue by jstuder-gh** [rakudo/rakudo#1588]
## The Problem

There isn't anything wrong with the idea of platform-independent signal numbers but when mixed with NativeCall the results are Less Than Awesome.

    use NativeCall;
    sub kill(int32, int32) is native {*}

    my $supply = signal(SIGUSR1);
    my $tap = $supply.tap: { say 'sigusr1 here' };
    kill($*PID, SIGUSR1);
    $tap.close;

    # OUTPUT: «Power Failure␤»

On my system (GNU/Linux), signal 30 (SIGUSR1 in MoarVM) is SIGPWR.

Since NativeCall is a heavily-advertised feature and it's usage is encouraged, I think that we should not use platform-independent signal numbers and instead have the Signal enum's values match the host system.

**Comment by jstuder-gh** [comment]
I do have a proposed fix for this although I wanted to run it by the community to see that it was agreed both that the current functionality should change and that this method of fixing it is a good way to go about it.

MoarVM:
<https://github.com/MoarVM/MoarVM/compare/master...jstuder-gh:sig_hash>

NQP:
<https://github.com/perl6/nqp/compare/master...jstuder-gh:sig_hash>

Rakudo:
<https://github.com/rakudo/rakudo/compare/master...jstuder-gh:sig_hash>

This development maps the MoarVM supported signal names to the proper value on the host system. If a signal is not supported on the host, the number is set to zero (kill's null signal; no signal sent).

It also sets a bit-flag indicating the mapped numbers of the MoarVM supported  signals that we can check before setting the signal handler. Finally, it creates an nqp op (getsignals) that exposes the mapped signal numbers to the HLL when called.

On the Rakudo side, the Signal enum is populated with the data retrieved via the nqp::getsignals op. This also allows us to remove the signal mapping code from the file as well, making it easier to read IMO.

The results of issue's example are below. (Note: the Moar code above does not include the output of update_ops which is necessary for it to compile and for the example below to work)

    use NativeCall;
    sub kill(int32, int32) is native {*}
    
    my $supply = signal(SIGUSR1);
    my $tap = $supply.tap: { say 'sigusr1 here' };
    kill($*PID, SIGUSR1);
    $tap.close;

    # OUTPUT: «sigusr1 here␤»

If you think this is a good way to go about it, I could clean things up a bit and submit as a PR to the various repos (as well as run update_ops and commit to complete the op mapping in Moar). I could also implement in JVM and update documentation. Let me know what you think.

**Comment by zoffixznet** [comment]
Related ticket [RT#132012 Numeric values of signals are wrong (say +SIGUSR1)](https://rt.perl.org/Ticket/Display.html?id=132012#ticket-history)

**Comment by jstuder-gh** [comment]
I swear I didn't see that other ticket :P

**Comment by AlexDaniel** [comment]
OK at least there's on less reason to go to RT now :) Closed that other ticket in favor of this one.

**Comment by jstuder-gh** [comment]
I have submitted a few pull requests recently dealing with signals (you can find the links throughout this thread) and when writing the method that returns signal values for the JVM's P6 runtime, I had it return a hash of the signals available on the host even though the JVM itself does not support them. I figured it wouldn't make sense to have JVM return a much more restricted selection of signals especially since the user might just want to use them to signal other processes via NativeCall. At the same time, it would be returning a whole bunch of signals that the JVM would not accept handlers for and trying to do so would cause the P6 runtime to throw an exception.

I want to run this idea by the community to see if you like this way of addressing this issue. We would have two separate ops that the backends would implement:

* The 'getsignals' op (could be renamed to 'gethostsignals' for clarity), that returns a hash indicating what signals are supported by the host system. Values are the signum that represents a given signal on the platform.
* The 'getvmsignals' op, that returns a hash indicating what signals can have signal handlers registered by the backend. Non-zero values indicate that the backend supports a given signal.

The enum populated by 'getsignals' will contain all the signals available on the platform and can be used with the native C kill function to signal other processes. At the same time, when a user submits a signal handler via the 'signal' sub, the 'getvmsignals' hash will be checked, filtering out those that are not supported, and warning the user (Consider [lines 14..23](https://github.com/rakudo/rakudo/compare/master...jstuder-gh:sig_hash_maybe#diff-4612cfdbd572895fd87079e61325cd63R10) for a proposed implementation).

In the case of MoarVM, the 'getsignals' op and 'getvmsignals' op can return the same hash. JVM, however, can return a proper mapping of the signals available on the host for 'getsignals' and a separate 'getvmsignals' hash with only SIGINT and SIGKILL having non-zero values. And this way each backend can set their own supported signals and Rakudo will not need to be aware of any such details prior to runtime.

Does it make sense to have two separate ops like this or can anyone think of a better way?

**Comment by niner** [comment]
How about keeping it as one op but negating unsupported signal values. So JVM would return: `{SIGHUP => -1, SIGINT => 2, SIGQUIT => -3, ...}`
After all you only need to convey a single bit more of information. It would actually be easier to filter supported/unsupported signal values from this list.

**Comment by jstuder-gh** [comment]
I like that suggestion. You're right, two ops would be overkill when we have a whole all those negative values being unused.

**Comment by jstuder-gh** [comment]
@AlexDaniel, sorry for the delay in answering back. I believe the issue is addressed although there are a few QOL changes / tweaks that can still be made (I have PRs [here](https://github.com/MoarVM/MoarVM/pull/870), [here](https://github.com/perl6/nqp/pull/457), and [here](https://github.com/rakudo/rakudo/pull/1897) that add a consistent ordering back to the Signals, something that went away because we are now retrieving the entries from a hash).

I'm not quite sure what to do in regards to new tests though. Should they be Roast tests or Rakudo tests? Should we have tests that explicitly check the signal values we retrieve (one for each host platform and backend) or is that overkill? What do you think?

**Comment by AlexDaniel** [comment]
@jstuder-gh these should be roast tests. `+SIGKILL` should return the same number regardless of the implementation, as long as it is on the same platform, it is safe to spec that. I'm not sure how would you get the values to test against, but I assume you have some idea? :)

**Comment by lizmat** [comment]
Is this still an issue?  Or does #1960 cover this?  Closing now, please re-open if you think this is wrong.
