### ISSUE TITLE
Procs should not get back with “exit code: 1” if the program does not exist at all

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1590]
Code:
```perl6
run ‘oeunohunteohuntoahuonathu’
```
Result (`92bd7e4f54a^`):
```
The spawned command 'oeunohunteohuntoahuonathu' exited unsuccessfully (exit code: -1)
  in block <unit> at /tmp/ARHjknJLZK line 1
```

Result (92bd7e4f54a):
```
The spawned command 'oeunohunteohuntoahuonathu' exited unsuccessfully (exit code: 1)
in block <unit> at /tmp/ARHjknJLZK line 1
```

Bisected to: (2017-06-12) https://github.com/rakudo/rakudo/commit/92bd7e4f54a92fa660f99b4d056d33a08fb98bd2
Output on all releases: https://gist.github.com/aa42b6eb50f114c31e4c070a59b26a53

I don't think that exit code `-1` is very meaningful, but at least it was possible to figure out that the program does not exist at all. Now it's indistinguishable from the actual program exiting with 1.

FWIW the `.signal` in this case is now 0 but previously it was `254`.

Context:
* Here's me trying to work around the issue: https://github.com/perl6/whateverable/commit/a401e1da8d
* And here's me asking for help, and then realizing it's a regression (an old one, but still): https://irclog.perlgeek.de/perl6/2018-03-05#i_15884805

**Comment by AlexDaniel** [comment]
For anyone reading by email: the link to the bisect result was wrong. Fixed now.

**Comment by CIAvash** [comment]
Just wanted to mention that `Proc::Async` dies with an exception in this case.

```raku
await Proc::Async.new('abcd').start
```
```
An operation first awaited:
  in block <unit> at <unknown file> line 1

Died with the exception:
    Failed to spawn process abcd: no such file or directory (error code -2)
```

Depending on how you invoke the process, you get different exception names: e.g, `X::OS+{X::Await::Died}`, `X::OS+{X::React::Died}`.
```
X::OS+{X::Await::Died}.new(await-backtrace => Backtrace.new, os-error => "Failed to spawn process abcd: no such file or directory (error code -2)")
```

**Comment by ab5tract** [comment]
With this [roast test @ 3805504](https://github.com/Raku/roast/commit/3805504e59), this can be considered completed.
