### ISSUE TITLE
LTAnesses with Range.rand

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1591]
Just spotted some rough edges with `Range.rand` on 2018.01:

1. `NaN` is technically "numeric":

```
$ perl6 -e 'say NaN ~~ Numeric; .rand with NaN..NaN'
True
Can only get a random value from numeric values
```
2. A "positive range"? Unclear. My end points *are* positive.

```
$ perl6 -e 'say .rand with 1..0'
Can only get a random value if the range is positive
  in block <unit> at -e line 1

$ perl6 -e 'say .rand with 1^..^1'
Can only get a random value if the range is positive
  in block <unit> at -e line 1
```

3. If you give it a Rat/FatRat Range with endpoints that have with too much precision, it's possible to get a hang, as the implementation contains an infinite loop that re-rands the value if it matches the exclusion point. Perhaps another error-condition check should be implemented where the range is first converted into a `.min.Num .. .max.Num` before performing the "positive range" check seen in (2) above.

```
$ perl6 -e 'say .rand == .max with 1^..^1.000000000000001'
False

$ perl6 -e 'say .rand == .max with 1^..^1.0000000000000001'
*hangs*
```

**Comment by ab5tract** [comment]
Closed as of 06e45d8
