### ISSUE TITLE
LTA (elem) doesn't special case Range

### ISSUE THREAD

**Issue by LLFourn** [rakudo/rakudo#1593]
```perl6
constant \𝒑 = 0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB9ED529077096966D670C354E4ABC9804F1746C08CA237327FFFFFFFFFFFFFFFF;

constant \ℤ𝒑 = 1..𝒑;

say 42 ∈ ℤ𝒑 # hangs forever
```
Obviously 42 is an element of the range, and you can just do `42 ~~ ℤ𝒑` instead but I think it should DWIM.

**Comment by lizmat** [comment]
I cannot reproduce.  Which version of Rakudo are you using?

**Comment by LLFourn** [comment]
Sorry!
Never golf without testing 😩🔨.

```perl6
constant \𝒑 = 0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB9ED529077096966D670C354E4ABC9804F1746C08CA237327FFFFFFFFFFFFFFFF;

constant \ℤ𝒑 = 1..𝒑;

say (𝒑 - 1) ∈ ℤ𝒑 # hangs forever
```

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/de30c16218 should fix this.

Tests needed

**Comment by LLFourn** [comment]
I wrote a test for the specific case of a large Int. But I noticed there are still a few related issues 

```
perl6 -e 'my $a = 10 ** 42; say ( $a - 0.1) ~~ ^$a' # works
my $a = 10 ** 42; say ( $a - 0.1) (elem) ^$a # hangs
```
```
perl6 -e 'say ( 10 ** 42) ~~ ^Inf' # fine
perl6 -e 'say ( 10 ** 42) (elem) ^Inf' # Cannot (elem) a lazy list
```
```
perl6 -e 'say ("x" x 23) ~~ ("a") .. ("z" x 42)' 
say ("x" x 23) (elem) ("a") .. ("z" x 42)
```

@lizmat Can't we just always delegate to Range.ACCEPTS (not only when is-int)?

**Comment by zoffixznet** [comment]
> Can't we just always delegate to Range.ACCEPTS (not only when is-int)?

No, `.ACCEPTS` checks if value is *within* the range, `(elem)` checks if the value is *an element* of the range:

```
<Zoffix_> m: say 1.5 ~~ 1..2
<camelia> rakudo-moar 3259953e5: OUTPUT: «True␤»
<Zoffix_> m: say 1.5 (elem) 1..2
<camelia> rakudo-moar 3259953e5: OUTPUT: «False␤»
<Zoffix_> m: say eager 1..2
<camelia> rakudo-moar 3259953e5: OUTPUT: «(1 2)␤»
```

Some common cases could be made faster ([RT#130437](https://rt.perl.org/Ticket/Display.html?id=130437#ticket-history), but there are a lot of questionable edge-cases that complicate things.

* Is `2e99` an element of range `2e89..2e100`? You might say "yes", but if you actually reify that range, you'll find, that's an infinite range, with all elements being `2e89` (not enough available precision to ever increase it)
* Is `"\0"` an element of range `"\0" .. "\0\0"`? If you reify, you'll find that's an infinite range, with all elements being `"\0"`

I forget the codepoint now, but there's also an infinite looping range, where thanks to normalization a higher codepoint gets normalized to a lower one, so reifying keeps looping in a space of the range.

**Comment by lizmat** [comment]
What Zoffix said  :-)

**Comment by LLFourn** [comment]
Understood and agreed. In other words, `(elem)` must give the same answer as if `.Set` was called on the range first. Any bounds based optimisations must follow that rule.
