### ISSUE TITLE
Consider not recommending RT

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1598]
Previous ticket: [RT #128520](https://rt.perl.org/Ticket/Display.html?id=128520)

Comment from that ticket:

> Maybe the ticket ([RT #128520](https://rt.perl.org/Ticket/Display.html?id=128520)) should be closed if/when the RT bug tracker is closed to new tickets itself and references to RT removed from all docs?

For example, we still don't even mention github on http://rakudo.org/tickets/.

According to [reportable](https://gist.github.com/Whateverable/4231f0f6267661be8df633fd1b4adede), in the first two months of 2018 only 8.6% of new tickets were created on RT (21 out of 243 total).

FWIW, currently RT gets more spam tickets that we have to delete than actual bug reports. I can totally see how we can reason a total block for new tickets there, but IMO we should not be so eager to do that just yet. RT still has a nice feature that allows you to submit bug reports via email (without having to create an account anywhere). GitHub, as far as I know, does not have that feature.

So let's just remove all text that says that you should submit bugs on RT, and replace it with a recommendation to submit bugs on github instead?

<br><br>
Things that have to be tweaked:

**⚠ Feel free to edit this list**
- [ ] http://rakudo.org/tickets/
- [ ] https://github.com/rakudo/rakudo/blob/master/README.md#reporting-bugs
- [ ] … more?

**Comment by zoffixznet** [comment]
👍 

> For example, we still don't even mention github on http://rakudo.org/tickets/.

That will be changed on new version of the site. [No one objected when I said that was outdated content](https://irclog.perlgeek.de/perl6/2018-03-07#i_15895687)

> FWIW, currently RT gets more spam tickets that we have to delete than actual bug reports

There's also a new message that says BitCard is going away and users must switch to a new system and must still use their old email address in the new system. This complicates the already pained and previously-problematic user accounts process:

![z](https://user-images.githubusercontent.com/5747918/37154467-22bb3b04-22ae-11e8-88b5-255e1caaf612.png)
