### ISSUE TITLE
Wrong output of in CArray.^shortname

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1606]
```
<Zoffix__> m: use NativeCall; say CArray[Pointer[int32]]
<camelia> rakudo-moar 26522e8ac: OUTPUT: «(CArray[Pointer)␤»
```

Needs a fix in this code somewhere: https://github.com/rakudo/rakudo/blob/26522e8acd096412325f6c667c823c675f2fbae6/src/Perl6/Metamodel/Naming.nqp#L5-L24

**Comment by zoffixznet** [comment]
Here's a possible test to cover this bug:

```perl6
use Test; 
role Foo::Bar::Ber[\T] {}
my Foo::Bar::Ber[Foo::Bar::Ber[int32]] %h{Foo::Bar::Ber[int32]};
is-deeply %h.^shortname, 'Hash[Ber[Ber[int32]],Ber[int32]]
```

@Kaiepi ++ is looking into this ticket.

**Comment by Kaiepi** [comment]
At the moment Rakudo deals with names like `Foo::Bar::Ber` by using the first part as the name, not the last. Is this intended? Should it be using the last instead?

**Comment by zoffixznet** [comment]
Using it where?

Shortname uses the last portion, as far as I can see:
```
<Zoffix__> m: class Foo::Bar::Ber {}; say Foo::Bar::Ber
<camelia> rakudo-moar 2a3947816: OUTPUT: «(Ber)␤»
```

**Comment by Kaiepi** [comment]
My mistake, I was misreading which roles I was using in some tests I'm writing

**Comment by Kaiepi** [comment]
I wrote up some tests for this for Roast. Should I add some for Rakudo's suite as well? Where in `t/` would they go?

**Comment by zoffixznet** [comment]
> Should I add some for Rakudo's suite as well?

No, if there's a test covering the bug in roast, nothing needs to be in rakudo's test suite.
