### ISSUE TITLE
Missing deconts in xx

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1607]
See this commit: https://github.com/rakudo/rakudo/commit/5b7b7fb5c942a3e74097b5eb94a22be262f74c9f

Two things:

- [ ] “Note that the fix is in the &x candidate, *not* in the Mu \x candidate. This needs further research and fixing.”

- [ ] “Note that xx should really always return a Seq anyway, so that is another thing that would need to get fixed.”

Note that this is a continuation of [RT #130941](https://rt.perl.org/Ticket/Display.html?id=130941).

**Comment by AlexDaniel** [comment]
On the first glance the second part was resolved in this commit: https://github.com/rakudo/rakudo/commit/1eb7b1f796214870b53c7ed055907cb29076dc78

**Comment by AlexDaniel** [comment]
Some discussion here: [RT #126014](https://rt.perl.org/Ticket/Display.html?id=126014)

**Comment by lizmat** [comment]
I'm not sure about the "Note that xx should really always return a Seq anyway, so that is another thing that would need to get fixed".  Why would that need to be the case?  I seem to missing something.

**Comment by lizmat** [comment]
Closing as this appears to have been fixed
