### ISSUE TITLE
[JVM] a nqp::null bound to an attribute gets hllized

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#1613]
[This was discovered in https://rt.perl.org/Ticket/Display.html?id=130532, but since that ticket is about (formerly) failing tests with infix:<Z>, I'm filing this rakudo issue and will close the RT ticket.]

On JVM a nqp::null bound to an attribute gets hllized, while it stays nqp::null on MoarVM:

```
<bartolin> r: use nqp; class A { has Mu $!foo; method foo () { $!foo := nqp::null; say nqp::isnull($!foo) ?? "null" !! $!foo } }.new.foo
<camelia> rakudo-jvm a92950fb4: OUTPUT: «(Mu)␤»
<camelia> ..rakudo-moar 71012beb5: OUTPUT: «null␤»
``` 

I think this is the reason why we need special cases for JVM like this one: https://github.com/rakudo/rakudo/blob/71012beb59bbecf27ff865def3f6117af6b1c478/src/core/Rakudo/Iterator.pm6#L887-L892

**Comment by usev6** [comment]
BTW, this might also be related to https://github.com/rakudo/rakudo/issues/1572.

**Comment by usev6** [comment]
Another note from https://rt.perl.org/Ticket/Display.html?id=130532:

**Comment by peschwa** [comment]
This is probably related to RT#128320 aslnd the discussion here (
https://irclog.perlgeek.de/perl6-dev/2016-10-25#i_13463752). In short,
seeing as we still run into lealing JVM-Level nulls we probably really
should build a sentinel value that represents a nqp-level null in a way
that doesn't make the JVM throw.

The basic idea I tried almost 2.5 years ago was a singleton returned from
Ops.null() and available in Ops.isnull. Back then bootstrappong foiled my
plans, and I don't really have time cirrently, HTH.

**Comment by usev6** [comment]
I've looked again, and I'm pretty sure the null gets lost when calling getattr. The autovivify machinery starts if we find a null here: https://github.com/perl6/nqp/blob/5fb8113c24/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/P6Opaque.java#L445

I don't see any other clean way of solving that, than going for a VMNull.

**Comment by usev6** [comment]
The original code works now as expected (after merging https://github.com/perl6/nqp/pull/605):
```
$ ./rakudo-j -e 'use nqp; class A { has Mu $!foo; method foo () { $!foo := nqp::null; say nqp::isnull($!foo) ?? "null" !! $!foo } }.new.foo'
null
```
