### ISSUE TITLE
.open with :truncate/:create violates "read only" default open mode

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1614]
There ~~are~~ [were](https://github.com/perl6/roast/commit/24822cf173cfbdbf859efd4121ccebad9a70a5a3) some proptests in S32-io/open.t that test `:truncate` and `:create` by their lonesome don't throw. But since the default open mode is "read-only", it doesn't make much sense to me that something opened only for reading would be created and especially truncated.

The throwage actually does occur on JVM:

```
$ ./perl6-j -e '"/tmp/zdsdsdsxczxsdzdasdsadsds".IO.open: :truncate, :create;'
java.nio.file.NoSuchFileException: /tmp/zdsdsdsxczxsdzdasdsadsds
  in block <unit> at -e line 1

Actually thrown at:
  in block <unit> at -e line 1
```

And apparently on MoarVM too sometimes: https://irclog.perlgeek.de/perl6-dev/2018-03-12#i_15913886

But on my Bodhi Linux box, it just silently creates/truncates:

```
$ perl6 -e '"/tmp/zdsdsdsxczxsdzdasdsadsds".IO.open: :truncate, :create;'                                                                                                                                    
$ ls /tmp/zdsdsdsxczxsdzdasdsadsds
/tmp/zdsdsdsxczxsdzdasdsadsds
```

Also, depsite JVM refusing to work with non-existant file, it silently fails to :truncate, if the file already exists:
```
$ cat /tmp/foo
abc
2018.02.1 zoffix@VirtualBox~/CPANPRC/judo (master)$ ./perl6-j -e '"/tmp/foo".IO.open: :truncate, :create;'
2018.02.1 zoffix@VirtualBox~/CPANPRC/judo (master)$ cat /tmp/foo
```

-----

So we need to give a closer look at the modes and consistify their behaviour.

-----

Some discussion on IRC: https://irclog.perlgeek.de/perl6-dev/2018-03-12#i_15913886

**Comment by usev6** [comment]
I wonder if it might be enough to just leave combinations like (:r, :create) or (:r, :truncate) unspecced and document them as being unsupported. (In fact, that's what the documentation says currently: https://docs.perl6.org/routine/open#class_IO%3A%3AHandle.)

Since open accepts a lot of named parameters I'm afraid it becomes even more complicated by adding (different?, typed?) Exceptions. For example, the docs say that specifying both a defined encoding :$enc and setting :$bin to true will cause X::IO::BinaryAndEncoding exception to be thrown. Is that still true, if I use (:r, :create) or do I get a different exception then?

**Comment by Kaiepi** [comment]
I think `open` should try to function as similarly to LibC `open` as much as possible, but that can cause problems for people deciding to use it in a way that won't work cross-platform. Even though the additional exceptions make using it more complex, I feel like it would simplify debugging those types of problems when they arise. Maybe using different types of exceptions where `die` is currently used in the function will help make it easier to work out why it throws

**Comment by zoffixznet** [comment]
> I wonder if it might be enough to just leave combinations like (:r, :create) or (:r, :truncate) unspecced

👍 if only just 'cause .open is already ridiculously complex. If both path and args are given to the method dynamically, currently the method can:

- Return an opened handle
- `fail` with an exception if opening failed
- `throw` an exception if bin and enc are both set
- `throw` an exception if path is `"-"` and mode is not `wo` or `ro`

> Maybe using different types of exceptions where die is currently used in the function will help make it easier to work out why it throws

But what's thrown for `open "-", :mode<rw>, :bin, :enc<utf-8>, :create, :truncate`? Possibilities are:

- throw `X::IO::CannotOpenSTDInMode` (made up name)
- throw `X::IO::BinaryAndEncoding`
- throw `X::IO::CreateTruncateReadOnly`  (made up name)

Three different exceptions, depending on how argument checking is implemented.

**Comment by zoffixznet** [comment]
> Three different exceptions, depending on how argument checking is implemented.

OTOH, `X::IO::BinaryAndEncoding` thowage is still a 6.d-proposal. It can easily become `X::IO::OpenWrongArgs` for all three cases.

**Comment by Kaiepi** [comment]
I think having the three different exceptions would be more descriptive, especially since `X::IO::BinaryAndEncoding` is used outside `open`, where it wouldn't make much sense for `X::IO::OpenWrongArgs` to be thrown

**Comment by zoffixznet** [comment]
> would be more descriptive

That's true, but then we get the point bartolin mentioned that that creates a number of ambiguous argument permutations that—despite increasing documentation/implementation weight—we'd still have to either leave unspecced or spec very tightly, potentially creating problems with other implementations, depending on how they decided to check the args.

Given we already have large differences between JVM and MoarVM in this area and the docs for `.open` are already overly-complex, I rather we err on the side of ambiguity here and leave this area as implementation-dependent behaviour.

I rewrote/expanded all the open modes proptests in https://github.com/perl6/roast/commit/37aa7c3d7f to match the combinations of open modes the docs list as approved. IIRC the combinations in the docs were written out during the IO Grant and it was decided to leave the rest implementation-defined, but that never made it as an active decision into the spec.
