### ISSUE TITLE
Promise.anyof(Promise.in(0), <Something Promise>) doesn't work if a member returns the result under 0.01s

### ISSUE THREAD

**Issue by titsuki** [rakudo/rakudo#1621]
## The Problem

See:
```
my $p = start { sleep 0.01; 10 }; await Promise.anyof(Promise.in(0),$p); $p.status.say;
Kept
```

`$p` is the Promise that returns the result in 0.01s.
In this case, I think `$p.status` should return `Planned` because `$p` couldn't return the result in 0s.
However, it returns `Kept`.

## Expected Behavior

`$p.status` returns `Planned`.

## Actual Behavior

`$p.status` returns `Kept`.

## Steps to Reproduce

It works as expected (sleep 0.1):
```
$ perl6 -e 'my $p = start { sleep 0.1; 10 }; await Promise.anyof(Promise.in(0),$p); $p.status.say;'
Planned
```

This issue happens (sleep 0.01):
```
$ perl6 -e 'my $p = start { sleep 0.01; 10 }; await Promise.anyof(Promise.in(0),$p); $p.status.say;'
Kept
```

## Environment
* Operating system: Debian Stretch
* Compiler version (`perl6 -v`): 
```
$ perl6 -v
This is Rakudo version 2018.02.1-172-g34889bebc built on MoarVM version 2018.02-171-geee5be412
implementing Perl 6.c.
```

**Comment by titsuki** [comment]
Sorry, I misunderstood the behavior.
I thought `Promise.anyof` stops the status of the members other than the first finished one; but it was the incorrect idea:
```
$ perl6 -e 'my $p = start {sleep 1; 1}; await Promise.anyof(Promise.in(0),$p); sleep 3; $p.status.say;'
Kept
```

**Comment by jnthn** [comment]
Correct, there's no implicit cancellation.
