### ISSUE TITLE
Weirdness on negative char class “[ ]”

### ISSUE THREAD

**Issue by llelf** [rakudo/rakudo#1622]
```
> use SomeBigGrammar
Iteration past end of iterator
```

After WTFing for some time, I found the culprit: `/<:SomeClass-[ ]>/`.
Even smaller test cases:
```
> /<-[ ]>/
Iteration past end of iterator

> /<-[]>/
Iteration past end of iterator
```

<details><summary>perl6 -v</summary>

This is Rakudo version 2018.02.1-137-g65874b1555 built on MoarVM version 2018.02-35-g1fca17994
implementing Perl 6.c.
</details>

**Comment by zoffixznet** [comment]
Originally reported on https://rt.perl.org/Ticket/Display.html?id=130586#ticket-history that has some additional info and responses from jnthn

**Comment by AlexDaniel** [comment]
OK, but new comments here please. Closing #130586 in favor of this ticket.

**Comment by jstuder-gh** [comment]
I've submitted a PR for NQP that address the issue at <https://github.com/perl6/nqp/pull/432>.
I will submit tests for the roast either tomorrow or over the weekend.

I attempted to have it return a helpful error about empty character classes as jnthn suggested in the RT thread ([like so](https://github.com/jstuder-gh/nqp/commit/7c41dfa72a4e7b4f21e148b990d3b11e382e6f0e)), but then NQP wouldn't compile without throwing that error, so I removed it from the branch.

**Comment by jstuder-gh** [comment]
I've merged in the panic-less fix for this issue into the NQP repo. Still need to add tests to the roast.

**Comment by jstuder-gh** [comment]
Still need to create separate panic PR as per discussion at <https://github.com/perl6/nqp/pull/432>

**Comment by AlexDaniel** [comment]
Tests added in https://github.com/perl6/roast/pull/411, @jstuder-gh++.

**Comment by AlexDaniel** [comment]
Oh wait, where's the separate panic PR?

**Comment by AlexDaniel** [comment]
Thanks.
