### ISSUE TITLE
Phasers FIRST/LAST in sub-loop doesn't compile: Cannot reference undeclared local 'LOOP_BLOCK_1'

### ISSUE THREAD

**Issue by relonger** [rakudo/rakudo#1623]
## The Problem

```perl6
sub f {
   my $i = 0;
   loop {
      FIRST { say "FIRST: $i"};
      LAST { say "LAST: $i"};
      last if ++$i > 100;
   }
}

f()
```
Can't compile at all! Compiler error 
```
Cannot reference undeclared local 'LOOP_BLOCK_1'
```

BUT if you move this code in the source root (without sub f()) everything works:
```perl6
my $i = 0;
loop {
   FIRST { say "FIRST: $i"};
   LAST { say "LAST: $i"};
   last if ++$i > 100;
}
```

```
FIRST: 0
LAST: 101
```

```
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.

Darwin WanMini.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

**Comment by lizmat** [comment]
Further golf:

my $i = 0;
sub {
   loop {
      FIRST $i;
      LAST  $i;
   }
}

Notes:

1. Both phasers must be present, if only one them is, then there is no compilation error
2. The variable does not need to live inside the scope of the sub
3. The scope *must* be a sub (or a method), if it is just a block: no compilation erro
4. —optimize=0 does not make the problem go away

**Comment by zoffixznet** [comment]
Thank you for the report. This is now fixed.

Fix:  https://github.com/rakudo/rakudo/commit/879b33405eca2d6
Test: https://github.com/perl6/roast/commit/dab963752cf8ea3a6

This particular case actually currently gens `Seq.from-loop` as if the loop was wanted. That issue still remains and I opened it as separate Issue: https://github.com/rakudo/rakudo/issues/1698
