### ISSUE TITLE
.unival of characters beyond 0x10FFFF is 0 but should be NaN

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1625]
Max unicode character currently is 0x10FFFF, but we still allow to create strings with characters beyond 0x10FFFF. However, .unival gives a wrong value:

```perl6
say (0x7FFFFFFF).chr.unival; # OUTPUT: «0␤»
```

Normally weird stuff gets NaN:
```perl6
say (0.chr.unival);          # OUTPUT: «NaN␤»
```

**Comment by dogbert17** [comment]
Behavior has now changed to :

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-82-gb30fa3a71.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.
    dogbert@dogbert-VirtualBox:~$ perl6 -e 'say (0x7FFFFFFF).chr.unival'
    chr codepoint 2147483647 (0x7FFFFFFF) is out of bounds in block <unit> at -e line 1

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/bc9a96e11a, so closing
