### ISSUE TITLE
Missing bits for .pm → .pm6 rename

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1627]
After these commits:
* https://github.com/rakudo/rakudo/commit/98e575de00db42101d4879e43fe740a34791c418
* https://github.com/rakudo/rakudo/commit/b7df58f25ba47bd404b19005626b6b0058435ec1
* https://github.com/rakudo/rakudo/commit/efd0d6c0516373c1c7a368854b7bc5d43fe463a0

All `.pm` files are gone, and now we use `.pm6` instead. However, if you grep for ``\.pm[^6]`` you will see that there are still some references to `.pm` files.

**Comment by lizmat** [comment]
Fixed with cecaacb520312cf103144  , can be closed
