### ISSUE TITLE
Do we need an API method "SLICE", as extension to AT-POS?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1639]
Sometimes I feel the absence of a SLICE method, essentially doing:

    method SLICE(@pos) {
        my @values;
        @values.push(self.AT-POS($_)) for @pos;
        @values
    }

Making this part of the internal API, would allow for several optimizations, e.g. when working on fully reified lists / arrays and given a Range.

**Comment by smls** [comment]
Would this only be called when `postcircumfix [ ]` is used *without* adverbs?

**Comment by lizmat** [comment]
Yes, that is my intent

**Comment by raiph** [comment]
Hi @lizmat,

I'm guessing the last comment ("[lizmat](https://github.com/lizmat) closed this as [completed](https://github.com/rakudo/rakudo/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [last week](https://github.com/rakudo/rakudo/issues/1639#event-14493333233)") is just some automation by GH that's unhelpful in this case (and some prior ones I've seen), and nothing to do with anything you intended and/or have any control over whatsoever, but in case there is something useful you can do _and_ you _also_ think it's worth bothering to try fix it, I have found the completed links unhelpful (as in, when I click on them, I've no idea why the link was generated).
