### ISSUE TITLE
Very simple spesh-related segfault

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1645]
Code:
```perl6
sub f { 4 ?? 8 !! 15 }; f for ^1000000
```
Result:
```
Segmentation fault
```

Output on all releases: https://gist.github.com/2ec512e2fc7fa27a735626ac03ae43b4

Bisectable points at (2018-02-16) https://github.com/rakudo/rakudo/commit/beaad7b979f99d07f546efa0d48b701e6372d9ae

Maybe it's https://github.com/MoarVM/MoarVM/commit/c7774e37d or something related to it?

**Comment by lizmat** [comment]
FWIW, the nqp version also segfaults:

    use nqp; sub func { nqp::if(1,10,5) }; func() for ^1000000

**Comment by niner** [comment]
I've got a patch. Running tests now.

**Comment by lizmat** [comment]
Also, the first value to segv is: `^13142`

    use nqp; sub func { nqp::if(1,10,5) }; func() for ^13142

It doesn't segfault for `^13141`

**Comment by niner** [comment]
Fixed in MoarVM commit 67056c20416a3629828340d09b916dd7f5b6c5bc

**Comment by AlexDaniel** [comment]
@niner I think there's something wrong. At the very least it is failing on windows: https://ci.appveyor.com/project/rakudo/rakudo/build/1.0.1537/job/356otftki3e98u50#L871

**Comment by AlexDaniel** [comment]
Should be better now after https://github.com/MoarVM/MoarVM/commit/b5b69681f62bd61e7dfd71ca9ef134c3dbccaa90, but I haven't tested yet.

**Comment by AlexDaniel** [comment]
This is indeed fixed now. Tests needed.
