### ISSUE TITLE
Travis needs oracle-java8-installer even when building for moar only

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1646]
See this failure: https://travis-ci.org/rakudo/rakudo/jobs/357788457#L571

Basically, the CI status was red for several commits in a row because:
```
Connecting to download.oracle.com (download.oracle.com)|23.52.164.194|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
```

Can we tweak it so that `oracle-java8-installer` is only installed when we're building for moar backend?

**Comment by AlexDaniel** [comment]
FWIW I understand that it is using the same configuration for all of the runs, but I'd be pissed if something like this was happening during the release. I'd much rather take an ugly workaround than keep it the way it is.

**Comment by ugexe** [comment]
It can easily be modified to use a conditional that checks a variable from the matrix, although it would be ugly. I'd be concerned if something this minor was enough to piss anyone off though -- gcc could fail just as well when an alternative compiler/version could be used instead.

**Comment by AlexDaniel** [comment]
> gcc could fail just as well when an alternative compiler/version could be used instead

GCC and everything else is installed from the repo, and oracle-java8-installer too, but it pulls data from a 3rd party source that is demonstrated to be unreliable.

**Comment by ugexe** [comment]
Something like this should work:
`'if [[ $RAKUDO_OPTIONS =~ "jvm" ]]; then apt-get install oracle-java8-installer; fi'`

**Comment by AlexDaniel** [comment]
@ugexe that's right! Thank you.
