### ISSUE TITLE
Sometime hyper does not hyper

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1656]
Code:
```perl6
sub foo() { sleep 1; take 42; take 50 };
say <a b c>.hyper(:1batch, :4degree).map({(gather foo).list});
say now - BEGIN now
```

Result:
```
((42 50) (42 50) (42 50))
3.049271
```

The result is correct, but it took 3 seconds to get there which means that it was doing it sequentially. I expected it to start 3 threads and finish in 1 second.

Rakudo version: 2017.10⌁2018.03

**Comment by jnthn** [comment]
The `gather` is lazy, `.list` doesn't force an eager evaluation. Thus the hyper'd `map`s return immediately three lazy lists, and `say` calls `.gist` which then evaluates them. Switch the `.list` for a `.eager`, and:

```
$ perl6 your-code.p6
((42 50) (42 50) (42 50))
1.0990797
```

**Comment by AlexDaniel** [comment]
Oh! I see. Hm. I think it's a doc issue then… maybe.

But also, I guess I was thinking about ``.List``, but that doesn't give a List also? Why not?

**Comment by AlexDaniel** [comment]
I mean, it does, but it still takes 3 seconds. Something is lazy in there, even though .is-lazy is False. Maybe I should just get some sleep…

**Comment by jnthn** [comment]
Neither `.list` nor `.List` will try to make a lazy thing eager; they both result in a lazy `List`.

**Comment by jnthn** [comment]
Hm, I think perhaps you're right about the `is-lazy` not being so truthful as would be nice.

**Comment by AlexDaniel** [comment]
FWIW at some point I attempted to create a table for `is-lazy`, but I don't think it's relevant anymore (and it's definitely not as full as it should be): https://github.com/rakudo/rakudo/wiki/is-lazy
