### ISSUE TITLE
[JVM] Native arrays are miscompiled in core settings

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#1666]
For some reasons its not possible to use native arrays when starting the supervisor thread (src/core/ThreadPoolScheduler.pm6) on the JVM backend.

Trying to create a native num array with ```my num @last-utils``` came out as a VMArrayInstance instead of VMArrayInstance_n. This problem already lead to the following workaround: https://github.com/rakudo/rakudo/commit/581edd58e9

I'm filing this issue, since another workaround is needed for using nqp::getrusage in src/core/ThreadPoolScheduler.pm6 and I want to reference a bug report.

**Comment by usev6** [comment]
As I found out in https://github.com/rakudo/rakudo/pull/4295 it seems to be possible to use native arrays if they are declared with
```
my @last-utils := array[num].new;
```
instead of
```
my num @last-util;
```

The latter form should work, too (so I won't close this issue), but it's good to have a workaround.

**Comment by usev6** [comment]
The same problem happens with precompilation. (It popped up in https://github.com/rakudo/rakudo/issues/4354.)

So this blows up:
```
$ cat lib/Foo.rakumod
use nqp;                                                                                                                                                                                                                                       
#no precompilation;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                               
class Foo {                                                                                                                                                                                                                                    
    method foo() {                                                                                                                                                                                                                             
        #my @data := array[int].new;                                                                                                                                                                                                           
        my int @data;                                                                                                                                                                                                                          
        nqp::bindpos_i(@data,0,42);                                                                                                                                                                                                            
        @data;                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                          
}
$ ./rakudo-j -Ilib -e 'use Foo; dd Foo.new.foo'
VMArray representation does not implement bind_pos_native
  in method foo at /path/to/rakudo.jvm/../rakudo.jvm/lib/Foo.rakumod (Foo) line 8
  in block <unit> at -e line 1
```

The code works with either ```no precompilation``` or ```my @data := array[int].new``` (instead of ```my int @data```).

**Comment by niner** [comment]
> The same problem happens with precompilation. (It popped up in
> https://github.com/rakudo/rakudo/issues/4354.)

In that case I'd say the problem _is_ precompilation. That's probably, why it 
affects the setting: because that's always precomiled.

**Comment by usev6** [comment]
I think I understand where things go wrong. All arrays (non-native and native) have the same REPR (```VMArray```). They differ in native arrays having a non-null REPRData in their STable.

When an array is serialized, a string representing the REPR is put into the string heap.

During the first pass of deserialization, this string is used to create a stub object (of the given REPR).

At this moment the REPRData is not yet known -- so a plain (non-native) VMArray is created (in [deserialize_stub](https://github.com/Raku/nqp/blob/3ff1af5daa/src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMArray.java#L91)).

Only during the second pass of deserialization, the REPRData is added to the STable (in [deserialize_repr_data](https://github.com/Raku/nqp/blob/3ff1af5daa/src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMArray.java#L210-L216).)

But that's too late to change the object.

**Comment by usev6** [comment]
If I'm not mistaken the native array is deserialized twice during the compilation of ```blib/CORE.d.setting.jar```.

So the problem was, that I did reset ```REPR.name``` to ```VMArray``` at https://github.com/Raku/nqp/commit/f3dc9779068df5a8b049974399edf129cc0f3013#diff-8a338b0030902eb3d512c10c0f1777948bb8a9017a3e320d2e080d9f9f32a324R127

Maybe it's quite fine to keep the special names (```VMArray_i```, ```VMArray_u32```, etc.). After all, it's just a name. I double checked and it seems to be used only for serialization and for error reporting in the base classes ```SixModelObject``` and ```REPR```.

On the other it feels wrong to give different names to objects of the same ```REPR```. An alternative would be to add an additional field (e.g. ```nameForSerialization```) to the base class ```REPR```, which would usually be identical to ```name```, but would differ for native arrays.

**Comment by usev6** [comment]
I've created another PR (implementing the first option -- keeping the special names): https://github.com/Raku/nqp/pull/721

**Comment by usev6** [comment]
Using native arrays in the core settings works now (the PR for nqp have been merged and nqp has been bumped in the last days). Existing special cases for the JVM backend have been removed with https://github.com/rakudo/rakudo/pull/4400.

I'm happy ;)
