### ISSUE TITLE
Some string benchmark

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1667]
So I stumbled upon this: https://raid6.com.au/~onlyjob/posts/arena/ (on perl5 subreddit)

Perl 6 is not listed in the article (the article is actually quite old), so I tested it against some other languages myself.
[**Here's the code**](https://gist.github.com/AlexDaniel/baae3c4ffda55f9cca783f17aaab1f2b) that I got by translating the perl5 version.

First three numbers from the output (got these numbers by running everything on my own machine):
```
rakudo:  14sec 52sec 112sec
python3:  2sec  8sec  20sec
perl5:    0sec  2sec   6sec
```

It looks like there's a lot of room for optimization in rakudo.

The snippet was discussed a lot during this whole day: https://irclog.perlgeek.de/perl6-dev/2018-03-28

Also, there's already at least one commit that was inspired by this: https://github.com/MoarVM/MoarVM/commit/32d66d568376a2ce346bb60339674df92f98c689 (but see this: https://irclog.perlgeek.de/moarvm/2018-03-29#i_15978231 and https://irclog.perlgeek.de/perl6-dev/2018-03-28#i_15978007)

Creating this ticket so that we have a place to write things down. Feel free to close once all mid-hanging fruits were picked (although it would be nice if by then we get it to work faster than at least python).

**Comment by zoffixznet** [comment]
TBH, I wouldn't call `$gstr ~~ s:g/efgh/____/;` "idiomatic" Perl 6. Even if regexes were optimized to be fast, that construct creates a bunch of `Match` objects that here are simply discarded. An idiomatic string-to-string replacement in Perl 6 would be `$gstr.subst-mutate: :g, 'efgh', '____'`

**Comment by AlexDaniel** [comment]
That doubles the runtime for me… huh.

```
This is Rakudo version 2018.03-86-gd0fbe7447 built on MoarVM version 2018.03-26-gb1f64db89
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
> string-to-string replacement in Perl 6 would be `$gstr .= subst: :g, 'efgh', '____'`

And surprisingly that doubles my runtime from 12s to 24s

**Comment by zoffixznet** [comment]
And if I remove `str` typing on variables, the `s///` version drops to 10s while `.subst` version shoots up to 26s.

**Comment by AlexDaniel** [comment]
Here it is ≈25s without `str` for both versions. So removing `str` does not make it faster for me at all.

**Comment by zoffixznet** [comment]
Replaced it with the guts of that `subst` version and it's still at 25s. Looks like the nqp::join/nqp::split trick isn't that efficient on large strings.

IIRC we use it in a bunch of places, so it'd be cool to figure out a Better Way(tm).

-----

My current version:
```
#!/usr/bin/env perl6
use nqp;
my str $str = 'abcdefgh' ~ 'efghefgh';
my $imax = 1024 / $str.codes * 1024 * 4;               # 4mb

my $starttime = now;
say "exec.tm.sec\tstr.length";

my $gstr='';
my $i=0;

while ($i++ < $imax + 1000) {   #adding 1000 iterations to delay exit. This will allow to capture memory usage on last step
        $gstr ~= $str;
        $gstr = nqp::join('____',nqp::split('efgh', $gstr));
        my $lngth = $str.codes * $i;
        say round(now - $starttime), "sec\t\t", $lngth/1024, 'kb' if $lngth %% (1024 * 256); #print out every 256kb
}
```

**Comment by MasterDuke17** [comment]
If I perf record a stripped down version like so...
```
perf record -g --call-graph dwarf perl6 -e 'use nqp; my str $str = "abcdefgh" ~ "efghefgh"; my $gstr= ""; for ^10_000 { $gstr ~= $str; $gstr = nqp::join("____", nqp::split("efgh", $gstr)); }; say $gstr.chars'
```
then this perf report
```
perf report --call-graph=none --no-children
```
gives
```
  33.09%  moar     libmoar.so            [.] knuth_morris_pratt_string_index
  17.84%  moar     libmoar.so            [.] iterate_gi_into_string
  17.68%  moar     libmoar.so            [.] MVM_string_get_grapheme_at_nocheck
  13.06%  moar     libmoar.so            [.] MVM_string_gi_get_grapheme
   7.35%  moar     libmoar.so            [.] copy_to_32bit
```

**Comment by samcv** [comment]
I'm working on changes which reduced it from 12s to 6s for me (256kb). Will update you guys when I have the kinks worked out. It optimizes nqp::indexingoptimized and collapse_strands which are called lots for this code.

**Comment by dogbert17** [comment]
Now, results will differ depending on what CPU etc you're using but I now get, with the original example:

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-82-gb30fa3a71.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.
    dogbert@dogbert-VirtualBox:~$ perl6 scratch.pl6
    exec.tm.sec	str.length
    3sec		256kb
    12sec		512kb
    28sec		768kb

The CPU used is a Ryzen 3700X

**Comment by AlexDaniel** [comment]
Yeah, it is faster now. Taking the table above and only rerunning the raku script:
```
rakudo:   6sec 25sec  58sec
python3:  2sec  8sec  20sec
perl5:    0sec  2sec   6sec
```
So, as @samcv mentioned, it is roughly 2x faster than it was before.

**Comment by samcv** [comment]
If I remember from when I did the MoarVM string optimizations 2 years ago, the next place we need to look is how Rakudo creates and modifies in `s/foo/bar` code. Haven't profiled Rakudo for a long time, will check and see what's taking up the time later today.

**Comment by lizmat** [comment]
Closing as the world has changed.
