### ISSUE TITLE
logMN doesn't equal to logM + logN

### ISSUE THREAD

**Issue by titsuki** [rakudo/rakudo#1670]
## The Problem

logMN doesn't equal to logM + logN:
```
$ perl6 -e 'use Test; is log(1/7 * 1/3), log(1/7) + log(1/3)'
not ok 1 - 
# Failed test at -e line 1
# expected: '-3.0445224377234235'
#      got: '-3.044522437723423'
```

## Expected Behavior
The left hand side equals to the right hand side.

## Actual Behavior
They are not equivalent.

## Steps to Reproduce

I mentioned that in the Problem section.

## Environment
* Operating system: Debian stretch
* Compiler version (`perl6 -v`): 
```
$ perl6 --version
This is Rakudo version 2018.03-129-g7572983a4 built on MoarVM version 2018.03-35-gafdcad424
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
That's the goodness of floating point math. There's noise, so even though mathematically those are equal, the noise makes the number slightly different and so not equivalent.

```perl6;
use Test; is log(1/7 * 1/3), log(1/7) + log(1/3);

# Failed test at <tmp> line 1
# expected: '-3.0445224377234235'
#      got: '-3.044522437723423'␤»
```

I get the exact same values in C too:
```
$ ccc 'printf("%.17g\n", log(1e0/7 * 1e0/3));'
-3.044522437723423
$ ccc 'printf("%.17g\n", log(1e0/7) + log(1e0/3));'                                                                                                                                                            
-3.0445224377234235
```

And the values are right next to each other. If you ask for next representable float after one result, you end up with the other value:
```
$ ccc 'printf("%.17g\n", nextafter(log(1e0/7) + log(1e0/3), DBL_MAX));'
-3.044522437723423
```
