### ISSUE TITLE
[JVM] Calling .perl on Sequence produced by chained .grep after .grep, :k gives wrong result

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#1671]
There is a test in S32-list/grep-k.t (and a similiar test in S32-list/grep-kv.t) that started to fail on the JVM backend, recently: https://github.com/perl6/roast/blob/4c1a52d7555ecbf8a13af0dbfdcc6ae99f0e97ca/S32-list/grep-k.t#L10

I wasn't able to golf it any further than this:
```
$ ./perl6-j -e 'say grep( { True }, ^3, :k).grep( { True } ).perl'
(2, 2, 2).Seq
```

The problem doesn't surface with .gist:
```
$ ./perl6-j -e 'say grep( { True }, ^3, :k).grep( { True } ).gist'
(0 1 2)
```

I tried to revert https://github.com/rakudo/rakudo/commit/e3aef509b1 and that made the problem go away (for the :k case).

**Comment by lizmat** [comment]
Please confirm it is fixed on JVM, and if so close.  I cannot even seem to build on the JVM these days anymore  :-(

**Comment by usev6** [comment]
Yes, that fixed the issue. I didn't spot the missing nqp::p6bix_i() ... Thanks for looking!
