### ISSUE TITLE
A "crossover" benchmark

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1676]
## The Problem

Crossover is an operation where two strings (chromosomes) interchange a part (genes), after randomly generating the crossover points. 

I have been benchmarking several languages for this, and the Perl 6 performance is the worst. [This is the fastest implementation so far](https://github.com/JJ/perl6eo/blob/master/xover.p6), which takes ~ 8 seconds for the smallest size. As a comparison, [this one](https://github.com/geneura-papers/2016-ea-languages-PPSN/blob/master/c%2B%2B/xover.cc) in C++ takes 0.27911 for the smallest size. It degrades with size, but for instance

C++, 2048, 29.8744
perl6-BitVector,2048,236.6089409

## Expected Behavior

A bit of improvement would be great. Even if it's a different data structure. That data structure has proved the fastest for other operations I need, but I'd happily consider them. 

## Actual Behavior

Very slow performance in every part of the operation, from random number generation to splicing.

## Steps to Reproduce

Test the code linked above with 2018.03

## Environment
* Operating system: 

Ubuntu 14.04.5

* Compiler version (`perl6 -v`): 

2018.03 with MoarVM 2018.03

**Comment by dogbert17** [comment]
Looks like things are improving:

    dogbert@dogbert-VirtualBox ~ $ uname -a
    Linux dogbert-VirtualBox 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    dogbert@dogbert-VirtualBox ~ $ perl6 -v 
    This is Rakudo version 2018.03-214-g72473bd built on MoarVM version 2018.03-99-g4234ab5
    implementing Perl 6.c.
    dogbert@dogbert-VirtualBox ~ $ perl6 scratch.pl6 
    perl6-BitVector,16,6.8396172
    perl6-BitVector,32,8.0817590
    perl6-BitVector,64,10.1717190
    perl6-BitVector,128,14.4833885
    perl6-BitVector,256,22.9058421
    perl6-BitVector,512,39.4818388
    perl6-BitVector,1024,72.31655215
    perl6-BitVector,2048,140.5483579

**Comment by JJ** [comment]
I'll try to change this into a gist so that we can measure improvement...

**Comment by dogbert17** [comment]
Here are the latest numbers, same system as in my comment on Apr. 9th

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ uname -a
    Linux dogbert-VirtualBox 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.10-129-g80edefc built on MoarVM version 2018.10-77-g6236eb5
    implementing Perl 6.d
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 scratch.pl6 
    perl6-BitVector,16,3.9610026
    perl6-BitVector,32,4.5882467
    perl6-BitVector,64,5.8039562
    perl6-BitVector,128,8.3460665
    perl6-BitVector,256,13.04964113
    perl6-BitVector,512,22.5815232
    perl6-BitVector,1024,41.2419408
    perl6-BitVector,2048,78.3956499

**Comment by AlexDaniel** [comment]
Niiiiice!

**Comment by lizmat** [comment]
Where does the script actually live again?

**Comment by JJ** [comment]
@lizmat here was the original: https://github.com/JJ/perl6eo
@dogbert17 an amazing 4x speed improvement. Thanks!

**Comment by JJ** [comment]
This has improved 4x since I last checked. It's now around 2 seconds for the smallest size, but it's still 100x slower than Perl 5. I have changed the data structure used to lists to avoid itemization, and eliminated all copies, using more purely functional style. Still, it is quite slow, mainly, apparently, due to many [pull-ones](http://jj.github.io/perl6eo/profile-1565512859.9110596.html), according to the profile. I'm not sure where that's happening, to optimize it out. Maybe it's the `.flat` when returning the lists. Not sure also if this is a Rakudo performance issue or simply a not knowing enough issue. 
Here's how the code is now:
https://github.com/JJ/perl6eo/blob/a9a8b1ed880f96b16d7a5d74d4b2305ccfe62500/xover.p6#L3-L11

**Comment by dogbert17** [comment]
Using the code from the original post I now get

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-82-gb30fa3a71.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.
    dogbert@dogbert-VirtualBox:~$ perl6 scratch.pl6
    perl6-BitVector,16,1.6770133
    perl6-BitVector,32,1.643561
    perl6-BitVector,64,1.6821902
    perl6-BitVector,128,1.7622771
    perl6-BitVector,256,1.919338
    perl6-BitVector,512,2.2548632
    perl6-BitVector,1024,2.9322712
    perl6-BitVector,2048,4.2866182
    perl6-BitVector,4096,7.013559

**Comment by JJ** [comment]
Ow wow. Thanks!

**Comment by lizmat** [comment]
On an M1
```
perl6-BitVector,16,1.0268556
perl6-BitVector,32,1.046288792
perl6-BitVector,64,1.161108336
perl6-BitVector,128,1.388105206
perl6-BitVector,256,1.820630568
perl6-BitVector,512,2.679533782
perl6-BitVector,1024,4.397873702
perl6-BitVector,2048,7.805707293
perl6-BitVector,4096,14.683835961
perl6-BitVector,8192,28.23717323
```

**Comment by lizmat** [comment]
A small change in the algorithm has a noticeable impact:
```
perl6-BitVector,16,0.778579769
perl6-BitVector,32,0.82609326
perl6-BitVector,64,0.93900991
perl6-BitVector,128,1.158055122
perl6-BitVector,256,1.591932469
perl6-BitVector,512,2.442910191
perl6-BitVector,1024,4.130396426
perl6-BitVector,2048,7.548829103
perl6-BitVector,4096,14.337854178
perl6-BitVector,8192,27.8615735
```
Assignments *to* lists are notoriously slow, so change the signature of `xover` to take two raw variable, and assign those inside the `xover` sub. 
```
sub xover( @chromosome1, @chromosome2, $elem1 is raw, $elem2 is raw ) {
    my $len := @chromosome1.elems;
    my $start := ($len -2 ).rand.Int;
    my $this-len := ($len-$start).rand.Int;
    $elem1 = (@chromosome2.head($start), @chromosome1.skip($start).head($this-len),
     @chromosome2.tail( $len - $this-len - $start  )).flat;
    $elem2 = (@chromosome1.head($start), @chromosome2.skip($start).head($this-len),
     @chromosome1.tail( $len - $this-len - $start  )).flat;
}

my Int $len = 16;
my $maxlen := 32768;
my $how-many := 100000;
while $len <= $maxlen {
    my $start = now;
    my @chromosome1 := Bool.roll($len).list;
    my @chromosome2 := Bool.roll($len).list;
    for 1..$how-many  {
        xover(@chromosome1, @chromosome2, my $elem1, my $elem2 );
    }
    say "perl6-BitVector,$len,",now - $start;
    $len = $len*2;
}
```

**Comment by JJ** [comment]
I'm closing this now, with thanks.
