### ISSUE TITLE
REPL exit instructions don't work on Windows

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1677]
It says to press `^D` to exit but that don't do nothing on `cmd.exe` on Win10: 
```
C:\rakudo>perl6

To exit type 'exit' or '^D'
> ^D^D^D^D^D^D^D^D^D^D
===SORRY!=== Error while compiling:
Bogus statement
------> <BOL><HERE>
    expecting any of:
        prefix
        term
> ^D
===SORRY!=== Error while compiling:
Bogus statement
------> <BOL><HERE>
    expecting any of:
        prefix
        term
> ^CTerminate batch job (Y/N)? y

C:\rakudo>perl6 -v
This is Rakudo version 2018.03-107-ge31dd96 built on MoarVM version 2018.03-31-gfdb5e4d
implementing Perl 6.c.
```

(partly related https://github.com/rakudo/rakudo/pull/1674 )

**Comment by Kaiepi** [comment]
Looks like it'd be better to use ^C instead of ^D to exit because of this. Which line editor are you using?

**Comment by zoffixznet** [comment]
The default one. The "terminate batch job" message in the `^C` option is unwanted. `^Z` works, but you have to press ENTER after pressing CTRL+Z to send it.

**Comment by Kaiepi** [comment]
^Z gives me a similar error to yours with ^D when I test it on OpenBSD. I think ^C would be more preferable for now

**Comment by zoffixznet** [comment]
> ^D when I test it on OpenBSD

We can customize the message based on the OS.

**Comment by Kaiepi** [comment]
>We can customize the message based on the OS.

You're right. I'm getting too caught up in trying to keep them equivalent across OSes when that wouldn't work
