### ISSUE TITLE
buffering difference between terminal and file

### ISSUE THREAD

**Issue by jdv** [rakudo/rakudo#1683]
## The Problem

stdout is line buffered when pointing to a terminal but not when pointing to a file.

## Expected Behavior

consistently line buffered as, i believe, is normal *nixish behavior.

## Actual Behavior

redirecting stdout to a file shows only the first line while the program is running
and the rest on proc end or flush.

## Steps to Reproduce

# buffered to file
jdv:~$ rm foo.log
jdv:~$ touch foo.log
jdv:~$ ./rakudo/install/bin/perl6 -e 'for 1..10 {sleep 2; say $_;}' > foo.log &
[1] 12108
jdv:~$ sleep 5
jdv:~$ kill %1
jdv:~$ cat foo.log
1
[1]+  Terminated              ./rakudo/install/bin/perl6 -e 'for 1..10 {sleep 2; say $_;}' > foo.log
jdv:~$

# unbuffered to file
jdv:~$ rm foo.log
jdv:~$ touch foo.log
jdv:~$ ./rakudo/install/bin/perl6 -e '$*OUT.out-buffer=0; for 1..10 {sleep 2; say $_;}' > foo.log &
[1] 12117
jdv:~$ sleep 5
jdv:~$ kill %1
jdv:~$ cat foo.log
1
2
3
4
5
[1]+  Terminated              ./rakudo/install/bin/perl6 -e '$*OUT.out-buffer=0; for 1..10 {sleep 2; say $_;}' > foo.log
jdv:~$

# unbuffered to terminal
jdv:~$ ./rakudo/install/bin/perl6 -e '$*OUT.out-buffer=0; for 1..10 {sleep 2; say $_;}' &
[1] 12125
jdv:~$ sleep 5
1
2
3
4
jdv:~$ kill %1
jdv:~$
[1]+  Terminated              ./rakudo/install/bin/perl6 -e '$*OUT.out-buffer=0; for 1..10 {sleep 2; say $_;}'
jdv:~$

## Environment
* Operating system: 

fedora 24

* Compiler version (`perl6 -v`): 

$ ./rakudo/install/bin/perl6 -v
This is Rakudo version 2018.03-134-g20495f0 built on MoarVM version 2018.03-56-g85fc758
implementing Perl 6.c.
$

**Comment by jnthn** [comment]
> stdout is line buffered when pointing to a terminal but not when pointing to a file.

This is intended.

> consistently line buffered as, i believe, is normal *nixish behavior.

Perl 5 seems to be doing just the same as Perl 6, so the Perl 6 behavior can't be *that* non-standard.

```
$ perl -e 'for (1..100) { print "foo\n"; sleep 1 }' > x
^Z
[1]+  Stopped                 perl -e 'for (1..100) { print "foo\n"; sleep 1 }' > x
$ cat x
```

**Comment by jdv** [comment]
OK.  Thanks.
