### ISSUE TITLE
once doesn't work in C-style loop conditional

### ISSUE THREAD

**Issue by b2gills** [rakudo/rakudo#1684]
``` perl6
my $end = 9;

loop (
    my $i = 0
  ;
    $i < (once ++$end)  # <--
  ;
    ++$i
) {
  last if $i > 20
};

say $end;
```

This should print `10` but instead prints `31`

A workaround is to use `(my $ //= ++$end)`.

rakudo (2018.03.153.gc.53.fde.3)

**Comment by jstuder-gh** [comment]
When running @lizmat's example with --target=ast, it returns this QAST subtree for the e2 (conditional expression) part of the c-style loop:

    ->    - QAST::Op(while) <sunk> loop (my $i = 0; $i < once { print $i; 10 }; ++$i)...
            - QAST::Op(chain &infix:«<») <wanted> <
              - QAST::Var(lexical $i) <wanted> $i
              - QAST::Op(if) <wanted>
    ->          - QAST::Op(p6stateinit)
                - QAST::Op(p6store) <wanted>
                  - QAST::Var(lexical once__1) <wanted>
                  - QAST::Op(call)
                    - QAST::Op(p6capturelex) <wanted> :past_block<?> :code_object<?>
                      - QAST::Op(callmethod clone)
                        - QAST::WVal(Block)  :uninstall_if_immediately_used<?> :past_block<?> :code_object<?>
                - QAST::Var(lexical once__1) <wanted>

```p6stateinit``` returns a truthy value if the current frame happens to be the first invocation of a closure (each clone of a block). In this instance it is the first invocation of the outer scope and each invocation of the ```p6stateinit``` in the QAST ```while``` is returning a truthy value, running the once block each time.

I have a series of PRs related to state initialization that could apply here as well, with a little tweaking. 
 [See here](https://github.com/rakudo/rakudo/compare/master...jstuder-gh:state_init_4_EXPERIMENT) for a modified version (WIP) that would address this issue. This coincides with [this MoarVM PR](https://github.com/MoarVM/MoarVM/pull/806) and [this NQP PR](https://github.com/perl6/nqp/pull/420), which create an ```is_hll_init``` value on a frame's coderef. With the modifications included in this linked branch it solves this issue and passes the existing spectest.

With this, a new coderef is generated for each clone of a block and when state value is set, it is not set again when encountering ```p6stateinit``` (regardless of whether the frame is the same). The onus is on the HLL to mark the ```is_hll_init``` variable as having been assigned a value (via extop). This solves the issue of state variables not being given a value within the first invocation of a closure and would also address this issue.

(Perhaps the coderef should have a hash of the lexical symbols where the ```is_hll_init``` value is stored? That would eliminate having to iterate though the lexical array to find the object and would work for a future implementation of native state variables. Just a thought.)

Thoughts?

**Comment by ab5tract** [comment]
FWIW, the following code does what you want:

```
ENTER my $end = 9;

loop (
    my $i = 0
  ;
    $i < (ENTER ++$end)  # <--
  ;
    ++$i
) {
  last if $i > 20
};

say $end;
```

```
> set-base; ./rakudo-m issues/r1684-enter.raku
10
> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-92-g24057e69c.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```

Unfortunately RakuAST blows up:

```
> set-rakuast; ./rakudo-m issues/r1684-enter.raku
===SORRY!===
Cannot iterate object with P6str representation (BOOTStr)
```

But this variant *does* work in RakuAST, taking advantage of the new return-value-capable `FIRST` implementation:

```
sub do-it() {
  BEGIN my $end = 9;
  
  loop (
      my $i = 0
    ;
      $i < (FIRST ++$end)  # also works with ENTER *or* once, now that we are in a subroutine
    ;
      ++$i
  ) {
    last if $i > 20
  };
 
  say $end;
}

do-it
```
