### ISSUE TITLE
Possible bug in `loop` with state vars and FIRST phaser

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1687]
(filing to remember to check it out; don't got time now)

In Actions, there's this bit of code that fixes up state vars:

```
            # Elevate statevars to enclosing thunk
            if $body.has_ann('has_statevar') {
                Perl6::Actions::migrate_blocks(
                    $body, $block.ann('past_block'),
                    -> $n { nqp::istype($n, QAST::Var) && $n.decl eq 'statevar' }
                )
            }
```

But if FIRST phaser is present, I think `$body` would just be a call to a `QAST::Var` holding a `QAST::WVal` with code object referecinging the actual location where I imagine those state vars would be at.

So I predict there's a bug with `loop` + state vars + `FIRST` phaser

**Comment by jstuder-gh** [comment]
That particular bit of code was in response to [GH Issue #1341](https://github.com/rakudo/rakudo/issues/1341) and was to resolve an error with statevars when used in conjunction with some statement prefixes like "do".

@jnthn had pointed out that that may be an inappropriate way of addressing the problem (see related issue [here](https://github.com/rakudo/rakudo/issues/1484)). There may be a better way of addressing the issue without as much potential for side-effects.

If it does need to be reverted, the commit where it was introduced is 299e85264b50104ad82411e9c3999dc727154091.

**Comment by zoffixznet** [comment]
Thanks. If there is in fact a bug, I'd expect it to be this code producing `1 1 1` instead of `1 2`:

```
say do loop { state $x = 0;  FIRST Nil; last if ++$x > 2;  $x; }
```

Currently it explodes due to https://github.com/rakudo/rakudo/issues/1623 which I have the fix for already, but just need to make it look nice.

**Comment by zoffixznet** [comment]
Can't produce any of the anticipated ill effects, so closing.
