### ISSUE TITLE
Seq.from-loop(&body) does not behave like `loop { ... }`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1692]
The docs say `Seq.from-loop(&body)` emulates `loop { body }`, however, it doesn't:

```
<Zoffix_> m: my int $i; say eager Seq.from-loop: {say $i++;  last if $i > 5 }; 
<camelia> rakudo-moar c8364d696: OUTPUT: «0␤()␤»

<Zoffix_> m: my int $i; loop {say $i++;  last if $i > 5 }; 
<camelia> rakudo-moar c8364d696: OUTPUT: «0␤1␤2␤3␤4␤5␤»
```

The cause is it treats an empty `Slip` (in this case, returned by the `if`) as an indicator to stop.

The same behaviour doesn't exist with the form of `Seq.from-loop` that takes a condition:
```
<Zoffix_> m: my int $i; say eager Seq.from-loop: {say $i++;  last if $i > 5 }, {1}
<camelia> rakudo-moar c8364d696: OUTPUT: «0␤1␤2␤3␤4␤5␤()␤»
```

----

We actually rewrite `loop` into a `Seq.from-loop` when we collect its values, such as here:
```
<Zoffix_> m: my int $i; say eager do loop { say $i++; last if $i > 10 }
<camelia> rakudo-moar c8364d696: OUTPUT: «0␤1␤2␤3␤4␤5␤6␤7␤8␤9␤10␤()␤»
```

And the reason the above doesn't exhibit the same bug is simply by chance: we gen a `QAST::IVal.new: :value(1)` as the conditional in the original loop, and since it lacks compile time value, we actually
end up making a block that returns `1` always, resulting in us calling the 2-arg form of `.from-loop` and avoiding the bug in the single-arg form.

I discovered this bug by fixing the above and I've now stashed that fix into [`better-loop` branch](https://github.com/rakudo/rakudo/commit/c1906c1af173fa5189b8229827da22a0bb1ecffc)

-----

I suspect the stop-on-empty-Slip behaviour was implemented to mirror what we do with `|() xx *`. I remember discussions about that. However, looking at that now, I wonder if that was the right decision. 

Yes `|() xx *` would otherwise hang, but so does `while 1 {}`. On the flipside of the coin, this abruptly stops:

```
<Zoffix_> m: say eager |(<a b c>.pick: 5.rand) xx *
<camelia> rakudo-moar c8364d696: OUTPUT: «(c b a a b c c c a b a c a c b)␤»
<Zoffix_> m: say eager |(<a b c>.pick: 5.rand) xx *
<camelia> rakudo-moar c8364d696: OUTPUT: «(c a c c b a c b a b c b c c b a a c a b b a c c b a a c a b c)␤»
```

And in real code, the condition might not be so frequent. And a program that's meant to chug along forever, flattening received items from a sub, will abruptly stop if a single fetch of a bunch of items returns zero of them.

IMO, this stop-on-encountering-empty-Slip behaviour should removed and both the routine—but primarily `Seq.from-loop(&body)` should continue trying to get more values 'till they're blue in the face.

**Comment by lizmat** [comment]
Feels that this is more a documentation issue, so closing
