### ISSUE TITLE
Some `loop`s end up as wanted even when they're not

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1698]
If you stick both `FIRST` and `LAST` into a `loop` that's the last statement of a sub, we code-gen a `Seq.from-loop` for it and collect and return its values:

```
sub { loop { FIRST Nil; LAST Nil; } }()
````

At first glance, looks like `tweak_loop` in Actions forgets to propagate `.sunk` flag to the `QAST::Stmts` genned for `LAST`

**Comment by lizmat** [comment]
Cannot reproduce
