### ISSUE TITLE
Issue with array / hash slice single element and adverbs

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1703]
my Int %h = a => 42; dd %h<b c>:v;
    ()
    dd %h<b>:v
    ()    # sorta expected Nil there

`Nil` is supposed to be the absence of a single value.  We agreed upon that when we ask for a single element from an array / hash, we will not return something listy with one element.  But it appears we *are* returning something listy in this case.

Changing those occurrences to `Nil` produces quite a few of spectest errors that specifically test for `()`   :-(

**Comment by zoffixznet** [comment]
FWIW, in `%h<foo>:v.elems` when `foo` key does not exist, the `:v` lets the user avoid the 1-elem-list issue with the `Any` obtained from autovivification. If we make `:v` in this case return a `Nil`, then `.elems` would return `1` and to differentiate the cases where the key doesn't exist, the user would need to do more extensive tests.

```
<Zoffix__> m: my %h; %h<foo>.elems.say; %h<foo>:v.elems.say; Nil.elems.say
<camelia> rakudo-moar c6c251596: OUTPUT: «1␤0␤1␤»
```
