### ISSUE TITLE
New stresstest floppers

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1710]
In the past 1-2 weeks, I started seeing a several new random files flop during stresstests. S10-packages/basic.t and S17-procasync/basic.t have been flopping for ages and possibly just problematic tests, but the rest of the files I've not seen before.

Just ran 7 stresstest, a couple for flopper-free, but the rest had these flops:

```
08:21 | Zoffix | ZOFFLOP: t/spec/S06-advanced/stub.t
-- | -- | --
08:21 |   | ZOFFLOP: t/spec/S10-packages/basic.t
08:21 |   | ZOFFLOP: t/spec/S10-packages/basict
08:22 |   | ZOFFLOP: t/spec/S02-types/capture.t
08:22 |   | ZOFFLOP: t/spec/S06-other/main.t
08:22 |   | ZOFFLOP: t/spec/S17-procasync/basic.t
08:23 |   | That's the floppers from 7 stresstest runs
08:23 |   | S10-packages/basic.t and S17-procasync/basic.t are familiar offenders, but the rest are freshcomers
```

This is a really vague issue, but perhaps someone who done some work in the past 2 weeks might think of something that might be causing random crashes or something?

**Comment by zoffixznet** [comment]
It was suggested to try runs with `MVM_SPESH_BLOCKING=1` and `MVM_SPESH_NODELAY=1` set. So I `export`ed them and did a few runs. Here are the failures/passed todos from a few runs:

```
run1:
Test Summary Report
-------------------
t/spec/MISC/bug-coverage-stress.rakudo.moar                     (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/spec/S04-exceptions/fail.t                                    (Wstat: 256 Tests: 37 Failed: 1)
  Failed test:  28
  Non-zero exit status: 1
t/spec/S06-signature/caller-param.rakudo.moar                   (Wstat: 0 Tests: 7 Failed: 0)
  TODO passed:   7
t/spec/S17-procasync/stress.t                                   (Wstat: 256 Tests: 23 Failed: 1)
  Failed test:  22
  Non-zero exit status: 1
t/spec/S32-exceptions/misc.rakudo.moar                          (Wstat: 512 Tests: 173 Failed: 2)
  Failed tests:  149-150
  Non-zero exit status: 2
Files=1294, Tests=153300, 336 wallclock secs (21.92 usr  3.28 sys + 6770.86 cusr 219.15 csys = 7015.21 CPU)
Result: FAIL
```

```
run2
Test Summary Report
-------------------
t/spec/MISC/bug-coverage-stress.rakudo.moar                     (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/spec/S04-exceptions/fail.t                                    (Wstat: 256 Tests: 37 Failed: 1)
  Failed test:  28
  Non-zero exit status: 1
t/spec/S06-signature/caller-param.rakudo.moar                   (Wstat: 0 Tests: 7 Failed: 0)
  TODO passed:   7
t/spec/S32-exceptions/misc.rakudo.moar                          (Wstat: 512 Tests: 173 Failed: 2)
  Failed tests:  149-150
  Non-zero exit status: 2
Files=1294, Tests=153300, 329 wallclock secs (21.68 usr  3.52 sys + 6639.43 cusr 218.59 csys = 6883.22 CPU)
Result: FAIL
```

```
run3
Test Summary Report
-------------------
t/spec/MISC/bug-coverage-stress.rakudo.moar                     (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/spec/S04-exceptions/fail.t                                    (Wstat: 256 Tests: 37 Failed: 1)
  Failed test:  28
  Non-zero exit status: 1
t/spec/S06-signature/caller-param.rakudo.moar                   (Wstat: 0 Tests: 7 Failed: 0)
  TODO passed:   7
t/spec/S17-procasync/stress.t                                   (Wstat: 256 Tests: 23 Failed: 1)
  Failed test:  22
  Non-zero exit status: 1
t/spec/S32-exceptions/misc.rakudo.moar                          (Wstat: 512 Tests: 173 Failed: 2)
  Failed tests:  149-150
  Non-zero exit status: 2
Files=1294, Tests=153300, 334 wallclock secs (21.79 usr  3.42 sys + 6723.38 cusr 218.38 csys = 6966.97 CPU)
Result: FAIL
Makefile:581: recipe for target 'm-stresstest5' failed
make: *** [m-stresstest5] Error 1
```

```
run4
Test Summary Report
-------------------
t/spec/MISC/bug-coverage-stress.rakudo.moar                     (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/spec/S04-exceptions/fail.t                                    (Wstat: 256 Tests: 37 Failed: 1)
  Failed test:  28
  Non-zero exit status: 1
t/spec/S06-signature/caller-param.rakudo.moar                   (Wstat: 0 Tests: 7 Failed: 0)
  TODO passed:   7
t/spec/S32-exceptions/misc.rakudo.moar                          (Wstat: 512 Tests: 173 Failed: 2)
  Failed tests:  149-150
  Non-zero exit status: 2
Files=1294, Tests=153300, 327 wallclock secs (21.95 usr  3.48 sys + 6702.04 cusr 226.73 csys = 6954.20 CPU)
Result: FAIL
```


This one [hang on `t/spec/S07-hyperrace/basics.t`](https://github.com/rakudo/rakudo/issues/1709) and after I `CTRL+C`ed it, gave these results:
```
run5
t/spec/S07-hyperrace/basics.t ..................................... ^C
Test run interrupted!

Test Summary Report
-------------------
t/spec/MISC/bug-coverage-stress.rakudo.moar                     (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/spec/S04-exceptions/fail.t                                    (Wstat: 256 Tests: 37 Failed: 1)
  Failed test:  28
  Non-zero exit status: 1
t/spec/S06-signature/caller-param.rakudo.moar                   (Wstat: 0 Tests: 7 Failed: 0)
  TODO passed:   7
t/spec/S32-exceptions/misc.rakudo.moar                          (Wstat: 512 Tests: 173 Failed: 2)
  Failed tests:  149-150
  Non-zero exit status: 2
Files=1293, Tests=153217, 569 wallclock secs (26.50 usr  4.52 sys + 7554.48 cusr 324.28 csys = 7909.78 CPU)
Result: FAIL
Makefile:581: recipe for target 'm-stresstest5' failed
make: *** [m-stresstest5] Interrupt

```

**Comment by dogbert17** [comment]
I believe that jnthn has stated something to the effect that, the following tests, will always flop when using MVM_SPESH_BLOCKING=1 and MVM_SPESH_NODELAY=1:

- t/spec/S04-exceptions/fail.t

- t/spec/S32-exceptions/misc.rakudo.moar

and that they can be safely ignored.

**Comment by AlexDaniel** [comment]
No way? I don't think so. A test that is allowed to fail? No-no-no…

**Comment by dogbert17** [comment]
Fair enough :) Will add the following piece of information instead.

https://irclog.perlgeek.de/moarvm/2018-01-07#i_15661411

**Comment by timo** [comment]
these two files not succeeding is "just" an NYI that we've had for a long time

**Comment by AlexDaniel** [comment]
We should then fudge them, right?

**Comment by jnthn** [comment]
> We should then fudge them, right?

I don't think so. The two tests in question will only fail if run with some environment variables set that are explicitly for MoarVM debugging/development purposes. I've never seen them fail under the standard environment (e.g. without those options turned on).

The gory details: the tests are looking at the precise content of a backtrace. At the moment, when the VM does inlining, this impacts upon the backtrace content (inlined frames don't show up there, just the one they were inlined in to). The `NODELAY` option forces that to happen on code that'd never normally get hot enough to be optimized/inlined (thus why the issue is never noticed).

Having inlining impact on stack trace output isn't peculiar to MoarVM; as an example, it's entirely possible to observe when debugging C code, for example, though these days the tooling there has advanced to the point where it can unravel things pretty well when compiled with sufficiently detailed debug symbols. I'd like to get MoarVM to the point where it also reassembles the backtrace content as if no inlining had taken place, which we're in a position to do as we track all that stuff for deoptimization purposes. It just needs doing.

It is possible to argue that we want to keep our options open with regards to backends and so should be careful about writing spectests that mandate such stack data recovery, though even then the tests as they stand today will likely get away with it for the same reason that they do on MoarVM in normal mode today.

**Comment by AlexDaniel** [comment]
> I've never seen them fail under the standard environment

That [seems to be](https://gist.github.com/70e60e6462656a10e1bb543bd7e045b2) true. OK then I guess a comment in these files indicating that it may fail when running like this should resolve the confusion.

**Comment by jnthn** [comment]
I've also now run the various tests in the initial report under various kinds of GC stressing, Unfortunately, didn't manage to reproduce any of them with that. :-(

**Comment by zoffixznet** [comment]
Just ran 10 make test + make stresstest runs on the same box as OP and can no longer repro any new floppers.

Out of 10 runs, only `t/spec/S10-packages/basic.t` failed once, which is a common flopper, and `t/04-nativecall/09-nativecast.t` segfaulted once.
