### ISSUE TITLE
Range.minmax inconsistency / LTA error

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1729]
If you call `.minmax` on an excluded Int range, you get the minmax values; if you call it on a non-Int range, you get an error saying you can't minmax excluded Ranges.

```
<Zoffix__> m: dd ^5 .minmax
<camelia> rakudo-moar 08b951c8f: OUTPUT: «(0, 4)␤»
<Zoffix__> m: dd ^5.1 .minmax
<camelia> rakudo-moar 08b951c8f: OUTPUT: «Failure.new(exception => X::AdHoc.new(payload => "Cannot return minmax on Range with excluded ends"), backtrace => Backtrace.new)␤»
```

Either the error should mention "non-Int" ranges or both types of ranges should fail.

**Comment by W4anD0eR96** [comment]
I create a PR #1734 that makes

`(^10).minmax` raise Exception, since [0, 10) surely has no max value.

We can use `(^10).int-bounds` to get (0 9) if we want to limit domain in Integer.

**Comment by AlexDaniel** [comment]
We should be careful about this change before the release, especially if we want to add more cases that throw. Probably a deprecation warning suggesting to use `.int-bounds` is needed.
