### ISSUE TITLE
Range.ACCEPTS fails to accept one of two equivalent Ranges

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1730]
```

07:54 | Tison | m: dd (0..9) ~~ (^10); dd (^10) ~~ (0..9);
-- | -- | --
07:54 | camelia | rakudo-moar 08b951c8f: OUTPUT: «Bool::True␤Bool::False␤»
07:54 |   | brrt joined #perl6
07:55 | Tison | Interesting, so (0..9) and (^10) both Range and they contain same data but not same thing


08:02 | Zoffix | looks like just failing to check the opposite of `!topic.excludes-max && $!excludes-max`
-- | -- | --
08:03 |   | m: use nqp; dd nqp::iseq_i(nqp::add_i(nqp::istrue(1), nqp::istrue(1)),1)
08:03 | camelia | rakudo-moar 08b951c8f: OUTPUT: «0␤»
08:03 | Zoffix | m: use nqp; dd nqp::iseq_i(nqp::add_i(nqp::istrue(1), nqp::istrue(0)),1)
08:03 | camelia | rakudo-moar 08b951c8f: OUTPUT: «1␤»
08:04 | Zoffix | m: use nqp; dd nqp::iseq_i(nqp::add_i(nqp::istrue(0), nqp::istrue(1)),1)
08:04 | camelia | rakudo-moar 08b951c8f: OUTPUT: «1␤»
08:04 | Zoffix | prolly that with topic.excludes-max and $!excludes-max (and the same for mins) would fix the bug  

```

```

08:11 | lizmat | m: dd 9.9 ~~ 0.0..^10.0   # can also have non-int in ranges
-- | -- | --
08:11 | camelia | rakudo-moar 08b951c8f: OUTPUT: «Bool::True␤»

```

**Comment by W4anD0eR96** [comment]
https://github.com/rakudo/rakudo/blob/08b951c8f33cfc702c308e64efcb44f3ec725117/src/core/Range.pm6#L438-L458

(^10).max == 10
(0..9).max == 9
so (^10) ~~ (0..9) meets $max < topic.max and then always be False

**Comment by zoffixznet** [comment]
> (^10) ~~ (0..9) meets $max < topic.max

Note that there `^10` is the `topic` and `0..9` is the `self`. So `topic.max < $!max` is False and it tries the `||` branch.

> no idea how about other types

Probably similar to how `Cool` candidate is done with the `after`/`not after` business (probably can simplify that to some numeric ops): https://github.com/rakudo/rakudo/blob/08b951c8f33cfc702c308e64efcb44f3ec725117/src/core/Range.pm6#L429-L434

**Comment by W4anD0eR96** [comment]
> Note that there ^10 is the topic and 0..9 is the self. So topic.max < $!max is False and it tries the || branch.

emm..then `topic.max == $!max` is false so it always false, something wrong?

**Comment by zoffixznet** [comment]
Guess I shouldn't file issues while I'm sick... 😢 

Per b2gillis++'s comment on roast:

```
^10 is not equivalent to 0..9

9.9 ~~ 0..9  # False
9.9 ~~ ^10  # True
```

The the behaviour seen in OP is correct. Unless there's some other bug I'm not seeing, then this Issue can be rejected.
