### ISSUE TITLE
Performance regression after latest MoarVM bump

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#1733]
The following code shows a large performance regression which seems to stem from MoarVM commit https://github.com/MoarVM/MoarVM/commit/957bb4bd8d61f98bacb3451cc1c93505a3412877

    use v6;
    
    sub bigpackids(int @ids) {
      my $ret = 0;
    
      my $c = 0;
      while $c++ < +@ids  {
        $ret = $ret +| (1 +< (@ids[$c] - 1));
      }
      $ret;
    }
    
    my int @a = ((^256).roll + 1) xx 256;
    say "Starting: " ~ my $instant = now;
    
    bigpackids(@a) xx 10_000;
    
    say "Ran bigpackids 10,000 times (sequential): {now - $instant}";
    
    $instant = now;
    
    await do for ^4 {
        start {
            say "started in thread $_";
            bigpackids(@a) xx 2_500;
            say "finished in thread $_";
        }
    }
    
    say "Ran bigpackids 10,000 times (parallel): {now - $instant}";

it used to display results like the following on my 64 bit Linux system:

    Starting: Instant:1523638370.858790
    Ran bigpackids 10,000 times (sequential): 4.9287254
    started in thread 0
    started in thread 1
    started in thread 2
    started in thread 3
    finished in thread 0
    finished in thread 1
    finished in thread 2
    finished in thread 3
    Ran bigpackids 10,000 times (parallel): 1.3968222

but now it's more like

    Starting: Instant:1523636420.773670
    Ran bigpackids 10,000 times (sequential): 13.10643339
    started in thread 0
    started in thread 1
    started in thread 2
    started in thread 3
    finished in thread 0
    finished in thread 1
    finished in thread 3
    finished in thread 2
    Ran bigpackids 10,000 times (parallel): 4.4074605

AlexDaniel++ for helping bisect this

**Comment by zoffixznet** [comment]
Verified that before the patch the runtime was `4.1630644` and after it dropped to `2.0255089`

**Comment by zoffixznet** [comment]
Some more runs. The master is definitely slower, even if not by the same amount as in OP. Don't know if that was the anticipated result:

#### master
```
Ran bigpackids 10,000 times (sequential): 7.81634945
Ran bigpackids 10,000 times (sequential): 6.0963268
Ran bigpackids 10,000 times (sequential): 7.4913838

Ran bigpackids 10,000 times (parallel): 2.4218071
Ran bigpackids 10,000 times (parallel): 1.9906159
Ran bigpackids 10,000 times (parallel): 2.40261445
```

#### 2018.03

```
Ran bigpackids 10,000 times (sequential): 5.6165769
Ran bigpackids 10,000 times (sequential): 5.50805300
Ran bigpackids 10,000 times (sequential): 5.56163690

Ran bigpackids 10,000 times (parallel): 1.8464684
Ran bigpackids 10,000 times (parallel): 1.8099004
Ran bigpackids 10,000 times (parallel): 1.796592
```

**Comment by dogbert17** [comment]
This is how things are now:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.03-236-gdb8b218 built on MoarVM version 2018.03-112-gfa0fc18
    implementing Perl 6.c.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ callgrind_annotate callgrind.out.13820 
    --------------------------------------------------------------------------------
    Profile data file 'callgrind.out.13820' (creator: callgrind-3.11.0)
    --------------------------------------------------------------------------------
    I1 cache: 
    D1 cache: 
    LL cache: 
    Timerange: Basic block 0 - 2717445393
    Trigger: Program termination
    Profiled target:  /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar --execname=./perl6-valgrind-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib /home/dogbert/perf.pl6 (PID 13820, part 1)
    Events recorded:  Ir
    Events shown:     Ir
    Event sort order: Ir
    Thresholds:       99
    Include dirs:     
    User annotated:   
    Auto-annotation:  off
    
    --------------------------------------------------------------------------------
                Ir 
    --------------------------------------------------------------------------------
    12,187,369,216  PROGRAM TOTALS
    
    --------------------------------------------------------------------------------
               Ir  file:function
    --------------------------------------------------------------------------------
    2,560,910,901  nqp/MoarVM/src/core/interp.c:MVM_interp_run [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      683,581,670  ???:mp_mul_2d [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      653,705,840  /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:_int_malloc [/lib/x86_64-linux-gnu/libc-2.23.so]
      431,838,154  /build/glibc-Cl5G7W/glibc-2.23/string/../sysdeps/x86_64/multiarch/memset-avx2.S:__memset_avx2 [/lib/x86_64-linux-gnu/libc-2.23.so]
      340,655,841  nqp/MoarVM/src/core/frame.c:MVM_frame_find_lexical_by_name [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      334,047,484  /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:_int_free [/lib/x86_64-linux-gnu/libc-2.23.so]
      317,328,371  nqp/MoarVM/src/6model/reprs/MVMMultiCache.c:MVM_multi_cache_find_callsite_args [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      252,306,015  nqp/MoarVM/src/6model/6model.c:MVM_6model_istype [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      249,604,959  nqp/MoarVM/src/core/frame.c:MVM_frame_invoke [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      202,765,923  nqp/MoarVM/src/core/frame.c:MVM_frame_try_return [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      193,088,219  nqp/MoarVM/src/core/fixedsizealloc.c:MVM_fixed_size_alloc [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      184,657,246  nqp/MoarVM/src/6model/sc.c:MVM_sc_get_object [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      176,273,203  nqp/MoarVM/src/core/frame.c:allocate_frame [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      164,969,922  /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:free [/lib/x86_64-linux-gnu/libc-2.23.so]
      155,809,422  nqp/MoarVM/src/core/args.c:MVM_args_get_required_pos_obj [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      148,265,575  nqp/MoarVM/src/core/frame.c:MVM_frame_find_invokee_multi_ok [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      142,626,882  nqp/MoarVM/src/core/fixedsizealloc.c:MVM_fixed_size_free [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      142,532,840  nqp/MoarVM/src/6model/reprs/P6opaque.c:initialize [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      137,982,077  /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:calloc [/lib/x86_64-linux-gnu/libc-2.23.so]
      133,713,206  nqp/MoarVM/src/6model/reprs/P6opaque.c:gc_free [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      132,129,868  ???:mp_set_long [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      130,107,389  nqp/MoarVM/src/gc/collect.c:MVM_gc_collect_free_nursery_uncopied [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      128,797,200  nqp/MoarVM/src/strings/ops.c:MVM_string_substrings_equal_nocheck [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      127,738,369  ???:mp_clamp [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      119,022,210  nqp/MoarVM/src/6model/reprs/P6opaque.c:get_boxed_ref [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      116,074,204  nqp/MoarVM/src/gc/allocation.c:MVM_gc_allocate_object [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      112,812,970  nqp/MoarVM/src/strings/ops.c:MVM_string_equal [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      109,976,727  /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:malloc [/lib/x86_64-linux-gnu/libc-2.23.so]
      108,648,296  nqp/MoarVM/src/6model/reprconv.c:MVM_repr_alloc_init [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
      106,554,861  nqp/MoarVM/src/strings/ops.h:MVM_string_equal
       91,735,356  nqp/MoarVM/src/gc/allocation.c:MVM_gc_allocate_nursery [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       85,646,704  nqp/MoarVM/src/spesh/arg_guard.c:MVM_spesh_arg_guard_run [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       83,601,944  nqp/MoarVM/src/core/frame.c:MVM_frame_find_invokee [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       81,982,859  nqp/MoarVM/src/core/args.c:MVM_args_checkarity [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       80,201,576  nqp/MoarVM/src/spesh/log.h:MVM_interp_run
       76,979,216  nqp/MoarVM/src/core/args.c:MVM_args_set_result_obj [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       70,712,293  /build/glibc-Cl5G7W/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcmp-sse4.S:__memcmp_sse4_1 [/lib/x86_64-linux-gnu/libc-2.23.so]
       69,860,842  /build/glibc-Cl5G7W/glibc-2.23/string/../sysdeps/x86_64/multiarch/../memset.S:__GI_memset [/lib/x86_64-linux-gnu/libc-2.23.so]
       69,234,369  nqp/MoarVM/src/6model/containers.c:native_ref_fetch [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       68,533,278  nqp/MoarVM/src/6model/sc.c:MVM_sc_get_sc_object [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       64,884,511  /build/glibc-Cl5G7W/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:__memcpy_avx_unaligned [/lib/x86_64-linux-gnu/libc-2.23.so]
       59,445,544  nqp/MoarVM/src/6model/reprconv.c:MVM_repr_box_int [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       58,695,076  nqp/MoarVM/src/6model/reprs/MVMHash.c:at_key [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       58,051,655  ???:mp_copy [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       55,699,537  nqp/MoarVM/src/core/args.c:MVM_args_proc_init [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       55,273,420  nqp/MoarVM/src/gc/roots.h:MVM_gc_allocate_object
       54,616,972  src/vm/moar/ops/container.c:rakudo_scalar_store [/home/dogbert/repos/rakudo/dynext/libperl6_ops_moar.so]
       47,608,000  nqp/MoarVM/src/math/bigintops.c:MVM_bigint_or [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       46,376,000  nqp/MoarVM/src/math/bigintops.c:MVM_bigint_shl [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       45,819,498  nqp/MoarVM/src/6model/reprs/VMArray.c:at_pos [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       42,074,013  nqp/MoarVM/src/math/bigintops.c:MVM_bigint_add [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       41,746,310  nqp/MoarVM/src/math/bigintops.c:MVM_bigint_sub [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       39,589,935  nqp/MoarVM/src/6model/serialization.c:MVM_serialization_read_int [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       39,570,960  nqp/MoarVM/src/gc/roots.h:MVM_repr_alloc_init
       37,330,000  ???:mp_or [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       36,636,943  nqp/MoarVM/src/core/validation.c:MVM_validate_static_frame [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       36,471,941  /build/glibc-Cl5G7W/glibc-2.23/malloc/malloc.c:malloc_consolidate [/lib/x86_64-linux-gnu/libc-2.23.so]
       36,314,370  nqp/MoarVM/src/core/args.c:MVM_args_proc_cleanup [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       36,267,315  nqp/MoarVM/src/6model/reprs/MVMCode.c:invoke_handler [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       35,790,694  nqp/MoarVM/src/6model/serialization.c:MVM_serialization_read_ref [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       34,266,739  nqp/MoarVM/src/6model/sc.h:MVM_sc_get_sc_object
       32,282,607  nqp/MoarVM/src/6model/reprconv.c:MVM_repr_at_pos_i [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       31,789,637  src/vm/moar/ops/perl6_ops.c:p6decontrv [/home/dogbert/repos/rakudo/dynext/libperl6_ops_moar.so]
       28,241,039  nqp/MoarVM/src/gc/allocation.h:MVM_gc_allocate_zeroed [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       28,102,320  nqp/MoarVM/src/core/fixedsizealloc.c:MVM_fixed_size_alloc_zeroed [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       27,289,705  nqp/MoarVM/src/6model/reprs/MVMNull.h:MVM_frame_find_lexical_by_name
       26,230,268  nqp/MoarVM/src/core/args.c:MVM_args_slurpy_named [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       25,802,699  ???:mp_clear [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       25,206,437  nqp/MoarVM/src/math/bigintops.c:MVM_bigint_cmp [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       23,337,100  nqp/MoarVM/src/6model/reprs/MVMNull.h:MVM_6model_istype
       22,979,768  ???:mp_lshd [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       22,279,653  nqp/MoarVM/src/6model/6model.c:MVM_6model_find_method [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       22,216,125  ???:mp_init [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       21,881,697  nqp/MoarVM/src/core/hll.c:MVM_hll_map
       21,874,040  nqp/MoarVM/src/6model/reprs/MVMNull.h:MVM_hll_map [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       21,626,638  nqp/MoarVM/src/6model/reprs/P6opaque.c:set_int [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       21,527,549  nqp/MoarVM/src/gc/gen2.c:MVM_gc_gen2_allocate [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       21,417,433  nqp/MoarVM/src/core/validation.c:validate_operands [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       20,836,845  nqp/MoarVM/src/6model/reprs/MVMNull.h:MVM_multi_cache_find_callsite_args
       20,042,784  nqp/MoarVM/src/6model/reprs/P6opaque.c:allocate [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       19,837,035  nqp/MoarVM/src/6model/reprs/P6opaque.h:get_boxed_ref
       19,821,061  nqp/MoarVM/src/core/intcache.c:MVM_intcache_get [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       19,621,840  nqp/MoarVM/src/core/hll.c:MVM_hll_current [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       19,268,040  /usr/include/x86_64-linux-gnu/bits/string3.h:allocate_frame
       19,242,252  nqp/MoarVM/src/core/coerce.c:MVM_coerce_istrue [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       18,494,352  nqp/MoarVM/src/6model/reprs/P6opaque.c:get_int [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       18,432,000  nqp/MoarVM/src/math/bigintops.c:two_complement_bitop [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       17,488,428  nqp/MoarVM/src/gc/wb.h:MVM_gc_allocate_object
       17,411,944  ???:mp_init_size [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       17,187,808  nqp/MoarVM/src/6model/reprconv.c:MVM_repr_set_int [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       16,384,000  nqp/MoarVM/src/6model/reprs/NativeRef.c:MVM_nativeref_pos_i [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       16,256,216  nqp/MoarVM/src/6model/reprs/MVMNull.h:MVM_frame_find_invokee
       15,752,108  nqp/MoarVM/src/6model/reprs/P6opaque.h:gc_free
       15,728,472  nqp/MoarVM/src/6model/reprs/P6bigint.c:set_int [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       15,519,950  nqp/MoarVM/src/6model/reprconv.c:MVM_repr_at_key_o [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       15,458,675  src/vm/moar/ops/container.c:rakudo_scalar_fetch [/home/dogbert/repos/rakudo/dynext/libperl6_ops_moar.so]
       13,971,696  nqp/MoarVM/src/core/compunit.h:MVM_interp_run
       13,932,816  nqp/MoarVM/src/6model/reprs/P6opaque.h:MVM_frame_find_invokee
       13,602,502  nqp/MoarVM/src/6model/reprs/P6bigint.c:gc_cleanup [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       13,213,596  nqp/MoarVM/src/gc/roots.h:MVM_6model_find_method
       12,412,335  nqp/MoarVM/src/6model/reprs/P6opaque.h:MVM_frame_find_invokee_multi_ok
       12,304,052  nqp/MoarVM/src/6model/reprs/P6opaque.h:MVM_interp_run
       12,130,052  nqp/MoarVM/src/jit/x64/tile_pattern.h:tile_node
       12,115,264  nqp/MoarVM/src/jit/compile.h:MVM_frame_try_return
       11,885,925  nqp/MoarVM/src/6model/reprs/P6opaque.h:initialize
       11,873,270  nqp/MoarVM/src/core/alloc.h:gc_free [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       11,839,429  ???:0x0000000004debc38 [???]
       11,778,166  ???:mp_init_copy [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       11,709,300  /usr/include/x86_64-linux-gnu/bits/string3.h:MVM_fixed_size_alloc_zeroed
       11,634,935  nqp/MoarVM/src/6model/reprs/P6opaque.c:get_attribute [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       11,583,466  nqp/MoarVM/src/6model/reprs/MVMNull.h:MVM_frame_find_invokee_multi_ok
       11,219,756  nqp/MoarVM/src/6model/serialization.c:MVM_serialization_demand_object'2 [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       11,072,310  nqp/MoarVM/src/jit/expr.c:walk_tree'2 [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       10,958,910  nqp/MoarVM/src/core/callstack.c:MVM_callstack_region_prev [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       10,408,575  nqp/MoarVM/src/6model/reprconv.c:MVM_repr_at_pos_o [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       10,309,675  src/vm/moar/ops/container.c:rakudo_scalar_can_store [/home/dogbert/repos/rakudo/dynext/libperl6_ops_moar.so]
       10,276,189  nqp/MoarVM/src/6model/reprs/VMArray.c:deserialize [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
       10,269,483  nqp/MoarVM/src/core/validation.c:validate_reg_operand [/home/dogbert/repos/rakudo/install/lib/libmoar.so]
        9,927,894  nqp/MoarVM/src/gc/roots.h:MVM_args_slurpy_named

**Comment by AlexDaniel** [comment]
@dogbert17 can you give an update on this? I think some recent commits by @timo should improve the situation.

**Comment by dogbert17** [comment]
The new commits by timotimo++ have indeed solved the problem

**Comment by lizmat** [comment]
Closing as untestable
