### ISSUE TITLE
Toaster results show several modules' tests rely on buggy Num stringification

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1736]
Filing in hopes of getting more helping hands on this.

There are several modules on https://toaster.perl6.party/ at the top, with "Fail" in the right column. If you click on "Fail" you'll see test results. And in a bunch of modules, you'll see they test a specific stringification of a Num.

Presumably, they're testing a num using `is` routine, when they should be using [`is-approx` routine](https://docs.perl6.org/language/testing#index-entry-is-approx-is-approx%28%24value%2C_%24expected%2C_%24description%3F%29) or, if the nums are actually meant to be exactly equal, with [`cmp ...,'==', ...` routine](https://docs.perl6.org/language/testing#By_arbitrary_comparison).

So we need volunteers to PR fixes to those modules' tests, swapping to correct testing functions or fixing the failures by some other means.

If you send a PR, please comment on this issue the name of the module, so others would know it's fixed already.

**Comment by sylints** [comment]
Changed tests on Stats module, which should resolve the failure in the BioInfo module as well.

**Comment by sylints** [comment]
Changed tests in ScaleVec module

**Comment by AlexDaniel** [comment]
Thank you, @sylints!

**Comment by AlexDaniel** [comment]
Not a blocker per se, but we try to fix issues in the ecosystem before the release.

**Comment by AlexDaniel** [comment]
I did my own toaster run today, and here are the results:

| | Module | Note |
|----|----|-----|
| ✓ | Algorithm::GooglePolylineEncoding | https://github.com/Scimon/p6-Algorithm-GooglePolylineEncoding/pull/1 |
| 👪 | BioInfo | depends on Stats |
| ¿ | CSS::Declarations | depends on CSS::Specification |
| ¿ | CSS::Module | depends CSS::Specification |
| ? | CSS::Specification | `No such symbol 't::CSS::Aural::Spec::Grammar'` in toaster but no issue locally (I should check it again) |
| ☠ | Chemistry::Elements | rakudobug https://github.com/rakudo/rakudo/issues/1753 |
| 🐦 | DB::Model::Easy | toaster flop, installs fine locally |
| 👪 | Music::Engine | depends on ScaleVec |
| ✓ | Ops::SI | https://github.com/scriptkitties/perl6-Ops-SI/pull/2 |
| ✓ | Perl6-Math-Quaternion | https://github.com/Util/Perl6-Math-Quaternion/pull/7 |
| ✓ | ScaleVec | https://github.com/samgwise/p6-ScaleVec/pull/1 (@sylints++) |
| ✓ | Stats | https://github.com/MattOates/Stats/pull/7 (@sylints++) |
| 🐦 | ANTLR4::Grammar | toaster flop, installs fine locally |
| 🐦 | Cro::HTTP::Session::Redis | toaster flop, installs fine locally |
| 🐦 | Number::Denominate | toaster flop, installs fine locally |

Those marked with ✓ had an issue described in this ticket and were fixed.
