### ISSUE TITLE
Fancy chars in filenames don't work right on Windows

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1737]
Don't know the actual cause and whether anything can be done about it, but using `"héllo.txt".IO.spurt: "foo";` on Windows creates a filename named `hÃ©llo.txt`

I found this workaround creates the desired filename: `"héllo.txt".encode("latin1").decode("utf8-c8").IO.spurt: "foo";` Hopefully this can be fixed not to require the workaround.

This is on Windows7 with rakudo 2017.07 and original user [on IRC](https://irclog.perlgeek.de/perl6/2018-04-16#i_16053133) had the same problem on French Windows 7 with rakudo 2018.03-209-g28c9ae4fa

**Comment by zoffixznet** [comment]
Likely similar issue, but if you `dir` the directory where that file was created and try to .slurp the returned object, it fails to find the file:

```
[assume héllo.txt is created] for dir(test => /.txt/) -> $file { say $file.IO.slurp; } # --> Failed to open file...
```

I also cooked up this workaround one can stick at the top of the program to wrap `.IO` method to apply the fix to encoding:

```
for Str, IO::Path { with .^lookup: 'IO' { .wrap: -> \p { IO::Path.new: (p ~~ Str ?? p !! p.absolute).encode("latin1").decode: "utf8-c8" } } }
```

**Comment by jeckyhl** [comment]
the problem does no longuer occurs with recents versions of Rakudo (ok with Rakudo version 2020.05)

**Comment by JJ** [comment]
I think that we might need a test to close this, but thanks for reporting.

**Comment by patrickbkr** [comment]
I'm thining about how to best test this.
Generating a file with a respective name and checking the name is a bit pointless, as this bug would be transparent (the actual filename could be wrong, but Raku land wouldn't notice). Adding a file with a fancy char to the repo is fragile as all the tools involved in putting the files on the filesystem (git, zip, tar, the filesystem itself, ...) can potentially break the test by not dealing with the fancy char filename correctly.
Any ideas?

**Comment by lizmat** [comment]
closing as untestable
