### ISSUE TITLE
Unintended consequences of converting routines from `only` to `multi`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1739]
(Originally reported on https://github.com/rakudo/rakudo/issues/1566#issuecomment-382105012)

We recently converted a bunch of `only` routines to `multi` in an effort to let users add own candidates. That created an originally unforeseen effect:

```
> say dir.sort(&lc)
Cannot resolve caller lc(IO::Path, IO::Path); none of these signatures match:
    (Cool $s)
```

Some routines can no longer be used as matchers or `Callable` args to some of the routines, because their `.count` is now reported as `Inf` instead of the actual count the sub used to have, because it's being reported for the proto:

```
$ ./perl6 -e 'sub z($) {}; say &z.count'
1
$ ./perl6 -e 'multi z($) {}; say &z.count'
Inf
$ ./perl6 -e 'multi z($) {}; say &z.candidates».count'
(1)
```

One potential fix is adding correct args to affected protos, but I don't know if that defeats the whole "let users add more candidates" thing that started this process.

```
$ ./perl6 -e 'proto z($) {*}; multi z($) {}; say &z.count'
1
```

Or maybe go the other way and make all the stuff that cares about `.count` instead collect largest `.count` from all the candidates of the multies?

**Comment by zoffixznet** [comment]
This one is even worse:

```
Zoffix │ c: 2018.02,HEAD dd <2 4 10 13 31337>.grep(&is-prime).head.^name                                                                                      Zoffix, ¦2018.02: «"IntStr"␤» ¦HEAD(ceeb3a0): «"List"␤»
```

The infinite `.count` makes `.grep` return a list of single-item lists

**Comment by jnthn** [comment]
> One potential fix is adding correct args to affected protos, but I don't know if that defeats the whole "let users add more candidates" thing that started this process.

I think it's fair enough to do this, provided the `proto` is like `($, *%)` or some such (that is, it admits candidates that accept adverbs). That means it can be extended both by type and by extra adverbial arguments, which I think should be sufficient extensibility for most practical needs. If not, folks can declare their own `proto` and delegate things they don't handle to the `CORE` one. (Yes, this is a tad inconvenient, but so is breaking somebody's innocent-looking `.map(&lc)`, so I think making that not entirely trivial will give people pause for thought in a place where they probably need to think.)

**Comment by zoffixznet** [comment]
Thinking more of it, feels like adding constrained protos is not the best of ideas.

* Doing so blocks off user's multies that use more positionals
    * Yes, they define their own proto, but they have to make it shuttle stuff to core ops, because the proto blocks off visibility of all core candidates
* It's very fragile, both in terms that we in core and users in their code need to remember to provide proper protos AND to ensure the protos match all the available candidates so none are blocked off by the proto's sig.

Basically, we're making it so the system depends on some manual step that isn't correlated to the `.sort`, or whatever, choosing which form to call. And requiring that step means potential for bugs.

I think we should make the stuff that checks `.count` to go through candidates and figure out what the largest count is based on that. And that's a perf loss, but it can be rectified by adding some `.apparent-count` method or something, calling which makes the dispatchers return the cached value of the largest count of its candidates (non-dispatchers would return their actual `.count`) and that cached value would be updated when `.add_dispatchee` is called to add a candidate (I'm just assuming that's how candidates are added; haven't actually looked)
