### ISSUE TITLE
Clunky expression in error message ("Useless use")

### ISSUE THREAD

**Issue by COMBORICO** [rakudo/rakudo#1748]
## The Problem

Useless use of "sqrt $five" in expression "sqrt $five" in sink context (line 2)

Error message sounds robotic, strange use of English.

## Expected Behavior

Ineffectual use of...

## Steps to Reproduce
my $five = 5;
sqrt $five;
say $five;

(This must be done in a script, not REPL.)

Also:

sub do_twice($code) {$code; $code}
WARNINGS for <unknown file>:
Useless use of $code in sink context (line 1)
sub do_twice ($code) { #`(Sub|94507960233504) ... }

**Comment by usev6** [comment]
The phrase 'useless use of' has some interesting background, cmp. http://porkmail.org/era/unix/award.html

I like the error message and IMHO it would be a pity to drop the 'use of' part.

**Comment by COMBORICO** [comment]
Yeah, "useless use of" is fine.  Sorry for taking up yall's time.  Thanks for responses!  Closing.
