### ISSUE TITLE
Bus error on armhf

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1751]
This ticket is just a reference to https://github.com/perl6/nqp/issues/431, marked as a blocker to make sure we take a look at it before the release.

**Comment by AlexDaniel** [comment]
OK there's one patch waiting for confirmation, so we have some progress on it.

This doesn't stop the next release given that for debian they'll be able to patch things like this on top of the 2018.04 release, so I'm removing the label.

Keeping the ticket open to track other bus errors on armhf.

**Comment by patrickbkr** [comment]
As far as I can tell there are no known "bus error" problems on armhf any more. Closing.
