### ISSUE TITLE
Multiple errors/crashes when running nqp tests and spectest with FSA_SIZE_DEBUG=1

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#1752]
nwc10++ noticed that several nqp tests caused asan to complain bitterly. The asan output looks like this:

    ./nqp t/serialization/01-basic.t
    
    ok 690 - $b is positive for 2 ** 13
    =================================================================
    ==24267==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61600213f288 at pc 0x7f1305b4151a bp 0x7fffbeb1ec80 sp 0x7fffbeb1ec78
    WRITE of size 8 at 0x61600213f288 thread T0
        #0 0x7f1305b41519 in MVM_sc_add_all_scs_entry src/6model/sc.c:78
        #1 0x7f1305b4058f in MVM_sc_create src/6model/sc.c:11
        #2 0x7f130585da6a in MVM_interp_run src/core/interp.c:3023
        #3 0x7f1305d46c4b in MVM_vm_run_file src/moar.c:407
        #4 0x402c47 in main src/main.c:299
        #5 0x7f130460cd1c in __libc_start_main (/lib64/libc.so.6+0x1ed1c)
        #6 0x4014c8 (/home/nicholas/Sandpit/moar-san/bin/moar+0x4014c8)
    
    0x61600213f288 is located 0 bytes to the right of 520-byte region [0x61600213f080,0x61600213f288)
    allocated by thread T0 here:
        #0 0x7f13083d362f in __interceptor_malloc ../../.././libsanitizer/asan/asan_malloc_linux.cc:72
        #1 0x7f1305956ac2 in MVM_malloc src/core/alloc.h:2
        #2 0x7f1305958c35 in MVM_fixed_size_alloc src/core/fixedsizealloc.c:178
        #3 0x7f1305958e0a in MVM_fixed_size_realloc_at_safepoint src/core/fixedsizealloc.c:233
        #4 0x7f1305b4127a in MVM_sc_add_all_scs_entry src/6model/sc.c:71
        #5 0x7f1305b4058f in MVM_sc_create src/6model/sc.c:11
        #6 0x7f130585da6a in MVM_interp_run src/core/interp.c:3023
        #7 0x7f1305d46c4b in MVM_vm_run_file src/moar.c:407
        #8 0x402c47 in main src/main.c:299
        #9 0x7f130460cd1c in __libc_start_main (/lib64/libc.so.6+0x1ed1c)
    
    SUMMARY: AddressSanitizer: heap-buffer-overflow src/6model/sc.c:78 MVM_sc_add_all_scs_entry
    Shadow bytes around the buggy address:
      0x0c2c8041fe00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c2c8041fe10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c2c8041fe20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c2c8041fe30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c2c8041fe40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    =>0x0c2c8041fe50: 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c2c8041fe60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c2c8041fe70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c2c8041fe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c2c8041fe90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c2c8041fea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    Shadow byte legend (one shadow byte represents 8 application bytes):
      Addressable:           00
      Partially addressable: 01 02 03 04 05 06 07
      Heap left redzone:       fa
      Heap right redzone:      fb
      Freed heap region:       fd
      Stack left redzone:      f1
      Stack mid redzone:       f2
      Stack right redzone:     f3
      Stack partial redzone:   f4
      Stack after return:      f5
      Stack use after scope:   f8
      Global redzone:          f9
      Global init order:       f6
      Poisoned by user:        f7
      Contiguous container OOB:fc
      ASan internal:           fe
    ==24267==ABORTING

Some manual bisecting points to the culprit being https://github.com/MoarVM/MoarVM/commit/a7bb6f0d2797e9eeb049ae05bf8f8caa9d3ba86b

It should be noted that the problem doesn't seem to cause any crashes if FSA_SIZE_DEBUG=0 but perhaps that is due to chance.

**Comment by AlexDaniel** [comment]
To uneducated me that looks like something we want to fix before the release, or at least take a look at. Please let me know what you think. @jnthn @timo @bdw @niner

**Comment by timo** [comment]
it was a bug in the FSA_SIZE_DEBUG implementation, since that's not for end-users, i'd say it's fine. but also it's now fixed with https://github.com/MoarVM/MoarVM/commit/05d589e5cd8f36e672f6d38e0325db0c57b3e8c8 so that's also good :)
