### ISSUE TITLE
Iterable appearing in subset constraints

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1753]
Code:
```perl6
say 42;
subset ZInt of Cool where { say $_; True };
sub foo(ZInt(Cool) $Z) {}
```

Output (2015.12⌁2018.03):
```
42
```

Output (HEAD(1c6701b)):
```
(Iterable)
42
```
Pretty sure this Iterable should not be appearing there.

This is causing an issue with [Chemistry::Elements](https://github.com/briandfoy/perl6-chemistry-elements) module ([code](https://github.com/briandfoy/perl6-chemistry-elements/blob/2283553c295d1b664234c5428e9c7acd91bf962d/lib/Chemistry/Elements.pm6)).

Bisected to (2018-04-04) https://github.com/rakudo/rakudo/commit/82b19b1f533fc43531906edf379796e6a4af9493

I think the commit is revertable, but I haven't tried yet.

**Comment by zoffixznet** [comment]
> Then it's legit that a test of Iterable  against such a subset

But there's no explicit test of anything in user's code. The sub is never even invoked.

And since you can't pun `Iterable`, subsets of Cool now crash pretty much on everything:

```
<Zoffix___> c: 2018.02,HEAD subset ZInt of Cool where *.elems; sub foo(ZInt(Cool) $Z) {}; say "OK"
<committable6> Zoffix___, ¦2018.02: «OK␤» ¦HEAD(92eaa11): «===SORRY!===␤Method 'iterator' must be implemented by Iterable because it is required by roles: Iterable.␤ «exit code = 1»»
```

**Comment by jnthn** [comment]
> But there's no explicit test of anything in user's code.

If the compiler isn't allowed to do type checks, then we're going to be a bit limited in what we can do. ;-) But yes, I think it's probably reasonable that we restrain ourselves from checks that would invoke `where` 
clauses, at least when we're not considering a value that appears - perhaps through a constant fold - in the program.
