### ISSUE TITLE
Awaiting a new promise hangs

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#1757]
Try to run any line of this code:

```perl6
await Promise.new;
await Promise.new.then({ 1 });
await Promise.new.then({ .result });
```

Each line hangs on OpenBSD 6.3 and FreeBSD 11.1-RELEASE-p8. I think `.result` blocking until the promise is kept/broken may be responsible, since it blocks until a vow is kept or broken, but that's not possible anymore.

**Comment by jnthn** [comment]
Well, yes. And `loop { }`, `for ^Inf { }`, and `sleep;` also hang. What's the supposed problem here?

**Comment by Kaiepi** [comment]
I feel like it should throw since it's reasonably possible to try to write this:

```perl6
my Promise $p .= new;
$p.keep(1);
await $p.then({ .result + 1 });
```

But forget a line and end up with:

```perl6
my Promise $p .= new;
await $p.then({ .result + 1 });
```

**Comment by Kaiepi** [comment]
Also, new promises in other languages are used the same was as `Promise.start` is here, so it's possible to write without thinking. I don't feel it could happen as easily as creating an infinite loop or sleeping forever

**Comment by AlexDaniel** [comment]
Yes but then this works:
```perl6
my Promise $p .= new;
start { sleep 5; $p.keep(1) };
say await $p.then({ .result + 1 });
```

So there's nothing wrong with awaiting a new promise. And I'm not sure if we can know whether something will eventually keep it or not…

I think this ticket is rejectable.

**Comment by Kaiepi** [comment]
>What is "it" here? Are you proposing a static data flow analysis and the compiler throwing? Or some kind of runtime solution?

I meant a runtime solution. I don't think the compiler should be handling exceptions for this.

 >Note however, there are other means to await a Promise, such as a react block:

True, but this still hangs on my system.

**Comment by jnthn** [comment]
> I think the original proposal is to make await throw if asking to await an unvowed Promise.

That won't happen, because we don't insist on people using the `vow` mechanism.

> I meant a runtime solution. 

Given the above constraint, what would this look like?

> True, but this still hangs on my system.

There's no "on my system"; you're observing portable, by-design, behavior.
