### ISSUE TITLE
Ancestor's submethods are typo-suggested when you try to call a submethod on a kid

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1758]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

```
01:11 | Zoffix | m: class A { method meth { say "meth in A" }; submethod submeth { say "submeth in A" } }; class B is A {}.submeth
-- | -- | --
01:11 | camelia | rakudo-moar a138dcf50: OUTPUT: «No such method 'submeth' for invocant of type 'B'. Did you mean 'submeth'?␤  in block <unit> at <tmp> line 1␤␤»
```

```
$ perl6 -e 'class A { submethod z {} }; class B is A {}.z'
No such method 'z' for invocant of type 'B'. Did you mean 'z'?

$ perl6 -v
This is Rakudo version 2018.03-236-gdb8b218f6 built on MoarVM version 2018.03-112-gfa0fc1832
implementing Perl 6.c.
```

I'm assuming it can see that it's a submethod of an ancestor, so it should probably say something along the line that submethods aren't inherited.

**Comment by MasterDuke17** [comment]
I suggest two outcomes for this.

First, if the method is a parent's submethod, give a specific error that those aren't inherited. It might be as simple as changing [this](https://github.com/rakudo/rakudo/blob/master/src/core/Exception.pm6#L174-L179) loop to not do the `>>.name` on the `Methods` and then `.^name` will give `Method` or `Submethod`, so then just return with the more specific error message if `.^name eq 'Submethod' and .name eq $.method`.

Second, don't include parent's submethods in the list of suggestions. If the first suggestion is implemented it should be pretty easy, just skip any thing where `.^name eq 'Submethod`. If the first suggestion is decided against, another way to accomplish this might be adding an option to [`method methods`](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/MethodContainer.nqp#L44-L66) that doesn't include results from the `submethod_table` if set.

**Comment by MasterDuke17** [comment]
Fixed in https://github.com/rakudo/rakudo/commit/b02a74139886605b3963dd1581db9c9740a2b33f

**Comment by Altai-man** [comment]
@MasterDuke17 but what about tests?

**Comment by MasterDuke17** [comment]
> @MasterDuke17 but what about tests?

Rakudo tests were added in that commit.
