### ISSUE TITLE
JVM build is busted

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1765]
Error during the build: https://gist.github.com/AlexDaniel/a3ff8848f785bb1e8a02da21e93cdcd3

Regressed after [this commit](https://github.com/rakudo/rakudo/commit/4b5d36f3a8), but it probably just exposes a different issue ([RT#126702](https://rt.perl.org/Ticket/Display.html?id=126702)?).

IRC discussion: https://irclog.perlgeek.de/perl6-dev/2018-04-22#i_16078190

**Comment by zoffixznet** [comment]
Reproed the crash: https://gist.github.com/zoffixznet/136495e58a008e8f5425d1292e6aefe2

**Comment by zoffixznet** [comment]
pmurias++ fixed in in https://github.com/rakudo/rakudo/commit/1ae4d2d426

Confirming the fix fixes the issue on my box.
