### ISSUE TITLE
Incorrect Unicode character names

### ISSUE THREAD

**Issue by chansen** [rakudo/rakudo#1770]
`.uniname` returns incorrect names for CJK Ideographs and Tangut Ideographs:

```Perl6
say .uniname for (0x4E00, 0x17000);
```
Output:
```
<CJK Ideograph-4E00>
<Tangut Ideograph-17000>
```
The correct Unicode names are:
```
CJK UNIFIED IDEOGRAPH-4E00
TANGUT IDEOGRAPH-17000
````
Looks like the existing names are derived from the meta name ranges in `UnicodeData.txt`.

The Unicode Name Derivation Rule Prefix Strings is documented in [Table 4-8. Name Derivation Rule Prefix Strings](https://www.unicode.org/versions/Unicode10.0.0/ch04.pdf#G144161).

--
chansen

**Comment by AlexDaniel** [comment]
Output on all releases:
```
«2015.09,2015.10,2015.11,2015.12,2016.01.1,2016.02,2016.03,2016.04,
  2016.05,2016.06,2016.07.1,2016.08.1,2016.09»:
<CJK Ideograph>
<illegal>

¦«2016.10,2016.11,2016.12,2017.01,2017.02,2017.03,2017.04.3,2017.05,
  2017.06,2017.07,2017.08,2017.09»:
<CJK Ideograph>
<Tangut Ideograph>

¦«2017.10,2017.11,2017.12,2018.01,2018.02.1,2018.03,HEAD(79ed89b)»:
<CJK Ideograph-4E00>
<Tangut Ideograph-17000>
```

**Comment by samcv** [comment]
@chansen thank you for this bug report. I will fix the CJK unified ideographs, but I will have to make sure it doesn't break anybodies code if I remove the angle brackets (since as you can see by @AlexDaniel's post they have been around forever). @AlexDaniel thoughts?

**Comment by AlexDaniel** [comment]
@samcv go for it, we'll see issues in modules next time we run toaster (which typically happens twice a month at least).

**Comment by samcv** [comment]
This issue has been fixed as of Rakudo rakudo/rakudo@94b4783df 

MoarVM commits to fix this were moarvm/moarvm@5728e1f39 and moarvm/moarvm@e7d79d869

@chansen please reopen and comment if there are any issues.

**Comment by chansen** [comment]
@samcv++ The returned name for Ideographs is now correct,  but unfortunately I have found a couple more issues.

Character names for Hangul Syllables and Jamo should be in uppercase:

`0xAC00.uniname` returns `Hangul Syllable GA` which is incorrect. 

[Unicode 4.8](https://www.unicode.org/versions/Unicode10.0.0/ch04.pdf#G135165): 
Only Latin capital letters A to Z (U+0041..U+0056), ASCII digits (U+0030.. U+0039), U+0020 space, and U+002D hyphen-minus occur in character names.

May I also suggest that Perl6 is consistent with Unicode when it comes to [Code Point Labels](https://www.unicode.org/versions/Unicode10.0.0/ch04.pdf#G135875):

`0xD800.uniname` returns `<Non Private Use High Surrogate-D800>` but Unicode recommends `<private-use-D800>`.

--
chansen

**Comment by AlexDaniel** [comment]
Alternatively, let's test uninames against this file: https://www.unicode.org/Public/10.0.0/ucd/extracted/DerivedName.txt (@chansen++)

I tried this script and only Hangul Syllables are not matching:
```perl6
for ‘DerivedName.txt’.IO.lines {
    next unless $_; # empty
    next if /^‘#’/; # comment
    my ($xcode, $name) = .split(‘;’)».trim;
    next if $xcode.contains(‘.’); # TODO Entries with trailing -* should be replaced with -%.4X, ordinal
    $xcode .= parse-base: 16;
    .say if $xcode.uniname ne $name
}
```

**Comment by samcv** [comment]
@AlexDaniel looks like DerivedName.txt was added in 10.0.0. Wish they had that earlier!

**Comment by samcv** [comment]
I have fixed the Hangul characters. I will get to the Private use and surrogates shortly.

**Comment by AlexDaniel** [comment]
Thank you for your work, @samcv.

**Comment by coke** [comment]
Reran this on head, generates no output. closing ticket.
