### ISSUE TITLE
Test.pm6 subs need to avoid containerizing arguments

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1771]
Because it affects how stuff is matched. `is-deeply` is one of such subs; I'm guessing `cmp-ok` is similarly affected and basically all of the routines in Test.pm6 need to be audited for this issue:

```
11:26 | lizmat | m: use Test; my %h = a => Mu; is-deeply %h, %h  # disappointing  :-(
-- | -- | --
11:26 | camelia | rakudo-moar 79ed89ba4: OUTPUT: «Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)␤  in sub _is_deeply at /home/camelia/rakudo-m-inst-1/share/perl6/sources/C712FE6969F786C9380D643DF17E85D06868219E (Test) line 651␤  in sub is-deeply at /home/camelia/…»

11:29 |   | m: my %h = a => Mu; say %h eqv %h
-- | -- | --
11:29 | camelia | rakudo-moar 79ed89ba4: OUTPUT: «True␤»
11:29 | Zoffix | huh
11:32 |   | m: my %h = a => Mu; say $%h eqv $%h
11:32 | camelia | rakudo-moar 79ed89ba4: OUTPUT: «Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)␤  in block <unit> at <tmp> line 1␤␤»
11:33 | Zoffix | s: &infix:<eqv>, do { my %h = a => Mu; \(%h, %h)}
11:33 | SourceBaby | Zoffix, Sauce is at https://github.com/rakudo/rakudo/blob/79ed89ba4/src/core/Map.pm6#L446
11:33 | Zoffix | s: &infix:<eqv>, do { my %h = a => Mu; \($%h, $%h)}
11:33 | SourceBaby | Zoffix, Sauce is at https://github.com/rakudo/rakudo/blob/79ed89ba4/src/core/Map.pm6#L446
11:33 | Zoffix | Ah, the non-conted version goes through the eqaddr fast-past

```

The fix in most cases would be just changing `$foo` param to `\foo` or adding `is raw` trait if sigil has to be kept.

**Comment by jnthn** [comment]
I suspect this will not be so simple, because people *will* have relied on top-level containerization not mattering when writing tests with `is-deeply`. (How do I know? Because I've got such tests.)

**Comment by zoffixznet** [comment]
`is-deeply` is becoming a monster 😃 It already does different things than `eqv` with `Seq`s. Now containerization is in play.

I can argue for making it stay the way it is too: the `eqaddr` fast-path in OP code hides the explosion due to `Mu`s that would occur anytime first arg is not the same object as the second arg.

**Comment by jnthn** [comment]
To be clear, I'm not (yet :grinning:) arguing for any particular behavior (current or different), just noting that we may well quite a lot of reliance on the current behavior. Either way, we want to nail down and document want the semantics are, though. :-)
