### ISSUE TITLE
Add "new-from-file" to CompUnit::PrecompilationID

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1776]
Very few modules, if any, use the precompilation facilities of Perl 6. One which does is [Pod::To::BigPage](https://github.com/perl6/perl6-pod-to-bigpage). However, it does have to `use nqp` for something which is probably an implementation detail, how IDs are computed from, well, things. It would be much more transparent, and implementation-independent, not to mention avoid going to the hardly documented nqp, to add `new-from-file` or `-from-filename` to the module above.

**Comment by lizmat** [comment]
Closing since there are other alternatives to Pod::To::BigPage being developed based on RakuDoc v2.0.
