### ISSUE TITLE
Implementing a CArray.allocate method

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#1778]
Currently it's possible to allocate some memory for a `CArray` like this:

```perl6
my CArray[uint8] $ptr .= new;
$ptr[4096 - 1] = 0;
```

Or:

```perl6
my CArray[uint8] $ptr .= new: 0 xx 4096;
```
But this isn't very clear. You could use a `Buf`/`Blob` to allocate memory like this, but I feel like `CArray` should be able to as well to make it easier to pass to other NativeCall functions. Would this be a good idea to add?

**Comment by jnthn** [comment]
Feels appropriate to me.
