### ISSUE TITLE
callframe info changes inside multi sub

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1781]
## The Problem

Multiple calls to a `multi sub` that does a `callframe` with a fixed index, produces different results between the first and subsequent calls.  Perhaps the proto is removed after the first call at that callsite?

## Expected Behavior

Multiple calls should produce the same result every time.

## Actual Behavior

They're different.

## Steps to Reproduce

    $ 6 'multi sub a() { dd callframe(2).my }; a; a; a'
    {"!UNIT_MARKER" => !UNIT_MARKER, "\$!" => Nil, "\$/" => Nil, "\$=finish" => Mu, "\$=pod" => [], "\$?PACKAGE" => GLOBAL, "\$_" => Any, "\$¢" => Nil, "\&a" => sub a (;; Mu | is raw) { #`(Sub|140354580098856) ... }, "::?PACKAGE" => GLOBAL, :EXPORT(EXPORT), :GLOBALish(GLOBAL)}
    {}
    {}

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

This is Rakudo version 2018.04-20-g7847768 built on MoarVM version 2018.04-34-g25f165a

**Comment by jnthn** [comment]
> Perhaps the proto is removed after the first call at that callsite?

Yes, an onlystar `proto` will be skipped on subsequent calls in the case that the candidate can be resolved through the multi-dispatch cache.

There's two sets of `nqp` ops for traversing the caller chain, one that tells the truth and one that lies about onlystar `proto`s and other thunk-y things. The `CALLER::` mechanism and various other things use the lying ops, while `callframe` was still using the honest ones. Fixing it to use the lying ones gives:

```
$ ./perl6-m -e 'multi sub a() { dd callframe(1).my }; a; a'
{"!UNIT_MARKER" => !UNIT_MARKER, "\$!" => Nil, "\$/" => Nil, "\$=finish" => Mu, "\$=pod" => [], "\$?PACKAGE" => GLOBAL, "\$_" => Any, "\$¢" => Nil, "\&a" => sub a (;; Mu | is raw) { #`(Sub|45835864) ... }, "::?PACKAGE" => GLOBAL, :EXPORT(EXPORT), :GLOBALish(GLOBAL)}
{"!UNIT_MARKER" => !UNIT_MARKER, "\$!" => Nil, "\$/" => Nil, "\$=finish" => Mu, "\$=pod" => [], "\$?PACKAGE" => GLOBAL, "\$_" => Any, "\$¢" => Nil, "\&a" => sub a (;; Mu | is raw) { #`(Sub|45835864) ... }, "::?PACKAGE" => GLOBAL, :EXPORT(EXPORT), :GLOBALish(GLOBAL)}
```

Which'd seem to be what you were after. The spectest seems happy enough with this change, so I've committed it; now all that's needed is a test, which I'll leave for somebody else.

**Comment by lizmat** [comment]
Interestingly, this fix makes my code need to take into account different pre and post https://github.com/rakudo/rakudo/commit/0d216befba336b1cd7a0b424cddc91a52d2f4aca behaviour.

I wouldn't be surprised if this change is going to have some ecosystem fallout  :-(

**Comment by jnthn** [comment]
Yeah, I found it hard to guess at that, but figured we've plenty of time until the next release to find out.

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/30c042c102 .  Closing.
