### ISSUE TITLE
Rat.Num does not choose the closest representable Num

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1782]
(filing for myself to remember to double-check as part of the CaR grant)

While fixing recent num parsing issues, I noticed that `nqp::div_In` on MoarVM did not always pick closest representable Num. While I had some local MoarVM modifications in place, I was able to repro the bug with `say 704387785625256607/10**91 == 70438778562525660700/10**93` giving `False`.

Now it's giving `True` and I'm failing to repro the bug, but I don't see why it'd get fixed and I suspect the point where it's failing to pick the closest representable num just shifted off and this will need to be covered by more robust tests.

(the bug itself is 20% likely to be in `MVM_bigint_div_num` and 80% likely to be in `mp_get_double`)

**Comment by lizmat** [comment]
Closing as not reproducible
