### ISSUE TITLE
"equal requires a concrete string, but got null"

### ISSUE THREAD

**Issue by smls** [rakudo/rakudo#1785]
## The Problem

A personal Perl 6 program of mine that used to work with old versions of Rakudo, now pretty reliably dies a few seconds in with

    equal requires a concrete string, but got null

I'd rather not publish the program (especially since the way it operates is entangled with my local file-system); If I manage to produce a golfed test-case, I'll post that.  
For now, here's a description of what the program does and the `-ll-exception` stack traces for a few runs:

https://gist.github.com/smls/a0995099890639493886d042bb2d2a73

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by smls** [comment]
No, I can't seem to reproduce this anymore with recent Rakudo.
Since I never got around to golfing it down to a proper test-case, I think it's best to just close this ticket.
