### ISSUE TITLE
Submethods are included in the list of suggested methods for child classes

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#1786]
However, they actually aren't callable. This leads to code such as `class A {method a{}; submethod b{}}; class B is A {}; B.new.b` giving the LTA error message `No such method 'b' for invocant of type 'B'. Did you mean any of these?␤    a␤    b`.

**Comment by zoffixznet** [comment]
Looks to be the same as https://github.com/rakudo/rakudo/issues/1758 ?

**Comment by MasterDuke17** [comment]
Doh, it is, closing now.
