### ISSUE TITLE
list of old 'Roast rakudo skip/todo test' from RT tickets that need to be closed

### ISSUE THREAD

**Issue by skids** [rakudo/rakudo#1797]
This is a github ticket to help cleaning up certain old tickets from RT which
need attention from someone with special RT foo.  Such tickets that can be
closed in RT can be listed here.

Specifically, this is for a number of RTs that were added by script which simply list a line
in a roast file that was marked skip/todo.  Some technical quirk prevents many
RT users from commenting on or closing out these tickets... otherwise they could
just be closed or diagnosed normally.  Often the issues they address get fixed
but then the RT ticket never gets closed.

If you know one of these RTs has been fixed, or if a github issue has been
opened to take its place, please identify it and explain the fix for historical purposes
here, and keep this ticket open until they are all done... you know... some day.

Hopefully someone with the ability to clear these RT tickets will happen across this ticket
and close the listed RTs. occasionally.

**Comment by usev6** [comment]
I've closed RT #124738.

**Comment by skids** [comment]
#124552 can be closed.  Test was working but skipped.  Unskipped in roast now.

**Comment by usev6** [comment]
I've closed RT #124552.

**Comment by thundergnat** [comment]
RT #124815 can be closed. It was a bogus test which has now been fixed with this commit. https://github.com/perl6/roast/commit/771a2bbeb1bfc8f3975b6e247c84125ce1643d9c

**Comment by thundergnat** [comment]
#124814 can be closed. Bogus test, fixed with this commit. https://github.com/perl6/roast/commit/14f5138f07a68742551f6dc499f15fe2a040d17e

**Comment by usev6** [comment]
Both, RT #124815 and RT #124814, have been closed by Zoffix++

**Comment by usev6** [comment]
I don't think we need this issue any longer. RT is no more and the tickets have been transferred to https://github.com/Raku/old-issue-tracker/.

Also some cleanup has been done in the meantime: @lizmat++ has updated most references to RT tickets, so that they point to github now. Also, I've closed the majority of the above mentioned automatically created RT ticket with https://github.com/Raku/roast/pull/556
