### ISSUE TITLE
Parameter of subset type in multi dispatch with default value fails in runtime.

### ISSUE THREAD

**Issue by cono** [rakudo/rakudo#1801]
## The Problem

Parameter of subset type in multi dispatch with default value fails in runtime.
```
subset CAT of Code where {.arity == 2}; multi xz(CAT :$x!) {$x(3,5).say}; multi xz(CAT $x = * <=> *) { say $x(3,5); }; xz()
```

## Expected Behavior

`Less` should be printed.

## Actual Behavior
```
Cannot invoke this object (REPR: Uninstantiable; CAT)
  in sub xz at -e line 1
  in block <unit> at -e line 1
```

## Steps to Reproduce
```
perl6 -e 'subset CAT of Code where {.arity == 2}; multi xz(CAT :$x!) {$x(3,5).say}; multi xz(CAT $x = * <=> *) { say $x(3,5); }; xz()'
Cannot invoke this object (REPR: Uninstantiable; CAT)
  in sub xz at -e line 1
  in block <unit> at -e line 1
```

## Environment
* Operating system: Gentoo
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.04.1-38-gede507b73 built on MoarVM version 2018.04-39-gc702f4c66
implementing Perl 6.c.

**Comment by dogbert17** [comment]
Fixed with the merge of new-disp, i.e. commit dd2b274fd59f18

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/83313e9e9d
