### ISSUE TITLE
Range.ACCEPTS gets some things wrong

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1809]
There are at least two, seemingly separate, bugs. (IRC: https://irclog.perlgeek.de/perl6/2018-05-09#i_16148196 )

#### 1. Smartmatch with another `Range` if it's given in a `Junction` doesn't get evaluated correctly:

```
p6: say 11..13 ~~ 1..12;
rakudo-moar e0ad668e2: OUTPUT: «False␤»

p6: say (5,6,11..13).all ~~ 1..12;
rakudo-moar e0ad668e2: OUTPUT: «all(True, True, True)␤»
```
The first one goes through `Range.ACCEPTS(Range)` candidate and gives the right answer. The second one goes through `Range.ACCEPTS(Mu)` candidate and that candidate seems to assume that if we got to that candidate the topic is neither a `Range` nor `Cool`, but that's not the case with `Junctions`. Personally, I don't quite understand why the comparison against whether the endpoint is excluded is made. That [comparison itself gives wrong result](https://irclog.perlgeek.de/perl6/2018-05-09#i_16148273), so this bug is nothing to do with Junction threading.

#### 2. Cool doesn't look to be compared right.

```
m: say "4" cmp 4
rakudo-moar e0ad668e2: OUTPUT: «Same␤»

m: say "4" ~~ 1..11
rakudo-moar e0ad668e2: OUTPUT: «False␤»

say 4 ~~ 1..11
e0ad668e2: OUTPUT: «True␤»
```

I would've though both comparisons against a `"4"` and `4` to yield the same results. Looking at the `Range.ACCEPTS(Cool)` candidate it seems it just does `before`/`after` comparisons, so `"4" ~~ 1..11` should probably give `True`,  yet the current result is `False`

**Comment by vrurg** [comment]
Fixed with #4653 and #4687
