### ISSUE TITLE
Recent regression "ctxlexpad needs an MVMContext"

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1810]
Spotted by @JJ in recent doc build https://travis-ci.org/perl6/doc/jobs/376963640#L1507-L1515 on e0ad668e228dba13147b28aacb0fe965d3d1db2f rakudo

```
An operation first awaited:
  in sub process-pod-dir at htmlify.p6 line 269
  in sub MAIN at htmlify.p6 line 200
  in block <unit> at htmlify.p6 line 1006
Died with the exception:
    ctxlexpad needs an MVMContext
      in sub extract-pod at /home/travis/build/perl6/doc/lib/Pod/Convenience.pm6 (Pod::Convenience) line 131
      in block  at htmlify.p6 line 264
```

Something gets inlined that shouldn't?

**Comment by AlexDaniel** [comment]
Any news on this? Is it still happening? Ping @JJ

**Comment by JJ** [comment]
Didn't happen again. Thanks!

**Comment by AlexDaniel** [comment]
https://github.com/perl6/doc/issues/1951#issuecomment-390418620

Is it because of the recent re-revert https://github.com/rakudo/rakudo/commit/fb0654cfb3bca6b8bcbf9ed01fc757871d5876df? Or is it this https://github.com/rakudo/rakudo/commit/849ba56d242b07a8c928ebb68eb41e94dd6de006?

**Comment by JJ** [comment]
Don't think so. This is in the docker container, which does not use HEAD. Looks like a different error:

```
# There's been this error in file: xt/trailing-whitespace.t
# Use of uninitialized value $repo-id of type Any in string context.
# Methods .^name, .perl, .gist, or .say can be used to stringi
# 
# There's been this error in file: xt/trailing-whitespace.t
# fy it to something meaningful.
# 
# 
# There's been this error in file: xt/trailing-whitespace.t
#   in any statement_control at /root/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
# Use of uninitiali
# 
# There's been this error in file: xt/trailing-whitespace.t
# zed value $repo-id of type Any in string context.
# Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
#   in any statement_control at /root/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
# 
# 
```

**Comment by zoffixznet** [comment]
Ran the build on HEAD (f98ea64de) a couple times, including after blowing all the `.precomp` folders.

Couldn't repro any problems (though haven't trived reproing OP issue on those commits on this box).

The fix could've been the revert in https://github.com/MoarVM/MoarVM/commit/a607c42f1bbb4136b6c7c4c328f73ebe897fd9d8 . Although it reverts a commit from 6 days earlier than the range listed in the OP. Don't know if that's not the reverted that (possibly) fixed the issue or the original range calculation is wrong.

**Comment by AlexDaniel** [comment]
OK, so let's call it a non-blocker then.

@JJ please let me know if there's any problem remaining.

**Comment by AlexDaniel** [comment]
For anyone reviewing this ticket months later, please just close it if there's no new info.

**Comment by rafaelschipiura** [comment]
@AlexDaniel That's an interesting method to test an intermittent bug.
