### ISSUE TITLE
ENTER fires twice in some(?) methods

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1815]
```perl6
class { method apply { ENTER say "[ENTER]"; say "In the method"; } }.apply;

# [ENTER]
# [ENTER]
# In the method

$ perl6 -v
This is Rakudo version 2018.04-20-g7847768 built on MoarVM version 2018.04-34-g25f165a
```

The same does not occur with a `LEAVE` phaser or if a subroutine is used:

```perl6
sub z { ENTER say "[ENTER]"; say "In the method"; }; z;
```

Committable says this has been the case in all the releases. I dumped the QAST and in the buggy version looks like the call to `ENTER` is duplicated. So likely we double-phaserize methods somewhere.

```perl6
Op (bind)
    Var (local __lowered_lex_2) <wanted> :statement_id<3>
    Op (call)
        WVal (Code) 
Op (bind)
    Var (local __lowered_lex_2) <wanted> :statement_id<3>
    Op (call)
        WVal (Code) 
```

---------

This bug was [originally found](https://irclog.perlgeek.de/perl6/2018-05-11#i_16155084) in a [more complex code](https://gist.github.com/zoffixznet/c5f1301ded57377a01b200aca3037c69) that involved protos, if the test writers would like to test that variant as well.

**Comment by lizmat** [comment]
The complex variant doesn't compile anymore.

Added test for the golfed version with https://github.com/Raku/roast/commit/3b53bff7c7
