### ISSUE TITLE
[JVM] Call to WHICH on capture with scalar container wrongly refers to type of value after preceding call on capture with non-container

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#1816]
## The Problem
The test for https://rt.perl.org/Ticket/Display.html?id=128977 in S02-types/capture.t fails on the jvm backend.

It looks like the second call to WHICH on a capture is confused be the preceding call and prints the type of the value instead of 'Scalar'.
```
$ ./perl6-j -e 'my $c1 = \(42); say $c1.WHICH; my $a = 42; my $c2 = \($a); say $c2.WHICH'
Capture|(Int|42)
Capture|(Int|1141817887)
```

On MoarVM the result looks fine:
```
$ ./perl6-m -e 'my $c1 = \(42); say $c1.WHICH; my $a = 42; my $c2 = \($a); say $c2.WHICH'
Capture|(Int|42)
Capture|(Scalar|34485429344)
```

Without the first call to WHICH the result looks fine with rakudo-j, too (it says 'Scalar' instead of 'Int'):
```
$ ./perl6-j -e 'my $a = 42; my $c2 = \($a); say $c2.WHICH'
Capture|(Scalar|1147359285)
```

BTW, it also happens if the first capture has a String and not an Int:
```
$ ./perl6-j -e 'my $c1 = \("foo"); say $c1.WHICH; my $a = 42; my $c2 = \($a); say $c2.WHICH'
Capture|(Str|foo)
Capture|(Int|787996824)
```

## Environment
* Operating system: FreeBSD 11.1-RELEASE-p4
* Compiler version (`perl6 -v`): This is Rakudo version 2018.04.1-70-gfebcb9177 built on JVM

**Comment by lizmat** [comment]
Assuming this is no longer an issue, please re-open if it is
