### ISSUE TITLE
Stringified Rat has trailing zeros

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1818]
(just filing as reminder for myself to look at as part of the grant; I'm suspicious of that trailing zero)

````
<Zoffix_> m: say <1/99999999999999999999>
<camelia> rakudo-moar febcb9177: OUTPUT: «0.000000000000000000010␤»
```

**Comment by thundergnat** [comment]
.say for 7/250378, 17/85099, 100/99953873, 777777/222222222, 331/20687744, 336/336005, 5/277777
>«0.0000280␤0.000200␤0.000001000␤0.00350000␤0.000016000␤0.0010000␤0.0000180␤»

Zoffix, Take a look at pull request https://github.com/rakudo/rakudo/pull/1822 which coincidentally addresses this among other things.

**Comment by dogbert17** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/e0dca0ccbddcd3b7911a47d6b478901adc135368

**Comment by ab5tract** [comment]
Tests added in [roast @ ee596d801f](https://github.com/Raku/roast/commit/ee596d801f)
