### ISSUE TITLE
non-interactive REPL mode breaks STDIN

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1824]
```
$ perl6 <<< get                                                                                                                                                                                                
Failed to stat file descriptor: Bad file descriptor
  in block <unit> at - line 1

$ echo 'get' | perl6 -
MVMArray: Index out of bounds
  in block <unit> at - line 1

$ perl6 -v
This is Rakudo version 2018.03-265-g656ff77b9 built on MoarVM version 2018.03-126-g876aa90ee
implementing Perl 6.c.
```

And the cause is:

```
$ echo '$*IN.native-descriptor.say' | perl6 -
-1
```

And the fix is to stick ` unless $filename eq '-'` for [the `.close` line in NQP](https://github.com/perl6/nqp/blob/7433cbed28e9366b4037ee475872958f9fbce650/src/HLL/Compiler.nqp#L415) (a few lines up, we use the same condition to [set that handle to stdin](https://github.com/perl6/nqp/blob/7433cbed28e9366b4037ee475872958f9fbce650/src/HLL/Compiler.nqp#L397-L399))

**Comment by uzluisf** [comment]
I already added:
```
unless $filename eq '-' {
     $in-handle.close;
}
```
in my local repo and running the same commands but I'm still getting the same output. I'm not sure what I should do next so any advice would be appreciated.

**Comment by zoffixznet** [comment]
Are you sure you rebuilt nqp and rakudo correctly? Which commands did you use?

**Comment by uzluisf** [comment]
I just used `make` and `make install`.

**Comment by uzluisf** [comment]
So I ran the commands to rebuild nqp and rakudo and everything went apparently fine.

After that, I executed `perl6 <<< get`, `echo 'get' | perl6 -` and `echo '$*IN.native-descriptor.say' | perl6 -` to check if the fix took effect but I'm getting the same output you detailed in the issue.

**Comment by uzluisf** [comment]
Yes, you're totally right. I was running the system's rakudo not the one I built. Sorry for that misunderstanding.

Regarding the commit message, can I reference the issue? I'm not really sure what I should put for the commit message.

**Comment by zoffixznet** [comment]
> Regarding the commit message, can I reference the issue? I'm not really sure what I should put for the commit message.

Yeah, if you include a link to it, GitHub will even reference the commit on this Issue.

Message could be something like

```
Do not close STDIN it is the source of the program

Fixes https://github.com/rakudo/rakudo/issues/1824
```
