### ISSUE TITLE
FYI: Renamed LHF label to "easy to resolve"/"good first issue" label pairs

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1825]
This just an FYI notification:

I renamed the "LHF" to a much easily understood "easy to resolve", which also should ease the fears a new contributor might have about starting to contribe.

I think GitHub pops up a notification to create "good first issue" labels in repo [and some repos follow it](https://www.google.ca/search?q=github+good+first+issue), so I created a second label for the same purpose—"good first issue".

This is done to encourage more people to dip their toes into the Rakudo codebase and hopefully start fixing more and more bugs.

**Comment by AlexDaniel** [comment]
FWIW This is right. Same change also happened in the doc repo [one month ago](https://github.com/perl6/doc/issues/1909#issuecomment-381029717).
