### ISSUE TITLE
<1i> should be a Complex literal, not ComplexStr

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1827]
When there are no spaces, we use the rule: if it contains an operator, create a numeric literal, otherwise, create an allomorph. So `<1/2>` has an operator, so it's a `Rat`, while `<1.2>` doesn't have an operator, so it's a `RatStr`. The `<1i>` does have a postfix operator, so it should come out as `Complex`, not a `ComplexStr`.

**Comment by lizmat** [comment]
Disagree: although complex values *are* implemented as postfix op, it is conceptually really notation, just like `<0x12>`, which **is** in `IntStr`.

So closing.
