### ISSUE TITLE
Regression exposed in Crane and other modules

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1832]
No golf yet, but stubbing this ticket anyway:

[Crane](https://github.com/atweiden/crane) module is failing some tests.

One of them:

```perl6
use Crane;
my %h = :a<alpha>,:b<bravo>,:c<charlie>;
my %expected = ("a",) => "alpha", ("b",) => "bravo", ("c",) => "charlie";
say Crane.flatten(%h)
```
```
¦2018.04:       «{[a] => alpha, [b] => bravo, [c] => charlie}␤»
¦HEAD(5ce2492): «{[c] => charlie}␤»
```

Bisected: (2018-05-12) https://github.com/rakudo/rakudo/commit/776ff354c3cfc09213723cd450900b5caee85a70

**Comment by AlexDaniel** [comment]
FWIW [Data::MessagePack](https://modules.perl6.org/dist/Data::MessagePack) is also affected.

[One](https://gist.githubusercontent.com/AlexDaniel/4d8b046c06f3dd5f4445f02ce7008177/raw/a0f9f34eaddcac3c0a7c0d82e9b44da0fa2d4714/202-unpack-int.t) of the failures:
```
1..2
Cannot invoke this object (REPR: Null; VMNull)
  in sub  at /home/bisectable/git/whateverable/data/all-modules/github/pierre-vigier/Perl6-Data-MessagePack/lib/Data/MessagePack/Unpacker.pm6 (Data::MessagePack::Unpacker) line 96
  in sub _unpack at /home/bisectable/git/whateverable/data/all-modules/github/pierre-vigier/Perl6-Data-MessagePack/lib/Data/MessagePack/Unpacker.pm6 (Data::MessagePack::Unpacker) line 130
  in sub unpack at /home/bisectable/git/whateverable/data/all-modules/github/pierre-vigier/Perl6-Data-MessagePack/lib/Data/MessagePack/Unpacker.pm6 (Data::MessagePack::Unpacker) line 123
  in sub unpack at /home/bisectable/git/whateverable/data/all-modules/github/pierre-vigier/Perl6-Data-MessagePack/lib/Data/MessagePack.pm6 (Data::MessagePack) line 11
  in block <unit> at /tmp/MbDLtO6drJ line 12

# Looks like you planned 2 tests, but ran 0
```

**Comment by zoffixznet** [comment]
Golf:

```
<Zoffix_> c: 2017.04.1,HEAD package Foo { our @bar = 1, |0 }; dd @::Foo::('bar')[^1]
<committable6> Zoffix_, ¦2017.04.1: «(1,)␤» ¦HEAD(5ce2492): «(Any,)␤»
```

**Comment by zoffixznet** [comment]
I started looking for a fix, but I noticed that the commit actually changes the semantics of array assignment. The assignment is meant to be mostly-eager and to reify non-lazy things *on assignment*. However, as the bisected commit's messages says, the change made it so *"[t]his then can lazily set up scalar containers and expand slips"*:

```
<Zoffix_> c: 2017.04.1,HEAD my @a = |(gather { say "hello"; }), 1;
<committable6> Zoffix_, ¦2017.04.1: «hello␤» ¦HEAD(5ce2492): «»
```

So I'd say we can't do this and the commit needs to be reverted.

------

Also, the commit title says *"Avoid calling STORE with huge number of arguments"*, but if I dump the pre-rewrite QAST, I see it being called with just a single arg:

```
- QAST::Op(callmethod STORE) <sunk nosink>
  - QAST::Var(lexical @a) <wanted sunk sinkok> @a
  - QAST::Op(callstatic &infix:<,>) <wanted> ,
    - QAST::Op(callstatic &prefix:<|>) <wanted> |
      - QAST::Op(callstatic &GATHER) <wanted>
        - QAST::Op(p6capturelex) <wanted sunk>
          - QAST::Op(callmethod clone) 
            - QAST::WVal(Block :cuid(1)) 
    - QAST::Want <wanted> 1
      - QAST::WVal(Int) 
      - Ii
      - QAST::IVal(1)  1
  - QAST::WVal+{QAST::SpecialArg}(Bool :named<initialize>) 
```

Nor are there any `.STORE` candidates that can take more than one arg:

```
<Zoffix_> m: [].^lookup('STORE').candidates».signature».say
<camelia> rakudo-moar 5ce24929f: OUTPUT: «(Array:D: Iterable:D \iterable, *%_)␤(Array:D: Mu \item, *%_)␤»
```

I think the Weekly said this fixed some JVM bug, but I suspect it just got swept under the rug.

@niner ping. Does the above assessment make sense? Should the commit be reverted?

------

Lastly, the bisected commit also introed this bug:

```
<Zoffix_> c: 2017.04.1,HEAD my @a; for ^5 { push @a, my @o = Empty, $_ }; say @a
<committable6> Zoffix_, ¦2017.04.1: «[[0] [1] [2] [3] [4]]␤» ¦HEAD(5ce2492): «[[4] [4] [4] [4] [4]]␤»
```

Both [first golf](https://github.com/rakudo/rakudo/issues/1832#issuecomment-389331520) and the above should be covered by tests for this ticket.

**Comment by niner** [comment]
The commit message is in error. It's not STORE that gets many arguments but &infix:<,> and that is what breaks JVM as on JVM a method call (which our sub calls compile to) may have at most 255 arguments.

I think my change can be salvaged though. We just have to add a call to $!todo.reify-until-lazy to the QAST.

**Comment by lizmat** [comment]
If you do this, could you add a more readable version of the nqp code that you’re generating as a comment?  This helps (me at least) a lot when trying to interpret the generated QAST  :-)

**Comment by zoffixznet** [comment]
> All three—the first golf, the reification regression at the top of this comment, and the last bug example above—should be covered by tests for this ticket.

There's a fourth bug. The `default` is being ignored:

```
19:26 		c: 2018.04, HEAD my @d is default(42) = 1, |2, Nil, 3; dd @d;
19:26 	committable6 	Zoffix, ¦2018.04: «Array @d = [1, 2, 42, 3]␤» ¦HEAD(a36adb2): «[1, 2, Any, 3]␤»
```

Also, looks like the change made performance worse (the `.eager` call is to equalize the bug of failing to reify on assignment on HEAD):

```
19:42 		c: 2018.04.1, HEAD for ^500 { my @a = 1, |^1000; @a.eager; Nil }; say now - ENTER now
19:42 	committable6 	Zoffix, ¦2018.04.1: «0.4575677␤» ¦HEAD(b8318b8): «1.20920365␤»
```

> to add a call to $!todo.reify-until-lazy

That fixed just one of the four bugs. Maybe calling `.is-lazy` on the array itself would help? Probably doesn't address the possible perf loss observed above.

I tried code-genning the `Array.STORE` code, but it needs to read `ArrayReificationTarget` the private type for it to work. Also, I now realize it ain't gonna work 'cause if I pass the `nqp::list` it doesn't expand the slips (and there did that Hash come from?). It would need the [`infix:<,>`'s slippification magic](https://github.com/rakudo/rakudo/blob/385308d35955c2848f58033a623a365439dcc622/src/core/List.pm6#L1541-L1589) to work right:

```
19:52 		c: 2018.04 my @d is default(42); use nqp; @d.STORE: nqp::list(1, |2, Nil, 3); dd @d;
19:52 	committable6 	Zoffix, ¦2018.04: «Array @d = [1, (2,), {}, 42, 3]␤»
``

I stashed the diff for that change here, if there's anything useful to pick from it: https://gist.github.com/zoffixznet/0015aa46075a0c3a970e2842916dac61

**Comment by zoffixznet** [comment]
Another thing I noticed is the bisected commit `nqp::create`s some stuff right in the Optimizer instead of `QAST::Op.new(:op<create>)`'ing it. Doesn't that re-use that object for all array assignments? Could that be the cause of some of the bugs?

**Comment by zoffixznet** [comment]
FWIW, while the bisected commit would avoid the 255+ item problem on JVM for arrays, it'd still exist in all the other places, like Hash assignment, won't it? So unless it provides some benefit on MoarVM too, I'd say revert it.

**Comment by usev6** [comment]
For the record, this was the issue with the 255+ item problem on JVM: https://github.com/rakudo/rakudo/issues/1817

Since it seems to be difficult to fix the regressions, I'd also vote for reverting.

> So unless it provides some benefit on MoarVM too, I'd say revert it.

I was under the impression that the main motivation for the patch was not the JVM breakage, but that a different code generation could help MoarVM, too: https://irclog.perlgeek.de/perl6-dev/2018-05-11#i_16156220 (and the following discussion). I don't know about the concrete effects (and trade-offs?), though.

**Comment by niner** [comment]
I pushed commit ac6e26e8fbcf2b22db01ac0c060b6c70e46d3c1e and commit 073a7f50f9dcd17e13a2d74c1c29aba4ed6717ce which seem to fix the golfed issues and Crane. The fourth bug seems to still be there but I don't think it's caused by my changes as it doesn't involve array initialization with a literal list.

**Comment by niner** [comment]
Btw. I have so far not seen any slow down. Quite contrary  for ^5000 { my @a = 1, |^1000; @a.eager; Nil }; runs in 3 seconds with my changes and in 4 seconds with everything reverted.

**Comment by niner** [comment]
I still get failures in one of Data::MessagePack's test files but that is clearly broken by hash randomization and unrelated to my changes.

**Comment by zoffixznet** [comment]
>  it doesn't involve array initialization with a literal list.

There are two assignments. The second one has a literal list.

> Unless my bench above is incorrect, it made things 2.5x slower.

That's no longer the case on HEAD. It's now ~2% faster than before all the work.

**Comment by niner** [comment]
Ah, I see it now. And could further golf it down:
nine@sphinx:~> perl6 -e 'say my @a = 1, 2, set()'
3
nine@sphinx:~> perl6 -e 'say my @a = 1, 2, 3'
[1 2 3]

So it's just that the my @a = ...; expression no longer returns @a. That sounds rather trivial after the other issues :)

**Comment by zoffixznet** [comment]
Looks like github no longer loads fresh comments onto the page unless you reload it manually.
