### ISSUE TITLE
Silent Whatevercode genning error

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1836]
## The Problem

    subset WalkCb of Callable where *.signature ~~ :(Int $);
    my WalkCb $x = sub (Int $a) { return $a }

fails with:

    Type check failed in assignment to $x; expected WalkCb but got Sub (sub (Int $a) { #`(Sub..

## Expected Behavior

    subset WalkCb of Callable where { .signature ~~ :(Int $) }
    my WalkCb $x = sub (Int $a) { return $a }

works as expected.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

This is Rakudo version 2018.04.1-91-gb8318b8 built on MoarVM version 2018.04.1-115-ga607c42

**Comment by lizmat** [comment]
Some more data points:

    my constant A = :(Int $);
    ===SORRY!===␤QAST::Block with cuid 1 has not appeared

**Comment by b2gills** [comment]
A `where` constraint can take a block (lambda) or a statement.

``` perl6
… where { $_ == 42 }; # block
… where    * == 42;   # lambda
… where   $_ == 42;   # statement
```

The thing is that `~~` doesn't participate in the creation of WhateverCode lambdas (`*`)  
So what you are really doing is creating a lambda of `*.signature` inside of a larger `where` **statement** (not lambda).

``` perl6
constant $lambda = *.signature;
subset WalkCb of Callable where $lambda ~~ :(Int $);
```

Which will of course never return `True` as the lambda has a signature of `:(;; $ is raw)`

---

So instead just write the statement form. (using implicit `$_`)

``` perl6
subset WalkCb of Callable where .signature ~~ :(Int $);
my WalkCb $x = sub (Int $a) { return $a }
say $x(42); # 42␤
```

---

It could be argued that `~~` should participate in WhateverCode lambdas, but that is a separate issue.

**Comment by lizmat** [comment]
Thanks for the explanation, also on SO!  Closing now
