### ISSUE TITLE
TODO: remove kludge in Str.perl after null str bug is resolved

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1837]
https://github.com/rakudo/rakudo/commit/b12fba38dd3c0f76b57d898c76646ef87c488703 adds a kludge to bail out if a string is null, however, the code shown in the commit message likely shouldn't have null strings in the first place as they cause issues in many other places:

```
m: -> Str $x { use nqp; dd $x ~ "" }((my str @)[1])
rakudo-moar 8ccda1890: OUTPUT: «concatenate requires a concrete string, but got null␤  in block <unit> at <tmp> line 1␤␤»
```

There's a possibly-incorrect PR in MoarVM to fix this bug: https://github.com/MoarVM/MoarVM/pull/767

When the bug is fixed, the kludge should be removed.

**Comment by lizmat** [comment]
It was decided that nqp::concat will not auto-vivify null strings.

Closing as WONTFIX
