### ISSUE TITLE
[JVM] Wrong results for Supply.from-list.rotor after recent optimization for @a.splice

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#1838]
## The Problem
Some tests started to fail on the JVM backend after the recent optimizations for @a.splice (a5d46b4273, maybe also 8d12d5b42d).

```
S17-supply/rotor.rakudo.jvm 3 - we can rotor with negative gap
S17-supply/rotor.rakudo.jvm 4 - we can rotor with negative gap without partial
S17-supply/rotor.rakudo.jvm 5 - we can rotor with negative gap with partial
S17-supply/rotor.rakudo.jvm 15 - we can rotor with multiple different gaps
S17-supply/rotor.rakudo.jvm 16 - we can rotor with multiple different gaps without partial
S17-supply/rotor.rakudo.jvm 17 - we can rotor with multiple different gaps with partial
S17-supply/rotor.rakudo.jvm 18 - we can rotor with negative gap
S17-supply/rotor.rakudo.jvm 19 - we can rotor with negative gap without partial
S17-supply/rotor.rakudo.jvm 20 - we can rotor with negative gap with partial
S17-supply/rotor.rakudo.jvm 30 - we can rotor with multiple different gaps
S17-supply/rotor.rakudo.jvm 31 - we can rotor with multiple different gaps without partial
S17-supply/rotor.rakudo.jvm 32 - we can rotor with multiple different gaps with partial
S32-str/unpack.t 4 - field 2 (A28) works
S32-str/unpack.t 5 - field 3 (A8) works
S32-str/unpack.t 6 - field 4 (A*) works
S32-str/unpack.t 8 - field 2 (A28) works
S32-str/unpack.t 9 - field 3 (A8) works
S32-str/unpack.t 10 - field 4 (A*) works
```

One of the failing tests does this:

> < bartolin> r: my $s = Supply.from-list(1..10).rotor(3 => 1, 2 => -1,:partial); $s.tap( { say $_ } )
> <+camelia> rakudo-jvm 8ccda1890: OUTPUT: «[1 2 3]␤[5 6]␤[5 6 7]␤[10]␤»
> <+camelia> ..rakudo-moar 8ccda1890: OUTPUT: «[1 2 3]␤[5 6]␤[6 7 8]␤[10]␤»

I reverted a5d46b4273 locally and rakudo-jvm gave the correct result, again.

With that commit the new nqp::slice op is used. I looked at the implementation (https://github.com/perl6/nqp/blob/master/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java#L177) but it looks like nqp::slice is called with the wrong arguments, already.

**Comment by lizmat** [comment]
Called with wrong arguments where?

**Comment by jstuder-gh** [comment]
The fact that it works fine on the MoarVM backend suggests that it is probably a bug in the JVM implementation of slice. There are multiple slice methods for the "native" classes ([here is one example](https://github.com/perl6/nqp/blob/master/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i.java#L177)) so the bug could be in one of those. I had added a number of tests to the nqp repo but, in retrospect, they don't properly test the "native" types so those could be off. I don't have time right now, but I can look at it again later tonight.

**Comment by lizmat** [comment]
Reverted a5d46b4 for now, guess will figure this out after the 2018.05 release.

**Comment by usev6** [comment]
Ok, after looking some more, I'm pretty sure the error is in this method (the one I linked yesterday): https://github.com/perl6/nqp/blob/master/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java#L177

With the following patch the errors are gone. @jstuder-gh Do you see any problems with that patch?
```
diff --git a/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java b/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java
index 38839b113..1855c9607 100644
--- a/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java
+++ b/src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java
@@ -184,7 +184,7 @@ public class VMArrayInstance extends VMArrayInstanceBase {
         long numWanted = end - start + 1;
         if (0 < numWanted) {
             for (long i = 0; i < numWanted; i++) {
-                dest.bind_pos_boxed(tc, i, this.slots[ (int)(start + i) ]);
+                dest.bind_pos_boxed(tc, i, this.at_pos_boxed(tc, start + i));
             }
         }
         return dest;
```

> Called with wrong arguments where?

@lizmat Sorry about my vague statement. I assumed that the call to nqp::splice here https://github.com/rakudo/rakudo/commit/a5d46b4273bc5cb011f8f9573dd4e553c5256302#diff-ea0833f3841cb4b437aa2a081f6e6862R1064 already passed the wrong arguments. But it looks like that piece of code worked fine.

**Comment by jstuder-gh** [comment]
@usev6, the patch looks good to me! I guess I failed to account for the (member variable) ```start``` offset being different.  I should have seen that. Good catch!

And looking at it again now, I guess it probably wasn't the best idea to name the local variable ```start``` too.

**Comment by usev6** [comment]
I've commited the patch: https://github.com/perl6/nqp/commit/e4bb7fbd00

@jstuder-gh I agree: I also didn't spot the member variable for a while, so it probably makes sense to use a different name for the local variable. I'll put it on my list :-)

@lizmat With regard to this issue, your original optimization https://github.com/rakudo/rakudo/commit/a5d46b4273 could go in again (there will be a version bump with the release). But I saw that @AlexDaniel mentioned that commit in https://github.com/rakudo/rakudo/issues/1843

**Comment by jstuder-gh** [comment]
This can be closed I believe? The issue has been resolved and I don't think that there is anything else to add in terms of new tests.
