### ISSUE TITLE
Deprecate the usage of .pm extension for modules

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#1846]
## The Problem
 
One cannot create a perl + perl6 project containing something like:
```
lib/MyPerl6Code.pm6
lib/MyPythonCode.py
lib/MyPerlCode.pm
```

because MyPerlCode.pm will always be treated as perl6 code during module lookup.

## Expected Behavior

```
$ perl6 -Ilib -e 'use MyPythonCode;'
===SORRY!===
Could not find MyPythonCode at line 1 in:
...

$ perl6 -Ilib -e 'use MyPerlCode;'
===SORRY!===
Could not find MyPerlCode at line 1 in:
...
```

## Actual Behavior

```
$ perl6 -Ilib -e 'use MyPythonCode;'
===SORRY!===
Could not find MyPythonCode at line 1 in:
...

$ perl6 -Ilib -e 'use MyPerlCode;'
===SORRY!===
This appears to be Perl 5 code.
...
```

## Why expected behavior is ideal

* Having two extensions make no sense other than for backwards compatibility. This is easy for anyone to submit PRs for, or to automate PRs for.

* Writing code to have to check for multiple extensions sucks, especially because it means it cannot simply be treated as `this-or-that `but `this-or-that-or-this_and_that`. It also means we technically need to document and justify choosing one of `this` or `that` when the result is `this_and_that`.

* `CompUnit::Repository::FileSystem` ( `CURFS` ) does not try to execute python, ruby, etc module files so its possible to have:
    ```
    lib/Implementation/Selector.pm6
    lib/Implementation.pm6
    lib/Implementation.py
    ```
    but not
    ```
    lib/Implementation/Selector.pm6
    lib/Implementation.pm6
    lib/Implementation.py
    lib/Implementation.pm
    ``` 
    meaning `lib/Implementation/Selector.pm6` could do `use Implementation:from<Python>` but not `use Implementation:from<Perl5>;` when invoking perl6 with `-Ilib` or using `use lib 'lib'` in a bin/script.

* Shouldn't break existing installations.

## Why expected behavior is not ideal

* Would break non-installed code relying on `use lib "lib"` finding some `.pm` file ( assuming a non-ecosystem module since PRs can fix those ) after updating rakudo. The deprecation period should probably be based on the seriousness of this point.

* It doesn't map to our packaging format / `provides` -- The expected behavior might lead one to think they can package $other-language module by adding something like `"MyPythonCode" : "lib/MyPythonCode.py"` to `provides` meta data, but that extension would be ignored during installation so any other perl6 modules in that distribution relying on loading that python module would not work the same after installation. ( Note that in the future this might be a perfectly fine way to handle things, but only if perl `.pm` files are treated the same as all other non `.pm6` files. )

* Updating `perl6/roast` will probably suck and will make git blame a bit worse.

**Comment by AlexDaniel** [comment]
I am 👍 on this change. Anyone should feel free to start creating PRs to these modules:
https://gist.github.com/fdefe991f172569f2a09b308be80a84a

Even if, for some reason, we decide not to deprecate .pm extension, it is still better to use `.pm6` because that is what our docs recommend. This was discussed to death: https://github.com/perl6/doc/issues/778

> Updating perl6/roast will probably suck and will make git blame a bit worse

Technically it's not a big deal, but I guess we'll have to think if this is something that should be done within v6.d or v6.e.

**Comment by ugexe** [comment]
It would have no impact because those Build.pm files are loaded via their
absolute path and thus don’t go through CURFS:
https://github.com/ugexe/zef/blob/e5005f4ecf1dc2bc2a9c1f6c607d18b36f51efbc/lib/Zef/Service/Shell/LegacyBuild.pm6#L19

**Comment by JJ** [comment]
I am not totally sure the merged change solves this issue.

I have this `META6.json`:

```json
{
  "name": "IV scripts",
  "description": "Scripts Raku para analizara datos de la asignatura IV",
  "version": "0.0.2",
  "perl": "6.d",
  "meta-version": 1,
  "authors": [
    "JJ Merelo"
  ],
  "auth": "github:JJ",
  "depends": [
    "IO::Glob",
    "Text::CSV",
    "Git::File::History",
    "JSON::Fast"
  ],
  "provides": {
    "IV::Stats": "lib/IV/Stats.rakumod",
    "IV::Stats::Fechas": "lib/IV/Stats/Fechas.rakumod",
    "IV::Stats::Utils": "lib/IV/Stats/Utils.rakumod"
  },
  "resources": [],
  "license": "Artistic-2.0",
  "tags": [
    "scripts",
    "learning analytics"
  ],
  "source-url": "https://github.com/JJ/plantilla-IV.git"
}
```

And effectively a .pm file for a separate Perl module I also use. Still, the `%provides` array in the code seems to include everything in the module, and not what's in this `provides` section. At any rate, the warking is issued (4 times in my case).

I'm not reopening the issue (although I have teh privs). Please decide if this is instead a new issue, I can create one instead.

**Comment by ugexe** [comment]
If you are using `-Ilib`, and it sounds like you are, then it has to guess what files to include in provides. Since the .pm extension is deprecated (not removed) it still has to consider files with a `.pm` extension as raku. Use `-I.` (i.e. point at your META6.json location) and it isn't an issue since you have explicitly declared which files are raku files.
