### ISSUE TITLE
Feature request: implement equivalent subroutine to print for stderr

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#1849]
The only subroutine that prints to stderr at the moment is `note`, but there isn't a subroutine that can print to it without a newline like there is with stdout, forcing users to use `$*ERR.print` to do the job. I think this is a feature that would be needed often enough to merit having a subroutine like `print` to make code that prints to both stdout and stderr more uniform.

**Comment by zoffixznet** [comment]
> I think this is a feature that would be needed often enough

What are some examples of this?

**Comment by pmichaud** [comment]
> forcing users to use ```$*ERR.print``` to do the job.

Well, not exactly.  A user could write something like:

```sub prerr(**@args) { $*ERR.print(@args); }```

and then ```print``` and ```prerr``` would look very uniform.

With some side effects, it's also possible to do things like:

```
{
   my $*OUT = $*ERR;
   print "This text ";
   print "is being sent ";
   print "to stderr\n";
}
print "...and this is going to stdout\n";
```

FWIW, I haven't experienced that a print-to-stderr function (without newlines) is needed often enough to merit its own subroutine in the core; I'd tend to choose one of the above options anyway.

Pm

**Comment by Kaiepi** [comment]
In [RakudoBot](https://github.com/Kaiepi/RakudoBot.git), in the child processes I spawn to handle make, I tap stdout and stderr for each child process I spawn. Since the newlines are included in the text output to stdout and stderr, the code I have that logs the output ends up looking like this:

```perl6
my @lines;
$p.stdout.tap({
     print $_ if $!debug;
     @lines.push($_);
});
$p.stderr.tap({
    $*ERR.print($_) if $!debug;
    @lines.push($_);
});
```

It's not a major issue, but I think it looks inconsistent.

**Comment by zoffixznet** [comment]
>  I haven't experienced that a print-to-stderr function (without newlines) is needed often enough to merit its own subroutine in the core

Seconded. Even `note` I rarely have any need for. Also, `note` is like `say`, not like `put`, so it's not just a newline that differs it from print and were a `print` equivalent being added for STDERR, an equivalent for `put` would also be needed by the same logic, and I don't see much need for either, considering the alternative is rather short and straight-forward.

> but I think it looks inconsistent.

You can write the STDOUT one as `$*OUT.print: $_` and then it'll look consistent.

**Comment by AlexDaniel** [comment]
> Even note I rarely have any need for

Maybe that's simply because you don't use STDERR that often? I find `note` to be somewhat useful.

FWIW if we say that we need “print” equivalent for STDERR, then I guess the same argument can also be used to justify adding another routine for `put` equivalent… and at that point we would have `say` `put` `print` `note` `xxx` `yyy`. In my opinion that's too much. The difference between these routines [is already a FAQ](https://docs.perl6.org/language/faq#How_and_why_do_say,_put_and_print_differ?), I don't think we should complicate it any more.

So yeah, 👎.
