### ISSUE TITLE
Pod convert non-breaking space into normal space.

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1852]
## The Problem

We use non-breaking space for Perl 6 and Perl 5 in the documentation to avoid splitting. However, these spaces are turned into normal space when processed through Pod:

    =head1 Talking about Perl 6
    say "Talking about Perl 6".comb.map: *.ord;
    say $=pod[0].contents[0].contents[0].comb.map: *.ord;

This causes problems like perl6/doc#2037 and perl6/Pod-To-HTML#38

## Expected Behavior

Leave non-breaking whitespace (and possibly other characters) unprocessed.

## Actual Behavior

Non-breaking space is turned into character 32, normal space.

## Steps to Reproduce

Run code above or check linked issues.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

Whatever the docs.perl6.org server is running, and also 2018.04 locally here.

**Comment by tbrowder** [comment]
Some of that may be due to pod handling in the last year—a lot of text splitting on whitespace uses /\h/ which I assume includes non-breaking whitespace based on results being seen.

**Comment by tbrowder** [comment]
I now have a test to show Perl 6 silently converts the non-breaking space to normal space. I can fix that iif we get consensus on defining pod non-breaking space as part of the words.

**Comment by JJ** [comment]
Thanks a lot, Tom.

**Comment by JJ** [comment]
This was closed, right? It's already working in the last version...

**Comment by tbrowder** [comment]
Closed by commit 4cbb0fa.
