### ISSUE TITLE
Test.pm "looks like"

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#1860]
## The Problem

Test.pm says "Looks like" something happened; we know what happened, we should drop this language.

## Expected Behavior

Instead of

Looks like you planned 30 tests

Should say

You planned 30 tests

(and same for failed)

## Actual Behavior

code:

```
$ ack -ai 'looks like' lib
lib/Test.pm6
746:    _diag("Looks like you planned $num_of_tests_planned test"
751:    _diag("Looks like you failed $num_of_tests_failed test"
```

**Comment by tqdv** [comment]
This issue can probably be closed now as the changes have been merged.

**Comment by Altai-man** [comment]
You are correct! Thank you very much for noting this. Closing.
