### ISSUE TITLE
Add more restrictive proto to Test.pm6's `plan`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1866]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

```
$ perl6 -e 'use Test; plan :skip<No widgets> if $*ENV<WIDGETS>; plan 1; ok 1'
1..1
ok 1 - 
$ perl6 -v
This is Rakudo version 2018.04-20-g7847768 built on MoarVM version 2018.04-34-g25f165a
implementing Perl 6.c.
```

The above code, conditionally skips the test file… Except it used incorrect named arg and will crash when the condition is true. It might be useful to make it detect wrong args sooner, since the condition might be something the user isn't expecting to be true on their system while writing the test.

That can be done by adding a `proto` to [`plan` multies](https://github.com/rakudo/rakudo/blob/154d985518f1415e3814f66094f1fd1eff0a1cba/lib/Test.pm6#L65-L87). Say:

```perl6
    proto sub plan ($, Cool:D :$skip-all) {*}
```

This [bit me today in a real life program](https://github.com/perl6/perl6-lwp-simple/commit/3e34aae1f5) and after committing, I had the mind to re-run the test file with the condition reversed, only to notice the crash occur then.

**Comment by lizmat** [comment]
Fixed with fa91b780df and 4eecb3c810
