### ISSUE TITLE
Add Of parametrized role

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1877]
## The Problem

Basic roles and classes such as Positional, Associative, Callable and even Scalar all include method of(), with a similar behavior, returning the underlying type the class or role has been parametrized with.

## Expected Behavior

Creating a parametrized role with that sole method would help find the commonalities among them. And it's the same code anyway, so it might be better to factor it out.

**Comment by lizmat** [comment]
I seem to recall trying that a *long* time (as in about 4 years ago).  And failing (with very cryptic messages during setting compilation).

These are all very basic functionalities very early in the setting, when not all of the functionality of Perl 6 is available to compile Perl 6.

But if someone can make this work, more power to them!
