### ISSUE TITLE
Convert documentation to pod6

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1881]
## The Problem

Documentation in the `doc` directory is still in Pod5.

## Expected Behavior

Moving it to Pod6 would help with things such as [this pull request to render pod6 in GitHub](https://github.com/github/markup/pull/1173). It's simply coherent, too.

**Comment by lizmat** [comment]
> On 29 May 2018, at 08:46, Juan Julián Merelo Guervós <notifications@github.com> wrote:
> 
> The Problem
> 
> Documentation in the doc directory is still in Pod5.

You mean the /docs directory, right?

> Expected Behavior
> 
> Moving it to Pod6 would help with things such as this pull request to render pod6 in GitHub. It's simply coherent, too.

Agree.


Liz

**Comment by lizmat** [comment]
> On 29 May 2018, at 08:46, Juan Julián Merelo Guervós <notifications@github.com> wrote:
> 
> The Problem
> 
> Documentation in the doc directory is still in Pod5.

Actually, I think most of the stuff in docs is in bad need of updating and/or deletion.  There’s still quite a lot of references to Parrot and PIR in there.


Liz

**Comment by JJ** [comment]
El mar., 29 may. 2018 a las 10:09, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

>
> > On 29 May 2018, at 08:46, Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
> >
> > The Problem
> >
> > Documentation in the doc directory is still in Pod5.
>
> You mean the /docs directory, right?
>

Correct.

**Comment by JJ** [comment]
El mar., 29 may. 2018 a las 10:14, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

> > On 29 May 2018, at 08:46, Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
> >
> > The Problem
> >
> > Documentation in the doc directory is still in Pod5.
>
> Actually, I think most of the stuff in docs is in bad need of updating
> and/or deletion. There’s still quite a lot of references to Parrot and PIR
> in there.
>

Whatever is left after the Big Deletion, let's move it to Pod6 :-)

**Comment by zoffixznet** [comment]
> Moving it to Pod6 would help with things such as this pull request to render pod6 in GitHub. It's simply coherent, too.

Not sure how it'd help exactly. I rather GitHub implement Pod6 rendering *before* we convert all rendered documents into format that is currently unrendered. I'm highly dubious GitHub will that easily start to execute a very expensive process that allows for execution of arbitrary code.

That PR to github/markup has numerous issues too:
* Why does it use 2018.02 rakudo instead of latest release? Will you be sending update PRs every so often?
* Why does the readme say no additional deps are needed when `Pod::To::HTML` is required?
* Does that test even pass? It has CSS code included as part of the text and the markup is missing all of the generated attributes as well as some tags (like `<caption>` in the table)

**Comment by JJ** [comment]
El mar., 29 may. 2018 a las 13:06, Zoffix Znet (<notifications@github.com>)
escribió:

> Moving it to Pod6 would help with things such as this pull request to
> render pod6 in GitHub. It's simply coherent, too.
>
> Not sure how it'd help exactly. I rather GitHub implement Pod6 rendering
> *before* we convert all rendered documents into format that is currently
> unrendered. I'm highly dubious GitHub will that easily start to execute a
> very expensive process that allows for execution of arbitrary code.
>

That's kind of a Catch-22 situation. GitHub is not going to accept that PR
unless there are enough examples in the wild. And I guess that code is
going to be run in some kind of blackbox so that it does not affect
anything else.

> That PR to github/markup has numerous issues too:
>
>    - Why does it use 2018.02 rakudo instead of latest release? Will you
>    be sending update PRs every so often?
>
>
Because it was done a loooong time ago.

>
>    - Why does the readme say no additional deps are needed when
>    Pod::To::HTML is required?
>
>
Right. That's probably an error.

>
>    - Does that test even pass? It has CSS code included as part of the
>    text and the markup is missing all of the generated attributes as well as
>    some tags (like <caption> in the table)
>
>
It does in github/markup. Or you mean somewhere else?

**Comment by zoffixznet** [comment]
> Because it was done a loooong time ago.

What relevance does that have?

**Comment by JJ** [comment]
El mar., 29 may. 2018 a las 14:07, Zoffix Znet (<notifications@github.com>)
escribió:

> Because it was done a loooong time ago.
>
> What relevance does that have?
>

It was the latest available?

**Comment by JJ** [comment]
El mar., 29 may. 2018 a las 14:09, JJ Merelo (<jjmerelo@gmail.com>)
escribió:

>
>
> El mar., 29 may. 2018 a las 14:07, Zoffix Znet (<notifications@github.com>)
> escribió:
>
>> Because it was done a loooong time ago.
>>
>> What relevance does that have?
>>
>
> It was the latest available?
>

I''ll check if there's a generic URL for the latest and upgrade it if
needed... But I don't know if that's why that PR is not being addressed, so
I'll really wait until there's some reaction from GitHub.

**Comment by zoffixznet** [comment]
> I''ll check if there's a generic URL for the latest

There should be. That's why I linked to the now-resolved Issue about fixed URL for latest available release: https://github.com/nxadm/rakudo-pkg/issues/35
