### ISSUE TITLE
Improve where clause unmet error

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1883]
## The Problem

When the constraint in a where clause is not met, it says `expected anonymous constraint to be met`

## Expected Behavior

It would be better if  there was some way of fleshing out `anonymous constraint` by printing the signature or the actual anonymous constraint. Or some way of making the constraints not anonymous and print the actual name of the constraint.

## Environment

This is perl 6 2018.05

**Comment by zoffixznet** [comment]
> print the actual name of the constraint

What would that look like? In the vast majority of cases it'd be a `Callable` without a name (hence the "anonymous") and they'd all just have a `;; $_? is raw` as signature, making printing that detrimental rather than useful.

**Comment by lizmat** [comment]
Perhaps we should store the code of the constraint as a string somewhere as well, something akin “use trace” does but then very locally?

**Comment by zoffixznet** [comment]
> Perhaps we should store the code of the constraint as a string somewhere as well, something akin “use trace” does but then very locally?

I'm a bit worried about this type of errors one day ending up in some error log. Same as value-printing errors can reveal credit card numbers, the code-dumping errors can reveal important pieces of the program. And would very long Callables be abridged or dumped as is, flooding the screen with code?

Also, wouldn't already-high memory use be even higher if we store the code itself together with all the anonymous Callables?

The user is in full control of what error shows up on typecheck. There's even a [`Subset::Helper`](https://modules.perl6.org/repo/Subset::Helper) module if you need to do it a lot. This feels a lot like the now-reverted "awesome" error for `.parse-base` that was bending over backwards to give marginally better error.

**Comment by JJ** [comment]
Wouldn't just the .gist of the where clause be enough here?

**Comment by 0racle** [comment]
This is an old issue, but I think the goal is worthy, so I wanted to open up discussion.

I suspect providing the constraint code in current implementation may not be easy as the "text" of the constrain is simply not available, but perhaps RakuAST with it's support for deparsing may make that easier?

Alternatively, could subset syntax be extended to take an additional (optional) field containing a String describing the constraint (which then gets printed in the exception if it's there)?

Thoughts?

**Comment by FCO** [comment]
@0racle isnt that kind of the intent of `will complain`?

**Comment by vrurg** [comment]
> @0racle isnt that kind of the intent of `will complain`?

It is. I'm closing this issue as resolved.

**Comment by vrurg** [comment]
@0racle thanks for unearthing this one! :)
