### ISSUE TITLE
Miscompilation (optimization) of chain ops

### ISSUE THREAD

**Issue by timo** [rakudo/rakudo#1886]
## The Problem

```perl6
sub foo($x, $y) { True };

sub bar($x, $y, $w)
{
    {
        my int $x2 = 1;
        my int $y2 = 2;
        if foo($x, $y) == foo($x, $y2) == foo($x2, $y2) == foo($x2, $y) {
            2;
        } else {
            1
        }
    }
};

say bar(1, 2, 25);
```

## Expected Behavior

```
2
```

## Actual Behavior

```
Cannot resolve caller Numeric(Sub+{is-pure}+{Precedence}: ); none of these signatures match:
    (Mu:U \v: *%_)
  in sub bar at the_bug.p6 line 8
  in block <unit> at the_bug.p6 line 16
```

## Steps to Reproduce

```
Cannot resolve caller Numeric(Sub+{is-pure}+{Precedence}: ); none of these signatures match:
    (Mu:U \v: *%_)
   at SETTING::src/core/Exception.pm6:57  (/home/timo/perl6/install/share/perl6/runtime/CORE.setting.moarvm:throw)
 from SETTING::src/core/Exception.pm6:2719  (/home/timo/perl6/install/share/perl6/runtime/CORE.setting.moarvm:)
 from gen/moar/BOOTSTRAP.nqp:2251  (/home/timo/perl6/install/share/nqp/lib/Perl6/BOOTSTRAP.moarvm:)
 from SETTING::src/core/Mu.pm6:539  (/home/timo/perl6/install/share/perl6/runtime/CORE.setting.moarvm:Numeric)
 from SETTING::src/core/Numeric.pm6:290  (/home/timo/perl6/install/share/perl6/runtime/CORE.setting.moarvm:infix:<==>)
 from SETTING::src/core/Numeric.pm6:288  (/home/timo/perl6/install/share/perl6/runtime/CORE.setting.moarvm:infix:<==>)
 from the_bug.p6:8  (<ephemeral file>:)
 from the_bug.p6:5  (<ephemeral file>:bar)
 from the_bug.p6:16  (<ephemeral file>:<unit>)
 from the_bug.p6:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1531  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1770  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1693  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/timo/perl6/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1619  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:<entry>)
```

Remove the `int` types from the `$x2` and `$y2` variable declarations and it doesn't crash.

bisectable points at this rakudo commit: https://github.com/rakudo/rakudo/commit/14c2cdb314ee5bbda34354ef535d4909dcea845a

That contains work by @jstuder-gh to make the chain op able to take the callee as first argument, and it seems like here the opposite is a problem, looks like the sub is used as a parameter to one of the == calls or something like that.

* https://gist.github.com/Whateverable/b17966f8408b98e63113af9a1ba06f28
* https://gist.github.com/Whateverable/49664966566ab8996f0719f89cece80c

## Environment
* Operating system: Fedora 27
* Compiler version (`perl6 -v`): This is Rakudo version 2018.05-27-g0666f6a86 built on MoarVM version 2018.05-29-g33d94f7ee

**Comment by jstuder-gh** [comment]
I've pushed up a [PR that addresses this issue](https://github.com/perl6/nqp/pull/455). When modifying the chain compilation, I included a 'decont' operation that is unnecessary at best. 

Looking at it now, I'm scratching my head a bit. I didn't use the results of the decont register anywhere and deconting a routine wouldn't do any good anyway...

I'm not sure why this is blowing up now vs. a pointless addition other times, but removing it fixes the problem (+ doesn't introduce other spectest failures)
