### ISSUE TITLE
Should 'use p5isms' be renamed / removed / documented & tested

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#1887]
A little while ago I added a `use p5isms` pragma, that will allow you to use Perl 5 like constructs without getting warnings / errors about it.  Which is handy for a number of CPAN Butterfly Plan modules.

So far, I have not added documentation or tests, because there was some discussion as to the usefulness, and to the naming.  Hence my question.

I will add three comments to this Issue that can be used by whoever to add thumbs up / thumbs down so we can have a little poll.

In about a week from now, I will look at it again and go forward with the poll results.

**Comment by lizmat** [comment]
It should be documented / tested

**Comment by lizmat** [comment]
It should be renamed to something else

**Comment by lizmat** [comment]
It should be removed

**Comment by zoffixznet** [comment]
The poll is confusing. Of course it should be documented and tested.... but after being renamed 😛

**Comment by AlexDaniel** [comment]
Could it be `use isms<perl5>` or something like that? Or what are the options for renaming?

**Comment by lizmat** [comment]
Implemented as `use isms <perl5>` in 4109ce36a5

**Comment by lizmat** [comment]
Change it to `use isms <Perl5>` to match `use Foo:from<Perl5>`, documented it, added tests for it
