### ISSUE TITLE
Signal(0) gives FreeBSD signals on Linux

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1891]
```
<AlexDaniel> m: say Signal(0)
<camelia> rakudo-moar c80ea2f28: OUTPUT: «SIGTHR␤»
<AlexDaniel> e: say Signal(0)
<evalable6> AlexDaniel, rakudo-moar c80ea2f28: OUTPUT: «SIGINFO␤»
```

Locally I also get SIGEMT. Seems to be somewhat random. Bisected to around this merge: https://github.com/rakudo/rakudo/pull/1601

Ping @jstuder-gh.

Related ticket: #1888.

**Comment by AlexDaniel** [comment]
Ah, expected behavior is `(Signal)` type object. It used to do that previously and it also does this for other values (e.g. `-1`).

**Comment by AlexDaniel** [comment]
FWIW please also test high values (like 32 and above).

**Comment by jstuder-gh** [comment]
All the sigs that don't have a signum on the host system are being set to 0. My thought process behind this was that a symbol would be registered for every sig but the value would be 0 so that it wouldn't be dangerous to use in conjunction with the native C kill function if it was not available (passing a 0 signal to kill does not emit anything). And the ```signal``` sub (that registers signal handlers with the backend) filters out all the 0's it encounters.

We could make it so that no entry is included in the hash for signals that are not available on the platform, but that would create issues where user code using a particular signame could produce compile-time error depending on the platform it is run on.

Personally, I don't think it's a problem having ```Signal(0)``` return a value instead of the type object but I do think it's a problem that it is inconsistent and that if there are multiple enumerations with the same value that some are not included.

Regardless of what we decide to do with ```Signal```, what should we do if multiple enumerations for a given type have the same value? We could make it so that it returns a list of all the enums that match if multiple, singular enum if only one?

(In regards to more consistent ordering, I figure that we can modify the getsignals op to return a list instead of a hash and have ```.[idx] %% 2``` be key and ```!(.[idx] %% 2)``` be the value. Since feeding the ```Signal``` enum is the only thing using this op now it would be safe to change. This would make the results of using ```.pred``` and ```.succ``` on ```Signal``` more sane as well.)

**Comment by AlexDaniel** [comment]
@jstuder-gh thanks! Merged your PRs.

Can't we just hardcode “nothing” for `0`?

**Comment by jstuder-gh** [comment]
@AlexDaniel, I was thinking about your question and I thought of a way to do it while still taking advantage of all the benefits provided to us via ```Enumeration```, but I don't know if it's a good idea. It involves ```augment```ing the ```Signal``` class (after contruction by the ```enum``` keyword) and overriding it's ```CALL-ME``` method.

[See proposed modification here](https://github.com/rakudo/rakudo/compare/master...jstuder-gh:monkey_type_signal)

With this approach we can make the bring the output back to what it was previously:

    say Signal(0)
    #OUTPUT: «(Signal)␤»

I know ```MONKEY-TYPING``` isn't generally recommended, but is this an acceptable use of the tool in the context of Rakudo development?

I'll definitely need some feedback on this as I'm not sure it's a good idea or if it would be opening up a can of worms to make the ```CALL-ME``` method on the base ```Enumeration``` class a multi. Is it exposing too much? It passes the spectest, but that doesn't necessarily mean it's a wise thing to do.

What do you think?

**Comment by AlexDaniel** [comment]
@jstuder-gh what's exactly the problem with creating an enum with no value at 0?

For example:
```perl6
my enum foo(hello => 42, world => 66);
say foo(0); # (foo)
say foo(42); # hello
```

**Comment by jstuder-gh** [comment]
@AlexDaniel, these are the reasons that I think that it makes sense to define all the missing signals with zero values as opposed to omitting them.

All 35 ```constant``` signal symbols are defined for each platform. If the no enum was declared, it would result in a compile-time error on a platform where it does not exist.

    say ($*KERNEL.name, |(~$_, +$_ given SIGUSR1)).perl;
    # OUTPUT: ("win32", "SIGUSR1", 0)
    
    say "Total Enums: {Signal.^enum_value_list.elems}";
    # OUTPUT: Total Enums: 35

The value zero gives us a common value to filter out when passed to the signal sub.

    my $supply = signal(SIGINT, SIGEMT, SIGUSR1, SIGBREAK);

    #`( OUTPUT
      The following signals are not supported on this system (win32): SIGEMT, SIGUSR1
       in block <unit> at -e line 1
    )

If user uses native C kill function (on POSIX compliant systems), no erroneous signal is sent to the process if the signal is not available (0 is defined as the [null signal](http://pubs.opengroup.org/onlinepubs/9699919799.2018edition/functions/kill.html)).

    use NativeCall;
    sub kill(int32, int32) is native {*};

    say ($*KERNEL.name, |(~$_, +$_ given SIGBREAK)).perl;
    # OUTPUT: ("linux", "SIGBREAK", 0)    

    kill $*PID, SIGBREAK;
    # RESULT: Nothing

Unfortunately it introduces the issue with ```Signal(0)```, but I think that the augmentation of the ```Signal``` class proposed in the comment above is a good resolution to this problem, assuming that using ```MONKEY-TYPING``` and setting ```Enumeration```'s base ```CALL-ME``` method to a ```multi``` is not opening a can of worms in terms of safety or potential for bugs.

We could potentially not use ```Enumeration```s to represent these values but I personally like the functionality provided by enums and the ease of creating all those ```constant``` symbols.

I'm definitely open to suggestion if there are ways that these can be handled better, but I think this is a reasonable approach.

**Comment by jnthn** [comment]
I agree that introducing a compilation failure in code that so much as mentions a signal that doesn't exist on the current platform is a bad thing, and so simply not mapping those signal names is indeed not an ideal solution.

I'm a tad less sure whether silent failure when sending a signal that doesn't exist is desirable or not. I guess it's robust in the sense of "the code won't throw", but if the signal being actually sent is important for correct behavior of the program, then silent failure may be less good. I don't feel strongly either way on that at present.

I believe it is possible for a role to be composed into an enum type (using the `does` trait on the enum declaration). This would provide us a more elegant way to handle introducing some custom behavior than `augment`, and we could probably make the zero signal value consistently stringify to `Unavailable` or some such in that case (which I think communicates better than "Nothing"). Overriding `CALL-ME` in that role to hand back the type object for anything with value zero also would seem workable.

If we did want the bad signal names to explode on use, then we could exclude them from the enum but still provide constants, which are mapped to a `Failure` that says the signal is not available. Though as noted, I'm not sure we want that.

Either way, I'm not sure we want to rush to resolve this for the release; it raises good questions that need some thought and input. Unless we can point at code that is adversely affected by the behavior change around `Signal(0)`, I don't really feel it's a release blocker.

**Comment by AlexDaniel** [comment]
> Unless we can point at code that is adversely affected by the behavior change around Signal(0), I don't really feel it's a release blocker.

I did require a change in whateverable: https://github.com/perl6/whateverable/commit/0d9ece4ca3b19521a8ac9a7c358416ecf9e650df

**Comment by lizmat** [comment]
Closing in light of #1960
