### ISSUE TITLE
Suppressing capture of lexical regex with <.regex-name> doesn't work - works with <&regex-name>

### ISSUE THREAD

**Issue by ronaldxs** [rakudo/rakudo#1894]
## The Problem
```
$ perl6 -e 'my token t { t }; say so "t" ~~ /<.t>/'
No such method 't' for invocant of type 'Match'.
```
Update: it looks like this is a doc issue.  If I don't hear back in a day or so I will move to doc ...

## Expected Behavior
The [Subrules section of the Regexes doc](https://docs.perl6.org/language/regexes#Subrules) essentially suggests that capture suppression with `<.` should work on a lexical token but it does not.

Update: it looks like a doc error:
In roast [S05-interpolation/lexicals.t#L10](https://github.com/perl6/roast/blob/107ff8372e3e137c5e441988e76576500b528625/S05-interpolation/lexicals.t#L10) it is done with `my token abc {}; 'foo abc def' ~~ / <&abc> /`

## Steps to Reproduce
```Perl6
my regex line { \N*\n }
if "abc\ndef" ~~ /<line> def/ {
    say "First line: ", $<line>.chomp;      # OUTPUT: «First line: abc␤»
}

grammar G {
    regex g-line { \N*\n }
    regex line-def-cap { <g-line> def }
    regex line-def-no-cap { <.g-line> def }
}
say G.parse("abc\ndef", :rule('line-def-cap'));
say G.parse("abc\ndef", :rule('line-def-no-cap'));

# works ^ above but not \/ below
if "abc\ndef" ~~ /<.line> def/ {
    say "matched wo capture";
}
```

## Environment
* Operating system: 
Description:    Ubuntu 14.04.5 LTS
Codename:       trusty

* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.05 built on MoarVM version 2018.05
implementing Perl 6.c.

**Comment by jnthn** [comment]
Can conform that `<.foo>` is meant to always be a method call without capturing, and `<&foo>` always a lexical call without capturing.

**Comment by ronaldxs** [comment]
Moved to doc issue [#2087]( https://github.com/perl6/doc/issues/2087).
