### ISSUE TITLE
Weird warning about sink context in loop phaser

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#1900]
Class to be compiled - Foo.pm
```perl6
unit class Foo;

method foo {
    loop { FIRST say 123; last; }
}
```
## The Problem

```
$ perl6 -I . -e 'use Foo; Foo.new.foo'
WARNINGS for /Users/bbkr/Developer/Foo.pm (Foo):
Useless use of LOOP_BLOCK_1 symbol in sink context (line 3)
123
```

Class compilation (first run without .precomp present) is throwing error about `FIRST` phaser being called in sink context. Is this a bug or is there any logical explanation behind it?

## Expected Behavior

Compilation without warning. From user perspective this is perfectly valid code. User should not be forced to `do loop { }` to avoid warning just because loop has phaser in it.

## Environment
* Operating system: macOS 10.13.4
* Compiler version (`perl6 -v`): Rakudo version 2018.05 built on MoarVM version 2018.05

**Comment by bbkr** [comment]
BTW: There is similar issue - https://github.com/rakudo/rakudo/issues/1704. I'm not sure if this issue with phaser is caused by the same bug or not.

**Comment by raiph** [comment]
I wonder if this is related to the fix done for https://github.com/rakudo/rakudo/issues/1698?

**Comment by jjatria** [comment]
This seems to have been fixed:
```
$ raku -e 'loop { FIRST say "foo"; last }'
foo
$ raku --version
This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.
```

**Comment by Altai-man** [comment]
Needs a test then to be closed.

**Comment by jjatria** [comment]
@Altai-man I've taken a stab at writing a test for this case. This is the first time I make a roast contribution, however, so please let me know if I can improve it. For starters, I'm not sure how I can directly test for (the lack of) a warning.

Incidentally, it might not even be necessary: the test added in https://github.com/Raku/roast/commit/dab963752cf8ea3a6 seems to cover a similar case (although that was added a full 2 months before this issue was opened, so perhaps the test case is different).

**Comment by Altai-man** [comment]
Hi, @jjatria !

>the test added in

I think those two are different cases, so should be tested differently.

>For starters, I'm not sure how I can directly test for (the lack of) a warning.

Let's see. I am not a pro in writing roast tests, but I just grepped files in roast for `warning` line. Among others that do not seem relevant, I see this:

```
➜  spec git:(master) rg 'warning'
(a lot of output skipped)
S32-list/reduce.t
100:    }, 'no warnings when setting associativity on the reduce &with';

S32-list/grep.t
133:    # `temp $_` business is merely to avoid warnings while we use the most

S32-list/first-end-kv.t
55:    temp $_ = 42; # avoid `uninitialized` warning

fudgeandrun
3:use warnings;

S06-signature/definite-return.t
149:# Should sub return-two(--> 2) { 3 } emit an error/warning?

S32-list/first-kv.t
54:    temp $_ = 42; # avoid `uninitialized` warning

t/fudgeandrun.t
4:use warnings;

S03-metaops/reduce.t
113:  # this would presumably emit warnings when we have them.

S05-match/capturing-contexts.t
91:    # This looks superfluous as there is a test for warning when interpolating
100:        'match with undefined capture emits a warning' );

S19-command-line/arguments.t
64:    'Unknown options do not spit warnings to stdout');

S01-perl-5-integration/eval_lex.t
22:    # perl -e 'no warnings; print qq|♥\x{26666}|; { use utf8; print qq|♥\x{26666}| }' |
26:    my $code = ｢no warnings; print qq|♥\x{26666}|; { use utf8; print qq|♥\x{26666}| }｣;

S04-statements/loop.t
126:        ~ ｢ do { say "saying"; warn "warning"; take "taking"; last } ｣
139:              :err(/«warning»/),

S04-blocks-and-statements/temp.t
11:    # warning - do {temp $a = 23; $a} not the same

S06-traits/is-copy.t
116:# the redeclaration thingy is only a warning
➜  spec git:(master) 
```

The line `100:    }, 'no warnings when setting associativity on the reduce &with';` from file S32-list/reduce.t looks relevant.

So I opened the file and there saw this:

```
{
    doesn't-warn {
        (^10).reduce(sub f ($a, $b) is assoc<right> {"Tuple $a ($b)"})
    }, 'no warnings when setting associativity on the reduce &with';
}
```

The sub `doesn't-warn` is not declared in the module itself, but if you grep it, it will be declared in `packages/Test-Helpers/lib/Test/Util.pm6`. The reduce.t file imports it with `use Test::Util;`.

As to where the test belongs, I think `S04-phasers/in-loop.t` file you mentioned is just right. So:

- Try to write a test using the `doesn't-warn` sub we found plus the code in OP.
- Don't forget to update `plan` number at the top of the test.
- Check if the test passes locally with fresh enough rakudo built.
- When it's ok (or when you want help), send a pull request for the roast repo.

**Comment by jjatria** [comment]
Thank you for the detailed help! I opened a PR and added some additional details on the PR message.
I guess I'll receive more feedback on that side :tada:

**Comment by Altai-man** [comment]
Closed as PR with a test is merged.
