### ISSUE TITLE
Deprecated method cannot be reached

### ISSUE THREAD

**Issue by W4anD0eR96** [rakudo/rakudo#1907]
https://github.com/rakudo/rakudo/blob/master/src/core/JSON/Pretty.pm6

I found these codes cannot be reached. That is, it is marked as deprecated, but in fact unreached.

**Comment by W4anD0eR96** [comment]
By the way, if we decide to delegate JSON parsing stuff to community modules, why remains `Rakudo::Internals::JSON`, since the deprecated method is unreached.

**Comment by niner** [comment]
Those subs can in fact be reached quite easily:
```
> perl6 -e 'say to-json("foo")'
"foo"
Saw 1 occurrence of deprecated code.
================================================================================
Sub to-json (from GLOBAL) seen at:
  -e, line 1
Please use JSON::Fast, JSON::Tiny or JSON::Pretty from https://modules.perl6.org/ instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
```

Rakudo::Internals::JSON is used by rakudo itself by the module management and precompilation code.
