### ISSUE TITLE
Why inconsistence of internal sub MAIN

### ISSUE THREAD

**Issue by TisonKun** [rakudo/rakudo#1909]
https://github.com/rakudo/rakudo/blob/148d7c56af911d59dde69daa4863e23b3ac4d7a2/src/main.nqp#L37-L42

If I change MoarVM ver. to `*@ARGS`, then it suddenly execute REPL while `make`, but why?

**Comment by TisonKun** [comment]
cc @usev6 @lizmat

**Comment by lizmat** [comment]
I have *no* idea
