### ISSUE TITLE
LTA Error in sequence operator

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1910]
I'm guessing it doesn't like the endpoint, but the error doesn't make the actual problem clear. In my original code, the LHS was just a `lines` call, making the error even more confusing.

```
$ perl6 -e 'say "a", "b", "c" … ""'
Decrement out of range
  in block <unit> at -e line 1

$ perl6 -v
This is Rakudo version 2018.05-54-g148d7c5 built on MoarVM version 2018.05-57-g89dee3b
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
Sorry, any issues with `infix:<...>` are basically unfixable without breaking something somewhere else, or severely affecting performance.  It's magic.  YMMV.

Yes, I have burned out on trying to make `infix:<...>` more sensible.
