### ISSUE TITLE
hyper and race should do `my $/`

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1912]
[IRC discussion](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-10#l268)

Basically, if you have code like:
```perl6
my @a = do hyper for (…).hyper -> $line {
    $line.match: /(…)/;
    $0
}
```
Then you need to stick `my $/` into the loop to get correct results:

```perl6
my @a = do hyper for (…).hyper -> $line {
    my $/;
    $line.match: /(…)/;
    $0
}
```

It would be nice if this was not needed (i.e. if it was done for you).

Also:
> \<jnthn\> $! should come along with it

**Comment by lizmat** [comment]
If you're hypering code that accesses `$/`, you simple need to provide that.  There is no easy wayu around this without breaking:
```raku
if /(foo)/ {
    say $0
}
```
so closing.
