### ISSUE TITLE
zef install Inline::Perl5 consumes 10G+ of ram

### ISSUE THREAD

**Issue by samcv** [rakudo/rakudo#1913]
## The Problem
Trying to install Inline::Perl5 with zef uses all of the systems memory (16GB). Subsequent tests I did after running with `ulimit -v 4000000` so it'd use max 4G of ram and my system wouldn't lock up. The issue doesn't occur on 2018.05. The memory goes up while it's searching for dependencies.

## Steps to Reproduce

`zef install Inline::Perl5`
## Environment
* Operating system: Sabayon Linux
* Compiler version (`perl6 -v`): 2018.05-75-gc10b1eec9

**Comment by ugexe** [comment]
Seems to work until merging https://github.com/rakudo/rakudo/commit/c5d14062abb2231a18688f3de854b6dbd3a3df1f 

Differing behavior is as follows:
1) The initial search for 'Inline::Perl5' is much slower than usual.
2) Each batch of dependencies that get searched for take 10+ minutes to complete.
3) CPU stays at 100%, memory jumps up and back down 3gb each second.

**Comment by timo** [comment]
maybe a spesh log of the process would be enlightening

**Comment by ugexe** [comment]
Confirmed fixed in bdbfee5

**Comment by lizmat** [comment]
I'm not sure how to craft a test for this.  I suggest we can close this ticket.

**Comment by samcv** [comment]
I would be fine with just closing the issue.
