### ISSUE TITLE
Binding in constant def silently ignores missing name

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1917]
```
$ perl6 -e 'constant := 42'

$ perl6 -v
This is Rakudo version 2018.04 built on MoarVM version 2018.04
implementing Perl 6.c.
```

**Comment by W4anD0eR96** [comment]
https://github.com/rakudo/rakudo/blob/874ead515dfe5d52c382b3c3ae0fd4dcdfde014c/src/Perl6/Grammar.nqp#L3325

**Comment by jnthn** [comment]
Are you sure this isn't a feature? We generally allow anonymous things.

**Comment by zoffixznet** [comment]
> Are you sure this isn't a feature?

The [commit that added that doesn't say](https://github.com/rakudo/rakudo/commit/cf3da00729148a434339d7aa0d819efebe5a0cb2).

> We generally allow anonymous things.

I think that's a fair argument :) I'll stash this one in my bag of curiosities.

**Comment by W4anD0eR96** [comment]
@jnthn anonymous for what? Why I declare a anonymous constant instead of write it down
