### ISSUE TITLE
LTA REPL tab auto complete

### ISSUE THREAD

**Issue by tisonkun** [rakudo/rakudo#1929]
## The Problem

REPL needs true tab auto complete

## Expected Behavior

auto complete based on current input

## Actual Behavior

wherever you enter tab, it "auto complete" from `Any` and so on

## Environment
* Operating system: Mac OS X
* Compiler version (`perl6 -v`):  
This is Rakudo Star version 2018.04.1 built on MoarVM version 2018.04.1
implementing Perl 6.c.

**Comment by AlexDaniel** [comment]
Yeah, it needs an auto complete.

**Comment by lizmat** [comment]
I believe this to be fixed.  If not, could you elaborate on what is going wrong?
