### ISSUE TITLE
IterationEnd and Mu.new fail to smart matching against Mu

### ISSUE THREAD

**Issue by kjkuan** [rakudo/rakudo#1940]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

## The Problem
```
> IterationEnd ~~ Mu
Cannot resolve caller ACCEPTS(Mu: ); none of these signatures match:
    (Mu:U: \topic, *%_)
    (Mu:U: Mu:U \topic, *%_)
  in block <unit> at <unknown file> line 3

> Mu.new ~~ Mu
Died with X::Multi::NoMatch
  in block <unit> at <unknown file> line 1

>
```
## Expected Behavior
```
> IterationEnd ~~ Mu
True
> Mu.new ~~ Mu
True
>
```

## Environment
* Operating system:  MacOS 10.13.4
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.05 built on MoarVM version 2018.05
implementing Perl 6.c.
```

**Comment by kjkuan** [comment]
>[14:07] &lt;Zoffix&gt; kjk: basically, there's no Mu:D candidate to make junctions thread, buuut, we can have that and still have a Mu:D candidate. You can fix the bug by changing `Any` to `Mu:D` here: https://github.com/rakudo/rakudo/blob/master/src/core/Mu.pm6#L16 and then adding another candidate for junction threading: multi method ACCEPTS(Mu:U: Junction:D \topic) { topic.THREAD: { self.ACCEPTS: $_ } }

**Comment by dogbert17** [comment]
Fixed with commit https://github.com/rakudo/rakudo/commit/3b4794f4aebac861a6b59470823aaebe0b92b8c9

**Comment by Altai-man** [comment]
Was test added?

**Comment by dogbert17** [comment]
Not by me and I could not find any matching roast commit. I guess we need a 'Tests needed' label.

**Comment by Kaiepi** [comment]
I can get some tests for this written up.

**Comment by Altai-man** [comment]
How it comes there is a(nother) fix coming if the fix was added in https://github.com/rakudo/rakudo/commit/3b4794f4aebac861a6b59470823aaebe0b92b8c9 ? Does it resolve another issue?

**Comment by Kaiepi** [comment]
https://github.com/rakudo/rakudo/commit/3b4794f4aebac861a6b59470823aaebe0b92b8c9 fixes smartmatching against `Mu` as a type object. The fix I'm proposing now is to allow instances of `Mu` to be smartmatched against as well, which is ultimately an unrelated problem to this. Getting sidetracked like this while solving issues users have raised isn't exactly the most efficient use of time here, so I'll work on better managing it. Sorry

**Comment by Altai-man** [comment]
Oh, I see. No problem with sidetracking, thanks for taking your time to solve issues! Just wanted to make it clearer, as later I'll have to write rakudo changelog, for example... :)
