### ISSUE TITLE
LTA error when using `,` instead of `;` to index a shaped array

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1943]
Here, a user accidentally used a `,` instead of `;` to index a cell in a two-dimentional shaped array. The error talks about partially-dimentioned views being NYI.

Took me some time to realize what the actual problem in the code was, but another user might think that indexing a shaped array is NYI. Perhaps, the error should suggest the user didn't use proper indexing.

```
$ perl6 -e 'my @a[2;2]; say @a[1,1]'
Partially dimensioned views of shaped arrays not yet implemented. Sorry.
  in block <unit> at -e line 1

$ perl6 -v
This is Rakudo version 2018.05-54-g148d7c5 built on MoarVM version 2018.05-57-g89dee3b
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
I think this ticket can be closed, as the PR by @bduggan basically did what we wanted, but at the expense of significant performance loss.  The take-away from that was to put more effort into making partially dimensioned views of shaped arrays work.
