### ISSUE TITLE
Can't directly iterate CORE::.kv with a for loop

### ISSUE THREAD

**Issue by kjkuan** [rakudo/rakudo#1944]
## The Problem
```
> for CORE::.kv -> $k, $v { put $k }
.... output omitted ...

Too few positionals passed; expected 2 arguments but got 1
  in block <unit> at <unknown file> line 1
```
## Expected Behavior
One should be able to iterate CORE::.kv without getting an exception.

## Environment
* Operating system: MacOS 10.13.4
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.05 built on MoarVM version 2018.05
implementing Perl 6.c.
```

**Comment by kjkuan** [comment]
This might give some clues:
```
> my %h = CORE::.kv                               
Odd number of elements found where hash initializer expected:                                        
Found 607 (implicit) elements:                    
Last element seen: "IterationEnd"                 
  in block <unit> at <unknown file> line 1
```

**Comment by kjkuan** [comment]
this also works: `for CORE::.pairs -> (:$key, :$value) { put $key }`

**Comment by lizmat** [comment]
This is, alas, a case of DIHWIDT, in my view.

The constant `IterationEnd` lives in `CORE::`, and as soon as the value is encountered, the iteration stops:

    my int $i; ++$i for CORE::.keys; say $i;     # 752
    my int $i; ++$i for CORE::.values; say $i;  # 284
    my int $i; ++$i for CORE::.kv; say $i;         # 867
    my int $i; ++$i for CORE::.pairs; say $i;     # 752

I'm afraid you can only use `.keys` and `.pairs` to iterate over `CORE::`.  It feels like it's going too much overhead to especially handle this case, which basically only occurs for iterating over `CORE::`

**Comment by lizmat** [comment]
Propose to close this ticket.

**Comment by kjkuan** [comment]
I see. Thanks for confirming. I'm fine with closing this ticket.
