### ISSUE TITLE
Improve empty hash creation performance with {}

### ISSUE THREAD

**Issue by Juerd** [rakudo/rakudo#1951]
Adding `multi sub circumfix:<{ }>() { my % }` to a program makes `{}` approximately 10x faster, and still return a new empty hash. This might be an indicator for a performance optimization opportunity.

I tried adding it to Hash.pm but that failed with the message "This type (Mu) does not support associative operations at SETTING::src/core/Mu.pm6:519".

**Comment by Juerd** [comment]
> I'd be interested to see how { } fares versus creating hashes that are initialized with particular elements in them.

I'd usually write that as `{...}` instead of `{}`, which is also why I originally didn't think of clearly specifying "empty hash" in the title.

According to a benchmark, `{...}` with a single pair literal is approximately half the speed of `my %` assigned the same single pair literal. `hash` seems much faster even, which I find weird, because it appears to be implemented using `my %` semantics.

Benchmark:
```
use Bench;
use Test;

my $foo;
my $bar;
my %subs := {
    'hash'     => sub { $foo = hash a => "b" },
    '{}'       => sub { $foo = { a => "b" } },
    'my %'     => sub { $foo = my % = a => "b"},
    'my %x ='  => sub { my %x = a => "b"; $foo = %x },
};

for %subs.kv -> $k, $v {
    say "Testing $k";
    $foo = "bad";
    $v();
    isa-ok($foo, Hash);
    is($foo.elems, 1);
    is($foo.keys[0], "a");
    is($foo.values[0], "b");
};

Bench.new.timethese: 1000000, %subs;
```

Output:
```
Testing my %x =
ok 1 - The object is-a 'Hash'
ok 2 - 
ok 3 - 
ok 4 - 
Testing hash
ok 5 - The object is-a 'Hash'
ok 6 - 
ok 7 - 
ok 8 - 
Testing my %
ok 9 - The object is-a 'Hash'
ok 10 - 
ok 11 - 
ok 12 - 
Testing {}
ok 13 - The object is-a 'Hash'
ok 14 - 
ok 15 - 
ok 16 - 
Benchmark: 
Timing 1000000 iterations of hash, my %, my %x =, {}...
      hash: 0.402 wallclock secs (0.413 usr 0.000 sys 0.412 cpu) @ 2490157.652/s (n=1000000)
      my %: 3.572 wallclock secs (3.573 usr 0.000 sys 3.573 cpu) @ 279986.953/s (n=1000000)
   my %x =: 3.636 wallclock secs (3.644 usr 0.000 sys 3.644 cpu) @ 275010.863/s (n=1000000)
        {}: 6.008 wallclock secs (6.003 usr 0.000 sys 5.999 cpu) @ 166431.222/s (n=1000000)
```

**Comment by pmichaud** [comment]
Thanks for the additional benchmarks, and yes this is an interesting result.  I think clearly there ought to be a way to improve the speed of ```{ ... }``` hash constructors, or at least to find out why it's being compiled into something that is so much slower than other alternatives.

Pm

**Comment by lizmat** [comment]
Closing in light of https://github.com/rakudo/rakudo/commit/f725f5f4bd, sorry it took so long!

**Comment by usev6** [comment]
If I'm not mistaken, the change from https://github.com/rakudo/rakudo/commit/f725f5f4bd leads to a problem on the JVM backend.
```
$ ./rakudo-j -e 'say hash(a => 1)'
Unexpected named argument 'a' passed
  in block <unit> at -e line 1
```

I might be wrong but it looks to me like the wrong multi is selected now. Since named arguments aren't taken into account, there is probably no way for the compiler to see that the alternative `multi sub hash(*%h) { %h }` should be used instead of the newly added multi sub.

Since this was "only" a performance improvement, I've opened a PR to not add the new alternative for the JVM backend: https://github.com/rakudo/rakudo/pull/5695
