### ISSUE TITLE
Rakudo::Internals.DIR-RECURSE fails if directory is deleted before iterating over it

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#1956]
## The Problem

Rakudo::Internals.DIR-RECURSE fails if a directory it will iterate over in the future gets deleted.

DIR-RECURSE is used in CompUnit::Repository::FileSystem

`S11-repository/curi-install.t` installs modules into a directory that `S11-modules/nested.t` uses as a CURFS lib.` S11-repository/curi-install.t` also deletes its files when it is finished. This can lead to a race condition if these two tests are run at the same time, but never in isolation.

## Steps to Reproduce

```
$ perl6 -e '\
    "foo".IO.mkdir andthen {\
        .add("1").mkdir.add("1").spurt("");\
        .add("2").mkdir.add("2").spurt("");\
    };\
    my $d := Rakudo::Internals.DIR-RECURSE($*CWD.add("foo").absolute);\
    say $d[0];\
    "foo".IO.add("1") andthen {\
        .add("1").unlink;\
        .rmdir;\
    };\
    say $d[1];
'
```

## Expected Behavior

Skip any directories that fail to open -- this is fine for how DIR-RECURSE gets used internally

```
/Users/ugexe/repos/rakudo/foo/2/2
(Any)
```

## Actual Behavior

```
/Users/ugexe/repos/rakudo/foo/2/2
Failed to open dir: 2
  in block <unit> at -e line 1
```

**Comment by niner** [comment]
Fixed in commit e9351cbaa961c4d1e4ef8b4cb52418d55766a8d6
Many, many thanks for the investigation!
