### ISSUE TITLE
Set.perl inconsistent with Bag/Mix.perl

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1958]
The bag and mix get `.perl` in a form of `bag()`/`mix()`, but set gets dumped as either `().Set` or `set()` (kinda surprised `Set.new` and `set()` get dumped differently, given they compare `===` as True)

```
<Zoffix__> m: .perl.say for Set.new, Bag.new, Mix.new
<camelia> rakudo-moar e9351cbaa: OUTPUT: «().Set␤bag()␤mix()␤»
<Zoffix__> m: .perl.say for set(), bag(), mix()
<camelia> rakudo-moar e9351cbaa: OUTPUT: «set()␤bag()␤mix()␤»
<Zoffix__> m: dd set() === Set.new
<camelia> rakudo-moar e9351cbaa: OUTPUT: «Bool::True␤»
```

**Comment by W4anD0eR96** [comment]
https://github.com/rakudo/rakudo/blob/e9351cbaa961c4d1e4ef8b4cb52418d55766a8d6/src/core/Baggy.pm6#L327-L355

https://github.com/rakudo/rakudo/blob/e9351cbaa961c4d1e4ef8b4cb52418d55766a8d6/src/core/Setty.pm6#L160-L175

Cherry pick from Baggy to Setty is enough.

**Comment by zoffixznet** [comment]
> There's a related ticket that could use your input as well: #1959

That's now resolved as not-a-bug, so it's fine for set()/bag()/mix() to be .perl'ed differently since in Rakudo we intern those.

The actual inconsistency now is that Set.new returns a separate object, but Mix.new/Bag.new return an interned copy. So we can "legally" make Set.new return an interned copy as well.

**Comment by lizmat** [comment]
AFAIK, `Bag.new` and `Mix.new` don't return an interned copy anymore?

**Comment by lizmat** [comment]
So I think this ticket can be closed.  Please re-open if you disagree.
