### ISSUE TITLE
RFC: warn on "... {$++} ..." and "... {++$} ..."

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1961]
I spotted about 6 bugs in the ecosystem where the construct was similar to this one:

```
$ perl6 -e 'say "count {$++}" for ^3'
count 0
count 0
count 0
```

The count doesn't increase because the anon var is mis-scoped. I figure we can probably emit a warning when a string has a block in it with just a `$++`, `$--`, `++$`, or `--$` in it? The other uses of `$` in similar circumstances won't warn, as there's probably some cases where there's no issue with it.

--------------------

If this RFC is removed, this Trap in the docs will need to be reworded to use a different example or removed entirely: https://github.com/perl6/doc/commit/77374a0a826598b35829a8b3d85538928dc4ddcc

**Comment by lizmat** [comment]
@coke Thinking about closing this
