### ISSUE TITLE
Destructuring hash signature params with defaults working as expected?

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#1967]
## The Problem

`perl6 -e 'sub foo(%h is copy [:$a = 1, *%]) { say %h.perl }; foo({})'`

## Expected Behavior

`{:a(1)}`

## Actual Behavior

`{}`

**Comment by zoffixznet** [comment]
Yeah, that looks right. 

The destructuring is done by calling `Capture` method and using that as the stuff to fill the params inside the destructure bit.

There's a way to shove a writable container into a capture, take it raw inside the destructure and write into it, but for defaults to be used the param would need to be absent from the `Capture`, so I guess there's no way to write in it.

```
<Zoffix__> m: sub foo($ [$a, :$z is raw, *%]) { dd [$z, $a]; $z = 500;  }; my $z := class Foo { has $.z is rw = 100; method Capture { \(42, :$.z) } }.new; foo $z; dd $z
<camelia> rakudo-moar e9351cbaa: OUTPUT: «[100, 42]␤Foo.new(z => 500)␤»
```
