### ISSUE TITLE
Pod input and output blocks don't preserve newlines

### ISSUE THREAD

**Issue by Tyil** [rakudo/rakudo#1968]
## The Problem

According to [the pod documentation](https://docs.perl6.org/language/pod#I/O_blocks), IO blocks should have newlines and other whitespace preserved, but newlines get squeezed.

## Expected Behavior

Newlines get preserved.

## Actual Behavior

Newlines get squeezed.

## Steps to Reproduce

Write a pod document with the following content:

```pod6
=begin pod

=begin code
This is a code block.
Newlines get preserved.
=end code

=begin output
This is an output block.
Newlines should get preserved, but are not.
=end output

=end pod
```

Run it with `perl6 --doc test.pod`. The output in the `code` block has its newline preserved, whereas the output in the `output` block does not.

## Environment
* Operating system: Funtoo Linux
* Compiler version (`perl6 -v`): Installed using LoneStar

```
This is Rakudo Star version 2018.04.1 built on MoarVM version 2018.04.1
implementing Perl 6.c.
```

**Comment by tbrowder** [comment]
Closed by commit c643383.
