### ISSUE TITLE
LTA "No such file or directory" error does not include WHICH such

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1970]
Getting this error thrown about in a program without any awaits, but with some reacts. Can't find a place to catch it (sticking a `CATCH` with a debug dump inside `whenever` makes the error vanish), but more importantly, it doesn't tell me what file or directory it's trying to do something with.

Is this from my `Proc::Async` code that tries to run a process (which one?) Is this from the guts of File::Find module trying to read a file?

Don't know if it's possible to provide that information, but having it would be immensely helpful in this situation.

```
An operation first awaited:
  in sub MAIN at reapp.p6 line 13
  in block <unit> at reapp.p6 line 57

Died with the exception:
    no such file or directory
      in sub MAIN at reapp.p6 line 13
      in block <unit> at reapp.p6 line 57
```

**Comment by zoffixznet** [comment]
Still didn't manage to find what the problem is. And now I ran out of time and have to switch to other tools for this job. No Perl-6-in-production for this job due to a poor error.

**Comment by lizmat** [comment]
Closing because of lack of gold
