### ISSUE TITLE
Allow another NQP repo source for a rakudo build

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#1984]
## The Problem

Developers have no easy way to test NQP changes with a rakudo build.

## Expected Behavior

Have a configuration option something like “—nqp-repo-user=X” so NQP forks can be used.

## Actual Behavior

Takes manual editing of file tools/lib/NQP/Configure.pm to use another NQP repo.

**Comment by zoffixznet** [comment]
You just compile nqp and when you build rakudo you [use the same `--prefix=` that use used when building nqp](https://github.com/zoffixznet/z/blob/fb991d307ca5207dacd244590030ebae6786bc09/lib/RDev.pm6#L227-L243) (i.e. use the same install location)

**Comment by tbrowder** [comment]
I’ve found you need this instead. Say you used for nqp “—prefix=$DIR”, then you
need for rakudo “—with-nqp=$DIR/bin/nqp”.
