### ISSUE TITLE
Call Perl 6 from C

### ISSUE THREAD

**Issue by TisonKun** [rakudo/rakudo#1991]
Our awesome NativeCall makes it easy to bind C lib inside Perl 6 thus we acquire goodies from exist clib.

Recently I heard from a Perl 6 interest group that it would be appreciated if one can call Perl 6 from C easily. That's to say, like [mruby](https://github.com/mruby/mruby), one can `#include "perl6.h"`, embedding Perl 6 and catch all its goodies.

**Comment by lizmat** [comment]
Have you looked into how the Inline::Perl6 module in Perl 5 does it?

**Comment by W4anD0eR96** [comment]
Sorry, no. What is that relevant?

**Comment by W4anD0eR96** [comment]
That's it. Though it is not a general, easy-to-use embedding solution. (it would provide a generated perl6.h and more top-level bridges)

Inline::Perl6 is a great lib, I will introduce it to the group :-)

**Comment by jnthn** [comment]
The `Inline::Perl6` approach does show the way to a general solution, however, namely that you:

1) Embed MoarVM
2) Use it to run a Perl 6 program that registers callbacks that the C code can use, via. `NativeCall`
3) Call those callbacks from the C code to trigger the Perl 6 code to do things as appropriate

I think a reasonable way forward would be to provide a minimal working example of this, along with some explanation of how it works. Also, on the MoarVM side, we should probably document what functions we could as part of providing a stable embedding interface, as well as look if there are other things that we need to do to make it more embedding friendly.

Of course, this only covers the MoarVM backend, but that's the only one that seems immediately reasonable to embed in a C program anyway. :-)

**Comment by TisonKun** [comment]
close as no longer interested in.

**Comment by AlexDaniel** [comment]
Callbacks do work, so I'm fine with this being closed.
