### ISSUE TITLE
Examine codebase for subs that can be `is pure`d

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1992]
*Note: routines that appear too early in the setting are affected by [R#1566](https://github.com/rakudo/rakudo/issues/1566). If resolving this Issue before that one, ensure what you purify still `~~ Callable`.*

We probably have a bunch of stuff that is currently missing `is pure` trait.

```
m: say .?is-pure for &list, &hash, &slip, &so, &substr
rakudo-moar 84f60adad: OUTPUT: «Nil␤Nil␤Nil␤Nil␤Nil␤»
```

My understanding is `is pure` *"means that the result is only dependent on the parameters and nothing else. It doesn't *have* to memoize or anything like that, but it wouldn't be wrong for it to"*. In other words, if all the args are known at compile time, the routine can be executed right there and then and its result used in the place of the call.

Note that currently static optimizer expects the `is pure` to be applied to the **proto** of multi subs and will not see it if you add it only to some candidates.

**Comment by zoffixznet** [comment]
FYI: http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-29#l748

```

14:53 | timotimo | i have a cautionary tale for you
-- | -- | --
14:53 | timotimo | we made x "is pure" at some point, and that caused performance to drastically worsen for very long resulting strings
14:53 | Zoffix | lizmat: ok, let SmokeMachine know :) I think they were working on that too
14:54 | Zoffix | timotimo: because it flattened the ropes?
14:54 | timotimo | because  the object it was creating had been serialized before the execution  started, so we ende up turning the string that was "this short thing  repeated 1000 times" in memory (i.e. implemented with a strand) into  actually many kilobytes (or megabytes in this case) of string data
14:54 | timotimo | yes
```

That problem was worked around with this piece of code in the optimizer: https://github.com/rakudo/rakudo/blob/84f60adad10f04b3ffa4a5747af9820f8244c2a2/src/Perl6/Optimizer.nqp#L1636-L1647

So possibly stuff that works with strings would either need to remain unpure or would require similar treatments (if they're worth it).

**Comment by zoffixznet** [comment]
Spotted one op that currently isn't constant folded, but probably should be:

```perl6
$ perl6 --target=optimize -e 'say ’a‘ <=> ’b‘'
[...]
- QAST::Op(callstatic &say) <sunk> :statement_id<1> say ’a‘ <=> ’b‘
                  - QAST::Op(callstatic &infix:«<=>») <wanted> <=>
                    - QAST::Want <wanted> a
                      - QAST::WVal(Str) 
                      - Ss
                      - QAST::SVal(a) 
                    - QAST::Want <wanted> b
                      - QAST::WVal(Str) 
                      - Ss
                      - QAST::SVal(b) 
```

**Comment by lizmat** [comment]
Closing as we won't be working on the legacy optimizer anymore
