### ISSUE TITLE
Bogus(?) Error when `is required` an attribute of CStruct repr

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1993]
If you mark an attribute as `is required` on a class with `CStruct` repr, then you get an error about `CStruct representation attribute`. Is that an accurate error? Sounds like it's saying an attribute with `CStruct` repr isn't supported, which isn't what the code is trying to use:

```
$ perl6 -e 'use NativeCall; class B is repr("CStruct") { has uint32 $.b } ; B.new(:1b)'


$ perl6 -e 'use NativeCall; class B is repr("CStruct") { has uint32 $.b is required} ; B.new(:1b)'
CStruct representation attribute not yet fully implemented
  in submethod BUILDALL at -e line 1
  in block <unit> at -e line 1

This is Rakudo version 2018.05-54-g148d7c5 built on MoarVM version 2018.05-57-g89dee3b
implementing Perl 6.c.
```

Looks like it comes [from here](https://github.com/MoarVM/MoarVM/blob/411f73fdcefeb68c75314e5e30d97d1c8da70645/src/6model/reprs/CStruct.c#L643-L646), but I'm unsure if the error should be changed to say the trait is not supported or if there is actually a way to check if an attribute has been initialized and that should be implemented instead of throwing an error.

**Comment by lizmat** [comment]
This appears fixed.  Added test with https://github.com/rakudo/rakudo/commit/b94ad1d7b3 so closing
