### ISSUE TITLE
establish a public key trust network for Rakudo and Perl

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#1994]
Here is a link for Debian's PKI (Public Key Infrastructure) key signing HOWTO which also discusses how to build a web of trust: <https://wiki.debian.org/Keysigning/>.

Here's a link to more PKI info: <https://en.wikipedia.org/wiki/Public_key_infrastructure>.

Folks near each other could start cross-signing keys, and get more cross-signed keys at Perl 6 gatherings. 
@masak and @jnth and others at Edument are a natural starting point, @coke, would also be a good one to start with his position at the Perl Foundation.  @lizmat and others who attend lots of Perl gatherings are also good starting points.

It would be handy to establish one main key server to use for Perl if there isn't one already.
Key locations and other PKI information needs to be published on the downloads page

**Comment by AlexDaniel** [comment]
FWIW I'm not convinced that what is asked in the OP is worth it, but I do agree that the current situation with tarball signing is a bit LTA. It's not entirely obvious where the public key is (see also https://github.com/perl6/nqp/issues/426). Compilers for other languages seem to link to the key on the download page, and that's one thing that we can improve for sure.

**Comment by lizmat** [comment]
Closing as this feels more like a problem solving issue.  Please re-open as such referring to this issue if you agree.
