### ISSUE TITLE
No way to use Test.pm6 routines in userland Test libraries

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1998]
Because all the diagnostics would reference the Test library's use of routines instead of the user's of that Test library: http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-30#l391

Currently, we just examine callframes and find the first that isn't from Test.pm6's file: https://github.com/rakudo/rakudo/blob/ddf496c72b2d90b9b02c7729d2d5806a71791a85/lib/Test.pm6#L715-L720

Maybe there could be something better that can also be used by the user?

P.S.: IIRC Perl 5's Test::Builder uses a global var to tell the "level" of nestiness so it could figure out how many frames to skip and I vaguely recall earlier discussions that we do NOT want any similar mechanism because it doesn't work quite well or something.

**Comment by lizmat** [comment]
Closing since we have the [`is test-assertion`](https://docs.raku.org/type/Routine#trait_is_test-assertion) trait nowadays.
