### ISSUE TITLE
`reduce` needlessly deconts

### ISSUE THREAD

**Issue by smls** [rakudo/rakudo#2000]
## Motivation

I tried to do a multi-dimensional Hash access with the help of `reduce`, as follows:

``` Perl 6
my %hash;
my @path = <a b c>;
my $value = 42;

my $slot := (%hash, |@path).reduce: &postcircumfix:<{ }>;

$slot = $value;  # ERROR: Cannot assign to an immutable value
say %hash;       # EXPECTED: {a => {b => {c => 42}}}
```

For non-existent elements, `postcircumfix { }` returns `Scalar` containers which autovivify when subscripted or assigned to. Therefore, it is critical in this example to pass these `Scalar`s on and not decont them.

Unfortunately, `reduce` decontainerizes its result before returning it, rendering this example non-functional.

## Investigation

It looks like `reduce` does preserve the containers when passing values from one invocation of the callback to the next, and only deconts the final result, as the following example demonstrates:

``` Perl 6
my $x = 1;
my $result := ($x, 2, 3, 4).reduce: -> $a is raw, $ {
    say ($a, $a.VAR.^name);
    $a
};
say ($result, $result.VAR.^name);
```
Output:
```
(1 Scalar)
(1 Scalar)
(1 Scalar)
(1 Int)
```

Maybe it's just a missing `is rw` on `sub reduce`?

## Expected Behavior

`reduce` should return the result exactly as the last invocation of the callback produced it, without deconting.

## Environment

This is Rakudo version 2018.06-25-ge9351cbaa built on MoarVM version 2018.06
implementing Perl 6.c.

**Comment by ab5tract** [comment]
So even if/when #5578 is merged, there will be an issue with the provided test case that uses `&postcircumfix:<{ }>`: `METAOP_REDUCE_LEFT` utilizes the `count` of the provided callable to determine how to rotor the reduction list into arguments for the callable.

For multis, `count` returns the total arguments for the proto (or `Inf`).

```
proto sub postcircumfix:<{ }>(Mu $, Mu $?, Mu $?, *%)
```

So the provided code still won't work as desired.

However, it can be changed to:

```
my $slot := (%hash, |@path).reduce: &postcircumfix:<{ }>.candidates.grep({.signature ~~ :(\SELF, Mu \key)  }).first
```

or

```
my $slot := (%hash, |@path).reduce: sub ($h is raw, $k) is raw { $h{$k} }
```

**Comment by ab5tract** [comment]
This one is finished and tested in [roast @ 8c34c67aac](https://github.com/Raku/roast/commit/8c34c67aac).
