### ISSUE TITLE
[RFC] Implement `:handle-win-shell` arg to `run`, `shell`, and `Proc::Async.new`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2005]
N.B.: I started on implementation already as part of fixing roast on Windows effort, so unless there's any 👎 on this, it will go in soonish.

The API is a bit warty, hoping there are better ideas.

## The Problem

- Window's shell (`cmd.exe`) requires [special quoting of command line arguments](https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/) that conflict with "normal" quoting.
- This is responsible for large portion of current [prop/spec]test failures on Windows, because `is_run` helper test routine fails execution if arguments are involved (more of them were passing [in the past because we passed arguments verbatim on windows](https://github.com/MoarVM/MoarVM/commit/05a7dc3d692a15d200affceac0d5cc459c6c1b7a), which used to cause a different set of issues)
- This means some commands are impossible to `shell` on Windows, because even if you quote stuff for `cmd.exe` yourself, the "normal" quoting MoarVM then does on top of that creates conflicts. E.g. this doesn't run: `shell  ｢perl6 -e "say \"@*ARGS foo\"" foo bar ber｣;`
- The reasons `run` and `Proc::Async.new` are included as well is because they can be used to execute a "batch" file (a shell script basically), so that option will be used with them as well. See [RT#132258 `run "perl6" ...` can be made to execute shell commands](https://rt.perl.org/Public/Bug/Display.html?id=132258#ticket-history)

## Proposed Solution

- Make `shell`, `run`, and `Proc::Async.new` accept `:$handle-win-shell` arg
    - It will have no effect on OSes that aren't Windows
    - It will currently take values `True` and `False`; in the future, it'll also take `Nil` for behaviour where it retries with alternative quoting if the first execution fails (I believe Perl 5's `qx//` or `system` do this by default).
- on `shell`, this argument will default to `True` and will mean to pass the given string to `cmd.exe` without applying any quoting. On implementation side of things, this will set `UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS` libuv flag, which is how we had things [until about a year ago](https://github.com/MoarVM/MoarVM/commit/05a7dc3d692a15d200affceac0d5cc459c6c1b7a), and that's it. We won't do any quoting at all.
    - Setting it to `False` would disable that libuv flag
- on `run` and `Proc::Async.new`, default will be `False` and setting it to `True` will apply `cmd.exe`'s quoting to all the args, instead of the "normal" quoting. On impl. side, this will set `UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS` flag and will use our hand-rolled arg quoter, based on this info: https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

## Warts

I don't like that the default value is not the same across all three routines. Perhaps, this option shouldn't be available on `shell` at all and should just be enabled by default at all times. Is there any good reason to have the option off?

If the arg is to not be available on `shell`, then I'd rather name it `:quote-win-shell`

**Comment by ugexe** [comment]
Other languages using libuv just expose the`UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS` flag:

https://github.com/JuliaLang/julia/pull/13780
https://github.com/nodejs/node/issues/5060

Of course such a flag is only enabling/disabling behavior that doesn't make much sense in the context of other back ends ( except the nodejs one which is backed by libuv, but that is besides the point ) since the mangling/escaping doesn't happen in rakudo itself. This makes me think the best solution would be to implement `UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS` in rakudo, and add a flag to toggle its use.

**Comment by patrickbkr** [comment]
This is technically solved.
What's missing is having a look at roast on Windows.

**Comment by patrickbkr** [comment]
I'm unsure what I meant with roast on Windows. I'll close this for now.
