### ISSUE TITLE
Regression with .comb on IntStr zero with leading zeros

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#2010]
## The Problem

The `.comb` method on an IntStr typically treats the invocant as a Str, however that does not appear to be the case with an IntStr of zero with leading zeroes, eg. `< 0000 >`

[IRC discussion](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-02#l178)

## Expected Behavior
```perl-6
<0000 0001>».comb.say  # OUTPUT: «((0 0 0 0) (0 0 0 1))␤» 
```
## Actual Behavior
```perl-6
<0000 0001>».comb.say  # OUTPUT: «(() (0 0 0 1))␤»
```
## Steps to Reproduce

This appears to be a regression since commit [d444f655](https://github.com/rakudo/rakudo/commit/d444f655fd82df4b71f29c0a04fc2626bc76be53)

**Comment by lizmat** [comment]
Added tests with 32157bd352 .  Thanks for reporting!
