### ISSUE TITLE
What makes `unit` be too late?

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2020]
I know you can stick `sub EXPORT {...}` before `unit foo` declaration, however, looks like you can stick any number of subs before `unit` as well:

```
16:24 | Zoffix | m: sub foo {}; unit class Bar;
16:24 | camelia | rakudo-moar 058addf14: ( no output )

16:24 | Zoffix | m: class foo {}; unit class Bar;

16:24 | camelia | rakudo-moar 058addf14: OUTPUT: «=== SORRY!===   Error while compiling <tmp>␤Too late for unit-scoped class  definition;␤Please use the block form.␤at <tmp>:1␤------> class foo {}; unit class Bar; ⏏ <EOL> ␤»
```

Is there a logical reason why subs are allowed, but classes/packages/modules are forbidden, or does this need to be tightened up to allow `EXPORT` sub only?

-----------------

I filed [D#2148](https://github.com/perl6/doc/issues/2148) to correct the documentation, and once this Issue is resolved, the result would go in to fix that issue.

**Comment by JJ** [comment]
Should we move this to the problem-solving repo?

**Comment by 2colours** [comment]
@JJ almost 4 years later... in the name of "forgiveness > permission", I would ask you to move it, if you still hold the sufficient permissions.

**Comment by JJ** [comment]
Afraid I don't have enough privs in this organization...

**Comment by lizmat** [comment]
Closing here, please re-open as a problem-solving issue if necessary.
