### ISSUE TITLE
Bad error "P6M Merging GLOBAL symbols failed: duplicate definition of symbol DocLinks"

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2021]
I've just made a bunch of changes in https://github.com/perl6/synopsebot/commit/386197a8d7f6435170c9bc1e0fb5e1bbde6b4fb9 and tried to start the bot, and it craps out with this error:

```bash
git clone https://github.com/perl6/synopsebot
cd synopsebot
git checkout 386197a8d7f643517
./dev-start-localhost 

===SORRY!===
P6M Merging GLOBAL symbols failed: duplicate definition of symbol DocLinks

$ perl6 -v
This is Rakudo version 2018.05-54-g148d7c5 built on MoarVM version 2018.05-57-g89dee3b
implementing Perl 6.c.
```

I'm guessing there's something duplicate, but *where* are those definitions comings from? The error doesn't say. Had it said, I'd immediately notice that I forgot to [change the class name](https://github.com/perl6/synopsebot/commit/386197a8d7f6435170c9bc1e0fb5e1bbde6b4fb9#diff-86bb7e0cbf05bb65f5449cd388323809R4) when I copy-pastaed the definition of a plugin.

---------------

P.S.: the "P6M Merging GLOBAL" is also not very… human… What exactly is "P6M" and why I, the user, need to be told about it? GLOBAL is familiar to me now, but isn't quite a thing most programmers come across often. Just saying *"Merging symbols failed: "* maybe clarifying more, saying that *"are you using the same names in multiple modules you're trying to load?"* or something.

**Comment by AlexDaniel** [comment]
Blocker label for myself. Don't know what's going on here, will check later.
