### ISSUE TITLE
LTA error: "not found module" message does not include file

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2022]
The error says "at line 1", but line 1 of which file? Many projects have multiple files with modules

```
$ echo "use Blah" > Foo.pm6
$ perl6 -I. -MFoo -e ''
===SORRY!===
Could not find Blah at line 1 in:
    /tmp/tmp.9BKT1VcNMJ
    /home/zoffix/.perl6
    /home/zoffix/rakudo/install/share/perl6/site
    /home/zoffix/rakudo/install/share/perl6/vendor
    /home/zoffix/rakudo/install/share/perl6
    CompUnit::Repository::AbsolutePath<67564160>
    CompUnit::Repository::NQP<45884840>
    CompUnit::Repository::Perl5<45884880>
$ perl6 -v
This is Rakudo version 2018.05-54-g148d7c5 built on MoarVM version 2018.05-57-g89dee3b
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
(for records, there's been additional discussion on the PR for this Issue: https://github.com/rakudo/rakudo/pull/2038#issuecomment-403482926 )

**Comment by niner** [comment]
I see two ways to get the source information into the error message:
* we either communicate the source location from the caller down to where the error is created or
* we catch the error and enhance the message at the point where we have the required information

I think the second option is the way to go as it works without adding unrelated attributes to `CompUnit::DependencySpecification` and without requiring each CompUnit::Repository implementation to support it. All that's required is catching the X::CompUnit::UnsatisfiedDependency, adding the source location info and then rethrowing it.

**Comment by niner** [comment]
Implemented in https://github.com/rakudo/rakudo/commit/6f527cea9a
