### ISSUE TITLE
Issues with contributors generating script

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2028]
This is going off from [R#2024](https://github.com/rakudo/rakudo/issues/2024).

There are these issues present in [the contributors generating script](https://github.com/rakudo/rakudo/blob/master/tools/contributors.p6) that caused or have potential to cause us to miss contributors:

#### Relying on the time when release manager runs the contributor script, potentially creating a gap of unrecorded contributions between the time the script is run and the time the next run considers as "last release".

The script currently uses the timestamp on rakudo's tag to determine the time of last release. However, there's a gap between the time when the release announcement is generated and when the tag is created. Anyone who makes a contribution during that time period is lost.

*This can potentially be fixed by recording (in some file in rakudo's repo) the last commits of each repo that were recorded for a release, and starting next release from those commits*

#### Relying on release manager's setup of directories/repos

We've missed a lot of contributors in 2016 because of the contributors script silently ignoring missing repo checkouts. However, even after [a previous fix](https://github.com/rakudo/rakudo/commit/05133931a9b6b2dd48e4001889bf7dbe37d5b8a4#diff-508f29ffdf70323e02c5be76f4f30364) in this area, we're still relying on the release manager to have up-to-date checkouts of repos (I think they have to be in the right branch too).

*This can potentially be fixed by using GitHub API to query info for new commits, like [Geth bot does](https://github.com/perl6/geth)*

#### What happens with commits made at the time of past release in a branch that are merged at the time of the next release?

Do they get lost? During my run of the contributors script with `for release ...` feature for past release lookup, I'm consistently getting 3-4 names I can't really explain why they're missing. Are these people from the "gaps" of the release or are these branches being merged with commits from them landing into the already-shipped releases and thus never seen by the script?

#### Missing contributors from entire repositories due to unnoticed bug in the code

We've been missing **all** contributors from MoarVM since 2016.09 due to [R#2024](https://github.com/rakudo/rakudo/issues/2024) but that went unnoticed.

Unsure if a solution to detect this is needed or possible. We could split the contributors list in the announcement into 5 categories, one for each repo (the downside is that waters down the total amount of commits the user made, which is currently used to sort the list).

#### Repos list is kinda arbitrary

For example `rakudo/star` isn't tracked; none of our websites repos are tracked. I'm just wondering if there's anyone else out there being upset that their work is never credited (like it was with the person who got missed twice on current list)?

**Comment by AlexDaniel** [comment]
> This can potentially be fixed by recording (in some file in rakudo's repo) the last commits of each repo that were recorded for a release, and starting next release from those commits

I think it should simply work based on the tagged commit. Just looking at the log of tag..HEAD should be enough, as far as I know. Why it wasn't done this way in the first place is unknown to me.

> However, even after a previous fix in this area, we're still relying on the release manager to have up-to-date checkouts of repos (I think they have to be in the right branch too).

Yes, this is somewhat annoying, but at the same time it allows me to use a branch of my choice (e.g. a release branch like I did for the very last few releases). It is still annoying because it has to be checked out in *all* repos properly…

**Comment by zoffixznet** [comment]
> Why it wasn't done this way in the first place is unknown to me

Doesn't seem to work. Here I see merges of branches, but the actual commits in those branches are "missing". Also, docs and roast ain't got no tags.

```
2018.05.122 zoffix@VirtualBox~/R/rakudo (master)$ git log --oneline --author=zoffix 2018.06...HEAD
1197c3f65 (HEAD -> master, origin/master, origin/HEAD) Make debug option dump repo info
f6c8159d2 Add --debug flag to contrib tool
c5cfbc64a Sort contribtrs with same commits num alphabetically
8fee8d485 Implement contributor lookup for past releases
7a87b7f55 Restore missing MoarVM repo in contrb gen script
4b0f39853 chmod +x ./tools/contributors.p6
058addf14 Merge pull request #2018 from jkramer/issue-1906
2f8074beb Merge pull request #2019 from jkramer/issue-1746
4bdb9787d Merge pull request #2006 from taboege/typo-immediately
82866b72b Merge pull request #2004 from JJ/patch-1
0721bfa75 Round the `of the time` measure as well
587cd4f9e Remove commented-out .child-secure
2177ee234 Add S03-metaops/misc.t to list of test files
b9b0838dd Opt nested meta assigns / fix meta assign bugs
23045bc86 Let QAST test helpers use smartmatching instead of `eq`
1dea30342 Merge pull request #1935 from rakudo/car-grant-constants
40bf22e9c Merge branch 'post-release-2018.06' into car-grant-constants
2871cd9e1 Merge branch 'master' into post-release-2018.06
a1f544ad4 (origin/car-grant-constants, car-grant-constants) [CaR Grant] Implement basic typecheck and coercers on constants
4dcf5929d Implement $*W.lang-ver-before method
b6cd61228 [CaR Grant] Implement X::ParametricConstant exception
0e2a7d93c Make safely_stringify routine safer
60447c626 [CaR Grant] Make Map.list return a List instead of Seq
c49a6ed1f Merge branch 'master' into car-grant-constants
b36f54b41 Fix typo
2138197b7 Merge branch 'master' into post-release-2018.06
9ea427a36 Fix/Test REPL auto-printing of low-level objects
0ef7109e7 (post-release-2018.06) Merge pull request #1921 from jstuder-gh/param_all_slurpies_not_positional
4854c05c0 [CaR Grant] Add S04-declarations/constant-6.d.t to list of tests
2018.05.122 zoffix@VirtualBox~/R/rakudo (master)$ 
```

**Comment by zoffixznet** [comment]
Published my research that led to this Issue as well as a list of missing contributors in https://rakudo.party/post/The-Missing-Contributors-of-Perl6

Once thing I noticed is the contrib script genned a new list for past releases that did not have one or more people that were on the announcement (just some historical artefact of people adding/changing their names in CREDITS?)

Also, I notice brrt is the frequent-misser on the list, missing even before the MoarVM-repo-dropping bug was introduced. One thing I recall is they were working on a JIT branch for year+. So I think their "missing" from the announcements is just those old commits that are now in master showing up as if they were in those releases?

Anyway, something about the script is really wonky.

**Comment by AlexDaniel** [comment]
> Docs and roast ain't got no tags tho

Ah… right. Maybe I should start tagging roast with rakudo-specific tags (e.g. `rakudo-2018.05`). For example, if today you decide to spectest 2018.05 against roast master, then only I know which commit was used when I was doing the release. Moreover, for latest releases when I was cutting from a release branch, I had to actually write out a commit hash for roast (because by the time the release was cut there were new tests that covered post-release bug fixes and whatever).

As for the doc repo, I think it has to rely on log xxx..HEAD mechanism also, even if there are no tags. I *think* when merging old pull requests the commit date can be much older (have older committer/author dates), so `--since` can filter that out. *So there's a chance that more people are missing.*

> What happens with commits made at the time of past release in a branch that is merged at the time of the next release? Do they get lost?

Pretty sure they won't be lost if `git log xxx..HEAD` is used.

**Comment by AlexDaniel** [comment]
Alright, so I worked a few hours on this today… it's a bit more difficult than it sounds. I am on the right track though, so sooner or later it will be done.

I understand that it is very important to generate the list properly, but depending on issues with other release-related things, this may no be ready before this release. I'm removing the blocker label because technically it is not blocking us from cutting this release, but I'll try to get it done asap.

**Comment by AlexDaniel** [comment]
Uhhhh, this slipped through the cracks really bad. I'm wondering how wrong the contributors list for 2019.03 is. I'll unassigned myself, but maybe now that I won't be doing releases I'll actually have some mental power to fix this.

**Comment by lizmat** [comment]
Please re-open if this still is an issue.
