### ISSUE TITLE
no warning for Callable in sink context

### ISSUE THREAD

**Issue by Juerd** [rakudo/rakudo#2040]
## The Problem
A bare block in sink context will execute immediately. Someone might expect similar behavior for other subs and blocks, but they are silently ignored. The lack of warning could make that harder to discover.

## Expected Behavior
    1;0 juerd@cxien:~$ perl6 -e'{ say "Hello, world!" }; sub { say "unreachable" }; -> { say "also unreachable" }'
    WARNINGS for -e:
    Useless use of anonymous sub in sink context (line 1)
    Useless use of pointy block in sink context (line 1)
    Hello, world!

## Actual Behavior
    perl6 -e'{ say "Hello, world!" }; sub { say "unreachable" }; -> { say "also unreachable" }'
    Hello, world!

**Comment by Juerd** [comment]
The case of an sunk anonymous sub could be made more awesome if it said something like "Did you forget to provide a name?" because it might only an identifier away from being useful code.

**Comment by lizmat** [comment]
The anonymous sub case has been fixed with d6c0539507 .

**Comment by lizmat** [comment]
I'm tempted to leave the `Block` case with signature be.  I feel that it is a much more rare error to be doing that, as it requires knowledge of the full citizenship of `Blocks`.

Also, https://github.com/rakudo/rakudo/blob/master/src/Perl6/Optimizer.nqp#L934 appears to imply that not complaining about `Block`s in void context is actually intentional.

**Comment by zoffixznet** [comment]
> imply that not complaining about Blocks in void context is actually intentional.

That's for phasers, per commit message in https://github.com/rakudo/rakudo/commit/f02606cea4d4508dab2d92d3cf7bfbd18700073f

It reads:

> The blocks of interest appear to be already annotated with 'WANTMEPLEASE'

So perhaps more than just phasered blocks are marked with that and it needs to be refined.

**Comment by lizmat** [comment]
ok, will look at it deeper tomorrow.

**Comment by lizmat** [comment]
Ok, I can't actually quickly see where the `-> { }` is being handled in the Optimizer.  Since I think this error is quite less likely than forgetting to give a sub a name, I'm not going to spend more time on this at the moment and close this ticket.  Please reopen if you feel otherwise.
