### ISSUE TITLE
LTAness with putting space before sig specifier of Callable

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2044]
There is a host of things here, some of which are probably of the DIHWIDT variety, but maybe some could be improved.

This is on 2018.05-54-g148d7c5.

--------

Since spaces are needed to unpack stuff like Arrays in signatures, I wrote a thing like this:

```
$ perl6 -e 'sub (&s :()) {}'
===SORRY!=== Error while compiling -e
Can only use the : invocant marker in the signature for a method
at -e:1
------> sub (&s :()⏏) {}
    expecting any of:
        constraint
```

The actual signature was longer, so the cursor was pointing in the wrong place, but eventually I realized that it's the extra space in the signature specifier of the Callable that was causing the problem (maybe that can be included in the error as a suggestion to check?)

-----

However, if you write it that way in places where invocant markers are allowed, you get silence and a signature you did not intend:

```
$ perl6 -e '.say for :(&s :(), *%_), method (&s :()) {}.signature'
(&s: $ (), *%_)
(&s: $ (), *%_)
```

Strangelly, though those two signatures gist the same, they smartmatch False:

```
$ perl6 -e 'say :(&s :(), *%_) ~~ method (&s :()) {}.signature'
False
```

-------

Also, there's this crash if you remove the space and make the thingie an invocant:

```
$ perl6 -e 'say :(&s:():)'
No such method 'multi-invocant' for invocant of type 'Any'
  in block <unit> at -e line 1
```

**Comment by lizmat** [comment]
In RakuAST:
```
% RAKUDO_RAKUAST=1 raku -e 'say :(&s:():)'
===SORRY!=== Error while compiling -e
Can only use : as invocant marker in a signature after the first parameter
```

Closing as all of these really feel like DIHWIDT
