### ISSUE TITLE
Rescalar merge & other toaster-related stuff

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2047]
## ✓ First round done, next toaster run will be in another ticket ✓

First toaster run:

* ✓ – potentially OK
* ✗ – clearly broken

| Module | Status | Comment |
|:--|:--:|:--|
| ANTLR4::Grammar | ✗ | Rakudobug https://github.com/rakudo/rakudo/issues/2046 |
| AWS::Session | ✗ | rescalar, PR https://github.com/zostay/AWS-Session/pull/1 |
| Algorithm::LibSVM | ✓ | flop |
| Algorithm::Trie::libdatrie | ✗ | randomization, PR https://github.com/zengargoyle/p6-Algorithm-Trie-libdatrie/pull/2 |
| App::GPTrixie | ✓ | dep on XML |
| App::redpanda | ✓ | dep on Getopt::Type |
| ArrayHash | ✗ | randomization, [author notified](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-11#l345), expecting a fix soon |
| Audio::Fingerprint::Chromaprint | ✓ | flop |
| Audio::Hydrogen | ✓ | dep on XML |
| Auth::SAML2 | ✓ | dep on XML |
| CSS::Module | ✓ | dep on CSS::Specification |
| CSS::Specification | ✓ | can't reproduce, likely a toaster-induced flap |
| Cache::Async | ✓ | ticketed flap https://github.com/robertlemmen/perl6-cache-async/issues/1 |
| Cro::TLS | ✓ | flap |
| DB::Model::Easy | ✓ | flap |
| Data::StaticTable | ± | randomization + previously flapping tests, ticketed https://github.com/shinobi/Data-StaticTable/issues/4 |
| GTK::Simple | ✓ | flap |
| Getopt::Type | ✗ | rescalar, PR https://github.com/tadzik/Getopt-Type/pull/3 |
| Git::Config | ✓ | weird toaster flap |
| HTML::Parser | ✓ | dep on XML |
| HTML::Parser::XML | ✓ | dep on XML |
| HTTP::Headers | ✗ | rescalar, PR https://github.com/zostay/p6-HTTP-Headers/pull/11 |
| Linux::Fuser | ✓ | can't reproduce, some sort of a flap |
| MinG | ✗| rescalar, rakudobug https://github.com/rakudo/rakudo/issues/2056#issuecomment-404575027 |
| Native::Packing | ✗| loop rakudobug https://github.com/rakudo/rakudo/issues/2069 |
| Net::XMPP | ✓ | dep on XML |
| P5quotemeta | ✗ | rescalar, rakudobug https://github.com/rakudo/rakudo/issues/2058 |
| P5substr | ✗ | rescalar, PR https://github.com/lizmat/P5substr/pull/1 |
| PDF | ✗ | rescalar, [fixed](https://github.com/p6-pdf/PDF-p6/commit/32c949a94d75b99ca1cf84282bffbc24feffab49) |
| Pekyll | ✓ | dep on XML |
| Printing::Jdf | ✓ | dep on XML |
| ProblemSolver | ✗ | randomization, PR https://github.com/FCO/ProblemSolver/pull/1 |
| Proxee | ✗ | rescalar, [fixed](https://github.com/zoffixznet/perl6-Proxee/commit/4c39fe1ae91b9ef1cf59097e21fb8f3ddfd5527a) |
| Slang::SQL | ✗ | loop rakudobug? https://github.com/rakudo/rakudo/issues/2069#issuecomment-405004712 |
| Sparrowdo::Chef::Client | ✓ | flop |
| Spit | ✗ | rescalar, rakudobug https://github.com/rakudo/rakudo/issues/2056 |
| Syndication | ✓ | dep on XML |
| Test::Notice | ✓ | dep on XML |
| Typesafe::HTML | ✓ | dep on XML |
| Typesafe::XHTML::Writer | ✓ | dep on XML |
| Unicode::PRECIS | ✗ | rescalar, rakudobug https://github.com/rakudo/rakudo/issues/2056 |
| Web::Scraper | ✓ | dep on XML |
| XML | ✗ | rescalar, PR https://github.com/supernovus/exemel/pull/55 |
| XML::Canonical | ✓ | dep on XML |
| XML::Class | ✓ | dep on XML |
| XML::Query | ✓ | dep on XML |
| XML::Rabbit | ✓ | dep on XML |
| XML::Signature | ✓ | dep on XML |
| Yapsi | ✗ | unknown, rakudobug https://github.com/rakudo/rakudo/issues/2057 |
| flow | ✓ | ticketed flap: https://github.com/tony-o/perl6-flow/issues/7 |

**Comment by zostay** [comment]
AWS-Session fix is released (or in the process of release). I'll take another look at the ArrayHash issue when I get a chance.

**Comment by AlexDaniel** [comment]
All rakudo bugs were ticketed. I filed PRs for affected modules trying to fix as much as I can. This ticket can be closed now. I'll open another ticket for next toaster run if there are as many failures as we have seen this time (otherwise I file rakudobugs and send PRs without a ticket). Also, modules that are marked with ✓ are not necessarily OK, but we will see their actual status a bit later (e.g. once the PR for XML is accepted).

**Comment by AlexDaniel** [comment]
Ah also, some things that are marked with “rescalar” in this ticket are not necessarily related to rescalar, see [this comment](https://github.com/rakudo/rakudo/issues/2057#issuecomment-405024240). It was just a crude way for me to categorize and make sense of noticed failures.

**Comment by supernovus** [comment]
I merged the pull request for XML.
