### ISSUE TITLE
Yapsi module is failing its tests

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2057]
I don't have much info. The module (https://github.com/masak/yapsi) was passing its tests in 2018.06 and now it doesn't.

Bisected: (2018-07-09) https://github.com/rakudo/rakudo/commit/c2446b03fa2341c6708277df8667e6356201cc21

Output before and after: https://gist.github.com/AlexDaniel/226eb12c876335a6b4b387d18cbaa8d5

There's a lot of stuff in the bump so it's unclear what exactly caused it. I can maybe bisect nqp/moar if there's no other hope.

**Comment by masak** [comment]
I minimized the failing Yapsi test to this.

    $ perl6 -e'"" ~~ /{ (make 0 for 0) }/ && .say for ^100'

Usually fails after around 50 or so iterations here.

* The `&& .say` part is not essential and only there for debugging.
* The parentheses are essential.
* The match and the `/{ ... }/` construction seems to be necessary.
* The statement-modifier `for` is essential.
* The `make` is essential.

It appears to be a spesh-related failure. Running with MVM_SPESH_DISABLE=1 makes the problem go away.

**Comment by masak** [comment]
The problem persists for `MVM_JIT_DISABLE` and `MVM_SPESH_OSR_DISABLE`, but goes away for `MVM_SPESH_INLINE_DISABLE`.

**Comment by jnthn** [comment]
Thanks for golfing it. The issue seems to be that one of the inlines that takes place causes `make` to find the wrong `$/`. Of note, in `(make 0 for 0)` it's inlining the `make 0` thunk into the `push-all` of the iterator from `map` that the `for` loop compiles in to. Looking a bit deeper, `MVM_frame_find_lexical_by_name_rel_caller` doesn't seem to care much about inlines, which might be the core issue here. To be continued...

**Comment by jnthn** [comment]
Also, as an aside, this is probably nothing to do with rescalar, and much more to do with the fact that MoarVM HEAD can do inlining of things that it hadn't used to attempt, and is seemingly uncovering an existing problem we'd just not hit before.

**Comment by jnthn** [comment]
Fixed in MoarVM HEAD by https://github.com/MoarVM/MoarVM/compare/0daa14c8743f...db6cc49cafd1

**Comment by AlexDaniel** [comment]
Looks good to me after a bump!

**Comment by masak** [comment]
Looks good here too! :heart:

**Comment by lizmat** [comment]
Test added with https://github.com/perl6/roast/commit/ceb0380ba0
