### ISSUE TITLE
MoarVM inlining regression found in P5quotemeta module (goes away with MVM_SPESH_INLINE_DISABLE=1)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2058]
The module (https://github.com/lizmat/P5quotemeta) is currently failing its tests, and it was OK on 2018.06.

Bisected: (2018-07-09) https://github.com/rakudo/rakudo/commit/c2446b03fa2341c6708277df8667e6356201cc21

Output before and after (large!!!): https://gist.github.com/3126cbaf5abf0f9d50a9bb5fad39806c

Note that the bisect result is similar to https://github.com/rakudo/rakudo/issues/2057, but the issue goes away with `MVM_SPESH_DISABLE=1` as in https://github.com/rakudo/rakudo/issues/2046.

**Comment by jnthn** [comment]
Fix applied in MoarVM HEAD. We've had a longstanding issue with inlining and pseudo-packages like `CALLERS` not interacting so well (or rather, the primitives that pseudo-packages depend on - some CORE.setting usages skip the `PseudoStash` and just use the ops). MoarVM started doing some further kinds of inlining this month, and a problem that could in theory occur became rather more visible. The fix changes the way we handle context traversal so it can be aware of inlining.

**Comment by lizmat** [comment]
Test added with https://github.com/perl6/roast/commit/8995cd75eb
