### ISSUE TITLE
Set.Hash returns badly typed Hash

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2068]
This possibly affects other QuantHashes as well.

Normally, if you type a Hash, you get typecheck errors either with direct assignment, or assigning to `.value` when looping through the pairs:

```
<Zoffix__> m: my Int %h = :42foo; %h<a> = 'meows';
<camelia> rakudo-moar ac2fa03b2: OUTPUT: «Type check failed in assignment to %h; expected Int but got Str ("meows")␤  in block <unit> at <tmp> line 1␤␤»
<Zoffix__> m: my Int %h = :42foo; %h<foo> = 'meows';
<camelia> rakudo-moar ac2fa03b2: OUTPUT: «Type check failed in assignment to %h; expected Int but got Str ("meows")␤  in block <unit> at <tmp> line 1␤␤»
<Zoffix__> m: my Int %h = :42foo; %h.map: { .value = 'meows' if .key eq 'foo' }; dd %h
<camelia> rakudo-moar ac2fa03b2: OUTPUT: «Type check failed in assignment to %h; expected Int but got Str ("meows")␤  in block <unit> at <tmp> line 1␤␤»
```

However, for a Hash given by `.Set.Hash`, only direct assignment typechecks. The `.value` one takes any value it wants:

```
<Zoffix__> m: my Int %h := :42foo.Set.Hash; %h.map: { .value = 'meows' if .key eq 'foo' }; dd %h
<camelia> rakudo-moar ac2fa03b2: OUTPUT: «(my Bool %{Any} = :foo("meows"))␤»
<Zoffix__> m: my Int %h := :42foo.Set.Hash; %h<foo> = 'meows';
<camelia> rakudo-moar ac2fa03b2: OUTPUT: «Type check failed in binding to parameter 'assignval'; expected Bool but got Str ("meows")␤  in block <unit> at <tmp> line 1␤␤»
```

----

Somewhat related: [`Set.hash` and `Set.Hash` return differently-parametarized hashes](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-07-13#l310).

**Comment by lizmat** [comment]
Partially fixed with 7629820461d9a9079

**Comment by lizmat** [comment]
Actually, this seems to have fixed it totally:

    perl6 -e 'my Int %h := :42foo.Set.Hash; %h.map: { .value = "meows" if .key eq "foo" }; dd %h'
    Type check failed in binding; expected Associative[Int] but got Hash[Any,Any] ($(my Any %{Any} = :foo))

**Comment by lizmat** [comment]
Test added with https://github.com/perl6/roast/commit/714be9c2ff
