### ISSUE TITLE
Bad propspec: Enum's :D accepts Enum's :U

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2073]
During 6.d spec review, I found https://github.com/perl6/roast/commit/09c8d3fd7 that specs a fix for a ticket, and IMO this behaviour is undesirable.

In 2016, [RT#129160](https://rt.perl.org/Ticket/Display.html?id=129160) was filed and fixed by adding an `ACCEPTS` candidate that makes a specific value of an enum (a `:D`) to smartmatch true with the name of the enum (a `:U`). Like if `Int ~~ 42` were true.

IMO the only problem in the ticket is an LTA error and the introduced behaviour should be reverted as the now-accepted value doesn't `===` or `eqv` or even `nqp::istype` to the specified "type", which makes the typecheck basically erroneous IMO (again, the same analogy holds. It's like if you wrote `sub ($x where 42) {}` and called it with an` Int` and it was accepted).

```
<Zoffix_> m: enum A ('a', b => 2, c => 2); sub (c \v) { say v === c }(A)
<camelia> rakudo-moar 5cf0afce0: OUTPUT: «False␤»
<Zoffix_> m: enum A ('a', b => 2, c => 2); sub (c \v) { say v eqv c }(A)
<camelia> rakudo-moar 5cf0afce0: OUTPUT: «False␤»
<Zoffix_> m: enum A <b>; sub (b \v) { use nqp; say so nqp::istype(v, b) }(A)
<camelia> rakudo-moar 5cf0afce0: OUTPUT: «False␤»
```

--------------------

.oO(forbid enum's :Ds to be used as type constrants using the same syntax as regular types entirely)

**Comment by zoffixznet** [comment]
Some discussion: http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-07-14#l395

**Comment by JJ** [comment]
Wouldn't this be solved already?
