### ISSUE TITLE
Meaning of `.bool-only`/`.count-only` after receiving IterationEnd ?

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2075]
Was improving some 6.d protests [and swapped range iterator tests to `test-iter-opt` helper routine (committed in a branch ATM)](https://github.com/perl6/roast/commit/ab6ade455b).

It currently tests `.count-only`/`.bool-only` remain at `0`/`False` after receiving `IterationEnd`.

**QUESTION: must such use have meaning or is the Iterator protocol forbidding calling `.pull-one` after receiving `IterationEnd` should be extended to forbid use of all other methods such as `.count-only` and `.bool-only`?**

Fixes to `.count-only`/`.bool-only` we done earlier in the year (https://github.com/rakudo/rakudo/commit/af9812fa73292723871 and https://github.com/rakudo/rakudo/commit/0e228fab8a0b6e91f001f45fa0b9327154e2c752) assume they have to return valid values after `IterationEnd` and IIRC removing that assumption would save some CPU cycles.

Currently, `Range.iterator` does *not* maintain valid values after `IterationEnd`. Does this have any potential for any bugs? (I couldn't come up with anything).

```
<Zoffix_> m: my $i := ^5 .iterator; say [$i.pull-one, $i.count-only] for ^10
<camelia> rakudo-moar ecbf44fb5: OUTPUT: «[0 4]␤[1 3]␤[2 2]␤[3 1]␤[4 0]␤[IterationEnd -1]␤[IterationEnd -2]␤[IterationEnd -3]␤[IterationEnd -4]␤[IterationEnd -5]␤»
```

---------------------------------------

I'm leaning towards making calls to `.count-only`/`.bool-only` after receiving `IterationEnd` a violation of Iterator protocol and will simplify existing rakudo iterators and amend the language spec accordingly if no further discussion on this Issue occurs.

**Comment by zoffixznet** [comment]
Got a couple more new tests that are blocked by current implementation of `test-iter-opt` routine: https://github.com/perl6/roast/commit/09f561314fd100c28c5da76bfb7e72f9b15d7d56

**Comment by lizmat** [comment]
Pulling after an IterationEnd is considered undefined behaviour.  I’m really in two minds on whether this is an issue or not: part of me says that we should be flexible in what we accept: an extra pull-one falls in that category to me.  On the other hand, sometimes keeping whether the Iterator is exhausted, can be a burden on normal operation.

If we compare this to e.g. the behaviour of doing receive on a closed channel, that throws an exception.  So if we want to be consistent with that, we should force iterators to throw if they’re being pulled after they produced IterationEnd.

The way I see it, is that it could be as easy as reblessing the Iterator object with a throwing pull-one / push-all etc.  This could even be part of the Iterator role, come to think of it  :-)

**Comment by zoffixznet** [comment]
> Pulling after an IterationEnd is considered undefined behaviour.

It is, but in this case we're *not* pulling anything; we're calling optimization methods. But I think an argument can be made in terms of pull-one: if the optimization methods were NOT implemented, to find out bool/count on this iterator one would have to pull, which makes the bool/count methods be part of the "don't pull after IterationEnd" restriction of the iterator protocol and the roast test should be amended (any any iterators that were made to behave well after iteration end in https://github.com/rakudo/rakudo/commit/af9812fa732927238715730d6c1e025bd89e74eb#diff-25f13a4730d5d25d5043528b73c8ea78 and https://github.com/rakudo/rakudo/commit/0e228fab8a0b6e91f001f45fa0b9327154e2c752#diff-25f13a4730d5d25d5043528b73c8ea78 be simplified)

> could be as easy as reblessing the Iterator object 

Cool. 

Say, in `^5 .grep(*.is-prime).map(*+1).reverse` you got a chain of like 3 iterators and on each pull from the chain you're performing 3 typechecks for IterationEnd to find when to stop, but would you have to do 3 *additional* type checks for IterationEnd just to rebless iterators that won't get used anymore anyway?

**Comment by FCO** [comment]
Make the Iterator role throw on pull-one after the IterationEnd would blow
stuff like the SeqSplitter module up. I’m not saying that should stop
anything, just remembering that there’s an use of pulling-one after an
IterationEnd
Em sáb, 8 de set de 2018 às 11:11, Zoffix Znet <notifications@github.com>
escreveu:

**Comment by zoffixznet** [comment]
> just remembering that there’s an use of pulling-one after an IterationEnd

That's a violation of the [currently-well-established iterator protocol](https://docs.perl6.org/type/Iterator#IterationEnd), so the only change that would occur were that to be implemented is giving an exception to go with the already-established verbal contract.

**Comment by zoffixznet** [comment]
http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-11#l256

> &lt;Zoffix&gt; lizmat:  is there a benefit to allowing count-only/bool-only after pulling  IterationEnd? I see the downside: the cost of all those extra operations
> 
> &lt;Zoffix&gt; c: HEAD\~100 my $i := ^10 .reverse.iterator; $i.pull-one xx 11; Seq.new($i).skip(-5).elems.say
\<committabl+\> Zoffix, ¦HEAD~100: «-1␤»
> 
> &lt;Zoffix&gt; Well,  that one is almost a bug, but  you could make an argument that making a new Seq from an exhausted  iterator is illegal.
> &lt;Zoffix&gt; And R#2075 can be rephrased: "Exhauster of the iterator must ensure the iterator is not given for consumtion to anything else"
> &lt;Zoffix&gt; And making a new seq, calls to .bool-only/.count-only, all fall under that category
> &lt;Zoffix&gt; And we don't have to do extra work in these methods to keep track of whether the iterator has been exhausted

**Comment by lizmat** [comment]
Hmmm... must admit I haven't thought about it this way: I've always thought of `count-only` and `bool-only` as a sort of "meta" methods, showing the state of the iterator.

But you have a very valid point: if we say that `count-only` and `bool-only` are not to be called after the iterator has been exhausted, than we can simplify all of the `count-only` methods significantly.

**Comment by lizmat** [comment]
At the SPW, I suggested the following idea to Jonathan:

Create a role `ExhaustedIterator` that would have a `die` in **each** of the interface methods.  Add a method "exhausted" to `Iterator` that would a. mix in the `ExhaustedIterator` role into `self` and b. return `IterationEnd`.  This would allow the code of a `pull-one` to have a:

    return self.exhausted;   # instead of `return IterationEnd`

Jonathan however vetoed that train of thought, as each `mixin` like that would cause a global deopt.

The alternative of making `self` `is rw` and then just changing the container to have the `ExhaustedIterator` class in it, won't work either as most of the time the iterator is not a container.  But maybe that's something we *could* look at?
