### ISSUE TITLE
Extensions, shebangs, executable permissions in tools/ and elsewhere

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2077]
Every now and then people try to consistify scripts in this repo (e.g. https://github.com/rakudo/rakudo/compare/0a32c621294fcbc2043983b8c8e5ef29df6b265f...248ee79cfb3f5f6d582a62d1c1db36bb9346688c), but there's has never been a goal to finish it. Maybe with this ticket we'd finally do it.

Basically:
* Every perl 6 script should have `.p6` extension
* If it's meant to be executed, then it should be executable (so `chmod +x` it)
* If it is executable, then it must have a shebang (`#!/usr/bin/env perl6` is a good choice)
* Make sure it has `\n` newlines and not `\r\n` or anything else (`file …` will tell you if it doesn't)

See also #1583 for a more difficult issue.

**Comment by AlexDaniel** [comment]
To anyone who starts working on this: please also grep the whole repo for the filename to make sure that any other file that was using or even just mentioning the renamed script is also modified accordingly.

**Comment by jkramer** [comment]
> even just mentioning the renamed script

There are plenty of comments saying something like "this file was generated by that_script.pl", should the name be changed there too? I assume those will be replaced automatically whenever the generator scripts are run the next time anyway?

**Comment by AlexDaniel** [comment]
Hey @jkramer, thanks for your work! Even though the problem is probably resolved in this repo, can you do the same in https://github.com/perl6/nqp/ ? Or maybe at least move the ticket there so that we can close this one. Thanks ♥

**Comment by AlexDaniel** [comment]
Also, please see https://github.com/rakudo/rakudo/issues/1583 for potential issues caused by the PR.

**Comment by jkramer** [comment]
nqp and moarvm repos are cleaned up too now. @AlexDaniel

**Comment by AlexDaniel** [comment]
Thanks!
