### ISSUE TITLE
exception propagation in await depends on order

### ISSUE THREAD

**Issue by kbucheli** [rakudo/rakudo#2079]
## The Problem
If I await two infinite threads, await immediately forwards the exception of the first thread, but not of the second thread.

## Expected Behavior
It should fail on both exceptions I guess.

## Steps to Reproduce
```
my $promise1 = start {
    react {
        whenever Supply.interval(5) {
            die;
        }
    }
}


my $promise2 = start {
    react {
        whenever Supply.interval(5) {
            say 'foo';
        }
    }
}

await $promise2, $promise1;
```

Output:
```
foo
foo
(forever)
```
but if I change the order of the two promises,
```
await $promise1, $promise2;
```
I get an exeption:
```
foo
An operation first awaited:
  in block  at p6die.p6 line 2

Died with the exception:
    Died
      in block  at p6die.p6 line 4
```
## Environment
* Operating system: Fedora release 28 (Twenty Eight)
* Compiler version (`perl6 -v`): Rakudo version 2018.04 built on MoarVM version 2018.04.1

**Comment by kbucheli** [comment]
Workaround:
```
my @promises = ($promise1, $promise2);

loop {
    last if !@promises;
    react {
        whenever Promise.anyof(@promises) { done }
    }
    my @next;
    for @promises -> $p {
        if ?$p {
            await($p);
        }
        else {
            push @next, $p;
        }
    }
    @promises = @next;
}
```

**Comment by kbucheli** [comment]
Why so complicated?
```
my @promises = ($promise2, $promise1);
react {
    for @promises -> $p {
        whenever $p {} # consume exceptions
    }
}
```
does the same without await.

**Comment by zoffixznet** [comment]
> It should fail on both exceptions I guess.

That's already the case in 6.d language. Currently, you need an explicit `use v6.d.PREVIEW;` pragma to enable the behaviour, but once 6.d is released, the behaviour will be enabled by default on compilers that support it:

```
use v6.d.PREVIEW;
my $promise1 := start react whenever Supply.interval: 5 { die }
my $promise2 := start react whenever Supply.interval: 5 { say 'foo' }
await $promise2, $promise1;

# foo
# An operation first awaited:
#   in block <unit> at ../z.p6 line 4
# 
# Died with the exception:
#     A react block:
#       in code  at ../z.p6 line 2
# 
#     Died because of the exception:
#         Died
#           in block  at ../z.p6 line 2
```

> Why so complicated?

¯\\_(ツ)_/¯ What's an easier way for the complicated part? :)
