### ISSUE TITLE
`is required` change removed useful feature

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2083]
Before a recent change that made `is required` on private attribute a fatal error, it actually was a useful feature, such as ensuring your code intialized private attributes (e.g. by making calculations, based on the instantiations data) inside methods like `BUILD`:

```
Zoffix | c: 2018.06 class ABC { has $!thing is required; }; ABC.new.perl.say;
-- | --
02:09 | committable6 | Zoffix, ¦2018.06: «The attribute '$!thing' is required, but you did not provide a value for it.␤ in submethod BUILDALL at /tmp/f1vpWNHMc8 line 1␤ in block <unit> at /tmp/f1vpWNHMc8 line 1␤␤ «exit code = 1»»
02:09 | Zoffix | c: 2018.06 class ABC { has $!thing is required; submethod BUILD(:$!thing = 42) {} }; ABC.new.perl.say;
02:09 | committable6 | Zoffix, ¦2018.06: «ABC.new␤»
```

We also have a proper user who is negatively affected by the change: http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-17#l109 (ignore my comments in the chat, I misunderstood old behaviour at first).

**Comment by zoffixznet** [comment]
And looks like there are ~9 ecosystem modules that use this feature: https://gist.github.com/Whateverable/c0349a59a74bf4406864c6aa3d89ae04

Including [my own](https://github.com/zoffixznet/perl6-WWW-vlc-Remote/blob/cd64c9aef50ea8445717af8df7e72398d3fb165d/lib/WWW/vlc/Remote.pm6#L6) one from July's Zoffix 😂. I don't know for sure, but I think July's Zoffix reasoned precisely that: that `is required` on privates was a safety check to ensure they're set in `BUILD` methods.

**Comment by lizmat** [comment]
Reverted with dd0cea31a2

**Comment by zoffixznet** [comment]
Just gonna mark it as test needed, so that future devs get blocked by spec for this change, if they decide to make it again.

**Comment by lizmat** [comment]
Test added with https://github.com/perl6/roast/commit/bdc9fd57b3
