### ISSUE TITLE
Make .toggle take matchers, not just Callables

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2088]
So today, [`#perl6` struggled to come up with a usecase for new 6.d method `.toggle`](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-17#l1076). Eventually, someone came up with this:

```
ifconfig | perl6 -e 'say join "\n", lines.toggle: :off, * ~~ /^lo/, * ~~ /^\s+/'
```

It's really gross looking, and were `.toggle` to take matchers (for smartmatching) instead of just `Callable`s, that could be simplified to just:

```
ifconfig | perl6 -e 'say join "\n", lines.toggle: :off, /^lo/, /^\s+/'
```

What's worse, is that currently using the above crashes with cryptic error, because `Regex` *is* `Callable` but you can't just call it with random stuff.

-------------

The matcher functionality is available in many things like, `.grep`, `.first`, and `where` clauses.

**Comment by zoffixznet** [comment]
(before working on this ticket, see any discussion on https://github.com/rakudo/rakudo/issues/2089 )

**Comment by lizmat** [comment]
Not going to work on this until clarity with https://github.com/Raku/problem-solving/issues/450
