### ISSUE TITLE
Range.roll(*) doesn't work with large minimums

### ISSUE THREAD

**Issue by b2gills** [rakudo/rakudo#2090]
## The Problem

``` perl6
my $range = (1 +< 125) .. ( 1 +< 126 -1 ); # IPV6 address range 2000::/3
$range.roll(*);
```
```
Cannot unbox 126 bit wide bigint into native integer
  in block <unit> at <unknown file> line 1
```

This is because the iterators for `.roll(*)` `.roll(42)` `.pick(42)` on Int Ranges have an `int $!min`

It may have been correct if `$!is-int` was for native integer ranges.

## Expected Behavior

The same as

``` perl6
$range.roll xx *
```

## Environment
* Compiler version:  v2018.06.216.g.7.a.7.e.5.e.9

**Comment by tison1** [comment]
@lizmat I try to add tests like 

```perl6
# Range.roll(*)/roll(N)/pick(N) with large number, from R#2090
{
  my $range = (1 +< 125) .. ( 1 +< 126 -1 );
  lives-ok { $range.roll(*) }, 'Range.roll(*) lives on large number';
}
```

but it hangs. which code you confirm for fix?

**Comment by jnthn** [comment]
I believe `lives-ok` will sink the thing passed to it, and `.roll(*)` produces an infinite sequence, so you'll be waiting a long time. :-)

**Comment by jnthn** [comment]
Ah, and `.roll(*).head(10)` or something will limit it to a finite sequence.

**Comment by tison1** [comment]
... close via rakudo/rakudo@b30800c8ec407309a289cf090b54e4cced57e7f9, test on perl6/roast@b30800c8ec407309a289cf090b54e4cced57e7f9

**Comment by lizmat** [comment]
no, `Range.roll(*)` produces an infinite sequence:

    $ 6 'dd (^1).roll(*)'
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0... lazy list)

**Comment by tison1** [comment]
thanks for your replies. as mention above, I add tests on roast. could we remove "testneeded" label and close this ticket?

**Comment by lizmat** [comment]
@tison1 : Thank you!
