### ISSUE TITLE
Allow IO::Socket::Async to listen to a system-defined (unspecified) port

### ISSUE THREAD

**Issue by jmaslak** [rakudo/rakudo#2091]
## The Problem

I want to be able to get a listening IO::Socket::Async network socket, but don't care what port it is on.  I want the system to do that (like would happen if I created a listening socket in C on port 0). 

## Expected Behavior

IO::Socket::Async, when setting up a listening socket, would allow binding to a dynamic port for listening.  It would need to somehow communicate back what port it set up the socket on to user code, either with a syncronous constructor or by send a message of some sort that could be processed by user code.

## Actual Behavior

This is not possible with today's interface.  It's also difficult to just randomly ask IO::Socket::Async to bind to a random port because the error for port in use is thrown asynchronously.

## Environment
* Operating system: All
* Compiler version (`perl6 -v`): 6.c, 2018.06

**Comment by zoffixznet** [comment]
I recall something like this coming in PRs, but looks like it was only for IO::Socket::INET: https://github.com/rakudo/rakudo/commit/bc98e671c91391b2720ef73ab4a3197a5072cfa6#diff-87c072020652d93e159c24f035fe1a02

**Comment by zoffixznet** [comment]
Saw this commit go in today https://github.com/rakudo/rakudo/commit/cb2ea9328a060e37227f322fc44ab15957cb1159

@timo does that implement the proposal in the ticket? Are there any docs/tests for it?

**Comment by timo** [comment]
Tests are done: https://github.com/perl6/roast/commit/9d7241417c36f8039b16874d9fef64904db766be
