### ISSUE TITLE
Too-fiddly error missing op name

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2093]
```

19:11 | AlexDaniel | m: my $a = 42; my $b = 100; $a R[and]= $b; say $a
-- | -- | --
19:11 | camelia | rakudo-moar a847abe52: OUTPUT: «=== SORRY!===   Error while compiling <tmp>␤Cannot reverse the args of because  assignment operator operators are too fiddly␤at <tmp>:1␤------>  my $a = 42; my $b = 100; $a R[and]= ⏏  $b; say $a ␤»
19:11 | AlexDaniel | args of what?


```

**Comment by lizmat** [comment]
Fixed with 2c7692fc7d , not sure how we're going to test that without getting too specific.

**Comment by zoffixznet** [comment]
> not sure how we're going to test that without getting too specific.

Tests can go to rakudo's test suite and there they can be as specific as we want. There three files testing errors already: https://github.com/rakudo/rakudo/blob/master/t/05-messages/03-errors.t

**Comment by lizmat** [comment]
Added test with https://github.com/Raku/roast/commit/98bc514cc9
