### ISSUE TITLE
We should decide on alternative compiler-specific executable names

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2095]
The other day someone pointed out to me that it's weird that you install Rakudo, but execute it with `perl6` binary.

What do you think of renaming it to something else on 6.d release? It'll be a fairly visible occasion for such a core change and will also coincide with the creation of the marketing alias for the language. The `perl6` executable will coexist with the new binary for backcompat reasons until 6.e release (end of 2019), and after that, only the new binary will exist.

I couldn't care less what the other binary name is, as long as it's fairly short.

-----------------------------------------------------------

As the well-known mantra goes, Rakudo is **a** Perl 6 compiler and not **the** Perl 6 compiler and we try to maintain the language separate from any particular implementation.

However, Rakudo does have an unfair advantage to other compilers by claiming `perl6` as its executable, thus inferring it is THE `perl6` and the rest of the implementations have to choose their own names. The problem is also slightly exacerbated from a legal standpoint, as Rakudo's license requires any modified versions to use a different name and installation to not conflict with the original version. While the license provides other options for that clause, Rakudo's claiming `perl6` name to itself makes it more difficult for other implementations to be installable under the same name (presumably they'd use part of Rakudo's code and not write everything from scratch, and thus would be bound by the license), but if they can't claim `perl6` executable name, then we're back at the original issue of rakudo implying it's THE Perl 6 compiler.

The other benefit of renaming the executable is avoiding accidental use of `perl` instead of `perl6` for executing scripts.

**Comment by ijneb** [comment]
I back this change, it makes sense. The main choices that come to mind for me are `rkd`, `rak`, and `kudo`.

**Comment by zoffixznet** [comment]
> No.

👍

**Comment by AlexDaniel** [comment]
FWIW we already have implementation-specific executables, in rakudo that's `perl6-m` and `perl6-j`. In debian if you install `rakudo` it will give you both `perl6` and `perl6-m`. I think there are enough letters for non-rakudo implementations to use.

**Comment by nxadm** [comment]
FWIW, the latest release of rakudo-pkg Linux packages (2018.09-2) creates a link from /opt/rakudo-pkg/bin/perl6 to /opt/rakudo-pkg/bin/rakudo.

**Comment by pmichaud** [comment]
FWIW, when ```perl6-m``` and ```perl6-j``` were introduced I wondered why we didn't go ahead and make the switch to ```rakudo-m``` and ```rakudo-j``` (and ```rakudo```) at that point, just to take the implementation out of the "perl6" executable namespace.  Then allow the OS distros or other groups to provide the link from ```perl6``` to the appropriate executable.

But I agree fully with Jonathan that we need to keep the "perl6" executable link working somehow -- even post-6.d .  This is a pretty standard part of Linux distros these days, where common commands like "vi", "awk", "yacc", "java", etc. actually redirect to specific implementations installed on the system.

If there's a choice to be made between "change the name of the executables" and "keep the 'perl6' command working", I vote for the latter.

My $0.02,

Pm

**Comment by nxadm** [comment]
> If there's a choice to be made between "change the name of the executables" and "keep the 'perl6' command working", I vote for the latter.

What about an symlink? This could satisfy both options.
`ln -s rakudo perl6` seems more logical to me, the logic being that the perl6 binary is provided for backward compatibility. Of course, the other way round (`ln -s rakudo perl6`) will work as well.

**Comment by jnthn** [comment]
Saying "backward compatibility" implies that the `perl6` command is going away, which it's not. Having `perl6` be linked to `rakudo` is probably the appropriate way around, though: that follows the principle that `perl6` points to your currently selected Perl 6 implementation.

**Comment by niner** [comment]
The "symlink a command to the installed implementation" part is nowadays usually handled by https://linux.die.net/man/8/alternatives (package update-alternatives or the like). We don't have to reinvent anything here.

**Comment by nxadm** [comment]
> We don't have to reinvent anything here.

I agree, but not temporarily reinventing the wheel here, will leave us with a rakudo binary and only the hope distributions catch up on the alternative setup for the perl6 link. And what with systems without it like Windows or maybe MacOS?

**Comment by zoffixznet** [comment]
> AlexDaniel reopened this 8 days ago

@AlexDaniel what needs to be done for this Issue still? Perhaps the title should reflect that or a new Issue opened.

**Comment by AlexDaniel** [comment]
@zoffixznet reopened because people really wanted to discuss this. Today @nxadm already provides a `rakudo` symlink https://github.com/nxadm/rakudo-pkg/commit/95c09759bdfb6f384f6d6334db3849994a7c66ae, and we should decide if that's really what we want to do. And if yes, we should do that universally (probably in rakudo repo itself?).

**Comment by cxw42** [comment]
Does the renaming resolve this issue?

**Comment by jonathanstowe** [comment]
There are now `raku`, `rakudo` and `perl6` targets installed by default:

```
[jonathan@coriolanus Ujumla]$ ls -l `which raku`
lrwxrwxrwx. 1 root root 6 Dec 20 09:04 /usr/local/bin/raku -> rakudo
[jonathan@coriolanus Ujumla]$ ls -l `which rakudo`
-rwxr-xr-x. 1 root root 23360 Dec 20 09:04 /usr/local/bin/rakudo
[jonathan@coriolanus Ujumla]$ ls -l `which perl6`
-rwxr-xr-x. 1 root root 23360 Dec 20 09:04 /usr/local/bin/perl6
```

But @jnthn's point about not wanting to break existing code still stands.
