### ISSUE TITLE
RFC: Close all the "roast" RT tickets

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2099]
There's a whole bunch of what I think are pointless tickets in RT, like [RT#124766](https://rt.perl.org/Ticket/Display.html?id=124766#ticket-history), [RT#124766](https://rt.perl.org/Ticket/Display.html?id=124766#ticket-history), [RT#124772](https://rt.perl.org/Ticket/Display.html?id=124772#ticket-history), [RT#124751](https://rt.perl.org/Ticket/Display.html?id=124751#ticket-history), etc.

The tickets have no bodies and their titles just reference a location of a fudge in roast.

I'd like to close all of those tickets because:
1. I can find all the fudges without tickets, by just running `grep -Firn '#?rakudo' .`
2. There are more fudges than these tickets, because some fudges are just your generic "JVM doesn't support Unicode well" type of fudges, so the list of tickets isn't an exhaustive list of fudges
3. When a fudge is resolved, you have to go through the extra steps to close the corresponding ticket. Since RT is not regularly used, personally, for me that'd mean going through the extra hassle of logging into RT 
4. These tickets give useless search results when trying to find other tickets. For example, I was trying to find other tickets for adverb ticket [R#2098](https://github.com/rakudo/rakudo/issues/2098) and I got the search results littered with RT#124754, RT#124673, RT#124672, RT#124553, RT#124996, RT#124995, RT#124991, RT#124989 all of which just reference a line number of some NYI fudge instead of a proper ticket

**Comment by coke** [comment]
Part of the purpose of having those tickets was to force a discussion About whether these were actually intended to be part of the language or just craft or whatever. We can have that discussion on the individual fudges versus the tickets that’s fine I’m OK with you closing them out. I would even be OK with removing any fudged  test from roast -  They can always be pulled from get history and add it back in if it’s decided that with they were actually desirable

**Comment by zoffixznet** [comment]
> having those tickets was to force a discussion

That would work if tickets actually had any content rather than just be a filename/line number for files that keep changing.

> OK with removing any fudged test from roast 

IMO:

* Bug cover fudges remain in roast master
* All the NYI fudges that don't have at least one working implementation get removed from roast and filed as proper tickets that can be discussed/implemented/rejected.

I mentioned it elsewhere: as of 6.d, the language spec will require a POV (Proof-Of-Viability) implementation for a feature to exist in at least one largely-compliant Perl 6 implementation for that feature to be included in a released spec. This way we don't spec untried language features that may conflict with something else or be a real-bad-idea once implemented and tried out.

**Comment by AlexDaniel** [comment]
Is there any way we can have an autogenerated list of fudges? Like something fancier than just grep? IMO if we had it, we'd be able to close all these tickets without even thinking.

**Comment by zoffixznet** [comment]
> Like something fancier than just grep?

What extra information/layout is needed?

**Comment by usev6** [comment]
I've just stumbled above a note referencing this issue and wanted to paste a status update: A while ago I've closed a lot of those "pointless" RT tickets -- cmp. https://github.com/perl6/roast/pull/556.

(For some of those placeholder tickets some information have been added -- if only by putting additional information into the subject or by tagging. I left those tickets open.)

**Comment by AlexDaniel** [comment]
I think we'll be able to do something about this once https://github.com/perl6/problem-solving/issues/49 is resolved.
