### ISSUE TITLE
Inconsistent behaviour with methods called on :Us

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2100]
Just taking a single type object for a spin, we get a:

1. `X::AdHoc` Exception (can't look up attributes)
2. `X::Parameter::InvalidConcreteness` Exception
3. Type object returned

```
<Zoffix_> m: dd DateTime.Instant
<camelia> rakudo-moar a5ab50d64: OUTPUT: «Cannot look up attributes in a DateTime type object␤  in block <unit> at <tmp> line 1␤␤»
<Zoffix_> m: dd DateTime.IO
<camelia> rakudo-moar a5ab50d64: OUTPUT: «Invocant of method 'IO' must be an object instance of type 'Dateish', not a type object of type 'DateTime'.  Did you forget a '.new'?␤  in block <unit> at <tmp> line 1␤␤»
<Zoffix_> m: dd DateTime.DateTime
<camelia> rakudo-moar a5ab50d64: OUTPUT: «DateTime␤»
<Zoffix_> m: dd DateTime.Date
<camelia> rakudo-moar a5ab50d64: OUTPUT: «Date␤»
```

Feels like it's all over the place and should be made more consistent.

The `X::Parameter::InvalidConcreteness` looks like the most attractive option to me, but "cannot look up attributes" is alright too ('d be better if it weren't X::AdHoc). But returning a type object, especially of a different type feels weird ([I'm a hypocrite, I know](https://github.com/rakudo/rakudo/commit/e5df7a7befd5dfd9daf2b6a808f691f959b30178))

----------------

(this came up while reviewing https://github.com/perl6/roast/commit/a7fe6b6f6 6.d propspec, so if we're not consistifying on `X::Parameter::InvalidConcreteness`, those proptests need to be amended)

**Comment by zoffixznet** [comment]
[Another propspec](https://github.com/perl6/roast/commit/0d9a5b143) for `Map:U.Hash` returning a `Hash:U`

**Comment by zoffixznet** [comment]
[Another propspec for Supply:U.skip](https://github.com/perl6/roast/commit/50138a913f) I moved to appendix

**Comment by zoffixznet** [comment]
Well, I think this is very widespread and I'd bet some of the inconsistencies are covered by 6.c spec. And trying to fix them all might lead to other problems, so I just added this to the [List of Inconsistencies](https://temp.perl6.party/inconsistencies.txt) and removed the 6.d-review label.

**Comment by lizmat** [comment]
Closing as the list of inconsistencies has disappeared in the fogs of time, and many of the listed case now produce better error messages.
