### ISSUE TITLE
[RFC] Implement setsockopt and getsockopt support

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2104]
## The Problem
Setting socket options isn't currently possible unless the user's using IO::Socket::INET and a recent version of MoarVM, and requires using NativeCall. This makes for a lot of boilerplate in projects that need to be able to access socket options.

I think `nqp::getsockopt` and `nqp::setsockopt` could be added as ops to help solve this:
```
nqp::getsockopt(int \fd, int \level, int \option --> int) {*} # returns option gotten, if any
nqp::setsockopt(int \fd, int \level, int \option, int \val --> int) {*} # returns option set
```

To get the options, an op like`nqp::getsockopts` may be needed if they differ between systems and can't just be made constants:

```
nqp::getsockopts(--> hash) {*}
```

With these, `option` methods could be added to IO::Socket::INET and IO::Socket::Async (once it supports getting its file descriptors).

```
constant SOL_SOCKET = 0xFFFF;

enum Option (
   SO_DEBUG => 0x0001, 
   # ...
);

# ...

proto method option(Option, Int $?) {*}
multi method option(Option \opt --> Int) {
    my int \ret := nqp::getsockopt(nqp::unbox_i(self.native-descriptor), nqp::unbox_i(SOL_SOCKET), opt);
    nqp::box_i(ret, Int)
}
multi method option(Option \opt, Int \val --> Int) {
    my int \ret := nqp::setsockopt(nqp::unbox_i(self.native-descriptor), nqp::unbox_i(SOL_SOCKET), opt, val);
    nqp::box_i(ret, Int)
}
```

The problem with this is how should errors be handled? i don't think it'd be a good idea to ignore them like the way I've written this does. Better yet, is it a good idea to have in the language at all for v6.d?

**Comment by Kaiepi** [comment]
Since 6.d is getting released so soon, I think it'd be better if this were held off until 6.e.
Does anyone have any comments?

**Comment by zoffixznet** [comment]
> I think it'd be better if this were held off until 6.e.

Unless it violates 6.c spec or has major impact on users, there's no reason to hold off until any language version.

**Comment by Kaiepi** [comment]
Closing this now that a pullreq has been made
