### ISSUE TITLE
DateTime.IO produces forbidden path on Windows

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2105]
During 6.d review, I came across [propspec for `DateTime.IO`](https://github.com/perl6/roast/commit/a7fe6b6f6). 

It feels wrong to spec the current behaviour, as the generated filenames are **always** invalid on Windows due to colons in the time portion and the programmers that do use this feature may be inadvertently writing non-portable programs.

I propose:
1. Removing `DateTime.IO` method entirely (TBH, I'd remove it from `Date` as well, though IIRC during IO Grant that was already discussed and it was decided to leave it in).
2. or barring that,  making it auto-convert the string to valid-ish filename by doing  `.subst: :g, ':', '_'` 

```
C:\Temp>perl6 -e "'2016-10-03T22:23:24Z'.IO.spurt: 'test'"
Failed to open file C:\Temp\2016-10-03T22:23:24Z: Invalid argument
  in block <unit> at -e line 1


C:\Temp>perl6 -e "'2016-10-03T22:23:24Z'.IO.absolute.say"
C:\Temp\2016-10-03T22:23:24Z

C:\Temp>perl6 -v
This is Rakudo version 2018.06-180-g5cf0afc built on MoarVM version 2018.06-220-gd4d8ff4
implementing Perl 6.c.
```

**Comment by stmuk** [comment]
I'd support removing it as the simplest option.

An alternative would be to substitute the colon with U+A789.

**Comment by niner** [comment]
I don't see why every platform should be restricted to what's supported on Windows. Creating a directory named after the current date or date + time is something that's very common for backups. I also have a script doing exactly this to store my meeting notes. This script will only ever run on my Linux machine, so I really don't care if it would work on Windows or not.

**Comment by zoffixznet** [comment]
> I really don't care if it would work on Windows or not.

Doesn't sound like a healthy attitude for a language designed for the next 100 years. Especially since [a quarter of our users](https://docs.google.com/forms/d/e/1FAIpQLSdqrrcxTQWuN1ISAvz3j_XkpCCc2AuQw9uKgAhTivxHBFsweg/viewanalytics) use Perl 6 on Windows.

> why every platform should be restricted

All we're talking about here is requiring the addition of a single character by the programmer:

```perl6
spurt  $date, $backup; # before
spurt ~$date, $backup; # after
```

Which is probably what many users would do anyway, rather than simply assuming a `DateTime` object can be used as a path.

> This script will only ever run on my Linux machine

And if I ask you to share it with me, will you remember to tell me it has a Windows bug in it, or do I get to discover it on my own?

-----------------------------------------------------

So far I see two possibilities: 

1. We document this as a non-portable method and point to those docs any time someone reports *"Failed to open file: Invalid argument"* as a bug
2. We remove a rarely-needed, broken method whose functionality can be replicated with a single character

I don't understand why the first one is preferable.

**Comment by niner** [comment]
On Sonntag, 22. Juli 2018 11:46:18 CEST Zoffix Znet wrote:
> > I really don't care if it would work on Windows or not.
> 
> Doesn't sound like a healthy attitude for a language designed for the next
> 100 years. Especially since [a quarter of our users] use Perl 6 on Windows.

Will we also try to guess the restrictions of platforms that will be in use in 
50 or 100 years from now and restrict ourselves to those allow?
And why do we support PF_UNIX sockets when a quarter of our users can't use 
them?

> > why every platform should be restricted
> 
> All we're talking about here is requiring the addition of a single character
> by the programmer:

We are talking about code that works and does exactly what the author 
intended.

> Which is probably what many users would do anyway, rather than simply
> assuming a `DateTime` object can be used as a path.
> > This script will only ever run on my Linux machine
> 
> And if I ask you to share it with me, will you remember to tell me it has a
> Windows bug in it, or do I get to discover it on my own?

It's unlikely that I will share my one line script with anyone soon. It's too 
trivial. I also think it's unlikely that the backup script that uses btrfs 
snapshots will run on Windows. Those are just examples of everyday 
trivialities.

Also with the addition of that character you suggested, the script does not 
become any more portable. So what problem would we really solve here?

> So far I see two possibilities:
> 
> 1. We document this as a non-portable method and point to those docs any
> time someone reports *"Failed to open file: Invalid argument"* as a bug 2.
> We remove a rarely-needed, broken method whose functionality can be
> replicated with a single character
> 
> I don't understand why the first one is preferable.

There's a third one: improve the error message, so Windows users become 
educated about the restrictions of their platform and get an idea on how to 
work around them. There's no reason we should be satisfied with telling the 
user "Invalid argument".

**Comment by zoffixznet** [comment]
> So what problem would we really solve here?

The addition of the character is a conscious thought by the programmer that considers what sort of data they're strigifying, while automatic conversion to an invalid path can be accidental.

The problem we solve is reducing the amount of bugs the users of our language create.

**Comment by ugexe** [comment]
ISO 8601 allows spaces and colons to be omitted, so `yyyymmddTHHMMSS` or `yyyy-mm-dd THHMMSS` would be standards compliant and safe for a typical file system.

**Comment by lizmat** [comment]
Couldn't this be done by providing an `.IO` method to `DateTime` and an `.DateTime` coercer to `IO::Path` ?

**Comment by ugexe** [comment]
I'm not sure a coercer is needed as much as the following should work:
`my @dates = map { DateTime.new($_.IO.basename) } $*CWD.dir`
which implies the date format used can round trip. A coercer implies some things I'm not sure make sense ( primarily working on anything path consisting of more than 1 path part ).

**Comment by zoffixznet** [comment]
I [moved `.IO` tests to appendix, out of main spec,](https://github.com/perl6/roast/commit/9062bb39fc) for now, until there's an agreement on how it should behave
