### ISSUE TITLE
Capture in `sub MAIN` doesn't work for named args

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2106]
I expected the capture to take all possible arguments, however, it appears to behave as a positional slurpy only and rejects any named args requiring additional use of `*%`:

```
<Zoffix_> m: @*ARGS = '-z'; sub MAIN(|) {}
<camelia> rakudo-moar cb2ea9328: OUTPUT: «Usage:␤  <tmp> <Any> ␤»
<Zoffix_> m: @*ARGS = '42'; sub MAIN(|, *%) {}
<camelia> rakudo-moar cb2ea9328: ( no output )
<Zoffix_> m: @*ARGS = '42'; sub MAIN(|) {}
<camelia> rakudo-moar cb2ea9328: ( no output )
```

**Comment by mustafaaydn** [comment]
seems to be fixed since 2019: https://gist.github.com/Whateverable/b89b76f4a308c7f62c1b4567a0f32abc
