### ISSUE TITLE
Inconsistency in .grab/.kxxv/.pick in Mix vs MixHash

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2109]
With `.grab`, on one you get an Exception thrown but on the other you get a Failure.

```
<Zoffix_> m: dd Mix.new(<a b c>).grab
<camelia> rakudo-moar cb2ea9328: OUTPUT: «Cannot call 'grab' on an immutable 'Mix'␤  in block <unit> at <tmp> line 1␤␤»
<Zoffix_> m: dd MixHash.new(<a b c>).grab
<camelia> rakudo-moar cb2ea9328: OUTPUT: «Failure.new(exception => X::AdHoc.new(payload => ".grab is not supported on a MixHash"), backtrace => Backtrace.new)␤»
```

With `.kxxv`/`.pick` both types fail:

```
<Zoffix_> m: dd MixHash.new(<a b c>).kxxv
<camelia> rakudo-moar cb2ea9328: OUTPUT: «Failure.new(exception => X::AdHoc.new(payload => ".kxxv is not supported on a MixHash"), backtrace => Backtrace.new)␤»
<Zoffix_> m: dd Mix.new(<a b c>).kxxv
<camelia> rakudo-moar cb2ea9328: OUTPUT: «Failure.new(exception => X::AdHoc.new(payload => ".kxxv is not supported on a Mix"), backtrace => Backtrace.new)␤»
```

**Comment by zoffixznet** [comment]
FWIW: There's a spectest speccing `.grab` throwing: https://github.com/perl6/roast/commit/8120b6b48721a6babd5331f6009dea3f04d8dfcc

**Comment by lizmat** [comment]
FWIW, the thought behind this was that `.grab` is a mutator, so it will **never** work on an immutable thing.  Whereas `.grab` on a `MixHash` was merely disallowed because we couldn't decide on the semantics.  `kxxv` **can** have a meaning on `Mix`, as it is not a mutator.  But again, we couldn't decide on the semantics.

So I think it *is* consistent.

**Comment by zoffixznet** [comment]
> But again, we couldn't decide on the semantics

FWIW, some other things along those lines currently throw X::NYI. There are some APPENDICES (i.e. optional) spectests for these in https://github.com/perl6/roast/tree/master/APPENDICES/A02-some-day-maybe

**Comment by JJ** [comment]
Not clear what's the status of this now...

**Comment by JJ** [comment]
Anyone picking up on this?
