### ISSUE TITLE
`please 'use experimental :pack'` even if code does exactly that

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2111]
Originally reported by @thundergnat++, confirmed by @dogbert17++, golfed by @ugexe++:

```
$ perl6 -e 'package Foo { use experimental :pack; sub go() is export { "".encode.unpack("*") }; }; import Foo; go()'
Use of the 'unpack' method is experimental; please 'use experimental :pack'
  in sub go at -e line 1
  in block <unit> at -e line 1
```

Original report in a gist: https://gist.github.com/thundergnat/057aef48c0612905aa88b7553cc3323c

Was working fine on 2018.06:

> \<AlexDaniel\> `c: 2018.06,HEAD package Foo { use experimental :pack; sub go() is export { "".encode.unpack("*") }; }; import Foo; go()`
> \<committable6\> AlexDaniel, `¦2018.06: «» ¦HEAD(cb2ea93): «Use of the 'unpack' method is experimental; please 'use experimental :pack'␤  in sub go at /tmp/DtKIwcN2IU line 1␤  in block <unit> at /tmp/DtKIwcN2IU line 1␤␤ «exit code = 1»»`

**⚠⚠⚠ Bisected: (2018-07-18) https://github.com/rakudo/rakudo/commit/a847abe5236a6d3b63ae08ba116ea19c3738c291**

I assigned some people who should know more about it, but anyone please feel free to work on this.

**Comment by lizmat** [comment]
It appears it's the `import` checks for whether `unpack` is allowed or not.  So at least a workaround is the move the `use experimental :pack` to the scope of the `import`:

    package Foo { sub go() is export { "".encode.unpack("*") }; }; use experimental :pack; import Foo; go()

Continuing ways of fixing this.

**Comment by jnthn** [comment]
Fixed the `getlexcaller` regression that caused this in https://github.com/MoarVM/MoarVM/commit/ba906c4297

**Comment by lizmat** [comment]
Test added with https://github.com/perl6/roast/commit/3129a4a708 , can be closed afaiac

**Comment by AlexDaniel** [comment]
@lizmat why a *roast* test for an experimental feature?

**Comment by lizmat** [comment]
FWIW, I just looked to "use experimental :pack' in t/spec and added the test there.  It was not the only one.  So, if this needs to be moved, many more will need to be moved.
