### ISSUE TITLE
Revisit bug compatibility unfix for returning Proxy

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2113]
Recent changes in rakudo required PRs like [this](https://github.com/supernovus/exemel/pull/55) to several modules in the ecosystem. Arguably in these cases (when returning Proxy without `is rw`) the code is wrong, but many modules were doing that. Even though I submitted PRs to affected modules as per https://github.com/rakudo/rakudo/issues/2047, it is desired to have backward compatibility with existing code before we get the release going.

```
<jnthn> Ah, I still should put in that Proxy compat thing, though that's easy
```

**Comment by jnthn** [comment]
Done in https://github.com/rakudo/rakudo/commit/8607f68238. Testing of the affected modules would be welcome. Given this isn't a desired behavior, no test needed, though we do need a plan for when we remove the bug fix, and probably should create an issue for that.

**Comment by AlexDaniel** [comment]
> though we do need a plan for when we remove the bug fix, and probably should create an issue for that.

I'm repurposing this ticket instead of creating a new one.

**Comment by zoffixznet** [comment]
@AlexDaniel what still needs to be done for this ticket?

**Comment by zoffixznet** [comment]
> though we do need a plan for when we remove the bug fix, and probably should create an issue for that.

@jnthn Ping. Is now a good time to do that?

**Comment by jnthn** [comment]
@zoffixznet Yes, though we need to decide if we're just going to remove the workaround, or if we're going to do it by language version and leave 6.c broken in this regard forever.

**Comment by zoffixznet** [comment]
👍 on just removing it

**Comment by AlexDaniel** [comment]
👍 for doing it by language version and not removing it. If I understand correctly, it was never made to issue a warning or anything like that. Meaning that those who update to Rakudo 2018.11 will have their v6.c code broken. Yes, broken because they had a bug, but that's LTA on our side and we can do much better.

**Comment by zoffixznet** [comment]
>  Yes, broken because they had a bug, but that's LTA on our side and we can do much better

It'd still break the moment that code is switched to do 6.d, which is now the default language of the compiler. So you're targeting the users who not only relied on a bug, but plan to keep that code locked in 6.c land, never getting 6.d benefits. 

I'm all for smooth user experience, but infesting the compiler with versioning conditionals to the point of keeping bugs around is IMO LTA. Break it now and make it all part of 6.d fixups.

I don't know what's jnthn's plan for versioning it, since it's a spesh plugin that gets executed at runtime, innit? So that'd be blocked by [R#1289](https://github.com/rakudo/rakudo/issues/1289)

**Comment by jnthn** [comment]
> It'd still break the moment that code is switched to do 6.d, which is now the default language of the compiler. So you're targeting the users who not only relied on a bug, but plan to keep that code locked in 6.c land, never getting 6.d benefits.

Well, the point is to let people upgrade bit by bit, but of course to do that they have to have written `use v6.c` in their code, and I'm not convinced a majority will have done such a thing yet.

> I don't know what's jnthn's plan for versioning it, since it's a spesh plugin that gets executed at runtime, innit?

Have two versions of the spesh plugin, one with the 6.c semantics, one with the 6.d semantics. Compile into the appropriate one.

**Comment by AlexDaniel** [comment]
According to greppable, [228 modules have `use v6.c` in their code](https://gist.github.com/1fc6dccc32b992ad4db96635bb7d97c8). That's a lot.

**Comment by jnthn** [comment]
> I'm all for smooth user experience, but infesting the compiler with versioning conditionals to the point of keeping bugs around is IMO LTA. Break it now and make it all part of 6.d fixups.

Well yes, this was an outright bug, which is why I just fixed it and tried to have us ship that in the first place.

**Comment by ugexe** [comment]
> According to greppable, 228 modules have use v6.c in their code. That's a lot.

...and they are almost entirely tests, so pretty much moot.

**Comment by AlexDaniel** [comment]
> ...and they are almost entirely tests, so pretty much moot.

Only 29 out of 228 have `use v6.c` exclusively in `.t` files.

**Comment by zoffixznet** [comment]
I'm swapping the labels from `6.d` to `blocker` so that 6.d spec release is clear for this issue, but we still should take care of it for the next compiler release.

**Comment by AlexDaniel** [comment]
I feel like removing the label and leaving bug compatibility in the next release. Thing is, in July there were PRs submitted to affected modules, but since then there could be *new* modules and code out there relying on the bug. IMO it has to go through a deprecation cycle, and that deprecation cycle does not necessarily have to be attached to a language version. If someone can do that before the release that'd be great, but otherwise we can just leave the bug compat in the next release.

**Comment by jnthn** [comment]
Now, code doing `use v6.c` will get the original buggy behavior, and 6.d code will get the corrected behavior.

We'll have other 6.c -> 6.d issues too, so this might as well go into the set of them rather than having its own distinct deprecation cycle. Plus it means "code broke in 2018.11? try adding `use v6.c`" will cover this issue too.
