### ISSUE TITLE
Misleading error in tr/// when including a # character

### ISSUE THREAD

**Issue by jmaslak** [rakudo/rakudo#2118]
## The Problem

Misleading error message for # in a tr/TR.

The error message indicates "Please backslash # for literal char or put whitespace in front for comment".

However, adding a backslash just generates the same error message.

## Expected Behavior

I'm not entirely sure what the proper behavior of a backslash in a TR should be.  When working on #2117, I was trying to generate errors based on unrecognized backslash sequences to test the PR, but was not able to trigger that condition.

My expectations (which may be wrong) would be that either the backslash in front of # should work and quiet this error or the error message should be changed.

## Actual Behavior

Without backslash:
```
[1] red:rakudo$ perl6 -e '1 ~~ TR/#//'
===SORRY!=== Error while compiling -e
Please backslash # for literal char or put whitespace in front for comment
at -e:1
------> 1 ~~ TR/#⏏//
```

With backslash:
```
[1] red:rakudo$ perl6 -e '1 ~~ TR/\#//'
===SORRY!=== Error while compiling -e
Please backslash # for literal char or put whitespace in front for comment
at -e:1
------> 1 ~~ TR/\#⏏//
```

## Steps to Reproduce

See above.

## Environment
* Operating system: Ubuntu 18.04
* Compiler version (`perl6 -v`): HEAD & 18.06

**Comment by zoffixznet** [comment]
Related ticket: https://github.com/rakudo/rakudo/issues/1324

**Comment by dogbert17** [comment]
There error message for the backslash case is gone as of https://github.com/rakudo/rakudo/commit/85107ec0c709f4fd1c762bde1b50bfd93e5c51d7
