### ISSUE TITLE
Segfault while indexing with infinite Seq

### ISSUE THREAD

**Issue by taboege** [rakudo/rakudo#2120]
## The Problem
The following code segfaults using rakudo-moar HEAD via camelia [^1]:
```
(^10)[2.polymod($_ xx *).map($_ ** *) »%» *] with 1
```
Interestingly, removing the `map` (which should produce constant 1) or inlining the `with 1` leads to a timeout [^2,3].

On my personal machine with Rakudo-moar 2018.06, it just hangs in all three cases.

## Expected Behavior
It should hang as the `polymod(1 xx *)` produces an infinite list.

## Actual Behavior
SIGSEGV, but only when the seemingly useless `map` and `with 1` are left intact.

## Environment
* Works as expected with `Rakudo version 2018.06 built on MoarVM version 2018.06`,
* Segfaults with `rakudo-moar c47e3681c`.

## References
[^1] http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-23#l486
[^2] http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-23#l504
[^3] http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-23#l506

**Comment by AlexDaniel** [comment]
Bisected: (2018-07-09) https://github.com/rakudo/rakudo/commit/c2446b03fa2341c6708277df8667e6356201cc21

NQP changes in the bump: https://github.com/perl6/nqp/compare/2018.06-27-gcec76ff79...2018.06-36-g39f1057
Moar changes in the bump: https://github.com/MoarVM/MoarVM/compare/2018.06-103-gaf455397f...2018.06-141-gcae4731

**Comment by zoffixznet** [comment]
Golf of the scoping issue: `{1}() + * with 1`
