### ISSUE TITLE
Failure in t/04-nativecall/02-simple-args.t with clang

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#2124]
```
not ok 11 - passed uint16 0xFFFE
# Failed test 'passed uint16 0xFFFE'
# at t/04-nativecall/02-simple-args.t line 72
# expected: '11'
#      got: '0'
```
`This is Rakudo version 2018.06-243-g85495890d built on MoarVM version 2018.06-313-gebf0464e0`
`clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)` on Kubuntu 18.04
`clang version 6.0.1 (tags/RELEASE_601/final)` on Arch linux
Passes on both if I configure MoarVM with `--optimize=0`. There are already some fudges for the failing test https://github.com/rakudo/rakudo/blob/master/t/04-nativecall/02-simple-args.t#L51-L73.

**Comment by AlexDaniel** [comment]
Looking at it again, given that the issue existed previously I can just fudge these tests for all platforms equally…

**Comment by usev6** [comment]
This seems to be the same problem that is analyzed in depth in https://github.com/rakudo/rakudo/issues/1619.

I'll close this issue, so that relevant info can be kept in one place. (Please reopen if you don't agree with closing here.)
