### ISSUE TITLE
Behavior of match occurrence adverbs: :nth(*) and :nth(*-1)

### ISSUE THREAD

**Issue by lucasbuchala** [rakudo/rakudo#2131]
Currently, `:nth(*-1)` returns the **next to last** match occurrence, while `:nth(*)` returns the last one. Is it possible to make `:nth(*)` mean the same thing as `:nth(1..*)` (return **all** occurrences) and make `:nth(*-1)` return the **last** occurrence?

Current behavior:

```
say 'abc' ~~ m:nth(*)/./;    #=> ｢c｣
say 'abc' ~~ m:nth(*-1)/./;  #=> ｢b｣
say 'abc' ~~ m:nth(*-2)/./;  #=> ｢a｣
```

Desired behavior:

```
say 'abc' ~~ m:nth(*)/./;    #=> (｢a｣ ｢b｣ ｢c｣)
say 'abc' ~~ m:nth(*-1)/./;  #=> ｢c｣
say 'abc' ~~ m:nth(*-2)/./;  #=> ｢b｣
```

**Comment by zoffixznet** [comment]
Related item from my [stash of language inconsistencies](https://temp.perl6.party/inconsistencies.txt):

> .match options take differring args and fail differently:
> https://irclog.perlgeek.de/perl6/2018-03-08#i_15897822
> https://irclog.perlgeek.de/perl6/2018-05-22#i_16194294

**Comment by lizmat** [comment]
I'm slightly apprehensive fixing this for 6.c.  Perhaps for 6.d ?

**Comment by zoffixznet** [comment]
> Perhaps for 6.d ?

I think that'd require implementing different behaviour *in methods,* and we don't have the capacity to do that in 6.d: https://github.com/rakudo/rakudo/issues/1289

**Comment by zoffixznet** [comment]
> I'm slightly apprehensive fixing this for 6.c. Perhaps for 6.d ?

Found the behaviour is actually [part of 6.c spec](https://github.com/perl6/roast/blob/2fa2ad50df40c446d2967b056cdfb7dfee7a7b1a/S05-modifier/counted.t#L218-L220), so it'd *have* to go behind a version pragma, and is blocked by https://github.com/rakudo/rakudo/issues/1289
