### ISSUE TITLE
Can't .gist/.Str/.perl Distribution::Resource:U

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2143]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

```
<Zoffix_> m: say Distribution::Resource.^mro
<camelia> rakudo-moar b7379a804: OUTPUT: «Cannot look up attributes in a Distribution::Resource type object␤  in block <unit> at <tmp> line 1␤␤»
```

Fix would simply involve [changing the methods to `multi`](https://github.com/rakudo/rakudo/blob/72c8cf68c/src/core/Distribution.pm6#L184-L192) and type-constraining them on `:D` invocant. e.g.:

```perl6
    multi method perl(::?CLASS:D: |c) {
        self.IO.perl(|c)
    }
```

**Comment by ribbon-otter** [comment]
Where would an appropriate place to write the tests be? Searching for either "Distribution" or "%?RESOURCES" on Perl6/Roast doesn't seem to give any hints for tests should be placed.

**Comment by zoffixznet** [comment]
> Distribution::Resource.Str

It doesn't error. That's a stringification *warning* that usually is displayed when you stringify classes ain't meant to be stringified.
