### ISSUE TITLE
several pod std config options not handled in Grammar.nqp or Pod.nqp

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2148]
## The Problem

The following pod standard configuration options described in the original S26 specification are not handled in rakudo/src/Perl6/*.nqp files:

+ :numbered
+ :formatted
+ :like
+ :margin

**Comment by lizmat** [comment]
superseded by RakuDoc v2.0, so closing

**Comment by tbrowder** [comment]
Excellent, RakuAST is cool!
