### ISSUE TITLE
Non-consistent behavior of mixins

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2149]
## The Problem

This is taken from an example in [the docs](https://docs.perl6.org/routine/but)

    my $forty-two = 42 but 'forty two'; 
    say $forty-two; 
    say $forty-two.^name; 
    say $forty-two.Int; 

returns:

    # OUTPUT: «forty two␤Int+{<anon|1>}␤forty two␤»

Check out the first and last answer; the last one is specially surprising. But let's invert the definition:

    my $forty-two = 'forty two' but 42; 
    say $forty-two; 
    say $forty-two.^name; 
    say $forty-two.Int

returning:

    # OUTPUT: «forty two␤Str+{<anon|1>}␤42␤»

Now the surprising thing is the first answer, which is exactly the same that the one above.

## Expected Behavior

I don't really know if this is according to spec or not; but I guess that, at least, `.Int` returning a string might be a bug. I would expect also either documentation of that "precedence" of Str over Int, and also documentation if that's the case for other classes.

## Steps to Reproduce

Just run the script using evalable

## Environment

`evalable` was used. [Commitable returns the same behavior across all versions](https://gist.github.com/Whateverable/1e5b49a5bc2884e9d1681e8c6ab7d0ce)

**Comment by lizmat** [comment]
That's because `say` coerces the given thing to a `Str`, which you have mixed in with `but 'forty-two`.  Or am I missing something?

**Comment by zoffixznet** [comment]
> at least, .Int returning a string might 

It doesn't returns a string. It returns `self`, which is then gisted according to your mixin.

**Comment by JJ** [comment]
OK, I see. Thanks!
