### ISSUE TITLE
Help with or additional documentation required for run / slurp

### ISSUE THREAD

**Issue by pprocacci** [rakudo/rakudo#2153]
## The Problem
The run routine allows one to set the :out named parameter in order to capture the commands' stdout.
However, in doing so, perl 6 can fail while `slurp`ing this data with 'Malformed UTF-8'.

The documentation doesn't make clear how to handle this.  I'd suspect setting the named parameter :bin would allow to slurp this data into a Buf, however the decode method for Buf too gives 'Malformed UTF-8'.

There's got to be a valid and documented way to slurp a commands STDOUT into a usable Buf, while catching such errors and optionally ignoring them.

Perhaps it is in the documentation but not at all clear.  In either case help is much appreciated.

Note: the below example uses google.com which fails as described, however yahoo.com for example works without error.

## Steps to Reproduce
my $proc = run('curl', 'https://www.google.com', :out);
my $b = $proc.out.slurp(:close);

OR

my $b = $proc.out.slurp(:bin, :close).decode;

## Environment
* Tested both on Ubuntu and FreeBSD
* Compiler version (`perl6 -v`): Rakuda Star version 2018.04.1 built on MoarVM version 2018.04.1

**Comment by zoffixznet** [comment]
FWIW using `:enc<utf8-c8>` will not explode on invalid bytes: https://docs.perl6.org/language/unicode#index-entry-UTF8-C8

**Comment by pprocacci** [comment]
Thanks for pointing this out!  After re-reading the documentation for both slurp and Buf, I can confirm this is mentioned in both places.  I suppose in my haste to figure out why the simple example I provided wasn't working, this was simply overlooked.

Thanks Again.

**Comment by pprocacci** [comment]
Sorry to beat a dead horse, but I still think there's a problem; specifically with slurp.

The following simply does not work:
##################
my $proc = run('curl', 'https://www.google.com', :out);
my $b = $proc.out.slurp(enc => 'utf8-c8', :close);
##################

It yields 'Malformed UTF-8'.

The slurp documentation says:  "Accepts :bin and :enc optional named parameters, with the same meaning as open()."

If I modify this slightly to instead read as follows:
###############################
my $proc = run('curl', 'https://www.google.com', :out);
my $b = $proc.out.slurp(:bin, :close).decode('utf8-c8');
###############################

Then it works fine.  Since the former doesn't work, yet the documentation points to :enc as being a valid parameter, yet it doesn't modify the behavior in a way I would expect, then this smells like a bug.

What are your thoughts?

**Comment by zoffixznet** [comment]
> The slurp documentation says: "Accepts :bin and :enc optional named parameters, with the same meaning as open()."

That's the documentation for `&slurp` (i.e. the subroutine). But you're using the [`.slurp` method on `IO::Pipe` object](https://docs.perl6.org/type/IO::Pipe.html#(IO::Handle)_method_slurp) (which inherits it from `IO::Handle` object). it doesn't take an encoding parameter.

You can either call `.encoding` method on the pipe, or just give `:enc` parameter to `run` itself:

```
$ perl6 -e 'run("curl", :enc<utf8-c8>, :out, "https://www.google.com").out.slurp(:close).say'
```

**Comment by zoffixznet** [comment]
Opened a docs ticket for `run` to make it clearer it takes extra args: https://github.com/perl6/doc/issues/2233

**Comment by pprocacci** [comment]
Thanks again.  You are naturally correct in all that you stated.
I would have never have guessed that enc would be applicable to the run subroutine as a search on the page for 'enc' yields nothing.

Opening the additional ticket regard this is much appreciated.

**Comment by zoffixznet** [comment]
If you spot any more docs that are confusing, just open a new ticket in the docs repo: https://github.com/perl6/doc/issues/new

It's hard to write good docs when you know all the details already, so we rely on new users to point out to us where the docs are lacking :)

**Comment by pprocacci** [comment]
Zoffix, I wanted to point out that the example you provided returns a truncated response.  It appears to stop reading at 1408 characters.

> perl6 -e 'run("curl", :enc<utf8-c8>, :out, "https://www.google.com").out.slurp(:close).say'

If I massage it to the following instead, I receive the entire response.

> perl6 -e 'run("curl", :out, "-s", "https://www.google.com").out.slurp(:bin, :close).decode("utf8-c8").say;'

Before I go claiming bug, I presume there's a good reason for this?

**Comment by lizmat** [comment]
That would appear to be a bug to me.

**Comment by zoffixznet** [comment]
Looks to be a legit bug. I opened a ticket for it: https://github.com/rakudo/rakudo/issues/2158
