### ISSUE TITLE
Unicode 'Block' property mapping seems to be wrong for many codepoints

### ISSUE THREAD

**Issue by alexghacker** [rakudo/rakudo#2154]
## The Problem
The 'Block' Unicode property mapping seems to not match the normative sources ( e.g. https://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt )

## Expected Behavior
All codepoints would return the block that they are included in.

## Actual Behavior
For some codepoints, such as reserved codepoints, the 'Block' property is returned as 'No_Block'.  For other codepoints the value returned is a different block.

## Steps to Reproduce
```perl6
# note that the UCD promises:
# #  All block ranges start with a value where (cp MOD 16) = 0,
# #  and end with a value where (cp MOD 16) = 15. In other words,
# #  the last hexadecimal digit of the start of range is ...0
# #  and the last hexadecimal digit of the end of range is ...F.
# #  This constraint on block ranges guarantees that allocations
# #  are done in terms of whole columns, and that code chart display
# #  never involves splitting columns in the charts.

# note also that the UCD says:
# 0370..03FF; Greek and Coptic
# 2F800..2FA1F; CJK Compatibility Ideographs Supplement

# note finally:
# these are just samples - I know that there are many others

my @samples-and-context = (
    0x377, # correct
    0x378, # reserved wrongly showing 'No_Block'
    0x379, # reserved wrongly showing 'No_Block'
    0x37a, # correct
    0x2f9dc, # wrongly showing a different block, 'CJK Unified Ideographs'
    0x2f9dd, # wrongly showing a different block, 'CJK Unified Ideographs Extension B'
    0x2f9de, # wrongly showing a different block, 'CJK Unified Ideographs'
);

for @samples-and-context -> $codepoint {
    my $glyph = chr( $codepoint );

    say "codepoint U+$codepoint.base(16) shows to be in block : $glyph.uniprop('Block')";
}
```

## Environment
* Operating system: Gentoo Linux
* Compiler version (`perl6 -v`):

This is Rakudo Star version 2018.04.1 built on MoarVM version 2018.04.1
implementing Perl 6.c.

**Comment by AlexDaniel** [comment]
Ping @samcv.

**Comment by alexghacker** [comment]
I just noticed that part of what I'm seeing is the automatic decomposition of glyphs for NFG, e.g. U+2F9DC decomposes into U+8DF0, which is in the 'CJK Unified Ideographs' block.

**Comment by alexghacker** [comment]
And I just now noticed a comment from @samcv directing me to open my original issue (just the reserved codepoints) in another project, so closing this one.

**Comment by AlexDaniel** [comment]
@alexghacker Both are OK. In fact, there are cases when having two tickets is fine. In this repo there's a strong standard requiring tests to close any ticket, and the reported issue is not exactly backend-specific and needs roast tests. I won't reopen this as I hope @samcv will add tests, but just letting you know that you did nothing wrong :)
