### ISSUE TITLE
Recent Perf regression for Data::Selector module

### ISSUE THREAD

**Issue by jdv** [rakudo/rakudo#2155]
## The Problem

The runtime of https://github.com/jdv/p6-data-selector/blob/master/t/03-apply_tree.t has recently gotten
~ 20% slower.  See http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-28#l1039.  IT was never fast but when I read of jnthn's recent perf work I thought I'd see if it helped this module.  That's how I noticed it.

## Expected Behavior

To run as fast or faster than under recent releases.

## Actual Behavior

It runs slower than under recent releases.

## Steps to Reproduce

Run the test file under different recent versions of rakudo.

**Comment by AlexDaniel** [comment]
Bisected: (2018-07-14) https://github.com/rakudo/rakudo/commit/5cf0afce02c50677c58d958563d844d0a5098e7d
(before 2.691408, after 3.27876625)

**Comment by AlexDaniel** [comment]
On HEAD (`229fa2c`) it is now 2.8018723 which is better but still not as fast.

**Comment by AlexDaniel** [comment]
> \<+AlexDaniel> dogbert2: so on HEAD it runs in 104.1% of the time it used to
> \<+AlexDaniel> not a big issue IMO
> \<+AlexDaniel> but I slapped blocker label on it so that it gets more eyes on it before the release
> \<dogbert2> AlexDaniel: I have code which has gone from 1m to 1m50s
> \<+AlexDaniel> dogbert2: ok now we're talking

http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-08-13#l390

**Comment by AlexDaniel** [comment]
`blocker` label removed with similar reasoning as in https://github.com/rakudo/rakudo/issues/2210#issuecomment-412691219. I don't know if it is related though, but I hope we'll figure it out as soon as possible (though likely after the release).

**Comment by AlexDaniel** [comment]
It's much [closer now](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-04#l188), but still not as fast. Around ≈2.74s on HEAD (post 2018.08) and like ≈2.70s on 2018.06, so just a tiny bit slower.
