### ISSUE TITLE
Wrong math in Int + Int

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2157]
Result should be 993097239240350**2**

```
m: dd 9930972392403501 + 1;
rakudo-moar 38de1e512: OUTPUT: «9930972392403501␤»
```
~~Bisects to https://github.com/rakudo/rakudo/commit/b61b3c7a7f0c6848f4698aaed23da21ca29115bc~~

The problem is present on both 64-bit and 32-bit systems

**Comment by zoffixznet** [comment]
Strangely, the problem doesn't occur if I rip out the nqp guts used and use them directly:

```
<Zoffix_> m: use nqp; dd nqp::box_i(nqp::atpos(nqp::radix(10, '9930972392403501', 0, 2), 0), Int)
    + nqp::box_i(nqp::atpos(nqp::radix(10, '1', 0, 2), 0), Int)
<camelia> rakudo-moar 42595c27d: OUTPUT: «9930972392403502␤»
```

**Comment by zoffixznet** [comment]
Looks like bisection isn't quite the full story. In pure NQP, same problem exists:

```
nqp: say(9930972392403501 + 1);
nqp-moarvm: OUTPUT: «9930972392403501␤» 
```

**Comment by MasterDuke17** [comment]
Seems like it's related to https://github.com/perl6/nqp/issues/363. My WIP NQP branch that switches to using int behavior by default doesn't have this problem.
