### ISSUE TITLE
"Bad address" when trying to spurt a lot of data into a handle

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2159]
Was trying to generate a large HTML file, but my program crashed with "bad address" error.

No idea what that means. Is this a bug or a limitation?

```
$ perl6 -e '"foo.html".IO.spurt: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" x 56500000'
Failed to write bytes to filehandle: Bad address
  in block <unit> at -e line 1

$ perl6 -v
This is Rakudo version 2018.06-146-g1b3dd35 built on MoarVM version 2018.06-141-gcae4731
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
OK. It took me killing my box trying the same program in Perl 5, before I realized this is 2.6B characters, which is probably like 10GB of data in memory or whatever.

Closing, as I believe we discussed this in the past that super large strings isn't something we currently support.

**Comment by lizmat** [comment]
I think we need the `Cat` object for that :-)
