### ISSUE TITLE
untracked files  interfere with merge from master

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2164]
When I tried to update from master, I got this error from git:

error: The following untracked working tree files would be overwritten by merge:
	tools/build/makeMAGIC_INC_DEC.p6
	tools/build/makeNATIVE_ARRAY.p6
	tools/build/makeNATIVE_SHAPED_ARRAY.p6
	tools/build/makeSLICE.p6

The Makefile target distclean should remove those files unless they are intended to be version controlled, or may .gitignore them.

**Comment by zoffixznet** [comment]
These files *are* tracked on master: https://github.com/rakudo/rakudo/tree/master/tools/build

There was [a recent rename](https://github.com/rakudo/rakudo/commit/906bec8c9d0debe1f6ffea1d99925724188b40d0) of them tho.

**Comment by tbrowder** [comment]
Thanks, closing.
