### ISSUE TITLE
Explosions due to missing deconts in a bunch of Set ops

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2167]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

This golfed example shows an explosion when we build a new set from a list of containerized Pairs:
```
m: dd 1 (-) ($ = :42foo,)
rakudo-moar 0ac427612: OUTPUT: «P6opaque: no such attribute '$!value' on type Pair in a Scalar when trying to get a value␤  in block <unit> at <tmp>
```

By running `$ ./perl6 --ll-exception -e 'dd 1 (-) ($ = :42foo,)'` we can see the explosion is from
https://github.com/rakudo/rakudo/blob/0ac42761217725647f7fd72acc9cc5b5a371ad07/src/core/Rakudo/QuantHash.pm6#L441 ~~Simply adding `nqp::decont` in `nqp::getattr($pulled,Pair,'$!value'),` and changing it to `nqp::getattr(nqp::decont($pulled),Pair,'$!value'),` will fix that particular issue.~~

However, looking at that file, there's a whole bunch of similar places with no deconts. We need to figure out which code examples cause each of the missing decont blow up and use them as tests in [roast](https://github.com/perl6/roast/) to cover all the cases.

So this is an easy issue, but it has a lot of work, so I'm marking it both easy and medium difficulty.

**Comment by lizmat** [comment]
I think the `nqp::decont` should be done when the value is pulled from the iterator.

**Comment by zoffixznet** [comment]
(linking to commit with the fix https://github.com/rakudo/rakudo/commit/fa73bb48d5 )

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/bb8de71453
