### ISSUE TITLE
Regex.ACCEPTS: NDF does not set $/

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2176]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

There [is a fudge in the propspec](https://github.com/perl6/roast/commit/b8bae2967) for this bug, but it doesn't look like it's been filed as a bug, only [for the match success itself](https://rt.perl.org/Ticket/Display.html?id=130458), which has been resolved.

The bug:
When you match with NFD, the `$/` variable is not set (the fudge itself tests `$/.orig` is of type NFD)

```
<Zoffix_> m: say so "7\x[308]".NFD ~~ /^ \d+ $/; dd $/.orig
<camelia> rakudo-moar c4bb1b19d: OUTPUT: «True␤Nil␤»
```

I suspect the fix involves just sticking the following into the [`.ACCEPTS: NDF`  candidate](https://github.com/rakudo/rakudo/blob/c4bb1b19d/src/core/Regex.pm6#L37) before calling the `Str` candidate:

```
$/ := nqp::getlexcaller('$/');
```

**Comment by dogbert17** [comment]
Test added with https://github.com/perl6/roast/commit/bbb233b73cc5a5d3a17987b837f6d19aee348b26
