### ISSUE TITLE
Captures, WHICH and Math::PascalTriangle

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2179]
Module [Math::PascalTriangle](https://modules.perl6.org/dist/Math::PascalTriangle) is failing its tests.

Bisected: (2017-03-18) https://github.com/rakudo/rakudo/commit/4605d5219ec12b2765877ee39f6dd1bcd0eb6892

Snippet: https://gist.github.com/AlexDaniel/df49e362c26527362bdeb4af1183d995

Output before and after:
```
¦2015.12,4605d5219^: «1␤1␤1␤2␤6␤» ¦4605d52,2018.06: «1␤1␤1␤2␤2␤»
```

Basically there's an issue with `my %cache{Capture:D};`.

Although it's an old regression, it feels like something we want to unbreak.

**Comment by zoffixznet** [comment]
That's just a bug in the snippet. It keeps re-using the same container over and over, so it gets the same cache lookup for the key. 

If you want to lookup by values of the variables instead of the variables themselves, you need to decont. Before the bisected-to-commit Capture's .WHICH could not differentiate between conted and unconted values (which lead to other bugs).

```
class Math::PascalTriangle {
	my %cache{Capture:D};
	my %LRU{Capture:D} = Bag.new;

	proto method get(Int:D() :$line! where * >= 0, Int:D() :$col! where * >= 0) {{*}}

	multi method get(:$line!, :$col! where * == 0) {1}

	multi method get(:$line!, :$col! where $line == *) {1}

	multi method get(:$line!, :$col! where $line > *) {
		%LRU{\($line, $col)}++;
		if %LRU.elems > 9999 {
			my \min = %LRU.sort(*.value)>>.key.first;
			%LRU{min}:delete;
			%cache{min}:delete;
		}

		return %cache{\($line<>, $col<>)} if %cache{\($line, $col)}:exists;
		%cache{\($line<>, $col<>)} = $.get(:line($line - 1), :$col) + $.get(:line($line - 1), :col($col - 1))
	}
}

say Math::PascalTriangle.get(:line(0):col(0));
say Math::PascalTriangle.get(:line(1):col(0));
say Math::PascalTriangle.get(:line(1):col(1));
say Math::PascalTriangle.get(:line(2):col(1));
say Math::PascalTriangle.get(:line(4):col(2));

# 1
# 1
# 1
# 2
# 6
```
