### ISSUE TITLE
Map.WHICH fails to discern between containerized and non-containerized contents

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2180]
These two maps are different, yet their `.WHICH`es match:

```perl6
    my $a = 42;
    my $m  := Map.new: (a => $a);
    my $m2 := Map.new: (a => 42);
    say $m === $m2; # True
```

```
$ ./perl6 -v
This is Rakudo version 2018.06-315-g6ad50d794 built on MoarVM version 2018.06-333-g977f3e1fc
implementing Perl 6.c.
```

`Set.WHICH` looks to be using the same sha-the-contents mechanism, yes isn't affected by the bug, so I presume the fix can be lifted from there.

**Comment by lizmat** [comment]
These two `Map`s are *not* different.  `Map`s created this way, decont the values when they create the `Map`, otherwise the `Map` would not be a value type.

    use nqp;
    dd nqp::iscont(Map.new( (a => my $ = 42) )<a>);    # 0

Therefor I would say this is not a bug.
