### ISSUE TITLE
Missing detail in spec for IO::Path

### ISSUE THREAD

**Issue by lembark** [rakudo/rakudo#2183]
## The Problem

dirname(3) and in File::Basename specifies that there will be no trailing directory separator on the value returned by dirname(). IO::Path's dirname lacks that detail.

The annoyance is that without it anyone wanting to examine the path has to stringify and regex off the possibly-trailing dir-sep each time the method is used. This prevents nicer things like $foo.IO, instead requiring

  my $foo = $path.dirname;
  $foo ~~ s{ $dir-sep * $ }{};
  $foo.IO.

## Expected Behavior

Always remove all trailing dir-sep char's from the return of $io.dirname

## Actual Behavior

Currently undefined.

This is hopefully only a doc-bug in failing to specify the actual return.

## Steps to Reproduce

Read the IO::Path doc's looking for the return value of dirname() specified to not have any trailing directory separator ($*SPEC.dir-sep) char's.

## Environment
* Operating system: Any/All
* Compiler version (`perl6 -v`):  6.c

**Comment by zoffixznet** [comment]
Thanks for the report.

It doesn't include the trailing separator, per spec. Added that information to the docs in
https://github.com/perl6/doc/commit/ceaa1bdf2b2f6534028e7dd63c6b5bd96fe54091

**Comment by lembark** [comment]
Thank you.
