### ISSUE TITLE
Look into implementing faster f.p. stringification algo

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2187]
We currently use (on MoarVM) [Grisu3 algo with sprintf fallback](https://github.com/MoarVM/MoarVM/commit/067c0594103a025472c39ae7f8670e47211b874b#diff-c8107b8dd67f693029f7075f86d79d17)

A new, allegedly better, algo came out recently that should be faster than Grisu3, yet offering the same benefits
- https://www.reddit.com/r/ProgrammingLanguages/comments/930pch/ryu_a_new_algorithm_to_quickly_convert_floating/
- https://pldi18.sigplan.org/event/pldi-2018-papers-ry-fast-float-to-string-conversion

We need to see if we can swap out to that new algo.

**Comment by lizmat** [comment]
Closing this here, please make a new issue in the MoarVM repo if still applicable

**Comment by timo** [comment]
as of this commit we are using ryu in moarvm: https://github.com/MoarVM/MoarVM/commit/8cc7fbdf7e44082142af33598588b64fbd01183a

**Comment by MasterDuke17** [comment]
MoarVM currently uses Ryu, but DragonBox is the new state-of-the-art algorithm/implementation.
