### ISSUE TITLE
MoarVM exception with constants, so, try, and cglobal

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2191]
## The Problem
In Net::LibIDN2, I had some code that was intended to determine if the version of the library installed included LibIDN compatibility functions:

```perl6
constant LIB = 'idn2';
constant IDN2_IDN_COMPAT = so try cglobal(LIB, 'idn2_to_ascii_8z', Pointer);
```

## Expected Behavior
`IDN2_IDN_COMPAT` should be `True` if the library has the function, otherwise it should be `False`.

## Actual Behavior
On systems where the version of LibIDN2 doesn't include the LibIDN compatibility functions (such as Ubuntu), it throws this exception:

```
Missing serialize REPR function for REPR VMException (BOOTException)
```

## Steps to Reproduce

Install the v0.04 release of Net::LibIDN2 from [here](https://github.com/Kaiepi/p6-Net-LibIDN2/releases/tag/v0.0.4) and run `$ PERL6LIB=lib prove -e perl6 t/`. I haven't been able to find a way to replicate the issue with simpler code.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.3 GENERIC.MP#4 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.06-348-g36d37cbc8 built on MoarVM version 2018.05-469-gecff5b47c
implementing Perl 6.c.

**Comment by Kaiepi** [comment]
I've already avoided the bug by checking the version of LibIDN2 instead of creating the constant. The compatibility functions aren't available before v2.0.0

**Comment by ab5tract** [comment]
Using this script:

```
use NativeCall;

constant LIB = 'idn2';
constant IDN2_IDN_COMPAT = so try cglobal(LIB, 'idn2_to_ascii_8z', Pointer);

dd IDN2_IDN_COMPAT;
```

I get the anticipated results:

```
> ./rakudo-m -Ilib issues/r2191.raku
Bool::False

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-96-ge3ad75a69.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```

**Comment by ab5tract** [comment]
Also: I miss you @Kaiepi
