### ISSUE TITLE
.list/.hash can give any Positional/Associative, but core code has stricter assumptions

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2199]
This is probably more of a docs Issue:

Based on previous discussions in [R#1344](https://github.com/rakudo/rakudo/issues/1344), it was stated that `.list` can return any `Positional`. However, a bunch of core code assumes it'll get a something a lot more like a `List` from that method.

A `Positional` doesn't require implementation of `.kv`, for example, so if I return this class from `.list`, I get an infiniloop hang because it keeps trying to coerce itself to something more like a `List`:
```
$ perl6 -e 'class :: does Positional { method list { self } }.new.kv.perl.say'
^C
```

Should the description of `.list` be more like *return any **core** `Positional` type*?

**Comment by lizmat** [comment]
Probably :-)
