### ISSUE TITLE
Native arrays aren't Lists?

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2200]
I'm reminded how sometimes we offer using native arrays as an optimization strategy, however, it turns out native arrays aren't lists:

```
$ ./perl6 -e 'my @a; -> List { say "all ok" }(@a)'
all ok

$ ./perl6 -e 'my int @a; -> List { say "all ok" }(@a)'
Type check failed in binding to parameter '<anon>'; expected List but got array[int] (array[int].new())
  in block <unit> at -e line 1

$ ./perl6 -v
This is Rakudo version 2018.06-404-g0b3fc07 built on MoarVM version 2018.06-399-g4fc267b
implementing Perl 6.c.
```

And I guess the question is: should they (somehow) be?

**Comment by zoffixznet** [comment]
The [Liskov thing](https://en.wikipedia.org/wiki/Liskov_substitution_principle) innit? An `Array` can be used anywhere a `List` can be, but not the other way around. `List` currently doesn't even have a `.splice` for example, but if it were the other way around, it'd need to have it and have it just throw.

**Comment by jnthn** [comment]
This is correct; `my int @a;` gets you an `array`, not an `Array`.

An `Array` adds extra functionality to `List` (you can mutate it), but in common they have being a potentially lazy, and they share a common representation of a `P6opaque` with reified and todo attributes.

By contrast, `array` is a `VMArray`, and as such does not support laziness, cannot be mixed in to, etc.

We select `array` when the type constraint that's specified the point of declaration is a native one.

**Comment by niner** [comment]
The upshot is: don't require a List, when all you need is a Positional or Iterable.
