### ISSUE TITLE
CompUnit::Util module failing after "use a spesh plugin for return value type checks" commit

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2201]
[CompUnit::Util](https://github.com/LLFourn/p6-CompUnit-Util) fails test file `t/02-re-export.t` with this error:

```
===SORRY!===
Type check failed for return value; expected Callable:D but got Nil (Nil)
```

Bisected: (2018-08-08) https://github.com/rakudo/rakudo/commit/fe5c8d497323b17b54defab6c0898bae0cf100c6

Output before and after: https://gist.github.com/49782b6992f2c234d15db8c2e8b21130

The commit message didn't indicate any changed behavior, so I'm assuming a regression. That said, I don't have a golf and don't know what's going on there.

**Comment by AlexDaniel** [comment]
Similar error message in DOM::Tiny:
```
Type check failed for return value; expected DOM::Tiny::HTML::DocumentNode:D but got Nil (Nil)
  in method select-one at /home/cpan/.zef/store/DOM-Tiny-0.4.1.tar.gz/DOM-Tiny-0.4.1/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 436
  in method at at /home/cpan/.zef/store/DOM-Tiny-0.4.1.tar.gz/DOM-Tiny-0.4.1/lib/DOM/Tiny.pm6 (DOM::Tiny) line 921
  in block <unit> at t/052-dom-sibling-combinator.t line 29
```
I did not bisect it, but I can bet it will bisect to the same commit :)

**Comment by jnthn** [comment]
Already building a provisional fix, but golfs to `sub foo(--> Callable:D) is rw { my $x is default(Nil) = Nil; $x }; foo`.

**Comment by jnthn** [comment]
Test in a5023b53c3.
