### ISSUE TITLE
too many levels of import: Missing serialize REPR function for REPR CStr (NativeCall::CStr)

### ISSUE THREAD

**Issue by kbucheli** [rakudo/rakudo#2209]
## The Problem
NativeCall seams to have a compliation problem when on the third level of import (in a script which imports a module importing a module which imports a module using NativeCall).

## Expected Behavior
```
$ perl6 -c direct.pl6 
Syntax OK
$ 
```
## Actual Behavior
```
$ perl6 -c indirect.pl6 
===SORRY!===
Missing serialize REPR function for REPR CStr (NativeCall::CStr)
$
```
## Steps to Reproduce
Bar.pm6
```
unit module Bar;

use Log::Syslog::Native;
our $log is export = Log::Syslog::Native.new(ident => 'bar');
```
Foo.pm6
```
unit module Foo;

use Bar;
```
indirect.pl6
```
#!/usr/bin/env perl6

use lib '.';
use Foo;
```
direct.pl
```
#!/usr/bin/env perl6

use lib '.';
use Bar;
```

The source files and the low level exception stacktrace are in the attached tarball 
[missing_serialize_repr.tar.gz](https://github.com/rakudo/rakudo/files/2283551/missing_serialize_repr.tar.gz).

## Environment
* Operating system: 
Linux
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.

**Comment by lizmat** [comment]
This appears fixed.  Not sure how to test so closing
