### ISSUE TITLE
Blob.subbuf regression since 2018.06

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#2215]
## Expected Behavior

The code runs without any errors which it did with 2018.06

## Actual Behavior

    dogbert@dogbert-VirtualBox ~/repos/p6-HTTP-Parser $ perl6 -v
    This is Rakudo version 2018.06-434-g66aa689 built on MoarVM version 2018.06-425-g0daf99b
    implementing Perl 6.c.
    
    dogbert@dogbert-VirtualBox ~/repos/p6-HTTP-Parser $ perl6 -e 'my $blob = blob8.new([1, 2, 3]); $blob.subbuf(0, Any)'
    Cannot resolve caller subbuf(Blob[uint8]: Int, Any); none of these signatures match:
        (Blob:D: Range:D $fromto, *%_)
        (Blob:D: Int:D $From, *%_)
        (Blob:D: &From, *%_)
        (Blob:D: Int:D $From, Int:D $Length, *%_)
        (Blob:D: &From, Int:D $Length, *%_)
      in block <unit> at -e line 1

Bisectable points to commit https://github.com/rakudo/rakudo/commit/cd43c4f1535d99b1c55c53bd262924a069ca3d8f

The change breaks the HTTP::Parser module

**Comment by lizmat** [comment]
FWIW, I'm not sure what the semantics for `subbuf(0,Any)` are supposed to be?  It is **not** documented to being a valid combination?

**Comment by jnthn** [comment]
> nd if it returned Nil, it should not wind up inside the if

But the `Nil` is being assigned to a variable, which sets it to its default, which is `Any`.

**Comment by lizmat** [comment]
aaaaahhhhh   yup

**Comment by lizmat** [comment]
Submitted a PR: https://github.com/tokuhirom/p6-HTTP-Parser/pull/8

Meanwhile, I'll make sure that `subbuf(1,x) and `substr(1,x)` give better error messages

**Comment by jnthn** [comment]
And to add: that makes the condition in question useless. A neater way would be:

```
with $req.first(* > 127, :k) {
    $req = $req.subbuf(0, $_);
}
```

Though the question is whether we want to go out of our way to preserve a dubious behavior for confused code, or just decide the PR is sufficient.

**Comment by AlexDaniel** [comment]
@lizmat tests?

**Comment by lizmat** [comment]
Tests for what?  `HTTP::Parser`?

**Comment by AlexDaniel** [comment]
@lizmat for subbuf, so that the right behavior is cast in stone and we won't change it by accident.

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/3b30b38330
