### ISSUE TITLE
method or submethod DESTROY?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2219]
## The Problem

[`IO::CatHandle` declares `DESTROY` as a `method`](https://github.com/rakudo/rakudo/blob/49363d690ef4a85e2fe27e4ab465b3b7901ccaf4/src/core/IO/CatHandle.pm6#L307)

## Expected Behavior

Shouldn't it be a `submethod`? In fact, it's subclassing [`IO::Handle`](https://github.com/rakudo/rakudo/blob/master/src/core/IO/Handle.pm6#L781-L799) which declares it as a submethod. You could argue that that way it's inherited, but if that was the intended behavior we could as well have declared DESTROY in the first element in the hierarchy a `method` to be inherited all the way down. It probably does not have a big impact in performance.

**Comment by zoffixznet** [comment]
Speaking from the person who wrote the code, it's just a typo and should've been a `submethod`.

However, I `IO::Handle`'s `DESTROY` does some Serious Business™ with regard to unmarking stuff for closing on `END`, so possibly it should become a `method`. (I tried to produce some negative effects from it being a `submethod` but did not come up with anything fatal)

**Comment by lizmat** [comment]
Feels to me if you're subclassing `IO::Handle` you better know what you're doing, so closing
