### ISSUE TITLE
Mu.emit seems broken

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#2223]
## The Problem

```
$ perl6 -e 'Mu.emit'
Type check failed in binding to parameter 'value'; expected Any but got Mu (Mu)
  in block <unit> at -e line 1
```

## Expected

```
$ perl6 -e 'Any.emit'
emit without supply or react
  in block <unit> at -e line 1
```

## Environment
* Operating system: OSX
* Compiler version (`perl6 -v`):
```
This is Rakudo version 2018.06-448-g34468f11d built on MoarVM version 2018.06-428-g727767006
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
The actual problem is with `emit Mu`.

**Comment by jnthn** [comment]
It probably just needs the type constraint loosening. I note that `take Mu` does work (though looking at the source, somewhat by accident).

**Comment by lizmat** [comment]
`Supply.emit` appears to suffer from the same issue.

**Comment by lizmat** [comment]
Fixed the `Supplier.emit` case with db3768e356, added tests with https://github.com/perl6/roast/commit/20de0d4773 and  https://github.com/perl6/roast/commit/1c939c2a58
