### ISSUE TITLE
conditional import bug

### ISSUE THREAD

**Issue by lichtkind** [rakudo/rakudo#2229]
## Expected Behavior
Math::Matrix exports a range of matrix ops as +, *, - by overloading the infix ops when operands are matrices. Once I:

use Math::Matrix :MM;

## Actual Behavior

the rest will not be imported.

## Steps to Reproduce
/Users/lichtkind/code/perl/six/module/Perl6-Math-Matrix $ perl6 -e 'use Math::Matrix; my $m = Math::Matrix.new([[1,2],[3,4]]); say  $m * $m'
  1   4 
  9  16 
/Users/lichtkind/code/perl/six/module/Perl6-Math-Matrix $ perl6 -e 'use Math::Matrix :MM; my $m = Math::Matrix.new([[1,2],[3,4]]); say  $m * $m'
16

. Here numeric context is applied and then multiplied as if the matrix * never happened.

## Environment
current perl 6

**Comment by ugexe** [comment]
"current perl 6" doesn't tell anyone who is looking at this issue in the future what version of rakudo you were experiencing this on. I would suggest putting the output of `perl6 -v` in future issues.

**Comment by jnthn** [comment]
I'm looking at the module and don't see any mandatory exports (that is, marked `is export(:MANDATORY)`), only ones not marked with any tags, which is `:DEFAULT`. Asking for a specific tag doesn't include the set of defaults.

**Comment by lichtkind** [comment]
sorry my bad than i misread the docs, which would look like it  was the same, sorry for inconvenience
