### ISSUE TITLE
t/spec/S32-num/complex.t errata file is failing

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2235]
Basically:
```
…
ok 474 - exp(3.0 * log(1i))
ok 475 - same as wrapped as sub
Unable to call postcircumfix $bt[ (Any) ] with a type object
Indexing requires a defined object
  in sub is_approx at /home/alex/git/rakudo/lib/Test.pm6 (Test) line 278
  in block <unit> at t/spec/S32-num/complex.t line 122

# Looks like you planned 512 tests, but ran 475
```

I bisected the change to (2018-08-09) https://github.com/rakudo/rakudo/commit/a41c37c89f45327c91c024b72ed1d59693cfa832

NQP bump brought in these changes: https://github.com/perl6/nqp/compare/2018.06-147-g39bfe08...2018.06-154-ge1929a4
Moar bump brought in these changes: https://github.com/MoarVM/MoarVM/compare/2018.06-391-g91d2878...2018.06-395-g0c5f6e5

Output before and after: https://gist.github.com/3015f5a6cbfedc8845f22a41b5ee6eda

I'm not sure what's going on there. No golf yet.

**Comment by AlexDaniel** [comment]
By the way, same error can be seen in `t/spec/S32-num/rat.rakudo.moar` (note that it is on `6.c-errata` branch in roast).

**Comment by AlexDaniel** [comment]
Yeah, it looks OK now. That said, `testneeded` because roast master doesn't catch it.

**Comment by lizmat** [comment]
closing as untestable
