### ISSUE TITLE
Failure stored in Array not throwing if element never accessed (not DWIMmy?)

### ISSUE THREAD

**Issue by jstuder-gh** [rakudo/rakudo#2239]
## The Problem

When storing a ```Failure``` in an ```Array```, the ```Failure``` is not thrown if the user does not attempt to retrieve the value at index 0.

```perl6
my @a = Failure.new;
say @a[1];

# OUTPUT:   (Any)
# EXPECTED: Failed
```
If you attempt to retrieve the value at index 0, this code produces the expected results.

This is also appearing in int arrays, producing unexpected results.

```perl6
# Assigning lazy sequence to int arr will return Failure
my int @geo = 2, 4, 8 ... *;
say @geo[2..10]

# OUTPUT: [0 0 0 0 0 0 0 0 0]  
# EXPECTED: Failed
```

## Expected Behavior?

Should the ```Failure``` be thrown when attempting to assign to an ```Array```? Or only on attempted access (if not handled)?

Ideally, the ```Failure``` explosion would be deferred until unhandled access but it would explode on attempting to access any element. My first thought was to have ```STORE``` return a ```Scalar``` or something other than ```Array```,  but since you cannot bind non-```Positional``` to a ```@``` variable, I'm not sure how that would be implemented.

I understand we may want to return ```Failure```s in an Array. But what about when we want to indicate the ```Failure``` of ```Array``` creation as a whole? Should a lone ```Failure``` throw?

```perl6
my @a = (Failure.new,); # List contains (at least one) Failure. Shouldn't Explode.
my @b =  Failure.new;   # Lone Failure (indicating failure to create Array?). Should Explode?
```

## Environment
* Operating system: 
GNU/Linux (Fedora 27)

* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.06-481-g5d1cec5a4 built on MoarVM version 2018.06-438-gde85c9b35
implementing Perl 6.c.

**Comment by jnthn** [comment]
A native `array` can't possibly store a `Failure`, and so that operation should throw the `Failure` immediately. So that one is certainly wrong, and wants fixing.

For `Array`, we consistently treat a single non-`Iterable` item being assigned into an array as if it were a 1-element list, and I'm not convinced that a discontinuity there for `Failure` would be a net good. Especially because it'd create another requirement any custom collection types would have to implement to behave like the built-in ones.

I'd also argue that it's somewhat unusual to assign an element to an `Array` and never read it. Such an unthrown `Failure` will warn when it is eventually GC'd, provided the program lives long enough and the array is freed up. (That won't happen in this small example program, mind.)

**Comment by lizmat** [comment]
FWIW, adding:

  multi method STORE(Array:D: Failure:D \failure) { failure.throw }

makes this throw and spectests clean.

**Comment by lizmat** [comment]
Also, FWIW:

$ 6 'my %h = Failure.new'
Failed

so there is a bit of a precedent here.

**Comment by jstuder-gh** [comment]
Hmm, I guess you're right @jnthn, that the user is likely to check the value stored in the ```Array``` and I agree that a special case in assignment for a ```Failure``` is not a good idea.

Still I get the feeling that this is could be a potential pain point for users who are returning a ```Failure``` with the intention of conveying that the entire assignment process has failed and not realizing that they are just storing a ```Failure``` in a one element ```Array```. Maybe that is something that should be documented as a potential pitfall/trap? Not sure what the best approach to educating users about that detail would be.

@lizmat, that's an interesting observation about the ```Hash``` assignment. It looks like ```STORE``` expects that the
 the argument have a ```iterator``` method (which Failure does it seems, it just [blows up](https://github.com/rakudo/rakudo/blob/fd6f512be718c5e9ea6f86a5c198a7b79951db4a/src/core/Hash.pm6#L86) when you ```pull-one```). Is this a bug?  Should the parameter be set explicitly to ```Iterable```?

I've submitted a PR that address the native arrays not throwing when encountering the lazy Seq Failure (located [here](https://github.com/rakudo/rakudo/pull/2240))

**Comment by zoffixznet** [comment]
> so there is a bit of a precedent here.

I think it fails in the process of reporting the odd items to hash error. If you give it proper even items, it consumes them just fine:

    perl6 -e 'my %h{Any} = Failure.new, Failure.new'

(side note: the user has the option of using the lexical `use fatal` pragma that blows up failures even in these cases)

    $ perl6 -e 'use fatal; my %h{Any} = Failure.new, Failure.new'
    Failed
