### ISSUE TITLE
Feature requset: coalesce role BUILD/TWEAK/DESTROY

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2241]
## The Problem

Currently any of `BUILD/TWEAK/DESTROY` submethods declared in a role are ignored if consuming class defines any of them. For this reason if a role needs to perform any action at the object construction/destruction stages it has to define a method and ask the consumer to call it in a respective submethod. This adds to the boilerplate and generally reduces flexibility of the code.

## Expected Behavior

    role R1 {
        submethod TWEAK { say "R1::TWEAK" }
    }
    role R2 {
        submethod TWEAK {say "R2::TWEAK" }
    }
    class Foo does R1 does R2 {
        submethod TWEAK { say "Foo::TWEAK" }
    }
    Foo.new

The output would be:

    R1::TWEAK
    R2::TWEAK
    Foo::TWEAK 

Since there is uncertainty about the order of calling class/role submethods it could be postulated that by default it's resembles MRO behavior (parents are first, children then following) in a way that a role could be taken as a kind of a parent to the class. Though in special cases a trait `is after` (or `call after`) could be used:

    role R1 {
        submethod TWEAK { say "R1::TWEAK" }
    }
    role R2 {
        submethod TWEAK is after {say "R2::TWEAK" }
    }
    class Foo does R1 does R2 {
        submethod TWEAK { say "Foo::TWEAK" }
    }
    Foo.new

would produce the output:

    R1::TWEAK
    Foo::TWEAK 
    R2::TWEAK

**Comment by AlexDaniel** [comment]
For anyone reading: please change the label to `6.d` if you know how to make it happen in v6.d.

**Comment by lizmat** [comment]
I think the order in which the roles are consumed, should define the order in which TWEAKs are called.

**Comment by lizmat** [comment]
BTW, the same issue exists for BUILD

**Comment by vrurg** [comment]
Note, please, that I mention `BUILD/TWEAK/DESTROY` in the beginning. 

And, as I remember,  order of parent classes define their order in MRO.

**Comment by lizmat** [comment]
Ah, yes, sorry, was not quite awake yet

**Comment by vrurg** [comment]
Closed with #3348
