### ISSUE TITLE
POD data blocks / POD variables not yet implemented

### ISSUE THREAD

**Issue by remorse** [rakudo/rakudo#2242]
Using Rakudo Star 2018.06.

According to the docs, I should be able to create and access "pod variables" using the `$=...` syntax. The only one that seems to be available is `$=finish` (which, as mentioned in another ticket, isn't really documented).

I'm not sure if you need more detail?

I did look through the source code, and in `Actions.nqp`, on line 2878, there is an elsif block regarding `=` twigils that seems relevant.

**Comment by tbrowder** [comment]
This should be fine, thanks!

This is also in the old rt perl as RT#116419 [open]: https://rt.perl.org/Ticket/Display.html?id=116419 [POD] Implement $=data for Pod data blocks

**Comment by lizmat** [comment]
`$=pod` got implemented afaik, and will be deprecated in 6.e in favour of `$=rakudoc`.  So closing
