### ISSUE TITLE
pod_configuration is made too early

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2251]
## The Problem

Per S26, some pod objects need configuration information prior to making the final object. Currently the pod_configuration is made as soon as it is assembled which is too early in some instances.

## Expected Behavior

Make the pod_configuration during the block making process after all block data are available.

## Proposed solution

1. Modify src/Perl6/Actions.nqp to remove ‘method pod_configuration’.

2. In src/Perl6/Pod.nqp, modify make_config to take extra args as needed.

3. In src/Perl6/Pod.nqp, in all the block-making functions, add a call to the
make_config function as appropriate but before the final block-making
step.

**Comment by lizmat** [comment]
Closing in light of rakudoc
