### ISSUE TITLE
Spec question: .Array/.List on shaped arrays

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2256]
Spotted https://github.com/perl6/roast/commit/1c61263ca in the 6.d prop spec and just want someone to verify that calling `.Array` or `.List` on shaped arrays does indeed meant to flatten the shapes into a single list as opposed to returning a list of lists (like what .perl looks like):

```
<Zoffix_> m: my @a[2;2]; dd @a
<camelia> rakudo-moar 070780e04: OUTPUT: «Array element = Array.new(:shape(2, 2), [Any, Any], [Any, Any])␤»
<Zoffix_> m: my @a[2;2]; dd @a.List
<camelia> rakudo-moar 070780e04: OUTPUT: «(Any, Any, Any, Any)␤»
```

(N.B. `.Array` call currently crashes; reported in [R#2257](https://github.com/rakudo/rakudo/issues/2257))

**Comment by lizmat** [comment]
That is my understanding that `.List` and `.Array` should flatten the shapes

**Comment by zoffixznet** [comment]
Thanks.
