### ISSUE TITLE
.Array on shaped array crashes

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2257]
[RT#130513](https://rt.perl.org/Public/Bug/Display.html?id=130513) reported this problem for `.List` method on shaped arrays and that was fixed in https://github.com/rakudo/rakudo/commit/8568dd1 However, the same issue exists with the `.Array` method:

```
<Zoffix_> m: my @a[2;2]; dd @a.List
<camelia> rakudo-moar 070780e04: OUTPUT: «(Any, Any, Any, Any)␤»
<Zoffix_> m: my @a[2;2]; dd @a.Array
<camelia> rakudo-moar 070780e04: OUTPUT: «Cannot access 2 dimension array with 1 indices␤  in block <unit> at <tmp> line 1␤␤»
```

The issue bisects to https://github.com/rakudo/rakudo/commit/c9a9bc855660812a91a534101476fad9642ac92f

There's [already a test for `.List` for this bug](https://github.com/perl6/roast/commit/1c61263ca), which can be simply expanded to cover this bug in `.Array`

(there's a slightly related [R#2256](https://github.com/rakudo/rakudo/issues/2256))

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/efbd58c8d5 , tests added with https://github.com/perl6/roast/commit/eae3635188
