### ISSUE TITLE
Test::isa-ok can't handle a Junction:D as $expected

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2258]
I was expecting this code to test that `$given` is an `Int`, as well as a `Cool` and is an `Any`. While the `isa-ok` does accept a `Junction` in `$expected` without threading (as I'd expect it to), it doesn't actually thread the contents in the test and simply blindly calls `.isa` on the `$given`, giving it the Junction I handed it.

```
<Zoffix_> m: use Test; isa-ok 42, Int & Cool & Any
<camelia> rakudo-moar 070780e04: OUTPUT: «not ok 1 - The object is-a 'all(Int, Cool, Any)'␤# Failed test 'The object is-a 'all(Int, Cool, Any)''␤# at <tmp> line 1␤# Actual type: Int␤»
```

I think it'd be more useful for the test to thread the junction internally and perform a single test on the result. Something like

```
<Zoffix_> m: use Test; use nqp; my $exp := Int & Cool & Any; my $giv := 42; nqp::istype($exp, Junction:D) ?? ok ?($exp.THREAD: { $giv.isa: $_  }) !! isa-ok $giv, $exp
<camelia> rakudo-moar 070780e04: OUTPUT: «ok 1 - ␤»
<Zoffix_> m: use Test; use nqp; my $exp := Int & Cool & Date; my $giv := 42; nqp::istype($exp, Junction:D) ?? ok ?($exp.THREAD: { $giv.isa: $_  }) !! isa-ok $giv, $exp
<camelia> rakudo-moar 070780e04: OUTPUT: «not ok 1 - ␤# Failed test at <tmp> line 1␤»
```

-----------------

Related ticket: [R#2017](https://github.com/rakudo/rakudo/issues/2017)

(tangently-related [R#2259](https://github.com/rakudo/rakudo/issues/2259))

**Comment by lizmat** [comment]
closing, please open problem solving issue if so wanted.
