### ISSUE TITLE
.keys on shaped arrays adds a list around returned values

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2262]
I assume the two versions are meant to give the same results:

```
<Zoffix_> m: dd (my str @ = "a".."z").keys
<camelia> rakudo-moar 3272207ae: OUTPUT: «(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25).Seq␤»
<Zoffix_> m: dd (my str @[26] = "a".."z").keys
<camelia> rakudo-moar 3272207ae: OUTPUT: «((0,), (1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,), (10,), (11,), (12,), (13,), (14,), (15,), (16,), (17,), (18,), (19,), (20,), (21,), (22,), (23,), (24,), (25,)).Seq␤»
```

**Comment by zoffixznet** [comment]
There was actually a proptest for the behaviour, which [was passing due to use of `is` instead of `is-deeply` on the data](https://github.com/perl6/roast/commit/a3e197822c). 

I fudged it in https://github.com/perl6/roast/commit/17db6d7112

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/5a9105ae23 , tests unfudged with ttps://github.com/perl6/roast/commit/5ecff38c64
