### ISSUE TITLE
IO::Path .r method returns false negative on VirtualBox shared path

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2264]
## The Problem

When testing for a file accessibility on a vboxsf type filesystem in a Linux virtual machine running under VirtualBox `.r` returns _false_ despite of file having group readability on.

## Expected Behavior

Must return _true_.

## Steps to Reproduce

On a mounted VirtualBox shared folder the following steps could performed to see the problem:
```
/media/sf_src/Perl6/experiments/filecheck ⇒ touch myfile                                                                                                                             18-09-08 22:28 
/media/sf_src/Perl6/experiments/filecheck ⇒ ll myfile                                                                                                                                18-09-08 22:28 
-rwxrwx--- 1 root vboxsf 0 Sep  8 22:28 myfile*
/media/sf_src/Perl6/experiments/filecheck ⇒ groups                                                                                                                                   18-09-08 22:28 
vrurg vboxsf
/media/sf_src/Perl6/experiments/filecheck ⇒ perl6 -e 'say "CAN READ" if "myfile".IO.r'                                                                                               18-09-08 22:28 
/media/sf_src/Perl6/experiments/filecheck ⇒ perl6 -e 'say "EXISTS" if "myfile".IO.e'                                                                                                 18-09-08 22:29 
EXISTS
```

**UPDATE** Same problem occurs on a samba mount in the same vboxed Linux. Perhaps it is common to networked file systems.

## Environment
* Operating system: macos 10.13, VirtualBox 5.2.18, Linux Mint 19
* Compiler version (`perl6 -v`): This is Rakudo version 2018.08 built on MoarVM version 2018.08

**Comment by zoffixznet** [comment]
Does `perl -wlE 'say -r "myfile" ? "readable" : "nope"'` print `readable`? (note it's `perl` not `perl6`)

**Comment by vrurg** [comment]
That's funny, but perl similarly fails with samba mount on all checks. But with vboxsf it works as expected: all positive.

Worth noting that shell (zsh) does it all correct with both file systems.

**Comment by lizmat** [comment]
Closing as unfixable at this level
