### ISSUE TITLE
Inconsistent .Numeric and .elems on infinite ranges

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2265]
I know we have `.elems` throw on lazy lists, but how come we do the same for infinite ranges (the ones we can know are infinite)?

The behaviour is even more flabbergasting considering calling the highly-related `.Numeric` instead of `.elems` *does* actually give `Inf`:

```
<Zoffix_> m: dd ^Inf .Numeric
<camelia> rakudo-moar 3272207ae: OUTPUT: «Inf␤»
<Zoffix_> m: dd ^Inf .elems
<camelia> rakudo-moar 3272207ae: OUTPUT: «Failure.new(exception => X::Cannot::Lazy.new(action => ".elems", what => Any), backtrace => Backtrace.new)␤»
```

**Comment by lizmat** [comment]
FWIW, if we change that, we will need to do a core audit because the throwing behaviour of .elems is used in many places to guard against infinity

**Comment by zoffixznet** [comment]
> how come we do the same for infinite ranges (the ones we can know are infinite)?

Found [some past discussion on this](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2017-06-07#l65):

> jnthn | No, elems should not return Inf :/
> jnthn | eveo: Because the expectation of .elems is you're getting an Int back

And a propspec for `.elems` throwing: https://github.com/perl6/roast/commit/c168311e6

**Comment by lizmat** [comment]
Also, laziness does **not** necessarily imply that there are infinite values.  It just implies that we don't know how many values will be produced.
