### ISSUE TITLE
 Delegation fails with "Cannot invoke this object" when loading class from a library

### ISSUE THREAD

**Issue by dmaestro** [rakudo/rakudo#2269]
## The Problem
I've created a perl6 library module which delegates a method via a role. When loading the module the delegation fails with a mysterious error message.
## Expected Behavior
I can run the simplified module code as a one-liner and I get the expected result of the delegation:
```
$ perl6 -e 'package TestD { role R { method foo(-->Int) {...} }; class C { has R $.delegate handles * is required; }; class D does R { has Int $.foo; }; }; my $d = TestD::D.new(:foo(2)); my $c = TestD::C.new(delegate => $d); say $d.foo; say $c.foo'
2
2
```

## Actual Behavior
Doing a 'use' (or -M) to load the module from a file ([gist: TestD.pm6](https://gist.github.com/dmaestro/826f4a602136606b8db98a1c72785ef2)) fails:
```
$ perl6 -Ilib -MTestD -e 'my $d = TestD::D.new(:foo(2)); my $c = TestD::C.new(delegate => $d); say $d.foo; say $c.foo'
2
Cannot invoke this object (REPR: Null; VMNull)
  in block <unit> at -e line 1
```
## Steps to Reproduce
Use the command lines show above with the module file copied to the `./lib` directory.

## Environment
* Operating system: linux
* Compiler version (`perl6 -v`): This is Rakudo Star version 2018.06 built on MoarVM version 2018.06

**Comment by dmaestro** [comment]
Adding `no precompilation;` to the module masks the error.

**Comment by vrurg** [comment]
Tested on 2019.07.1 – fails. `HEAD` passes.

Closing via MoarVM/MoarVM#1209 and 7e3d023b4b070ed798915336a98f2bbc7fbac2e7
