### ISSUE TITLE
Closed handles are still readable for some time

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2272]
You used to get a (somewhat LTA) error when trying to read from a closed handle. Now, you'll actually get some data:

```
<Zoffix_> c: 2017.05,2017.06 "/tmp/fooo42".IO.spurt: "a\nb\nc"; my $*IN = "/tmp/fooo42".IO.open; dd $*IN.get; $*IN.close; dd $*IN.get

<committable6> Zoffix_, ¦2017.05: «"a"␤readline requires an object with REPR MVMOSHandle (got VMNull with REPR Null)␤  in block <unit> at /tmp/quwQc9ptTK line 1␤␤ «exit code = 1»» ¦2017.06: «"a"␤"b"␤»
```

I'm guessing that data is coming from the decoder's buffer and you will get the same old error once that buffer is exhausted. The `.close` method needs to empty the buffer.

**Comment by lizmat** [comment]
I think this is going to require a `Decoder.reset` interface method **and** support at the NQP/MoarVM level.  My attempts at emptying out the current buffer by consuming available chars / bytes, create a number of different internal errors.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/d419a31312 removes the error by returning `Nil` instead,  **AFTER** the buffer has been exhausted,

**Comment by zoffixznet** [comment]
I haven't had the chance to spectest this, but seems it fixes the problem:

```
$ ./perl6 -e '"/tmp/fooo42".IO.spurt: "a\nb\nc"; my $*IN = "/tmp/fooo42".IO.open; dd $*IN.get; $*IN.close; dd $*IN.get'
"a"
eof requires an object with REPR MVMOSHandle (got VMNull with REPR Null)
  in block <unit> at -e line 1
```

```diff
diff --git a/src/core/IO/Handle.pm6 b/src/core/IO/Handle.pm6
index c3e1485ad..6627aa9f9 100644
--- a/src/core/IO/Handle.pm6
+++ b/src/core/IO/Handle.pm6
@@ -211,6 +211,7 @@ my class IO::Handle {
     }
 
     method close(IO::Handle:D: --> True) {
+        $!decoder && $!decoder.consume-all-chars;
         nqp::if(
           nqp::defined($!PIO),
           nqp::stmts(
```

**Comment by lizmat** [comment]
That’s exactly what I did.  Spectest it and you’ll see it is not enough :-(

**Comment by zoffixznet** [comment]
Using this code, I avoided all the malformed UTF-8 errors:

```perl6
$!decoder && $!decoder.consume-exactly-bytes: $!decoder.bytes-available;
```

But it still dies on one test with:
```
Decoder may not be used concurrently
  in block  at t/spec/S32-io/io-handle.t line 261
  in block <unit> at t/spec/S32-io/io-handle.t line 254
```

I looked at the referenced line, and don't see any concurrency involved, so not sure how to proceed.

**Comment by lizmat** [comment]
Apart from the one test failure, this could work.  But may do unnecessary work.  We need an API function to reset the decoder buffer.

**Comment by lizmat** [comment]
FWIW, the test just before it is bogus:

    dies-ok { $fh.slurp.encode }

already dies on the `.slurp` with:

    Will not decode invalid ASCII (code point > 127 found)

**Comment by lizmat** [comment]
Golf:

    my $h = "fovo".IO.open(:enc<ascii>); try $h.slurp; $h.close

whereby "fovo" contains the string 'fo♥o"

**Comment by lizmat** [comment]
I think the problem is caused by leaving the buffer in some weird state if `nqp::decodertakeallchars(self)` fails because of a decoding error.  It looks like `nqp::decoderbytesavailable(self)` is still set to the complete buffer size, instead of being reset.

**Comment by lizmat** [comment]
So I guess this means that we *really* should have a "reset" function, that resets the buffer regardless of what state it is in.

**Comment by zoffixznet** [comment]
Reopened for the `testneeded` tag, but IIRC when I was playing with this Issue I tried what you done in the code and that leads to subsequent `.get` (and other routines) to die with "cannot read on binary handle" instead of giving proper error about closed handle (or the null thing in OP)

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/7e30619fba

**Comment by zoffixznet** [comment]
> that leads to subsequent .get (and other routines) to die

Ah, OK, I backlogged IRC now:

> jnthn | iirc, there's a function that throws if we're missing the decoder, and we can probably tweak it to check the $!VMIO and complain about a read from a closed handle rather than about the thing being in binary mode

> Tests added with

That doesn't cover the OP bug tho.

**Comment by lizmat** [comment]
`$!decoder && ($!decoder := $!decoder.new($!encoding)),` seems to do a better trick.

But I shudder at the thought of having to allocate a new decoder **EVERY TIME WE CLOSE A HANDLE**

**Comment by niner** [comment]
I have fixed the "Decoder may not be used concurrently" issue in MoarVM this summer during my GC issue fixing spree: https://github.com/MoarVM/MoarVM/commit/e2f576370f231f36ceb52c780c64a1a13a3cedef

So maybe one of the proposed fixes here can now be implemented?

**Comment by vrurg** [comment]
@niner off-topic, but what is the condition for "Decoder may not be used concurrently" error to fire? This is the problem which prevents `EVAL` to be trully concurrent. Things did really improved since I tested it last time. But a test script is still flapping and more likely to throw the error than to pass.

The script is following, if you interested in trying it:

```perl6
my @w;
for ^30 -> $i {
    @w.push: start {
        my $a;
        EVAL q|$a = $i; sleep .3.rand|;
        say "Oops?" unless $a == $i;
    }
}

note "await";
await @w;
note "done";
```

**Comment by niner** [comment]
@vrurg well that error message was totally legit! The MAST compiler uses a latin1 string decoder to turn a buffer into a string for use as a hash key. Multiple compiler objects shared a single global decoder which is just not a good idea, since string decoders are stateful. Fixed that in https://github.com/perl6/nqp/commit/d69855343c8dbf95b16412efa3ddb99fb0164007

With that your example runs much more stable, though there are still other issues.

**Comment by vrurg** [comment]
@niner I don't know what other issues are lurking in the dark, but on the top 50 runs, 100 concurrent threads went on smoothly, no failures. Fantastic! Thanks!

I think, with the next NQP bump we can close a couple of issues.

**Comment by lizmat** [comment]
so is this still an issue?
