### ISSUE TITLE
Future removal of returns?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2274]
## The Problem

In [Constraining return types](https://docs.perl6.org/type/Signature#Constraining_return_types), this is said:

> (`returns`) This form is proposed for future removal.

and mentioned as a caveat for constraining return types.

Is that true? Where is that mentioned? I'm asking this only to be aware of when it happens, changing that text. Or if it's not going to happen, just delete that caveat.

**Comment by zoffixznet** [comment]
The wording there is very precise: **proposed**. Not planned.

From [the commit that added that wording](https://github.com/perl6/doc/commit/704c7f7361d36a5db714c6be9994ba44c0042b9d):

> The removal of `returns` trait was only ever proposed by TimToady and jnthn was against it.
Currently, `grep -FR 'returns' | wc -l` gives 11,263 matches, so unless TimToady wants
to invoke Rule 1, feels like the ship for making this change has sailed.

So, I'd suggest following up with @TimToady

**Comment by lizmat** [comment]
FWIW, I wouldn’t be against a removal of “returns”.  Especially since we cannot see a difference once it has been parsed:

    sub a($a) returns Int { };
    dd &a.signature;   # :($a --> Int)

The “returns” feels like a trait on the sub, whereas it just add things to the signature of the sub.  Having that between the parens of the rest of the signature, feels much more natural to me.

**Comment by zoffixznet** [comment]
> Having that between the parens of the rest of the signature, feels much more natural to me.

Same here. And I recall TimToady's argument was more practical. It was something about adding some features in the future. Also, AFAIK you can't stick `returns` on a block, and some things (e.g. literals) don't work with the `returns` form either.

**Comment by JJ** [comment]
OK. Thanks for clarifying.
