### ISSUE TITLE
Make rakudo relocatable / portable

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#2278]
Currently neither moarvm nor rakudo are portable. In both the installation location is set at compile time and required to stay that way at runtime. I can be helpful to be able to compile a rakudo that can be freely moved.
I think there is a justified need for a rakudo with a fixed install location (classic installation in linux distributions is an example), so this should be optional.

**Comment by patzim** [comment]
This RT ticket is related: https://rt.perl.org/Public/Bug/Display.html?id=122752

**Comment by patzim** [comment]
This has been fixed in #2693
Tests are still missing. @ugexe had the idea to use a CI job to test relocatability.

**Comment by patrickbkr** [comment]
A CI building and testing relocatable builds has been deployed. So I consider this fixed. See also #3679
