### ISSUE TITLE
Make it easier to set up custom argument parsers

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2279]
Based off http://colabti.org/irclogger/irclogger_log/perl6?date=2018-09-15#l316

```
13:30 | leont | Sure, but given that there isn't any non-internal way to do this,
      I would still like it to keep working.
-- | -- | --
13:30 | leont | Now working around it with a multi, but it's a bit unfortunate.
13:30 | Zoffix | leont: "do this" is do what?
13:30 | leont | Install a different argument parser
13:31 | Zoffix | leont: and basically replace the MAIN_HELPER with a new sub?
13:32 | leont | Yeah. I'm not even the first to do that.
```

I'm imagining a module that sets something in `%*SUB-MAIN-OPTS` (e.g. assigns a custom `Callable` to some key) affect how the arguments are parsed. I'm hoping that's possible to do in a way that the use of that module would just be able to `use GetOpt::Whatever` and not have to modify `SUB-MAIN-OPTS` themselves.

**Comment by Leont** [comment]
Quite frankly, parsing arguments is what `MAIN_HELPER` is about, and while I can imagine a better hook to override it, I don't think it would be functionally very different.

**Comment by Leont** [comment]
> I'm imagining a module that sets something in %*SUB-MAIN-OPTS (e.g. assigns a custom Callable to some key) affect how the arguments are parsed.

That sounds sensible enough.

**Comment by Leont** [comment]
Is it possible to create  a contextual variable in an outer scope though?

**Comment by Leont** [comment]
Yeah I meant dynamic. I'm not sure that solution really is better than our current, at last `MAIN_HELPER` is scoped!

**Comment by zoffixznet** [comment]
Does that even matter? There's only one MAIN (even if it's a bunch of multies) that would get processed and `%*SUB-MAIN-OPTS` is the official hash with `MAIN` handling options.

In fact, it was global briefly before, but was removed so that we don't pay for its initialization when the user isn't gonna use it.

**Comment by zoffixznet** [comment]
Also, we could have something similar to how you can do `use Foo:from<Perl5>` without having to explicitly `use Inline::Perl5`, so that the user would specify which processor they want by declaring the `%*SUB-MAIN-OPTS`. Something like

```perl6
    my %*SUB-MAIN-OPTS = :processor<Awesome>;
````

And that would automatically load `GetOpt::Awesome` module and use its callable from its predefined method or something (sort-of how we handle custom exeption handlers with `Exceptions::BlahBlah` and setting env var to `BlahBlah` string)

**Comment by Leont** [comment]
To be honest, the old (pre 2018.06) `MAIN_HELPER` still looks like the best interface I've seen so far.

**Comment by zoffixznet** [comment]
@Leont would you be able to take [new MAIN helpers](https://github.com/rakudo/rakudo/commit/fbfccfa2ff30f6093176fa34da038442d8d427d5) for a spin?

**Comment by Leont** [comment]
Yeah it looks sensible.
