### ISSUE TITLE
Problems with `EmptySeq`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2281]
The `EmptySeq` was introduced in https://github.com/rakudo/rakudo/commit/b4df753dfcd4260ab9a0d40d1eb9dfdb5a5043d9 as an optimization and there are two issues with it:

### Leak to userspace

It exists as a symbol in user space.

```
<Zoffix_> m: dd EmptySeq
<camelia> rakudo-moar 8fcebb861: OUTPUT: «().Seq␤»
```

It's unspecced and undocumented (and shouldn't be IMO). If there's no way to hide it, then it should be named `RakudoInternalsEmptySeq` instead. However...

### It doesn't pass as a proper Seq

It doesn't `eqv` to a `().Seq`, nor does it `===` to it and possibly some other ops are similarly affected.

```
<Zoffix_> m: %*ENV<PATH> = ''; dd IO::Spec::Unix.path eqv ().Seq
<camelia> rakudo-moar 8fcebb861: OUTPUT: «Bool::False␤»

<Zoffix_> m: %*ENV<PATH> = '';  dd IO::Spec::Unix.path === ().Seq
<camelia> rakudo-moar 8fcebb861: OUTPUT: «Bool::False␤»
```

**Comment by zoffixznet** [comment]
This issue required fudging one of the proptest in https://github.com/perl6/roast/commit/84da99b988 Once the Issue is fixed, the fudge should be reverted.

**Comment by lizmat** [comment]
Basically reverted with a4db33e72b

**Comment by lizmat** [comment]
Test unfudged with https://github.com/perl6/roast/commit/6360992678
