### ISSUE TITLE
.lines/.words :close closes too late when $limit is specified

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2283]
If you specify $limit to these two methods, you have to pull one more than $limit items from the iterator before the handle is actually closed.

This causes the handle to remain open when a slice or list assignment is used:

```
$ echo -e 'A\nB\nC' | perl6 -e '@ = $*IN.lines(2, :close); say $*IN.opened'
False
$ echo -e 'A\nB\nC' | perl6 -e '@ = $*IN.lines(2, :close)[^2]; say $*IN.opened'
True
$ echo -e 'A\nB\nC' | perl6 -e 'my ($a, $b) = $*IN.lines(2, :close); say $*IN.opened'                                                                                                                           
True

$ perl6 -v
This is Rakudo version 2018.08-47-g070780e04 built on MoarVM version 2018.08-28-g2fb3265a1
implementing Perl 6.c.
```

The change likely will involve modifying the conditionals of the `FirstNThenSinkAllN` and `FirstNThenSinkAllCallable` iterators: https://github.com/rakudo/rakudo/blob/a4db33e72/src/core/Rakudo/Iterator.pm6#L1571-L1631

**Comment by lizmat** [comment]
FWIW, I think the .lines($limit) / .words($limit) features have lost a lot of their use now that we have .head($limit).  Personally, I wouldn’t mind seeing them go.  They only now have a use in conjunction with :close

**Comment by zoffixznet** [comment]
Sorry. I noticed this ticket was assigned only after I already got a fix. Feel free to revert it and use something better.
