### ISSUE TITLE
.WHAT bug; REPL only

### ISSUE THREAD

**Issue by frithnanth** [rakudo/rakudo#2284]
## The Problem

This bug shows only in the REPL:
```
> my int32 $a = 2
2
> $a.^name
Int
> $a.WHAT
At Frame 1, Instruction 20, op 'getlex_ni', operand 0, MAST::Local of wrong type (3) specified; expected 4
```

## Expected Behavior

The command line behavior is correct:
```
$ perl6 -e 'my int32 $a = 2;say $a.^name;say $a.WHAT'
Int
(Int)
```

## Environment
* Operating system: Debian Linux
* Compiler version (`perl6 -v`): `This is Rakudo version 2018.08 built on MoarVM version 2018.08`

**Comment by zoffixznet** [comment]
Looks like `.WHAT` isn't even needed:

```
2018.08.47 zoffix@VirtualBox~$ perl6
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
> my int32 $a = 2
2
> say $a
At Frame 1, Instruction 23, op 'getlex_ni', operand 0, MAST::Local of wrong type (3) specified; expected 4

> 
```

And looks like there's an RT ticket for the same issue, except now the error is different [RT#127933](https://rt.perl.org/Ticket/Display.html?id=127933#ticket-history) (I'm gonna close it in favour of this ticket)

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/7c0a81f501
