### ISSUE TITLE
t/spec/S10-packages/require-and-use.t hangs

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2299]
Based on [my last successfull stresstest run](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-20#l245) the suspect commits would be either https://github.com/rakudo/rakudo/commit/58592bd0de or https://github.com/rakudo/rakudo/commit/c9432c2072

**Comment by zoffixznet** [comment]
To add: it hangs while failing to detect circularity (can be seen by setting `RAKUDO_MODULE_DEBUG`). I also added a debug print [before the error message would normally be thrown](https://github.com/rakudo/rakudo/blob/c9432c20721104ced7e2408da5ba1f15ad320975/src/core/CompUnit/PrecompilationRepository.pm6#L247) dumping `$modules` and it's always empty.

**Comment by zoffixznet** [comment]
Reverting c9432c2 fixes the problem.

**Comment by lizmat** [comment]
Reverted with c14df18932
