### ISSUE TITLE
Replace code of the internal json parser with code from JSON::Fast

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2311]
This was discussed multiple times recently but afaik no ticket was created, so I'm making one.

Some discussions:
* https://github.com/ugexe/zef/issues/272
* http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-19#l281
* http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-20#l67

Simple TL;DR: just swap [this code](https://github.com/rakudo/rakudo/blob/c14df1893205ab2fcca9f0ee0222bfcc254bc05e/src/core/Rakudo/Internals/JSON.pm6) with [this](https://github.com/timo/json_fast/blob/master/lib/JSON/Fast.pm), and make sure that @timo is OK with it.

Ping @timo, @tony-o.

As far as I know nobody is working on it right know, so *please assign yourself* here if you start working on it.

**Comment by coke** [comment]
I think lizmat has work in progress on a non-json-fast fast json.

**Comment by AlexDaniel** [comment]
@coke more details please. So far I've seen efforts to parallelize parsing of the ecosystem file, which I guess is a good idea in terms of wall clock time… but doesn't solve the problem of having a json parser that is slower than it can be.

**Comment by coke** [comment]
Only other details I have: @lizmat

**Comment by lizmat** [comment]
FWIW, I never wanted to make a full JSON parser replacement, I wanted to make module installing faster.  Whether that be by replacing R:I:JSON by JSON::Fast, or something else that parallelizes, I don't care much as it's all under the hood.  So my eyes have purely on make parsing JSON faster, **not** writing JSON.

**Comment by AlexDaniel** [comment]
> Whether that be by replacing R:I:JSON by JSON::Fast, or something else that parallelizes

It can be both.

**Comment by lizmat** [comment]
Actually, with the last batch of improvements of JSON::Fast, the parallelizing code that I had, only made it slower.  Changing the batch size from 32 to 128 helped a bit, but the
difference is now 0.19 vs .17 (parallel) on my machine.  I don’t think that warrants the added complexity / fragility.  And it will probably be dwarved again by further JSON::Fast improvements.

**Comment by AlexDaniel** [comment]
Thank you for your work, @lizmat!

**Comment by AlexDaniel** [comment]
@ugexe thank you very much! But in case somebody wants to depend on that change, most likely it won't be part of the upcoming release.
