### ISSUE TITLE
Mismatch between `cas` docs and spec

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2313]
The [docs](https://docs.perl6.org/routine/cas) show it taking `(atomicint, int, int)` and say values will be coerced and unboxed, but [the spec](https://github.com/perl6/roast/commit/a42b3995b) tests it with a custom object and no unboxing/coercion seems to occur.

Are the docs wrong?

ping @jnthn

**Comment by lizmat** [comment]
Before @jnthn implemented `cas()` properly, there was a not very well functioning place holder.  I think the test is from that time and should probably be ditched / adapted.

**Comment by zoffixznet** [comment]
Then, is it just a fluke that it seems to work with arbitrary objects, [as claimed by the test](https://github.com/perl6/roast/blob/84974bf372d86780d88e1e34334161a4bea8c9b4/S17-lowlevel/cas.t#L50-L71)?

**Comment by zoffixznet** [comment]
Moved Issue to docs repo https://github.com/perl6/doc/issues/2393
