### ISSUE TITLE
Perl 6 keywords.

### ISSUE THREAD

**Issue by Alihusejn** [rakudo/rakudo#2315]
Could you change these keywords with more briefly? These keywords are very tiresome.

atomic-fetch(); 
atomic-assign();
atomic-fetch-inc();
atomic-fetch-dec();
atomic-inc-fetch();
atomic-dec-fetch();
atomic-fetch-add();

**Comment by lizmat** [comment]
https://docs.perl6.org/language/unicode_ascii.html#Atomic_operators

**Comment by zoffixznet** [comment]
Thanks for the suggestion, but this has been discussed thoroughly in the past and the current names is fairly settled. These aren't a type of routines most users would use commonly, so we're aiming at them being more descriptive than terse.

You have the option of using Unicode ops. Most operating systems and some hardware let you bind shortcuts to various typing constructs, so you could look into binding some easy key for the ops, if you use them frequently.

Also, you could define your own operators or routines and stick 'em in a module, potentially [releasing it to the Ecosystem as well](https://docs.perl6.org/language/modules.html):

```
<Zoffix_> m: constant &postfix:<@++> = &atomic-fetch-inc; my atomicint $x; $x@++; dd $x
<camelia> rakudo-moar 75cf8be72: OUTPUT: «1␤»
```
