### ISSUE TITLE
Confusing typecheck results with native types

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2316]
You can typecheck native "type objects" accuratelly, but if you typecheck against a native variable, then the result seems to be always `False` for native types.

I was expecting either the "type object" version to fail or for both versions to work:

```
1324    @Zoffix │ m: use nqp; my int64 $x; say int64 ~~ int64                                                                                                          │                
1324   +camelia │ rakudo-moar 2bdf2b35a: OUTPUT: «True␤»                                                                                                               │        
1324    @Zoffix │ m: use nqp; my int64 $x; say $x ~~ int64                                                                                                             │      
1324   +camelia │ rakudo-moar 2bdf2b35a: OUTPUT: «False␤»
```

```
1323    @Zoffix │ m: use nqp; dd nqp::istype(int64, int64)                                                                                                             │         
1323   +camelia │ rakudo-moar 2bdf2b35a: OUTPUT: «1␤»                                                                                                                  │                
1323    @Zoffix │ m: use nqp; my int64 $x; dd nqp::istype($x, int64)                                                                                                   │      
1323   +camelia │ rakudo-moar 2bdf2b35a: OUTPUT: «0␤» 
```

And the question is: is this normal? Is there a logic underneath it that could be documented?

**Comment by jnthn** [comment]
> And the question is: is this normal? Is there a logic underneath it that could be documented?

Yes. Type checking is an operation on objects; the more general way to remember it is that method calls require an object (and so box their target if needed), and `~~` is defined in terms of `.ACCEPTS`, thus what's actually being tested is if a boxed object will be an `int64`, which it never will be. By contrast, the check `int64 ~~ int64` involves two objects.
