### ISSUE TITLE
atomicint.Range lies

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2317]
It's missing [from the list of things checked](https://github.com/rakudo/rakudo/blob/b537ce2e5/src/core/Int.pm6#L196).

If I'm not mistaken, its size varies depending on the platform.

```
+Zoffix │ m: say atomicint.Range                                                                                                                              +camelia │ rakudo-moar b537ce2e5: OUTPUT: «-Inf^..^Inf␤»
```

```
+Zoffix │ Yeah, `my atomicint $x; $x = 2**31; say $x` is -2147483648 on my 32-bit box, but 2147483648 on 64-bit
```

**Comment by jnthn** [comment]
I always found that a slightly strange API to introspect a meta-property, but yes, this should indeed reflect the supported atomic size on the current machine.
