### ISSUE TITLE
Size doesn't matter for native assignment when deciding to throw

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2318]
As I recall, the behaviour for natives is assigning too large a value throws, but mutating an existing value into overflow (e.g. `$x++`) overflows/underflows.

However, regardless of the size of a native you choose, the throwage happens only at 64-bit mark. This includes `atomicint` on 32-boxes assignment of `32bit < v < 34bit` values to which overflows, yet over 64bit throws.

```
1447    +Zoffix │ Looks like throwage happens only when you go over 64 bit — regardless of the type used
1447    +Zoffix │ m: my int8 $x = 500                                                                                                                                 
1447   +camelia │ rakudo-moar b537ce2e5: ( no output )                                                                                                                
1447    +Zoffix │ m: my int8 $x = 2**64                                                                                                                               
1447   +camelia │ rakudo-moar b537ce2e5: OUTPUT: «Cannot unbox 65 bit wide bigint into native integer␤  in block <unit> at <tmp> line 1␤␤» 
1448    +Zoffix │ And same for atomicint. Throws over 64bit, but overflows on my 32bit box if it's over 32bit but still under 64bit 
```

------

Related ticket: https://rt.perl.org/Ticket/Display.html?id=127409 [BUG] Inconsistencies and Bugs in Native Types Behaviours

**Comment by lizmat** [comment]
See [`Native::Overflow`](https://raku.land/zef:lizmat/Native::Overflow)
