### ISSUE TITLE
LTA error with $^foo/$:foo variables in methods

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2320]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

```
$ perl6 -e 'class { method z { $^a } }'
===SORRY!=== Error while compiling -e
Placeholder variables cannot be used in a method
at -e:1
------> class { method⏏ z { $^a } }



16:12 | SmokeMachine | what this mean? `Placeholder variables cannot be used in a method`
-- | -- | --
16:12 | SmokeMachine | what's a Placeholder variable?
```

Should probably extend the error text to say `"please specify an explicit signature"` or something along the lines. Maybe explain the vars too:

```
Placeholder variables (e.g $^foo/$:foo) cannot be used in a method. 
Please specify an explicit signature
```

Bonus points for reporting actual variable name the user tried to use.

**Comment by dogbert17** [comment]
Shouldn't this be closed? The error message has been improved and tests have been added. Perhaps I'm missing something here.

**Comment by vrurg** [comment]
Closing.

@dogbert17 thanks for clearing up a bunch of tickets!
