### ISSUE TITLE
Segfault in test-compilation of documentation examples

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2324]
## The Problem

Download the perl6/doc repo. 

With Rakudo 2018.08 and 2018.09, 

    perl6 xt/examples-compilation.t doc/Type/Cool.pod6

Segfaults when it arrives to the test #175 or #176. The particular number changes with each running, BTW, but it's in that ballpark.
It's not specific code, I have skipped testing what was there and it keeps segfaulting:

    segmentation fault (core dumped)  perl6 xt/examples-compilation.t doc/Type/Cool.pod6

It works with Rakudo 2018.06. It's probably segfaulting in some other cases. I have tested other "heavy" clases, and it segfaults too:

    segmentation fault (core dumped)  perl6 xt/examples-compilation.t doc/Language/operators.pod6

In this case when it arrives to test number 169. 

It might have something to do with this perl6/doc#1951, which is a similar, intermitent, error (only it's stopped being intermitent). That one, in turn, might have something to do with MoarVM/MoarVM#943, but it's not clear what.

## Steps to Reproduce

Provided above. I haven't been able to golf it down, and it might be difficult to golf, since it actually only happens when lots of tests are involved. 

## Environment

Also provided above. This is Ubuntu server with kernel 3.13 in x86_64 linux.

**Comment by coke** [comment]
I was having similar issues on mac os x on an older box. (not running latest OS or xcode). No issues on a beefier system.

**Comment by JJ** [comment]
@coke maybe related to memory?
I know that it might be the bugle call for taking a look at the tests and revamping them, but I still think there might be an underlying issue there, even more so when it's started to happen with the latest versions.

**Comment by coke** [comment]
badly written tests or no, rakudo should never segv.

**Comment by JJ** [comment]
This fixed itself with the latest version of Rakudo.
