### ISSUE TITLE
Possible `for...` Opt Opportunity

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2326]
Currently [we opt only `for ^$32-bit-number {}`](https://github.com/rakudo/rakudo/commit/1a103e7457d15029333fb8840cfc4351f2ec5598#diff-c6d4338f0fe083856631860c53453281R893), but we could potentially go up to 64-bit.

Probably not many loops with so many iterations in the wild, but still, some boost...

http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-27#l660

```
22:35 | yoleaux | 16:55Z <Zoffix> jnthn: is it deliberate that the range of optimized values doesn't include the endpoints? I.e. that comparators are `>`/`<` instead of `>=`/`<=`? https://github.com/rakudo/rakudo/commit/1a103e7457d15029333fb8840cfc4351f2ec5598#diff-c6d4338f0fe083856631860c53453281R893
-- | -- | --
22:36 | jnthn | Zoffix: Umm...I can't immediately think of a reason.
22:37 | jnthn | I wonder if we can do it with 64-bit numbers even
22:38 | jnthn | Or at least, do that on MoarVM and JVM...I dunno about js in that reguard
```

**Comment by lizmat** [comment]
I think this was done this way because we still support 32bit builds and we cannot easily / reliably see at that stage for which arch we're compiling?

**Comment by zoffixznet** [comment]
I thought `int` was 64-bit even on 32-bit hardware, at least on MoarVM.

**Comment by lizmat** [comment]
This will need to be revisited in RakuAST anyway, so closing this here now
