### ISSUE TITLE
Problem with typed Arrays of roles

### ISSUE THREAD

**Issue by mikkelstb** [rakudo/rakudo#2328]
## Problem:
At certain conditions, assigning a typed Array with roles to Nil, results in the somewhat strange error message of the type:

Type check failed in assignment to $myroles; expected Array[MyRole] but got Array[MyRole]
  in method test at /../(Example) line 9
  in block <unit> at test.t line 6

## Expected Behavior
I would assume this should not end in an error message

## Steps to Reproduce
Assuming you have two classes A and B and one role R each in separate file, and a test script running an instance of class A.
All 4 files are located within the same folder. The test script has a lib statement pointing to the current folder, and a use statement use A.

Class A has a use statement: use B
Both classes A and B has a use statement: use R
Class A has a B as an instance variable
Cass B has an Array[R] as an instance variable

If in class A within any given method I try to assign:
my $r_collection Array[R] = Nil;
Type check failed in assignment to $myroles; expected Array[R] but got Array[R]

This only happens as long class B has an instance variable of an Array[R]. If I comment out this in class B, the assignment statement in class A validates.

I have attached an example.
[roletest.tar.gz](https://github.com/rakudo/rakudo/files/2427200/roletest.tar.gz)

Running perl6 test.t will result in a type check error:

Type check failed in assignment to $mov; expected Array[Moveable] but got Array[Moveable]
  in method getMoveables at /home/mikkel/perl6/roletest/Factory.pm6 (Factory) line 9
  in block <unit> at test.t6 line 6

Commenting out line 6 in Robot.pm6 and the code validates. Though this instance variable in Robot should not have any relation with the assignment in Factory at line 9.

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): 
Rakudo version 2018.09-39-g49baea7 built on MoarVM version 2018.09-90-gb5eb48c
implementing Perl 6.c.

Hope this explains the problem well enough. This is my first ever bug report.

**Comment by CIAvash** [comment]
Sounds like another shape of these bugs:
https://github.com/rakudo/rakudo/issues/2182
https://rt.perl.org/Public/Bug/Display.html?id=132525
https://rt.perl.org/Public/Bug/Display.html?id=127001
https://rt.perl.org/Public/Bug/Display.html?id=128287
https://rt.perl.org/Public/Bug/Display.html?id=132592
https://rt.perl.org/Public/Bug/Display.html?id=127309
https://rt.perl.org/Public/Bug/Display.html?id=127049

**Comment by lizmat** [comment]
This is fixed afaik, please re-open should this not be the case
