### ISSUE TITLE
Should a punned role A be an A

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2331]
role A { }; dd A.new.^isa(A); # 0

It feels to me that that should be `1` (aka true).

Or am I missing something?

Also, this causes inconsistent behaviour with `isa-ok`:

    use Test;
    role A { }
    isa-ok A.new, A;    # fails
    isa-ok A.new, "A";  # passes

**Comment by jnthn** [comment]
No. `isa` is testing inheritance, but roles are composed, not inherited.

**Comment by lizmat** [comment]
Then we should fix the `isa.ok A.new, "A"`, right?

**Comment by lizmat** [comment]
Fixed with 5f3579eb03

**Comment by lizmat** [comment]
tests added with https://github.com/perl6/roast/commit/d739ec7168
