### ISSUE TITLE
allow some formatting in pod declarator blocks

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2332]
## The Problem

Pod declarator blocks currently produce a single line of normalized text. Users would like to be able to make lists and other formatting as in other pod blocks.

## The Solution

A full solution would allow use of all pod constructs inside the declarator block.

**Comment by lizmat** [comment]
In the Raku grammar, all whitespace is preserved in the `RakuAST::Doc` objects that are created.  A renderer should be able to run with this.

So closing
