### ISSUE TITLE
JIT ERROR: Negative offset for dynamic label 8

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2340]
Code:
```perl6
say run <echo 0>.exitcode
```

Result:
```
JIT ERROR: Negative offset for dynamic label 8
No such method 'exitcode' for invocant of type 'List'
  in block <unit> at <tmp> line 1
```

The code is not right but it shouldn't fail with JIT ERROR.

Bisected: (2018-10-01) https://github.com/rakudo/rakudo/commit/acd8325cbcc3dcdfea742c9763744e8fe2de9aa7
version bump brought in these changes: https://github.com/perl6/nqp/compare/2018.09-10-gb33470c...2018.09-11-ga911a64
version bump brought in these changes: https://github.com/MoarVM/MoarVM/compare/2018.09-98-g67f85dc...2018.09-116-g80397b2

**Comment by AlexDaniel** [comment]
This was resolved. I don't know if we should test if there's no JIT ERROR.

**Comment by AlexDaniel** [comment]
Maybe `is_run` should always try to match “JIT ERROR” string? This way it will be tested everywhere by default…

**Comment by lizmat** [comment]
closing as untestable
