### ISSUE TITLE
Apparent failure in 6.d language switching mechanism on 32-bit boxes

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2343]
> dogbert17 | ZOFFLOP: t/spec/MISC/misc-6.d.rakudo.moar - ===SORRY!=== An exception occurred while evaluating a constant at /home/dogbert/repos/rakudo/t/spec/MISC/misc-6.d.rakudo.moar:123 - You cannot create an instance of this type (Int:D)

> it happens on my 32 bit Linux VM running 'Rakudo version 2018.09-72-g687a3cbb0 built on MoarVM version 2018.09-123-g0191bd9cf

> if I get it during spectest I will also get it *the first time I run* it separately i.e. './perl6  t/spec/MISC/misc-6.d.rakudo.moar'

The message in the error should occur only in 6.c language, which suggests this failure is a problem with 6.d switching mechanism. I ran that test file in a loop for half an hour on 64-bit Linux and had no failures.

**Comment by dogbert17** [comment]
Here's what the output looks like when it fails:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6  t/spec/MISC/misc-6.d.rakudo.moar
    ===SORRY!=== Error while compiling /home/dogbert/repos/rakudo/t/spec/MISC/misc-6.d.rakudo.moar
    An exception occurred while evaluating a constant
    at /home/dogbert/repos/rakudo/t/spec/MISC/misc-6.d.rakudo.moar:123
    Exception details:
      ===SORRY!=== Error while compiling 
      You cannot create an instance of this type (Int:D)
      at :

**Comment by zoffixznet** [comment]
Ran in a loop for 15 minutes on my 32-bit Debian, but could not reproduce.

**Comment by dogbert17** [comment]
Neither can I using version 2018.10-53-g8e858c8d0 built on MoarVM version 2018.10-26-g318e1ec55

**Comment by zoffixznet** [comment]
great :)
