### ISSUE TITLE
Post-2018.09 module install failures

### ISSUE THREAD

**Issue by japhb** [rakudo/rakudo#2345]
(Submitting as per [discussion with AlexDaniel](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-08#l16); full thread [starts here](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-07#l405).)

**TL;DR:** I haven't been able to build Rakudo and my usual modules with any rev I've tried post-2018.09.

**Background:** Every couple days, I fully rebuild my default (in `PATH`) Rakudo environment with a large script that starts from clean repo clones and rebuilds Moar, NQP, and Rakudo from scratch, followed by installing zef from its own clean repo clone and using it to install a set of standard modules.  Normally this works pretty well, with occasional Rakudo revs that won't install every module, but otherwise fine.

However, post-2018.09 (the release itself works fine for me), I've not had a successful build of Rakudo plus all my standard modules.  Here's the list of standard zef installs I run:

    # Must be installed first
    zef --/tap-harness --/cached install System::Query Distribution::Builder::MakeFromJSON || exit 8

    # Known to fail tests while working anyway
    zef --/tap-harness --/cached --/test install IO::Socket::Async::SSL || exit 8

    # Regular set
    zef --/tap-harness --/cached install URI File::Temp Terminal::ANSIColor Term::termios Debugger::UI::CommandLine JSON::Tiny DBIish Linenoise Inline::Perl5 IRC::Client OO::Monitors Grammar::Debugger Test::Mock App::Mi6 cro || exit 8

Notes:

- There are a couple more I build from local repos, but I always do those last, and they haven't had any problems if the ones above are successful.
- The `|| exit 8` bits are simply the script's way of signaling that build failure occurred during module installs, as opposed to earlier in the build sequence.

At each Rakudo rev I've tried after 2018.09, one of these modules (or their dependencies) have failed to install, but the actual failing module changes from rev to rev.  Note that I've tried less than a dozen different post-release Rakudo revs, so I could just be getting very unlucky.  Still, this seems much worse than the usual frequency that I get failures.

**Comment by zoffixznet** [comment]
FWIW, I reproduced `IO::Path::ChildSecure` failure on `2018.09-371-g8bb34ff07 built on MoarVM version 2018.09-124-g588873f7a`. It says "expected `Match`", but there's not even a mention of `Match` anywhere in module's code.

```
$ perl6 --ll-exception t/01-operation.t 
1..10
IO::Path.new("/tmp/perl6_roast_01_operation_t_line1_0_3496814481061191538959884", :SPEC(IO::Spec::Unix), :CWD("/"))
Type check failed for return value; expected Match but got IO::Path (IO::Path.new("/tmp/perl6_roas...)
```

**Comment by AlexDaniel** [comment]
FWIW the only regressed module that I know of from that discussion is IO::Path::ChildSecure. My tool says that it became uninstallable since https://github.com/rakudo/rakudo/commit/3b453c575de14efd3abfa4f49c82a059ddccc3cd, but right now I'm not entirely sure if this info is trustworthy.

**Comment by zoffixznet** [comment]
Golfed `IO::Path::ChildSecure` failure to this:

```
$ echo '$ = IO::Path:D' > Foo.pm6
$ perl6 -I. -MFoo -e '-> --> IO::Path:D {".".IO}()'
Type check failed for return value; expected Block but got IO::Path (IO::Path.new(".", :SPEC(IO::S...)
  in block <unit> at -e line 1
```

Use of a `:D` coercer in a module makes the main script blow up with that weird type check error.

**Comment by zoffixznet** [comment]
I'm getting an `Associative`  in the error message from https://github.com/zoffixznet/z now:

```
$ z f
Type check failed in assignment to $!conf; expected Associative but got IO::Path (IO::Path.new("/home/zoffix/zs...)
  in block <unit> at /home/zoffix/zscript/bin/z line 9
```

**Comment by japhb** [comment]
I wrote a script to attempt full Rakudo builds/module installs at all revs on the main line of Rakudo development, and ran it overnight.  Discussion and summary of results in [today's perl6-dev irclog](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-08#l672).

**Comment by jnthn** [comment]
Also:

```
$ perl6 -I. -MFoo -e 'dd IO::Path:D'
-> gnatur { #`(Block|208098776) ... }
```

Shows the problem even more directly. Curiously, this is OK:

```
$ perl6 -I. -MFoo -e 'dd Metamodel::DefiniteHOW.new_type(base_type => IO::Path, :definite)'
IO::Path:D
```

And even more oddly, if I do `--target=ast` then I see:

```
                  - QAST::Op(call &dd) <sunk> :statement_id<1> dd IO::Path:D
                    - QAST::WVal(IO::Path:D) <wanted> IO::Path:D
```

Which is also looking sensible, and it looks the same in `--target=optimize`. So quite how we end up with the WVal looking up something different at runtime, I've no idea. In fact, I've no idea what `gnatur` is, except part of the word `Signature`, which is even more odd.

**Comment by jnthn** [comment]
It's also a totally bogus block.

```
jnthn@jnthn-praha:~/dev/rakudo$ perl6 -I. -MFoo -e 'dd IO::Path:D.file'
getcodelocation needs an object of MVMCode REPR, got P6opaque instead
  in block <unit> at -e line 1

jnthn@jnthn-praha:~/dev/rakudo$ perl6 -I. -MFoo -e 'dd IO::Path:D.line'
getcodelocation needs an object of MVMCode REPR, got P6opaque instead
  in block <unit> at -e line 1

jnthn@jnthn-praha:~/dev/rakudo$ perl6 -I. -MFoo -e 'dd IO::Path:D.()'
Segmentation fault (core dumped)
```

**Comment by AlexDaniel** [comment]
@jnthn any news on this one? Or any thoughts on what can be done here?

**Comment by jnthn** [comment]
I've been too busy to look at it since I last posted. However, seems I have some time now so I'll try and hunt it a bit further.

**Comment by jnthn** [comment]
Oh, and as for thoughts on what can be done: none really. It's utterly confusing.

**Comment by jnthn** [comment]
It seems that reverting ab3d0566757f9fb8 makes it go away. That narrows things down a bit.

**Comment by jnthn** [comment]
Finally hunted it down and applied a fix in MoarVM. The change in 4b60df8 exposed a long-standing issue that we'd not tripped over - at least not in this way - before. It was about interning of parametric things across compilation units. It's possible, though not certain, that we might find this also fixes some other parametric role related issue.

**Comment by jmaslak** [comment]
I've confirmed this fix solved my issue.
