### ISSUE TITLE
JIT ERROR: Negative offset for dynamic label 33

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#2346]
## The Problem

I'm converting a list of strings to objects. Within the first 50-odd entries, I will get up to 4 STDERR messages saying `JIT ERROR: Negative offset for dynamic label 33`

## Steps to Reproduce

The issue occurs when using my module [`Net::Netmask`](https://github.com/0racle/p6-Net-Netmask/).

```perl-6
use Net::Netmask;

sub random-subnet() {
    (^256 xx 4)».pick.join('.')
    ~ (((True) => 10, (False) => 1).Bag.pick ?? "/{(16..32).pick}" !! '') 
}

for ( random-subnet() xx Inf ).head(30) -> $line {
    say Net::Netmask.new($line)
}
```

  > NOTE: I'm actually using a file (`for 'subnets'.IO.lines -> $line`) but the above also reproduces it.

OUTPUT:

```
Net::Netmask.new("230.18.225.192/27")
Net::Netmask.new("31.194.88.128/25")
Net::Netmask.new("160.157.128.0/20")
JIT ERROR: Negative offset for dynamic label 33
JIT ERROR: Negative offset for dynamic label 33
Net::Netmask.new("169.242.9.200/30")
Net::Netmask.new("93.113.165.92/31")
Net::Netmask.new("14.29.160.0/19")
Net::Netmask.new("22.216.79.52/32")
Net::Netmask.new("238.179.128.0/22")
Net::Netmask.new("162.141.112.0/23")
Net::Netmask.new("250.107.32.240/30")
Net::Netmask.new("150.86.128.0/20")
Net::Netmask.new("109.33.208.175/32")
Net::Netmask.new("93.161.8.14/32")
Net::Netmask.new("107.198.243.182/31")
Net::Netmask.new("111.62.89.224/29")
Net::Netmask.new("102.157.159.248/29")
Net::Netmask.new("240.123.173.128/26")
Net::Netmask.new("101.164.176.0/22")
Net::Netmask.new("192.149.130.0/27")
Net::Netmask.new("211.119.99.224/31")
Net::Netmask.new("2.181.32.0/19")
Net::Netmask.new("110.253.192.0/19")
Net::Netmask.new("43.8.223.64/26")
Net::Netmask.new("147.111.156.225/32")
Net::Netmask.new("105.17.177.212/31")
JIT ERROR: Negative offset for dynamic label 33
JIT ERROR: Negative offset for dynamic label 33
Net::Netmask.new("233.6.115.96/27")
Net::Netmask.new("252.203.0.0/19")
Net::Netmask.new("18.32.0.0/16")
Net::Netmask.new("48.118.80.0/20")
Net::Netmask.new("249.41.55.138/32")
```

I will golf down the cause, but potential avenues for investigation I suspect would center on what happens inside `Net::Netmask.new`. The `new` method is a multi which accepts various named or positional arguments with `where` clauses. Additionally there is a `BUILD` submethod.

## Environment
I'm running an older distro that has old versions of glibc, gcc, and other build tools. Previously bug's I have encountered are not able to be reproduces on more modern distro's, so this may also be a factor.

* Operating system: 
CentOS release 6.9 (Final)
Linux spawn 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.09-371-g8bb34ff built on MoarVM version 2018.09-124-g588873f
implementing Perl 6.c.

**Comment by 0racle** [comment]
FWIW, I only wrote this script yesterday. Previously I hadn't tried creating large amounts of Net::Netmask objects... which is to say... I don't know if a recent commit caused this, or it's been lying dormant for longer.

Also, I tried rebuilding MoarVM, NQP, and Rakudo all from HEAD using Developer Toolset 2 (which provides later versions of build tools like gcc) and the issue is still present, so this mostly rules out an issue with old gcc.

**Comment by 0racle** [comment]
When creating an `Net::Netmask` object from CIDR notation (aka "slash notation") I have to convert the bits to a subnet mask, which is done with this function

    sub dec2ip(\d where { 0 <= $_ < 2**32 or die 'not in IPv4 range 0-4294967295'} --> IPv4) is export {
        ( (d +> 0x18, d +> 0x10, d +> 0x08, d) »%» 0x100 ).join('.');
    }

When I removing the return type from the signature, I stop getting the JIT ERROR. I also stop getting the error when I change the return type to simply `Str`.

The `IPv4` is a custom subset defined as follows

    our token octet   { (\d+) <?{ $0 <= 255 }>  }
    our regex address { <octet> ** 4 % '.'      }
    our subset IPv4 of Str where / ^ <address> $ /;

So it seems so far that the JIT ERROR occurs during validation of the return type against a custom subset... possibly also related to the Regex engine.

**Comment by 0racle** [comment]
Issue seems to be somewhere in the `octet` token.

Currently I'm just testing the `dec2ip` function (which is exported from `Net::Netmask`) as follows

```perl-6
use Net::Netmask;
for (16..32).roll(50) -> $bits {
    say dec2ip((2 ** $bits - 1) +< (32 - $bits))
}
```

I have tried changing around the regex associated with the subset...

Changed the `address` to `{ <digit> ** 4 % '.' }`, no error.

Changed `octet` to `{ (\d+) }`, error occurred.

Changed `octet` to  `{ \d+ }`, no error.

Changed `octet` to `{ (\d+) }`, error occurred (except it was label 32)

Changed `octet` to `{ \d+ <?{ $/ <= 255 }> }`, error occurred

**Comment by 0racle** [comment]
Here is a minimal golf that doesn't rely on any module to be installed.

```perl-6
my token octet   { (\d+) <?{ $0 <= 255 }>  }
my regex address { <octet> ** 4 % '.'      }
my subset IPv4 of Str where / ^ <address> $ /;

sub dec-to-ip(\d --> IPv4) {
    join('.', d +> 0x18 % 0x100, d +> 0x10 % 0x100, d +> 0x08 % 0x100, d % 0x100)
}

for (16..32).roll(50) -> $bits {
    say dec-to-ip((2 ** $bits - 1) +< (32 - $bits))
}
```

**Comment by 0racle** [comment]
I've updated the golf above to reflect a more recent golf.

Given the above code, if I change `octet` to just `{ \d }` (ie. no capture) or get rid of `octet` and change `address` to `{ (\d+) ** 4 % '.' }' then I do not get any JIT ERROR.

That seems to suggests it's something to do with one or all of
  * using a capture in a sub-pattern
  * in a subset where clause
  * as a return type

**Comment by bdw** [comment]
Very probably nothing to be concerned about, since this error message was already happening before I added a recent change to make it more noisy.
I kind of want to keep it noisy because it's been very helpful in uncovering latent issues.
But evidence suggests that we usually get away with it.

I found that I cannot easily remove all of them without introducing a signfiicant pessimisation, though.
So please let me know what you want.

**Comment by AlexDaniel** [comment]
> since this error message was already happening before I added a recent change to make it more noisy

What do you mean? I see no error message on 2018.09.


> I kind of want to keep it noisy because it's been very helpful in uncovering latent issues.
But evidence suggests that we usually get away with it.

I'm not sure yet, but I think it'd be better to turn it off for the release and re-enable it shortly after. Otherwise users will have to look at pessimistic error messages for 3 months. :)

**Comment by jnthn** [comment]
> What do you mean? I see no error message on 2018.09.

I believe it was going into a log file before that was only ever written if a particular environment variable was set.

> But evidence suggests that we usually get away with it.

Usually, yes, though as I understand it, the consequences of us *not* getting away with it could include a mis-deopt or an incorrect dynvar resolution? Or is it only happening with labels that are likely not to mark out inline boundaries?

> I found that I cannot easily remove all of them without introducing a signfiicant pessimisation, though.
So please let me know what you want.

Well, as usual, we all want fast until it breaks our program, and then we want slower but correct... :-)

**Comment by bdw** [comment]
Understood, so I've decided to a): silence this error unless `MVM_JIT_DEBUG` is on, and b): bail out if we find that it happens
