### ISSUE TITLE
JIT ERROR: Negative offset for dynamic label 32

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2347]
This issue was discussed on #perl6-dev but I believe no ticket was filed.

Code:
```perl6
my $a = ('a' x 200).comb; $a ~~ s:g/<ws>//
```
Output:
```
JIT ERROR: Negative offset for dynamic label 32
```

**Comment by bdw** [comment]
Decently sure I fixed this one.

**Comment by AlexDaniel** [comment]
When?
> \<AlexDaniel\> m: my $a = ('a' x 200).comb; $a ~~ s:g/<ws>//
> \<camelia\> rakudo-moar b781479ea: OUTPUT: «JIT ERROR: Negative offset for dynamic label 32␤»

**Comment by lizmat** [comment]
On HEAD I get:

$ 6 'my $a = ("a" x 200).comb; $a ~~ s:g///'
===SORRY!=== Error while compiling -e
Null regex not allowed
at -e:1
------> my $a = ("a" x 200).comb; $a ~~ s:g/⏏//

**Comment by zoffixznet** [comment]
> On HEAD I get:

A crucial piece of code got swallowed by Markdown markup in the ticket. There's a `<ws>` token inside the regex:

`my $a = ('a' x 200).comb; $a ~~ s:g/<ws>//`

**Comment by lizmat** [comment]
I needed to run the code *with* the <ws> about 5 times, but then I got:

$ 6 'my $a = ("a" x 200).comb; $a ~~ s:g/<ws>//'
JIT ERROR: Negative offset for dynamic label 32

So this one is definitily *NOT* fixed yet.

**Comment by bdw** [comment]
You are correct, I was working on a different branch where I have fixed those errors. They are not on master, because they pessimize the compilation of nativeinvoke.
I've decided to silence them for now and bail out of JIT compilation if it happens.
