### ISSUE TITLE
Implementation of shaped array elems mismatches roast test

### ISSUE THREAD

**Issue by SyrupThinker** [rakudo/rakudo#2351]
https://github.com/perl6/roast/blob/f11042b93790302a3c1d792168546bd66b0204bb/S02-types/multi_dimensional_array.t#L31

## The Problem
IRC: http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-08#l404
The question is if the test still defines the inteded behaviour.
 
## Expected Behavior
The elems method returns the product of the dimensions.

## Actual Behavior
The elems method returns the first dimension of the Array.

## Steps to Reproduce
`my @a[3;4]; say @a.elems; # RESULT: 3`

## Environment
* Operating system: Gentoo Linux
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.09-374-ga2e78ec8e built on MoarVM version 2018.09-124-g588873f7a
implementing Perl 6.c.

**Comment by SyrupThinker** [comment]
[IRC Discussion](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-08#l472)

As this seems to be the intended behaviour the test needs to be updated.

**Comment by SyrupThinker** [comment]
I guess this can be closed because the tests have been adapted?

**Comment by lizmat** [comment]
I think so?
