### ISSUE TITLE
JS backend doesn't build

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#2353]
## The Problem

Can't build JS backend on rakudo master.

## Expected Behavior

```
$ perl Configure.pl --gen-nqp --gen-moar --backends=moar,js
# ... configure JS backend (building moar & nqp)
```

## Actual Behavior

Dies with two issues:

```
/Users/coke/sandbox/rakudo/nqp/src/vm/js/nqp-runtime/reprs.js:1603
  if (n < -(2n**63n) || 2n**63n <= n) {
            ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
```
and

```
Cleaning up ...
make: *** No rule to make target `js-clean', needed by `clean'.  Stop.
```

## Environment
* Operating system: Mac OS X 10.13.6
* Compiler version (`perl6 -v`): `605bcb391`

**Comment by vendethiel** [comment]
What’s your nodejs version?

**Comment by coke** [comment]
```
$ node --version
v8.11.3
```

After the fact, I looked for a version requirement, found one in NQP that is back at 7.10.0

**Comment by jstuder-gh** [comment]
The ```n``` postfixes in that expression indicate that the the value isn't a ```Number``` but a ```BigInt``` (not multiplication by scalar as it looks like; a bit confusing imo). According to [this table](https://node.green/#ESNEXT-candidate--stage-3--BigInt), it looks like you need at least Node v10.8.0.

**Comment by pmurias** [comment]
It's a too old node.js without BigInt support. I'll add a feature check to
Configure for that.

**Comment by coke** [comment]
Upgraded to v10.11.0, much better, thanks.
