### ISSUE TITLE
say ᱁𑛂೩᮴୫᱆᥍𑇘᱙꘠ eq 1234567890    # True

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2358]
Being able to use all characters with the `Nd` Unicode property in a number is nice.  But it can be abused.

I would therefore propose that literal numbers should always be of the same script (perhaps while disregarding `.`) and create a compilation error if they are not.  The above string would then most definitely be a compilation error:

    dd "᱁𑛂೩᮴୫᱆᥍𑇘᱙꘠".NFD>>.uniprop("Script")'
    ("Lepcha", "Takri", "Kannada", "Sundanese", "Oriya", "Lepcha", "Limbu", "Sharada", "Ol_Chiki", "Vai")

A good place would probably be as a post-condition of the `numish` token.

**Comment by AlexDaniel** [comment]
Removing `detrap` label. It is meant for issues when the user writes something thinking that it will do X but instead it does Y (often silently). Here the choice to use weird characters is deliberate.

I think it would be nice to define the problem for this ticket. Yes, it is possible to do weird stuff using this feature, but so what? Many features can be abused, what's especially bad with this one?

**Comment by zoffixznet** [comment]
> Yes, it is possible to do weird stuff using this feature, but so what? Many features can be abused, what's especially bad with this one?

:+1: to that comment, especially considering the current possibility of [invisible operators](https://perl6.party/post/Anguish--Invisible-Programming-Language-and-Invisible-Data-Theft).

**Comment by lizmat** [comment]
FWIW, I mentioned this one because it is:

- easily contained and most likely easy to implement without performance issues
- unlikely to happen in real life: people will most likely use numbers in the script they're familiar with
- so if it happens, it is an attempt at obfuscation in the best case, and in the worst case?

**Comment by lizmat** [comment]
@zoffixznet Re invisible operators: do we have a ticket for that?

**Comment by zoffixznet** [comment]
>  do we have a ticket for that?

[RT#128159](https://rt.perl.org/Public/Bug/Display.html?id=128159#ticket-history)

**Comment by AlexDaniel** [comment]
> and in the worst case?

I'm interested to know what is the worst case.

**Comment by lizmat** [comment]
Someone will think of one.  But apparently there are worse cases to tackle.

**Comment by jonathanstowe** [comment]
The only thing I can think of is that an application developer may, for perfectly sensible reasons of their own, want to only allow digits of a single script in user input.  In that case they would need to process the input as a string until after they have done the check, this may or may not be FAQ-worthy :-)
