### ISSUE TITLE
LTA parsing in coloned method calls

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2368]
If you forgot to add a space after the colon, usually you'd get a parse error:

```
<Zoffix_> m: my $n = 3; say ^10 .head:1
<camelia> rakudo-moar 8e4d17a79: OUTPUT: «===SORRY!=== Error while compiling <tmp>␤Confused␤at <tmp>:1␤------> my $n = 3; say ^10 .head:⏏1␤    expecting any of:␤        colon pair␤»
```

However, if you are giving a variable as an argument and accidentally leave a space, you'll get a portentially-hard-to-spot bug in your code:

```
<Zoffix_> m: my $n = 3; say ^10 .head: $n
<camelia> rakudo-moar 8e4d17a79: OUTPUT: «(0 1 2)␤»
<Zoffix_> m: my $n = 3; say ^10 .head:$n
<camelia> rakudo-moar 8e4d17a79: OUTPUT: «0␤»
```

**Comment by lizmat** [comment]
If `.head` would not have `*%_` in its signature, `.head:$n` would be a dispatch error.

**Comment by lizmat** [comment]
Closing in favour of the problem solving issue
