### ISSUE TITLE
Unwanted/incorrect declarator blocks in Pod

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2369]
The [user wanted](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-10-14#l40) to have annotated `sub MAIN` args for good `USAGE` output as well as some Pod in the program. The problem is the Pod of the annotated args shows up in the main pod:

```perl6
#! /usr/bin/env perl6

=begin pod

some test pod documentation

=end pod

sub MAIN(
          $arg1, #= nice description of arg 1
          #|(and for arg2)
          $arg2 ) {
    ...
}
```

```bash
2018.09 zoffix@VirtualBox~/R/rakudo (master)$ ./perl6 ../z.p6 
Usage:
  ../z.p6 <arg1> <arg2>
  
    <arg1>    nice description of arg 1
    <arg2>    and for arg2
2018.09 zoffix@VirtualBox~/R/rakudo (master)$ ./perl6 --doc=Text ../z.p6 
some test pod documentation

class Mu $
nice description of arg 1

class $arg2
and for arg2
2018.09 zoffix@VirtualBox~/R/rakudo (master)$ ./perl6 -v
This is Rakudo version 2018.09-426-g8e4d17a79 built on MoarVM version 2018.09-124-g588873f7a
implementing Perl 6.c.
2018.09 zoffix@VirtualBox~/R/rakudo (master)$ 
```

Reading the speculations ( http://design.perl6.org/S26.html#Declarator_blocks ), those blocks are part of Pod and their rendering is implementation-dependent and can be affected by configuration. However, I'm not seeing any configuration handling options in the source (at least for Pod::To::Text) ( https://github.com/rakudo/rakudo/blob/master/lib/Pod/To/Text.pm6#L84-L109 ) so sounds like there's
currently no good way to hide them. I'm also noticing another bug with those in that they're reported as `class` rather than argument or something.

**Comment by lizmat** [comment]
Closing in light of https://github.com/Raku/problem-solving/issues/439
