### ISSUE TITLE
Modifying a class can lead to it being unloadable

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#2378]
## The Problem

Loading a class that dynamically sets itself up (using `$?CLASS.^add_method`) from another module does with an error. 

## Expected Behavior

The module loads cleanly, as it does when not loading from another module

## Actual Behavior

~~~~
===SORRY!===
STable conflict detected during deserialization.
(Probable attempt to load a mutated module or modules that cannot be loaded together).
~~~~

## Steps to Reproduce

`Foo.pm6`:
~~~~
unit class Foo;

$?CLASS.^add_method('foo', anon method foo() {} );
~~~~

`Bar.pm6`:
~~~~
unit class Bar;

use Foo;
~~~~

~~~~
$ perl6 -I. -MBar -e0
~~~~

## Environment
~~~~
This is Rakudo version 2018.09 built on MoarVM version 2018.09
~~~~

**Comment by zoffixznet** [comment]
> ... attempt to load a mutated module ...

Not an expert on this, but it's possible that it's not meant to work (or NYI).

If you add that method during compile time, then it works fine:

```perl6
BEGIN $?CLASS.^add_method('foo', anon method foo() {} );
```

Bisecting this shows this behaviour existed since The Christmas.

**Comment by Leont** [comment]
> Not an expert on this, but it's possible that it's not meant to work (or NYI).

Probably, though adding `BEGIN` blocks turns out to be problematic in my case, probably because of another bug.

**Comment by coke** [comment]
Given that the BEGIN fixes the original issue, do we need to keep this open for the potentially LTA "STable" warning?
