### ISSUE TITLE
Loop variable in BEGIN block becomes a VMNull

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#2379]
## The Problem

This code:
~~~~
unit class Foo;

BEGIN {
    my $foo = 1;
    { $?CLASS.^add_method('foo', anon method () { dd $foo } ) }
} 
~~~~

when run as

~~~~
perl6 -I. -Mfoo -e'Foo.new.foo'
~~~~

fails with
~~~~
Cannot invoke this object (REPR: Null; VMNull)
  in sub  at /home/leont/Code/6pan/TestCase/lib/Foo.pm6 (Foo) line 4
  in method <anon> at /home/leont/Code/6pan/TestCase/lib/Foo.pm6 (Foo) line 5
  in block <unit> at -e line 1
~~~~

unless one adds `no precomplication` to the class.

## Environment
This is Rakudo version 2018.09 built on MoarVM version 2018.09

**Comment by Leont** [comment]
Some more investigation indicates it's not the loop per se that's essential in triggering this, but it needs a scope below the main BEGIN one

**Comment by zoffixznet** [comment]
> but it needs a scope below the main BEGIN one

Doesn't look like even that is necessary. Just a core routine call inside the added method:


```perl6
# Foo.pm6
unit class Foo;
BEGIN { $?CLASS.^add_method: 'foo', { join } }

# script.p6
use lib '..';
use Foo;
Foo.foo;

# OUTPUT: Cannot invoke this object (REPR: Null; VMNull)
```

And it happens only for core routine calls, not ones you define inside `BEGIN`.

And if you define a routine outside the begin and try to use it, you get a different error:

```perl6
# Foo.pm6
unit class Foo;
sub join {}
BEGIN { $?CLASS.^add_method: 'foo', { join } }

# script.p6
use lib '..';
use Foo;
Foo.foo;

# OUTPUT: getlex: outer index out of range
```

**Comment by zoffixznet** [comment]
Found what could possibly be a workaround you could use: assign a sub you want to use to another symbol inside `BEGIN` and then use that symbol inside the code of the method:

```
unit class Foo;
BEGIN { my &sym2 = &dd; $?CLASS.^add_method: 'foo', { sym2 42 } }
```

**Comment by Leont** [comment]
> Found what could possibly be a workaround you could use: assign a sub you want to use to another symbol inside BEGIN and then use that symbol inside the code of the method:

That only work because &dd doesn't have to be kept alive. This for example will fail:

~~~~
BEGIN { my &sym2 = sub ($arg) { dd $arg }; $?CLASS.^add_method: 'foo', { sym2 42 } }
~~~~

**Comment by zoffixznet** [comment]
Yeah, I guess it's fairly limited; you have to extract `&dd` into that scope as well:

```perl6
unit class Foo;
BEGIN {
    my &dd2 = &dd; my &sym2 = sub ($arg) { dd2 $arg };
    $?CLASS.^add_method: 'foo', { sym2 42 } }
```

**Comment by niner** [comment]
This would probably be the place to start looking at: https://github.com/rakudo/rakudo/blob/master/src/Perl6/World.nqp#L2636
is_nested in that context means "BEGIN time EVAL"

**Comment by Leont** [comment]
> Yeah, I guess it's fairly limited; you have to extract &dd into that scope as well:

That isn't going to help in my use-case, where I need to do this over many values.

**Comment by Leont** [comment]
> This would probably be the place to start looking at: https://github.com/rakudo/rakudo/blob/master/src/Perl6/World.nqp#L2636
> is_nested in that context means "BEGIN time EVAL"

That does indeed look like it deals with the outermost BEGIN scope and not further. Not that I'd know how to fix that.

**Comment by lizmat** [comment]
FWIW, a similar issue exists with:

    use nqp;
    BEGIN my $h := nqp::hash("a",42);

**Comment by vrurg** [comment]
Tested on 2019.07.1 – fails. `HEAD` passes.

Closing via MoarVM/MoarVM#1209 and 7e3d023b4b070ed798915336a98f2bbc7fbac2e7
