### ISSUE TITLE
LTA role multi method stubs enforce arguments but not return value

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2385]
```
19:09 | ryn1x | m: role Foo { multi method bar(Str --> Str) { … } }; class Bar does Foo { multi method bar(Str $a --> Int) { return 1} }
19:09 | camelia | rakudo-moar 4bf55b1ef: ( no output )
```

(related ticket: https://github.com/rakudo/rakudo/issues/2384 )

**Comment by FCO** [comment]
It looks that it happens because it uses `eqv` to compare both signatures, but `eqv` do not compare the return.

http://colabti.org/irclogger/irclogger_log/perl6?date=2018-10-20#l332

**Comment by FCO** [comment]
Here is were the signatures are being tested: https://github.com/rakudo/rakudo/blob/de4e82259be36ac9c97b56d594591ea796a1b131/src/core/Signature.pm6#L207

**Comment by FCO** [comment]
Should `eqv` use the return to compare signatures or shouldn’t the comparison of multi stub with multi method use `eqv`?

**Comment by zoffixznet** [comment]
> Should eqv use the return to compare signatures or shouldn’t the comparison of multi stub with multi method use eqv?

Not an expert on this, but to me it'd make sense for `eqv` to check return as well.

**Comment by FCO** [comment]
Fixed, test needed
