### ISSUE TITLE
Two modules failing after “Refactor the use of STORE(:initialize)”

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2398]
These two modules used to work on 2018.09 but currently don't pass their tests. Bisected to the same commit.

[Hash::Restricted](https://modules.perl6.org/dist/Hash::Restricted:cpan:ELIZABETH) – Fail, Bisected: 00cb3315c5c90b9f74d737aad560b909372ae69c
[Tuple](https://modules.perl6.org/dist/Tuple:cpan:ELIZABETH) – Fail, Bisected: 00cb3315c5c90b9f74d737aad560b909372ae69c

No golf yet, but these modules don't have any dependencies so golfing is probably a low-hanging fruit.

**Comment by zoffixznet** [comment]
Not a Rakudo Issue. 

Filed PRs:
https://github.com/lizmat/Hash-Restricted/pull/1
https://github.com/lizmat/Tuple/pull/1
