### ISSUE TITLE
Unicode::GCB failing tests after “Bump NQP to get unicode 11”

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2399]
[Unicode::GCB](https://modules.perl6.org/dist/Unicode::GCB:github:N'A) – Fail, Bisected: acd8325cbcc3dcdfea742c9763744e8fe2de9aa7

This is likely not a bug in rakudo, but it should be investigated and a PR to the module should be sent.

```
===> Testing: Unicode::GCB:ver<0.2.1>:auth<github:cygx>
# Failed test at t/01-sanity.t line 14
# Failed test at t/01-sanity.t line 15
# Looks like you failed 2 tests of 4
t/01-sanity.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests 

Test Summary Report
-------------------
t/01-sanity.t (Wstat: 512 Tests: 4 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
Files=1, Tests=4,  5 wallclock secs ( 0.03 usr  0.00 sys +  2.68 cusr  0.12 csys =  2.83 CPU)
Result: FAIL
```

**Comment by AlexDaniel** [comment]
Further discussion here: https://github.com/cygx/p6-unicode-gcb/issues/1

Keeping it open for a bit until it is resolved.

**Comment by cygx** [comment]
I'll look into it. As far as I'm concerned, I wouldn't *necessarily* consider this a blocker (the `use nqp` disclaimer applies).

However, this does raise the following question: How should incompatible changes to Unicode be handled in the future?

Should MoarVM ship with several versions of the unicode database, and have a mechanism for users to decide which one to use? Or do we accept that code relying on advanced unicode features might break occasionally, even when the Perl6 language version stays the same?

**Comment by AlexDaniel** [comment]
@cygx See https://github.com/rakudo/rakudo/issues/2031 for a very related issue.
