### ISSUE TITLE
Module Crane is failing tests on HEAD

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2400]
Crane used to install fine on 2018.09 but on HEAD it is failing some tests. My tool bisected it to the `js` branch merge but that info is totally not helpful.

[Crane](https://modules.perl6.org/dist/Crane:github:atweiden) – Fail, Bisected: a09536fd942dd48c969a092549693b1bfa9c4be5, …

```
===> Testing: Crane:ver<0.1.0>:auth<atweiden>
Type check failed for return value; expected Hash[Any:D,List:D] but got $(my Any:D %{List:D} ...
  in method flatten at /home/alex/.zef/store/crane.git/77270457082ff654f91ab13ad52e359ea6c68752/lib/Crane.pm6 (Crane) line 189
  in block <unit> at t/methods/flatten.t line 16

===> Testing [FAIL]: Crane:ver<0.1.0>:auth<atweiden>
Aborting due to test failure: Crane:ver<0.1.0>:auth<atweiden> (use --force-test to override)
```

**Comment by zoffixznet** [comment]
Golfed: 

```
$ cat Bar.pm6 
my $ = Hash[Any:D,List:D]

$ cat Foo.pm6 
use Bar;
our sub foo(--> Hash[Any:D,List:D]) { my Any:D %tree{List:D} }

$ perl6 -I. -MFoo -e 'dd foo'
Type check failed for return value; expected Hash[Any:D,List:D] but got $(my Any:D %{List:D})
  in sub foo at /tmp/tmp.GR21mJFoZH/Foo.pm6 (Foo) line 2
  in block <unit> at -e line 1
```

Which looks to be a brother of this bug: https://github.com/rakudo/rakudo/issues/2345#issuecomment-431033154

**Comment by zoffixznet** [comment]
Tests in https://github.com/perl6/roast/commit/6c0173886d6352561a609c951f595e78d9b2b292 (fudged by https://github.com/perl6/roast/commit/feb20336900348d8bde500f369395659f7a1bb0b )

**Comment by zoffixznet** [comment]
> Which looks to be a brother of this bug: #2345 (comment)

Although, reverting https://github.com/rakudo/rakudo/commit/4b60df8f84fdf2ed8f5eab1426247fbc649d062c helped #2345, but does not help this bug.

**Comment by zoffixznet** [comment]
> Golfed:

And turns out the golfed version was broken since at least 2016.01.

**Comment by jnthn** [comment]
Could well be related to parametric intern handling or some such. I'll not be able to look for a couple more days, but [this file](https://github.com/MoarVM/MoarVM/blob/master/src/6model/parametric.c) and [this bit of the deserialization handling](https://github.com/MoarVM/MoarVM/blob/master/src/6model/serialization.c#L3050) are probably reasonable places to poke in a bit of debug logging to see what's happening.

**Comment by zoffixznet** [comment]
Some more findings:

`:D` is not needed for the bug. Changing the type used to `Hash[Mu]` in all three places still has the bug. However, changing it to `Iterable[Mu]` avoids the bug. The same with `Array[Mu]` (has bug) vs. `Positional[Mu]` (no bug)

**Comment by zoffixznet** [comment]
Also, noticed this change in how the module crashes, which was effected by https://github.com/rakudo/rakudo/commit/fd5d5bdfb97930cfae1f9b2572d2ab6eea7ca92f

```

¦«fd5d5bd»:
1..2
Type check failed for return value; expected Hash[Any:D,List:D] but got $(my Any:D %{List:D} ...
  in method flatten at /home/bisectable/git/whateverable/sandbox/crane/lib/Crane.pm6 (Crane) line 189
  in block <unit> at EVAL_0 line 16
  in block <unit> at /tmp/AjV9cHx5Rb line 1

 «exit code = 1»
¦«fd5d5bdfb97930cfae1f9b2572d2ab6eea7ca92f~1»:
1..2
Type check failed in assignment to %tree; expected Crane::Add but got Int (1)
  in method flatten at /home/bisectable/git/whateverable/sandbox/crane/lib/Crane.pm6 (Crane) line 189
  in block <unit> at EVAL_0 line 16
  in block <unit> at /tmp/AjV9cHx5Rb line 1

«exit code = 1»
```

**Comment by zoffixznet** [comment]
More info. This is comparing golfed code that uses `Array[Mu]` (`A` case, broken) vs. `Positional[Mu]` (`P` case, working) as types.

When `resolve_param_interns` is called the [`reader->root.num_param_interns`](https://github.com/MoarVM/MoarVM/blob/8b4d58c7ab3a52de4cccbd3f062976d2115b64a5/src/6model/serialization.c#L3063) is 1, but in broken one it's 0, so that loop never runs and never finds anything.

--------------------------------

Just to repeat the code I'm running:

```bash
$ cat Bar.pm6 
my $a = Array[Mu];

$ cat Foo.pm6 
use Bar;
our sub foo(--> Array[Mu]) { Array[Mu] }

$ ./perl6 -I. -e 'use Foo; foo'
Type check failed for return value; expected Array[Mu] but got Array[Mu]
...
```

Yet changing that to `Positional[Mu]` does not crash:

```bash
$ cat Bar.pm6 
my $a = Positional[Mu];

$ cat Foo.pm6 
use Bar;
our sub foo(--> Positional[Mu]) { Positional[Mu] }

$ ./perl6 -I. -e 'use Foo; foo'
$
```

**Comment by jnthn** [comment]
Oddly enough, it seems it's not an interning bug, or at least not a very direct one. The two `Array[Mu]` come out as precisely the same object, and this patch:

```
diff --git a/src/vm/moar/spesh-plugins.nqp b/src/vm/moar/spesh-plugins.nqp
index 74ac15b..8d778bb 100644
--- a/src/vm/moar/spesh-plugins.nqp
+++ b/src/vm/moar/spesh-plugins.nqp
@@ -177,7 +177,7 @@ sub identity($obj) { $obj }
     }
     sub check_type($type, $orig_type) {
         -> $ret {
-            nqp::istype($ret, $type) || nqp::istype($ret, Nil)
+            $ret =:= $type || nqp::istype($ret, $type) || nqp::istype($ret, Nil)
                 ?? $ret
                 !! return_error($ret, $orig_type)
         }
```

Works around the issue. Next us is trying to work out why `nqp::istype` gives the wrong result here.

**Comment by zoffixznet** [comment]
Test unfudged and I verified Crane's tests now pass.
