### ISSUE TITLE
have a short form of Perl 6 option “—ll-exception”

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2407]
For one-fingered users, running Perl 6 (or NQP) with option “—ll-exception” is a lot of chars.

It would be nice to have a short form like “-d” (debug) or “-b” (backtrace).

**Comment by zoffixznet** [comment]
:-1: considering this option is largely used by core devs.

You can simply setup an alias for it: `alias pe='perl6 --ll-exception'

**Comment by lizmat** [comment]
Agree, that's not needed.  But it would be nice if all building actions while building / installing the settings, would do a `--ll-exception`.  That would be very helpful when trying to figure out where something went wrong in e.g. installing the core modules.

**Comment by tbrowder** [comment]
What about at least mentioning the “—ll-exception in the SORRY message text smewhere?

**Comment by tbrowder** [comment]
I’m happy to use an alias, so I’m okay with closing this. But I will say, as a very noob to p6, the —ll-exception was very useful to me, but long. Sometimes the error messages will be LTA, and the exception option necessary even for non-devs.

**Comment by zoffixznet** [comment]
I rather we don't add any options willy-nilly.

There are many options we're yet to implement and I rather we don't make our users read [a 17-page long document ](https://perldoc.perl.org/perlrun.html) to understand the options.

> What about at least mentioning the “—ll-exception” in the SORRY message text somewhere?

The error messages are text-dense as it is. Those advanced enough to make use of `--ll-exception` would've seen it in options long time ago. 

> as a very noob to p6

I think having 81 commits in the core of Perl 6 compiler automatically disqualifies you from that claim 😂 

> okay with closing this.

👍
