### ISSUE TITLE
Signatures does not shows Coercion types when gisted.

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#2416]
http://colabti.org/irclogger/irclogger_log/perl6?date=2018-10-23#l443

**Comment by lizmat** [comment]
Fixed with 0243275def , test needed.  Also, this seems to have broken tests in t/spec/S06-currying/positional.t , which seem to depend on the coerce_type not being shown.

**Comment by lizmat** [comment]
Added test with https://github.com/Raku/roast/commit/8498f84f1050cdc3893
