### ISSUE TITLE
Multies do not use Coercion types constraints to decide what candidate to call

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#2417]
http://colabti.org/irclogger/irclogger_log/perl6?date=2018-10-23#l443

**Comment by FCO** [comment]
@lizmat Isn't that a `Int` that would then be converted to `Str`?

**Comment by lizmat** [comment]
Yeah, I got it backwards.  :-(   Looks like a genuine bug or at least a massive misunderstanding

**Comment by vrurg** [comment]
I think the message is much better now:

```
⇒ raku -e 'multi a(Str(Int) $a) { say "$a from Int" }; multi a(Str $a) { say "$a from Str" }; multi a(Str(Cool) $a) { say "$a from Cool" }; a 1; a "2"; a 3.14'
1 from Int
Ambiguous call to 'a(Str)'; these signatures all match:
  (Str(Int) $a)
  (Str $a)
  (Str(Cool) $a)
  in block <unit> at -e line 1
```

Perhaps, we can close this?
