### ISSUE TITLE
Nil.ACCEPTS returns False and spec says it must be Nil

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2419]
Filing so it doesn't get forgotten:

There is a 6.c spec test that, going by its description, specs that `Nil.ACCEPTS(Any)` must return a `Nil`. However, that test used incorrect operator for the test and [was passing](https://github.com/perl6/roast/commit/ac1ad09150) for the wrong reason.

Corrected test shows Rakudo actually returns a `False` (or `True`, for `.ACCEPTS(Nil)`) there instead of a `Nil`. There's a comment in [rakudo's source](https://github.com/rakudo/rakudo/blob/18eed380b08b4e0a6c714fb4b400f5fae75cd432/src/core/Nil.pm6#L12) saying making that method return `Nil` causes a hang in spectest.

------

Fudged proptest in https://github.com/perl6/roast/blob/bd7bdb82d575a5a593700a1de088ee3597e0df6b/S02-types/nil.t#L29

**Comment by lizmat** [comment]
FWIW, changing `Nil.ACCEPTS` to just return `False` causes quite extensive spectest breakage

**Comment by lizmat** [comment]
This is roast behaviour, so can be closed
