### ISSUE TITLE
Some Callables can't do .cando

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2420]
Don't know if there's some valid reason for making only some `Callable`s have `.cando` method, but IMO it makes sense for it to be present on all of them, as then the code accepting a `Callable` they can call can just use that method for logic control without worrying that some of them won't have it.

```
$ perl6 -e 'my Callable \c = sub {}; say so c.cando: \()'
True

$ perl6 -e 'my Callable \c = -> {}; say so c.cando: \()'
No such method 'cando' for invocant of type 'Block'. Did you mean 'can'?
  in block <unit> at -e line 1

$ perl6 -e 'my Callable \c = *.self; say so c.cando: \()'
No such method 'cando' for invocant of type 'WhateverCode'. Did you mean 'can'?
  in block <unit> at -e line 1

$ perl6 -v
This is Rakudo version 2018.06-146-g1b3dd35 built on MoarVM version 2018.06-141-gcae4731
implementing Perl 6.c.
```

------------------------------------

Worth mentioning that we seem [to be slowly migrating methods to lower code objects](https://github.com/rakudo/rakudo/commit/6e8dc6f132758b15d03998a7d73244b5e5cc9232), similar [to drift to Any and Mu](https://github.com/rakudo/rakudo/issues/1575)

**Comment by lizmat** [comment]
Fixed with 45eeab7876

**Comment by lizmat** [comment]
Docs added with  https://github.com/perl6/doc/commit/7af9d67f04

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/86dc2d14e6

**Comment by lizmat** [comment]
I think this can be closed now.
