### ISSUE TITLE
Cannot decode a buffer of bytes if it was produced by utf8 encode

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2421]
I was playing with custom encodings and needed a `Blob` to practice-decode. Naturally, I reached for a string that I then called `.encode`. That produced a `utf8` type, indicating that not only it's a `Blob`, but one that can successfully be decoded to utf8.

However, the `utf8` type—despite [the protests of Prof. Liskov](https://en.wikipedia.org/wiki/Liskov_substitution_principle)—does not let you decode those bytes into anything but `utf8`:

https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-24#l181
```
14:39 | Zoffix | m: 'bark bark bark'.encode.decode('utf-c8').say
-- | -- | --
14:39 | camelia | rakudo-moar  74687ae5c: OUTPUT: «Can not decode a utf-8 buffer
                       as if it were utf-c8␤  in block <unit> at <tmp> line 1␤␤»
14:39 | Zoffix | Why not? It's just bytes.
14:40 | samcv | Zoffix: good question. i am not against letting people do that
```

IMO that constraint doesn't make any sense. It's just bytes. What does it care what I decode them into?

**Comment by lizmat** [comment]
FWIW, removing the check does not make any spectests fail.

Perhaps we should introduce a `:force` named parameter to force decoding even if it did not match?  To at least keep some backward (bug) compatibility ?

**Comment by jnthn** [comment]
The applicable bit of S02 reads:

> The utf8 type is derived from blob8, with the additional constraint that it may only contain validly encoded UTF-8. Likewise, utf16 is derived from blob16, and utf32 from blob32.

I guess the constraint came from reading a little too much into this: it doesn't actually say anything about what the thing can be decoded as.

If there's no spectests, then I think we can probably just quietly drop that check. I've tripped over it at least before, and can't remember ever being helped by it (nor seeing anyone be helped by it).

**Comment by lizmat** [comment]
Implemented with 790d4c7ae2 . Results:

    $ 6 'dd "bark bark bark".encode.decode("utf8-c8")'
    "bark bark bark"

    $ 6 'dd "bark bark bark".encode.decode("utf16le")'
    "慢歲戠牡⁫慢歲"

    $ 6 'dd "bark bark bark".encode.decode("utf16be")'
   "扡牫⁢慲欠扡牫"

Are those last two what we expected / want ?

**Comment by lizmat** [comment]
BTW, shouldn't we also need have classes for `utf16le` and `utf16be` ?

**Comment by dogbert17** [comment]
Tests added with https://github.com/perl6/roast/commit/ca8952031fa4c4a35fe8bb5208761cbd2bb59d77
