### ISSUE TITLE
Wrong Signature.ACCEPTS after add CALL-ME method in a Sub

### ISSUE THREAD

**Issue by atroxaper** [rakudo/rakudo#2430]
## The Problem

After I add a role with CALL-ME method into any Sub object the sub's signature does not ACCEPTS any capture. I found it when I .wrap the sub but it reproduced with any role with CALL-me method; 

## Expected Behavior

All manipulations with sub and capture have to work as before application the role.

## Steps to Reproduce
For example:
```
sub s(:$arg) {};
say %(:arg(3)) ~~ &s.signature; # True
say &s.^find_method('CALL-ME'); # (Mu)

&s does role r { submethod CALL-ME(|) {} };
say %(:arg(3)) ~~ &s.signature; # False
say &s.^find_method('CALL-ME'); # CALL-ME

# even .cando does't work
&s.cando(%(:arg(3)).Capture); # `Cannot invoke object with invocation handler in this context`
```

## Environment
* macOs, #perl6 channel evalbot
* `This is Rakudo version 2018.09-72-g687a3cbb0 built on MoarVM version 2018.09-123-g0191bd9cf`

**Comment by dogbert17** [comment]
I'm not entirely certain but it seems as if new-disp (dd2b274fd59) fixed this

**Comment by atroxaper** [comment]
Yes. Now the issue is gone. Tested on:
```
raku -v
Welcome to Rakudo™ v2021.10-133-g24333b112.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10-117-g7d58542da.
```

Close the issue then.
