### ISSUE TITLE
change PAST comment references to QAST in all source code

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2431]
Also change variables named ‘$past’ to ‘$qast’.

**Comment by zoffixznet** [comment]
Let's not make frivolous changes all over the source. It makes `git blame` more annoying to use and makes merges of branches harder.

[That already caused a lot of trouble just two days ago](https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-24#l214):

```

16:05 | nine | Oh the joy of fixing merge conflicts because of whitespace cleanup :/ 
https://github.com/perl6/nqp/commit/86362f5c3c211acc09bc0dbdb592d7d3f52637bf
16:06 | nine | For future reference: please just don't


16:41 | jnthn | Yeah, I was annoyed by that PR doing so called "code quality improvements", 
which mostly meant `final` clutter, whitespace changes, style changes that aren't better just 
different...I didn't see a single useful thing in there. Wish I'd not been distracted with other 
things and could have shot the PR down before it got merged :/
16:42 | jnthn | Maybe we need a tighter commit policy on NQP, as MoarVM and Rakudo have.
```

**Comment by jnthn** [comment]
Yeah, I'd say the comments are maybe OK as one doesn't care much for those in `blame`; for the `$past` -> `$qast` thing, let's just do it when we're touching bits of code using them anyway for other reasons.

**Comment by tbrowder** [comment]
Okay.

**Comment by lizmat** [comment]
None of the RakuAST code mentions "past" since https://github.com/rakudo/rakudo/commit/c9d03adff9

It looks like all other references to "past" are in the legacy grammar code, and that's going the way of the dodo anyway.  So closing this
