### ISSUE TITLE
Optimizer likely doesn't consider 6.d setting's symbols as core

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2432]
Probably doesn't matter much now, but filing so we don't forget.

At the time of this writing, `$*COMPILING_CORE_SETTING` was not set when we were compiling CORE.d setting. I needed it for the language version decision logic, so I turned it on for CORE.d too, but the Optimizer shouted at me with:

```
"Stage optimize   : Optimizer couldn't find Sub in SETTING"
```

And that's cause `$*COMPILING_CORE_SETTING` in World.nqp controls whether we use `!CORE_MARKER` or `!UNIT_MARKER` and Optimizer looks for the first `!CORE_MARKER` it finds.

So what I'm gonna do now is make `$*COMPILING_CORE_SETTING` take `1` for 6.c setting and `2` for 6.d setting, to get the flag I need and make World.nqp use `!CORE_MARKER` only when `$*COMPILING_CORE_SETTING` is `1`, but we probably need to teach optimizer to handle CORE.d well, so that it can fully optimize the things inside of it, instead of thinking those are custom user stuff.

**Comment by zoffixznet** [comment]
Looks like it affects Actions/Grammar as well

> So what I'm gonna do now is make $*COMPILING_CORE_SETTING take 1 for 6.c setting and 2 for 6.d setting, 

It was becoming too messy, so what I done is add another dynvar for my flag and then I passed `NULL.d` instead of just `NULL` for `--setting` flag when compiling `d` setting. This let me be able to set my flag, while still letting the "`NULL` path" be used used for other bits that relied on that: https://github.com/rakudo/rakudo/commit/4a6d910839

**Comment by vrurg** [comment]
Closing via #3040 and #3055
