### ISSUE TITLE
LTA div-by-zero error with two `num` vars and `infix:<%>`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2434]
Normally, we get a Failure:
```
<Zoffix__> m: my num $x = 5e0; dd  $x % 0e0
<camelia> rakudo-moar e7e91ecfb: OUTPUT: «Failure.new(exception => X::Numeric::DivideByZero.new(using => "\%", details => Any, numerator => 5e0), backtrace => Backtrace.new)␤»
```

But if we use two `num` vars, we get a Failure unboxing error:
```
<Zoffix__> m: my num $x = 5e0; my num $y = 0e0; dd  $x % $y
<camelia> rakudo-moar e7e91ecfb: OUTPUT: «This type cannot unbox to a native number: P6opaque, Failure␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by zoffixznet** [comment]
Fudged tests in https://github.com/perl6/roast/commit/1fae4fb4ac

**Comment by lizmat** [comment]
Added tests with https://github.com/Raku/roast/commit/e2d90988f9

**Comment by MasterDuke17** [comment]
What about the tests added in https://github.com/perl6/roast/commit/1fae4fb4ac ?Sent from my iPhoneOn Oct 7, 2024, at 3:09 PM, Elizabeth Mattijsen ***@***.***> wrote:﻿
Added tests with ***@***.***

**Comment by lizmat** [comment]
Thanks for the nudge!  Fixed with https://github.com/Raku/roast/commit/2795530cf3
