### ISSUE TITLE
Crash in 6.d with sunk start

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2436]
```
<Zoffix__> m: use v6.d.PREVIEW; for ^1000 { my $z = 42; start { $z.abs } }; sleep 1;
<camelia> rakudo-moar e7e91ecfb: OUTPUT: «No such method 'abs' for invocant of type 'Any'␤  in block  at <tmp> line 1␤␤»
```

Working on a fix ATM, but if releasing, just revert https://github.com/rakudo/rakudo/commit/6ee5f7577 instead of waiting for me.

**Comment by AlexDaniel** [comment]
This was reverted in https://github.com/rakudo/rakudo/commit/933f936a02.

Blocker label removed, but the ticket should probably stay so that we can come back to this later.
