### ISSUE TITLE
.native-descriptor for async sockets

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2437]
Even though @Kaiepi++ did some great job to get .native-descriptor stuff working, we had to revert it before the release.

Reverted in:
* Moar https://github.com/MoarVM/MoarVM/commit/b2e870c6ff
* NQP https://github.com/perl6/nqp/commit/16f0f458fa
* Rakudo https://github.com/rakudo/rakudo/commit/005f66670e

These commits can be rereverted after the release if https://github.com/MoarVM/MoarVM/issues/987 is resolved.

Ping @Kaiepi.

**Comment by zoffixznet** [comment]
There are also Spec https://github.com/perl6/roast/issues/490 ticket. Didn't see a Docs ticket, but the feature would need to be documented as well (with the Docs ticket opened, if the author of the code is unavailable to document it).

**Comment by Kaiepi** [comment]
I'm working on reimplementing it as we speak. Should hopefully be ready for a pullreq later today
