### ISSUE TITLE
What's the meaning of `my @a[;]`

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2441]
There's ~~a proptest https://github.com/perl6/roast/commit/1fbede86d~~ (moved to appendix https://github.com/perl6/roast/commit/8d864563cb) that the construct doesn't infini-loop, but I don't get what it's supposed to mean. Should it throw?

```
<Zoffix__> m: dd my @a[;];
<camelia> rakudo-moar 266af373d: OUTPUT: «Array element = []␤»

<Zoffix__> m: my @a[;]; dd @a[;]
<camelia> rakudo-moar 266af373d: OUTPUT: «Unable to call postcircumfix element[ Nil ] with a type object␤Indexing requires a defined object␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by lizmat** [comment]
This now dies with:
```
% raku -e 'dd my @a[;]'  
Ignoring [Nil] as shape specification, did you mean 'my Nil @foo' ?
```
which still could use some work in understandibility of the error message, but otherwise pretty much covers it I think, so closing
