### ISSUE TITLE
Captures in sub MAIN params don't capture named args

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2445]
You can use a Capture parameter to capture any number of positional params:
```
2018.09 zoffix@VirtualBox~$ perl6 -e '(my %*SUB-MAIN-OPTS = :named-anywhere); sub MAIN(*@args) { dd @args }' foo bar
Array element = ["foo", "bar"]
\("foo", "bar")
```

Yet, the same does not seem to apply to named arguments:
```
2018.09 zoffix@VirtualBox~$ perl6 -e '(my %*SUB-MAIN-OPTS = :named-anywhere); sub MAIN(|args) { dd args }' foo bar --foo
Usage:
  -e '...' <args> 
2018.09 zoffix@VirtualBox~$ perl6 -e '(my %*SUB-MAIN-OPTS = :named-anywhere); sub MAIN(|args) { dd args }' --foo foo bar
Usage:
  -e '...' <args> 
2018.09 zoffix@VirtualBox~$ 
```

**Comment by dogbert17** [comment]
Seems to work now:

    dogbert@dogbert-VirtualBox:~/repos/rakudo$ perl6 -v
    Welcome to Rakudo™ v2021.09-238-gec65ffc8d.
    Implementing the Raku™ programming language v6.d.
    Built on MoarVM version 2021.09-600-g6cdb0846c.
    dogbert@dogbert-VirtualBox:~/repos/rakudo$ perl6 -e '(my %*SUB-MAIN-OPTS = :named-anywhere); sub MAIN(|args) { dd args }' --foo foo bar
    \("foo", "bar", :foo(Bool::True))

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/42efdb75be
