### ISSUE TITLE
LTA Coercer return type coercers Nil

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2452]
Don't know what the behaviour should be here, but thought we should make a conscious decision on it:

Normally, `Nil` bypasses return typecheck. I believe this is what makes `Failure` mechanism work:

```
$ perl6 -e 'dd -> --> Str { Nil }()'
Nil

$ perl6 -e 'dd sub (--> Str) { fail "meows" }()'
Failure.new(exception => X::AdHoc.new(payload => "meows"), backtrace => Backtrace.new)
```

However, if you use a coercer, an attempt will be made to coerce that `Nil` to the type you requested. This works in a sort of haphazard way, in that you can:

1. Get your standard "no typecheck; return a Nil" behaviour, because `Nil` has `FALLBACK` defined, which returns a `Nil`, so you get that from coercion:

```
$ perl6 -e 'class A {}; class B { method A { A.new } }; dd -> --> A(B) { Nil }()'
Nil
```

2. Or you could get the type you asked for, but perhaps not the value that makes sense for your program. This is especially wonky with `Array`/`Hash`/`QuantHash`es, because the 1-el-list semantics kick in and give you an object with "stuff" in it.

```
$ perl6 -e 'dd -> --> Str(Date) { Nil }()'
Use of Nil in string context
  in block  at -e line 1
""
$ perl6 -e 'dd -> --> Set(Date) {  }()'
Set.new(Nil)
$ perl6 -e 'dd -> --> Array(Date) {  }()'
[Any]
$ perl6 -e 'dd -> --> Hash(Date) {  }()'
Hash % = {}
```

3. And no `Failure`s come through anymore, because coercion explodes them:

```
$ perl6 -e 'dd sub (--> Str(Date)) { fail "meows" }()'
meows
  in sub  at -e line 1
  in block <unit> at -e line 1
```

------------------------------------------

```
$ perl6 -v
This is Rakudo version 2018.06-146-g1b3dd35 built on MoarVM version 2018.06-141-gcae4731
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
Perhaps we shouldn't allow coercers on return types?

**Comment by zoffixznet** [comment]
👍 

There's 6.d propspec for it (cover for [RT#128964](https://rt.perl.org/Ticket/Display.html?id=128964)) that will need to be removed before 6.d release.

**Comment by zoffixznet** [comment]
> There's 6.d propspec for it 

Moved to appendices

**Comment by vrurg** [comment]
Resolved, not sure when.
