### ISSUE TITLE
Literal \ broken in tr/// and TR///

### ISSUE THREAD

**Issue by donaldh** [rakudo/rakudo#2456]
## The Problem

`tr/\\//` fails to parse. `tr/\\_//` does not transliterate a `\` as expected.

## Steps to Reproduce

```
say TR/\\// given '\\'
===SORRY!=== Error while compiling:
Malformed replacement part; couldn't find final /
at line 2
------> <BOL>⏏<EOL>
```

## Environment
* Operating system: macOS
* This is Rakudo version 2018.09-517-ge7e91ecfb built on MoarVM version 2018.09-140-g32a47383b

**Comment by zoffixznet** [comment]
Fixed in https://github.com/rakudo/rakudo/pull/2457 Test needed

**Comment by zoffixznet** [comment]
Tests in https://github.com/perl6/roast/commit/ccd5a0caf7b06b95516cc44bbad234acaf53f044
