### ISSUE TITLE
Weirdness with 6.d switching and set ops

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2458]
Maybe there's too much blood in my coffee veins, but I'm not getting good behaviour.

What's supposed to happen is the `≼` operator needs to issue deprecation warnings in 6.c and as of https://github.com/rakudo/rakudo/commit/951303f9aa it should die on 6.d

However, first, the camelia bot seems to die even if you ask for 6.c language:

```
<Zoffix__> m: use v6.c; say 42 ≼ 45
<camelia> rakudo-moar 0bdf51809: OUTPUT: «≼ was removed in 6.d, please use ⊆ operator instead␤  in block <unit> at <tmp> line 1␤␤»
```

However, when I build HEAD of rakudo, it's the reverse, I can't get it to die in 6.d lang:

```
$ ./perl6 -e 'say 42 ≼ 45'
False
Saw 1 occurrence of deprecated code.
[...]

$ ./perl6 -e 'use v6.d; say 42 ≼ 45'
False
Saw 1 occurrence of deprecated code.
[...]

$ ./perl6 -e 'use v6.d.PREVIEW; say 42 ≼ 45'
False
Saw 1 occurrence of deprecated code.
[...]

$ ./perl6 -e 'use v6.d; infix:<≼>'                                                                                                                                                                                 
===SORRY!=== Error while compiling -e
Calling infix:<≼>() will never work with signature of the proto ($, $, *%)
at -e:1
------> use v6.d; ⏏infix:<≼>

$ ./perl6 -v
This is Rakudo version 2018.10-40-g0bdf51809 built on MoarVM version 2018.10-27-gcd4f98aff
implementing Perl 6.d.
```

Despite other 6.d things, like 6.d deprecation of `undefine` working fine:

```
$ ./perl6 -e 'undefine []'
Saw 1 occurrence of deprecated code.
[...]
$ ./perl6 -e 'use v6.c; undefine []'
$ 
```

**Comment by lizmat** [comment]
that's constant folding that's dieing.  Try it with something not constant, and it should work as advertised.  I guess we need to make the die() somehow conditional on it being run in constant folding.

**Comment by zoffixznet** [comment]
*phew*. Thanks. I opened that as a separate Issue: https://github.com/rakudo/rakudo/issues/2459
