### ISSUE TITLE
Constant-folder does not see 6.d stuff

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2459]
The 6.c version of `≼` op issues deprecation warning, while its 6.d version dies.

It appears our static optimizer that constant folds stuff only considers 6.c candidates of routines when folding, as the 6.d death occurs only when we use non-foldable arguments:

```
<Zoffix__> e: my $x = 42; say $x ≼ 45
<evalable6> Zoffix__, rakudo-moar 0bdf51809: OUTPUT: «(exit code 1) ≼ was removed in 6.d, please use ⊆ operator instead␤  in block <unit> at /tmp/NbYlFYamOu line 1␤␤»

<Zoffix__> e: say 42 ≼ 45
<evalable6> Zoffix__, rakudo-moar 0bdf51809: OUTPUT: «False␤Saw 1 occurrence of deprecated code.␤===============================================…»
```

Likely a related problem to https://github.com/rakudo/rakudo/issues/2432

**Comment by lizmat** [comment]
Fixed with 7a1a18688446f4386 , not sure we need tests for this?

**Comment by lizmat** [comment]
FWIW, have a generic mechanism with which we can see if we're called in constant folding mode, is a nice thing to have and possibly should be documented and made into a feature.  IMO this doesn't have to be version specific at all.

**Comment by lizmat** [comment]
But you're right: the constant folder *was* trying to run the v6.c code while being in v6.d.

**Comment by vrurg** [comment]
@lizmat can you check if the problem still exists? I was fixing optimizer for language-version support and it was exactly about it not seeing symbols on other settings but `c`.
