### ISSUE TITLE
Weird `Seq.ACCEPTS` with a List

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2468]
I was expecting both to give the same result and the result in version with `List` on RHS makes the most sense to me:

```
<Zoffix_> m: dd (Any,)~~ (42,).Seq
<camelia> rakudo-moar bfe2ad63f: OUTPUT: «Bool::True␤»
<Zoffix_> m: dd (Any,)~~ (42,)
<camelia> rakudo-moar bfe2ad63f: OUTPUT: «Bool::False␤»
```

**Comment by JJ** [comment]
Also: 
```
 for ^10 -> $i { say $i ~~ @fib } # Fib is the infinite Fibonacci sequence
```

is always true, but

```
for ^10 -> $i { say [$i] ~~ @fib }
```

is always false.

**Comment by JJ** [comment]
OK, I see what happens with the second: @fib is lazy, and if any of them is lazy it will fail.

**Comment by JJ** [comment]
Ping?

**Comment by 2colours** [comment]
@JJ  
"always False": this line throws (`.elems` is invoked on a lazy list) https://github.com/rakudo/rakudo/blob/704a05b934ba10f3240e8764827bbfd7fe089cdf /src/core.c/List.pm6#L666 and https://github.com/rakudo/rakudo/blob/704a05b934ba10f3240e8764827bbfd7fe089cdf/src/core.c/List.pm6#L657 this line converts it to False

"always True": https://github.com/rakudo/rakudo/blob/704a05b934ba10f3240e8764827bbfd7fe089cdf/src/core.c/List.pm6#L700 this line turns the failure into False value which was assumed to always stand for 0 elems:

> If $topic is not an [Iterable](https://docs.raku.org/type/Iterable), returns the invocant if the invocant has no elements or its first element is a [Match](https://docs.raku.org/type/Match) object (this behavior powers m:g// smartmatch), or False otherwise.
(https://docs.raku.org/type/Array#(List)_method_ACCEPTS)

This seems to be an easy bugfix if the supposed behavior is to always return False on lazy lists.

**Comment by 2colours** [comment]
For the original issue: it was hard to notice but the `Seq.ACCEPTS(Iterable)` candidate had the arguments reversed - so `(42, ) ~~ (Any, ).Seq` would have been False indeed.
