### ISSUE TITLE
Method style subroutine calls insist that any string that resembles a negative number, IS

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#2471]
## The Problem
Method style subroutine calls insist that any string that resembles a negative number, IS, regardless of any string coercion.

```
sub k ($n) {
    my $s = $n < 0 ?? '-' !! '';
    $s ~ "{($n.abs/1000).round(.001).Str}" ~ 'K'
}

dd k 1234;
# dd k(1234); ok
dd 1234.&k;
dd k -1234;
# dd k(-1234); ok
dd -1234.&k;
```
## Expected
"1.234K"
"1.234K"
"-1.234K"
"-1.234K"

## Actual 
"1.234K"
"1.234K"
"-1.234K"
Cannot convert string to number: trailing characters after number in '1.234⏏K' (indicated by ⏏)
  in block <unit> at huh.p6 line 11

## Environment
*  Linux Mint 19
* Tested on 2018.09: This is Rakudo version 2018.09 built on MoarVM version 2018.09
* Tested on HEAD: This is Rakudo version 2018.10-66-gb09926693 built on MoarVM version 2018.10-72-g4fbaeee5f
* Tested on: Camelia

**Comment by zoffixznet** [comment]
> Expected
> Actual

The shown `Expected` matches my `Actual`. The ticket doesn't show what your `Actual` behaviour is. Any info on it?

**Comment by thundergnat** [comment]
Arrgh. method call binds tighter than prefix -. 

Notabug.
