### ISSUE TITLE
Array built with hyper operations becomes immutable

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#2480]
## The Problem
After copying array structure (and filling with zero values) via »*», attempting to modify it fails with complaint about 'immutable value'.

## Expected Behavior
Assignment should work.

## Actual Behavior
Error message is:
Cannot assign to an immutable value  in block <unit> ...

## Steps to Reproduce
my @A = [[1], [2, 3]]; my @B = @A; @B[0][0] = 42;  # this is fine
my @A = [[1], [2, 3]]; my @B = @A »*» 0; @B[0][0] = 42; # this generates error

## Environment
This is Rakudo version 2018.10-102-ga575effea built on MoarVM version 2018.10-72-g4fbaeee5f
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
Bisected to one of these:
* b0a2ce765714d088d835f42f197d6616de21ba5a
* ec2848c43ae54961dd7b9109a48f68c03b206abb
* 2eb43ab9e4d451449dd411e9694f55add9182dfe
* 547f28baf614bb958751b033f0fb8d30639a6b63
* f06e8582fe6da9a04dcacab34b2e9c0d3c31602f
* 73eb297f6cee67989a3583171640b9945d37d444

**Comment by lizmat** [comment]
Fixed with 1a2b39dc1a
