### ISSUE TITLE
[wishlist] the ability to check if an argument was provided in the call

### ISSUE THREAD

**Issue by Tux** [rakudo/rakudo#2483]
## Cannot tell if value was passed as argument or stems from a default
```
class Foo {
    method (Int :$foo = 0) {
        if ($foo == 0) {
            # I cannot tell if this call is from Foo.foo() or from Foo.foo(foo => 0);
            }
        }
    }
```
If possible, I'd loke to see a method or trait, so that I can check if `$foo` was provided in the arguments of the call or that it was set by the default, something like
```
method (Int :$foo = 0) {
    if ($foo == 0) {
        if ($foo:provided) { # Foo.foo(foo => 0)
            # ...
            }
        else { # Foo.foo()
            # ...
            }
        }
    }
```

**Comment by lizmat** [comment]
You can work around this by supplying a default value that is unique, and checking for that later:

    class A {
        constant NOT-SPECIFIED = Any.new;  # Mu fails decont :-(
        has $.a = NOT-SPECIFIED;

        method a() {
            say "not specified" if $!a<> =:= NOT-SPECIFIED;
            $!a<> =:= NOT-SPECIFIED ?? 666 !! $!a
        }
    }

    dd A.new.a;                 # not specified, 666
    dd A.new(a => 42).a; # 42

**Comment by lizmat** [comment]
Another approach could be to mix in a role into the default, and check for that:

    role not-specified { }

    class A {
        has $.a = 666 but not-specified;

        method a() {
            say "not specified" if $!a ~~ not-specified;
            $!a ~~ not-specified ?? 666 !! $!a
        }
    }

    dd A.new.a;                 # not specified, 666
    dd A.new(a => 42).a;  # 42

**Comment by Tux** [comment]
```
#!raku

# https://github.com/rakudo/rakudo/issues/2483
# [wishlist] the ability to check if an argument was provided in the call

class Foo {

    sub action (@kh) {
        say @kh ~~ Array ?? "YES" !! "no";
        } # action

    method foo (:@kh = Array but my role NOT-PROVIDED {}) {

        @kh ~~ NOT-PROVIDED and say "It is missing";
        action(@kh);
        }

    method f (:@kh) {
        self.foo(kh => @kh);
        }
    }

sub f (*%args) is export {
    Foo.f(|%args);
    }

f();
f(kh => Array);
f(kh => my @kh);
```
=>
```
YES
YES
YES
```
In this case a role does not help

Another issue is that
```
    method foo (:@kh but my role NOT-PROVIDED {}) {
```
(same without a default assignment) is not allowed:
```
===SORRY!=== Error while compiling /pro/3gl/CPAN/Text-CSV6/issue-2483.pl
Malformed parameter
at /pro/3gl/CPAN/Text-CSV6/issue-2483.pl:12
------>     method foo (:@kh⏏ but my role NOT-PROVIDED {}) {
    expecting any of:
        constraint
```

**Comment by lizmat** [comment]
OOC, question: why do you want to be able to see if a named argument is passed, other than to do some default behaviour that couldn't be supplied by a default value?

**Comment by Tux** [comment]
If it is passed - in my case - it *implies* a Hash-like environment regardless of the contents of the parameter. This means that I need to optionally change some defaults
```
@kh.provided and $out //= Hash;
```
would be part of the example here. In this specific case, `@kh` (if provided) will always be empty, as it will be filled inside the method.

I've by now had this "wish" a few more time already.
(I'm also trying to reproduce the case where I tried this role-approach and something went wrong down the line)

**Comment by Tux** [comment]
```
class Foo {

    method action (Array @kh) {
        say @kh ~~ Array ?? "YES" !! "no";
        } # action

    method foo (:@kh = Array but my role NOT-PROVIDED {}) {

        @kh ~~ NOT-PROVIDED and say "It is missing";
        self.action(@kh);
        }

    method f (:@kh) {
        self.foo(kh => @kh);
        }
    }

sub f (*%args) is export {
    Foo.f(|%args);
    }

f();
f(kh => Array);
f(kh => my @kh);
```
=>
```
Type check failed in binding to parameter '@kh'; expected Positional[Array] but got Array ([])
  in method action at issue-2483.pl line 8
  in method foo at issue-2483.pl line 15
  in method f at issue-2483.pl line 19
  in sub f at issue-2483.pl line 24
  in block <unit> at issue-2483.pl line 27
```
is part of the problem

**Comment by vrurg** [comment]
@Tux, you just do it not the way it is supposed to be:

```raku
role NOT-SET {}

multi sub foo(:@k = [] but NOT-SET) {
    samewith @k;
}
multi sub foo(@k) {
    say "got ", @k.^name;
    say "default? ", @k ~~ NOT-SET;
}

foo;
foo(:k(5,6));
```

**Comment by Tux** [comment]
That won't fly if the method has 8 optional parameters

**Comment by lizmat** [comment]
If it really has that many optional parameters, why not do it the old fashioned Perl way?
````raku
sub foo (*%_) {
    if (%_<k>:exists) {
        ...
    }
    else {
        ...
    }
}

**Comment by Tux** [comment]
1. Because of speed
2. Because of previous advice
3. Because of (self)documenting code layout (old fashioned is not really obvious)
4. Because of error reporting

I can create a wrapper method that copes with all the options that would change defaults, but it - in my perception - completely passes by all the goodness that Raku has to offer like reporting wrong argument types.

Maybe my mind still is not raku enough, but this "provided" wish has now come up with me for at least 10 times and all the alternative approaches either won't work in my stuff the way I feel it should or feel like doing it the wrong way.

My goal in this API is to make it
- as close to the perl5 API as possible, though I support way more stream types in Raku
- as intuitive as possible
- as defensive as possible (give the right warning/error as possible appropriate)

Additional issues/problems to my mind is that perl5 is a combination of pure perl and XS and that in XS I can do whatever I want, so the code is not a limit to my ideas

**Comment by niner** [comment]
On Sunday, 30 April 2023 12:34:29 CEST H.Merijn Brand wrote:
> 1. Because of speed

To argue with performance would require an actual proposal for an alternative 
to the existing methods. Assume that we do provide a mechanism for telling 
whether a certain arguments has been passed by the caller. What would it look 
like? Without knowing that we cannot tell if there is even a way to make that 
perform better than the existing ways.

> Maybe my mind still is not raku enough, but this "provided" wish has now
> come up with me for at least 10 times and all the alternative approaches
> either won't work in my stuff the way I feel it should or feel like doing
> it the wrong way.

Usually the correct answer for these cases is to use multis. Behaving 
differently depending on which and what arguments are provided is exactly what 
multis are for. They also give you the best possible performance for this. 

That this causes a combinatory explosion in your case may actually point at a 
problem with your interface. Having 8 optional arguments is usually a cause 
for concern and points at some architectual issue (usually - of course not 
always).

> My goal in this API is to make it
> - as close to the perl5 API as possible, though I support way more stream
> types in Raku - as intuitive as possible

Maybe that's the problem? Raku is good at supporting Raku style APIs. It 
shouldn't be surprising that it's less good at supporting code that tries to 
behave like a different language.

I still don't understand why the version with the default value sentinel 
wouldn't work for you.

```
my role DefaultValue {};
sub ***@***.*** = [] but DefaultValue) {
    say @a.does(DefaultValue) ?? "default" !! @a
}
foo;
foo(a => [1,2];
```
gives:
```
default
[1 2]
```

You say that you can't use this trick if there is no default value, but what 
keeps you from simply adding a default value? It works even with an undefined 
default value i.e Array but DefaultValue.


Yet another way in which Raku already answers that question:
```
sub ***@***.*** = (my $a-default = [])) {
    say $a-default !=:= Any ?? "default" !! @a
}
foo;
foo(a => [1,2])
```
again gives:
```
default
[1 2]
```

**Comment by vrurg** [comment]
@niner spoke it out before me, but architectural problem was on my mind too.

> 1. Because of speed

Believe me, implementing the feature you want on the language level would have the same problem. Worse, it would affect even the code not needing it. I.e. – overwhelming majority of the code around.
