### ISSUE TITLE
Multi-dimensional slice with Callable returning Iterable

### ISSUE THREAD

**Issue by nwellnhof** [rakudo/rakudo#2488]
According to the documentation, you can use [Callables in slices](https://docs.perl6.org/language/subscripts#Slices).

> Be aware that slices are controlled by the type of what is passed to **(one dimension of)** the subscript, not its length. In particular the type can be any of the following: [...] Callable, **whatever is returned by the callable**

But this doesn't work in multi-dimensional subscripts if the Callable returns an Iterable. I'm seeing:

    say (1,2,3; 4,5,6; 7,8,9)[{0,1}]    # ((1 2 3) (4 5 6))
    say (1,2,3; 4,5,6; 7,8,9)[*;0,1]    # (1 2 4 5 7 8)
    say (1,2,3; 4,5,6; 7,8,9)[*;{0,1}]  # (3 6 9)

I'd expect the third example to work like the second. But apparently, the Iterable returned from the Callable is numified.

**Comment by nwellnhof** [comment]
I think that *right at the beginning* of `MD-ARRAY-SLICE-ONE-POSITION`, if `idx` is a Callable, it should be evaluated until it doesn't return another Callable.

**Comment by lizmat** [comment]
This will not be fixed for 6.c or 6.d, as there's too much code out there depending on broken semantics.  6.e has a completely new implementation that I will look at :-)

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/4b56d481c2

**Comment by melezhik** [comment]
@lizmat am I right this issue is not yet fixed?

**Comment by lizmat** [comment]
This is fixed for 6.e, so any test would require a `use v6.e.PREVIEW`.
