### ISSUE TITLE
Feature request: easy oneliner data reporting.

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#2489]
## The Problem

When processing different data through tons of oneliners I've found that Perl6 is missing an easy way to report it back. At some point I always end up with constructs like:

```perl6
@data>>.say  # as column
.say for @data; # as column
@data.Str.say # as row
say ~@data # as row
@data.join(" ").say # as row
```

So I'd like to propose two changes, to make oneliners more powerful:

## In oneliner (`perl6 -e '...'`) context print everything invoked in sink context instead of throwing a warning

That will make reporting super easy, for example:

```
perl6 -e 'my @data = 1,2,3; @data'
1 2 3
```
(stringified `1 2 3` is more DWIM than `[1 2 3]`, however forcing string context by `~@data`  would be also short enough)

or

```
perl6 -e 'my $total; sub parse_report { $total += ... }; $total'
1024
```

## Provide vertical context

Sometimes data must be reported as columns. I don't have a good solution for that. Maybe separate prefix that will force vertical context?

```
perl6 -e 'my @data = 1,2,3; ↓@data'
1
2
3
```

## Summary

This feature request is **not** about implementing full blown pretty-printing formatter. The point is to make most common operations in oneliners - horizontal and vertical data reporting - easier.

**Comment by bbkr** [comment]
BTW: That will make shortest [Quine](https://code-golf.io/quine) possible:
```
perl6 -e '1'
1
```
:)

**Comment by lizmat** [comment]
How about you create a script called `dd` containing:

    use MONKEY;
    dd EVAL @*ARGS.join(' ');

then run with:

    $ perl6 dd '42 + 666'
    708

Same number of letters, and complete freedom in how *you* want to format this.

Script name / features up to bikeshedding.

**Comment by bbkr** [comment]
That works but its additional script required. In my proposed solution (printing in sink context) I can report stuff more freely (for example in loops) and without gathering whole buffer to print in memory.

**Comment by lizmat** [comment]
Apart from `-n -e` not being possible, could you elaborate on situations where you would need that and what output you expect?
