### ISSUE TITLE
Assignment to hash via array subscript fails

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#2490]
## The Problem
Assigning to hash via array subscript fails.
 
## Expected Behavior
Assignment to hash should work.

## Actual Behavior
No assignment occurs, array is unchanged.

## Steps to Reproduce
my @a; @a[0]<a b> = 42, 47; dd @a;

## Environment
This is Rakudo version 2018.10-145-gf7007ac0e built on MoarVM version 2018.10-77-g6236eb5de
implementing Perl 6.d.

**Comment by lizmat** [comment]
Fixed with c4da4c7eab and 9a2c4b447b

**Comment by Altai-man** [comment]
I am sorry, but the ticket description is a bit confusing to me.

It uses "Hash" in description, but the code offered uses an Array. What's more, the code offered returns the same result on all 6.c and on master, `Array @A = [(42, 47),]`.

Can anyone clarify the intent so a test could be written? Ping @SqrtNegInf.

**Comment by SqrtNegInf** [comment]
These two statements always worked:
```
my %h; %h<a b> = 42, 47;
my @b; @b[0]<a> = 42; @b[0]<b> = 47;

```
This has behaved similarly, but had stopped working
`my @a; @a[0]<a b> = 42, 47;
`

Hopefully this is clearer...

**Comment by lizmat** [comment]
Array @a = [{:a(42), :b(47)},]  # Array @a = [{:a(42), :b(47)},]

This looks correct to me.  Did you expect something else?  If so, what?

**Comment by Altai-man** [comment]
Referenced this issue by a mistake, sorry for the noise.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/6b4e89cc4d
