### ISSUE TITLE
LTA: Certain methods on Failure don't explode it

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2492]
Normally, calling virtually any method on a `Failure` object will cause that failure to blow up, revealing the exception it was holding:

```
$ perl6 -e 'open("/a/b/c/d/bogus", :w).print'
Failed to open file /a/b/c/d/bogus: No such file or directory
  in block <unit> at -e line 1
```

However, the same is not the case for methods provided by `Mu`, `Any`, `Cool`, and `Nil` (which are inherited by `Failure`) if those methods are called with some set of arguments those methods do not usually take:

```
$ perl6 -e 'open("/a/b/c/d/bogus", :w).print: 42'
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at -e line 1
```

The error does not reflect the actual problem or the original exception and unless the user realizes the call is happening on a `Failure` instead of `IO::Handle` the error doesn't make any sense for them, since they're calling the method with correct arguments.

This Issue is tangently related to `.?` safe-call method op, which propagates a `Nil` if the method was not found, and how some methods called on a `Nil` result in a similar crash, instead of propagating that `Nil` further.

```
$ perl6 -e 'class Foo {}; Foo.?meow.?print: 42'
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at -e line 1
```

-------------

```
$ perl6 -v
This is Rakudo version 2018.06-146-g1b3dd35 built on MoarVM version 2018.06-141-gcae4731
implementing Perl 6.c.
```

**Comment by lizmat** [comment]
This appears fixed:
```
% raku -e 'open("/a/b/c/d/bogus", :w).print: 42'
Earlier failures:
 (HANDLED) Failed to open file /a/b/c/d/bogus: No such file or directory
  in block <unit> at -e line 1

Final error:
 Cannot resolve caller print(Failure:U: Int:D); none of these signatures matches:
```

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/4f4fe9090a
