### ISSUE TITLE
unexpected behavior from cglobal pointers

### ISSUE THREAD

**Issue by emakman** [rakudo/rakudo#2501]
I was playing around with the NCurses bindings and ran into an issue with a cglobal pointer.

## The Problem
ncurses exports a variable pointer $stdscr, which is in turn accessed in the NCurses module by cglobal. (returning a class which `is repr<CPointer>`). When this in turn is plugged into native functions expecting the same pointer type (for example, the `wrefresh` function), it causes a segfault.

## Expected Behavior
The standard ncurses `refresh()` function should behave exactly the same as `wrefresh(stdscr)` (in fact is a macro defined as `wrefresh(stdscr)`); the contents of the screen should be updated. In particular, I do not expect a segfault.

## Actual Behavior
The program unexpectedly crashes.

Output (run with `perl6 --ll-exception`):
  `Segmentation fault (core dumped)`

## Steps to Reproduce
  The issue with NCurses can be reproduced with the following code:

    use NCurses;
    initscr; endwin; # This guarantees sure stdscr has been set.
    wrefresh(stdscr);

 The corresponding C code compiles and executes correctly.

 I seem to be able to avoid the problem if I avoid using cglobal pointers. The following executes as expected:

    use NCurses;
    use NativeCall;
    initscr; endwin;
    my \intptr_t = (nativesizeof(Pointer) == 8) ?? int64 !! int32;
    my $stdscr := cglobal(library,'stdscr',intptr_t);
    wrefresh(Pointer.new($stdscr));

## Environment
* Operating system: 
  Arch Linux (4.18.16-arch1-1-ARCH)
* Compiler version (`perl6 -v`): 
    Rakudo version 2018.10-163-g50f0fce9b built on MoarVM version 2018.10-81-g7ba02259b
implementing Perl 6.d.

**Comment by emakman** [comment]
OK, after playing around, I have a better minimal example:

in libtest.c (compiled with `gcc libtest.c -olibtest.so --shared -fPIC`):

    int a;
    extern int *x = &a;
    void SET() { a = 3; }
    void GET(int *t) { return *t; }

in test.pl6:

    use NativeCall;

    my \LIB = 'PATH/TO/libtest.so';
    my $x := cglobal(LIB,'x',Pointer);
    my \interptr_t = (nativesizeof(Pointer) == 8) ?? int64 !! int32;
    my $intx := cglobal(LIB,'x',intptr_t);

    sub SET() is native{LIB} {*};
    sub GET(Pointer) returns int32 is native{LIB} {*};
    SET();
    GET($x).say; # returns a random integer value;
    GET(Pointer.new($intx)).say; # returns 3.

No segfault this time, but the cglobal pointer in `$x` still seems to be erroneous. I was hesitant o give this example originally because I don't know what I'm doing when it comes to C shared libraries, but I still would have expected GET($x) to return 3.

**Comment by scovit** [comment]
As an elegant workaround ;) on linux 64bit, it seems you can just add 12 to the Pointer obtained by cglobal and make it work:

`
use NativeCall;

my \LIB = '/home/romain/src/test/libtest.so';
my $x := cglobal(LIB,'x',Pointer);
my \interptr_t = (nativesizeof(Pointer) == 8) ?? int64 !! int32;
my $intx := cglobal(LIB,'x',interptr_t);

sub SET() is native{LIB} {*};
sub GET(Pointer) returns int32 is native{LIB} {*};
SET();

#say ($x + 12).base(16);
#say $intx.base(16);

GET(Pointer.new($x+12)).say;                 # returns a random integer value;
GET(Pointer.new($intx)).say; # returns 3.
`

**Comment by emakman** [comment]
It's been a while and I'm not sure anybody else was ever having this issue, nor is the code snippet I submitted before valid. Closing.
