### ISSUE TITLE
Can't assign Nil to an attribute from a role

### ISSUE THREAD

**Issue by lucasbuchala** [rakudo/rakudo#2503]
```
> role R[::T] { has T $!x }; class C does R[Any] { method m { $!x = Nil } }; C.new.m; say 'ok'
Died with X::TypeCheck::Assignment
  in method m at - line 1
  in block <unit> at - line 1
```

Bisectable pointed at: https://github.com/rakudo/rakudo/commit/d3c5381b747169f951db578bebbfd0c5d8165116

Context: https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-11-20#l263

**Comment by vrurg** [comment]
Fixed since at least 2019.07
