### ISSUE TITLE
Rational number slowdown

### ISSUE THREAD

**Issue by GrayJoKing** [rakudo/rakudo#2504]
## The Problem
Doing large calculations with rational numbers has slowed down since [rakudo/rakudo@5c429e4](https://github.com/rakudo/rakudo/commit/5c429e4eadcdcb9ba5aa3d7eb79264f172990f0e).

## Code
```
my $pi = 1.FatRat;
for 2000...1 {
   $pi = .FatRat²/$pi+$_*2-1
}
$pi = 4/$pi;
say $pi
```

@AlexDaniel says [here](https://github.com/JRaspass/code-golf/issues/65#issuecomment-440820984) for a almost identical program:

> I'm getting 1.21s before and 3.27s after. On HEAD it is also slow (3+ seconds).

**Comment by AlexDaniel** [comment]
Output and timings on 6c releases: https://gist.github.com/e52f9904ae05d3c7c3f75d8d3777112d
Note that it used to be even slower, but around 2018.05 was an all-time low.

Confirmation that (2018-07-31) https://github.com/rakudo/rakudo/commit/5c429e4eadcdcb9ba5aa3d7eb79264f172990f0e is when it regressed:

```
¦«5c429e4^»:
3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268066130019278766111959092164201989380952572010654858632788659361533818279682303019520353018529689957736225994138912497217752834791315155748572424541506959508295331168617278558890750983817546374649393192550604009277016711390098488240128583616035637076601047101819429555961989467678374494482553797747268471040475346462080466842590694912933136770289891521047521620569660240580381501935112533824300355876402474964732639141992726042699227967823547816360093417216412199245863150302861829745557067498385054945885869269956909272107975093029553211653449872027559602364806678901887051798675039500424161950235063077647134634014798660213213873011072029040569893394274973183547121156391294859471907499736540665295597976397654814146468159744121999226476434521274571404671001215402700041417443105177901112313868293897676525592693596994984583185760477964091419719811403582652140579983665371366142307194760027960770772868066680053067073835051895825298792656066901175367820030834
1.246372121

¦«5c429e4»:
3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268066130019278766111959092164201989380952572010654858632788659361533818279682303019520353018529689957736225994138912497217752834791315155748572424541506959508295331168617278558890750983817546374649393192550604009277016711390098488240128583616035637076601047101819429555961989467678374494482553797747268471040475346462080466842590694912933136770289891521047521620569660240580381501935112533824300355876402474964732639141992726042699227967823547816360093417216412199245863150302861829745557067498385054945885869269956909272107975093029553211653449872027559602364806678901887051798675039500424161950235063077647134634014798660213213873011072029040569893394274973183547121156391294859471907499736540665295597976397654814146468159744121999226476434521274571404671001215402700041417443105177901112313868293897676525592693596994984583185760477964091419719811403582652140579983665371366142307194760027960770772868066680053067073835051895825298792656066901175367820030834
3.2994194
```

**Comment by GuyJoKing** [comment]
Interestingly, replacing the `.FatRat` in the loop with just `$_` slows it down even further

**Comment by zoffixznet** [comment]
It's not a regression. Quoting the commit message:

> This commit changes the performance landscape of rationals.

> As described in the Work Proposal[^1], the optimization was removed
from +/- of Rationals, so those are now slower, but tossing reduction
calls boosts other areas and lets us use simpler code paths in some ops,
making them faster. So overall the removal of this opt is likely
beneficial (and it had to be removed to fix the data race)

> [1] https://github.com/rakudo/rakudo/blob/master/docs/archive/2018-03-04--Polishing-Rationals.md#3-limited-usefulness-of-the-optimization

Looking at OP code, I'd guess it's the `infix:<+>` operation in particular that got slower for that particular code. That was expected.

**Comment by AlexDaniel** [comment]
> It's not a regression.

Well, it was fast and now it is slow, so it regressed. I'd say the ticket is valid if we want to discuss how to regain the performance we had earlier.

**Comment by zoffixznet** [comment]
> Well, it was fast and now it is slow, so it regressed

Another way to look at it is it was fast because it was broken. There is a stresstest covering the bug as well: https://github.com/perl6/roast/blob/ac08d5ca529944086795949a51f22ae55593a4ef/MISC/bug-coverage-stress-6.d.t#L12-L35

> I'd say the ticket is valid if we want to discuss how to regain the performance we had earlier.

Fair enough, but IMO regaining entails general performance work, rather than viewing it as a regression from a particular commit that needs to be fixed.

But if it helps: in the past, `infix:<+>` and `infix:<->` used to avoid reduction of the resultant `Rational`, which is why it was faster than it is before. Because it avoided reduction, this meant that in many other operations you had to reduce (a possibly-already-reduced) `Rational` in order to get the result. We had many bugs due to missed reduction, including `infix:<===>`. In addition, because you were mutating the `Rational` in order to have that delayed reduction, it was also not thread safe (which is what the linked-to test covers).

So to fix those problems, the opt in `infix:<+>`/`infix:<->` was removed and now all `Rationals` are reduced on creation. Thus, we no longer have the race condition, and some operations no longer have to potentially pointlessly reduce the invocant, and so they're faster than before when used repeatedly on the same `Rational`. Going by memory, `infix:<==>`, `infix:<===>`, `infix:<**>`, `Rational.narrow`, `Rational.is-prime`, `Rational.ceiling`, and `Rational.Str` are all faster now.
