### ISSUE TITLE
Change in FatRat to string and back again behaviour

### ISSUE THREAD

**Issue by GrayJoKing** [rakudo/rakudo#2505]
The behaviour of 

`say 1+sum((1.FatRat/($×=++$))xx 450).chop`

bisects at ([rakudo/rakudo@5c429e4](https://github.com/rakudo/rakudo/commit/5c429e4eadcdcb9ba5aa3d7eb79264f172990f0e)).

From @AlexDaniel in [this issue](https://github.com/JRaspass/code-golf/issues/65#issuecomment-440824800)

> The difference in the output:
> 
> ```
> ${:exit-code(0), :output("2.7182818284590452353602874713526624977572470936999595749669676277240766303535475945713821785251664274274663919320030599218174135966290435729003342952605956307381323286279434907632338298807531952510190115738341879307021540891499348841675092447614606680822648001684774118537423454424371075390777449920695517027618386062613313845830007520449338265602976067371132007093287091274437470472306969772093101416928368190255151086574637721112523897844250569536967707854499699679468644549059879316368892300987931277361782154249992295763514822082698951936680331825288693984964651058209392398294887933203625094431173012381970684161403970198376793206832823764648042953118023287825098194558153017567173613320698112509961818815930416903515988885193458072738667385894228792284998920868058257492796104841984443634632449684875602336248270419786232090021609902353043699418491463140934317381436405462531520961836908887070167683964243781405927145635490613031072085103837505101157477041718986106873969655212671546889570350354\n"), :signal(0), :time(Duration.new(<399049/1157286>))}
> ${:exit-code(0), :output("2.718281828459045\n"), :signal(0), :time(Duration.new(<10019/29666>))}
> ```

I believe the first should be the appropriate behaviour.

**Comment by zoffixznet** [comment]
> bisects at (rakudo/rakudo@5c429e4).

When I bisected it, I got https://github.com/rakudo/rakudo/commit/008b9279aded22fd67c0de88129a4845b625b8f3 as the point where the change occurred. Looks more relevant to the OP Issue as well.

**Comment by AlexDaniel** [comment]
@zoffixznet See https://gist.github.com/Whateverable/a77480546b37bdf419f43d7e8ac8dffa

**Comment by lizmat** [comment]
All this basically has been superseded by [`$*RAT-OVERFLOW`](https://docs.raku.org/language/variables#$*RAT-OVERFLOW), so closing
