### ISSUE TITLE
Stringifying zero-denominator rationals explodes

### ISSUE THREAD

**Issue by cygx** [rakudo/rakudo#2506]
Stringifying zero-denominator rationals throws an exception due to https://github.com/rakudo/rakudo/blob/a804ab5/src/core/Rational.pm6#L95

This comes as a surprise, as other operations treat them as (semi-)regular values, which however will 'randomly' explode when trying to display them.

Just like the equivalent floating point values, they should probably stringify to `"Inf"`, `"-Inf"` and `"NaN"` as appropriate instead.

**Comment by zoffixznet** [comment]
Why though? Specifically, why should **integer** division by zero result in a floating point value rather an exception, which is what many languages do? That's what `Rational` type really is; just lazy integer division.

> the equivalent floating point values

BTW, these semantics are already available in `Rational` when you use `Num` (Perl 6's floating point type) "view" of them; i.e. coercing a `<0/0>` with a `.Num` call gives you a `NaN` instead of exploding)

**Comment by zoffixznet** [comment]
> why should division of an integer by an integer zero result in a floating point value

Oh right, we produce them anyway if denominator is over 64-bits, so that argument doesn't apply:

```
$ perl6 -e 'say 2/2⁶⁵'
5.421010862427522e-20
```

How to determine which is more useful overall? An exception or an exceptional value?

**Comment by cygx** [comment]
Why? Condsider code like this:

    my $inf = 1/0;
    say 42 < $inf;   # works fine
    say $inf;        # now we throw?!

Division by zero does not throw or fail. Comparing the result of such a division to another number does not throw or fail. But an innocuous operation like gisting such a value (eg for debugging purposes) will then throw? Seems crazy to me.

Regarding conversion to JSON, that's not much different than JSON not being able to represent integer values that are too large. First, Perl6 language semantics need to make sense in isolation. Worrying  about conversion to other languages should be of secondary concern at best (though backwards compatibility is of course a valid concern, ie any change in semantics might have to wait for the next language release).

As I see it, there are three options that would make sense:

  1. make division by 0 throw
  2. make division by 0 fail
  3. make division by 0 return sentinel values that I can call `.gist` and `.Str` on

Note that if option 3 is chosen, care has to be taken that all operations work properly on such values, which they currently do not;

    say Inf > -Inf; # True
    say Inf.Rat > (-Inf).Rat; # False

**Comment by cygx** [comment]
So in your mental model, `&infix:</>` is the floating point division operator when its arguments are of type `Num`, but the `Rat` object constructor when its arguments are of type `Int`, and these operators just happen to share the same symbol? I would have to agree that might just be a side-effect of too much guts-poking ;)

But even under that model, how does it make sense for `.Str`, and even more preposterously, `.gist` to throw?

"Look, here's this shiny `Rat` value you can use to represent inifnity and NaN (eg `(0/0).isNaN` and `1/0 == Inf`). It's mostly fine to use, but don't you dare try to look at it (ie call `.gist` and `.Str`), because that'll blow up. Think that's crazy? Tough luck, because That's How Stringification Works for rationals..."

Sorry for the snark, no offense intended.

**Comment by zoffixznet** [comment]
> But even under that model, how does it make sense for .Str, and even more preposterously, .gist to throw?

*"You have to actually divide numerator and denominator to get the answer and division by zero throws, unless you explicitly request IEEE semantics."*

That's basically all there is to it.

1. Do you have to divide nu. by de. to get result for `.Str`, `.Int`, `.floor`, `.ceiling`, `.isNaN`, `.is-prime`, or `.Num`?
    - For `.isNaN` and `.is-prime`, **no**, we can just look at the components individually, so no explosion occurs
    - For all others, yes.
        - Were IEEE semantics requested?
            - For `.Str`, `.Int`, `.floor`, `.ceiling`: **no**. Throw if denominator is zero
            - For `.Num`, **yes**, produce `Inf`/`-Inf`/`NaN` if denominator is zero

---------------------------------------

How come some other languages, like Perl 5, throw on division by zero instead of producing IEEE values?

**Comment by zoffixznet** [comment]
> That's basically all there is to it.

But, again, is `"do you have to divide nu. by de. to get result"` really easy to determine for users who haven't looked at how those methods are actually implemented?

**Comment by cygx** [comment]
What's the purpose of `.gist`? To return a (not necessarily faithful) string representation of a value, optimized for human consumption. I would argue that you should be able to gist *any* value except failures.

What's the purpose of `.Str`? To return a (more likely to be faithful) string representation of a value, not specifically optimized for human consumption. I would argue that you should be able to stringify most defined values, perhaps with some rare exceptions.

You should clearly be able to gist zero-denominator rationals. If the current implementation throws instead, that implementation is broken.

Now, the case of stringification is a bit less clear, because for ordinary rationals, it returns a decimal representation, which does not exist for non-finite values. But does that mean we should just throw instead? Personally, I would argue against that. It very much possible to have a faithful string representation of zero-denominator rationals (such as proposed in my original comment), and people who want to force an exception can stringify using `.base(10)` instead.

**Comment by smls** [comment]
To see the value for debugging purposes, you can use `.perl` (or `dd` which calls it for you):
``` Perl 6
➜  dd 1/0;
<1/0>
```

I think `.perl` is the only stringification method for which the ideal "Can faithfully represent every value of the type" mustn't be compromised. For `.Str` (and `.gist` I suppose), simplicity, non-surprisingness & universal recognizability of the output format are also considerations, and compromises are to be expected.
