### ISSUE TITLE
Intersecting with a Set type object exhausts memory

### ISSUE THREAD

**Issue by taboege** [rakudo/rakudo#2514]
## The Problem
Intersecting a set object with a set type object leads to out-of-memory error.

## Expected Behavior
No overzealous memory consumption. Probably the empty set.

## Actual Behavior
`MoarVM panic: Memory allocation failed; could not allocate xyz bytes`

## Steps to Reproduce
`$ ulimit -v $((1024*1024)) && perl6 -e 'Set ∩ set(1)'`

It doesn't matter if the other set is empty or not.

Suggestion by timotimo++:
https://colabti.org/irclogger/irclogger_log/perl6?date=2018-12-03#l718

## Environment
Tested on camelia `rakudo-moar 38bc682b0`.

**Comment by lizmat** [comment]
Fixed with 99d94db4dd

**Comment by lizmat** [comment]
Additional fix with 9f5cc8d1ba , tests added with https://github.com/perl6/roast/commit/771ab61bf4

**Comment by taboege** [comment]
Thank you!
