### ISSUE TITLE
Configure.pl bombs if the --prefix dir doesn't exist when building in a fresh checkout on Cygwin

### ISSUE THREAD

**Issue by cxw42** [rakudo/rakudo#2518]
First issue here - please let me know if you need more information.  I am trying to build from source so I can understand the MAST->bytecode conversion (I read jnthn's slides but am still not clear on that step).

**Edit** [This gist](https://gist.github.com/Siddhant/12342fb623f95c788df4) appears to be the same problem, from three years ago.  If so, it may be specific to building on Cygwin.

## The Problem

`Configure.pl` bombs if the `--prefix` dir doesn't exist the first time it is run in a brand-new checkout of rakudo.

## Expected Behavior

`Configure.pl` runs to completion.

## Steps to Reproduce

This log uses `--prefix=foo`.

    $ git clone https://github.com/rakudo/rakudo.git

I am at commit 194c84b91064ab6f8cc5e1168fa9332ac3df0e41.

    $ cd rakudo
    $ perl Configure.pl --gen-moar --moar-option='--optimize=0 --debug=3'     --gen-nqp --backends=moar --prefix=foo

(Other than `--prefix=foo`, I got these options from the README)

    No pre-existing installed file found at /home/ChrisW/src/rakudo/foo/bin/nqp-m
    HEAD is now at 472a1b94c [release] Bump VERSION to 2018.11
    Building NQP ...
    /home/ChrisW/perl5/perlbrew/perls/perlcygbrew-5.26.2-1/bin/perl Configure.pl --prefix=/home/ChrisW/src/rakudo/foo --backends=moar --make-install --git-protocol=https --gen-moar --moar-option=--optimize=0 --debug=3
    
    Creating tools/build/install-jvm-runner.pl ...
    /home/ChrisW/src/rakudo/foo: No such file or directory at Configure.pl line 134.
    Command failed (status 65280): /home/ChrisW/perl5/perlbrew/perls/perlcygbrew-5.26.2-1/bin/perl Configure.pl --prefix=/home/ChrisW/src/rakudo/foo --backends=moar --make-install --git-protocol=https --gen-moar --moar-option=--optimize=0 --debug=3

Oops!

    $ mkdir foo
    $ perl Configure.pl --gen-moar --moar-option='--optimize=0 --debug=3'     --gen-nqp --backends=moar --prefix=foo
    No pre-existing installed file found at /home/ChrisW/src/rakudo/foo/bin/nqp-m
    HEAD is now at 472a1b94c [release] Bump VERSION to 2018.11
    Building NQP ...
    /home/ChrisW/perl5/perlbrew/perls/perlcygbrew-5.26.2-1/bin/perl Configure.pl --prefix=/home/ChrisW/src/rakudo/foo --backends=moar --make-install --git-protocol=https --gen-moar --moar-option=--optimize=0 --debug=3
    
    Creating tools/build/install-jvm-runner.pl ...
    Can't exec "/home/ChrisW/src/rakudo/foo/bin/moar": No such file or directory at tools/lib/NQP/Configure.pm line 292.
    Use of uninitialized value $moar_version_output in pattern match (m//) at tools/lib/NQP/Configure.pm line 306.
    Command failed (status 2): git checkout 2018.11
    Command failed (status 512): /home/ChrisW/perl5/perlbrew/perls/perlcygbrew-5.26.2-1/bin/perl Configure.pl --prefix=/home/ChrisW/src/rakudo/foo --backends=moar --make-install --git-protocol=https --gen-moar --moar-option=--optimize=0 --debug=3
    
And it keeps running (I truncated the log here).

I also tried it with no `--prefix` option, and got the same result.  The only difference was that I had to create an `install` directory to get it to run.

## Environment
* Operating system: Cygwin on Win8.1
* P6 Compiler version (`perl6 -v`): N/A
* P5 version: 5.26.2

Thanks!

(**Edit 2** I see that Cygwin is currently unsupported per MoarVM/MoarVM#533, due to libuv difficulties.  However, libuv is now available on Cygwin.  For this issue, however, I think all it needs is a `mkdir unless -w -d` check.)

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by cxw42** [comment]
Unfortunately, I no longer have a running Cygwin installation so can't re-test.  Since no-one else has reported, I think this can be closed.
