### ISSUE TITLE
Problem in perl6/doc (tests taking too long to run)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2524]
See https://github.com/perl6/doc/issues/2498.

**Comment by JJ** [comment]
What tests are you running?

**Comment by JJ** [comment]
I am not sure it's really the fault of a new feature in Rakudo, but it could be; it could also be related to the way pod6 is parsed, since that's the bulk of what we're doing.

**Comment by AlexDaniel** [comment]
Alright, we'll call it a non-blocker then for now. Let me know if you can isolate a rakudo perf regression (if there is any).
