### ISSUE TITLE
Numification of native int array fails

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#2533]
```
> my int @foo = 1,2,3; say @foo > 2;
Cannot resolve caller Real(array[int]: ); none of these signatures match:
    (Mu:U \v: *%_)
  in block <unit> at <unknown file> line 1
```

This works fine with an Int array:

```
> my Int @foo = 1,2,3; say @foo > 2;
True
```

Note that explicit numification works fine.

```
> my int @foo = 1,2,3; say +@foo > 2;
True
```

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`):  Rakudo Star version 2018.10 built on MoarVM version 2018.10

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/dd3f91a2ff8142a

**Comment by lizmat** [comment]
Tests added with 
https://github.com/perl6/roast/commit/49e4b211a5aee3e5514a822c38b715f5bb63a3eb

**Comment by mscha** [comment]
Aren't those the tests for [a different bug fix](https://github.com/rakudo/rakudo/commit/7bf7a2c6f83a57713c)?

**Comment by lizmat** [comment]
Argh, yes:  https://github.com/perl6/roast/commit/0b8606df7d is the one :-)
