### ISSUE TITLE
Augmenting Cool results in weird error.

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#2534]
## The Problem

using MONKEY-TYPING, I can augment Num, but not Cool.

## Expected Behavior

This works:
```
use MONKEY-TYPING; augment class Num { method rad { self * pi / 180 }; }; say 90.Num.rad
```
Output: 1.5707963267948966

However, this does not:

```
use MONKEY-TYPING; augment class Cool { method rad { self * pi / 180 }; }; say 90.rad
```
The output is kind of telling: 
```
No such method 'rad' for invocant of type 'Int'. Did you mean any of these?
    rad
    rand
```
The rad function is mentioned, but if so, why is there an error?

## Actual Behavior
I would expect both outputs to be the same, allowing for rounding errors.

## Environment
This was found on the IRC bot, camelia.

**Comment by coke** [comment]
Pretty sure you need to use compose on the class you’re calling the method on, since it’s not the same as the class you modified.

**Comment by Xliff** [comment]
Got it. Will close. Why do I not need to compose on Num, though?

**Comment by coke** [comment]
In the original, you modified Num, then called the method on a Num, so the instance already knew about it.

In the updated one, you modified Cool, then called the method on a child class; the compose on Int will force it re-check its parents.
