### ISSUE TITLE
$?FILE shouldn't add garbage to end of filename.

### ISSUE THREAD

**Issue by pprocacci** [rakudo/rakudo#2539]
## The Problem
$?FILE appends the object in which it was invoked ... sometimes.
Though this is arguably useful in some contexts, it's _NOT_ what $?FILE should be doing in my humble opinion.  When I ask for a filename via $?FILE I expect just a filename and nothing more.

https://docs.perl6.org/language/variables#Compile-time_variables

The above documentation clearly states: `what file am I in`, not `what file am I in and what class was I invoked from` (or similar).

## Expected Behavior
I always expect just a filename.  I.E /some/path/to/where/I'm/invoked

## Actual Behavior
Object name gets displayed along with the filename to stdout.
I.E /some/path/to/where/I'm/invoked (ThisClassByTheWay)

## Steps to Reproduce

Two files:
------------------------

./test.pl6
++++++++++++++++++++
use lib \<lib\>;
use Test;

my Test $t = Test.new;
++++++++++++++++++++

lib/Test.pm6
++++++++++++++++++++
unit class Test;

submethod BUILD()
{
        $?FILE.say;
}
++++++++++++++++++++

## Environment
Both Linux and FreeBSD.
This is Rakudo Star version 2018.10 built on MoarVM version 2018.10
implementing Perl 6.c.

**Comment by lucs** [comment]
How is this a 'detrap'? Looks more like an outright bug to me.

**Comment by rafaelschipiura** [comment]
It shouldn't even return Str, it should be an IO::Path object: https://colabti.org/irclogger/irclogger_log/raku?date=2020-02-14#l549

**Comment by niner** [comment]
Clearly a bug. That " (Foo)" should only appear in error messages and backtraces and was not meant to land in $?FILE.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lucs** [comment]
More weirdness. Have these two files in some directory:

    bar.raku:
        #!/usr/bin/env raku
        use lib '.';
        use Foo;

    Foo.pm6:
        no precompilation;
        say $?FILE;

Running 'raku bar.raku' prints "bar.raku". Same result when adding "no precompilation;" before the "use lib..." line in bar.raku (maybe there is some precompiled file lying around, I just know where they all end up).

**Comment by ugexe** [comment]
$?FILE has never turned an IO::Path, and I've always thought one would just use `$*PROGRAM` if that is what they really wanted.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/2e69d7a888  Stefan Seifert++ for pointing in the right direction.

**Comment by lizmat** [comment]
Reverted with https://github.com/rakudo/rakudo/commit/4829711aa9

**Comment by lizmat** [comment]
Fixed for now with https://github.com/rakudo/rakudo/commit/4e12365b19
