### ISSUE TITLE
Segfault on doing `read-int8` and friends on a type object

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2540]
## The Problem

    $ perl6 -e 'dd buf8.^find_method("read-int8")(blob8.new(255),0)'
    # Segmentation fault: 11

Oddly enough, this does not happen on roles in general:

    $ perl6 -e 'role A { method a() { "foo" } }; say A.^find_method("a")()'
    # foo

`blob8` and `buf8` are defined as `constant` of a parameterized role.  But that's not the issue either:

    $ perl6 -e 'role A[::T] { method a() { "foo" } }; constant B = A[Int]; dd B.^find_method("a")(A)'
    # foo

So I guess the role being in the setting (aka a pre-compiled module) is what causes this.

The workaround is to pun the role:

    $ perl6 -e 'dd buf8^pun.^find_method("read-int8")(blob8.new(255),0)'
    # -1

## Expected Behavior

The `^pun` should not be necessary.

## Actual Behavior

Segfault.

**Comment by jnthn** [comment]
It's something of a breach of protocol to call `$obj.^find_method` and then not feed the same `$obj` in when making the call. When calling `find_method` on a role, it returns a closure that produces a pun, and then dispatches the call using the pun as the invocant. Thus, the `blob8.new(255)` is discarded, and it ends up doing the method on the punned type object. Arguably, we could say that if the invocant we're really given when invoking is concrete, then we should somehow use that, but I'm not that inclined to do so.

The recently added MoarVM buffer ops fail to do concreteness checks, and thus SEGV if used on a type object. Thus, the same segfault is obtained from simply `blob8.read-int8(0)`, and that certainly should be fixed.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/fecfb22d70

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/88a20c74f3

**Comment by niner** [comment]
Fixed in https://github.com/MoarVM/MoarVM/commit/1343702c3f91a6ed527deef68f23f42da3df802a
