### ISSUE TITLE
Error message uses .gist when there's a 'where' constrained parameter

### ISSUE THREAD

**Issue by lucasbuchala** [rakudo/rakudo#2543]
```
> multi sub f($x, $y) {}; f('XXX', Mu)
Cannot resolve caller f(Str, Mu); none of these signatures match:
    ($x, $y)

> multi sub f($x, 1) {}; f('XXX', Mu)
Cannot resolve caller f(XXX, Mu); none of these signatures match:
    ($x, Int $ where { ... })
```

This is Rakudo version 2018.11 built on MoarVM version 2018.11

**Comment by lizmat** [comment]
Just for clarity: what do you think the output should be?

    Cannot resolve caller f(XXX, Mu); none of these signatures match:
    ($x, 1)

??  or are you referring to the missing quotes around `XXX` in that case?
