### ISSUE TITLE
Missing serialize REPR function for REPR MVMContext (BOOTContext)

### ISSUE THREAD

**Issue by jmaslak** [rakudo/rakudo#2544]
## The Problem

Receiving `Missing serialize REPR function for REPR MVMContext (BOOTContext)` when executing code.  

I saw this show up here - https://travis-ci.org/jmaslak/Perl6-Net-BGP/builds/467814811

It occurs on "master" but not 2018.11.

## Expected Behavior

No error. :)

## Actual Behavior

Error described above.

## Steps to Reproduce

I've tried to golf it.  If I run perl6 on A.pm6, or B.pm6, it runs fine (and does nothing, which is correct).  If I run it on a.pl6, it gives an error message.

Create a.pl6 with contents:
```use v6;
use A;
```

Create A.pm6 with contents:
```use v6;
use B;
```

Create B.pm6 with contents:
```use v6;
module B {
    our @octet = ^256;
    our subset octet of Str where / @octet /;
    our sub foo() { };
};
```

Set your PERL6LIB to "."

Run a.pl6:
```
$ PERL6LIB=. perl6 a.pl6
===SORRY!===
Missing serialize REPR function for REPR MVMContext (BOOTContext)
```

## Environment
* Operating system: Ubuntu 18.04.
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.11-62-g01c56b484 built on MoarVM version 2018.11-33-gee6ea722c
implementing Perl 6.d.
```

**Comment by jmaslak** [comment]
I believe this broke within the last few days.

**Comment by AlexDaniel** [comment]
Bisected: https://github.com/rakudo/rakudo/commit/e747b19a792d7c610845135bd2ef6b6ca1de9407

(gist for whateverable: https://gist.github.com/AlexDaniel/815d139a7e7e072288b7c43fcf07d64b)

**Comment by AlexDaniel** [comment]
@jmaslak thank you for the golf! By the way, I can bisect ungolfed problems with modules too (using [Blin](https://github.com/perl6/Blin)). Ping me if this happens again!

**Comment by jnthn** [comment]
Let's just revert the opt for the release. `/.../` regexes are not their own lexical scope (example: `"x" ~~ /:my $a = 42; <?>/; say $a` compiles fine), so the context it stashes away in a secret lexical ends up in `UNIT`, which is not safe.

**Comment by AlexDaniel** [comment]
Commit reverted.

**Comment by dakkar** [comment]
another case of this, which may be related:

create `A.pm6` containing:
```perl6
use v6.d;
my BagHash[Str] $a;
```

then run `perl6 -I. -MA -e1`, to get:
```
===SORRY!===
Missing serialize REPR function for REPR MVMContext (BOOTContext)
```

Removing the type parameter (i.e. making it `my BagHash $a`) makes it work.

**Comment by lizmat** [comment]
FWIW, I think there's a reason there is no REPR function for the MVMContext.  Because it is not meant to be serialized into a precomp.  @jnthn: do you agree?

**Comment by lizmat** [comment]
@grondilu QuantHashes should be ok now.

**Comment by lizmat** [comment]
As that was the remaining issue here, I think we can close this now
