### ISSUE TITLE
Difference between Int @a and @a[Int]

### ISSUE THREAD

**Issue by hythm7** [rakudo/rakudo#2554]
## The Problem
Int @a and @a[Int] is confusing a little.
Please check IRC related conversation below:
https://colabti.org/irclogger/irclogger_log/perl6?date=2018-12-18#l436

**Comment by AlexDaniel** [comment]
Commit: https://github.com/rakudo/rakudo/commit/79824db536

**Comment by lizmat** [comment]
Warning added with 79824db536 and improved with 55d08c8fbc .  Not sure what to do more about this:

    $ perl6 -e 'my @a[Int] = 1,2,3; dd @a'
    Ignoring [Int] as shape specification
      in block <unit> at -e line 1
    Array element = [1, 2, 3]

**Comment by lizmat** [comment]
Attempts to write tests for this so far have only yielded:

    MoarVM panic: Trying to unwind over wrong handler

errors :-(

**Comment by Altai-man** [comment]
Wasn't able to spot any errors of this kind.

**Comment by hythm7** [comment]
Should this be closed now?

**Comment by Altai-man** [comment]
@hythm7 once https://github.com/rakudo/rakudo/pull/3245 is merged.

**Comment by Altai-man** [comment]
The PR in question with a test was merged, so closing.
