### ISSUE TITLE
&[op] is broken in precompiled code

### ISSUE THREAD

**Issue by pmurias** [rakudo/rakudo#2555]
in Bug.pm6:

```
sub bug is export {
  &[!<];
}

```
in bug6.p6

```
use Bug;
bug()(9, 9)
```

perl6-m bug6.p6
Cannot invoke this object (REPR: Null; VMNull)
  in block <unit> at bug.p6 line 2

The same problem also occurs in the JS and JVM backends

The cause of the problem is that &[!<] works by compiling and running code that calls &METAOP_NEGATE and the closure it returns doesn't have the outer ctx serialized properly.

**Comment by timo** [comment]
This bug seems to have been around for a really, really long time, so at least it isn't a regression

**Comment by vrurg** [comment]
Tested on 2019.07.1 – fails. `HEAD` passes.

Closing via MoarVM/MoarVM#1209 and 7e3d023b4b070ed798915336a98f2bbc7fbac2e7
