### ISSUE TITLE
Need t/spectest.data.6.d

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2557]
In Rakudo's repo, we have several files that list which roast test files the test suite needs to run. If 6.c roast is being tested, [t/spectest.data.6.c](https://github.com/rakudo/rakudo/blob/master/t/spectest.data.6.c) will be used. And by default, [t/spectest.data](https://github.com/rakudo/rakudo/blob/master/t/spectest.data) will be used, which is typically used by roast master branch, which contains proposals for the next language version.

Since 6.d spec was released, we need to create `t/spectest.data.6.d` file, based on current `t/spectest.data`.

There are some docs for how this system works: https://github.com/rakudo/rakudo/blob/master/docs/roast-spectest.data-versioning.md

Also, 6.d release forgot to update the VERSION file. Filed as https://github.com/perl6/roast/issues/506

**Comment by vrurg** [comment]
With regard to perl6/problem-solving#31 discussion, revision-specific files are not needed. To mark milestones and revision statuses tags and branches are used: `6.<revision>` tag on master as a watershed between previous and following `PREVIEW`s and `6.<revision>-errata` branch for changes specific to that particular release.
