### ISSUE TITLE
Endianess flag is ignored for read-num*

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#2558]
## The Problem

```perl6
my $b = Buf.new(0x3F, 0x8C, 0xCC, 0xCD);
say $b.read-num32(0, BigEndian);
say $b.read-num32(0, LittleEndian);
```
Prints `-428967904` in **both** cases. For BigEndian this should be `1.1`.

Rakudo 2018.12.

**Comment by AlexDaniel** [comment]
@lizmat

**Comment by AlexDaniel** [comment]
> is all very new and still a work in progress

Please keep the bug reports coming anyway, I think it will be easier to fix things this way.

**Comment by bbkr** [comment]
Maybe https://github.com/perl6/roast/blob/master/S03-buf/read-num.t should have specific fixed values compare output to. Currently it checks if output is not zero, which allows bugs as this one to pass undetected.

**Comment by lizmat** [comment]
Yeah, that was on the todo list  :-)   Patches welcome!

**Comment by jnthn** [comment]
> Please keep the bug reports coming anyway, I think it will be easier to fix things this way.

Oh, absolutely; pointing out the relative newness of these things wasn't intended to mean feedback isn't wanted; it is. :-)

**Comment by niner** [comment]
Fixed with https://github.com/MoarVM/MoarVM/commit/1404d51680e01938d123713caea853641d725b05 https://github.com/perl6/nqp/commit/b0d32b635badbbadc693af6da1f5f90312e92ba1 and https://github.com/perl6/nqp/commit/86dbca4eab48223ca860ed1826931f911c5c5b27
