### ISSUE TITLE
Native libraries not found on openSUSE

### ISSUE THREAD

**Issue by ryn1x** [rakudo/rakudo#2566]
## The Problem
Modules using NativeCall cannot find installed library files on openSUSE.

It seems in openSUSE libraries can be named like `libgtk-3.so.0` or `libgtk-3.so.0.2402.0` instead of just `libgtk-3.so`.

https://en.opensuse.org/openSUSE:Shared_library_packaging_policy

## Expected Behavior
Modules using NativeCall can find installed libraries in openSUSE without modifying their name.

## Actual Behavior
Error stating cannot locate native library.

## Steps to Reproduce
```
sudo zypper in libgtk-3-0
zef install GTK::Simple
.
.
.
Cannot locate native library 'libgtk-3.so': libgtk-3.so: cannot open shared object file: No such file or directory
```

If i then `sudo cp /usr/lib64/libgtk-3.so.0 /usr/lib64/libgtk-3.so` GTK::Simple installs without errors.

I am assuming this is a NativeCall bug, but if I am wrong let me know and I can move this issue to GTK::Simple.

## Environment
* Operating system: openSUSE Tumbleweed
* Compiler version (`perl6 -v`): `This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.`

**Comment by jonathanstowe** [comment]
Yeah, arguably this is an issue with GTK::Simple as it avoids looking for the versioned library.  Somewhere I started looking at a way of specifying a number of acceptable library versions for something else, I'll try to remember to dig it out.

**Comment by ryn1x** [comment]
@niner thanks for that. You are completely right. The library works fine with gtk3-devel. Looks like it was user-error. Sorry =/
