### ISSUE TITLE
Junction concat infix:<~> should be Cool

### ISSUE THREAD

**Issue by fecundf** [rakudo/rakudo#2568]
## The Problem
Concatenating a number with a junction fails with an LTA error
```
3 ~ ( 5 | '18' )
Type check failed for return value; expected Str:D but got Junction (any("35", "318"))
  in block <unit> at <unknown file> line 1
```

## Expected Behavior
result of `any('35','318')`
a better-behaved similar op:
```
3 + ( 5 | '18' )
any(8, 21)
```
**OR**
A better error message, eg
_Did you mean 3 ~~ ... ? If you want string concatenation, use 3.Str ~ ..._

## Discussion
[perl-6 users list says...](https://www.nntp.perl.org/group/perl.perl6.users/2018/12/msg6373.html)
I think the fix is to coerce Cool to Str, eg `Str(Cool:D), Junction:D` and similar as candidates for the `~` operator.

I now think `Str(Any:D)` is too accepting- someone coding @short-array ~ ($option1 | $option2) ought to be more explicit, as that could be programmer error.

**OR**
Narrow the error to "If you really mean to string-concat a junction with a non-string, then convert the non-string explicitly using .Str. Because maybe you meant to say non-string ~~ Junction"

## Environment
* OSX, Rakudo Star version 2018.10 built on MoarVM version 2018.10 implementing Perl 6.c.

**Comment by lizmat** [comment]
Fixed with 0368fe95be

**Comment by lizmat** [comment]
Not sure where one would add tests for this.  Haven't been able to find the place where `infix:<~>` is actually tested among the 236 test files that actually have the string " ~ " in them.

**Comment by lizmat** [comment]
tests added with https://github.com/perl6/roast/commit/dbd19e9b39  moritz++ for pointer
