### ISSUE TITLE
Missing "is already bound to an outer symbol" compilation error when (re)declarations with list assignment are done

### ISSUE THREAD

**Issue by chromis** [rakudo/rakudo#2570]
It seems that I have discovered a bug - or rather an omitted "re-declaration check" - related to using variables that will be re-declared later in the same scope during a list assignment. Consider the following snippet of code that yields a compilation error that I expect:

```
my $foo = 3;

say $foo;
say "^ #1\n";

{
    say $foo;
    say "^ #2\n";

    die if defined $foo;

    my $foo = 6;

    say $foo;
    say "^ #3\n";
}

say $foo;
say "^ #4\n";
```
The compilation error:

```
===SORRY!=== Error while compiling /storage_q/projects/KR/perl/6/language/./myscope.p6
Lexical symbol '$foo' is already bound to an outer symbol;
the implicit outer binding must be rewritten as OUTER::<$foo>
before you can unambiguously declare a new '$foo' in this scope
at /storage_q/projects/KR/perl/6/language/./myscope.p6:14
------>     my $foo⏏ = 6;
    expecting any of:
        constraint
```

I (inadvertently) found a way to suppress this error by changing the 'inner assignment'...

```
my $foo = 6;
```
... to:
```
my ($foo) = 6;
```
... then the output will become:

```
3
^ #1

(Any)
^ #2

6
^ #3

3
^ #4
```
That really puzzled me because I was working on a much larger program that just compiled but gave very confusing results... when I managed to isolate the syntax that underpinned my issue I then decided to ask a question about this on the `perl6-users` mailing list (date/time: 27 Dec 2018, 09:29 - subject: '_Basic question about lexical binding in relationship with "list assignment"_'). During the discussion I was advised to open this issue.

## The Problem
Consider the following program file:
```
my $foo = 3;

{
    say $foo; my ($foo) = 6;
}
```

## Expected Behavior
I expected the same `Lexical symbol '$foo' is already bound to an outer symbol;` compilation error as provided before.

## Actual Behavior
This program gets actually compiled and `$foo` is "undefined" (assuming that is the proper term here) before it gets redeclared and assigned the value 6.

### Steps to Reproduce
Running this/these program(s) on Rakudo 2018.12 (I got my version via `rakudobrew`).

## Environment
* Operating system: Debian 8.11, kernel 3.16.0-7-amd64
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
```

**Comment by jnthn** [comment]
Fixed, and test added in https://github.com/perl6/roast/commit/dd1b3a8b3c.
