### ISSUE TITLE
WARNING: unhandled Failure detected in DESTROY when runtime module loading

### ISSUE THREAD

**Issue by aeruder** [rakudo/rakudo#2572]
This looks similar to #1515 but I can no longer get the test case there to reproduce and it is referencing another issue that has been closed.

## The Problem

Running the following testcase dies:

```
==> Bar.pm <==
say "Loaded Bar";

==> Baz.pm <==
say "Loaded Baz";

==> Foo.pm <==
say "Loaded Foo";

==> Makefile <==
a:
	rm -fr .precomp && perl6 -I. main.p6

==> main.p6 <==
for <Foo Bar Baz> -> $module_name {
    require ::($module_name);
}
```

Adding `unit module ...` to each module - works.  Loading less than 3 distinct modules - works.

## Expected Behavior

```
$ make
rm -fr .precomp && perl6 -I. main.p6
Loaded Foo
Loaded Bar
Loaded Baz
```

## Actual Behavior

```
$ make
rm -fr .precomp && perl6 -I. main.p6
Loaded Foo
Loaded Bar
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol 'Foo'
  in block <unit> at main.p6 line 2

Loaded Baz
```

## Steps to Reproduce

Run above testcase.

## Environment
* Operating system: OS X High Sierra
* Compiler version (`perl6 -v`):
```
This is Rakudo version 2018.12-70-g501231ee4 built on MoarVM version 2018.12-8-g45d15efe9
implementing Perl 6.d.
```

**Comment by aeruder** [comment]
Maybe the failure makes sense, but not the part that it fails on just 1/3?

**Comment by lizmat** [comment]
What happens if you do:

    BEGIN require ::($_) for <Foo Bar Baz>;

aka, run the import at compile time, rather than at runtime?

**Comment by lizmat** [comment]
Assuming this is fixed, pleas re-open if not
