### ISSUE TITLE
How foreign is ForeignCode?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2575]
[This issue in `perl6/doc` requests documentation of `ForeignCode`](https://github.com/perl6/doc/issues/2528) 

The class itself does not seem to be in the design documents. However, it's `normal` [in Roast](https://github.com/perl6/roast/blob/master/S02-types/WHICH.t), but it's tested only for existence, not about particular features. It's [defined as part of Core](https://github.com/rakudo/rakudo/blob/master/src/core/ForeignCode.pm6) but its [implementation seems to be implementation specific](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/BOOTSTRAP.nqp).

I guess, then, that the *existence* of the class is spec, its place in the hierarchy is too, but the rest is not. Is that correct? Any other hint on how to document it?

**Comment by lizmat** [comment]
FWIW, that test in roast is one of mine from the early days of my involvement in Rakudo Perl 6.  I had no specific intent to adding it, just that I knew it existed and that we *maybe* should test for its existence.  If it is deemed to be implementation specific, then I have no problem whatsoever removing it from that list (which, BTW, is wildly outdated now).

**Comment by JJ** [comment]
So maybe the question is really how spec is the whole ForeignCode class.

**Comment by jnthn** [comment]
It was introduced in Rakudo to give us a Perl 6 type that we could use to wrap up code objects defined outside of Perl 6, such as all of those implemented in NQP, to allow them to be more easily passed around inside of Perl 6 code. So in that sense it's Rakudo-specific, and was only speculated in design docs to the degree that it was pointed out that the meta-level can have implementation-defined elements.

Other implementations may choose to do things differently, and Rakudo may itself change to make coming across `ForeignCode` less likely, by trying to better fake up Perl 6 `Method` objects on methods defined directly on user-visible types (though I don't think exploring this is high on anybody's priority list). Even then, once you go doing introspection of meta-objects (so, the `.HOW.HOW` level), we'd still have things that need wrapping in `ForeignCode`. Again, in theory, another implementation might find a way to do differently, but it's highly unlikely this aspect of the Rakudo/NQP meta-space is going to change a great deal any time soon.

**Comment by lizmat** [comment]
So I guess that brings back the question: should `ForeignCode` be documented, or should it be marked as an implementation detail and thus have its mention removed from Roast?

**Comment by jnthn** [comment]
I don't think it should be mentioned in Roast. As for documentation, it's the usual toss-up between "helping people who stumble into it and want to look it up" vs. "only documenting things that are spec". I'm not sure what the current position on that is (I know there's been some resistance to documenting Rakudo-specific things, though on the other hand NativeCall seems very well covered, so I guess it's maybe considered on a case-by-case basis).

**Comment by lizmat** [comment]
Removed mention of `ForeignCode` from roast with https://github.com/perl6/roast/commit/249bf80b05 and https://github.com/perl6/roast/commit/7d5fd40040

Leaving it up to @JJ as to whether to document this as a Rakudo specific feature, or nor document at all.  FWIW, I would be +1 on documenting as a Rakudo specific internal feature.

**Comment by JJ** [comment]
Thanks @lizmat @jnthn !

The usual rule of thumb is that if someone requests it should be documented
and it's somehow exposed to the public, it should be documented, so I guess
that's what we'll do in this case.

**Comment by jonathanstowe** [comment]
But documenting ties the hands of implementors and/or causes overhead for documentors if  it goes away when the underlying design is changed.  I'd go with some language like _"from time to time introspection of built in types may reveal further undocumented types, these are likely to be implementation specific and are subject to change and should not be relied on in user code"_

Or alternatively give these things a ```.gist``` that says ```(Implementation Detail, Ignore)``` ;-)
