### ISSUE TITLE
LTA error message when parsing a META6.json file

### ISSUE THREAD

**Issue by rabbitisle** [rakudo/rakudo#2591]
## The Problem
When parsing an invalid META6.json file it would be nice if we got an informative message of what's wrong with the file. 

## Expected Behavior
We would be getting an informative message e.g. `Invalid META6.json - Mandatory field 'description' is missing`.

Friendly Comment: I'd like to comment that as a newcomer to perl6 I spent a significant amount of time searching for a clear specification of what's needed on a META6.json file. I found [this synopsis](https://design.perl6.org/S22.html#META6.json) and [this documentation](https://docs.perl6.org/language/modules) among others but they are not complete/up-to-date. For example source-type and source-url are not even mentioned but required in META6. I had to copy from another project to create a successful META6.json file. 

## Actual Behavior
Currently we get a generic message stating an error:

`Invalid JSON found in META6.json`

This message does not make it clear if the json syntax is invalid -e.g. missing a comma - or a mandatory field is missing such as `name`. This makes it hard to detect errors on the META6.json file. What makes this even harder is the lack of clear documentation regarding the META6.json file (that's another issue with documentation not belonging here). 

## Steps to Reproduce
Invalidate a META6.json file,  such as the following, by removing a field such as source-type or by removing a required comma in order to malform the json file:
```
{
    "perl"        : "6",
    "name"        : "Monetary::Amount",
    "version"     : "6.*",
    "description" : "A Perl 6 module for money and currency representation",
    "provides"    : {
        "Monetary::Currency": "lib/Monetary/Currency.pm6",
        "Monetary::Amount": "lib/Monetary/Amount.pm6"
    },
    "depends"     : [ ],
    "source-type" : "git",
    "source-url" : "git://test.test/TODOCHAGE.git"
}
``` 

## Environment
* Operating system: Windows
* Compiler version (`perl6 -v`):  `This is Rakudo Star version 2018.10 built on MoarVM version 2018.10
implementing Perl 6.c`

**Comment by rabbitisle** [comment]
@jonathanstowe Thank you for the suggestion, I'll give it a go. 

Also, I could potentially try to fix this issue if it's deemed a legitimate thing to fix and if I get some pointers on which part I should get working.

**Comment by lizmat** [comment]
FWIW, I've opened a documentation issue for this: 
https://github.com/perl6/doc/issues/2543

**Comment by ugexe** [comment]
source-url and source are *not* required. Rakudo has no reason to require those fields. I’m not sure zef will even install something with an invalid meta ( which is where such a check should be if not Test::META itself ).

**Comment by rabbitisle** [comment]
@ugexe Just to clarify, are you saying that `source-url` and `source-type` are not required according to the specification or are not required in the current implementation of Rakudo? If it's the second case I can confirm that removing either from the example file above causes the error.

**Comment by ugexe** [comment]
I'm saying both. For instance [here](https://github.com/perl6/roast/blob/1c121e979b14e2fb8c8120e6438eb9b78192f20a/S11-repository/curli-install.t#L25-L29) are two distributions being installed without declaring a source-url, source-type, source, etc.

**Comment by rabbitisle** [comment]
@ugexe Please correct me if I'm wrong as I'm new to perl6 but what happens in the link is that the installation correctly happens with only 4 fields. However, this example does not test the transformation from json to a hash which seems to be much stricter than the specification. It seems to me that the parsing/transformation of the META6.json file in Rakudo is much stricter than it should be as it fails for `source-url` for example. 

If that's truly the case then it should be filed as a bug.

**Comment by ugexe** [comment]
[Here](https://github.com/perl6/roast/blob/1c121e979b14e2fb8c8120e6438eb9b78192f20a/S11-repository/cur-candidates.t#L151) is a different example, [again](https://github.com/perl6/roast/blob/1c121e979b14e2fb8c8120e6438eb9b78192f20a/S11-repository/cur-candidates.t#L134-L146) with no source, source-url, etc.

**Comment by rabbitisle** [comment]
@ugexe You're right, it works as you said originally. I've not removed the trailing comma as you said. Apologies for that!

**Comment by JJ** [comment]
@rabbitisle I've clarified a bit the documentation, including which fields are mandatory, which are "customary" (meaning they might be used in the module ecosystem) and which are optional, or even ignored (as is the case of source-type). Please check the site in a while to see if it addresses your concern now.

**Comment by rabbitisle** [comment]
@JJ Thanks Juan, that's much better now.
