### ISSUE TITLE
[wishlist] Make Signatures and Parameters first class citizens

### ISSUE THREAD

**Issue by scovit** [rakudo/rakudo#2594]
## The Problem

It is very complicated to dynamically create Parameter and Signature objects in code. At the moment, this task requires reverse engineering and writing nqp code setting up all the attributes correctly. In contrast, typing Signature literals is very easy (using the :() syntax) but does not cover all the use cases. A particularly interesting use-case is to link at runtime to frameworks providing functions and type informations such as Cocoa or GObject.

## Example use case

With nativecast it is already possible to link to an exported C function symbol at runtime, this allow, for instance, this code to run:
```
dlsym(Pointer, Str --> Pointer) is native { };
my $point = dlsym(Pointer.new(0), "puts");
my &f = nativecast( :( Str --> int32), $point);
f("ciao")
```
This issue aims at completing this functionality, and allowing the following code to also work:

```
my $par1 = Str;
my $ret    = int32;

dlsym(Pointer, Str --> Pointer) is native { };
my $point = dlsym(Pointer.new(0), "puts");
my &f = nativecast(
      Signature.new(
            parameters => (
                  Parameter.new(nominal_type => $par1, flags => $SIG_ELEM_MULTI_INVOCANT),
            ),
            returns => $ret
      ), $point
);
f("ciao")
```

## Expected Behavior
I think it should work

## Details
Both Signature and Parameter are defined in BOOTSTRAP.nqp and expanded in core, World.nqp contains the nqp code to create Signature and Parameter used by the Perl compiler.

**Comment by lizmat** [comment]
Wouldn't `$SIG_ELEM_MULTI_INVOCANT` need to be externalized as well then?  Or some interface to it?

**Comment by lizmat** [comment]
So if I understand your request: you want `Parameter` and `Signature` to become first class citizens, *without* spilling too much of the internals.

**Comment by scovit** [comment]
Yes: it would be great to have a nice interface and the multi invocant is very internal. I think that this is not trivial because many properties of the parameters, including this, are there just to serve the signature.

For my task, making `Signature` a first class citizen might be enough. This might be easier.

**Comment by scovit** [comment]
E.g.

```
      Signature.new(
            parameters => (
                  Str,
            ),
            multi-invocants => 1,
            returns => $ret
      ), $point
```
and multi-invocants can default to the number of parameters

**Comment by scovit** [comment]
also parameters can be a map to allow names and types at the same type. I really think the API should be decided by somebody with more insight than me.

**Comment by vrurg** [comment]
If anybody going to count votes on this, take mine, pls! I didn't get enough time and guts to go as deep, as @scovit managed to.

**Comment by lizmat** [comment]
First stab at making `Parameter` a first class citizen: 3d3578b605

**Comment by scovit** [comment]
Thank you @lizmat ! I think your code still needs some work: for some reason it cannot create a signature with an imported type (e.g. `Pointer`):

```
$ perl6 -Ilib -MNativeCall -e 'use nqp; my $type = Str; say $type; say Parameter.new(type => $type)'
Str $

$ perl6 -Ilib -MNativeCall -e 'use nqp; my $type = Pointer; say $type; say Parameter.new(type => $type)'
Failure $
```

**Comment by lizmat** [comment]
Fixed with c4723cbafa .

**Comment by lizmat** [comment]
BTW, `Parameter.new(type => $par1` should be enough now: the `$SIG_ELEM_MULTI_INVOCANT` is set unless inhibited by specifying `exclude => True` or of course `:exclude`.

**Comment by scovit** [comment]
Great, I think it is a very good job! I keep the issue open for now to do some extra testing.

**Comment by lizmat** [comment]
Commits so far caused `NativeCall` breakage for `Parameter` objects that got roles mixed in.  This has been fixed in e463518924

**Comment by scovit** [comment]
Do you have any objection to add support for binding also the `$!sub_signature` attribute? This is quite common and useful in `NativeCall` to define callbacks, and in general for de-structuring arguments.

**Comment by lizmat** [comment]
No, I don't  :-)   How would you propose to do that?

**Comment by lizmat** [comment]
Just add a `sub-signature => Signature:D` parameter ?

**Comment by scovit** [comment]
Yes, that would do the job 👍

**Comment by lizmat** [comment]
Added with 7be075eb59

**Comment by lizmat** [comment]
(Untested, I might add :-)

**Comment by lizmat** [comment]
Fixed with 081b15ee9e

**Comment by lizmat** [comment]
Any other things that need to be implemented?  Or can this ticket be closed now?

**Comment by scovit** [comment]
Thank you for asking, I close the ticket since what has been done is working for me
