### ISSUE TITLE
Return type check using captured type.

### ISSUE THREAD

**Issue by TopherCooper** [rakudo/rakudo#2595]
## The Problem
Using a captured type as the return type of a routine does not work -- captured value is not used.  Note, this is probably related to #1417, but is a different manifestation.

## Expected Behavior
When a captured type T is used as the return type check on a sub (or method, etc.) the returned value should be type checked against T.

## Actual Behavior
The type parameter itself, not its binding, is used in the return type check.

### Basic example:
File: capturedReturns.pl6
--------------------------------------------------
```perl6
   use v6;

   # capturedReturns.pl6  Topher Cooper
   # Demonstration of type capture returns check bug/infelicity.

   sub binder(::T $x --> T)
   {
       say "Binder({T.^name} {$x}) called.";
       return $x;
   }

   say "Calling binder(18).";
   say binder(18).perl;
   CATCH
   {
       default
       {
           put $_.^name, ': ', $_.Str;
           put "    value = {$_.got().gist},";
           put "    expected an object of type = {$_.expected().^name}.";
       }
   };
```
--------------------------------------------------
Result of running capturedReturns.pl6
--------------------------------------------------
```
$ perl6 capturedReturns.pl6
Calling binder(18).
Binder(Int 18) called.
X::TypeCheck::Return: Something went wrong in (Return)
    value = 18,
    expected an object of type = T.
```
--------------------------------------------------
One possible culprit would be some kind of scoping issue, but this is unlikely.

### Using a closure to expand scope.
File: capturedClosureReturns.pl6
--------------------------------------------------
```perl6
use v6;

# capturedClosureReturns.pl6  Topher Cooper
# Demonstration of type capture in closure returns check
# bug/infelicity.

sub closureFactory(::T)
{
    say "closureFactory(::{T.^name}) called.";
    sub binder(T $x --> T)
    {
        say "Binder({T.^name} {$x}) called.";
        return $x;
    }
}

my $binder = closureFactory(Int);

say $binder(18).perl;
CATCH
{
    default
    {
        put $_.^name, ': ', $_.Str;
        put "    value = {$_.got().gist},";
        put "    expected an object of type = {$_.expected().^name}.";
    }
};
```
--------------------------------------------------
Result of running capturedClosureReturns.pl6
--------------------------------------------------
```
$ perl6 capturedClosureReturns.pl6
closureFactory(::Int) called.
Binder(Int 18) called.
X::TypeCheck::Return: Something went wrong in (Return)
    value = 18,
    expected an object of type = T.
```
--------------------------------------------------
### Workaround: subset declaration.
File: capturedClosureReturnsWSubset.pl6
--------------------------------------------------
```perl6
use v6;

# capturedClosureReturnsWSubset.pl6  Topher Cooper
# Demonstration of use of subset to workaround type capture returns
# check bug/infelicity.

sub closureFactory(::T)
{
    say "closureFactory(::{T.^name}) called.";
    my subset RT of Any where { $_ ~~ T };
       # NOTE "my subset RT of T" does not work.
    return
       sub binder(::T2 $x --> RT)
       {
           say "Binder({T2.^name} {$x}) called.";
           return $x;
       };
}

my $binder = closureFactory(Int);

say 'Calling $binder(18).';
say $binder(18).perl;

say 'calling $binder(1.8).';
{
    say $binder(1.8).perl;

    CATCH
    {
        default
        {
            put $_.^name, ': ', $_.Str;
        }
    }
}
```
--------------------------------------------------
Result of running capturedClosureReturnsWSubset.pl6
--------------------------------------------------
```
$ perl6 capturedClosureReturnsWSubset.pl6
closureFactory(::Int) called.
Calling $binder(18).
Binder(Int 18) called.
18
calling $binder(1.8).
Binder(Rat 1.8) called.
X::TypeCheck::Return: Type check failed for return value; expected RT but got Rat (1.8)
```

## Steps to Reproduce
Run the three pl6 files shown above and included in this zip file.
[capturedReturns.zip](https://github.com/rakudo/rakudo/files/2742092/capturedReturns.zip)

## Environment
* Operating system:  Windows 10.
* Compiler version (`perl6 -v`):
   Rakudo Star: v 2018.10
   built on MoarVM: v 2018.10
   implementing: Perl 6.c

**Comment by usev6** [comment]
This seems to work nowadays:
```
$ ./rakudo-m -e 'sub binder(::T $x --> T) { say "Binder({T.^name} {$x}) called."; return $x; }; say "Calling binder(18)."; say binder(18).perl;'
Calling binder(18).
Binder(Int 18) called.
18
$ ./rakudo-m -e 'sub closureFactory(::T) { say "closureFactory(::{T.^name}) called."; sub binder(T $x --> T) { say "Binder({T.^name} {$x}) called."; return $x; } }; my $binder = closureFactory(Int); say $binder(18).perl'
closureFactory(::Int) called.
Binder(Int 18) called.
18
$ ./rakudo-m -e 'sub closureFactory(::T) { say "closureFactory(::{T.^name}) called."; my subset RT of Any where { $_ ~~ T }; return sub binder(::T2 $x --> RT) { say "Binder({T2.^name} {$x}) called."; return $x; } }; my $binder = closureFactory(Int); say "Calling \$binder(18)."; say $binder(18).perl; say "calling \$binder(1.8)."; say $binder(1.8).perl;'
closureFactory(::Int) called.
Calling $binder(18).
Binder(Int 18) called.
18
calling $binder(1.8).
Binder(Rat 1.8) called.
Type check failed for return value; expected RT but got Rat (1.8)
  in sub binder at -e line 1
  in block <unit> at -e line 1
```

As the linked issues https://github.com/rakudo/rakudo/issues/1417 and https://github.com/rakudo/rakudo/issues/3618 this has very likely been fixed with https://github.com/rakudo/rakudo/pull/5048.

A couple of tests have been added to roast with https://github.com/Raku/roast/commit/eedaf1471a.
I believe that they cover this bug report, so I'm closing this issue as resolved.
