### ISSUE TITLE
Signature smartmatch against capture operator | fails if it contains slurpy hash

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2596]
## The Problem

`*%_` doesn't match properly against `|` in a signature match.

## Actual Behavior

```
sub f ( $a, *%_ ) { }
say &f.signature ~~ :( $, | ) 
```

Outputs _False_.

## Expected Behavior

Must output _True_.

## Environment
* Operating system: macOS 10.14, Linux Mint
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12 built on MoarVM version 2018.12
Tested against 2017.10 with same result.

**Comment by dogbert17** [comment]
Fixed with 66ae8612972efd2

**Comment by lizmat** [comment]
Added test with https://github.com/Raku/roast/commit/6dca656e19
