### ISSUE TITLE
Scope flattening causes inner scope to lose value of topic variable

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#2601]
## The Problem
The inner scope no longer knows the value of $_, prints 'True' instead of '2':

`for 1..3 { { say $_ ; last } if $_ == 2 }`

## Environment
The problem appears with commit [541a4f16](https://github.com/rakudo/rakudo/commit/541a4f1628e4e156f6eefc547938746f7b736104)

This is Rakudo version 2018.12-171-g541a4f162 built on MoarVM version 2018.12-13-g473324ee3
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
**cfa**++ reported that `URI::Encode` is failing. [Blin](https://github.com/perl6/Blin) bisected to the same commit https://github.com/rakudo/rakudo/commit/541a4f1628e4e156f6eefc547938746f7b736104.

However, it's a bit interesting. After attempting to golf we found that this code changed its behavior:
```
my $rr = rx/<[bc]>/; say "abcd".comb.map({ so $rr })
```
But that golf bisected to (2019-01-03) https://github.com/rakudo/rakudo/commit/eb3917c260bce1cb56e2ee40abebd12c4dbcd9b2, which is a different commit.
```
¦2018.12,eb3917c260bc^: «(False True True False)␤» ¦eb3917c,541a4f1628^,541a4f1,HEAD(d6b1bd2): «(False False False False)␤»
```

Furthermore, that same commit doesn't affect the module! [Proof](https://gist.github.com/20f754f0ea5bbf727281ba89da44232a).

Both commits are part of the same work.

**Comment by AlexDaniel** [comment]
Ah! Alright! Here's a code snippet that's golfed a bit *less* (**cfa**++):

```perl6
my $rx = rx/<[a..z]>/; 'abc'.comb.map({ if $rx { 'yes' } else { 'no' } }).say;
```
And this golf, unlike the one in the comment above, is not affected by https://github.com/rakudo/rakudo/commit/eb3917c260bce1cb56e2ee40abebd12c4dbcd9b2:
```
<AlexDaniel`> c: 2018.12,eb3917c260bc^,eb3917c260bc,541a4f1628^,541a4f1628,HEAD my $rx = rx/<[a..z]>/; 'abc'.comb.map({ if $rx { 'yes' } else { 'no' } }).say;
<committable6> AlexDaniel, ¦2018.12,eb3917c260bc^,eb3917c,541a4f1628^: «(yes yes yes)␤» ¦541a4f1,HEAD(d6b1bd2): «(no no no)␤»
```

**⚠ when adding tests, please test both golfs**

**Comment by jnthn** [comment]
Let's create fresh issues for the regex boolean context issue. The original post is a straight bug that obviously wants fixing. The regex case, we probably do not want to spec; doing so is in contradiction with the design decision made in 6.d that `$_` is no longer dynamically scoped. The best we can probably offer is a migration period.

**Comment by FCO** [comment]
```
<•SmokeMachine> Fernando Corrêa de Oliveira m: say do if 42 { $_ }
00:24 C<•camelia> combined, experimental evalbot rakudo-moar e87b7afb0: OUTPUT: «(LoweredAwayLexical)␤»
```

**Comment by AlexDaniel** [comment]
@jnthn done! Feel free to use this button:
![image](https://user-images.githubusercontent.com/5507503/51094758-593b7180-17b8-11e9-9ee5-48a5efcacad9.png)

**Comment by MasterDuke17** [comment]
> ```
> <•SmokeMachine> Fernando Corrêa de Oliveira m: say do if 42 { $_ }
> 00:24 C<•camelia> combined, experimental evalbot rakudo-moar e87b7afb0: OUTPUT: «(LoweredAwayLexical)␤»
> ```

Bisects to 541a4f16 also.

**Comment by jnthn** [comment]
@AlexDaniel Ooh, I'd not seen that button. Neat!

**Comment by jnthn** [comment]
Both issues - which were distinct - have been resolved and given tests.
