### ISSUE TITLE
Smartmatch doesn't produce correct result on a run-time created class stored in a Scalar container

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2602]
## The Problem

When a class is created with `Metamodel::ClassHOW.new_type` at run-time and stored in a scalar then smartmatching of an object created of this class with the containing scalar gives _False_.

## Expected Behavior

Object must smartmatch its class.

## Steps to Reproduce

This code:

```
my $a = Metamodel::ClassHOW.new_type(name => "A");
$a.^compose;
say $a.new.WHAT ~~ $a
```

prints _False_.

## Environment
* Operating system: macOS 10.14, Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12 built on MoarVM version 2018.12
Also tested against Perl6/MoarVM 2017.10

**Comment by lizmat** [comment]
This appears to be related to the fact that you're putting the class definition into a scalar container by assigning to `$a`.  If you **bind** to `$a`, it appears to work, for me at least.

    my $a := Metamodel::ClassHOW.new_type(name => "A");
    $a.^compose;
    say $a.new.WHAT ~~ $a;    # True

**Comment by vrurg** [comment]
Yes, it does. And this is the advise I gave on IRC and how I fixed similar issue in my own code. But the point is that this works:

```
my $a = class A { };
say $a.new ~~ $a;
```

And I see no reason why creation from the metamodel class must not work either. Here is another interesting variation of the code:

```
my $b = my $a := Metamodel::ClassHOW.new_type(name => "A"); 
$a.^compose; # Use of $b here changes the result
my $o = $a.new;
say $o ~~ $a; 
say $o ~~ $b
```

Depending on whether `compose` is called on `$a` or `$b` the resulting smartmatch gives either both _True_ for `$a`, or both _False_ for `$b`.

**Comment by lizmat** [comment]
Fixed with ab8052dde0 .

**Comment by vrurg** [comment]
Tested with rakudobrew, on moar-blead:

`This is Rakudo version 2018.12-200-gd6b1bd2ae built on MoarVM version 2018.12-27-g9ce36b6a2`

The reported buggy behavior is not reproducible on neither variant of the code I tried. Looks like it's fixed.

**Comment by Altai-man** [comment]
Tests proposed at https://github.com/perl6/roast/pull/540
