### ISSUE TITLE
High memory consumption and crashes when running t/spec/S07-slip/slip.t

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#2606]
## The Problem

The memory consumption when running 

    MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 /usr/bin/time ./perl6  t/spec/S07-slip/slip.t

and

    MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 /usr/bin/time make  t/spec/S07-slip/slip.t

differs markedly on my system. On my 32 bit Linux running the first variant reports

    1..23
    ok 1 - simple | middle
    ok 2 - simple | left
    ok 3 - simple | right
    ok 4 - simple slip middle
    ok 5 - simple slip left
    ok 6 - simple slip right
    ok 7 - simple Slip coercion middle
    ok 8 - simple Slip coercion left
    ok 9 - simple Slip coercion right
    ok 10 - simple Slip coercion middle
    ok 11 - simple Slip coercion left
    ok 12 - simple Slip coercion right
    ok 13 - simple slip listop middle
    ok 14 - simple slip listop left
    ok 15 - simple slip listop right
    ok 16 - slip flat listops middle
    ok 17 - slip flat listops left
    ok 18 - slip flat listops right
    ok 19 - .Slip can slip a long lazy list
    ok 20 - Slip() can slip a one-arg long lazy list
    ok 21 - slip works with one-arg long lazy
    ok 22 - prefix:<|> works with one-arg long lazy
    ok 23 - can .perl.EVAL roundtrip an itemized slip
    10.98user 0.17system 0:11.13elapsed 100%CPU (0avgtext+0avgdata 156748maxresident)k
    0inputs+0outputs (0major+32553minor)pagefaults 0swaps

while the second variant crashes with the following output

    /usr/bin/perl tools/build/check-nqp-version.pl /home/dogbert/repos/rakudo/install/bin/nqp-m
    rm -f -- perl6
    cp -- perl6-m perl6
    chmod -- 755 perl6
    /usr/bin/perl t/harness5 --fudge --moar --keep-exit-code --verbosity=1 t/spec/S07-slip/slip.t
    
    ok 1 - simple | middle
    ok 2 - simple | left
    ok 3 - simple | right
    ok 4 - simple slip middle
    ok 5 - simple slip left
    ok 6 - simple slip right
    ok 7 - simple Slip coercion middle
    ok 8 - simple Slip coercion left
    ok 9 - simple Slip coercion right
    ok 10 - simple Slip coercion middle
    ok 11 - simple Slip coercion left
    ok 12 - simple Slip coercion right
    ok 13 - simple slip listop middle
    ok 14 - simple slip listop left
    ok 15 - simple slip listop right
    ok 16 - slip flat listops middle
    ok 17 - slip flat listops left
    ok 18 - slip flat listops right
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 5/23 subtests 
    
    Test Summary Report
    -------------------
    t/spec/S07-slip/slip.t (Wstat: 256 Tests: 18 Failed: 0)
      Non-zero exit status: 1
      Parse errors: Bad plan.  You planned 23 tests but ran 18.
    Files=1, Tests=18, 22 wallclock secs ( 0.03 usr  0.01 sys + 10.81 cusr 11.13 csys = 21.98 CPU)
    Result: FAIL
    make: *** [t/spec/S07-slip/slip.t] Error 1
    Command exited with non-zero status 2
    10.98user 11.17system 0:22.10elapsed 100%CPU (0avgtext+0avgdata 2994652maxresident)k
    0inputs+8outputs (0major+10027340minor)pagefaults 0swaps

As can be seen the maxresident numbers are vastly different and this leads to an out of memory failure.

On 64 bit systems the second variant doesn't crash, instead it hangs bringing my vm to a crawl.

With the help of AlexDaniel's++ bisectable wizardry a suspect commit has been identified, i.e. https://github.com/rakudo/rakudo/pull/1812/commits/3a68cc9618bf8dd57a633bbd782990e5b5810a69

## Expected Behavior

Both variants, see above, should behave more or less the same wrt to memory consumption, the time it takes to run them and the result of the run

## Actual Behavior

See above

## Steps to Reproduce

See above

## Environment
* Operating system: Ubuntu 14.04.3 LTS
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12-206-g7be075eb5 built on MoarVM version 2018.12-29-g1ff55bf1c implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
> With the help of AlexDaniel's++ bisectable wizardry a suspect commit has been identified, i.e. 3a68cc9

Note that this is technically when the issue became visible, see [proof](https://gist.github.com/Whateverable/9e5c198de40e5b87df3eb2193e9451e4). But the commit itself is likely innocent.

**Comment by jnthn** [comment]
A couple of questions:

1. Does this happen with a standard configuration (e.g. no `NODELAY`)?
2. Does setting `PERL6LIB=lib` cause the high memory use? I believe the harness sets that.

**Comment by dogbert17** [comment]
Setting MVM_SPESH_INLINE_DISABLE=1 seems to resolve the problem, i.e.

    MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 MVM_SPESH_INLINE_DISABLE=1 PERL6LIB=lib ...
