### ISSUE TITLE
Cannot specify a parameterized class (e.g., Array[Str]) as a class parent

### ISSUE THREAD

**Issue by TopherCooper** [rakudo/rakudo#2611]
## The Problem
If a parameterized class is specified as a parent, it is parsed incorrectly.  Apparently the square brackets are taken as an additional argument, specifically an Array literal.

Contents of file illustrating the problem:
    use v6;
    
    class StrArray is Array[Str] {}

## Expected Behavior
Either no error message, a NYI message, or (if I missed something documented somewhere -- could easily be the case) an error message saying that a parameterized type cannot be a class parent.

## Actual Behavior
 
    ===SORRY!=== Error while compiling C:/.../quickTest.pl6
    Cannot resolve caller trait_mod:<is>(StrArray, Array, Array); none of these signatures match:
        (Mu:U $child, Mu:U $parent)    
    
            ... All signatures for trait "is" ...

        (Routine $r, Str :$looser!)
    at C:/ ... /quickTest.pl6:3

This also occurs if using the also declarator or creating a class using the meta object protocol.
## Steps to Reproduce
Cut, paste run.

## Environment
* Operating system: Windows 10.

* Compiler version (`perl6 -v`): 
    Rakudo Star: v 2018.10
    built on MoarVM: v 2018.10
    implementing: Perl 6.c

**Comment by lizmat** [comment]
spectesting a fix

**Comment by lizmat** [comment]
Fixed with 35ecfc8e24

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/e58a55d5b9
