### ISSUE TITLE
Astro::Sunrise, wrong paths in META6.json and CURFS changes

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2618]
https://github.com/perlpilot/p6-Astro-Sunrise fails to install in Blin.

Output:
```
===> Searching for: Astro::Sunrise
===> Found: Astro::Sunrise:ver<0.0.1> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Astro::Sunrise:ver<0.0.1> to /home/alex/Blin/data/zef-data/tmp/1547756891.22313.6058/p6-Astro-Sunrise.git
===> Extraction [OK]: Astro::Sunrise to /home/alex/Blin/data/zef-data/store/p6-Astro-Sunrise.git
===> Testing: Astro::Sunrise:ver<0.0.1>
===SORRY!===
Failed to open file /home/alex/Blin/data/zef-data/store/p6-Astro-Sunrise.git/10f748bfe733fbc5081b019533c83ed5b003176d/lib/Astro/Sunrise.pm: No such file or directory
t/01basic.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/01basic.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.42 cusr  0.04 csys =  0.49 CPU)
Result: FAIL
===> Testing [FAIL]: Astro::Sunrise:ver<0.0.1>
Failed to get passing tests, but continuing with --force-test
```

It bisected to https://github.com/rakudo/rakudo/commit/b378a157ebc000c35ed9ea2702050ad4de6d23a4. I'm not 100% confident about that result, but the commit looks related.

The issue seems to be that the path is:
```
lib/Astro/Sunrise.pm6
```

But in META6.json:
```
        "Astro::Sunrise" : "lib/Astro/Sunrise.pm"
```

So it is `pm6` vs `pm`. It does seem like something that needs to be fixed in the module, but then, why did it work previously? *EDIT: actually… did it?*

Ping @ugexe. Any thoughts?

**Comment by ugexe** [comment]
Its tests only worked because it depended on (obviously) broken behavior. Sure, the tests might have passed previously, but installation itself would have always failed.

**Comment by AlexDaniel** [comment]
@ugexe I see, thanks.

I confirmed that the module wasn't installable. There is a PR with a fix here: https://github.com/perlpilot/p6-Astro-Sunrise/pull/1
Unfortunately I can't transfer the module to perl6-community-modules because there's no license attached. The module is a port of a perl5 module, and the perl5 module is based on code that is in public domain. That, however, doesn't give us any rights to fork & change the perl 6 module at will, so we will have to leave it as is.

**Comment by lizmat** [comment]
FWIW, perhaps we should contact the next of kin to formally ask for permission?  Having known Scott Duff personally, I don't think he would have a problem with a transfer.  If anything, he would have welcomed it, as it would make sure his work would continue on.

**Comment by AlexDaniel** [comment]
> If anything, he would have welcomed it, as it would make sure his work would continue on.

That's my understanding as well, but we can't do anything until we actually have a permission from the current copyright owner. If you can get one, that'd be great. Also we should probably take a look at other repos by @perlpilot++.

**Comment by jonathanstowe** [comment]
FWIW I maintain ```Term::ReadKey``` which was in a similar position and I've mostly stuck to the line I describe in https://github.com/jonathanstowe/TermReadKey/issues/11#issuecomment-226739042  it's tricky but unless you genuinely know what the authors original intent was beyond what was expressed in the explicit licence terms then you just have to work with it.
