### ISSUE TITLE
Installing Zef with rakudobrew on Mac sometimes fails with  Cannot invoke this object (REPR: Null; VMNull)

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2625]
## The Problem
See title.

## Expected Behavior
Zef should install.

## Actual Behavior
Installing Zef sometimes fails with this error:
```
===SORRY!===
Cannot invoke this object (REPR: Null; VMNull)
Failed running /Users/travis/.rakudobrew/bin/../moar-master/install/bin/perl6 -Ilib bin/zef test . at /Users/travis/.rakudobrew/bin/rakudobrew line 57.
	main::run('/Users/travis/.rakudobrew/bin/../moar-master/install/bin/perl...') called at /Users/travis/.rakudobrew/bin/rakudobrew line 494
	main::build_zef() called at /Users/travis/.rakudobrew/bin/rakudobrew line 351
	main::build_impl('zef', undef, '') called at /Users/travis/.rakudobrew/bin/rakudobrew line 115
```

## Steps to Reproduce

Install Zef with rakudobrew.

## Environment
* Operating system: 
macOS 10.13
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.12-238-g99d30be2a built on MoarVM version 2018.12-35-gc001ce23c

**Comment by lizmat** [comment]
FWIW, I've seen Rakudo's `make install` fail with the same error message about 1 in 20 times.  Just running it again then works (well, haven't had it fail yet two times in a row)

**Comment by vrurg** [comment]
@Kaiepi I think this shouldn't be a problem anymore. Can we just close this ticket?
