### ISSUE TITLE
P6Repl::Helper and return type annotations

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2636]
When running tests in P6Repl::Helper module:
```
# Failed test 'testing ll a sub'
# at t/01-basic.t line 51
# expected: 'proto sub substr($, $?, $?, *%)
# multi sub substr(\what)
# multi sub substr(\what, \from)
# multi sub substr(\what, \from, \chars)
# '
#      got: 'proto sub substr($, $?, $?, *%)
# multi sub substr(\what --> Str:D)
# multi sub substr(\what, \from --> Str:D)
# multi sub substr(\what, \from, \chars --> Str:D)
# '
# Looks like you failed 1 test of 10
```

> \<timotimo\> the P6Repl::Helper problem is just testing output from an introspection for a sub that has since gotten return type annotations
> \<timotimo\> so LHF :)

This is not an issue in Rakudo, it's just that the module tests are too specific. Just [submit a PR for the module](https://github.com/kjkuan/P6Repl-Helper) that makes tests work on new **and** old versions of rakudo.

**Comment by AlexDaniel** [comment]
@lizmat you are absolutely correct, but please don't unmark such tickets. It doesn't take much time and it keeps the ecosystem in a much better state. Note that insignificant failures like this make the whole module go off radar for Blin. Also, the module author may not know that there is a problem because they are unlikely to run latest rakudo from master, so it's a good idea to send a PR before the release (this way there'd be less disruption for maintained/used modules). Also note that I've been doing this for all rakudo releases.

See also: [unbitrot squashathons](https://github.com/perl6/ecosystem-unbitrot) .

Here's a PR https://github.com/kjkuan/P6Repl-Helper/pull/1.

This is now resolved.

**Comment by lizmat** [comment]
"@lizmat you are absolutely correct, but please don't unmark such tickets"

Understood.
