### ISSUE TITLE
Tests in Sake module and dynamic $_

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2639]
```perl6
sub test-run() {
    my $cwd = CALLERS::(‘$_’); # ‘foo’
    dd $cwd;
}

given ‘foo’ {
    test-run
}
```
Output:
```
Rakudo::Internals::LoweredAwayLexical $cwd = Rakudo::Internals::LoweredAwayLexical
```

Bisected: eb3917c260bce1cb56e2ee40abebd12c4dbcd9b2

This comes from an actual module (in fact I wrote that code…):
* https://github.com/perl6/p6-sake/blob/08ce6c0628cd3332af726043c955b175d7b4b24a/t/30-help.t#L16-L19
* https://github.com/perl6/p6-sake/blob/08ce6c0628cd3332af726043c955b175d7b4b24a/t/lib/SakeTester.pm6#L19

@jnthn++'s comment from a related ticket: https://github.com/rakudo/rakudo/issues/2608#issuecomment-455200826

Adding `use v6.c` in the test files resolves the problem for the module. I'll do exactly that a bit later, but opening a ticket anyway for potential discussion.

**Comment by jnthn** [comment]
This one is precisely the case that we removed spectests for as part of 6.d.

**Comment by AlexDaniel** [comment]
Yeah. Resolved by adding `use v6.c` in test files of the module (only tests themselves were affected, the module itself is fine).
