### ISSUE TITLE
META6.json causes an issue when it's in lib (why?)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2641]
1. Clone [JSON::WebToken](https://github.com/jamesalbert/JSON-WebToken)
2. Run `PERL6LIB=lib perl6 t/01_basic.t` and you'll get an error (shown below)
3. Rename `META6.json` file in the root directory of the repo to anything else, like `NOT-META6.json`
4. The error goes away.

Error:
```
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in any statement_control at /home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in any statement_control at /home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
===SORRY!===
Cannot resolve caller new(IO::Path:U: Any:U, :CWD(Str)); none of these signatures match:
    (IO::Path: Str $path, :$SPEC = { ... }, Str:D :$CWD, *%_)
    (IO::Path: Str $path, :$SPEC = { ... }, :$CWD = { ... }, *%_)
    (IO::Path: Cool $path, :$SPEC = { ... }, :$CWD = { ... }, *%_)
    (IO::Path: :$basename!, :$dirname = "", :$volume = "", :$SPEC = { ... }, :$CWD = { ... }, *%_)
    (IO::Path: *%_)
```

The test file has this:
```perl6
use lib '.';
```
So that's why files in the cwd play some role, but is it wrong to have a META6.json file in your lib?

This issue did not exist in 2018.12.

Ping @ugexe.

**Comment by ugexe** [comment]
It is expecting the directory ‘.’ to act as two separate distributions: lib/ and t/Util.pm6

Instead the test should require $?FILE.parent.add(‘Util.pm’) or use lib $?FILE.parent.absolute

**Comment by AlexDaniel** [comment]
@ugexe can you elaborate a little bit? For example, why did it work before?

**Comment by ugexe** [comment]
Because now it doesn't ignore the META6.json if one exists, whereas before it would ignore the META6.json if the file existed and wasn't in the META6.json. The META6.json is authority, so if it exists it then it gets used. Otherwise there is no way to test using only the modules you have declared without installing them first, among other things.

**Comment by AlexDaniel** [comment]
I submitted a PR that resolves the issue for the module. Removing the blocker label as I don't it affects anything else (please prove me wrong :) ).

However, the error message is really weird, and IMO can be improved.

**Comment by ugexe** [comment]
This now gives the compile time error:
```
===SORRY!===
Could not find t::Util at line 4 in:
    /Users/ugexe/repos/rakudo/JSON-WebToken
    /Users/ugexe/repos/rakudo/JSON-WebToken/lib
    /Users/ugexe/.perl6
    /Users/ugexe/repos/rakudo/install/share/perl6/site
    /Users/ugexe/repos/rakudo/install/share/perl6/vendor
    /Users/ugexe/repos/rakudo/install/share/perl6
    CompUnit::Repository::AbsolutePath<140608224271232>
    CompUnit::Repository::NQP<140608214995880>
    CompUnit::Repository::Perl5<140608214995920>
```

**Comment by AlexDaniel** [comment]
Looks nice. I've added `testneeded` in case we can have tests for this, but feel free to handle this ticket any way you want.

**Comment by 2colours** [comment]
> Because now it doesn't ignore the META6.json if one exists, whereas before it would ignore the META6.json if the requested module-file existed and wasn't in the META6.json. The META6.json is authority, so if it exists it then it gets used.

@ugexe This causes problems for modules that have a dependency that they use while testing as well, doesn't it? How to allow them to still use those dependencies so that the `zef test .` part can finally pass?

**Comment by ugexe** [comment]
That’s just a bad idea. They should put such dependencies in e.g. t/lib and include that in their tests

**Comment by 2colours** [comment]
It seems a much worse idea to hardwire the source of an external (mind you) module into your testing.

Anyway, it seems that an external module *can* actually be looked up if the distribution depends on it; it's just the error message gave a bad hint about the problem.

**Comment by ugexe** [comment]
Yeah I dunno what to tell you, “it seems” doesn’t really explain to me what you’re confused about. Wiring up a test dependency as I describe is a perfectly reasonable thing to do. If you need to use that dependency outside of those tests then you create a new distribution to be properly shared across e.g. different versions of whatever distribution you are testing.

**Comment by 2colours** [comment]
> Wiring up a test dependency as I describe is a perfectly reasonable thing to do

It's not a "test dependency" but a real external dependency. A module that appears in the "dependencies" section of the META6 json file.
