### ISSUE TITLE
Algorithm::LibSVM and segfaults

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2642]
When installing [Algorithm::LibSVM](https://github.com/titsuki/p6-Algorithm-LibSVM) some of the test files are segfaulting:
```
free(): double free detected in tcache 2
Aborted
```
Or just:
```
Segmentation fault
```

Blin bisected it to 685f6cc3b6af59a7df92fcd33eef5f1cc36e34de, but there were some zef-related issues during the process so most likely it's not this commit. Also, the module relies on nativecall so maybe the issue is not in rakudo, **but** the module used to install cleanly on 2018.12.

No stacktrace yet.

**Comment by dogbert17** [comment]
dogbert@dogbert-VirtualBox ~/repos/p6-Algorithm-LibSVM $ perl6 -v
    This is Rakudo version 2018.12-297-g84ed854 built on MoarVM version 2018.12-94-g2eab275
    implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~/repos/p6-Algorithm-LibSVM $ ASAN_OPTIONS=detect_leaks=0 zef install Algorithm::LibSVM
    ===> Searching for: Algorithm::LibSVM
    ===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Building: Algorithm::LibSVM:ver<0.0.3>
    ===> Building [OK] for Algorithm::LibSVM:ver<0.0.3>
    ===> Testing: Algorithm::LibSVM:ver<0.0.3>
    =================================================================
    ==7309==ERROR: AddressSanitizer: attempting double-free on 0x6020002a5f10 in thread T0:
        #0 0x7f69cb0352ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
        #1 0x7f69c24d4d7c in svm_destroy_param (/home/dogbert/.zef/store/Algorithm-LibSVM-0.0.3.tar.gz/Algorithm-LibSVM-0.0.3/resources/libraries/libsvm.so+0xbd7c)
        #2 0x7f69ca20e231  (//home/dogbert/.rakudobrew/moar-master/nqp/MoarVM/../../install/lib/libmoar.so+0x9d0231)
    
    0x6020002a5f10 is located 0 bytes inside of 16-byte region [0x6020002a5f10,0x6020002a5f20)
    freed by thread T0 here:
        #0 0x7f69cb0352ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
        #1 0x7f69ca011446 in MVM_free src/core/alloc.h:40
        #2 0x7f69ca011446 in gc_cleanup src/6model/reprs/CArray.c:140
        #3 0x7f69ca011446 in gc_free src/6model/reprs/CArray.c:147
        #4 0x7f69c9f6d45f in MVM_gc_collect_free_nursery_uncopied src/gc/collect.c:620
        #5 0x7f69c9f5d888 in finish_gc src/gc/orchestrate.c:241
        #6 0x7f69c9f5d888 in run_gc src/gc/orchestrate.c:413
        #7 0x7f69c9f5fa0c in MVM_gc_enter_from_allocator src/gc/orchestrate.c:526
        #8 0x7f69c9f60164 in MVM_gc_allocate_nursery src/gc/allocation.c:35
        #9 0x7f69c9f6081e in MVM_gc_allocate_object src/gc/allocation.c:89
        #10 0x7f69c9fa5762 in MVM_repr_clone src/6model/reprconv.c:32
        #11 0x7f69c9ef9258 in MVM_frame_vivify_lexical src/core/frame.c:1259
        #12 0x7f69c375a6d4  (<unknown module>)
        #13 0x7f69c9ebbe48 in MVM_interp_run src/core/interp.c:6140
        #14 0x7f69ca186756 in MVM_vm_run_file src/moar.c:444
        #15 0x40184f in main src/main.c:302
        #16 0x7f69c949482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    
    previously allocated by thread T0 here:
        #0 0x7f69cb03579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
        #1 0x7f69ca0104cf in MVM_calloc src/core/alloc.h:11
        #2 0x7f69ca0104cf in initialize src/6model/reprs/CArray.c:95
        #3 0x7f69c9edc8c1 in MVM_interp_run src/core/interp.c:1848
        #4 0x7f69ca186756 in MVM_vm_run_file src/moar.c:444
        #5 0x40184f in main src/main.c:302
        #6 0x7f69c949482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    
    SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_free
    ==7309==ABORTING
    ASAN:SIGSEGV
    =================================================================
    ==7313==ERROR: AddressSanitizer: SEGV on unknown address 0x0001000000b1 (pc 0x7f870b252c34 bp 0x7ffc111d2a18 sp 0x7ffc111d29e0 T0)
        #0 0x7f870b252c33 in svm_free_model_content (/home/dogbert/.zef/store/Algorithm-LibSVM-0.0.3.tar.gz/Algorithm-LibSVM-0.0.3/resources/libraries/libsvm.so+0xbc33)
        #1 0x7f870b252d58 in svm_free_and_destroy_model (/home/dogbert/.zef/store/Algorithm-LibSVM-0.0.3.tar.gz/Algorithm-LibSVM-0.0.3/resources/libraries/libsvm.so+0xbd58)
        #2 0x7f8712f8d231  (//home/dogbert/.rakudobrew/moar-master/nqp/MoarVM/../../install/lib/libmoar.so+0x9d0231)
    
    AddressSanitizer can not provide additional info.
    SUMMARY: AddressSanitizer: SEGV ??:0 svm_free_model_content
    ==7313==ABORTING
    ===> Testing [FAIL]: Algorithm::LibSVM:ver<0.0.3>
    Aborting due to test failure: Algorithm::LibSVM:ver<0.0.3> (use --force-test to override)

**Comment by AlexDaniel** [comment]
So that's an issue in the module and we shouldn't do anything about it in Rakudo, is that correct?

**Comment by jnthn** [comment]
@AlexDaniel It looks that way to me.

**Comment by AlexDaniel** [comment]
OK.

If there's any new information regarding this issue, please let me know.
