### ISSUE TITLE
Something going on in Data::StaticTable

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2643]
There's something going on with [Data::StaticTable](https://github.com/shinobi/Data-StaticTable) but I don't know what exactly yet. Basically, [some of the test files](https://github.com/shinobi/Data-StaticTable/issues/4) are known to flap, but on HEAD it's consistently bad. For example, `t/StaticTable-examples.t` is now failing even though previously it didn't (I think…).

Not bisected, and no golf of the issue. Feel free to dive in.

**Comment by lizmat** [comment]
This appears to be related to the use of `rx/foo/` as a "matcher" parameter to a custom `grep` method, which in turn uses grep with `$_` and the "matcher" parameter that assumes it can match with `$_`:

    https://github.com/shinobi/Data-StaticTable/blob/master/lib/Data/StaticTable.pm6#L320
    https://github.com/shinobi/Data-StaticTable/blob/master/lib/Data/StaticTable.pm6#L325

I'm not sure if this is supposed to work like this or not.  Perhaps @jnthn knows / can decide.

**Comment by jnthn** [comment]
> I'm not sure if this is supposed to work like this or not. Perhaps @jnthn knows / can decide.

Under 6.c semantics, yes; under 6.d ones, including with the proposed refinement in #2608, no.

**Comment by jnthn** [comment]
Um, to be clear, that could work with 6.c semantics, but not the 6.d ones.

**Comment by AlexDaniel** [comment]
I submitted a PR here: https://github.com/shinobi/Data-StaticTable/pull/5

However, the label remains for now. See https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-01-29#l74

**Comment by AlexDaniel** [comment]
Ah, this one is fixed, as far as I can see. Some tests are needed, I think, but otherwise everything is good.
