### ISSUE TITLE
Multi-dispatcher erroneously can't figure out default value of typed container

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#2645]
## The Problem

This works:
~~~~
perl6 -e 'sub foo ($foo, Str :@bar) { say $foo }; foo(1)'
~~~~

This dies with a "Cannot resolve caller foo(Int:D); none of these signatures match:" error:
~~~~
perl6 -e 'multi foo ($foo, Str :@bar) { say $foo }; foo(1)'
~~~~

These do work though:
~~~~
perl6 -e 'multi foo ($foo, Str :@bar = Array[Str].new) { say $foo }; foo(1)'
perl6 -e 'multi foo ($foo, Str :@bar) { say $foo }; foo(1, bar => Array[Str].new)'
~~~~

## Expected Behavior

I expect all multis to behave the same as onlys.

## Actual Behavior

A multi with a parameterized container argument fails to dispatch

## Environment
````
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
````

**Comment by jnthn** [comment]
I don't think it's specific to multiple dispatch, but rather that named parameters cause it to use the signature binder to disambiguate, and:

```
$ ./perl6-m -e 'sub foo (Str :@bar []) {}; foo()'
Type check failed in binding to parameter '@bar'; expected Positional[Str] but got Array ($[])
  in sub foo at -e line 1
  in block <unit> at -e line 1
```

The `[]` there forces the slow-path binder to be used, and exposes the problem also.

**Comment by dogbert17** [comment]
Fixed with the merge of new-disp, i.e. dd2b274fd59f
