### ISSUE TITLE
Supply eats all values from Channel, not allowing reuse across multiple react blocks

### ISSUE THREAD

**Issue by kbucheli** [rakudo/rakudo#2646]
## The Problem
The data from a channel is not received anymore if the same react/whenever block is executed twice.

## Expected Behavior
The second execution should receive the second item in the channel.

## Actual Behavior
nothing is received

## Steps to Reproduce
```
#!/usr/bin/env perl6

my $execute_max = 2;
my $timeout = 10;

my $channel = Channel.new;

$channel.send(1);
$channel.send(2);

my $worker = start {
    for (1..$execute_max) {
        my $timed-out = False;
        react {
            note "try to receive $channel ";
            whenever $channel {
                note "received from backfill-channel $_";
                done;
            }
            whenever Promise.in($timeout) {
                note "timed out";
                $timed-out = True;
                done;
            }
        }
        last if $timed-out;
    }
    note "finishing worker";
};

await($worker);
note "workers done, remaining in Channel: " ~ $channel.poll.gist;
```
outputs
```
try to receive Channel<139662271319664> 
received from backfill-channel 1
try to receive Channel<139662271319664> 
timed out
finishing worker
workers done, remaining in Channel: Nil
```
remark: if it would be possible to set a timeout on Channel.receive I would not have found the bug ;-)

## Environment
* Operating system: custom Linux 
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
```

**Comment by lizmat** [comment]
A simple one liner appears to do what is documented:

    my $c = Channel.new; $c.send($_) for ^2; $c.close; react { whenever $c { .say } }; say "done"
    0
    1
    done

So looks it's some interaction with the timeout.

**Comment by lizmat** [comment]
Please disregard previous comments: I think I understand what happens.

When you use a `Channel $c` in a `whenever`, you are in fact processing values coming in from a `$c.Supply.tap`.  This supply grabs **all** of the values of the `Channel` and starts emitting them.  This `Supply` however, is closed when the `done` is executed.  So it ate all the values, but only produced one before being discarded.  The next iteration in the loop will then create a new `Supply`, which will now wait for things to happen on a Channel that is not getting any new values, thus creating the described behaviour.

I think this could be fixed by mixing in the created `Supply` into the `Channel` object, so that it can continue with the `Supply` in the next iteration, and only close the `Supply` if the `Channel` it is associated with is also closed.

@jnthn Is that a solution to this problem?  Or is there a better way?

**Comment by lizmat** [comment]
Alas, a naive way of keeping the `Supply` with the `Channel` does not fix this issue:

    diff --git a/src/core/Channel.pm6 b/src/core/Channel.pm6
    index 6e190f2..2b1b13a 100644
    --- a/src/core/Channel.pm6
    +++ b/src/core/Channel.pm6
    @@ -12,6 +12,7 @@ my class Channel does Awaitable {
         # The queue of events moving through the channel.
         my class Queue is repr('ConcBlockingQueue') { }
         has $!queue;
    +    has $!supply;

         # Promise that is triggered when all values are received, or an error is    
         # received and the channel is thus closed. 
    @@ -115,7 +116,7 @@ my class Channel does Awaitable {
     
         method Capture(Channel:D:) { self.List.Capture }
         multi method Supply(Channel:D:) {
    -        supply { 
    +        $!supply //= supply {
                 # Tap the async notification for new values supply.
                 whenever $!async-notify.unsanitized-supply.schedule-on($*SCHEDULER)
                     my Mu \got = self.poll;

**Comment by lizmat** [comment]
@jnthn: Why does Channel.Supply eat all of the values?  Shouldn't that just hook into the async.notify and then receive?  That should work with just a single Tap?

**Comment by kbucheli** [comment]
I created a unit test:

```
#!/usr/bin/env perl6

use Test;
plan 1;

my $channel = Channel.new;

$channel.send(1);
$channel.send(2);

react whenever $channel { done }

is $channel.poll, 2, 'second value should still be in the channel';
```

**Comment by jnthn** [comment]
I'll be away for a few days, so won't be able to poke at it for a bit, but I'd perhaps try a patch in this direction:

```
diff --git a/src/core/Channel.pm6 b/src/core/Channel.pm6
index 6e190f2..9b58d4e 100644
--- a/src/core/Channel.pm6
+++ b/src/core/Channel.pm6
@@ -116,8 +116,11 @@ my class Channel does Awaitable {
     method Capture(Channel:D:) { self.List.Capture }
     multi method Supply(Channel:D:) {
         supply {
+            my $closed = False;
+
             # Tap the async notification for new values supply.
             whenever $!async-notify.unsanitized-supply.schedule-on($*SCHEDULER) {
+                done if $closed;
                 my Mu \got = self.poll;
                 if nqp::eqaddr(got, Nil) {
                     if $!closed_promise {
@@ -137,6 +140,7 @@ my class Channel does Awaitable {
             # not result in a notification, and so we'd not emit it on
             # the supply. This lost event can then cause a deadlock.
             loop {
+                done if $closed;
                 my Mu \got = self.poll;
                 last if nqp::eqaddr(got, Nil);
                 emit got;
@@ -147,6 +151,10 @@ my class Channel does Awaitable {
                     ?? done()
                     !! die $!closed_promise.cause
             }
+
+            CLOSE {
+                $closed = True;
+            }
         }
     }
```

**Comment by kbucheli** [comment]
I can confirm that the patch fixes the issue aka makes the unit test pass.

Due to the time passed the patch moved a bit:

```
diff --git a/src/core.c/Channel.pm6 b/src/core.c/Channel.pm6
index 9a8b3e7cf..35e24fd96 100644
--- a/src/core.c/Channel.pm6
+++ b/src/core.c/Channel.pm6
@@ -119,8 +119,11 @@ my class Channel does Awaitable {
     method Capture(Channel:D:) { self.List.Capture }
     multi method Supply(Channel:D:) {
         supply {
+            my $closed = False;
+
             # Tap the async notification for new values supply.
             whenever $!async-notify.unsanitized-supply.schedule-on($*SCHEDULER) {
+                done if $closed;
                 my Mu \got = self.poll;
                 if nqp::eqaddr(got, Nil) {
                     if $!closed_promise {
@@ -149,6 +152,7 @@ my class Channel does Awaitable {
             # `last if ...` check in this loop is still essential.
             my int $initial-items = nqp::elems($!queue);
             while $initial-items-- {
+                done if $closed;
                 my Mu \got = self.poll;
                 last if nqp::eqaddr(got, Nil);
                 emit got;
@@ -159,6 +163,10 @@ my class Channel does Awaitable {
                     ?? done()
                     !! X::AdHoc.new( payload => $!closed_promise.cause ).throw
             }
+
+            CLOSE {
+                $closed = True;
+            }
         }
     }
 
```
Shall the test be added somewhere? Shall I prepare a PR? To whereabout?

**Comment by jnthn** [comment]
Merged both fix and tests; thank you!
