### ISSUE TITLE
IO::Path.dir gives numeric error in message

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#2649]
## The Problem

When `IO::Path.dir` encounters an error, the error message gives a numeric error instead of an error string. Like this example:

## Expected Behavior
~~~~
Failed to get the directory contents of '/var/spool/cups': Permission denied
~~~~

## Actual Behavior
~~~~
Failed to get the directory contents of '/var/spool/cups': Failed to open dir: 13
~~~~

## Steps to Reproduce
~~~~
"/var/spool/cups".IO.dir
~~~~

## Environment
Rakudo 2018.12

**Comment by jnthn** [comment]
Partial (POSIX only) fix added. Also created https://github.com/MoarVM/MoarVM/issues/1041 after glancing the `strerror` docs.

**Comment by jonathanstowe** [comment]
The Windows CRT has a strerror IIRC.

**Comment by Leont** [comment]
I think this can be closed
