### ISSUE TITLE
WhateverCode.pos is not tested

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2651]
## The Problem

[`WhateverCode` has a `pos`](https://github.com/rakudo/rakudo/blob/master/src/core/WhateverCode.pm6) method that is not tested.

## Expected Behavior

It's probably Rakudo specific, since [it does not seem to be defined in the synopsis](https://design.perl6.org/S02.html#The_WhateverCode_Types).

## Environment

Current source code at the date of posting this issue.

**Comment by lizmat** [comment]
`Block.pos` and `WhateverCode.pos` are intended as internal methods.  I have therefore renamed them to `.POSITIONS` ( in ccf350e4bc ) to better indicate that they are internal.  Making them private method is unfortunately not an option.

As far as I'm concerned, this issue can now be closed.

**Comment by JJ** [comment]
Thanks a lot, Liz.
