### ISSUE TITLE
Disallow making new Perl 6 tickets on rt.perl.org?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2652]
Now that basically all new Rakudo / Perl 6 issues occur on Github, I think it's a good idea that we should at least disallow making new tickets on rt.perl.org.

**Comment by AlexDaniel** [comment]
Yes, but please remove all references of RT first. I believe there are still places that list RT as an option.

For those who wonder what the justification for that proposal is, here are some stats:
* All tickets of year 2018: https://gist.github.com/Whateverable/00ee88af2c114763fec630c792f6b287#all-new-tickets-1254
* Only 33 of 1254 tickets/patches are on RT, which is 2.6%.
* 33 may sound like a lot, but Jul..Dec there **was just one ticket**. That is, just one ticket in half a year, with a downward trend.

One way to argue against this is to say that github requires an account, while on RT you can create a ticket just but mailing it. I remember TimToady himself praising that feature. However, I'm very sorry to say this, but 1 ticket in 6 months is not a good justification for all the spam that we have to deal with. FYI, I keep deleting tickets from https://fail.rakudo.party/ (which is a useful resource for me), and while it doesn't take much time, I'd much rather let that single ticket not be submitted…

**Comment by jnthn** [comment]
> Jul..Dec there was just one ticket

I think that number speaks for itself.

> Yes, but please remove all references of RT first. I believe there are still places that list RT as an option.

Maybe we can replace them with some text like "If you are unwilling to make a GitHub account, contact us on the #perl6-dev IRC channel on freenode.org." If the traffic is one bug report per 6 months, I think we can handle accepting it in that unconventional way.

**Comment by lizmat** [comment]
https://github.com/perl6/doc/commit/e24031ed4b

**Comment by rspier** [comment]
FYI, rt.perl.org went read-only for Perl6 bugs ~4 months ago.

**Comment by AlexDaniel** [comment]
OK then.

Further discussion here: https://github.com/perl6/problem-solving/issues/49
