### ISSUE TITLE
Is the "dynext" directory used?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2653]
There's a single file, and the commit modifying it is 10 years old.

**Comment by JJ** [comment]
It's apparently used here: https://github.com/rakudo/rakudo/blob/89fee86acec7feaf2b70843416c513f2a4bac5f6/tools/build/Makefile-Moar.in#L107
Maybe add some .gitignore with file types and a comment to avoid deletion?

**Comment by jnthn** [comment]
Eventually, the extops will go away, and this will no longer be needed, but that's probably quite a few months away at earliest.
