### ISSUE TITLE
Cryptic error when parametrizing Bufs with non-native types

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2655]
## The Problem

    my $b = Buf[Int].new( 3, -3, 44, -44)

fails with

    MVMArray: bindpos expected object register

Ditto for UInt and possibly other non-native Integer types.

## Expected Behavior

From these lines:

https://github.com/rakudo/rakudo/blob/master/src/core/Buf.pm6#L18-L20

it looks as it any Int is OK; from the next lines it would seem as if as long as they have use a multiple of 8, is OK. However, the exception is not caught there.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

    This is Rakudo version 2018.11 built on MoarVM version 2018.11

Same problem occurs with newer versions, though.

**Comment by lizmat** [comment]
Fixed with 7133b81e4f , adapted tests as well, so can be closed as far as I am concerned.

**Comment by JJ** [comment]
Great, thanks!

**Comment by lizmat** [comment]
JJ: could you privmsg me re next weekend (FOSDEM & Squashathon?)

**Comment by JJ** [comment]
Unfortunately, I'm not attending FOSDEM this year... I'll send you a
message anyway.
