### ISSUE TITLE
isa-ok does not work with parametrized types

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2656]
## The Problem

Further to what's indicated in #2259 , it does not work with parametrized types:

    isa-ok(Buf[uint64],Buf[uint64], "OK" )

Fails:

```
# Failed test 'OK'
# at <unknown file> line 1
# Actual type: Buf[uint64]
```

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

```
This is Rakudo version 2018.12-130-gcbc3e72 built on MoarVM version 2018.12-13-g473324e
```

**Comment by jnthn** [comment]
This is correct; `isa-ok` compares inheritance, but `Buf[uint64]` is a parameterized role.

**Comment by JJ** [comment]
Then, is there a test that works on this case?

**Comment by jnthn** [comment]
Yes, `does-ok`:

```
$ perl6 -e 'use Test; does-ok Buf[uint8], Buf[uint8]'
ok 1 - The object does role 'Buf[uint8]'
```

**Comment by JJ** [comment]
Ok, thanks. Isa-OK works anyway for non-parametrized types, if I remember
correctly

**Comment by jonathanstowe** [comment]
Maybe a more generalised (say,) ```type-ok```  that tries both is in order.
