### ISSUE TITLE
Accidental use of 'is' with a role in class declaration causes 'No concretization' error

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2659]
## The Problem

If by a class is inheriting from a role instead of doing it then class-qualified calls to role methods fail with 'No concretization found' exception.

## Steps to Reproduce

The following code demosntrated the problem:

     role R2 {
         method foo {
             "R2::foo"
         }
     }
     class Foo is R2 {
         method foo {
             say "Foo::foo" ~ callsame;
         }
     }
     Foo.new.foo;

## Environment
* Operating system: macOS, Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12 built on MoarVM version 2018.12
_Also tested on 2018.08 and 2017.10_

**Comment by jonathanstowe** [comment]
Neither for me, I was  expecting  'Did you mean to use "does" instead?'' but I guess it is punned somehow before adding the new parent.  If that is the case is there a way of having the role to indicate that it shouldn't be inherited from as I'm pretty sure the difference between the two may be significant in some cases.

**Comment by lizmat** [comment]
To prevent a role from being punned, `::?ROLE.HOW.archetypes..inheritalizable` should return a false value at compile time.  It will then die with a `X::Inheritance::Unsupported` exception.  Leaving this as an exercise to the reader on how to make that happen, and what syntactic sugar we will devise for that.

**Comment by jonathanstowe** [comment]
Need a new trait word : ```isn't``` so we can have ```role Foo isn't inheritalizable { }``` ;-)

**Comment by jnthn** [comment]
Use of a role with `is` is a deliberate feature, and actually the point of `inheritalizable` ("am I able to turn this into something I can inherit from?") even existing. The result is to pun the role, and then inherit from that.

The `callsame` behavior looks a bit broken, however.

**Comment by vrurg** [comment]
I'm very sorry for a mistake. While playing with different variants of the code I chose a wrong one to post. The problematic version is following:

     role R2 {
         method foo {
             "R2::foo"
         }
     }
     class Foo is R2 {
         method foo {
             say "Foo::foo", self.R2::foo;
         }
     }
     Foo.new.foo;

And it fails on blead as well as on 2018.12.

**Comment by lizmat** [comment]
FWIW, this gives the same error:

    role R2 {
        method foo {
            "R2::foo"
        }
    }
    my constant R3 = R2.^pun;
    class Foo is R3 {
        method foo {
            say "Foo::foo", self.R2::foo;
        }
    }
    Foo.new.foo;

which indicates to me that the `self.R2::foo` syntax is not looking for a punned `R2`

**Comment by vrurg** [comment]
Pull request #2675 fixes this issue as well as two other with similar sympthoms.

**Comment by jnthn** [comment]
Merged PR and also tests in https://github.com/perl6/roast/pull/510/commits/6b3d51ce878ef495ad9584b12285c909073847b0 cover this.
