### ISSUE TITLE
self is corrupted when calling a role method with .&

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2661]
## The Problem

This is kind of a followup to #2657. While trying to work around that problem I decided to get the method directly from the role and call it on `self`. This kind of worked except that role's method `self` happens to be the role type object itself.

## Steps to Reproduce

The following code demonstrates the problem:

     role R2 {
         method foo {
             note "R2 self: ", self.WHICH;
         }
     }
     class Foo does R2 {
         method foo {
             my &m = R2.^find_method( 'foo' );
             note "Foo self: ", self.WHICH;
             self.&m;
             &m( self );
         }
     }
     Foo.new.foo;

It outputs the following:

> ```
> Foo self: Foo|140291225759552
> R2 self: R2|U140291240572832
> R2 self: R2|U140291240572832
> ```

## Environment
* Operating system: macOS, Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12 built on MoarVM version 2018.12

**Comment by vrurg** [comment]
I've done some further investigation which revealed that `$?CLASS` is corrupt with some, er..., _funny_ side effects. Here is the modified code from the report:

     role R2 {
         has $.attr is rw;
         method foo {
             note "R2 self: ", self.WHICH;
             note '\$?CLASS: ', $?CLASS.WHICH;
             try $.attr = 42;
             if $! {
                 note "\$.attr failure: ", $!
             }
             else {
                 note "\$.attr is set";
             }
             try $!attr = 42;
             if $! {
                 note "\$!attr failure: ", $!
             }
             else {
                 note "\$!attr is set";
             }
         }
     }
     class Foo does R2 {
         method foo {
             note "Direct role lookup:";
             my &m = R2.^find_method( 'foo' );
             note "Foo self: ", self.WHICH;
             self.&m;
             &m( self );

             note "\nLookup via ^roles";
             my \r = self.^roles.grep( *.^name eq 'R2'  )[0];
             note "FOUND ROLE: ", r.WHICH;
             &m = r.^candidates[0].^lookup('foo');
             self.&m;
         }
     }

     Foo.new.foo;

The point is to try another approach: locate the role in `^roles` list and then get the method using the finding.

And here is it's output:

> 
> ```
> Direct role lookup:
> Foo self: Foo|140325299598960
> R2 self: R2|U140325300437640
> \$?CLASS: R2|U140325300437640
> $.attr failure: Invocant of method 'attr' must be an object instance of type 'Mu', not a type object of type 'R2'.  Did you forget a '.new'?
>   in method foo at role.p6 line 6
>   in method foo at role.p6 line 27
>   in block <unit> at role.p6 line 38
> 
> $!attr failure: Cannot look up attributes in a R2 type object
>   in method foo at role.p6 line 13
>   in method foo at role.p6 line 27
>   in block <unit> at role.p6 line 38
> 
> R2 self: R2|U140325300437640
> \$?CLASS: R2|U140325300437640
> $.attr failure: Invocant of method 'attr' must be an object instance of type 'Mu', not a type object of type 'R2'.  Did you forget a '.new'?
>   in method foo at role.p6 line 6
>   in method foo at role.p6 line 28
>   in block <unit> at role.p6 line 38
> 
> $!attr failure: Cannot look up attributes in a R2 type object
>   in method foo at role.p6 line 13
>   in method foo at role.p6 line 28
>   in block <unit> at role.p6 line 38
> 
> 
> Lookup via ^roles
> FOUND ROLE: R2|U140325300436752
> R2 self: Foo|140325299598960
> \$?CLASS: R2|U140325300437640
> $.attr is set
> $!attr failure: P6opaque: no such attribute '$!attr' on type R2 in a Foo when trying to get a value
>   in method foo at role.p6 line 13
>   in method foo at role.p6 line 34
>   in block <unit> at role.p6 line 38
> ```

At first it looked as if things are ok now: _Lookup via ^roles_ section has `self` pointing at the invoker. But an attempt to directly reference an attribute causes the _P6opaque: no such attribute_ exception. I'm not sure if `$?CLASS` should point to `R2` here or to `Foo`, but in a more complex code where I've encountered this problem my `$?CLASS` contains a type object of `Metamodel::GenericHOW`! And this is certainly not ok.

**Comment by vrurg** [comment]
Ok, two questions arise then: 

Is the protocol formally described somewhere?

How is it possible to get around #2657 then? It seems to be impossible to reach the method object in a form suitable for `self.&method` call.

**Comment by jnthn** [comment]
> Is the protocol formally described somewhere?

I know that we introduced `.^lookup` specifically because we needed `.^find_method` to have more freedom in what it returned, while it was still desirable to have a way to look up the exact declared thing, and I'm pretty sure that was test-covered, so in the sense of "there are spectests" I think it's described. The docs for `find_method` and `lookup` probably want to mention each other.

> How is it possible to get around #2657 then? It seems to be impossible to reach the method object in a form suitable for self.&method call.

The form that's suitable for that is the concretization - that is, the method as it was after the generic role was made concrete for the target of the composition. The best bet is just to fix #2657 (unfortunately, I'll be away for the next several days, so can't look at it immediately), though if you want something sooner then:

* There might be a way to manually obtain the concretization through `.^concretization` API
* Failing that, the concretization is probably sat somewhere in the `.^role_typecheck_list`, and can be extracted by grepping on name and the meta-object of type `Metamodel::ConcreteRoleHOW`. One could then call `.^find_method` on that, giving the method in the appropriate form.

**Comment by vrurg** [comment]
Thanks! Will be waiting for the fix as all workarounds are too clumsy for the real code.

Alternatively, I'm trying get into the compiler internals with [your presentation](http://edumentab.github.io/rakudo-and-nqp-internals-course/slides-day1.pdf) hoping to produce meaningful patches for the bugs some day.

**Comment by MasterDuke17** [comment]
@vrurg have you seen Zoffix's blog post? It would also be helpful. https://perl6.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6

**Comment by vrurg** [comment]
@MasterDuke17 it's a bit preliminary for this info, but it is certainly useful! Thanks!
