### ISSUE TITLE
implement a new var @*ARGFILES listing paths for @*ARGS that are existing files

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2666]
## The Problem

Iterating over $*ARGFILES throws an error if the system tries to get a handle on a non-existent file.

## Expected Behavior

Ability to iterate over only valid file handles as the name implies.

## Actual Behavior

Throws on non-existent files.

## Steps to Reproduce

```
$ rm t
$ cat t.p6
say($_.path) for $*ARGFILES;
$ perl6 t.p6
Failed to open file /path/to/t: No such file or directory
  in block <unit> at t.p6 line 1
```
## Environment

Debian 9, 64-bit.
$ perl6 -v
This is Rakudo version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.

## Solution

Create the new dynamic variable simultaneously with the creation of @*ARGS. It should contain the paths of the elements of @*ARGS that are existing, readable files.

**Comment by ugexe** [comment]
What does "if the file exist" mean to different users? Does it exist at the time the program starts? Does it exist at the moment it is iterated over  by `$*ARGFILES`? I'm not sure a pragma can properly capture all the valid variations one might consider. Maybe a pragma to make `$*ARGFILES` not open the handles, leaving that to be done by the user explicitly (allowing them a chance to do an existence check and skip if needed). Otherwise a naive solution:
```
BEGIN @*ARGS = @*ARGS.grep(!*.starts-with("-")).grep(*.IO.e);
say($_.path) for $*ARGFILES;
```

**Comment by tbrowder** [comment]
In my naive view, I see $*ARGFILES reflecting the current file state of CLI @*ARGS when the program starts. That's the only way I've used Perl scripts (P5 or P6) in my years of use since 1993.

**Comment by JJ** [comment]
@ugexe It simply means valid filehandles. Right now, as Tom has indicated, $*ARGFILES does create a filehandle for non-existing or invalid files, only nothing can be done with it other than capturing the exception when it's used.

**Comment by lizmat** [comment]
Feels to me `$*ARGFILES` should return a `Failure` rather than throw.

**Comment by tbrowder** [comment]
Yes, then that would satisfy my use case and be a very useful tool, especially if I could iterate it like this

```
for $*ARGFILES -> $handle {
    next if !$handle;
    say $handle.path
}
```

**Comment by ugexe** [comment]
@JJ It was a rhetorical question. What “valid file handle” means isn’t so clear; backlog the chat channel the last few days to see others with a similar informed opinion and explanation.

**Comment by ugexe** [comment]
@JJ It was a rhetorical question. What “valid file handle” means isn’t so clear; backlog the chat channel the last few days to see others with a similar informed opinion and explanation.
