### ISSUE TITLE
Error on .resume

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#2667]
https://colabti.org/irclogger/irclogger_log/perl6?date=2019-02-01#l560

**Comment by ugexe** [comment]
It helps to give more information. It might make sense *now*, but will it in 6 months when anyone working on this needs to know e.g. what versions this affected? Sure the user could cross check dates with releases, but I think including a bit more information by the submitter is a better option.

**Comment by cxw42** [comment]
Another example: https://stackoverflow.com/q/58041372/2877364

**Comment by lizmat** [comment]
This appears fixed.
