### ISSUE TITLE
Remove all AdHoc exceptions from core

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2669]
Often times I find myself in a situation when I want to handle some exceptions but can't do it selectively because something throws an AdHoc.

Here's an example inspired by #2666:
```bash
perl6 'for lines() { .say }; CATCH { default { .WHAT.say } }' foo bar baz
```

If `foo` or any other file does not exist it throws an AdHoc exception with the following text:
```
Failed to open file /home/alex/bar: No such file or directory
  in block <unit> at -e line 1
```

Let's *replace all AdHoc exceptions with proper exceptions* in v6.e.

**Comment by jonathanstowe** [comment]
Yeah, the ad-hoc throwing thing is particular problematic in cases like https://github.com/sergot/http-useragent/issues/205 where an ad-hoc exception is being thrown with a platform specific (possibly localised,) message which makes it difficult to catch specific conditions.

So total; :+1:  for this.

**Comment by alabamenhu** [comment]
I would go even a bit further: remove adhoc reasons/messages for non-adhoc exceptions.

Most exceptions have a single message that they print, but for instance, example, the X::Str::Numeric has three attributes, `source`, `pos`, and `reason`.  The latter has arbitrary content, and prevents, e.g., localized exception messages that are possible with the most other exceptions.  An enumerated reason could preserve stringy behavior while allowing stable introspection/exceptionhandling (the reason may change to fix a LTA message), or just further subtyping it.

**Comment by lizmat** [comment]
Closing in favour of https://github.com/Raku/problem-solving/issues/446
