### ISSUE TITLE
Do we need an overhaul of .ACCEPTS methods wrt Any / Mu?

### ISSUE THREAD

**Issue by lisprog** [rakudo/rakudo#2676]
## The Problem

say so (3,0).one ~~ (1 .. 9)

## Expected Behavior

expected to return True

## Actual Behavior

returns False

## Steps to Reproduce

> say (3,5).any ~~ (1 .. 9)
any(True, True)
> say so (3,5).any ~~ (1 .. 9)
True
> say so (3,5).one ~~ (1 .. 9)
False
> say so (3,0).one ~~ (1 .. 9)  # expect True because 0 not in range and 3 is
False
> say so (3,0).any ~~ (1 .. 9)
True
> say so (0, 3).one ~~ (1..9)   # expected True; 0 not in range; exactly one item (3) is in range
False
> so 0 ~~ 1..9                  # as expected;
False
> so 3 ~~ 1..9
True
> say (0, 3).one ~~ (1..9)      # unexpected; 0 not in range;
one(True, True)                 # expected one(False, True)
> say (1..9).elems
9
> say (0, 10).one ~~ (1..9)     # why is it true that 0 ~~ 1..9 ??
one(True, False)
> say so (0, 10).one ~~ (1..9)  # unexpected !!! neither 0 nor 10 in range
True
> say (-1, 3).one ~~ (1..9)     # why -1 in range of 1..9 ??
one(True, True)
> 

## Environment
* Operating system: 

Linux, Xubuntu 18.04

* Compiler version (`perl6 -v`): 

This is Rakudo Star version 2018.10 built on MoarVM version 2018.10
implementing Perl 6.c.

**Comment by lizmat** [comment]
First research indicates that `Range.ACCEPTS` has a `Mu` candidate, which means it will absorb the `Junction`.  This seems like a leftover from way, way in the past as the last change on that line was in 2012, and that did not change the types in the signature.  It makes much more sense to **not** have a `Mu` there, so I removed that.  This changes the result of:

    $ perl6 -e 'dd (1..9).ACCEPTS(0|3)'
    any(Bool::True, Bool::True)

To:

    any(Bool::False, Bool::False)

Even stranger, it then appears that **none** of the other `Range.ACCEPTS` candidates is being called then.  Continuing the search...

**Comment by lizmat** [comment]
Found the underlying issue.  For some reason, `(2..9).ACCEPTS(1|3)` calls the `Any.ACCEPTS(Any:D: Mu:D)` candidate, rather than the `Range.ACCEPTS(Range:D: Cool:D)` candidate.  @jnthn is that correct?

**Comment by lizmat** [comment]
Ah, duh, the `Junction` matches the `Mu:D` and not the `Cool:D`.

**Comment by lizmat** [comment]
Changing the `Mu:D` in the `Any.ACCEPTS` candidate to `Any:D` breaks the build by because of ambiguous dispatch (the other being the `Code:D:` candidate.

Is the whole hierarchy of `ACCEPTS` methods due for an overhaul, or am I missing something essential?

**Comment by raiph** [comment]
v2018.12

```
    say  (3,    1,    2,    '1',  'a',  '0',   0        ).one ~~ 1..2;
    # one(True, True, True, True, True, False, False)

    say  (3,    1,    2,    '1',  'a',   '0',   0       ).any ~~ 1..2;
    # any(False, True, True, True, False, True, True)

    say  (3,    1,    2,    '1',  'a',  '0',   0        ).all ~~ 1..2;
    # all(True, True, True, True, True, False, False)

    say  (3,    1,    2,    '1',  'a',  '0',   0        ).none ~~ 1..2;
    #none(True, True, True, True, True, False, False)

    say  (3,    1,    2,    '1',  'a',  '0',   0        ).one ~~ 0..2;
    # one(True, True, True, True, True, True, True)

    say  (3,     1,    2,    '1',  'a',   '0',  0       ).any ~~ 0..2;
    # all(False, True, True, True, False, True, True)

    say  (3,    1,    2,    '1',  'a',  '0',   0        ).all ~~ 0..2;
    # all(True, True, True, True, True, False, False)

    say  (3,    1,    2,    '1',  'a',  '0',  0         ).none ~~ 0..2;
    #none(True, True, True, True, True, True, True)

    say  (3,    1,    2,    '1',  'a',  '0',  0         ).one ~~ 'a'..'b';
    # one(True, True, True, True, True, True, True)

    say  (3,    1,    2,    '1',  'a',  '0',  0         ).any ~~ 'a'..'b';
    # any(True, True, True, True, True, True, True)

    say  (3,     1,     2,    '1',    'a',  '0',   0    ).all ~~ 'a'..'b';
    # all(False, False, False, False, True, False, False)

    say  (3,     1,     2,    '1',    'a',  '0',   0    ).none ~~ 'a'..'b';
    #none(False, False, False, False, True, False, False)
```

**Comment by lizmat** [comment]
Added test with https://github.com/Raku/roast/commit/3b4981dd82
