### ISSUE TITLE
Some issue exposed by Chronic

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2683]
See https://github.com/perl6/ecosystem-unbitrot/issues/353

Chronic – Fail, Bisected: 46409c070ec49e0ac15e48613215bcdb258783d0

Ping @lizmat.

**Comment by dogbert17** [comment]
Works for me, could it have been fixed already?

    dogbert@dogbert-VirtualBox ~ $ perl6 -v
    This is Rakudo version 2018.12-293-gd904b70 built on MoarVM version 2018.12-94-g2eab275
    implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~ $ zef install Chronic
    ===> Searching for: Chronic
    ===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Testing: Chronic:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>
    ===> Testing [OK] for Chronic:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>
    ===> Installing: Chronic:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>

**Comment by AlexDaniel** [comment]
Probably! I wonder if any tests were added…

**Comment by jonathanstowe** [comment]
Yep WFM too.

**Comment by lizmat** [comment]
WFM as well.
