### ISSUE TITLE
Some issue exposed by IO::Glob

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2686]
See https://github.com/perl6/ecosystem-unbitrot/issues/560.

IO::Glob – Fail, Bisected: b3eb38261736eb618fb6758e0186eb5c6d48a31d

Fortran::Grammar is also affected by this.

**Comment by lizmat** [comment]
confirmed reverting b3eb382 fixes the problem

**Comment by lizmat** [comment]
Fixed with 9d6e508d0d4b3fd2e36 for now

**Comment by lizmat** [comment]
Confirmed `zef` installs `IO::Glob` cleanly with this change

**Comment by AlexDaniel** [comment]
@lizmat it's still there for Fortran::Grammar
```
===> Searching for: Fortran::Grammar
===> Found: Fortran::Grammar:ver<0.0.6> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Fortran::Grammar:ver<0.0.6> to /home/alex/Blin/data/zef-data/tmp/1549729503.9314.1815/perl6-fortran-grammar.git
===> Extraction [OK]: Fortran::Grammar to /home/alex/Blin/data/zef-data/store/perl6-fortran-grammar.git
===> Testing: Fortran::Grammar:ver<0.0.6>
[31m===[0mSORRY![31m===[0m Error while compiling /home/alex/Blin/installed/IO::Glob_0.6/sources/9B78006EC28345074FD9A0ED374EC5857ADEF036 (IO::Glob)
No such method 'flat' for invocant of type 'IO::Glob'
at /home/alex/Blin/installed/IO::Glob_0.6/sources/9B78006EC28345074FD9A0ED374EC5857ADEF036 (IO::Glob):445
t/FortranBasic.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/FortranBasic.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  2 wallclock secs ( 0.01 usr  0.01 sys +  2.83 cusr  0.17 csys =  3.02 CPU)
Result: FAIL
===> Testing [FAIL]: Fortran::Grammar:ver<0.0.6>
Failed to get passing tests, but continuing with --force-test
===> Installing: Fortran::Grammar:ver<0.0.6>
===> Install [OK] for Fortran::Grammar:ver<0.0.6>
```

**Comment by lizmat** [comment]
I cannot reproduce:

$ zef install Fortran::Grammar
===> Searching for: Fortran::Grammar
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Testing: Fortran::Grammar:ver<0.0.6>
===> Testing [OK] for Fortran::Grammar:ver<0.0.6>
===> Installing: Fortran::Grammar:ver<0.0.6>
$

**Comment by dogbert17** [comment]
Works for me as well:

    dogbert@dogbert-VirtualBox ~/repos/perl6-IO-Glob $ perl6 -v
    This is Rakudo version 2018.12-308-g5b62bb1 built on MoarVM version 2018.12-110-g04982f6
    implementing Perl 6.d
    dogbert@dogbert-VirtualBox ~/repos/perl6-IO-Glob $ zef install IO::Glob
    ===> Searching for: IO::Glob
    ===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Testing: IO::Glob:ver<0.6>:auth<github:zostay>
    ===> Testing [OK] for IO::Glob:ver<0.6>:auth<github:zostay>
    ===> Installing: IO::Glob:ver<0.6>:auth<github:zostay>
    dogbert@dogbert-VirtualBox ~/repos/perl6-IO-Glob $ zef install Fortran::Grammar
    ===> Searching for: Fortran::Grammar
    ===> Testing: Fortran::Grammar:ver<0.0.6>
    ===> Testing [OK] for Fortran::Grammar:ver<0.0.6>
    ===> Installing: Fortran::Grammar:ver<0.0.6>

**Comment by AlexDaniel** [comment]
Yeah, it works now. Weird.
