### ISSUE TITLE
NativeCall issue exposed by Audio::Convert::Samplerate

### ISSUE THREAD

**Issue by jonathanstowe** [rakudo/rakudo#2687]
## The Problem

[Audio::Convert::Samplerate](https://modules.perl6.org/dist/Audio::Convert::Samplerate) has started failing its tests as per https://github.com/perl6/ecosystem-unbitrot/issues/555

@AlexDaniel has bisected this to https://github.com/rakudo/rakudo/commit/ada116ef99a2a68dc6e1f77f2c3959f1d4e49e0d

## Expected Behavior

Tests should pass (and did last few weeks https://travis-ci.org/jonathanstowe/Audio-Convert-Samplerate/builds/478720750)

## Actual Behavior

Tests fail.  Removing the lives-ok from around the failing line gives:

```
Can only store CArray attribute in CArray slot in CStruct
  in submethod BUILD at /home/jonathan/devel/perl6/modules/Audio-Convert-Samplerate/lib/Audio/Convert/Samplerate.pm (Audio::Convert::Samplerate) line 213
  in method process at /home/jonathan/devel/perl6/modules/Audio-Convert-Samplerate/lib/Audio/Convert/Samplerate.pm (Audio::Convert::Samplerate) line 310
  in method process-other at /home/jonathan/devel/perl6/modules/Audio-Convert-Samplerate/lib/Audio/Convert/Samplerate.pm (Audio::Convert::Samplerate) line 323
  in method process at /home/jonathan/devel/perl6/modules/Audio-Convert-Samplerate/lib/Audio/Convert/Samplerate.pm (Audio::Convert::Samplerate) line 336
  in method process-array at /home/jonathan/devel/perl6/modules/Audio-Convert-Samplerate/lib/Audio/Convert/Samplerate.pm (Audio::Convert::Samplerate) line 342
  in method process-int at /home/jonathan/devel/perl6/modules/Audio-Convert-Samplerate/lib/Audio/Convert/Samplerate.pm (Audio::Convert::Samplerate) line 352
  in block  at t/020-process.t line 175
  in block <unit> at t/020-process.t line 22
```
https://github.com/jonathanstowe/Audio-Convert-Samplerate/blob/master/lib/Audio/Convert/Samplerate.pm#L212

Which is the binding of a CArray value to a CArray attribute.

## Steps to Reproduce

Running the tests of the module suffice but it golfs to:

```perl6
use NativeCall;
  
class Data is repr('CStruct') {
    has CArray[num32] $.data-in;

    submethod BUILD(CArray :$data-in) {
        $!data-in := $data-in;
    }
}


my $d = Data.new(data-in => CArray[num32].new);
```

## Environment
* Operating system:  

Linux coriolanus 4.20.5-100.fc28.x86_64 #1 SMP Mon Jan 28 19:29:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`perl6 -v`):

This is Rakudo version 2018.12-293-gd904b7048 built on MoarVM version 2018.12-94-g2eab275df
implementing Perl 6.d.

**Comment by jonathanstowe** [comment]
BTW I'm actually surprised there isn't a test for this as it is fairly fundamental to the way NativeCall is described to work https://docs.perl6.org/language/nativecall#Structs

**Comment by AlexDaniel** [comment]
See https://github.com/rakudo/rakudo/issues/2681

**Comment by lizmat** [comment]
Fixed with 5e5c909d1a

**Comment by lizmat** [comment]
Really fixed with 30fc5146ca

**Comment by jonathanstowe** [comment]
The above snippet with a ```lives-ok``` round it would work as a simple test ;-)

**Comment by jonathanstowe** [comment]
Confirmed okay:

```
jns:~/me/Perl6-Modules/Audio-Convert-Samplerate$ perl6 -v
This is Rakudo version 2018.12-296-g30fc5146c built on MoarVM version 2018.12-94-g2eab275df
implementing Perl 6.d.
jns:~/me/Perl6-Modules/Audio-Convert-Samplerate$ zef test . --debug
===> Testing: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
Testing with plugin: Zef::Service::TAP+{<anon|1>}
t/001-meta.t ......... ok
t/001-use.t .......... ok
# testing with samplerate version libsamplerate.0.1.9.c.2002.2008.Erik.de.Castro.Lopo
t/010-constructor.t .. ok
t/020-process.t ...... ok
All tests successful.
Files=4, Tests=222,  3 wallclock secs
Result: PASS
===> Testing [OK] for Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
```

**Comment by lizmat** [comment]
Test added with bfadefaa6799
