### ISSUE TITLE
asinh() is not an odd function

### ISSUE THREAD

**Issue by ramillies** [rakudo/rakudo#2688]
## The Problem

The function `asinh()` should be odd, i. e. `asinh(-x) = - asinh(x)`. However, `asinh` of a negative argument gets more and more wrong with increasing absolute value of the argument.

## Expected Behavior

`(1e5,1e6,1e7,...,pretty much any values).map({ .asinh + asinh(-$_) })` approximately equal to `(0, 0, 0, ..., 0)`.

## Actual Behavior

`(1e5,1e6,1e7,3e7,5e7,7e7).map({ .asinh + asinh(-$_) })` yields roughly `(-1.117e-6, 7.614e-6, 5.811e-3, -0.111, -0.294, -Inf)`.

The current version of `asinh` yields `-Inf` for anything less than approximately -7e7. This is quite unfortunate, since the function drops only logarithmically, and so, for instance, correct result for asinh(-7e7) is -18.757..., which is far from being -Inf.

## Environment
* Operating system: GNU/Linux, Debian sid. (I don't think this has any bearing on it but I will provide more detail if needed.)
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12 built on MoarVM version 2018.12, implementing Perl 6.d.

**Comment by ramillies** [comment]
I explored it a little bit more. I'd guess that the function is just implemented by asinh x = ln(x + √(x² + 1)). With large negative x, the argument of the logarithm is very small and probably drops to 0 way too early. I'd suggest using the formula only for x ≥ 0 and returning -asinh(-x) for x < 0.

**Comment by lizmat** [comment]
Fixed  by merging the PR, now only needs testing afaics
