### ISSUE TITLE
Role consumption by multiple roles

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2694]
## The Problem

When two or more roles (let them be `R1` and `R2`) directly or indirectly all consume the same role (`R3`) it results in at least two kinds of problems.

1. If `R3` declares an attribute we get attribute conflict:

   ```
   role R3 { has $.a; }
   role R2 does R3 { }
   role R1 does R3 { }
   class C does R1 does R2 { }
   ```

   While this is possibly resolvable within a single project, it may cause serious problems when each role and class all belong to different packages. Say, in the first releases of the package declaring `R3` the role didn't have any attributes. But at some point developers of the package decide that the role needs one! `C` is broken, an end-user is unhappy at best...

2. Same situation, `R3` comes from a third-party package. It was never designed for multiple consumption. If defines a method `foo` and both `R1` and `R2` define it too and both qualify-call `R3::foo`. `C` resolves the conflict by qualify-calling both methods from `R1` and `R2`. `foo` on `R3` gets called twice.

To me it looks like the attribute conflict situation can only be resolved by building C3 linearization for roles instead of the deep scan currently employed by the role specialization code.

For the second one there is probably no solution whatsoever in the current model. Method call dispatch similar to that one we have for classes would serve as a solution.

Unfortunately, in both cases I see it as a huge overhaul of the metamodel with serious consequences.

**Comment by barcharcraz** [comment]
what about a way to have a role do another role, but with all the methods stubbed out, and private variables removed? This could probably be done with some metaprogramming.

**Comment by vrurg** [comment]
It is fixed with pending #3199. Just waiting for the next release and an approval to be merged.

**Comment by patzim** [comment]
@vrurg: The release branches have already been set, so no need to wait for the release.

**Comment by vrurg** [comment]
@patzim yep, but Jonathan is yet to approve `.-`, `.?+`, and `.?-` operators.
