### ISSUE TITLE
Labeled last/next doesn't work with FIRST/LAST/NEXT phasers

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2699]
FOO: for <a b> { NEXT say "bar"; .say; next FOO }
    # a
    # labeled next without loop construct

Without the label it works fine.  This seems to occur for any combination of `next`, `last` and the `FIRST`, `NEXT` and `LAST` phasers.

Bisected to 031efe0d9fa1cf38 (29 Jan 2017) so definitely **not** a blocker for the upcoming release.

**Comment by usev6** [comment]
I've stumbled upon this issue and noticed that the code works as expected on the JVM backend:
```
$ ./rakudo-j -e 'FOO: for <a b> { NEXT say "bar"; .say; next FOO }'
a
bar
b
bar
```

Output on with MoarVM is unchanged.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/3c83ce75a1

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/d449e88273
