### ISSUE TITLE
Please close rt #131297 (`|@a` is apparently-equivalent to just `@a` but is 70x slower)

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#2708]
Zoffix got confused. The rt bug should be closed (and then this issue too).

Zoffix's confusion was due to them not golfing their code. The regex code `foo | bar` or `foo || bar` is always an alternation between foo or bar, never foo followed by an alternation of what's held inside bar, even if it's written as `foo |bar`, without the space before the `bar`. Here's Zoffix's examples trimmed:

```perl6
/'-- '  |@a '-' \d**2 '-' \d**4 /
/'-- ' ||@a '-' \d**2 '-' \d**4 /
/'-- '   @a '-' \d**2 '-' \d**4 /
```

It's not surprising that the first one, which always succeeds in matching '-- ', but first tries to match the RHS of the alternation, takes by far the longest; the second one, which also always succeeds in matching '-- ' and doesn't bother to try the RHS is 35 times faster, and the last one, which always fails to match, is twice as fast again. Zoffix confused themselves by not golfing and it seems timotimo too.

**Comment by AlexDaniel** [comment]
Looks like you're right.

**Comment by raiph** [comment]
Hi @AlexDaniel 

I've emailed the rt admins to see if I can get a way to close RT tickets myself.

At the moment I'm enjoying going thru rt issues to see if I can golf them, dedupe them etc. and move them here. Any feedback you have about whether that's OK and anything I can do to do it better would be great.

----

The following couple points prolly shouldn't be in an issue comment, and will prolly make me seem weird, but whatever...

Thx for all the things u do for P6. I've dropped out of irc for a year or so and have never gotten into using the bots but I'm looking forward to returning to irc and using the bots this year. Maybe I'll see you there, even though you'll no longer be doing releases.

I miss Zoffix and no doubt you do too. At the moment I'm thinking the best thing I can do to respect the energy they and you have put into P6 is to keep looking ahead, not behind. But I think I'll be reeling from the loss of Zoffix's love for P6, and the globally increasingly common online communication based misunderstanding, drama and harshness that drove it, for the rest of my life. I hope to see you around for years to come but regardless, take care, wherever life takes you or you take it.

And, last but not least, thanks for closing the RT issue for me and for P6. :)

**Comment by AlexDaniel** [comment]
> Any feedback you have about whether that's OK and anything I can do to do it better would be great.

Yes, it's totally OK. And yes, you should be given privileges to close RT tickets.

> the globally increasingly common online communication based misunderstanding

We're working on improving this and https://github.com/perl6/user-experience/issues/33. It will be announced soon. Exciting times.

**Comment by coke** [comment]
I should be able to add you to rt - pls send me an email with your rt account/email
