### ISSUE TITLE
nice to have a .deepclone method for classes and grammers

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#2710]
Currently, cloning a class instance does not clone its container objects. According to the docs, there are ways to write one's own clone method, but no practical example is shown.

I have found a need for deep cloning in a module I am working on, and, I believe others would find it useful as well.

**Comment by rassoc** [comment]
In what way has this been addressed that would warrant closing the issue?
There's still no simple built-in function and the docs only provide the following example which appears quite daunting for new users:

```raku
# […] you could implement your own .clone that clones the appropriate 
# attributes and passes the new values to Mu.clone, for example, via nextwith

class Bar {
    has $.quux;
    has @.foo = <a b>;
    has %.bar = <a b c d>;
    method clone { nextwith :foo(@!foo.clone), :bar(%!bar.clone), |%_  }
}

my $o1 = Bar.new( :42quux );
with my $o2 = $o1.clone {
    .foo = <Z Y>;
    .bar = <Z Y X W>;
}
```

A bit more involved than the `x.deepcopy()` functionality from our competition.
