### ISSUE TITLE
Pod::To::Text is mishandling footnotes.

### ISSUE THREAD

**Issue by cfa** [rakudo/rakudo#2711]
## The Problem

Footnote codes (`N<>`) are incorrectly handled by `Pod::To::Text`. Given

```perl6
=begin pod
TestN<note>.
=end pod
```

`perl6 --doc` outputs: “Testnote.”

## Expected Behavior

Any of the following would make sense:

1. List footnotes at the end of the document, cross referenced from the source site;
2. List footnotes in place, perhaps in parentheses: _“Test (FOOTNOTE: note)”_;
3. As a temporary measure, at least distinguish a footnote by prepending whitespace.

## Actual Behavior

The formatting code is simply stripped and the footnote joined directly to the immediately preceding text.

    > use Pod::To::Text;
    Nil
    > my $pod = EVAL "\$=pod;\n=begin pod\nTestN<note>.\n=end pod";
    [Pod::Block::Named{:name("pod")}
      Pod::Block::Para
        Test
        Pod::FormattingCode{:type("N")}
          note
        .
    ]
    > pod2text $pod
    Testnote.

## Environment

    This is Rakudo version 2018.12 built on MoarVM version 2018.12
    implementing Perl 6.d.

**Comment by lizmat** [comment]
Superseded by --rakudoc=Text in RakuAST, which *does* handle footnotes ok afaik
