### ISSUE TITLE
Any.print-nl is broken

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2713]
## The Problem

`Any.print-nl` seems to be broken.

    say 3.print-nl ; #OUTPUT: «(exit code 1) Too many positionals passed; expected 1 argument but got 2␤  in block <unit>  at /tmp/wr3cSi1LHi line 1␤␤»
    say "a".print-nl  ;# OUTPUT: «(exit code 1) Too many positionals passed; expected 1 argument but got 2␤  in block <unit>  at /tmp/hvP21obWke line 1␤␤»

This was already noticed in perl6/doc#1494, but apparently not reported.

## Expected Behavior

Probably print the object version of nl.

## Version

v2018.12.311.gd.6563816.e , which Camelia is running right now.

**Comment by lizmat** [comment]
I think the fix is:

    diff --git a/src/core/Any.pm6 b/src/core/Any.pm6
    index da6e1cb..4450b47 100644
    --- a/src/core/Any.pm6
    +++ b/src/core/Any.pm6
    @@ -448,7 +448,7 @@ my class Any { # declared in BOOTSTRAP
         multi method Supply() { self.list.Supply }

         method nl-out(--> Str:D) { "\n" }
    -    method print-nl() { self.print(self.nl-out) }
    +    method print-nl() { self.nl-out.print }

         method lazy-if($flag) { self }  # no-op on non-Iterables

However, this breaks https://github.com/perl6/roast/blob/master/S29-any/deg-trans.t#L40

**Comment by JJ** [comment]
Ping?

**Comment by raiph** [comment]
In two recent Rakudos I just tried (early 2022 and mid 2024) the breakage has shifted as follows:
```
Any.print-nl; # New error compared to 2019: Cannot resolve caller print(Any:U: Str:D) ...
Match.print-nl; # Same error as in 2019: Too many positionals passed; expected 1 argument but got 2 
```
