### ISSUE TITLE
Role inheriting from a class fails type checking against that class

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2714]
## The Problem

When a role defines inheritance from a class type checking against that class doesn't pass.

## Steps to Reproduce

```
class C { }
role R is C { }
say R ~~ C;
```

outputs

>```
>False
>```

## Notes

The fix should be a simple patch of role metaclasses `type_check` methods.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`):

**Comment by jnthn** [comment]
A role doesn't really "inherit from a class", it just stashes away the parent and then adds it as a parent to a class that it is eventually composed in to. It's *probably* harmless to patch the `type_check` method if we want to try and pretend a bit harder. Note that it will have an impact on multi dispatch candidate sorting, although I suspect this construct is used rarely enough (I can think of zero uses of it in anything I've written...) that it won't have many consequences.

**Comment by vrurg** [comment]
As to the terminology – that's easier to say 'it inherits'. From user point of view – it actually does. So, why not? Also, for a user it looks reasonable if role would pass the check.

I'll try and see if it passes spectest.

**Comment by vrurg** [comment]
Closed via #2717
