### ISSUE TITLE
6.c-errata and S11-repository/curli-install.t

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2722]
[curli-install.t](https://github.com/perl6/roast/blob/6.c-errata/S11-repository/curli-install.t) file in roast 6.c-errata branch does not pass. It is OK on 6.d-errata and master.
```
/usr/bin/perl t/harness5 --fudge --moar --keep-exit-code --verbosity=1 t/spec/S11-repository/curli-install.t

ok 1 - repository does C::R::Installable
ok 2 - repository does C::R::Locally
ok 3 - repository has an identifier
ok 4 - short-id exposes type of repository
ok 5 - no compilation units were loaded so far
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 13/18 subtests 

Test Summary Report
-------------------
t/spec/S11-repository/curli-install.t (Wstat: 65280 Tests: 5 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 18 tests but ran 5.
Files=1, Tests=5,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.67 cusr  0.03 csys =  0.71 CPU)
Result: FAIL
make: *** [Makefile:687: t/spec/S11-repository/curli-install.t] Error 1
```

I don't see any relevant changes to that test file on master, so I'm a bit confused as to what has changed and what needs to be done on 6.c-errata branch.

Ping @ugexe.

**Comment by ugexe** [comment]
No idea

**Comment by AlexDaniel** [comment]
Output before and after: https://gist.github.com/Whateverable/830d24921929a17fe19a17f11f1e5f97

**Comment by AlexDaniel** [comment]
The above bisected to this: (2018-12-20) https://github.com/rakudo/rakudo/commit/f430518f568b29d6112e82077f44483f1197ca24

**Comment by ugexe** [comment]
That test should not exist.

**Comment by ugexe** [comment]
https://github.com/perl6/roast/commit/b82233a6973ad18d7b74a2fdd0ae8789a1977a76#diff-cade5f3b2d7b5c7647e906bf45a1b7d8 This is where the tests were removed

**Comment by AlexDaniel** [comment]
@ugexe do you think it makes sense to change it like this?
```diff
diff --git a/S11-repository/curli-install.t b/S11-repository/curli-install.t
index 6546dfafa..124a8374b 100644
--- a/S11-repository/curli-install.t
+++ b/S11-repository/curli-install.t
@@ -16,13 +16,15 @@ rm_rf $path.IO if $path.IO.e;
     is $*REPO.short-id, 'inst', 'short-id exposes type of repository';
     is $*REPO.loaded.elems, 0, 'no compilation units were loaded so far';
 }
-my $dist = Distribution.new(:name<Foo>);
+my $prefix   = $path.IO.parent;
+my %provides = Foo => 'Foo.pm';
+my $dist = Distribution::Hash.new({ :name<Foo>, :%provides }, :$prefix);
 
-$*REPO.install($dist, { Foo => 't/spec/packages/Foo.pm' });
+$*REPO.install($dist);
 
-throws-like { EVAL q[$*REPO.install($dist, { Foo => 't/spec/packages/Foo.pm' })] },
+throws-like { EVAL q[$*REPO.install($dist)] },
     X::AdHoc,
-    message => "$dist already installed",
+    message => /'already installed'/,
     "cannot reinstall the very same distribution";
 
 {
```
The files in 6.c and master diverged quite significantly, and this is the smallest diff to make it work. Or should we bring it up to date (even though it is 6.c spec) by including :api and :ver stuff and other changes that were done to that file?

**Comment by ugexe** [comment]
Well to me it seems pointless to fix this at all. I changed roast on May 11, 2018 and yet the errata branch is still stale. I posit there are many changes across the entire roast that are not going to be reflected in the errata branch -- does it make sense to fix this one specific test in a one-off manner?

**Comment by AlexDaniel** [comment]
@ugexe it wasn't changed on 6.c-errata before because the test file used to pass. If you checkout `6.d-errata` or `6.c-errata` branches and run `spectest` *all* tests will pass. Part of the release process is to ensure that this is the case. That's the only test file that is not OK right now.

**Comment by ugexe** [comment]
I'm confused. If there are tests that were added after e.g. May 18, 2018 that are part of the spec then 6.c-errata would not be reflecting those (i.e. its only "passing" because it isn't testing the new thing) unless the author explicitly committed to multiple branches (6.c-errata and master as of May 18, 2018).

Regardless, the fix you posted is appropriate.

**Comment by AlexDaniel** [comment]
That's correct. The goal is ensure that user code that relied on 6.c behavior continues to work (with any compiler that supports 6.c, of course). So new features that are added later are not reflected in the 6.c spec, and that is fine. Also, even today some features may behave differently depending on which language version your code `use`s.

**Comment by ugexe** [comment]
But what I'm getting at is this: if roast/6.c-errata was not kept in sync with roast/master until rakudo 6.d was released then there is at least 6 months of rakudo commits with associated roast commits that are not reflected in 6.c-errata but should be, but won't be exposed until it happens to get broken in the following release.

In other words: why isn't roast/6.c-errata a snapshot of master at a later date then May 18, 2018 but before 6.d? I imagine its just because no one ever did it. But then what else is going to break in the future, and are we just going to keep doing one-off fixes or find a way to bring the branch up-to-date? Or maybe its not really a problem and I'm overthinking this.

**Comment by AlexDaniel** [comment]
I guess you're right that many changes could (and maybe should) be brought to 6.c-errata, especially when it comes to throwing away tests that shouldn't be there. On the other hand, 6.c-errata spec is there to preserve old behavior for code that does `use v6.c`, so ideally we shouldn't be touching it at all.

I think it serves a useful function, and the current approach seems to be working. I can't tell if you're overthinking it or not. It is not a problem now, but a few releases down the road the picture is going to be completely different… I don't know for how long we want to keep 6.c maintained, and I can totally see how it'd be difficult to do fixes to the spec when there are many 6.*-errata branches that need to be maintained.

**Comment by AlexDaniel** [comment]
Committed: https://github.com/perl6/roast/commit/894dee8d4d8009a552114dde0401e6519e3cdfca
