### ISSUE TITLE
Automate a nightly docker release via CircleCI

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#2723]
CircleCI is capable of executing [via cron](https://github.com/crystal-lang/crystal/blob/86e0f40dc64f7b2ee623434436ec1fa3bbccf168/.circleci/config.yml#L418-L425), and also capable of creating and [publishing](https://github.com/crystal-lang/crystal/blob/86e0f40dc64f7b2ee623434436ec1fa3bbccf168/.circleci/config.yml#L273) docker images. This would give module authors an easy way to [use the docker container](https://github.com/crystal-lang/crystal/blob/86e0f40dc64f7b2ee623434436ec1fa3bbccf168/.circleci/config.yml#L91-L93) for CI testing against a 'latest' version of rakudo instead of only official releases.

Other public repo examples of CircleCI configs: https://circleci.com/docs/2.0/example-configs/

Our current CircleCI config: https://github.com/rakudo/rakudo/blob/master/.circleci/config.yml

**Comment by tony-o** [comment]
Is someone with access to the rakudo organization on docker and circleci able to add me so I can do this?

**Comment by AlexDaniel** [comment]
People who can do that: @jnthn @masak @moritz @pmichaud

**Comment by AlexDaniel** [comment]
@tony-o actually, try accepting an invite now. Do you now have the required privileges?

**Comment by AlexDaniel** [comment]
OK, after thinking about it, I'm now ever more confused. Are there some separate organizations elsewhere (e.g. on circeci)? Or do you just need to be an admin or owner of the `rakudo` organization on github?

**Comment by tony-o** [comment]
@AlexDaniel i'll need some permissions both on the circleci side and docker site (not sure who owns the orgs there).  I believe through the rakudo org i'll get what i need on the circleci side

**Comment by tony-o** [comment]
@AlexDaniel appears I can get it going on circle ci 👍 , now just need permission to publish to docker's rakudo org

**Comment by AlexDaniel** [comment]
> docker's rakudo org

Where's that exactly? Do you have a link?

**Comment by tony-o** [comment]
@AlexDaniel - i think i just had shoddy internet where I was and I was able to create the repo 👍

**Comment by tony-o** [comment]
Docker image is now available from docker hub under `tonyodell/rakudo-nightly:latest`.  Will be built nightly by circleci.  An example using it from a module testing perspective can be found [here](https://github.com/tony-o/perl6-xoo/blob/master/.circleci/config.yml).

**Comment by lizmat** [comment]
Superseded by other CI solutions, so closing
