### ISSUE TITLE
(s)printf misleading error message should report values, not types

### ISSUE THREAD

**Issue by Altreus** [rakudo/rakudo#2724]
`printf` should report the value when it could not be applied to a directive; currently, it reports the *type* of the value.

```
> printf("%d",Inf)   
Directive d not applicable for type Num
```

This is misleading when the type is expected to work, but can have unworkable values; in the above example, it is surprising to hear that `Num` does not apply to `d`, whereas in fact it is `Inf` or `NaN` that don't apply to `d`.

Another misleading case is `Str`, since again it is the value that is unusable, not the type:

```
> printf("%d", "1")
1

> printf("%d", "raku")
Directive d not applicable for type Str
```

**Comment by lizmat** [comment]
Thanks for the report.  This is now fixed!
