### ISSUE TITLE
%h{$a}{$b}{$c} = True in a loop with different abcs is really slow

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#2735]
A code example posted by rindolf++ in perl6 turned out to be more than a magnitude slower than an equivalent piece of code written in P5.

AlexDaniel++ took a look a the script and noted, among other things, that code like 

    %starts{$s}{$e}{$sum} = True;
    %ends{$e}{$s}{$sum} = True;

is very slow. The question then, are there any 'easy' opts which can be applied in this case.

[rindolf.zip](https://github.com/rakudo/rakudo/files/2926821/rindolf.zip)

**Comment by lizmat** [comment]
It appears that timings for recursive hash accesses are pretty ok:
```
% raku -e 'use v6.*; my %h; Nil for ^1_000_000; say (nano - ENTER nano) / 1_000_000'
19.12916
% raku -e 'use v6.*; my %h; %h{42} = True for ^1_000_000; say (nano - ENTER nano) / 1_000_000' 
89.102968
% raku -e 'use v6.*; my %h; %h{42}{666} = True for ^1_000_000; say (nano - ENTER nano) / 1_000_000'     
186.29584
% raku 'use v6.*; my %h; %h{42}{666}{127} = True for ^1_000_000; say (nano - ENTER nano) / 1_000_000'  
272.972991
```
so closing
