### ISSUE TITLE
Directories are no longer accessible from %?RESOURCES

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#2746]
## The Problem

Somewhere between 2018.12 and `2018.12-302-g121ca5fda` %?RESOURCES start to return `()` instead of a directory. The files are ok.
Regression has appear in Cro::HTTP tests, see https://github.com/croservices/cro-http/issues/71

I suspect https://github.com/rakudo/rakudo/commit/370310b35e9a755229b0b8bb9a18e3708dfbf6b9, but don't know for sure.

## Expected Behavior

For Cro::HTTP `http-router.t` test on master to pass just as it does on 2018.12.

## Actual Behavior

Not
```
➜  cro-http git:(master) ✗ perl6 -Ilib t/http-router.t
"/home/koto/Work/cro/cro-http/resources/index.html".IO
(Resource)
ok 1 - Get index.html from %*RESOURCES
ok 2 - Static-resource sets correct status code
"/home/koto/Work/cro/cro-http/resources/folder".IO
(Resource)
ok 3 - indexes in a folder of %*RESOURCES
ok 4 - Good status
1..4
```
but
```
➜  cro-http git:(master) ✗ perl6 -Ilib t/http-router.t
"/home/koto/Work/cro/cro-http/resources/index.html".IO
(Resource)
ok 1 - Get index.html from %*RESOURCES
ok 2 - Static-resource sets correct status code
()
(Resource)
No such method 'e' for invocant of type 'Slip'
  in sub static-resource at /home/koto/Work/cro/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 1067
  in block  at t/http-router.t line 1938
  in block  at /home/koto/Work/cro/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 130

not ok 3 - indexes in a folder of %*RESOURCES
# Failed test 'indexes in a folder of %*RESOURCES'
# at t/http-router.t line 1973
# expected a match with: rx{ 'this is a test' \n }
#                   got: ""
not ok 4 - Good status
# Failed test 'Good status'
# at t/http-router.t line 1974
# expected: '200'
#      got: '500'
1..4
# Looks like you failed 2 tests of 4

```

## Environment
* Operating system: linux
* Compiler version (`perl6 -v`): `This is Rakudo version 2018.12-302-g121ca5fda built on MoarVM version 2018.12-94-g2eab275df`

**Comment by Altai-man** [comment]
The `regression` label is necessary, at least. I don't know how urgent it may be.

**Comment by ugexe** [comment]
Those tests would never have passed with an installed distribution so they are flawed assumptions. There is no directory access via `%?RESOURCES`. It just so happened that (only) CURFS didn't error when attempting this before.

**Comment by Altai-man** [comment]
>It just so happened that (only) CURFS didn't error when attempting this before.

Oh, this is pretty important. Thanks! I'll look for what can be done about it.

**Comment by ugexe** [comment]
What You could probably do is give the router a `Distribution::Resources` / `%?RESOURCES` multi so it can use non-IO::Path logic to get the info you want. For instance you can get the list of resources with `$?DISTRIBUTION.meta<resources>.grep({ .ends-with("/") })` and from that you could fake simple IO like a directory listing.
