### ISSUE TITLE
$?PACKAGE.^ver does not exist

### ISSUE THREAD

**Issue by MARTIMM** [rakudo/rakudo#2752]
## The Problem
The following piece of code
```
unit package P:ver<0.1.0>;
note $?PACKAGE.^ver;
```
produces the error: `No such method 'ver' for invocant of type 'Perl6::Metamodel::PackageHOW'`

## Expected Behavior
It should show the version object as per doc page: https://docs.perl6.org/language/packages#Version.

## Environment
* Linux fedora 28: 
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12-363-ga1c2e20d7 built on MoarVM version 2018.12-117-gdcafbc4c7

**Comment by ugexe** [comment]
fwiw I thought packages were versionless (since originally you would be able to have multiple packages of the same name in different files or some such), and instead you would probably use `unit module P:ver<0.1.0>`

**Comment by MARTIMM** [comment]
That's true now I think of it, I've done it myself.
Indeed it works for module.
So if a package does not have a version object attached as the docs explain, the docs should be changed I think.

**Comment by jnthn** [comment]
Yes, the implementation in Rakudo is correct. A `package` doesn't really have an identity, and can be taken over by a `module`, `class`, etc.

```
$ perl6 -e 'package Foo { }; module Foo { }'
jnthn@lviv:~/edument/comma-website$ perl6 -e 'module Foo { }; module Foo { }'
===SORRY!=== Error while compiling -e
Redeclaration of symbol 'Foo'
at -e:1
------> module Foo { }; module Foo⏏ { }
```

Which is what allows for:

```
class Foo::Bar { }
class Foo { }
```

To work; between the two lines there, a `Foo` exists but is a package, later taken over by the `Foo` class. As @ugexe points out, the `package` declaration can also appear multiple times without conflicts being caused, and even spread over multiple files.

I've made a [docs issue](https://github.com/perl6/doc/issues/2659).
