### ISSUE TITLE
Is self.WRITE tested?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2755]
## The Problem

6.d has added new methods that can be overridden for writing IO::Handles, WRITE and READ and so on. However, they don't seem to be tested, or I haven't found where they are tested. This I'm trying to use it to fix the issue that caused #2751, but I'm bumping into trouble.

## Expected Behavior

Test, so that at least we have an actual example of it working. The example in the [documentation](https://docs.perl6.org/type/IO::Handle#method_WRITE) just throws an error.

**Comment by ugexe** [comment]
```
~/repos/roast$ git grep WRITE
APPENDICES/A02-some-day-maybe/io-cathandle.t:    WRITE  READ        EOF
S06-advanced/caller.t:# WRITEME: label tests
S32-io/io-handle.t:subtest '.WRITE method' => {
S32-io/io-handle.t:        method WRITE (Blob:D \data --> True) { $!data.append: data }
S32-io/io-handle.t:subtest '.EOF/.WRITE methods' => {
docs/announce/6.d.md:- `IO::Handle` provides `.READ`, `.WRITE`, `.EOF`, `.DESTROY`,
```

**Comment by coke** [comment]
@JJ, can you verify if the tests in S32-io/io-handle.t are sufficient?

**Comment by JJ** [comment]
Right, `WRITE` and `READ`, as well as `EOF` are tested there.
