### ISSUE TITLE
REPL: The Readline history file is not created when absent.

### ISSUE THREAD

**Issue by cfa** [rakudo/rakudo#2758]
## The Problem

The Readline history file (`~/.perl6/rakudo-history`) is not created if absent. When present and writable, the log is appended to as expected.

## Expected Behavior

Create `~/.perl6/rakudo-history` if missing.

## Steps to Reproduce

```
$ mv ~/.perl6/rakudo-history{,.bak}
$ perl6 # enter some input, ^D
$ cat ~/.perl6/rakudo-history
cat: /Users/cfa/.perl6/rakudo-history: No such file or directory
$ touch ~/.perl6/rakudo-history
$ perl6 # enter some input, ^D
$ cat  ~/.perl6/rakudo-history
1
2
```

(Input is logged; in this case `1` then `2`.)

## Environment
* Operating system: macOS.
* Compiler version (`perl6 -v`): 2019.03. `Readline` installed.

**Comment by lizmat** [comment]
Fixed with cb691da514a499dcae722f91 by making sure the history file is created regardless of the underlying library used.
