### ISSUE TITLE
watch-path spectest failing on macOS

### ISSUE THREAD

**Issue by clarkema** [rakudo/rakudo#2760]
## The Problem

I'm trying to build a Rakudo Star 2019.03 release for macOS.  `make spectest` is failing.  See https://github.com/rakudo/star/issues/124

## Expected Behavior

Tests should pass!

## Actual Behavior

`t/spec/S17-supply/watch-path.t` consistently fails in the same place, which suggests that I'm not seeing a timing issue related to macOS randomly failing to deliver notifications in a prompt manner.

There are a number of failures, but the initial one is https://github.com/perl6/roast/blob/master/S17-supply/watch-path.t#L145, which then throws off later counts.

For some reason the write at 'https://github.com/perl6/roast/blob/master/S17-supply/watch-path.t#L142' generates two notifications rather than one.  I've summarized this in a quick script below:

```
# Summarized from t/spec/S17-supply/watch-path.t

use v6;

my $filename = "watch-path_checker";

my $handle = open( $filename, :w );

my $s = $filename.IO.watch.grep({ .path.IO.basename eq $filename }).unique;

my $tap = $s.tap: -> \change {
    say "Got event! " ~ change.perl;
}

$handle.say( "Hello world" );

sleep 10;
```

The spec test as it's written expects to see one notification here; I consistently get two.

## Steps to Reproduce

Build Rakudo and run `make spectest` or `PERL6LIB=lib ./perl6 t/spec/S17-supply/watch-path.t` on macOS.

## Environment

* Operating system: OS X 10.4.1
* Compiler version (`perl6 -v`):  2018.10 and 2019.03

**Comment by clarkema** [comment]
Turns out this is actually a timing issue -- the test needs to wait long enough after the call to open() for the notification caused by opening the file for write to be 'lost'.  Otherwise it arrives after the supply is set up, and we end up with one notification for opening the file and second for actually writing to it.

**Comment by AlexDaniel** [comment]
So why was this closed? I don't see any commit in roast.

**Comment by lizmat** [comment]
Tests removed from spectest.data for now: https://github.com/rakudo/rakudo/commit/3afbc1204a

**Comment by clarkema** [comment]
@AlexDaniel I'm working on a couple of patches for roast that will fix it, but assumed I would need to open a ticket there rather than here in the Rakudo repo.

**Comment by AlexDaniel** [comment]
@clarkema that's right, but please keep at least one ticket *open* at all times.

**Comment by lizmat** [comment]
@clarkema please make the necessary changes in roast: if the tests pass, I'll revert the removal of the test file for the spectest.  Meanwhile, you can still just `make t/spec/S17-supply/watch-path.t` regardless of whether it is part of spectest.data, afaik.

**Comment by clarkema** [comment]
See https://github.com/perl6/roast/pull/519

**Comment by lizmat** [comment]
Closing as this appears to be testing a very frugal and moving target
