### ISSUE TITLE
rakudo.org IPv6 is broken

### ISSUE THREAD

**Issue by pfeilmann** [rakudo/rakudo#2762]
## The Problem

Download of the source files is not possible over IPv6 from your website.
![grafik](https://user-images.githubusercontent.com/1765966/54298960-20eac080-45ba-11e9-9e5a-7683256427b3.png)

so for example the installation from Arch User Repository (AUR) will not work on systems with IPv6
https://aur.archlinux.org/packages/nqp/

## Expected Behavior
HTTP 301 to redirect to https and that the download

## Actual Behavior
HTTP 404

## Steps to Reproduce
`curl -6IkvL http://rakudo.org/downloads/nqp/nqp-2019.03.tar.gz`

## Environment
* A working IPv6 adress

**Comment by AlexDaniel** [comment]
Ping @moritz.

**Comment by moritz** [comment]
Do the HTTPS URLs work? If yes, I'd suggest using them as a first step.

Will look into a proper solution later.

**Comment by moritz** [comment]
I've fixed some stuff in Apache, please try again.

**Comment by pfeilmann** [comment]
Looks good :)
