### ISSUE TITLE
Failed Text::CSV zef install with rakudo-star-2019.03-RC

### ISSUE THREAD

**Issue by michael-776** [rakudo/rakudo#2763]
Hello,
I'm following this advice: "You can use [this issue tracker] even if you're unsure where to file your report."

I had reported this to the Text::CSV maintainer, who said:
"On today's rakudo, I get a full pass"

I've successfully installed rakudo-star-2019.03-RC and  several  modules with zef, including Inline::Perl5, and Cro (and others, I didn't take notes...). Native::Exec also could not be installed, but I'm not sure it was working anyway.

cat /etc/debian_version 
9.8

uname -a
Linux etch2 4.19.16lowlatency2-etch #1 SMP PREEMPT Tue Feb 12 11:47:20 EST 2019 x86_64 GNU/Linux

perl -v
This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-multi

perl6 --version
This is Rakudo Star version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.

zef --version
v0.7.1

zef install Text::CSV  
full log:

===> Searching for: Text::CSV
===> Searching for missing dependencies: Slang::Tuxic
===> Testing: Slang::Tuxic:ver<0.0.1>:auth<github:FROGGS>
===> Testing [OK] for Slang::Tuxic:ver<0.0.1>:auth<github:FROGGS>
===> Testing: Text::CSV:ver<0.008>:auth<github:Tux>
TODO: EOL = "!", RS = ""
      "1,2,3!4,5,6!"
  --> ["1"]
TODO: EOL = "!!", RS = ""
      "1,2,3!!4,5,6!!"
  --> ["1"]
TODO: EOL = "!!", RS = "!"
      "1,2,3!!4,5,6!!"
  --> ["1", "2", "3!"]
TODO: EOL = "!\n", RS = ""
      "1,2,3!\n4,5,6!\n"
  --> ["1"]
TODO: EOL = "!\n", RS = "!"
      "1,2,3!\n4,5,6!\n"
  --> ["1", "2", "3!"]
TODO: EOL = "!\n!", RS = ""
      "1,2,3!\n!4,5,6!\n!"
  --> ["1"]
TODO: EOL = "!\n!", RS = "\n"
      "1,2,3!\n!4,5,6!\n!"
  --> ["1", "2", "3!\n"]
TODO: EOL = "!\n!", RS = "!"
      "1,2,3!\n!4,5,6!\n!"
  --> ["1", "2", "3!"]
TODO: EOL = "!\n!", RS = "!\n"
      "1,2,3!\n!4,5,6!\n!"
  --> ["1", "2", "3!\n"]
TODO: EOL = "!!!!!!!!", RS = ""
      "1,2,3!!!!!!!!4,5,6!!!!!!!!"
  --> ["1"]
TODO: EOL = "!!!!!!!!", RS = "!"
      "1,2,3!!!!!!!!4,5,6!!!!!!!!"
  --> ["1", "2", "3!"]
TODO: EOL = "!!!!!!!!!!", RS = ""
      "1,2,3!!!!!!!!!!4,5,6!!!!!!!!!!"
  --> ["1"]
TODO: EOL = "!!!!!!!!!!", RS = "!"
      "1,2,3!!!!!!!!!!4,5,6!!!!!!!!!!"
  --> ["1", "2", "3!"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = ""
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "\n"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "!"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "!\n"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!!!!!\n"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "\n!"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "!\n!"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!!!!!\n!"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = ""
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "\n"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "!"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "!\n"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "\n!"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n!"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "!\n!"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n!"]
TODO: EOL = "\%^+_\n\0!X**", RS = ""
      "1,2,3\%^+_\n\0!X**4,5,6\%^+_\n\0!X**"
  --> ["1"]
TODO: EOL = "\%^+_\n\0!X**", RS = "\n"
      "1,2,3\%^+_\n\0!X**4,5,6\%^+_\n\0!X**"
  --> ["1", "2", "3\%^+_\n"]
TODO: EOL = "\%^+_\n\0!X**", RS = "!"
      "1,2,3\%^+_\n\0!X**4,5,6\%^+_\n\0!X**"
  --> ["1", "2", "3\%^+_\n\0!"]
TODO: EOL = "\r\n", RS = ""
      "1,2,3\r\n4,5,6\r\n"
  --> ["1"]
TODO: EOL = "\r", RS = ""
      "1,2,3\r4,5,6\r"
  --> ["1"]
\# Failed test 'Content'
\# at t/90_csv.t line 105
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'Content'
\# at t/90_csv.t line 105
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'Content'
\# at t/90_csv.t line 105
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'Content'
\# at t/90_csv.t line 105
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Str   (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 125
\# expected: 'bar,baz,foo
1,2,3
2,a b,
'
\#      got: 'foo,bar,baz
\# 3,1,2
\# 2,a b,
\# '
\# expected: 'bar,baz,foo
\# 1,2,3
\# 2,a b,
\# '
\#      got: 'foo,bar,baz
\# 3,1,2
\# 2,a b,
\# '
\# Failed test 'csv => Array (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 134
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Hash  (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 139
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Failed test 'csv => Hash + skip (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 146
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("3"), :baz("1"), :foo("2")}, {:bar("2"), :baz("a b"), :foo("")}]
\# Failed test 'csv => Hash + auto (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 153
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Failed test 'csv => Block (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 162
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Block (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 169
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Failed test 'csv => Channel (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 188
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Channel (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 202
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Channel (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 216
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Failed test 'csv => Supplier (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 226
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Supplier (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 235
\# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
\#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
\# Failed test 'csv => Supplier (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 244
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Failed test 'csv => Hash + hdrs (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
\# at t/90_csv.t line 252
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("3"), :baz("1"), :foo("2")}, {:bar("2"), :baz("a b"), :foo("")}]
\# Failed test 'AOH parse out'
\# at t/90_csv.t line 268
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Failed test 'AOH parse out no header'
\# at t/90_csv.t line 271
\# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
\#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
\# Looks like you failed 20 tests of 428
Aborting due to test failure: Text::CSV:ver<0.008>:auth<github:Tux> (use --force-test to override)
===> Testing [FAIL]: Text::CSV:ver<0.008>:auth<github:Tux>

**Comment by hankache** [comment]
I tried using both RCs (Linux and Windows) and couldn't reproduce this error. In both cases Text::CSV installed successfully.

Can someone else try?

**Comment by michael-776** [comment]
I discovered the "zef nuke StoreDir TempDir" command, and after using that I was able to do a successful "zef install Text::CSV"  
So maybe just a corrupted download? 
I thought I had deleted the old source download before  when looking at the problem, I guess I was wrong. Sorry about that.

**Comment by hankache** [comment]
@michael-776 No worries.

**Comment by AlexDaniel** [comment]
Alright!
