### ISSUE TITLE
What is the use of "is dynamic" ?  Maybe we should deprecate it?

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2768]
There seems to be little point in externalizing the `is dynamic` trait.  It currently only makes sense if you also add the `*` as a twigil, but then you don't have to as the `*` twigil makes already makes it dynamic.  Even adding `no strict` doesn't make it work, as that just silently creates a lexical that masks the dynamic.

    $ perl6 -e 'sub a() { dd $*a }; my $*a = 42; a'
    Int $*a = 42

    $ perl6 -e 'sub a() { dd $*a }; my $a is dynamic = 42; a'
    Failure.new(exception => X::Dynamic::NotFound.new(name => "\$*a"), backtrace => Backtrace.new)

    $ perl6 -e 'sub a() { dd $*a }; my $a is dynamic = 42; a'
    ===SORRY!=== Error while compiling -e
    Variable '$a' is not declared
    at -e:1
    ------> sub a() { dd ⏏$a }; my $a is dynamic = 42; a

    $ perl6 -e 'sub a() { no strict; dd $a }; my $a is dynamic = 42; a'
    Any $a = Any

**Comment by lizmat** [comment]
The only example (lifted from documentation) that *does* work.  But OTOH, we want to discourage the use of `CALLER::`, so maybe that's another reason for de-emphasizing `is dynamic` in favour of just using the twigil `*` syntax?

    $ perl6 -e 'sub a() { dd $CALLER::a }; my $a is dynamic = 42; a'
    Int $a = 42

**Comment by JJ** [comment]
Maybe move this now to the problem-solving repo?

**Comment by jnthn** [comment]
> Maybe move this now to the problem-solving repo?

Ah, I'd been meaning to reply to this one, but forgot.

`is dynamic` abstracts the concept behind:

* Dynamic variable declared `$*FOO`
* Implicitly dynmaic things (`$!` and `$/`)

That is, to make the symbol available by `CALLER` and `CALLERS` introspection, and as a side-effect of that prevent the optimizer from optimizing the symbol away completely (which it's free to do with ordinary lexicals).

I agree that the vast majority of the time, `is dynamic` isn't something a Perl 6 programmer would need to use. Like the MOP, it's more of a power-user feature, for use in modules or in language extension. For example, one could introduce their own variable trait that delegates to `is dynamic` as part of its overall action. Concrete scenario: a module that allowed marking of variables as the inputs to an equation; one could then call a solver, which would use `CALLER::` to access those variables.
