### ISSUE TITLE
Multi-dispatch chooses wrong proto during compile-time execution

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#2772]
## The Problem

When the following conditions are met:

- class 'Foo' defines a `proto method foo`
- class `Bar` is declared in the same compunit and inherits from `Foo`
- `Bar` defines a `multi method foo`

In this case  if the `multi` method `foo` would be called on a instance of `Bar` during compilation time rakudo will chose the `proto` `method` from `Foo` resulting in use of wrong `MultiDispatcher` instance and, correspondingly, ignoring the `multi` variant from `Bar`.

## Steps to Reproduce

The problem is best demonstrated when a module file is used. For example, the following archive contains _multi-method.pm6_ and _multi-method.p6` files. Both are instantiating `Bar` class and calling its `foo` method in `BEGIN` blocks while _.p6_ also does it during normal run time.

[multi-method.zip](https://github.com/rakudo/rakudo/files/2985713/multi-method.zip)

To ease describing the problem, I'll duplicate their code here:

_multi-method.pm6_
```
     unit module multi-method;
     no precompilation;

     class Foo is export {
         proto method foo (|) {*}
         multi method foo (Mu \o) { say "foo(Mu)" }
     }

     class Bar is Foo is export {
         multi method foo (Any \o) { say "foo(Any)" }
     }

     BEGIN {
         say "precomp.";
         Bar.new.foo(Str);
     }
```

_multi-method.p6_
```
     #!/usr/bin/env perl6
     use lib '.';
     use multi-method;

     BEGIN {
         say ".p6 BEGIN";
         Bar.new.foo(Str);
     };

     Foo.new.foo(Str);
     Bar.new.foo(Str);
```

_multi-method.p6_ would generate the following output:

>```
>precomp.
>foo(Mu)
>.p6 BEGIN
>foo(Mu)
>foo(Mu)
>foo(Mu)
>```

Note the `no precompilation;` line. Removing it results in completely different picture. The first run when there is no precompiled code for the module results in the following output:

>```
>precomp.
>foo(Mu)
>.p6 BEGIN
>foo(Any)
>foo(Mu)
>foo(Any)
>```

Obviously, any following execution would only have the part of the output which starts with '.p6 BEGIN` line.

# Environment
* Operating system: macOS, Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.03 built on MoarVM version 2019.03

**Comment by vrurg** [comment]
The bug was discovered while working on perl6/problem-solving#3 and #2166. Initially I found it in `SubsetHOW` code which tries calling `ACCEPTS` on a `Block` instance in `accepts_type` method as a consequence of validating a container's default value when a variable/attribute is declared as a `subset`. The sequence of actions leading to the bug is following:

- _Perl6/Actions.nqp_ processes a variable/attribute declaration
- it calls `check_default_value_type`
- `nqp::istype` validates type acceptance with `SubsetHOW.accepts_type`
- the method calls `ACCEPTS` on `$!refinement` attribute.
- `ACCEPTS` fails because no match was found for a multi-dispatch.

I traced the problem down to method `onlystar` in _Perl6/Actions.nqp_ where it generates `nqp::invokewithcapture` call on a method found either in multi-cache or by calling `find_best_dispatchee`. Because this is the first time, there is no cache yet. So, `find_best_dispatchee` is been fed with what `nqp::getcodeobj(nqp::curcode())` returns. The problem is that instead of cloned copy of `ACCEPTS` `proto method` added to the `$!refinement`'s class (in my case it was `Block` and, correspondingly, `ACCEPTS` `proto` should've been from `Code`) `getcodeobj` returns the original `proto method` from class `Mu`. Consequently – `find_best_dispatchee` considers only the two candidates from `Mu` and fails to find the one which would accept instantiated `Block` invokator.

This is also the point where I see why everything works fine with precompiled code. When I look at `MVM_frame_get_code_object` function in `MoarVM` _core/frame.c_ source I see that in the presence of a resolved serialization context it provides the valid code object. Otherwise, as far as I understand it, when `proto` method is cloned in `Routine.derive_dispatch` method it preserves "memory" about the original method (`Mu.ACCEPTS` in my case) which is then fetched by `nqp::getcodeobj`.

And this is the point at which I stopped because of my lack of knowledge about the architecture of `nqp` and `MoarVM`.

**Comment by vrurg** [comment]
I probably got closer to the source of the problem. This is how I see it now:

When `derive_dispatcher` method clones `proto method` at compile time the method exists as a stub, created in `Perl6::World.finish_code_object` method. Correspondingly, the clone is a stub too. The actual method is not compiled until a call takes place. 

Now, we have two code objects with two stubs stored in `%!methods` attributes of metaobjects of two classes. But both stubs share the same closure, they got from `finish_code_object` method where they were created. Because actual compilation in this case  takes place in a thunk which refers to `$code` parameter of the `finish_code_object` method, the resulting compiled `proto method` code is the original method, not the result of `clone` in `derive_dispatcher`.

**Comment by vrurg** [comment]
Fix is merged.

**Comment by jnthn** [comment]
We should really add tests before closing.

**Comment by vrurg** [comment]
@jnthn sorry, I forgot about the tests! I will produce a PR for roast later today.

**Comment by vrurg** [comment]
@jnthn Added perl6/roast#521 and rakudo/rakudo#2784

**Comment by jnthn** [comment]
@vrurg Excellent; merged both.
