### ISSUE TITLE
$p is Mu

### ISSUE THREAD

**Issue by taboege** [rakudo/rakudo#2773]
## The Problem
There seems to be a lexial $p declared and Mu:
```
say $p
#= (Mu)
```
Other names such as $res and $iter are also affected. @ugexe (https://colabti.org/irclogger/irclogger_log/perl6?date=2019-03-19#l741) found this commit: https://github.com/rakudo/rakudo/blob/774ec5a0cb3e00fa4f5159228f540632277f2d30/src/core/signals.pm6

#2366 seems to result from the same thing.

**Comment by ugexe** [comment]
See: https://github.com/rakudo/rakudo/commit/774ec5a0cb3e00fa4f5159228f540632277f2d30

https://github.com/rakudo/rakudo/blob/774ec5a0cb3e00fa4f5159228f540632277f2d30/src/core/signals.pm6#L3-L8

**Comment by lizmat** [comment]
Fixed with 76b6416d00 .  Not sure how to test this.

**Comment by jnthn** [comment]
@lizmat If nothing else, a Rakudo test that checks everything in `CORE::.keys` falls within a whitelist of things we're OK with, so we know if another accidentally slips in.

**Comment by lizmat** [comment]
Test added with 4825f31e29 .  Should we do this also with SETTING::  PROCESS:: and the like?

**Comment by lizmat** [comment]
Added tests for keys on `SETTING::` and `PROCESS::` with 9399ea1198
