### ISSUE TITLE
Defined-or operator lets negative subscript cause a crash

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#2788]
## The Problem
Given:
`my @a = 1..2 Z 'a'..'b';`

These work as they should
`say @a[ $_][   1] // 42 for <0 -1>; # prints 'a' and '42'`
`say @a[*-1][$_] // 42 for <0 -1>; # prints '2' and '42'`

But // fails to catch the negative subscript value (in the 1st dimension)
 when subscripting with `*-1` (in the 2nd dimension)
`say @a[$_][*-1] // 42 for <0 -1>`;
`Fails with "Index out of range. Is: -1, should be in 0..^Inf"`

## Environment
Failure first seen with:
Rakudo version 2019.03-40-g4ffb4082b built on MoarVM version 2019.03-31-g6c7810ce7

**Comment by AlexDaniel** [comment]
Bisected: https://github.com/rakudo/rakudo/commit/4ffb4082b04a87cdddca098bad0089d943651942

**Comment by lizmat** [comment]
Fixed with 7bbbebc0be and 9ce87eeb9c

**Comment by lizmat** [comment]
Tests added with https://github.com/perl6/roast/commit/1e29231ed5f0223ff64e01 .  So closing.
