### ISSUE TITLE
Zero-width negative assertion with character class does not work at end-of-string

### ISSUE THREAD

**Issue by dmaestro** [rakudo/rakudo#2791]
## The Problem

Trying to match a token not followed by non-whitespace.

Using a character class within a negative zero-length assertion (`<!before ... >`) fails to match when the token is at the end-of-string.

I've tried combinations with various character classes ( `\S`, `<[ a..z ]>`, etc.) and all fail to match the same way.

Using property tests or alternation with `$` work fine, and I can't see any reason why character classes shouldn't work similarly.

## Expected Behavior

These work as expected:
`"C"  ~~ / <:Lu> <!before <:!Space> > / # ｢C｣`
`"C "  ~~ / <:Lu> <!before <:!Space> > / # ｢C｣`
`"Cm" ~~ / <:Lu> <!before <:!Space> > / # Nil`

## Actual Behavior

These (essentially equivalent) do not:
`"C"  ~~ / <:Lu> <!before \S > /    # Nil`  !!
`"C " ~~ / <:Lu> <!before \S > /    # ｢C｣`
`"Cm" ~~ / <:Lu> <!before \S > /    # Nil`

## Test (using grammar)

z-length_negative_assertion.t
```
use v6;

grammar Chord {
    rule TOP { <key> \S* }
    regex bare-key { <key> <!before \S > }
    regex bare-key-one { <key> [ <!before \S > | $ ] }
    regex bare-key-two { <key> <!before <:!Space> > }
    token natural-note { <[ A..G ]> }
    token accidental { <[ \# b ]> }
    regex key { <natural-note> <accidental>? }
}

use Test;

ok Chord.parse('C#');
ok my $m = Chord.parse('C#m');
note 'C#m: ', $m;

ok ! Chord.subparse(:rule(<bare-key>), 'C#m');
ok Chord.subparse(:rule(<bare-key>), 'C# m');
ok Chord.subparse(:rule(<bare-key>), 'C# ');
ok Chord.subparse(:rule(<bare-key>), 'C#'), 'Character class recognizes end-of-line';
ok Chord.subparse(:rule(<bare-key-one>), 'C#'), 'Alternation recognizes end-of-line';
ok Chord.subparse(:rule(<bare-key-two>), 'C#'), 'Property recognizes end-of-line';

done-testing;
```

## Environment
* Operating system: 
```
Linux ender 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz GenuineIntel GNU/Linux
```
* Compiler version (`perl6 -v`): 
```
$ perl6 -v
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
```

Also tested with irc camelia-bot :-)

**Comment by dmaestro** [comment]
Test file:
https://gist.github.com/dmaestro/15aa917cd7238f8dcea637ea5a5e3526

**Comment by dogbert17** [comment]
Seems to be an optimizer problem since running the test file with --optimize=0 or --optimize=1 works whereas --optimize=2 fails.

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-m -v
    This is Rakudo version 2019.07.1-467-g8f30cc7 built on MoarVM version 2019.07.1-315-gf10a31b
    implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ perl6 --optimize=1 test.pl6
    ok 1 - 
    ok 2 - 
    C#m: ｢C#m｣
     key => ｢C#｣
      natural-note => ｢C｣
      accidental => ｢#｣
    ok 3 - 
    ok 4 - 
    ok 5 - 
    ok 6 - Character class recognizes end-of-line
    ok 7 - Alternation recognizes end-of-line
    ok 8 - Property recognizes end-of-line
    1..8
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ perl6 --optimize=2 test.pl6
    ok 1 - 
    ok 2 - 
    C#m: ｢C#m｣
     key => ｢C#｣
      natural-note => ｢C｣
      accidental => ｢#｣
    ok 3 - 
    ok 4 - 
    ok 5 - 
    not ok 6 - Character class recognizes end-of-line
    # Failed test 'Character class recognizes end-of-line'
    # at test.pl6 line 22
    ok 7 - Alternation recognizes end-of-line
    ok 8 - Property recognizes end-of-line
    1..8
    # You failed 1 test of 8
