### ISSUE TITLE
CatHandle cannot be created from a lazy list

### ISSUE THREAD

**Issue by scovit** [rakudo/rakudo#2796]
## The Problem

```
$ perl6 -e 'my $inflist = 1..*; my @inflist = $inflist.map: { "$_.txt" }; my $*ARGFILES = IO::CatHandle.new(@inflist);'
```

## Expected Behavior

Create a Lazy CatHandle

## Actual Behavior

```
Cannot .elems a lazy list
  in block <unit> at -e line 1
```

## Comment with slightly higher entropy content

I cannot make any sense of `IO::CatHandle` if this cannot handle infinite lists of files. It is just extremely slow and bogus. But I might be missing some reasoning

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/0f005e842c
