### ISSUE TITLE
Using quantifiers with zero-width regex elements runs until out of memory

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2806]
## The Problem
See title.

## Expected Behavior
An exception should be thrown.

## Actual Behavior
The code will run until the process runs out of memory.

## Steps to Reproduce

```
bastille% perl6 -e "'If two astronauts were on the moon and one bashed the other\'s head in with a rock would that be fucked up or what?' ~~ / <wb>+ /" 
MoarVM panic: Memory allocation failed; could not allocate 36864 bytes
```

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.4 GENERIC.MP#683 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
Related: https://rt.perl.org/Public/Bug/Display.html?id=132004

**Comment by vendethiel** [comment]
In all but the simplest cases, this seems like a NP-hard problem to solve.
