### ISSUE TITLE
Autothreading gone wrong?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2814]
## The Problem

```
<a b c d e f>.classify( * eq 'a'|'c'|'f' ).say; #2813  OUTPUT: «{False => [a b b b c c d d d e e e f f], True => [a c f]}␤» 
(1..5).classify( * == 1|3|5 ).say; # OUTPUT: «{False => [1 2 2 2 3 3 4 4 4 5 5], True => [1 3 5]}␤»  
```

## Expected Behavior

No idea. At least, if they are repeated, they should be repeated the same number of times. If the Junction receives another member, non-junctioned members repeat themselves that number of times

```
07:54:26   jmerelo | m: (1..5).classify( * == 1|3|5|7 ).say # OUTPUT: «{False => [1 2 2 2 2 3 3 3 4 4 4 4 5 5 5], True => [1 3 5]}␤»                                │
```

## Environment

Reproducible in [Camelia](https://gist.github.com/Whateverable/11c9ac8ec81c1274c28d250f6b8dfb7f)

**Comment by tony-o** [comment]
@jj did you mean to use `~~ 'a'|'c'|'f'` ?

**Comment by JJ** [comment]
@tony-o no, I meant to use precisely that, as in the roast test. The classification is shown in the output, and if that's the case, b would be classified as any(False, True, False) and f as any(False, False, True). How come then a appears once classified as True, once as False, and c and f twice as True and once as False?
the fact that the elements of the list appear several times, I can grok that (although it keeps being mildly bewildering). But the fact that the first one of them appears one time less than the rest, that's what strikes me.

**Comment by FCO** [comment]
maybe the returned value should be `.Bool` before used as key if its. a junction?

**Comment by lizmat** [comment]
Golfed to:

    say <a>.classify: * eq "a"|"b";  # {False => [a], True => [a]}

Compare this to:

    say (* eq "a"|"b")("a");  # any(True, False)

And you should see why "a" gets added in both `True` and `False`.

**Comment by FCO** [comment]
```perl6
<a b c d e f>.classify( * eq 'a'|'c'|'f' )
```
I can't see another reason to use that unless I want `{False => [<b d e>], True => [<a c f>]}` as response, but to do what I want, I could just add a `so`...

```perl6
<a b c d e f>.classify( so * eq 'a'|'c'|'f' )
```

I think it would make sense to `classify` do to Junctions the same thing `so` does ...

**Comment by lizmat** [comment]
Would you want that for all types of `Junction`s, or just the ones that happen to have `Bool`s only in their eigenstates?

**Comment by lizmat** [comment]
How about making `.classify` die when using a `Junction` to classify?  Suggesting to add a `so` to the condition?

**Comment by lizmat** [comment]
For reference, 7fa2ba77d438a7169f6b1e1 introduced the current behaviour: before that, it was an (unintentional) execution error.

**Comment by lizmat** [comment]
A diff that would make that an error:

    --- a/src/core/Hash.pm6
    +++ b/src/core/Hash.pm6
    @@ -312,6 +312,13 @@ my class Hash { # declared in BOOTSTRAP
                         $tested := test($value);
                     };
                 }
    +
    +            # Junctions are bad mojo in classify
    +            elsif nqp::istype($tested,Junction) {
    +                die "Using a Junction to classify with, will not to what you th
    +Perhaps you need to prefix a 'so' to the condition?";
    +            }

**Comment by lizmat** [comment]
Doing that diff makes test fail in t/spec/S32-list/classify.t .  If we decide to do this, we would probably need a deprecation cycle.

**Comment by JJ** [comment]
The 6.d spec includes that. I don't think it should be deprecated or
eliminated. If only the behavior for all elements in the list was
consistent, that might be explainable.

**Comment by lizmat** [comment]
Then I'm not understanding the inconsistent part.  As far as I understand it, it *is* consistently doing what it is supposed to, although this may not be what you expected.  Could you elaborate?

**Comment by tony-o** [comment]
@FCO using `~~` rather than `eq` would give the same as using `so * eq`. 

The current output is useful and shouldn't die.

**Comment by FCO** [comment]
@tony-o the `~~` works because it do not return a `Junction`, so no `Junction` would be received by the classify, so it would not die...

**Comment by tony-o** [comment]
@FCo the question was raised as to whether it should die, I think it shouldn't and the distinction between eq and ~~ makes the behavior useful.

**Comment by JJ** [comment]
Again, this is the roast test:
https://github.com/perl6/roast/blob/7dc829e0fbd87d271e5ad3feb2ce3b01ab79f983/S32-list/classify.t#L121-L137

Taking out the tests:
```perl6
say <abc abcdef xyz>.classify: *.contains: any 'a'..'f';
```

prints:
```
{False => [abc xyz xyz xyz xyz xyz xyz], True => [abc abcdef abcdef abcdef abcdef abcdef abcdef]}
```

Which is, of course, according to spec since it passes the test. Now, how would you describe that behavior?

If it was only the repeated outputs, I could live with that. But repeated output *and* inconsistent behavior for the first element of the list, I don't think that's according to spec. Please note that in the example (as well as in the test) there's no ~~ vs eq|==. I simply used that example because it reproduces the same behavior.

**Comment by JJ** [comment]
Also, what @lizmat  said: is it spec that *the first element* is classified as both True and False?

**Comment by tony-o** [comment]
@jj - I see.  I think if the return value is a list of values then yes that is spec and `eq Junction` does just that. `.contains: any` returns a junction but to your point it `abc` should be in the `False` list three times and the `True` list three times rather than the inconsistent one and one.

I think I see what's happening.  But, it doesn't sound like we agree on how to fix.  Should `die` with `did you mean ~~ or so ?`, should it auto-coerce to that _if_ it's comparing to a `Junction` (but default to the described behavior if given a list) or should it do something else?

**Comment by JJ** [comment]
@tony-o at least the test should be rewritten so that it precisely reflects the spec, I guess. The problem is that the spec is vague "classify should work with Junctions". The test kinda reflects that... So I really have no idea what the spec behavior should be.

**Comment by tony-o** [comment]
Seems consistent with the error of an `Iterable` throwing an error in that method to throw a `did you mean ~~ or so ` and for that test to be split into two, one with a `so` producing`False => [xyz], True => [abc abcdef]` and the other dying.

I'll submit a patch

**Comment by tony-o** [comment]
This has been golfed down to: `my %x;  %x{any(True, False, False)}.push: 5;  %x{any(True, False, False)}.push: 15;` which produces `%x( True => [5, 15], False => [5, 15, 15] )`.

Forcing this to die with the Junction error limits the abuse to this function and I'm inclined to only patch after further discussion.  The actual issue golfs down to: how do we want to handle assigning hash keys from a junction?

**Comment by JJ** [comment]
I'm kinda lost here. Shouldn't 5 be pushed twice to False too? As in True,
False, False? Why is only 15 pushed twice?

**Comment by JJ** [comment]
So, short answer: always consistently. How is none handled, anyway?

**Comment by tony-o** [comment]
@JJ I think it's consistent with `Junction` short circuiting

`Implementations are allowed to short-circuit Junctions. For example one or more routine calls (a(), b(), or c()) in the code below might not get executed at all, if the result of the conditional has been fully determined from routine calls already performed (only one truthy return value is enough to know the entire Junction is true):` - from https://docs.perl6.org/type/Junction

**Comment by vrurg** [comment]
As I mentioned it in Raku/problem-solving#297, since the classifier results in a junction (`eq` autothreads), the classification keys must be junctions. Here is the first approach:

```
⇒ ./rakudo-m -e "<a b c d e f e>.classify( * eq 'a'|'c'|'f' ).say;"
{any(False, False, False) => [d], any(False, False, False) => [e], any(False, False, False) => [b], any(False, False, False) => [e], any(True, False, False) => [a], any(False, False, True) => [f], any(False, True, False) => [c]}
```

Since every invocation of the classifier results in a new junction, the outcome is expected because the underlying hash is parameterized with `Mu, Mu`.

I need to resolve some failing spectests, but otherwise I'd say that the above outcome is what is to be expected.
