### ISSUE TITLE
Cannot run perl6 without using LD_LIBRARY_PATH on OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2818]
## The Problem
MoarVM can't find `libmoar.so` when it's compiled to be relocatable, but can't find its dependencies when it's compiled not to be. The only way I can get perl6 to run is to compile moar to be relocatable and export `LD_LIBRARY_PATH`, `NQP_HOME`, and `PERL6_HOME` manually before running it.

I don't think this was an issue back when I originally tested relocatable MoarVM, but that was long before many commits related to it were added.

## Expected Behavior
perl6 and moar should be possible to compile to be relocatable or not relocatable.

## Actual Behavior
They're not.

## Steps to Reproduce

Install `moar` with a path given to `--prefix` and try to run it with the path in `PATH`:
```
bastille% moar
ld.so: moar: can't load library 'libmoar.so'
zsh: killed     moar
```

This the output of `readelf`:
```
bastille% readelf -d $HOME/.perl6/bin/moar 

Dynamic section at offset 0x3098 contains 21 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
 0x0000000000000001 (NEEDED)             Shared library: [libmoar.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.95.0]
 0x000000000000001e (FLAGS)              ORIGIN
 0x000000006ffffffb (FLAGS_1)            Flags: ORIGIN
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000007 (RELA)               0x870
 0x0000000000000008 (RELASZ)             240 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          8
 0x0000000000000017 (JMPREL)             0x960
 0x0000000000000002 (PLTRELSZ)           672 (bytes)
 0x0000000000000003 (PLTGOT)             0x3200
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x2c0
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x6c8
 0x000000000000000a (STRSZ)              424 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x5a8
 0x0000000000000004 (HASH)               0x5c8
 0x0000000000000000 (NULL)               0x0
```

And with `LD_DEBUG=1`:
```
bastille% LD_DEBUG=1 moar
ld.so loading: 'moar'
exe load offset:  0x231aa8d5000
 flags moar = 0x80
head moar
obj moar has moar as head
orig_path $ORIGIN/../lib
new_path  /home/morfent/Documents/zef/../lib
 flags /usr/lib/libwcwidth-icons.so = 0x0
obj /usr/lib/libwcwidth-icons.so has moar as head
linking dep /usr/lib/libwcwidth-icons.so as child of moar
examining: 'moar'
loading: libc.so.95.0 required by moar
 flags /usr/lib/libc.so.95.0 = 0x0
obj /usr/lib/libc.so.95.0 has moar as head
loading: libmoar.so required by moar
ld.so: moar: can't load library 'libmoar.so'
zsh: killed     LD_DEBUG=1 moar
```

It looks like `$ORIGIN` is getting ignored entirely.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.5 GENERIC.MP#839 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03.1-150-gd5044de2f built on MoarVM version 2019.03-68-g25b486dee
implementing Perl 6.d.

**Comment by patzim** [comment]
I'll have a look.

**Comment by patzim** [comment]
[This email correspondence](https://www.mail-archive.com/misc@openbsd.org/msg143490.html) describes a very similar problem. The symptoms the asker in that thread describes match the ones in this bug report. Thus I assume OpenBSD still lacks a usable implementation of $ORIGIN.

**Comment by patzim** [comment]
An interesting idea is to use dlopen to link the libmoar.so at runtime. I know little about dlopen. But a basic requirement for this to work is a way to determine the executable path at runtime. A quick google doesn't look good. [libuv](https://github.com/libuv/libuv/blob/master/src/unix/openbsd.c#L84) inspects ARGV[0] (I haven't done any tests, but is ARGV[0] always absolute on OpenBSD?). [whereami](https://github.com/gpakosz/whereami) [doesn't support OpenBSD](https://github.com/gpakosz/whereami#issuecomment-254142506).

**Comment by patzim** [comment]
I guess the conservative thing is to disable relocatability on OpenBSD for now, just as we do with AIX. :-(

**Comment by Kaiepi** [comment]
I tried reproducing the issues I had earlier with installing moar with `--no-relocatable` but I can't seem to get them to happen again. I must've forgotten to switch to master from my branch that builds MoarVM with jemalloc

**Comment by Kaiepi** [comment]
Never mind, found it. Passing `--has-dyncall` and `--no-relocatable` to `./Configure.pl` when building moar creates an executable that can't find any dyncall libraries.

**Comment by patzim** [comment]
Does that mean the bugreport can be closed once the MoarVM PR is merged?

**Comment by Kaiepi** [comment]
>Never mind, found it. Passing --has-dyncall and --no-relocatable to ./Configure.pl when building moar creates an executable that can't find any dyncall libraries.

I looked more into this. Rakudo can't find `dynext/libperl6_ops_moar.so` when running either `make` or `make install`, not sure which since I just run `make install` usually. This didn't happen when I tested again, so I'm guessing it only happens if the file doesn't already exist by installing in other ways first.

>Does that mean the bugreport can be closed once the MoarVM PR is merged?

Yes.

**Comment by patzim** [comment]
[MoarVM/MoarVM#1089](https://github.com/MoarVM/MoarVM/pull/1089) just got merged.
Not sure what's still left to do here. Is the build still broken on OpenBSD? Are you on this? Should I have another look?

**Comment by Kaiepi** [comment]
Nah, everything works now.
