### ISSUE TITLE
Rounding behaviors

### ISSUE THREAD

**Issue by alabamenhu** [rakudo/rakudo#2826]
## The Problem

`.round` currently works on ~half-up~ away-from-zero principle for equidistant values.  Some applications of rounding need to use half-even (IEEE specifies this method, for instance)

## Expected Behavior

1.5.round == 2
2.5.round == 2
3.5.round == 4
4.5.round == 4

## Actual Behavior

1.5.round == 2
2.5.round == 3
3.5.round == 4
4.5.round == 5

## Steps to Reproduce

See above.

I'm not sure the best way to introduce it, as the current method is certainly the "default" interpretation in most people's mind and changing the default would be breaking.  Perhaps adding an adverb for rounding modes?

**Comment by AlexDaniel** [comment]
May I ask why you need this? It'll help us understand why this needs to be part of the language. Somewhat related: https://github.com/perl6/problem-solving/issues/4

**Comment by alabamenhu** [comment]
I'm currently working on an implementation of CLDR / ICU stuff, and the rounding is specified as being the default for binary floats.  This is also the default rounding method for Java, Python, Haskell, among others, since it's the default under IEEE 754.  For any implementations or ports, there's likely going to be an unstated assumption that the rounding mode is this way and to maintain equivalent results between languages there should be an easy way to maintain similar math results.  (I only noticed it because the Unicode's TR35 specifically mentioned that half-even rounding was the expected default, and upon testing realized that — even when using Num or native floats rounding is always up)

For most applications, not doing it won't cause a problem and of course a separate module can be written (and I'll probably do that in the meantime), but it seems like it'd be better handled at the core level — and it was suggested by tony-o on #perl6 to open a ticket for it.

**Comment by tony-o** [comment]
If there isn't any objection, it wouldn't be difficult to add adverbs
half-[even|odd|down] or [away-from|toward]-zero to round while maintaining
the default half-up

**Comment by alabamenhu** [comment]
> If there isn't any objection, it wouldn't be difficult to add adverbs half-[even|odd|down] or [away-from|toward]-zero to round while maintaining the default half-up

I should actually probably correct myself in that P6 is defaulting to an away-from-zero.  The other IEEE defined methods are toward-zero, toward-positive-infinity, toward-negative-infinity and half-even (but curiously, not half odd). 

toward-negative-infinity is a long adverb though.  Maybe use half-up/half-down for the infinities, and then have toward-zero / away-from-zero (longer, but also the default), and half-even / half-odd to gravitate to those numbers?

**Comment by AlexDaniel** [comment]
Just as heads up, I temporarily closed https://github.com/rakudo/rakudo/pull/2831 because there was no decision yet. Changes to the language are nowadays requested in https://github.com/Raku/problem-solving, so please recreate this ticket if you think more rounding modes should be added.

However, I'll tell you right away that the change you're requesting is potentially harder than it seems, and you should definitely be prepared to list *all* edge cases and convince me (as one of the reviewers) that you indeed covered all of them.

**Comment by AlexDaniel** [comment]
Ah, there is already a ticket in the problem-solving repo! https://github.com/Raku/problem-solving/issues/13
