### ISSUE TITLE
Method fallback interfering with method lookup?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2828]
## The Problem

This instance is tested:

    ( j => 3).?foo 

It returns Nil, as expected. However, 

    ( j => 3).?match

which is not tested, returns an error:

    OUTPUT: «(exit code 1) Invocant of method 'match' must be a type object of type 'Any', not an object  instance of type 'Pair'.  Did you forget a 'multi'?␤

## Expected Behavior

It should also return Nil, as the spec says.

## Environment

[Camelia](https://gist.github.com/Whateverable/fc1bbb7de6877b0cb9a4bf3b6ad5411b)

**Comment by lizmat** [comment]
> On 9 Apr 2019, at 09:42, Juan Julián Merelo Guervós <notifications@github.com> wrote:
> 
> The Problem
> 
> This instance is tested:
> 
> ( j => 3).?foo 
> 
> It returns Nil, as expected. However,
> 
> ( j => 3).?match
> 
> which is not tested, returns an error:
> 
> OUTPUT: «(exit code 1) Invocant of method 'match' must be a type object of type 'Any', not an object  instance of type 'Pair'.  Did you forget a 'multi'?␤
> 
> Expected Behavior
> 
> It should also return Nil, as the spec says.

The problem is that Any has a method ‘match’ with an Any:U: signature.  Which seems to have been put there to fix another problem in 1c21974d29be3f2d8a08209 .

Perhaps that commit should be reverted and another fix should be attempted?

**Comment by jnthn** [comment]
> as the spec says

Given that's not what it does, I'm quite sure the spec (e.g. the tests) do *not* say that. :-) The design of `.?foo` has always been that there's a method of that name; if it's a `proto`, that's another level of dispatch and not a concern of `.?`.

> Which seems to have been put there to fix another problem in 1c21974 .

But there was already a multi-method even before that change, no?
