### ISSUE TITLE
Parameter subclasses don't initialize attributes

### ISSUE THREAD

**Issue by patzim** [rakudo/rakudo#2829]
## The Problem
class ParameterChild is Parameter {
    has $.foobar;
}
say ParameterChild.new(foobar => 'Baz').foobar;

## Expected Behavior
Output: 'Baz'
## Actual Behavior
Output: (Any)

I already bisected this to [3d3578b6058d552](https://github.com/rakudo/rakudo/commit/3d3578b6058d552b4842952ad1bfdbd9ed7d3c5f).

This currently breaks Cro::OpenAPI::RoutesFromDefinition.

**Comment by jnthn** [comment]
Fixed and tested now. Arguably, we should have spectests for this functionality too; it is, at least, covered by a Rakudo test, though.
