### ISSUE TITLE
dd sprintf("%#o",65)    # is 0101, shouldn't this be 0o101  ??

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2830]
The output of the format "%#o" is currently inconsistent with the outputs for "%#x" and "%#b":

    dd sprintf("%#b",65);  # "0b1000001"
    dd sprintf("%#x",65);  # "0x41"
    dd sprintf("%#o",65);  # "0101"

This feels like a leftover from the days where `0101` would actually be interpreted as an octal literal number.

**Comment by lizmat** [comment]
FWIW, this behaviour is identical to Perl 5's behaviour in this respect.

**Comment by Altai-man** [comment]
Looking at https://github.com/perl6/specs/blob/master/S32-setting-library/Str.pod#sprintf I don't see any clarifications on how the output should be formatted.

It says "This function is mostly identical to the C library sprintf function", and then "an integer, in binary" or "an integer, in octal", which is rather implies that there are no prefixes included. The prefix is added by the hash flag (`#`), but there are no documentation about flags too.

So the change is very easy to do, but do we want to update roast and nqp tests that will be certainly broken by this?

**Comment by lizmat** [comment]
https://github.com/perl6/problem-solving/issues/11 

Jonathan implies that we should stick with what people expect from `sprintf`.  So that would mean fixing tests when someone (probably me) picks up the work on Sprintf.pm6 again.
