### ISSUE TITLE
macOS library names do not all end in ".dylib"

### ISSUE THREAD

**Issue by remorse** [rakudo/rakudo#2833]
## The Problem

I was trying to use the `NativeCall` feature to interact with the `/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess` library. However, it insisted in trying to load `/System/Library/PrivateFrameworks/UniversalAccess.framework/libUniversalAccess.dylib`, which doesn't exist.

## Expected Behavior

The `is native("/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess")` trait would correctly load the library.

## Actual Behavior

It tries to load a non-existent library.

## Steps to Reproduce

Try the following program:

```
#!/usr/bin/env perl6
use v6;
use NativeCall;

sub UAGrayscaleIsEnabled returns int32 is native("/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess") { * }

say UAGrayscaleIsEnabled();
```

This outputs:

```
$ perl6 toggle_greyscale.pl6
Cannot locate native library '/System/Library/PrivateFrameworks/UniversalAccess.framework/libUniversalAccess.dylib': dlopen(/System/Library/PrivateFrameworks/UniversalAccess.framework/libUniversalAccess.dylib, 1): image not found
  in method setup at /usr/local/Cellar/rakudo-star/2019.03/share/perl6/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 287
  in method CALL-ME at /usr/local/Cellar/rakudo-star/2019.03/share/perl6/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 576
  in block <unit> at toggle_greyscale.pl6 line 13
```

I think this is because the library is some sort of combined library. It is a proper library:

```
$ file /System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess
/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess: Mach-O 64-bit dynamically linked shared library x86_64
```

I think it is a combined library because the particular symbols I'm interested in are located in another location -- `/System/Library/PrivateFrameworks/UniversalAccess.framework/Versions/Current/Frameworks/UAEHCommon.framework/Versions/Current/Libraries/libUAEHDisplay.dylib`.

## Environment
* Operating system: macOS 10.13.6 (Darwin Kernel Version 17.7.0)
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

**Comment by ugexe** [comment]
The name mangling used in NativeCall leaves much to be desired. You can work around the mangling issue by wrapping your library name in a subroutine that returns the stringified path of the library (as shown below):

```
#!/usr/bin/env perl6
use v6;
use NativeCall;

sub UAGrayscaleIsEnabled returns int32 is native(sub { "/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess" }) { * }

say UAGrayscaleIsEnabled();
```

**Comment by remorse** [comment]
Thanks! That does make things work better, although I can't abstract the sub out and just call it there?

That is,

```
sub UALib { "/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess" }
sub UAGrayscaleIsEnabled returns int32 is native(UALib()}) { * }
```

doesn't work. I have to do something like:

```
constant $UALib = "/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess";
sub UAGrayscaleIsEnabled returns int32 is native(sub {$UALib}) { * }
```

**Comment by ugexe** [comment]
You want to pass the subroutine, not the result of calling the subroutine:

```
sub UALib { "/System/Library/PrivateFrameworks/UniversalAccess.framework/UniversalAccess" }
sub UAGrayscaleIsEnabled returns int32 is native(&UALib) { * }
```

**Comment by remorse** [comment]
Thanks! That works perfectly. I'd argue there's still a bug in some way here, but at least I have a much better solution now.
