### ISSUE TITLE
Precomp files contain ENV variables breaking packaging and reproducible builds

### ISSUE THREAD

**Issue by niner** [rakudo/rakudo#2838]
## The Problem

According to my bisection precomp files started containing ENV variables with commit 2d007bf431c173c70bc6f964c5cb8d2da0e5bdae by @ugexe

That's apparent by `strings install/share/perl6/precomp/F9DF3D314C318967262C2CED4F12317325F8D5C3.1555152677.26072/1C/1C08282E0E9C9AD04D60AE924EF6A2DD50636161` yielding results like:

/tmp/ssh-hDmVPftN8fLN/agent.4226
CompUnit::Repository::Staging#name(perl)#/home/nine/rakudo/install/share/perl6,inst#/home/nine/rakudo/install/share/perl6,ap#,nqp#,perl5#
local/sphinx:@/tmp/.ICE-unix/4364,unix/sphinx:/tmp/.ICE-unix/4364
/usr/lib/git:/home/nine/perl5/perlbrew/bin:/home/nine/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/nine/rakudo/install/

This breaks reproducibility of builds as well as packaging rakudo on openSUSE, since the build service will rightfully complain about the BUILDROOT path being contained in installed files.

Note that reprodicibility of builds is also important for not having to recompile all modules on a rakudo rebuild without changes to the source. Such rebuilds may again be triggered by distribution build systems. If they do not automatically rebuild module packages (and most of them don't), the module packages' precomp files will become worthless.

## Expected Behavior

Ordinary precomp files should not contain ephemeral information from the build system.

**Comment by niner** [comment]
This patch seems to fix/work around the issue:

```
diff --git a/src/core/CompUnit/Repository/Installation.pm6 b/src/core/CompUnit/Repository/Installation.pm6
index 56b18700f..aa9b50ff6 100644
--- a/src/core/CompUnit/Repository/Installation.pm6
+++ b/src/core/CompUnit/Repository/Installation.pm6
@@ -9,7 +9,7 @@ class CompUnit::Repository::Installation does CompUnit::Repository::Locally does
     has $!precomp-stores;
     has $!precomp-store;
 
-    my $verbose := nqp::getenvhash<RAKUDO_LOG_PRECOMP>;
+    #my $verbose := nqp::getenvhash<RAKUDO_LOG_PRECOMP>;
 
     submethod BUILD(:$!prefix, :$!lock, :$!WHICH, :$!next-repo --> Nil) { }
 
@@ -200,7 +200,7 @@ sub MAIN(:$name, :$auth, :$ver, *@, *%) {
                 :time(try $file.IO.modified.Num),
                 :$!cver
             };
-            note("Installing {$name} for {$dist.meta<name>}") if $verbose and $name ne $dist.meta<name>;
+            #note("Installing {$name} for {$dist.meta<name>}") if $verbose and $name ne $dist.meta<name>;
             $destination.spurt($content);
         }
 
@@ -274,10 +274,10 @@ sub MAIN(:$name, :$auth, :$ver, *@, *%) {
                 my $source-file = $repo-prefix ?? $repo-prefix ~ $source.relative($.prefix) !! $source;
 
                 if %done{$id} {
-                    note "(Already did $id)" if $verbose;
+                    #note "(Already did $id)" if $verbose;
                     next;
                 }
-                note("Precompiling $id ($source-name)") if $verbose;
+                #note("Precompiling $id ($source-name)") if $verbose;
                 $precomp.precompile(
                     $source,
                     CompUnit::PrecompilationId.new-without-check($id),
```

**Comment by lizmat** [comment]
Maybe a less intrusive change:

-    my $verbose := nqp::getenvhash<RAKUDO_LOG_PRECOMP>;
+    my $verbose := 0;

assuming that also fixes the problem for now?

Longer term: perhaps shell out and do something like:

    my $verbose := qx/set | grep ^RAKUDO_LOG_PRECOMP=/.chomp.substr(19) // 0;

?  Although that probably won’t work on Win systems?

**Comment by lizmat** [comment]
Or more simply:

    my $verbose = ?nqp::getenvhash<RAKUDO_LOG_PRECOMP>;

any string from the hash should then not be directly kept alive anymore, no?

**Comment by niner** [comment]
It's not just the string in RAKUDO_LOG_PRECOMP. Somehow the whole env hash ends up in the precomp files.
