### ISSUE TITLE
Grammar errors out with: Substring length (-243) cannot be negative

### ISSUE THREAD

**Issue by zostay** [rakudo/rakudo#2851]
## The Problem

The DateTime::TimeZone module's parser seems to trigger a problem with grammars or the optimizer or some other internal of Rakudo. This parser was written long ago (mostly in 2013) to parse time zones in the Olson DB. It does not work. It does not appear to be a fault of the grammar itself, though. It is passing through the compiler and dying during execution in an obscure fashion. When I run it (on the Olson DB from 2013 that it ships with), it reports the following output:

```
% perl6 gen-tzdata-classes.pl6 tzdata/backward .
Outputting to .
Reading file tzdata/backward
parsed
0 rules
0 zones
112 links
Substring length (-243) cannot be negative
  in block  at gen-tzdata-classes.pl6 line 196
  in sub MAIN at gen-tzdata-classes.pl6 line 72
  in block <unit> at gen-tzdata-classes.pl6 line 66
```

## Expected Behavior

Either to die with an error at compile time or runtime because there's something wrong with the grammar or match or parser or to run normally.

## Actual Behavior

Dies with a bizarre error about substring length being negative. No call to `substr` or similar is made anywhere in the code and the line that causes the problem is:

```
            my $old-tz = ~$link<old-tz>;
```

where `$link` is a Match object.

## Steps to Reproduce

```
git clone https://github.com/supernovus/perl6-timezone.git
cd perl6-timezone
git checkout 7b5369e508bd2e1a265eaafb4a11939def7d58b9
cd tools
perl6 gen-tzdata-classes.pl6 tzdata/backward .
```

So far I've tried this Rakudo 2018.10, but I will be upgrading to 2019.03 and try again shortly with that and make this go away if it is fixed. However, I wanted to at least record the problem somewhere since I couldn't find it online anywhere except some other online post with an obscure reference to "braids".

## Environment
* Operating system: 
Mac OS X 10.14.4
Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64

* Compiler version (`perl6 -v`): 
This is Rakudo Star version 2018.10 built on MoarVM version 2018.10
implementing Perl 6.c.

**Comment by zostay** [comment]
The problem is identical under the latest Rakudo release:

```
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```

**Comment by ugexe** [comment]
The grammar uses a rule named `to` which you cannot do: https://github.com/supernovus/perl6-timezone/blob/7b5369e508bd2e1a265eaafb4a11939def7d58b9/tools/gen-tzdata-classes.pl6#L26

**Comment by zostay** [comment]
Confirmed.

Seems like it might be useful for Rakudo to at least warn on grammar rules that override methods as rules.

**Comment by lizmat** [comment]
Is this still an issue?  I remember putting in some code to work around this.

**Comment by MasterDuke17** [comment]
bisectable seems to have trouble narrowing it down to the exact commit, but for `raku -e 'grammar A { token TOP { <to> }; token to { \w+ } }; say A.parse("abc")'`, 2023.10 printed `｢｣
 to => ｢｣` and 2023.11 printed `｢abc｣
 to => ｢abc｣`

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/994d0be545
