### ISSUE TITLE
CallFrame.new is not tested

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2853]
## The Problem

This code:

https://github.com/rakudo/rakudo/blob/master/src/core/CallFrame.pm6#L27-L33

is not tested either here or in roast.

## Expected Behavior

For the time being it's a literal copy of sub callframe(), but that need not be the case. It should be tested, probably here.

## Environment

Current source at commit https://github.com/rakudo/rakudo/commit/c940a0ed06b523ee8952108ee292099c5e15eaf6

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/ff9bcf57bc
