### ISSUE TITLE
"try" does not work with signatures of return-type "Nil"

### ISSUE THREAD

**Issue by chrsteel** [rakudo/rakudo#2859]
## The Problem

I think this code...
```
sub my_sub (--> Nil) { say try { +"99" } // "no" };
my_sub;
```
## Expected Behavior
...should say `99`...

## Actual Behavior
...but actually says `no`.

The code works as expected if `--> Nil` is omitted in the sub's signature.

## Environment
* Compiler version (`perl6 -v`): This is Rakudo version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by dogbert17** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/7cab810bce7d0e2b859f6de4b92ccb1a37168b4f, Tests were added as part of fixing https://github.com/rakudo/rakudo/issues/3070

**Comment by vrurg** [comment]
@dogbert17 Thank you! Closing.
