### ISSUE TITLE
Initializing hash works differently depending on comma usage

### ISSUE THREAD

**Issue by voldenet** [rakudo/rakudo#2864]
This bug may be a duplicate of parser bug described here ["Unknown QAST node type NQPMu" when missing a comma hash initialization](https://github.com/rakudo/rakudo/issues/2863)

## Description
```perl6
{:b<B> :a}{"a"}.WHAT.say
```
`(Int)`

```perl6
{:b<B>, :a}{"a"}.WHAT.say
```
`(Bool)`

## Expected
Value of `:a` should always be `(Bool)`.

## Environment
evalable6 at freenode, rakudo-moar cac95fbbc

**Comment by skids** [comment]
Locally I run with PR#1858 applied and get the expected results here.

Maybe someone has time to look over that PR?  It's approaching its first birthday, so I'm sure it would love the attention.

**Comment by lizmat** [comment]
Closing issue since https://github.com/rakudo/rakudo/pull/1858 got merged, skids++
