### ISSUE TITLE
All Junctions behave the same when used to define a hash key

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2865]
## The Problem

There seems to be no distinction between types of junctions when they are used to define a hash key.

```perl6
my %hash = %( "a"|"b" => "c" ); say %hash<a>; #OUTPUT: «c␤»
```

It does not make a lot of sense with `none`

```perl6
my %hash = %( none("a","b") => 1 ); say %hash{"a"} #2816 #2779 # OUTPUT: «1␤»
```

## Expected Behavior

Really can't say. Maybe error with `none`, or special-case `one`. All and any should probably behave that way.

## Environment

https://gist.github.com/Whateverable/ad8a8c3646a7ee4fce3b93c4b15c3b63

**Comment by lizmat** [comment]
Golfed to:

    $ perl6 -e 'sub a($a) { dd $a }; a none("a"|"B")'
    "a"
    "B"

aka, auto-threading does not appear to take into account the type of junction.  Or always creates an `any` junction:

    $ perl6 -e 'sub a($a) { $a }; dd a none("a"|"B")'
    none(any("a", "B"))

@jnthn @masak suggestions?

**Comment by jnthn** [comment]
> aka, auto-threading does not appear to take into account the type of junction

Correct, and I'm not sure it meaningfully can, in general.

>  Or always creates an any junction:

You created the any `Junction` inside of the `none` junction by writing the `|`; the auto-threader simply replicated the input junction structure.

**Comment by lizmat** [comment]
Ah, duh...  I meant:

   $ perl6 -e 'sub a($a) { $a }; dd a none("a","B")'
   none("a", "B")

which works as expected.

**Comment by masak** [comment]
My suggestion is to encourage junctions as hash key (when initializing or assigning to the hash) to the smallest extent possible.

I remember there was another case where we encouraged junctions for hash keys. But that wasn't hash assignment, it was something like `:exists` on a hash slice. Should it have `any` or `all` semantics, "intuitively". No idea, so forbid it and encourage an actual `any` or `all` instead. Feels kinda similar here -- assigning junctions to hash keys is not what junctions are for, really, so maybe disallow it and catch some honest thinkos.

**Comment by lizmat** [comment]
Regarding slicing with a `Junction`: I think that already DWIM:

    $ perl6 -e 'my %h = a => 42, b => 666; dd %h{"a"|"b"}'
    any(42, 666)
    $ perl6 -e 'my %h = a => 42, b => 666; dd %h{"a"&"b"}'
    all(42, 666)

**Comment by lizmat** [comment]
Commit 358d59f disallows using  Junctions for initialization of `Map`s or `Hash`es with a Junction.  This did **not** cause any spectest breakage.  After tests for this have been added, it should be ok to close this ticket.

**Comment by dwarring** [comment]
I use junctions as keys in a number of places, as a shorthand for when there is a many to one mapping between keys and values. One example distilled from https://github.com/p6-pdf/PDF-Content-p6/blob/fff1f2280c2ab3f2c02beaea111fb8346da0625f/lib/PDF/Content/Ops.pm#L396 is setting up a state transition table.
```
enum GraphicsContext is export(:GraphicsContext) <Path Text Clipping Page Shading Image>;
my constant PaintingOps = set <S s f F f* B B* b b* n>;

my constant %Transition = %(
            'BT'     => ( (Page) => Text ),
            'ET'     => ( (Text) => Page ),

            'BI'     => ( (Page) => Image ),
            'EI'     => ( (Image) => Page ),

            'W'|'W*' => ( (Path) => Clipping ),
            'm'|'re' => ( (Page) => Path ),
            'Do'     => ( (Page) => Page ),
            any(PaintingOps.keys) => ( (Clipping|Path) => Page ),
);
```

**Comment by masak** [comment]
That junction doesn't really mean `'W'` _or_ `'W*'` though, does it? Would you expect the `'W'&'W*'` junction to do something different for you, or exactly the same?

I'm not sure the fact that this use happens to save you repeating a few values makes it any less confusing. :wink:

**Comment by masak** [comment]
Put differently, I don't think this is what the junctions _mean_, nor what they are for.

**Comment by lizmat** [comment]
FWIW, I could see an argument for allowing `all` junctions in such a situation.

    my %h = "a"&"b" => 1;  # {:a(1), :b(1)}

**Comment by dwarring** [comment]
I'm not defending it. I've already found something else that I prefer:
```
enum GraphicsContext is export(:GraphicsContext) <Path Text Clipping Page Shading Image>;
my constant PaintingOps = set <S s f F f* B B* b b* n>;

my constant %Transition = %(
            'BT'     => ( (Page) => Text ),
            'ET'     => ( (Text) => Page ),

            'BI'     => ( (Page) => Image ),
            'EI'     => ( (Image) => Page ),

            <W 'W*> => ( (Path) => Clipping ),
            <m re> => ( (Page) => Path ),
            'Do'     => ( (Page) => Page ),
            PaintingOps.keys => ( (Clipping|Path) => Page ),
);
say %Transition.keys.sort;
```
Will change it.

**Comment by lizmat** [comment]
@dwarring: feels to me that's not doing what you think it does?

    $ perl6 -e 'my $s = <a b c>.Set; my %h = $s => 42; dd %h'
    Hash %h = {"b c a" => 42}

**Comment by dwarring** [comment]
@lizmt ahh, you're right. I just look at the gist.

**Comment by masak** [comment]
@lizmat I don't see such an argument. If we had an `each` junction (which was discussed but which we never got), I could see that one having the perfect semantics for this situation. But not `all`, nor `any`.

**Comment by lizmat** [comment]
What would be the functional difference between an `each` and a `all` function?

**Comment by jnthn** [comment]
I'm not particularly inclined to start ruling out use of junctions (and their implicit auto-threading) on a case-by-case basis.

**Comment by jnthn** [comment]
Ah, and doubly not inclined to start doing that based on the kind of `Junction` it is.

**Comment by lizmat** [comment]
Added tests with https://github.com/perl6/roast/commit/40c3f305d9

**Comment by masak** [comment]
@lizmat An `all` junction, besides the hyperthreading semantics, is an uncollapsed `[+&]` of all its constituents. In the hash key case, we're not using the boolean aspect of `all`; only the hyperthreading aspects. That's (IIUC) what `each` was once meant for.

@jnthn Agree, ruling out would be too harsh. Hence my choice of words "encourage [...] to the smallest extent possible". That's more about how we teach the feature than about what we allow.

**Comment by lizmat** [comment]
So if I get this right, an `each` Junction (assuming an `@` infix for fun) would numerify to the number of eigenstates?

    dd +("a" @ "b")  # 2

rather than as a `Junction` of `Failure`s (in this example, because `+"a"` is a `Failure`)?

**Comment by masak** [comment]
No idea how `each` junctions would numify. As far as I know, they were discussed now and then over the past 15 years but never left the idea stage. Their main use would not be numification, but the ability to soak up _repetition_ in the middle of an expression.

If I may be so bold, it might be that the most concrete design of the `each` junction (which, mind you, is still pretty fuzzy) can be found in [this 007 issue](https://github.com/masak/007/issues/158) and [this ancient gist](https://gist.github.com/masak/7074924). (tl;dr: `each` has been a driving macro use case from the start &mdash; this would give us "syntactic `each`", that is, it would never actually be represented as a first-class junction at runtime. This may or may not be in line with Perl 6's design esthetic &mdash; after all, the other junction types are first-class, not syntactic.)

**Comment by masak** [comment]
Oh, and notice how _the first use case_ in that gist is "assign each hash key". :wink:

**Comment by labster** [comment]
I do like the idea of `each` junctions.  A few years back when I was first getting involved in 6, the first-class junctions were confusing, and you're often not quite sure where the junction will collapse.  Having access to syntactic junctions would be very useful.

**Comment by dwarring** [comment]
Could we deprecate the use of Junctions as keys?

**Comment by lizmat** [comment]
@jnthn: instead of prohibiting (which appears to affect code in the wild), should we deprecate instead?

**Comment by AlexDaniel** [comment]
[PDF::Content](https://modules.perl6.org/dist/PDF::Content) is currently broken because of that change. @dwarring, I guess you already know about this?

I don't think there's any other module that relied on this, so I'm fine with fixing the module in this case. I'm also fine with deprecation. Either way I think we should do something about it before the release.

**Comment by lizmat** [comment]
Reverted with 0b9762642c . We need more time / problem solving issue to figure out the best cause of action here.
