### ISSUE TITLE
Grammar error about method 'default' on NQPMu object with 'my $parameter'

### ISSUE THREAD

**Issue by pminten** [rakudo/rakudo#2869]
## The Problem

The following gives a rather confusing error `Cannot find method 'default' on object of type NQPMu`.

```perl6
sub bar($foo) { my $foo }
```

Context: I'm learning Perl 6. This came up while editing some code in emacs which has a mechanism for checking Perl 6 code on the fly (flycheck-perl6). But in this case there wasn't a clear "you goofed here" but a message without any source location information which makes figuring out what went wrong a bit difficult.

## Expected Behavior

A hint about what goes wrong with the location in the source file where the error is.

## Actual Behavior

A rather confusing error method.

```
Cannot find method 'default' on object of type NQPMu
  in any scope_declarator:sym<my> at C:\rakudo\share\nqp\lib/Perl6/Grammar.moarvm line 1
  in any scope_declarator at C:\rakudo\share\nqp\lib/Perl6/Grammar.moarvm line 1
  in any term:sym<scope_declarator> at C:\rakudo\share\nqp\lib/Perl6/Grammar.moarvm line 1
  in any term at C:\rakudo\share\nqp\lib/Perl6/Grammar.moarvm line 1
```

## Steps to Reproduce

`perl6 -e 'sub bar($foo) { my $foo }'`

## Environment
* Operating system: Windows 7
* Compiler version (`perl6 -v`): ```This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.```

**Comment by pminten** [comment]
elcaro on #perl6 tried this in an old version (2018.04) and after seeing a "normal" redeclaration error there ran a bisect. The result is 42024539877fbebfdfbbc9b006106454cdaf5187, which according to it's commit message is relevant.

**Comment by dogbert17** [comment]
The behavior was changed/fixed with commit https://github.com/rakudo/rakudo/commit/3498c540a6ef185287ade361ff955dbf4bb7a213 which in turn fixed (and tested) https://github.com/rakudo/rakudo/issues/3102 and https://github.com/rakudo/rakudo/issues/2909

**Comment by vrurg** [comment]
@dogbert17 Thanks!
