### ISSUE TITLE
$match.^methods.perl dies

### ISSUE THREAD

**Issue by ufobat** [rakudo/rakudo#2870]
I think this is not the expected behavior.
```
> perl6 -e 'my $match = "yada" ~~ /a(d)a/; say $match.^methods.perl'           
Died with X::Method::NotFound
  in block <unit> at -e line 1
```
```
> perl6 -v
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```

**Comment by 0racle** [comment]
Golf'd down to this
```
> Match.^methods.perl
Died with X::Method::NotFound
  in block <unit> at <unknown file> line 1
```

Also affects `Cursor` which is an alias for `Match`

```
> Cursor.^methods.perl
Died with X::Method::NotFound
  in block <unit> at <unknown file> line 1
```

**Comment by ufobat** [comment]
It's one of the methods, cause  `perl6 -e '.say for Cursor.^methods'` prints out a few and then it dies.

**Comment by 0racle** [comment]
It's essentially anything that's an `NQPRoutine`

This works fine
```
> Match.^methods.grep(*.^name ne 'NQPRoutine').perl
```

However, I'm kinda hesitant to consider this a bug. At the very least, it's low priority. There's no good reason I can think to call `.^methods.perl`.

**Comment by ufobat** [comment]
But it does make sense if this code would not fail: `.say for Match.^methods`

I was looking for the not documented methods of Match, https://github.com/perl6/doc/issues/2736

**Comment by niner** [comment]
In that case `.say for Match.^methods>>.name` would be more correct though.
