### ISSUE TITLE
Whatever and excluded max endpoint on range in slice... one off

### ISSUE THREAD

**Issue by skids** [rakudo/rakudo#2872]
## The Problem
In an array slice, a range that uses both an endpoint exclusion on the max side and a whatever star seems to double-count the exclusion and returns one fewer elements than it should.

## Expected Behavior
$ perl6 -e '[1,2,3][1..^*].say;'
(2 3)

## Actual Behavior
$ perl6 -e '[1,2,3][1..^*].say;'
(2)

Traced by AlexDaniel and tobs (and the venerable whateverable bots of course) to 456358e3c3

**Comment by taboege** [comment]
I'm not sure anymore if the "new" behaviour isn't more logical. Indexing with `1..^*` gives the Range `1..^Inf` to the subscript posfix, it doesn't give a Callable that produces a Range given `.elems`:
``` perl6
(^5)[0 ..^ *];           #= (0 1 2 3)
(^5)[{ 0 ..^ $^elems }]; #= (0 1 2 3 4)
```
If the range endpoint is `Inf :excludes-max`, it gives you all it has except the last one. I think that's sensible, but yes, it's off-by-one if you think about `*` being `.elems`.

The [documentation](http://docs.perl6.org/language/list#Range_as_slice) explicitly shows the new behaviour as an example. But in any case, roast has no test for this, at least not in slice.t. So I'm not sure if this must be fixed or if it was an (accidental) fix.

**Comment by skids** [comment]
If 1..^Inf is the interpretation, then still it should return the last element, as that range definitely includes 3.  Excluding the max from the end of an infinite range gives you effectively... an infinite range.  I'm not sure that's what is actually happening, though:

$ perl6 -e '[1,2,3][1..^Inf].say;'
(2 3)

That's sane.  It would make no sense to get (2) out of that.

Consider a user that iteratively increments the endpoint and keeps getting more elements, until they run off the end of the array and stop getting more elements.  That's what they would expect from the slice's special handling of ranges.  They would not expect if they then sent Inf in, to get less elements than they did when they sent e.g. 100000.

Further, a beginning user, not aware of the pitfalls of figuring out what operator grabs a whatever star would not expect `1..^*` and `1..^*-1` to do the same thing and `1..^*` to do something different from `1..^*-0`.

IMO the documentation and implementation are both mistaken.
