### ISSUE TITLE
How Perl6 process the type

### ISSUE THREAD

**Issue by HaoDaWang** [rakudo/rakudo#2876]
## The Problem
I have a confuse about type mechanism of Perl6, because I can write this code in Perl6
```perl6
sub foo(Int bar){ ... }
```
That I can explicitly declare type in Perl6, I want to know is there any special processor of type mechanism in Perl6? 
And I want to know Does Perl6 have compile time?  the code come in compile time first, then come in interpreter? the special processor of type exist in compile time?

Thx for your answers

**Comment by vendethiel** [comment]
> That I can explicitly declare type in Perl6, I want to know is there any special processor of type mechanism in Perl6?

Yes, see the docs page on Perl 6's [Type System](https://docs.perl6.org/language/typesystem).

> And I want to know Does Perl6 have compile time? the code come in compile time first, then come in interpreter? the special processor of type exist in compile time?

Yes, Perl 6 has a compilation phase (most scripting languages do nowadays). The early type errors come IIRC at this moment from the Optimizer

**Comment by HaoDaWang** [comment]
Oh Thx for your reply, this answer resolve my question. Thx :)

can you answer to me does Perl6 has JIT like most scripting languages?
and I don't understand what IIRC means. :(

**Comment by coke** [comment]
IIRC is "if I recall correctly"

The rakudo implementation of perl6 has multiple backends- moarvm is the custom VM that does have a JIT. Using the Java or is backends-, you get whatever those vms provide for a JIT.
