### ISSUE TITLE
CompUnit::Repository::FileSystem doesn't accept IO::Path

### ISSUE THREAD

**Issue by rafaelschipiura** [rakudo/rakudo#2879]
Originally opened by @frithnanth as doc issue 2766. @lizmat asked to reopen here.
https://github.com/perl6/doc/issues/2766
## The Problem

In https://docs.perl6.org/type/CompUnit::Repository::FileSystem the example under "method candidates" reads:

my $repo = CompUnit::Repository::FileSystem.new(prefix => $*CWD);
my $dist = $repo.candidates("Zef").head;
say "Zef version: " ~ $dist.meta<version>;

When I try to execute the first line I get an error:
Type check failed in binding to parameter '$prefix'; expected Str but got IO::Path
I found the same kind of error in the example under "method files".
## Expected Behavior
This seems to work:

my $repo = CompUnit::Repository::FileSystem.new(prefix => ~$*CWD); # or $*CWD.Str or $*CWD.path or similar

**Comment by lizmat** [comment]
Am working on this but it's become part of a larger refactor that I'm not confident enough to merge before the 2019.05 release.
