### ISSUE TITLE
Inconsistency of coercion methods

### ISSUE THREAD

**Issue by ufobat** [rakudo/rakudo#2881]
## The Problem

The coercion methods like `.Array`, `.Str` or `.Int` do remove mixins, sometimes. Maybe It's been optimized out if the Source and Destination Type are _the same_.

## Expected Behavior

That all coercion methods return _plain_ objects without any mixins.

## Steps to Reproduce
```
# doesn't work
> perl6 -e 'role Foo {}; my $a = 42 but Foo; $a.Int.WHAT.say'
(Int+{Foo})
> perl6 -e 'role Foo {}; my $a = "hello" but Foo; $a.Str.WHAT.say'  
(Str+{Foo})

# but for Array it works
> perl6 -e 'role Foo {}; my $a = [1,2,3] but Foo; $a.Array.WHAT.say'
(Array)

# if you change the type it works as well
> perl6 -e 'role Foo {}; my $a = 42 but Foo; $a.Str.WHAT.say'
(Str)

```

**Comment by niner** [comment]
FWIW `.List` on Array was more of a stop gap measure during the GLR drive. `.list` was there already as a no-op and I needed something that downgraded to a List. At least from that we can learn, that there are really three cases for coercion:
* to something that matches a type (like `.list` or `.Str` on Array)
* to the exact type (like `.List` on Array)
* to something providing an API (like `.Stringy`)

Though the `.Stringy`case is technically the same as the "matches a type" case, the common usage of `Str()` in the SETTING compared to an often more appropriate `Stringy()` shows that better distinction would be helpful.

**Comment by lizmat** [comment]
Might I mention [Tuple](http://modules.perl6.org/dist/Tuple) ?

**Comment by lizmat** [comment]
Question: if I have an `Int` with `Foo` mixed in, how can I create an `Int` out of that **without** the `Foo` mixed in?

My first guess would be that `.Int` would be it.  But from @jnthn 's response, I gather that's not what he expected?
