### ISSUE TITLE
EVAL memory leak

### ISSUE THREAD

**Issue by pprocacci** [rakudo/rakudo#2885]
## The Problem
I have a script which is parsing shapes for the services defined in the botocore distribution 
however it never completes and eventually dies due to lack of memory.

It has thousands of iterations.  I was initially using Template::Mustache which didn't exhibit this problem.  It was only until I swtiched to Template::Mojo due to needing something a bit more powerful that the problem cropped up.

I have reason to believe this is due to how Template::Mojo leans on EVAL for template processing.

Note: The script at the end of this issue requires a git clone of https://github.com/boto/botocore.git in the local directory from which it's being ran to function properly.

## Expected Behavior
I expect the script to finished without gobbling up all my memory.

## Actual Behavior
The script eats up all physical memory on the machine then gets killed.

## Steps to Reproduce
- git clone https://github.com/boto/botocore.git
- Place the below script in the same directory.
- Run it

## Environment
* FreeBSD 12
* # perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

Trimmed Version
-----------------------------

```#!/usr/bin/env perl6

use JSON::Pretty;
use Template::Mojo;

my IO @service-files = gather for dir("botocore/botocore/data") {
  if .d {
    my IO $service-file = (dir($_).sort.tail ~ '/service-2.json').IO;
    take $service-file unless !$service-file.f;
  }
}

for @service-files {
  for (from-json .slurp)<shapes>.kv -> $keys, $value {
    Template::Mojo.new('').render();
  }
}

**Comment by lizmat** [comment]
Trimmed even further:

    $ perl6 -Msnapper -e 'my $a = 42; for ^100 { EVAL q/$a++/ }; dd $a'
    Int $a = 142
    Telemetry Report of Process #54898 (2019-05-10T18:06:34Z)
    Number of Snapshots: 9
    Initial/Final Size: 64080 / 160756 Kbytes
    Total Time:           0.79 seconds
    Total CPU Usage:      1.28 seconds
    Supervisor thread ran the whole time

    wallclock  util%  max-rss
       102441  19.64    29556
       107608  21.67    12828
       102720  19.86     9288
       103522  22.77    12868
       102152  18.96    17464
       101962  20.12     6868
       100431  17.64     7104
        70311  22.05      700
    --------- ------ --------
       791147  20.29    96676

    Legend:
    wallclock  Number of microseconds elapsed
        util%  Percentage of CPU utilization (0..100%)
      max-rss  Maximum resident set size (in Kbytes)

**Comment by lizmat** [comment]
@timo: any other suggestions on finding out what is eating memory here?

**Comment by MasterDuke17** [comment]
@lizmat Heaptrack (https://github.com/KDE/heaptrack) can be very useful for this sort of thing.

**Comment by lizmat** [comment]
Isn't there something more MoarVM / Perl 6 specific available ?

**Comment by pprocacci** [comment]
https://github.com/jonathanstowe/LibraryCheck/issues/3

I had forgotten I ran into this program too while developing a curses based application that leaned on Jonathan's LibraryCheck routine linked above.

It just came to me that Jonathan might have the fix already as stated in the above link.  He stated he was going to open an issue but never did.  Any way to ping him to get his eyes on this as "the fix is in" (hopefully)?
