### ISSUE TITLE
Where clause throws 'cannot call method 'chars' on a null object'

### ISSUE THREAD

**Issue by oterhals** [rakudo/rakudo#2886]
## The Problem

```
sub MAIN(Str $a, Str $b where { $a.chars == $b.chars }) { 
    say "$a = $b"; 
} 
```

## Expected Behavior

If the program is called with two parameters, the parameters have to be of equal length. If not, the ususal Usage report will be printed.

## Actual Behavior

If the two strings are of equal length all works as expected. But when they differ, the program throws 'cannot call method 'chars' on a null object'. This happens with Rakudo Star 2019.03.01. 

However: On 2018.06 this works as expected.

## Steps to Reproduce

*$ perl6 test.p6 a b*
a = b

*$ perl6 test.p6 a bd*
Cannot call method 'chars' on a null object
  in block <unit> at test.p6 line 2

## Environment
* Operating system: macOS 10.14.1
* Compiler version (`perl6 -v`): 
Rakudo Star 2019.03.01

**Comment by lizmat** [comment]
Cannot reproduce this on HEAD.  So I assume this has been fixed somehow between 2019.03.1 and the upcoming 2019.05.

**Comment by MasterDuke17** [comment]
FYI, bisected to https://github.com/rakudo/rakudo/commit/dd1c805949b5996a79adeb690cc0d468e2d88836.

**Comment by lizmat** [comment]
hmmm.. reverting that commit, still does not fail for me.  But I think we can keep this ticket closed, right?

**Comment by oterhals** [comment]
I cloned and compiled the rakudo compiler now. This version behaves as
expected, so then I guess we can say this is fixed.

Jo Christian.

**Comment by lizmat** [comment]
Thanks for the confirmation!
