### ISSUE TITLE
my $n = 1 / 0; $n !~~ Failure

### ISSUE THREAD

**Issue by kjkuan** [rakudo/rakudo#2887]
## The Problem
```
my $n = 1 / 0;
$n ~~ Failure;  # should be True, but is False
dd $n;  # OUTPUT: Rat $n = <1/0>

# This works though
my $m = 1 % 0;
$n ~~ Failure;  # True
```
## Expected Behavior
```
my $n = 1 / 0;
$n ~~ Failure ;  #  $n should be a Failure instance instead of a Rat.
```
## Environment
* Operating system:  Ubuntu 18.04.2 LTS
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by jnthn** [comment]
Why should it?

**Comment by kjkuan** [comment]
Using `$n` after `my $n = 1 / 0` does blow up with a `DivideByZero` exception..., it's just that as an user, with my limited understanding of perl 6, I'd expect that `$n` to contain a `Failure` instance as a result of assigning `1 / 0` to it, and that's also the reason that it doesn't blow up on the spot with the exception.

hmm, ok, I suspect the reason is probably we still want a way to represent `1 / 0`. If `1 / 0` returns a `Failure` then there would be no way to represent `1 / 0`, which is equal to `Inf` ?

**Comment by AlexDaniel** [comment]
```perl6
say (1/0).Num # Inf
```

**Comment by kjkuan** [comment]
alright, TIL. Thanks for the clarification.
