### ISSUE TITLE
class{}.can("something") should not work

### ISSUE THREAD

**Issue by ufobat** [rakudo/rakudo#2889]
## The Problem

You can invoke something like this `Mu.can("something")` This works until someone implements the method `can`.. e.g: 
```
perl6 -e 'class Foo {method foo() {}; method can() {} }.can("foo").say'      
```

## Expected Behavior

That you get a runtime error that method can is not defiend.

## Actual Behavior

It seems that you get the same results like `^can` would give.

## Steps to Reproduce
```
perl6 -e 'Mu.can("something").say'
```

**Comment by jnthn** [comment]
The existence of a `can` method inherited from `Mu` is a [specified feature](https://github.com/perl6/roast/blob/master/S12-introspection/can.t) and was even included in the [original design docs](https://github.com/perl6/specs/blob/master/S12-objects.pod#introspection), so this is certainly not an implementation accident or Rakudo bug.
