### ISSUE TITLE
dd fails on lazy lists

### ISSUE THREAD

**Issue by nkh** [rakudo/rakudo#2892]
## The Problem
dd fails when a class element is a lazy list

## Expected Behavior
no failure

## Actual Behavior
output :
Cannot .elems a lazy list
  + stack trace
  + kills the program

## Steps to Reproduce
class C { has $.list = (1...*) } ; dd C.new

compare with:
(1...*)
    OUTPUT: «(1, 2, 3, 4, 5, 6, 7, 8, 9, 10... lazy list)␤»

## Environment
* Operating system: 
linux

* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03.1-317-gb2e72d6d7 built on MoarVM version 2019.03-110-g081823ffc
implementing Perl 6.d.

**Comment by lizmat** [comment]
Golfed to `(1...*).perl`
