### ISSUE TITLE
Rakudo.org "Bugs" page needs correction (removal of obsolete procedure)

### ISSUE THREAD

**Issue by alanrocker** [rakudo/rakudo#2895]
## The Problem
It contains the line:
If you do not have a GitHub account, you can email your report to rakudobug@perl.org.

## Actual Behavior
Mail message bounces
## Environment
N/A

**Comment by lizmat** [comment]
I could not find that line in the perl6.org repo.  I did find another occasion where `rakudobug@perl.org` was mentioned.  I fixed that with https://github.com/perl6/perl6.org/commit/f564bffb1f .

Could you give me the URL of the page where you saw this line?

**Comment by patzim** [comment]
@lizmat: https://rakudo.org/bugs

**Comment by lizmat** [comment]
Oops, yes rakudo.org , not perl6.org.  Removed mention with https://github.com/perl6/rakudo.org/commit/b3d4c4b847 .  Not sure what needs to be done to update the websites, or whether that happens automatically.  Leaving issue open until we see the website change.

**Comment by lizmat** [comment]
Both pages updated online.  Closing now.
