### ISSUE TITLE
Are feed operators supposed to append??

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2899]
$ perl6 -e 'my @a; @a <== 1,2,3; @a <== <a b c>; dd @a'
    Array @a = [1, 2, 3, "a", "b", "c"]  # expected Array @a = ["a", "b", "c"]

In my mind, the pointy end of a feed operator always initializes the receiver.  This seems to be supported by the specs: https://github.com/perl6/specs/blob/master/S06-routines.pod , feed operators:

> It binds the (potentially lazy) list from the blunt end to the slurpy parameter(s) of the receiver on the sharp end.

which would imply that the current implementation of feed operators (which, afaik, predates the GLR) is incorrect.

**Comment by Kaiepi** [comment]
It looks like only `==>>` and `<<==` are supposed to append:
> To append multiple sources to the next sink, double the angle:

**Comment by ugexe** [comment]
That can be interpreted as “if you want to append multiple sources INSTEAD of appending a single source”

**Comment by lizmat** [comment]
Perhaps this is a problem-solving issue after all  :-)

**Comment by AlexDaniel** [comment]
> Perhaps this is a problem-solving issue after all :-)

I think I agree, and if we can get a few more tickets for feed operators, maybe we'll be able to fix a bunch of things in the spec at once.

**Comment by lizmat** [comment]
Moved to https://github.com/perl6/problem-solving/issues/27 , so closing issue here.
