### ISSUE TITLE
LTA error message

### ISSUE THREAD

**Issue by alanrocker** [rakudo/rakudo#2900]
## The Problem

The error message: "Too many positionals passed; expected 1 argument but got 2
  in sub build_index" 
gives no clues about the offending arguments,  The code line identified appears to be correct. (I'm not convinced that the error is even being reported correctly.) 

## Steps to Reproduce

$ p6doc build

## Environment
* Operating system: 
Linux localhost 4.14.116-desktop-1.mga6 #1 SMP Sat May 4 08:34:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`perl6 -v`): 
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by alanrocker** [comment]
This was triggered by attempting to print to a file that had not opened because of permissions failures. However, the error message did not contribute much to the solution.

**Comment by thundergnat** [comment]
See #2492

**Comment by coke** [comment]
Can you golf this LTA error?

**Comment by alanrocker** [comment]
> Can you golf this LTA error?
>
Apologies for the delay in replying. It's been 4 years sice I filed this.
Multiple Raku versions have come and gone, and I can't reproduce it, so
it's probably safe to close the ticket.

**Comment by lizmat** [comment]
Thanks for checking.  Closing now.
