### ISSUE TITLE
Making a syntax error in an nqp call panics with an unhelpful message

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2908]
## The Problem
```
bastille% perl6 -e 'use nqp; nqp::getattr($*VM. VM, q[$!config])'
===SORRY!===
Unknown QAST node type NQPMu
```
Note there's a period instead of a comma.

## Expected Behavior
The compiler should panic with an error that makes this easier to debug.

## Actual Behavior
The compiler panics with "Unknown QAST node type NQPMu".

## Steps to Reproduce

See "The Problem"

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.5 GENERIC.MP#8 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03.1-407-g7124a00448 built on MoarVM version 2019.03-111-g24b3ef1ad
implementing Perl 6.d.

**Comment by lizmat** [comment]
Adding error checking to this, feels like adding a lot of overhead.

If you're doing NQP, you're bleeding edge.

Closing as a wont fix
