### ISSUE TITLE
potential regression: sub foo($i) {my $i; say $i}

### ISSUE THREAD

**Issue by ufobat** [rakudo/rakudo#2909]
```
> perl6 -e 'sub foo($i) { my $i; say $i}; foo(1)'
===SORRY!===
Cannot find method 'default' on object of type NQPMu

```
* Expected Behaviour

```
# something like:
Potential difficulties:
    Redeclaration of symbol '$i'
```

* Compiler version (`perl6 -v`): 
> perl6 -v
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by Altai-man** [comment]
```
bisectable6: old=2018.12 new=2019.03 sub foo($i) {my $i; say $i}
```
pointed to https://github.com/rakudo/rakudo/commit/42024539877fbebfdfbbc9b006106454cdaf5187
Ping @jnthn.

**Comment by jnthn** [comment]
Fixed and test covered.
