### ISSUE TITLE
Large non-Infinite gists are eager

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#2920]
## The Problem

Large, non-infinte sequences should `gist` lazily, showing the fist 100 elements. Instead, Rakudo seems to be evaluating the entire sequence before it gists. Suspect the sequence is not being detected as lazy.

## Expected Behavior

As per old compiler version

    > $*PERL.compiler
    rakudo (2018.04.1)
    > { (2, 4 ... 1_000_000).gist; say (now - ENTER now).Int }
    0

## Actual Behavior

Recent compiler  version

    > $*PERL.compiler
    rakudo (2019.03.1.427.gb.279670)
    > { (2, 4 ... 1_000_000).gist; say (now - ENTER now).Int }
    15

Bisectable points to [this](https://github.com/rakudo/rakudo/commit/8f424c9d8ecac7c6fbf4f3aa7e0e5fc4b46ea8fe) commit as the regression.

**Comment by lizmat** [comment]
Reverted with 2566db7b9dca3e07d5b9f

**Comment by AlexDaniel** [comment]
What about tests?

**Comment by AlexDaniel** [comment]
How to test:
```
(0, { $_ == 1000 ?? die ‘ouch!’ !! $_ + 1 } ... 99999).gist
```
