### ISSUE TITLE
compilation ends and error message is not helpful

### ISSUE THREAD

**Issue by nkh** [rakudo/rakudo#2921]
## Expected Behavior
an error message with a file name and line
 
## Actual Behavior
compilation is aborted

error message: rakudo-moar a643b8be1: OUTPUT: «===SORRY!===␤This type (QAST::WVal) does not support positional operations␤»

## Steps to Reproduce

bleah:(0)

## Environment
Linux
Rakudo version 2019.03.1-317-gb2e72d6d7 built on MoarVM version 2019.03-110-g081823ffc

**Comment by ugexe** [comment]
```
$ perl6 --ll-exception -e 'bleah:(0)'
This type (QAST::WVal) does not support positional operations
   at gen/moar/Perl6-Actions.nqp:7032  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Actions.moarvm:EXPR)
 from gen/moar/stage2/QRegex.nqp:1662  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/QRegex.moarvm:!reduce_with_match)
 from gen/moar/stage2/NQPHLL.nqp:1163  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:EXPR_reduce)
 from gen/moar/stage2/NQPHLL.nqp:1089  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3651  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Grammar.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:955  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Perl6-Grammar.nqp:883  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1215  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Perl6-Grammar.nqp:1319  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Perl6-Grammar.nqp:825  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Perl6-Grammar.nqp:555  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2300  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2030  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1950  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1983  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1975  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1970  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1666  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1793  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1848  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1773  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:48  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:1  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/Users/nicklogan/.rakudobrew/versions/moar-2019.03.1/install/share/perl6/runtime/perl6.moarvm:<entry>)
```

**Comment by nkh** [comment]
slightly different lines in my version:

This type (QAST::WVal) does not support positional operations
   at gen/moar/Perl6-Actions.nqp:7055  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Actions.moarvm:EXPR)
 from gen/moar/stage2/QRegex.nqp:1664  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/QRegex.moarvm:!reduce_with_match)
 from gen/moar/stage2/NQPHLL.nqp:1211  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:EXPR_reduce)
 from gen/moar/stage2/NQPHLL.nqp:1137  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3675  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Grammar.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:956  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Perl6-Grammar.nqp:884  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1263  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Perl6-Grammar.nqp:1320  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Perl6-Grammar.nqp:826  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Perl6-Grammar.nqp:555  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2302  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2078  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1998  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2031  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2023  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2018  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1714  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1936  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1896  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1821  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:95  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:60  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/nadim/nadim/devel/repositories/rakudo/install/bin/../share/perl6/runtime/perl6.moarvm:<entry>)

**Comment by ugexe** [comment]
If you are not using the exact same version as I was (2019.03.1) then naturally it's not likely to be the same.

**Comment by dogbert17** [comment]
Seems to have changed for the better:

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-84-g240bc9eb1.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.
    dogbert@dogbert-VirtualBox:~$ perl6 -e 'bleah:(0)'
    ===SORRY!=== Error while compiling -e
    You can't adverb :(0)
    at -e:1
