### ISSUE TITLE
Some classes missing ^mro

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#2924]
There is a test in perl6/doc which walks the MRO, and is failing to find even a mro meta method for some types. To see the issue:

```
$ perl6 -e 'dd Perl.^mro'
(Perl, Any, Mu)
$ perl6 -e 'dd Systemic.^mro'
No such method 'mro' for invocant of type 'Perl6::Metamodel::ParametricRoleGroupHOW'
  in block <unit> at -e line 1
$ perl6 -MTest -e 'dd Test.^mro'
No such method 'mro' for invocant of type 'Perl6::Metamodel::ModuleHOW'
  in block <unit> at -e line 1
```

If this is a rakudobug, needs fix, if it's intended behavior, we will fix the doc repo test.

**Comment by lizmat** [comment]
I think this is intended.  MRO is only applicable to classes.

Systemic is a Role.  Until it has been mixed in or punned, it has no MRO.

The same for Test, which is a module.  A module does not do inheritance, so does not have an MRO.

So I think the test should only be done on things that have:

    thing.HOW.^name eq "Perl6::Metamodel::ClassHOW”

?

**Comment by coke** [comment]
(Role only) that's why I included Perl, which I thought was a role, but oops.

Just tried with "Awaitable", same error.

Thanks.

**Comment by coke** [comment]
Ah, in fact, it's because our list of types to graph didn't declare these as non-classes. (we're using a list, not introspection) - fixed.
