### ISSUE TITLE
Silent prompt

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#2936]
## The Problem

There is no way to safely ask for sensitive data (namely passwords) using prompt because user input is printed to STDOUT.

Is it possible to add silent mode to prompt? Like equivalent of `read -s -p "Password: "` in bash?

**Comment by 0racle** [comment]
As the implementation of such a feature is platform specific, it's typically better served as a module, which is what most languages do (including Python, but it just happens to ship that module in the standard library).

A simple way to achieve this on Linux is to shell out to `stty`.

```perl-6
sub getpass($prompt = 'Password: ') {
    run <stty -echo>;
    my $password = prompt($prompt);
    run <stty echo>;
    print "\n";
    return $password;
}

my $password = getpass();
say $password;
```

Though it's probably better to use a module like [Term::termios](https://github.com/krunen/term-termios) to manage your terminal state... but if you're using a module anyways...

There is a [Terminal::Getpass](https://github.com/titsuki/p6-Terminal-Getpass) that exports a `getpass` function, and it works on Windows too.

```perl-6
use Terminal::Getpass;

my $password = getpass();

say $password;
```

**Comment by bbkr** [comment]
Thanks. I didn't know about Terminal::Getpass.

I still believe this is a reasonable request to build such feature into the language to further reduce boilerplate required for such trivial and frequent tasks.

**Comment by ugexe** [comment]
I’m don’t agree that this falls under what most people would consider a frequent task.

**Comment by 0racle** [comment]
Whether or not it's a frequent task may be subjective. A better reason is that Rakudo's core should be as platform agnostic as possible. Platform specific code should only creep in when it's required for essential functionality. All non-essential platform specific functionality is best served in ecosystem.
