### ISSUE TITLE
Sorting two elements with mapper isn't stable

### ISSUE THREAD

**Issue by nwellnhof** [rakudo/rakudo#2937]
I'm seeing

    say sort {1}, ^2  # (1 0)
    say sort {1}, ^$_ for ^6  # ()␤(0)␤(1 0)␤(0 1 2)␤(0 1 2 3)␤(0 1 2 3 4)

Sorting a two-element list isn't stable. Other list sizes seem to work.

**Comment by nwellnhof** [comment]
The code here https://github.com/rakudo/rakudo/blob/e9351cbaa961c4d1e4ef8b4cb52418d55766a8d6/src/core/Rakudo/Sorting.pm6#L277 should probably be changed to

    nqp::islt_i($n,2)
      || nqp::isle_i(
          mapper(nqp::atpos($O,0)) cmp mapper(nqp::atpos($O,1)),0),

**Comment by lizmat** [comment]
Thanks for the report and the fix.  Fixed with ab56324da8 , tests added with d8d4926dae
