### ISSUE TITLE
Sub push doesn't die on named parameters

### ISSUE THREAD

**Issue by rehsack** [rakudo/rakudo#2943]
## The Problem
$ perl6 -e 'my %h; push %h, 'd' => 5; say %h'
{}

## Expected Behavior
{d => 5}
## Actual Behavior
{}

## Environment
* Operating system: Darwin ernie.dynamic.ziggo.nl 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
* Compiler version (`perl6 -v`): This is Rakudo Star version 2018.10 built on MoarVM version 2018.10 implementing Perl 6.c.

**Comment by jnthn** [comment]
Your shell ate the inner quotes, so Perl 6 never saw them.

```
$ perl6 -e 'my %h; push %h, "d" => 5; say %h'
{d => 5}
```

**Comment by rehsack** [comment]
The example was badly copied.

`perl6 -e 'my %h; push %h, d => 5; say %h'`

should do or throw an error. It does neither.

**Comment by lizmat** [comment]
@jnthn: aren't we supposed to throw an error on unexpected named parameters on subs?

**Comment by lizmat** [comment]
Aka, shouldn't `my %h; push %h, d => 5; dd %h` throw, instead of silently eating the named parameter?  We expect that of methods, but not generally of subroutines, right?

**Comment by ugexe** [comment]
It appears slurpies will accept “b” => ... but not b => ...

**Comment by lizmat** [comment]
the code:

    multi sub push(\a, |elems) { a.push: |elems }

so the name parameters are slurped into the capture, and then ignored when flattened into the method call.

**Comment by lizmat** [comment]
Fixed with b20ccbae44 , tests added with https://github.com/perl6/roast/commit/dd9a661f02
