### ISSUE TITLE
Possible slowdown in is-prime

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#2945]
On my system, at HEAD, `(^10_000).grep(*.is-prime).tail.say; say now - INIT now` reports ~2.2s, but 2018.12 reports ~1.3s.

**Comment by lizmat** [comment]
$ perl6 --profile -e '(^10_000).grep(*.is-prime).tail.say'

produces a profile for me that spends ~ 99% of the time in `is-prime`.  And I don't think that has been changed at all since then.  Could you reproduce this performance difference with something other than `is-prime` ?

**Comment by MasterDuke17** [comment]
I haven’t had time to try and reproduce with something different, but I I thought maybe some of the bigint optimizations @jnthn recently landed in MoarVM might have caused this.

**Comment by AlexDaniel** [comment]
So there's this (GCC-related): https://github.com/rakudo/rakudo/issues/2945

And then this:
```
¦7d7aaf0c1d2^: «29989␤5.1725937␤»
¦7d7aaf0     : «29989␤6.4280064␤»
```
https://github.com/rakudo/rakudo/commit/7d7aaf0c1d2626570384f354d4904486bcdc7790 and this commit specifically: https://github.com/MoarVM/MoarVM/commit/304f568f19d22ce6f74be163003c3a6cffa1be9d
Haven't checked if it's a compiler difference again, but I guess it's not.

**Comment by AlexDaniel** [comment]
Then there's also this:
```
¦787596d00^: «29989␤5.76303753␤»
¦4459364:    «29989␤8.2163708␤»
````
And the commits in between are:
* c1c108fdbbaee1fa76856828037f01a493ae36cd
* db5becfb1a1d343d9a615131f246452fed62e567
* 44e0386afd55a8d9afe273e6a872a4e80936eb37
* 5bc6269997cd18261b08368fc7a0819a2062b265
* 787596d0053583a44335ffa63e4eff9f23d93405
* bafa52392ab20de686d7daa3ebf6667b8cf69539
* 4459364eeff0c3089548ab5833f30ff37fb60a26

Not sure what that is about, could it be that some compiler flags are not being passed correctly? Ping @patzim
