### ISSUE TITLE
sink start { say 1 / 0 }  exits the REPL

### ISSUE THREAD

**Issue by kjkuan** [rakudo/rakudo#2947]
## The Problem
The code:
```
my $p = start { say 1 / 0 };
sink $p;
say 'done';
```
Immediately exists the REPL at the second line (`sink $p`) with an error message:
```
> my $p = start { say 1 / 0 }
Promise.new(scheduler => ThreadPoolScheduler.new(initial_threads => 0, max_threads => 64, uncaught_handler => Callable), status => PromiseStatus::Broken)
> sink $p
Nil
> Unhandled exception in code scheduled on thread 4
Attempt to divide by zero when coerc
```
However, the same snippet when run as a script with `perl6` prints `done` without any error messages nor exceptions.

## Expected Behavior
I don't know what the expect behavior should be, but I think at least it shouldn't exit the REPL.

## Environment
* Operating system: Ubuntu 18.04.2
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by lizmat** [comment]
Looks like this is caused by the `Exception` object inside the `Promise` being thrown after all.  Looks like we need to have some extra checking starting at line 359 in REPL.pm6

**Comment by jnthn** [comment]
> However, the same snippet when run as a script with perl6 prints done without any error messages nor exceptions.

Only because it hits the end of the mainline and exits before the exception can happen and be printed. Precede the the `say "done"` with a `sleep 1` and you'll see exactly the same thing.

As for the REPL: it can install an `uncaught_handler` on the scheduler if it wishes to catch such fatal exceptions.

**Comment by jnthn** [comment]
These days one needed something more like `start die "foo"; 42` to be entered into the REPL to trigger this. I've now registered the uncaught handler I mentioned, and it survives.

**Comment by melezhik** [comment]
I've implemented test in r3:

```
[root@fd31ecb74909 r3tool]# SP6_FORMAT_TERSE=1 tomty   --env=2021_05 2947
load configuration from /root/projects/r3tool/.tomty/env/config.2021_05.pl6
index updated from file:///root/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/2947]
==================================================
cat $root_dir/task.bash

$RAKUBIN -v

echo "repl >>>"

cat  << 'HERE' | $RAKUBIN --repl-mode=interactive
my $p = start { say 1 / 0 };
sink $p;
say 'done';
HERE

echo "<<<"

echo "as_script >>>"

cat  << 'HERE' | $RAKUBIN --repl-mode=non-interactive
my $p = start { say 1 / 0 };
sink $p;
say 'done';
HERE

echo "<<<"
Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.
repl >>>
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.05.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.05.

You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
> Promise.new(scheduler => ThreadPoolScheduler.new(initial_threads => 0, max_threads => 64, uncaught_handler => -> $exception { #`(Block|94421260419520) ... }), status => PromiseStatus::Planned)
> Nil
stderr: Uncaught exception on thread 4:
    Attempt to divide by zero when coercing Rational to Str
      in block  at <unknown file> l
stderr: ine 1

> done
> <<<
as_script >>>
done
<<<
[task check] if we run as REPL, we should see 'done' in stdout
[task check] stdout match (r) <^^ done $$> False
[task check] if we run as script, we should see 'done' in stdout
[task check] stdout match (r) <^^ done $$> True
=================
TASK CHECK FAIL
```

**Comment by melezhik** [comment]
interesting, looks  like the test flaps ...  every other test succeeds, every other test fails ... hmm

**Comment by melezhik** [comment]
confirming it passes r3 tests on the latest Rakudo - https://sparky.sparrowhub.io/report/gh-melezhik-r3tool/22699

**Comment by melezhik** [comment]
Btw how to test this ?

**Comment by lizmat** [comment]
Something like:
```raku
my $proc = run $*EXECUTABLE, '--repl-mode=interactive', :in, :out, :err;
my $in = $proc.in;
$in.say: 'start die "foo"; 42';
$in.close;
say $proc.out.slurp;  # check output
```
