### ISSUE TITLE
NQP requiring JDK 1.9 forces you to use Oracle's JDK on OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2954]
## The Problem
OpenJDK on OpenBSD -current is still on v1.8, so it's impossible to install the JVM backend without using Oracle's version of the JDK. This is a problem for me because other programs I have on my system only work with the OpenJDK.

## Expected Behavior
A bleeding-edge OS release would have more up-to-date packages. Jokes aside, the JVM should run on both JDKs, if available, on all systems.

## Actual Behavior
The build fails because JDK v1.9 is needed.

## Steps to Reproduce

Run an OpenBSD -current VM, run `pkg_add jdk`, select OpenJDK when it prompts for which version to run, run `pkg_add libtommath`, and try to rakudo with `./Configure.pl --gen-moar --gen-nqp --moar-option=--has-libtommath`

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.5 GENERIC.MP#36 amd64
* Compiler version (`perl6 -v`): 
Can't build the JVM at the moment, but the rakudo version's 2019.03.1-573-g1cd24a2b4c and nqp-j's version is 2019.03-218-g8c8d0a820

**Comment by ugexe** [comment]
It cannot run on both JDKs are there are v1.9+ features used to implement nqp ops.

**Comment by ugexe** [comment]
https://github.com/perl6/nqp/pull/442 Here is the thread where it was determined upgrading to java9 was the correct move. Being stuck on java 8 would be more alienating than the current situation.

**Comment by Kaiepi** [comment]
Ah, ok. Should this be closed?

**Comment by usev6** [comment]
Yeah, I think we don't need to keep this one open. I hope it won't take too long until there is a current OpenJDK (11?) for OpenBSD.
