### ISSUE TITLE
libuv doesn't respect cores disabled by Meltdown/Spectre patches on OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2957]
This isn't so much an issue with MoarVM as it is libuv. [Here's the pullreq fixing this](https://github.com/libuv/libuv/pull/2326). I'm just leaving this here in case the pullreq gets declined and we need to come up with another way to get the correct CPU count.

**Comment by dogbert17** [comment]
Shouldn't this be resolved now that we're using libuv 1.33?

**Comment by Kaiepi** [comment]
Yes, since my fix for this was included in v1.31.0. `$*KERNEL.cpu-cores` now reports the correct number of CPU cores available on my machine:

```perl6
bastille% perl6 -e 'say $*KERNEL.cpu-cores'
4
```
