### ISSUE TITLE
Characters classes interfere with :ignoremark

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2961]
## The Problem

Character classes in a regex appear to interfere with `:ignoremark` flag

## Expected Behavior

    $ perl6 -e 'say "a\x[300]" ~~ / :ignoremark <[ a b c ]> / '
    ｢à｣

## Actual Behavior

    $ perl6 -e 'say "a\x[300]" ~~ / :ignoremark <[ a b..c ]> / '
    Nil

Perhaps I'm misunderstanding how `:ignoremark` is supposed to work.  Documentation currently says:

> The :ignoremark or :m adverb instructs the regex engine to only compare base characters, and ignore additional marks such as combining accents:

**Comment by tbrowder** [comment]
It seems to me the current behavior makes sense: the match results shows the actual characters giving the desired characteristics; in words I think the search can be "show all 'a' regardless of accents." I used your example and added a bare 'a' and '*' just to see results:

    say "a\x[300]a" ~~ / :ignoremark <[a b c]>* /;  # output [aa]

**Comment by bluebear94** [comment]
This bug isn’t present in Rakudo v2024.06; I think we can close this.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/d2f6b9b346
