### ISSUE TITLE
[windows] Running`perl6` inside rakudo directory can't find CORE modules

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#2969]
## The Problem

When running `perl6` from inside the rakudo directory none of the default repos are finding their modules.

## Steps to Reproduce

```
C:\Users\ugexe\.rakudobrew\moar-blead-master>perl6 t\04-nativecall\04-pointers.t
===SORRY!===
Could not find NativeCall at line 5 in:
    file#C:\Users\ugexe\.rakudobrew\moar-blead-master\t\04-nativecall
    inst#C:\Users\ugexe\.perl6
    inst#C:\Users\ugexe\.rakudobrew\share\perl6\site
    inst#C:\Users\ugexe\.rakudobrew\share\perl6\vendor
    inst#C:\Users\ugexe\.rakudobrew\share\perl6
    ap#
    nqp#
    perl5#
```
```
C:\Users\ugexe\.rakudobrew\moar-2019.03.1>perl6 t\04-nativecall\04-pointers.t
1..22
04-pointers.c
   Creating library 04-pointers.lib and object 04-pointers.exp
Generating code
Finished generating code
ok 1 - Got passed back the pointer I returned
ok 2 - Non-NULL pointer is trueish
ok 3 - Calling .Int on non-NULL pointer is trueish

...
```

## Environment
* Operating system: windows
* Compiler version (`perl6 -v`): `This is Rakudo version 2019.03.1-583-g847a2f0d2 built on MoarVM version 2019.05-49-gfbb1ddd8e
implementing Perl 6.d.`

**Comment by ugexe** [comment]
ping: @patzim @vrurg (not sure if relocatable work or build refactor was the cause)

**Comment by vrurg** [comment]
Looks like a problem with relocability.

**Comment by patzim** [comment]
I think I see what's going on. The perl6 executable in the build directory currently is not linked to the install directory (except for the NQP lib path). It also does not look in the install directory for any modules. The repo paths that you see in the output is the relocatable default of `../share/perl6/{,site,vendor}`. There is obviously nothing there.
It's easy to fix this by adding `NQP_HOME=...` and `PERL6_HOME=...` to the runner scripts. They then work, but only once rakudo is installed. It does not work before `make install`.

@ugexe I think you might be the right one to ask. Is this what we want to do? Is it ok for this to not work prior to installation?

**Comment by ugexe** [comment]
Your solution sounds correct. `perl6 -MTest -e ''` shouldn't work until `make install` has been run once (installing the modules, possibly updating meta data formats, etc). For pre-install (or to not use the installed versions for whatever reason) one can do `perl6 -Ilib -MTest -e ''`.

**Comment by niner** [comment]
All that's required is that `make test` works before `make install`

**Comment by patzim** [comment]
I think `make test` before `make install` will not work with the proposed solution. I could either:
1. Additionally statically add `-Ilib` to the build runner scripts.
2. Change `make test` to pass `-Ilib` to the build runner.

If noone objects I'll go for 2. (I'll probably have time for this in the evening.)

**Comment by patzim** [comment]
Just started looking into this and noticed that `make test` already uses `-Ilib` so all should be fine. I'll test my changes and create a PR soonish.

**Comment by patzim** [comment]
@ugexe PR #2978 did not solve the AppVeyor build errors. I quickly looked at the build log and it seems the 04-nativecall.t failures that keep popping are not the result of missing libs.

**Comment by ugexe** [comment]
No they aren’t. But while tracking that problem locally I encountered this issue.
