### ISSUE TITLE
Wrong detection of declaration to initialize itself

### ISSUE THREAD

**Issue by HarmtH** [rakudo/rakudo#2974]
Rakudo ver: c9a78928febafe8b174cddaa4f52338cd854816d

The compiler wrongfully detects self-initialization, when doing run-time resolution.
```
sub foobar() { say "foobar" }

my $x = "bar";
my &foo = ::("&foo$x");
foo();
```

```
===SORRY!=== Error while compiling ***/test.p6
Cannot use variable &foo in declaration to initialize itself
```

Different namespace, same problem
```
module foo {
    our sub bar() { say "foo::bar" }
}

my &bar = ::foo::("&bar");
bar();
```

```
===SORRY!=== Error while compiling ***/test.p6
Cannot use variable &bar in declaration to initialize itself
```

Workarounds:
```
my &foo = ::("\&foo$x");
my &foo = ::("&"~"foo$x");
my &bar = ::foo::<&bar>;
```

**Comment by AlexDaniel** [comment]
Possibly related: https://github.com/rakudo/rakudo/pull/1020

**Comment by ugexe** [comment]
I don't see a bug -- the code should be `my &foo = ::('&foo' ~ $x);` or `my &foo = &::("foo$x")`

**Comment by HarmtH** [comment]
Thank you for giving more workarounds :-) Here's another one: ```my &foo = ::(Q:s[&foo$x]);``` (the ```:f``` modifier of ```Q``` triggers the bug)

According to [this](https://docs.perl6.org/language/quoting),  ```&``` is only interpolated inside ```""``` when followed by the symbol name and parentheses. And if it's not interpolated, ```'&foo'``` and ```"&foo"``` should give the same result, right? 

Besides, the commit introducing this bug is https://github.com/rakudo/rakudo/commit/3754356d8e4401c2e567f20462adb2ecd97dc7d5 which fixed [this](https://rt.perl.org/Public/Bug/Display.html?id=125371). So the current behaviour is just a side-effect of that fixing that bug.

**Comment by ugexe** [comment]
> According to this, & is only interpolated inside "" when followed by the symbol name and parentheses. And if it's not interpolated, '&foo' and "&foo" should give the same result, right?

Ah I overlooked this.

**Comment by HarmtH** [comment]
```
my @foo = "@foo";
```
```
===SORRY!=== Error while compiling ***/test.p6
Cannot use variable @foo in declaration to initialize itself
```
Also triggers the bug (```@``` should only be interpolated when followed by the symbol and ```[]```)
Same for ```"%foo"``` (should only be interpolated when followed by the symbol and ```<>```)

**Comment by HarmtH** [comment]
But this isn't detected:
```
my @foo := "{@foo}";
```
```
Cannot call method 'Stringy' on a null object
```

**Comment by HarmtH** [comment]
I've reverted https://github.com/rakudo/rakudo/commit/3754356d8e4401c2e567f20462adb2ecd97dc7d5 on the current master. The original bug report which was fixed by that commit seems to be fixed by other means as well:
```
> my $a := $a; say $a; '---'.say; $a.say # no jackpot anymore! :-(
(Mu)
---
Cannot call method 'say' on a null object
  in block <unit> at <unknown file> line 1
```

**Comment by AlexDaniel** [comment]
Yes, yes. See https://github.com/rakudo/rakudo/pull/1020/. Mentioned commits should indeed be reverted, but it's a bit more complicated because there are 6.c tests and stuff. It's explained in my PR. If you need any help with this, please ping me, but we need a bit more than just a rakudo PR.

**Comment by lizmat** [comment]
Added test with https://github.com/Raku/roast/commit/002bbf8272
