### ISSUE TITLE
Seq.elems using a PredictiveIterator doesn't cache

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2976]
## The Problem

    $ perl6 -e 'given Seq.new((1,2,3).iterator) { dd .elems; dd .all; dd .all }'
    3
    all(1, 2, 3)
    The iterator of this Seq is already in use/consumed by another Seq
    (you might solve this by adding .cache on usages of the Seq, or
    by assigning the Seq into an array)

## Expected Behavior
    $ perl6 -e 'given Seq.new((1,2,3).iterator) { dd .elems; dd .all; dd .all }'
    3
    all(1, 2, 3)
    all(1, 2, 3)

Bisected to https://github.com/rakudo/rakudo/commit/9107215a99f106835a121d8446d97d11fc017758

**Comment by lizmat** [comment]
I guess this could also be considered a documentation issue regarding `.elems`.  I don't think that it is documented anywhere that `Seq.elems` should cache the `Seq`.  But there is a **lot** of code out there that assumes that it does.  So perhaps we will need to revert https://github.com/rakudo/rakudo/commit/9107215a99f106835a121d8446d97d11fc017758 even though it provides some nice performance benefits.

**Comment by lizmat** [comment]
Fixed with the introduction of the `CachedIterator` role in https://github.com/rakudo/rakudo/commit/94ba19f7e5 .

**Comment by Altai-man** [comment]
Documented at https://github.com/perl6/doc/pull/3067
Tests proposed at https://github.com/perl6/roast/pull/590
