### ISSUE TITLE
Rakudo binary failing with an error

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#2977]
## The Problem

We download HEAD for testing docs, but lately it's been failing with this error:

perl6: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by //tmp/whateverable/rakudo-moar/bed0695df251587f565bf6278a6ff01503341f74/lib/libmoar.so)

Check it out [here](https://travis-ci.org/perl6/doc/jobs/543817824), for instance. [This is the first instance](https://travis-ci.org/perl6/doc/jobs/537855714) where I found it in the logs.

**Comment by AlexDaniel** [comment]
Maybe `libc6-dev` simply needs to be installed on the system? Maybe also see other debian dependencies to see what else should be installed: https://packages.debian.org/sid/rakudo

**Comment by JJ** [comment]
Apparently this is due to the fact that moarvm is being compiled with a version of Glibc that is more modern than what's available in the default repositories, is that correct?
(Also, maybe I should move this issue to MoarVM)

**Comment by JJ** [comment]
Closed and superseded [by this issue in MoarVM](https://github.com/MoarVM/MoarVM/issues/1121)
