### ISSUE TITLE
Define "-i" to be "+0-i" not the IEEE "-0-i" variant

### ISSUE THREAD

**Issue by fecundf** [rakudo/rakudo#2986]
## The Problem
From perl6-users, IEE defines both +0 and -0. And we end up with
> (-i).reals
    (-0 -1)

For the case of the constant -i == 0-i is less surprising than a Complex involving the IEEE negative zero, but currently -i == -0-i

On the list Brad Gilbert mentioned adding
    constant term:<-i> = Complex.new(0,-1);

which sounds good to me...

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/f74eff7a6a
