### ISSUE TITLE
Slowdown with newer GCC versions

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2988]
Found it when trying to bisect this issue: https://github.com/rakudo/rakudo/issues/2945

This is the code that I used for the benchmark:
```
(^50_000).grep(*.is-prime).tail.say; say (now - INIT now)
```

Using bisectable I found this:
```
¦1cb266b^^^: «49999␤7.3227272␤»
¦1cb266b   : «49999␤9.4255653␤»
```

So the slowdown was caused by one of these commits:
* [1cb266b8da^^](https://github.com/rakudo/rakudo/commit/1cb266b8da^^)
* [1cb266b8da^](https://github.com/rakudo/rakudo/commit/1cb266b8da^)
* [1cb266b8da](https://github.com/rakudo/rakudo/commit/1cb266b8da)

Which obviously makes no sense at all. So I tested it again and again and again, trying to make sure that it is not some kind of noise. It's not.

On [irc](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-06-14#l520) @timo jokingly suggested that the compiler itself can be an issue (these rakudo+moar builds were produced long time ago, and it's possible that it was done with different compilers). So I checked with objdump:

```
objdump --full-contents --section=.comment moar
```

And indeed:
```
GCC: (Debian 4.9.2-10) 4.9.2
GCC: (Debian 6.3.0-18) 6.3.0 20170516
```
That is, rakudo+moar built with newer gcc has worse performance. And not just a little bit worse, it's around 0.78x as fast. Weird, huh?

> \<timotimo\> we should first check to see if the time difference lives inside libtommath or moarvm
> \<timotimo\> probably not in the jit, since that shouldn't be dependent on the compiler
> \<timotimo\> though a difference in compiler could change when jitting happens exactly

Though I'd say that we should simply bisect gcc and see what we get.

**Comment by taboege** [comment]
FWIW, I tested both revisions compiled with the same compiler `gcc (GCC) 8.3.0` and indeed don't notice a difference:

```
# This is Rakudo version 2017.09-102-g9af5607d5 built on MoarVM version 2017.09.1-46-g27d3d01e5
49999
8.0941886
```

```
# This is Rakudo version 2017.09-105-g1cb266b8d built on MoarVM version 2017.09.1-46-g27d3d01e5
49999
8.101132
```

**Comment by AlexDaniel** [comment]
Oh yes, it is worth noting that both compilers in my tests are relatively old. Maybe we should test against gcc 9.
