### ISSUE TITLE
Windows installer checksum 

### ISSUE THREAD

**Issue by foehnwind** [rakudo/rakudo#2989]
Dear developer, 

I wonder whether you can release a checksum file for the Windows installer (https://rakudostar.com/latest/star/win64)?

Thanks,

**Comment by hankache** [comment]
Hi @foehnwind 
https://rakudostar.com/files/star/rakudo-star-2019.03-x86_64%20%28JIT%29.msi.sha256.txt

**Comment by foehnwind** [comment]
@got it, thanks.
