### ISSUE TITLE
Windows regression in t/04-nativecall/4-pointers.t

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#2992]
## The Problem

https://ci.appveyor.com/project/rakudo/rakudo/branch/master/job/i08dmlpmmu75ms0c?fullLog=true#L2777

```
t\04-nativecall\04-pointers.t ................................... 
1..22
04-pointers.c
   Creating library 04-pointers.lib and object 04-pointers.exp
Generating code
Finished generating code
ok 1 - Got passed back the pointer I returned
ok 2 - Non-NULL pointer is trueish
ok 3 - Calling .Int on non-NULL pointer is trueish
ok 4 - Calling prefix:<+> on non-NULL pointer is trueish
ok 5 - Pointer roundtrips okay using .perl and EVAL
ok 6 - Numerical value of Pointer.new is 0
ok 7 - Pointer.new(0) has 0 numerical value
ok 8 - Pointer.new(1234) has numerical value 1234
ok 9 - Pointer.new accepts a native int too
ok 10 - A returned NULL pointer is the Pointer type object itself
ok 11 - typed pointer deref method
ok 12 - typed pointer array dereference
ok 13 - typed pointer increment
not ok 14 - .add(-1)
# Failed test '.add(-1)'
# at t\04-nativecall\04-pointers.t line 36
# expected: '10'
#      got: '30'
ok 15 - typed pointer incremented (1)
ok 16 - typed pointer incremented (2)
not ok 17 - typed pointer decrement
# Failed test 'typed pointer decrement'
# at t\04-nativecall\04-pointers.t line 39
# expected: '10'
#      got: '30'
not ok 18 - typed pointer incremented (1)
# Failed test 'typed pointer incremented (1)'
# at t\04-nativecall\04-pointers.t line 40
# expected: '10'
#      got: '30'
not ok 19 - typed pointer incremented (2)
# Failed test 'typed pointer incremented (2)'
# at t\04-nativecall\04-pointers.t line 41
# expected: '20'
#      got: '0'
not ok 20 - .add(2)
# Failed test '.add(2)'
# at t\04-nativecall\04-pointers.t line 42
# expected: '30'
#      got: '1'
ok 21 - Signature matching with Pointer[int32] works (RT  \#124321)
ok 22 - Signature matching with CArray[Int] works
# Looks like you failed 5 tests of 22
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/22 subtests 
```

## Environment
* Operating system: windows

**Comment by AlexDaniel** [comment]
It seems like it passes now? Although this just happened:
```
Test Summary Report
-------------------
t\04-nativecall\06-struct.t                                   (Wstat: 29696 Tests: 29 Failed: 0)
  Non-zero exit status: 116
  Parse errors: Bad plan.  You planned 34 tests but ran 29.
t\09-moar\General_Category__extracted-DerivedGeneralCategory.t (Wstat: 0 Tests: 1 Failed: 0)
  TODO passed:   1
t\09-moar\Line_Break__LineBreak.t                             (Wstat: 0 Tests: 2 Failed: 0)
  TODO passed:   2
Files=98, Tests=1754, 192 wallclock secs ( 0.59 usr +  0.20 sys =  0.80 CPU)
Result: FAIL
```

**Comment by ugexe** [comment]
That is probably a flapper given that rakudo built against MoarVM HEAD passed.

**Comment by AlexDaniel** [comment]
It is, yeah, though somehow we don't seem to be keeping track of flappers… so I'm wondering if it's new or not. Anyway, I think we can close this for now, we'll see if something wrong happens in appveyor again.

**Comment by vrurg** [comment]
Does [this](https://ci.appveyor.com/project/rakudo/rakudo/builds/25447697/job/xvraux6sl89kk8mr#L4831) counts as something wrong? It is also a possible flapper: 1 of 3 runs is ok.

**Comment by AlexDaniel** [comment]
@vrurg seems to be the same as above. It's not great. Maybe one way to figure it out is to try running that test file a loop on linux, maybe it'll also fail there.

**Comment by vrurg** [comment]
40 runs on macOS, 40 runs on a Linux VM – no single failure. Odds are against a Win-specific cause.

**Comment by AlexDaniel** [comment]
In my experience 40 runs is not enough. If you can, leave it running for much longer. Also, many issues only appear when the system is under load. Sometimes a thing that doesn't trip on your excellent system can fail almost every time on travis/appveyor.

**Comment by vrurg** [comment]
So far the results are:

`Configure.pl --backends=moar --gen-moar=master --gen-nqp=master` on both Windows and Linux. Test script:

```
use v5.20;
for my $i (1..10000) {
    system( q<./perl6-m t/04-nativecall/06-struct.t> );
    my $rc = $? >> 8;
    if ($rc == 0) {
        say "Done $i";
    }
    else {
        die "Failed on $i, rc=" . $rc;
    }
}
```

Windows dies within 5 iterations with rc 255. No visible signs of what's happened. 

Linux testing was stopped after approx. 1700 repetitions because I wanted some more resources for other tasks.

I conclude that if nothing was overlooked then Windows build is clearly has an issue which doesn't affect Linux.

**Comment by ugexe** [comment]
It might be interesting to see if disabling the JIT fixes it.

**Comment by vrurg** [comment]
If setting `MVM_JIT_DISABLE` in the env is sufficient without recompilation then the answer is: no, it doesn't fix things.
