### ISSUE TITLE
On use/require: Cannot invoke this object (REPR: Null; VMNull)

### ISSUE THREAD

**Issue by ajs** [rakudo/rakudo#2995]
## The Problem

In this branch:

https://github.com/ajs/perl6-Math-Sequences/tree/ajs/more-numberphile 

In the HEAD revision, running:

    perl -I lib t/numberphile.t

Gives:

```
$ perl6 -I lib t/numberphile.t
1..11
ok 1 - topologically-ordered-numbers
ok 2 - base 16 topologically-ordered-numbers
Cannot invoke this object (REPR: Null; VMNull)
  in block  at /home/ajs/src/perl6-Math-Sequences/lib/Math/Sequences/Integer.pm (Math::Sequences::Integer) line 79
  in method pull-one at /home/ajs/src/perl6-Math-Sequences/lib/Math/Sequences/Integer.pm (Math::Sequences::Integer) line 70
  in block <unit> at t/numberphile.t line 40
```

But if you remove the `require Math::Sequences::Integer;` from `numberphile.t` this error does not occur (and the symbol is not found).

The previous revision on that branch works fine, and as far as I can tell, I have done nothing in that revision that could have caused this error directly. I believe that I am stumbling on a bug in rakudo, though maybe I'm also using symbolic name lookup incorrectly? The docs aren't super clear.

## Expected Behavior

Read compunit and resolve symbol.

## Actual Behavior

Error above.

## Environment

* Under Windows 10 WSL Ubuntu
* This is Rakudo Star version 2018.10 built on MoarVM version 2018.10
implementing Perl 6.c.

**Comment by ugexe** [comment]
Unrelated, but lib contains more than two files yet the META6.json provides section only lists two (making this not installable).

**Comment by ajs** [comment]
Yep @ugexe thanks! Lots of new stuff is being added and I need to go back and re-do the module metadata at some point!

**Comment by ajs** [comment]
I'm now running into this non-deterministically on this commit:

https://github.com/ajs/perl6-Math-Sequences/tree/dae34acd3edda35508655d1f65c20e92f904fbcf

When I run: `perl6 -I lib t/numberphile.t` about 50% of the time!

**Comment by AlexDaniel** [comment]
I'd like to see this figured out before the release.

**Comment by lizmat** [comment]
It's more like 90% fail for me, versus 10% success.  The success rate appears to be a *lot* higher if the module was *not* precompiled yet.

**Comment by lizmat** [comment]
This change to the module appears to fix the problem.

    $ git diff
    diff --git a/lib/Math/Sequences/Numberphile.pm b/lib/Math/Sequences/Numberphile.pm
    index bc7fc1c..6af2570 100644
    --- a/lib/Math/Sequences/Numberphile.pm
    +++ b/lib/Math/Sequences/Numberphile.pm
    @@ -177,13 +177,13 @@ our @A232448 is export = lazy 𝕀.grep: -> $n { "1{0 x $n}666{0 x $n}1".is-prim
     
     # A125524 - Republican primes: primes such that the right half of the prime
     # is prime and the left half is not.
    -our @A125524 is export = lazy @A000040.grep: -> $p {
    +our @A125524 is export = lazy (1..*).grep(*.is-prime).grep: -> $p {
            !$p.substr(0,$p.chars div 2).is-prime and $p.substr(* - ($p.chars div 2)).is-prime
     }
     
     # A125523 - Democratic primes: primes such that the left half of the prime
     # is prime and the right half is not.
    -our @A125523 is export = lazy @A000040.grep: -> $p {
    +our @A125523 is export = lazy (1..*).grep(*.is-prime).grep: -> $p {
            $p.substr(0,$p.chars div 2).is-prime and !$p.substr(* - ($p.chars div 2)).is-prime
     }

Investigating further

**Comment by lizmat** [comment]
Giving up on this now.  It looks like it is some interaction of multiple level exports / constants / iterators from several files.

Since this module is going to be the target of the next Squashathon, I suggest fixing the module with the above fix for now.  Looking at the code of this module, there seems to be a lot of things that can be done better / more efficient.

**Comment by lizmat** [comment]
Recommend removing the blocker label but not closing this ticket.

**Comment by AlexDaniel** [comment]
OK

**Comment by ajs** [comment]
In this version: https://github.com/ajs/perl6-Math-Sequences/commit/3978e14e23f4d21842f3f74f99f4d23fa33c75eb The bug comes up about 50% of the time when running `perl6 -I lib t/numberphile.t` which I just confirmed on moar-master pulled about 20 minutes ago, locally.

**Comment by ajs** [comment]
@liznat I'll take your proposed changes and apply. However, this module can be disabled for the squashaton. Integer.pm is the one that's needed for that.

**Comment by AlexDaniel** [comment]
@ajs is there a golf of that issue? A multi file gist is OK too. I just want to throw that into a bot to see if this issue existed before.

**Comment by lizmat** [comment]
FWIW, I haven't been able to golf it  :-(

**Comment by ajs** [comment]
@AlexDaniel I would love it if there were. I have not seen this happen in smaller examples.

**Comment by AlexDaniel** [comment]
@ajs doesn't have to be much smaller, just in a multifile gist.

**Comment by vrurg** [comment]
Tested on the latest `HEAD` and on 2019.07.1. The former passes, the latter fails.

Closing via MoarVM/MoarVM#1209 and 7e3d023b4b070ed798915336a98f2bbc7fbac2e7
