### ISSUE TITLE
Some ecosystem fallout after “Make List.reverse a bit less Seqqy” commit

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2999]
Part of https://github.com/rakudo/rakudo/issues/2998.

Tests in some modules are unhappy after 2683b3d0987a93a8e8dccca96bd4097ec221a49f. Ping @lizmat :)

- [I18N::LangTags](https://modules.perl6.org/dist/I18N::LangTags) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f
- [Net::OSC](https://modules.perl6.org/dist/Net::OSC) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f
- [Numeric::Pack](https://modules.perl6.org/dist/Numeric::Pack) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f
- [Ranker](https://modules.perl6.org/dist/Ranker) – Fail, Bisected: 2683b3d0987a93a8e8dccca96bd4097ec221a49f

Errors look like this:

```
Type check failed for return value; expected Seq but got List ($(1, 0, 0, 0))
```

**Comment by lizmat** [comment]
Fixed with 8ddc2ad503
