### ISSUE TITLE
Parrot age

### ISSUE THREAD

**Issue by cup** [rakudo/rakudo#3003]
I was looking at an issue on the Parrot repo, and I noticed that its not been
updated in 2 years:

https://github.com/parrot/parrot/commit/53284177b4f4107da5b7e2394cefccaa98194ec3

as Rakudo relies on Parrot this is troubling. Is something being done to resolve
this?

**Comment by AlexDaniel** [comment]
Just to clarify for anyone who stumbles upon this: support for Parrot was dropped a long time ago. We are now using [MoarVM](https://github.com/MoarVM/MoarVM), although you can also use rakudo on JVM if you really need to. JS backend is also in progress.
