### ISSUE TITLE
Intermittent failure in 06-struct.t on Windows

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3009]
`Configure.pl --backends=moar --gen-moar=master --gen-nqp=master` on both Windows and Linux. Test script:

```
use v5.20;
for my $i (1..10000) {
    system( q<./perl6-m t/04-nativecall/06-struct.t> );
    my $rc = $? >> 8;
    if ($rc == 0) {
        say "Done $i";
    }
    else {
        die "Failed on $i, rc=" . $rc;
    }
}
```

Windows dies within 5 iterations with rc 255. No visible signs of what's happened. 

Linux testing was stopped after approx. 1700 repetitions because I wanted some more resources for other tasks.

I conclude that if nothing was overlooked then Windows build is clearly has an issue which doesn't affect Linux.

_Originally posted by @vrurg in https://github.com/rakudo/rakudo/issues/2992#issuecomment-504532471_

**Comment by AlexDaniel** [comment]
I think this is relatively new, it'd be nice if somebody can take a look.

**Comment by lizmat** [comment]
Did this affect any ecosystem modules?  If not, I would remove the BLOCKER label for now.

**Comment by AlexDaniel** [comment]
@lizmat I won't remove the label as I *really* want this to be fixed. But I'm fine with making a release with this ticket still open.

**Comment by Kaiepi** [comment]
I think I have a fix for this ready, I just need to wait for more iterations of the test before I can safely pullreq it.

**Comment by AlexDaniel** [comment]
Nice! It won't make it into this release as it's a moarvm fix, but it'll be in the next one! I think this ticket can be closed for now.
