### ISSUE TITLE
Unwanted caching of Seqs

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3014]
Blin found an issue (thanks to [Test::Deeply::Relaxed](https://modules.perl6.org/dist/Test::Deeply::Relaxed), [tests](https://github.com/ppentchev/perl6-Test-Deeply-Relaxed/blob/bdc0e1316ee14f70ad039fd94133a0b48631733e/t/05-cache.t#L15))

```perl6
my $s = (1, 2, 3).Seq; say $s.iterator.pull-one; say $s[0]
```
Output:
```
1
1
```
Obviously the Seq in question shouldn't be cached‽

Bisected: 7af0fb1c4cc49f7fbcf438e6428ccd8846014269

Ping @lizmat.

**Comment by jnthn** [comment]
That commit is surely wrong; the entire reason for the `.cache` vs `.list` distinction is that `.list` doesn't cache and `.cache` does. `@($foo)` was even made to call `.cache` at some point also.

**Comment by jnthn** [comment]
> at some point 

To be clear, during the GLR, so long, long ago. :-)

**Comment by AlexDaniel** [comment]
I tried reverting https://github.com/rakudo/rakudo/commit/7af0fb1c4cc49f7fbcf438e6428ccd8846014269 but it's not enough. Another commit at fault is 
https://github.com/rakudo/rakudo/commit/94ba19f7e5ece517ca48ac16bf385bee2650b018.

**Comment by lizmat** [comment]
Which was a fix for https://github.com/rakudo/rakudo/commit/9107215a99f106835a121d8446d97d11fc017758

**Comment by jnthn** [comment]
I think revert my attempt to speed up `.split(...).elems` also. I'll probably end up doing a more substantial rewrite of at least the common case of `split`, since we don't actually need to waste time constructing the `Match` objects at all, and can, I think, just take all we need straight from the cursor.

**Comment by lizmat** [comment]
Before reverting 94ba19f I would like to understand what's wrong with that commit.  Because it feels to me it's a nice way of reducing memory churn / CPU usage ?

**Comment by AlexDaniel** [comment]
@lizmat test case:
```perl6
    my $s1 = (1, 2, 3).Seq;
    $s1.iterator.pull-one; # forget the first element
    throws-like { say $s1[0] }, X::Seq::Consumed, 'Seqs are not always cached';
```
> what's wrong with that commit

As I understand, it's wrong unless that test passes.

**Comment by AlexDaniel** [comment]
Ah, just read your comments here: https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-06-22#l14

I don't know then.

**Comment by AlexDaniel** [comment]
OK, what about this:
```perl6
my @a = <foo bar baz>;
my Seq $s = @a.Seq;
say $s.first;
@a[0] = 20;
say $s.first
```
Output (HEAD):
```
foo
20
```
So it's a Seq with a mutable cache. Doesn't feel right, right?

**Comment by lizmat** [comment]
Reverted all 3 commits with 090f3f1b45

**Comment by AlexDaniel** [comment]
Needs tests though!

**Comment by lizmat** [comment]
Test added with https://github.com/perl6/roast/commit/270e09cb14
