### ISSUE TITLE
Some issue in LMDB module

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3015]
[LMDB](https://modules.perl6.org/dist/LMDB) is failing some tests on the latest rakudo.

```
…
…
ok 36 - basic put works
ok 37 - Unicode put works
elems requires a concrete object (got a NativeCall::Types::CArray[uint8] type object instead)
  in method elems at /home/alex/.rakudobrew/versions/moar-master/install/share/perl6/core/sources/8660F65A7B3492675BB3B2058DB30E411A4C4E54 (NativeCall::Types) line 223
  in submethod BUILD at /home/alex/git/p6-LMDB/lib/LMDB.pm6 (LMDB) line 98
  in method get at /home/alex/git/p6-LMDB/lib/LMDB.pm6 (LMDB) line 452
  in block <unit> at t/01-basic.t line 84

# Looks like you planned 77 tests, but ran 37
```

Not sure if it's a problem in rakudo or in the module itself. I don't have a golf yet.

* Bisected: 235f14cd5138663c35f574a694e45b5bc0141031
* NQP version bump brought in these changes: https://github.com/perl6/nqp/compare/2019.03-62-gb46d91b...2019.03-76-gf68c2ba
* Moar version bump brought in these changes: https://github.com/MoarVM/MoarVM/compare/2019.03-76-gc10fee6...2019.03-97-g8fef199

**Comment by dogbert17** [comment]
The regression was introduced with https://github.com/MoarVM/MoarVM/commit/a92be01531b44e4599a23e2ef1eeb514eb1e9bb0

**Comment by dogbert17** [comment]
Here's a golf of what the module is doing when the test is run.

    my class MDB-val is repr('CStruct') {
        has size_t          $.mv_size;
        has CArray[uint8]   $.mv_buff;
    
        submethod BUILD(CArray[uint8] :$mv_buff) {
            $!mv_size = $mv_buff.elems;
            $!mv_buff := $mv_buff;
        }
    
        method Str() {
            self.Blob.decode('utf8');
        }
    }
    
    my $res = MDB-val.new;

**Comment by timo** [comment]
before the commit in moarvm that changed this, it will have read memory belonging to something else, essentially returning random data. CArray will probably in the future behave like Array and others that return 1 for .elems if it's undefined (the "one object behaving like a list containing that one object" behavior). either way, the module most likely needs to be changed.

**Comment by AlexDaniel** [comment]
> \<timotimo\> if that's what the module does, it's just wrong

Removing the blocker label and closing the ticket. Will file a ticket in the module shortly.
