### ISSUE TITLE
Duplication of the first element in a returned sequence.

### ISSUE THREAD

**Issue by ajs** [rakudo/rakudo#3017]
## The Problem

In my code at:

https://github.com/ajs/perl6-Math-Sequences/commit/3978e14e23f4d21842f3f74f99f4d23fa33c75eb

The first element of a sequence is duplicated when you run the tests.

Rather than re-type the whole thing I'm just going to link to my reddit post for the details which contains the command, the workaround, the context, etc.:

https://old.reddit.com/r/perl6/comments/c3quwd/is_this_a_rakudo_bug_in_list_handling/

## Expected Behavior

Calling `.perl` on an array variable should not change its contents.

## Environment
* Operating system: 

Windows 10 WSL Ubuntu

* Compiler version (`perl6 -v`): 

This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

Just built it yesterday.

## Related issue

https://github.com/rakudo/rakudo/issues/2995

That bug crops up about 50% of the time while running tests on this module, but seems (?) to be unrelated to my bug, here.

**Comment by AlexDaniel** [comment]
That sounds pretty horrifying, so I'm adding a blocker label :)

**Comment by lizmat** [comment]
I can't reproduce this on HEAD.  Can you?  I suspect that 090f3f1b45c1af1e355 fixed this also.

**Comment by ajs** [comment]
@liznat that sounds great. Rebuilding to test now...

**Comment by ajs** [comment]
Confirmed working on moar-master. Sounds like this can be closed, but will leave that up to you all.

**Comment by AlexDaniel** [comment]
I guess.
