### ISSUE TITLE
Vague precompilation issue

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3022]
In a code base for $work, the following situation exists:

- project code is located in a "lib" directory
- tests are run with `PERL6LIB="lib" prove -j16 -exec 'perl6' t`

The following sequence of events reliably produces compilation errors in at least one of the 20+ test files:

1. nuke `lib/.precomp`
2. run all the tests (successfully)
3. add an empty line to one of the source files
4. run all the tests (at least one compilation error)

The compilation error is:

    New type Stash for Perl6::Metamodel::ClassHOW is not a mixin type

FWIW, I've seen other types for `Perl6::Metamodel::ClassHOW`, such as `Str` in similar messages.

The error does *not* occur in step 4, if the tests are run with `-j1`, aka no parallelization.  Therefore this bug seems to occur when two conditions are met:

1. there has been a previous compilation.
2. multiple *processes* attempt to re-precompile (potentially the same) modules at the same time.

I hope this description will give someone an idea on where to look to solve this issue and/or to create a more easily reproducible case.

Sample stacktrace:

    ========New type Stash for Perl6::Metamodel::ClassHOW is not a mixin type
       at SETTING::src/core/Exception.pm6:62  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:throw)
     from SETTING::src/core/CompUnit/Loader.pm6:25  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/Loader.pm6:23  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/Loader.pm6:22  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from <unknown>:1  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/Exception.pm6:58  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:throw)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:81  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:79  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:78  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from <unknown>:1  (*WORK*/lib/.precomp/2D77F48693DD398BA79C9CD6F83C57F12C7B6048/2D/2D0BAD864906598D5953344E1DD3DD85E69A9A60:<dependencies+deserialize>)
     from SETTING::src/core/CompUnit/Loader.pm6:50  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:load-precompilation-file)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:71  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:load-handle-for-path)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:195  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:191  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:190  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:load)
     from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:46  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:try-load)
     from SETTING::src/core/CompUnit/Repository/FileSystem.pm6:79  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/Repository/FileSystem.pm6:73  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:need)
     from src/Perl6/World.nqp:1434  (rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:load_module)
     from src/Perl6/World.nqp:1384  (rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:do_pragma_or_load_module)
     from gen/moar/Perl6-Grammar.nqp:1292  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control:sym<use>)
     from gen/moar/stage2/QRegex.nqp:1624  (rakudo.moar/install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control)
     from gen/moar/Perl6-Grammar.nqp:956  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
     from gen/moar/Perl6-Grammar.nqp:884  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
     from gen/moar/stage2/NQPHLL.nqp:1350  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:LANG)
     from gen/moar/Perl6-Grammar.nqp:1320  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
     from gen/moar/Perl6-Grammar.nqp:826  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
     from gen/moar/Perl6-Grammar.nqp:555  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
     from gen/moar/stage2/QRegex.nqp:2210  (rakudo.moar/install/share/nqp/lib/QRegex.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2178  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2098  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:2131  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:2123  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:2118  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from SETTING::src/core/CompUnit/Loader.pm6:16  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:load-source)
     from SETTING::src/core/CompUnit/Repository/FileSystem.pm6:88  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/CompUnit/Repository/FileSystem.pm6:73  (rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:need)
         from src/Perl6/World.nqp:1434  (rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:load_module)
         from src/Perl6/World.nqp:1384  (rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:do_pragma_or_load_module)
         from gen/moar/Perl6-Grammar.nqp:1292  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control:sym<use>)
         from gen/moar/stage2/QRegex.nqp:1643  (rakudo.moar/install/share/nqp/lib/QRegex.moarvm:!protoregex)
         from <unknown>:1  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control)
         from gen/moar/Perl6-Grammar.nqp:956  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
         from gen/moar/Perl6-Grammar.nqp:884  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
         from gen/moar/stage2/NQPHLL.nqp:1350  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:LANG)
         from gen/moar/Perl6-Grammar.nqp:1320  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
         from gen/moar/Perl6-Grammar.nqp:826  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
         from gen/moar/Perl6-Grammar.nqp:555  (rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
         from gen/moar/stage2/QRegex.nqp:2210  (rakudo.moar/install/share/nqp/lib/QRegex.moarvm:parse)
         from gen/moar/stage2/NQPHLL.nqp:2178  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:parse)
         from gen/moar/stage2/NQPHLL.nqp:2098  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
         from gen/moar/stage2/NQPHLL.nqp:2131  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
         from gen/moar/stage2/NQPHLL.nqp:2123  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
         from gen/moar/stage2/NQPHLL.nqp:2118  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
         from gen/moar/stage2/NQPHLL.nqp:1802  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
         from gen/moar/stage2/NQPHLL.nqp:2036  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
         from gen/moar/stage2/NQPHLL.nqp:1996  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
         from src/Perl6/Compiler.nqp:52  (rakudo.moar/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
         from gen/moar/stage2/NQPHLL.nqp:1921  (rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
         from gen/moar/main.nqp:82  (rakudo.moar/install/share/perl6/runtime/perl6.moarvm:MAIN)
         from gen/moar/main.nqp:47  (rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<mainline>)
         from <unknown>:1  (rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<main>)
         from <unknown>:1  (rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<entry>)

**Comment by raiph** [comment]
See also #2839 and #3414.
