### ISSUE TITLE
LTA: Cannot map a $thing to a Hash

### ISSUE THREAD

**Issue by taboege** [rakudo/rakudo#3032]
## The Problem

It's a known trap that `{}` is an empty hash and not an empty block. But this error could be more helpful:

```
$ perl6 -e '^10 .map: {}'
Cannot map a Range to a Hash.
Did you mean to add a stub ({...}) or did you mean to .classify?
```

The error message should definitely include a line number. Then the error would be easy to spot. If possible, maybe even explain `{}` vs. `{;}` when the hash is obviously empty. The suggestion of using `{…}` is helpful as this was what I meant in this case; can't make sense of `.classify` though.

**Comment by jnthn** [comment]
> The error message should definitely include a line number.

Rakudo version? I see a line number in `2019.03.1-667-g91ba858`:

```
$ perl6 -e '^10 .map: {}'
Cannot map a Range using a Hash
Did you mean to add a stub ({ ... }) or did you mean to .classify?
  in block <unit> at -e line 1
```

I don't immediately understand the classify thing either, but I'm guessing there was a motivating example that resulted in it being mentioned. I'm not sure why you'd ever want to map to an empty block; what were you trying to achieve them you wrote the code in question? We could suggest `{;}`, but I think suggesting `-> $ {}` is even better in that it makes clear that the result would be to take an argument and throw it away.

**Comment by taboege** [comment]
> Rakudo version?

Oh, sorry, I was on 2019.03.1 release. The backtrace in a more recent rakudo has a line number and leaves nothing to be desired!

> I'm not sure why you'd ever want to map to an empty block; what were you trying to achieve them you wrote the code in question?

It was an oversight. I changed something and went on to debug something else in the other half of the file. More than anything I missed the line number in my old rakudo in this case. But perhaps a "did you mean the empty block here?" is helpful for people unaware of `{}` vs. `{;}`. `-> $ {}` looks good too.
