### ISSUE TITLE
strange behavior of eqv

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#3033]
I would expect all 6 to return True.
This probably has to do with containers. But even with that it does not makes sense to me.
I would like a comparaison operator that is oblivious to that.
Or a good explanation of eqv works.

> my        $a = 'a'; $a eqv 'a'
True
> my Str $a = 'a'; $a eqv 'a'
True
> my str $a = 'a'; $a eqv 'a'
True
> my       @a = ['a']; @a eqv ['a']
True
> my str  @a = ['a']; @a eqv ['a']
False
> my Str  @a = ['a']; @a eqv ['a']
False

# perl6 -v
This is Rakudo version 2018.12-245-g94995d60e built on MoarVM version 2018.12-35-gc001ce23c
implementing Perl 6.d

**Comment by ugexe** [comment]
This seems consistent with how typing works elsewhere.
```
$ perl6 -e 'sub foo(Str @a) { }; my @a = ["a"]; foo(@a)'
Type check failed in binding to parameter '@a'; expected Positional[Str] but got Array ($["a"])
  in sub foo at -e line 1
  in block <unit> at -e line 1
```

**Comment by jnthn** [comment]
Indeed, this is consistent with `Scalar` containers disappearing under just about all operations, so when you do `eqv` on them you're talking about their contents, whereas `eqv` on two arrays is talking about the arrays, which are type-parameterized and so differ in type. Further, `eqv` is defined on objects, so the `str` is boxed into `Str` before any comparison happens.
