### ISSUE TITLE
Inconsistant syntax required to call module sub

### ISSUE THREAD

**Issue by ryn1x** [rakudo/rakudo#3034]
## The Problem
When calling a sub from a module the `M::foo` syntax works everywhere (that I have encountered) except for when using the statement modifier form of an if statement, then `&M::foo()` is required.

## Expected Behavior
`M::foo` syntax to work everywhere.

## Actual Behavior
`M::foo` syntax does not work with an if statement modifier.

### no & or parens with if statement modifier
```
module M {
    our sub foo() { say "foo" }
}

# this will error with "Cannot find method 'Nil' on object of type List"
M::foo if True;
```

### & and parens with if statement modifier
```
module M {
    our sub foo() { say "foo" }
}

# this works
&M::foo() if True;
```

### no & or parens with traditional if statement
```
module M {
    our sub foo() { say "foo" }
}

# this also works
if True { M::foo }
```

### & but no parens with if statement modifier
```
module M {
    our sub foo() { say "foo" }
}

# this does not error, but foo is never called
&M::foo if True;
```

**Comment by AlexDaniel** [comment]
It's an [old bug](https://gist.github.com/ab8cf513d1e988a4eeab2214af47763e), but bisected nonetheless: (2016-08-11) https://github.com/rakudo/rakudo/commit/977797fa401856e5310155f13469b7e6ff5f620a

**Comment by jnthn** [comment]
Fix and test committed.
