### ISSUE TITLE
signal has odd signature

### ISSUE THREAD

**Issue by chloekek** [rakudo/rakudo#3035]
The signature for signal contains a scalar parameter followed by a _flattening_ slurpy parameter:

```perl6
(Signal $signal, *@signals, :$scheduler = $*SCHEDULER)
```

This means that you can pass a list of signals, but only if the first element is given separately:

```perl6
signal(SIGHUP, SIGTERM); # ok
signal(SIGHUP, [SIGTERM]); # ok

# Cannot resolve caller signal(Array:D);
# none of these signatures match:
#     (Signal $signal, *@signals, :$scheduler = { ... })
signal([SIGHUP, SIGTERM]);
```

Which is rather odd and surprising. DWIM suggests allowing either one signal per argument or a list of signals as one argument.

* * *

Roast doesn't seem to test multiparameter signal, so whether this behavior is intended is unclear.

There would be two ways to resolve this:

```perl6
# Make the second parameter non-flattening slurpy.
# This does not allow passing a list of signals.
(Signal $signal, **@signals, :$scheduler = $*SCHEDULER)

# Remove the first parameter. This allows passing either
# separate signals or a list of signals. This is the signature
# that the documentation of signal presents.
(*@signal, :$scheduler = $*SCHEDULER)
```

Both would be compatible with Roast and incompatible with the current behavior.

**Comment by lizmat** [comment]
Agree the second would be better.  Not sure what I was on when I originally implemented that.  Fixed with eb88e64ea3
