### ISSUE TITLE
Diagnostic or definition problem?

### ISSUE THREAD

**Issue by alanrocker** [rakudo/rakudo#3036]
## The Problem
It's not clear what bounding characters are legitimate for multi-line comments
## Expected Behavior
Ambiguous: Either accept character following ` as valid, or complain about it at the start

## Actual Behavior 
For #`! ......
===SORRY!=== Error while compiling /home/guru/bin/./trivial
Prefix !
 requires an argument, but no valid term found
at /home/guru/bin/./trivial:21
------> !⏏<EOL>
    expecting any of:
        prefix

For #`@
===SORRY!=== Error while compiling /home/guru/bin/./trivial
Undeclared name:
    Doesn't used at line 32
Undeclared routines:
    either used at line 32. Did you mean 'ENTER', 'GATHER'?
    work used at line 32

## Steps to Reproduce
Run the following program, (with correct #!) then remove the comments around the examples.
Note the line numbers may not match the ones in the examples, depending on editing

#! /home/guru/bin/perl6
# program trivial 

#`(
  multi-line {1} works
  )

#`[
  another {2} works
  ]

#`{
  another (3) works
}

=begin comment

#`!
  Doesn't work
!

#=end comment
#=begin comment
#`@
  Doesn't work either
@

=end comment

# end trivial
                         
## Environment
* Operating system: Linux localhost 4.14.131-desktop-1.mga6 #1 SMP Thu Jun 27 11:19:36 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`perl6 -v`): 
Rakudo Star version 2019.03.1 built on MoarVM version 2019.03

**Comment by tbrowder** [comment]
What you refer to as "multi-line comments" are in fact "declarator blocks." The docs clearly state that a declarator block uses "matched pairs of parenthesis constructs such as ()..."  But I agree a completely delineated list would be more appropriate. 

Also declarator blocks are not defined inside other pod blocks, even "=begin comment" blocks.

**Comment by alanrocker** [comment]
> The docs clearly state that a declarator block uses "matched
> pairs of parenthesis constructs such as ()..."  But I agree a completely
> delineated list would be more appropriate.

In that case, perhaps the compiler should test for an invalid character
after the `, and flag it with "Invalid character for delimiting block, or
something similar, rather than exploding at random later?

> Also declarator blocks are not defined inside other pod blocks, even
> "=begin comment" blocks.

I provided the code to be uncommented to generate the error messages, in
contrast to the 3 working examples.

**Comment by tbrowder** [comment]
Hm, I just noticed the # followed by the backticks. Where is that construct mentioned in the docs?

**Comment by alanrocker** [comment]
> Hm, I just noticed the # followed by the backticks. Where is that
> construct mentioned in the docs?
>

https://docs.perl6.org/language/syntax#Multi-line_/_embedded_comments

**Comment by tbrowder** [comment]
I just added the missing '#' from the OP's example.

**Comment by tbrowder** [comment]
I removed myself because I don't think I can fix the Rakudo side. But I will still work on the docs side to better describe correct usage.

**Comment by alanrocker** [comment]
> I removed myself because I don't think I can fix the Rakudo side. But I
> will still work on the docs side to better describe correct usage.

I'd suggest changing https://docs.perl6.org/language/syntax

after "followed by a backtick, and then some opening bracketing character,
and end with the matching closing bracketing character.", insert
"Only the paired characters (), {}, [], and <> are valid for bounding
comment blocks. (Unlike matches and substitutions, where pairs such as !!,
|| or @ may be used.)"

I'd do it myself, if I had a map of the procedure for updating the docs.

**Comment by lizmat** [comment]
Do you know how to make a Pull Request?

**Comment by alanrocker** [comment]
> Do you know how to make a Pull Request?
>

No.

**Comment by lizmat** [comment]
Do you have a Github login?

**Comment by lizmat** [comment]
If you can find your way to the file you want to change in the repo, you can click the "pen" symbol: this will then open up an online editor.  Make the changes and follow the directions given.  That should allow you to make a Pull Request very quickly.

**Comment by alanrocker** [comment]
> Make the changes and follow the directions given.

Thank you for the instructions. I've done my best to follow them.

When trying something like this for the first time, it's nice to know that
one is unlikely to disobey the Hippocratic injunction:
https://tinyurl.com/y3536kyj

**Comment by tbrowder** [comment]
I think I've found a solution to the LTA Rakudo error message. Look for first cut tomorrow...
