### ISSUE TITLE
The Match class exposes internal Cursor methods

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#3038]
That could be confusing if the user wants to use the .print method.
The workaround is obvious though, use the equivalent function.

 perl6 --ll-exception -e '$_="a"; m/(.)/ &&  $0.print ' 
!cursor_start_cur cannot restart a cursor
   at gen/moar/stage2/QRegex.nqp:1527  (/Users/cog/git/rakudo/install/share/nqp/lib/QRegex.moarvm:!cursor_start_cur)
 from gen/moar/stage2/QRegex.nqp:2101  (/Users/cog/git/rakudo/install/share/nqp/lib/QRegex.moarvm:print)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1685  (/Users/cog/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1796  (/Users/cog/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1851  (/Users/cog/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:48  (/Users/cog/git/rakudo/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1777  (/Users/cog/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:54  (/Users/cog/git/rakudo/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:42  (/Users/cog/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/Users/cog/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/Users/cog/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<entry>)

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/4489a37e86
