### ISSUE TITLE
Cro::LDAP regression since 2019.03.1

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3045]
## The Problem

The module is not added to the ecosystem, so no Blin for it.

It is _probably_ a release blocker, **but**:
1)There were merges after `release` branch was cut, so if the module works in the release branch, we are safe.
2I have not sorted out latest commits that just hang with both versions and too sleepy to investigate this too. On #perl6 ugexe has confirmed the issue.

Good travis log for 2019.03.1: https://travis-ci.org/Altai-man/cro-ldap/jobs/556030341

Broken log for This is Rakudo version 2019.03.1-679-g80bf3d003 built on MoarVM version 2019.05-94-g459e68675: https://travis-ci.org/Altai-man/cro-ldap/jobs/556030342

## Expected Behavior

For module to be tested and installed fine.

## Actual Behavior

```
===> Testing: Cro::LDAP:ver<0.5.2>:auth<github:Altai-man>
===SORRY!===
Missing serialize REPR function for REPR NativeRef (StrLexRef)
```

## Steps to Reproduce

1)`git clone https://github.com/Altai-man/cro-ldap`
2)`cd cro-ldap`
4)`zef install .`

## Environment
* Operating system: Linux dispair 4.19.57_1 #1 SMP PREEMPT Wed Jul 3 21:16:27 UTC 2019 x86_64 GNU/Linux
* Compiler version (`perl6 -v`):

**Comment by Altai-man** [comment]
See https://colabti.org/irclogger/irclogger_log/perl6?date=2019-07-11#l689

**Comment by AlexDaniel** [comment]
Bisect log: https://gist.github.com/AlexDaniel/602d4af5feb32870540582d336533172
Bisected: e274f4a26ed0323369937fc867871d644173fe54

**Comment by AlexDaniel** [comment]
For the record, this is how you use Blin for cases like this: https://colabti.org/irclogger/irclogger_log/perl6?date=2019-07-11#l739

**Comment by AlexDaniel** [comment]
Thanks, @niner!

**Comment by Altai-man** [comment]
@niner, @AlexDaniel you are superheroes.

**Comment by AlexDaniel** [comment]
@Altai-man btw have you tested it? Does it *fully* work now?

**Comment by Altai-man** [comment]
I don't see this error anymore. As a bad thing, the travis seems to hang...
I will build release branch rakudo locally and see how it'll be later today.

**Comment by Altai-man** [comment]
```
===> Testing: Cro::LDAP:ver<0.5.2>:auth<github:Altai-man>
MoarVM panic: non-AsyncTask fetched from eventloop active work list
```
This is probably something for another blocker...

Building release branch.

**Comment by niner** [comment]
The hang is just a plain bug in Cro::LDAP: unbind calls disconnect which calls unbind. The test comes farther with this patch:

```
diff --git a/lib/Cro/LDAP/Client.pm6 b/lib/Cro/LDAP/Client.pm6
index a51f4d6..05a30ba 100644
--- a/lib/Cro/LDAP/Client.pm6
+++ b/lib/Cro/LDAP/Client.pm6
@@ -166,8 +166,8 @@ class Cro::LDAP::Client {
                 is-secure => $url.is-secure, :$ca-file);
     }
 
-    method disconnect() {
-        self.unbind;
+    method disconnect(Bool :$unbind = True) {
+        self.unbind if $unbind;
         $!pipeline.close;
         $!pipeline = Nil;
     }
@@ -189,7 +189,7 @@ class Cro::LDAP::Client {
         die X::Cro::LDAP::Client::NotConnected.new(:op<unbind>) unless self;
 
         self!wrap-request({ UnbindRequest.new });
-        self.disconnect;
+        self.disconnect(:!unbind);
     }
 
     method add($dn, :@attrs, :@controls) {
```

**Comment by Altai-man** [comment]
You are totally right. Fudged some tests that relied on broken `unbind` I started to fix yesterday and the fix was clearly not good enough while saw the rakudo issue and lost my will to continue.
I have fudged broken tests, if the travis passes with latest, I'll close the issue.
https://travis-ci.org/Altai-man/cro-ldap/jobs/557983590

**Comment by Altai-man** [comment]
Ok, so the state is:
1)On latest (after a fix) it passes all tests for me for 5 times in row.
2)But on travis I am getting the error... Possibly the travis setup exposes some concurrency bug. And this error also occured on 2019.03.1 too, so it is not new, thus not a blocker anymore.

Closing.
