### ISSUE TITLE
Unnecessary warnings on stderr

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3046]
The code in the script can be something as simple as:
```perl6
sub MAIN() { .sqrt.say for lines }
```

In your terminal:
```
$ perl6 ./testme.p6 
Reading lines from your keyboard, which is usually only done when debugging.
Please provide input and press Ctrl-d when done, or press Ctrl-c to abort.
```
What?! What debugging?

Commit in question: https://github.com/rakudo/rakudo/commit/ad8b5a64

If somebody develops an application which users often mistakenly run with no input, they should implement this logic themselves. It's as easy as `note ‘blah blah blah’ if $*IN.t`. The current implementation (`$*IN does role`) is a hack and it's even unclear how to turn that “feature” off.

To me the commit makes no sense, so I recommend to simply revert it. But I'm filing this issue in case I'm wrong and there's a disagreement.

**Comment by Kaiepi** [comment]
I'm ambivalent to this. It's easy to check if there's no input, but it's also easy to forget to add the check in the first place. I think the question is what behaviour would users expect a script to have by default when there's no input and input's expected?

**Comment by lizmat** [comment]
This commit was in response to I think a StackOverflow question on why a program was hanging.  It only happens when all of $*IN, $*OUT and $*ERR have `.t` True on them.

If you're stuck with the "usually with debugging" bit, we could think about removing the first line.  I think the second line explains what is expected of the user, and *is* useful.  Even *if* you know you're expected to do, that line doesn't hurt, does it?

FWIW, it has helped me realize that I was waiting for something that wouldn't come once or twice since this commit.

**Comment by lizmat** [comment]
Re the BLOCKER label?   Are you serious???   :-)

**Comment by patzim** [comment]
IMO this is too magical. I think this has potential to break someones code sooner or later in a situation where this gets triggered unexpectedly.

**Comment by lizmat** [comment]
The text is displayed:

    if $*IN.t && $*OUT.t && $*ERR.t && !@*ARGS

**and** you call `.slurp`, `.lines` or `.words` on `$*IN`

I'm unsure how this could break anybody's code.  Could you provide an example?

Also, please read the inspiration for this commit: https://www.reddit.com/r/perl6/comments/bc0efq/sql2png_turn_create_table_statements_into_a_graph/ekq6khy/

I would argue that some people (especially beginners) are helped by this.

**Comment by lizmat** [comment]
Also, I'd argue that removing https://github.com/rakudo/rakudo/commit/ad8b5a64 and https://github.com/rakudo/rakudo/commit/3060d1d0bd7e902d8ee501667df456b99dec2748 would be a regression.  But if consensus is that this should be removed, then by all means do.  It's been in the last release for 4+ months, and only now someone is complaining about it.

> If somebody develops an application which users often mistakenly run with no input, they should implement this logic themselves. It's as easy as note ‘blah blah blah’ if $*IN.t.

> The current implementation ($*IN does role) is a hack and it's even unclear how to turn that “feature” off.

**Comment by lizmat** [comment]
> The current implementation ($*IN does role) is a hack

Why is that a hack??  Could you elaborate on that?  To me, it is a perfect good use of being able to mix in methods into an existing object.  On which much of Perl 6 is based, by the way.

> and it's even unclear how to turn that “feature” off.

I'm unsure why you'd want to do that.  But maybe we should focus on that, instead of just claiming it is a regression?

**Comment by lizmat** [comment]
Commit 7668301dd6 adds another check: only display the message if nothing has been said on `$*OUT` or `$*ERR`.  So if you want disable the message, it is as simple as:

    note ‘blah blah blah’ if $*IN.t

This, to me, allows this ticket to be closed.

**Comment by patzim** [comment]
> I'm unsure how this could break anybody's code. Could you provide an example?

I would have to make one up. It's mostly a gut feeling that this will end up biting us in a situation we didn't think about.
Thinking more about it I can give a reason why I feel this is strange: Having `.slurp`, `.lines` and `.words` print stuff is unexpected for a low level function. I imagine me reading the documentation for the `.slurp` method: "Slurps stuff, and in this very specific situation prints stuff on $*ERR." - I would think "That's strange. I don't want to use that function, it has that strange sideeffect. Where is the slurp that just slurps?"

> I would argue that some people (especially beginners) are helped by this.

I agree. I do see the benefit of the warning.

**Comment by lizmat** [comment]
> Having .slurp, .lines and .words print stuff is unexpected for a low level function.

It is **only** in the context of using `MAIN`, and attempting to use those methods on `$*IN`.  So if this should be documented (of which I'm not convinced), it should be documented with the use of `MAIN`, and **not** with either `slurp`, `lines` or `words`.

**Comment by AlexDaniel** [comment]
Reverted for now, further discussion here: https://github.com/perl6/problem-solving/issues/60
