### ISSUE TITLE
Can the sequence operator be re-written to faster constructs in more cases than it is currently?

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#3048]
So e.g., https://github.com/ajs/perl6-Math-Sequences/pull/151 wouldn't be necessary? It will re-write some cases, e.g., `4...1` will become a `while`.

**Comment by lizmat** [comment]
Since I burned about a month of my life trying to sanitize ... and failed, I'd say: go ahead!

Meanwhile closing this issue
