### ISSUE TITLE
Digit grouping

### ISSUE THREAD

**Issue by ghost** [rakudo/rakudo#3053]
Perl 6 seems to have no way to format a number with commas or digit grouping.
Other languages offer this, for example C:

~~~c
#define _XOPEN_SOURCE 700
#include <locale.h>
#include <stdio.h>
int main() {
   setlocale(LC_ALL, "");
   printf("%'d\n", 1000);
}
~~~

Python:

~~~py
f'{1000:,}'
~~~

JavaScript:

~~~js
(1000).toLocaleString();
~~~

PHP:

~~~php
number_format(1000);
~~~

Go:

~~~go
package main
import "golang.org/x/text/language"
import "golang.org/x/text/message"
func main() {
   message.NewPrinter(language.English).Println(1000)
}
~~~

D:

~~~d
import std.format, std.stdio;
void main() {
   auto aa = "%,d".format(1000);
   writeln(aa);
}
~~~

**Comment by tbrowder** [comment]
There is a module that will commify a number:  "Text::More :commify"

**Comment by AlexDaniel** [comment]
I guess this is a request to change the language, so moving to problem-solving.

**Comment by AlexDaniel** [comment]
Oops.

**Comment by thundergnat** [comment]
Another module that provides this is [Lingua::EN::Numbers](https://modules.perl6.org/search/?q=Lingua%3A%3AEN%3A%3ANumbers):

    use Lingua::EN::Numbers;
    say comma 1e12.Int;

>: 1,000,000,000,000

**Comment by 0racle** [comment]
May as well also mention this can be implemented with a fairly small snippet...

    *.flip.comb(3).join(',').flip

So I don't think it needs it's own function in core. I think incorporating it into `printf/sprintf` is reasonable, particularly considering it's available in C... though I think D's use of `%,d` makes more sense than C's `%'d`.

**Comment by FCO** [comment]
or just a regex... 
```perl6
say S:g[^ (\d ** 1..3) (\d ** 3)+ $] = "$0,$1.join(",")" given 12345678
```

**Comment by lizmat** [comment]
Or even without a regex:
```raku
say 1000000.flip.comb(3).join("_").flip;  # 1_000_000
```

**Comment by lizmat** [comment]
closing as there are plenty code and ecosystem ways of doIng this
