### ISSUE TITLE
PseudoStash rework breaks compile time aliasing

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3058]
$ perl6 -e 'our constant &abs = CORE::<&abs>'
    ===SORRY!=== Error while compiling -e
    Type check failed in constant declaration of &abs; expected Callable but got Any (Any)
    at -e:1
    ------> our constant &abs = CORE::<&abs>⏏<EOL>

This used to work until 43582f5372e7413ee474 .

This breaks code at $work, and wouldn't be surprised this would break part of the ecosystem as well.

**Comment by lizmat** [comment]
Temporary workaround: remove the `constant` and use binding:

    our &abs := CORE::<&abs>

**Comment by vrurg** [comment]
I think this needs to be tested in roast, BTW.

Thanks! I'll see what can be done.

**Comment by lizmat** [comment]
Fixed, thanks!
