### ISSUE TITLE
Configure.pl attempts to use git when it shouldn't

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3062]
This affects people using release tarballs. If no git is installed, you get this error:
```
Can't exec "git": No such file or directory at Configure.pl line 14.
```
If it is, then you'll see this:
```
fatal: not in a git directory
```

It shouldn't even run these lines in these circumstances.

It doesn't affect anything badly, but it causes unnecessary output on stderr.

https://github.com/rakudo/rakudo/blob/f66c238ffa65990dfc4161ee04c95f4ca0786baf/Configure.pl#L18-L35

> \<patrickb\> Is looking for a .git folder a good way to check whether we are dealing with a release rakudo, i.e. no need for doing any submodule update stuff?
> \<AlexDaniel\> patrickb: that's going to work, yes. It makes sense not to run submodule commands if there's no git folder
> \<patrickb\> should be a two line change. I'll throw together a patch in the evening.

**Comment by patzim** [comment]
This has been fixed in [78c05c1225a8](https://github.com/rakudo/rakudo/commit/78c05c1225a8eb5485362494bcca1367daea1bb9) some days ago.
