### ISSUE TITLE
2019.07.1 point release?

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3067]
~It's currently not 100% clear if we want a point release~, but here's a list of things that will be included in one if we do it:

* MoarVM
  * https://github.com/MoarVM/MoarVM/pull/1138 – fix 06-struct.t flapping on Windows and elsewhere
  * https://github.com/MoarVM/MoarVM/commit/f1b26bb0e8f4e0a00ac31f9defb1ed74b820eb39 – `/usr` issue
  * https://github.com/MoarVM/MoarVM/commit/cfb5b3ae0f - fix excessive resource usage by spesh in certain cases
  * https://github.com/MoarVM/MoarVM/commit/2d54fa36bc, https://github.com/MoarVM/MoarVM/commit/ab7bac5ad1, and https://github.com/MoarVM/MoarVM/commit/c3c9d7dfac - make the debugger, profiler, and coverage work out significantly better on any multi-threaded programs
  * MoarVM/MoarVM@9cf16bb and MoarVM/MoarVM@e07c0f2 are essential for using confprog for anything nontrivial, so i'd love them both to go in. they are also both very simple
  * https://github.com/MoarVM/MoarVM/pull/1146 would be nice to have in case @Kaiepi can't argue for enabling the JIT by default when they get around to updating OpenBSD's port of MoarVM.
  * https://github.com/MoarVM/MoarVM/pull/1148 – fix debug server socket initialization https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-07-22#l123
* NQP
  * https://github.com/perl6/nqp/commit/cf98e04cfc244ce164f45d296ee3dfd5f62d457a?w=1
* Rakudo
  * https://github.com/rakudo/rakudo/commit/99e60a22c6?w=1
  * https://github.com/rakudo/rakudo/commit/1e0220ff59 – `/usr` issue

TODO:
- [x]  https://github.com/rakudo/rakudo/issues/3065

**Comment by patzim** [comment]
There is the install to `/usr` not working bug, for which I have not yet commited the fix.

**Comment by patzim** [comment]
[There it is.](https://github.com/rakudo/rakudo/pull/3068)

**Comment by jnthn** [comment]
If there's to be a MoarVM point release I'd also nominate:

* https://github.com/MoarVM/MoarVM/commit/cfb5b3ae0f - fix excessive resource usage by spesh in certain cases
* https://github.com/MoarVM/MoarVM/commit/2d54fa36bc, https://github.com/MoarVM/MoarVM/commit/ab7bac5ad1, and https://github.com/MoarVM/MoarVM/commit/c3c9d7dfac - make the debugger, profiler, and coverage work out significantly better on any multi-threaded programs

**Comment by timo** [comment]
MoarVM/MoarVM@9cf16bb7b and MoarVM/MoarVM@e07c0f252 are essential for using confprog for anything nontrivial, so i'd love them both to go in. they are also both very simple

**Comment by Kaiepi** [comment]
https://github.com/MoarVM/MoarVM/pull/1146 would be nice to have in case I can't argue for enabling the JIT by default when I get around to updating OpenBSD's port of MoarVM.

**Comment by Altai-man** [comment]
If seems that GB2312 encoding has landed, possibly we should add it too?

**Comment by AlexDaniel** [comment]
New features can wait till 2019.09. I prefer to focus on actual bug fixes that didn't exist in previous releases.

**Comment by lizmat** [comment]
Agree...  should only be 3 weeks until the next release or so...

**Comment by lizmat** [comment]
Not going to be a 2019.08 ?

**Comment by hankache** [comment]
Please ping me whenever 2019.07.1 gets released so we can start packaging Rakudo Star. Thanks :)

**Comment by AlexDaniel** [comment]
> Not going to be a 2019.08 ?

Yeah, it is currently not planned:

https://github.com/rakudo/rakudo/blob/60cfbb39e967c44d08c460ba2c7d7dce0d9ba304/docs/release_guide.pod#L15-L22

**Comment by lizmat** [comment]
then let's try to get it out on 1 Sep, so we have some time to fix blockers  :)

**Comment by AlexDaniel** [comment]
I like it, sounds like a great idea.

**Comment by AlexDaniel** [comment]
Ah, this is now done!
