### ISSUE TITLE
String interpolation with block evaluates to declared return value of enclosing routine, if any

### ISSUE THREAD

**Issue by chloekek** [rakudo/rakudo#3070]
## Expected Behavior

```perl6
sub f(--> Nil) { say "{1}"; }
sub g(--> 2) { say "{1}"; }
sub h { say "{1}"; }
f; # OUTPUT: «1␤»
g; # OUTPUT: «1␤»
h; # OUTPUT: «1␤»
```

## Actual Behavior

```perl6
sub f(--> Nil) { say "{1}"; }
sub g(--> 2) { say "{1}"; }
sub h { say "{1}"; }
f; # OUTPUT: «Use of Nil in string context␤␤  in sub f at <tmp> line 1␤»
g; # OUTPUT: «2␤»
h; # OUTPUT: «1␤»
```

## Environment

* Operating system: Ubuntu GNU/Linux 16.04.
* Compiler version (`perl6 -v`): This is Rakudo version 2019.03 built on MoarVM version 2019.03 implementing Perl 6.d.

## P.S.

If confirmed a bug I'd like to add this to Roast to get familiar with the workflow and maybe even fix it in Rakudo.

**Comment by AlexDaniel** [comment]
Yes, it's clearly a bug. If you're on IRC (or Matrix, or Discord), then you can ask `committable6` to run that code snippet on `all` releases ([log](https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-07-19#l144)):

> \<AlexDaniel\> c: all `sub f(--> Nil) { say "{1}"; }; sub g(--> 2) { say "{1}"; }; sub h { say "{1}"; }; f; g; h;`
> \<committable6\> AlexDaniel, https://gist.github.com/5d984e23482807fb04214c05e10e3d6f

So we can see it's not a regression, and it has always been like that. Weird. So yes, a fix is welcome :) I'll assign you to this issue.

**Comment by JJ** [comment]
I'm not so sure this is a bug, or at least all of them, or at least that type of bug. 
For instance, let's check this out:
```perl6
sub f( --> Nil ) { say "hey" }; say f
# hey
# Nil
```
That's OK. It works in the same way if we just use `f`. It will return Nil in a void context, we don't care about it, that's fine. But we are using a block inside a string. Well.
```perl6
sub f() { say "hey" }; say f
hey
True
```
This is what happens. It returns True, because that is what say does, runs the body, that's fine too. We turn that into a block:
```perl6
sub f() { say "{'hey'}" }; say f
hey
True
```
Same thing. No problem. Something weird starts to happen here:
```perl6
sub f(--> "Hey" ) { say "{'hey'}" }; say f
Hey
Hey
```
Say what? The return value has sneaked into the block evaluation. 
```perl6
sub f(--> 32 ) { say "{3+2}" }; say f
32
32
```
Come again? 
You don't even need the `say`
```perl6
my $zipi; sub f(--> 32 ) { $zipi = "{33+44}" }; say f; say $zipi
32
32
```
It does not need to be the last expression in the block:
```
my $zipi; sub f(--> 32 ) { $zipi = "{33+44}"; say "zape" }; say f; say $zipi
zape
32
32
```

So it seems to be a problem with `{}` in a sub context, a rather general one. Also, it might be a feature but not a bug, but I guess not...

**Comment by JJ** [comment]
I would say that what --> actually does is to make the return value of *any* block inside it equal to the constant it returns, not only the outer scope. So quite a nasty bug, and a nice catch, @chloekek 
I don't know if that will happen also when it's not a constant. Let me think of a test for that

**Comment by chloekek** [comment]
Doesn't seem to happen for all blocks:

```
sub f(--> 2) { my &g = { 1 }; say g }; f
# OUTPUT: «1␤»
```

**Comment by JJ** [comment]
Right. I'll fix that.

**Comment by JJ** [comment]
It does not happen when the return signature is not a constant, apparently, or I have not been able to reproduce it.

**Comment by JJ** [comment]
This is not a problem either:
```perl6
my $zipi;

sub f(--> 33 ) {
    $zipi = {44}();
};

say f;
say $zipi
```

Block evaluation in a string context only? In a string interpolation context only?

**Comment by JJ** [comment]
This works correctly too:
```perl6
my $zipi;

sub f(--> 33 ) {
    $zipi = <a b c>.map: {44}
};

say f;
say $zipi
```

So, again, it does not seem to affect block return value unless it's in a string context.

**Comment by chloekek** [comment]
Nested interpolation is also affected:

```perl6
sub f(--> 2) { "{say "{1}"}" }; f
# OUTPUT: «2␤»
```

But other nested blocks aren't:

```perl6
sub f(--> 2) { "{say {1}()}" }; f
# OUTPUT: «1␤»
```
