### ISSUE TITLE
Deadlock when using multiple CATCH + rethrow

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#3080]
## The Problem

```
perl6 -Mnqp -e '                              \
    loop {                                    \
        say ++$;                              \
        CATCH { default { } };                \
        {                                     \
            CATCH { };                        \
            my $ex := nqp::newexception();    \
            try nqp::setmessage($ex, "test"); \
            nqp::rethrow($ex);                \
        }                                     \
    }
'
```

This program deadlocks. See: https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-07-23#l183 -- this is a golf of the deadlock when doing:
`perl6 -e 'loop { say ++$; my $r = run("xxx"); }'`

but works with `MVM_SPESH_DISABLE=1`

## Expected Behavior

The program should run indefinitely

## Actual Behavior

The program deadlocks after some number of iterations

## Environment
* Operating system: `OSX`
* Compiler version (`perl6 -v`): `This is Rakudo version 2019.03.1-683-g20e74837a built on MoarVM version 2019.07-5-gdefe0a959
implementing Perl 6.d.`

**Comment by voldenet** [comment]
Using `nqp::throw` instead of `nqp::rethrow` also produces similar bug, but default awaiter users rethrow.

**Comment by dogbert17** [comment]
This seems to work now with

    dogbert@dogbert-VirtualBox:~/repos/rakudo$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-88-gc37ffe71b.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/e5baa0c63b
