### ISSUE TITLE
Using "multi" vs. "sub" breaks state variables.

### ISSUE THREAD

**Issue by lembark** [rakudo/rakudo#3083]
## The Problem

Using a sub with state var's wrks; replacing the sub with a multi (no other changes in the code) leaves the state variables not keeping their state.

## Expected Behavior

state %init = %sample;    # state variable should retain value between calls.

## Actual Behavior

%init is empty.

## Environment
* Operating system: 
(1) Linux steamer 5.1.7-gentoo.at #1 SMP Fri Jun 7 17:04:25 CDT 2019 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux

(2) Linux dizzy 5.1.15-gentoo.domu-ac #2 SMP Tue Jul 9 23:16:28 CDT 2019 x86_64 AMD Opteron(tm) Processor 6172 AuthenticAMD GNU/Linux

* Compiler version (`perl6 -v`): 

(1) This is Rakudo version 2019.03.1-640-g63b9e1fe3 built on MoarVM version 2019.05-53-gcce71cdbf
implementing Perl 6.d.

(2) 

This is Rakudo version 2019.03.1-585-gb8669fe6f built on MoarVM version 2019.05-49-gfbb1ddd8e
implementing Perl 6.d.

**Comment by lembark** [comment]
#! /usr/bin/env perl6
use v6.d;

use Test;
plan 6;

my %data = :a(1), :b(2), :c(3);

{
    sub demo (%positional, :$named)
    {
        state %state = %positional;
        is-deeply %state, %positional, 'sub demo(%positional, :$named)';
    }

    demo(%data);
}
{
    multi demo (%positional, :$named)
    {
        state %state = %positional;
        is-deeply %state, %positional, 'multi demo(%positional, :$named)';
    }

    demo(%data);
}
{
    sub demo (%positional)
    {
        state %state = %positional;
        is-deeply %state, %positional, 'sub demo(%positional)';
    }

    demo(%data);
}
{
    multi demo (%positional)
    {
        state %state = %positional;
        is-deeply %state, %positional, 'multi demo(%positional)';
    }

    demo(%data);
}
{
    sub demo (%positional, :$named)
    {{
        state %state = %positional;
        is-deeply %state, %positional, 'sub demo(%positional, :$named) {{...}}';
    }}

    demo(%data);
}
{
    multi demo (%positional, :$named)
    {{
        state %state = %positional;
        is-deeply %state, %positional, 'multi demo(%positional, :$named) {{...}}';
    }}

    demo(%data);
}
done-testing;

=finish

{
    multi demo (%positional, :$named)
    {{
        state %state = %positional;
        dd 'multi{{}}', %positional, %state, '_' x 50;
    }}

    my %data = :a(1), :b(2), :c(3);
    demo(%data);
    demo(%data);
}

**Comment by lembark** [comment]
Unable to attach a .p6 file...

**Comment by lembark** [comment]
https://pastebin.com/ECDEFLnQ

**Comment by dogbert17** [comment]
This seems to have been fixed with the merge of the new-disp branch, i.e. commit dd2b274fd59f18. All tests the example above now pass.

**Comment by jnthn** [comment]
Yes, the elimination of a trial invocation happened as part of the `new-disp` work, and that would have been to blame for the failed state variable intialization. Another nice benefit of that change.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/3cd5e8d87d
