### ISSUE TITLE
`use` is not working in the module load by `require`.

### ISSUE THREAD

**Issue by araraloren** [rakudo/rakudo#3084]
## The Problem

The test repository: https://github.com/araraloren/for-perl6-bug

`use` is not working in the module (APlugin) load by `require`.

## Expected Behavior

Display the string `bar`.

## Actual Behavior

An error was raised by rakudo: `Cannot invoke this object (REPR: Null; VMNull)`

## Steps to Reproduce

Clone the code, run command `perl6 main.p6`
PS: The code will working when you run command `perl6 -Ilib -MCommon main.p6`

## Environment
* Operating system: fedora 30 64bit
* Compiler version (`perl6 -v`):  2019.07

**Comment by AlexDaniel** [comment]
* Output on all releases: https://gist.github.com/Whateverable/18409e3ef8773f652bd2cff88e28c264
* Bisected: (2016-04-01) https://github.com/rakudo/rakudo/commit/34942c8597d9ba8b3a8367a688a2b9f68a914a46
* NQP version bump brought in these changes: https://github.com/perl6/nqp/compare/2016.03-13-gbd39fe2...2016.03-44-g2632192

**Comment by vrurg** [comment]
Tested on 2019.07.1 – fails. `HEAD` passes.

Closing via MoarVM/MoarVM#1209 and 7e3d023b4b070ed798915336a98f2bbc7fbac2e7
