### ISSUE TITLE
bad link in README: to features page on perl6.org

### ISSUE THREAD

**Issue by GregDavidson** [rakudo/rakudo#3089]
## The Problem
the features page on perl6.org, linked to by the README does not link to a valid page
# Expected Behavior
A working link
## Actual Behavior
A broken link
## Environment
* Operating system: 
* Compiler version (`perl6 -v`):

**Comment by tqdv** [comment]
This was fixed by [commit 302bc8e](https://github.com/rakudo/rakudo/commit/302bc8ed8b22adce05f1b84277ca471e0300a3a4) in August 2019. We can probably close this issue now.

**Comment by Altai-man** [comment]
Indeed. Thank you very much for noticing! Closing now.
