### ISSUE TITLE
Installer is broken with --libdir=/usr/lib

### ISSUE THREAD

**Issue by atweiden** [rakudo/rakudo#3093]
rakudo-2019.07.1 with `Configure.pl --libdir=/usr/lib` does not work post-installation:

```
Unhandled exception: While looking for '/usr/share/perl6/runtime/perl6.moarvm': no such file or directory
```

The 2019.03 release did not have this problem.

It can be fixed with `ln -rs /usr/lib/perl6 /usr/share/perl6`.

**Comment by patzim** [comment]
@atweiden The is a plan to remove the `--libdir` option, because it's conceptually conflicting with a recent change. In what context do you need to put the core libraries in a different folder? Would a solution that allows to install the entire `share/perl6` and the entire `share/nqp` folder into a different place also solve your need?

**Comment by atweiden** [comment]
> In what context do you need to put the core libraries in a different folder?

Placing ELF binaries in `/usr/share` [violates](https://github.com/void-linux/void-packages/blob/master/common/hooks/post-install/11-pkglint-elf-in-usrshare.sh) Void Linux packaging standards.

> Would a solution that allows to install the entire share/perl6 and the entire share/nqp folder into a different place also solve your need?

So long as it prevents ELF binaries from being installed under `/usr/share`, yes.

**Comment by AlexDaniel** [comment]
@patzim any updates on this? :)

**Comment by patzim** [comment]
I have a branch [home-config-option](https://github.com/patzim/rakudo/tree/home-config-option) (and related nqp and nqp-configure branches) lying around that fix this. They was waiting for vrurgs build refactorings so the merge wouldn't interfere. And now I have two more weeks of No Time At All™ ahead of me. I might find some time in between, but no guarantees.

**Comment by vrurg** [comment]
@patzim BTW, I'm done with rakudo. Hope that NQP rework doesn't affect you.

**Comment by patzim** [comment]
@atweiden I have now implemented `--perl6-home` and `--nqp-home` `Configure.pl` options that allow putting the respective folders in a different place. I also removed the now broken `--libdir` option. I'd be grateful for feedback whether these changes address your packaging needs.
