### ISSUE TITLE
Confusing error message when redeclaring/modifying a read-only variable

### ISSUE THREAD

**Issue by randyl** [rakudo/rakudo#3102]
## The Problem

Executing the following code returns a confusing error message:

```
perl6 -e 'sub MAIN( :$input ) { my $input //= 1; }'
===SORRY!===
Cannot find method 'default' on object of type NQPMu
```
## Expected Behavior

An error about redeclaring $input, or modifying a read-only variable.

## Actual Behavior

The confusing message `Cannot find method 'default' on object of type NQPMu`

## Steps to Reproduce

Run the above command.

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07 built on MoarVM version 2019.07
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
Previously:
```
Potential difficulties:
    Redeclaration of symbol '$input'
    at /tmp/u2cNivMWW8:1
    ------> sub MAIN( :$input ) { my $input⏏ //= 1; }
Cannot assign to a readonly variable ($input) or a value
  in sub MAIN at /tmp/u2cNivMWW8 line 1
  in block <unit> at /tmp/u2cNivMWW8 line 1
```

Bisected: (2019-01-02) https://github.com/rakudo/rakudo/commit/42024539877fbebfdfbbc9b006106454cdaf5187
Output before and after: https://gist.github.com/9dca1ae54d66d0cf2132c07315d3cb23

Obligatory ping: @jnthn :)

**Comment by AlexDaniel** [comment]
Seems to be a dup of https://github.com/rakudo/rakudo/issues/2909.

**Comment by jnthn** [comment]
Fixed and test covered.
