### ISSUE TITLE
Flapping segfault in this program

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3114]
## The Problem

This program segfaults 1/3 of the times (roughly)

```perl6
#!/usr/bin/env perl6

use v6;

sub road-royale ( @χ ) {
    @χ.rotor(4).map( {so @_.all + so @_.none}).sum;
}

sub mutate ( @x is copy ) {
    @x[ (^@x.elems).pick ] ?^= True;
    @x;
}

sub xover( @x, @y ) {
    my @pairs = @x Z @y;
    my $xover1point = @x.keys.pick;
    my $xover2point = ($xover1point^..@x.elems).pick;
    my @crossed =  gather for @pairs.kv -> $index, @value {
        take ( ($xover1point <= $index <= $xover2point) ?? @value.reverse !!
            @value );
    }
    return [Z] @crossed;
}

sub MAIN( :$length = 64, :$population-size =  200 ) {

    my @population = ( Bool.pick() xx $length ) xx $population-size;
    say @population[0],@population[1];
    say xover( @population[0],@population[1]);
    loop {
        my $evaluated = @population.map( { @$_ => road-royale( @$_ ) } ).Mix;
        say "Evaluating ";
        last if any( $evaluated.values ) == $length/4;
        my @reproductive-pool = $evaluated.roll( $population-size );
        my @crossed = @reproductive-pool.pick( $population-size / 5 ).rotor(2).map( { xover( @$_[0], @$_[1] ) } );
        my @mutated = @reproductive-pool.pick( $population-size*3/5).map( {mutate(@$_)} );
        @population = ( @crossed.Slip, @mutated.Slip, @reproductive-pool.pick( $population-size / 5 ).Slip );
    }
    say @population;
}
```

## Steps to Reproduce

Run it three times, it's likely to segfault at least once.

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

```
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.
```

```
Linux bojack 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by niner** [comment]
Doesn't fail with MVM_SPESH_DISABLE=1, fails much more often with MVM_SPESH_BLOCKING=1. It's neither JIT. PEA seems innocent, too. MVM_SPESH_INLINE_DISABLE=1 however does seem to help.

A little debugging session with rr gave a hint that uninlining may be involved. So maybe it's the combination of an uninline deopt with an inlined ìs copy`call. Maybe uninlining does not restore all the information needed to finish argument processing? I don't see code for setting up uf->params

**Comment by AlexDaniel** [comment]
I was able to reproduce it. The bug exists in rakudo 2019.03.1, so it's not very new, but I think it's important to fix this.

**Comment by dogbert17** [comment]
This seems to be a relatively old bug. With the help of the excellent bisectbot and AlexDaniel++ it would seem as if the offending commit can be found here 2840a2960a3159a2292d15fc58d156768bd3bd4f

Some additional, i.e. manual, work leads me to believe that the real culprit is commit https://github.com/MoarVM/MoarVM/commit/50c76e211f2702ee2868ec718a03b9022c21f13b

**Comment by niner** [comment]
I guess that the commit you found is not really the reason. Reads like it just unblocked inlining while the bug seems to be in deopt of code inlined into arg processing. So the bug was there before, it was just hidden

On August 25, 2019 11:09:02 PM GMT+02:00, dogbert17 <notifications@github.com> wrote:
>This seems to be a relatively old bug. With the help of the excellent
>bisectbot and AlexDaniel++ it would seem as if the offending commit can
>be found here 2840a2960a3159a2292d15fc58d156768bd3bd4f
>
>Some additional, i.e. manual, work leads me to believe that the real
>culprit is commit
>https://github.com/MoarVM/MoarVM/commit/50c76e211f2702ee2868ec718a03b9022c21f13b
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/rakudo/rakudo/issues/3114#issuecomment-524663793

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jnthn** [comment]
> Maybe uninlining does not restore all the information needed to finish argument processing? I don't see code for setting up uf->params

Indeed, that's probably the issue.

**Comment by jnthn** [comment]
With https://github.com/MoarVM/MoarVM/commit/cf3b545e53664db022a68e2b8dccbceb095bc134 this goes from quite reliably segfaulting with `MVM_SPESH_BLOCKING=1` to not segfaulting at all.

**Comment by jnthn** [comment]
It should probably get a test, however I fixed the issue by tracing it from the SEGV location and based on the analysis of @niner, so I'm afraid I've no golfed version to offer.

**Comment by AlexDaniel** [comment]
Confirming that it doesn't segfault anymore. Blocker label removed, but yes I'd love to have a test for this.
