### ISSUE TITLE
regex in package treated as subroutine

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3119]
```
package P { our regex r { .+ } };
say 'match' ~~ P::r;
# rakudo-moar ecf2b1e4f: OUTPUT: «Too few positionals passed; expected 1 argument but got 0␤  in regex r at <tmp> line 1␤  in block <unit> at <tmp> line 1␤␤»
```

our-scoped regexes in a different scope seem not to be treaded the same way then regex that are in the same scope then the caller. Also `/<P::r>/` will fail too, what may be related.

**Comment by jnthn** [comment]
Regexes are code objects, and so will be invoked if called. The `package` isn't needed to show this behavior; this is the same:

```
our regex r { .+ }
say 'match' ~~ r;
```

As does `my` scope:

```
my regex r { .+ }
say 'match' ~~ r;
```

To smart-match against it, one needs to noun it:

```
package P { our regex r { .+ } };
say 'match' ~~ &P::r;
```

Which prints:

```
｢match｣
```

Closing because this behavior is to spec.
