### ISSUE TITLE
LTA error msg with pod configuration value

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3121]
## The Problem

Given this invalid pod code at compilation:

    =begin code :preamble<my @letters = <a b>>
        some text
    =end code

    say "'{$=pod[0].config<preamble>}'";

## Expected Behavior

A good error message pointing to the invalid pod configuration value.

## Actual Behavior

This LTA error message results:

    ===SORRY!=== Error while compiling /home/tbrowde/rakudo-dev/rakudo/d4.t
    Colon pair value 'my @letters = <a b>' too complex to use in name
    at /home/tbrowde/rakudo-dev/rakudo/d4.t:4
    ------> egin code :preamble<my @letters = <a b>>⏏<EOL>

## Environment

* Operating system: Debian Buster
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07-91-gdcf8c16d4 built on MoarVM version 2019.07-17-ga7563e71b
implementing Perl 6.d.

## Using correct syntax

Using this corrected pod code:

    =begin code :preamble('my @letters = <a b>')
        some text
    =end code

    say "'{$=pod[0].config<preamble>}'";

At compilation yields the desired result:

    'my @letters = <a b>'

**Comment by lizmat** [comment]
Superseded by RakuDoc where this *is* a valid config value

**Comment by tbrowder** [comment]
Cool, you're rockin' and rollin'!
