### ISSUE TITLE
Clarification/Help - META6.json

### ISSUE THREAD

**Issue by pprocacci** [rakudo/rakudo#3124]
I have a perl6 module that I am developing that dynamically builds class files that are to be used at runtime.  While the build process gets invoke from the META6.json file, I can not fathom how to reference the created class files within the META6.json as they are the be made available to "other" "outside" scripts.

Currently I stick these generated files in a directory called auto-lib:
# find auto-lib -type f -ls | wc -l
     179

Normally, I stick such stuff in either "provides" or "resources" within the META6.json file, but given that both the names and number of the class files themselves are dynamic, there's simply no way for me to pre-populate this file with the necessary entries.

What's the suggested way to handle this?  Is it even necessary?  (cleanup, etc)

**Comment by vrurg** [comment]
Normally you're not obliged to have them in META6.json if you don't publish and using them with either `-I` command line option, or with `use lib` statement.

But if you publish it in any way (either it be CPAN, ecosystem, or just into a local repo with `zef install .`) then I guess you have those pre-generated prior to publishing. For this case I can recommend you `META6` module and a script which would collect the classes and produce `META6.json` file for you.

**Comment by pprocacci** [comment]
The intention is certainly a local repo with zef.
Thanks for pointing me to the META6 module.
It sounds like that's the way I'll need to go with this.

Appreciate the quick feedback.
