### ISSUE TITLE
Backtrace.new.list.elems doesn't reflect the depth of the "callstack"

### ISSUE THREAD

**Issue by ufobat** [rakudo/rakudo#3148]
## The Problem
Currently I was playing around with recursive calls. I wanted to figure out how deep a call to a sub-routine is. I was assuming that `Backtrace.new.list.elems` reflects to that depth.

Either my assumptin is wrong or Backtrace is missing a method which returns the current depth of the callstack (#3147). Whatever the case may be, it should be documented, no?

## Expected Behavior
In `perl6 -e 'sub a() { say Backtrace.new.list.elems; a() }; a()'` each say should print a number which is 1 bigger then the number in the last line.

## Actual Behavior
In `perl6 -e 'sub a() { say Backtrace.new.list.elems; a() }; a()'` the output stops to increase at `101`

**Comment by dogbert17** [comment]
Perhaps the explanation can be found here:

https://github.com/rakudo/rakudo/blob/master/src/core/Backtrace.pm6#L316

**Comment by lizmat** [comment]
Addressed with 559c24f066
