### ISSUE TITLE
Processes that segfault should return a failure (just like they do for non-zero exit codes)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3149]
Say you have code that runs a process which exits with non-zero exit code:
```perl6
run ‘perl6’, ‘-e’, ‘exit 42’
```
You get this:
```
The spawned process exited unsuccessfully (exit code: 42)
  in block <unit> at /tmp/YpeQuSQlLe line 1
```

Which makes sense! However, if your process segfaults, like this:
```perl6
run ‘perl6’, ‘-e’, ‘use NativeCall; sub strdup(int64) is native(Str) {*}; strdup(0)’
```
Then it's considered absolutely fine! No Failure, and your program keeps going as if nothing wrong happened.

**Comment by jnthn** [comment]
This somewhat explains it:

```
$ perl6 -e 'dd run ‘perl6’, ‘-e’, ‘use NativeCall; sub strdup(int64) is native(Str) {*}; strdup(0)’'
Proc.new(in => IO::Pipe, out => IO::Pipe, err => IO::Pipe, exitcode => 0, signal => 11, pid => 8454, command => ("perl6", "-e", "use NativeCall; sub strdup(int64) is native(Str) \{*}; strdup(0)"))
```

We only consider the exitcode part, not the signal part, when deciding whether to blow up. I'm trying a patch to address that.
