### ISSUE TITLE
 ```Promise.in(2**54)``` yields a confusing exception. ```Promise.in(2**53)``` is accepted (but maybe is wrong?)

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#3152]
Reproduced here: https://colabti.org/irclogger/irclogger_log/perl6?date=2019-08-29#l261

----

Both the following are absurdly long times ...

```
Promise.in(2**53);
Promise.in(2**54);
```

... but it's disconcerting that the first one is accepted (but with the right time? what about ```Promise.in(2**21)```?) and the second one fails with:

```Cannot unbox 64 bit wide bigint into native integer```

Note that the input is 54 bits wide but the unbox message says 64 bits wide.

----

Per [Wikipedia](https://en.wikipedia.org/wiki/Power_of_two), ```2**53``` is "The number until which all integer values can exactly be represented in IEEE double precision floating-point format."

Maybe that's relevant?

----

I thought about testing whether a `Promise.in(2**16)` (a bit over 18 hours) works but even if it did it would be on an old Rakudo and still leave me with lingering doubt so I thought it better to study the code and see if I could figure out what was going on. Then, having done that, I decided I might as well file an issue to record what I found.

----

I've looked at the Rakudo code. It's perhaps beyond my saygrade but regardless I'm going to say I think ```Promise.in``` turns into a call to ```.cue``` on a scheduler and lands in [this area](https://github.com/rakudo/rakudo/blob/master/src/core.c/ThreadPoolScheduler.pm6#L842-L894).

**Comment by jnthn** [comment]
The `Promise.in`/`Scheduler.cue` level will accept any `Real` and treats it as a number of seconds, but the internals need a number of milliseconds. Thus it'll be the `2**54 * 1000` that is overflowing.

**Comment by jnthn** [comment]
Oh, and:

> Per Wikipedia, 2**53 is "The number until which all integer values can exactly be represented in IEEE double precision floating-point format."
> 
> Maybe that's relevant?

No, but it's a mildy entertaining coincidence; there's 10 bits for the exponent, and 1000 is roughly 1024 which is the range of those bits. :)
