### ISSUE TITLE
Provide system admins a module and scripts suitable for installing and maintaining ecosystem modules 

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3159]
## The Problem

System administrators may not be Raku experts, but they may need to maintain system-wide currency on available (and testable) modules in the ecosystem.

## Expected Behavior

The Raku developers should provide a curated module that includes scripts that can operate as follows.

A. a script that:

1. can generate a list of all currently available modules
2. downloads, tests, and installs modules that pass tests
3. provide a log of installed modules including latest version data

B. a script that uses the log from A to run a cron job to:

1. check for later versions of installed modules
2. download, test, and install modules that pass tests
3. provide the same log as described in A.3. above

Such scripts should be optimized to test modules concurrently based on available cores and threads.

**Comment by niner** [comment]
Isn't this a job that Linux distributions do fairly well already? Why reinvent this, when I already can just run `zypper up` to get my modules updated, complete with cron jobs for that, logs, querying functionality and the possibility to lock modules to versions if I know there are issues?

**Comment by jonathanstowe** [comment]
The https://github.com/jonathanstowe/App-ModuleSnap may do part of what you want.

**Comment by tbrowder** [comment]
> The https://github.com/jonathanstowe/App-ModuleSnap may do part of what you want.

That looks like the ticket--I'll check it out. Thanks!

**Comment by tbrowder** [comment]
> Isn't this a job that Linux distributions do fairly well already? Why reinvent this, when I already can just run `zypper up` to get my modules updated, complete with cron jobs for that, logs, querying functionality and the possibility to lock modules to versions if I know there are issues?

I'm on Debian and not familiar with zypper. The Deb packages provided by @nxadm work fine but modules aren't handled by any Debian package I'm aware of--way too fast-moving for the Debian way.
