### ISSUE TITLE
Different behavior for `reduce &[<=], @numbers` and `[<=] @numbers`

### ISSUE THREAD

**Issue by koorchik** [rakudo/rakudo#3163]
## The Problem
Bug in "reduce" behavior. 

## Expected Behavior
According to the documentation this should behave the same:
```
reduce &[<=], @numbers;
[<=] @numbers;
```

## Actual Behavior
The results are different. Only the short form works correctly. The same is with "reduce" method.
## Steps to Reproduce
```
> my @numbers = 23, 5, 46;
[23 5 46]
> reduce &[<=], @numbers
True
> [<=] @numbers
False
> @numbers.reduce(&[<=])
True

```

## Environment
* Operating system: 
```
>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

But the same issue is on OSX too

* Compiler version (`perl6 -v`): 
```
>perl6 -v
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.
```

**Comment by vendethiel** [comment]
The equivalence only exists for non-chaining operators. `<=` is a chaining operator.

**Comment by koorchik** [comment]
Is there any place to read about it?

According to the docs, it says that short-form is just a syntactic shortcut for a larger form:  "Since reducing with an infix operator is a common thing to do, the [ ] metaoperator provides a syntactic shortcut"

Another thing:  "in other words, (VAL1, VAL2, VAL3).reduce(&[OP]) is the same as VAL1 OP VAL2 OP VAL3 even for operators which aren't left-associative" but in real when OP = "<=" the behavior is different. 

I am rather new to Perl6, possibly it is my understanding of the docs :)

**Comment by codesections** [comment]
As of Rakudo v2021.05, all of the examples above now (correctly) return `False`.

I'm not sure when that fix landed, but I'm going to close this issue.  Please feel free to re-open it if the issue persists in a current version of Rakudo.
