### ISSUE TITLE
Rakudo's perl6-gdb-m Does Not Provide a Mechanism for Loading core-dumps

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#3167]
Currently, when I get a SEGV in perl6, it is easy enough to trace back if the error is readily reproducible. However, when the error seems to either float or flap, the only way to perform a backtrace is to load a core dump.

perl6-gdb-m does not seem to provide such a mechanism.

If I am mistaken and there is one, can someone please let me know, otherwise I think this is a feature that is seriously overdue.

What would be required to implement this?

**Comment by niner** [comment]
I usually load those core dumps with `gdb --core=mycoredump --exec=perl6`
I wonder what perl6-gdb-m could add to this in terms of functionality. Thinking about this, I wonder if perl6-gdb-m has any use at all anymore. It was very useful when perl6 was just a shell script but nowadays `gdb --args perl6 myprogram.p6` does the job just fine.

**Comment by Xliff** [comment]
Thanks, @niner!
