### ISSUE TITLE
multi method from role with hash constraint not callable in class

### ISSUE THREAD

**Issue by bduggan** [rakudo/rakudo#3172]
## The Problem

When a class `does` a role and the role has a multi method which has a constraint that uses a hash, the multi method is not callable from other compunits.

## Expected Behavior
It should be callable

## Actual Behavior
You get `Cannot resolve caller` -- see below

## Steps to Reproduce

Make a file with a class and a file with a role --
```
$ cat C.pm6
use R;

class C does R { }
```
```
$ cat R.pm6
my %h = abc => 1;

role R {
    multi method m(:$arg where %h = 'abc') { }
}
```
Then try to use the class and call a method
```
$ cat broken.p6
use C;

C.new.m();
```
Note that this works:
```
$ cat works.p6
use C;
use R;
class D does R { }
C.new.m();
```

Output:
```
$ perl6 -I. broken.p6
Cannot resolve caller AUTOGEN(C.new: ); none of these signatures match:
    (C: :$arg where { ... } = "abc", *%_)
  in block <unit> at broken.p6 line 3
$ perl6 -I. works.p6
$
```

## Environment
* Operating system: 
  OS/X
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.
```

**Comment by lizmat** [comment]
If the role and the class live in the same file, this problem does not appear to exist.  So somehow module precompilation is involved.

**Comment by jjatria** [comment]
In the example above, if the role class is modified to

``` raku
my constant HASH = %( abc => 1 );

role R {
    multi method m(:$arg where HASH = 'abc') { }
}
```

the code compiles without problems.

**Comment by lizmat** [comment]
This appears to be fixed

**Comment by bduggan** [comment]
Confirmed!  Thanks!
