### ISSUE TITLE
Cannot initialize a CUnion nested in a CStruct

### ISSUE THREAD

**Issue by moon-chilled** [rakudo/rakudo#3173]
Consider this code:

```perl6
use NativeCall;

class Nested is repr("CUnion") {
	has int32 $.int;
	has num32 $.num;
}
class Outer is repr("CStruct") {
	HAS Nested $.nested;
}

my $outer = Outer.new(nested => Nested.new(int => 7));
# fails with 'assign requires a concrete object (got a Nested type object instead)'

my $outer = Outer.new;
$outer.nested.int = 7;
# fails with 'Cannot look up attributes in a Nested type object'
```

There seems to be no way to have an instance of `Outer` with an initialized `$.nested`.

Someone on reddit said it's a problem with moar where $.nested is not connected to the right memory area--happy to redirect the report to moarvm if so.  However, there does seem to be [some code](https://github.com/MoarVM/MoarVM/blob/8622835bdf01ec01a68f9e0aee7846a9f571e90c/src/6model/reprs/CStruct.c#L283) in moar for handling an inline CUnion nested in a CStruct.

**Comment by raiph** [comment]
Perhaps same issue, simpler example:

```
class union  is repr('CUnion')  { has int $.foo }
class struct is repr('CStruct') { has union $.bar = union.new }
struct.new; # CStruct representation attribute not yet fully implemented
```

**Comment by irced** [comment]
> NativeCall currently doesn't put object members in containers, so assigning new values to them (with =) doesn't work. Instead, you have to bind new values to the private members [p6docs](https://docs.perl6.org/language/nativecall#Structs)

use NativeCall;

class Nested is repr("CUnion") {
    has int32 $!int;
    has int32 $!num;

    method int is rw {$!int}
    method int is rw {$!num}
}

class Outer is repr("CStruct") {
    HAS Nested $!nested;
    has int32 $!dummy;

    submethod TWEAK {
        $!nested := Nested.new;
    }

    method nested is rw {$!nested}
}

my $outer = Outer.new();
$outer.nested.int = 7;

sorry about the formatting, i'm new to this.

**Comment by Elronnd** [comment]
Thank you so much!

BTW, you can format code by putting \`\`\` at the beginning of your codeblock and \`\`\` again at the end.  You can also put a language name after the beginning to get syntax highlighting, like \`\`\`perl6.
