### ISSUE TITLE
42 as sum of cubes - doesn't work on Windows

### ISSUE THREAD

**Issue by scriplit** [rakudo/rakudo#3176]
## The Problem
On Windows:
>perl6 -e "say -80538738812075974³ + 80435758145817515³ + 12602123297335631³"
214281900452106748271702072587124736

## Expected Behavior
the sum of cubes should return 42

## Environment
* Operating system: 
Windows 10 (Version 1809)
* Compiler version (`perl6 -v`): 
Rakudo Star version 2019.03.1 built on MoarVM version 2019.03

## Curiosities
On the same machine:
>perl6 -e "say (−284650292555885)**3 + 66229832190556**3 + 283450105697727**3"
74
>perl6 -e "say 8866128975287528 ** 3 + (-8778405442862239) ** 3 + (-2736111468807040) ** 3"
33

These results are correct (according to [aperiodical.com](https://aperiodical.com/2019/09/42-is-the-answer-to-the-question-what-is-80538738812075974%C2%B3-80435758145817515%C2%B3-12602123297335631%C2%B3/) )

**Comment by treyharris** [comment]
You aren’t using the unicode `³` in your “same machine” examples, like you did in your first example. On Linux, I get the correct answer:

```console
$ perl6 -e "say -80538738812075974³ + 80435758145817515³ + 12602123297335631³"
42
``` 

As I do with

```console
$ % perl6 -e "say -80538738812075974**3 + 80435758145817515**3 + 12602123297335631**3"
42
```

I suggest doing an apples-to-apples comparison (using the Unicode cubing operator ³ for the other examples and using `**3` for the 42 one) and tell us what you get.

**Comment by treyharris** [comment]
(Also, are you using cmd.exe, PowerShell, Windows Terminal, bash or some other shell to run these commands?)

**Comment by scriplit** [comment]
Using the superscript or not leads to the same result. I should have said that this issue was discussed [on IRC](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-09-06#l365) a few days ago. Reproduced by 3 different users. In my case, I was entering the perl6 line in cmd.exe.

**Comment by scriplit** [comment]
I just compiled rakudo from HEAD on Windows 10, and it seems this issue is already solved:

```
c:\Work\rakudo\install>bin\perl6.exe -v
This is Rakudo version 2019.07.1-306-gfce964231 built on MoarVM version 2019.07.1-180-gcf3b545e5
implementing Perl 6.d.

c:\Work\rakudo\install>bin\perl6.exe -e "say -80538738812075974³ + 80435758145817515³ + 12602123297335631³"
42

c:\Work\rakudo\install>bin\perl6 -e "say 8866128975287528 ** 3 + (-8778405442862239) ** 3 + (-2736111468807040) ** 3"
33

c:\Work\rakudo\install>bin\perl6 -e "say (−284650292555885) ** 3 + 66229832190556 ** 3 + 283450105697727**3"
74
```
So, at least Rakudo Star version 2019.03.1 for Windows was buggy, but future versions should not. Additional tests might be needed to confirm this.

**Comment by lizmat** [comment]
Assuming fixed
