### ISSUE TITLE
12602123297335631 ** 3 not always equal to 2001387454481788542313426390100466780457779044591

### ISSUE THREAD

**Issue by scumdog** [rakudo/rakudo#3178]
## The Problem
The following calculation
12602123297335631 ** 3 
is not calculated correctly on windows (2019.03.1) , but on linux (2018.03) it is.

## Expected Behavior
12602123297335631 ** 3 => 2001387454481788542313426390100466780457779044591
## Actual Behavior
12602123297335631 ** 3 => 2001387454481789018753961193848934679938057555968
## Steps to Reproduce

#!env perl6.bat

use v6;

my $z =  12602123297335631;
my $ret = $z ** 3;
if ( $ret != 2001387454481788542313426390100466780457779044591) {
        print "#wrong:   $ret\n";
        print "#shouldbe:2001387454481788542313426390100466780457779044591\n";
} else {
        print "#Good\n";
}

#wrong:   2001387454481789018753961193848934679938057555968
#shouldbe:2001387454481788542313426390100466780457779044591

## Environment
* Operating system: 
Windows 10
* Compiler version (`perl6 -v`): 
 Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by scriplit** [comment]
It seems that this issue doesn exist anymore in rakudo@HEAD:

```c:\Work\rakudo\install>bin\perl6.exe -v
This is Rakudo version 2019.07.1-306-gfce964231 built on MoarVM version 2019.07.1-180-gcf3b545e5
implementing Perl 6.d.

c:\Work\rakudo\install>bin\perl6.exe -e "say 12602123297335631 ** 3"
2001387454481788542313426390100466780457779044591
```
see also #3176 which is a clone of this issue.

**Comment by lizmat** [comment]
Closing as this is a clone and the problem does not appear on HEAD
