### ISSUE TITLE
useless use with FIRST in while

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#3179]
## The Problem

Using a FIRST inside a while LOOP generates a warning about a useless use which seems too aggressive.

```
$ cat /tmp/fail.t
my $a=0; my $b = 3;
while $a < $b {
    FIRST $a=3;
}
$ perl6 /tmp/fail.t
WARNINGS for /tmp/fail.t:
Useless use of LOOP_BLOCK_1 symbol in sink context (line 2)
```

## Expected Behavior

No output

## Environment
* Operating system: Mac OS X 10.14.6
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1-239-g579ac66e8 built on MoarVM version 2019.07.1-134-ga37504d12

**Comment by raiph** [comment]
This looks like a "dupe" of #1900.

**Comment by dogbert17** [comment]
Given that the dupe, i.e. https://github.com/rakudo/rakudo/issues/1900, has been closed I guess we should close this one as well.

**Comment by Altai-man** [comment]
Yes, this is duplicate and can be closed. @dogbert17++ @raiph++
