### ISSUE TITLE
Classes and Roles are unable to manage object lifecycle

### ISSUE THREAD

**Issue by lembark** [rakudo/rakudo#3181]
## The Problem

add_phaser() cannot add a method call to any block which does not have the phaser defined
at compile time. Worse yet, it does not raise any exception when the call fails. For example, LEAVE is P6's standard way of managing handling objects at end-of-scope. Catch: classes or roles cannot reliably add a handler to the LEAVE of a context at runtime. Ideally this should work for 
any paser, but it is especially troublesome for LEAVE/KEEP/UNDO handling since there is no 
other effective way to handle end-of-life issues for objects.

The correct way to deal with clean-up at the end of a scope boundary 
is to specify that clean-up in a phaser. If the clean-up is 
unconditional: in a LEAVE phaser; if the clean-up should only happen 
on normal exit from a scope: in a KEEP phaser; if the clean-up should 
only happen on abnormal exit (i.e. exception throw) from a scope: in 
an UNDO phaser.

This requires manually curating the appropriate phasor:
```
    my $obj1 = MyClass.new(n=>1);   LEAVE { $obj1.clean() }
    my $obj2 = MyClass.new(n=>2);   LEAVE { $obj2.clean() }
    my $etc  = MyClass.new(n=>*);   LEAVE { $etc.clean() }
```

or

```
    my $obj1 will leave {.CLEANUP} = MyClass.new(n=>1);
    my $obj2 will leave {.CLEANUP} = MyClass.new(n=>2);
    my $etc  will leave {.CLEANUP} = MyClass.new(n=>*);
```

Catch is that this breaks encapsulation: Whomever codes the construction
of the variable must know the specifics of how it is torn down in order
to manage it.

Ideally we'd be able to define a trait for the object (e.g., via a
role):

```
    # Define an "is cleaned" trait on variables (invokes .CLEANUP)...
    multi trait_mod:<is>(Variable $v, :$cleaned! where Bool) {
        $v.block.add_phaser('LEAVE', $v.willdo({.CLEANUP}));
        $v.implicit-lexical-usage = True;
    }

    # Define an "is cleaned{...}" trait on variables 
    # (invokes specified block)...

    multi trait_mod:<is>(Variable $v, :$cleaned! where Block) {
        $v.block.add_phaser('LEAVE', $v.willdo($cleaned));
        $v.implicit-lexical-usage = True;
    }

    say 'BEFORE';
    {
        # Call the .CLEANUP method on these at end-of-scope...
        my $foo is cleaned = MyClass2.new(name=>'foo');
        my $bar is cleaned = MyClass2.new(name=>'bar');
        my $etc is cleaned = MyClass2.new(name=>'etc');

        # Execute the specified block at end-of-scope...
        my $other is cleaned{note "Final value was: $_"} = 42;

        say 'DURING';
    }
    say 'AFTER';
...

This should be handled by a class or role that provides 
auto-self-registration of new objects into LEAVE phasers, but it's 
currently impossible to register new LEAVE phasers into blocks at 
run-time, unless they already have at least one compile-time LEAVE 
phaser already declared. Here's as close as I could get:

```
    # Mix-in this role to allow objects to set provide lexical clean-ups
    # when leaving the scope in which they were created...

    role Housekeeping {
        # Abstract method; classes using this role must redefine it...
        method CLEANUP {...}

        # Sets up a LEAVE phaser in scope where ctor was called...
        submethod TWEAK () {
            # Where are we installing the new LEAVE phaser???
            my $caller = callframe(3).code;

            # Fatal if it doesn't already have a LEAVE phaser...
            die "Cannot create a housekept object of type
{self.WHAT.perl}\n"
            ~ "in this scope (scope has no predefined LEAVE phaser)"
                    unless $caller.has-phaser('LEAVE');

            # Do the installation...
            $caller.add_phaser('LEAVE', {self.CLEANUP});
        }
    }

    # Now use the role to add end-of-construction-scope clean-up to
    # a class...

    class MyClass
        does Housekeeping     # This class can now do lexical cleanups
    {
        has $.name;

        method CLEANUP {
            say "...cleaning up $.name";
        }
    }

    # Demo...

    say 'STARTING';
    {
        LEAVE {}  # This is necessary to make it work.

        my $bar = MyClass.new(name=>'bar');

        my $baz = MyClass.new(name=>'baz');

        my $qux = MyClass.new(name=>'qux');

        # Even works for objects not stored in variables
        MyClass.new(name => 'anon');

        say 'DOING';
    }

    say 'DONE'

```

**Comment by lizmat** [comment]
Feels like [`FINALIZER`](https://raku.land/zef:lizmat/FINALIZER) would be a solution for you
