### ISSUE TITLE
Reading from or writing to async sockets using Str truncates data

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3183]
This is more of a reminder for when I start focusing on async sockets for the networking grant.

## The Problem
See title. This script is what I used to test:

```perl6
use v6.d;

my Str:D    $message = 'i will face god and walk backwards into hell';
my Supply:D $server  = IO::Socket::Async.listen: 'localhost', 0;
my Tap:D    $tap     = $server.tap(-> IO::Socket::Async:D $connection {
    react whenever $connection.Supply -> Str:D $data {
        await $connection.print: $data;
        done;
    }
});

my IO::Socket::Async:D $client   =
    await IO::Socket::Async.connect: 'localhost', await $tap.socket-port;
my Str:D               $received = '';

react whenever $client.print: $message {
    whenever $client.Supply -> Str:D $data {
        $received ~= $data;
        say "Echoed: $received";
        done if $received eq $message;
    }
}

say 'Done!';
```

## Expected Behavior
It should output `Echoed: i will face god and walk backwards into hell`, then `Done!`.

## Actual Behavior
It outputs `Echoed: i will face god and walk backwards into he` and never finishes.

## Steps to Reproduce

Save the script and run it.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.6 GENERIC.MP#253 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.07.1-313-ga08dcf0036 built on MoarVM version 2019.07.1-198-gafc4be154
implementing Perl 6.d.

**Comment by ugexe** [comment]
Add a new line to your message, or use `.Supply(:bin)` + `$received ~= $data.decode;` and it'll work as expected.

**Comment by ugexe** [comment]
It isn't truncating data. The decoder is waiting to fill its buffer.

**Comment by Kaiepi** [comment]
Oh. So is this a bug or just how it's supposed to be behaving?

**Comment by ugexe** [comment]
Well, I imagine there should be some way to get the behavior you want even if it means doing something inefficient like setting an e.g. out-buffer to 1. I also expected `$client.Supply(:bin)` to fix the issue but it shows the same behavior.

**Comment by jnthn** [comment]
It's correct behavior if you're asking to receive strings; we can't know there isn't a codepoint that forms a grapheme with the last one coming next. (A newline implies a grapheme boundary.) You can use `:bin` (needed on server and client in this example), or probably use ASCII encoding instead if you know that's enough.
