### ISSUE TITLE
Performance regression in starts-with

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3185]
Found by @timo++.

Code:
```perl6
my $a; $a = $_.starts-with("1").Int for ^1_000_000; say now - INIT now
```

Rough timings on all releases: https://gist.github.com/8fb484bd265d43096c33c0886694a1a0

Previously it was around 1-2s for that code, now it's 5s and more.

Bisected: (2017-03-18) https://github.com/rakudo/rakudo/commit/8c88b0cc62ee25000603a920002d2060bdb9f5a1

**Comment by lizmat** [comment]
It appears that is not getting speshed / JITted.  A spesh log indicates a *single* BAIL for this code, and it balils on:

    # JIT: bailed completely because of <ctxouter>
    # expr bail: Cannot get template for: ctxouter

**Comment by lizmat** [comment]
Hmmm... it looks like the *proto* is not getting JITted.  So the proto is getting called a million times, instead of it getting bypassed?  Not sure what is going on here, but maybe this points to a more general problem?

**Comment by lizmat** [comment]
Yeah, a similar thing appears to be happening with e.g. `ends-with`.

**Comment by jnthn** [comment]
I'm really not a fan of the commit this bisects to, not only because flattening is bad for performance, but also because using `|c` in the signature is bad for introspection too. So anybody using introspection to explore the language, or using an IDE/editor plugin that uses that, gets much less useful information about how to call, say, `starts-with`.

**Comment by jnthn** [comment]
> using an IDE/editor plugin that uses that

And to be clear, this already exists:

![image](https://user-images.githubusercontent.com/50259/65771427-717dd180-e138-11e9-88c9-8e00e2e490ad.png)

**Comment by lizmat** [comment]
I've started reorganizing a lot of Cool / Str functions.  I will continue to do this over the weekend.  So far, `starts-with`, `ends-with`, `substr-eq`, `.contains`, `index`, `rindex`, `comb` have been done.

**Comment by lizmat** [comment]
The above benchmark is now at `0.17354853` for yours truly.

**Comment by jnthn** [comment]
Given the performance issue was fixed, I guess we no longer need this ticket.
