### ISSUE TITLE
Spectests are failing after the last NQP bump

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3191]
## The Problem

After the latest NQP bump (daaf0277e4c71f0cb82e90149b2aaf3ad102e2c5 and b55b85aefaac21d3e78aef390f03f3965e840209) `t/spec/S32-temporal/DateTime.t` is failing. Always reproducible.

Also a couple of tests are flapping. In particular:

- `t/spec/S32-list/combinations.t` – broken sort order in test 33. Sometimes passes but mostly fails
- `t/spec/S32-str/indent.t` - this one is hard to reproduce but one in a few spectest runs results in this test freezing.

## Environment
* Operating system: macOS, Linux
* Compiler version (`perl6 -v`): **HEAD** This is Rakudo version 2019.07.1-323-g1601b1fb0 built on MoarVM version 2019.07.1-219-gb2dc3f3ba

**Comment by vrurg** [comment]
For the record: reverting the above mentioned commits fixes the tests. Or, at least, `DateTime` and `combinations` are ok for enough repeated runs to conclude that they're ok.

**Comment by salortiz** [comment]
Seems that new NQP bump ( 565b2ac ) fixes this issue and the breakage in DBIish I reported.

**Comment by vrurg** [comment]
Confirm and closing the issue. Thanks!
