### ISSUE TITLE
Subclass with custom new function for positional parameters, and with no own attributes (only inherited ones through multiple(!) inheritance) initializes only the inherited attributes of the first super class, unless an empty BUILD() {} in supplied in the subclass(!)..

### ISSUE THREAD

**Issue by OndrejPopp** [rakudo/rakudo#3195]
## The Problem
See the title.
## Expected Behavior
All inherited attributes should be initalized
## Actual Behavior
See the title.
## Steps to Reproduce

The folowing code,

```
class A1
{
   has $.a1;
   method new ($a1)
   {
      return self.bless(:$a1);
   }
}

class A2
{
   has $.a2;
   method new ($a2)
   {
      return self.bless(:$a2);
   }
}

class B is A1 is A2
{
   method new ($a1, $a2)
   {
      return self.bless(:$a1, :$a2);
   }
   # submethod BUILD() {}
}

my $b = B.new("a1", "a2");
say $b;
```

With the BUILD function disabled gives the following output,
B.new(a1 => "a1", a2 => Any)
with the BUILD method enabled, the output is OK,
B.new(a1 => "a1", a2 => "a2")

Please note, it is important to place the empty BUILD method in the inheriting Subclass, so B in this example and not in A1 or A2.

## Environment
* Operating system: 
Linux Genesis 5.2.15-200.fc30.x86_64 #1 SMP Mon Sep 16 15:17:36 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.

[Bug.pl.gz](https://github.com/rakudo/rakudo/files/3642369/Bug.pl.gz)

**Comment by vrurg** [comment]
Unreproducible, everything works fine for me both with and without the `BUILD` submethod.

**Comment by OndrejPopp** [comment]
Weird.. What platform are you on? I am using the Fedora 30 package.

**Comment by jnthn** [comment]
Potentially was fixed by a855b9c06f7e271d.

**Comment by vrurg** [comment]
@OndrejPopp I can confirm for sure that 2019.07.1 doesn't have this problem whereas 2019.03.1 does actually have it.

Closing as already fixed. Anyway, thanks @OndrejPopp!

**Comment by OndrejPopp** [comment]
Ok. Thanks for your help. I will go upgrade then to the 2019.07.1
