### ISSUE TITLE
for any 1

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#3198]
## The Problem

Any `for` expression with no statement prefix and with a single junction argument produces a non-sensical result.

See https://stackoverflow.com/questions/58122017/can-gather-be-used-to-unroll-junctions

## Expected Behavior

 ```
print .^name for any 1 ; # Junction
```

or, perhaps:
```
print .^name for any 1 ; # Int
```

## Actual Behavior

 ```
print .^name for any 1 ; # Mu
```

## Environment

Rakudo 2018.12.

**Comment by raiph** [comment]
Looking at roast I see:

Tests of `for` with junctional args at https://github.com/perl6/roast/blob/master/S03-junctions/autothreading.t#L274-L288 but they don't test the value passed into the block.

A test of `for` with a junctional arg at https://github.com/perl6/roast/blob/master/S03-junctions/misc.t#L209-L219 but the test is disabled with the comment "Not sure what is expected".

A test of `for` with a junctional arg at https://github.com/perl6/roast/blob/master/S03-junctions/misc.t#L361-L371 but the test doesn't test the value passed into the block.

**Comment by lucasbuchala** [comment]
Results by release: https://gist.github.com/Whateverable/0aba2f59030c549091d58498ced0abab

Bisectable pointed to: https://github.com/rakudo/rakudo/commit/9b0b9effe5fee1f35497cf97a5e7bda9bb083507

**Comment by jnthn** [comment]
Now outputs `Junction`, and is test-covered.
