### ISSUE TITLE
LTA - "Cannot find method 'panic' on object of type QAST::MASTRegexCompiler"

### ISSUE THREAD

**Issue by holli-holzer** [rakudo/rakudo#3208]
>perl6 -e "say 'a1'.subst(/<.[\d]>/, '')"

triggers the aforementioned error. However

>perl6 -e "say 'ab'.subst(/<.[a]>/, '')"

just seems to ignore the dot.

This is an easy to occur typo on german keyboards where the . is right next to the -

In both cases there probably should be a better error message, "Illegal use of . as character class modifier, did you mean to negate (-)?" or something like that.

* Windows 10, 
* This is Rakudo version 2019.07.1-357-gd00674b31 built on MoarVM version 2019.07.1-233-g270f1b0be implementing Perl 6.d.

**Comment by jnthn** [comment]
It turns out if we actually make this an error, we will break compilation of NQP and Rakudo, which doesn't bode well for the ecosystem. For now, I've made it consistently ignore `.`. But we should probably decide whether to spec that, or whether to make it an error from 6.e onward.
