### ISSUE TITLE
LTA - No such method 'foo' for invocant of type 'Int'. Did you mean 'foo'?

### ISSUE THREAD

**Issue by holli-holzer** [rakudo/rakudo#3209]
When augmenting a class, and forgetting to ^compose one gets the aformentioned error 

    use MONKEY; 
    augment class Any { method foo() { say "foo"; } }; 
    1.foo;

That's confusing, since R. obviously knows about the method. The error could be improved to read "Uncomposed method 'foo' called for invocant of type 'Int'. Did you forget to ^compose?" or something similar.

## Environment
* Operating system: 
* This is Rakudo version 2019.07.1-357-gd00674b31 built on MoarVM version 2019.07.1-233-g270f1b0be implementing Perl 6.d.

**Comment by lizmat** [comment]
The problem has 2 causes:

    1. Parent classes do *not* know which child classes they have (classes only know their parents).
    2. `1` is not an `Any`, but an `Int`, which is a child class of `Any`.

Since the `Int` class has been composed already by the time the augment of the `Any` class happens, it does not see the new method added to `Any`.  If you however would compose the `Int` class manually, then it *does* work:

    use MONKEY;
    augment class Any { method foo() { say "foo"; } };
    BEGIN Int.^compose;
    1.foo;  # foo

It is planned to somehow support classes knowing which child classes they have.  Until then, you will have to manually `^compose` child classes when augmenting a parent class.

**Comment by holli-holzer** [comment]
I know it works when you call `compose`, that's not the point. I'm fine with that.

My concern is with the error message. The compiler obiously knows about "foo" or else it could not mention it ( "Did you mean 'foo' ). So if it sees the method, but knows it cannot call it, why not tell the user? ("Did you forget to call 'compose'?" )

**Comment by lizmat** [comment]
Ah, ok.  Hmmm...

    use MONKEY;
    augment class Any { method foo() { say "foo"; } };
    .name.say for 1.^methods(:all).grep( *.name eq "foo" );  # foo

So, the error reporting is using `.^methods(:all)` to levenshtein the suggestions out of.  But perhaps this shouldn't be an error at all then?  Perhaps the runtime should not throw immediately, but instead do a more thorough search of the method name, and call any method found (plus a `.^compose` of the class of the object) and only throw an exception if it didn't find it?
