### ISSUE TITLE
MMD in role not working with natives

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3210]
## The Problem

    role A { multi method a(::?ROLE:U: int $b) { 1 }; multi method a(::?ROLE:D: int $b) { 2 } }; class B does A { };  dd B.a(1)
    Cannot resolve caller a(B:U: Int:D); none of these signatures match:
        (A:U: int $b, *%_)
        (A:D: int $b, *%_)

versus:

    role A { multi method a(::?ROLE:U: Int:D $b) { 1 }; multi method a(::?ROLE:D: Int:D $b) { 2 } }; class B does A { };  dd B.a(1)
    1

## Expected Behavior

    role A { multi method a(::?ROLE:U: int $b) { 1 }; multi method a(::?ROLE:D: int $b) { 2 } }; class B does A { };  dd B.a(1)
    1

This appears to have been an issue since at least Christmas.

**Comment by jnthn** [comment]
You're not passing a native int here:

`dd B.a(1)`

If you do so, then you'll get a match:

`role A { multi method a(::?ROLE:U: int $b) { 1 }; multi method a(::?ROLE:D: int $b) { 2 } }; class B does A { };  dd B.a(my int $ = 1)
1`
