### ISSUE TITLE
Attributes can't be used in submethods with $.

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3222]
# The Problem

If an attribute is referenced in a submethod with `$.` the compilation fails with:

```
Virtual method call $.a may not be used on partially constructed object (maybe you mean $!a for direct attribute access here?)
```

## Expected Behavior

`$.a` must be allowed for any submethod except for `BUILD` and perhaps `BUILDALL` if declared as submethod. 

I doubt if `TWEAK` should be limited in using `$.` as it's being called after the `BUILD` has completed and installed all the accessors. But this is yet to be tested.

## Steps to Reproduce

Both sample fail to compile:

```
role R { has $.a; submethod foo { $.a } }
```
```
class C { has $.a; submethod foo { $.a } }
```

**Comment by jnthn** [comment]
I'm pretty sure this was intended as a general behavior in submethods, given that they themselves are not inherited. The rule also applies in attribute initializers.

A `TWEAK` exception also makes no sense, since child class' `BUILD`s run after the current class' `TWEAK`.

**Comment by vrurg** [comment]
But then:

```
role R { submethod foo { self.a } }

```

Must not work too. But it does.

With regard to `TWEAK` – it must not know about its children classes. All it must care about is its own and, perhaps, parent class attributes. So, there must be no side effects.

**Comment by vrurg** [comment]
BTW, for the record:

```
role R { has $.a; method foo { $.a } }; R.foo
```

results in:

```
Invocant of method 'a' must be an object instance of type 'Mu', not a type object of type 'R'.  Did you forget a '.new'?
```

**Comment by vrurg** [comment]
And, after all, experimental code passes all tests and spectests flawlessly. I'm about to make a PR and see how it goes.

**Comment by jnthn** [comment]
> Must not work too. But it does.

Yes, this is deliberate, and indeed the "escape hatch" for if one does (think they) know what they're doing. The point of the design is to try and prevent accidents in state access in `submethod`s, which should almost always be using the `$!foo` form.

> I'm about to make a PR and see how it goes.

Nowhere if it changes this behavior.

**Comment by vrurg** [comment]
Ok, before closing the ticket, what does _state access_ means in this context? I can't google anything useful.

**Comment by jnthn** [comment]
From very early on in the language design, it's been that `has $!foo` declares an attribute (that is, part of the state of the class), and a declaration like `has $.foo;` really means `has $!foo; method foo() { $!foo }` (so it again declares state). Similarly, `$.foo` as a usage means `$(self.foo)`; there's nothing that ties its usage to an attribute.

At some point, there was a discussion about being able to conveniently call methods on `self`; there was a proposal for a `./foo` syntax as a shortcut for `self.foo`. That didn't happen, but the resolution was to allow `$.foo` to be followed by an argument list, so it could be used to call methods more generally (however, note that it implies itemization of the return value).

While that means that `$.foo` and friends are, therefore, a general way to call methods on `self`, the vast majority of their practical usage is to access an attribute through an accessor. It's easy for those learning Perl 6 to fall into the trap of thinking that if it's declared `has $.foo`, then it should be accessed as `$.foo`, whereas in reality `$!foo` would be far more appropriate most of the time. Heck, even those of us who know this very well can have a thinko.

In some contexts where it's very unlikely that virtual dispatch was really intended, we choose to call this out. Those include attribute initializers and `submethod`s. The most common use of `submethod`s is `BUILD`, `TWEAK`, and `DESTROY`, but given `submethod`s aren't inherited (a general property), it would be very odd to have a `submethod` that wanted to access the state (attributes) of the object via. a virtual call.

**Comment by vrurg** [comment]
Now it makes clear sense. Thanks Jonathan! 

Funny that similar thought did cross my mind but I rejected it as insignificant.

With regard to use of `$!foo` in normal practice: books and docs are using `$.foo` most of the time.
