### ISSUE TITLE
missing info when a module is not found

### ISSUE THREAD

**Issue by MARTIMM** [rakudo/rakudo#3238]
## The Problem

I've seen a LTA error message when some module is not found. It only presents a line number but not the source file where it is 'use'd.

E.g.

running a Perl program

```
===SORRY!===
Could not find Gnome::Gtk3::ImageMenuItem at line 18 in:
file#/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/lib
    file#/home/marcel/Languages/Perl6/Projects/gtk-v3/lib
    file#/home/marcel/Languages/Perl6/Projects/gtk-glade/lib
    file#/home/marcel/Languages/Perl6/Projects/Library/lib
    inst#/home/marcel/.perl6
    inst#/mnt/Data/opt/Perl6/rakudo/install/share/perl6/site
    inst#/mnt/Data/opt/Perl6/rakudo/install/share/perl6/vendor
    inst#/mnt/Data/opt/Perl6/rakudo/install/share/perl6/core
    ap#
    nqp#
    perl5#
```

The project I'm working on is somewhat large and consists of many files. Grep didn't do it for me and also the search in the atom editor did not help me out. What the possible cause could be is a `require ::($x)` somewhere, where this name is not visible, so I'd rather see a module/program name along with the line number.

In the end it was caused by a `use lib` statement pointing to old software. If I looked better I could have seen it in the list, `gtk-v3`, `gtk-glade` but it didn't ring a bell.

## Expected Behavior
I'd like to see a module/file name along with the line number

## Actual Behavior
list of where rakudo has searched for module starting with an error message and line number.

## Environment
* Operating system (uname -a): Linux h03-fedora 5.2.17-100.fc29.x86_64 #1 SMP Mon Sep 23 14:09:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1-417-g051638d5a built on MoarVM version 2019.07.1-249-g01f85c8bf
implementing Perl 6.d.

**Comment by ugexe** [comment]
https://github.com/rakudo/rakudo/issues/2022

**Comment by coke** [comment]
#2022 is a duplicate - looks like the issue was fixed and needs tests to be closed.
