### ISSUE TITLE
Empty #| cause compilation error

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3242]
# The Problem

    #| foo
    #|
    #| bar

now causes compilation error:

    ===SORRY!=== Error while compiling /Users/liz/Github/rakudo.moar/foo
    Opening bracket required for #| declarator block
    at /Users/liz/Github/rakudo.moar/foo:2
    ------> #|⏏ 

It didn't before.  Probably related to recent pod handling changes by Tom Browder.

This is breaking Raku code in production  :-(

**Comment by AlexDaniel** [comment]
Reverted in https://github.com/rakudo/rakudo/commit/9f1794cf36, I guess there are no tests for this?

**Comment by tbrowder** [comment]
On Fri, Oct 18, 2019 at 08:43 Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> Reverted in 9f1794c <https://github.com/rakudo/rakudo/commit/9f1794cf36>,
> I guess there are no tests for this?
>

I have not yet added any, but I think @lizmat did.

**Comment by lizmat** [comment]
Yes, I've added a single test, so closing for now
