### ISSUE TITLE
Windows NativeCall regression 

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#3247]
https://ci.appveyor.com/project/rakudo/rakudo/history

**Comment by ugexe** [comment]
Looks like its new tests that don't work right on windows.

**Comment by AlexDaniel** [comment]
So that it's not lost later after more commits are added, this is the commit that seems to be the culprit according to the link above: https://github.com/rakudo/rakudo/commit/e45bb3418d5f3964907739e916e95078e6e09995

**Comment by niner** [comment]
Fixed in commit 7dc34148eb7fb2d614214bfa9a110833c42730fb
