### ISSUE TITLE
Regression introduced with new moarvm expr templates

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3256]
See https://colabti.org/irclogger/irclogger_log/moarvm?date=2019-10-21#l43

No moarvm ticket yet.

**Comment by bdw** [comment]
I can't assign this to myself for reasons?

**Comment by AlexDaniel** [comment]
@bdw that's right, because rakudo is in its own organization which makes it mildly painful when it comes to anything.

See https://github.com/perl6/problem-solving/issues/46, and maybe also https://github.com/perl6/problem-solving/issues/124.

> various projects are managed in somewhat different ways and have rather different commit policies. For example, the Perl 6 org is very liberal, Rakudo is guarded by CLA + other contributors are happy with the commit bit being given out (we never really formalized the second part of that), and MoarVM's policy is "whoever jnthn feels comfortable having a commit bit". :-)

Did you sign a CLA?

**Comment by bdw** [comment]
Didn't, not interested in doing so at the moment

**Comment by AlexDaniel** [comment]
Should be fixed with https://github.com/MoarVM/MoarVM/commit/97e26c0186 https://github.com/MoarVM/MoarVM/commit/d5f5185b2e, thanks @bdw++!

The golf of this issue [comes from the spectest](https://colabti.org/irclogger/irclogger_log/moarvm?date=2019-10-21#l188), so I don't think there's a need to add more tests.
