### ISSUE TITLE
calculation of argument done even when method not available

### ISSUE THREAD

**Issue by MARTIMM** [rakudo/rakudo#3259]
## The Problem
In the following line
```
$my-object.?"my-method"(some-complex-argument-calculation());
```
the function `some-complex-argument-calculation()` is executed even when the method `my-method` is not defined.

## Expected Behavior
The availability of the method `my-method` must be checked first before handling any of the arguments.

## Actual Behavior
The compiler calls `some-complex-argument-calculation()` before seeing that the method is not available.

## Environment
* Operating system (uname -a): Linux h03-fedora 5.2.17-100.fc29.x86_64 #1 SMP Mon Sep 23 14:09:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1-446-g2eca09a74 built on MoarVM version 2019.07.1-279-g0aa43a983
implementing Perl 6.d.

**Comment by vendethiel** [comment]
Well.. You can't - in general - know if the method is available or not without building a Signature object. I suppose in cases there's no possible candidates it could figure out it earlier, but that means `finding candidates -> evaluating arguments -> match the candidate -> call fn`.
That'd also mean, for some crazy reason (that hopefully won't ever happen), in `$a.f(g);`, that `g` could add `$a.f` (I really hope there's no such code).

**Comment by MARTIMM** [comment]
At the moment I have to work like below
```
if $my-object.^can("my-method") {
  $my-object."my-method"(some-complex-argument-calculation());
}
```
Here there is a check whithout needing the signature, so... there is a way

**Comment by Altai-man** [comment]
>Here there is a check whithout needing the signature

But what about:

```
class A { method m(Int $a) { say $a + 1 } }
A.^can('m'); # <- yes, it can!
A."m"('hehe') # <- oops, it can't
```

?

We can detect presence of a method with a given name, but no guarantees it'll work, just its name.

**Comment by vrurg** [comment]
My five cents: `FALLBACK`:

```
class Foo {
    method FALLBACK( $name, Int $n where * < 10 ) {
        say "FALLBACK ON {$name}($n)";
    }
}

say so Foo.^can("foo"); # False
Foo.new.?"foo"(5);
Foo.new.?"foo"(10);
```

The second case would be a error. In the following case it would even be harder to understand what's going on (not recommended for real life use):

```
class Foo {
    submethod FALLBACK( $name, |args(Int $n) ) is hidden-from-backtrace {
        X::Method::NotFound.new(:method($name), :typename(self.WHAT.^name)).throw
            if $n >= 10;
        say "FALLBACK ON {$name}($n)";
    }
}

Foo.new.?"foo"(5);
Foo.new.?"foo"(10);
```

This code results in:

```
FALLBACK ON foo(5)
No such method 'foo' for invocant of type 'Foo'
  in block <unit> at fallback-2.p6 line 13
```

I think this issue can be closed.
