### ISSUE TITLE
Breaking async socket changes

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3262]
Currently, rakudo does not pass these test files on 6.d-errata branch:
* S32-io/IO-Socket-Async-UDP.t 
* S32-io/IO-Socket-Async.t 

The tests were tweaked in roast master:
https://github.com/perl6/roast/commit/9513102a53896779c216bb716a127d59c6e2a5d5

I'm not willing to cherry-pick this commit yet. I think there's nothing obviously wrong with using ‘localhost’, and there could be code out there using it.

IRC discussion: https://colabti.org/irclogger/irclogger_log/raku-dev?date=2019-10-23#l142

Ping @Kaiepi

**Comment by AlexDaniel** [comment]
I think the options are:
* Make it just work
* Introduce backward compatibility so that the change only affects those who `use v6.e`

However, feel free to prove me wrong, I don't know enough about the issue.

**Comment by jnthn** [comment]
I'm also a bit dubious about that change; I know that `localhost` can resolve to multiple things, but shouldn't the one it picks be consistent on the client and server side?

**Comment by jnthn** [comment]
And yes, I'm almost certain this change will have real-world fallout, if it regresses the tests.

**Comment by Kaiepi** [comment]
> I'm also a bit dubious about that change; I know that localhost can resolve to multiple things, but shouldn't the one it picks be consistent on the client and server side?
`0.0.0.0` represents any given local IPv4 address here. When connecting with `127.0.0.1`, connections will get accepted on that address, but this should've been done explicitly.

> And yes, I'm almost certain this change will have real-world fallout, if it regresses the tests.
On top of that, the way we handle DNS resolution using all addresses rather than the first isn't compliant with RFC 8305, so it's not something that I think should be included in the release either. My apologies, this was not something I had done enough research with before implementing.

**Comment by niner** [comment]
On Donnerstag, 24. Oktober 2019 14:11:48 CEST Ben Davies wrote:

> On top of that, the way we handle DNS resolution using all addresses rather
> than the first isn't compliant with RFC 8305, so it's not something that I
> think should be included in the release either. My apologies, this was not
> something I had done enough research with before implementing.

It's just as much my fault. I've been aware of the Happy Eyeballs algorithm 
standardised in RFC 8305, but I couldn't remember the name and only yesterday 
spent the time to look it up. Sorry for wasting your time this way!

**Comment by AlexDaniel** [comment]
It is also my fault because I didn't notice it earlier, and I should have. Even though this test failure does not happen on every system, it definitely happens on mine.

**Comment by AlexDaniel** [comment]
The changes were reverted, so it shouldn't be an issue now. Thanks!
