### ISSUE TITLE
Dynamic variables set via PROCESS:: doesn't have .dynamic set in their container.

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3270]
## The Problem

If a dynamic variable is set via `PROCESS::` package its container doesn't have `.dynamic` set to _True_

## Steps to Reproduce

```
PROCESS::<$v> = 1;
PROCESS::<%a> = [];
$*v.VAR.dynamic.say; # False
%*a.VAR.dynamic.say; # False
```

**Comment by jnthn** [comment]
Why would it?

**Comment by vrurg** [comment]
PseudoStash pseudo-packages marked with `REQUIRE_DYNAMIC` flag check if the symbol they found is actually a dynamic. That wasn't a problem when `DYNAMIC::` lookup didn't use `PROCESS::`. Now, as I'm experimentally made it use `&DYNAMIC` the following:

```
PROCESS::<$foo> = 1; say DYNAMIC::<$*foo>
```

throws `X::Caller::NotDynamic`. Actually, this could be workarounded by checking twigil. And it will be to handle cases of binding:

```
PROCESS::<$foo> := 1;
my $v = 42;
PROCESS::<$bar> := $v; # Dynamic must not be set.
```

But for common consistency I think `Scalar`s produced by an assignment must have the flag on.

**Comment by jnthn** [comment]
> PseudoStash pseudo-packages marked with REQUIRE_DYNAMIC flag check if the symbol they found is actually a dynamic. 

It should only enforce that when visiting the caller chain; the `GLOBAL` and `PROCESS` fallbacks do not need this check.

**Comment by vrurg** [comment]
The pieces of code where the check is done are basically agnostic of where a symbol comes from. Thus, special handling of `GLOBAL` and `PROCESS` would require additional flags and checks. I'm not sure which approach is worse: those checks in `PseudoStash`, or additional (very simple) method `ASSIGN-KEY` in `Stash`:

```
    method ASSIGN-KEY(|) is raw {
        my $cont := callsame;
        nqp::if(
            $!is-dynamic,
            nqp::stmts(
                (my $desc := nqp::getattr(nqp::decont($cont.VAR), Scalar, '$!descriptor')),
                nqp::if(
                    nqp::isconcrete($desc),
                    nqp::bindattr_i(
                        $desc,
                        ContainerDescriptor,
                        '$!dynamic',
                        1
                    )
                )
            )
        );
        $cont
    }
```

**Comment by vrurg** [comment]
This issue doesn't worth being kept open. If similar one is ever opened it would most likely have different reasoning and perspective.

Closing for now.
