### ISSUE TITLE
slow raku regex matches

### ISSUE THREAD

**Issue by wtwt5237** [rakudo/rakudo#3281]
## The Problem
I have a simple raku script that parses a flat file. It involves several regex matches (embedded in loops). I found that the regex matches are very slow

Please see the benchmark section of my github repo: https://github.com/wtwt5237/perl6-for-bioinformatics

I used perl5 to solve the same problem, and it took 0.195s, while raku is taking more than 6s. I profiled the codes a little bit, and found that 4s are spent on doing regex matches

the flat file (a sam format file) and the raku and perl5 scripts can be found in the "Come on, sister" folder.

## Steps to Reproduce
Please download the test1.sam file and run

```shell
time perl benchmark.pl test1.sam
time perl6 benchmark.p6 --sam_file=test1.sam
```

## Environment
* Operating system: redhat 7.4
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
So I did a rough benchmark across releases using whateverable ([runnable gist](https://gist.github.com/AlexDaniel/e1118542a47aa7a53576e37e7c55c13a)):

```
¦«2015.12,2016.01.1,2016.02,2016.03,2016.04,2016.05,2016.06,2016.07.1,
  2016.08.1,2016.09,2016.10,2016.11,2016.12,2017.01,2017.02,2017.03,
  2017.04.3,2017.05,2017.06»:
«timed out after 10 seconds» «exit signal = SIGHUP (1)»
¦«2017.07»:       9.6884009
¦«2017.08»:       8.81022353
¦«2017.09»:       8.72356533
¦«2017.10»:       8.5067019
¦«2017.11»:       8.56042001
¦«2017.12»:       8.45787879
¦«2018.01»:       8.21402332
¦«2018.02.1»:     8.1513578
¦«2018.03»:       8.1069349
¦«2018.04.1»:     7.82542269
¦«2018.05»:       7.2934323
¦«2018.06»:       7.054478
¦«2018.08»:       7.3682121
¦«2018.09»:       7.2133363
¦«2018.10»:       7.3709767
¦«2018.11»:       6.5194245
¦«2018.12»:       6.6024234
¦«2019.03.1»:     6.778443
¦«2019.07.1»:     5.7278661
¦«HEAD(1d84c64)»: 5.72919022
```

So it's getting faster almost every release, but it seems there will be no change in the upcoming 2019.11 release. 

@jnthn perhaps it's worth trying to run this with your unmerged changes? I wonder how it's going to affect this benchmark, if at all.

Ping @lizmat, maybe you can shave a few % too :)

**Comment by wtwt5237** [comment]
great folks! thanks a lot! hope raku gets better and better soon!

**Comment by AlexDaniel** [comment]
Hold on, I think @lizmat was trying out some improvements to make this benchmark faster.

@lizmat please close if that's not the case.

**Comment by lizmat** [comment]
I've posted my improvements as a PR in @wtwt5237 's repository.  So I think the ticket can be closed here?
