### ISSUE TITLE
where is zef?

### ISSUE THREAD

**Issue by wtwt5237** [rakudo/rakudo#3285]
## The Problem
I apologize if I am missing something obvious, but I can't seem to find zef for installing packages?

This is under my /bin/ folder:

[twang6@Nucleus005 bin]$ ls -1
moar
nqp
nqp-m
perl6
perl6-debug
perl6-debug-m
perl6-gdb-m
perl6-lldb-m
perl6-m
perl6-valgrind-m

## Environment
* Operating system: redhat
* Compiler version (`perl6 -v`): 6.d.

**Comment by vrurg** [comment]
How did you install rakudo? If from a package then most likely you need to look for zef package too.

**Comment by wtwt5237** [comment]
thanks!

I installed the 2019.07.1 version (https://github.com/rakudo/rakudo/releases) by: 

perl Configure.pl --gen-moar --make-install --prefix ~/rakudo

Could you please elaborate on "If from a package then most likely you need to look for zef package too."?

**Comment by AlexDaniel** [comment]
@wtwt5237 zef is a separate piece of software. If you're installing rakudo from source, then you need to install zef by following the instructions here: https://github.com/ugexe/zef. If you were using distro packages, then usually there'd be two separate packages (`rakudo` and `perl6-zef`, or similar). If, however, you were to install [Rakudo Star](https://rakudo.org/files), then it'd come bundled with zef.

Just as an interesting fact, it seems that there's an alternative to zef in the works: https://github.com/hythm7/Pakku

**Comment by hythm7** [comment]
I think we need to have a recommended way for installing Raku, which should be clear and easy, specially for new people who want to try Raku. Then add it to `raku.org` website. I'm aware that `raku.org` has installation instruction from source, and installing Rakudostar. but this still doesn't answer questions like the one in this issue. IMO the easiest way (and that is probably subjective) is installing Raku via `rakudodbrew`, since it has clear instructions for installing Raku on the main operating systems, as well as installing zef. and from there any module can be installed.

**Comment by patzim** [comment]
I hope we'll soon provide precompiled monthly(?) releases of rakudo + zef. These might also tick the "clear and easy" box.
(Teaser: I plan to enable rakudobrew to install these precompiled releases, so rakudobrew users don't necessarily need to compile.)

**Comment by wtwt5237** [comment]
@AlexDaniel 

Thanks!  https://github.com/ugexe/zef worked for me

**Comment by wtwt5237** [comment]
@hythm7 and @patzim 

I may not be using rakudobrew in the correct way? I got the following error

```shell
[twang6@Nucleus005 ~]$ git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
[twang6@Nucleus005 ~]$ export PATH=~/.rakudobrew/bin:$PATH
[twang6@Nucleus005 ~]$ rakudobrew init # Instructions for permanent installation.
# Load rakudobrew automatically by adding
#   eval "$(/home2/twang6/.rakudobrew/bin/rakudobrew init <Bash|Fish|Sh|Zsh>)"
# to your local profile file.
# (often ~/.bash_profile, ~/.zsh_profile or ~/.profile)
# This can be easily done using:

echo 'eval "$(/home2/twang6/.rakudobrew/bin/rakudobrew init <Bash|Fish|Sh|Zsh>)"' >> ~/.profile

# On Fish:

echo '/home2/twang6/.rakudobrew/bin/rakudobrew init Fish | source' >> ~/.config/fish/config.fish

[twang6@Nucleus005 ~]$ echo 'eval "$(/home2/twang6/.rakudobrew/bin/rakudobrew init <Bash|Fish|Sh|Zsh>)"' >> ~/.bash_profile 
[twang6@Nucleus005 ~]$ source .bash_profile 
-bash: command substitution: line 55: syntax error near unexpected token `)'
-bash: command substitution: line 55: `/home2/twang6/.rakudobrew/bin/rakudobrew init <Bash|Fish|Sh|Zsh>)"'
```
Any suggestions?

**Comment by hythm7** [comment]
@wtwt5237 T IIRC it is 
```echo 'eval "$(/home2/twang6/.rakudobrew/bin/rakudobrew init Bash)"'```

You may need to remove line 55 from .bash_profile

**Comment by wtwt5237** [comment]
@hythm7 

works, thanks! weird, I did try this (Bash) yesterday and it didn't work. today it works

Tao
