### ISSUE TITLE
need suggestions with reading text files by every n-th line

### ISSUE THREAD

**Issue by wtwt5237** [rakudo/rakudo#3290]
## The Problem
Could someone please give me some suggestions on how I can read text files by every n-th file? 

This is in reference to my prior question at #3281, where I got great suggestions from lizmat about how to speed up reading a text file (a SAM format file from bioinformatics research) by every line, by using "IO.lines". But in bioinformatics, sometimes we have more complicated situations, such as Fastq files, which store data in groups of 4 lines at a time. Even more, these Fastq files come in pairs. So if we need to parse such files, we may need to do something like reading 4 lines from the first Fastq file, and reading 4 lines from the second Fastq file, then read the next 4 lines from the first Fastq file, and then read the next 4 lines from the second fastq file, ...... 

May I have some suggestions regarding what is the best way to approach this problem? @lizmat,  may I have your advice again?

Example:

```shell
[twang6@Nucleus005 KC00004-N1-B2A]$ zcat 191025_X250_FCHT5HMDSXX_L1_HUMrefEAAAEAAA-90_1.fq.gz | head -n 8
@A00250:188:HT5HMDSXX:1:1101:11397:1313 1:N:0:GTCCAGAA
ATCCACTTGACATACACTATTGAAGGAAGTTTAAAGCTTATCTACAAACTCTGCTTTCTACACAGTCACCTTTCTTTATATTAGCATCAAATAAGATCAATTTGAGCACTAATCTCTAGGGGAAGAAATGTTGTTCTTGACACAAGATCG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF:FF
@A00250:188:HT5HMDSXX:1:1101:11867:1313 1:N:0:GTCCAGAA
GCGTCACGCAAGGGCGCGAGAGCTGCTCCTGCTGGGTGTAGGCAGTGAGGCCGTGCGGGCAGAGCTGGAGGAGATCACAGGCAGCCCAAAGCATGTGATGGTCTACTCGGATCCTCAGGATCTGTTCAACCAAATCCCTGAGCTGCAGGG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[twang6@Nucleus005 KC00004-N1-B2A]$ zcat 191025_X250_FCHT5HMDSXX_L1_HUMrefEAAAEAAA-90_2.fq.gz | head -n 8                                                                                                        
@A00250:188:HT5HMDSXX:1:1101:11397:1313 2:N:0:GTCCAGAA
TGTGTCAAGAACAACATTTCTTCCCCTAGAGATTAGTGCTCAAATTGATCTTATTTGATGCTAATATAAAGAAAGGTGACTGTGTAGAAAGCAGAGTTTGTAGATAAGCTTTAAACTTCCTTCAATAGTGTATGTCAAGTGGATAGATAG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF
@A00250:188:HT5HMDSXX:1:1101:11867:1313 2:N:0:GTCCAGAA
GTCAGGCACTGGGACCTTACCTGGCCGCTGCCGGCTGCACAGCTTCCCCTGCAGCTCAGGGATTTGGTTGAACAGATCCTGAGGATCCGAGTAGACCATCACATGCTTTGGGCTGCCTGTGATCTCCTCCAGCTCTGCCCGCACGGCCTC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

Thanks!

Tao

**Comment by lizmat** [comment]
This is not really a Rakudo problem, rather than a question.  This is more appropriately asked on [StackOverflow](https://stackoverflow.com/questions/tagged/raku).  Please ask your question there, and I will give an extensive answer (which I'm already preparing).

**Comment by lizmat** [comment]
for zip @filenames.map: *.IO.lines.rotor(4, :$partial) {
    # expect ((a,b,c,d),(e,f,g,h),(i,j,k,l))
}

**Comment by lizmat** [comment]
Closing ticket now, as a solution has been provided.  But please ask these kind of questions on StackOverflow or such.  Thank you!

**Comment by wtwt5237** [comment]
Thanks, @lizmat!

I have posted the question here: https://stackoverflow.com/questions/58776407/need-suggestions-with-reading-text-files-by-every-n-th-line-in-raku-perl6

I noticed what you typed above:

```raku
for zip @filenames.map: *.IO.lines.rotor(4, :$partial) {
    # expect ((a,b,c,d),(e,f,g,h),(i,j,k,l))
}
```

So this has handled the situation of reading one file, but doesn't seem to have solved the problem of reading two files in parallel?

**Comment by lizmat** [comment]
> On 9 Nov 2019, at 05:31, Tao Wang <notifications@github.com> wrote:
> I have posted the question here: https://stackoverflow.com/questions/58776407/need-suggestions-with-reading-text-files-by-every-n-th-line-in-raku-perl6
> 
> I noticed what you typed above:
> 
> for zip @filenames.map: *.IO.lines.rotor(4, :$partial) {

Oops, that should read ":partial"

>     # expect ((a,b,c,d),(e,f,g,h),(i,j,k,l))
> }
> 
> So this has handled the situation of reading one file, but doesn't seem to have solved the problem of reading two files in parallel?

No, this handles N files, depending on number of files in @filenames.
