### ISSUE TITLE
error installing Math::Matrix

### ISSUE THREAD

**Issue by wtwt5237** [rakudo/rakudo#3294]
## The Problem
Could someone please help me with this error message that happened when I installed Math::Matrix?

```
[twang6@Nucleus005 script]$ zef install Math::Matrix
===> Searching for: Math::Matrix
===> Searching for missing dependencies: AttrX::Lazy, Test::META
===> Searching for missing dependencies: META6, URI, License::SPDX
===> Searching for missing dependencies: JSON::Class, JSON::Class:ver<0.0.5+>, JSON::Fast
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
===> Testing: AttrX::Lazy:ver<0.0.3>
===> Testing [OK] for AttrX::Lazy:ver<0.0.3>
===> Testing: JSON::Fast:ver<0.10>
===> Testing [OK] for JSON::Fast:ver<0.10>
===> Testing: JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
===> Testing: JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
===> Testing: JSON::Unmarshal:ver<0.08>
===> Testing [OK] for JSON::Unmarshal:ver<0.08>
===> Testing: JSON::Class:ver<0.0.13>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for JSON::Class:ver<0.0.13>:auth<github:jonathanstowe>:api<1.0>
===> Testing: META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
===> Testing: URI:ver<0.3.0>
===> Testing [OK] for URI:ver<0.3.0>
===> Testing: License::SPDX:ver<3.7.0>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for License::SPDX:ver<3.7.0>:auth<github:jonathanstowe>:api<1.0>
===> Testing: Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
[Test::META] # the following may make some diagnostics from the module itself
===> Testing [OK] for Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
===> Testing: Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier>
**[Math::Matrix] Cannot modify an immutable Rat (3.142857)
[Math::Matrix]   in block  at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 633
[Math::Matrix]   in method LU-decomposition at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 627
[Math::Matrix]   in block <unit> at t/041-decomposition.t line 26
[Math::Matrix]     # You planned 16 tests, but ran 4
===> Testing [FAIL]: Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier>
Aborting due to test failure: Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier> (use --force-test to override)**
```

Or maybe I can safely ignore by using "--force-test"?

## Environment
* Operating system: redhat 7.4
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.

**Comment by wtwt5237** [comment]
To follow up, I tried --force-test to override, but got another error:

[twang6@Nucleus005 script]$ zef install --force-test Math::Matrix
===> Searching for: Math::Matrix
===> Searching for missing dependencies: AttrX::Lazy, Test::META
===> Searching for missing dependencies: META6, URI, License::SPDX
===> Searching for missing dependencies: JSON::Class, JSON::Class:ver<0.0.5+>, JSON::Fast
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
===> Testing: AttrX::Lazy:ver<0.0.3>
===> Testing [OK] for AttrX::Lazy:ver<0.0.3>
===> Testing: JSON::Fast:ver<0.10>
===> Testing [OK] for JSON::Fast:ver<0.10>
===> Testing: JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
===> Testing: JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
===> Testing: JSON::Unmarshal:ver<0.08>
===> Testing [OK] for JSON::Unmarshal:ver<0.08>
===> Testing: JSON::Class:ver<0.0.13>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for JSON::Class:ver<0.0.13>:auth<github:jonathanstowe>:api<1.0>
===> Testing: META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
===> Testing: URI:ver<0.3.0>
===> Testing [OK] for URI:ver<0.3.0>
===> Testing: License::SPDX:ver<3.7.0>:auth<github:jonathanstowe>:api<1.0>
===> Testing [OK] for License::SPDX:ver<3.7.0>:auth<github:jonathanstowe>:api<1.0>
===> Testing: Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
[Test::META] # the following may make some diagnostics from the module itself
===> Testing [OK] for Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
===> Testing: Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier>
[Math::Matrix] Cannot modify an immutable Rat (3.142857)
[Math::Matrix]   in block  at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 633
[Math::Matrix]   in method LU-decomposition at /home2/twang6/.zef/store/Perl6-Math-Matrix.git/f1d54489e787d8b5f440d3cf094c71faabc07533/lib/Math/Matrix.pm6 (Math::Matrix) line 627
[Math::Matrix]   in block <unit> at t/041-decomposition.t line 26
[Math::Matrix]     # You planned 16 tests, but ran 4
===> Testing [FAIL]: Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier>
[Math::Matrix] Failed to get passing tests, but continuing with --force-test
===> Installing: AttrX::Lazy:ver<0.0.3>
===> Installing: JSON::Fast:ver<0.10>
===> Installing: JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
===> Installing: JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
===> Installing: JSON::Unmarshal:ver<0.08>
===> Installing: JSON::Class:ver<0.0.13>:auth<github:jonathanstowe>:api<1.0>
===> Installing: META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
===> Installing: URI:ver<0.3.0>
===> Installing: License::SPDX:ver<3.7.0>:auth<github:jonathanstowe>:api<1.0>
===> Installing: Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
===> Installing: Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier>
**===> Install [FAIL] for Math::Matrix:ver<0.3.8>:auth<github:pierre-vigier>: ===SORRY!===
Could not find Math::Matrix::Type at line 2 in:
    inst#/home2/twang6/software/languages/raku/share/perl6/site
    inst#/home2/twang6/software/languages/raku/share/perl6/vendor
    inst#/home2/twang6/software/languages/raku/share/perl6/core
    ap#
    nqp#
    perl5#

===SORRY!===
Could not find Math::Matrix::Type at line 2 in:
    inst#/home2/twang6/software/languages/raku/share/perl6/site
    inst#/home2/twang6/software/languages/raku/share/perl6/vendor
    inst#/home2/twang6/software/languages/raku/share/perl6/core
    ap#
    nqp#
    perl5#**

**Comment by dogbert17** [comment]
Quite some time has passed since this was reported and now it seems to work, at least on my system:

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-92-g6e6c9e5cc.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-20-gf99bc2ce7.
    dogbert@dogbert-VirtualBox:~$ zef install Math::Matrix
    ===> Searching for: Math::Matrix
    ===> Testing: Math::Matrix:ver<0.3.9>:auth<github:pierre-vigier>
    ===> Testing [OK] for Math::Matrix:ver<0.3.9>:auth<github:pierre-vigier>
    ===> Installing: Math::Matrix:ver<0.3.9>:auth<github:pierre-vigier>
    dogbert@dogbert-VirtualBox:~$

**Comment by coke** [comment]
Based on @dogbert17 's feedback, closing ticket.
