### ISSUE TITLE
Coercion behaviour in list assignment

### ISSUE THREAD

**Issue by jonathanstowe** [rakudo/rakudo#3298]
## The Problem

I'm fairly certain that something like:

```perl6
my ( Int() $a ) = ("12345");
```
Actually did the coercion at one point (I have code from mid-June that uses this)

## Expected Behavior

The Str value is coerced to an Int

## Actual Behavior

The type constraint and the coercion are totally ignored (silently).
 
## Steps to Reproduce

```
 perl6 -e ' my ( Int() $a ) = ("12345"); say $a.WHAT'
(Str)

```

Note a non-coercing type constraint is *not* ignored:

```
perl6 -e ' my ( Int $a ) = ("12345"); say $a.perl'
Type check failed in assignment to $a; expected Int but got Str ("12345")
  in block <unit> at -e line 1
```

## Environment

* Ubuntu 18.04
*  This is Rakudo version 2019.07.1-470-gdd2f072d6 built on MoarVM version 2019.07.1-309-g48491b896
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
> Actually did the coercion at one point (I have code from mid-June that uses this)

I don't think so:

> \<AlexDaniel\> 6c: my ( Int() $a ) = ("12345"); say $a.WHAT
> \<committable6\> AlexDaniel, ¦6c (39 commits): «(Str)␤»

**Comment by jonathanstowe** [comment]
Entirely possible it actually never worked and the code I have doesn't rely on the behaviour.

**Comment by FCO** [comment]
maybe something like this?
```
perl6 -e '
my ( Int() $a ) := \("12345"); say $a.^name
'
Int
```

**Comment by jonathanstowe** [comment]
In the actual code I'm destructuring a homogeneous array of strings to properly type variables, so one would have to do something like:

```
 my @o = ("gaha", "12345"); my ( Str $f, Int() $a ) := \(|@o); say $a.WHAT
```

Which is a bit, er, eugh to may eye.  But it works :-)

**Comment by vrurg** [comment]
Fixed with the latest changes to the coercion semantics. No additional tests needed because coercive-typed variables are tested already.
