### ISSUE TITLE
Add some more Rakudo developer cookbook docs

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3302]
## The Problem

New developers may find it difficult to track down the source code required to work some issue.
Experienced Rakudo developers should be encouraged to write cookbook-style articles, to be placed in rakudo/rakudo/docs, that help an interested developer get familiar with the expert's knowledge of a topic.

Some suggested topics might be:

+ how to switch between slangs in the grammar
+ how to add a new compiler option
+ how to add a new World variable that can be accessed from Raku

**Comment by lizmat** [comment]
Closing in favour of a possible problem solving issue
