### ISSUE TITLE
`raku` executable

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3303]
We need a `raku` executable so that people can use `raku` in their shebangs and stuff. `perl6` executable should be preserved so the two have to be linked together somehow. It's likely there will be different solutions for different platforms.

> \<nine\> AlexDaniel: on Windows just copy the executable. It's just a couple of kilobytes anyway

**Comment by vrurg** [comment]
I think we can close this with 41ca7570b796e46cc1c6b77b2254b447a2867d36

**Comment by AlexDaniel** [comment]
Thank you, @vrurg! Any reports from windows users? Can somebody verify that it works?

**Comment by AlexDaniel** [comment]
To clarify, this issue is not blocking in any way, I'd just love to know that it does work on other platforms.

**Comment by vrurg** [comment]
My Windows VM came back to its sense and managed to compile `moar`. So, I can now confirm successful builds on:

- FreeBSD 11.3
- OpenBSD 6.5
- Windows 7, MSVC toolchain

Spectests are passing except for Windows. But this is on `master` and most definitely unrelated to the build anyway.

**Comment by MasterDuke17** [comment]
Can this be closed now?

**Comment by vrurg** [comment]
It can.
