### ISSUE TITLE
"colon syntax" on $. (e.g. self) in a method does not work

### ISSUE THREAD

**Issue by chromis** [rakudo/rakudo#3306]
## The Problem

I asked a question about "colon syntax" on the perl6-users mailing list. See https://www.nntp.perl.org/group/perl.perl6.users/2019/11/msg7170.html

It seems that I've stumbled over a bug.

Consider the following snippet of code:

```
#!/usr/bin/env perl6

use v6.d;

class Foo
{
    has $.attribute;

    method say-times($times)
    {
        say $.attribute * $times
    }

    method say-default-works
    {
        $.say-times(2)
    }

    method say-default-works-too
    {
        self.say-times: 2
    }

    method say-default-does-not-parse
    {
        $.say-times: 2
    }
}

my $foo = Foo.new: attribute => 42;

$foo.say-times: 2;

$foo.say-default-works;

$foo.say-default-works-too;
```

## Expected Behavior

I would expect that this program parses and that the `say-default-does-not-parse` method should "just work" (and emit "84" on `stdout`)

## Actual Behavior

I get a parse error:

```
===SORRY!=== Error while compiling /home/chromisx/raku/./oo.pl6
Confused
at /home/chromisx/raku/./oo.pl6:26
------>         $.say-times:⏏ 2
    expecting any of:
        colon pair
```

## Environment

```
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.
```

Thanks!

Regards,

Raymond.

**Comment by vrurg** [comment]
Fixed with #3317

**Comment by vrurg** [comment]
Test commited with perl6/roast@03a18d29c69d3caf8cbd744c23d4871a7cb8b815. Closing.

**Comment by chromis** [comment]
Thanks!
