### ISSUE TITLE
BOOTStr issue

### ISSUE THREAD

**Issue by j-mckim** [rakudo/rakudo#3308]
## The Problem

When I run the example code, it fails in various ways that lead me to believe what is being assigned to the variable is not a "normal" type.

This may be related to [rakudo/rakudo/issues/1800)] in which case I apologize for the noise.

## Expected Behavior

I should get an object of type string.

## Actual Behavior

I get something else - a BOOTStr. Subsequent code in the program is unable to deal with it.
An example diagnostic:

Type check failed in binding to parameter '$content'; expected Str but got BOOTStr (?)
  in sub do_something at bootstr-bug.p6 line 9
  in block <unit> at bootstr-bug.p6 line 11

## Steps to Reproduce

Run this script:

<
#!perl6

use v6;

my $user_name = Str($*USER);

#say $user_name; # fails, no method 'gist'

sub do_something(Str $content) {}

do_something($user_name); # fails, with mention of BOOTStr
>

## Environment
* Operating system:  Ubuntu 18.04
* Compiler version: Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by kjkuan** [comment]
Curiously `$*USER` is a `IntStr` rather than a `Str`...hmm, and using `Str( )` on instances of `IntStr` does result it a `BOOTStr`:
```
my $n = Str(<123>);
say $n.^name;  # BOOTStr
say $n;   # fails
```

**Comment by lizmat** [comment]
Oddly enough I *can* replicate the issue with `$*USER` on HEAD, but not the more generic `<123>` case.

**Comment by lizmat** [comment]
bisectable points to: https://github.com/rakudo/rakudo/commit/b0a1b6c31c8ee93dec53ba117bd2d8b68bfcfd31

**Comment by Kaiepi** [comment]
I think this points to a broader issue with the MOP than just the `name` meta-method. Take this for example:

```perl6
use v6.d;

class FooHOW
    does Metamodel::Naming
    does Metamodel::TypePretense
{
    method new_type(FooHOW:_: Str:D :$name --> Mu) {
        my ::?CLASS:D $meta := self.new;
        my Mu         $type := Metamodel::Primitives.create_type: $meta;
        $meta.set_name: $type, $name;
        $type
    }
}

BEGIN FooHOW.pretend_to_be: (Mu, Any);

my constant Foo = FooHOW.new_type: :name<Foo>;
say Metamodel::Primitives.is_type: Foo, Any;
```

When you run this, this happens:
```perl6
bastille% perl6 test.p6
===SORRY!===
Cannot iterate object with P6opaque representation (List)
```

Making `pretend_to_be` take a `BOOTArray` instead of a `List` makes this output `True` instead. Similarly, the MOP expects the `mro` metamethod to return a `BOOTArray`, and will throw the same error if it returns something like a `List` instead. This means that in order to do everything the MOP allows you to do, you need to know how to work with nqp, which I don't think makes sense if `Metamodel::Primitives` exists so you don't need to.

**Comment by kjkuan** [comment]
Hmm, some tests show that It doesn't always happen, and I was only able to make it fail when run it in the REPL. Running this line a from the REPL failed on the second try:
```
my $x = Str(<123>); say $x.^name; say $x;
```

**Comment by jnthn** [comment]
Fixed this in the coercion logic handling, which covers both this, but also any similar accidents we might get into.
