### ISSUE TITLE
Using a shaped array in a signature stores incorrectly in lexical pad

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3314]
(-> @a[3] {
        dd MY::.keys
    })(my @b[3] = <a b c>)
    # ("\@a[3]", "\$_", "\$*DISPATCHER").Seq
        ↑↑↑↑↑↑↑  note the q/@a[3]/ there

Note that with a normal definition of a shaped array, the lexpad is correct:

    { my @a[3]; dd MY::.keys }
    # ("\$_", "\@a", "\$*DISPATCHER").Seq
               ↑↑↑↑

Bisectable points to https://github.com/rakudo/rakudo/commit/1cafc67b1aad14eafa8d3e6431656524e4d0d5d3 but that feels bogus.  Possibly that's the one that started supporting shaped arrays in the first place.

**Comment by lizmat** [comment]
Hmmm... looks like it is also stored incorrectly in the signature:

    (-> @a[3] { dd &?BLOCK.signature })(my @b[3] = <a b c>)
    # :(@a[3] where { ... })

Not sure if that is cause or effect

**Comment by jnthn** [comment]
Fixed and test added.
