### ISSUE TITLE
%?RESOURCES behaves strangely on Windows

### ISSUE THREAD

**Issue by Prince213** [rakudo/rakudo#3315]
## The Problem
I'm trying to fix Windows builds of https://github.com/hoelzro/p6-linenoise and I noticed a strange behavior. On Linux, `%?RESOURCES<libraries/linenoise>.absolute` works without error while on Windows, it triggers `Use of Nil in string context`. Is this a bug or a feature?
## Expected Behavior
no error
## Actual Behavior (Windows only)
```
Use of Nil in string context
  in block  at site#sources\0BDF8C54D33921FEA066491D8D13C96A7CB144B9 (Linenoise) line 16
Warning: something's wrong
  in block  at site#sources\0BDF8C54D33921FEA066491D8D13C96A7CB144B9 (Linenoise) line 16
```
## Steps to Reproduce
clone https://github.com/hoelzro/p6-linenoise and add `warn %?RESOURCES<libraries/linenoise>.absolute;` before line 16 if on Windows or at line 25 if not.
Run `zef install .`
## Environment
* Operating system: Windows 10 64-bit
* Compiler version (`perl6 -v`): `This is Rakudo version 2019.07.1-479-ged8f5141f built on MoarVM version 2019.07.1-309-g48491b896
implementing Perl 6.d.`

**Comment by ugexe** [comment]
Note this gets trigger because of a recent invalid change to Linenoise. There is no Rakudo bug here.

**Comment by Prince213** [comment]
Do you mean https://github.com/hoelzro/p6-linenoise/pull/30?

**Comment by niner** [comment]
I wouldn't even try to debug this, but instead rip out the whole section of code. It's utterly useless and apparently harmful.

**Comment by ugexe** [comment]
> Do you mean hoelzro/p6-linenoise#30?

No, this is different. What is likely happening is `nmake` isn't generating the file into `libraries/whatever`. There would be no file there and hence no such key.

**Comment by Prince213** [comment]
> > Do you mean [hoelzro/p6-linenoise#30](https://github.com/hoelzro/p6-linenoise/pull/30)?
> 
> No, this is different. What is likely happening is `nmake` isn't generating the file into `libraries/whatever`

No, I'm using `gmake` but this error is still triggered.

**Comment by Prince213** [comment]
Also, if it's not a rakudo bug, https://github.com/hoelzro/p6-linenoise/issues/29 won't happen and the fix won't be needed.

**Comment by ugexe** [comment]
A wild guess would be:

```diff
-    my constant LIBLINENOISE = %?RESOURCES<libraries/linenoise>.Str;
+    my sub LIBLINENOISE { %?RESOURCES<libraries/linenoise>.Str }
```

and replace `native(LIBLINENOISE)` with `native(&LIBLINENOISE)`

**Comment by niner** [comment]
No, please, this stuff is broken on so many levels that it should really be replaced with something sane: https://github.com/hoelzro/p6-linenoise/issues/31

**Comment by Prince213** [comment]
> A wild guess would be:
> 
> ```diff
> -    my constant LIBLINENOISE = %?RESOURCES<libraries/linenoise>.Str;
> +    my sub LIBLINENOISE { %?RESOURCES<libraries/linenoise>.Str }
> ```
> 
> and replace `native(LIBLINENOISE)` with `native(&LIBLINENOISE)`

That solves the problem, but why?

**Comment by ugexe** [comment]
> No, please, this stuff is broken on so many levels that it should really be replaced with something sane: hoelzro/p6-linenoise#31

While that PR is indeed incorrect I believe it is unrelated to this

> That solves the problem, but why?

Dunno without really investigating. But that isn't going to actually fix it either. If you do `perl6` after installing it you should get an error about it not being able to find some symbol -- that issue seems like the "windows doesn't like renamed dll" problem. OpenSSL has a hacky fix ( https://github.com/sergot/openssl/blob/master/lib/OpenSSL/NativeLib.pm6 ), and niner has an experimental rakudo branch which skips the renaming on install.

**Comment by Prince213** [comment]
I have tried on both Windows and Linux, tab completion on Windows works fine without error.
