### ISSUE TITLE
Async socket performance regression in 2019.11

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#3326]
server.pl
```perl6
react {
    whenever IO::Socket::Async.listen('localhost', 3333) -> $connection {
        whenever $connection.Supply.lines -> $line {
            die unless $line eq 'ping'; # just checking...
            $connection.print( "pong\n" );
        }
    }
}
```

client.pl
```perl6
my $connection = IO::Socket::INET.new( host => 'localhost',  port => 3333 );

my $start = now;
for ^100000 {
    $connection.put( 'ping' );
    my $status = $connection.get( );
    die unless $status eq 'pong'; # just checking...
}
say now - $start;
```

When server.pl is running on Rakudo 2019.07.1 client reports 13.1s on average, but for server running on Rakudo 2019.11 it takes 15.5s. Thats **13% performance drop**.

Only Async sockets are affected, it does not matter which Rakudo client.pl is running on.

**Comment by Kaiepi** [comment]
This doesn't seem to be related to any of the changes made to how sockets are handled since 2019.07.1. All that's changed with sockets is how they can now specify a family of address to use (which isn't exposed for use with `IO::Socket::Async` yet) and how GC is handled when listening on an async socket. The sockets created by `IO::Socket::INET` and `IO::Socket::Async` use the same addresses as before in this case, and how socket reads and writes are handled hasn't changed. Maybe it has to do with how the data received is decoded?

**Comment by vrurg** [comment]
@bbkr Can you by chance try bisecting it?

**Comment by AlexDaniel** [comment]
Pretty sure [I bisected it](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2019-11-28#l79).

(2019-08-06) https://github.com/rakudo/rakudo/commit/ae4ba74262b1155ddf57cd2bac1f3aaccfc1e47f

I can't believe that the commit affects performance that much but it does. See https://gist.github.com/44c459e804c8a2d0231b56eb669243cf.

Can somebody try confirming it locally? It can also be a change in gcc and it just happens that whateverable got an update between these commits.

**Comment by AlexDaniel** [comment]
Confirming that the GCC version didn't change between these builds:

```
ae4ba74262b1155ddf57cd2bac1f3aaccfc1e47f/bin$ objdump --full-contents --section=.comment moar

moar:     file format elf64-x86-64

Contents of section .comment:
 0000 4743433a 20284465 6269616e 20362e33  GCC: (Debian 6.3
 0010 2e302d31 382b6465 62397531 2920362e  .0-18+deb9u1) 6.
 0020 332e3020 32303137 30353136 00        3.0 20170516.
```

```
84b3e9fda042329a280dd4523337bdee038665df/bin$ objdump --full-contents --section=.comment moar

moar:     file format elf64-x86-64

Contents of section .comment:
 0000 4743433a 20284465 6269616e 20362e33  GCC: (Debian 6.3
 0010 2e302d31 382b6465 62397531 2920362e  .0-18+deb9u1) 6.
 0020 332e3020 32303137 30353136 00        3.0 20170516.   
```
So this is not like https://github.com/rakudo/rakudo/issues/2988.

**Comment by vrurg** [comment]
Following IRC [discussion](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2019-11-28#l73), the cause is probably linked to rakudo/rakudo@ae4ba74262b.

**Comment by jnthn** [comment]
Unfortunately I don't have time to dig further, but my first guess is that something about the new setting arrangement has thrown off some things the static optimizer does; of note, if the optimization that turns a `call` into a `callstatic`. See [this code](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Optimizer.nqp#L2082).

**Comment by vrurg** [comment]
@jnthn I think the primary cause is that v6c core was previously compiled with language set to `6.d`. I made each core use it's respective language version in the compiler which is likely thrown away some optimizations `6.d` is doing. As @niner noted, `decontrv` vs. `decontrv_6c`, for example.

I'm about to return the status quo on this and make `6.c` compiled with `6.d` and see if this resolve the degradation. Most likely it will.

**Comment by bbkr** [comment]
Thanks!

**Comment by vrurg** [comment]
@bbkr I'm not sure if it helped. Could you, please, benchmark it again on your side? My laptop did show significant improvement, but it's hardly a reliable source due to active CPU throttling.

**Comment by bbkr** [comment]
Rakudo, same hardware, same build process:

* 2019.07.1 - 13.1s
* 2019.11 - 15.5s
* moar-blead (today) - 13.4s

So performance is back to normal.

**Comment by vrurg** [comment]
Phew, thank you!
