### ISSUE TITLE
clone on multi dimensional array

### ISSUE THREAD

**Issue by ufobat** [rakudo/rakudo#3334]
`.clone()` on a multi dimensional array is not deep but shallow. 

I am okay with this behaviour but I am not perfectly sure if this intended since there is a _short-hand_ syntax to acces values in a multi-dimensional array like that `@a[1;2;3]` which hides away the fact that the multi-dimensional Array is an Array of Arrays.

In addition a clone of an shaped array seems to have lost its shape.

**Comment by lizmat** [comment]
Could you create a separate issue for the `@a[2].clone` issue losing its shape ?

**Comment by ufobat** [comment]
I've put it in the same issue since the shape on an array can be the definition of an _multi-dimensional_ structure. I would assume, if clone() takes the shape into account, it should clone it in a shallow way as well (aka only keep the shape of the first dimention - i think this is called jagged array shape) in order to be consistent.

**Comment by jnthn** [comment]
The shape part seems fine, so I just added a test for that. The too-shallow problem was fixed in 4a954cbc2b and is covered by the test too.

**Comment by jnthn** [comment]
Ah, also to mention: `my @a[2;2]; my @b = @a.clone; say @b.shape;` will not reflect the shape of `@a`, because array assignment is a copying operation, so you're actually copying out of a shaped clone of `@a` into an unshaped `@b`.
