### ISSUE TITLE
Modules with exported objects with and and without tags fail with LTA msg

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3341]
## Problem (WIP)

Given a module like this:

    unit module Foo;
    sub a is export { say "a" }
    multi b is export { say "b" }
    multi b(:$char = 'b') is export { say "$char" }

Use it:

    $ raku -e -I. 'use Foo; a'
    a
    $ 
    b

## Environment
* Operating system:  Debian 10 (Buster)
* Compiler version (`perl6 -v`): 
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

**Comment by lizmat** [comment]
Cannot reproduce, so assume is fixed
