### ISSUE TITLE
A module's test is flapping due to a grammar action method is not being called

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3345]
## The Problem

[OO::Plugin](https://github.com/vrurg/Perl6-OO-Plugin) _020-method-handling.t_ test is flapping because a method in grammar actions class is not always invoked.

## Actual Behavior

Test fails with output like the following:

```
not ok 5 - shared data comes from Bar plugin, but it's not called yet
# Failed test 'shared data comes from Bar plugin, but it's not called yet'
# at t/020-method-handling.t line 47
# expected: ${}
#      got: ${:Bar("Do me a favor, please!")}
```

## Steps to Reproduce

```
git clone https://github.com/vrurg/Perl6-OO-Plugin.git
cd Perl6-OO-Plugin
zef install --deps .
perl6 -Ilib t/020-method-handling.t
```

Because the test is flapping sometimes it might take a few runs of the test before it fails.

## Notes

The tests failing are all related to plugin ordering. This happens because plugin typeobjects use a keyword like `before` to declare that they must go before some other plugin. The module defines a slang to handle this in _lib/OO/Plugin.pm6_. The grammar itself works ok, but methods associated with tokens/rules are sometimes get skipped. In the particular case of `OO::Plugin` the problematic methods are `trait_mod:sym<ordering-keyword>`.

**Comment by vrurg** [comment]
The problem was bisected to 36fa16bb38af3796b3044ba7f34b88e30fcdd90f which looks reasonable catch. @jnthn, can you have a look at this?

**Comment by jnthn** [comment]
> OO::Plugin 020-method-handling.t test is flapping because a method in grammar actions class is not always invoked.

How was this determined? I added this patch:

```
diff --git a/lib/OO/Plugin.pm6 b/lib/OO/Plugin.pm6
index 346f2d6..54ff114 100644
--- a/lib/OO/Plugin.pm6
+++ b/lib/OO/Plugin.pm6
@@ -201,30 +201,37 @@ sub EXPORT {
         }
 
         method package_declarator:sym<plugin>(Mu $/) {
+            note "package decl plugin";
             $/.make( mkey($/, 'package_def').ast );
         }
 
         method package_declarator:sym<plug-class>(Mu $/) {
+            note "package decl plug class";
             $/.make( mkey($/, 'package_def').ast );
         }
 
         method ptype-name-list ( Mu $/ ) {
+            note "ptype-name-list";
             $/.make: $/.list[0].list.map: { mkey( $_, 'longname' ).Str };
         }
 
         method trait_mod:sym<for> (Mu $/) {
+            note "trait mod for";
             @*PLUG-CLASS-EXTENDING.append: mkey( $/, 'ptype-name-list' ).ast;
         }
 
         method trait_mod:sym<after> ( Mu $/ ) {
+            note "trait mod after";
```

On a failing run I see:

```
package decl plugin
ptype-name-list
trait mod before
package decl plugin
```

And on a passing run I see the very same:

```
package decl plugin
ptype-name-list
trait mod before
package decl plugin
```

**Comment by jnthn** [comment]
Further findings:

* It's not about spesh
* It is about hash randomization: when I disable that in MoarVM, the module always fails (though I guess with a different default seed it'd always pass).

**Comment by vrurg** [comment]
I don't remember exactly what was happening, but I think I wasn't getting debug output from `note` in action method when test were failing. That's why I decided that they were not ran. Unfortunately, lack of time didn't allow me to debug deeper as it would require going into grammar's code which I don't know well enough.

Now the situation is different and additional output in the methods doesn't "fix" the test. Perhaps I'd be able to do more debug when over with my daytime work.

**Comment by vrurg** [comment]
With a little time of my hands, I tracked down the issue to another cause. Rule `ptype-name-list` builds a list of plugin (package) names. Corresponding method in actions was pulling the list. It seems that the bisected commit breaks the data structure and `ptype-name-list` from actions now returns an empty sequence. 

I don't know if it's intended change or a regression. But if I replace `before Bar` in the test with `before Bar,Foo`, `$/` in the method stringifies to 'Bar,Foo ' (with the space at the end). On the contrary, `$/.list` is 1 element long and only contains 'Foo ' with the same space in the end.

The biggest difference is what `$/.list[0]` has. On 2019.03 `$/.list[0].list` has two elements: 'Bar' and 'Foo '. On the `HEAD` it's just 'Foo '.

**Comment by vrurg** [comment]
I forgot about `dump` method. Here is what I get on `HEAD`:

```
- 0: Foo
  - longname: Foo
    - name: Foo
      - identifier: Foo
      - morename:  isa NQPArray
    - colonpair:  isa NQPArray
```

And this is on 2019.03:

```
- 0: 2 matches
  - longname: Bar
    - colonpair:  isa NQPArray
    - name: Bar
      - identifier: Bar
      - morename:  isa NQPArray
  - longname: Foo
    - name: Foo
      - morename:  isa NQPArray
      - identifier: Foo
    - colonpair:  isa NQPArray
```

**Comment by jnthn** [comment]
Seems fixed; no spectest cus this is non-spec behavior.

**Comment by vrurg** [comment]
Thanks, @jnthn! Works as a charm!
