### ISSUE TITLE
infix:<eqv> hangs on Iterables that are not Positional

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#3346]
## The Problem

The following code hangs:

```raku
class Null does Iterable does Iterator {
    method iterator { self }
    method pull-one { IterationEnd }
}

say Null.new eqv Null.new;
```

This happens because `multi sub infix:<eqv>(Iterable:D \a, Iterable:D \b)` assumes that the arguments are `Positional`. But by default `elems` returns 1 and `AT-POS(0)` returns the invocant.

## Expected Behavior

The `multi sub infix:<eqv>(Iterable:D \a, Iterable:D \b)` should return a `Bool` indicating whether the respective iterators return the same elements.

## Actual Behavior

The `multi sub infix:<eqv>(Iterable:D \a, Iterable:D \b)` keeps comparing `a` with `b`.

## Action

I will submit a spectest asserting that `AT-POS` is not invoked on an `Iterable` that is not `Positional`. Then I will try to change the implementation of `multi sub infix:<eqv>(Iterable:D \a, Iterable:D \b)` to use the respective iterators.

## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by lizmat** [comment]
Example code?

**Comment by dumarchie** [comment]
There you are. I accidentally submitted the issue before adding a description.

**Comment by dumarchie** [comment]
Using the iterators is a flawed approach as I explained in https://github.com/rakudo/rakudo/pull/3356#issuecomment-567640625.

Maybe it's better to replace the `infix:<eqv>` candidate accepting `Iterable` objects with candidates accepting `Positional` and/or `PositionalBindFailover` objects. `Iterable` objects not implementing `Positional` or `PositionalBindFailover` can be compared like `Any` objects.

Comments are welcome.

**Comment by dumarchie** [comment]
This issue affects `eqv` comparison between `HyperSeq` and `RaceSeq` objects as well.

I've changed the [spectest](/perl6/roast/pull/601) to compare `HyperSeq` objects.
