### ISSUE TITLE
[LTA] Coercing a value to an enum fails if the types don't exactly match

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#3349]
## The Problem

Coercing a value to an `enum` only works if the value's type is exactly the same as the type of the `enum` values.  For instance, if you have an `enum` with `Int` values, and you try to coerce `Order::Less` to it, it returns a type object.
It'd be nice if it first tries to coerce the given value to the expected type.

## The Code

    enum Direction (:LEFT(-1), :NEUTRAL(0), :RIGHT(1));
    say Direction(2 <=> 3);
    say Direction(+(2 <=> 3));

## Expected Output

    LEFT
    LEFT

## Actual Output

    (Direction)
    LEFT

## Environment

Linux
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

(but also fails with the bot in IRC)

**Comment by raiph** [comment]
> For instance, if you have an enum with `Int` values, and you try to coerce `Order::Less` to it, it returns a type object.

Fwiw, in recent Rakudos, it throws an exception:

```
enum Direction (:LEFT(-1), :NEUTRAL(0), :RIGHT(1));
say Direction(2 <=> 3); # No value 'Less' found in enum Direction
```

**Comment by lizmat** [comment]
FWIW, I think the current behaviour is correct.

Added test with https://github.com/Raku/roast/commit/81477853e0
