### ISSUE TITLE
'last` in a `CATCH` block sometimes applies to an unexpected loop

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#3353]
## The Problem

When you use `last` in a `CATCH` block inside a loop, and an exception occurs in a loop in a sub or method, that loop is exited, instead of the loop where the `CATCH` block resides.

Example code:

    sub foo($x)
    {
        for (^1) {
            say 1/$x;
        }
    }

    for -3 .. 3 -> $i {
        foo($i);
        CATCH {
            say "Oops with i=$i";
            last;
        }
    }

## Expected Output

-0.333333
-0.5
-1
Oops with i=0

## Actual Output

-0.333333
-0.5
-1
Oops with i=0
1
0.5
0.333333

## Workaround

If you add a label, the code behaves as expected:

    sub foo($x)
    {
        for (^1) {
            say 1/$x;
        }
    }

    BAR:
    for -3 .. 3 -> $i {
        foo($i);
        CATCH {
            say "Oops with i=$i";
            last BAR;
        }
    }

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

(Also fails with the bots in IRC)

**Comment by lizmat** [comment]
This behaviour is correct, or at least expected: `last` is a CONTROL message that will be caught by the first **dynamically** found loop structure by default.  If you want to be sure where the `last` will get caught, you will need to add a label:
```raku
sub foo($x) {
    for ^1 {
        say 1/$x;
    }
}

VALUES:
for -3 .. 3 -> $i {
    foo($i);
    CATCH {
        say "Oops with i=$i";
        last VALUES;
    }
}
```
outputs:
```
-0.333333
-0.5
-1
Oops with i=0
```
