### ISSUE TITLE
Complex numbers 0+0i and 0-0i aren't the same value

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#3354]
## The Problem

Looks like `Complex` values 0+0i and 0-0i aren't treated as the same value in some cases, for instance when using them as a hash key.

    my %h{Complex} = 0+0i => 'foo'; 
    dd %h;
    say 0+0i == 0-0i;
    say %h{0+0i};
    say %h{0-0i};

## Expected Behavior

    Hash[Any,Complex] %h = (my Any %{Complex} = <0-0i> => "foo")
    True
    foo
    foo

## Actual Behavior

    Hash[Any,Complex] %h = (my Any %{Complex} = <0-0i> => "foo")
    True
    (Any)
    foo

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

(but also fails with the bot in IRC)

**Comment by jnthn** [comment]
I think this is correct behavior. A `Complex` is represented as a pairing of two `Num`s, and `0e0` and `-0e0` are distinct values (nothing specific to Raku, just a consequence of how floating point numbers work). You get consistent behavior there too:

```
my %h{Num};
%h{0e0} = 1;
%h{-0e0} = 1;
say %h.elems;    # 2
```

**Comment by jnthn** [comment]
Furthermore, equivalence for hashing is defined has having `===` semantics, and again, this all matches up (note how `==` is actually sloppier here):
```
$ perl6 -e 'say 0e0 === -0e0'
False
$ perl6 -e 'say 0e0 == -0e0'
True
$ perl6 -e 'say 0+0i === 0-0i'
False
$ perl6 -e 'say 0+0i == 0-0i'
True
```

All in all, I think everything is working consistently and as designed; if you want a different behavior, you'll need to normalize values before storing them.
