### ISSUE TITLE
Odd behavior when using `$^a` within a substitution regex

### ISSUE THREAD

**Issue by SirBogman** [rakudo/rakudo#3358]
## Actual Behavior

This works as I would expect:
```perl6
> $_ = "12345"; [3,4].map:{$^a;S/5/$a/}
(12343 12344)
> $_ = "12345"; [3,4].map:{$^a;S{5}=$a}
(12343 12344)
> $_ = "12345"; [3,4].map:{$^a;S/$a/X/}
(12X45 123X5)
> $_ = "12345"; [3,4].map:{$^a;S{$a}='X'}
(12X45 123X5)
```
This does not:
```perl6
> $_ = "12345"; [3,4].map:{S{5}=$^a}
(3 4)
> $_ = "12345"; [3,4].map:{S/5/$^a/}
(3 4)
> $_ = "12345"; [3,4].map:{S{$^a}='X'}
(3 4)
> $_ = "12345"; [3,4].map:{S/$^a/X/}
(3 4)
```
Is this a bug, or am I missing something?

## Expected Behavior
```perl6
> $_ = "12345"; [3,4].map:{S{5}=$^a}
(12343 12344)
> $_ = "12345"; [3,4].map:{S/5/$^a/}
(12343 12344)
> $_ = "12345"; [3,4].map:{S{$^a}='X'}
(12X45 123X5)
> $_ = "12345"; [3,4].map:{S/$^a/X/}
(12X45 123X5)
```
## Environment
* Operating system: macOS 10.15.2 (19C57)
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1-478-g75056dfa1 built on MoarVM version 2019.07.1-317-g1b2f72e5e
implementing Perl 6.d.

**Comment by SirBogman** [comment]
Is the regex like a block and it's capturing the $^a instead of the outer block?

**Comment by AlexDaniel** [comment]
Bisected: https://github.com/rakudo/rakudo/commit/739d1a3f1c48656daf418967089e74f5f280f518
Previously worked as expected by the OP.

**Comment by SirBogman** [comment]
Wow, that was quick! What does RT #128809 refer to?

**Comment by AlexDaniel** [comment]
https://rt.perl.org/Public/Bug/Display.html?id=128809

**Comment by AlexDaniel** [comment]
> Wow, that was quick!

On IRC:
> 06:52:47 \<AlexDaniel\> 6c: `$_ = "12345"; say [3,4].map:{S{5}=$^a}`
> 06:53:03 \<committable6\> AlexDaniel, https://gist.github.com/992b5151a1244b35ff9c288aad2a3f63
> 06:53:21 \<AlexDaniel\> bisect: `$_ = "12345"; say [3,4].map:{S{5}=$^a}`
> 06:53:23 \<bisectable6\> AlexDaniel, Bisecting by output (old=2015.12 new=0e2485a) because on both starting points the exit code is 0
> 06:53:52 \<bisectable6\> AlexDaniel, bisect log: https://gist.github.com/72ea3e5ac3f2eb57ccc0c0ffc2b19dab
> 06:53:52 \<bisectable6\> AlexDaniel, (2016-08-17) https://github.com/rakudo/rakudo/commit/739d1a3f1c48656daf418967089e74f5f280f518

**Comment by SirBogman** [comment]
Very cool.
