### ISSUE TITLE
Enums don't work with v6.e.PREVIEW

### ISSUE THREAD

**Issue by barcharcraz** [rakudo/rakudo#3362]
## The Problem
The code

```
use v6.e.PREVIEW
enum Day <Sun Mon Tue Wed Thu Fri Sat>;
```

Fails to work
## Expected Behavior
File runs with no output
## Actual Behavior

```
===SORRY!=== Error while compiling C:\Users\chbarto\source\repos\curator\curator.p6/.\bin\main
Cannot find method 'roles' on object of type Perl6::Metamodel::EnumHOW
at C:\Users\chbarto\source\repos\curator\curator.p6/.\bin\main:4
```

## Environment
* Operating system:
Windows 10
 
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.11-271-g0e2485a83 built on MoarVM version 2019.11-92-gd7b6855d3
implementing Perl 6.d.

**Comment by vrurg** [comment]
Fixed with #3363
