### ISSUE TITLE
No trailing pod on sub routine parameters

### ISSUE THREAD

**Issue by kalkin** [rakudo/rakudo#3367]
## The Problem

Given the following code:
```perl6
#| Sub f
sub f($asd #= bar
){}

#| Sub g
sub g(
    $asd #= bar
){}

```

## Expected Behavior

Function `f()` param `$asd` has a trailing pod documentation, like `g()`. 

## Actual Behavior
Function `f()` param `$asd` has no trailing pod documentation.
## Steps to Reproduce
See code above

## Environment
* Operating system: Everywhere 
* Compiler version (`perl6 -v`): 2019.11

I also added a roast test for this. I'm not sure if I shall do a PR for it or not. https://github.com/kalkin/roast/commit/3149a8b49309862c4ab42baf3ed94069b51c1965

**Comment by lizmat** [comment]
Closing in light of several discussions, particularly https://github.com/Raku/problem-solving/issues/438
