### ISSUE TITLE
User Defined `is assoc<chain>` function not acting as expected

### ISSUE THREAD

**Issue by Scimon** [rakudo/rakudo#3370]
## The Problem

    use v6.d;
    sub infix:<eog> ( $a,  $b ) is assoc<chain> is pure { 
        so $a == $b+1 
    }
    say 5 eog 4 eog 3 eog 2 eog 1;
    say ( (5 eog 4) and (4 eog 3) and (3 eog 2) and (2 eog 1) );

## Expected Behavior

    True
    True

The second line is implementing a chain operator as described in the Docs. 

## Actual Behavior

    False
    True

It would appear user generated chaining operators are instead treated as left associative. 

## Environment
* Operating system: Ubuntu Linux 19.04
* Compiler version (`perl6 -v`): Rakudo version 2019.11 built on MoarVM version 2019.11

**Comment by alabamenhu** [comment]
In the past it sometimes would get right associativity ([TIO](https://tio.run/##dZBBCsIwEEX3nuJTC1XpxkRdVBHBrbjwBqmoDZRWjIoinr1OpoNWqavHMJ@X/DnuTvmkqtwlhS329pbM8t3@PAd6oYkRpn1YB@Ncue1FfhOhjwecuSNY0ZgAocHVUTLAc9ppeLaZscW8zcOb6O1Z@jH56znZQ3Zu9fDm49n48b8nt457DRYGwFcv2jR70Ui9ghichPd0G6KipFqtB6JNhI9oXVKtnwN1xvBnBEZCLVTC4ZQi3IwiNbVQCTnCR6RITS1UQo74XvwQUwuVkCLdMejL8JmaWqiElKmqFw) link)

```
sub infix:<left>  ($a, $b) is assoc('left' ) { say "Left:  $a vs $b" };
sub infix:<chain> ($a, $b) is assoc('chain') { say "Chain: $a vs $b" };
sub infix:<right> ($a, $b) is assoc('right') { say "Right: $a vs $b" };
sub infix:<list>  (*@a   ) is assoc('list' ) { say "List:  ", @a     };
#sub infix:<non>  ($a, $b) is assoc('non'  ) { say "Non:   $a vs $b" };

5 left  4 left  3 left  2 left  1;
5 right 4 right 3 right 2 right 1;
5 chain 4 chain 3 chain 2 chain 1;
5 list  4 list  3 list  2 list  1;
#5 non  4 non   3 non   2 non   1;
```

Results in 

```
Left:  5 vs 4
Left:  True vs 3
Left:  True vs 2
Left:  True vs 1
Right: 2 vs 1
Right: 3 vs True
Right: 4 vs True
Right: 5 vs True
Chain: 2 vs 1
Chain: 3 vs True
Chain: 4 vs True
Chain: 5 vs True
List:  [5 4 3 2 1]
```

(The `non` assoc works fine, but is commented out for obvious reasons)
