### ISSUE TITLE
Missing comma in hash literal can confuse the compiler

### ISSUE THREAD

**Issue by puyawsiht** [rakudo/rakudo#3374]
## The Problem
This code (note the missing comma)
```
my $x;
{:$x :$x}
```
produces what I assume is an exception in the compiler:
```
~/raku $ perl6 test.p6
===SORRY!===
Unknown QAST node type NQPMu
```

The same thing happens with
* `{:x($x) :y($x)}`
* `{:x<a> :y<b>}`
* `{:$x :y($x)}`

These expressions produce a Hash with two elements:
* `{:x($x) :y(1)}`
* `{:$x :1y}`
* `{:1x :1y}`

`{:$x 1}` produces a syntax error, which is what I would expect to happen.

## Environment
```
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```

**Comment by jnthn** [comment]
These all seem to be fixed in `HEAD`:

```
$ ./perl6-m -e 'my $x; dd {:$x :$x}'
Hash % = {:x(Any)}
$ ./perl6-m -e 'my $x; dd {:x($x) :y($x)}'
Hash % = {:x(Any), :y(Any)}
$ ./perl6-m -e 'my $x; dd {:y<a> :y<b>}'
Hash % = {:y("b")}
$ ./perl6-m -e 'my $x; dd {:$x :y($x)}'
Hash % = {:x(Any), :y(Any)}
```

So just need tests.

**Comment by LINEdd1346** [comment]
Thoughtful management / safe and reliable / best quality
☆ New Tea First ☆ Zhengmei Concentration Camp ☆
This is heaven! Coming here is great ~
[North, Middle, South], Send M service
☆ The best quality A-grade tea supply
+ Line: dd1346☑
WeChat: JG942640

**Comment by melezhik** [comment]
I've added a couple if rkp tests:

* negative - http://rakudist.raku.org/sparky/report/RakuPlay-2/1273
* positive - http://rakudist.raku.org/sparky/report/RakuPlay-1/1274

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/746ef5001d
