### ISSUE TITLE
composalizable seems to work, but then it's all it does

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3376]
## The Problem

Composalizable and composalize seem to be applied only to enums, so this works:

```raku
enum Norse-gods <Þor Oðinn Freija>;

say "Composalizable ", Norse-gods.HOW.archetypes.composalizable();

enum All-gods does Norse-gods <Ammon>;

say All-gods::<Oðinn>;
```

But then, it's not clear what that composalization actually does. `Norse-gods` enums are not included in All-gods, for instance, so the `say` above returns `(Any)` as with any other unknown string.

## Expected Behavior

I guess composing (or composalizing) in the defined enums is what would make the most sense in this case.
Initially, I was looking for an example of one of the 6.d features (to advance Raku/doc#2632), 
> &infix:<does> can be used with non-composable instances on RHS

I guess non-composable means *composalizable*, of which enum seems to be the only example.

## Actual Behavior

There's no behavior I can replicate, except it does not blow with an exception.

## Steps to Reproduce

Run above script with 2019.11.

## Environment

    This is Rakudo version 2019.11 built on MoarVM version 2019.11 implementing Perl 6.d.

OS is Ubuntu 16.04

**Comment by jnthn** [comment]
I believe it's implementing [these semantics](https://design.raku.org/S12.html#Anonymous_Mixin_Roles_using_but_or_does).

**Comment by JJ** [comment]
In this case, it would be `All-gods` *as a container* what would get `Norse-gods` composed, then, right?

**Comment by lizmat** [comment]
Appears fixed
