### ISSUE TITLE
Method::Also regression since 2019.11

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3378]
## Steps to Reproduce

`zef install Method::Also`

## Environment
* Operating system: Linux dispair 5.3.14_1
* Compiler version (`perl6 -v`): `019.11-291-g9a571b685 built on MoarVM version 2019.11-93-g7a93b2897`

**Comment by lizmat** [comment]
Reverting to version 0.02 (prior to Xliff's work) does not fix the problem.

**Comment by lizmat** [comment]
Looks like an incompatible change was made with the API of the `specialize_with` method.  The following change makes `Method::Also` pass its tests:

    -        method specialize_with (Mu \obj, Mu \type_env, @pos_args) {
    +        method specialize_with(Mu $, Mu $, Mu \type_env, |c) {

AKA, the `type_env` seems to have moved from position 2 to 3.

@vrurg: does that ring a bell?

**Comment by lizmat** [comment]
Changed `Method::Also` like this:

    -        method specialize_with (Mu \obj, Mu \type_env, @pos_args) {
    -            $*TYPE-ENV := type_env;
    +        method specialize_with(Mu $, Mu \old_type_env, Mu \type_env, |) {
    +            $*TYPE-ENV := old_type_env.^name eq 'BOOTContext'
    +              ?? old_type_env
    +              !! type_env;

A new release of `Method::Also` with this change is on its way to CPAN now.

**Comment by dogbert17** [comment]
Can/should this be closed?

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-92-g6e6c9e5cc.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-20-gf99bc2ce7.
    dogbert@dogbert-VirtualBox:~$ zef install Method::Also
    ===> Searching for: Method::Also
    ===> Testing: Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
    ===> Testing [OK] for Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
    ===> Installing: Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
