### ISSUE TITLE
surprising-to-me difference between assigning to $var and @var

### ISSUE THREAD

**Issue by dakkar** [rakudo/rakudo#3392]
## The Problem

```perl6
use v6.d;
use Test;

subtest '@ sigil' => {
    subtest 'direct assigment' => {
        my (@a,) = Array.new();
        ok(!@a);
        my (@b,) = Array;
        ok(!@b);
    }

    subtest 'via hash' => {
        my %x;
        %x<a> = @();
        my (@a,) = %x<a>;
        ok(!@a);
        my (@b,) = %x<b>;
        ok(!@b);
    }
}

subtest '$ sigil' => {
    subtest 'direct assigment' => {
        my $a = Array.new();
        ok(!$a);
        my $b = Array;
        ok(!$b);
    }

    subtest 'via hash' => {
        my %x;
        %x<a> = @();
        my $a = %x<a>;
        ok(!$a);
        my $b = %x<b>;
        ok(!$b);
    }
}

done-testing;
```

## Expected Behavior

When I have an expression that can return a defined array, or not (e.g. accessing an element of the `%x` above), I'd like to assign it to a @-sigilled variable, and having that variable be false when the expression didn't return a defined array.

## Actual Behavior

See the test. `(@a,)=Array` gives a true `@a`, `(@a,)=Array.new` gives a false `@a`.

## Environment
* Operating system: linux
* Compiler version (`raku -v`): This is Rakudo version 2019.11 built on MoarVM version 2019.11

**Comment by jonathanstowe** [comment]
In your True example you are winding up with a one element array with an `Array` type object as the value:

```
perl6 -e 'my (@b,) = Array; say @b.perl'
[Array,]
```

Whereas assigning an Array instance is effectively assigning an empty list:

```
perl6 -e 'my (@b) = Array.new; say @b.perl'
[]
```

**Comment by dakkar** [comment]
@jonathanstowe thank you, I sort-of understand why, under the current implementation, the behaviour is what it is.

I should probably have asked the question differently: is this the behaviour we want? Especially when the undef / type object comes from a possibly-complicated expression?

Might we change Positional & Associative & whatever else, so that when asked to access an element that's not there, they return something that becomes the appropriate type object in item context, and nothing at all in list context?

Or should we document the current behaviour, and essentially telling people «if you can't guarantee that your expressions will always return defined values, you're better off assigning to `Array $foo` instead of `@foo`»?

**Comment by vrurg** [comment]
@dakkar there is definitely nothing to be changed. The current behavior is what should be expected.

With regard to documenting, I would rather expect this kind of specifics to be covered in a book rather than explicitly stated in the docs. Because to the best of my knowledge each elementary behavior is documented, it's just not always trivial to put 'em all together. For me it's like: "This should work... Oh, no? Why? Ah, that's why, of course it won't!" :)
