### ISSUE TITLE
Move all .precomp to one location

### ISSUE THREAD

**Issue by rabbiveesh** [rakudo/rakudo#3395]
## The Problem
When raku precompiles a module, it creates a new folder in the current directory and puts the precompiled modules there. This is helpful for when running the same script in one directory, but a burden when using it in multiple places. 

## Expected Behavior
If I use `jmp`, as an example of something that I'd want to use anywhere on my file system, it takes a good 20 seconds of precompiling before it starts running. I'd expect this precompiling to happen once after installing, stored somewhere relative to my home directory (maybe at the install path of the module? That's debatable) and then never again, no matter what directory it's run from.

## Actual Behavior
The .precomp is stored relative to the current directory, so changing directories requires a new precompilation.

## Steps to Reproduce
1) Run `jmp` (after installing it from zef) from any directory. 
2) cd to a subdirectory
3) run `jmp` again

It will re-precompile.

## Environment
* Operating system: Ubuntu 16.04
* Compiler version (`raku -v`): This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.
installed from rakudo-pkg (though I don't imagine this is related to that)

I find this especially an issue, b/c I use these commands inside of my git repos, and I have to keep adding .precomp to my gitignore (a more annoying take on #2984 ). This shouldn't be something that I need to think about if I'm casually consuming raku scripts.

**Comment by jonathanstowe** [comment]
I think that's because it has a  relative `use lib 'lib'` in it....

**Comment by rabbiveesh** [comment]
Oh, so it's a problem over there?
While I'm here, what's the way to deal with that? I'll make a pull request
against it.

**Comment by niner** [comment]
Just remove that `use lib`. It's unnecessary

**Comment by rabbiveesh** [comment]
Thanks, that's a simple fix.
Is this intended behavior? Shouldn't raku check where a module was loaded from, and then use the precomp relative to that, rather than the top of the @INC (assuming that's what it's called here, i'm mainly a perl person).

**Comment by lizmat** [comment]
There is no @INC in Raku.  There is a $*REPO, which is basically a linked list with CompUnitRepo objects, that are asked in sequence whether they can supply the code for a given module/version/authority/api .  If they cannot, they pass the request on to the next one in the list.  Each CompuUnitRepo is completely free in how it handles the requirement of being able to provide a module.  Pre-compilation is provided by the 2 standard CompUnitRepo modules that come with Raku: one providing Perl's -I functionality, and one providing Perl's "installed modules"-like functionality.

So you cannot generally say that precomps should be stored somewhere, because it is entirely up to the CompUnitRepo module in question how to decide that.  Hope this made sense  :-)

**Comment by Altai-man** [comment]
Can this issue be closed if the original question is answered?

**Comment by rabbiveesh** [comment]
Should I start a new issue with my current question of why raku precompiles in a local location when `use lib 'lib'` is added even though the modules in question were loaded from the "installed modules" loader? Or was that answered and I didn't get it?

**Comment by niner** [comment]
@rabbiveesh please run your test with RAKUDO_MODULE_DEBUG=1
That may shine some light on why it seems to precompile.
Btw. are you actually sure it really does precompile? Or does it just create the directory structure and place some .repo-id files there? The latter do *not* mean that it precompiles.

**Comment by rabbiveesh** [comment]
Hey, you're right. It's not precompiling. What seems to be happening is
that it rechecks all the dependencies, which involves getting a checksum of
each file (seems like?), and that's what's taking all the time, not
precompilation.

I guess I'll close this now, because rechecking the dependencies is
probably something that should be done...
