### ISSUE TITLE
[JVM] RW attribute reported as readonly when setting value via qualified method name

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3399]
## The Problem
The following code (golfed from S12-methods/accessors.t) started to fail on the JVM backend a while ago. I'm pretty sure it happened after the merge of https://github.com/rakudo/rakudo/pull/3348, but I didn't properly bisect (the JVM backend is slow, you know :) ).
```
$ ./perl6-j -e 'class C { has $.foo is rw }; C.new.C::foo = 5'
Cannot assign to a readonly variable or a value
  in block <unit> at -e line 1
```

There is no error if the qualified method name is omitted:
```
$ ./perl6-j -e 'class C { has $.foo is rw }; C.new.foo = 5'
```

## Additional Observations
Accessing the value of $.foo via the qualified method name works as expected:
```
$ ./perl6-j -e 'class C { has $.foo is rw }; my $o = C.new(foo => 42); say $o.C::foo'
42
```

It looks like the container descriptor (that signals rw-ness) is missing when using the qualified method name:
```
$ ./perl6-j -e 'use nqp; class C { has $.foo is rw }; my $o = C.new(foo => 42); say nqp::isnull(nqp::getattr($o.foo, Scalar, "\$!descriptor")); say nqp::isnull(nqp::getattr($o.C::foo, Scalar, "\$!descriptor"))'
0
1
```

This code prints '0\n0' on older versions of perl6-j and on MoarVM.

## Environment
* Operating system: FreeBSD 11.3-RELEASE-p3
* Compiler version (`perl6 -v`): This is Rakudo version 2019.11-315-g5162e6f5a built on JVM
implementing Perl 6.d.

**Comment by vrurg** [comment]
Unfortunately, it's not much I can tell you on this for now. I would start digging at `dispatch:<::>`, but this is what you already know anyway. I would try checking what attributes the method it finds has.

**Comment by usev6** [comment]
I'm not totally sure, but probably the attribute was changed to read-only by 'return'. There is [a nqp::p6recont_ro involved](https://github.com/rakudo/rakudo/blob/add2ec0d49/src/core.c/control.pm6#L37), that could very well cause the problem I was seeing.
