### ISSUE TITLE
t/spec/S32-num/stress.t is flapping

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#3400]
Bisect points to

https://github.com/rakudo/rakudo/commit/a3afde603779c8eb810a15a4e635021023be36b4

**Comment by lizmat** [comment]
yeah  :-(

**Comment by Altai-man** [comment]
@lizmat after https://github.com/rakudo/rakudo/commit/b770971fff7cf4bfa218f32d809d29ddf0b3247c can we remove BLOCKER label? Are roast tests reverted?

**Comment by lizmat** [comment]
Apparently the new val() tests didn't make it to roast anyway :-(  So, yes, no more blocker.
