### ISSUE TITLE
roundrobin behave inconsistently on single list within list.

### ISSUE THREAD

**Issue by xinminglai** [rakudo/rakudo#3402]
##The Problem

my %h = %(:a<a b c>); for roundrobin(%h<>:v.map: *.flat) -> @list { @list.perl.say; }
Above code prints  «Type check failed in binding to parameter '@list'; expected Positional but got Str ("a")␤  in block <unit> at <tmp> line 1␤␤»

While this works:
my %h = %(:a<a b c>, :xx[]); for roundrobin(%h<>:v.map: *.flat) -> @list { @list.perl.say; }

OUTPUT: «("a",)␤("b",)␤("c",)

And there is inconsistency between these 2, when the hash contains only single pair will cause the bug.

The fix provided by jnthn fixes the issue.

[roundrobin-fix.txt](https://github.com/rakudo/rakudo/files/4020231/roundrobin-fix.txt)

**Comment by lizmat** [comment]
Thanks for the report!

**Comment by jnthn** [comment]
@lizmat Did it get a test too?

**Comment by lizmat** [comment]
A good point, no.

**Comment by jnthn** [comment]
OK, re-opened to make sure one happens. :-)

**Comment by lizmat** [comment]
test should be added for identical cases for `zip` and `cross`

**Comment by lizmat** [comment]
Added tests with https://github.com/perl6/roast/commit/1fa860cb91
