### ISSUE TITLE
Regression in Blin between 2019.11 and 2020.01

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3405]
## The Problem

```
➜  Blin git:(master) ✗ which perl6
/home/koto/.rakudobrew/versions/moar-2019.11/install/bin/perl6
➜  Blin git:(master) ✗ perl6 -Ilib bin/blin.p6 Cro::Core
🥞 Prep
🥞 Will use up to 4 threads for testing modules
^C⏎                                                                                                                                      ➜  Blin git:(master) ✗ rakudobrew switch moar-master
Switching to moar-master
➜  Blin git:(master) ✗ perl6 -Ilib bin/blin.p6 Cro::Core
===SORRY!=== Error while compiling /home/koto/Devel/Blin/bin/blin.p6
===SORRY!=== Error while compiling /home/koto/Devel/Blin/lib/Blin/Processing.pm6 (Blin::Processing)
Invalid typename 'Module' in parameter declaration.
at /home/koto/Devel/Blin/lib/Blin/Processing.pm6 (Blin::Processing):412
------> sub process-module(Module⏏ $module,

at /home/koto/Devel/Blin/bin/blin.p6:6
➜  Blin git:(master) ✗ perl6 --version
This is Rakudo version 2019.11-387-g734047a01 built on MoarVM version 2019.11-113-g703f023d5
implementing Perl 6.d.
```

## Expected Behavior

`Module` symbol will be available as well as `Blin::Module`, but it is not so in 2020.01.

## Steps to Reproduce

```
git clone https://github.com/perl6/Blin.git
cd Blin
perl6 -Ilib bin/blin.p6 Cro::Core
```

A thing that looks like a 100% culprit is I suspect https://github.com/rakudo/rakudo/pull/3388
cast @vrurg ?

## Environment
* Operating system: linux box
* Compiler version (`perl6 -v`): 2019.11-387-g734047a01

**Comment by AlexDaniel** [comment]
In Blin… itself? :joy:

**Comment by Altai-man** [comment]
Exactly. It is a blocker, as we can't compile a not so complex code pattern we could before.

**Comment by vrurg** [comment]
I'm not sure how to handle this correctly. The point is that `is export` is not actually needed for for `unit class`. All it did in this situation was exporting `Blin::Module` under its short name `Module`. Basically, it golfs down to:

_Bar/C.rakumod_
```perl6
unit class Bar::C is export;
```

Then:

```
use Bar::C;
say Bar::C.new; # Bar::C.new
say C.new;      # Bar::C.new
```

What #3388 changes is that `is export` now exports it as `Blin::Module`, i.e. it's rather a noop in the module. The fix for `Blin` would be to use long name which I consider as more correct things as it reduces any risk of name collisions. I would propose this change for now and if no other modules suffers would leave things as they're. Otherwise, if there're more related failures, I could make the change `6.e` specific.

PS. And what's so funny, you, fools??? 😜😂

**Comment by Altai-man** [comment]
cast @jnthn 
Is the new implemented behavior actually sane for us to break backward compatibility?

\<rant>
I am not sure how to proceed from this point, to be honest.

Latest Blin run has shown more than 700 module failures, which is an insane number. About 200 are bogus "already installed" errors, which leaves 500. Numerous were broken by Cro::TLS breakage, which is already fixed by me, but not pushed to cpan yet. Dozens are in "always broken" state, some became broken unrelated to rakudo changes, in between of releases.
Blin also suffers from "can't find Encode module" error with HTTP::UserAgent installation, which causes a large tree of failures as an outcome. Interesting how that survived before.
\</rant>

**Comment by vrurg** [comment]
@Altai-man how hard would it be to get `Blin` adapted for use of full `Blin::Module` name and have a run to see if any other modules are affected by the change?

**Comment by Altai-man** [comment]
@vrurg I am concerned that proprietary systems we don't have access to people have in production can be damaged one day. Because they'll restart something and "Oops, this type is not available anymore".
Fixes are great, additions are awesome, but sudden behavior changes are dangerous in this sense. I mean, sure, we can patch Blin, but we can't be sure that no other raku code can be affected by this.

**Comment by vrurg** [comment]
@Altai-man I agree. I have this point in mind too. Though would like to estimate the situation first. My reluctance to making it `6.e` only is that I'm dodging spaghetti code of language versions checks here and there.

**Comment by ugexe** [comment]
Well, the Encode issue looks like the same one from before -- it needs to rename its `META.info` to `META6.json` and bump its version, or users need to `zef nuke StoreDir`. Or you can use a slightly older version of zef. That was removal of a feature deprecated for awhile; zef warned to stdout every time before that it would stop working.

**Comment by AlexDaniel** [comment]
> Is the new implemented behavior actually sane for us to break backward compatibility?

No. If the tool you use to find regressions gets broken by changes in rakudo, it's quite telling. There's nothing obviously wrong in the code, I'm almost certain that people do that relatively often. It's possible it shouldn't've worked before, but it's too late now and we have keep some sort of backcompat until there's a better plan.

> I am not sure how to proceed from this point, to be honest.
>
> Latest Blin run has shown more than 700 module failures, which is an insane number.

I think we should focus on reviving as much as we can. [People have worked hard](https://github.com/perl6/ecosystem-unbitrot/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) on getting the number of broken modules as close to zero as possible. I couldn't care less what excuses are used to justify changes that break stuff, it doesn't matter. All I see is that hundreds of modules are not working as they did before and we should fix that.

**Comment by jnthn** [comment]
IMO, let's back out this change now, to have chance to think about it some more and to remove it as a release blocker.

That the `export` trait only looked at the final component was perhaps not a spectest'd behavior, but it was also the way I understood it to work (quite possibly because I considered it years back when I did the name vs. short name split in the MOP). Also note that one can always wrap the class in an enclosing `package` or `module` and stick `is export` on that in order to achieve a multi-level export.

**Comment by vrurg** [comment]
While writing this reply, I came over the following bug:

_Foo/Bar.rakumod_
```perl6
use v6;
unit package Foo is export;
role Base { }
class Base::C1 does Base { }
class Base::C2 does Base { }

```

_Foo/Baz.rakumod_
```perl6
use v6;
unit class Foo::Baz;
use Foo::Bar;
method baz(Foo::Baz:D $obj) { }
```

_script_
```perl6
use Foo::Baz;
Foo::Baz.new.baz;
```

Compilation fails with:

> ```
> Invalid typename 'Foo::Baz' in parameter declaration.
> ```

But I also found a solution which was escaping my attention all this time: it is enough to export role `Base` to get all other classes/roles under this prefix available. Though I'm still in favor of `is export` using the given name, but that's pretty much minor argument to preserve the change in the core. So, reverting it as excessive.

**Comment by Altai-man** [comment]
The change is reverted, I'll close the issue as soon as I'll rebase the release branch a bit later.
