### ISSUE TITLE
Should `Str.is-identifier` be exposed as a public method?

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#3408]
I'm not sure I see the appeal of exposing this API in the language. In my opinion it seems a bit hasty to put it into a release to speed up a call to `.raku`.

**Comment by jnthn** [comment]
Perhaps something to put in `Rakudo::Internals` somewhere if the goal is to re-use it. The concept of "identifier" is quite context-dependent.

**Comment by lizmat** [comment]
Putting it in Rakudo::Internals sort of defeats the purpose, as it needs to be a `Str` method for it to make sense.  Will renaming it to `ALLOWED-AS-KEY-IN-A-PAIR-SPECIFICATION` be ok?

**Comment by jnthn** [comment]
> Putting it in Rakudo::Internals sort of defeats the purpose, as it needs to be a Str method for it to make sense.

Why? You'd just pass the string as an argument to a method on a type object?

**Comment by lizmat** [comment]
And that makes it slower.  Since it apparently is a bad idea to expose this functionality as a `Str` method, I've made it a local `Pair` sub.  This should be slightly better than making it a `Rakudo::Internals` method.  Still makes Pair.raku 10% slower, simply because it is not a `Str` method.
