### ISSUE TITLE
ENTER fires more often than expected

### ISSUE THREAD

**Issue by rbt** [rakudo/rakudo#3411]
## The Problem
The below code snipped spits out "IN f" twice.
```
class A {
	method f {
		ENTER {say "IN f"}
		LEAVE {say "OUT f"}
		say "EXECUTE f";
	}
}

A.new().f;

```
Output:
```
IN f
IN f
EXECUTE f
OUT f
```

## Expected Behavior
ENTER block will only be fired a single time.

Output:
```
IN f
EXECUTE f
OUT f
```

## Environment
Linux rbt-inspiron-123 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.

**Comment by lizmat** [comment]
Confirmed.  Also, instantiation is not necessary: this golf shows the issue as well:

    class A {
        method f() {
            ENTER say "foo";
        }
    }
    A.f;   # foo foo

**Comment by lizmat** [comment]
Looks like it is inside the codegen of the method, as this gives the same result:

    class A {
        method f() {
            ENTER say "foo";
        }
    }
    A.^find_method("f")(A);  # foo foo

**Comment by lizmat** [comment]
Looks like `$*W.add_phasers_handling_code` is being run twice during compilation.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/blob/master/src/Perl6/Actions.nqp#L4505 and https://github.com/rakudo/rakudo/blob/master/src/Perl6/Actions.nqp#L4632 both call `$*W.add_phasers_handling_code`.  If I remove either, the `ENTER` block only is executed once.  However, different test failures occur in `make spectest` for removal of either case  :-(

**Comment by ugexe** [comment]
Note the expected result occurs if an extra scope is added:
```
perl6 -e 'class A { method f { { ENTER { say "IN f" } } } }; A.f;'
IN f
```

**Comment by lizmat** [comment]
Yeah, it only happens if the scope is a `method`.  The first call above is in `methodize_block`, and the second is in `method_def`.  It *only* happens with methods.

**Comment by lizmat** [comment]
Guess I am too tired to follow the logic of phaser handling.  Will try again tomorrow.
