### ISSUE TITLE
Attributes sometimes composed more than once on Rakudo 2019.11+ blead

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#3412]
## The Problem

Consider:
```
use Test;
my UInt %composed;

role MooishAttrHOW {
    method compose( Mu $pkg ) {
        %composed{self.name}++;
        callsame;
    }
}

multi trait_mod:<is> (Attribute:D $attr, :$mooish!) {
    $attr does MooishAttrHOW;
}

class Foo {
    has $.bar is mooish is rw;
}

is-deeply %composed<$!bar>, 1, "attribute composed once";
```

## Expected Behavior

```
$ perl6 -v; perl6 tst.raku
This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.
ok 1 - attribute composed once
```

## Actual Behavior

```
$ perl6 -v; perl6 tst.raku
This is Rakudo version 2019.11-417-g73e98a6c8 built on MoarVM version 2020.01-1-g105d09d62
implementing Perl 6.d.
not ok 1 - attribute composed once
# Failed test 'attribute composed once'
# at tst.raku line 19
# expected: 1
#      got: 2
```

## Steps to Reproduce

Only seems to be a problem when executed from a script. Problem goes away in precompiled modules.

## Environment
* Operating system: Linux toshiba 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.11-417-g73e98a6c8 built on MoarVM version 2020.01-1-g105d09d62
implementing Perl 6.d.

**Comment by Altai-man** [comment]
Bisected to https://github.com/rakudo/rakudo/commit/55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17
cast @vrurg

**Comment by vrurg** [comment]
This is expected behavior. [Here](http://blogs.perl.org/users/vadim_belman/2020/01/class-role-and-attribute-accessor.html) I explain why is it so (sorry, longread). `AttrX::Mooish` [demonstrates](https://github.com/vrurg/raku-AttrX-Mooish/blob/master/lib/AttrX/Mooish.pm6#L625) how it has to be treated.
