### ISSUE TITLE
Rebless to a custom type no longer seems to work

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#3414]
## The Problem

Rebless to a custom type no longer seem to work, or at least, no longer works the way it used to.

See: https://stackoverflow.com/questions/44486985/how-can-i-rebless-an-object-in-perl-6

First noticed by Arne Sommer (See bottom of the above linked page)

## Expected Behavior

Worked this way through 2019.03.1

    perl6 -e'class MyInt is Int { }; my $x = 42; Metamodel::Primitives.rebless( $x, MyInt); dd $x'

    MyInt $x = 42

## Actual Behavior

As of 2019.07.1

    perl6 -e'class MyInt is Int { }; my $x = 42; Metamodel::Primitives.rebless( $x, MyInt); dd $x'

    New type MyInt for Int is not a mixin type
      in block <unit> at -e line 1

Bisect log: https://gist.github.com/Whateverable/c13043b0c069803aa29900d672490412

Points to one of these commits:
https://github.com/rakudo/rakudo/commit/7b863b72aac89ddee02826266e28685b12b1f74f
https://github.com/rakudo/rakudo/commit/f09156240a52b34bc356ef715bd955c8f4378cb4
https://github.com/rakudo/rakudo/commit/7bd3b3a0a8a3c1faaef602d2d3fe1e619e4ef640

Whateverable query: https://gist.github.com/Whateverable/fbf6aece339ffef8a1b990b1c58b0da2

## Environment
* Operating system:  Linux Mint 19.3
* Compiler version (`perl6 -v`): This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d. and current Camelia

**Comment by jnthn** [comment]
You'll need to arrange to have the `is_mixin` named argument passed to `ClassHOW.new_type` (here's [new_type](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/ClassHOW.nqp#L46), and here's an [example where it's passed](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/Mixins.nqp#L84)). There's no way to do that with the `class` syntax, thus the target type of the rebless shall have to be assembled using the MOP also.
