### ISSUE TITLE
Should the GitHub organization's name and logo be changed from "Rakudo Perl"?

### ISSUE THREAD

**Issue by cxw42** [rakudo/rakudo#3416]
I noticed that https://github.com/rakudo has a "Rakudo Perl" name and logo:
![image](https://user-images.githubusercontent.com/10515894/72197781-3fe0fb80-33f3-11ea-8b1f-b5d8a6efc125.png)

Should that be changed?  I can't find an open issue in this repo, and I'm not sure where else to ask the question.  Thanks!

**Comment by jnthn** [comment]
Thanks for noticing; updated.
