### ISSUE TITLE
Int.new(Int); hangs

### ISSUE THREAD

**Issue by chrsteel** [rakudo/rakudo#3419]
## The Problem
Executing `raku -e 'Int.new(Int);'` hangs indefinitely on my system.

## Expected Behavior
I expected an error (or maybe the `Int` type object) as a result.

## Environment
* Operating system: gentoo
* Compiler version (`perl6 -v`):
```
$ raku --version
This is Rakudo version 2019.11 built on MoarVM version 2020.01
implementing Perl 6.d.
```

**Comment by AlexDaniel** [comment]
Output on all commits: https://gist.github.com/7f1cf3678a22f64c53d94a2b6d363e62

When it started hanging: (2017-09-19) https://github.com/rakudo/rakudo/commit/0834036dd436ac7372c8c0fe2f49511a4f5186dd

Also, it used to error out previously, and it stopped after: (2016-10-05) https://github.com/rakudo/rakudo/commit/798c2e2dca34e5cf93da99d1f401eb161efca854

**Comment by lizmat** [comment]
working on a fix

**Comment by lizmat** [comment]
Thanks for the report!

**Comment by Altai-man** [comment]
A test?

**Comment by lizmat** [comment]
Test was already added with https://github.com/perl6/roast/commit/e835c8296be17172733 yesterday.
