### ISSUE TITLE
Warning mentions mysterious `:so` and `:!so` syntaxes

### ISSUE THREAD

**Issue by taboege** [rakudo/rakudo#3425]
## The Problem

When smartmatching against `True` or `False`, Rakudo gives a mostly helpful suggestion:
```
Smartmatch against True always matches; if you mean to test the topic for truthiness, use :so or *.so or ?* instead
Smartmatch against False always fails; if you mean to test the topic for truthiness, use :!so or *.not or !* instead
```

But what is the `:so` or `:!so` syntax supposed to be? Looks like an adverb, but [none of the things that come to mind](https://colabti.org/irclogger/irclogger_log/raku?date=2020-01-14#l543)  actually do what the hint advertises. And no mention of such an adverb is indexed in the documentation.

I traced the origin of that warning back to 2010: c716715817e6735832604e903389453f47df5d97. Perhaps that was a feature once that has been removed?

**Comment by ab5tract** [comment]
This doesn't really match any idiomatic usage of Raku that I'm familiar with. I've never seen a truthy-ness check addressed via `:so`.

I have, however, seen people use this example of `temp $_ = Any; say 'true' if :so; say 'true' if .so'` as a direct "oh I've encountered an awkward corner case already, lol, Perl, lol!!" kneejerk example before.

More than once

**Comment by FCO** [comment]
```perl6
say “yes” if 5 ~~ :is-prime
```

Will run `is-prime` on 5 and return that casted to Bool

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by taboege** [comment]
Oh, of course! Now it's not mysterious to me anymore and it makes total sense in a hint about what to use on the RHS of a smartmatch.
