### ISSUE TITLE
LTA error when adverbing Bool (or identifiers?)

### ISSUE THREAD

**Issue by taboege** [rakudo/rakudo#3426]
## The Problem

The following code generates a less-than-awesome error message:

``` perl6
say False:so
#= Invalid type smiley 'so' used in type name
```

## Expected Behavior

The expression is invalid, but the value `False` (or anything that is an identifier?) seems to invoke a different code path than other literals. I think this is the more appropriate error:

``` perl6
say 42:so
#= You can't adverb 42
```

**Comment by jnthn** [comment]
`False:so` is parsed as a longname (just like seen in things like `token foo:bar` in grammars). Thus it never gets parsed as an operator adverb; it's been swallowed as part of the term.

**Comment by lizmat** [comment]
Hopefully improved the error message with https://github.com/rakudo/rakudo/commit/246f20db14 .  @taboege please close this ticket if you think this is enough.
