### ISSUE TITLE
ADT regression in 2020.01

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3427]
This was spotted in https://github.com/rakudo/rakudo/issues/3417

https://github.com/timo/ADT can't be installed since https://github.com/rakudo/rakudo/commit/add2ec0d491218e59e6c7a517e37458e1a6c3daf and installs just ok on 2019.11 release.

**Comment by lizmat** [comment]
Adding "raku" to the methods to be generated, makes it pass the .perl -> .raku change.  I've created a PR for that: https://github.com/timo/ADT/pull/6  .

After adding the new `is built` trait, things go bad again.  ADT actually adds Attributes programmatically using the `Attribute.new`.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/f1f690e045 fixes the issue.

**Comment by lizmat** [comment]
Turns out the PR was not needed in the end either.  So I've closed that one as well.
