### ISSUE TITLE
overload::constant regression in 2020.01

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3428]
This was spotted in https://github.com/rakudo/rakudo/issues/3417

https://github.com/FROGGS/p6-overload-constant can't be installed since https://github.com/rakudo/rakudo/commit/63f117502a93b44f12d97898eb3438417996793a yet works on 2019.11.

**Comment by lizmat** [comment]
Let me effectively revert 63f1175 and re-instate THROW.  This was an optimization, not something really important.

**Comment by lizmat** [comment]
I have now reverted the appropriate commits.  Seems that Geth is awol, so you don't see it on channel .

**Comment by lizmat** [comment]
Since this is deep throw / voodoo of which `succeed` is an integral part, I'm not going to mess with that anymore, so going to leave the situation as it is now.  Which means the problem as solved itself.  So this ticket can be closed.
