### ISSUE TITLE
Raku allows negative uint

### ISSUE THREAD

**Issue by fecundf** [rakudo/rakudo#3429]
## The Problem
    my uint $no = 2**63; say $no
prints a negative number, -9223372036854775808

## Expected Behavior
Should print positive number, 9223372036854775808

## Environment
I ran the above in the `#raku` Freenode IRC chatbot
`rakudo-moar ada7c3654: OUTPUT: «-9223372036854775808␤»`

**Comment by lizmat** [comment]
Yes, this is a known issue on at least the MoarVM backend.

**Comment by grondilu** [comment]
related issue : https://github.com/rakudo/rakudo/issues/4526

**Comment by niner** [comment]
This is fixed as of https://github.com/rakudo/rakudo/commit/4e1a772147d7a3c9171cefaee95da13f5cca5597
