### ISSUE TITLE
"Redeclaration of symbol" while using smartmatch on enums

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3431]
## The Problem

    enum Foo <bar baz>; say bar ~~ Foo
    enum Gods <þor oðin>; say þor ~~ Gods

returns "Redeclaration of symbol 'Foo'" or "Gods".

## Expected Behavior

The 6.d spec says:

> Defined Enumeration:D not does .ACCEPT an Enumeration:U

So that might be part of the "not accepting". But the fact that it fails when the enum name is some times on the right hand side, sometimes on the left hand side, is weird. It might simply be a LTA error, but no idea.

## Steps to Reproduce

Use raku 2019.11

## Environment

```
This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.
```

**Comment by Altai-man** [comment]
Can you write more steps to reproduce?
```
➜  ~ perl6 --version
This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.
➜  ~ perl6
To exit type 'exit' or '^D'
> enum Foo <bar baz>; say bar ~~ Foo
True
> ⏎                                                                             ➜  ~ 
```

**Comment by JJ** [comment]
![Captura de pantalla de 2020-01-18 13-45-31](https://user-images.githubusercontent.com/500/72663976-d5364e00-39f8-11ea-9192-22b525f02bb3.png)
If that works, turn the enum and name around.

**Comment by JJ** [comment]
Updated. The order of the first one was incorrect.

**Comment by JJ** [comment]
Well and color me surprised
![Captura de pantalla de 2020-01-18 13-54-00](https://user-images.githubusercontent.com/500/72664079-0d8a5c00-39fa-11ea-88b2-0a331c696f07.png)
Works differently if you invoke it as perl6 or if you invoke it as Raku

**Comment by JJ** [comment]
Oh, well, not really. It actually depends on... something, but it might work some times one way, and the next in another. That's why in my initial post it worked differently for the two examples.
![Captura de pantalla de 2020-01-18 13-55-43](https://user-images.githubusercontent.com/500/72664111-5c37f600-39fa-11ea-9311-2d085e6b4903.png)

**Comment by vrurg** [comment]
@JJ  Doesn't it bother you that you do have `Foo` defined by the previous statement?

**Comment by JJ** [comment]
@vrurg Er. Right. Sorry.
