### ISSUE TITLE
update-tai-utc.pl is outdated (doesn't understand we have many CORE now)

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3437]
## The Problem

Release guide suggests to use the named script to update leap seconds table, yet on running:

```
> perl tools/update-tai-utc.pl
read_file 'src/core/Rakudo/Internals.pm6' - open: No such file or directory at tools/update-tai-utc.pl line 25.
```

Apparently, it wasn't updated to know there is no `core` anymore.

**Comment by AlexDaniel** [comment]
Yeah, well, good catch. There were no leap seconds in the last three years, so I'm surprised you even noticed it :)

**Comment by Altai-man** [comment]
~Monkey sees - Monkey does~ The guide suggests -> I am doing. :)

**Comment by AlexDaniel** [comment]
To be honest I've never even tried running it, because:

> If a new leap second has been announced, src/core/Rakudo/Internals.pm will be modified

Which, by the way, feels a bit wrong. I think there should be a way to know for sure that there were no leap seconds. Also, I don't think we're exposing it to users in any way? Maybe we should.

**Comment by lizmat** [comment]
It's an internal thing.  It updates an internal table that changes every few years?

But I agree this should no longer be Perl code, but Raku instead.

**Comment by AlexDaniel** [comment]
> But I agree this should no longer be Perl code, but Raku instead.

That can be said about any script in the tools/ directory. I don't think rewriting all the tools is justified.

**Comment by AlexDaniel** [comment]
OK, actually, I think many of these scripts are not even used. I think it's safe to carefully delete some of them.

**Comment by Altai-man** [comment]
@AlexDaniel for deletion there is https://github.com/rakudo/rakudo/issues/1252
This ticket is about updating a script that has to work (or we need some means to justify removing the update, which we don't have as far as I am aware).

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/25c84b3ab8 removed this script and replaced it with a Raku script for *adding* a leap second.  Since that is what will need to be done in the future, as past values will *not* change.
