### ISSUE TITLE
Suggest "Str" type when user writes "String"

### ISSUE THREAD

**Issue by Siddhant** [rakudo/rakudo#3439]
## The Problem
I'm a beginner, so I guessed that the string type in Raku would be called "String". On using that, the compiler suggests using "Stringy". I think "Str" is the right recommendation here.
```
$ perl6
To exit type 'exit' or '^D'
> my String $test;
===SORRY!===
Type 'String' is not declared. Did you mean 'Stringy'?
------> my String⏏ $test;
Malformed my
------> my⏏ String $test;
```
## Expected Behavior
Should either suggest "Str" only, or "Str" along with "Stringy".

## Actual Behavior
See code snippet above.
## Steps to Reproduce

See code snippet above.
## Environment
* Operating system: Ubuntu 18.04 LTS running on Windows Subsystem for Linux
* Compiler version (`perl6 -v`): 
$ perl6 --version
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by AlexDaniel** [comment]
@MasterDuke17, I think you know how to tweak messages like this :)

**Comment by MasterDuke17** [comment]
@lizmat++ just handled this in https://github.com/rakudo/rakudo/commit/b291fc78aa5dcbb680bd40a0bfc4ce1169a87455

**Comment by jnthn** [comment]
Closing, because I don't think this warrants a spectest. Feel free to re-open if disagreeing.
