### ISSUE TITLE
RFE: REPL dependency check for Readline

### ISSUE THREAD

**Issue by ToddAndMargo** [rakudo/rakudo#3440]
Dear Rakudo,

Fedora 31
https://github.com/nxadm/rakudo-pkg/releases

$ rpm -qa \*rakudo\*
rakudo-pkg-2019.07.1-03.x86_64

Would you please consider the following Request for Enhancement?

When running REPL and Readline has not been installed, when you use your arrow keys, which I use a lot, you get a lot of

    my $history^[[A^[[A
    a todd special booboo^[[D^[[D^[[D^[[D^[[D

Would you please consider informing the user that Readline is missing and give zef install Readline as an example of how to install it.

Thank you for your consideration,
-T

**Comment by lucasbuchala** [comment]
Currently, the REPL already prints such message:

```
$ raku
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
> 
```

This is Rakudo version 2020.01 built on MoarVM version 2020.01.1

**Comment by ToddAndMargo** [comment]
Then I was running an out of date version.
