### ISSUE TITLE
Release 2020.01 rakudo hangs on 6.c-errata advent2011-day07.t

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3441]
When doing release from 2020.01-release branch, `t/spec/integration/advent2011-day07.t` test hangs (left on night, it didn't complete in more than 7 hours, and on a second run it hung too):

The full log of releasable run: https://gist.github.com/Altai-man/16c352ffa637a786c1e848df8255f505

## Steps to Reproduce

The long way: `VERSION=2020.01 VERSION_MOAR=2020.01.1 BRANCH_ROAST=b425a4b31fb36b91bbac15e5d63b992f6acf5bc1 BRANCH_RAKUDO=release-2020.01 BRANCH_NQP=master sake all` using sake and https://github.com/rakudo/rakudo/blob/master/tools/releasable/Sakefile
The short way: not yet found.

**Comment by Altai-man** [comment]
So this is a certainly persistent issue as I am getting it 3rd time in a row.
The bad thing is I don't have an idea how to golf down the sakefile command to anything smaller.
@AlexDaniel maybe you have some ideas?

**Comment by lizmat** [comment]
I find the number of TODO tests passing suspect?  Could this be using the wrong roast checkout?

**Comment by Altai-man** [comment]
I am setting 6(7) days old roast commit to match with the fact that release branch is a bit behind:
https://github.com/perl6/roast/commit/a5af083cd5c54c4aaa328f3ce1b2793a06fa4df0
A newer one https://github.com/perl6/roast/commit/db3fec5c30486adf9ad1f70422daabf1d1b217a0 doesn't pass test on this rakudo branch.

**Comment by Altai-man** [comment]
Trying with https://github.com/perl6/roast/commit/a5af083cd5c54c4aaa328f3ce1b2793a06fa4df0

**Comment by lizmat** [comment]
I've fixed the test with https://github.com/perl6/roast/commit/9a9ba99c1c , it is no longer hanging for me.
