### ISSUE TITLE
Code produces "Seq is already in use/consumed" error once, but subsequently works.

### ISSUE THREAD

**Issue by SirBogman** [rakudo/rakudo#3444]
## The Problem

The first time the function `f` in the following sample is called it causes an error. Subsequent calls work as expected.

```perl6
my &f = { .rotor( 1 Xxx 1 ) };
{
    say f [1,2,3];
    CATCH {
        default { say .message }
    }
}
say f [1,2,3];
```

## Expected Behavior

The output should be:
```
((1) (2) (3))
((1) (2) (3))
```

## Actual Behavior

The output is:
```
The iterator of this Seq is already in use/consumed by another Seq
(you might solve this by adding .cache on usages of the Seq, or
by assigning the Seq into an array)
((1) (2) (3))
```

## Bisected

bisect log (for the original, more complex example): https://gist.github.com/285991893013f795788c8078f67f1bee
Behavior changed in: (2017-05-05) https://github.com/rakudo/rakudo/commit/5e6b38789aeac32adc09c1977c8d2ac7251659f8
Previously works as expected.

## Notes

The following example is currently working, where I expanded `1 Xxx 1` to `((1).Seq,).Seq` using `(1 Xxx 1).perl` and then added `.cache` to the first sequence. Unfortunately, with `1 Xxx 1`, I don't think it's possible for me to cache this sequence, because it's generated internally.

```perl6
my &f = { .rotor( ((1,).Seq.cache,).Seq ) };
{
    say f [1,2,3];
    CATCH {
        default { say .message }
    }
}
say f [1,2,3];
```
This produces the expected output:
```
((1) (2) (3))
((1) (2) (3))
```

## Environment
* Operating system: macOS 10.15.2 (19C57)
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1-478-g75056dfa1 built on MoarVM version 2019.07.1-317-g1b2f72e5e
implementing Perl 6.d.

**Comment by SirBogman** [comment]
It's unclear from the error message which Seq was already in use and why it's not a problem on subsequent function calls. Is it referring to an internal Seq?

**Comment by SirBogman** [comment]
I've edited my original comment to provide a simpler way to reproduce the issue.

**Comment by lizmat** [comment]
Shortest repro of problem: `(1,2,3).rotor( 1 Xxx 1 )`.  Fixed with https://github.com/rakudo/rakudo/commit/c7e0df64cb , tests added with https://github.com/perl6/roast/commit/0e07a4d5c9

**Comment by lizmat** [comment]
@SirBogman: thanks for the report!
