### ISSUE TITLE
Build docs include non-working test sample

### ISSUE THREAD

**Issue by treyharris** [rakudo/rakudo#3448]
## The Problem

https://github.com/rakudo/rakudo/blob/0d530092fade3f5efa5fb80ed99361347fe9c8b1/README.md#running-tests

Includes the line:
```
make t/spec/S12-traits/parameterized.t
```
as an example. This test has been failing for some time.

## Expected Behavior

Running the example line with cut-and-paste passes, proving that the `make` behavior described is working.

## Actual Behavior

The test fails (see https://gist.github.com/db7dd6440564ef3c8f90efe257fce2e7 for the output).

## Suggestion

Change `t/spec/S12-traits/parameterized.t` to a test that passes.

**Comment by usev6** [comment]
Fixed with ab6710e605.

Thanks for the report!
