### ISSUE TITLE
Regression caused by compile typechecking change

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3450]
With d8e859d000fa658766266a45f99e58661dec7b0e the following code is broken:

```perl6
class Foo {
    has Int $.a;
    BEGIN {
        for ::?CLASS.^attributes -> $attr {
            if $attr.name eq '$!a' {
                $attr.set_build(-> | { 42 });
            }
        }
    };
}

say Foo.new.a;
```

Compilation fails with:

```
Can never assign default value Block (-> |c { #`(Block|1405...) to attribute '$!a', it expects: Int
```

On 2020.01 release the code produces `42` as expected.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/pull/3452 , added test with https://github.com/perl6/roast/commit/8f30f40621
