### ISSUE TITLE
S32-io/socket-recv-vs-read.t doesn't pass anymore (on FreeBSD with MoarVM only)

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3457]
## The Problem
Running a spectest (on MoarVM, rakudo commit 6c5615ecf1) gave me 13 aborted tests for S32-io/socket-recv-vs-read.t. The tests from that file passed the last time I looked (rakudo from 2020-01-24, don't know the exact commit).

Please note that the tests file still passes on the JVM backend (same commits as above).

## Steps to Reproduce
```
$ PERL6LIB=lib ./perl6-m t/spec/S32-io/socket-recv-vs-read.t
1..13
No such method 'recv' for invocant of type 'Any'
  in block <unit> at t/spec/S32-io/socket-recv-vs-read.t line 29

# You planned 13 tests, but ran 0
```

Taking a look at the failing code it seems to be this (no change if I add some sleeping before the call to ```IO::Socket::INET.new``` -- as it is done in the test file):
```
$ ./perl6-m -e 'my $hostname = "localhost"; my $port = 5002; my ($send-rest, $client); IO::Socket::Async.listen($hostname, $port).tap(-> $conn { $conn.print("first thing"); await $send-rest; $conn.print("another thing"); $conn.close; }); $send-rest = Promise.new; $client = IO::Socket::INET.new(:host("$hostname:$port"));'
Could not connect socket: Connection refused
  in block <unit> at -e line 1
```

It works if IO::Socket::Async.listen is called with ```127.0.0.1``` instead of ```localhost``` as its first argument. (IO::Socket::INET.new still uses ```localhost```):
```
$ ./perl6-m -e 'my $hostname = "localhost"; my $port = 5002; my ($send-rest, $client); IO::Socket::Async.listen("127.0.0.1", $port).tap(-> $conn { $conn.print("first thing"); await $send-rest; $conn.print("another thing"); $conn.close; }); $send-rest = Promise.new; sleep 0.2; $client = IO::Socket::INET.new(:host("$hostname:$port"));'
```

## Environment
* Operating system: FreeBSD 11.3-RELEASE-p6
* Compiler version (`perl6 -v`): This is Rakudo version 2020.01-56-g6c5615ecf built on MoarVM version 2020.01.1-2-gcbb04d462
implementing Perl 6.d.

The host is configured for IPv6 and IPv4.
```
$ grep localhost /etc/hosts
::1                     localhost localhost.my.domain
127.0.0.1               localhost localhost.my.domain
$ ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
```

**Comment by usev6** [comment]
It doesn't happen on Linux. From #raku-dev 2020-02-01:
```
12:29 < nine> bartolin: FWIW I've failed to reproduce the issue on Linux. So I guess it's FreeBSD specific.
```

**Comment by usev6** [comment]
The first bad commit is a NQP bump for IP6NS changes: bae5fc7d49

**Comment by Altai-man** [comment]
cast @Kaiepi ?

**Comment by usev6** [comment]
I'm pretty sure the behaviour changed with https://github.com/MoarVM/MoarVM/commit/ca2a4c4c52. The difference that was introduced with this commit between ```IO::Socket::Async.listen()``` and ```IO::Socket::INET.new()``` seems to be, that the flag ```passive``` when calling ```MVM_io_resolve_host_name``` is ```1``` in the first case and ```0``` in the second case.

This seems to make a difference on FreeBSD, but not on Linux. If I'm not mistaken, the following test program shows the difference. The call to getaddrinfo() mimics what MoarVM does in https://github.com/MoarVM/MoarVM/blob/0736761163/src/io/syncsocket.c#L286-L399. (I've just copied some examples from the internet, but I hope it proves my point.)

```
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <netinet/in.h>
#include <arpa/inet.h>

void print_first_ip(int passive) {
    struct addrinfo hints, *addrinfo;
    int error;

    memset(&hints, 0, sizeof(hints));

    hints.ai_flags = AI_ADDRCONFIG | AI_NUMERICSERV | passive;
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = 0;
    hints.ai_protocol = 0;

    printf("resolving \"localhost\" with passive == %i\n", passive);
    error = getaddrinfo("localhost", "5002", &hints, &addrinfo);

    if (error || !addrinfo) {
        printf("getaddrinfo failed with code %i.\n", error);                                                                                                                                                                                   
    }
    else {
        int sa_family = ((struct sockaddr*)addrinfo->ai_addr)->sa_family;
        if (sa_family == AF_INET6) {
            char straddr[INET6_ADDRSTRLEN];
            struct sockaddr_in6* _ai_addr_ptr=(struct sockaddr_in6*)addrinfo->ai_addr;
            struct sockaddr_in6 _ai_addr=*_ai_addr_ptr;

            inet_ntop(AF_INET6, &_ai_addr.sin6_addr, straddr, sizeof(straddr));
            printf("%s\n", straddr);
        }
        else if (sa_family == AF_INET ) {
            printf("%s\n", inet_ntoa( ((struct sockaddr_in*)addrinfo->ai_addr)->sin_addr ));
        }
    }
}

int main() {
    print_first_ip(0);
    print_first_ip(1);
    return(0);
}
```

The output when running this program differs between Linux and FreeBSD:
```
linux$ ./print_address
resolving "localhost" with passive == 0
127.0.0.1
resolving "localhost" with passive == 1
127.0.0.1
```

```
freebsd$ ./print_address
resolving "localhost" with passive == 0
127.0.0.1
resolving "localhost" with passive == 1
::1
```

**Comment by Kaiepi** [comment]
Odd.. as far as my understanding goes, the `AI_PASSIVE` flag is only relevant when passing a null hostname to `getaddrinfo`, where it decides whether `0.0.0.0`/`::` or `127.0.0.1`/`::1` gets used, but doing this isn't even supported as of now. This is the case on OpenBSD and Linux, but maybe not FreeBSD. I'll take a look at what's going on more closely on my FreeBSD system.

**Comment by usev6** [comment]
I guess, it is this part of getaddrinfo(). It checks for AI_PASSIVE and reorders the list for active connections: https://svnweb.freebsd.org/base/release/11.3.0/lib/libc/net/getaddrinfo.c?view=markup#l639

**Comment by usev6** [comment]
For the record: From the output of ```ip6addrctl``` it looks like my machine prefers IPv4 over IPv6.

```
# ip6addrctl 
Prefix                          Prec Label      Use
::1/128                           50     0        0
::/0                              40     1       22
::ffff:0.0.0.0/96                100     4        0
2002::/16                         30     2        0
2001::/32                          5     5        0
fc00::/7                           3    13        0
::/96                              1     3        0
fec0::/10                          1    11        0
3ffe::/16                          1    12        0
```

I didn't configure that explicitly. If I change it to prefer IPv6 over IPv4 (taking the rules from /etc/rc.d/ip6addrctl) the tests from S32-io/socket-recv-vs-read.t are passing.

```
# ip6addrctl
Prefix                          Prec Label      Use
::1/128                           50     0        0
::/0                              40     1        0
::ffff:0.0.0.0/96                 35     4        0
2002::/16                         30     2        0
2001::/32                          5     5        0
fc00::/7                           3    13        0
::/96                              1     3        0
fec0::/10                          1    11        0
3ffe::/16                          1    12        0
```

But I don't think we should assume a specific setup for roast.

BTW, reading throug https://tools.ietf.org/html/rfc3484 I've found this statement:

> Well-behaved applications SHOULD iterate through the list of
>  addresses returned from getaddrinfo() until they find a working
>  address.

So, maybe we need to do more work in MoarVM and try to connect to different addresses?

**Comment by Kaiepi** [comment]
The way DNS is handled is a problem I'm aware of and have a problem solving issue open for (https://github.com/Raku/problem-solving/issues/111), but was hoping would be something that could be solved after the IP6NS grant. The original behaviour WRT address resolution was to always use `AI_PASSIVE`, which seems to work, but is a behaviour I'm pretty wary of. For the time being, MoarVM could use the old behaviour again, but I think a solution to that issue may be needed before I can continue with the work the grant originally included.
