### ISSUE TITLE
Issue with native num on Windows

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#3459]
##  The Problem

Unless I move the following tests to the top of the file, t\spec\S32-temporal\DateTime.t exits prematurely with error code 5 on Windows 10:

```raku
# --------------------------------------------------------------------
# L<S32::Temporal/C<DateTime>/'one additional constructor: now'>
# --------------------------------------------------------------------

{
    my $t = time;
    Nil while time == $t; # loop until the next second
    $t = time;
    my $dt1 = DateTime.new($t);
    my $dt2 = DateTime.now.utc;        # $dt1 and $dt2 might differ very occasionally
    is show-dt($dt1), show-dt($dt2), 'DateTime.now uses current time';

    $t = time;
    Nil while time == $t;
    $t = time;
    $dt1 = DateTime.new($t);
    $dt2 = DateTime.now(
        timezone => 22*60*60,
        formatter => { ~($^x.hour) });
    is ~$dt2, ~(($dt1.hour + 22) % 24), 'DateTime.now with time zone and formatter';

    is-approx(DateTime.now.Instant, now,
        'DateTime.now agrees with now pseudo-constant');
}

# RT #127170
{
    my role Foo { has @.a = 7, 8, 9 }
    my class BarDate is DateTime does Foo {}
    is-deeply BarDate.now.a, [7, 8, 9],
        'did role attributes get initialized ok';
}

```

## Expected Behavior

The tests should pass no matter where they are in the file.

## Actual Behavior

On Windows 10, the script exits with error code 5 when the first `DateTime.now` in the quoted code is encountered in its current location.

## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`): This is Rakudo version 2019.11-597-gaaf9a93e4 built on MoarVM version 2020.01.1-2-gcbb04d462
implementing Raku 6.d.

**Comment by dumarchie** [comment]
The bug appears to be triggered by the following test:

```raku
dies-ok  { dt month => 1, day => 32 }, 'DateTime rejects January 32';
```

**Comment by dumarchie** [comment]
The bug disappears if I replace `nqp::time_n` with `nqp::time_i` in `DateTime`'s method `now`.

So this appears to be an issue with the `nqp::time_n` implementation.

**Comment by MasterDuke17** [comment]
`nqp::time_n` and `nqp::time_i` have almost the exact same implementation (https://github.com/MoarVM/MoarVM/blob/master/src/io/procops.c#L1092-L1100). The win32 implementation of `MVM_platform_now()` (https://github.com/MoarVM/MoarVM/blob/master/src/platform/win32/time.c#L12-L17) is pretty simple, maybe you can figure something out (I don't have a windows machine to test on).

**Comment by dumarchie** [comment]
I was looking at the C source already. I don't know much C but it appears as if some parentheses are missing in the body of `MVM_proc_time_n`.

**Comment by dumarchie** [comment]
I'm out of my depth here, but https://docs.microsoft.com/nl-nl/windows/win32/api/minwinbase/ns-minwinbase-filetime states:

> Do not cast a pointer to a **FILETIME** structure to either a **ULARGE_INTEGER\*** or **__int64\*** value because it can cause alignment faults on 64-bit Windows.

In https://stackoverflow.com/questions/32470442/c-beginner-how-to-use-getsystemtimeasfiletime/32470582#32470582 it is demonstrated how to get something useful out of a `FILETIME`.

**Comment by dumarchie** [comment]
@MasterDuke17, I'll happily rebuild Rakudo from scratch if you would like me to test a change in the MoarVM code.

**Comment by MasterDuke17** [comment]
@dumarchie the nice thing about making changes to MoarVM is that you usually don't have to rebuild NQP or Rakudo. If you just adapted the code you found in that stackoverflow answer to the windows `MVM_platform_now()`, you should just be able to `make install` in the moarvm directory and rakudo will pick up the changes without needing to rebuild. So you can add in debugging prints and such easily to help with making the changes.

**Comment by dumarchie** [comment]
Okay, I'll have a go at it tonight.

**Comment by dumarchie** [comment]
@MasterDuke17, didn't find anything wrong with `MVM_platform_now()` or `MVMnum64 MVM_proc_time_n`, but I found a solution (or workaround) in Rakudo. Can you have a look at the PR?

Maybe you understand why boxing the result of `nqp::time_n()` is apparently required on Windows only.

**Comment by dumarchie** [comment]
The issue also disappears when `proto method new` is changed to explicitly dispatch to the first `.cando` candidate. So the root cause appears to be an intermittent issue with multi dispatch when the first argument is a native `num`.

**Comment by dumarchie** [comment]
The [workaround](/rakudo/rakudo/pull/3463) for the `DateTime.now` issue resolves the following spectest failures on my Windows box:

```
t\spec\S32-temporal\DateTime-Instant-Duration.t                 (Wstat: 1280 Tests: 59 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 64 tests but ran 59.
t\spec\S32-temporal\DateTime.t                                  (Wstat: 1280 Tests: 118 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 306 tests but ran 118.
t\spec\S32-temporal\local.rakudo.moar                           (Wstat: 1280 Tests: 1 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 25 tests but ran 1.
```

It does _not_ resolve the following failures that are also caused by an early exit with status 5:

```
t\spec\S02-types\num.rakudo.moar                                (Wstat: 1280 Tests: 79 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 108 tests but ran 79.
t\spec\S32-num\narrow.t                                         (Wstat: 1280 Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 17 tests but ran 0.
```
I think this clearly points to an issue with `num`.

**Comment by lizmat** [comment]
Could you paste the output of the test script runs with `--ll-exception` ?

**Comment by dumarchie** [comment]
When running each test separately with `--ll-exception`,

* **t\spec\S32-temporal\DateTime-Instant-Duration.t** and **t\spec\S32-temporal\DateTime.t**  exit early without displaying a backtrace
* **t\spec\S32-temporal\local.rakudo.moar**, **t\spec\S02-types\num.rakudo.moar** and  **t\spec\S32-num\narrow.t** run to completion

**Comment by jnthn** [comment]
> exit early without displaying a backtrace

What happens if doing `echo %ERRORLEVEL%` after those two?

**Comment by dumarchie** [comment]
In both cases the `%ERRORLEVEL%` is -1073741819

**Comment by Altai-man** [comment]
Was it resolved?

**Comment by MasterDuke17** [comment]
Nope, still troubleshooting in #raku-dev

**Comment by dumarchie** [comment]
This issue was fixed by https://github.com/MoarVM/MoarVM/commit/dd20883c34f69c607d7741935d5284983d5f499a
