### ISSUE TITLE
Can't use stubs across multiple files

### ISSUE THREAD

**Issue by ALANVF** [rakudo/rakudo#3460]
## The Problem
Stubbed classes/roles/modules in a module can't be used in other files for the module.

An example of something that does work:
`lib/MyMod.pm6`
```raku
unit module MyMod;
class A is export {...}
class A {}
```

An example that doesn't work:
`lib/MyMod.pm6`
```raku
unit module MyMod;
class A is export {...}
use MyMod::A;
```

`lib/MyMod/A.pm6`
```raku
class MyMod::A {}
```

## Expected Behavior
The module compiles successfully.

## Actual Behavior
It returns an error: ```
===SORRY!===
P6M Merging GLOBAL symbols failed: duplicate definition of symbol A```

## Steps to Reproduce

1) Create the files/directories described in the example that doesn't work.
2) Create `main.p6` containing
```raku
use lib './lib';
use MyMod;
```
3) run as `perl6 main.p6`

## Environment
* Operating system: Ubuntu 0.18.04.1
* Compiler version (`perl6 -v`): 2019.07.1

**Comment by vrurg** [comment]
It doesn't work this way. A forward declaration must be completed within scope of its compunit. A package-like object (a class in this case) defined externally is in fact a different object. The error you receive is a legitimate message.

**Comment by ALANVF** [comment]
Thanks for responding. The docs never explained that so I wasn't sure why it wasn't working.

**Comment by jonathanstowe** [comment]
If you don't feel that the forward declaration is documented well enough it might be worth dropping an issue in https://github.com/Raku/doc
