### ISSUE TITLE
CircleCI blocks Windows builds

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#3462]
CircleCI currently blocks Windows builds for the rakudo organization, stating there are no credits left.
AFAIK we should have:

- 2.500 Windows credits
- 40.000 Linux credits
- 25.000 MacOS credits

As there are currently only automated Linux and MacOS builds, the Windows credits should still be available.
I don't have permissions to view the orginization settings to check what's up with the credits.
Can someone have a look?

**Comment by ugexe** [comment]
Ah sorry I forgot about this. I will try and look later... otherwise @moritz should have more access than anyone.

**Comment by moritz** [comment]
https://circleci.com/gh/organizations/rakudo/settings says

Plan: Free, 1 concurrent job with access to Linux and Windows builds on Small and Medium sizes  
Credits:2,500 credits per week  
Credits Avaliable: 0 (0%)  
Support: Community

and https://circleci.com/gh/organizations/rakudo/settings#usage says

You have used 0/2,500 credits. Free credits will refresh on Sunday, February 9 12:00 AM UTC.

How both 0% can be available and 0 of 2500 have been used up at the same time is a riddle to me.

**Comment by patrickbkr** [comment]
I have written an e-mail to the CircleCI team about this. Hopefully they can clear up the confusion.

**Comment by patrickbkr** [comment]
After a lot of back and forth the CircleCI support has forwarded this to the development department. That was some months ago. Since then nothing has changed as far as I know. This has led me to switch all of our CI over to Azure. All other CI integrations, including CircleCI, are destined to be shut down soon-ish. So I'm closing this.
