### ISSUE TITLE
Varying results despite fixed srand seed

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#3469]
## The Problem
A constant seed to srand should give repeatable results, but .pick and .roll results vary

## Steps to Reproduce
sub t ($s) { srand($s); say (^100).roll}; t(1) for 1..3

## Environment
First seen on Rakudo version 2020.01-76-ge1faa704e built on MoarVM version 2020.01.1-25-g9709537d9, subsequent to the 'libtommath' update.

This behavior is not being caught by the tests in S32-num/rand.rakudo.moar because it only tests srand with .rand, not .roll or .pick

**Comment by Altai-man** [comment]
Perhaps @MasterDuke17 can help with this?

**Comment by lizmat** [comment]
It appears that `nqp::rand_I()' is *not* paying to the `srand` seed, whereas `nqp::rand_n()` *is*.  Bisecting this code:

    use nqp; for ^10 { srand(1); dd nqp::rand_I(100,Int) }

brings up https://github.com/rakudo/rakudo/commit/f8b9d027594b385e8d5c646f62f799e703777ba9 as the offending commit.

**Comment by lizmat** [comment]
Tests added with https://github.com/rakudo/rakudo/commit/21320191e6

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/f95bf76a7b
