### ISSUE TITLE
Platform-specific (MacOS 'El Capitan') failure in S32-list/pick.t

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#3470]
## The Problem
On one platform (MacOS 'El Capitan') a test in S32-list/pick.t fails.  Linux/Ubuntu works fine.

## Actual Behavior
Error randomizing a big integer: Invalid error code
   at SETTING::src/core.c/Range.pm6:488  (/Users/dhoekman/.rakudobrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:roll)

## Steps to Reproduce
`my $v = 2; for (1..31) { is ([+|] ((^$v).pick for ^162)), $v - 1 ; $v +<= 1 }
`

Note that the original test is as below, but the limits used above show the exact iteration at which the failure occurs.

`my $v = 2; for (1..259) { is ([+|] ((^$v).pick for ^200)), $v - 1 ; $v +<= 1 }
`
## Environment
I'm seeing this only on an older MacOS ('El Capitan'):
Darwin Mac-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

First noticed on:
Rakudo version 2020.01-76-ge1faa704e built on MoarVM version 2020.01.1-25-g9709537d9

It may be there's no easy fix (this is an older OS, with increasingly out-of-date libraries) but I report in case it illuminates other issues related .pick or `libtommath`.  Direct tests on with `libtommath` package showed no errors.

## See Also

The test that's failing was added in response to an older issue:

https://github.com/Raku/old-issue-tracker/issues/2633

**Comment by Altai-man** [comment]
Is it a regression after 2020.01 or?

**Comment by SqrtNegInf** [comment]
As with https://github.com/rakudo/rakudo/issues/3469 it appeared around the time of the commit https://github.com/rakudo/rakudo/commit/f8b9d027594b385e8d5c646f62f799e703777ba9  

It was definitely not present the previous day with the build:

Rakudo version 2020.01-70-gc1b8ff60f built on MoarVM version 2020.01.1-2-gcbb04d462

**Comment by SqrtNegInf** [comment]
I can confirm that the problem is fixed on older MacOS (10.11, 10.13).
