### ISSUE TITLE
rakudo-history is still written to ~/.perl6

### ISSUE THREAD

**Issue by voegelas** [rakudo/rakudo#3476]
## The Problem

Modules are now stored in ~/.raku, but the readline history is still written to ~/.perl6/rakudo-history in src/core.c/REPL.pm6. Is this intended or something that ought to be changed?

```
method history-file(--> Str:D) {
    without $!history-file {
        $!history-file = $*ENV<RAKUDO_HIST>
          ?? $*ENV<RAKUDO_HIST>.IO
          !! ($*HOME || $*TMPDIR).add('.perl6/rakudo-history');
```

## Expected Behavior

The history file is created in ~/.raku.

## Actual Behavior

The history is still read from and written to the ~/.perl6 directory.

## Steps to Reproduce

Install [per6-readline](https://github.com/drforr/perl6-readline), run the rakudo interpreter, enter an expression and exit the REPL. Rakudo creates the directory ~/.perl6 and the file rakudo-history.

## Environment

* Operating system: Slackware Linux Current 64-bit
* Compiler version (`perl6 -v`): Rakudo version 2020.01 built on MoarVM version 2020.01.1

**Comment by jnthn** [comment]
In general, the migration is gradual rather than everything at once. This one should change, though question is if it's worth the logic to try and look for the previous location as well as the new one, so folks don't find themselves with missing history after upgrading.

**Comment by voegelas** [comment]
In my opinion a hint in docs/ChangeLog to move the history file manually would be enough.

**Comment by lizmat** [comment]
Too bad, I've already written the migration code: https://github.com/rakudo/rakudo/commit/c5c98dea2b

**Comment by lizmat** [comment]
Thanks for the report!
