### ISSUE TITLE
Build process calling Raku does not use `--ll-exception`

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3478]
The places in the build process that actually run Raku code on the just created executable, do **NOT** set the `--ll-exception` parameter, causing incomplete information when something goes wrong.

This specifically happens when doing some types of core development, where some rather deep internals are refactored.  Such refactorings often do not affect building of Raku itself, but *do* affect execution, to the point of failure.  For such situations, it would be nice to have a *full* stacktrace.  And if all goes well with building, the extra parameter would not make a difference at all.

I tried looking for "install-dist", but came up empty, so I have *no* idea where to tweak this.

**Comment by MasterDuke17** [comment]
Maybe somewhere around https://github.com/perl6/nqp-configure/blob/326895a2e462f652cdb845174b771c13bfe2001a/lib/NQP/Config.pm#L689-L690 ?

**Comment by MasterDuke17** [comment]
Hm, that might not be right. Maybe https://github.com/rakudo/rakudo/blob/master/tools/templates/Makefile-backend-common.in#L18 ? Or at least somewhere in that file.

**Comment by vrurg** [comment]
@lizmat What exact stage causing the problem?

**Comment by vrurg** [comment]
Ok, deriving from mention of `install-dist`, I guess the point of problem is `install-post` target. So, as a quick fix you could stick in the parameter manually at that location. If you need to re-generate the `Makefile`, then best place to do it would be _tools/templates/Makefile-backend-common.in_. For more thorough fix I'd need to check a couple of things.

**Comment by vrurg** [comment]
@lizmat could you, pls, verify and re-open if not solved.

**Comment by lizmat** [comment]
I've verified (adding a `die` to `install-core-dist.raku`) and indeed produces an `--ll-exception` backtrace.  vrurg++  !
