### ISSUE TITLE
inconsistency between `my Int() $a = "42";`  and  `my (Int() $a) = "42"`

### ISSUE THREAD

**Issue by xinminglai** [rakudo/rakudo#3479]
## The Problem

`my Int() $a = "42";` raises error Error while compiling <tmp>␤Coercion Int(Any) is insufficiently type-like to qualify a variable␤`
While `my (Int() $a) = "42";` succeeds.

## Expected Behavior

I think, ATM, We should make my (Int() $a) raise the same error as my Int() $a;

But if we can make the var declaration coercive, something like `my Int() $a = "a"` would be best.

## Environment
* Operating system:  linux
* Compiler version (`perl6 -v`): 

This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

**Comment by jonathanstowe** [comment]
I think this is the same thing as #3298

**Comment by xinminglai** [comment]
Ok, So, This is already discussed.
Thanks for your info, I'll close the issue.
