### ISSUE TITLE
Signatures with `where` clauses of types parameterized with generics throw when typechecking

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3485]
## The Problem
In my `Kind::Subset::Parametric` module, I have a set of unit tests for a contravariant parametric subset that currently does not work, and doesn't work with roles either. I golfed the issue down to this:

```perl6
role Foo[\] { }
class Bar {
    proto method baz($ --> Bool:D)                 {*}
    multi method baz(::T: $ where Foo[T] --> True) { }
    multi method baz($ --> False)                  { }
}

say Bar.baz: Foo[Bar];
```

## Expected Behavior
This should output `True`.

## Actual Behavior
The typecheck for the call to `Bar.baz` throws:

```
Cannot find method 'ACCEPTS' on object of type T
  in method baz at test.raku line 4
  in block <unit> at test.raku line 8
```

## Steps to Reproduce

Save the test code as `test.raku` and run it.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.6 GENERIC.MP#644 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2020.01-213-g246f20db1 built on MoarVM version 2020.01.1-39-g657b536cf
implementing Raku 6.d.

**Comment by vrurg** [comment]
Looks like more  #3486 is a golfed down version of this issue. `where` creates an anonymous subset actually.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/fc45a415d1
