### ISSUE TITLE
Subsets lack support for generics

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3486]
## The Problem
It's possible to create subsets that wind up with generics in their refinee or refinement:

```perl6
role Foo {
    my subset Bar of ::?CLASS;
    method bar(Bar: --> True) { }
}

say Foo.new.bar;
```

This is kind of a niche edge case normally, but becomes more of a problem when using `Kind::Subset::Parametric`.

## Expected Behavior
This should output `True`.

## Actual Behavior
This results in a compiler error:

```perl6
bastille% raku test.raku
===SORRY!===
Cannot find method 'nominalize' on object of type Perl6::Metamodel::GenericHOW
```

## Steps to Reproduce

Save the test code as `test.raku` and run it.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.6 GENERIC.MP#644 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2020.01-213-g246f20db1 built on MoarVM version 2020.01.1-39-g657b536cf
implementing Raku 6.d.

**Comment by Kaiepi** [comment]
It's been a while since I originally ran into this, but `Kind::Subset::Parametric` being a mixin for `Metamodel::SubsetHOW`, I tried to fix this by giving the HOW support for generics. IIRC, code like this ended up throwing some sort of signature binder error, so there may be a combination of issues involved with this.

**Comment by jonathanstowe** [comment]
For reference changing the `::?CLASS` to `::?ROLE` there works fine.

**Comment by vrurg** [comment]
A quick look into the problem.

It doesn't matter where the subset is used in a role. The key problem is that subsets are never getting instantiated and thus any use of subset defined against a generic could (and most likely will) result in a error. I.e., the following:

```perl6
method foo { my Bar $v = self.new }
```

fails with `X::TypeCheck::Assignment`.

**Comment by jnthn** [comment]
Further, it's not clear how it ever could be instantiated; there's no meta-level relationship between the `subset` and the enclosing `role`. For that to work, roles would probably need to become rather more macro-esque.

**Comment by vrurg** [comment]
Perhaps, it makes sense to raise 'no implemented yet' kind of error for a subset with generic base? Because so far it looks like the only viable solution is run-time construction of a subset. `EVAL` do it for type captures. Got no time to test another variants.

**Comment by lizmat** [comment]
```
% raku -e 'role Foo { my subset Bar of ::?CLASS }'
===SORRY!=== Error while compiling -e
Use of a generic as 'of' type of a subset is not implemented yet
```
