### ISSUE TITLE
6.c/d-errata and S06-signature/introspection.t

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3492]
## The Problem

https://github.com/perl6/roast/blob/master/S06-signature/introspection.t does not pass on 6.c-errata and 6.d-errata branches, with or without https://github.com/perl6/roast/commit/e92bc17a24bafeb8320897132974710ef170e568#diff-9a587e599f788822d2ab875ad7fdc50f from master.

It is not visible when doing a separate test, but is reliable during make spectest / make stresstest, thus blocking release.

## Environment
* Operating system: gnu/linux box, my local void one and debian one.
* Compiler version (`perl6 -v`): 6844be9dd9b1d1660a7a9e682ff0aa772eb0212f

**Comment by jnthn** [comment]
You can reproduce it with:

```
make t/spec/S06-signature/introspection.t
```

Rather than having to run the whole test suite. It also does fail for me when run directly too, however.

**Comment by Altai-man** [comment]
I did `z t S06-signature/introspection.t` instead and it worked, maybe it somehow differ (though this seems unlikely for me). Glad it to be reproducible in an easy way though.

**Comment by jnthn** [comment]
```
13:13 < jnthn> bisectable6: 2020.01 HEAD say :($ is raw where True, $ is copy, Int $ is rw, $ is 
               raw where True = 2).perl
13:13 < bisectable6> jnthn, Using old=2020.01 new=HEAD in an attempt to do what you mean
13:13 < bisectable6> jnthn, Bisecting by output (old=2020.01 new=9217b1c) because on both starting 
                     points the exit code is 0
13:13 < bisectable6> jnthn, bisect log: https://gist.github.com/b7992194f19d10fc260ee8225cc2dd15
13:13 < bisectable6> jnthn, (2020-01-17) 
https://github.com/rakudo/rakudo/commit/3f6a2a2225f410e1aa62c3e3812c2810da3cd756

```

**Comment by Altai-man** [comment]
Closed by https://github.com/rakudo/rakudo/commit/2aa4d09596

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/2aa4d09596 test added with https://github.com/perl6/roast/commit/d0ee46628c
