### ISSUE TITLE
[WIP] Blin 2020.02

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3494]
(aside from https://github.com/rakudo/rakudo/issues/3492 which is a release requirement as well)

Current Blin outcome:

- [x] [Date::Calendar::CopticEthiopic](https://gist.github.com/Altai-man/6859eba5677670df029ceedf3be6d3ba) and [Date::Calendar::Hebrew](https://gist.github.com/Altai-man/d7e1b4724b3faabfeb461b23677d5297) by 67022d4c673f2a3e8bbc0157b95fccf73aa007c ping @lizmat 
- [x] [Date::WorkdayCalendar](https://gist.github.com/Altai-man/0c9bb40e5f9147a32866f77e50947a8b) by https://github.com/rakudo/rakudo/commit/16962c8417519795830140637f88bdb5c1b3a6e8 ping @lizmat 
- [x] [DateTime::Format::W3CDTF](https://gist.github.com/Altai-man/f7bd1192a8bfaa99ea8c88ae6192fe33) by a331ac4d1beb0d9b3799072ebfa5e12a4b54b673 ping @lizmat

**Comment by lizmat** [comment]
Looks like the Date::Calendar::CopticEthiopoc and Date::Calendar::Hebrew cases are actually problems with Date::Calendar::Strftime in the t/02-test-meta.t test.

**Comment by Altai-man** [comment]
How so?

```
===> Testing: Date::Calendar::Strftime:ver<0.0.3>:auth<cpan:JFORGET>
===> Testing [OK] for Date::Calendar::Strftime:ver<0.0.3>:auth<cpan:JFORGET>
```
is the output for 99b67a4b6adb85952e423fbb92288ef3a145e136

**Comment by lizmat** [comment]
Not for me...

**Comment by lizmat** [comment]
Ok, turned out that I had older versions of License::SPDX and JSON::Class installed.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/2b7d5ffeb8 should fix the Date::Calendar::CopticEthiopoc and Date::Calendar::Hebrew issue.

**Comment by lizmat** [comment]
I can't get `DateTime::Format::W3CDTF` to fail anymore, so I assume https://github.com/rakudo/rakudo/commit/2b7d5ffeb8 also fixed this one, despite the bisect showing a different commit.

**Comment by lizmat** [comment]
`Date::WorkdayCalendar` fixed with https://github.com/rakudo/rakudo/commit/0286904b45
