### ISSUE TITLE
Date formatting is lost after 28 days

### ISSUE THREAD

**Issue by andemark** [rakudo/rakudo#3497]
## The Problem
While solving the Raku Weekly Challenge 48 I came across an issue where the Date formatter is lost after being incremented past 28 days. I googled and came across this...

https://stackoverflow.com/questions/57270373/date-object-forgets-formatter

but it looks like there is still a problem. 

Here is a minimal program.

#!/usr/bin/env perl6

my $mdy = sub ($self) { 
                        sprintf "%02d%02d%04d", .month, .day, .year given $self;
                    }     

my $dt = Date.new(
    year         => 2000,
    month     => 1,
    day          => 1,
    formatter => $mdy
);

for (1 .. 50) {
    say $dt;
    $dt += 1;
}

## Expected Behavior
...
01262000
01272000
01282000
01292000
01302000
01312000
02012000
02022000
02032000
...

## Actual Behavior
...
01262000
01272000
01282000
2000-01-29
2000-01-30
2000-01-31
2000-02-01
2000-02-02
2000-02-03
...

## Environment
* Operating system: Windows and FreeBSD 
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

**Comment by lizmat** [comment]
This code runs correctly on HEAD, so is fixed since then.  Could you try out the Rakudo Star RC-1 at https://dist.tyil.nl/raku/rakudo-star/ to see if that fixes your problem?  Thank you!

**Comment by andemark** [comment]
Yep, it works under RC-1. 

This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.

Thanks!
