### ISSUE TITLE
multi method dispatch doesn't work with inheritance.

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3499]
## The Problem

When both parent and child classes define `proto` calling `nextsame` in a child `multi` method doesn't dispatch to parent even if child's dispatcher exhausted.

## Expected Behavior

Must dispatch.

## Steps to Reproduce

```perl6
class Foo {
    proto method foo(|) {*}
    multi method foo(Str:D $s) { note "Foo Str:D"; nextsame }
    multi method foo(Any:D) { note "Foo Any:D"; nextsame }
}
class Bar is Foo {
    proto method foo(|) {*}
    multi method foo(Str $s) { note "Bar Str"; nextsame }
    multi method foo(Any) { note "Bar Any"; nextsame }
}
Bar.new.foo("foo");
```

This code outputs:

```
Bar Str
Bar Any
```

instead of expected:

```
Bar Str
Bar Any
Foo Str:D
Foo Any:D
```

**Comment by jnthn** [comment]
I don't think this is anything much to do with the multi method dispatch, and more about `nextsame` and friends not continuing the iteration beyond the initial set of multi candidates found. When we have a `proto` and a subclass adds methods, the `proto` is cloned and placed into the subclass, and the multi methods of the subclass added to it. All candidates up to the point of the `proto` are thus known, and the invocant then behaves as a normal argument for the purpose of the multiple dispatch. This means in the typical case where you don't declare another `proto` in a subclass, then all the `multi` candidates are to hand for `nextsame`.

**Comment by vrurg** [comment]
BTW, the process of clonging `proto` and adding another candidate in a child is where another bug is lurking. I didn't have time yesterday to report it separately.

Anyway, I don't see why should we change `nextsame` (and others of the family). They're implemented to be agnostic of what they're dispatching over and this is good. As I thought of it overnight, The right thing would be to teach `MethodDispatcher` of handling `multi`s. In #3500 I took it from the point of view of `MultiDispatcher` but that's wrong and resulted in somewhat overcomplicated and still buggy code.
