### ISSUE TITLE
building rakudo on android fails on .a files

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#3505]
## The Problem

I am on an `aarch64` phone running `Android 10` and a Linux environment under [Termux](https://termux.com/). It comes with `clang 9.0.1` and `perl 5.30` (the latter runs all of my `.pl` scripts fine, can install `CPAN` modules, etc. etc.; it seems to be a perfectly functional `perl 5` as far as I can tell)

I'm trying to use this setup to build `rakudo` by 

- cloning this repo, and then
- running 

```
perl Configure.pl --gen-moar --moar-option='--compiler=clang' --gen-nqp --backends=moar

```  
as per the documentation on the [front page](https://github.com/rakudo/rakudo). 

The configuration fails at some point, informing me that the `.a` files cannot be built. The full output of the above `perl Configure.pl` command is [pasted here](http://ix.io/2clj).  

You'll see a `FAIL` in `Configuring native build environment` and then another `FAIL` when configuring 3rd party libs. Specifically, I get 

```
no idea how to build '3rdparty/libuv/libuv.a'
```

I'm looking for suggestions on how one might go about pushing this forward. I can find precious little info on getting this going on Android, so am wondering whether it's hopeless for now. 

## Environment
* Operating system: Android 10
* Compiler version (`perl6 -v`): I do not have `perl6` yet, as the point is to build it. `perl -v` returns `5.30`.

**Comment by patrickbkr** [comment]
Just a datapoint: I did successfully build Rakudo on aarch64 using qemu and Debian not long ago. No special trickery was necessary.

**Comment by stuart-little** [comment]
Thanks!

I'm not necessarily expecting trickery, which is why I gave it a go in this simple-minded fashion. 

My hope is I'm just missing some lib/package that I can install via `termux`, so am fishing for hints as to what people think might have gone wrong with the build (e.g. what the deal is with that `no idea how to build '3rdparty/libuv/libuv.a'` complaint).

**Comment by vrurg** [comment]
Not sure about the exact cause, but would be nice if you check `nqp/MoarVM/3rdparty/libuv` subdirectory for actual existence of `libuv` submodule content. You can also `cd nqp/MoarVM` and try executing `Configure.pl`. Perhaps it would tell you some useful information.

**Comment by stuart-little** [comment]
> Not sure about the exact cause, but would be nice if you check `nqp/MoarVM/3rdparty/libuv` subdirectory for actual existence of `libuv` submodule content. 

Listing that directory produces 

```
AUTHORS
CMakeLists.txt
CONTRIBUTING.md
ChangeLog
LICENSE
LICENSE-docs
MAINTAINERS.md
Makefile.am
README.md
SUPPORTED_PLATFORMS.md
android-configure-arm
android-configure-arm64
android-configure-x86
android-configure-x86_64
appveyor.yml
autogen.sh
common.gypi
configure.ac
docs
gyp_uv.py
img
include
libuv.pc.in
m4
src
test
tools
uv.gyp
vcbuild.bat

```

> You can also `cd nqp/MoarVM` and try executing `Configure.pl`. Perhaps it would tell you some useful information.

That execution fails with a subset of the output in the pastebin, still choking on `3rdparty/libuv/libuv.a`:

```
Welcome to MoarVM!

Updating submodules .................................... OK
    unknown OS 'android'
Configuring native build environment ................... 
FAIL
    assuming POSIX userland ............................     trying to compile a simple C program ............... YES
did not find libzstd; will not use heap snapshot format version 3
OK

    probing whether your compiler thinks that it is gcc  YES
    probing how your compiler does static inline ....... static __inline__
    your CPU can't read unaligned values for any of int32 int64 num64
    probing the size of pointers ....................... 8
JIT isn't supported on aarch64-android yet.
    probing C type support for: _Bool, bool ............ YES: _Bool,bool
    probing computed goto support ...................... YES
    probing pthread_yield support ...................... NO
    probing existance of optional malloc_trim() ........ NO
    probing support of rdtscp intrinsic ................     no idea how to build '3rdparty/libuv/libuv.a'
NO

        make: make
     compile: cc  -O -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=2
    includes:   -I3rdparty/libuv/include -I3rdparty/libuv/src -I3rdparty/libatomicops/src -I3rdparty/libtommath -I3rdparty/dyncall/dynload -I3rdparty/dyncall/dyncall -I3rdparty/dyncall/dyncallback
        link: cc  -O -DNDEBUG -Wl,-rpath,"/@libdir@"
        libs:  -lm -lpthread

  byte order: little endian

Configuring 3rdparty libs .............................. FAIL
    continuing anyway .................................. OK

  3rdparty: 3rdparty/cmp/libcmp.a
            3rdparty/dyncall/dyncall/libdyncall_s.a
            3rdparty/dyncall/dyncallback/libdyncallback_s.a
            3rdparty/dyncall/dynload/libdynload_s.a
            3rdparty/libatomicops/src/libatomic_ops.a
            3rdparty/libtommath/libtommath.a
            3rdparty/libuv/libuv.a
            3rdparty/sha1/libsha1.a
            3rdparty/tinymt/libtinymt.a

Generating src/gen/config.c ............................ OK
Generating src/gen/config.h ............................ OK
Generating Makefile .................................... OK
Generating tools/check.mk .............................. OK
Generating build/mk-moar-pc.pl ......................... OK

Configuration FAIL. You can try to salvage the generated Makefile.

```

**Comment by stuart-little** [comment]
An update: I've just tried to point  `nqp/MoarVM/Configure.pl` to my `pkg-config` and my `libuv`, running (inside `nqp/MoarVM`) the command 

```
./Configure.pl --pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config --has-libuv
```
This causes the 3rdparty libs to configure this time around, but the overall configuration still fails:
```
Welcome to MoarVM!

Updating submodules .................................... OK
    unknown OS 'android'
Configuring native build environment ................... 
FAIL
    assuming POSIX userland ............................     trying to compile a simple C program ............... YES
    Testing pkgconfig .................................. 0.29.2
Adding extra include for libuv: -I/data/data/com.termux/files/usr/include
Adding extra libs for libuv: -L/data/data/com.termux/files/usr/lib
OK

    probing whether your compiler thinks that it is gcc  YES
    probing how your compiler does static inline ....... static __inline__
    your CPU can't read unaligned values for any of int32 int64 num64
    probing the size of pointers ....................... 8
JIT isn't supported on aarch64-android yet.
    probing C type support for: _Bool, bool ............ YES: _Bool,bool
    probing computed goto support ...................... YES
    probing pthread_yield support ...................... NO
    probing existance of optional malloc_trim() ........ NO
    probing support of rdtscp intrinsic ................ NO

        make: make
     compile: cc  -O -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=3
    includes:  -I/data/data/com.termux/files/usr/include  -I3rdparty/libatomicops/src -I3rdparty/libtommath -I3rdparty/dyncall/dynload -I3rdparty/dyncall/dyncall -I3rdparty/dyncall/dyncallback
        link: cc  -O -DNDEBUG -Wl,-rpath,"/@libdir@"
        libs:  -L/data/data/com.termux/files/usr/lib -luv -lm -lpthread -lzstd 

  byte order: little endian

Configuring 3rdparty libs .............................. OK

  3rdparty: 3rdparty/cmp/libcmp.a
            3rdparty/dyncall/dyncall/libdyncall_s.a
            3rdparty/dyncall/dyncallback/libdyncallback_s.a
            3rdparty/dyncall/dynload/libdynload_s.a
            3rdparty/libatomicops/src/libatomic_ops.a
            3rdparty/libtommath/libtommath.a
            3rdparty/sha1/libsha1.a
            3rdparty/tinymt/libtinymt.a

Generating src/gen/config.c ............................ OK
Generating src/gen/config.h ............................ OK
Generating Makefile .................................... OK
Generating tools/check.mk .............................. OK
Generating build/mk-moar-pc.pl ......................... OK

Configuration FAIL. You can try to salvage the generated Makefile.

```
Now the only `FAIL` (preceding the final one) is the `native build environment`. Is that what propagates over to the final failure?

**Comment by stuart-little** [comment]
It works! Here's a summary of how this went down, in case anyone else finds their way here.

---

(1) I first made sure I had `libuv` and `pkg-config` installed through [termux](https://termux.com/)

(2) Then, in order to ensure the `MoarVM` configuration doesn't die because `android` is unrecognized as an os, I made the following change to `nqp/MoarVM/Configure.pl`:

```
diff --git a/Configure.pl b/Configure.pl
index ae6285f83..1aad1a798 100755
--- a/Configure.pl
+++ b/Configure.pl
@@ -863,7 +863,7 @@ sub dots {
 # fail but continue
 sub softfail {
     my ($msg) = @_;
-    $failed = 1;
+    $failed = 0;
     print "FAIL\n";
     warn "    $msg\n";
 }

```
I know it's a bit drastic (causing all "soft fails" to just forge on), but I just wanted this to build..

(3) back in the root directory of the repo I ran 

```
perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --gen-nqp --backends=moar
```
This went through fine.

(4) Running `make` afterwards actually croaked with a segfault, but following that up with `make install` seems to have produced a workable installation.

(5) I've since installed [zef](https://github.com/ugexe/zef) and through it [Linenoise](https://github.com/hoelzro/p6-linenoise/) to make the `perl6` REPL nicer to work with, and so far it's been behaving.

**Comment by jonathanstowe** [comment]
As a matter of interest does it work without the above change but instead supply the additional option

      --moar-option='--os=linux'

?  I'm guessing that it is sufficiently similar that it has a fighting chance.

**Comment by stuart-little** [comment]
It goes through configuration, but fails later and less reliably with a segfault. But then again so does my old method now (on a new, clean clone). 

The build dies typically during `STAGE 1`, sometimes making it to `STAGE 2`:

```
===ATTENTION===
  No --prefix supplied, building and installing to /data/data/com.termux/files/home/tmp/rakudo/install
No pre-existing installed file found at /data/data/com.termux/files/home/tmp/rakudo/install/bin/nqp-m
Fetching submodule 3rdparty/nqp-configure
Fetching submodule 3rdparty/nqp-configure
HEAD is now at 3f99c1ba6 Get MoarVM with async proc stdin close support
Building NQP ...
/data/data/com.termux/files/usr/bin/perl Configure.pl --prefix=/data/data/com.termux/files/home/tmp/rakudo/install --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --no-force-rebuild --backends=moar --gen-moar --moar-option=--compiler=clang --moar-option=--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config --moar-option=--has-libuv
Found /data/data/com.termux/files/home/tmp/rakudo/install/bin/moar version 2020.01.1-43-ga71eee4c2, which is new enough.
Cleaning up ...
+++ Preparing MOAR build directories
++++++ BUILDING MOAR BACKEND
++++++ STAGE1 ++++++
+++ Generating	gen/moar/stage1/nqpmo.nqp
+++ Compiling	gen/moar/stage1/nqpmo.moarvm
+++ Compiling	gen/moar/stage1/ModuleLoader.moarvm
+++ Generating	gen/moar/stage1/NQPCORE.setting
+++ Compiling	gen/moar/stage1/NQPCORE.setting.moarvm
+++ Generating	gen/moar/stage1/QASTNode.nqp
+++ Compiling	gen/moar/stage1/QASTNode.moarvm
+++ Generating	gen/moar/stage1/QRegex.nqp
+++ Compiling	gen/moar/stage1/QRegex.moarvm
+++ Generating	gen/moar/stage1/NQPHLL.nqp
+++ Generating	gen/moar/stage1/MASTNodes.nqp
+++ Compiling	gen/moar/stage1/MASTOps.moarvm
make: *** [Makefile:373: gen/moar/stage1/MASTOps.moarvm] Segmentation fault
Command failed (status 512): make
 at /data/data/com.termux/files/home/tmp/rakudo/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
	NQP::Config::__ANON__("Command failed (status 512): make\x{a}") called at /data/data/com.termux/files/home/tmp/rakudo/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 1480
	NQP::Config::system_or_die("make") called at Configure.pl line 109
Command failed (status 512): /data/data/com.termux/files/usr/bin/perl Configure.pl --prefix=/data/data/com.termux/files/home/tmp/rakudo/install --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --no-force-rebuild --backends=moar --gen-moar --moar-option=--compiler=clang --moar-option=--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config --moar-option=--has-libuv
 at /data/data/com.termux/files/home/tmp/rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
	NQP::Config::__ANON__("Command failed (status 512): /data/data/com.termux/files/usr/"...) called at /data/data/com.termux/files/home/tmp/rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 1480
	NQP::Config::system_or_die("/data/data/com.termux/files/usr/bin/perl", "Configure.pl", "--prefix=/data/data/com.termux/files/home/tmp/rakudo/install", "--make-install", "--git-protocol=https", "--no-relocatable", "--no-ignore-errors", "--silent-build", ...) called at /data/data/com.termux/files/home/tmp/rakudo/tools/lib/NQP/Config/Rakudo.pm line 702
	NQP::Config::Rakudo::gen_nqp(NQP::Config::Rakudo=HASH(0x7d102128e8)) called at Configure.pl line 101

```
This, I'm at a bit of a loss on. I suppose I got lucky the first time around..

**Comment by jonathanstowe** [comment]
That ` make\x{a}` looks a bit rum, but it could just be an artefact of the way it is being printed.

**Comment by stuart-little** [comment]
It does look strange, but building `NQP` did go through eventually, past the segfaults, after I simply ran the command repeatedly. 

This is still in the old setup though, *without* the extra `--moar-option='--os=linux'` option and *with* the modification to `nqp/MoarVM/Configure.pl`.

I'll be trying again with `os=linux`, but the segfault problem seems to be past that point anyway.

**Comment by stuart-little** [comment]
Indeed, on yet another clean clone 

```
perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --moar-option='--os=linux' --gen-nqp --backends=moar
```
worked to build and install `NQP` in one go, without the previous segfaults.

I don't know what's going on. I'd much rather it fail reliably than work unreliably..

**Comment by niner** [comment]
Can you try running the whole thing with MVM_SPESH_DISABLE=1 in your environment, please?
Is there a way to get core dumps on Android?

**Comment by stuart-little** [comment]
> Can you try running the whole thing with MVM_SPESH_DISABLE=1 in your environment, please?

Done. This has worked flawlessly, but due to prior fickleness of behavior I can't tell whether setting that environment variable made a difference.

To recap, I did the following (went through the whole process, for good measure):

```
export MVM_SPESH_DISABLE=1
```
Then, in the cleanly-cloned repo,

```
perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --moar-option='--os=linux' --gen-nqp --backends=moar

make

make install
```
This worked without issue.

> Is there a way to get core dumps on Android?

Never done it myself. 

In my context it would likely be something specific to this [termux](https://termux.com/) environment I'm working in, but I've never had to look up how to do core dumps, or indeed whether it's possible.

**Comment by jonathanstowe** [comment]
It may be something like `ulimit -c unlimited` though I am entirely ignorant of `termux`.

**Comment by stuart-little** [comment]
> It may be something like `ulimit -c unlimited` though I am entirely ignorant of `termux`.

Will keep in mind for next time. There's a `ulimit` command, and just running it with no flags returns `unlimited`, for what it's worth.

Would this mean the coredumps should be somewhere already? I've searched for files of the form `core.*` but can find nothing relevant.

**Comment by hungrydonkey** [comment]
> > Can you try running the whole thing with MVM_SPESH_DISABLE=1 in your environment, please?
> 
> Done. This has worked flawlessly, but due to prior fickleness of behavior I can't tell whether setting that environment variable made a difference.
> 
> To recap, I did the following (went through the whole process, for good measure):
> 
> ```
> export MVM_SPESH_DISABLE=1
> ```
> 
> Then, in the cleanly-cloned repo,
> 
> ```
> perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --moar-option='--os=linux' --gen-nqp --backends=moar
> 
> make
> 
> make install
> ```
> 
> This worked without issue.
> 
> > Is there a way to get core dumps on Android?
> 
> Never done it myself.
> 
> In my context it would likely be something specific to this [termux](https://termux.com/) environment I'm working in, but I've never had to look up how to do core dumps, or indeed whether it's possible.

It really works!!, many thanks😘.

**Comment by stuart-little** [comment]
@hungrydonkey Oh, I know :): since that exchange you quote took place, I must have built `Raku` on `Android` with that exact setup dozens of times. 

I have all of that scripted and run the script regularly, and it hasn't failed once.

**Comment by colomon** [comment]
I'm trying this now, just wanted to point out for the sake of completeness that in addition to libuv and pkg-config, I also had to install perl and make.  (I mean, duh, but I didn't realize I didn't have them when I started the process...)

**Comment by stuart-little** [comment]
@hungrydonkey Is it still not compiling for you?

I tried just now and the exact same recipe works as-is, with one caveat (see below).

I have
- `Android 11` on an `aarch64` phone
- [termux](https://termux.com/) `0.118.0`
- with its `perl` package, currently at `v5.34.0`
- plus the other packages mentioned before, above (`clang`, etc.).

**The caveat**
After all of the `Android` / `termux` updates I was running into [this termux issue](https://github.com/termux/termux-packages/issues/8095) because of stale `perl` modules from an earlier version. So on my machine I just had to move the directory
```
/data/data/com.termux/files/usr/lib/perl5/site_perl
```
out of the way. That was it; the compilation procedure worked exactly as described above, with the latest `rakudo` as I type this:
```
$ raku -v                         

Welcome to Rakudo™ v2022.02-69-g967a130ff.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02.
```

**Comment by hungrydonkey** [comment]
> @hungrydonkey Is it still not compiling for you?
> 
> I tried just now and the exact same recipe works as-is, with one caveat (see below).
> 
> I have
> 
> * `Android 11` on an `aarch64` phone
> * [termux](https://termux.com/) `0.118.0`
> * with its `perl` package, currently at `v5.34.0`
> * plus the other packages mentioned before, above (`clang`, etc.).
> 
> **The caveat**
> 
> After all of the `Android` / `termux` updates I was running into [this termux issue](https://github.com/termux/termux-packages/issues/8095) because of stale `perl` modules from an earlier version. So on my machine I just had to move the directory
> 
> ```
> /data/data/com.termux/files/usr/lib/perl5/site_perl
> ```
> 
> out of the way. That was it; the compilation procedure worked exactly as described above, with the latest `rakudo` as I type this:
> 
> ```
> $ raku -v                         
> 
> Welcome to Rakudo™ v2022.02-69-g967a130ff.
> Implementing the Raku® Programming Language v6.d.
> Built on MoarVM version 2022.02.
> ```
I'm happy to say that it works well now. After querying you about that,  I have successfully compiled the 2021.12 release which I am using. Thanks contributors for solving these problems, and thanks for your concern 😊. By the way, I haven't tried  2022.02 version of `rakudo` on `termux`, but I am happy to know it's also available.

**Comment by stuart-little** [comment]
Actually, this has started failing again on `Android 11` (trying to build tag `2023.04-94-gc14084ecd`).

I am following the same recipe that used to work before:

```
git fetch origin && git pull
export MAKEFLAGS="-j8"
export MVM_SPESH_DISABLE=1 && perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --moar-option='--os=linux' --gen-nqp --backends=moar
```
You can see the [full output](https://termbin.com/83yx), including the errors that finally choke it: something about incompatible pointer types, which `src/6model/containers.c` screams about, as in 

```
src/6model/containers.c:117:5: error: incompatible function pointer types initializing 'void (*)(MVMThreadContext *, MVMObject *, MVMuint64)' (aka 'void (*)(struct MVMThreadContext *, struct MVMObject *, unsigned long)') with an expression of type 'void (MVMThreadContext *, MVMObject *, MVMint64)' (aka 'void (struct MVMThreadContext *, struct MVMObject *, long)') [-Wincompatible-function-pointer-types]
    code_pair_store_i, /* FIXME need a code_pair_store_u but lacking tests showing this need */
    ^~~~~~~~~~~~~~~~~
```

Any idea how to patch this up?
