### ISSUE TITLE
Spec-code discrepancy with package.^name

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3512]
## The Problem

The [6.d release guide](https://github.com/perl6/roast/blob/c0740a9261e69f7de6d4bf8f14fccd204e1d8e30/docs/announce/6.d.md) includes this:

> .^ver, .^auth, and .^name metamethods are available on module and are absent on a package, by design

Nothing wrong with `^ver` and `^auth`. However, `^name` works in packages:

```perl6
package Foo:ver<0>:auth<bar> {};
say Foo.^name; # OUTPUT: «Foo␤»
```

And the code for it has been there [for 9 years](https://github.com/rakudo/rakudo/blame/b787095358bcbac4c6326b99e9673e54ef5afd58/src/Perl6/Metamodel/PackageHOW.nqp).

```
class Perl6::Metamodel::PackageHOW
    does Perl6::Metamodel::Naming
```

As far as I can see, there's nothing in roast testing this (or the contrary). So I really wonder if what's wrong is that statement, or the rest of the world.

**Comment by lizmat** [comment]
FWIW, especially in that order, it should have said ".^ver, .^auth, and .^~~name~~api"
