### ISSUE TITLE
qqx, shell not operating quotes properly

### ISSUE THREAD

**Issue by ToddAndMargo** [rakudo/rakudo#3518]
Dear Raku,

Windows 7, SP1, X64 and Windows 10-1909, x64

C:\NtUtil>perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

qqx is not handling quoted parameters correctly.   Specifically Windows command that receive file names with spaces in them.  I do believe that Windows is seeing the extra quotes as part of the actual file name, but I am only speculating.

This is a good baseline with a file name without a space in it. 
```
echo "hi mom" > "test2"
perl6 -e "say qqx { dir test2 };"
 Volume in drive C is DRIVE_C
 Volume Serial Number is 3CDF-1B03
 Directory of C:\NtUtil
02/26/2020  15:24                11 test2
               1 File(s)             11 bytes
               0 Dir(s)  13,269,639,168 bytes free
```

Here is a file name with a space in it:

```
echo "hi mom" > "test 1"
perl6 -e "say qqx { dir 'test 1' };"
File Not Found
 Volume in drive C is DRIVE_C
 Volume Serial Number is 3CDF-1B03
 Directory of C:\NtUtil
 Directory of C:\NtUtil
```

perl6 -e "say qqx { dir \"test 1\" };"
The system cannot find the file specified.

perl6 -e "say qqx { dir 'test2' };"  # note this works without the quotes
File Not Found
 Volume in drive C is DRIVE_C
 Volume Serial Number is 3CDF-1B03
 Directory of C:\NtUtil

On a more complicated scale, it is the fsutil command that initially  show this error.  These comand also failed with 
```
Usage : fsutil usn readData <filename>
   Eg : fsutil usn readData C:\Temp\sample.txt
Error:  The filename, directory name, or volume label syntax is incorrect.

my @Result = qqx { C:/Windows/System32/fsutil.exe usn readdata "$FileName" }.lines;
for @Result -> $Line  { say $Line; };

my $proc=run( "dir", "$FileName", :out );
my @RtnStr  = $proc.out.slurp-rest.lines; 
for @RtnStr -> $Line { say $Line; }

@Result = shell( "C:/Windows/System32/fsutil.exe usn readdata \"$FileName\"" );
for @Result -> $Line  { say $Line; };

@Result = shell( 'C:/Windows/System32/fsutil.exe usn readdata "$FileName"' );

Usage : fsutil usn readData <filename>
   Eg : fsutil usn readData C:\Temp\sample.txt
Error:  The filename, directory name, or volume label syntax is incorrect.
Proc.new(in => IO::Pipe, out => IO::Pipe, err => IO::Pipe, exitcode => 1, signal => 0, pid => 1192, command => ("C:/Windows/System32/fsutil.exe usn readdata \"\$FileName\"",))

```

**Comment by patrickbkr** [comment]
I'm not entirely sure it's related, but there is a known deficiency in argument passing when calling external programs on Windows. An extensive problem analysis and proposals for solution was done in [problem-solving#20](https://github.com/Raku/problem-solving/issues/20).

**Comment by ToddAndMargo** [comment]
Hi Patrick,

That does sound like the issue

-T

**Comment by ToddAndMargo** [comment]
#20 sure does look like it.

Anyway, I have a workaround for anyone stopped because of this bug:
I am taking advantage of the Windows build in batch programming language:

```
my $PathIAm = $?FILE;
( my $IAm = $PathIAm ) ~~ s| .* "/" ||;

my $FileName = "@*ARGS[0]";

my Str $CmdStr = 
    Q[@echo off] ~ "\n" ~
    Q[C:\Windows\System32\fsutil.exe usn readdata ] ~
    Q["] ~ $FileName ~ Q["] ~ "\n";

spurt( $BatFile, $CmdStr );
say qqx { $BatFile };
```

Result:

```
C:\NtUtil>raku k:\Windows\NtUtil\FileAttributes.pl6 "Test 1"

Major Version    : 0x3
Minor Version    : 0x0
FileRef#         : 0x00000000000000000058000000000340
Parent FileRef#  : 0x00000000000000000013000000000eb9
Usn              : 0x00000000711dab68
Time Stamp       : 0x0000000000000000 12:00:00 AM 1/1/1601
Reason           : 0x0
Source Info      : 0x0
Security Id      : 0x0
File Attributes  : 0x20
File Name Length : 0xc
File Name Offset : 0x4c
```
FileName         : test 1

**Comment by jubilatious1** [comment]
Similar to my comment on the Perl6-Users mailing list, you shouldn't want/need to put a `\n` at the end of your filename when using `spurt`. 

Does this whole issue boil down to newline processing?

@patrickbkr

**Comment by ToddAndMargo** [comment]
It should not matter one way or the other.  It is up to what you want written to the file.  I personally like the line feed at the end so I can "cat" the file and not have my shell new line prompt at the end of the file rather than on a new line.

**Comment by patrickbkr** [comment]
@ToddAndMargo Without digging into this issue more, have you realized that problem-solving#20 has been solved? https://github.com/Raku/problem-solving/blob/7fbe6dcb1fc4ac17c89485f398136f07f1a6d423/solutions/language/Windows-process-argument-quoting.md Does the solution somehow fit this problem as well?

**Comment by ToddAndMargo** [comment]
On 11/6/23 00:05, Patrick Böker wrote:
> @ToddAndMargo <https://github.com/ToddAndMargo> Without digging into 
> this issue more, have you realized that problem-solving#20 has been 
> solved? 
> https://github.com/Raku/problem-solving/blob/7fbe6dcb1fc4ac17c89485f398136f07f1a6d423/solutions/language/Windows-process-argument-quoting.md <https://github.com/Raku/problem-solving/blob/7fbe6dcb1fc4ac17c89485f398136f07f1a6d423/solutions/language/Windows-process-argument-quoting.md> Does the solution somehow fit this problem as well?
>
Hi Patrick,

Thank you for the heads up.  I was not carbon copied
on the bug report, so I was in the dark.

I did a quick read through of the link.  I did not
understand most of it, so I will have to tray again
when I can read it slowly.

My workaround of writing the commands I want to run to
a batch file and then running the batch file is
working out marvelously as it gives me a lot of control
over what I want to do, including multiple commands
bunched together.

-T

**Comment by jubilatious1** [comment]
> It should not matter one way or the other. It is up to what you want written to the file. I personally like the line feed at the end so I can "cat" the file and not have my shell new line prompt at the end of the file rather than on a new line.


https://unix.stackexchange.com/questions/23163/newlines-in-filenames    
https://unix.stackexchange.com/questions/189784/remove-newlines-in-file-names/397659#397659        
https://unix.stackexchange.com/questions/542421/recursively-remove-newline-in-file-names?noredirect=1&lq=1

**Comment by jubilatious1** [comment]
Note: `slurp-rest` is deprecated:

https://docs.raku.org/routine/slurp-rest
