### ISSUE TITLE
Why is "foo".IO.lines.elems taking much more memory than "foo".IO.slurp.lines.elems

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3520]
Inspired by https://stackoverflow.com/questions/60448142/how-to-emulate-wc-l-in-raku

    lines.elems: 178584
    slurp.lines.elems: 104456

This feels counter-intuitive, as the `.lines` case should not keep the whole file in memory?

    $ raku -Msnapper -e 'say +"words".IO.lines'
    235886
    Telemetry Report of Process #21689 (2020-02-28T11:19:37Z)
    Number of Snapshots: 3
    Initial/Final Size: 78672 / 178584 Kbytes
    Total Time:           0.16 seconds
    Total CPU Usage:      0.20 seconds
    Supervisor thread ran the whole time

    wallclock  util%  max-rss
       103466   8.94    59016
        51574   6.29    40896
    --------- ------ --------
       155040   8.06    99912

    Legend:
    wallclock  Number of microseconds elapsed
        util%  Percentage of CPU utilization (0..100%)
      max-rss  Maximum resident set size (in Kbytes)

vs:

    $ raku -Msnapper -e 'say +"words".IO.slurp.lines'
    235886
    Telemetry Report of Process #21688 (2020-02-28T11:19:32Z)
    Number of Snapshots: 2
    Initial/Final Size: 79288 / 104456 Kbytes
    Total Time:           0.06 seconds
    Total CPU Usage:      0.10 seconds
    Supervisor thread ran the whole time

    wallclock  util%  max-rss
        61742  10.16    25168
    --------- ------ --------
        61742  10.16    25168

    Legend:
    wallclock  Number of microseconds elapsed
        util%  Percentage of CPU utilization (0..100%)
      max-rss  Maximum resident set size (in Kbytes)

**Comment by jnthn** [comment]
> This feels counter-intuitive, as the .lines case should not keep the whole file in memory?

It does, because `elems` causes `.cache` to happen.

**Comment by lizmat** [comment]
$ raku -Msnapper -e 'Nil for "words".IO.lines'
    Telemetry Report of Process #18021 (2020-03-25T12:34:32Z)
    Number of Snapshots: 3
    Initial/Final Size: 85176 / 110116 Kbytes
    Total Time:           0.11 seconds
    Total CPU Usage:      0.14 seconds
    Supervisor thread ran the whole time

    wallclock  util%  max-rss
       105422   7.82    24612
         7936   6.40      328
    --------- ------ --------
       113358   7.72    24940

    Legend:
    wallclock  Number of microseconds elapsed
        util%  Percentage of CPU utilization (0..100%)
      max-rss  Maximum resident set size (in Kbytes)

vs:

    $ raku -Msnapper -e 'Nil for "words".IO.slurp.lines'
    Telemetry Report of Process #18026 (2020-03-25T12:35:19Z)
    Number of Snapshots: 3
    Initial/Final Size: 85256 / 112508 Kbytes
    Total Time:           0.11 seconds
    Total CPU Usage:      0.13 seconds
    Supervisor thread ran the whole time

    wallclock  util%  max-rss
       102160   7.47    27244
         6764   8.59        8
    --------- ------ --------
       108924   7.54    27252

    Legend:
    wallclock  Number of microseconds elapsed
        util%  Percentage of CPU utilization (0..100%)
      max-rss  Maximum resident set size (in Kbytes)
