### ISSUE TITLE
Broken links in annoucement

### ISSUE THREAD

**Issue by gugod** [rakudo/rakudo#3530]
## The Problem

In the [the latest announcement for 2020.02](https://github.com/rakudo/rakudo/blob/master/docs/announce/2020.02.md), there is a link to this url: https://rakudo.org/how-to-help

However, it's an url leading to a 404 page.

The page did did contain some content before: http://web.archive.org/web/20180407170728/http://rakudo.org/how-to-help/

## Expected Behavior

Shall we update the announcement (for future ?)  to avoid using this broken link, or shall we bring back that page ?

**Comment by Altai-man** [comment]
Thanks for your report!
I think @patrickbkr was doing some overhaul in this area.
Maybe it should redirect to https://rakudo.org/community ?

**Comment by AlexDaniel** [comment]
Ping @patrickbkr @rba

**Comment by patrickbkr** [comment]
I changed the link to point to <https://rakudo.org/community> in the release announcement template and @rba has added a redirect to <https://rakudo.org/how-to-help>.
