### ISSUE TITLE
Comparing Buf with the is routine from Test does not behave well

### ISSUE THREAD

**Issue by Skarsnik** [rakudo/rakudo#3535]
## The Problem

When comparing Buf with the routine `is` from the test module, it will work if data are the same, but if the 2 Buf is not the same it will make the module dies because it can't call Str to show the regular error of 'Expected : blablab, Got : claclalc'

## Expected Behavior

Fail like a regular test failing to pass when data are not the same and not like a crash

## Actual Behavior

Failed test at -e line 1
Cannot use a Buf as a string, but you called the Stringy method on it
  in block  at /home/skarsnik/raku/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 188

## Steps to Reproduce

raku -e 'use Test; is Buf.new([0 xx 40]), Buf.new([0 xx 40]); is Buf.new([0 xx 40]), Buf.new([1 xx 40]);'
ok 1 -
not ok 2 -
# Failed test at -e line 1
Cannot use a Buf as a string, but you called the Stringy method on it
  in block  at /home/skarsnik/raku/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 188
  in sub is at /home/skarsnik/raku/share/perl6/core/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 171
  in block <unit> at -e line 1

## Environment

skarsnik@DESKTOP-UIA12T1:/mnt/f/Project/QUsb2snes/tests/usb2snes-tests/raku-tests$ raku --version
This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

**Comment by Altai-man** [comment]
See conversation at https://colabti.org/irclogger/irclogger_log/raku?date=2020-03-07#l204
