### ISSUE TITLE
raku -o doesn't dump, but raku --output does

### ISSUE THREAD

**Issue by rypervenche** [rakudo/rakudo#3543]
## The Problem
Using `-o` for an output file results in an error. This happens with both `-o <filename>` and `-o=<filename>`. Using `--output <filename>` and `--output=<filename>` instead work just fine.

## Expected Behavior
`raku --target=mbc -o /tmp/blah.moarvm ./script.raku`
(outputs bytecode to /tmp/blah.moarvm)

`raku --target=mbc -o=/tmp/blah.moarvm ./script.raku`
(outputs bytecode to /tmp/blah.moarvm)

## Actual Behavior
```
raku --target=mbc -o /tmp/blah.moarvm ./script.raku
===SORRY!===
Cannot dump this object; no dump method
```

```
raku --target=mbc -o=/tmp/blah.moarvm ./script.raku
===SORRY!===
Cannot dump this object; no dump method
```

## Steps to Reproduce
Run `raku --target=mbc -o <output-file> <raku-script>`.

## Environment
Gentoo (both Stable and Testing)
`This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.`

**Comment by lizmat** [comment]
This appears fixed
