### ISSUE TITLE
New class assigned to $*ARGFILES breaks "IO::CatHandle::Autolines"

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3548]
## The Problem

[IO::CatHandle::Autolines](https://github.com/raku-community-modules/perl6-IO-CatHandle-AutoLines) rely on $*ARGFILES being a IO::ArgFiles; it's now become a IO::Handle, at least in the default case.

That causes a number of issues in that module (from 2020.01) as well as derived modules (such as [LN](https://github.com/raku-community-modules/perl6-LN/issues/2), making them fail tests.

## Expected Behavior

I guess that was not spec, but there was no warning in the changes either, except for this one:

> `$*ARGFILES` special variable now defaults to `$*IN` if no arguments [bde10698]

I guess that the problem is that it bounds to $*IN, instead of containing $*IN (but I could be wrong, of course).

The behavior is not a problem per se, but this new behavior should maybe be tested either locally here or in roast, so that we don't break stuff that relies on it later on.

## Environment

Tested with 2020.01 and 2020.02

**Comment by lizmat** [comment]
Technically, this is not a Rakudo issue.  The module uses Rakudo internals information, and that can change without notice.  As has happened.  This thing is, that change was made to get better performance in the simple case.  I don't think it is wise to revert that change, and make every user suffer from performance degradation, just to make this special case work again.

I am now looking at upgrading the module in such a way that it can be used before and after the breaking change in Raku.

**Comment by JJ** [comment]
El vie., 13 mar. 2020 a las 18:33, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

> Technically, this is not a Rakudo issue. The module uses Rakudo internals
> information, and that can change without notice. As has happened. This
> thing is, that change was made to get better performance in the simple
> case. I don't think it is wise to revert that change, and make every user
> suffer from performance degradation, just to make this special case work
> again.
>
Of course. It doesn't make a lot of sense.

> I am now looking at upgrading the module in such a way that it can be used
> before and after the breaking change in Raku.
>

That would be great. But another option is simply refactoring the using
module; that particular thing is used for a feature which I don't really
find that useful. I really just found out because the downstream module was
mentioned in StackOverflow, and was curious as to its state...  But it
would be great, of course, if it continued working the way it did.

**Comment by lizmat** [comment]
The updated versions of `IO::CatHandle::AutoLines` and `LN` now work transparently with older as well as newer versions of Rakudo.  So I think we can close this ticket.
