### ISSUE TITLE
IO::Path comparison is not OS independent

### ISSUE THREAD

**Issue by antoniogamiz** [rakudo/rakudo#3551]
## The Problem

I am trying to make a comparison between two `IO::Path` objects:

https://github.com/perl6/Pod-To-Cached/pull/12/files#diff-12050ba336b2774ee0b8264cb2d7a0f3R29-R32

Though they are equal, the test fails if executed in a Windows environment (in Unix works perfectly).

## Expected Behavior

Comparison should return `True`.

## Actual Behavior

It errors. More info: https://ci.appveyor.com/project/JJ/pod-to-cached/builds/28050389

## Steps to Reproduce

~~~raku
"a/b".IO(:SPEC(IO::Spec::Win32.new)) ~~ "a\\b".IO(:SPEC(IO::Spec::Win32.new))
~~~

## Environment
* Operating system: Windows
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

**Comment by thundergnat** [comment]
It is difficult to have a universal, cross platform solution.

Would something like this work for you?

```
sub win32-path-cmp (Str $a, Str $b) {
     IO::Spec::Win32.canonpath(:parent, $a).fc eq IO::Spec::Win32.canonpath(:parent, $b).fc
}

for ("a/b", "a\\b"), # original
    ('C:/home/bernie/.', 'C:\temp\Win32/../../home/bernie'), # more complicated
    ('C:/TEST/.', 'C:\temp\space in name/../../test'), # case insensitive, with spaces (on Win32)
    ('E:/TEST/.', 'C:\temp\space in name/../../test') # fail
  -> ($a, $b) {
    say "\nOriginal: ", $a, '  ', $b;
    say 'IO.Spec: ', IO::Spec::Win32.canonpath(:parent, $a),
        '  ', IO::Spec::Win32.canonpath(:parent, $b);
    say 'Compare equal: ', win32-path-cmp($a, $b);
}
```
yields:

```
Original: a/b  a\b
IO.Spec: a\b  a\b
Compare equal: True

Original: C:/home/bernie/.  C:\temp\Win32/../../home/bernie
IO.Spec: C:\home\bernie  C:\home\bernie
Compare equal: True

Original: C:/TEST/.  C:\temp\space in name/../../test
IO.Spec: C:\TEST  C:\test
Compare equal: True

Original: E:/TEST/.  C:\temp\space in name/../../test
IO.Spec: E:\TEST  C:\test
Compare equal: False
```
(on my system at least)

**Comment by antoniogamiz** [comment]
It worked, thanks :D.
