### ISSUE TITLE
Errors on REPL launch

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#3552]
## The Problem

Since [86bc3b3](https://github.com/rakudo/rakudo/commit/86bc3b3d296fde7330b9ab17ce74f101ae07b9b9), running `raku` at the command line to load the REPL produces some error. Afterwards the REPL seems to work perfectly normal, so this just appears to be when loading the REPL.

Error does not appear in previous commit [b639221](https://github.com/rakudo/rakudo/commit/b639221dd7eb3bfa2ff1c5cdf37a4e50628ea98e).

## Expected Behavior

    % raku
    To exit type 'exit' or '^D'
    >

## Actual Behavior

	% raku
	Use of uninitialized value element[0] of type Any in string context.
	Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
	in any protect at gen/moar/stage2/NQPCORE.setting line 1216
	Use of uninitialized value element[1] of type Any in string context.
	Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
	in any protect at gen/moar/stage2/NQPCORE.setting line 1216
	Use of uninitialized value element[2] of type Any in string context.
	Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
	in any protect at gen/moar/stage2/NQPCORE.setting line 1216
	Use of uninitialized value element[3] of type Any in string context.
	Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
	in any protect at gen/moar/stage2/NQPCORE.setting line 1216
	Use of uninitialized value element[4] of type Any in string context.
	Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
	in any protect at gen/moar/stage2/NQPCORE.setting line 1216
	To exit type 'exit' or '^D'
	>

## Environment
* Operating system: CentOS release 6.9
* Compiler version: Rakudo version 2020.02.1-189-g86bc3b3d2 built on MoarVM version 2020.02.1-44-g04005cf43

**Comment by lizmat** [comment]
This error does not appear on MacOS, which is probably why I didn't see it (and still can't see it).  But I think I know where this is coming from.

**Comment by lizmat** [comment]
Question: do you see the same error if you do:

     $ raku -e '$*DISTRO'

??

**Comment by 0racle** [comment]
Yes, the error still occurs when running `raku -e '$*DISTRO'`.

Note that `$*DISTRO` also appears to be empty

    > $*DISTRO
     ()

**Comment by lizmat** [comment]
I've reverted https://github.com/rakudo/rakudo/commit/86bc3b3d296fde7330b9ab17ce74f101ae07b9b9 , could you verify if that fixed the problem?

**Comment by 0racle** [comment]
Yes, the revert resolves the issue.

**Comment by lizmat** [comment]
What does:

    dd .<osvers>, .<osname> with VM.new.config

say?

**Comment by 0racle** [comment]
On the broken commit? This: -

    > dd .<osvers>, .<osname> with VM.new.config
    "2.6.32-696.23.1.el6.x86_64"
    "linux"
    Nil

**Comment by lizmat** [comment]
The only way I can see `$*DISTRO` become an empty list, is the following sequence:

    $ raku -e 'PROCESS::<$FOO> := do { if 0 { } }; say $*FOO'
    ()

But I don't really see a code path that could create that.  Weird.

**Comment by lizmat** [comment]
Ok, found a way to reproduce the problem on Darwin.

**Comment by lizmat** [comment]
Second attempt with https://github.com/rakudo/rakudo/commit/73c7ded2e8  .  Could you please verify that a. this doesn't produce any warnings, and b. shows `$*DISTRO` to be something more than `()`.

**Comment by 0racle** [comment]
Looks like you've done it!

Issue no longer present on both machines that were previously exhibiting the behavior

1: 

    % raku
    To exit type 'exit' or '^D'
    > $*DISTRO
    linux (2.6.32.696.23.1.el.6.x.86._.64)

2:

    % raku
    To exit type 'exit' or '^D'
    > $*DISTRO
    linux (2.6.32.696.13.2.el.6.x.86._.64)

**Comment by lizmat** [comment]
Good!   :-)
