### ISSUE TITLE
Pair.raku adds unnecessary parens

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3555]
Code:
```
(‘$foo’ => 42).raku.say
```
Output:
```
("\$foo") => 42
```

Expected:
```
"\$foo" => 42
```

Bisected: (2020-01-06) https://github.com/rakudo/rakudo/commit/08aec410ef68251e3bdad0987528e50c9087c687

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/35a827af36

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/94a78e6bab
