### ISSUE TITLE
VMNull error instead of “No such private method”

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3556]
wildtrees++ [reported this](https://colabti.org/irclogger/irclogger_log/raku?date=2020-03-18#l278) on IRC but I don't have a golf.

Two-file gist to reproduce the issue: https://gist.github.com/AlexDaniel/f05c6ea19f09ad38fc852ec2d06903ab

Output on all releases: https://gist.github.com/0201bf3c8341fdb4ee090642bf6ab65f (TL;DR `Cannot invoke this object (REPR: Null; VMNull)` starting from 2018.06, before that you'd get `No such private method` or similar)

Bisected to `Merge branch 'spesh-plugins'`:
* (2018-06-08) https://github.com/rakudo/rakudo/commit/f6f43d58e3 Use a spesh plugin for $foo.Qual::Ified::meth()
* (2018-06-08) https://github.com/rakudo/rakudo/commit/51ff83c7ca Use a MoarVM spesh plugin for private method calls
* (2018-06-08) https://github.com/rakudo/rakudo/commit/c6a61f563b Use a spesh plugin to optimize .?
* (2018-06-08) https://github.com/rakudo/rakudo/commit/c5d14062ab Merge branch 'spesh-plugins'

Obligatory ping: @jnthn :)

**Comment by AlexDaniel** [comment]
Actually, I'm not sure what's going on here. It's a bit random.

You may actually see that *sometimes* it complains about this line:
```
our %world = {};
```
And a fix to that would be:
```
our %world := {};
```
However, if you do that, the VMNull error goes away. No idea. Even the bisect result may be wrong. I don't know.

**Comment by lizmat** [comment]
Assuming this is no longer an issue
