### ISSUE TITLE
REPL increments ++$counter variable even though statement errors out (  .=abs example)

### ISSUE THREAD

**Issue by jubilatious1** [rakudo/rakudo#3561]
## The Problem

I attempted to reproduce the example code demonstrating use of the ".=" infix operator found here:

https://docs.raku.org/routine/.=

To test whitespace requirements, I inserted a few spaces to see the effect on the code. What I  discovered is that the REPL will increment the LHS ++$counter variable ("$a") anyway, even though statement as a whole fails and errors out. Thes means that the LHS executes while the RHS (.=abs function/assignment) fails to execute. The upshot is that although you end up with a failed statement, the ++$counter variable ("$a") doesn't get "rolled back" to its initial value before the statement was called.

```
mbook:~ homedir$ perl6
To exit type 'exit' or '^D'
> my $a = -5;
-5
> say $a
-5
> say ++$a .= abs;
Cannot modify an immutable Int (-4)
  in block <unit> at <unknown file> line 1

> say $a
-4
> say ++$a .=abs;
Cannot modify an immutable Int (-3)
  in block <unit> at <unknown file> line 1

> say $a
-3
> say ++$a.=abs;
4
> say $a
4
> exit
mbook:~ homedir$ 
```
## Expected Behavior

I expected the code above to return "6"; instead it returns "4".

## Actual Behavior

I expected the code above to return "6"; instead it returns "4".

## Steps to Reproduce

See code above.

## Environment
* Operating system: MacOS
* Compiler version (`perl6 -v`): mbook:~ homedir$ perl6 -v
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1 implementing Perl 6.d.

Note: this is a REPL-only issue. Command-line "one-liners" stop at the first error. See below: 

```
mbook:~ homedir$ perl6 -e 'my $a = -5; say $a; ++$a .= abs; say $a; ++$a.=abs; say $a;'
-5
Cannot modify an immutable Int (-4)
  in block <unit> at -e line 1

mbook:~ homedir$
```

**Comment by jubilatious1** [comment]
Confirmed as still present in Raku/Perl6 version 2020.02.1:

```
homedir$ perl6 -v
This is Rakudo version 2020.02.1.0000.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

**Comment by jnthn** [comment]
> The upshot is that although you end up with a failed statement, the ++$counter variable ("$a") doesn't get "rolled back" to its initial value before the statement was called.

I don't think this is a reasonable expectation; there's no such transaction mechanism specified anywhere in the language.

> Note: this is a REPL-only issue. Command-line "one-liners" stop at the first error. See below:

Well, we could make the REPL also simply exit completely on error, but I don't think that'd be very usable. If you make the command line version also recover from errors you'll see the very same situation:

```
$ perl6 -e 'my $a = -5; say $a; try ++$a .= abs; say $a; say $!;'
-5
-4
Cannot modify an immutable Int (-4)
  in block <unit> at -e line 1
```
