### ISSUE TITLE
JVM: NullPointerException when calling wrapped method

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3563]
## The Problem
A couple of spectest files have started to abort recently due to a NullPointerException. I didn't bisect, but I'm pretty sure it happens since the 'Big rewrite of dispatchers and wrapping' by @vrurg++.
* S02-names/is_cached.rakudo.jvm aborted 38 test(s)
* S06-advanced/dispatching.t aborted 3 test(s)
* S06-advanced/wrap.rakudo.jvm aborted 62 test(s)
* S14-traits/routines.rakudo.jvm aborted 4 test(s)
* integration/99problems-41-to-50.t aborted 9 test(s)
* integration/advent2011-day04.t aborted 2 test(s)
* integration/advent2011-day14.t aborted 6 test(s)
* integration/failure-and-callsame.t aborted 50 test(s)

I tried to find a short example for the dying code and ended up with this:
```
$ ./rakudo-j --ll-exception -e 'class Foo { method foo { "foo" } }; Foo.^lookup("foo").wrap(-> \SELF, | { "bar" }); Foo.new.foo.say'
java.lang.NullPointerException
  in onlywrap (gen/jvm/CORE.c.setting:15926)
  in <unit> (-e:1)
  in <unit-outer> (-e:1)
  in eval (gen/jvm/stage2/NQPHLL.nqp:1210)
  in <anon> (gen/jvm/stage2/NQPHLL.nqp:1322)
  in command_eval (gen/jvm/stage2/NQPHLL.nqp:1319)
  in command_eval (gen/jvm/Compiler.nqp:65)
  in command_line (gen/jvm/stage2/NQPHLL.nqp:1303)
  in MAIN (gen/jvm/rakudo.nqp:133)
  in <mainline> (gen/jvm/rakudo.nqp:121)
  in <anon> (gen/jvm/rakudo.nqp)
```

## Expected Behavior
The code prints ```bar\n``` on stdout on MoarVM:
```
$ ./rakudo-m -e 'class Foo { method foo { "foo" } }; Foo.^lookup("foo").wrap(-> \SELF, | { "bar" }); Foo.new.foo.say'
bar
```

## Compiler version
```
$ ./rakudo-j --version
This is Rakudo version 2020.02.1-201-gbaeba2f built on JVM
implementing Raku 6.d.
```

**Comment by vrurg** [comment]
The problem is in `nqp::setcodeobj` implementation in JVM and I need somebody to take care of it. Here is what exactly happens:

```perl6use nqp;
class Foo {
    method foo {
        note "foo";
    }
}
my &foo := Foo.^method_table<foo>;
my &bar := my sub (|) { note "bar"; };
my $do := nqp::getattr(&bar, Code, '$!do');
nqp::bindattr(&foo, Code, '$!do', $do);
# nqp::setcodeobj($do, &foo);
Foo.new.foo;
```

The code above works until `nqp::setcodeobj` is uncommented. Unfortunately, there is no workaround and setcode is mandatory in the wrapping implementation.

**Comment by usev6** [comment]
Thanks for looking and showing example code that doesn't rely on .wrap! That's very helpful.

I'll investigate further.

**Comment by usev6** [comment]
Just a short update. If I'm not mistaken the NullPointerException happens here: https://github.com/rakudo/rakudo/blob/4fca947436/src/vm/jvm/runtime/org/perl6/rakudo/Binder.java#L600

```sci.oTryGetLexicalIdx("self")``` seems to return ```null``` at some point. I don't know why the StaticCodeInfo doesn't know about ```self```, but at least that's where the code dies.

**Comment by usev6** [comment]
This is no longer an issue. The changes that lead to the NPE were reverted for now (via https://github.com/rakudo/rakudo/pull/3651), because they had negative impacts on performance.
