### ISSUE TITLE
Unexpected, slurp(:bin) returns type Str

### ISSUE THREAD

**Issue by rbt** [rakudo/rakudo#3566]
## The Problem
my Buf $buf = slurp(:bin); fails due to type problem

## Expected Behavior

This returns a Buf as expected:
```
echo "message" | rakudo -e 'my $msg = slurp(:bin); say $msg.^name; say $msg.elems;'
=> Buf[uint8]
=> 8
```

This returns a string despite requesting a Buf.
```
echo "message" | rakudo -e 'sub MAIN() {my $msg = slurp(:bin); say $msg.^name; say $msg.chars;}'
=> Str
=> 8
```

Likely related. Perhaps slurp(IO::ArgFiles, :bin) doesn't know to return Buf.
```
m: sub MAIN() { say $*ARGFILES.^name}
rakudo-moar 13559242f: OUTPUT: «IO::ArgFiles␤»

m: say $*ARGFILES.^name
rakudo-moar 13559242f: OUTPUT: «IO::Handle␤»
```

```
rakudo --version
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/42c4c3fcb2

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/8943531beb
