### ISSUE TITLE
Appveyor builds fail each commit for different, but possibly linked reasons

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3568]
Rakudo can't be built on appveynor for a week now.

Reasons are different, but they are persistent. Among ones we have:
* `Stage optimize   : NMAKE : fatal error U1077: 'C:\projects\rakudo\install\bin\moar.exe' : return code '0xc0000005'`
* `No plan found in TAP output` for numerous files during testing
* `Stage optimize   : MoarVM panic: Internal error: invalid thread ID -795475840 in GC work pass` <- this one bothers me the most.

Such a persistent inability to build something means a release blocker.

**Comment by lizmat** [comment]
Open failed: No such file or directory at C:/projects/rakudo/tools/lib/NQP/Config/Rakudo.pm line 850.

**Comment by Altai-man** [comment]
https://github.com/MoarVM/MoarVM/commit/162b68b6b676318901c7baf6fd4c4955710b6f7d is the most likely culprit based on commit history.

**Comment by ugexe** [comment]
@MasterDuke17 any reason not to revert that commit if the above comment is correct?

**Comment by MasterDuke17** [comment]
> @MasterDuke17 any reason not to revert that commit if the above comment is correct?

Well, I'm not exactly sure what the plans are re @jnthn's rethinking of dispatching. If he's planning to implement the rework before the next release, reverting might not be required (though the code in the commit might go away). If it'll take so long that we want to get a release out the door, then sure, but there will be a performance hit. But is the AppVeyor problem still happening? I just rebased an old MoarVM PR (https://github.com/MoarVM/MoarVM/pull/689) and it's AppVeyor status is green (https://ci.appveyor.com/project/samcv/moarvm-35u74/builds/32313778).

**Comment by ugexe** [comment]
My guess is the MoarVM build/test/install scenario does not encounter the issue like building rakudo does.

**Comment by MasterDuke17** [comment]
> My guess is the MoarVM build/test/install scenario does not encounter the issue like building rakudo does.

Ah, for some reason I remembered the breakage happening during the NQP build (don't know why, it's pretty clearly Rakudo being mentioned in the issue).

**Comment by jnthn** [comment]
> Well, I'm not exactly sure what the plans are re @jnthn's rethinking of dispatching.

I got some good progress in on the design (though some things still needing exploration). I've got some days allocated next week for trying to implement it; I'll have a better feel for the overall timeline once I've spent some time trying to do that.

**Comment by Altai-man** [comment]
>But is the AppVeyor problem still happening?

It's Rakudo only, MoarVM is not enough to trigger it, but with rakudo it's 100% trigger-able.

**Comment by niner** [comment]
Fixed in https://github.com/MoarVM/MoarVM/commit/b77aa1622390b2f09473d8b8465dd048f004e9e7

Turned out to be a very subtle error in the JIT code really only affecting Windows due to different calling conventions and therefore different registers getting used.
