### ISSUE TITLE
&nextcallee can misbehave with wrapped routines in threaded code

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3569]
## The Problem
I have a short, racey script that I use to test `Trait::Traced`. This script no longer works properly after making it use `Routine.wrap` for routine call tracing. I golfed the issue down to this:

```perl6
sub foo { state $++ }
&foo.wrap: -> { bar nextcallee };

proto sub bar(&)   { say $*THREAD.id ~ ' ' ~ {*} }
multi sub bar(&cb) { cb }

(race for ^1024 { start foo })».result;
```

## Expected Behavior
This should output 1024 lines of thread IDs and call counts.

## Actual Behavior
This dies somewhere around the 500th call, usually:

```
Tried to get the result of a broken Promise
  in block <unit> at test.raku line 7

Original exception:
    Type check failed in binding to parameter '<anon>'; expected Callable but got Nil (Nil)
      in sub bar at test.raku line 4
      in block  at test.raku line 2
      in code  at test.raku line 7
```

## Steps to Reproduce

Save the test script as `test.raku` and run it.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.6 GENERIC.MP#43 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2020.02.1-239-g170add262 built on MoarVM version 2020.02.1-47-g3c3ad0678
implementing Raku 6.d.

**Comment by vrurg** [comment]
Did you try to bisect it? Is it a regression?

**Comment by Kaiepi** [comment]
I didn't think to try bisecting this before posting, but this looks like a regression because this code runs fine on v2020.02.1, even when running 65535 iterations instead of 1024.

**Comment by vrurg** [comment]
Ok, no need to bisect then. Only my changes could have resulted in it.

**Comment by vrurg** [comment]
BTW, why do you use `start` under `race`? It makes no sense to me.

**Comment by Kaiepi** [comment]
The aim's to stress out the thread pool scheduler as much as possible. It doesn't serve any functional purpose

**Comment by vrurg** [comment]
This is funny, but it has nothing to do with threading. Replacing the last line with just:

```raku
for ^1024 { foo }
```

Causes the same failure.... And a few second later: bingo! It's optimization:

```
$ MVM_SPESH_DISABLE=1 raku --ll-exception race.raku
3 0
3 1
3 2
[many more lines of the kind are skipped]
3 1021
3 1022
3 1023
```

**Comment by vrurg** [comment]
@MasterDuke17 you helped with JITting of nextdispatcher code in MoarVM. Maybe you can have a look at spesh too?

**Comment by niner** [comment]
@Kaiepi can you please try again with current rakudo master?

**Comment by Kaiepi** [comment]
My test script, along with the script in the OP, work OK for me now.

**Comment by Altai-man** [comment]
Can we close it?

**Comment by Kaiepi** [comment]
Fine with me.

**Comment by AlexDaniel** [comment]
Test. Ignore this please.
