### ISSUE TITLE
Lazy lists result in variety of errors, usually fatal

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#3570]
## The Problem
A regression in building lazy lists, programs fail or give incorrect results.

## Steps to Reproduce
Nub of the problem from http://rosettacode.org/wiki/Kolakoski_sequence#Raku:

% raku -e 'sub s () { my @a = 1, { @a[1] } ... * }; s()[1]'
This continuation has already been invoked
  in block <unit> at -e line 1

## Environment
Observed on macOS and Linux.
Problem first seen: Rakudo version 2020.02.1-233-g439b86095
Last good commit: Rakudo version 2020.02.1-231-g87226876a

This would seem to limit it to two commits on March 22nd.

## Related examples
All of these programs involve lazy lists, though the ways in which they malfunction can vary 
(e.g. the first program runs to completion, but gives incorrect results).
http://rosettacode.org/wiki/Esthetic_numbers#Raku
http://rosettacode.org/wiki/Four_is_the_number_of_letters_in_the_...#Raku
http://rosettacode.org/wiki/Gauss-Jordan_matrix_inversion#Raku
http://rosettacode.org/wiki/Palindromic_gapful_numbers#Raku
http://rosettacode.org/wiki/Smarandache_prime-digital_sequence#Raku

**Comment by lizmat** [comment]
Golfed to:

    $ raku -e 'say (my @A = 1, { @A[1] } ... *)[1]'
    This continuation has already been invoked

This code, which I think is functionally the same, does not cause any problems:

    $ raku -e 'say my @A = (1, { @A[1] } ... *)[1]'
    [(Any)]

**Comment by Altai-man** [comment]
This is certainly a blocker, right?

**Comment by lizmat** [comment]
@Altai-man not sure, as I think this is a. troublesome code to begin with, and b. may well have been like this since at least Christmas 2015.  I think this is the case because the commit just before the work I did on SEQUENCE also exhibited the problem, *and* before that the code basically hasn't been touched since 2015 (except for some optimizations by @zoffixznet in July 2017).

**Comment by lizmat** [comment]
FWIW, I intend to reverse engineer the `infix<...>` functionality to be completely iterator based, rather than being based on `gather`, `take`.  Which means that no continuation taking would be needed anymore, which would automatically fix this problem, I think.  And would help a lot in performance.

**Comment by thundergnat** [comment]
It would certainly be a blocker for me. Full disclosure: I am the author of ALL of the failing Rosettacode examples listed in the issue. It could certainly be said that I abuse the language in weird and wacky ways and skirt the edges of what is possible; that's kind-of the point. ++SqrtNegInf uses the Rosettacode Raku corpus as an early-warning smoke test, so pushing the language to its limits has some value. These examples have all _been_ working; for years in some cases, and still do in 2020.02, so it is definitely some kind recent change causing the failures.

 It is entirely possible that I have been abusing the language in improper ways, (you language molester you!) in which case we need to figure out how and update the examples and Raku docs.

**Comment by lizmat** [comment]
I suggest still not making it a blocker and see how fast I can get a reverse engineered alternative implementation for `infix:<...>` going.  This will *not* be ready for the 2020.03 release, but may very well be part of 2020.04.  Would that be ok?

**Comment by lizmat** [comment]
@thundergnat sanity check: what should `sub s () { my @A = 1, { @A[1] } ... * }; s()[1]` produce in your opinion ?

**Comment by thundergnat** [comment]
In general, I would expect that to produce:  Any

Though that specific code fails with "This continuation has already been invoked" even on much older releases; so I'm not 100% sure that it is tickling the exact same failure seen in the issue examples.

(To be sure, I think it would be nice if it DID work as I expect, but my expectations may not match up with reality.)

**Comment by lizmat** [comment]
OK, if `Any` is what you expected, then that's what you're going to get  :-)

**Comment by Altai-man** [comment]
Considering the situation, If it did not raise an exception (maybe due to another bug / change hiding the original bug) before and does now, that's a regression, meaning a blocker after all.

**Comment by lizmat** [comment]
Update: it looks like the given code is basically unsolvable.  A more direct approach:

    $ raku -e 'my @A = 1, @A[1]'
    ===SORRY!=== Error while compiling -e
    Cannot use variable @A in declaration to initialize itself

Now, with the `{ @A[1] }`, that compile time check doesn't trigger, but it probably should.  In my first iterator based attempts, it winds up in an infinite loop trying to produce the 2nd value (aka `@A[1]`).

Even if I prefill the `@A[1]` element, it winds up in an infinite loop.  Investigating were the actual recursion takes place: it is *not* in `Array.STORE`.

**Comment by lizmat** [comment]
Sorry, this problem has existed already for a long time.  It's not a blocker for 2020.03.  We *could* make it a blocker for 2020.04.

**Comment by Altai-man** [comment]
>Sorry, this problem has existed already for a long time

But rosetta code examples were working prior potential 2020.03, no?

**Comment by lizmat** [comment]
I'm focusing on the golf:

    [18:51:49]  <lizmat>	bisectable6: sub s () { my @A = 1, { @A[1] } ... * }; s()[1]
    [18:52:01]  <bisectable6>	lizmat, Bisecting by exit signal (old=2015.12 new=d8366ff). Old exit signal: 1 (SIGHUP)
    [18:53:43]  <bisectable6>	lizmat, bisect log: https://gist.github.com/6f2bdeff81d206dd231f074702300b8f
    [18:53:43]  <bisectable6>	lizmat, (2017-01-10) https://github.com/rakudo/rakudo/commit/e182deb5299076ef8c8cd40514b8817eaafbc92b

which clearly shows this is a long standing issue.

**Comment by thundergnat** [comment]
I think we steered you wrong from the get-go. (I did wonder if ```sub s () { my @A = 1, { @A[1] } ... * }; s()[1]``` ) was a red herring.  The "continuation already used" error was a symptom, but not the root cause.
I think I more accurately pinpointed the problem, flattened arrays are not reliably flattening. But only when followed buy a sequence. 

```
my @wat = flat [2,3,4], 10,11 ... *; say @wat[^5];
```
yields:  ([2 3 4] 10 11 12 13)

but used to yield: (2 3 4 10 11 12 13)

See https://colabti.org/irclogger/irclogger_log/raku?date=2020-03-26#l387

<bisectable6> thundergnat, bisect log: https://gist.github.com/35b46a929accbeca8bb5320dcf70a891
<bisectable6> thundergnat, (2020-03-22) https://github.com/rakudo/rakudo/commit/9286def3c85028a60f97bf2d41b505b13b3062b1

Interestingly enough, 
```my @wat = lazy flat [2,3,4], 10,11 .. *; say @wat[^5];``` is ok but 
```my @wat = lazy flat [2,3,4], 10,11 ... *; say @wat[^5];``` fails.

**Comment by lizmat** [comment]
Ok, I think I found the path of the recursion: basically `reify-at-least` calls `AT-POS`, which calls `reify-at-least` again.  Looking into this further.

**Comment by lizmat** [comment]
I will no longer pursue the recursion issue: this feels like a case of DIHWIDT.

**Comment by thundergnat** [comment]
Agreed. I can't really see how that would be particularly useful anyway, so probably not worth spending valuable time on. On the other hand, I _am_ fairly surprised that method form of take flattens and sub form doesn't. On the surface that seems a little odd, but there may be good reasons for it.
++lizmat in any case.
