### ISSUE TITLE
Feature: find as an independant routine in the core

### ISSUE THREAD

**Issue by tinmarino** [rakudo/rakudo#3571]
Could [File::Find](https://github.com/tadzik/File-Find) be included in the core as an [independent routine](https://docs.perl6.org/language/independent-routines) ?

1. It is really useful
2. Only few code is required
3. The test are already implemented
4. It saves code and readability as shown in [Rosetta](https://rosettacode.org/wiki/Walk_a_directory/Recursively#Raku)

Or even better: can it be included as a standard module (installed by default) and only loaded if `find` appears (so it doesn't slower the startup time).

**Comment by AlexDaniel** [comment]
This should probably be reopened in https://github.com/Raku/problem-solving.

As for the feature request itself, there is no justification presented besides a rosettacode example. I don't think that it is a trivial feature to implement, and there are enough complicated and buggy features that we need to maintain.

**Comment by tinmarino** [comment]
@AlexDaniel, effectively, it is not the right place. Sorry for that

**Comment by tinmarino** [comment]
Do you mean it is feature bloat ? In which case, your opinion is enough not to create another issue.
In the other case, I am willing to do a PR of some "on-demand default modules with attached routine" starting with Find::File or  just move the code.

**Comment by AlexDaniel** [comment]
@tinmarino I'm not fully sure. As a separate routine it surely is, but as a named arg to [`dir`](https://docs.perl6.org/routine/dir) maybe it is somewhat reasonable. Features like this are actually very delicate, it's easy to implement the basics but it's hard to get all edge cases right.
