### ISSUE TITLE
Compiler configuration key 'static_nqp_home' is used but never set

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3581]
## The Problem

When NQP home is determined in _main.nqp_ and _raudo-debug.nqp_ compiler configuration key `static_nqp_home` is used. But it is nowhere to be set in first place.

Same problem applies to NQP itself too.

I think they is expected to be set from `NQP::Config` of `nqp-configure` where a configuration variable of the same name exists. But for this to work it has to be added to _main-version.in_ build template. For NQP it should be _tools/build/gen-version.pl_.

I could add it on my own but not sure I could do appropriate testing.

Also, @patrickbkr, considering the discussion in Raku/nqp#608, I would suggest using kebab-case for the key: `static-nqp-home` – to stay in line with the existing keys in compiler configuration.

**Comment by patrickbkr** [comment]
Fixed with  PR #3602.
