### ISSUE TITLE
RFE: shell / no shell switch

### ISSUE THREAD

**Issue by ToddAndMargo** [rakudo/rakudo#3582]
Hi All,

Windows 10-1909 Pro
This is Rakudo version 2020.01 built on MoarVM version
2020.01.1 implementing Perl 6.d.

There are times when having a big black shell pop up when running a Raku program and othes when it is very much not desirable, such are running somethign fromteh registry:
```
[HKEY_CLASSES_ROOT\*\shell\OpenWithFileAttributes.pl6\command]
@="\"C:\\rakudo\\bin\\raku.exe\" \"K:\\Windows\\NtUtil\\FileAttributes.pl6\" \"%1\""
```
Would you please consider adding a no shell command line switch to the run string that would disable the big black shell pop up?

Raku --noshell myprogram.pl6

Many thanks,
-T

**Comment by ToddAndMargo** [comment]
Any movement on this?  I have customers killing the black box pop ups and causing havoc.

**Comment by Altai-man** [comment]
Hi. It is hard to say what is going on without knowing more about the code you have.
Can you provide some of the code you use? I suspect it it runs external commands using `shell` or `run`?

**Comment by patrickbkr** [comment]
I [read up](https://stackoverflow.com/a/574918/1975049) a bit about this. On Windows an executable is either marked as a `console` or a `windows` executable (or some obscurer others). I *think* that our `raku.exe` executables are marked as `console`. Which would mean they always spawn a console window in which the output is printed. If my guess is correct we should evaluate what the consequences of making our executables `windows` would be.

**Comment by vrurg** [comment]
@patrickbkr no way. A specific `rakudo-w.exe` which is a Win version – yes.

**Comment by vrurg** [comment]
Not really as I did very little win-programming. Literally – played for a moth with something years ago.

My point is that `rakudo` executable must open a console because it is likely to be desirable in many situations like double-clicking a _.raku_ file.

**Comment by ToddAndMargo** [comment]
On 2020-07-20 07:39, Altai-man wrote:
> Hi. It is hard to say what is going on without knowing more about the 
> code you have.
> Can you provide some of the code you use? I suspect it it runs external 
> commands using |shell| or |run|?


It is being run from from Cobian Backup.  I am
not sure how he is calling things.

**Comment by ToddAndMargo** [comment]
On 2020-07-20 08:02, Vadim Belman wrote:
> Not really as I did very little win-programming. Literally – played for 
> a moth with something years ago.
> 
> My point is that |rakudo| executable must open a console because it is 
> likely to be desirable in many situations like double-clicking a /.raku/ 
> file.


A "no shell switch" would be perfect.  That way, doubled clicking the 
file would give you the pop up you'd expect.
And I could run things in the background just by adding
a simple switch to the command line

Typical users see a black pop up windows and they click
"X" in the upper right corner faster than a shop-a-hollic
swipes a credit card.

**Comment by vrurg** [comment]
There is no way to turn a binary into windows or console one with a command line option. A binary bears a flag in its file header telling the system which way it's to be started.

Unless my years of Windows abstinence made me out of sync with modern trends.

**Comment by ToddAndMargo** [comment]
On 2020-07-20 17:39, Vadim Belman wrote:
> There is no way to turn a binary into windows or console one with a 
> command line option. A binary bears a flag in its file header telling 
> the system which way it's to be started.
> 
> Unless my years of Windows abstinence made me out of sync with modern 
> trends.

Seems to me them, that we would need two versions
of Raku to run then.  one with windows and one with
console

**Comment by ToddAndMargo** [comment]
Any idea when this will appear?

**Comment by Altai-man** [comment]
Most likely in Rakudo 2020.10 release, which is planned on 24th.

**Comment by ToddAndMargo** [comment]
On 2020-10-15 23:44, Altai-man wrote:
> Most likely in Rakudo 2020.10 release, which is planned on 24th.

Awesome!!!  Thank you guys!

**Comment by ToddAndMargo** [comment]
Request for an MSI:
https://github.com/rakudo/rakudo/issues/4001
