### ISSUE TITLE
sub push much slower than method push

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#3584]
While tinkering with an old benchmark program I noticed a rather large speed discrepancy between the sub and method forms of push:

    dogbert@dogbert-VirtualBox ~ $ perl6 -v
    This is Rakudo version 2020.02.1-262-g5baa645 built on MoarVM version 2020.02.1-69-g16ff158 implementing Raku 6.d.
    dogbert@dogbert-VirtualBox ~ $ perl6 -e 'my @a; push @a, $_ for ^500000; say now - $*INIT-INSTANT'
    2.7522366
    dogbert@dogbert-VirtualBox ~ $ perl6 -e 'my @a; @a.push: $_ for ^500000; say now - $*INIT-INSTANT'
    0.16206493

lizmat++ looked at some profiles and noticed that "it looks like @a.push is not getting jitted from inside sub push"

**Comment by lizmat** [comment]
Fixed with 385ab4cfce38a8b8d b98d2e00e119b5326 6541775c2ef53f7acc8 9b735b76997c3da7bb5080  Also tried to do `splice`, but that's an entirely different can of worms.
