### ISSUE TITLE
Native shaped array performance regression

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#3586]
##  The Problem

I'm noticing a significant drop in performance when creating native shaped arrays. Has regressed between Rakudo 2020.02.1 and the latest blead .e.g `for 1 ..^1000 {my uint64 @[4] = 3, 4, 5, 6;}` is much slower.

## Expected Behavior

```
$ perl6 -v ;/usr/bin/time perl6 -e' for 1 ..^1000 {my uint64 @[4] = 3, 4, 5, 6;}'
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
0.63user 0.06system 0:00.46elapsed 147%CPU (0avgtext+0avgdata 93964maxresident)k
0inputs+0outputs (0major+17531minor)pagefaults 0swaps
```

## Actual Behavior

```
perl6 -v ;/usr/bin/time perl6 -e' for 1 ..^1000 {my uint64 @[4] = 3, 4, 5, 6;}'
This is Rakudo version 2020.02.1-261-g478239e61 built on MoarVM version 2020.02.1-69-g16ff1585e
implementing Raku 6.d.
5.78user 0.17system 0:05.53elapsed 107%CPU (0avgtext+0avgdata 160360maxresident)k
0inputs+0outputs (0major+34552minor)pagefaults 0swaps
```
## Environment
* Operating system: Linux toshiba 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
* Compiler version (`perl6 -v`): Rakudo version 2020.02.1-261-g478239e61 built on MoarVM version 2020.02.1-69-g16ff1585e implementing Raku 6.d.

**Comment by lizmat** [comment]
Wow.  A profile shows that it is composing a type for each iteration.  That's pretty bad.

**Comment by lizmat** [comment]
It appears that reverting 80f2aebff482da6e6 solves the issue.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/4325972835
