### ISSUE TITLE
Rakudo JVM backend build broken on Windows

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3591]
While testing a fix for Raku/nqp#609 I have found out that JVM backend is unbuildable on Windows. The problem is simple enough: `NQP::Config::Rakudo` expects all `nqp-<backend>` runtimes to be `.exe`, but for JVM it is `nqp-j.bat`. 

The problem was introduced with abc072cd641525f8444284310b6c4bf7cbc1b284. @patrickbkr, can you have a look at it?

**Comment by markyys** [comment]
It appears that I can pass Configure.pl `--set-var="exe=.bat"` as a workaround,.

**Comment by vrurg** [comment]
It would be ok if you build one backend at a time. 

In either case `--set-var` isn't really recommended for manual use.

**Comment by patrickbkr** [comment]
This should be fixed with #3604.
