### ISSUE TITLE
(Inf .. Inf) is wrong

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3596]
Code:
```raku
say (Inf .. Inf)[^10]
```
Result:
```
(-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf)
```
Definitely shouldn't be negative infinity, the right answer is most likely `(Inf Inf Inf Inf …)`

Output on all releases: https://gist.github.com/6583c1c0b3d7e9cd2edcfa8651b5797d

Bisected: (2018-08-24) https://github.com/rakudo/rakudo/commit/a949a161446d7698e279b5e2943b28330c2eaf60

**Comment by AlexDaniel** [comment]
`Inf .. NaN` has the same issue.

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/2010266f68
