### ISSUE TITLE
Inconsistency between array and hash multi-dim indexing

### ISSUE THREAD

**Issue by jnthn** [rakudo/rakudo#3601]
## Expected Behavior

A hash slice like `%h{'a' ; 'b'}` would produce a single value, like `@a[1 ; 2]` does.

## Actual Behavior

It returns a 1-element `List` instead.

## Steps to Reproduce

```
$ ./rakudo-m -e 'my @a = [1,2],[3,4]; dd @a[1;0]'
Int element = 3
$ ./rakudo-m -e 'my %h = x => { :1a }; dd %h{"x";"a"}'
(1,)
```

## Environment
* Operating system: Ubuntu 16.04
* Compiler version (`perl6 -v`): 2020.02.1-316-g78ee549

**Comment by lizmat** [comment]
Behaviour change needed a language level change:
```
% raku -e 'my %h; %h<a><b> = 42; dd %h{"a";"b"}'
(42,)
% raku -e 'use v6.e.PREVIEW; my %h; %h<a><b> = 42; dd %h{"a";"b"}'
42
```
