### ISSUE TITLE
Exception.message does not really exist

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3603]
## The Problem

There's no `message` method in Exception.

```perl6
say Exception.new.message()
No such method 'message' for invocant of type 'Exception'
  in block <unit> at <unknown file> line 1
```

## Expected Behavior

Declare a stub and convert Exception into an abstract base class.

## Actual Behavior

It's not defined, but is [documented as defined](https://docs.raku.org/type/Exception#method_message) (actually, it's documented to be defined as a stub, which it's not)

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

Source at 99cb2fa2261d976f9a3455daf4007b06bba20596

**Comment by lizmat** [comment]
Add `Exception.message` as a stub.

I'm not sure what you mean with turning `Exception` into an abstract base class.  You mean a role to be punned?

**Comment by jnthn** [comment]
@lizmat Does that change of preserve the behavior of `class C is Exception { }; C.new.throw`?

**Comment by lizmat** [comment]
Looks like?

    [21:07:27]  <lizmat>	bisectable6: old=2020.02.1 class C is Exception { }; C.new.throw
    [21:07:28]  <bisectable6>	lizmat, On both starting points (old=2020.02.1 new=2e60552) the exit code is 1 and the output is identical as well
    [21:07:28]  <bisectable6>	lizmat, Output on both points: «Died with C␤  in block <unit> at /tmp/0KmXCd7r2_ line 1␤␤»

**Comment by jnthn** [comment]
OK, good, thanks.

**Comment by JJ** [comment]
El dom., 5 abr. 2020 a las 20:26, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

> Add Exception.message as a stub.
>
> I'm not sure what you mean with turning Exception into an abstract base
> class. You mean a role to be punned?
>
Well, as long as it's got a stub, you can't instantiate it...

**Comment by jnthn** [comment]
> Well, as long as it's got a stub, you can't instantiate it...

That's true of roles. It is not true of classes.

**Comment by JJ** [comment]
Thanks! (And that's documented, although probably not where it should
https://docs.raku.org/language/glossary#Abstract_class)
