### ISSUE TITLE
Segfault when trying to print last element of nqp::backtrace()

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3605]
## The Problem
While hunting a NullPointerException on the JVM backend I've stumbled upon a segfault on MoarVM. The ```nqp::backtrace()``` that is used to produce the segfault stems from ```src/core.c/CallFrame.pm6``` -- it's actually used in [```sub callframe```](https://github.com/rakudo/rakudo/blob/2e60552099/src/core.c/CallFrame.pm6#L62).

```
$ ./rakudo-m -e 'use nqp; my $bt := nqp::backtrace(nqp::handle(nqp::die(""),"CATCH",nqp::exception)); say nqp::elems($bt)'
11
$ ./rakudo-m -e 'use nqp; my $bt := nqp::backtrace(nqp::handle(nqp::die(""),"CATCH",nqp::exception)); say $bt[10]'
Segmentation fault (core dumped)
```

Looking a bit further, it turns out that the key ```sub``` in that last element of that backtrace contains a NULL:
```
$ ./rakudo-m -e 'use nqp; my $bt := nqp::backtrace(nqp::handle(nqp::die(""),"CATCH",nqp::exception)); my $sub := nqp::atkey(nqp::getattr($bt[10],Map,"\$!storage"),"sub"); dd nqp::isnull($sub)'
1
```

If I'm not mistaken this NULL comes from this line: https://github.com/MoarVM/MoarVM/blob/c7e75be60a/src/core/exceptions.c#L576. Doing a NULL check there and falling back to ```tc->instance->VMNull``` seems to avoid the segmentation fault. But I don't know if that would be the correct fix.

## Expected Behavior
Obviously, there should be no segfault. I'm not sure what the correct value for ```sub``` should be at that point.

Compiler version (`perl6 -v`):
```
This is Rakudo version 2020.02.1-289-g2cbf58372 built on MoarVM version 2020.02.1-71-g1bd5f19e0
implementing Raku 6.d.
```

**Comment by jnthn** [comment]
> Doing a NULL check there and falling back to tc->instance->VMNull seems to avoid the segmentation fault. But I don't know if that would be the correct fix.

yes, it would.
