### ISSUE TITLE
LAST before FIRST

### ISSUE THREAD

**Issue by Jlevens** [rakudo/rakudo#3608]
## The Problem

LAST phaser in a loop executes before FIRST and related issues

### Example 1, expected
Starting loop
0
1
2
Finishing loop
### Example 1, actual
Finishing loop
Starting loop
0
1
2

### Example 2, expected
The last number was 5.

### Example 2, actual
The last number was 1.

### Example 3, expected
Starting loop
0
1
2
Finishing loop
The last number was 5.

### Example 3, actual
WARNINGS for /home/julian/raku/last3.raku:
Useless use of LOOP_BLOCK_1 symbol in sink context (line 4)
Starting loop. $n is n
0
1
2
Finishing loop. $n is n
The last number was 1.

Note that the first loop now works, while the second one does not. Plus there's now a superfluous warning given.

## Steps to Reproduce

3 short example programs

Example 1: (from Learning Perl 6 by Brian D Foy, chapter 5: Phasers (changed so $n is not output thus eliminating warning about undefined $n))

```raku
sub MAIN () {
    loop {
        state $n = 0;
        put $n++;
        last if $n > 2;
        FIRST { put "Starting loop. \$n is n" }
        LAST { put "Finishing loop. \$n is n" }
    }
}
```

Example 2: (from https://docs.raku.org/syntax/last)

```raku
sub MAIN () {

    my Int $i = 1;
    while ($i < 10) {
        if ($i % 5 == 0) {
            last;
        }
 
        LAST {
            say "The last number was $i.";
        }
        NEXT {
            $i++;
        }
    }
}
```

Example 3 (above examples combined):

```raku
sub MAIN () {
    loop {
        state $n = 0;
        put $n++;
        last if $n > 2;
        FIRST { put "Starting loop. \$n is n" }
        LAST { put "Finishing loop. \$n is n" }
    }

    my Int $i = 1;
    while ($i < 10) {
        if ($i % 5 == 0) {
            last;
        }
 
        LAST {
            say "The last number was $i.";
        }
        NEXT {
            $i++;
        }
    }
}
```

## Environment
* Operating system: Linux julian-MS-7918 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

**Comment by JJ** [comment]
Maybe [related](https://colabti.org/irclogger/irclogger_log/raku?date=2020-12-19#l83):

```

09:14 | atroxaper | First strange thing. Does LAST in a loop work wrong?
-- | -- | --
09:15 | atroxaper | m: sub foo() { loop { LAST {say "LAST"}; say "IN"; last } }; foo
09:15 | camelia | rakudo-moar 604f64f46: OUTPUT: «LAST␤IN␤»
09:15 | atroxaper | Second strange thing. Does return in a loop with LAST work wrong?
09:16 | atroxaper | m: sub foo() { loop { LAST {say "LAST"}; say "IN"; return } }; foo
09:16 | camelia | rakudo-moar  604f64f46: OUTPUT: «LAST␤Attempt to return outside of  immediately-enclosing Routine (i.e. `return` execution is outside the  dynamic scope of the Routine where `return` was used)␤ in code at  <tmp> line 1␤ in block <unit> at <tmp> line 1␤␤IN␤»
09:16 | atroxaper | Without LAST:
09:16 | atroxaper | m: p6: sub foo() { loop { say "IN"; return } }; foo
09:16 | camelia | rakudo-moar 604f64f46: OUTPUT: «IN␤»

```

**Comment by coke** [comment]
I don't see the warning on example 2 with v2021.04 - can you verify this is still an issue?

**Comment by Jlevens** [comment]
I will check this out, sorry not until August, moving home right now

**Comment by lizmat** [comment]
Assuming this is no longer an issue
