### ISSUE TITLE
Closing curly brace missing?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3615]
## The Problem

I'm sure there's something I miss here, but why is the curly brace that closes this missing?

https://github.com/rakudo/rakudo/blob/e3a9d641e1003ddff39043dcf083ebaf587150a9/src/core.c/Supply.pm6#L70-L105

**Comment by lizmat** [comment]
The `Supply` class is spread over 3 files.  https://github.com/rakudo/rakudo/commit/b9105f1a8b should make that clear.

**Comment by JJ** [comment]
How is it assembled before compilation?

**Comment by lizmat** [comment]
By the normal core setting logic, that assembles *all* source files in `src/core.c` into a single file for compilation in the order as determined by `tools/templates/6.c/core_sources`
