### ISSUE TITLE
Modifying a Map no longer complains

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3617]
Code:
```raku
my %e := Map.new(‘a’, 1, ‘b’, 2);
%e<c> = 42;
dd %e
```
Output:
```
Map.new((:a(1),:b(2)))
```

Output on all releases: https://gist.github.com/09943cb4d55dc59ffa704823ef291df6
Bisected: (2019-07-24) https://github.com/rakudo/rakudo/commit/2ee82afe6e6713c26b929e2855ea05d8eb3b9fee

**Comment by vrurg** [comment]
Funny bug: where it used to be a `die` with a condition, only condition left. Easy fix, will do tomorrow unless @lizmat do it first.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/1a10b63a28 added tests with https://github.com/Raku/roast/commit/d28673780b
