### ISSUE TITLE
Type capture cannot be used in return type

### ISSUE THREAD

**Issue by hughsimpson** [rakudo/rakudo#3618]
## The Problem
A type capture used in a sub's return type always dies with `X::TypeCheck::Return`

## Expected Behavior
`X::TypeCheck::Return` is only throw when the return value of the sub is _not_ capture type,

## Actual Behavior
`X::TypeCheck::Return` is thrown every time

## Steps to Reproduce
```
sub test(::T, T $foo --> T) { $foo } ; 
test Str, "foo"
```

## Environment
```
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

**Comment by lizmat** [comment]
Feels to me that these could be related:

    $ raku -e 'sub test(::T, T $foo --> Str) { } ; dd &test.signature.returns.WHO.^name
    "Stash"

    $ raku -e 'sub test(::T, T $foo --> T) { } ; dd &test.signature.returns.WHO.^name
    "VMNull"

so it feels to me something is not being propagated properly.

**Comment by wimvanderbauwhede** [comment]
This is the same bug as  #2595.

**Comment by usev6** [comment]
This seems to work nowadays:
```
$ ./rakudo-m -e 'sub test(::T, T $foo --> T) { $foo }; test Str, "foo"; say "alive"'
alive
$ ./rakudo-m -e 'sub test(::T, T $foo --> T) { $foo }; test Str, 42; say "alive"'
Type check failed in binding to parameter '$foo'; expected Str but got Int (42)
  in sub test at -e line 1
  in block <unit> at -e line 1
```

According to ```bisectable6``` it has been fixed with https://github.com/rakudo/rakudo/commit/a302194442 (https://github.com/rakudo/rakudo/pull/5048).

Tests, that cover this behaviour, have been added to roast with https://github.com/Raku/roast/commit/eedaf1471a. So I'm closing this issue as resolved.
