### ISSUE TITLE
Call to non-existing method Slip.from-loop in src/core.c/array_slice.pm6

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3624]
## The Problem
This line from src/core.c/array_slice.pm6 has a call to ```Slip.from-loop()```: https://github.com/rakudo/rakudo/blob/f987cdb0ba/src/core.c/array_slice.pm6#L250

But we only have ```Seq.from-loop()```.

Unfortunately, I have no idea for code that would trigger this elsif branch (to create a test and changing the line to use the exising ```from-loop``` method).

> 20:47 | lizmat | m: Slip.from-loop
> 20:47 | camelia | rakudo-moar  f987cdb0b: OUTPUT: «No such method 'from-loop' for invocant of type  'Slip'␤ in block <unit> at <tmp> line 1␤␤»
> 20:47 | lizmat | which implies that path is never taken
> [...]
> 20:49 | lizmat | seeing that that code has been in there since Sep 2015, I'm pretty sure we can just take it out
> 20:49 | lizmat | as there has been no test breakage and no ecosystem breakage because of it

**Comment by niner** [comment]
> Unfortunately, I have no idea for code that would trigger this elsif branch
> (to create a test and changing the line to use the exising ```from-loop```
> method).

Seems pretty straight forward to me:
raku -e 'my @a; my @i = 1, 2; my @c = 1, 2; @a[@i] = @c.iterator'
No such method 'from-loop' for invocant of type 'Slip'

**Comment by lizmat** [comment]
I think this is a leftover from before the GLR.  An `Iterator` is *not* an `Iterable`.  For the same reason, this doesn't iterate:

    my @a = ^5;
    .say for @a.iterator; # Rakudo::Iterator::ReifiedArrayIterator.new

So I think deleting that piece of code was the right thing to do.

**Comment by usev6** [comment]
For the sake of completeness: the code I've mentioned in the original report has been removed with 3aaca26a52. Therefor I'm closing this issue.
