### ISSUE TITLE
Explicit MAIN breaks LAST

### ISSUE THREAD

**Issue by synthmeat** [rakudo/rakudo#3626]
## The Problem

Explicit `MAIN` breaks `LAST`.

```
sub MAIN () {
  loop {
    state $n = 0;
    put $n++;
    last if $n > 2;
    LAST { put $n }
  }
}
```

## Expected Behavior

```
0
1
2
3
```

## Actual Behavior

```
Use of uninitialized value $n of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in block  at exercise.raku line 8
0
1
2
```
## Steps to Reproduce

Just running the said example.

## Environment
* Operating system: macos 10.15.4
* Compiler version (`perl6 -v`): This is Rakudo version 2020.01 built on MoarVM version 2020.01.1 implementing Perl 6.d

**Comment by AlexDaniel** [comment]
If anybody is interested, output on all releases: https://gist.github.com/6dd390dbe257fce676b110ee128c64f2

**Comment by Jlevens** [comment]
#3608 appears to be related. I've just re-tested the examples in #3608 without an explicit MAIN and the results are mostly correct, but with spurious warnings.

**Comment by JJ** [comment]
It will probably happen for any kind of function, as shown in #3608. Probably in any case it's in sink context, I would say. I'll try to think about a way to sink a loop to check if that's the case.

**Comment by lizmat** [comment]
Test added with https://github.com/rakudo/rakudo/commit/dd62b98e09
