### ISSUE TITLE
Assigning to num32 variable breaks the REPL

### ISSUE THREAD

**Issue by puyawsiht** [rakudo/rakudo#3632]
## The Problem 

    > my num32 $x = 1.Num
    1
    > 2
    Unhandled lexical type 'num32' in lexprimspec
    
    > "a"
    Unhandled lexical type 'num32' in lexprimspec
    
    > say "halp :("
    Unhandled lexical type 'num32' in lexprimspec
    
All other types I tried worked fine.

## Environment

Tested on both

    $ raku -v
    This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
    implementing Raku 6.d.

and

    $ ~/build/rakudo-prefix/bin/raku -v
    This is Rakudo version 2020.02.1-332-gfdfa6ac85 built on MoarVM version 2020.02.1-86-gab3f19251
    implementing Raku 6.d.

**Comment by raiph** [comment]
cf https://stackoverflow.com/questions/61087357/int32-failure-in-raku#comment108079091_61087357
