### ISSUE TITLE
Hardwired /usr/bin/env breaks in some environments

### ISSUE THREAD

**Issue by lembark** [rakudo/rakudo#3635]
## The Problem

Line 53:
    my $perl_wrapper = '#!/usr/bin/env #perl#

/usr/bin/env does not exist on all *NIX platforms; the absolute path may also be '/bin/env'.

## Expected Behavior

Generating #! code that references an extant "env" executable.

e.g., checking if the absolute path exists prior to inserting it w/ a terniary operator prior to writing the file.

## Actual Behavior

Generating #! code that blows up due to a non-existant /usr/bin/env.

## Steps to Reproduce

Install, for example, zef and notice that ./bin/zef begins with "#!/usr/bin/env"

## Environment
* Operating system: Linux
* Distribution: Gentoo 

* Compiler version (`perl6 -v`): 

This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
Raku::source-digest=004deb157fb8c3c0506108049265d0f68ab84f15

**Comment by lembark** [comment]
e.g., 

state $env_path =  |</usr/bin/env /bin/env>.first( { "$_".IO.e } );

**Comment by niner** [comment]
Can you please submit a PR with that change?

**Comment by lembark** [comment]
Working on it. Basic iteration is to take the first of /bin/env or /usr/bin/env, lacking that find an 
absolute path to rakudo or give up.

**Comment by lembark** [comment]
If you want to believe that all reasonable systems will have env on them this is trivial; the messy part is finding a solution using $.prefix to locate bin/rakudo where env doesn't exist.
