### ISSUE TITLE
The situation with .. and … 

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3638]
This is an empty ticket to group/link other tickets. It makes my work easier.

**Comment by AlexDaniel** [comment]
More tickets:
* https://github.com/rakudo/rakudo/issues/3599
* https://github.com/rakudo/rakudo/issues/3598
* https://github.com/rakudo/rakudo/issues/3600
* https://github.com/rakudo/rakudo/issues/3596
* https://github.com/rakudo/rakudo/issues/3597
* https://github.com/rakudo/rakudo/issues/3595
* https://github.com/rakudo/rakudo/issues/1224

**Comment by lizmat** [comment]
Calling something a "trainwreck" is not helping getting any problems fixed.

**Comment by AlexDaniel** [comment]
To be clear, I think there are two issues at hand. One is that the implementation is just buggy, which can be fixed. Another is that the behavior is often unpredictable and generally there are *a lot* of edge cases, which is a language problem that is much harder to fix. That said, the two go together because complex unpredictable features are hard to implement correctly.

Ranges and Sequences are completely different features. However, their behavior mimics each other so if we're changing one then the other needs to be tweaked too (or if we have found an edge case for one then it's very likely that the same edge cases should be considered for the other feature).

@lizmat++ is working on improving https://github.com/lizmat/Sequence-Generator

**Comment by AlexDaniel** [comment]
This was a ticket primarily for myself. I don't need it anymore. If somebody else does, feel free to reopen.
