### ISSUE TITLE
When a file opened in exclusive mode doesn't exist raku should throw a useful exception

### ISSUE THREAD

**Issue by barcharcraz** [rakudo/rakudo#3640]
## The Problem

if a file opened in exclusive mode doesn't exist rakudo throws an X::AdHoc exception,
this isn't that useful for trying to open a "lock" file

## Expected Behavior

rakudo should throw a useful exception, maybe something like 'X::IO::FileExists"

## Actual Behavior

rakudo throws an X::AdHoc exception

## Steps to Reproduce

"foo".IO.open(:create, :exclusive);
CATCH {
default { say .perl }
}

## Environment
* Operating system: 
Windows 10
* Compiler version (`perl6 -v`): 
This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

**Comment by lizmat** [comment]
Cannot reproduce, assuming this is no longer an issue.  Please re-open if this assumption is wrong
