### ISSUE TITLE
The current position in file can seem advanced after .readchars 

### ISSUE THREAD

**Issue by doomvox** [rakudo/rakudo#3646]
## The Problem

Code like this returns to the same place in the
file only in the case of 7-bit ascii-range characters:

    my $fh    = $file.IO.open;
    my $str   = $fh.readchars($grapheme_count);
    my $width = $str.encode('UTF-8').bytes;  
    $fh.seek: -$width, SeekFromCurrent;

For anything above the ascii range the current
location ($fh.tell) is larger than you might expect by
3 bytes.

Brad Gilbert explains that this is a side-effect of a
look-ahead strategy to deal with unicode combining
characters:

  https://www.nntp.perl.org/group/perl.perl6.users/2020/04/msg8385.html

I suggest it would be better if Raku programmers were
better insulated from this behavior and had a simpler
meaning for the "current" point in file that would be
easier to understand.

If that's not practical, the actual behavior needs to be better documented.

## Expected Behavior

After a .readchars, .tell should report a new position
advanced by the number of bytes associated with the
characters (graphemes) that have been read.

## Actual Behavior

When reading unicode characters (meaning, characters
with codepoints beyond the 7-bit ascii range), the
current point in the file is advanced 3 bytes beyond
the characters that have been read via .readchars.

## Steps to Reproduce

A test file should be attached which fails
with the current behavior of Raku: "current_position_after_readchars.t"

## Environment
* Operating system: 
* Compiler version (`perl6 -v`):

**Comment by doomvox** [comment]
[current_position_after_readchars.tar.gz](https://github.com/rakudo/rakudo/files/4536488/current_position_after_readchars.tar.gz)

**Comment by lizmat** [comment]
@coke ping
