### ISSUE TITLE
WhateverCode.raku shows up as { … } but WhateverCode is not a Block

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3653]
Basically:
```
say (*+2).raku # OUTPUT: «{ ... }␤»
```
Output on all releases: https://gist.github.com/18caecf989cea86977beca1b45f93a55
Bisected: (2016-03-04) https://github.com/rakudo/rakudo/commit/360232a54fadc83efdafc29dfe808677bcde2865

Its mro is (WhateverCode, Code, Any, Mu), so technically it's not a Block so it shouldn't .rakufy as `{ }` (`WhateverCode.new` is a better answer).

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/f115a8a556
