### ISSUE TITLE
.reverse on arrays with holes (Mu)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3654]
```raku
my @a = 4,8,15,16;
@a[1]:delete;
.say for @a; # the hole will appear as (Any)
say ‘----’;
.say for @a.reverse; # the hole will appear as (Mu)
```

Output on all releases: https://gist.github.com/ae0c6598a5bd214e77f51a3b25aed44f
Bisected: (2017-03-01) https://github.com/rakudo/rakudo/commit/beda5767ba6934e84122a0c0458a53d919c695d0

**Comment by lizmat** [comment]
Possibly fixed with e9468d6a02

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/ca49c153db , adding correct container support

**Comment by lizmat** [comment]
tests added with https://github.com/Raku/roast/commit/d0452c4f14
