### ISSUE TITLE
:delete-ing fractional indexes sometimes doesn't work

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3657]
```raku
my @a = <3 4 5>;
@a[0.5, 0.5]:delete;
say @a;
say @a.elems
```
and
```raku
my @a = 3, 4;
@a[1.5, 0.5]:delete;
say @a;
say @a.elems
```
You'd expect elements to be deleted but they're not.

Output on all releases:
* https://gist.github.com/2775723fe3e02fe07e8b5672874608ef
* https://gist.github.com/356a54aabe571f66534d8f182dd684fa

**Comment by AlexDaniel** [comment]
Ah, actually, I don't think it works at all. But it should.

**Comment by mustafaaydn** [comment]
both cases work since 2021.02.1:
https://gist.github.com/Whateverable/e97a8056e4cb689615716c291e6c746b
https://gist.github.com/Whateverable/ba626db2788284457f803069da91447a

**Comment by lizmat** [comment]
Added tests with https://github.com/Raku/roast/commit/82d5b1b0e7
