### ISSUE TITLE
@a[-42..∞]:delete does not work

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3658]
Code:
```raku
my @a = 3, 4, 5;
@a[-5..∞]:delete; # same should work with *
say @a;
say @a.elems
```

Output:
```
[3 4 5]
3
```

It should work because -5..99999999 deletes all elements.

Output on all releases: https://gist.github.com/78189c36599a3dbb02724435723053b0

Related:
* (2017-10-08) https://github.com/rakudo/rakudo/commit/456358e3c380eeeb5fe5bc6260ba6f51c42a52ff
* (2018-02-08) https://github.com/rakudo/rakudo/commit/f330d7fc44d76258e651c9114360d08f929b25b9

**Comment by AlexDaniel** [comment]
FWIW same happens with …

**Comment by lizmat** [comment]
Negative indices are not allowed on slices, so it should die, should it not?

**Comment by lizmat** [comment]
Working on this in the `faster-slice-access` :-)

**Comment by lizmat** [comment]
The problem is not with infinity, but with laziness:
```raku
my @a = 1,2,3;
say @a[(-1..2).lazy];  # ()
say @a[(-1..2).lazy];  # Index out of range. Is: -1, should be in 0..^Inf
```

**Comment by lizmat** [comment]
Also, it appears that slices produce a list with Failures.  The above error is caused by the `say` throwing a `Failure`, which `dd` doesn't:
```raku
my @a = 1,2,3;
dd @a[-1..9];
# (Failure.new(exception => X::OutOfRange.new(what => "Index", got => -1, range => "0..^Inf", comment => Any), backtrace => Backtrace.new), 1, 2, 3, Any, Any, Any, Any, Any, Any, Any)
```

**Comment by lizmat** [comment]
So preliminary conclusion is that the laziness of the `Range` (and thus its iterator) causes the slice production to halt the production / adverb application of the slice if a `Failure`is produced (which is probably interpreted as an empty slot).  Compare:
```raku
my @a = 1,2,3;
dd @a[(1,-1,0)]:delete;
# (2, Failure.new(exception => X::OutOfRange.new(what => "Index", got => -1, range => "0..^Inf", comment => Any), backtrace => Backtrace.new), 1)
dd @a;
# [Any, Any, 3]
```
with
```raku
my @a = 1,2,3;
dd @a[(1,-1,0).lazy]:delete;
# (2,)
dd @a;
# [1, Any, 3]
```
