### ISSUE TITLE
Iteration past end of grapheme iterator (my $b = ‘a’ x 99999; say ‘a’ ~ $b)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3660]
This works fine:
```raku
my $b = ‘a’ x 66666; say ‘b’ ~ $b OUTPUT: «baaaaa…»
```
This doesn't:
```raku
my $b = ‘a’ x 66666; say ‘a’ ~ $b # OUTPUT: «Iteration past end of grapheme iterator␤  in block <unit> at <tmp> line 1␤␤»
```

See this:
https://github.com/MoarVM/MoarVM/blob/3d8ff61e20a8abde79b46fec5f324c54433d5fb2/src/strings/ops.c#L813

uint16 :joy: :joy: :joy:

**Comment by MasterDuke17** [comment]
Whoops, needs tests.

**Comment by melezhik** [comment]
I've added rkp for this - http://rakudist.raku.org/sparky/report/RakuPlay-3/1213 if it helps ...
