### ISSUE TITLE
I cannot install 2020.05 version of rakudo

### ISSUE THREAD

**Issue by wtwt5237** [rakudo/rakudo#3666]
I cannot install 2020.05 version of rakudo. This is the error that I got:

[twang6@Nucleus005 raku]$ perl Configure.pl --gen-moar --gen-nqp --backends=moar 
error: could not lock config file .git/config: No such file or directory
error: could not lock config file .git/config: No such file or directory
Can't locate NQP/Config.pm in @INC (you may need to install the NQP::Config module) (@INC contains: /project/shared/xiao_wang/software/raku/tools/lib /project/shared/xiao_wang/software/raku/3rdparty/nqp-configure/lib /home2/twang6/software/languages/perl/lib/lib/5.22.1/x86_64-linux /home2/twang6/software/languages/perl/lib/lib/5.22.1 /home2/twang6/software/languages/perl/lib/lib /home2/twang6/software/languages/perl/lib/site_perl/5.22.1/x86_64-linux /home2/twang6/software/languages/perl/lib/site_perl/5.22.1 /home2/twang6/software/languages/perl/lib/5.22.1/x86_64-linux /home2/twang6/software/languages/perl/lib/5.22.1 .) at Configure.pl line 30.
BEGIN failed--compilation aborted at Configure.pl line 30.

I am working on linux. Could you please give me some advice?

Thanks!

Tao

**Comment by nxadm** [comment]
@wtwt523, do you have write access to the directory? If you do, you can try this:
rm ~/.gitconfig.lock
ls -la ~/.gitconfig

If not owned by you:
sudo chown $SUDO_USER:$SUDO_GID ~/.gitconfig

**Comment by wtwt5237** [comment]
Thanks, @nxadm 

The git problem is easy to solve. 

It took me a while to figure out how to get around the nqp::configure issue. I had to download nqp_configure myself from github and manually put them where they belong for raku to be installed

It looks like the newer version of 2020.05 is slower than 2020.02:

https://github.com/wtwt5237/raku-for-bioinformatics/blob/master/README.md

**Comment by nxadm** [comment]
If it's a regression, pop on the [IRC channel](https://www.raku.org/community/irc) and let people know. Speed improvements is something many rakudo devs care about.

If possible, can you run your tests against my packages as well. I didn't encounter any problems when building them today: https://github.com/nxadm/rakudo-pkg

**Comment by timo** [comment]
did you use github's "donwload zip" feature? it doesn't give you submodules, which are really quite necessary for installation to work

**Comment by wtwt5237** [comment]
@timo 

I downloaded the "source (tar.gz)" file from https://github.com/rakudo/rakudo/releases

**Comment by timo** [comment]
i believe those are auto-generated by github and don't have what you need. the tgz above that should be exactly what you need. i've got to double-check if we can make the wrong ones go away - last time i checked it didn't seem possible

**Comment by wtwt5237** [comment]
gotcha, @timo

**Comment by Altai-man** [comment]
@wtwt5237 hi!
Does use of rakudo-2020.05.tar.gz help?
If yes, while the regression is something to file in another ticket, can this be closed?

**Comment by wtwt5237** [comment]
@Altai-man 

It doesn't help with the speed. Installation issue is solved.
