### ISSUE TITLE
native ints don't match Int in a multi

### ISSUE THREAD

**Issue by CurtTilmes** [rakudo/rakudo#3667]
A native int works fine with an `Int` in a sub signature:
```
raku -e 'sub foo(int32 $x) { say $x }; foo(27);'
27
```

but doesn't match an `Int` in a multi:

```
raku -e 'multi foo(int32 $x) { say $x }; foo(27);'
Cannot resolve caller foo(Int:D); none of these signatures match:
    (int32 $x)
  in block <unit> at -e line 1
```

It seems like multi dispatch should allow that.

**Comment by jnthn** [comment]
In a `sub` signature, there's no decision making to do about where we're going; we call the `sub`, and as part of its parameter binding it unboxes the boxed integer object.

In multi dispatch, however, the goal is to pick an appropriate candidate, and the rules are defined in terms of topological sorting. A native `int` is narrower than a boxed `Int`, and so would be considered first. Thus if we had both an `int` and an `Int` candidate, and the `int` one admitted the boxed integer, we'd never reach the one for `Int`.

We already tried to DWIM in multi dispatch in all kinds of scenarios related to arity (slurpy, optional, etc.) to the degree that even though I implemented it, I couldn't tell you off the top of my head what the rules are. I'm not so interested in making the rules for the type side of it more complex.
