### ISSUE TITLE
Relocatability seems to be broken on Windows

### ISSUE THREAD

**Issue by Prince213** [rakudo/rakudo#3669]
## The Problem
Relocatability seems to be broken on Windows.
## Expected Behavior
```
X:\>raku -v
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.

X:\>raku

To exit type 'exit' or '^Z'
> use NativeCall;
Nil
>
```
## Actual Behavior
```
X:\>raku -v
This is Rakudo version 2020.05 built on MoarVM version 2020.05
implementing Raku 6.d.

X:\>raku

To exit type 'exit' or '^Z'
> use NativeCall;
===SORRY!=== Error while compiling:
Could not find NativeCall in:
    inst#C:\Users\FILLE_ME_IN\.raku
    inst#C:\projects\rakudo-bin\prefix\share\perl6\site
    inst#C:\projects\rakudo-bin\prefix\share\perl6\vendor
    inst#C:\projects\rakudo-bin\prefix\share\perl6\core
    ap#
    nqp#
    perl5#
>
```
## Steps to Reproduce
1. Start a REPL instance
2. Run `use NativeCall;`
## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2020.05 built on MoarVM version 2020.05
implementing Raku 6.d.
```

The scripts used to make the binaries can be found at https://github.com/Prince213/rakudo-bin and the binaries themselves can be found at https://ci.appveyor.com/project/Prince213/rakudo-bin.

**Comment by patrickbkr** [comment]
Datapoint: Using the precompiled 2020.02.1-02 release from rakudo.org ([rakudo-moar-2020.02.1-02-win-x86_64.zip](https://rakudo.org/dl/rakudo/rakudo-moar-2020.02.1-02-win-x86_64.zip)) works as expected.

@Prince213 Looking at the script  you used to build rakudo, you did not pass `--relocatable` to nqp `Configure.pl`. Can you do that and try again?

**Comment by Prince213** [comment]
I don't think 2020.02.1 has the problem. As you can see from the 'Expected Behavior' section, 2020.02.1 works fine. What I think has the problem is version 2020.05 which doesn't have a precompiled version yet.

**Comment by Prince213** [comment]
I will try to pass --relocatable option the nqp's Configure.pl. I'll come back to you with the result.

**Comment by Prince213** [comment]
I have added --relocatable and rebuilt the binaries, but the problem is still there.
```
X:\>raku --version
This is Rakudo version 2020.05 built on MoarVM version 2020.05
implementing Raku 6.d.

X:\>raku

To exit type 'exit' or '^Z'
> use NativeCall;
===SORRY!=== Error while compiling:
Could not find NativeCall in:
    inst#C:\Users\FILLE_ME_IN\.raku
    inst#C:\projects\rakudo-bin\prefix\share\perl6\site
    inst#C:\projects\rakudo-bin\prefix\share\perl6\vendor
    inst#C:\projects\rakudo-bin\prefix\share\perl6\core
    ap#
    nqp#
    perl5#
>
```

**Comment by patrickbkr** [comment]
@Prince213 This is now fixed on master. Thanks for your report!

**Comment by Altai-man** [comment]
This means a point release with the fix, right?

**Comment by Altai-man** [comment]
How is it even regressed in the first place, by the way?

**Comment by Altai-man** [comment]
Superseded by the new ticket.

**Comment by patrickbkr** [comment]
@Altai-man [This](https://github.com/rakudo/rakudo/commit/94fdb3d517f519aa14b513b667c0862d9afa9c5a#diff-efc15ae98a2fe750b38af943ea67fcb2L354) is the exact line that introduced this regression.
