### ISSUE TITLE
test t/02-rakudo/15-gh_1202 failed on alpine ppc64le architecture

### ISSUE THREAD

**Issue by CurtTilmes** [rakudo/rakudo#3670]
Building 2020.05 on the alpine linux build farm,  This is the only test that failed.

```
t/02-rakudo/15-gh_1202.t ........................................ 
 Dubious, test returned 1 (wstat 256, 0x100)
 Failed 1/2 subtests 
```
Here's the complete build log:

https://gitlab.alpinelinux.org/ctilmes/aports/-/jobs/110124#L1850

**Comment by Altai-man** [comment]
I see the test is kind of race-y (https://github.com/rakudo/rakudo/blob/master/t/02-rakudo/15-gh_1202.t), is the failure reliable?
Do we even officially support ppc64le, is there a list of architectures supported, by the way?

**Comment by AlexDaniel** [comment]
> Do we even officially support ppc64le, is there a list of architectures supported, by the way?

Yes, we tend to make sure that if rakudo used to build on some architecture then it should continue doing so. Usually it doesn't require a lot of effort, but occasionally there are some hard-to-track bugs.

**Comment by JJ** [comment]
Very probably a flapper...

**Comment by Altai-man** [comment]
>Yes, we tend to make sure that if rakudo used to build on some architecture then it should continue doing so

Is there is a list available? Are there means to make sure there are no regressions on all supported architectures before actual release?

**Comment by niner** [comment]
One thing that can help here is the builds I do for every rakudo commit on the Open Build Service: https://build.opensuse.org/project/show/home:niner9:rakudo-git

I've now added builds for openSUSE on ARM (aarch64 and armv7l), PowerPC and zSystems (that was literally just 3 clicks) and this already showed that Inline::Perl5 has endianness issues. And that zSystems is just not supported by dyncall (but maybe libffi?).

The Open Build Service supports many other distributions and targets. It just needs adaptions to the .spec files or alternative build descriptions (most importantly the .deb stuff)
