### ISSUE TITLE
Issue template still refer to perl6 and not raku 

### ISSUE THREAD

**Issue by shishini** [rakudo/rakudo#3672]
Below is the default template

&lt;!--

    The template below contains optional suggestions. You
    can omit some information.

--&gt;

## Steps to Reproduce
&lt;!-- Provide a set of steps to reproduce the problem.
     If the program unexpectedly crashes, please run it with
     `perl6 --ll-exception` and provide the produced output. --&gt;

## Environment
* Operating system: 
* Compiler version (`perl6 -v`):

**Comment by JJ** [comment]
Well, perl6 still works; in fact, raku will not work for versions older
than 2019.11. perl6 will be deprecated, but for the time being it stays. We
could mention the alternative, though...
