### ISSUE TITLE
-o command line option doesn't work

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#3676]
`raku --help` outputs:
```
...
-o, --output=name    specify name of output file
...
```
however, `r --target=mbc -o foo -e 'say "hi"'` dies with `Cannot dump this object; no dump method`, while `r --target=mbc --output=foo -e 'say "hi"'` successfully writes a bytecode file to foo. Same with NQP.

**Comment by lizmat** [comment]
This appears fixed
