### ISSUE TITLE
Relocatability does not have automatic tests

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3679]
Relocatability of rakudo/nqp/MoarVM builds is a relatively new feature and it appears we don't have non-manual tests for it yet. If we have, they are under-reported.
This leads us to cases like https://github.com/rakudo/rakudo/issues/3669

To close this issue, it is required to have:

* Automated tests for this feature (hopefully, it'll be easier to add with migration to azure pipelines?)
* Tests should check all three platforms but more is merrier
* Failures must be reported in a clear and easy to find way

As usual with blockers, there won't be new Rakudo release until we have this issue closed.

**Comment by patrickbkr** [comment]
There are no tests for this at all at the moment. I planed to work on this for quite a while now. I'll get to this soon.

**Comment by patrickbkr** [comment]
I have added an [Azure CI configuration](https://github.com/rakudo/rakudo/commit/78fe25b81fc59d871e188eb349dec1bf9c2d2090) to rakudo. It includes test runs on MacOS, Windows and Linux with a relocatable build that is moved. So I think this issue is now fixed.
