### ISSUE TITLE
Packaging and releasing the latest binaries

### ISSUE THREAD

**Issue by Prince213** [rakudo/rakudo#3681]
Since we have already set up CI to test Rakudo, we can also pack the binaries and release them, which enables users to have easy access to the latest bug fixes, new features, etc.

**Comment by nxadm** [comment]
See https://github.com/nxadm/rakudo-pkg

**Comment by lizmat** [comment]
Isn't this about just about every commit ?

**Comment by Prince213** [comment]
It seems that nxadm only provides binaries of releases.

**Comment by nxadm** [comment]
I don't think so. Maybe :)

**Comment by nxadm** [comment]
@Prince213 You're looking for the sources of releases?

**Comment by Prince213** [comment]
Nope, I'm looking for binaries for each commit (or at least the latest one).

**Comment by nxadm** [comment]
The releases sources are here: https://rakudo.org/downloads/rakudo/

**Comment by niner** [comment]
Binaries for every git commit are available for openSUSE at: https://build.opensuse.org/project/show/home:niner9:rakudo-git
This also tests various modules with each commit and soon the spectest suite.

**Comment by Altai-man** [comment]
I think this is about "nightly" releases, so commits directly from HEAD.
I wonder how safe that is. People can use rakudobrew (not sure if it works on Windows, though) to build any branch/commit/release if they want flexibility. But nightly releases on each commit... What's the use case?

**Comment by nxadm** [comment]
@Prince213, ah ok, @lizmat's interpretation was right. It's doable if needed. I think @niner does this already for Suse.

**Comment by Prince213** [comment]
Do we have anything similar for windows? (latest commits)

**Comment by patrickbkr** [comment]
I'm planing on setting up a comprehensive build and test pipeline on Azure. It should be easy to keep the build artifacts. This would result in artifacts for Linux, Windows and MacOS.

**Comment by MasterDuke17** [comment]
> I'm planing on setting up a comprehensive build and test pipeline on Azure.

I don't know how many resources are available, but there were some musings on #moarvm today about wanted to automate coverage reports of spectest runs.

**Comment by patrickbkr** [comment]
The [recently added Azure CI configuration](https://github.com/rakudo/rakudo/commit/78fe25b81fc59d871e188eb349dec1bf9c2d2090) tests a relocatable rakudo on Windows, MacOS and Linux and publishes the compiled artifacts.

The artifacts can be accessed [directly on the AzureCI website](https://dev.azure.com/rakudo/rakudo/_build?definitionId=1&_a=summary). Select a build, then click on the tiny _3 published_ at the top.

Those artifacts do have some limits as they are not built in the same way as the actual releases are built. (e.g. they are built on recent Linux and not an ancient one, which makes the executables unable to run on older Linuxes)

**Comment by patrickbkr** [comment]
@Altai-man [rakubrew](https://rakubrew.org) (rakudobrew is the old name) works fine on Windows. The only precondition for compiling ones own Rakudos on Windows is having Git and the MS BuildTools installed.
