### ISSUE TITLE
LTA error msg with improper use of '$' in format string

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3682]
## The Problem

Unhelpful error message when using sprintf.  Run the following Raku program:

    my $k = 'foo';
    my $v = 'bar %s';
    say sprintf("%s => $v", $k);
    
and get:

    Your printf-style directives specify 2 arguments, but 1 argument was supplied
      in block <unit> at ./sprintf-err.raku line 4

## Expected Behavior

An error message more like:

    Your printf-style directives specify 2 arguments, but 1 argument was supplied
      in block <unit> at ./sprintf-err.raku line 4
    Have you used a '$' symbol improperly?

## Environment
* Operating system: Debian Buster
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.05 built on MoarVM version 2020.05
implementing Raku 6.d.

**Comment by Altai-man** [comment]
Sorry?

**Comment by tbrowder** [comment]
I got sidetracked last night but wanted to ensure the issue was started.

**Comment by tbrowder** [comment]
Fixed and closed with commit c988f83.
