### ISSUE TITLE
Date(now) no longer works

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#3683]
## The Problem

Date(now) no longer works

## Expected Behavior

    say Date(now) # 2020-05-11 (or whatever)

## Actual Behavior

     say Date(now) # Type check failed in binding to parameter '$dateish'; expected Str but got Instant (Instant.from-posix(<89792177...)

See https://colabti.org/irclogger/irclogger_log/raku?date=2020-05-12#l2

bisectable6: 2020.01 say Date(now)
Using old=2020.01 new=HEAD in an attempt to do what you mean
Bisecting by exit code (old=2020.01 new=110324d). Old exit code: 0
bisect log: https://gist.github.com/5c4297b65b3da90a89e0d9dd1eddb18a
(2020-02-29) https://github.com/rakudo/rakudo/commit/d95d218f3192b06f0bb52bceb90e43d198747f09

on 2020.05 and HEAD

**Comment by lizmat** [comment]
Fixed with 9dcbc5ff76

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/6a90004e15
