### ISSUE TITLE
slurp routine with :enc("utf16") broken

### ISSUE THREAD

**Issue by doomvox** [rakudo/rakudo#3691]
## The Problem

The routine form of slurp doesn't read text correctly with the 
utf16 encoding:

    my $contents = slurp( $file, :enc("utf16") );

## Expected Behavior

If you've written text with the utf16 encoding, you would expect
you could read it back in using that feature of slurp (which
works for other encodings such as utf8 and latin1).

## Actual Behavior

You get an empty string.

## Steps to Reproduce

     my $unicode_string = "\x[1200]\x[2D80]\x[4DFC]\x[AAAA]\x[2CA4]\x[2C8E]";  
     my $file = "/tmp/unicode-chars-as-utf16.txt";
     my $fh = $file.IO.open( :w, :enc("utf16") );
     spurt $fh, $unicode_string;
     my $contents = slurp( $file, :enc("utf16") );

I'll attach a test file that excercises the routine and method
forms of slurp for various encodings: encodings_and_file_io.t

## Environment
* Operating system:

  uname -a
  Linux fandango 4.9.0-8-686 #1 SMP Debian 4.9.144-3 (2019-02-02) i686 GNU/Linux

* Compiler version (`perl6 -v` or `raku -v`):

  This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
  implementing Perl 6.d.

**Comment by doomvox** [comment]
[encodings_and_file_io.t.tar.gz](https://github.com/rakudo/rakudo/files/4624628/encodings_and_file_io.t.tar.gz)

**Comment by lizmat** [comment]
I cannot reproduce this on HEAD.

Could you try out the 2020.05 Rakudo Star Release candidate mentioned at https://www.nntp.perl.org/group/perl.perl6.users/2020/05/msg8451.html and see if the problem is solved with that version of Rakudo Star ?

**Comment by doomvox** [comment]
> Could you try out the 2020.05 Rakudo Star Release candidate

Sure, I'll give it a try.

**Comment by doomvox** [comment]
I'm afraid I don't know what to do with the "rc1" release you pointed me at.
I tried:

   cd /home/doom/End/Sys/Perl6/rakudo-star-2020.05-rc1/src/rakudo-2020.05.1
   perl Configure.pl --gen-moar --gen-nqp --backends=moar
   make

But afterwards I don't see the expected "perl6".  So I tried:


   apt-get install gdb gdb-doc

   ./perl6-gdb-m /home/doom/End/Cave/Perl6/bin/encodings_and_file_io.t

But now I'm just getting errors like:

   Unhandled exception: While looking for
'/home/doom/End/Sys/Perl6/rakudo-star-2020.05-rc1/src/rakudo-2020.05.1/perl6.moarvm':
no such file or directory

**Comment by doomvox** [comment]
I have a similar trouble with seeing how to build from github.

For what it's worth, I can reproduce the bug with the 2020.01 release:

cd /home/doom/End/Sys/Perl6/rakudo-star-2020.01
perl Configure.pl --gen-moar --gen-nqp --backends=moar
make

./perl6-m --version
This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

./perl6-m -Ilib /home/doom/End/Cave/Perl6/bin/encodings_and_file_io.t

Sub-tests 9 and 10 fail, which both test slurp with utf16 via the :enc option

**Comment by thundergnat** [comment]
FWIW as an passing observer, I get the same failure on 2020.05 on Linux Mint.

Interestingly enough, if I replace the encoding

    enc    => "utf16",

with 

    enc    => "utf8-c8",

on lines 38 and 43 of doomvox's test file, the tests all pass (bogus, but they pass)

It seems like it just isn't recognizing the utf16 encoding directive.

**Comment by doomvox** [comment]
Okay, so using the new (and not yet documented) method of
building perl6:

   perl Configure.pl --gen-moar --gen-nqp --make-install

I can reproduce the problem with both rakudo-star-2020.05-rc1 and
github HEAD.

I suggest just trying to run the attached test file:
  ./perl6 /home/doom/End/Cave/Perl6/bin/encodings_and_file_io.t 

You should see tests 9 & 10 fail, like so:

ok 1 - slurp method: latin1-range chars written by default as utf8
ok 2 - slurp method: latin1-range chars written using latin1 encoding
ok 3 - slurp method: unicode (bmp) chars written using explicit utf8 encoding
ok 4 - slurp method: latin1-range chars written using utf16 encoding
ok 5 - slurp method: unicode (bmp) chars written using utf16 encoding
ok 6 - slurp routine: latin1-range chars written by default as utf8
ok 7 - slurp routine: latin1-range chars written using latin1 encoding
ok 8 - slurp routine: unicode (bmp) chars written using explicit utf8 encoding
not ok 9 - slurp routine: latin1-range chars written using utf16 encoding
# Failed test 'slurp routine: latin1-range chars written using utf16 encoding'
# at /home/doom/End/Cave/Perl6/bin/encodings_and_file_io.t line 100
# expected: 'ÀÁÂÃÄÅýþÿ'
#      got: ''
not ok 10 - slurp routine: unicode (bmp) chars written using utf16 encoding
# Failed test 'slurp routine: unicode (bmp) chars written using utf16 encoding'
# at /home/doom/End/Cave/Perl6/bin/encodings_and_file_io.t line 100
# expected: 'ሀⶀ䷼ꪪⲤⲎ'
#      got: ''

**Comment by lizmat** [comment]
The problem is in the test code.  The file being spurted to is **NOT** closed, so it may not have flushed to disk yet.

    my $unicode_string = "\x[1200]\x[2D80]\x[4DFC]\x[AAAA]\x[2CA4]\x[2C8E]";
    my $file = "/tmp/unicode-chars-as-utf16.txt";
    spurt $file, $unicode_string, :enc<utf16>, :close;
    my $contents = slurp $file, :enc<utf16>;
    say $contents;  # ሀⶀ䷼ꪪⲤⲎ

Please close ticket if you agree.  If not, please provide another test case  :-)

**Comment by doomvox** [comment]
Yes: closing the file handle before slurping it fixes the test.   

Interesting that that was only needed for utf16 and not the other encodings...

**Comment by doomvox** [comment]
So, closing the issue...

**Comment by lizmat** [comment]
> Interesting that that was only needed for utf16 and not the other encodings...

Writing an `utf-16` file starts with writing a BOM: it was only the BOM that was being returned for those files, and they disappear (fortunately) on decoding.

**Comment by jnthn** [comment]
The first write to a file isn't buffered, while the follow-up ones are; this is partly to provide faster feedback when we actually cannot write to the handle, but also makes the common case of a single write a bit more optimal by skipping the whole buffering thing, which only pays off if there are multiple writes.

**Comment by doomvox** [comment]
I see... that's really interesting.  Myself, I saw what Elizabeth was
getting at the moment she said it, but I've gotten out of the habit of
worrying about buffering issues because with perl5 I always do a
"$|=1" to force autoflushing.

I guess you could argue that in the case of utf16 output, it might
make sense to do lead off with *two* unbuffered writes... but then my
test would've been passing without alerting me of this problem.

**Comment by lizmat** [comment]
Also: I've just re-imagined `IO::Path.spurt`, and that won't do a separate write for the BOM anymore.  Instead it will prefix the BOM to the buffer *before* being written.

**Comment by doomvox** [comment]
Elizabeth Mattijsen <notifications@github.com> wrote:
> Also: I've just re-imagined `IO::Path.spurt`, and that won't do a separate
> write for the BOM anymore.  Instead it will prefix the BOM to the buffer
> *before* being written.

Cool.

**Comment by jnthn** [comment]
> I've just re-imagined IO::Path.spurt, and that won't do a separate write for the BOM anymore. Instead it will prefix the BOM to the buffer before being written.

Hm, doesn't that imply that if we get a 10MB buffer to write, we end up allocating another 10MB + 2 bytes worth of buffer in order to do it that way? In most cases it'd be easier to just disable buffering (so it doesn't waste time on that) and do the two writes.
