### ISSUE TITLE
INSTALL.txt out of date

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#3693]
Joseph Brenner noted on perl6-users that INSTALL.txt is out of date; it says you can use ./perl6 to test once you've completed the "make" step - pretty sure you need to do a 'make install' and then use ./install/bin/perl6 - someone should run through the directions and validate that they work, updating as needed.

**Comment by vrurg** [comment]
It is outdated indeed.

**Comment by vrurg** [comment]
Closed via #3696
