### ISSUE TITLE
Unicode numeric digit strings no longer coercible to Numeric

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#3694]
say $_, ', ', +$_ for |(^0x0FFF).grep( { .chr ~~ /<:Nd>/ and .unival == 1|2|3 }).batch(3)».chr».join;

## Expected Behavior

```
123, 123
١٢٣, 123
۱۲۳, 123
߁߂߃, 123
१२३, 123
১২৩, 123
੧੨੩, 123
૧૨૩, 123
୧୨୩, 123
௧௨௩, 123
౧౨౩, 123
೧೨೩, 123
൧൨൩, 123
෧෨෩, 123
๑๒๓, 123
໑໒໓, 123
༡༢༣, 123
```
## Actual Behavior

```
123, 123
Error encoding ASCII string: could not encode codepoint 1633
  in block <unit> at printf.p6 line 1
```
See https://colabti.org/irclogger/irclogger_log/raku?date=2020-05-15#l219
Bisecting by exit code (old=2020.02 new=b874c68). Old exit code: 0
bisect log: https://gist.github.com/c927fb1991f1f9e6f0f1562d437439b7
(2020-05-12) https://github.com/rakudo/rakudo/commit/a0e58412a04253ce0321a30587eda6eb75db2b30

Rakudo HEAD

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/c2e8b22f7b, tests added with https://github.com/Raku/roast/commit/0172bf5bb5
