### ISSUE TITLE
Windows JVM build failure: StringIndexOutOfBoundsException in gen\jvm\rakudo.nqp

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#3695]
Installing Rakudo on the JVM backend on Windows fails on AzureCI.
This is a link to a failing build:
<https://dev.azure.com/Rakudo/rakudo/_build/results?buildId=10&view=logs&j=937494d5-1234-5892-3cc2-7f43d429b312&t=0ba135ab-a642-5c2d-992e-cd86786415fb&l=116>

This is a snippet of the failure:

```
+++ Preparing installation
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Unhandled exception: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 21
  in <mainline> (gen\jvm\rakudo.nqp:121)
  in <anon> (gen\jvm\rakudo.nqp)
```

**Comment by usev6** [comment]
The StringIndexOutOfBoundsException should go away with https://github.com/rakudo/rakudo/commit/8e5b610aa2.

But ```make install``` still doesn't work, another problem surfaces:
```
Invalid JSON: VMArray representation does not implement push_native
  in throw (gen\jvm\CORE.c.setting:40947)
  in die (gen\jvm\CORE.c.setting:959)
  in die (gen\jvm\CORE.c.setting:947)
  in <anon> (gen\jvm\CORE.c.setting:903)
  in <anon> (gen\jvm\CORE.c.setting:903)
  in <anon> (gen\jvm\CORE.c.setting)
  in push (gen\jvm\CORE.c.setting:32702)
  in push (gen\jvm\CORE.c.setting:2560)
  in <anon> (gen\jvm\CORE.c.setting:701)
  in <anon> (gen\jvm\CORE.c.setting:700)
  in parse-string (gen\jvm\CORE.c.setting:679)
  in <anon> (gen\jvm\CORE.c.setting:868)
  in parse-thing (gen\jvm\CORE.c.setting:867)
  in <anon> (gen\jvm\CORE.c.setting:841)
  in parse-array (gen\jvm\CORE.c.setting:840)
  in <anon> (gen\jvm\CORE.c.setting:870)
  in parse-thing (gen\jvm\CORE.c.setting:867)
  in from-json (gen\jvm\CORE.c.setting:908)
  [...]
```

I don't have easy access to a Windows VM, so I can't promise to look at this.

**Comment by patrickbkr** [comment]
@usev6 I do have access to a full Windows 10. If there is anything I can do to assist you, give me a shout.

**Comment by usev6** [comment]
I've made some progress. The error happens when ```install-core-dist.raku``` is run.
It goes away if I comment out the ```NativeCall``` modules from ```%provides```.

I think the problem can be golfed to this: This is not specific to windows -- it happens on my FreeBSD machine as well:
```
$ ./rakudo-j -e 'say Rakudo::Internals::JSON.from-json: q["C:\\\\Users"]'
Invalid JSON: VMArray representation does not implement push_native
  in block <unit> at -e line 1
```

After some poking I've found https://github.com/rakudo/rakudo/commit/e22aeafb50. The commit mentioned, that
>  the JVM backend doesn't grok native str arrays in the setting.

I've tried to compile the setting with this patch:
```
diff --git a/src/core.c/Rakudo/Internals/JSON.pm6 b/src/core.c/Rakudo/Internals/JSON.pm6
index 383ae190c..746ecba74 100644
--- a/src/core.c/Rakudo/Internals/JSON.pm6
+++ b/src/core.c/Rakudo/Internals/JSON.pm6
@@ -426,8 +426,8 @@ my class Rakudo::Internals::JSON {
             $raw = $startcombiner ~ $raw
         }
         if not $has_treacherous and not $has_hexcodes and $escape_counts {
-            my str @a;
-            my str @b;
+            my @a;
+            my @b;
             if nqp::existskey($escape_counts, "n") and nqp::existskey($escape_counts, "r") {
                 @a.push("\\r\\n"); @b.push("\r\n");
             }
@@ -454,7 +454,7 @@ my class Rakudo::Internals::JSON {
             $raw = $raw.subst(/ \\ (<-[uU]>) || [\\ (<[uU]>) (<[a..f 0..9 A..F]> ** 3)]+ %(<[a..f 0..9 A..F]>) (:m <[a..f 0..9 A..F]>) /,
                 -> $/ {
                     if $0.elems > 1 || $0.Str eq "u" || $0.Str eq "U" {
-                        my str @caps = $/.caps>>.value>>.Str;
+                        my @caps = $/.caps>>.value>>.Str;
                         my $result = $/;
                         my str $endpiece = "";
                         if my $lastchar = nqp::chr(nqp::ord(@caps.tail)) ne @caps.tail {
```

With that patch I get:
```
$ ./rakudo-j -e 'my $string = q["C:\\\\Users"]; say Rakudo::Internals::JSON.from-json($string)'
C:\Users
```

I'm optimistic that this also helps with the current error for installing rakudo on the JVM backend on Windows.

But since this change would probably make things slower on MoarVM, I wouldn't commit it right away ... (Also, it's totally untested apart from compiling and executing the given command.)

**Comment by niner** [comment]
Well, it's easy to make that change only `#?if jvm`

**Comment by usev6** [comment]
@niner yeah, I ended up doing that. If someone else comes up with a nice solution that doesn't require the special case, that could be implemented. At least the installation on Windows should succeed now.
