### ISSUE TITLE
Programs using MAIN and USAGE show nothing at execution with no args

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3703]
## The Problem

Raku programs using the MAIN and USAGE features provide no clue to the user when executed without any arguments.

## Expected Behavior

Given such a program, say **foo**, I would expect something like:

    $ foo
    Usage: foo --help

or

    $ foo
    Execute "foo --help" for more information

## Actual Behavior

As an example of current behavior see the executable **documentable** provided by Raku module **Documentable**.

**Comment by ugexe** [comment]
Its perfectly reasonable for a CLI program to take no arguments (or set default values to all parameters so no parameters even need to be passed). I'm not so sure about adding a feature that breaks consistency e.g. "if your program takes no arguments then USAGE will be printed, otherwise your program will do X" (these add up -- try to build a mental model based on 10s of such rules).

**Comment by tbrowder** [comment]
I respectfully disagree. I don't think there is any justification for a newly installed executable to do anything when executed with no args except advertise itself and exit.

**Comment by Altai-man** [comment]
>I don't think there is any justification for a newly installed executable to do anything when executed with no args except advertise itself and exit

This does not correspond to how CLI programs behave in general.

I mean, even in a generic gnu/linux environment you have coreutils with tons of commands like ls, ps, cat. When they don't have required arguments they don't print anything.

If user wants to see help, it is `--help` flag. Can you provide any counter-examples well known and seen in the wild?

**Comment by tbrowder** [comment]
I was going to say something about the *nix utils because, as you say, many do not respond without an arg, or take some default action. I think you'll find they all have a man page; whereas I don't know if anyone has signed on to any standard for something similar for Raku.

**Comment by ugexe** [comment]
Programs like top, prove, screen, make, raku, perl, etc having man pages are not the reason they don't print usage without arguments though.

**Comment by AlexDaniel** [comment]
> "if your program takes no arguments then USAGE will be printed, otherwise your program will do X" (these add up -- try to build a mental model based on 10s of such rules)

Yeah, but… actually, that summarizes Raku very well. I wish more people understood that it's not the way to do things.

**Comment by tbrowder** [comment]
I'm not arguing that having a man page is reason for not requiring arguments. In fact, my only reason for wanting a modicum of help is because we have not mandated any standard way for a user to find help for Raku modules. Building in any response is better than nothing in my opinion.

You probably weren't around when interactive terminals were first introduced, and, fortunately, we're now in a more helpful environment than the old wild west code-slinging days.

**Comment by vendethiel** [comment]
I don't understand the issue. Given this code:

```perl6
sub MAIN($) {}
```

then invoking it without arguments does give the USAGE message:

```perl6
$ raku temp.p6
Usage:
  temp.p6 <Any>
```

**Comment by niner** [comment]
Since the original report didn't include the actual code that triggers the criticized behavior, I had a look at `Documentable::CLI` and tried to reproduce it. It's this MAIN candidate:
```
    multi MAIN (
        Bool :V(:$version)
    ) {
        say "Documentable version: {$?DISTRIBUTION.meta<version> or '(not found)'}"
        if defined $version;
    }
```

Turning the Bool into a Bool:D makes it print a USAGE message, but apparently that was not desired by the author of the code (as it explicitly handles the case of an undefined $version).

**Comment by tbrowder** [comment]
Okay, I haven't looked at the example prog in some time. I just assumed (my bad), given my knowledge of the author's extensive use of MAIN and USAGE that the no-response was the default. I will close this issue for now.

Thanks for your patience.
