### ISSUE TITLE
nmake detection failing

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#3705]
I'm refactoring our AzureCI setup because of #3700. I have set up the new setup in my personal rakudo clone.
On Windows nmake detection is failing. It might be a flapper.

* [Link 1](https://dev.azure.com/patrickboeker/Precomp-Builds/_build/results?buildId=45&view=logs&j=2db7a664-d2d0-5ac0-d075-a564c179f8bb&t=f54c5258-4df7-5ae4-2299-ec9c7caec43c&l=159)
* [Link 2](https://dev.azure.com/patrickboeker/Precomp-Builds/_build/results?buildId=45&view=logs&j=937494d5-1234-5892-3cc2-7f43d429b312&t=f5ed2be0-7639-5111-7f2b-fa2a015cce46&l=153)

**Comment by vrurg** [comment]
How did you miss Raku/nqp-configure#19? I think this can be closed and we can proceed over there.

**Comment by Altai-man** [comment]
Oh, so this was the issue I was recalling this morning, but couldn't remember to check *-configure repos.
Yes, this can be closed in place of the ticket specified. @vrurg++

I wonder if there can be anything new found in new logs, though.
