### ISSUE TITLE
DateTime string parsed incorrectly

### ISSUE THREAD

**Issue by vladimir-nechaev** [rakudo/rakudo#3717]
## The Problem

String '2020-05-24T10:10:00.034Z' is parsed by DateTime.new to value '2020-05-24T10:10:34000.0Z'

Note that amount of seconds has changed from 00.034 to 34000.0!

## Expected Behavior

the value must correspond to the input string

## Actual Behavior

see above

## Steps to Reproduce

my $s1 = '2020-05-24T10:10:00.034Z';
my $dt = DateTime.new: $s1;
my $s2 = $dt.Str;
say "s1: $s1";
say "s2: $s2";
fail "Incorrect conversion of DateTime to Str" unless $s1 eq $s2;

## Environment
* Operating system: Linux hostname 5.6.13-300.fc32.x86_64 #1 SMP Thu May 14 22:51:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): This is Rakudo version 2020.02 built on MoarVM version 2020.02
implementing Raku 6.d.

**Comment by lizmat** [comment]
Note that using `Str` is **not** a way to get roundtripping of a value.  The only way to do that is to use the `.raku` method and then `.EVAL` the result of that.  And then do an `eqv` on the results:

    my $s1 = '2020-05-24T10:10:00.034Z';
    my $d1 = DateTime.new: $s1;
    my $s2 = $d1.raku;
    my $d2 = $s2.EVAL;
    fail "Incorrect conversion of DateTime to Str" unless $d1 eqv $d2;

does not fail.

Question: what does:

    say DateTime.new("2020-05-24T10:10:00.034Z").second

say for you?  Does it say `0.034` ?  Then the parsing of the string is ok.

**Comment by vladimir-nechaev** [comment]
Yes, it says 0.034 - the parsing is really correct.
However DateTime.new("2020-05-24T10:10:00.034Z").raku.EVAL still gives string
"2020-05-24T10:10:34000.0Z"

**Comment by lizmat** [comment]
$ raku -e 'say DateTime.new("2020-05-24T10:10:00.034Z").raku.EVAL'
    2020-05-24T10:10:00.034000Z

    $ raku -v
    This is Rakudo version 2020.05.1-201-g1c94538e6 built on MoarVM version 2020.05
    implementing Raku 6.d.

**Comment by vladimir-nechaev** [comment]
Closed as non-reproducible with newer version of Rakudo
