### ISSUE TITLE
require: runtime loading, but with compile-time symbol loading

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3718]
## The Problem

`require` allows you to load code at runtime, however the symbols that you want to export from it need to be declared at compile time.

This is `foo.p6`

    our $bar is export = 7;

This works:

    require "foo.p6" <$bar>;
    say $bar;

(it works also if we declare a variable at BEGIN). This does not:

```
my @imported = ['$bar'];

require "foo.p6" @imported;
say $bar;
```

And it fails with:

```
Variable '$bar' is not declared
```

## Expected Behavior

Well, the fact that the variables used are not known at runtime is decidedly hairy, so this is probably spec. But there should maybe be some workaround here, since it limits what can be done with it.

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

Latest version. 2020.05

**Comment by niner** [comment]
There's just no way around that. We need to know at compile time what's in the lexical scope. So if you want to make this dynamic for some reason, you need to do this at compile time, before the names are used. You can do this with a BEGIN block, like you mentioned, or with a constant:

```
my constant @imported = <$bar>;
require "foo.p6" @imported;
say $bar;
```

**Comment by JJ** [comment]
OK, in that case, could the error message be improved? `require` can check the value of the array of imported symbols, and complain if the value is not known.

**Comment by niner** [comment]
I don't think so, because `require` cannot distinguish between an array that's empty because it was mistakenly filled at runtime and one that's empty on purpose (because the dynamic part decided that we don't need symbols after all).
