### ISSUE TITLE
$proc.out.close() sinks the Proc

### ISSUE THREAD

**Issue by softmoth** [rakudo/rakudo#3720]
## The Problem

Closing any of the file handles created by `Proc.run(:in, :out, :err)` causes `$proc.sink` to throw an error, unless the result of `.close()` is saved.

It should sink the IO::Handle, not the Proc.

This shows up in both an explicit `$proc.in.close` or `$proc.out.close` call and also with the `:close` flag to `.words()` and `.lines()`.

### Test case

```raku
for
    comb => (/\w+/),
    split => ('/'),
    words => (),
    lines => (),
    slurp => ()
{
    $++ and print "\n";
    say .key;

    my $close = True;  # Set to False and the bug disappears
    my $proc = run(</bin/false>, :out);
    my $output = $proc.out."{.key}"(|@(.value), :$close);
    my $rc = $proc.exitcode;

    note "RC $rc  OUT '$output'";

    CATCH {
        when X::Proc::Unsuccessful {
            note .message;
            next;
        }
    }
}
```

### Output

```
comb
RC 1  OUT ''

split
RC 1  OUT ''

words
The spawned command '/bin/false' exited unsuccessfully (exit code: 1, signal: 0)

lines
The spawned command '/bin/false' exited unsuccessfully (exit code: 1, signal: 0)

slurp
RC 1  OUT ''

```
## Expected Behavior

It should not throw an error, because the calling code is not sinking the Proc. The calling code should not need to worry about saving the result of `.close()` just to avoid the `Proc.sink()`.

## Environment
* `Linux 5.6.13-300.fc32.x86_64 `
* `This is Rakudo version 2020.05.1-108-gf33ce01c1 built on MoarVM version 2020.05-12-g3605efdbf implementing Raku 6.d.`

**Comment by softmoth** [comment]
Hmmm, calling `.words(:close)` also sinks the Proc, but calling `.slurp(:close)` is fine.

**Comment by softmoth** [comment]
Hmm, calling `$proc.out.close()` on the next line does cause the exception — *in all cases*.

So this leads me to believe that slurp, comb and split don't actually honor `:close`, which could be another bug.

**Comment by softmoth** [comment]
But calling `my $dont-die = $proc.out.close();` avoids the error. So the problem is with `close()` returning the `Proc`, which naturally gets sunk.

**Comment by usev6** [comment]
Since I've looked at the code that is run for ```$proc.out.slurp(:close)``` the other day (for https://github.com/rakudo/rakudo/issues/3706), I'd like to point out the we do assign the Failure for that case, so that is doesn't get sunk: https://github.com/rakudo/rakudo/blob/8b94d8d279/src/core.c/IO/Handle.pm6#L801-L811

My guess would be that this just isn't done (but should be done) for ```.lines(:close)``` and ```.words(:close)```.

**Comment by softmoth** [comment]
This problem shows up with `$proc.in.close`, also. The `my $dont-die = $proc.in.close();` trick works around it.

**Comment by softmoth** [comment]
Thank you, @usev6. I probably am missing something, but I don't think `$proc.*.close` should sink $proc in any circumstances. Not while `Proc.sink` has the feature of throwing, at least. Would it make sense to return a `$proc but sink { 'do nothing' }`? (My syntax is wrong, hopefully my intention is clear enough.)

**Comment by usev6** [comment]
By all means, I'm not an authoritative source in this matters, but I think this is by design. There are even tests in roast that make sure that (for an unsuccessful ```$proc```) ```$proc.in.close``` throws with ```X::Proc::Unsuccessful``` if it gets sunk: https://github.com/Raku/roast/commit/56c5a98b68

**Comment by softmoth** [comment]
OK. I'm certainly no expert either, unfortunately. I think the intention might be to enable shorthand like `run(:out, "foobar").out.slurp()` to throw. It doesn't, currently. I am not coming up with a useful incantation for this feature.

I'll look into the Proc/Proc::Async unification commits and see if I can become *somewhat* more informed about this. At the very least we should update the docs for Proc to document the `.close()` behavior, but I need to understand its purpose to do that. At the moment it still feels like the wrong design or a bug that got concretized into roast.

Thank you for looking into this!

**Comment by niner** [comment]
If in doubt it should throw. It's easier to catch a failure if that's intended 
than to remember to check for errors. Failing silently was the major design 
error in Perl's IO functions that we set out to fix.

**Comment by softmoth** [comment]
If I've saved off the `$proc` and check it's `exitcode`, it's be nice for that to keep it from throwing an error. I agree it's best to throw it no checks have been done.

I don't think the current behavior makes sense, though. Calling

**Comment by softmoth** [comment]
Yes. But I think the current behavior doesn't make sense:

```raku
# This should throw, but doesn't
say run(:merge, </bin/ls / /ERR>).out.lines.raku;

my $proc = run(:merge, </bin/ls / /ERR>);
my $exitcode = $proc.exitcode;
say "Exit code: ", $proc.exitcode, "; ", $proc.out.lines.raku;
# This shouldn't throw, but does
$proc.out.close;
```

Perhaps it should throw earlier / more often, plus adding an option like `run(:expect-exit(any(0..2))`. I could be way off base, though....
