### ISSUE TITLE
"make spectest" pulls from github:perl6 instead of github:raku

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3729]

**Comment by JJ** [comment]
I would say this is because that's what's defined as a submodule. I'll have to try and find the way to redefine that.

**Comment by JJ** [comment]
OK, I got it in Makefile-common-rules.in...

**Comment by JJ** [comment]
Really no idea where that is defined or the `@roast_pull_url@` variable is set. Beats me.

**Comment by AlexDaniel** [comment]
https://github.com/Raku/nqp-configure/blob/7c343d49176e627e1aa4ba9dbeaf2f544d287443/lib/NQP/Config.pm#L153-L156 ?

**Comment by JJ** [comment]
Probably. How did you find that?

**Comment by JJ** [comment]
Ah, OK,  different repo...

El sáb., 30 may. 2020 a las 13:35, JJ Merelo (<jjmerelo@gmail.com>)
escribió:

> Probably. How did you find that?
>


-- 
JJ

**Comment by vrurg** [comment]
@JJ Usually it's best to grep on built source tree with all submodules and subprojects fetched. That's what I always do.

**Comment by vrurg** [comment]
@tbrowder thanks for spotting the issue!

**Comment by tbrowder** [comment]
You're welcome--my pleasure.
