### ISSUE TITLE
printf('>%3d<', $n) problems

### ISSUE THREAD

**Issue by vonbrand** [rakudo/rakudo#3732]
## The Problem
Calling `printf('>%3d<', 10)` prints `10<>`
## Expected Behavior
Print `> 10<`

## Steps to Reproduce

* Start raku
* printf('>%3d<', 10)

## Environment
* Operating system: Fedora 32, x86_64
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.05.1-226-g62adc88c6 built on MoarVM version 2020.05-20-gee8acf9c6
implementing Raku 6.d.

**Comment by tbrowder** [comment]
When I used sprintf I got:

   10<

with no leading '>'.

**Comment by tbrowder** [comment]
I'm not seeing the problem. Exactly how are you executing the comman: REPL, raku -e, or in a script?

**Comment by demanuel** [comment]
You can "reproduce" this on the raku repl. 

It seems there's a confusion with the '>' char.  The last '>' is the raku prompt:

```
To exit type 'exit' or '^D'
> printf('>%3d<', 10)
> 10<>

```

**Comment by lizmat** [comment]
Indeed, try:

    $ raku -e 'printf(">%3d<", 10)'
    > 10<

So closing this issue.

**Comment by pmichaud** [comment]
Or add a clarifying newline to see it in the REPL:

  $ rakudo
  To exit type 'exit' or '^D'
  > printf(">%3d<\n", 10)
  > 10<
  > 

Or perhaps pad with zeroes to show that the padding is indeed occurring:

  > printf('>%03d<', 10)
  >010<> 

Pm
