### ISSUE TITLE
1/0 should be a Failure

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#3738]
## The Problem

    > say 1/0;
    Attempt to divide by zero when coercing Rational to Str
      in block <unit> at <unknown file> line 3
    > say (1/0).raku;
    <1/0>
    > say 1/0 > 0;  # oops
    True

Compare with:

    > say 1e0/0;
    Attempt to divide 1 by zero using /
      in block <unit> at <unknown file> line 1
    > say (1e0/0).raku
    Failure.new(exception => X::Numeric::DivideByZero.new(using => "/", details => Any, numerator => 1e0), backtrace => Backtrace.new)
    > say 1e0/0 > 0;
    Attempt to divide 1 by zero using /
      in block <unit> at <unknown file> line 1

## Expected Behavior

`1/0` should be a `Failure`, just like `1e0/0`, so that it will consistently throw an exception when you try to do something with it; just like `1e0/0`.

## Actual Behavior

`1/0` isn't evaluated (into a `Failure`) until it is actually used, e.g. in a computation or when you print it.  In some cases, though (like in a comparison), it doesn't become a `Failure` but results in a wrong answer.

## Steps to Reproduce

See above.

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v` or `raku -v`): 2020.05.1

**Comment by lizmat** [comment]
I think a part from the confusion stems from the fact that `1/0` is a valid `Rat`, whereas `1e0/0` cannot ever be a `Rat`, because `Rat`s are basically a representation of **two integers**, which will be evaluated appropriately when needed.  The result of `1e0/0` needs to be evaluated immediately to create an appropriate `Num`, but it can't, which is why it throws immediately.

Raku has taken the approach that `1/0` is a representation for `Inf`, `-1/0` a representation of `-Inf`, and `0/0` a representation of `NaN`.  You can see this is you're using them in comparisons:

    say 42 <  1/0;  # True, because 42 < inf
    say 42 < -1/0;  # False, because 42 > -Inf
    say 42 <  0/0;  # False, because nothing compares to NaN

Perhaps this is more of a documentation bug?

**Comment by mscha** [comment]
IMHO this is a bad idea, and it leads to hard to find bugs.
Dividing by zero never gives a useful result.  Assigning `Inf` to `1/0` (and `-Inf` to `-1/0`) is arbitrary, it simply has no value.  (Lim x↗0 1/x is -∞, for instance.)  You should always get an exception if you divide by 0 and try to use the result.

Also,

    > say 42 ≤ 0/0;
    True

**Comment by lizmat** [comment]
Ah, intriguing  :-)

**Comment by jnthn** [comment]
I think this ticket has a bit of an X/Y problem. It's true that `1/0 > 0` should not just go ahead and give a nonsense answer. However, that doesn't imply that `Rat` cannot represent such values. Thus, there's a legit problem, but I'm not yet convinced by the suggested solution.

**Comment by lizmat** [comment]
There is code in `src/core.c/Rat.pm6` to explicitly make this `True`:

    say 1/0 == 3/0

Also, `Rat < Int` is defined as `a.numerator  < b * a.denominator`.  So should we add checks for zero-ness of denominators?

**Comment by mscha** [comment]
I still think a `Failure ` _is_ the right way to represent this.  (After all, a division by zero is by definition a failure.)  No need for special cases, you get an exception as soon as you use the result.  No need for special cases anywhere else in the code.

For floating points, division by zero (e.g. `1e0/0`) could have assigned (`Inf`, `-Inf` ot `NaN`) – they are valid floating point numbers – but it generates a `Failure`.  IMHO, that's exactly right, and what rational division by zero should also do.

**Comment by pmichaud** [comment]
Although, it may be interesting to note that the type was named 'Rat', with a strong connotation of "Rational Numbers", and rational numbers aren't allowed to have a zero denominator.

I suspect I could argue either side of "exception when zero is assigned to the denominator" and "exception when a zero-denominator Rat is used" and "as currently implemented with fixes for the obvious incorrect values".

Pm

**Comment by AlexDaniel** [comment]
This was discussed many times, does anybody have a link to any previous discussion?

**Comment by gfldex** [comment]
I believe we have two problems where. Firstly `1/0` is not a Rat but a Rat-literal. I would like to see the compiler tell me that I am setting myself up for a trap. The 2nd case would be something like this.
```
my $a = 0;
my $fail-rat = 1 / $a;

say $fail-rat;
# Attempt to divide by zero when coercing Rational to Str
  in block <unit> at div-by-zero-rat.raku line 6
```
This runtime error should produce an error message near to the creation of the odd Rat. Not 2 lines later as in this example. Or even in a completely different file.

If this stays as it is at least an ENODOC in /type/Rat. I would hate to fill that gap tho. It's a [wat](https://www.destroyallsoftware.com/talks/wat).

**Comment by lizmat** [comment]
Closing issue as the PR is the solution to this issue, but if the PR is not accepted, then there is no solution
