### ISSUE TITLE
Behavior of (raku -) command

### ISSUE THREAD

**Issue by sumanstats** [rakudo/rakudo#3743]
## The Problem

To get a Raku interactive shell, I have to type `raku` in command line but accidentally I typed `raku -` and the command line stays as it is without response even if I give further commands.

## Expected Behavior
I think it should exit or give some informative message.

## Actual Behavior

Stays as it is, seems like expecting more input, but does not response. 
To exit it, I have to type `Ctrl + C`.

## Steps to Reproduce
Once the `raku` binary is in PATH, type `raku -` in the powershell.

## Environment
* Operating system: Windows 10 
* Compiler version (`raku -v`):

```
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.
```

**Comment by JJ** [comment]
I think raku - would read from standard input, but it does not echo. Exit would be done via Ctrl-d. Let me check.

**Comment by lizmat** [comment]
FWIW, Perl and Ruby act the same way.  Only Python (2.7) opens an interactive shell on `python -`, but only if STDIN is connected to a terminal.

**Comment by lizmat** [comment]
FWIW, https://github.com/Raku/nqp/commit/59c6124d08 and https://github.com/rakudo/rakudo/commit/83b2a15cd4 now make `nqp` and `raku` have the same behaviour as `python -`

**Comment by nxadm** [comment]
@lizmat Wouldn't you breaking expectations? As a UNIX person the "-" behaviour feels natural to me (open for input and closing with Ctrl+D). I don't think a typo (what this issue is about) warrant breaking expectations.

**Comment by lizmat** [comment]
Feels to me that expecting that behaviour is a leftover from the fact that `perl` does not have a REPL, so you were *forced* to do it that way.  Also  I think a REPL is not that much different from you entering multiple lines and then getting a result, and ending with `ctrl-d`.  You even get more direct feedback, and can actually edit your lines, and have a history.

Note that this behaviour only applies if STDIN is connected to a TTY.  `raku - <foo` will still just execute the code in `foo`.

The fact that `python -` (2.7) has the same behaviour, tells me that many people, especially with Python experience, expect this behaviour.

So I don't think we're breaking expectations that much.
