### ISSUE TITLE
difference of behavior for List.head and Supply.head

### ISSUE THREAD

**Issue by stoned** [rakudo/rakudo#3746]
## The Problem

Supply.head and List.head seem to have a different take on how to handle a Callable argument.

## Actual Behavior
Compare for example:

```
say (1..10).head(*-5);
say Supply.from-list(1..10).head(*-5).List;
```

## Environment
$ raku -v
This is Rakudo version 2020.05.1-248-ge1cefecc9 built on MoarVM version 2020.05-39-ga8b086155
implementing Raku 6.d.

**Comment by lizmat** [comment]
Thanks for the report!

Fixed with https://github.com/rakudo/rakudo/commit/5c8c7324e6 , tests corrected with https://github.com/Raku/roast/commit/c4e8458bb6
