### ISSUE TITLE
any(0,4) != 0 is False

### ISSUE THREAD

**Issue by mscha** [rakudo/rakudo#3748]
## The Problem

```
> any(0,4) == 0
any(True, False)
> any(0,4) != 0;
False
```

## Expected Behavior

```
> any(0,4) == 0
any(True, False)
> any(0,4) != 0;
any(False, True)
```

## Actual Behavior

See above

## Steps to Reproduce

See above

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v` or `raku -v`): Rakudo version 2020.05.1 built on MoarVM version 2020.05

**Comment by coke** [comment]
One more note:
```
> any(0,4) == 0
any(True, False)
> so any(0,4) == 0
True
```
So I think we're first getting the Boolean, and then negating the boolean, not the junction.

**Comment by pmichaud** [comment]
On Mon, Jun 08, 2020 at 08:28:26AM -0700, Will Coleda wrote:
> So I think we're first getting the Boolean, and then negating 
> the boolean, not the junction.

I recall that this is the specced behavior.  See the documentation for Junctions at https://docs.raku.org/type/Junction :

  Negated operators are special-cased when it comes to autothreading. 
  $a !op $b is rewritten internally as !($a op $b). The outer negation 
  collapses any junctions, so the return value always a plain Bool.

    my $word = 'yes';
    my @negations = <no none never>;
    if $word !eq any @negations {
        say '"yes" is not a negation';
    }

  Note that without this special-casing, an expression like $word ne 
  any @words would always evaluate to True for non-trivial lists on one side.

So, I suspect this ticket is actually "notabug".

Pm

**Comment by AlexDaniel** [comment]
Documentation will not fix this. Not only it is special-cased, it is also fully unreadable. Just ban it if the code doesn't do what it says.

**Comment by pmichaud** [comment]
I'm not claiming that the documentation is a fix; I'm simply saying that it was a deliberate design decision after a fair bit of discussion (i.e., not an arbitrary decision), and using the documentation as evidence of that.

There are tests in roast (autothreading.t) that enforce this behavior; the tests reference another issue ticket that describes more behind the issue.  https://github.com/Raku/old-issue-tracker/issues/1787

**Comment by FCO** [comment]
> On 8 Jun 2020, at 16:54, Patrick R. Michaud <notifications@github.com> wrote:
> 
> 
> On Mon, Jun 08, 2020 at 08:28:26AM -0700, Will Coleda wrote:
> > So I think we're first getting the Boolean, and then negating 
> > the boolean, not the junction.
> 
> I recall that this is the specced behavior. See the documentation for Junctions at https://docs.raku.org/type/Junction :
> 
> Negated operators are special-cased when it comes to autothreading. 
> $a !op $b is rewritten internally as !($a op $b). The outer negation 
> collapses any junctions, so the return value always a plain Bool.
> 
> my $word = 'yes';
> my @negations = <no none never>;
> if $word !eq any @negations {
> say '"yes" is not a negation';
> }

I’m not sure if I really understood it, but for this, instead of changing the behaviour of the operator with any, wouldn’t it be better to just do `$word eq none @negations` or `$word !eq all @negations`?

**Comment by mscha** [comment]
For general interest, I encountered this (nota)bug after watching [this video](https://youtu.be/vTscGwAEQS4) and writing the following raku code:

```
sub diffy(*@n)
{
    say @n;
    my $count = 0;
    while any(@n) != 0 {
        @n = (@n Z @n.rotate(1)).map: -> ($a, $b) { abs($a - $b) };
        $count++;
        say @n;
    }
    say $count;
}
```

`diffy(1,2,3,4)` gave the following output:

```
[1 2 3 4]
[1 1 1 3]
[0 0 2 2]
2
```

“Fixed” it by using `any(@n) > 0`.

```
[1 2 3 4]
[1 1 1 3]
[0 0 2 2]
[0 2 0 2]
[2 2 2 2]
[0 0 0 0]
5
```

This may be a notabug, but it's really unexpected and annoying behavior.  This makes junctions way too unpredictable to work with.

**Comment by MasterDuke17** [comment]
Some prior conversation with @TimToady about this: https://colabti.org/irclogger/irclogger_log/perl6?date=2016-08-21#l51

**Comment by mscha** [comment]
> TimToady | in English, "A is not any of B or C" means "it is not the case that A is any of B or C"

I accept that, applied to this case, “0 is not any of 0 and 4” is false in English.  But I'd argue that “Any of 0 and 4 is not 0” is true.

And if that still sounds too convoluted, “One of 0 and 4 is not 0” is certainly true.

```
> one(0,4) != 0
False
```

**Comment by pmichaud** [comment]
FWIW, in the example given, the code  ```while any(@n) > 0``` could potentially be replaced with ```while none(@n) == 0```, which definitely gets the negation into the correct place and doesn't rely solely on positive numbers.

I see your point on the ```one(0,4) != 0``` example.  My initial reaction is that this might be a case where sets or some other (counting) structure is more i suitable than Junctions; I feel the ```one(...)``` predicate is really more about exclusive-or relationships than counting elements of a set.

Pm

**Comment by mscha** [comment]
`while none(@n) == 0` doesn't do what I need, though.  (It stops when one of the values is equal to zero; I need it to continue until they're all zero.)
`until all(@n) == 0` does the trick.  

I still feel that `while any(@n) != 0` should be equivalent.  But I have a background in maths, not linguistics.  😉

**Comment by lizmat** [comment]
It appears that the behaviour is as designed, even though it may be a WAT in some cases.  Closing this issue as there does not seem to be a solution in sight.  Please re-open if you disagree.
