### ISSUE TITLE
Add 'truncate-to' as alias for DateTime's  'truncated-to' method

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3750]
This seems a more natural syntax:

    my $dt = DateTime.now;
    # ...
    $dt .= truncate-to: 'seconds';

but it currently must be:

    $dt .= truncated-to: 'seconds';

It should be an easy fix if approved.

**Comment by lizmat** [comment]
Hmmm... `truncated-to` describes the return value, `truncate-to` describes the action to perform.  I guess looking at things like `comb` and `split`, we generally favour the action (as we don't have `combed` or `splat`  :-)

**Comment by tbrowder** [comment]
I think that's a great idea! But I need to finish my pod thingy and some other non-Raku stuff before I could handle looking for more such cases. Could we start a candidate list somewhere to accumulate them?

**Comment by lizmat** [comment]
Started a ticket at https://github.com/Raku/problem-solving/issues/204
