### ISSUE TITLE
No such spesh plugin '' for current language

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3755]
## The Problem

Will try to golf it

```
use NativeCall;

our class mat4 is repr('CStruct') is export {
    HAS num32 @.mat[16] is CArray;

    submethod BUILD( :@mat = 0.Num xx 16) {
        for ^16 {
            @!mat[$_] = @mat[$_];
        }
    }

    method gist() {
        "[", (@!mat[$_] for ^16).join(", "), "]";
    }
}

sub kmMat4Fill( mat4 $mat, CArray[num32] $filler )
        returns mat4 is native('kazmath') is export {*}

my mat4 $one-mat .= new;
my CArray[num32] $riller .= new( 2.Num xx 16 );
my $returned-mat = kmMat4Fill( $one-mat, $riller );
say $returned-mat;
```

The problem only shows up when you try to use it for an object that is returned by the native sub. [`kazmath` can be built from here](https://github.com/Kazade/kazmath), and it's in the gist.

## Expected Behavior

Probably a more informative error

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

Raku 2020.05

**Comment by Altai-man** [comment]
This sounds like something to be addressed by new-disp branch.

**Comment by lizmat** [comment]
I doubt this is still an issue, so closing.  Please re-open if this assumption was incorrect.
