### ISSUE TITLE
Strange issue with assignments to Str.split's return value

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3758]
## The Problem
I rebased the branch I'm working on the solution for https://github.com/Raku/problem-solving/issues/111 on to master yesterday. I can't continue with my work at the moment because `tools/update_ops.p6` in MoarVM is failing. I golfed what looks to be the issue down to this:

```perl6
my ($name, $mark, @operands) = 'no_op               :confprog'.split(/\s+/);
say $name, ' ', $mark, ' ', @operands;
```

## Expected Behavior
This should output `no_op :confprog []`.

## Actual Behavior
This outputs `no_op :confprog [g]`.

## Steps to Reproduce

Save the test code as `test.raku` and run it.

## Environment
* Operating system:
OpenBSD bastille.kennel.qt 6.7 GENERIC.MP#261 amd64
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.05.1-323-g4d6fab0ba built on MoarVM version 2020.05-115-g8831476e2
implementing Raku 6.d.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/077300c56c , tests added with https://github.com/Raku/roast/commit/b4ff353c95
