### ISSUE TITLE
rakudo/repl.t fails consistently on Windows

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3761]
See [log](https://dev.azure.com/Rakudo/rakudo/_build/results?buildId=170&view=logs&j=70f6b8a1-f3cf-5727-bd79-d08ddb1caf67&t=f59a17df-92a9-5d7f-18bb-7f81f1c720a8) on Azure for details.

[Here](https://dev.azure.com/Rakudo/rakudo/_build/results?buildId=127&view=results) (commit https://github.com/rakudo/rakudo/commit/cde948aee058ecddf7cbfe69f38754cab19ab642) it still worked, but starting from https://github.com/rakudo/rakudo/pull/3576 the test starts to fail.

Ping @patrickbkr.

**Comment by Altai-man** [comment]
The main issue seems to be this failure preventing other tests from running:
```
Constraint type check failed in binding to parameter '@args'; expected anonymous constraint to be met but got Array ($[])
  in block <unit> at t/02-rakudo/repl.t line 192
# You planned 45 tests, but ran 31
```

From the [file](https://github.com/rakudo/rakudo/blob/master/t/02-rakudo/repl.t#L192):
```
    my $proc = run $*EXECUTABLE, :in, :out, :err;
```
^ this triggers the exception on Windows.

Signature is indeed `*@args where .so` everywhere. There is only a single usage of newly added function, [here](https://github.com/rakudo/rakudo/pull/3576/files?diff=split&w=1#diff-18abaf0c28115c4b6a5488be9338c09eR336). What if there are no @*args? Can someone check correctness of this, please?

**Comment by coke** [comment]
The test fails on my windows also, but the REPL does seem to work.
