### ISSUE TITLE
Clarify state of circle-ci checks

### ISSUE THREAD

**Issue by Altai-man** [rakudo/rakudo#3764]
## The Problem

Not sure about the reason, but CircleCI checks are failing for all commits without clear explanations, which is annoying and hides the real state of things.

## Suggested solution

Since we migrated to azure and announced about it weeks ago, just disable it.

**Comment by JJ** [comment]
I think it includes only a limited amount of checks per month. Anyway, if what it does is not complementary to the rest, it might be best to disable it.

**Comment by ugexe** [comment]
It’s failing because https://github.com/MoarVM/MoarVM

**Comment by Altai-man** [comment]
This needs another ticket for the moarvm fix, superseded by https://github.com/Raku/problem-solving/issues/206
