### ISSUE TITLE
A very strange problem with piping

### ISSUE THREAD

**Issue by svndad** [rakudo/rakudo#3768]
## The Problem
Unexpected behaviour when piping the output. 
% ./a.pl6 | head -n1
c => 3
Unhandled exception: Failed to write bytes to filehandle: Broken pipe

## Expected Behavior
No exception when using | head and  other generic piping in UNIX. A person should not try/catch any one-liner script for the case of piping. It does not make sense. 

## Steps to Reproduce
my %hash =  "a" =>  1, "b" => 2, "c" => 3;
.say  for %hash;

Run it and pipe it to head -n1 

## Environment
* Operating system: OS X 10.15.4

* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.

**Comment by MasterDuke17** [comment]
Can repro on linux with `This is Rakudo version 2020.06-6-gf470b544d built on MoarVM version 2020.06-4-g06d8cdd16`

**Comment by JJ** [comment]
Same here:

raku -e "my %hash = 'a' => 1, 'b' => 2, 'c' => 3;  .say for %hash;" | head
-n1

**Comment by JJ** [comment]
Goes back to at least 2020.02

**Comment by svndad** [comment]
UPDATE: I hoped this was somehow connected to looping cycle. It actually isn't. Any given program  with multiple "say" statements will cause the same issue. 

% perl6 -e 'say "oooh"; say "yeaaah"; say "there is a bug";' | head -n1
oooh
Unhandled exception: Failed to write bytes to filehandle: Broken pipe


A single "say" instuction with multiple lines works as expected. 
% perl6 -e 'say "oooh\nyeaah\neverything works fine"' | head -n1
oooh

Multiple print statements cause the same problem. Printf acts the same way. It seems like any output to STDOUT is exposed to the bug.

**Comment by AlexDaniel** [comment]
This is actually pretty old: https://gist.github.com/1bd4253559f0be01aee4d5723fb80677

> A single "say" instuction with multiple lines works as expected and does not throw an exception

Yeah, otherwise the pipe is closed before it gets to `say`-ing more stuff.

This is not strictly specific to Raku. See this:
```
python3 -c 'for i in range(10000): print("oooh");' | /usr/bin/head -n1
```
```
oooh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by svndad** [comment]
> This is actually pretty old: https://gist.github.com/1bd4253559f0be01aee4d5723fb80677
> 
> This is not strictly specific to Raku. See this:
> 
> ```shell
> python3 -c 'for i in range(10000): print("oooh");' | /usr/bin/head -n1
> ```
> 
> ```
> oooh
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> BrokenPipeError: [Errno 32] Broken pipe
> ```

`#!/usr/bin/env python3

a = {'a':1,'b':2,'c':3}

for x in a :
	print(x)`

 % ./pypy.py | head -n1
a

Does not affect the trivial cases as represented in the issue above.

**Comment by AlexDaniel** [comment]
> In python3 it is a very special case connected to direct execution with -c option

No, it doesn't matter how you run it. Your output is buffered so all your `print`s come at the same time, which is why you don't see an error. I guess rakudo is simply doing less buffering.

**Comment by AlexDaniel** [comment]
To clarify, you can still reproduce it if you put `for i in range(10000): print("oooh");` into your file.

**Comment by lizmat** [comment]
I gather this is not actually a bug in Raku, so closing.  Please re-open if you disagree.
