### ISSUE TITLE
Installation size got bigger by around ≈13MB

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3769]
* See the graph here: https://gist.github.com/d84b13d00e2bd85d10719b06d38bf796 (ignore broken builds that appear as points below 20M)
* Clearly something went wrong recently
* So it seems to be caused by https://github.com/rakudo/rakudo/commit/537f8877034fa4c3697d3a8b093039b18c331b79
* It goes like this:
a9796fe5a437844e796ad9073ba35a9e635e8242 44.558575
98dec90df8b620f3c722e3577ae5e8294eed0baf 44.559146
792a0f0072e4043a78f9adfcf285a3f314cdbf95 44.557213
537f8877034fa4c3697d3a8b093039b18c331b79 57.451045
169f63d90fd97250272fcfedc309cee39ab17f27 57.451118
0a84aa7f609b4f1b2a2d493def37e121872b4a2a 57.448781

**Comment by AlexDaniel** [comment]
Ping @niner

**Comment by AlexDaniel** [comment]
Maybe I need to explain what that number is. You get that number by installing rakudo into some specific directory and then getting the size of that directory. It's how much space rakudo installation takes.

**Comment by niner** [comment]
The commit does exactly what the commit message says. Now that all compiled frames actually make it into the bytecode file, it's no wonder that the bytecode is larger. Why is this an issue?

**Comment by AlexDaniel** [comment]
@niner so are you saying that we were not saving 13MB of stuff that we should've been saving previously? Or, in other words, 23% of stuff was missing?

**Comment by niner** [comment]
> @niner so are you saying that we were not saving 13MB of stuff that we
> should've been saving previously? Or, in other words, 23% of stuff was
> missing?

I don't think missing this frames did cause any problems. I can't say for sure 
because with a language this large and complex, there may have just been 
issues that I have not heard about or that no one connected to those missing 
frames.

They now get added as a side effect of a fix for very real issues. Previously 
frames created by a nested compiler at BEGIN time (e.g. EVAL) were lost. The 
fix actually involved removing special handling in EVAL and effected all 
frames to get added to the bytecode.

**Comment by lizmat** [comment]
I don't think that the increase in installation size in itself is an issue if there are good reasons for it.

I think we need to revisit this after the various behind-the-scenes projects have landed:

- RakuAST
- newdisp
- in-process precomp
- MoarVM hash optimizations

By that time, I think we need another ticket, as we will be closer to understanding what is going on.  So closing now.
