### ISSUE TITLE
Regex lexical var acts like state var

### ISSUE THREAD

**Issue by b2gills** [rakudo/rakudo#3775]
## The Problem

If you use `:my $foo = …;` and somehow re-enter the regex it gets overwritten by the one you call. (Similar to `(state $foo) = …`)

It seems to only be an issue when written as a literal regex. (`/…/`, `m/…/` and `rx/…/` are all affected)

It is not a problem if you use `regex`, `token`, or `rule`. Either anonymous or as part of a grammar.

## Test Code

```raku
'A{B{C{DD}C}B}A' ~~ /
    (\w) # match a letter
    {}
    :my $L = ~$0; # hold onto it for later

     # recurse the regex
    [｢{｣ <&?BLOCK>? ｢}｣]?

    # print the current value of $L (DEBUG statement)
    { say "expected($0), got($L)" }

    # match the letter we started with
    # "$L" # <-- I want to write this
    "$0"
/;
```

As a One Liner:
```raku
'A{B{C{DD}C}B}A' ~~ /(\w){}:my $L= ~$0;[｢{｣<&?BLOCK>?｢}｣]?{say "expected($0), got($L)"}"$0"/
```

Note that it is still an issue if written more like this:

```raku
my $regex; $regex = /… <$regex> …/;
'A{B{C{DD}C}B}A' ~~ $regex;
```

## Expected Results

```
expected(D), got(D)
expected(C), got(C)
expected(B), got(B)
expected(A), got(A)
```

This is what we get with `regex`, `token`, and `rule`. Either anonymous or as part of a grammar.

## Actual Results

```
expected(D), got(D)
expected(C), got(D)
expected(B), got(D)
expected(A), got(D)
```

As you can see the variable is incorrectly shared among all instances.

## Environment
* Operating system: Ubuntu Linux
* Compiler version (`perl6 -v` or `raku -v`): 2020.06-10-g9f546ef6f built on MoarVM version 2020.06-14-g5832b2628

**Comment by jnthn** [comment]
The Raku scoping rules are that only blocks introduce new lexical scopes; there are no exceptions. Thus a `:my` in a quoted regex is declaring a variable in the surrounding lexical scope. You can prove this by using it outside of the quote construct:

```
$ raku -e '"abc" ~~ /:my $x = 42; ./; say $x'
42
```

This behavior is consistent over other kinds of quote constructs too:

```
$ raku -e 'say "answer $(my $x = 42)"; say $x'
answer 42
42
```

A `state` variable's behavior is basically as if it were declared in a surrounding scope, so it's not surprising the behavior looks like that if one believes that a quoted regex is creating a scope of its own. However, it is not, so all we're really looking at is a consistent application of scoping rules, and thus this is per design, not a bug.
