### ISSUE TITLE
Overriding the backtrace method in a subclass of Exception and throwing it fails

### ISSUE THREAD

**Issue by tqdv** [rakudo/rakudo#3776]
## The Problem

The following (golfed) piece of code fails.
```raku
class X is Exception {
	method backtrace { True }
}

X.new.throw;
```

## Expected Behavior

Not sure if it's a bug, or a bad manoeuver on my part. I guess that, at the very least, it's an LTA error message.

## Actual Behavior

Fails with the error message:
```
No exception handler located for catch
   at SETTING::src/core.c/Exception.pm6:423  (…rakudo-2020.01/bin/../share/perl6/runtime/CORE.c.setting.moarvm:print_exception)
 from SETTING::src/core.c/Exception.pm6:480  (…rakudo-2020.01/bin/../share/perl6/runtime/CORE.c.setting.moarvm:<anon>)
 from gen/moar/stage2/NQPHLL.nqp:2084  (…rakudo-2020.01/bin/../share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (…rakudo-2020.01/bin/../share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2003  (…rakudo-2020.01/bin/../share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/perl6.nqp:127  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/perl6.nqp:92  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:<entry>)
```

## Steps to Reproduce

Output with `raku --ll-exception`:
```
Unhandled exception: concatenate requires a concrete string, but got null
   at gen/moar/stage2/NQPCORE.setting:970  (…rakudo-2020.01/bin/../share/nqp/lib/NQPCORE.setting.moarvm:say)
 from gen/moar/stage2/NQPHLL.nqp:2078  (…rakudo-2020.01/bin/../share/nqp/lib/NQPHLL.moarvm:command_eval)    
 from gen/moar/Compiler.nqp:55  (…rakudo-2020.01/bin/../share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2003  (…rakudo-2020.01/bin/../share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/perl6.nqp:127  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/perl6.nqp:92  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (…rakudo-2020.01/bin/../share/perl6/runtime/perl6.moarvm:<entry>)
```

## Environment
* Operating system: OpenSUSE Leap 15.1
* Compiler version: Rakudo version 2020.01 built on MoarVM version 2020.01.1 implementing Perl 6.d

**Comment by jnthn** [comment]
Given you're not returning a `Backtrace` or something compatible with it, you're certainly breaking the Liskov Substitution Principle, which is asking for trouble.

Things blow up in the code that displays the exception, no doubt because the `backtrace` method returns something that doesn't match expectations. Maybe it can be made more robust, though at best you'll be getting an error without location information, because overriding `backtrace` means we can no longer reach it.

**Comment by lizmat** [comment]
Yeah, I would consider this a DIHWIDT (Doctor, It Hurts When I Do This).  Since this is not a thing one would do generally, I would be against putting in checks here.  Even though it's only when an exception is thrown.

**Comment by jnthn** [comment]
> Even though it's only when an exception is thrown.

So far as I can tell from the output, it's only when an exception is *uhandled* and we try to print it, which means we're about to exit anyway.

**Comment by tqdv** [comment]
For context, I was writing a custom error class, and decided to store the backtrace in `$.backtrace`.
