### ISSUE TITLE
IO::Path is missing a method or procedere to remove or replace extensions

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3779]
Removing or replacing a file extension is a common operation in shell scripting (transcoding .avi to .webm, Makefileish stuff, ...). `IO::Path` does not provide a method to do so where many other languages do. Proposals how such a method could look like as follows.

```
my $old-file = "linux.tar.gz";
my $new-file = $old-file.IO.basename(:without-extension(2)) ~ '.zip'; # stolen from Ruby
$new-file eq 'linux.zip'; $new-file ~~ Str;
$new-file = $old-file.IO.replace-extension('.zip', *); # 2nd argument defaults to 1 and * means all
$new-file eq 'linux.zip'; $new-file ~~ IO::Path;
```

I had a discussion with lizmat about this but more eyes see more nits. Other advice is likely available and very welcome.

**Comment by ugexe** [comment]
I wonder if feature requests should go in problem-solving... anyways before we add a new interface lets just use/fix what already exists:

```
➜  ~ raku -e 'say "./xxx/foo.avi".IO.extension: "webm", :joiner("");'
"./xxx/foowebm".IO
```

**Comment by AlexDaniel** [comment]
> I wonder if feature requests should go in problem-solving

Yeah, but I think lizmat is trying to redefine the problem-solving repo or something like that. I'm no longer involved so all the power to those interested in changing things.

Yeah, `.extension` does exactly that, it seems. Just an issue with the documentation maybe?

**Comment by ugexe** [comment]
> Just an issue with the documentation maybe?

fwiw its [already documented](https://docs.raku.org/type/IO::Path#method_extension)

```
# Replacing an extension 
say "foo.tar.gz".IO.extension: '';                # OUTPUT: «"foo.tar".IO␤» 
say "foo.tar.gz".IO.extension: 'ZIP';             # OUTPUT: «"foo.tar.ZIP".IO␤» 
say "foo.tar.gz".IO.extension: 'ZIP', :0parts;    # OUTPUT: «"foo.tar.gz.ZIP".IO␤» 
say "foo.tar.gz".IO.extension: 'ZIP', :2parts;    # OUTPUT: «"foo.ZIP".IO␤» 
say "foo.tar.gz".IO.extension: 'ZIP', :parts(^5); # OUTPUT: «"foo.ZIP".IO␤» 
```

**Comment by gfldex** [comment]
It's a documentation issue. "Returns the extension consisting of $parts parts (defaults to 1), ..." The conditional that this might return a new IO::Path followes 3 paragraphs further down. By renaming the 'ZIP' in the example to 'newext' the example would become a little more speaking. This is not the docs repo, so time to close this.
