### ISSUE TITLE
antipairs sub is not implemented

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3782]
```
23:34 | AlexDaniel | m: my $s = <a b c>.words; say $s.pairs
23:34 | camelia    | rakudo-moar a74550507: OUTPUT: «(0 => a 1 => b 2 => c)␤»
23:34 | AlexDaniel | m: my $s = <a b c>.words; say pairs $s
23:34 | camelia    | rakudo-moar a74550507: OUTPUT: «(0 => a 1 => b 2 => c)␤»
23:34 | AlexDaniel | m: my $s = <a b c>.words; say $s.antipairs
23:34 | camelia    | rakudo-moar a74550507: OUTPUT: «(a => 0 b => 1 c => 2)␤»
23:35 | AlexDaniel | m: my $s = <a b c>.words; say antipairs $s
23:35 | camelia    | rakudo-moar a74550507: OUTPUT: «=== SORRY!===  Error while compiling <tmp>␤Undeclared routine:␤ antipairs used at line 1␤␤»
23:35 | AlexDaniel | :|
23:35 | AlexDaniel | srsly?
```

**Comment by lizmat** [comment]
Having implemented `.antipairs` at the time, I remember asking that question, and I seem to remember that it was not deemed necessary.

BTW, this also goes for other string methods, like `starts-with`, `ends-with`, `substr-eq` and possibly more.

**Comment by lizmat** [comment]
@AlexDaniel this would be easy to implement.  Why don't you give it a try?

**Comment by AlexDaniel** [comment]
@lizmat OK, I didn't know about starts-with and friends. Should I add them too?

**Comment by lizmat** [comment]
If you think antipairs should be added, why should starts-with and friends not be?

**Comment by AlexDaniel** [comment]
Okay. I'm too tired physically today but I'll get back to it later.

**Comment by lizmat** [comment]
Can this issue be closed?  Or should someone else add these subs?

**Comment by AlexDaniel** [comment]
I don't see why it would be closed. Anyone else is free to do it, yes. Or you can just wait, I don't have that many tickets assigned to me but I do have a backlog of things to do.

**Comment by AlexDaniel** [comment]
By the way, @lizmat, have you thought about some kind of automated way of creating subs for existing methods? As I see it, currently both should be created manually, but maybe there's a way to, let's say, just mark a method that a sub should exist too? Maybe even user libs should be able to use the same mechanism so that they can provide APIs that feel like rakudo std lib does.

**Comment by AlexDaniel** [comment]
To illustrate:

```raku
class Foo {
    has $.x;
    submethod bar { $.x × 2 }
}
Foo.new(:42x).bar.say; # 84
say bar Foo.new(:42x); # 84
```

(Yes, it doesn't work because `submethod` does something completely different, but what if?)

**Comment by lizmat** [comment]
class Foo {
        has $.x;
        method bar { $.x × 2 }
    }
    Foo.new(:42x).bar.say; # 84

    constant &bar = Foo.^find_method("bar");
    say bar Foo.new(:42x); # 84

Now, how to do the `constant` bit through the MOP, that is something for someone else to beat me to figure that one out.

**Comment by lizmat** [comment]
Closing as consensus appears not needed
