### ISSUE TITLE
Build after an NQP bump, is broken

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#3798]
## The Problem

Cannot build rakudo after a bump in NQP

## Expected Behavior

Should be able to build rakudo *ALWAYS*

## Actual Behavior

    $ perl Configure.pl --gen-moar --make-install; date
    ===ATTENTION===
      No --prefix supplied, building and installing to /Users/liz/Github/rakudo.moar/install
    Found /Users/liz/Github/rakudo.moar/install/bin/nqp-m (backend moar)
    ===WARNING===
      /Users/liz/Github/rakudo.moar/install/bin/nqp-m version 2020.06-16-g6bdf69921 is outdated, 2020.06-19-g3e928af0b expected.
    remote: Enumerating objects: 8, done.
    remote: Counting objects: 100% (8/8), done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 8 (delta 4), reused 5 (delta 4), pack-reused 0
    Unpacking objects: 100% (8/8), done.
    From https://github.com/Raku/nqp
       1cd9594ec..3e928af0b  master     -> origin/master
    Fetching submodule 3rdparty/nqp-configure
    Fetching submodule 3rdparty/nqp-configure
    Previous HEAD position was 6bdf69921 [MoarVM Bump] Brings 20 commits
    HEAD is now at 3e928af0b Merge pull request #646 from patrickbkr/nqp_home_env_precedence
    Building NQP ...
    /usr/local/bin/perl Configure.pl --prefix=/Users/liz/Github/rakudo.moar/install --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --no-force-rebuild --backends=moar --gen-moar
    Found /Users/liz/Github/rakudo.moar/install/bin/moar version 2020.06-34-gd564695f6, which is new enough.
    Cleaning up ...
    +++ Preparing MOAR build directories
    ++++++ Building MOAR backend
    +++ Generating	gen/moar/stage1/nqpmo.nqp
    +++ Compiling	gen/moar/stage1/nqpmo.moarvm
    +++ Compiling	gen/moar/stage1/ModuleLoader.moarvm
    +++ Generating	gen/moar/stage1/NQPCORE.setting
    +++ Compiling	gen/moar/stage1/NQPCORE.setting.moarvm
    +++ Generating	gen/moar/stage1/QASTNode.nqp
    +++ Compiling	gen/moar/stage1/QASTNode.moarvm
    +++ Generating	gen/moar/stage1/QRegex.nqp
    +++ Compiling	gen/moar/stage1/QRegex.moarvm
    +++ Generating	gen/moar/stage1/NQPHLL.nqp
    +++ Generating	gen/moar/stage1/MASTNodes.nqp
    +++ Compiling	gen/moar/stage1/MASTOps.moarvm
    +++ Compiling	gen/moar/stage1/MASTNodes.moarvm
    +++ Compiling	gen/moar/stage1/NQPHLL.moarvm
    +++ Generating	gen/moar/stage1/QAST.nqp
    +++ Compiling	gen/moar/stage1/QAST.moarvm
    +++ Generating	gen/moar/stage1/NQPP6QRegex.nqp
    +++ Compiling	gen/moar/stage1/NQPP6QRegex.moarvm
    +++ Creating	stage 1 NQP
    +++ Generating	gen/moar/stage2/nqpmo.nqp
    +++ Compiling	gen/moar/stage2/nqpmo.moarvm
    +++ Compiling	gen/moar/stage2/ModuleLoader.moarvm
    +++ Generating	gen/moar/stage2/NQPCORE.setting
    +++ Compiling	gen/moar/stage2/NQPCORE.setting.moarvm
    +++ Generating	gen/moar/stage2/QASTNode.nqp
    +++ Compiling	gen/moar/stage2/QASTNode.moarvm
    +++ Generating	gen/moar/stage2/QRegex.nqp
    +++ Compiling	gen/moar/stage2/QRegex.moarvm
    +++ Generating	gen/moar/stage2/NQPHLL.nqp
    +++ Generating	gen/moar/stage2/MASTNodes.nqp
    +++ Compiling	gen/moar/stage2/MASTOps.moarvm
    +++ Compiling	gen/moar/stage2/MASTNodes.moarvm
    +++ Compiling	gen/moar/stage2/NQPHLL.moarvm
    +++ Generating	gen/moar/stage2/QAST.nqp
    +++ Compiling	gen/moar/stage2/QAST.moarvm
    +++ Generating	gen/moar/stage2/NQPP6QRegex.nqp
    +++ Compiling	gen/moar/stage2/NQPP6QRegex.moarvm
    +++ Creating	stage 2 NQP
    +++ Installing MOAR stage 2 files locally
    +++ Setting up	nqp-m
    +++ Compiling	NQPP5QRegex.moarvm
    +++ Compiling	inst-nqp-m
    +++ Compiling	inst-nqp
    +++ Compiling MOAR default runner
    +++ Preparing MOAR build directories
    ++++++ Building MOAR backend
    +++ Installing MOAR stage 2 files locally
    +++ Compiling	NQPP5QRegex.moarvm
    +++ Creating MOAR installation directories
    +++ Installing into /Users/liz/Github/rakudo.moar/install
    +++ Installing MOAR specifics
    +++ Compiling MOAR default runner
    +++ Installing default runner

    NQP has been built and installed.
    Using /Users/liz/Github/rakudo.moar/install/bin/nqp-m (version 2020.06-19-g3e928af0b / MoarVM 2020.06-34-gd564695f6).
    Cleaning up ...
    +++ Checking for moar NQP version
    +++ Expanding	gen/moar/main-version.nqp
    +++ Generating	gen/moar/rakudo.nqp
    +++ Generating	gen/moar/Grammar.nqp
    +++ Generating	gen/moar/World.nqp
    +++ Generating	gen/moar/ModuleLoader.nqp
    +++ Compiling	blib/Perl6/ModuleLoader.moarvm
    +++ Generating	gen/moar/Ops.nqp
    +++ Compiling	dynext/libperl6_ops_moar.dylib
    +++ Compiling	blib/Perl6/Ops.moarvm
    +++ Generating	gen/moar/Pod.nqp
    +++ Compiling	blib/Perl6/Pod.moarvm
    +++ Compiling	blib/Perl6/World.moarvm
    +++ Generating	gen/moar/Actions.nqp
    +++ Compiling	blib/Perl6/Actions.moarvm
    +++ Compiling	blib/Perl6/Grammar.moarvm
    +++ Generating	gen/moar/Compiler.nqp
    +++ Generating	gen/moar/Optimizer.nqp
    +++ Compiling	blib/Perl6/Optimizer.moarvm
    +++ Compiling	blib/Perl6/Compiler.moarvm
    +++ Compiling	rakudo.moarvm
    +++ Generating	gen/moar/BOOTSTRAP/v6c.nqp
    +++ Generating	gen/moar/Metamodel.nqp
    +++ Compiling	blib/Perl6/Metamodel.moarvm
    +++ Compiling	blib/Perl6/BOOTSTRAP/v6c.moarvm
    +++ Compiling	blib/CORE.c.setting.moarvm
    The following step can take a long time, please be patient.
    Stage start      :   0.000
    Missing or wrong version of dependency 'gen/moar/stage2/QAST.nqp' (from 'gen/moar/BOOTSTRAP/v6c.nqp')
       at <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:<dependencies+deserialize>)
     from gen/moar/ModuleLoader.nqp:93  (/Users/liz/Github/rakudo.moar/blib/Perl6/ModuleLoader.moarvm:)
     from gen/moar/ModuleLoader.nqp:76  (/Users/liz/Github/rakudo.moar/blib/Perl6/ModuleLoader.moarvm:load_module)
     from gen/moar/World.nqp:1458  (/Users/liz/Github/rakudo.moar/blib/Perl6/World.moarvm:load_module_early)
     from gen/moar/World.nqp:788  (/Users/liz/Github/rakudo.moar/blib/Perl6/World.moarvm:comp_unit_stage1)
     from gen/moar/Grammar.nqp:840  (/Users/liz/Github/rakudo.moar/blib/Perl6/Grammar.moarvm:comp_unit)
     from gen/moar/Grammar.nqp:555  (/Users/liz/Github/rakudo.moar/blib/Perl6/Grammar.moarvm:TOP)
     from gen/moar/stage2/QRegex.nqp:2258  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2300  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2216  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:2251  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:2247  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:2243  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from gen/moar/stage2/NQPHLL.nqp:1918  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:2153  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:2113  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from gen/moar/Compiler.nqp:56  (/Users/liz/Github/rakudo.moar/blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:2038  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/rakudo.nqp:115  (rakudo.moarvm:MAIN)
     from gen/moar/rakudo.nqp:1  (rakudo.moarvm:<mainline>)
     from <unknown>:1  (rakudo.moarvm:<main>)
     from <unknown>:1  (rakudo.moarvm:<entry>)
    make: *** [blib/CORE.c.setting.moarvm] Error 1
    Command failed (status 512): make
     at /Users/liz/Github/rakudo.moar/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): make\x{a}") called at /Users/liz/Github/rakudo.moar/3rdparty/nqp-configure/lib/NQP/Config.pm line 1483
        NQP::Config::system_or_die("make") called at Configure.pl line 121
    Fri Jul 17 21:58:34 CEST 2020

**Comment by Altai-man** [comment]
Can confirm three bumps we had (https://github.com/rakudo/rakudo/commit/8543f855b322c9571800b26648ade0c660a0e430 and https://github.com/rakudo/rakudo/commit/c38b5a366d09e9ae5f006faac3e1fdfd06d57c56 and https://github.com/rakudo/rakudo/commit/1b3780f72569f3a8a74ee4beb69c0a9ca2f2f333) since the issue was somehow introduced this issue was persistent.

**Comment by patrickbkr** [comment]
I noticed something in the error message:

> Missing or wrong version of dependency 'gen/moar/stage2/QAST.nqp' (from 'gen/moar/BOOTSTRAP/v6c.nqp')
   at <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:<dependencies+deserialize>)
 from gen/moar/ModuleLoader.nqp:93  (/Users/liz/Github/rakudo.moar/blib/Perl6/ModuleLoader.moarvm:)

The file that reports the wrong version of dependecy is `/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm`. That's a file from the **installation**, not the build.

IIUC it's expected, that that file reports a wrong version of dependency, as it's the old installation that still expects the older NQP. So the next question is: Why is the Rakudo build using the v6c.moarvm from the installation and not the build directory?

**Comment by patrickbkr** [comment]
I added some debug prints to the rakudo-home dir detection logic and the following is printed during CORE.c.setting.moarvm compilation:

```
The following step can take a long time, please be patient.
Stage start      :   0.000
RAKUDO_HOME env: 
PERL6_HOME env: 
static-rakudo-home: /home/patrick/repos/rakudo/../install/share/perl6
dynamic rakudo home: /home/patrick/repos/rakudo/../install/share/perl6
Resulting rakudo home: /home/patrick/repos/rakudo/../install/share/perl6
```

With such a rakudo-home it's understandable that it tries to use the installed files.

**Comment by patrickbkr** [comment]
At that point in the Rakudo build process the `rakudo-m` build runner has not yet been created. `moar` is called directly and passed some `--libpaths` and an `--nqp-lib`. See `M_RUN_RAKUDO` in the Makefile. So this way of running rakudo does *not* use the logic of setting the `RAKUDO_HOME` env variable to `$BUILD_DIR/gen/build_rakudo_home`.
I think that's the core of the problem.

**Comment by patrickbkr** [comment]
Currently the only way to influence the rakudo home dir from the outside is by setting an environment variable. That's inconvenient in the context of a Makefile command.

The only idea I can currently come up with is adding another small wrapper program `rakudo-bootstrap-m` or similar that is used instead of calling `moar` directly (this could be a near copy of [nqp-m-build.c](https://github.com/Raku/nqp/blob/master/tools/templates/unix/nqp-m-build.c) and [nqp-m-build.c.win](https://github.com/Raku/nqp/blob/master/tools/templates/windows/nqp-m-build.c)) and setting the environment variable in there. This feels like overkill. Are there any alternative ideas?

**Comment by patrickbkr** [comment]
I don't understand how this ever worked. I think it was broken in some subtle way before and this error was hidden. Then [e4f020ca](https://github.com/rakudo/rakudo/commit/e4f020caba80cf00a94b8d54b5319a75e09e46ea) somehow fixed that subtle bug and uncovered this current error. I'm not sure about any of this.

**Comment by patrickbkr** [comment]
@vrurg Can you weight in on how we can best proceed here?

Open questions:

- Should we revert or try to fix this? (I'm not sure which commit is at fault. So we would have to find out before we can revert.)
- If we try to fix this, how can we set the Rakudo home in the early stages of the build?
    - Replace `M_RUN_RAKUDO` with a wrapper script written in `.bat` and `.sh`
    - Replace `M_RUN_RAKUDO` with  wrapper script written in C
    - Setting an environment variable in the `M_RUN_RAKUDO` command in the Makefile itself

**Comment by vrurg** [comment]
1. We must fix it.
2. I don't like neither way which is about push in the environment variable. Env must be for use by a user, not by the compilation.

We have another way. It is funny, but it's a day of discoveries. Looking at `M_RUN_RAKUDO` we see `--nqp-lib` command line option which points exactly where need it to point to. But surprisingly, the option is never used! I think this where we should fix it.

This should be the general rule, to my view: because CLI overrides anything else then as many of compilation-specific things are to be put into it as possible.

**Comment by patrickbkr** [comment]
@vrurg So how could this look in practice? Renaming `--nqp-lib` to `--rakudo-home` and make that take precedence over all the other ways to set the Rakudo home?

**Comment by patrickbkr** [comment]
We shouldn't remove `--nqp-lib` without a deprecation period. Better plan:

- Add a new `--rakudo-home` parameter that can be passed to the Rakudo compiler. This option will take precedence over all the other options.
- Pass that parameter in `M_RUN_RAKUDO` and set it to `${BUILD_DIR}/gen/build_rakudo_home`.
- Remove those effectless `--nqp-lib` parameters from the build.
- Add a warning when `--nqp-lib` is passed that the option will be removed.

**Comment by vrurg** [comment]
@patrickbkr Looks like a plan. For now it doesn't matter to me what's the name of the option, the point is there must be some robust way of setting the path for compilation.
