### ISSUE TITLE
"Anchors valid in lookarounds": what does it mean. Plus: circumflex in lookaround does not work.

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3800]
## The Problem

The [specs for 6.d](https://github.com/Raku/doc/issues/2632) include:

> Anchors ^, ^^, $, and $$ are valid in lookarounds

However, it's not clear what that's supposed to mean. `$` works in lookarounds like the literal character

```
say '333$' ~~ m/ \d+ <?[$]>/
```

Double dollar is frowned upon; double circumflex is frowned upon too, and circumflex in lookaround does not seem to work:

```
say '^333' ~~ m/<?[^]> \d+ /
```

## Expected Behavior

Not clear what the intended behavior is. I guess make ^ and $ work in character classes. lookaround assertions are also under-tested in roast, apparently, with a single test (and only with a single character) each.

## Actual Behavior

I'm looking for clarification of actual behavior.

## Steps to Reproduce

The same behavior in all releases, according to commitable.

**Comment by thundergnat** [comment]
I suspect that that is just ambiguously worded and means "Anchors ^, ^^, $, and $$ are valid in lookahead and lookbehind assertions"

    $ say ("aabZ ccd eef" ~~ m:g/ \w+ <before 'Z' | $> /).Str
    $ aab eef

**Comment by ugexe** [comment]
> Double dollar is frowned upon; double circumflex is frowned upon too

What? Please provide the reasoning behind this statement.

**Comment by JJ** [comment]
Brilliant, thanks

**Comment by jnthn** [comment]
> However, it's not clear what that's supposed to mean. $ works in lookarounds like the literal character

When reading something like `<?foo>`, it should be read as "a positive lookahead based on whatever foo would normally mean if the `?` wasn't there". So:

* `<?alpha>`  (lookahead for `<alpha>`) - call the rule `alpha`, check it passes at this point, but don't advance the cursor
* `<?[abc]>` (lookahead for `<[abc]>`) - check the character class matches at this point, but don't advance the cursor
* `<?:L>` (lookahead for `<:L>`) - check we have a letter at this point, but don't advance the cursor

All of these are lookaheads, but it's the lack of advancing the cursor that makes them a lookahead. What follows is just a rule or character class or Unicode property respectively. And so this:

> Double dollar is frowned upon; double circumflex is frowned upon too

Isn't anything to do with lookaheads, but rather about character classes; you'd observe the same with `<[$$]>`.

**Comment by jnthn** [comment]
Closing this, since it wasn't a Rakudo bug, and I think the answers have led to documentation clarifications and so there's probably no further action needed.
