### ISSUE TITLE
Unexpected side effect of calling .raku (and effects of .eqv on lazy sequences)

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3803]
## The Problem

This program:

```
my $a = lazy ^10;
my $b = lazy gather for ^10 { take $_ };

say $a.raku;
say $b.raku;
say $a eqv $b;
```

prints 
```
$((0, 1, 2, 3, 4, 5, 6, 7, 8, 9).lazy.Seq)
$((0, 1, 2, 3, 4, 5, 6, 7, 8, 9).lazy.Seq)
True
```

However, it stops working as soon as you eliminate the .raku call. Depending on whether you use [`.cache`](https://github.com/Raku/roast/blob/fea1d16d993eb851d2935155e0b0d074fa3593bf/S03-operators/eqv.t) or not, it might either print `False` or throw 

## Expected Behavior

Calling .raku shouldn't have side effects, I guess.

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

raku 2020.06

**Comment by lizmat** [comment]
> Calling .raku shouldn't have side effects, I guess.

`.raku` is supposed to generate a round-trippable source representation as much as possible.  In the case of lazy lists, this means reificiation as much as possible.  And that may in turn cause other behaviour.

Closing as unfixable
