### ISSUE TITLE
Pod declarator blocks cannot be attached to all declarators 

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#3804]
The [docs say](https://docs.raku.org/language/pod#index-entry-declarator_blocks_#|) that "since declarator blocks are attached to source code, they can be used to document classes, roles, subroutines and in general any statement or block."  However, this last bit isn't currently correct.  For example, when given this code:

```raku
#| docstring for a variable
my $a = "foo";

sub f() { 42 }
```

the resulting Pod object will have one declarator block, with `content` of "docstring for a variable" and `WHEREFORE` of `&f`.

It is possible that Pod is behaving as intended and the docs are incorrect.  If so, please feel free to close this issue tell me to open an issue on the docs repository.

**Comment by tbrowder** [comment]
After reviewing S26, I don't think this is a bug, but the text is a bit confusing. All the examples in S26 are either declarations of user declared object types or instances of such. I'm sure someone else can describe the nuance between built-in types and user-declared ones.

But I could certainly be very wrong, so I won't close this until someone else comments. I'll also go check roast to review pod tests. 

Thanks for filing the issue. One way or the other, clarification is in order.

**Comment by codesections** [comment]
Thanks for the reply.

> All the examples in S26 are either declarations of user declared object types or instances of such. 

That's certainly true of the examples.  However, the text of S26 says

> Declarator Pod blocks must either precede or immediately follow **a valid Perl 6 declarator, and are then said to be "attached" to it**.… [Every Declarator block] has  `.WHEREFORE` method that returns the code object or metaobject created by the declarator **to which the documentation is attached**.

(Emphasis added)

That certainly reads, at least to me, as though Declarator blocks can be attached to *any* valid declarator – which would of course include `my`, `our`, etc.

I don't mention that to be difficult, and I know that the Synopsis isn't binding; only Roast is.  However, if the current behavior isn't clearly intended, it would be really handy to have Pod documentation available for variables.  For example, I note that Comma currently displays quick-documentation for variables declared with Declarator blocks – and it would be nice if other users could get the same info through `WHY` introspection.

**Comment by JJ** [comment]
Maybe checking out the generated AST will help? It certainly looks like a bug.

**Comment by tbrowder** [comment]
Yep, good idea. Would the OP please post the exact code used to show the problem.

**Comment by codesections** [comment]
Sure.  Given this code:

```raku
#|  docstring for variable $a
my $a = "foo";

sub f() { 42 }

print '$a: '; say $a.WHY;
print '&f: '; say &f.WHY;
```

I get this output:
```txt
$a: No documentation available for type 'Str'.
Perhaps it can be found at https://docs.raku.org/type/Str
&f: docstring for variable $a
```

If I load the Pod object from that file (with `Pod::Load`), I get a Pod object with a single Declarator block associated with `&f` 

All of this is on Rakuko 2020.06.

**Comment by codesections** [comment]
I misunderstood what @tbrowder was asking for; @JJ, thanks for clarifying via IRC.

Here is the generated AST from `raku --target=ast`

```
- QAST::CompUnit  :W<?> :UNIT<?> :CAN_LOWER_TOPIC<?>
  [pre_deserialize]
    - QAST::Stmt 
      - QAST::Stmt 
        - QAST::Op(loadbytecode) 
          - QAST::VM 
            [moar]
              - QAST::SVal(ModuleLoader.moarvm) 
            [jvm]
              - QAST::SVal(ModuleLoader.class) 
            [js]
              - QAST::SVal(ModuleLoader) 
        - QAST::Op(callmethod load_module) 
          - QAST::Op(gethllsym) 
            - QAST::SVal(nqp) 
            - QAST::SVal(ModuleLoader) 
          - QAST::SVal(Perl6::ModuleLoader) 
      - QAST::Op(forceouterctx) 
        - QAST::BVal(3) 
        - QAST::Op(callmethod load_setting) 
          - QAST::Op(getcurhllsym) 
            - QAST::SVal(ModuleLoader) 
          - QAST::SVal(CORE.d) 
  [post_deserialize]
    - QAST::Stmts 
      - QAST::Op(bind) 
        - QAST::Var(attribute $!do) 
          - QAST::WVal(Sub) 
          - QAST::WVal(Code) 
        - QAST::BVal(1) 
    - QAST::Stmts 
      - QAST::Op(bind) 
        - QAST::Var(attribute $!do) 
          - QAST::WVal(Block) 
          - QAST::WVal(Code) 
        - QAST::BVal(2) 
    - QAST::Op(bindcurhllsym) 
      - QAST::SVal(GLOBAL) 
      - QAST::WVal(GLOBAL) 
  [load]
    - QAST::Op(call) 
      - QAST::BVal(3) 
  [children]
    - QAST::Block(:name(<unit-outer>) :cuid(3))  :in_stmt_mod<?> #|  docstring for variable $a\nmy $a = \"foo\";\n\...
    │ - QAST::Var(local __args__ :decl(param)) 
    │ - QAST::Stmts  #|  docstring for variable $a\nmy $a = \"foo\";\n\...
    │ - QAST::Op(call) 
    │   - QAST::Block(:name(<unit>) :cuid(2) :blocktype(declaration_static))  :outer<?> :in_stmt_mod<?> :code_object<?> :IN_DECL<mainline>
    │   │ - QAST::Stmts  #|  docstring for variable $a\nmy $a = \"foo\";\n\...
    │   │   - QAST::Var(lexical $a :decl(contvar)) 
    │   │   - QAST::Var(lexical $¢ :decl(contvar)) 
    │   │   - QAST::Var(lexical $! :decl(contvar)) 
    │   │   - QAST::Var(lexical $/ :decl(contvar)) 
    │   │   - QAST::Var(lexical $_ :decl(contvar)) 
    │   │   - QAST::Var(lexical GLOBALish :decl(static)) 
    │   │   - QAST::Var(lexical EXPORT :decl(static)) 
    │   │   - QAST::Var(lexical $?PACKAGE :decl(static)) 
    │   │   - QAST::Var(lexical ::?PACKAGE :decl(static)) 
    │   │   - QAST::Var(lexical $=finish :decl(static)) 
    │   │   - QAST::Stmt 
    │   │     - QAST::Block(:name(f) :cuid(1) :blocktype(declaration_static)) <wanted> :statement_id<2> :signatured<?> :outer<?> :in_stmt_mod<?> :count<?> :code_object<?> :IN_DECL<sub> { 42 }
    │   │     │ - QAST::Stmts  
    │   │     │   - QAST::Var(lexical $¢ :decl(contvar)) 
    │   │     │   - QAST::Var(lexical $! :decl(contvar)) 
    │   │     │   - QAST::Var(lexical $/ :decl(contvar)) 
    │   │     │   - QAST::Var(lexical $_ :decl(contvar)) 
    │   │     │   - QAST::Var(lexical $*DISPATCHER :decl(var)) 
    │   │     │   - QAST::Op(takedispatcher) 
    │   │     │     - QAST::SVal($*DISPATCHER) 
    │   │     │ - QAST::Op(p6typecheckrv) 
    │   │     │   - QAST::Op(p6decontrv) 
    │   │     │     - QAST::WVal(Sub) 
    │   │     │     - QAST::Stmts <wanted>  42 
    │   │     │       - QAST::Stmt <wanted final> 42 
    │   │     │         - QAST::Want <wanted> :statement_id<3> 42
    │   │     │           - QAST::WVal(Int) 
    │   │     │           - Ii
    │   │     │           - QAST::IVal(42)  42
    │   │     │   - QAST::WVal(Sub) 
    │   │     │   - QAST::WVal(Nil) 
    │   │   - QAST::Var(lexical &f :decl(static)) 
    │   │     [value]
    │   │       - f
    │   │   - QAST::Var(lexical $=pod :decl(static)) 
    │   │     [value]
    │   │       - docstring for variable $a
    │   │   - QAST::Var(lexical !UNIT_MARKER :decl(static)) 
    │   │ - QAST::Stmts 
    │   │   - QAST::Op(bind) 
    │   │     - QAST::Var(local ctxsave :decl(var)) 
    │   │     - QAST::Var(contextual $*CTXSAVE) 
    │   │   - QAST::Op(unless) 
    │   │     - QAST::Op(isnull) 
    │   │       - QAST::Var(local ctxsave) 
    │   │     - QAST::Op(if) 
    │   │       - QAST::Op(can) 
    │   │         - QAST::Var(local ctxsave) 
    │   │         - QAST::SVal(ctxsave) 
    │   │       - QAST::Op(callmethod ctxsave) 
    │   │         - QAST::Var(local ctxsave) 
    │   │ - QAST::Stmts 
    │   │   - QAST::WVal(Array) 
    │   │   - QAST::Stmts <sunk> my $a = \"foo\";\n\nsub f() { 42 }\n\nprint '$a: '...
    │   │     - QAST::Stmt <sunk> my $a = \"foo\"
    │   │       - QAST::Op(p6assign)  :statement_id<1>
    │   │         - QAST::Var(lexical $a) <wanted sinkok> $a
    │   │         - QAST::Want <wanted> foo
    │   │           - QAST::WVal(Str) 
    │   │           - Ss
    │   │           - QAST::SVal(foo) 
    │   │     - QAST::Want <sunk> sub f() { 42 }\n\n
    │   │       - QAST::Op(p6capturelex)  :statement_id<2> :sink_ast<?> :past_block<?> :code_object<?>
    │   │         - QAST::Op(callmethod clone) 
    │   │           - QAST::WVal(Sub :cuid(1))  :past_block<?> :code_object<?>
    │   │       - v
    │   │       - QAST::Op(null) 
    │   │     - QAST::Stmt <sunk> print '$a: '
    │   │       - QAST::Want <sunk>
    │   │         - QAST::Op(call &print) <sunk> :statement_id<5> print '$a: '
    │   │           - QAST::Want <wanted> $a: 
    │   │             - QAST::WVal(Str) 
    │   │             - Ss
    │   │             - QAST::SVal($a: ) 
    │   │         - v
    │   │         - QAST::Op(p6sink) 
    │   │           - QAST::Op(call &print) <sunk> :statement_id<5> print '$a: '
    │   │             - QAST::Want <wanted> $a: 
    │   │               - QAST::WVal(Str) 
    │   │               - Ss
    │   │               - QAST::SVal($a: ) 
    │   │     - QAST::Stmt <sunk> say $a.WHY
    │   │       - QAST::Want <sunk>
    │   │         - QAST::Op(call &say) <sunk> :statement_id<6> say $a.WHY
    │   │           - QAST::Op(hllize) <wanted>
    │   │             - QAST::Op(callmethod WHY)  WHY
    │   │               - QAST::Var(lexical $a) <wanted> $a
    │   │         - v
    │   │         - QAST::Op(p6sink) 
    │   │           - QAST::Op(call &say) <sunk> :statement_id<6> say $a.WHY
    │   │             - QAST::Op(hllize) <wanted>
    │   │               - QAST::Op(callmethod WHY)  WHY
    │   │                 - QAST::Var(lexical $a) <wanted> $a
    │   │     - QAST::Stmt <sunk> print '&f: '
    │   │       - QAST::Want <sunk>
    │   │         - QAST::Op(call &print) <sunk> :statement_id<7> print '&f: '
    │   │           - QAST::Want <wanted> &f: 
    │   │             - QAST::WVal(Str) 
    │   │             - Ss
    │   │             - QAST::SVal(&f: ) 
    │   │         - v
    │   │         - QAST::Op(p6sink) 
    │   │           - QAST::Op(call &print) <sunk> :statement_id<7> print '&f: '
    │   │             - QAST::Want <wanted> &f: 
    │   │               - QAST::WVal(Str) 
    │   │               - Ss
    │   │               - QAST::SVal(&f: ) 
    │   │     - QAST::Stmt <sunk final> say &f.WHY
    │   │       - QAST::Want <sunk>
    │   │         - QAST::Op(call &say) <sunk> :statement_id<8> say &f.WHY
    │   │           - QAST::Op(hllize) <wanted>
    │   │             - QAST::Op(callmethod WHY)  WHY
    │   │               - QAST::Op(ifnull) <wanted>
    │   │                 - QAST::Var(lexical &f)  &f
    │   │                 - QAST::WVal(Nil) 
    │   │         - v
    │   │         - QAST::Op(p6sink) 
    │   │           - QAST::Op(call &say) <sunk> :statement_id<8> say &f.WHY
    │   │             - QAST::Op(hllize) <wanted>
    │   │               - QAST::Op(callmethod WHY)  WHY
    │   │                 - QAST::Op(ifnull) <wanted>
    │   │                   - QAST::Var(lexical &f)  &f
    │   │                   - QAST::WVal(Nil) 
    │   │   - QAST::WVal(Nil) 
```

**Comment by codesections** [comment]
I was looking more closely at the [relevant Roast test](https://github.com/Raku/roast/blob/fea1d16d993eb851d2935155e0b0d074fa3593bf/S26-documentation/why-both.t) and realized that the exact feature described in this issue is tagged as Not Yet Implemented:

```raku
skip 'declaration comments are NYI on constants', 7;
#`(
#| A cool
constant $pi = 3.14159;
#= constant
test-both($pi.VAR, 'A cool', 'constant');
)

skip 'declaration comments are NYI on variables', 7;
#`(
#| Very
our $fancy-var = 17;
#= fancy!
test-both($fancy-var.VAR, 'Very', 'fancy!');
)
```

Given that, should I close this issue as a duplicate of an already-planned feature?  Or should I leave it here to track progress on that implementation?  (I'm not sure of the etiquette around NYI features; if I shouldn't have opened this issue, sorry for the clutter)

**Comment by JJ** [comment]
Just tagged it as NYI. I guess that's OK for the time being.

**Comment by finanalyst** [comment]
There is a bug here too. Look at code below. Any POD added at the top `#|` of a variable is concatenated to POD of next Routine. Code in `declarators.raku`:
```
use v6.*;

#| This is a variable
my $variable;

#| more over
my $under-variable;
#= Some under content

#| Here is a subroutine with a signature
#| with two lines
sub a-nice-sub(Str $fish, :$fingers = 'real potato') {
    my $y = 2;
}

#| This is a proto
proto sub flamingo($one, $two, $three) {
*
}

for $=pod {
    .raku.say;
    .contents.say
};
```
# OUTPUT 
```
raku declarators.p6 
Pod::Block::Declarator.new(WHEREFORE => sub a-nice-sub (Str $fish, :$fingers = "real potato") { #`(Sub|94160247082320) ... }, config => {}, contents => [])
[This is a variable more over Here is a subroutine with a signature with two lines]
Pod::Block::Declarator.new(WHEREFORE => proto sub flamingo ($one, $two, $three) {*}, config => {}, contents => [])
[This is a proto]
```
Note how `This is variable` and `more over` are in the 1st Pod::Block - there are no Pod::Blocks for the variables.

Even if the Pod::Blocks for the variables are thrown away, the contents should not be given to a different Pod::Block

Also: The content for `#=` is not recognised at all.

**Comment by codesections** [comment]
Agreed, this seems like a bug.  The current implementation not only doesn't support people documenting variables with declarators, it actively punishes them for doing so by messing up the output for other declarators. 

>  The content for #= is not recognized at all.

Actually, it looks like it is – it's attached to the *previous* Declarator Block.  It's just not visible in your example because there isn't a previous Declarator Block (that's currently recognized, that is).

While we're collecting related bugs, I also noticed one.  The trailing block in the example below gets "lost" – it's still part of the pod output, but it's detached from the `sub`.  It ends up attached to an `Any` value.

```raku
#| Leading doc
sub foo(
   $thing
) {}
#= Trailing doc
```

The bug here is triggered by splitting `foo`'s parameter list over multiple lines; the trailing doc renders properly if `foo`'s signature is on one line.

**Comment by jnthn** [comment]
So far as "arbitrary statements" goes, I don't think that can ever really work out; declarator blocks attach to a *declarator*, and an arbitrary statement isn't one of those. More specifically, they attach to some kind of meta-object (for example, `Method` if they document a method, `Metamodel::ClassHOW` if the document a class, `Attribute` if they document an attribute, `Parameter` if they document a parameter, and so forth).

So far as variables go, it's...interesting, because all of the things I just mentioned that documentation may be attached to are first class entities in Raku. Meaning you can store them in a variable, and generally, operations on a variable are about the thing in contains. At the very least, if we wanted to have this kind of declarator comment attach to the variable:

```
#| Something about this var
my $var = &some-function;
```

Then you'd have to write `$var.VAR.WHY` to retrieve the documentation of the variable itself, otherwise you're asking about the documentation of `&some-function`. However, this could only work in the case we actually have a container (like a `Scalar` or `Array`) which has an underlying descriptor that we can attach the documentation to, and making that happen would - at least naively - lead to an extra slot in every variable statically existing in the program to store the property. In the case there's a sigilless variable or a binding, there isn't even an introspectable object to attach the declarator block object to. So I'm not really sure we should go down that road.

To me at least, introspectable documentation feels useful on elements you can actually introspect. But lexical variables and statements are implementation details, and not reachable from outside of their enclosing program element. If there's an argument that actually documenting an ordinary variable declaration is useful even if that's only reachable at compile time (e.g. in macros), I guess I can go with that. Though I'm curious to hear use cases.

**Comment by codesections** [comment]
> So far as "arbitrary statements" goes, I don't think that can ever really work out; declarator blocks attach to a _declarator_

That makes perfect sense, and I've edited the issue title to reflect that distinction.  I'd definitely consider this issue closed if Rakudo passes the existing Roast tests for variables and constants.  That arbitrary blocks aren't valid targets for declarators   means that the docs are slightly incorrect, but I'll work on resolving that in the docs repo. 

> To me at least, introspectable documentation feels useful on elements you can actually introspect. … I'm curious to hear use cases.

I 100% agree, but take a broad definition of both "you" and "inspect"!  In particular, I view declarator blocks as very useful for 1) tools, and 2) REPL usage.  

The tool use case includes displaying the documentation of a variable to the user when the user hovers over that variable – even for a variable from the same lexical scope, the documentation could be userful.  In fact, I notice that Comma already provides this feature.  I'm somewhat surprised that the issue of variable declarator blocks didn't come up when adding it, but I guess Comma is re-parsing everything anyway, if I correctly understood your talk on Comma's architecture.  

(Of course, tools could chose to display comments starting with `#|` without those comments creating Pod blocks.  But that seems needlessly confusing: then Raku would have `#|` + declarator syntax that _sometimes_ produces a Pod block, and other times does not, but that may still produce a documentation hover even when it doesn't produce a Pod element.  Having everything that might be a doc comment also be a Pod element seems both cleaner and to better support multiple editors.)

The REPL use case is similar to the tool one, but relies even more directly on introspection.  If a user is working with variables in the REPL, they likely do not have an editor displaying hover documentation for the variable, and `WHY` is the only way they could access that info (short of navigating to it in the source code, at which point it might as well have been documented with `#` instead of `#|`).

Finally, when you say: 

> But lexical variables and statements are implementation details, and not reachable from outside of their enclosing program element.

that's true for a strict definition of "lexical variables", but, of course, not all Raku variables are lexically scoped.  In addition to dynamic variables, there are also package-scoped variables and constants.  As someone who doesn't deal with physics all that often, it would be pretty useful to be able to type `μ0.VAR.WHY` when using `Math::Constant` and get a meaningful result!  Dynamic variables and package scoped variables/constants are not _super_ common, but they're not exactly rare, either.

**Comment by alabamenhu** [comment]
> Then you'd have to write `$var.VAR.WHY` to retrieve the documentation of the variable itself, otherwise you're asking about the documentation of `&some-function`. [snip]
> 
> To me at least, introspectable documentation feels useful on elements you can actually introspect. But lexical variables and statements are implementation details, and not reachable from outside of their enclosing program element. If there's an argument that actually documenting an ordinary variable declaration is useful even if that's only reachable at compile time (e.g. in macros), I guess I can go with that. Though I'm curious to hear use cases.

The issue of `$foo` containing `&bar` isn't too different than we get with attributes or parameters. In Comma, for instance, if I have a parameter defined as `Str $s #= A string!`, hovering over `$s` displays `A string!` — what I imagine most users would expect — rather than the `WHY`(-ish) for `Str`. An IDE could show `.VAR.WHY` or `.WHY` or both.  Realistically, I don't see many people assigning pod declarators to variables very often in a REPL.  But in longer/complex code in an IDE, it would make sense to be able to describe intermediate calculation values in the same way that we can describe input values:

```
sub foo (
  $x, #= the first input
  $y, #= the second input
) {
  $i = invert $x; #= The inverse of $x
  $j = invert $y; #= The inverse of $y

  [ long calculation that uses many instances of $i, $j, $x, $y ]
}
```

Currently, in an IDE like Comma we can get tooltips for $x and $y but not $i or $j.  FWIW, if I actually included the code `say $x.WHY` in that `sub`, I'd be okay with (and even expect) to get the `WHY` for the passed variable, not the `WHY` of the parameter.  By extension, I'd expect the same for $i and $j.  Looking at the math for calendar calculations that I'm about to go through for extending `Date[Time]` to have support for non-Gregorian calendars, every little bit helps :-) 

The point about sigil-less and bound variables is noted, however, both of those are things that already have other limitations on them, so maybe that's not quite as big of an issue in practice. If someone *really* wanted sigil-less variables with a declarator, they could fake it with a sub that returns a defined value or something.

**Comment by vrurg** [comment]
@alabamenhu The point is not in a variable being sigilled or sigilless. The point is that a `WHY` block is a thing of compile-time. But at the compile time one can't know what exactly would end up in a variable. The point about parameters and attributes is that they're always instances of `Parameter` or `Attribute` classes. But what you call _a variable_ is actually a symbol. What exactly the symbol points at is questionable and is not guaranteed. Consider this:

```raku
my $s is my-trait; # my-trait makes $s a non-Scalar
my $v = 1; # So far so good.
...
$v := $some-other-value; # How do we get the original WHY in this case?
```

Any attempt to handle all possible situations would end up with a monstrous code with many special cases, exceptions, heuristics, etc. Only to realize that eventually somebody would find a cause to complain about.

**Comment by alabamenhu** [comment]
> @alabamenhu The point is not in a variable being sigilled or sigilless. The point is that a `WHY` block is a thing of compile-time. But at the compile time one can't know what exactly would end up in a "variable". Parameters and attributes are always instances of `Parameter` or `Attribute` classes. But what you call _a variable_ is actually a symbol. What exactly the symbol points at is questionable and is not guaranteed.
>
> Any attempt to handle all possible situations would end up with a monstrous code with many special cases, exceptions, heuristics, etc. Only to realize that eventually somebody would find a cause to complain about.

Right, I get that.  That's why I mentioned bound variables as a source of potential problems.  Obviously the line has to be drawn somewhere —  I'm just arguing for pushing it a bit farther.  YMMV, but at the moment the following feels inconsistent to me:

```
my $a =         2; #= two
my &a = { 1 + 1 }; #= two

say $a.WHY; # No documentation available for type 'Int'.
say &a.WHY; # two
```

A simple way might be declarator blocks work with `Scalar`. So for instance:

```perl6
my $a = 1; #= I'm the first! 
my $b = 2; #= I'm the second!

say $a.VAR.WHY; # ↳ I'm the first
say $b.VAR.WHY; # ↳ I'm the second

my \c = $b; # c is bound to $b's container
c.VAR.WHY; # ↳ I'm the second

$b := $a; # $b's points to $a's container, so…
say $b.VAR.WHY; # ↳ I'm the first

# but c is still pointing to $b's original container so...
say c.VAR.WHY; # ↳ I'm the second
```

That is a pretty clear cut line to work with that gives a bit more flexibility/expressiveness, while still having a straightforward explanation of why it would produce values that some might find surprising.  The answer to "how do we get the original WHY" would be simply "you don't" (unless it happens to still be referenceable elsewhere, like with `c`)

**Comment by lizmat** [comment]
Closing in light of https://github.com/Raku/problem-solving/issues/438
