### ISSUE TITLE
Flapper in t\04-nativecall\03-simple-returns.t on Windows

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#3813]
I observed the failure only once during building the Rakudo pre-compiled release 2020.07.

Here is the link to the log.
<https://dev.azure.com/rakudo/rakudo/_build/results?buildId=286&view=logs&j=16f9ddfc-d9ca-5995-c750-0312180a9a51&s=245fc62e-fdaf-50e4-0172-bce0e47261f5&t=a36945d5-2667-5933-cf0b-9a70b74351d4&l=1798>

Rerunning the build succeeded.

**Comment by lizmat** [comment]
Closing as unreproducible
