### ISSUE TITLE
Proc::Async.write loses data on systems with high load

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3817]
While running `stress -c 30` the following code will flap. Often the output will start somewhere in the middle. At times no output makes it to the native descriptor in time. This is easily triggered on Travis. So this makes using Proc::Async in production very risky.

```
use v6;

my $in = Proc::Async.new: ‚/usr/bin/sort‘, :w;
LEAVE { $in.close-stdin; }

$in.start;
await $in.ready;

my @a = ('a'..'z').reverse;

for @a {
    $in.write: „$_\n“.encode;
}
```

## Environment
* Operating system: Linux dexhome 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): This is Rakudo version 2020.06-58-g16d24a212 built on MoarVM version 2020.06-14-g5832b2628

**Comment by jnthn** [comment]
Please try it with:

```
for @a {
    await $in.write: „$_\n“.encode;
}
```

**Comment by jnthn** [comment]
(Otherwise any errors from `write` are being discarded.)

**Comment by gfldex** [comment]
With `await $in.write: „$_\n“.encode;` the problem is gone. At least here locally. I will try that in ungolfed code and on Travis later.

**Comment by gfldex** [comment]
This solves my problems in ungolfed code both locally and on Travis. Is this a workaround or an ENODOC?

**Comment by gfldex** [comment]
With `This is Rakudo version 2020.07-41-g3843a1e89 built on MoarVM version 2020.07` running `make spectest` and `stress -c 30` results in the following failed tests.

```
Test Summary Report
-------------------
t/spec/S16-filehandles/filetest.rakudo.moar                     (Wstat: 12800 Tests: 128 Failed: 50)
  Failed tests:  57-64, 69-72, 77-80, 83-84, 87-88, 91-92
                95-96, 101-112, 115-128
  Non-zero exit status: 50
t/spec/S32-io/chdir.t                                           (Wstat: 9472 Tests: 82 Failed: 37)
  Failed tests:  30-33, 35, 38, 40-41, 43, 45, 47, 49, 52-57
                59, 61-65, 67-69, 71-73, 75-81
  Non-zero exit status: 37
t/spec/S32-io/file-tests.t                                      (Wstat: 1280 Tests: 16 Failed: 5)
  Failed tests:  6-10
  Non-zero exit status: 5
t/spec/S32-io/indir.t                                           (Wstat: 9472 Tests: 77 Failed: 37)
  Failed tests:  22-25, 27, 30, 32-33, 35, 37, 39, 41, 44-49
                51, 53-57, 59-61, 63-65, 67-73
  Non-zero exit status: 37
Files=1308, Tests=113043, 792 wallclock secs (26.38 usr  3.22 sys + 2449.30 cusr 119.87 csys = 2598.77 CPU)
Result: FAIL

```

**Comment by gfldex** [comment]
I had to use the rather odd pice of code to make my ungolfed code work.

```
method write($blob) { my $p = Promise.new; $p.keep; a.push: $blob.decode.chomp; $p }
```

So I had to add a Promise just to have something to await on. That removed the last flapper in https://github.com/gfldex/raku-shell-piping/blob/master/lib/Shell/Piping.rakumod
