### ISSUE TITLE
multi method ACCEPTS(Regex:D \SELF: @a) claims to demand Positional but then assumes Iterable.

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3833]
```
class Exitcode does Positional {
    has @.captured handles <elems AT-POS EXISTS-POS>;
}
my $ex = Exitcode.new: :captured(<abc def ghi>);
say [$ex[1], $ex ~~ /a/]; # OUTPUT: [def (Any)]
```

To make this work `.iterator` has to be implemented as well. Both the signature and the docs state that `Positional` is required. Yet, `Iterable` is also required. So this is either a Rakudobug or an ENODOC in https://docs.raku.org/type/Regex#method_ACCEPTS .

## Environment
* Operating system: Linux dexhome 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): This is Rakudo version 2020.07-41-g3843a1e89 built on MoarVM version 2020.07

**Comment by jubilatious1** [comment]
Hi, to help everyone find this issue (and work on it), you should change the spelling of your title to read: "Positional".

**Comment by JJ** [comment]
Well, this definitely works:

```perl6
class Exitcode does Positional does Iterable {
    has @.captured handles <elems AT-POS EXISTS-POS iterator>;
}
my $ex = Exitcode.new: :captured(<abc def ghi>);
say [$ex[1], $ex ~~ /a/]; # OUTPUT: [def ｢a｣]
```

So I'll see where that description in the documentation comes from and raise the corresponding issue.
