### ISSUE TITLE
last-date-in-month not working

### ISSUE THREAD

**Issue by p6steve** [rakudo/rakudo#3841]
## The Problem
Date.new('2015-11-24').last-date-in-month.say not working ;-(

## Expected Behavior
«2015-11-30␤»

## Actual Behavior
No such method 'last-date-in-month' for invocant of type 'Date'

## Steps to Reproduce
raku -e "Date.new('2015-11-24').last-date-in-month.say"

## Environment
*macOS
*This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

**Comment by ugexe** [comment]
That wasn't added until 2020.05

**Comment by p6steve** [comment]
oops - red face
