### ISSUE TITLE
Alpine build "raku -V" says "No exception handler located for catch"

### ISSUE THREAD

**Issue by CurtTilmes** [rakudo/rakudo#3875]
Building `2020.08.1` under alpine, everything builds fine and seems to work fine:
```
~ $ raku -v
This is Rakudo version 2020.08.1 built on MoarVM version 2020.08
implementing Raku 6.d.
~ $ raku -e "say 'hi'"
hi
```

But when I use `-V`, I get unexpected results.  I probably missed copying something over from the build to the runtime, but I'm not quite sure where to look to fix this:

```
~ $ raku -V
No exception handler located for catch
   at SETTING::src/core.c/Exception.pm6:62  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/Exception.pm6:2919  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from gen/moar/BOOTSTRAP/v6c.nqp:3946  (/usr/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from gen/moar/BOOTSTRAP/v6c.nqp:3941  (/usr/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from gen/moar/BOOTSTRAP/v6c.nqp:3938  (/usr/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from SETTING::src/core.c/Compiler.pm6:44  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:verbose-config)
 from <unknown file>:1  (<ephemeral file>:<unit>)
 from <unknown file>:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1945  (/usr/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/Compiler.nqp:98  (/usr/share/perl6/lib/Perl6/Compiler.moarvm:verbose-config)
 from gen/moar/stage2/NQPHLL.nqp:2043  (/usr/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:64  (/usr/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2035  (/usr/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:126  (/usr/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/usr/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/usr/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/usr/share/perl6/runtime/perl6.moarvm:<entry>)
```

**Comment by Altai-man** [comment]
This is rather bad... Is it new?

**Comment by JJ** [comment]
I checked it with 2020.08, and there was no problem.

**Comment by JJ** [comment]
Ah, no, scratch that. It does not work in 2020.08 either. At least from
This is Rakudo version 2020.07-74-gee96b37ad built on MoarVM version
2020.07-16-g03d3e43fa

El mar., 25 ago. 2020 a las 10:41, JJ Merelo (<jjmerelo@gmail.com>)
escribió:

> I checked it with 2020.08, and there was no problem.
>


-- 
JJ

**Comment by Altai-man** [comment]
So we need a test and a fix for it.

**Comment by patrickbkr** [comment]
This is not Alpine specific.

**Comment by lizmat** [comment]
Confirmed on MacOS as well.

**Comment by patrickbkr** [comment]
I think I know what's wrong:

[d2a35ac5ac](https://github.com/Raku/nqp/commit/d2a35ac5ac3a3c8a5d5f80bd0ed8e2330d660559#diff-2ae3feb79d2ecdfb920726f8d0863c78L58) removes `Compiler.config()` which is used in rakudo [/src/core.c/Compiler.pm6](https://github.com/rakudo/rakudo/blob/master/src/core.c/Compiler.pm6#L45)

I hope I can fix this in the coming days.

**Comment by patrickbkr** [comment]
Tests are still missing.
