### ISSUE TITLE
Supply.head($n) is not done when it should be

### ISSUE THREAD

**Issue by jnthn** [rakudo/rakudo#3877]
## The Problem

This behaves as I'd expect:

```
$ ./rakudo-m -e 'my $s = Supplier.new; react { whenever $s.Supply.head { .say }; $s.emit(42); }'
42
```

That is, once it's satisfied because it's received enough values, it sends `done` and unsubscribes from the data source. However, if I make do this:

```
$ ./rakudo-m -e 'my $s = Supplier.new; react { whenever $s.Supply.head(1) { .say }; $s.emit(42); }'
42
```

It hangs.

## Expected Behavior

`.head(1)` on a `Supply` sends the `done` signal immediately after receiving and passing on one element.

## Actual Behavior

Considering this does terminate:

```
$ ./rakudo-m -e 'my $s = Supplier.new; react { whenever $s.Supply.head(1) { .say }; $s.emit(42) xx 2; }'
42
```

It apparently needs an extra value (which it then discards).

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v` or `raku -v`): This is Rakudo version 2020.07-234-g06f8c3c built on MoarVM version 2020.07-19-g9a52033 implementing Raku 6.d.

**Comment by Altai-man** [comment]
It seems there is a test at https://github.com/Raku/roast/blob/master/S17-supply/head.t#L49-L60 added with https://github.com/Raku/roast/commit/86272fb848f8cda2fd9fafd9b754830aceb10615#diff-a1600c96be47183c08da0897380fc3d5
@lizmat++, you are great!
Closing this ticket, please re-open if I misunderstood something.
