### ISSUE TITLE
`Cool.EVAL` does not check for the MONKEY-SEE-NO-EVAL pragma

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#3896]
## The Problem

The following code works:

```raku
say "$a + 1".EVAL  # OUTPUT: «2»;
```
## Expected Behavior
I expected that using the method form of `EVAL` would throw the same error as the subroutine form of `EVAL`
## Actual Behavior
The method form of `EVAL` does *not* throw an error, even when used without the `MONKEY-SEE-NO-EVAL`

### Note
If this behavior not a bug, please let me know so that I can close this issue and open a raku/docs issue.  If this behavior is intended and/or a known bug, we should note it in `Cool.EVAL` docs.

**Comment by ugexe** [comment]
> I expected that using the method form of EVAL would throw the same error as the subroutine form of EVAL

```
raku -e 'my $a = 0; say &EVAL("$a + 1")'
1
```

which is just to say there are probably more cases where the pragma doesn't work than where it does.

**Comment by lizmat** [comment]
AFAIK, this behaviour is intentional.

**Comment by jnthn** [comment]
> AFAIK, this behavior is intentional.

Any references for that? It feels a bit more like an oversight to me. (As an aside: I'm not really a fan of the method form of `EVAL`.)

**Comment by lizmat** [comment]
For better or worse, not allowing `foo.EVAL` will break a lot of tests and ecosystem modules.

So closing
