### ISSUE TITLE
Add additional deprecation warnings

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#3901]
# The Problem 

Many methods that are deprecated in v6d do not show deprecation warnings.  Examples include `Str.parse-names`, `Str.path`, `Any.flatmap`, and `IO::Path.chdir`.  I just submitted a PR to address the first of these (#3900) and would be happy to submit PRs to address the others.  Before doing so, however, I wanted to ask three questions:

* Am I correct that it's correct to add deprecation warnings to all items marked as deprecated in v6d?
* Should I be adding tests that show that the item is deprecated?  I saw `t/02-rakudo/11-deprecated`, but I didn't see any code testing that specific functions were deprecated.
* Is there a master list of deprecated items, or should I just be searching Roast/Rakudo for comments or other indications of deprecated items?

**Comment by lizmat** [comment]
This feels more like a problem solving issue at this point, so closing in favour of one now
