### ISSUE TITLE
rx:s/ / is considered a null regex

### ISSUE THREAD

**Issue by holli-holzer** [rakudo/rakudo#3906]
Observe: 
```
>6e "' ' ~~ rx:s/ /"
===SORRY!=== Error while compiling -e
Null regex not allowed
at -e:1
------> ' ' ~~ rx:s/ <HERE>/
6 -v
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.
```

Since :sigspace is active, / / should not be a "null regex" but a regex consisting of a single chr(32) whitespace.

**Comment by timo** [comment]
here's the comments i put in the "original" issue from the other repo:

the first whitespace in a sigspace regex is ignored, which is why the regex in this case is considered a null regex

here's a quote from the documentation:

> Where whitespace in a regex turns into <.ws> depends on what comes before the whitespace. In the above example, whitespace in the beginning of a regex doesn't turn into <.ws>, but whitespace after characters does. In general, the rule is that if a term might match something, whitespace after it will turn into <.ws>.
>
> In addition, if whitespace comes after a term but before a quantifier (+, *, or ?), <.ws> will be matched after every match of the term. So, foo + becomes [ foo <.ws> ]+. On the other hand, whitespace after a quantifier acts as normal significant whitespace; e.g., "foo+ " becomes foo+ <.ws>.

https://docs.raku.org/language/regexes#index-entry-regex_adverb_:sigspace-regex_adverb_:s-Sigspace

**Comment by raiph** [comment]
The doc's wording ("The `:sigspace` or `:s` adverb makes whitespace significant in a regex.") is unfortunate.

This adverb doesn't mean "spaces are spaces", nor does it mean that *all* spaces are *significant*. And turning it off doesn't mean that *all* spaces are suddenly "insignificant".

It isn't doing something like the inverse of the `/x` option in Perl style regexes. That's entirely unrelated.

Even when `:s` is *off*, spaces *inside* strings inside a pattern are still "significant" in the simple sense they're retained. So `/ 'x x' /` is a pattern matching a three character string with a space in the middle. The space isn't thrown away. But inside a string a space's significance is merely that it's literally a space within a string.

When `:s` is *on*, then *spacing* (any amount of contiguous whitespace) *in certain positions* (but not all) becomes "significant" *in a particular way*, namely being converted to the `<ws>` rule. The doc covers the general scheme. [This SO answer](https://stackoverflow.com/a/48896144/1077672) provides the precise details.

As the doc tries to explain, and timotimo too, these certain positions don't include the *start* of the pattern, just as they don't include inside strings, and don't include some other places within patterns as per the SO.

**Comment by pmichaud** [comment]
Perhaps change the doc wording to something like "The ```:sigspace``` adverb changes the behavior of unquoted whitespace in a regex."

If more is needed, then "Without ```:sigspace```, unquoted whitespace in a regex is generally ignored, to make regexes more readable by programmers.  When ```:sigspace``` is present, unquoted whitespace may be converted into ```<.ws>``` subrule calls depending on where it occurs in the regex."

Just a suggestion.

Pm

**Comment by moritz** [comment]
I've changed the docs, as suggested by @pmichaud 

Rakudo's behavior is correct, so there's no rakudo bug, so I'm closing this issue.
