### ISSUE TITLE
Performance inconsistency with simple exponentiation

### ISSUE THREAD

**Issue by Michael-S** [rakudo/rakudo#3910]
## The Problem
For Num type, and possibly others, $x ** 2 is substantially slower than $x * $x.   A similar but smaller gap seems to exist between $x ** 3 and $x * $x * $x.

## Expected Behavior
Identical performance.

## Actual Behavior
Using the exponentiation operator is slower

## Steps to Reproduce

    # runs in 6+ seconds
    my Num $tot = 0e0;
    for 0..10_000_000 -> $x {
      $tot += ($x ** 2);
    }
    say $tot;

    # runs in < 4 seconds.
    my Num $tot = 0e0;
    for 0..10_000_000 -> $x {
      $tot += ($x * $x);
    }
    say $tot;

## Environment
* Operating system:  Ubuntu 20.04 x86_64
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.08.2-59-ge65466fcd built on MoarVM version 2020.08-91-g590bac47e
implementing Raku 6.d

**Comment by MasterDuke17** [comment]
FWIW, using a native int is much faster. I get ~7.6s for `**`, but it drops to ~2.2s with `-> int $x` and `**`. For `$x * $x` I get ~2.8s and it also drops to ~2.2s with `-> int $x`.

**Comment by lizmat** [comment]
I'd argue to make *all* of these benchmarks with nqp ops only.  That way we can figure out if it is the nqp op / math library that needs fixing, or that there is some massive dispatch overhead at work.

**Comment by lizmat** [comment]
For some more references and probably the reason for this ticket, see https://www.reddit.com/r/rakulang/comments/iodenj/how_can_i_make_my_program_that_calculates_π_faster/

**Comment by MasterDuke17** [comment]
> I'd argue to make _all_ of these benchmarks with nqp ops only. That way we can figure out if it is the nqp op / math library that needs fixing, or that there is some massive dispatch overhead at work.

Well, the native version https://github.com/rakudo/rakudo/blob/master/src/core.c/Int.pm6#L414-L416 is just a single call to `nqp::pow_i`, which does exponentiation by squaring in C (or hand-crafted assembly when JITted). The Int version https://github.com/rakudo/rakudo/blob/master/src/core.c/Int.pm6#L402-L412 has a bunch of extra logic and uses `nqp::pow_I` which ends up in libtommath big integer functions.

**Comment by jnthn** [comment]
Running each with `MVM_SPESH_INLINE_LOG` shows up a significant difference; in the one with multiplication it's:

> Can inline infix:<*> (3584) with bytecode size 54 into  (1)

And in the other its:

> Can NOT inline infix:<**> (3593) with bytecode size 742 into  (1): bytecode is too large to inline

And the definition of `infix:<**>` on `Num`s is:

```
multi sub infix:<**>(Num:D \a, Num:D \b) {
    nqp::p6box_n(nqp::pow_n(nqp::unbox_n(a), nqp::unbox_n(b)))
      or a == 0e0 || b.abs == Inf
        ?? 0e0
        !! Failure.new(X::Numeric::Underflow.new)
}
```

So that's probably part of what is being observed, potentially along with the boolification not being completely free.

**Comment by jnthn** [comment]
Argh, I misread due to the `Num`; it really is on `Int`s. I thought that seemed a bit small to produce 742 bytes of bytecode. The Int candidate is:

```
multi sub infix:<**>(Int:D \a, Int:D \b --> Real:D) {
    my $power := nqp::pow_I(nqp::decont(a), nqp::decont(b >= 0 ?? b !! -b), Num, Int);
    # when a**b is too big nqp::pow_I returns Inf
    nqp::istype($power, Num)
        ?? Failure.new(
            b >= 0 ?? X::Numeric::Overflow.new !! X::Numeric::Underflow.new
        ) !! b >= 0 ?? $power
            !! ($power := 1 / $power) == 0 && a != 0
                ?? Failure.new(X::Numeric::Underflow.new)
                    !! $power;
}
```

**Comment by jnthn** [comment]
> Argh, I misread due to the Num

Though by the time I realized this, I'd already discovered that truth tests of `Num`s were JIT-compiled rather worse than they could be, and it led to [this PR](https://github.com/MoarVM/MoarVM/pull/1346), so my mis-read resulted in *something* getting optimized. :-) This:

```
my $x = 4e2;
say foo($x);
sub foo($y) { my int $i; for ^100_000_000 { $i++ if $x }; $i }
```

Goes from 2.624s to 1.815s with the linked PR, thus running in 70% of the time it used to.

So far as this issue goes, I suspect it'll be a case of looking at if `infix:<**>` can be gotten below the inline limit.

**Comment by lizmat** [comment]
Special casing literal ** N where 0 <= N <= 7 probably makes sense to handle in a RakuAST based optimizer (which would produce bytecode).  Trying to do this in the runtime looks like it's just going to produce overhead making all other cases slower.
