### ISSUE TITLE
Does Distribution::Resource.platform-library-name work on non-Linux OSs?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3911]
## The Problem

This is the line used right now to match "library" files:

https://github.com/rakudo/rakudo/blob/8134470538457c68164eb64f90e8d3e946d235a0/src/core.c/Distribution.pm6#L155

Not too sure about the actual use case, but wouldn't that mean it will not work for OSx and Windows?

## Expected Behavior

Check also Mac and Windows extensions.

**Comment by ugexe** [comment]
So this is an issue wondering if their is an issue? There is no issue.

**Comment by Altai-man** [comment]
Is `platform-library-name` in roast/rakudo tests?
