### ISSUE TITLE
Type capture fails on sigil-less variable

### ISSUE THREAD

**Issue by wimvanderbauwhede** [rakudo/rakudo#3920]
## The Problem

A type variable defined in the signature used to type a sigil-less lexical in the body gives a type error. 

## Expected Behaviour

    > sub (::T \x){ my T \r =x;  }( 42 )
    42

## Actual Behaviour

    > sub (::T \x){ my T \r =x;  }( 42 )
    Type check failed in binding; expected T but got Int (42)
      in sub f2 at <unknown file> line 1
      in block <unit> at <unknown file> line 1

Using  `$r` works as expected, but the \r could in principle bind to a non-scalar T

    > sub (::T \x){ my T $r =x;  }( 42 )
    42

## Comment

The reason for writing this code is that type captures for return values don't work. I would like to write

    > sub (::T \x --> T){ x }( 42 )
    42

But a the moment this gives

    Type check failed for return value; expected T but got Int (42)
      in sub  at <unknown file> line 1
      in block <unit> at <unknown file> line 1

Note that this is exactly the same error as for my "Actual Behaviour" code

## Environment

This is Rakudo version 2020.08.2 built on MoarVM version 2020.08
implementing Raku 6.d.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/36b4414151
