### ISSUE TITLE
$*USER and $*GROUP gives Nil output with different locales

### ISSUE THREAD

**Issue by rypervenche** [rakudo/rakudo#3927]
## The Problem
$*USER and $*GROUP return Nil when using non-English locale (zh_TW.UTF-8 and maybe others). This looks to be caused by the `id` command being used in Process.pm6. The `id` output on my machine, which uses the zh_TW.UTF-8 locale, produces the output:

    使用者id=1000(rypervenche) id群組=1000(rypervenche) 組=1000(rypervenche),10(wheel),18(audio),27(video)

The problem code can be found [here](https://github.com/rakudo/rakudo/blob/master/src/core.c/Process.pm6#L81).
## Expected Behavior
$*USER and $*GROUP should output actual username and group.
## Actual Behavior

$*USER and $*GROUP return Nil.

## Steps to Reproduce

1. Generate zh_TW.UTF-8 locale (varies by distro)
2. `LANG="zh_TW.UTF-8" raku -e 'say $*USER; say $*GROUP'`

## Environment
* Operating system: Gentoo Linux Testing
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.08.2 built on MoarVM version 2020.08
implementing Raku 6.d.

**Comment by Altai-man** [comment]
A data point: can't reproduce it with ru_RU.UTF8 locale:

>uid=1000(koto) gid=1000(koto) группы=1000(koto),10(wheel),63(audio),971(docker) контекст=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
>➜  ~ raku -e 'say $*USER; say $*GROUP'
>koto
>koto

**Comment by niner** [comment]
Well, `id(1p)` clearly documents that our current approach is wrong:
```
       The following formats shall be used when the LC_MESSAGES locale category specifies the POSIX locale. In other locales, the strings uid, gid, euid, egid,
       and groups may be replaced with more appropriate strings corresponding to the locale.

           "uid=%u(%s) gid=%u(%s)\n", <real user ID>, <user-name>,
               <real group ID>, <group-name>
```

I see 3 solutions:
* run `id` with `LC_MESSAGES=POSIX` so the string will always look like what we expect
* run `id -g`, `id -n -g`, `id -u` and `id -n -u` separately, so we only get the information we need and don't have to parse anything
* we avoid costly calls to an external process and instead use `getuid()`, `getgid()`, `getpwuid_r()` and `getgrgid_r()` directly

**Comment by lizmat** [comment]
That last choice would mean interning `NativeCall` into to the core, right?  Or do you mean adding them as nqp:: ops ?

**Comment by niner** [comment]
Both would be possible. As would be using low level native calling 
functionality instead of the module. Adding NQP ops would just be simpler 
though. It's not like a couple more would hurt all that much.

**Comment by rypervenche** [comment]
Would it be worth it to add a workaround in the meantime, such as using LC_MESSAGES=POSIX until a proper solution is made, so that it's not broken until then? I currently have to patch rakudo on my machines to keep my scripts from breaking.

**Comment by lizmat** [comment]
Sure, please make a PR  :-)
