### ISSUE TITLE
Assigning negative integers to a uint64 doesn't appear to underflow

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3936]
## The Problem

Normally, with unsigned native ints, assigning a negative integer to one will underflow. With `uint64`, instead the value appears to remain negative:

```perl6
use v6;

say (my uint8 $ = +^0) == -1;
say (my uint16 $ = +^0) == -1;
say (my uint32 $ = +^0) == -1;
say (my uint64 $ = +^0) == -1;
```

## Expected Behavior

All of these values should underflow to their type's max value, so `False` should get output 4 times.

## Actual Behavior

The `uint64` winds up equal to `-1`:

```
bastille% raku test.raku
False
False
False
True
```

## Steps to Reproduce

Save the sample code as `test.raku` and run it.

## Environment
* Operating system:
OpenBSD bastille.kennel.qt 6.8 GENERIC.MP#64 amd64
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.09-11-gdc2d318ff built on MoarVM version 2020.09-3-gcd8e18280
implementing Raku 6.d.

**Comment by japhb** [comment]
Possibly related, though may just be a similar bug and not from the same source:

```
< japhb> m: my uint32 $i = 4294967295; say $i; class A { has uint32 $.i = 4294967295 }; A.new.i.say;  # HUH?
< camelia> rakudo-moar b0caab5bf: OUTPUT: «4294967295␤-1␤»
```

**Comment by niner** [comment]
Fixed by https://github.com/MoarVM/MoarVM/commit/a851fcf406 (and lots of previous work).

Would you be so kind to add tests for this to roast?

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/d8f0ad76cb
