### ISSUE TITLE
Multi level hash not working with adverbs

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#3937]
Knowing that all these work:

```raku
my %a = :a{:1b};

say %a{"a"};         # {b => 1}
say %a{"a"}:v;       # {b => 1}
say %a{"x"};         # (Any)
say %a{"x"}:v;       # ()
say %a{"a"; "b"};    # (1)
```

and also these:

```raku
my @a = [["a", ], ];
say @a[0;0]:v;       # a
say @a[0;0]:p;       # (0 0) => a
say @a[0;0]:kv;      # ((0 0) a)
say @a[0;0]:k;       # (0 0)
```

Shouldn't also these work?
```raku
say %a{"a"; "b"}:v;  # Unexpected named argument 'v' passed
say %a{"a"; "b"}:k;  # Unexpected named argument 'k' passed
say %a{"a"; "b"}:kv; # Unexpected named argument 'kv' passed
say %a{"a"; "b"}:p;  # Unexpected named argument 'p' passed
```

Is that a bug? (It looks like a bug to me)

**Comment by lizmat** [comment]
I'm afraid it's more a case of NYI  :-(

**Comment by lizmat** [comment]
Some more research:

    %a{"a"; "b"}:exists;

*is* actually supported.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/6986ea1d03 implements all supported combinations, but it requires `use v6.e.PREVIEW`

@FCO would you be willing to write the tests?

**Comment by FCO** [comment]
I'll try this weekend! Thank you very much!

**Comment by lizmat** [comment]
@FCO I'm about done with adding tests now.  If you think I've missed some (maybe simple) cases, please feel free to add tests for them.

**Comment by lizmat** [comment]
@FCO please close the issue if you think there are sufficient tests  :-)

**Comment by FCO** [comment]
That looks perfect. Thank you very much!
