### ISSUE TITLE
Unable to specify command-line arguments and still get interactive REPL

### ISSUE THREAD

**Issue by markjreed** [rakudo/rakudo#3952]
## The Problem
When invoked with command-line arguments, raku does not drop into the REPL, even if told to execute `-` with `--repl-mode=interactive`.

If this behavior is as-designed, then consider this a feature request to add some mechanism for dropping to the REPL despite also supplying command-line arguments, but specifying `--repl-mode=interactive` alongside such arguments seems like a reasonable way to request that behavior.

## Expected Behavior
When invoked with` --repl-mode=interactive -` followed by additional command-line arguments, raku should place those additional arguments into @*ARGS and drop into the REPL prompt.

## Actual Behavior
When invoked with any such additional command-line arguments, raku goes into script/batch mode processing stdin as its script, instead of interactive mode. There appears to be no way from the command-line to get an interactive REPL prompt with `@*ARGS` prepopulated.

## Steps to Reproduce

raku --repl-mode=interactive - hello

## Environment
* Operating system: MacOS Catalina 10.15.7
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.09 built on MoarVM version 2020.09
implementing Raku 6.d.

**Comment by lizmat** [comment]
I've created a PR for nqp to allow for this: https://github.com/Raku/nqp/pull/676  Once merged and bumped to Rakudo, *should* be enough to make this work.
