### ISSUE TITLE
DateTime.now ≠ DateTime.new(now)

### ISSUE THREAD

**Issue by alabamenhu** [rakudo/rakudo#3958]
## The Problem

There is a difference between using `DateTime.now` and `DateTime.new(now)`

## Expected Behavior

They should produce identical values.

## Actual Behavior

`DateTime.now` produces a `DateTime` whose `second` attribute is a `Num`

`DateTime.new(now)` produces a `DateTime` whose `second` attribute is a `Rat` approximation thereof.

## Steps to Reproduce

Reproduction is simple, but demonstrating the difference is best illustrated by:

```
my $a = DateTime.now;
my $b = DateTime.new(now);

say $a.second.WHAT; # Num
say $b.second.WHAT; # Rat
```

## Explanation

The problems can be found in the definitions for [`DateTime.now`](https://github.com/rakudo/rakudo/blob/33bb6504d1b5c016d66d1dcf7d91a739762b07fd/src/core.c/DateTime.pm6#L299) and `DateTime.new(Instant)` along with [`&term:<now>`](https://github.com/rakudo/rakudo/blob/8134470538457c68164eb64f90e8d3e946d235a0/src/core.c/Instant.pm6#L118):

`DateTime.now` simply does:

```
    method now(:$timezone=$*TZ, :&formatter --> DateTime:D) {
        self.new(nqp::time_n(), :$timezone, :&formatter)
    }
```

Where `nqp::time_n()` returns a float value. `DateTime.new(now)` is a more multistep process.  First `&term:<now>`:

```
sub term:<now>(--> Instant:D) {
    nqp::p6bindattrinvres(nqp::create(Instant),Instant,'$!tai',
      Rakudo::Internals.tai-from-posix(nqp::time_n,0).Rat)
}
```

`$!tai` (*temps atomique international*?) has to be coerced to a `Rat` because of the definition of `Instant`, which means we're looking at microsecond-ish precision.

```
my class Instant is Cool does Real {
    has Rat $.tai;
    ...
}
```

`DateTime.new(Instant ...)` has a quite interesting approach to creating:

```
    multi method new(DateTime:
      Instant:D $i, :$timezone = 0, *%_
    --> DateTime:D) {
        my ($p, $leap-second) = $i.to-posix;
        my $dt = self.new( floor($p - $leap-second).Int, |%_ );
        $dt.clone(
          :second($dt.second + $p % 1 + $leap-second), |%_
        ).in-timezone($timezone)
    }
```

Summed up, it makes not one, but TWO `DateTime` objects, the first with integral seconds, and the second one adjusting for fractional seconds and leap seconds. I don't think the fractional has to be handled per se separately, but I'd need to test it.

## Possible Solutions and Extended Solutions

I see two basic solutions and an extended solution:

 - **Make `Instant` use `Num`**  
This actually would speed up `Instant` quite a bit too.  Arbitrary `Rat` conversion is non-trivial, especially for effectively random values.  For a rough idea here, `DateTime.now` (passes the `Num` through) is about [ten times faster](https://tio.run/##K0gtyjH7/z@3UkGlxNCaC0wbgWmHRAiVZM3FlZZfpBBnrFDNpQBSpmCrkJdfbg3kOCQC2RouiSWpIZm5qXpAUQ1NhYoKBUMDINAEqShOrAQpVtCFmA82wAjJgCRUA1LLNYAyeMwAuq32/38A) to create than `DateTime.new(now)` which incurs the coercion penalty.

 - **Make `DateTime.now` use `Rat`**  
As noted above, this would incur a significant speed penalty, and also reduce the accuracy of `Num`.  Plus, now all operations on `DateTime` objects will incur the typical `Rat` math penalty which is worst on very weird and very large denominators.

  - **Compromise**  
Is there a way to compromise?  I think there might be.  Currently, Note that the `Rat` conversion by default limits us to microsecond precision (because **ε = 10⁻⁶**).  If we go the `Rat` route, I'd recommend us in BOTH cases creating a `Rat` with a fixed power-of-ten denominator.  Using a denominator of 10⁹, for instance, we could have nanosecond precision with vastly simpler math (both in creating and in doing operations with DateTime).  Heck, even extending later to 10¹² or 10¹⁵ would be effectively free, although I don't know of any way to accurately generate such values (typical nanosecond libraries's accuracies can be off by a hundred or two nanoseconds for various reasons).  My basic tests show that using a fixed denominator, the `Rat` creation is about [4-5x faster](https://tio.run/##fY/LCsIwEEX3@YqhuFCxpW3ARYLgwi8Ql6KkJUWhTfqkFOm3x2lSV5YGwp3M48xNKev8aEwxwKaNOLEaz0qtnoWTxEnKSddIUFXJCcl0DQ8KHwLTOJxA6Z7jw@ajEI@tAUKCsmteDC6ilbd3IQPsxMqItxHDNAe@s2BZ8Ror@WPJnsEyMJ6BdAWI37qrqV6VjLUIfCruNqWLm66idUGWa11vFezB4sJwd/hFC1aotTJlPN/3PU5GY74) (and about 2-3x slower than pass-throw Num), although the leapsecond calculation may be skewing this a little bit and I'll need to test more.  Math on a fixed-based `Rat` though (to calculate `Duration` for instance) should be much faster.

## Environment

This difference has been present since at least 6.c early releases and is present in TOT Rakudo.

**Comment by AlexDaniel** [comment]
OK, this ticket assumes that the source of truth is inherently a floating-point value of some sort. This is not the case. See https://github.com/MoarVM/MoarVM/blob/3abd2888bc9d5b91d4b2536c63efa4d21c4bece7/src/platform/posix/time.c#L15-L39. The fact that it currently gets converted to Num to get through NQP is an issue of itself. Of course, it is platform-dependent, but in most cases we can have exact nanosecond precision with no involvement of floating point numbers whatsoever.

Just out of curiosity, I wrote this very rough benchmark with gmp to compare creation of rational numbers from floats vs from numerator/denumerator pairs:

```c
#include <gmp.h>
#include <stdio.h>

mpq_t rat;

int main() {
    mpq_init(rat);
    double d = 0;
    size_t total = 0;

    for (size_t i = 0; i < 10000000; i++) {
        mpq_set_d(rat, d);
        //mpq_set_ui(rat, i, 6);

        total += mpq_sgn(rat);

        d += 0.3;
    }

    printf("total: %lu\n", total);

    return 0;
}
```

The line converting from `double` is indeed at least 4x slower (0.026s vs 0.006s for 1 million iterations, and scales consistently), so in some sense you are correct that floating point values should be avoided. That is if the benchmark is not totally bunk, but logically it makes sense.

Anyway. The solution is to implement `nqp::time_rat` that returns a rational number from the VM. That will keep the Rat behavior, and it will make the provided results both faster and more accurate. Win-win-win.

Of course, I'm assuming that MoarVM will eventually switch to gmp and start using its rational numbers to make all this awesomeness possible.

**Comment by alabamenhu** [comment]
> OK, this ticket assumes that the source of truth is inherently a floating-point value of some sort

Not really. It's just what we get from the VMs which is why I assumed NQP also uses the float. Keeping an Rat, provided that's possible, still certainly keep our precision high, although won't likely improve accuracy much at all: the typical overhead of high precision timing causes inaccuracies much greater than the difference between a rat and a float.

If we can get the Rat directly from MoarVM, I'm all for keeping that. My assumption was that NQP used a float because it's more universally available: I know we can't get that from JS. Not sure on JVM: the main Java high precision time package does fractional time as integral nanoseconds, but I'm too lazy to look up how it works internally right now.

I opened the ticket mainly per lizmat's prompting since the two DateTime creations should be identical. But I noticed the huge performance hit of making them both use the Rats as currently implemented, so held off on a PR and figured it deserved a few more eyes and potential solutions especially from the NQP/MVM crowd.

**Comment by AlexDaniel** [comment]
> the typical overhead of high precision timing causes inaccuracies much greater than the difference between a rat and a float

Hmm. Maybe? I'm not so sure yet, any way we can quantify it? For example, let's say I had this timestamp returned from the OS: `1602750659.123456789` (with precision to ns). Converting that to Num:
```raku
say "1602750659.123456789".Num # 1602750659.1234567
```
I don't know if stringification in this particular case is meaningful, but just glancing at it feels like it dropped 89ns just for the conversion alone. If I understand correctly, you're saying that high precision timing itself has overhead larger than that, which is possible, but it's losing some data *on top of that*. Anyway, correct me if I'm wrong, I probably am.

Either way, I think GMP rational number creation is extremely cheap for everyday needs, and beyond everyday needs Raku itself at this point is unlikely to allow doing that kind of measurements. And if eventually it does, I wouldn't be surprised to see people use NativeCall with things like `rdtsc` for that ([example of how cool rdtsc is](https://github.com/rakudo/rakudo/issues/3648)).

Also, please consider the language design aspect. Nums poison expressions they're in, meaning that even basic math with Instants will then result in floating point values (and errors) propagating through the logic of user code. That's something “Rats by default” idea is meant to prevent, and if we're doing that already, let's stick to it.

**Comment by alabamenhu** [comment]
> > the typical overhead of high precision timing causes inaccuracies much greater than the difference between a rat and a float
> 
> Hmm. Maybe? I'm not so sure yet, any way we can quantify it?
> I don't know if stringification in this particular case is meaningful, but just glancing at it feels like it dropped 89ns just for the conversion alone. If I understand correctly, you're saying that high precision timing itself has overhead larger than that, which is possible, but it's losing some data _on top of that_. Anyway, correct me if I'm wrong, I probably am.

What I meant was that if we get a high resolution stamp of `$x`, its margin of error off of the actual time the code calls the timing function will probably be +/-200 ns (this is a rough guestimate gathered from reading various discussions on it, it's fairly system dependent).  That's more than the 89ns loss you point out, which is where I meant it's not the worst thing — that's not to say it's not something we should consider, though.  

Actually, right now with the current `.Num.Rat` coercion, we lose up to 1000ns given the default sensitivity of the `Rat` coercion (obviously that wouldn't be an issue if we can get raw Rat values).

> Either way, I think GMP rational number creation is extremely cheap for everyday needs, and beyond everyday needs Raku itself at this point is unlikely to allow doing that kind of measurements. And if eventually it does, I wouldn't be surprised to see people use NativeCall with things like `rdtsc` for that ([example of how cool rdtsc is](https://github.com/rakudo/rakudo/issues/3648)).
> 
> Also, please consider the language design aspect. Nums poison expressions they're in, meaning that even basic math with Instants will then result in floating point values (and errors) propagating through the logic of user code. That's something “Rats by default” idea is meant to prevent, and if we're doing that already, let's stick to it.

The Rats-by-default is something I can definitely appreciate — that's actually why I was trying to find a compromise between the very fast `Num`-only, and the much slower `Rat`-coercion method.  But especially since getting the raw ones will be much faster on systems that support it.

So I guess we could do a `nqp::time_rat` function that gets raw `Rat`s if available from the VM.  JS's `performance.now()` gives a float rounded to microseconds, so in the case of VM's that don't support giving rational values, I'd suggest having it do the quick `Rat.new($f * 1000000000, 1000000000)` approach to avoid poisoning the rat-math pipeline, but also not destroying performance either by needing to do a full throated coercion (which wouldn't be more accurate anyways).

**Comment by lizmat** [comment]
Note that `nqp::time` returns nano-seconds nowadays:
```
% raku -e 'use nqp; say nqp::time; say nqp::time'  
1728915088606660605
1728915088607021852
```
Note that this is exposed as [`nano`](https://docs.raku.org/routine/nano)
