### ISSUE TITLE
Windows `rakudow.exe` dies when writing to STDOUT/STDERR

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#3961]
This is a follow up ticket for PR#3955. That PR implemented separate executables on Windows that don't spawn a console window by using the `windows` subsystem. A side effect of the `windows` subsystem is that the standard handles `STDOUT`, `STDERR` and `STDIN` are not connected to anything. Writing to them will trigger a program abort.

This is normal Windows behaviour and not necessarily a bug. A respective workaround is already hinted at in the documentation. Still the question remains whether we can do better.

The Python folks have been discussing this very same problem a few years ago and ended up binding those handles to `none` in Python 3. See [issue 706263](https://bugs.python.org/issue706263).

This issue is mainly here to start a discussion of how to best proceed.

@scovit hinted at this MS documentation: <https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/dup-dup2?view=vs-2019#requirements>. It basically recommends using `_dup2()` to redirect the standard handles to some where else.

An obvious possibility is to redirect them to `NUL` (also proposed by @scovit). This should even be possible without touching MoarVM by simply adding a respective logic to [rakudo/src/vm/moar/runner/main.c](https://github.com/rakudo/rakudo/blob/master/src/vm/moar/runner/main.c#L167). The drawback is that all output (including errors, even low level VM errors) are silently ignored. On the other hand one could still redirect the handles to a file using nativecall to retrieve the output.

**Comment by scovit** [comment]
Hi, I think that the current solution has the issue that many common actions in Raku, such as warn, cause the program to abort. Doing as python and redirect output to NUL hide both warning and errors, which might be preferable, but not optimal. But has the plus of allowing the user to still assign different files using NativeCall.

A more windows solution might be to set STDIN and STDOUT to NUL, and for STDERR hook into: 
https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw
or
https://docs.microsoft.com/en-us/windows/win32/dlgbox/using-dialog-boxes

**Comment by patrickbkr** [comment]
I have implemented the "simple" solution of just redirecting everything to `NUL:` for now. That's also what Python 3 does.
Note that calling the process with attached IO will make the handles work again and the output appear. The following will do what one would expect:

    rakuw.exe foo.raku 2>stderr.txt >stdout.txt

I'm not objected per se to exploring alternative solutions (MessageBoxing STDERR?). But this will need careful consideration. (What about services?)
