### ISSUE TITLE
Attempting to copy a directory to an existing file throws but destroys the file

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3971]
## The Problem

Given an existing directory and existing file, inadvertently attempt to copy the directory to the file.

## Expected Behavior

The attempt will result in an exception and the target file will be unaltered.

## Actual Behavior

The file is destroyed.

## Steps to Reproduce

execute:

````
my $f = "/tmp/f1";
spurt $f, "some text";
my $dir = "/tmp/dir";
mkdir $dir;
copy $dir, $f;
````

get OUTPUT:

````
Failed to copy '/tmp/dir' to '/tmp/f1': Failed to copy file: illegal operation on a directory
  in block <unit> at dirfil.raku line 5
````

check the original file:

````
$ ls -l /tmp/f1
ls: cannot access '/tmp/f1': No such file or directory
````

## Environment

* Operating system: Debian Buster (10)
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.09 built on MoarVM version 2020.09
implementing Raku 6.d.

**Comment by lizmat** [comment]
Thanks for the spot and thanks for the fix and tests!
