### ISSUE TITLE
Regex array interpolation tracks changes in array, should it?

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#3988]
## The Problem

```
my @keywords = < this that>;
my $re = / @keywords /;
dd "this is fun" ~~ $re;
dd "what is fun" ~~ $re;
@keywords.push: 'what';
dd "what is fun" ~~ $re;
```
## Expected Behavior

I would expect the regex to be fixed at creation time:
```
Match.new(:orig("this is fun"), :from(0), :pos(4))
Nil
Nil
```
## Actual Behavior

But it tracks the change to the array:

```
Match.new(:orig("this is fun"), :from(0), :pos(4))
Nil
Match.new(:orig("what is fun"), :from(0), :pos(4))
```
## Notes

in NQP, this construct was very fast; converting to Raku, my script went from about 5s to about 145s - by eliminating the regex and instead using ```.contains(any(@keywords))```, performance went back to 5s for that script. I am unsure if the slowdown is related, but that's how I found this.

https://github.com/Raku/nqp/commit/d1b2c12d836d51e366f6da4836d19974bf034cb5

## Environment

This is Rakudo version 2020.07-54-gd4bac47ff built on MoarVM version 2020.07
implementing Raku 6.d.

**Comment by alabamenhu** [comment]
This is the intended design — after all, you want to be able to do something like

```
my &rx = /
  :my $foo;
  $<bar> = [ a | b ]
  { $foo = $<bar> eq 'a' ?? 'x' !! 'y' }
  $foo
/;
```

`$foo` here is conditioned on a code block that isn't run until matched against.  `$foo` needn't belong to the regex's scope either.  Having such variables fixed at creation in such cases is very unintuitive.  After all, a regex is really just a code block in a different language, and if we had written your code as:

```
my @keywords = <this that>
my $re = { .contains: any @keywords };
dd "this is fun" ~~ $re;
dd "what is fun" ~~ $re;
@keywords.push: 'what';
dd "what is fun" ~~ $re;
```

the result would be the same, and intuitively/unremarkably so:

```
Bool::True
Bool::False
Bool::True
```

If you need to freeze it in place, you can use a closure to protect its value:

```
my @keywords = < this that>;
my $re = { my @k = @keywords; / @k / }();
dd "this is fun" ~~ $re;
dd "what is fun" ~~ $re;
@keywords.push: 'what';
dd "what is fun" ~~ $re;

# Output:
# Match.new(pos => 4, hash => Map.new(()), list => (), made => Any, orig => "this is fun", from => 0)
# Nil
# Nil
```

**Comment by coke** [comment]
> in NQP, this construct was very fast; converting to Raku, my script went from about 5s to about 145s - by eliminating the regex and instead using `.contains(any(@keywords))`, performance went back to 5s for that script. I am unsure if the slowdown is related, but that's how I found this.

Unsurprisingly, using the closure doesn't speed it up at all, it's still much slower in Raku using this construct than the junction.

**Comment by MasterDuke17** [comment]
FWIW, NQP has the same behavior:
```perl6
my @a := 1, 3, 5, 7;
my $rx := / @a /;
say("246005" ~~ $rx);
nqp::unshift(@a, 2);
say("246005" ~~ $rx);
```
outputs "5␤2".

In NQP literals are faster, but only slightly.
`time ./nqp-m -e 'my @a := 1, 3, 5, 7; my $b := 0; my $c := 0; while $b++ < 100_000 { $c++ if $b ~~ / 1 | 3 | 5 | 7 / }; say($c)'` gives ~0.52s, but
`time ./nqp-m -e 'my @a := 1, 3, 5, 7; my $b := 0; my $c := 0; while $b++ < 100_000 { $c++ if $b ~~ / @a / }; say($c)'` gives ~0.66s
