### ISSUE TITLE
Mixing in roles (but, does) dies under 6.e.PREVIEW

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#3990]
## The Problem

Attempting to use `but` or `does` to mixin Roles dies when using `v6.e.PREVIEW`.

## Expected Behavior

This should not die

```perl-6
use v6.e.PREVIEW;
say 0 but True;
```

## Actual Behavior

Dies with the following error

```
Type object Int+{<anon|2>} of v6.c is not compatible with <anon|2> of v6.e
```

## Steps to Reproduce

See the above example.

Additionally, these examples from the [Docs](https://docs.raku.org/routine/but) also fail

```perl-6
my $forty-two = 42 but 'forty two';
my $s = 12 but class Warbles { method hi { 'hello' } }.new;
```

All these examples use `Int`, but the same issue affects other types.

## Environment
* Operating system: CentOS6
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.10.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.10.

**Comment by 0racle** [comment]
Attempted to run this through Bisectable found commit: [Don't use client core rev to determine class language version ](https://github.com/rakudo/rakudo/commit/15a5580164da49345a92e71ff4a68567b232c574)

Bisectable logs: -

(00:36:15)     elcaro │ bisectable6: https://gist.githubusercontent.com/0racle/d279dc13db03bd1602cd02e4cb7d0981/raw/c72f4872ab1e81fe68279df62db9dba992519ef4/mixin-role.raku
(00:36:28)  bisectabl • elcaro, Will bisect the whole range automagically because no endpoints were provided, hang tight
(00:36:28)  bisectabl • elcaro, Successfully fetched the code from the provided URL
(00:36:47)  bisectabl • elcaro, Successfully fetched the code from the provided URL
(00:36:47)  bisectabl • elcaro, Output on all releases: https://gist.github.com/cd180baa8e1e3cca8a92d69df6b57120
(00:36:51)  bisectabl • elcaro, Bisecting by exit code (old=2019.11 new=2020.01). Old exit code: 0
(00:37:14)  bisectabl • elcaro, bisect log: https://gist.github.com/7355b269372d80d4d6c6a76f81f9d06a
(00:37:14)  bisectabl • elcaro, (2019-12-13) https://github.com/rakudo/rakudo/commit/15a5580164da49345a92e71ff4a68567b232c574
(00:37:15)  bisectabl • elcaro, Successfully fetched the code from the provided URL
(00:37:18)  bisectabl • elcaro, Bisecting by exit code (old=2019.03.1 new=2019.07.1). Old exit code: 1
(00:37:47)  bisectabl • elcaro, bisect log: https://gist.github.com/031c6b4ea38972612400c1901d398758
(00:37:48)  bisectabl • elcaro, Successfully fetched the code from the provided URL
(00:37:51)  bisectabl • elcaro, Bisecting by output (old=2018.10 new=2018.11) because on both starting points the exit code is 1
(00:38:12)  bisectabl • elcaro, bisect log: https://gist.github.com/44de295953b0c8fd8f0a66376d535373
(00:38:12)  bisectabl • elcaro, (2018-10-27) https://github.com/rakudo/rakudo/commit/46ef0ea08cae96db25c7b5a9543ba696034408c8
(00:38:25)  bisectabl • elcaro, Output on all releases and bisected commits: https://gist.github.com/441dadb6d781e0c0cb3194ba19a472cb

**Comment by vrurg** [comment]
This is expected behaviour. Due to drastic changes in `6.e` role behavior they're really not backward compatible with type objects from older language versions. This means that most of the core type objects can't be mixed with roles from `6.e`. The only workaround for now is to have a module of `6.c`/`6.d` version which would define and export roles supposed to be used in such mixins.

**Comment by lizmat** [comment]
@vrurg could you elaborate about what would be needed *exactly* to make `0 but True` work in 6.e?

**Comment by AlexDaniel** [comment]
@vrurg 🤯 That probably requires a rework of whateverable. `but` is a hacky way of doing things but it's extremely convenient.

**Comment by vrurg** [comment]
> @vrurg could you elaborate about what would be needed _exactly_ to make `0 but True` work in 6.e?

I don't know yet as I don't know the details of `but` implementation. It would be necessary to determine the version of LHS object and create a role of the same version for it. Basically, as long as these auto-gen roles do not use construction/destruction submethods (and they don't) it would only be a matter of setting required language version for them. Or, for that matter, they could always be `6.c` only.

On the other hand, there is no solution for:

```raku
use v6.e.PREVIEW;
role R { }
my $v = 0 but R;
```

In this case `R` is explicitly created as `6.e`. To make this work I move such roles in dedicated `6.c` modules.

**Comment by vrurg** [comment]
#3997 resolves this.
