### ISSUE TITLE
'start react whenever' is unreliable.

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#3995]
# The Problem

The following construct: 

```raku
start react whenever $supply -> $item { ... }
```

is unreliable and prone to freezing or stucking.

## Steps to Reproduce

It's a rather long script which allows to try slightly different scenarios. The idea of the test is to run multiple jobs, start a `react`/`whenever` thread (event loop) for each one, send an event object from job's main thread and wait until the event loop keeps a promise attached to the event object. If an event object is lost then it causes the job to stuck in `await` and result in a timeout.

```raku
BEGIN: {
    $*SCHEDULER = ThreadPoolScheduler.new: :max_threads(200);
}

constant JOBS = 100;
constant TOTAL = 1000000;
constant EVENTS = 10;

my atomicint $failures = 0;
my atomicint $total-ran = 0;

class Event {
    has Promise:D $.complete .= new;
    has Bool:D $.last = False;
}
class EventLoop {
    has Int:D $.id is required;
    has Channel $.queue .= new;
    has atomicint $.count is rw = 0;
    has Promise $.done;
    has Promise $.ev-loop is rw;

    # has Supplier:D $.supplier .= new;
    # has Supply $.queue = $!supplier.Supply;

    submethod TWEAK {
        self.event-loop;
    }

    method run {
        CATCH {
            note "IN RUNNER: ", .message;
            .rethrow;
        }
        sub send-events {
            for ^EVENTS -> $i {
                my Event:D $ev = Event.new: :last($i == (EVENTS - 1));
                # XXX THE PACKET IS GETTING SEND, NO ERROR HERE ...
                $.queue.send: $ev;
                # $.supplier.emit: $ev;
                await $ev.complete.then: {
                    ++⚛$!count if .status ~~ Kept;
                };
            }
        }
        ++⚛$total-ran;
        $!done = Promise.anyof(
            Promise.in(10).then({
                if $!done.status ~~ Planned {
                    note "ID #$.id TIMED OUT, channel stuck after ", $!count, " processed events";
                    ++⚛$failures;
                    die "$.id timed out"
                }
            }),
            start {
                send-events;
                note "ID $!id: bad count of processed events: ", $!count if $!count != EVENTS;
            }
        )
    }

    # Fetching with `react`
    method event-loop {
        # XXX ... THE PACKET DOESN'T LAND IN $ev
        $.ev-loop = start react whenever $.queue -> $ev {
            $ev.complete.keep;
            done if $ev.last;
        }
    }

    # Fetching with `tap`
    # # THIS VERSION IS SEEMINGLY NOT AFFECTED BY THE PROBLEM
    # method event-loop {
    #         $.queue.tap:
    #             -> $ev {
    #                 $ev.complete.keep;
    #                 $.supplier.done if $ev.last;
    #             }
    # }

    # Fetching with `receive`
    # # THIS VERSION IS SEEMINGLY NOT AFFECTED BY THE PROBLEM
    # method event-loop {
    #     $.ev-loop = start {
    #         CATCH {
    #             note "ID #$!id IN EV LOOP: ", .message;
    #             .rethrow;
    #         }
    #         loop {
    #             my $ev = $.queue.receive;
    #             $ev.complete.keep;
    #             last if $ev.last;
    #         }
    #     }
    # }
}

my %active;
my $id = 0;
my $lock = Lock.new;
while ($id < TOTAL || +%active) && $failures < 2 {
    my @promises;
    $lock.protect: {
        $*ERR.printf: "Active: %4d / %6d \r", %active.elems, $id;
        if $id >= TOTAL || %active.elems >= JOBS {
            @promises = %active.values.map: *.done;
        }
    }
    if @promises {
        await Promise.anyof(@promises);
    }
    while ($id < TOTAL) && (%active.elems < JOBS) {
        my $cur_id = $id;
        my $el = EventLoop.new: :$id;
        $lock.protect: {
            %active{$cur_id} = $el;
            $*ERR.printf: "Active: %4d / %6d \r", %active.elems, $id if ($id % 100) == 0;
        }
        $el.run;
        $el.done.then: {
            $lock.protect: {
                %active{$cur_id}:delete;
            }
        }
        ++$id;
    }
}

note "\nDone, failure rate: ", $failures / $total-ran;

exit ($failures min 254)
```

## Outcomes

Here is what I got on Linux Mint and macOS. List items define what means were used for event delivery, what method of fetching, and values of script constants used. Note that script stops producing new jobs after two failures. So, not all `TOTAL` jobs were ran on failing tests.

### Linux

- `Channel`, `react`, JOBS==1, EVENTS==3

   ```
   ID #88936 TIMED OUT, channel stuck after 1 processed events
   ID #141834 TIMED OUT, channel stuck after 1 processed events
   ```

- `Channel`, method `receive`, JOBS=100, EVENTS=100

   ```
   IN EV LOOP: Cannot call method 'last' on a null object
   ID #70822 TIMED OUT, channel stuck after 2 processed events
   ```

   I think the timeout here was caused by the erroneous null object received. Otherwise, no timeouts occur when `receive` method is used. The _null object_ issue happened only once to me in the numerous attempts to get a timeout with this method.

- `Supply`, `react`, JOBS==100, EVENTS==10

   ```
   ID #293032 TIMED OUT, channel stuck after 0 processed events
   ID #293067 TIMED OUT, channel stuck after 0 processed events
   ID #293070 TIMED OUT, channel stuck after 0 processed events
   ```

## macOS:

It looks like macOS is overall more problem-proof. It was less likely to fail, than Linux. Yet, it's still not immune.

- `Channel`, `react`, JOBS=1000, EVENTS=3

   ```
   ID #411982 TIMED OUT, channel stuck after 1 processed events
   ID #674842 TIMED OUT, channel stuck after 1 processed events
   ```

- `Supply`, `react`, JOBS==100, EVENTS=10

   ```
   ID #370015 TIMED OUT, channel stuck after 0 processed events
   ID #370028 TIMED OUT, channel stuck after 0 processed events
   ID #370030 TIMED OUT, channel stuck after 0 processed events
   ID #370031 TIMED OUT, channel stuck after 0 processed events
   ID #370032 TIMED OUT, channel stuck after 0 processed events
   ID #370033 TIMED OUT, channel stuck after 0 processed events
   ID #370034 TIMED OUT, channel stuck after 0 processed events
   ```

## Conclusion

The problem is clearly lies somewhere in `react`/`whenever` chain. Use of `receive` on `Channel` and `tap` on `Supply` eliminates it.

The tests were done using Rakudo v2020.10. But, considering that the bug was discovered with real code of `Test::Async`, which I ran against various Rakudo builds starting with 2019.11, my guess would be that it's not something new or recently introduced.

**Comment by vrurg** [comment]
I have a strong desire to put `BLOCKER` on this case because Raku claims to be asynchronous with `react`/`whenever` been one of the language corner stones. A bug in them resulting in data loss is something we should consider intolerable.

**Comment by Altai-man** [comment]
@vrurg we can, but it's a question if there will be someone brave enough with free time to tackle on the problem.

**Comment by niner** [comment]
On Samstag, 31. Oktober 2020 03:39:54 CET Vadim Belman wrote:
> I have a strong desire to put `BLOCKER` on this case because Raku claims to
> be asynchronous with `react`/`whenever` been one of the language corner
> stones.A bug in them resulting in data loss is something we should
> consider intolerable.

Why would this bug block a release if as you say it's probably not a 
regression and can re reproduced in a year old release? The point of having 
release blocking bugs is to avoid shipping something that is worse for our 
users than what they already have. In other words: why would we keep bug fixes 
from our users just because we've discovered another bug that's been there 
probably forever. How would users benefit from that?

As @Altai-man pointed out, designating a bug a BLOCKER does not create or free 
up resources to create a fix for that bug.

**Comment by AlexDaniel** [comment]
> Why would this bug block a release if as you say it's probably not a
regression and can re reproduced in a year old release?

Well, there's a reason a completely separate label exists. In the past the label was indeed sometimes used for relatively horrible issues (that were not regressions), and it was successful. That said, nobody seemed to argue as much back then, so there's that too.

Personally, in the past I would've found this justification sufficient:

> Raku claims to be asynchronous with `react`/`whenever` been one of the language corner stones. A bug in them resulting in data loss is something we should consider intolerable.

Yes.

Why can it block? Well, simply because I wouldn't've felt comfortable making a release knowing full well that a bug like this exists in it. So, I think, the classification is 100% up to the current release manager, and I believe the release manager has enough pressure on them that trying to argue that something shouldn't be marked as a blocker with an attitude like this is not a good idea (but trying to get attention to a particularly nasty issue *is*).

Thought I'd chime in on something that relates that much to my past work.

🙋

**Comment by vrurg** [comment]
@niner 

> Why would this bug block a release if as you say it's probably not a regression and can re reproduced in a year old release? 

I kept all that in mind and thus the suggestive tone of my comment. Today I it crossed my mind that we have `severe` label which is probably better for this case.

**Comment by vrurg** [comment]
Closing because a subtle race condition found in the test code itself. When the condition is taken care of the code works as expected.
