### ISSUE TITLE
Make the offered Rakudo (Windows) versions consistent

### ISSUE THREAD

**Issue by AntonOks** [rakudo/rakudo#3996]
## The Problem
Cannot automate Rakudo installation on Windows via [scoop ](https://scoop.sh/) and other package managers due to different Rakudo release information's on various places.

## Expected Behavior
Have the same Rakudo version information everywhere consistent. Especially the offered ZIP file and the included compressed Rakudo folder should have 100% the same logic / naming!

## Actual Behavior
The latest [release on GitHub](https://github.com/rakudo/rakudo/releases) says [2020.10](https://github.com/rakudo/rakudo/releases/tag/2020.10) but no corresponding Windows package (zip) is offered here.

There is NO version **_2020.10_** on the "[official download page](https://rakudo.org/downloads/rakudo)" (??!). Here we have a [2020.10**_-01_**](https://rakudo.org/dl/rakudo/rakudo-moar-2020.10-01-win-x86_64.zip) ZIP file, **_BUT_** within this ZIP file the directory, which should represent the Rakudo version is _2020.01_ instead of 2020.10**_-01_** (aka same as the Rakudo version).

## Steps to Reproduce

- Download https://rakudo.org/dl/rakudo/rakudo-moar-2020.10**_-01_**-win-x86_64.zip
- Extract it to C:\Temp\rakudo-moar and look into this directory. You will see "rakudo-**_2020.10_**" there instead of (expected related to the offered ZIP file name!) **_rakudo-2020.10-01_**

## Environment
* Operating system: Windows but this doesn't play a role ;)
* Compiler version (`perl6 -v` or `raku -v`): 2020.10 ZIP file ;)

**Comment by AntonOks** [comment]
@patrickbkr 

Seems like the "problem" is https://github.com/rakudo/rakudo/blob/0a4eaf3110e8fe52f33f0f43cbd3d78908c2138c/tools/build/binary-release/build-windows.ps1#L67

Guess [$Env:REVISION](https://github.com/rakudo/rakudo/blob/0a4eaf3110e8fe52f33f0f43cbd3d78908c2138c/azure-pipelines.yml#L12) would also be known in this script so this line should be `mv install rakudo-$Env:VERSION-$Env:REVISION`... and L68 needs then also to reflect this change afterwards ;)

**Comment by patrickbkr** [comment]
For context: The `-01` is the build revision number. It is incremented, when the process of creating the precompiled release archive (not the source release!) some how messed up and we need to make a second precompiled archive. Then that second precomp archive will have a `-02`, in its name, but will be based on the same source.

@AntonOks Thanks for your report! Can you elaborate a bit how scoop and similar tools are tripped up? I'm just wondering, since even with the added `-01` in the folder name the archive file and folder name would still be different. i.e. `rakudo-moar-2020.10-01-win-x86_64.zip` vs `rakudo-moar-2020.10-01`.

@Altai-man What's your opinion wrt backwards compatibility? How much should we be worried when changing the directory layout in the precompiled release files?

@nxadm I'd be interested in your opinion on this one.

**Comment by AntonOks** [comment]
> @AntonOks Thanks for your report! Can you elaborate a bit how scoop and similar tools are tripped up? I'm just wondering, since even with the added `-01` in the folder name the archive file and folder name would still be different. i.e. `rakudo-moar-2020.10-01-win-x86_64.zip` vs `rakudo-moar-2020.10-01`.

scoop is just one / my example. It's very flexible and I guess I could hack the [manifest ](https://github.com/lukesampson/scoop/wiki/App-Manifests) around the existing Rakudo ZIP file and it's autoupdate -  "[extract_dir](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#properties-of-autoupdate)" requirement... as the Rakudo ZIP file is done today it is just inconsistent and makes little sense in general from my point of view.

Other SW packers have **_EITHER_** the compressed directory representing the version similar to the ZIP file name/version itself, so rakudo-(moar)-2020.10**-01** in my given example, **_OR_** they have a **general directory name** without any version information in it (because the version is represented in the ZIP file name anyhow already ;)), so her this would result in "rakudo" or "rakudo-moar"...

Again, IMHO mixing up the version information given by the ZIP file name and by the included compressed directory just makes no sense... and sometimes things are therefore unnecessarily complicate.

**Comment by Altai-man** [comment]
>What's your opinion wrt backwards compatibility? How much should we be worried when changing the directory layout in the precompiled release files?

Cannot say anything particular unless I see any examples.

**Comment by AntonOks** [comment]
> Cannot say anything particular unless I see any examples.

@Altai-man Examples for what? So you want some "rakudo-moar" ZIP files?

**Comment by Altai-man** [comment]
@AntonOks I meant a more detailed plan of changes from @patrickbkr to make us support what you suggest, so that we could consider how breaking the changes would be. Sorry for the confusion, "examples" is probably not the best word.

**Comment by AntonOks** [comment]
@Altai-man Thanks for your explanation.
@patrickbkr @nxadm I've created pull #4006 so it's hopefully easier for you to check and decide on the "impact" of this change...

**Comment by patrickbkr** [comment]
I have looked at the rakubrew source. Luckily [rakubrew will not trip](https://github.com/Raku/App-Rakubrew/blob/master/lib/App/Rakubrew/Download.pm#L72) over a changed name, as long as it starts with `rakudo-`. That's the only automated tool I know about that relies on the prebuilt executables. I can't rule out that there are already other tools out there relying on this.

I have looked around what others do:

- Python has no single folder in its zip files at all, they put the `bin`, `share`, `README` directly in the zip.
- Go has a folder in the zip named `go`.
- Ruby(Installer) names the folder identical to the zip file name: `rubyinstaller-2.7.2-1-x64`.
- Julia does what we currently do with Rakudo: `julia-1.5.2-win64.zip` containing a folder named `julia-1.5.2`
- Our Rakudo source releases have: `rakudo-2020.10.tar.gz` containing a folder named `rakudo-2020.10`

So the naming is all over the field.

I personally like having the folder name include the version. This makes it easier unzipping a newer version in the same folder where a previous one already exists. Also I tend to have rakudo versions lying around and like it when the folder name is a bit telling (in contrast to the generic `rakudo`).

I think the obvious alternative to our current `rakudo-2020.10` folder name would be the full description, i. e. `rakudo-moar-2020.10-01-win-x86_64`. I myself wouldn't mind much having such a long name. What do others think?

@Altai-man @nxadm @niner 

@AntonOks I'd like to clarify one more thing. The only place where we offer the full set of release files (source and binaries) is the <rakudo.org> website. We actually do provide the `rakudo-2020.10` (without the `-01`) releases on the <rakudo.org> website. You have to select the `Source` tab though. The reason there is no `-01` in the source archive name is that the source is not compiled and thus does not have a _build revision number_. We also put the source releases on GitHub, but currently those serve as a backup mostly.

I think what this issue makes quite clear, is that we need to be more clear with how the file name of the binary release files is put together. I'll try to create a respective PR.

**Comment by niner** [comment]
> I think the obvious alternative to our current `rakudo-2020.10` folder name
> would be the full description, i. e. `rakudo-moar-2020.10-01-win-x86_64`. I
> myself wouldn't mind much having such a long name. What do others think?

rakudo-2020.10 would fit the presumably most common convention, the naming of 
our source dist and what I use for packaging. I could live with rakudo-
moar-2020.10-01-win-x86_64 but would prefer the former.

**Comment by patrickbkr** [comment]
Since we are now thinking about changing something in the binary release names it might be a good time to also think about whether we want to include the toolchain in the name (i. e. `msvc`, `gcc` or `clang`). Others sometimes do that and I think it's possible we want to provide files for different architectures some time in the future as well.

That could then look like this: `rakudo-moar-2020.10-01-win-x86_64-msvc.zip`

**Comment by AntonOks** [comment]
> @AntonOks I'd like to clarify one more thing. The only place where we offer the full set of release files (source and binaries) is the <rakudo.org> website. We actually do provide the `rakudo-2020.10` (without the `-01`) releases on the <rakudo.org> website. You have to select the `Source` tab though. The reason there is no `-01` in the source archive name is that the source is not compiled and thus does not have a _build revision number_. We also put the source releases on GitHub, but currently those serve as a backup mostly.
> 
> I think what this issue makes quite clear, is that we need to be more clear with how the file name of the binary release files is put together. I'll try to create a respective PR.

@patrickbkr Thanks for clarifying & I know... see my initial "problem statement"... I wrote a manifest for the scoop package manager and so this here started...

BTW., the [rakudo-star-2020.01-01](https://rakudo.org/dl/star/rakudo-star-2020.01-01-win-x86_64-(JIT).msi) MSI package is packed into a simple "**_rakudo_**" folder as you can see [here  ](https://github.com/ScoopInstaller/Main/blob/c704d5b149fe63d3bc960abaf60e3dfd5f6b21e5/bucket/rakudo-star.json#L12) or check by yourself by extracting it with [lessmsi ](http://lessmsi.activescott.com/) to a folder of your choice...
 
@Altai-man @nxadm @niner

**Comment by patrickbkr** [comment]
@AntonOks I'm not sure if it's relevant for your current efforts. But did you know that there is an API for the downloads available on rakudo.org? <https://rakudo.org/dl/rakudo/>

**Comment by AntonOks** [comment]
> @AntonOks I'm not sure if it's relevant for your current efforts. But did you know that there is an API for the downloads available on rakudo.org? https://rakudo.org/dl/rakudo/

@patrickbkr Cool, thanks, didn't know that. Where can I find more about how to use it?

**Comment by patrickbkr** [comment]
@AntonOks There isn't any documenation at the moment. It's basically only an index of all available releases with some meta information. That API is what rakubrew uses for it's `download` mechanism. Looking at [the source](https://github.com/Raku/App-Rakubrew/blob/master/lib/App/Rakubrew/Download.pm#L91) might give some hints on how to use it.

**Comment by patrickbkr** [comment]
@Altai-man Can you explain why you consider this issue a blocker?

It's not a regression.
The current behaviour is debatable, but not obviously wrong. (JuliaLang does the exact same thing we do.)
If I understood AntonOks correctly work on scoop is not blocked by the current behavior.

**Comment by patrickbkr** [comment]
@Altai-man I'm unsure about who else to ask to give feedback. I suspect it's mostly a matter of taste. So I'd like to make sure we actually hit the taste of the majority if we decide to change something.

**Comment by nxadm** [comment]
Sorry for my late reaction. 

I think the pkg release version should be part of the zip file name. I am OK with all the suggested changes (and the status quo), but I have to choose I would name the directory within the zip `rakudo`, without version number.

@Altai-man This looks like an slight improvement to me, not a blocker at all.

**Comment by AntonOks** [comment]
> If I understood AntonOks correctly work on scoop is not blocked by the current behavior.

@patrickbkr Correct. scoop is very flexible and I've already a manifest in my private scoop bucket with a working ["autoupdate" regex](https://github.com/AntonOks/scoop-aoks/blob/319d63f3b4cee75eca1f74924e2ed0bf71f057ec/bucket/rakudo-moar-aoks.json#L28)

I'm now just waiting for your decision and the future setup and would then add it also to the ["scoop main" bucket](https://github.com/ScoopInstaller/Main) so many more dev's could benefit from the frequently updated rakudo moar versions

THANKS for all your feedback, ideas, efforts...!!!

@Altai-man @nxadm @niner

**Comment by Altai-man** [comment]
>Can you explain why you consider this issue a blocker?

This affects actual packages we produce and at the same time it is not a huge change, so if we can make yet another platform support easier one month later, I would take that.

But yes, it is probably not really severe, I am just paranoid.

**Comment by patrickbkr** [comment]
Just to make clear what options we are talking about. We have an archive file currently named as follows: `rakudo-moar-2020.10-01-win-x86_64.zip`

Options proposed so far:

1. `rakudo` (preferred by: nxadm)
2. `rakudo-2020.10` (no change, preferred by: niner)
3. `rakudo-2020.10-01` (preferred by: AntonOks)
4. `rakudo-2020.10-01-moar-win-x86_64-msvc` (preferred by: patrickb)

If we decide to touch the naming, I would like to also rename the archive itself: `rakudo-2020.10-01-moar-win-x86_64-msvc.zip` (put the version number first, add compiler toolchain). That name change is necessary as soon as we start to offer builds with multiple compiler toolchains anyways.

I'll leave this open until Friday for further feedback / opinions and then decide.

**Comment by niner** [comment]
I could warm up to going all in, i.e. option 4. That would allow for unpacking 
e.g. builds differing only in the used compiler tool chain into the same 
directory for comparison of behaviour.

**Comment by patrickbkr** [comment]
@niner That's one of the two reasons I like option 4. The other being boring consistency of file and dir name.

**Comment by patrickbkr** [comment]
We'll go with option 4. New prebuilt binary archives will include the toolchain in their filename. The included folder will have the same name. Older release archives will not be touched and will stay the way they are. The 2020.11 release will already follow the new naming scheme.
