### ISSUE TITLE
∈/(elem) given an an Int:D argument from sub MAIN and a Seq:D gives erroneous results

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#4004]
## The Problem
While toying with a script, I found that it wasn't behaving like I expected it to with the input I was giving. This is about as far as I can golf the problem:
```perl6
use v6;
unit sub MAIN(Int:D $x) {
    say $x ∈ [X+] (1..3) xx 2;
}
```

## Expected Behavior
This should output `True` given any possible sum of `1`, `2`, or `3` (e.g. `2`) as input.

## Actual Behavior
This outputs `False` given `2`.

The weird thing is this will work with other `Int:D`s:
```perl6
use v6;
unit sub MAIN(Int:D $x) {
    my Int:D $y = 2;
    say $y ∈ [X+] (1..3) xx 2;
}
```

But not `$x`. Not even clones of `$x`. Other ways of generating a new `Int:D` from `$x` with the same value will allow this to work though:

```perl6
use v6;
unit sub MAIN(Int:D $x) {
    say $x.succ.pred ∈ [X+] (1..3) xx 2;
}
```

## Steps to Reproduce

Save the test code as `test.raku` and run it with an integer as an argument.

## Environment
* Operating system:
OpenBSD bastille.kennel.qt 6.8 GENERIC.MP#116 amd64
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to Rakudo(tm) v2020.10-51-g53b558fe0.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.10-20-g70e3608cb.

**Comment by AlexDaniel** [comment]
Int:D does not guarantee you an Int, as surprising as it sounds. In this case I think you're getting an IntStr.

**Comment by taboege** [comment]
That statement is not what I would call surprising, because IntStr is a subclass of Int, so of course an Int constraint would accept it. By contrast, I would be surprised if, for the same reason, `Any:D` would refuse to accept anything whose type is more specific than `Any`.

Otherwise AlexDaniel is spot on. You get an IntStr and set semantics of (elem) rely on the value type behavior of IntStr, where `<2>.WHICH` is `IntStr|2`, distinct from `2.WHICH`. That's a hairy situation...

**Comment by AlexDaniel** [comment]
@taboege well, OOP is not surprising, yes, but its combination with primitive types and this specific implementation is. It is explainable but still surprising – if a user asked for an Int:D it is not obvious that the constraint will still allow something that acts essentially as a Str. And yes, we have this ticket after all :)

> That's a hairy situation...

Heh, I guess that's a more accurate description :)

**Comment by lizmat** [comment]
Please change the code to:

    say +$x ∈ [X+] (1..3) xx 2;

And you should be fine.  This is a bit of a trap, I agree.

Or you could be more explicit:

    unit sub MAIN(IntStr:D $x) {
        say $x.Int ∈ [X+] (1..3) xx 2;
    }

Conceivably it would be possible to create a module called `allomorphs-are-numeric` and/or a `allomorphs-are-strings` that would export special set operator candidates that would do the necessary   coercions, but that still feels like sweeping this under the rug.  I think being explicit in the signature, and do the coercion yourself, would create better readable and better maintainable code.

**Comment by ugexe** [comment]
```
$ raku -e 'sub MAIN(Int(Int:D) $x) { say $x.WHAT }' 42

(IntStr)
```
Could coercions be used/changed such that the above instead prints `(Int)`? Similar to how (non-allomorph) `IO()` works:

```
$ raku -e 'sub MAIN(IO() $x) { say $x.WHAT }' 42

(Path)
```

**Comment by lizmat** [comment]
> $ raku -e 'sub MAIN(Int(Int:D) $x) { say $x.WHAT }' 42
> (IntStr)

I think that is actually a bug.  It *should* have coerced to `Int`.  Feels like the coercion logic is doing an `istype` check, rather than a `eqaddr` check.

**Comment by vrurg** [comment]
How come is this a bug? Coercion should only be done when the requested type doesn't accept the parameter. `IntStr` is an `Int` after all.

**Comment by lizmat** [comment]
@vrurg well, that's a matter of interpretation.  The way I always read coercion syntax in signatures for e.g. `Int(Cool)` is `parameter.Int if parameter ~~ Cool`.

**Comment by vrurg** [comment]
@lizmat but the implementation we have say otherwise. Compare: `class Foo { method Int { note "INT"; 42 } }; sub foo(Int(Any) $v) { note $v.WHICH }; foo(Foo.new)` and `class Foo is Int { method Int { note "INT"; 42 } }; sub foo(Int(Any) $v) { note $v.WHICH }; foo(Foo.new)`. To my view this is correct because what's the point of wasting CPU cycles on coercion if an object is already passes the typecheck?

**Comment by lizmat** [comment]
@vrurg I think it should only skip the coercion part if the type matches **exactly**.

Also, there are plenty of cases where the typecheck for acceptance would not pass the typecheck of the coercer, e.g. `Int(Str)`.

**Comment by vrurg** [comment]
> @vrurg I think it should only skip the coercion part if the type matches **exactly**.

Absolutely no. Imagine a class family where `Base` is the root class and others inherit from it directly or not. I need to be able to accept any class from the family but provide means for other classes outside of the family to coerce into `Base`. Yet, any family class I need as-is without transformation, even though some of them can coerce into plain `Base`. So, some child classes will translate into `Base` despite my will. If the coercion behaves as you see it – I wouldn't have a solution except for manual check in `where` which is ugly. Yet, whenever I need exactly `Base` – I can always do it manually, and it's easier, than manually typechecking a parameter.

Yet, it's even worse considering that `Base` doesn't need a coercion method for itself. It's pointless to have one. But an attempt to `Base(Any)` will likely result in an error would a child class be used – exactly for the reason there is no `Base` method on it.

> Also, there are plenty of cases where the typecheck for acceptance would not pass the typecheck of the coercer, e.g. `Int(Str)`.

When I eventually finish my recent work on coercing, this should be fixed. I believe, most of your confusion comes from the currently problematic typecheck implementation.

**Comment by lizmat** [comment]
Now that https://github.com/rakudo/rakudo/pull/4005 has been merged, I think this issue can be closed.  Please re-open if you disagree.
