### ISSUE TITLE
Str.uniparse appears to duplicate last code point in at least one case

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4007]
dd "WAVING WHITE FLAG, VARIATION SELECTOR-16,
      ZERO WIDTH JOINER, TRANSGENDER SYMBOL,
      VARIATION SELECTOR-16".uniparse.NFD;
    # Uni.new(0x1f3f3, 0xfe0f, 0x200d, 0x26a7, 0xfe0f, 0xfe0f).NFD

Note that the last code point `VARIATION SELECTOR-16` (`0xfe0f`) appears *twice* at the end in the NFD version.  And occurs in the string when converted back to string and uninamed:

    dd "WAVING WHITE FLAG, VARIATION SELECTOR-16,
      ZERO WIDTH JOINER, TRANSGENDER SYMBOL,
      VARIATION SELECTOR-16".uniparse.NFD.Str.uninames;
    # ("WAVING WHITE FLAG", "VARIATION SELECTOR-16", "ZERO WIDTH JOINER", "MALE WITH STROKE AND MALE AND FEMALE SIGN", "VARIATION SELECTOR-16", "VARIATION SELECTOR-16").Seq

Since any module that tries to do this actual uniparsing of this sequence in Rakudo before the Unicode 13.1 merge dies in interesting ways:  https://github.com/lizmat/Text-Flags/runs/1359363360?check_suite_focus=true I assume support for the transgender flag was added in 13.1.  But apparently, it still needs some work.

**Comment by lizmat** [comment]
@samcv @thundergnat ping

**Comment by AlexDaniel** [comment]
`TRANSGENDER SYMBOL` itself contains a variation selector:

```bash
perl6 -e 'dd "TRANSGENDER SYMBOL".uniparse.uninames'
```
```
("MALE WITH STROKE AND MALE AND FEMALE SIGN", "VARIATION SELECTOR-16").Seq
```

I don't know why. It appears in [emoji-sequences.txt](https://unicode.org/Public/emoji/13.1/emoji-sequences.txt):
```
26A7 FE0F     ; Basic_Emoji                  ; transgender symbol                                             # E13.0  [1] (⚧️)
```
And also [ends up](https://raw.githubusercontent.com/MoarVM/MoarVM/master/src/strings/unicode_db.c) in `unicode_db.c` in moar:

```
static const MVMint32 uni_seq_2660[] = {2,0x26A7,0xFE0F}; /* TRANSGENDER SYMBOL */ /*Basic_Emoji */
```

So it's unicode character name vs emoji sequence, can be confusing at times. Possibly not a bug.

**Comment by lizmat** [comment]
That explains!
