### ISSUE TITLE
Migrate https://github.com/perl6/rakudo.org over to https://github.com/rakudo/rakudo.org

### ISSUE THREAD

**Issue by AntonOks** [rakudo/rakudo#4010]
move the source code of the [rakudo web site](https://rakudo.org/), which is currently in the [perl6 organization](https://github.com/perl6/rakudo.org) (btw., why wasn't this renamed to raku already?!?) to a new repo https://github.com/rakudo/rakudo.org

**Comment by lizmat** [comment]
I've moved it to https://github.com/raku/rakudo.org for now at least, because I could.

**Comment by AntonOks** [comment]
> I've moved it to https://github.com/raku/rakudo.org for now at least, because I could.

Thanks @lizmat! From your point of view, whould it (also) make sense to have it in `https://github.com/rakudo/` finally? And if so, to whom do we need to talk?

**Comment by lizmat** [comment]
To someone with enough rights in rakudo.  Which I think is @jnthn and possibly others.

**Comment by AntonOks** [comment]
@lizmat @jnthn 

guess this can now be closed now, right? thanks to all the helping hands...
