### ISSUE TITLE
home page not found

### ISSUE THREAD

**Issue by ohmycloud** [rakudo/rakudo#4011]
## Home page not found

The [home page](https://rakudo.org/home) is not found when click the **House** icon.

## Expected Behavior

No 404 error

## Actual Behavior

```
404 - Page Not Found
The page you tried to access does not exist.
```

## Steps to Reproduce

click the  [House](https://rakudo.org/home) icon.

**Comment by Altai-man** [comment]
Hmm, https://github.com/perl6/rakudo.org/pull/52 ?
