### ISSUE TITLE
Can't create a signature in runtime with a given count differing from arity

### ISSUE THREAD

**Issue by yguillemot** [rakudo/rakudo#4014]
## The Problem
Calling Signature.new with any integer value for count gives an empty signature.
This is a problem when arity and count have to be different.

## Expected Behavior
Calling Signature.new(params => (...), count => 3, arity => 2) should return a Signature with 3 or more parameters, arity = 2 and count = 3.

## Actual Behavior
Calling Signature.new(params => (...), count => 3, arity => 2) returns an object Signature with 0 parameter, arity = 0 and count = (Num).

The preceding result is got whatever integer value count is set to.
If count is unspecified, the resulting signature has the given parameters and count = arity.
If count is set to Inf, the resulting signature has the given parameters, arity  = 2 and count = Inf.
There is no way to create a signature with count being finite and not equal to arity.

## Steps to Reproduce
The following script may be used :
```
my $p1 = Parameter.new(type => Int);
my $p2 = Parameter.new(type => Str);
my $p3 = Parameter.new(type => Int, default => 42);
my $p4 = Parameter.new(type => Int, name => ':$val');

my $s = Signature.new(
            params => ($p1, $p2, $p3, $p4),
            count => 3,
            arity => 2
        );

say $s;
say "arity = ", $s.arity;
say "count = ", $s.count;
```

## Environment
* Operating system: Linux Mageia 6 - Kernel 4.14.137 or Linux Mageia 8 Beta 1 - Kernel 5.9.3
* Compiler version (`perl6 -v` or `raku -v`):
This is Rakudo version 2020.01-114-gcfe2cdc56 built on MoarVM version 2020.01.1-33-g571c731ff
implementing Raku 6.d.
or
Welcome to Rakudo v2020.10.
Implementing the Raku programming language v6.d.
Built on MoarVM version 2020.10.

**Comment by vendethiel** [comment]
I think you have to call .Num explicitly

**Comment by yguillemot** [comment]
Thanks for your reply. You are right: calling .Num explicitly fixes my problem.
I should have guessed that count is a Num while setting it to Inf.
Moreover this is clearly written in the documentation.

I fall in that trap for two reasons :
* There is a wrong example in the documentation in the paragraph "Runtime creation of Signature objects" :
` Signature.new(params => (...), returns => Type, arity => 1, count => 1) `
* Weirdly the type returned by count depends of the way the signature was created :
` :().count.WHAT ` returns (Int)
` Signature.new.count.WHAT ` returns (Num)

I presume I have now to close this issue.
Do you think it's worth to open a new one related to the documentation ?
Anyway thanks again for your reply and my apologies for the noise.

**Comment by lizmat** [comment]
If you feel you were misled by the documentation, then indeed I think opening a documentation issue is in order.  Even better would be a Pull Request  :-)

**Comment by yguillemot** [comment]
I will try the pull request as soon as possible (I first have to learn how to do it...)

**Comment by yguillemot** [comment]
Pull Request Raku/doc #3690 done : _"Add a warning paragraph about type of arguments of Signature.new"_
