### ISSUE TITLE
`does` on an Int|Str affects other variables holding that Int|Str

### ISSUE THREAD

**Issue by nwc10** [rakudo/rakudo#4015]
##  The Problem

`$a` and `$b` are unrelated:

    my $a = 1;
    my $b = 1;
    $a does role { method Str() { "foo" } };
    $b.Str.say

## Expected Behavior

Should output `1` (well, d'oh!)

## Actual Behavior

Outputs `foo`

## Environment

Tested on

```
$ ./rakudo-m -v
Welcome to Rakudo(tm) v2020.10-59-g1321a8533.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.10-46-gafc076678.
```

but confirmed on both `rakudo-m` and `rakudo-j` on the [cameila IRC bot](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-11-09#l62)

The seemingly related bug for `my` *int* `$a = 1;` etc is MoarVM specific, and would be fixed by MoarVM/MoarVM#1379

**Comment by lizmat** [comment]
This behaviour is not limited to `Int`:

    my $a = "foo" does False;
    my $b = "foo";
    say $a.Bool;   # False
    say $b.Bool;   # False

Oddly enough, this does **not** extend to non-`Cool` types apparently:

    my $d = Date.today does False;
    my $e = Date.today;
    say $d.Bool;   # False
    say $e.Bool;   # True

even though `Date` is also a value type:

    dd Date.today.WHICH;  # ValueObjAt.new("Date|59166")

So I tried to fix this with adding a `Cool:D` candidate to `infix:<does>`

    multi sub infix:<does>(Cool:D \obj, Mu \role, |c) {
        die "Cannot use 'does' operator on Cool values, did you mean 'but'?";
    }

but that fails because Hashes are also `Cool` and I guess we are allowed to do a `does` on a Hash, as e.g. happens at https://github.com/rakudo/rakudo/blob/master/src/core.c/CompUnit/Repository/Installation.pm6#L491

**Comment by lizmat** [comment]
After figuring out the undesirable behaviour is only applicable to `Int` and `Str`, but **not** to other `Cool` objects, nor any other core objects (not even `Num`s), it was easy to add two candidates to `infix:<does>` that take care of this specific issue: https://github.com/rakudo/rakudo/commit/2f3de2faab

I'm not sure that is enough to close this ticket, as it does not address the underlying issue.  But it does prevent people from falling into this trap.

**Comment by lizmat** [comment]
Since one can no longer fall into this trap because of https://github.com/rakudo/rakudo/commit/2f3de2faabf9dbac2f21b38a5396bcd534e45fc1 I'm closing this issue.  Please re-open if you disagree.
