### ISSUE TITLE
Mixing in roles inside module with higher language version breaks

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4021]
Found while trying out my modules on 6.e.PREVIEW, golfed down to: create a module `lib/B.rakumod` with:

    use v6.*;  # effectively 6.e.PREVIEW atm
    role A { has $.a }
    42 but A("ten");

And then run:

    $ raku --ll-exception -Ilib -MB

you will get:

    Type object Int+{A} of v6.d is not compatible with A of v6.e

This appears to happen with a module doing 6.e.PREVIEW, and the consuming code doing anything less than 6.e.PREVIEW.

This basically means that it is currently not safe to upgrade a module to the latest version of Raku if it does any kind of mixins.

This is also visible with **massive** spectest breakage when putting a:

    use v6.e.PREVIEW;

in `lib/Test.rakumod`.

Full stack trace:

    Type object Int+{A} of v6.d is not compatible with A of v6.e
       at SETTING::src/core.c/Exception.pm6:62  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:103  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:101  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:100  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
     from gen/moar/Metamodel.nqp:262  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Metamodel.moarvm:check-type-compat)
     from gen/moar/Metamodel.nqp:3931  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Metamodel.moarvm:compose)
     from gen/moar/Metamodel.nqp:1667  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Metamodel.moarvm:generate_mixin)
     from gen/moar/Metamodel.nqp:1593  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Metamodel.moarvm:)
     from gen/moar/Metamodel.nqp:1619  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Metamodel.moarvm:mixin)
     from SETTING::src/core.c/operators.pm6:69  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:infix:<but>)
     from SETTING::src/core.c/operators.pm6:58  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:infix:<but>)
     from /Users/liz/Github/rakudo.moar/lib/B.rakumod (B):3  (/Users/liz/Github/rakudo.moar/lib/.precomp/5BF0B1BFB0D0ADF13708931D0F85FDAA2C5DF499/AE/AE4F281DF5A5D0FF3CAD6371F76D5C29B6D953EC:<unit>)
     from /Users/liz/Github/rakudo.moar/lib/B.rakumod (B):1  (/Users/liz/Github/rakudo.moar/lib/.precomp/5BF0B1BFB0D0ADF13708931D0F85FDAA2C5DF499/AE/AE4F281DF5A5D0FF3CAD6371F76D5C29B6D953EC:<unit-outer>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/lib/.precomp/5BF0B1BFB0D0ADF13708931D0F85FDAA2C5DF499/AE/AE4F281DF5A5D0FF3CAD6371F76D5C29B6D953EC:<load>)
     from SETTING::src/core.c/CompUnit/Loader.pm6:51  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:load-precompilation-file)
     from SETTING::src/core.c/CompUnit/Loader.pm6:33  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:load-precompilation-file)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:94  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:load-handle-for-path)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:282  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:277  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:276  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:load)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:249  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:load)
     from SETTING::src/core.c/CompUnit/PrecompilationRepository.pm6:65  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:try-load)
     from SETTING::src/core.c/CompUnit/Repository/FileSystem.pm6:82  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
     from SETTING::src/core.c/CompUnit/Repository/FileSystem.pm6:76  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
     from gen/moar/World.nqp:1487  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:load_module)
     from gen/moar/World.nqp:1437  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:do_pragma_or_load_module)
     from gen/moar/World.nqp:822  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:comp_unit_stage1)
     from gen/moar/Grammar.nqp:840  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
     from gen/moar/Grammar.nqp:555  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
     from gen/moar/stage2/QRegex.nqp:2258  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2297  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2213  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:2248  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:2244  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:2240  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from gen/moar/stage2/NQPHLL.nqp:1915  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/Compiler.nqp:145  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Compiler.moarvm:interactive)
     from gen/moar/stage2/NQPHLL.nqp:2110  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from gen/moar/Compiler.nqp:106  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:2035  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/rakudo.nqp:127  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:MAIN)
     from gen/moar/rakudo.nqp:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<mainline>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<main>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<entry>)

**Comment by vrurg** [comment]
```
⇒ raku -v
Welcome to Rakudo(tm) v2020.10-85-gf87c84ccb.
⇒ raku -e 'use v6.*; role A { has $.a }; say (42 but A("aa")).WHICH'
Int+{A}|42
```

Are you sure you do it on the master?

**Comment by lizmat** [comment]
I'm on master, afaik:

    $ raku -v
    Welcome to Rakudo(tm) v2020.10-63-g08f5d028e.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2020.10-31-gb13f6a24c.

You appear to be ahead in your git describe?  08f5d028e *is* the last commit on master, afaik.

Also, the problem occurs if a pre-compiled *module* has a higher language version than the code in which the module is used.  And that still gives me:

    $ raku -Ilib -MB
    ===SORRY!=== Error while compiling:
    Type object Int+{A} of v6.d is not compatible with A of v6.e

Please note that:

     $ $ raku -Ilib -MB -e 'use v6.*'

is clean.

**Comment by vrurg** [comment]
Really, really weird. My describe is coming from the coercion branch, but I regularly rebase it onto master. Anyway, here is the pure master:

```
⇒ raku -v                                                                          11-11-20 14:49:51
Welcome to Rakudo(tm) v2020.10-63-g08f5d028e.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.10-31-gb13f6a24c.
⇒ raku -e 'use v6.*; role A { has $.a }; say (42 but A("aa")).WHICH'
Int+{A}|42
```

So, 6.e `A` do mixin into Int with no problem.

**Comment by vrurg** [comment]
Ok, I tried it in a module and, in fact, it does fail. No idea how is it possible other than different compiler versions are used for composing role `A` and the mixin class. Unfortunately, I'm not sure if will have time today to check my assumption.

**Comment by lizmat** [comment]
Don't worry, we still have some time before what we call 6.e.PREVIEW now will be released.  :-)

**Comment by vrurg** [comment]
Heh... I planned 6.e release to be closely following RakuAST release. No idea when this is gonna happen now... :(

**Comment by lizmat** [comment]
I wouldn't worry too much about that at this time  :-)

**Comment by vrurg** [comment]
BTW, a note on what's actually happening in this case. The module is compiled using 6.e, as it must. But the mixin is created at runtime, when script compiler is in charge. Thus, it tries to create a 6.d mixin class – and fails.

I'm now left with two options only: either lookup for `CORE-SETTING-REV` which means runtime context dependency which is way too unreliable as any change in invocation path can lead to, say, CORE.c to be the first client context to the metamodel layer.

Or, as I was thinking of it since the beginning, role's language revision must be used. This is ok when a mixin is created in the same language revision context to which the role belongs. But if it is exported into a lower language code which actually creates the mixin class then I have a feeling that some unexpected side effects could happen to the user.

**Comment by lizmat** [comment]
Hmmm... last I tried, the `Memoize` module's testing would break if I set the version in `lib/Memoize.pm6` to `v6.*`, and used `v6.d` in the test files.  Should that be fixed or not?

**Comment by lizmat** [comment]
Ah, I see #4046 got merged, will check if that's still an issue now.

**Comment by lizmat** [comment]
Indeed, problem solved!  @vrurg++
