### ISSUE TITLE
nmake test fails on Windows

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#4023]
## The Problem

I'm trying to build Rakudo in the "Developer Command Prompt for VS 2019". `perl Configure.pl --gen-moar --gen-nqp --backends=moar` was successful, `nmake` was successful, but `nmake test` fails.

## Test Summary Report

```
t\04-nativecall\11-cpp.t                                      (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 22 tests but ran 1.
t\04-nativecall\13-cpp-mangling.t                             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 26 tests but ran 0.
Files=109, Tests=1776, 138 wallclock secs ( 0.69 usr +  0.69 sys =  1.38 CPU)
Result: FAIL
NMAKE : fatal error U1077: 'C:\Strawberry\perl\bin\perl.exe' : return code '0x1'
Stop.
```

## Environment
* Operating system: Windows 10
* Compiler version (`.\install\bin\nqp --version`): This is nqp version 2020.10-64-g217d54151 built on MoarVM version 2020.10-31-gb13f6a24c

**Comment by Altai-man** [comment]
Hi. Is it a regression compared to previous releases?

**Comment by dumarchie** [comment]
@Altai-man, I don't know. This is the first time I'm building with msvc and it has been quite a while since I managed to build with gcc.

**Comment by dumarchie** [comment]
This is a bit of a long shot, but could it have something to do with ` is nativeconv('thisgnu')`?

**Comment by ugexe** [comment]
fwiw `nmake test` is green per https://ci.appveyor.com/project/rakudo/rakudo/branch/master/job/40v1k60fytqu35g9?fullLog=true#L1127

**Comment by dumarchie** [comment]
One obvious difference is that I have:

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.7
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
```

**Comment by dumarchie** [comment]
Running `nmake test` with `HARNESS_VERBOSE=1` gives the following error messages:

```
t\04-nativecall\11-cpp.t ........................................
1..22
ok 1 - sizeof(Derived1)
Cannot locate symbol '??0Derived1@@QEAA@XZ' in native library 'C:\raku\rakudo\11-cpp.dll'
  in method setup at C:\raku\rakudo\lib\NativeCall.rakumod (NativeCall) line 298
  in block new at C:\raku\rakudo\lib\NativeCall.rakumod (NativeCall) line 587
  in block <unit> at t\04-nativecall\11-cpp.t line 51

# You planned 22 tests, but ran 1
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 21/22 subtests
```

```
t\04-nativecall\13-cpp-mangling.t ...............................
1..26
Don't know how to mangle symbol 'Foo::new' for library 'C:\raku\rakudo\13-cpp-mangling.dll'
  in sub guess-name-mangler at C:\raku\rakudo\lib\NativeCall.rakumod (NativeCall) line 245
  in method setup at C:\raku\rakudo\lib\NativeCall.rakumod (NativeCall) line 288
  in block new at C:\raku\rakudo\lib\NativeCall.rakumod (NativeCall) line 587
  in block <unit> at t\04-nativecall\13-cpp-mangling.t line 57

# You planned 26 tests, but ran 0
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 26/26 subtests
```

**Comment by dumarchie** [comment]
In *11-cpp.dll* I found symbol `??0Derived1@@QAE@XZ` instead of symbol `??0Derived1@@QEAA@XZ` sought by *NativeCall.rakumod*.

In *13-cpp-mangling.dll* I found symbol `??0Foo@@QAE@XZ` so maybe *NativeCall.rakumod* is looking for `??0Foo@@QEAA@XZ` there?

**Comment by dumarchie** [comment]
If I change the order of `my @cpp-name-mangler` in *NativeCall.rakumod*, it still looks for `??0Derived1@@QEAA@XZ`, so it looks like `try cglobal($libname, mangler($r, $sym), Pointer)` in `sub guess-name-mangler(Routine $r, $name, Str $libname)` returns false for `&mangler := &NativeCall::Compiler::MSVC::mangle_cpp_symbol`.

**Comment by dumarchie** [comment]
Maybe the failing tests are caused by [C++ conformance improvements in Visual Studio](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/overview/cpp-conformance-improvements.md)?

**Comment by dumarchie** [comment]
The error messages are the same in the "Visual Studio 2017 Developer Command Prompt v15.9.29".

**Comment by dumarchie** [comment]
The problem goes away if I execute

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
```

before doing anything else in the Developer Command Prompt.

This kind of build dependency should be documented, for example in the [Platform specific notes](https://github.com/rakudo/rakudo/blob/master/CAVEATS.md)!

**Comment by ugexe** [comment]
I believe you need to use “x86 Native Tools Command Prompt for VS ...”, not “Developer Command Prompt for VS ...”

**Comment by dumarchie** [comment]
Thank you @ugexe, that indeed initializes the environment for 'x64' automatically.

**Comment by dumarchie** [comment]
The problem returns in the "x86 Native Tools Command Prompt for VS 2019".

**Comment by dumarchie** [comment]
The problem goes away again if I use the "Developer Command Prompt for VS 2019" and run `VC\Auxiliary\Build\vcvars64.bat` before doing anything else. So to build Rakudo on Windows one just has to follow a very specific recipe.

I will document the recipe.
