### ISSUE TITLE
Inconsistent flattening by push and unshift

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#4034]
##  The Problem

The flattening of multiple values by `sub push` and `sub unshift` is inconsistent with the flattening by the corresponding `Array` methods.

## Expected Behavior

If multiple values are passed, `push` and `unshift` should not flatten them.

## Actual Behavior

If multiple values are passed, `sub push` and `sub unshift` do flatten them.

## Steps to Reproduce

See the pull request I'll be offering to the [test suite](/Raku/roast)

**Comment by lizmat** [comment]
It is my understanding that `append` should flatten, and that `push` should not.

This is why there is an `append` and `prepend` in the first place.

@TimToady ran into this long ago, when `pop`ing an array from an array, and then `push`ing it to another array.  Before the GLR, that would flatten.  After the GLR with the single argument rule, that would also flatten.  That's when `append` and `prepend` came to be.

If we're doing it wrong now, I think we can only fix this in the next language version.

**Comment by dumarchie** [comment]
@lizmat, it is clearly documented that `append` follows the "single argument rule", while `push` does not. Neither of them should flatten.

And in any case, `sub push` should be consistent with `method push`. Currently it's not.

Fixing `sub push` and `sub unshift` does not break any spectest on my machine.

**Comment by lizmat** [comment]
I understand that it doesn't break any spectests.  Which indicate missing spectests as I apparently borked it last March  :-(

I just want to make 200% sure to find out what happened between the March commit and your PR, and why this wasn't caught before.

**Comment by dumarchie** [comment]
As far as I could see, nobody thought of asserting that `push(@array, b, c)` flattens neither `b` or `c`. All the non-flattening assertions only covered `multi sub push(\a, \b)`.
