### ISSUE TITLE
Trailing (#=) declarator blocks on attributes not attaching correctly when combined with defaults

### ISSUE THREAD

**Issue by m-dango** [rakudo/rakudo#4036]
## The Problem
When an attribute is given a non-basic default (e.g. `= 1` is fine, `= do 1` is not), the trailing declarator block must come before the semicolon to end the statement, else the block will not attach correctly.

### Code
```raku
unit class Foo;

#| leading
has $.basic = 1;
#= trailing

#| leading
has $.ternary1 = 1 ?? 1 !! 0
#= trailing
;

#| leading
has $.ternary2 = 1 ?? 1 !! 0;
#= trailing

for Foo.^attributes(:local) {
  say "\n" ~ .name;
  given .WHY {
    .leading.say;
    .trailing.say;
  }
}
```

### Output
```
$!basic
leading
trailing

$!ternary1
leading
trailing

$!ternary2
leading
Nil
```

### More Examples
https://repl.it/@mienaikage/WorthlessBelovedScandisk#main.raku

## Environment
2020.07 and 2020.10 on Ubuntu

**Comment by melezhik** [comment]
I rakuplayed it - http://rakudist.raku.org/sparky/report/RakuPlay-3/1545 , soo n I want to add rebuild for commit feature so no need will be to copy/paste an example to run it for new commits.

http://rakudist.raku.org/sparky/report/RakuPlay-3/1545

**Comment by lizmat** [comment]
Closing in light of https://github.com/Raku/problem-solving/issues/438
