### ISSUE TITLE
Segfault depends on order of use statements [SO64837072]

### ISSUE THREAD

**Issue by librasteve** [rakudo/rakudo#4038]
viz. https://stackoverflow.com/questions/64837072/should-i-get-a-raku-segfault-depending-on-order-of-use-statements
and lizmat suggestion to raise an issue with my Physics::Unit / Physics::Measure modules,

## The Problem
I would like users of the modules to be able to write their use statements in any order. However, if they use Physics::Measure first, I either get a SegFault. Or slightly better I have been able to pin down to this error:

## Expected Behavior
Runs without error

## Actual Behavior
Generally a segfault, this golfed version I have been able to coax out an error....
```
No such symbol 'Physics::Measure::Length'
  in sub do-postfix at /Users/stephenroe/Dropbox/ThreeMeasures/raku-Physics-Measure/bin/../lib/Physics/UnitAffixQ.rakumod (Physics::UnitAffixQ) line 14
  in sub postfix:<nm> at /Users/stephenroe/Dropbox/ThreeMeasures/raku-Physics-Measure/bin/../lib/Physics/UnitAffixQ.rakumod (Physics::UnitAffixQ) line 17
  in block <unit> at synopsis-unitaffixq.raku line 6 
```

## Steps to Reproduce
I have created a new branch 'SO64837072' of raku-Physics-Measure on GitHub to help Reproduce this setup, please go:
```
 zef install Physics::Unit
 or zef install https://github.com/p6steve/raku-Physics-Unit.git
    git clone git clone https://github.com/p6steve/raku-Physics-Measure.git
    git checkout SO64837072
    cd raku-Physics-Measure/bin
    ./synopsis-unitaffixq.raku
```

## Environment
* Operating system: macOS Catalina 10.15.7
* My kit: Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.10. Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d. Built on MoarVM version 2020.10.

**Comment by MasterDuke17** [comment]
I was able to repro, and a MoarVM and Rakudo backtrace are here https://gist.github.com/MasterDuke17/1ca3751839081a8ffb1126e4113a65e5

**Comment by niner** [comment]
On Dienstag, 17. November 2020 09:16:38 CET MasterDuke17 wrote:
> I was able to repro, and a MoarVM and Rakudo backtrace are here
> https://gist.github.com/MasterDuke17/1ca3751839081a8ffb1126e4113a65e5

I guess tc->instance->all_scs[sc_idx] is NULL there? Does look sc_idx sane 
(i.e. a smallish number)? I bet it doesn't. So there's probably junk in the 
worklist. You can watch -l on the object's sc_idx to see where it get's 
overwritten (probably GC though) and the slot in the worklist to see where the 
object comes from (which may be a place that's missing an MVMROOT). Then let 
rr reverse-cont and watch the magic :)

**Comment by MasterDuke17** [comment]
> I guess tc->instance->all_scs[sc_idx] is NULL there? Does look sc_idx sane (i.e. a smallish number)?

```
(rr) p sc_idx
$2 = 4045642928
(rr) p tc->instance->all_scs[sc_idx]
Cannot access memory at address 0x557776dd6b10
```

**Comment by p6steve** [comment]
Hi - this is all a bit hardcore for me. At the module source level I would mention that Physics::Unit predefines about 250 objects like so

Unit.new( factor => 0.01, offset => 0, defn => '1/100', type => '',
	  dims => [0,0,0,0,0,0,0,0], dmix => ().MixHash, 
	  names => ['%','percent','percents'] , stock => True  );

so there might be quite a lot of resources consumed in the compiler / garbage collection. I do this in a longhand way (as opposed to parsing definition files in the Grammar) to speed up compile time.

**Comment by raiph** [comment]
> Let me know if there's anything I can do to help!!

Since you've got reproducibility sorted, and a reproduction, and an initial look by niner, I'd say it's time to focus back on golfing, but this time golfing the modules, not the program.

**Comment by p6steve** [comment]
@raiph 

> Since you've got reproducibility sorted, and a reproduction, and an initial look by niner, I'd say it's time to focus back on golfing, but this time golfing the modules, not the program.

sure - that was the 'M' that I had in mind anyway (ie. get to Minimal in the modules) ... I'll need a 'day or three' for this...

**Comment by melezhik** [comment]
I reproduced it via RakuPlay, if it helps - https://rakudist.raku.org/sparky/report/RakuPlay-1/1522

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by melezhik** [comment]
Unfortunately can test this as my Rakuplay test has gone, maybe I will restore it, will take some time

**Comment by librasteve** [comment]
will check and revert in a couple of days

**Comment by librasteve** [comment]
ok - I have tried to rebuild the 2021 version of code stack to reproduce, but this is too hard

lesson is: always pin your deps

closing this issue
