### ISSUE TITLE
Regression? Sequence of junctions wrapped in singleton lists

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#4039]
## The Problem

See https://www.nntp.perl.org/group/perl.perl6.users/2020/11/msg9338.html

"This seems to happen for any kind of junction, not just or-junctions."

## Expected Behavior

Same  as:
```
say $*PERL.version; # v6.d
say $*PERL.compiler.version; # v2018.12
say ({ 1 | -1 } ... *)[^3]; # (any(1, -1) any(1, -1) any(1, -1))
```
## Actual Behavior

```
say $*PERL.version; # v6.d
say $*PERL.compiler.version; # v2020.07
say ({ 1 | -1 } ... *)[^3]; # ((any(1, -1)) (any(1, -1)) (any(1, -1)))
```

**Comment by lizmat** [comment]
Confirmed, bisected to https://github.com/rakudo/rakudo/commit/e1aaa83cc1e28586d3a273b7dd57742284a585fe .  Looking at a proper fix that won't lose the performance benefit that it brought.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/3e10cc6f8a

**Comment by melezhik** [comment]
i've added rkp for this if it helps - http://rakudist.raku.org/sparky/report/RakuPlay-1/1212

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/5aee10dfc3
