### ISSUE TITLE
[JVM] Failing test in S12-coercion/coercion-types.t after switch to new coercion semantics

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4040]
## The Problem
After the merge of https://github.com/rakudo/rakudo/pull/3891 a test in S12-coercion/coercion-types.t started to fail: https://github.com/Raku/roast/blob/861bc6c8d4/S12-coercion/coercion-types.t#L77-L84

The problem is not specific to arrays, but to assignment:
```
$ ./rakudo-j -e 'my Rat(Str) $foo = 42'
Type check failed in assignment to $foobar; expected Rat(Str) but got Int (42)
  in block <unit> at -e line 1
```

I suspect the problem to be in https://github.com/rakudo/rakudo/blob/3e10cc6f8a/src/Perl6/bootstrap.c/BOOTSTRAP.nqp#L1634. The call to ```.coerce``` two lines below is not reached, because the conditional evaluates to false.

[Aside: If I'm not mistaken, MoarVM takes a different path and doesn't hit this code (for this example) -- probably because assignment is handled differently.]

## Environment
* Operating system: FreeBSD 11.3-RELEASE-p6
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2020.10-104-g1f090e04d.
Implementing the Raku(tm) programming language v6.d.
Built on JVM.

**Comment by Altai-man** [comment]
Can this be fixed before release this weekend?

**Comment by usev6** [comment]
@Altai-man I hope @vrurg will find a way to fix it. But I wouldn't consider this a blocker -- given that the JVM backend isn't fully functional.

**Comment by vrurg** [comment]
There is no need to fix this because JVM behaves correctly in this case. It is a bug in MoarVM, actually because `Int !~~ Rat(Str)`. There is, actually, a proof for this: `my Rat $foo = 42`. The question is how far this erroneous behavior stretches back.

**Comment by vrurg** [comment]
One more check which do the right thing:

```raku
sub foo(Rat(Str) $v) {
    note $v.WHICH;
}
foo(1);
```

So, I wonder where exactly things go wrong with the assignment... O-o-okay...
