### ISSUE TITLE
[JVM] Failing tests in S06-currying/positional.t after switch to new coercion semantics

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4041]
## The Problem
After the merge of #3891 some tests in S06-currying/positional.t started to fail: https://github.com/Raku/roast/blob/861bc6c8d4/S06-currying/positional.t#L162-L166

A somewhat shortened code snippet from the first failing test:
```
$ ./rakudo-j --ll-exception -e 'my Int @AoI = 1,2; my $foo := sub (Str(Int) @a, Str(Int) @b) { }; dd $foo.assuming($@AoI)'
Method 'coerce' not found for invocant of class 'Perl6::Metamodel::CurriedRoleHOW'
  in trybind (EVAL_1:1)
  in <unit> (EVAL_1:1)
  in <unit-outer> (EVAL_1:1)
  in <anon> (gen/jvm/CORE.c.setting:57381)
  in EVAL (gen/jvm/CORE.c.setting:57374)
  in assuming (gen/jvm/CORE.c.setting:16397)
  in <unit> (-e:1)
  in <unit-outer> (-e:1)
  in eval (gen/jvm/stage2/NQPHLL.nqp:1216)
  in <anon> (gen/jvm/stage2/NQPHLL.nqp:1328)
  in command_eval (gen/jvm/stage2/NQPHLL.nqp:1325)
  in command_eval (gen/jvm/Compiler.nqp:116)
  in command_line (gen/jvm/stage2/NQPHLL.nqp:1309)
  in MAIN (gen/jvm/rakudo.nqp:133)
  in <mainline> (gen/jvm/rakudo.nqp:121)
  in <anon> (gen/jvm/rakudo.nqp)
```

## Environment
* Operating system: FreeBSD 11.3-RELEASE-p6
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2020.10-104-g1f090e04d.
Implementing the Raku(tm) programming language v6.d.
Built on JVM.

**Comment by Altai-man** [comment]
Can this be fixed before release this weekend? [2]

**Comment by usev6** [comment]
It looks like the ```.assuming``` can be golfed away:
```
$ ./rakudo-j --ll-exception -e 'my Int @AoI = 1,2; sub (Str(Int) @a) { 42 }($@AoI)'
Method 'coerce' not found for invocant of class 'Perl6::Metamodel::CurriedRoleHOW'
  in <anon> (-e:1)
  in <unit> (-e:1)
  in <unit-outer> (-e:1)
  in eval (gen/jvm/stage2/NQPHLL.nqp:1216)
  in <anon> (gen/jvm/stage2/NQPHLL.nqp:1328)
  in command_eval (gen/jvm/stage2/NQPHLL.nqp:1325)
  in command_eval (gen/jvm/Compiler.nqp:116)
  in command_line (gen/jvm/stage2/NQPHLL.nqp:1309)
  in MAIN (gen/jvm/rakudo.nqp:133)
  in <mainline> (gen/jvm/rakudo.nqp:121)
  in <anon> (gen/jvm/rakudo.nqp)
```

**Comment by usev6** [comment]
@Altai-man I'm looking, but I can't promise anything. I wouldn't consider this a blocker -- given that the JVM backend isn't fully functional.

**Comment by melezhik** [comment]
BTW It is not confirmed on RakuPlay for the mentioned Rakudo version - **v2020.10-104-g1f090e04d**

- http://rakudist.raku.org/sparky/report/RakuPlay-2/1303 - PASSED

**Comment by usev6** [comment]
@melezhik This only happens on the JVM backend. (Hence the label and the tag in the subject.) On MoarVM there is no problem.
