### ISSUE TITLE
REPL complaints about "useless" actions

### ISSUE THREAD

**Issue by vonbrand** [rakudo/rakudo#4057]
## The Problem
Delayed complaints for "useless" actions in REPL
## Expected Behavior
Silence (as before ;.)
## Actual Behavior
```
WARNINGS for <unknown file>:
Useless use of "(elem)" in expression "'a' (elem) @a" in sink context (line 2)
[a b c d]
```
## Steps to Reproduce

```
my @a = <a b c d>
'a' (elem) @a
say @a
```
## Environment
* Operating system: Fedora 33, x86_64
* Compiler version (`perl6 -v` or `raku -v`): v2020.11-25-g7c0a81f50

**Comment by vonbrand** [comment]
It seems this for logical expressions only. E.g., `eq` between values gives the same.

**Comment by lizmat** [comment]
Yep, a new nest of bugs introduced with 7c0a81f501d8956c  :-)   Working on a fix.

**Comment by lizmat** [comment]
Fixed with eae309a , thanks for the report!

**Comment by lizmat** [comment]
Sadly had to revert  eae309a with e46a1da29c

**Comment by melezhik** [comment]
I see this in RP - https://rakudist.raku.org/sparky/report/RakuPlay-2/1502 as well

**Comment by lizmat** [comment]
@melezhik: thanks, but there was no doubt about it being a problem.  In any case https://github.com/rakudo/rakudo/commit/f2851b9078 should fix that for most cases.  The one case it does *not* fix, is:

    $ raku 
    > 22;33
    WARNINGS for <unknown file>:
    Useless use of constant integer 22 in sink context (line 1)
    33
    > 66
    WARNINGS for <unknown file>:
    Useless use of constant integer 33 in sink context (line 1)
    66
    > 99
    WARNINGS for <unknown file>:
    Useless use of constant integer 33 in sink context (line 1)
    99

Note that it will keep repeating the last warning for each statement that does not write to STDOUT themselves.  But I find that to be a case of DIHWIDT.  So closing this issue again.

**Comment by melezhik** [comment]
Oh, I see. Thanks for the clarification. I just thought it was started as
REPL only issue ))) so decided to show an example of regular code.
