### ISSUE TITLE
EVAL documentation uses misleading example

### ISSUE THREAD

**Issue by doomvox** [rakudo/rakudo#4061]
The documentation for string evals:

    https://docs.raku.org/routine/EVAL

Has an example that seems confused:

    use MONKEY-SEE-NO-EVAL;  
    EVAL "say { 5 + 5 }";   # OUTPUT: «10␤»

It is true that that outputs 10, but it does it because the
double-quotes do interpolation of the block, executing { 5 + 5 }
before it gets to the EVAL.

This form doesn't work at all:

    EVAL 'say { 5 + 5 }'; 

Because actually this doesn't work:

   say { 5 + 5 };

Though this *does* work, because once again the double-quotes are
doing the magic, not the EVAL:

   say "{ 5 + 5 }";

I'm not sure what a really good example of EVAL would be.
Looking through my old test scripts, I see this was the first
thing I tried with it:

   use MONKEY-SEE-NO-EVAL;
   my $c = 'say "hello"';
   EVAL( $c );

**Comment by melezhik** [comment]
I tried to express @doomvox ideas through a RP - https://rakudist.raku.org/sparky/report/RakuPlay-1/1541

**Comment by JJ** [comment]
Checking it out. Thanks!

**Comment by Altai-man** [comment]
>I'm not sure what a really good example of EVAL would be

I am not sure about a really good one either, maybe because EVAL is always a bit smelly, but why not just `EVAL 'say 5 + 5'`? :)
