### ISSUE TITLE
Accept Mu as cas target

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#4066]
##  The Problem

The `cas` routine does not accept a target of type `Mu`. For example:

```
{
    CATCH { default { put .^name, ': ', .Str } }
    my Mu $var;
    my \seen = cas $var, Mu, Mu.new;
    put seen.raku;
}

{
    CATCH { default { put .^name, ': ', .Str } }
    my Mu $var;
    my \updated = cas $var, { Mu.new };
    put updated.raku;
}
```

## Expected Output

```
Mu
Mu.new
```

## Actual Output

```
X::TypeCheck::Binding::Parameter: Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)
X::TypeCheck::Binding::Parameter: Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)
```

## Environment
* Operating system: Windows 10
* Compiler version (`raku -v`): This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.

**Comment by dumarchie** [comment]
I will cover this in the spectest if the PR is accepted.

**Comment by niner** [comment]
> ##  The Problem
> 
> The `cas` routine does not accept a target of type `Mu`. For example:

Why is this actually a problem? Where does one need to use Mu as target of 
cas, i.e. what does the use case look like?

**Comment by dumarchie** [comment]
My use case is a concurrent stack implementation that should be able to store any value. I noticed the current limitation while working on an elimination buffer that uses `cas` to store pushed values or the `constant Absent = Mu.new`.
