### ISSUE TITLE
inescapable 'Redeclaration of symbol' warnings in the REPL

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#4077]
## The Problem

Declaring a variable twice with `my` in the REPL produces `Redeclaration of symbol` warnings after every single instruction afterwards. Surely this is not the intended behavior..

## Expected Behavior

Perhaps one warning, and silence afterwards. 

## Actual Behavior

The warning in the title on *every* instruction run after the reassignment attempt.

## Steps to Reproduce

Session in the `perl6` REPL:

```
> my $x=1
1
> my $x=1
Potential difficulties:
    Redeclaration of symbol '$x'.                        
    at line 3
    ------> my $x⏏=1
1
> 42
Potential difficulties:                                  
      Redeclaration of symbol '$x'.
      at line 3
      ------> $ = my $x⏏=1;
42
>
```
Notice how a call to `42` (nothing to do with `$x`) still issues the complaint. I have to explicitly run `$x=Any` (or quit the REPL..) to escape.

## Environment
* Operating system: `Ubuntu 20.04.1 LTS` (so `Linux` on `x86_64`)
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo(tm) v2020.11-59-g3d8e942f0.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11-47-g1c7358004
```

## Comment

This appears to be relatively new behavior: I'm in the REPL all the time, and used to be able to redeclare with `my` repeatedly with no issue.

**Comment by lizmat** [comment]
Yeah, my work on fixing some issues with the REPL has created a new nest of issues.  :-(

Will look at this after finishing the RWN.

**Comment by stuart-little** [comment]
Good to know it wasn't just me bungling things :). Thanks!
