### ISSUE TITLE
shell output pollutes subsequent command output in REPL

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#4079]
## The Problem

In the REPL, running the `.f` method on a file after having run `shell("file <file>")` keeps displaying the `shell` output. 

## Expected Behavior

Simply display a boolean (`True` or `False`) upon calling `<file>.IO.f`. 

## Actual Behavior

Displays the boolean *after* also showing the output of the previously run `shell` command. 

## Steps to Reproduce

Start the REPL in a directory where you have an empty file, say `file.txt`. My session:

```
> shell("file file.txt")
file.txt: empty
Proc.new(in => IO::Pipe, out => IO::Pipe, err => IO::Pipe, exitcode => 0, signal => 0, pid => 461510, command => ("file file.txt",))
> "file.txt".IO.f
file.txt: empty
True
> "file.txt".IO.f
file.txt: empty
True
>
```
Notice how the line `file.txt: empty` (returned by the initial `shell` command) keeps reappearing, even though it is not part of the output of the `.f` call (*that* output is just a boolean). 

This behavior is not confined to calling file-check methods on that specific file. Note (I was in a directory called `tmp/`):

```
> "../tmp/".IO.d
file.txt: empty
True
> "boo".IO.e
file.txt: empty
False
```
This ends after erroring out at least once: 
```
> "boo".IO.f
file.txt: empty
Failed to find '<HOME>/tmp/boo' while trying to do '.f'
  in block <unit> at <unknown file> line 7
> "boo".IO.e
False
```
That extraneous line is gone now. 

## Environment
* Operating system: `x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo(tm) v2020.11-65-g260f01588.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11-47-g1c7358004.
```

**Comment by Altai-man** [comment]
My gut feeling is that patching this won't go too well. I think we should probably go back to old behavior and keep the original REPL ticket as a reference to the time when we have more resources to do a very from ground re-design of how REPL works.

**Comment by lizmat** [comment]
I'm not ready to give up on this just yet...

So we need a way to find out if the REPL shelled out to an external process, and then reset the internal buffer.

**Comment by Altai-man** [comment]
I would not say this is a "giving up", more of a tactical retreat approach to re-group.

**Comment by lizmat** [comment]
Understood.  :-)
