### ISSUE TITLE
infix:<\> not recognized in Rakudo 2020.11 on macOS

### ISSUE THREAD

**Issue by markjreed** [rakudo/rakudo#4093]
## The Problem
Infix `\` is not recognized

## Expected Behavior
`\` should function as a set-difference operator

## Actual Behavior
```
===SORRY!=== Error while compiling:
Confused
expecting any of:
        infix
        infix stopper
        postfix
        statement end
        statement modifier
        statement modifier loop
```
## Steps to Reproduce

raku -e 'say <1 2 3> (-) <1 3>' # works
raku -e 'say <1 2 3> \ <1 3>' # errors

## Environment
* Operating system: macOS 10.15.7
* Compiler version (`perl6 -v` or `raku -v`): Rakudo v2020.11

**Comment by JJ** [comment]
Looks the same, but it's not the same: the actual character is [∖](https://docs.raku.org/language/operators#index-entry-Set_difference_operator)
![Captura de pantalla de 2020-12-06 09-47-18](https://user-images.githubusercontent.com/500/101275710-0d2cb800-37a8-11eb-981a-ad8e4c29d1e4.png)
See them side by side: `∖` and `\` They actually look more different in Fira Code, which is what I use in my terminal above.

**Comment by lizmat** [comment]
In your "steps to reproduce", `raku -e 'say <1 2 3> \ <1 3>' # errors` **is** actually a backslash.

On my MacOS (Mojave):

    $ raku -e 'say <1 2 3> ∖ <1 3>'
    Set(2)

**Comment by markjreed** [comment]
Yup, my mistake, I was using \ instead of ∖. Nothing to see here...

**Comment by lizmat** [comment]
No problem.  Glad it got cleared up!
