### ISSUE TITLE
Roles are not auto-punned for postcircumfix:<( )>

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4094]
This works as expected:

    class A {
        method CALL-ME(|c) { dd c }
    }
    A(42,666);  # \(42,666)

    role B {
        method CALL-ME(|c) { dd c }
    }
    B(42,666);  # Cannot invoke this object (REPR: Uninstantiable; B)
    (B.^pun)(42,666);  # \(42,666)

Seems to me some magic is missing to handle auto-punning in this situation, like would happen with:

    B.CALL-ME(42,666);  # \(42,666)

**Comment by vrurg** [comment]
I briefly checked it out. Looks like `Metamodel::ParametricRoleHOW` must consume `Metamodel::InvocationProtocol`. There is a problem though as invocation composition causes the role to pun immediately and the first defined role is composed before `Attribute` class is fully composed and ready to be used. Looks like some kind of late composition is needed.

**Comment by melezhik** [comment]
confirmation from RICH - http://rakudist.raku.org/sparky/report/RakuPlay-1/5087
