### ISSUE TITLE
Whatever star consumes non-auto-quoted fat arrow keys, but not auto-quoted ones

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#4100]
## The Problem
Whatever-star consumes non-auto-quoted fat arrow keys, but not auto-quoted ones:

```
dd Int => *.Int;
dd (Int) => *.Int;
```

## Expected Behavior
I expect both cases to behave similar, probably by not consuming the fat arrow operator
```
:Int(WhateverCode.new)
(Int) => WhateverCode.new
```

## Actual Behavior
```
:Int(WhateverCode.new)
WhateverCode.new
```

## Environment
```
Welcome to Rakudo(tm) v2020.11.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11.
```

**Comment by melezhik** [comment]
added to RICH - http://rakudist.raku.org/sparky/report/RakuPlay-2/4405

**Comment by lizmat** [comment]
I seem to remember this difference was intentional.  But I could be wrong, and definitely don't have an explanation for the current behaviour.

**Comment by lizmat** [comment]
Feels like this needs a problem solving issue.  Closing in favour of one.
