### ISSUE TITLE
Array.of throws on type objects

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#4104]
## The Problem
All of these work:
```
dd Positional.of
dd Positional[Str].of
dd Array[Str].of
```
But `Array.of` throws `Cannot look up attributes in a Array type object`. It should return `Mu` or `Any`.

## Environment
```
Welcome to Rakudo(tm) v2020.11.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11.
```

**Comment by lizmat** [comment]
if the PR is the right approach, this will have to be done for the `returns`, `name` and possibly other methods as well.

**Comment by Leont** [comment]
> if the PR is the right approach, this will have to be done for the returns, name and possibly other methods as well.

Yeah, that makes sense

**Comment by melezhik** [comment]
Added to RICH - http://rakudist.raku.org/sparky/report/RakuPlay-2/4803

**Comment by Leont** [comment]
This has been fixed in the mean time
