### ISSUE TITLE
weird characters in repl welcome message on windows 

### ISSUE THREAD

**Issue by shishini** [rakudo/rakudo#4109]
Where I start the latest rakudo star on windows I get weird characters in the welcome message 

`PS C:\Users\ali> raku
Welcome to ≡¥Éæ≡¥ÉÜ≡¥Éñ≡¥É«≡¥É¥≡¥É¿Γäó v2020.11.
Implementing the ≡¥Éæ≡¥ÉÜ≡¥Éñ≡¥É«Γäó programming language v6.d.
Built on MoarVM version 2020.11.`

**Comment by lizmat** [comment]
See https://github.com/rakudo/rakudo/issues/3986 and https://github.com/Raku/problem-solving/issues/193

**Comment by shishini** [comment]
No clue what happened,
I logged out and logged in back again, and now it looks good 


`PS C:\Users\ammselshishini> raku --version
Welcome to Rakudo(tm) v2020.11.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11.`

I
