### ISSUE TITLE
successive 'use' statements in the REPL error out with 'undeclared routine'

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#4115]
## The Problem

Calling `use` twice in the REPL results in an error. 

## Expected Behavior

Return `nil` after calling `use` on a present module.

## Actual Behavior

Return `undeclared name` and `undeclared routine` errors.

## Steps to Reproduce

Full REPL session:

```
> use MONKEY
Nil
> use MONKEY
===SORRY!=== Error while compiling:
Undeclared name:
    MONKEY used at line 1
Undeclared routine:
    use used at line 1 (in Raku please use "v" prefix for pragma (e.g., "use v6;", "use v6.c;") instead)
```

## Environment
* Operating system: `x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo(tm) v2020.11-136-g1639c7877.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11-85-g82a34e25a.
```
**Additional comments:**
This is not specific to `MONKEY`, as illustrated above. *Any* two successive `use` commands result in essentially the same behavior, as far as I have been able to test.

Calling `use v6` *after* another `use`, for instance, returns the complaint
```
===SORRY!=== Error while compiling:
Too late to switch language version. Must be used as the very first statement.
at line 2
------> use v6⏏<EOL>
``` 
But in any case, the point is there's still an error on the second call to `use`.

**Comment by Altai-man** [comment]
The MONKEY error is a regression.
The "Too late to switch language version" message is totally valid, though, IMO.

**Comment by stuart-little** [comment]
Ah, that's a good point. That behavior is consistent, and unrelated to the double `use`"

```
> 3
3
> use v6;
===SORRY!=== Error while compiling:
Too late to switch language version. Must be used as the very first statement.
at line 2
------> use v6⏏;
```
So you're right: I take back the part about the `switch language version` error. This just leaves the original matter then.

**Comment by lizmat** [comment]
Fixed for now with https://github.com/rakudo/rakudo/commit/be455078cf to make it for the 2020.12 release.
