### ISSUE TITLE
Alpine linux install failing

### ISSUE THREAD

**Issue by GaboFDC** [rakudo/rakudo#4125]
## The Problem
Not 100% sure if this is the place to report. But seems like since the rakudo package was moved from testing to community on alpine linux, the dependencies are broken or something of those sorts.

## Expected Behavior
Should be able to install rakudo normally

## Actual Behavior

We get some kind of dependency error

Adding or removing the testing repo makes no difference.

## Steps to Reproduce

1) Run the container:

`podman run --rm -it python:alpine sh

2) try to install rakudo:

When trying to install it under python:alpine i get:

```
# apk add rakudo
ERROR: unsatisfiable constraints:
  rakudo (missing):
    required by: world[rakudo]
# 
```

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

**Comment by Altai-man** [comment]
Is there a way in Alpine to get to know who maintains this package? `rakudo` package depending on `rakudo` package seems like a maintainer problem, not something compiler devs canresolve.

**Comment by GaboFDC** [comment]
Yeah, I think is maintained by @CurtTilmes 
I think I saw he also contributed here, so that's why I decide to open the issue, but you are right, and is not really related to the development of it.

**Comment by CurtTilmes** [comment]
python:alpine is based on alpine v3.12 which doesn't have rakudo yet -- it is only in edge.  You can use image alpine:edge for now, or wait for v3.13.

**Comment by GaboFDC** [comment]
I tested on alpine:edge and it works fine. But is this a recent change? because this was working previously, adding the testing repo from alpine.

**Comment by CurtTilmes** [comment]
It was recently moved from testing to community.  It works for me in image `python:alpine` if I add the edge/community repository.  (It is no longer in edge/testing so it will no longer find it there)

**Comment by GaboFDC** [comment]
I was confused between the normal `community` and the `edge/community` thanks.
