### ISSUE TITLE
my %hash; my %n = |%hash<>:p.map({ .key => .value }); dies with internal error

### ISSUE THREAD

**Issue by xinminglai** [rakudo/rakudo#4132]
## The Problem

When we run

`my %hash; my %n = |%hash<>:p.map({ .key => .value });`

script dies with error MVMArray: Can't pop from an empty array

## Expected Behavior

It should work be the same as `my %hash; my %n = |(%hash<>:p.map({ .key => .value }));`

## Actual Behavior

dies with error `MVMArray: Can't pop from an empty array`

## Environment
* Operating system: Debian (bullseye)
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.
```

**Comment by lizmat** [comment]
I think the code example does not express what you want because of precedence issues.  Did you in fact mean:

    my %hash; my %n = |(%hash<>:p).map({ .key => .value });

If that's the case, then please use the extra parens and it will run fine.

Meanwhile, the original example shouldn't throw like that, so looking into that.

**Comment by lizmat** [comment]
Turns out this is actually a compilation problem deep in NQP land.  Golfed it to:

    $ raku --ll-exception -e 'my %h; |%h<>:p.map: *.say'
    ===SORRY!===
    MVMArray: Can't pop from an empty array
       at gen/moar/stage2/NQPHLL.nqp:1381  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:EXPR_reduce)
     from gen/moar/stage2/NQPHLL.nqp:1354  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
     from gen/moar/Grammar.nqp:3758  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:EXPR)
     from gen/moar/Grammar.nqp:962  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
     from gen/moar/Grammar.nqp:890  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
     from gen/moar/stage2/NQPHLL.nqp:1465  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:LANG)
     from gen/moar/Grammar.nqp:1342  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
     from gen/moar/Grammar.nqp:838  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
     from gen/moar/Grammar.nqp:553  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
     from gen/moar/stage2/QRegex.nqp:2258  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2298  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2214  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:2249  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:2245  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:2241  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from gen/moar/stage2/NQPHLL.nqp:1916  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:2056  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:2111  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from gen/moar/Compiler.nqp:109  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:2036  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/rakudo.nqp:127  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:MAIN)
     from gen/moar/rakudo.nqp:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<mainline>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<main>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<entry>)

This feels like someone more knowledgeable about these NQP internals should look at this.  @jnthn @pmichaud

**Comment by salortiz** [comment]
Minimal golf: raku -e 'my %h;  |%h{}:p.Seq'

**Comment by lizmat** [comment]
A much clearer compile time error message:
```
% raku -e 'my %hash; my %n = |%hash<>:p.map({ .key => .value });'
===SORRY!=== Error while compiling -e
Cannot determine the destination for adverb: :p
Try placing parentheses around the desired callsite to disambiguate.
at -e:1
------> my %hash; my %n = |%hash<>:p.⏏map({ .key => .value });
```
