### ISSUE TITLE
Can't use junctions in regexes

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#4136]
## The Problem
One can safely use a string inside a regex or a list of strings and they will DWIM, but when using a junction of strings it fails.

## Expected Behavior
I would expect
```
my @options = <a b>;
my $junction = any(@options);
$foo ~~ /$junction/;
```
to be equivalent to:
```
my @options = <a b>;
$foo ~~ /@options/;
```
## Actual Behavior
It will die with `This type cannot unbox to a native string: P6opaque, Junction`

## Environment
```
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.
```

**Comment by lizmat** [comment]
Did you really mean `my @options = "a"|"b";` ??  aka, a one element array with a `Junction` in it?  Or did you mean `my @options = "a", "b";` aka `my @options = <a b>;` ?

**Comment by Leont** [comment]
> Did you really mean my @options = "a"|"b"; ?? aka, a one element array with a Junction in it? Or did you mean my @options = "a", "b"; aka my @options = <a b>; ?

Oops, I updated it.

**Comment by raiph** [comment]
cf https://stackoverflow.com/a/53992397/1077672

**Comment by melezhik** [comment]
confirming the issue on the latest Rakudo -https://gist.github.com/melezhik/7bbddb2eddb6a1b473cf313032cb4ef2

**Comment by jubilatious1** [comment]
https://gist.github.com/melezhik/7bbddb2eddb6a1b473cf313032cb4ef2?permalink_comment_id=5235707#gistcomment-5235707

**Comment by melezhik** [comment]
confirming the issue is fixed as for v2024.09-105-g3d2f478b8 - https://sparky.sparrowhub.io/report/gh-melezhik-r3tool-openbugs/22724

**Comment by jubilatious1** [comment]
Not sure I agree with @Leont 's assessment here. 

The docs are very clear:

> Junctions are very special objects. They fall outside the [Any](https://docs.raku.org/type/Any) hierarchy, being only, as any other object, subclasses of [Mu](https://docs.raku.org/type/Mu). That enables a feature for most methods: autothreading. Autothreading happens when a junction is bound to a parameter of a code object that doesn't accept values of type Junction. Instead of producing an error, the signature binding is repeated for each value of the junction.

It really seems that the sort of change that @Leont  wants seems to be outside of the normal object hierarchy present within the Raku Language. This means to me that @Leont 's change might be better incorporated into a Module, perhaps @lizmat 's `eigenstates` module (https://raku.land/zef:lizmat/eigenstates).

@thoughtstream

**Comment by lizmat** [comment]
FWIW, making this work in a module is virtually impossible.

Also FWIW, a lot of people think the `eigenstates` module shouldn't exist.  I sorta agree, but instead of letting people start depending on Rakudo internals, I thought it would be better to wrap this in a module.  That at least would give people a chance to survive any internals changes (if they were followed up by a module update, of course).

**Comment by thoughtstream** [comment]
I can understand why @Leont might find it reasonable and useful for interpolated disjunctions 
to act like regex disjunctions. I find it reasonable and useful myself.

However, that interpolation behaviour would not be consistent with the behaviour
of junctions when they are interpolated in other interpolating contexts. 

Consider:
```raku
    my @options = <a b>;
    my $junction = any(@options);
    $foo = qq/the $junction string/;
```

Here the interpolation of a junction into a string creates a junction of interpolated strings, 
equivalent to:
```raku
    $foo = any(qq/the a string/, qq/the b string/);
```

Likewise, interpolating a junction into a quoted word list:
```raku
    my @options = <a b>;
    my $junction = any(@options);
    $foo = qqw/the $junction string/;
```
...creates a junction of interpolated quoted-word lists, 
equivalent to:
```raku
    $foo = any(("the", "a", "string"), ("the", "b", "string"));
```

Likewise, interpolating a junction into a shell call:
```raku
    my @options = <a b>;
    my $junction = any(@options);
    $foo = qqx/cat $junction/;
```
...creates a junction of interpolated shell-call results, 
equivalent to:
```raku
    $foo = any("contents\n of\n file\n a\n", "contents\n of\n file\n b\n");
```

So I would argue that, if junctions were allowed to be interpolated into regexes at all,
then they should produce a junction of interpolated regexes. Thus:
```raku
    my @options = <a b>;
    my $junction = any(@options);
    $foo ~~ /$junction/;
```
...should be equivalent to:
```raku
    $foo ~~ any(/a/, /b/);
```

Of course, in that case, the outcome would be the same as for @Leont's proposed semantics
(even though the underlying mechanism leading to that outcome would be quite different).

The real issue with making `any('a', 'b')` interpolate as `a|b` in a regex is:
what do you do when the interpolated junction is `all('a', 'b')`, or `one('a', 'b')`, or `none('a', 'b')`? 

And, even more of a challenge, what do you do if the junction is: `all(any('a', 'b'), none('b', 'c'), one('a', 'c'))`?

But if interpolating a junction into a regex just produces a junction of interpolated regexes 
(by analogy to `qq` interpolation), then even that complex nested final example is simple(-ish), 
being merely the equivalent of:
```raku
    $foo ~~ all(any(/a/, /b/), none(/b/, /c/), one(/a/, /c/));
```

So, in my opinion, if we were to allow junctions to be interpolated into regexes at all 
(and I'm still not certain we should), then they probably interpolate in a manner 
consistent with how they interpolate into strings, wordlists, or shell-quotes:
interpolating a junction into a regex should create a junction of interpolated regexes.

**Comment by lizmat** [comment]
@thoughtstream 
> Of course, in that case, the outcome would be the same as for @Leont's proposed semantics

The semantics are already implemented and in the 2024.10 release.

> what do you do when the interpolated junction is all('a', 'b'), or one('a', 'b'), or none('a', 'b')?

These are currently not allowed:
```
% raku -e 'my $a = all(<a b>); "a" ~~ / $a /' 
Interpolation of 'all' junction is not supported
```
Same for `one` and `none`

**Comment by Leont** [comment]
> However, that interpolation behaviour would not be consistent with the behaviour of junctions when they are interpolated in other interpolating contexts.

That makes sense if you see regexes as more string-like, but does not if you see them as more code-like. My argument is essentially that they should be code-like, because regexes are fundamentally code.

**Comment by raiph** [comment]
For the specific case of "any" semantics I stand by my first comment in this thread, written in 2021. But I've no idea if anyone paid attention to it. To save a scroll/click, it was a link to the following SO question, and my answer, both written in 2019:

>> [How to use junction inside a perl6 regex interpolation?](https://stackoverflow.com/questions/53992260/how-to-use-junction-inside-a-perl6-regex-interpolation)
>>
>> Sometimes I have a long list and I would like to check whether a string matches anything in the list. ...
>
> **Use a list, not a Junction.**

**Comment by lizmat** [comment]
> Use a list, not a Junction.

Indeed, if you are in complete control, yes.

However, if you're not, e.g. in a module that uses some regex logic internally, you may receive a `Junction` as an argument to that routine.  With the change in 2024.10, as a module author you no longer have to special case such an occurrence, but you can safely interpolate that into the regex.

**Comment by raiph** [comment]
@Leont 

>> However, that interpolation behaviour would not be consistent with the behaviour of junctions when they are interpolated in other interpolating contexts.

> That makes sense if you see regexes as more string-like, but does not if you see them as more code-like.

I see _Raku_ regexes as code-like, and I'd be shocked if @thoughtstream did not too.

When I originally considered this question in 2019, and then again when I saw you had raised it again in 2020, my thought process was similar to that in @thoughtstream's recent comment (though without their vigor or rigor), and when I considered it I was thinking of the mooted interpolation as being interpolation of something into code, where the something could be a string, but could also be code.

As a thought experiment, what do you think the following code should do, and why?:
```
my @inner-regex = / . /, / b /;
my $any-junction = any @inner-regex;
my $any-junction = all @inner-regex;
say 'abc' ~~ / a   $any-junction   c /;
say 'abc' ~~ / a   $all-junction   c /;
```

**Comment by raiph** [comment]
@lizmat 

Yes, but my conclusion was partially tied to considering only the specific case of an "any" junction.

If we're going to address the case of not being in enough control of the variable to know what one is getting, then I would think we need to consider the other kinds of junctions.

As a starting point, consider the thought experiments in @thoughtstream's comment, and then stretch a bit further to the one in my last comment (interpolating a junction of regexes into a regex rather than a junction of strings into a regex; and doing so for either an _any_ or an _all_ junction), and then stretch further to interpolate a _none_ or _one_ junction (and then combine these experiments with @thoughtstreams's nested junction thought experiments).

Those were the kinds of mental gymnastics I did in 2019.

(And, FWIW, my conclusion at the time was that, if someone wanted this for just _any_ of just _strings_, then "Just use a list" was probably the best answer, all things considered.)

**Comment by lizmat** [comment]
FWIW, I'd welcome the use of other types of junctions in regexes as well.

There's only one practical issue with it (after we're worked out the semantics): the regex engine is 99.5% written in NQP, and Junctions are a HLL (Rakudo) construct falling out of the type hierarchy of `Junction` not being `Any`.

So either we'd have to move the concept of Junctions to NQP, or we will need to rewrite the regex engine in Raku.  I'd say the latter has more chance of being successful and more future proof.

**Comment by melezhik** [comment]
> the regex engine in Raku.
Maybe silly question - will it have performance penalty then ?

**Comment by jubilatious1** [comment]
@thoughtstream wrote:
> The real issue with making `any('a', 'b')` interpolate as `a|b` in a regex is: what do you do when the interpolated junction is `all('a', 'b')`, or `one('a', 'b')`, or `none('a', 'b')`?
> 
> And, even more of a challenge, what do you do if the junction is: `all(any('a', 'b'), none('b', 'c'), one('a', 'c'))`?

My concerns exactly: `any` *might* work conceptually, however another Junction (`all`) makes little sense. 

Actually, does `any` work, conceptually? Raku has already DWIMmied the use of \@-sigiled Arrays within Regexes by having them default to LTM (Longest Token Matching). @raiph graciously showed how to get "First-Matching" semantics in his SO post. But since Arrays do Positional a new user might expect "First-Matching" semantics by default, and the same for Junctions within Regexes. Of course there are ways to address this (e.g. sort your Array elements by `chars`), but that's another topic.

Other issues:
1. Another (unaddressed?) issue is what to do if your Junction is actually comprised of Regexes? 
2. Backtracking? How is that supposed to work?

@lizmat 
@Leont

**Comment by jubilatious1** [comment]
@raiph wrote:
> > Use a list, not a Junction.
> 
@lizmat wrote:
> Indeed, if you are in complete control, yes.
> 
> However, if you're not, e.g. in a module that uses some regex logic internally, you may receive a `Junction` as an argument to that routine. With the change in 2024.10, as a module author you no longer have to special case such an occurrence, but you can safely interpolate that into the regex.

I've not run into this issue, but I **can** see it being relevant. However here's a thought from a StackExchange answer I wrote:

https://unix.stackexchange.com/a/767403/227738

When you try to use a \%-sigiled hash in a Regex matcher, you get the error: ["The use of hash variables in regexes is reserved](https://docs.raku.org/language/regexes#Regex_interpolation)."

So, if you are presented with a hash and/or you are **not** in complete control and are given a hash, you `@`-coerce to an Array and you're done:

```raku
s:g/@(%h.keys)/%h{$/}/;'
```

So why not the same thing with a Junction? 
```raku
[0] > my @options = <a b>;
[a b]
[1] > say "a"  ~~ /@options/;
｢a｣
[1] > my $junction = any(@options);
any(a, b)
[2] > say "a"  ~~ $junction;
True
[2] > say "a"  ~~ /$junction/;
This type cannot unbox to a native string: P6opaque, Junction
[2]  > say "a"  ~~ /@$junction/; #hoped for solution
｢a｣
```

@thoughtstream 
@Leont

**Comment by lizmat** [comment]
> you @-coerce to an Array and you're done: `s:g/@(%h.keys)/%h{$/}/;'` So why not the same thing with a Junction?

This is essentially how interpolation of `any` junctions is now implemented.
