### ISSUE TITLE
Variable names support UTF-8 characters.

### ISSUE THREAD

**Issue by fenginsc** [rakudo/rakudo#4144]
Hello, raku team, can you support UTF-8 for variable names. Although this is not necessary, most languages currently support this feature. I wonder if raku can also add this feature?

**Comment by niner** [comment]
It already does. Identifiers (such as variable names) consist of Unicode General Category value Letter (L), the underscore Unicode General Category value Number, Decimal Digit (Nd).

See the documentation on Ordinary Identifiers:
https://docs.raku.org/language/syntax#Ordinary_identifiers

**Comment by fenginsc** [comment]
@niner 
Sorry, what I want to say is that REPL does not support variable names with UTF-8 characters.
My environment is Windows 7 x86_64.

**Comment by lizmat** [comment]
Can you use UTF-8 characters in a string in the REPL?

**Comment by JJ** [comment]
It's very likely that it's the console program that does not support UTF-8.
I can create variables with UTF-8 characters from a shell open as an emacs
buffer alright. My console supports them, also, I use Fira code for it.

**Comment by fenginsc** [comment]
@lizmat @JJ
I think it should be the problem of Windows 7 operating system. It is impossible to input UTF-8 characters under CMD.
I'll try again when I have time to change the windows 10 operating system.
