### ISSUE TITLE
Compiling a v6.c only version

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4155]
## The Problem

This fully belongs into the category of "Why would anyone want to do this?", but also, well, it might be interesting to do and the tooling theoretically allows it so I thought it might work.

Basically what I did was to leave only "c" in the RAKU_SPECS file. Theoretically, that file seems to list the versions you want compiled, implying that every version by itself should be possibly compilable (with all the other versions below, of course).

## Expected Behavior

I should be able to obtain a rakudo executable that implements only the 6.c version

## Actual Behavior

Goes mostly well, but it fails here:

```text
+++ Compiling	rakudo-debug.moarvm
Cannot find method 'typed_panic' on 'BOOTStr': no method cache and no .^find_method
   at gen/moar/World.nqp:566  (/rakudo/blib/Perl6/World.moarvm:!check-version-modifier)
 from gen/moar/World.nqp:606  (/rakudo/blib/Perl6/World.moarvm:load-lang-ver)
 from gen/moar/Grammar.nqp:872  (/rakudo/blib/Perl6/Grammar.moarvm:lang-version)
 from gen/moar/Grammar.nqp:832  (/rakudo/blib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Grammar.nqp:553  (/rakudo/blib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2258  (/usr/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2298  (/usr/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2214  (/usr/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2249  (/usr/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2245  (/usr/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2241  (/usr/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1916  (/usr/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2151  (/usr/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2111  (/usr/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:109  (/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2036  (/usr/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:102  (rakudo.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (rakudo.moarvm:<mainline>)
 from <unknown>:1  (rakudo.moarvm:<main>)
 from <unknown>:1  (rakudo.moarvm:<entry>)
make: *** [Makefile:1184: RESTRICTED.setting.moarvm] Error 1
```

So it does not really fail at the rakudo level, but at the rakudo-debug level. Which maybe it's not really part of rakudo.

## Steps to Reproduce

Build this Dockerfile:

```
FROM alpine:latest as base

# Set up as root
ENV PKGS="git make gcc musl-dev" \
    PKGS_TMP="perl linux-headers bash"

RUN apk update && apk upgrade \
    && apk add --no-cache $PKGS $PKGS_TMP


RUN git clone https://github.com/MoarVM/MoarVM.git \
    && cd MoarVM \
    && perl Configure.pl --prefix /usr \
    && make install\
    && echo $PWD \
    && cd .. \
    && git clone  git://github.com/Raku/nqp.git \
    && cd nqp \
    && perl Configure.pl --backends=moar --prefix /usr \
    && make install \
    && cd .. \
    && git clone  https://github.com/rakudo/rakudo.git \
    && cd rakudo \
    && echo c > tools/templates/RAKU_SPECS\
    && perl Configure.pl --backends=moar --prefix /usr \
    && make install \
    && ls /usr/share/nqp/

RUN apk del $PKGS_TMP

FROM alpine:latest

LABEL version="0.0.1" maintainer="JJMerelo@GMail.com"

COPY --from=base /usr/lib/libmoar.so /usr/lib
COPY --from=base /usr/share/nqp/  /usr/share/nqp
COPY --from=base /usr/share/perl6/  /usr/share/perl6
COPY --from=base /usr/bin/moar /usr/bin/nqp  /usr/bin/raku   /usr/bin/

RUN addgroup -S raku  && adduser -S raku -G raku --home /home/raku

USER raku
WORKDIR /home/raku

ENTRYPOINT ["raku"]
```

## Environment
* Operating system: Alpine
* Compiler version (`perl6 -v` or `raku -v`): HEAD

**Comment by vrurg** [comment]
You started with a wrong assumption. RAKU_SPECS isn't meant to define what version are to be compiled but to contain all versions the source supports.

**Comment by JJ** [comment]
That file is actually used to generate the Makefile. There are specific targets for every version, and they are compiled separately, one on top of each other. This macro:

```
@for_specs(
@bpv(BOOTSTRAP_@ucspec@_SOURCES)@ = \
		@insert_filelist(bootstrap_sources)@
)@
```

For instance, expands to targets for every version, 

```
M_BOOTSTRAP_C_SOURCES = \
		src/Perl6/bootstrap.c/BOOTSTRAP.nqp \
    src/Perl6/bootstrap.c/EXPORTHOW.nqp \
    src/vm/moar/spesh-plugins.nqp

M_BOOTSTRAP_D_SOURCES = \
		src/Perl6/bootstrap.d/BOOTSTRAP.nqp \
    src/Perl6/bootstrap.d/EXPORTHOW.nqp

M_BOOTSTRAP_E_SOURCES = \
		src/Perl6/bootstrap.e/BOOTSTRAP.nqp \
    src/Perl6/bootstrap.e/EXPORTHOW.nqp
```

Depending on what you have there, there will only be variables defined for that specific version.

**Comment by vrurg** [comment]
@JJ, let me remind you that I designed this part of the build subsystem. So, I told about my intentions when it was developed. :) The primary purpose of _RAKU_SPEC_ is to provide data to generate language revision related data structures in _gen/*/main-version.nqp_. The problem has two aspects.

First, we have a number of explicit language versions and revisions mentioned here and there. I'm not sure how many of them result in trying to pick data from the data structure, but apparently if `6.d` or `d` is requested then it's going to result in an error. The error is going to be something as obscure as the one in your case because this kind of situation just must not happen by design. Things working in this given configuration do so by pure coincidence, nothing is guaranteed.

The second one is minor. _RAKU_SPEC_ also defines the current default compiler revision. For the moment it's `d`. From your description I conclude that you simply commented out `d` and `e` entries. This resulted in incorrect _gen/moar/main-version.nqp_ generated. I was curios and checked this out and got the very same compilation error as you did. Yet, marking `c` as the current allows `rakudo` to compile in full. Apparently, it doesn't pass all tests, but otherwise looks like it's working.

**Comment by JJ** [comment]
> @JJ, let me remind you that I designed this part of the build subsystem. So, I told about my intentions when it was developed. :) The primary purpose of _RAKU_SPEC_ is to provide data to generate language revision related data structures in _gen/*/main-version.nqp_. The problem has two aspects.
> 
> First, we have a number of explicit language versions and revisions mentioned here and there. I'm not sure how many of them result in trying to pick data from the data structure, but apparently if `6.d` or `d` is requested then it's going to result in an error. The error is going to be something as obscure as the one in your case because this kind of situation just must not happen by design. Things working in this given configuration do so by pure coincidence, nothing is guaranteed.
> 

Well, rakudo is quite clearly built by layers. That was clear enough if you look at how compilation is done in three phases, one for each version, so by the end of every phase there's *something*. Then by looking here and there I discovered that file in the template directory. All the thing is an impressive piece of work, and congrats, but that also implies there might be unexplored possibilities, and it might be worth the while to document it a bit more thoroughly (and also explore #4156). So I wanted to try and give it a shot. It's quite clear, for instance, that you need to build the "older" targets if you want to generate the "newer" versions. But, theoretically, it should be possible at one point in time to peel the "newer" layers and just grab the old ones; for instance, it should be possible right now to just generate the d without the 6.e components. It might be worth the while to explore that... 

> The second one is minor. _RAKU_SPEC_ also defines the current default compiler revision. For the moment it's `d`. From your description I conclude that you simply commented out `d` and `e` entries. 

If you see the Dockerfile I created it with, I just created a `RAKU_SPEC` file from scratch that contained only "c".

> This resulted in incorrect _gen/moar/main-version.nqp_ generated. I was curios and checked this out and got the very same compilation error as you did. Yet, marking `c` as the current allows `rakudo` to compile in full. Apparently, it doesn't pass all tests, but otherwise looks like it's working.

And that's what I would like to do, but #4156 are not letting me do that. There's a whole bunch of executables that's being generated, with or without `_inst_`, with or without `_debug_`. My impression was that the error was somewhere there, which is why I tried to do #4156.

**Comment by JJ** [comment]
It's failing now with a different error, more related to @vrurg comment, BTW:

```
echo '+++ Checking for moar NQP version'
'perl' -I'/rakudo/tools/lib' -I'/rakudo/3rdparty/nqp-configure/lib' '/rakudo/tools/build/check-nqp-version.pl' '/usr/bin/nqp-m'
make: *** No rule to make target 'gen/nqp-version', needed by 'gen/moar/main-version.nqp'.  Stop.
```

So it does not even get to the point where it compiles rakudo.

**Comment by niner** [comment]
On Montag, 4. Jänner 2021 08:44:57 CET Juan Julián Merelo Guervós wrote:
> But,
> theoretically, it should be possible at one point in time to peel the
> "newer" layers and just grab the old ones; for instance, it should be
> possible right now to just generate the d without the 6.e components. It
> might be worth the while to explore that...

But what would be the point? Why would you want to do that? What would make it 
worth exploring? Except for plain curiosity of course. I understand that one 
very well :)

**Comment by JJ** [comment]
Well, curiosity is something, but there's also Raku/problem-solving#253. At the end of the day, we're talking about version 6.c, but there's no single executable that includes *only* version 6.c.
I wanted also, on the fly, to understand the build process. But at the end of the day, this is something that we might want to do. Right now, for instance, version e is also included. We might want to compile a version c and d only, for instance. The whole 6.c and 6.d subsystems are isolated in the source, but they are not in the build process, so that it seems very difficult to do that kind of thing (although @vrurg mentions to have been able to do it).

**Comment by niner** [comment]
> We might want to compile a version c and d only, for instance.

Just omitting the 6.e setting won't get you there by far.

> The whole 6.c and 6.d subsystems are isolated in the source

No, they are not. Only new or overridden lexical symbols are isolated. 
Additions to existing classes or behavior that uses other means to distinguish 
language versions are not.

**Comment by JJ** [comment]
I think it's better to close this. Thanks for all the clarification
