### ISSUE TITLE
Multi as last statement returns candidate, not proto.

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#4157]
```
# script.raku

multi sub foo() {}
multi sub foo(42) {}

# evaler.raku

my &foo = EVALFILE('script.raku');
foo();

# raku evaler.raku
# OUTPUT: 
# Too few positionals passed; expected 1 argument but got 0
#  in sub foo at script.raku line 2
#  in block <unit> at evaler.raku line 3
```

The last statement returns the candidate with signature `:(42)`, not the dispatcher. This is either a rakudobug or ENODOC. Since `$!dispatcher` in `Routine` is not exposed, there is no way to call `foo()` with specced Raku.

This issue is filed by request of lizmat. I was surprised by the lack of proto and the workarounds ain't pretty. I could not find this in Roast. There might be good reason to return the candidate, even if I can't see any. So exposing `$!dispatcher` in `Routine` via a method called `proto` or `dispatcher` may be desireable.

## Workarounds

Place `my $ = &foo` at the end of script.raku. (looks like a code smell) or decent into nqp land in `evaler.raku` with:

```
use nqp;
my &disp = &foo.multi ?? nqp::getattr(&foo, Routine, '$!dispatcher') !! &foo;

disp();
```

## Environment
Welcome to Rakudo(tm) v2020.12-32-g8150a2864.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12-16-g34f9d8c7a.

Linux dexhome 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux

**Comment by jnthn** [comment]
> This is either a rakudobug or ENODOC.

The latter; `multi` routines and roles evaluate to the particular candidate in question, not the controlling `proto` or role group. That's useful for patterns where we want to pass the particular thing we're declaring to some other function.

> Place my $ = &foo at the end of script.raku

Why not just `&foo`?

> or decent into nqp land

There's a `dispatcher` method exposing it:

```
$ raku -e 'multi f() {1}; my $m = multi f($a) {2}; say $m.dispatcher()()'
1
```

**Comment by gfldex** [comment]
Just `&foo` will produce

```
WARNINGS for /home/dex/projects/raku/deep-script/script.raku:
Useless use of &MAIN in sink context (line 21)
```

And cron really likes to send e-mail with the content of STDERR.

The lines with `&?ROUTINE.dispatcher` in S12-methods/defer-next.t are commented out. Shall I file issues in Roast and docs?

**Comment by lizmat** [comment]
Tests adapted with https://github.com/Raku/roast/commit/82fbddefb0
