### ISSUE TITLE
The POD6 parser inserts whitespace before the last ">" in a C POD block

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4158]
## The Problem

This looks weirdly specific, but here's what happens:

```raku

=begin pod

I would like to talk about C<-->>, C<<< >>>,  C< << >> >, C<< >> and C«<--»

=end pod

say $=pod[0].contents;
```

This prints:

```text
[Pod::Block::Para
  I would like to talk about 
  Pod::FormattingCode{:type("C")}
    --
  >, 
  Pod::FormattingCode{:type("C")}
     
  , 
  Pod::FormattingCode{:type("C")}
    << >
   >, 
  Pod::FormattingCode{:type("C")}
     
   and 
  Pod::FormattingCode{:type("C")}
    <--
]
```

(see the  `>` in the next line, but also how <<>> is simply gobbled up in the second case), and also:

```
raku --doc C-syntax.p6 
I would like to talk about -->,  , << > >,   and <--
```

(please see the whitespace in the third example between the first and the second `> `)

## Expected Behavior

It should behave just like any other character

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

raku 2020.12

**Comment by lizmat** [comment]
Superseded by RakuDoc v2.0
