### ISSUE TITLE
Weird "Block object coerced to string" when trying to use a constant with object metainformation

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4159]
## The Problem

```raku
constant VER = v3; class Foo:ver{VER} {}; say Foo.^ver
# OUTPUT: «Block object coerced to string (please use .gist or .raku to do that)␤v␤␤» 
```

Similar thing with other fields, but maybe weirdr:

```raku
constant auth = "Þor"; class Foo:auth{auth} {}; say Foo.^auth
# OUTPUT: «-> ;; $_? is raw = OUTER::<$_> { #`(Block|68336832) ... }␤»
```

Where I have also discovered that the auth field can actually be a object... 

## Expected Behavior

It should probably behave in the same way as if we're using the other form of subscripting.

## Environment

That's Camelia, it's rakudo master.

**Comment by jnthn** [comment]
The colonpair syntax `:foo{ 42 }` is equivalent to `:foo({ 42 })` (just as `:foo[1,2,3]` is equivalent to `:foo([1,2,3])`. This is where the block comes from. Using `:ver(VER)` (which is a colonpair with a value) works fine:

```
$ raku -e 'constant VER = v3; class Foo:ver(VER) {}; say Foo.^ver'
v3
```

**Comment by JJ** [comment]
We should probably take that into account in the documentation. Thanks for letting us know.

**Comment by JJ** [comment]
TBH, I don't think that's mentioned in the colonpair syntax either...

**Comment by jnthn** [comment]
> We should probably take that into account in the documentation.

Yes; to be clear about it, the colonpair syntax parsed as part of a longname is precisely that of any other colonpair, rather than being a special case of it. The only different is in the timing: the colonpair is immediately evaluated at compile time, in order to form the name.
