### ISSUE TITLE
REPL repeating statements

### ISSUE THREAD

**Issue by kjpye** [rakudo/rakudo#4160]
## The Problem

Under some circumstances the REPL will execute the previous statement(s) before each new statement.

## Expected Behavior

Once a statement has been executed it is not executed again.

## Steps to Reproduce

At the REPL:

> my $a;
(Any)
> $a + 2;
Use of uninitialized value of type Any in numeric context
  in block <unit> at <unknown file> line 2

> $a += 2;
2
> dd $a;
Int $a = 4
> 

## Environment

> uname -a
Linux linux-3txv 5.3.18-lp152.57-default #1 SMP Fri Dec 4 07:27:58 UTC 2020 (7be5551) x86_64 x86_64 x86_64 GNU/Linux
> raku -v
Welcome to Rakudo(tm) v2020.12-35-g4d40e23e0.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12-16-g34f9d8c7a.

## Note

This is the same issue reported by tech_hutch on #raku

**Comment by kjpye** [comment]
This is directly caused by commit 7c0a81f501d8956c5b8dbb8ba3044e4ed382f821 (Make the REPL a bit smarter). The REPL behaved as expected before that commit.

Without the error, the issue does not occur.

With multiple "$a += 2" lines the errors accumulate.

The "dd $a" resets things, but the issue still arises without a second error. For example:

> my $a;
(Any)
> $a + 2;
Use of uninitialized value of type Any in numeric context
  in block <unit> at <unknown file> line 2

> $a += 2;
2
> $a += 2;
6
> $a += 2;
12
> dd $a;
Int $a = 18
> $a += 2;
20
> $a += 2;
24
>

**Comment by lizmat** [comment]
I'm open to suggestions on how to fix this *and* keep the fixes in place that these and following commits fixed.

**Comment by Altai-man** [comment]
Are there general (theoretical-wise) approaches for writing REPLs? I mean, there are lots of languages with REPL support and I am not sure they all do impossible tricks to keep everything working.

**Comment by lizmat** [comment]
I have no idea.  Rakudo's REPL's "E" is basically `EVAL`.  Unfortunately, not all aspects of the environment are saved between `EVAL`s, needing a way to re-EVAL some aspects of previously entered code.  The heuristics to determine when previous code should be included is currently basically: "if it didn't cause any output by itself, it is assumed that it is some kind of setup, so needs to be included in future results".

**Comment by lizmat** [comment]
An alternate approach could be to always replay the whole session with STDOUT and STDERR disabled until the final line?

**Comment by Altai-man** [comment]
I thought about that, but 1)It could mess user's files (if previous statements messed with e.g. FS or network); 2)The execution time will be pretty bad for numerous cases. Say a user executes a line which takes 10s. Then each sequential line will take at the very least 10s plus delta to finish.

I guess it boils down to the fact that Raku is not an interpreted language, but really a compiled one. And if you want an e.g. Java REPL or C++ REPL, you will suffer some consequences. You cannot have an interpreter to feed it code line by line and freeze the state between that, you need a whole file at once.

**Comment by jnthn** [comment]
The approach of replaying things is just asking for trouble. It seems that is a workaround for:

```
$ raku -e 'my int32 $a = 2; EVAL q/say $a/'
Bytecode validation error at offset 146, instruction 23:
operand type 32 does not match register type 24 for op getlex_ni in frame <unit>
  in block <unit> at -e line 1
```

And thus we're looking at a straight bug in `EVAL`.

**Comment by lizmat** [comment]
Added https://github.com/rakudo/rakudo/issues/4161

**Comment by notagoodidea** [comment]
I thing this is due to same issue but make the REPL unusable and can only be exited with `Ctrl+c` as `exit` routine will fail.
The session is the following:

```
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.12.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.12.

To exit type 'exit' or '^D'
> enum Flag (foo => "bar");
Map.new((foo => bar))
> sub f($a){say $a};
&f
> f(b => "foo")
Too few positionals passed; expected 1 argument but got 0
  in sub f at <unknown file> line 2
  in block <unit> at <unknown file> line 3

> f(3)
===SORRY!=== Error while compiling:
Redeclaration of symbol 'Flag'.
------> $ = enum Flag⏏ (foo => "bar");;
> exit
===SORRY!=== Error while compiling:
Redeclaration of symbol 'Flag'.
------> $ = enum Flag⏏ (foo => "bar");;
```

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/d53a927331
