### ISSUE TITLE
metamodel role invocant compilation bug.

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#4162]
## The Problem

```
my method a(Metamodel::PrivateMethodContainer: $obj) { ... }
```

## Expected Behavior

Compile successfully

## Actual Behavior

```
===SORRY!===
Cannot find method 'coercive' on object of type Archetypes
```

## Environment

https://gist.github.com/Whateverable/68c5c4fdb1a2b168437329a6dbfd36bb

Shows this behavior changed recently. (The snippet shown in whateverable just shows when the compilation error started happening, it's not enough to compile successfully once the error is fixed)

Discovered by automated compilation testing in the documentation repository.

**Comment by vrurg** [comment]
kaipei got there before me, raku/nqp#694 should fix this issue when merged.

**Comment by vrurg** [comment]
Closing as Raku/nqp#694 has been merged and NQP version bumped since then.
