### ISSUE TITLE
Add an "include" file capability for source code

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4171]
## The Problem

Currently there is no way to emulate the C/C++ preprocessing step of including source code at a given position in another source file.

## Expected Behavior

Be able to "include" one or more other files into the main source file (at least in module source files) during compile time with some unique statement. Of course that included file would have to satisfy the Raku grammar and would be the equivalent of manually inserting that code into the module's existing code as is required with the current compiler.

Maybe add something like this inside file **My.rakumod**:

    include-source-file<filename>;

and have the compiler include that file as it scanned source during compilation.

## Actual Behavior

The capability does not exist.

**Comment by vrurg** [comment]
This is clearly a language extension and as such it belongs to problem-solving.

**Comment by niner** [comment]
I wonder what you would use this for?

**Comment by tbrowder** [comment]
On Mon, Jan 18, 2021 at 01:38 niner <notifications@github.com> wrote:

> I wonder what you would use this for?


For example my current use case: creating a new PDF::Document module which
includes a class with methods that wrap methods of low-level class methods
in the PDF suite of modules.  Generate the new class methods by reading
lists of the of a couple of those classes, modify them a bit in the
process, and write out 61 methods at last count.

At the moment, I copy/paste the results into my module and its target class
and all is well. It would be so much easier to just let Raku do the
insertion.

I can use a Makefile to handle all but I'm too lazy for that.

If there is a better way to do it "I'm listening."

**Comment by lizmat** [comment]
FWIW, I think this functionality is similar to what we use to create the setting.  Which consists of many source files, some of which are partly or completely generated.  I seem to recall generalizing this functionality in the past, but it didn't gain enough traction then.

**Comment by tbrowder** [comment]
On Mon, Jan 18, 2021 at 06:11 Elizabeth Mattijsen <notifications@github.com>
wrote:

> FWIW, I think this functionality is similar to what we use to create the
> setting. Which consists of many source files, some of which are partly or
> completely
>
I was think thinking that one easy approach could be, when reaching an
include, rescan to generate a combined source and begin parsing anew, but
that would break the parse once rule.

**Comment by ugexe** [comment]
Sounds like a recipe for terrible error message

**Comment by niner** [comment]
Implementing this in the parser is the easy part. To make it work, you'd 
actually have to add support for include files in precompilation. After all 
you want the precomp file to get outdated when an included file gets changed.

Compared to that a Makefile doesn't sound that bad anymore :)

As to alternative ideas: maybe you can generate those methods at compile time, 
i e. BEGIN { $?CLASS.^add_method(...) }. Depends on what exactly your 
generator does.

**Comment by tbrowder** [comment]
All good points. And I'll look into the add_method idea.

**Comment by jnthn** [comment]
> Implementing this in the parser is the easy part. To make it work, you'd
> actually have to add support for include files in precompilation. After all
> you want the precomp file to get outdated when an included file gets changed.

Not to mention the effects on all downstream tooling, such as module installation (how would we represent these files in `META6.json`?) and editors/IDEs.

> At the moment, I copy/paste the results into my module and its target class
> and all is well. It would be so much easier to just let Raku do the
> insertion.

Could you generate a single file that exports a role containing these, and then `use` that file and compose the role into the class that should have the methods?

> a suitable challenge for a 100 year language

Well, if there's this much time, then probably a `macro` could be used to drive the generation, once we have those. :-)

**Comment by tbrowder** [comment]
I have looked briefly at using a role and that might work. But I am holding off at the moment because it will need some attributes that currently make it awkward. But that appears to be the best route when the design finally settles down.

I look forward to macros!  :-D

**Comment by tbrowder** [comment]
**UPDATE**

Eureka! A role did the trick. I no longer need an "include" capability for my use case. Perhaps a suitable doc entry under tutorials would be useful. 

This issue is OBE for me and can be closed.
