### ISSUE TITLE
comb should handle Junctions in Bool context

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#4174]
## The Problem

Maybe this is not an issue. This is possibly more "undefined behavior", but I think it's probably behavior no one would really want or reasonably expect.

## Actual Behavior

    > 'together'.comb('t'|'e');
    any((t t), (e e))

## Expected Behavior

    > 'together'.comb('t'|'e');
    (t e t e)

## Comments

In my mind, it's similar to #2975 (and fix 8652386) where `grep` was modified to handle Junctions in Bool context.

It's not quite the same because this is no regression. Bisectable says `comb` always had this behavior, but again I'm not sure it's the logical behavior.

In any case, if it's decided that it should _not_ return a Seq of Junctions, it's a breaking change and may need to be a 6.e feature.

Thoughts?

**Comment by lizmat** [comment]
I think the difference is that `grep` is supposed to use the return value as a `Bool`, and boolification of a `Junction` is supposed to collapse the `Junction`.  And that's what it does now.  I see no boolification with `.comb`?

**Comment by jnthn** [comment]
The behavior is both defined (it's the standard `Junction` auto-threading behavior) and seems correct to me.

The role of `Junction`s is ultimately to end up in a boolean context. In this case, we'd be boolifying the result of `comb`, which is asking if the `comb` operation found anything. We can thus read `so together'.comb('t'|'e')` as meaning "does `comb` find any of `t` or `e`", and indeed the result will reflect that.

The flattening behavior suggested as "expected" here would be incorrect for both `all` and `one` Junctions`. Consider `so "together".comb('t'&'z')` - meaning does `comb` find `t` and `z` - which I hope we'd agree should come out as `False`, but a flat `all('t', 't')` would be `True`.
