### ISSUE TITLE
Dateish `later` and `earlier` should accept multiple units

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#4175]
## The Problem

Passing multiple time units to a `Date` or `DateTime` object dies `More than one time unit supplied`.

There's no reason why we can't support multiple time units.

## Expected Behavior

```perl6
my $dt = DateTime('2020-12-31T22:30:00')
say $dt.later(:1hour, :30minutes);
# OUTPUT: 2021-01-01T00:00:00Z
```

This would allow a Hash of time units to be `Slip`d to the methods,

```perl6
my %units = (hours => 1, minutes => 30);
$dt .= later(|%units);
```

FWIW, this is supported in Python

```python
from datetime import datetime, timedelta
dt = datetime(2020, 12, 31,  22, 30, 0)
print(dt + timedelta(hours=1, minutes=30))
# OUTPUT: datetime.datetime(2021, 1, 1, 0, 0)
```

**Comment by 0racle** [comment]
I had hoped I could PR this one myself, but it would require a bit of re-work, as currently the `later` method can simply exit early. 

The simplest solution would be call `later` recursively until `%units` was exhausted.
A naïve solution would try to wrap the current logic in a loop, which would create a new Date/DateTime object with each loop. (Even though I would guess most loops would be <3, it's not ideal)

An optimal solution would need to accumulate time and then add it once at the end, but I'm not sure how best to tackle it.

At the very least, I think it would allow us to `!move-die` method in `Date` and just die inside `later` if `%units` is empty.

**Comment by jnthn** [comment]
My recollection is that the reason it doesn't at present is because named arguments are not ordered, and that the additions of different date units do not commute. Example:

```
$ raku -e 'say Date.new(2021, 1, 30).later(months => 1).later(days => 1)'
2021-03-01
$ raku -e 'say Date.new(2021, 1, 30).later(days => 1).later(months => 1)'
2021-02-28
```

To be clear, `.later(months => 1, days => 1)` and `.later(days => 1, months => 1)` are not possible to distinguish on the callee side, so you'd have to pick which one to do first, and that could be rather confusing.

If this problem doesn't exist for hours/minutes/seconds, only for months/days, then maybe a partial liberalization is possible without increasing risk (that is, permit multiple units only when the addition of those units commutes).

**Comment by salortiz** [comment]
> My recollection is that the reason it doesn't at present is because named arguments are not ordered, …

So DWIMing nothing prevents us from defining a certain order of application, especially if the one defined is a "natural" one.

> … so you'd have to pick which one to do first, and that could be rather confusing.

In this case it would be enough to document what the user should expect, IMHO.

**Comment by 0racle** [comment]
> In this case it would be enough to document what the user should expect, IMHO.

You expect users to read the docs!? /sarcasm

  > permit multiple units only when the addition of those units commutes

This is preferable in my mind. Support multiple units when you can, die when you can't. For example, if there are multiple units, and `%units<months>:exists`, then die with a helpful error.

Or you could hardcode the order and doc it... but principle of least surprise favours the former option.

Again to contrast with Python's `timedelta`... it looks like they avoid the issue by not even supporting months.

   >  class datetime.timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)

**Comment by niner** [comment]
> This is preferable in my mind. Support multiple units when you can, die when
> you can't. For example, if there are multiple units, and
> `%units<months>:exists`, then die with a helpful error.

Except that not even days and hours commute. Or if, then there's still 
ambiguity thanks to daylight saving time.

Take 2021-03-28T01:30:30+1, add 1 hour, then it's 2021-03-28T03:30:30+2, add 1 
day then it's 2021-03-29T03:30:30+2
Take 2021-03-28T01:30:30+1, add 1 day, then it's 2021-03-29T01:30:30+2, add 1 
day then it's 2021-03-29T02:30:30+2. Or you treat 1 day as always meaning 24 
hours, then you would get the same result. But what happens with leap seconds? 
A day with a leap second actually is 24 hours + 1 second long.

Nine's date rule #1: date time calculations are always more terrible than you 
imagine.

**Comment by patrickbkr** [comment]
I favour the obvious solution to the overly smart one. Allowing multiple offsets only when they commute feels too smart. People will keep tripping over why the one is allowed and the other isn't.

**Comment by lizmat** [comment]
Allowing a List candidate would allow for multiple values to be specified **and** determine the order in which they should be executed:

    $dt.later( (:1hour, :30minutes) );

Internally that would (at least initially) map to:

    $dt.later(:1hour).later(:30minutes);

so you could consider this to be syntactic sugar for not having to repeat `.later`.

The proposed syntax is currently illegal, so it should be possible to add it without any problems.  The code could be as simple as:

    multi method later(@pairs) {
        my $dt := self;
        $dt := $dt.DateTime::later( |$_ ) for @pairs;
        $dt
    }

**Comment by Altai-man** [comment]
>There's no reason why we can't support multiple time units.

Judging by the replies, there are reasons. Maybe they are reasons "why is it quite hard", not the "why is it completely impossible", but do we have a reason telling why we have to support it? The "we technically can do it, so we do it then" is not a reasoning to include something to an already big language while the existing way just works.

**Comment by vrurg** [comment]
> The proposed syntax is currently illegal, so it should be possible to add it without any problems. The code could be as simple as:

While overall a List candidate appeals to me, I see a problem with it where a non-`Pair` value can cause a LTA error. Additional type checking can be added, but it'll cost performance-wise.

**Comment by lizmat** [comment]
I don't think an additional nqp::istype() would be that expensive  :-)

**Comment by gfldex** [comment]
A more general solution has been depicted in https://gfldex.wordpress.com/2021/01/24/chain-calling/ . Adapted for methods that only take one named argument, as `later` and friends, the follwoing code does the trick.

```
use MONKEY-TYPING;

augment class Any {
    method chain {
        class Chainer {
            has $.the-object;
            method FALLBACK($name, *@a) {
                my $o = $.the-object;
                if @a {
                    for @a -> $e {
                        $o = $o."$name"($e, |%_);
                    }
                } elsif %_ {
                    for %_ -> %p {
                        $o = $o."$name"(|%p);
                    }
                } else {
# XXX error handling
                }

                $o
            }
        }

        Chainer.new(the-object => self)
    }
}

IO::Path.HOW.compose(IO::Path);
DateTime.HOW.compose(DateTime);

'/home/dex'.IO.chain.add(<tmp foo.txt>).say;
'/home/dex'.IO.chain.add('tmp').add('foo.txt').say;

my $d = now.DateTime;
say $d;
say $d.later(:1hour).later(:30minutes);
say $d.chain.later(:1hour, :30minutes);
```

**Comment by 0racle** [comment]
> Judging by the replies, there are reasons (why we can't support multiple time units)

Yeah, as  I often do, I spoke before putting much thought into it

  > Allowing multiple offsets only when they commute feels too smart. 

On further thought, I agree with you.

I do like the idea of a list candidate. The type check (and potential minor performance hit) would only impact that candidate.

**Comment by lizmat** [comment]
Implement List of Pairs approach as PR in https://github.com/rakudo/rakudo/pull/4181

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/cdc1b23c95
