### ISSUE TITLE
Stash lookups and augment don't always cooperate

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#4179]
## The Problem

I'm doing an overhaul of `Trait::Traced` and have a good reason to be placing an `our`-scoped sub in a class. I figured the same syntax that can be used to access a routine as a stash member from within the class would be usable from the context of `augment` as well. That golfs down to this:

```raku
use v6;
use MONKEY-TYPING;

class WithOurSub {
    our sub it(| --> Nil) { }
}

augment class WithOurSub {
    method call-it(::?CLASS:_:) { &::it() }
}

WithOurSub.call-it;
```

## Expected Behavior

This should perform the `&::it` lookup and call it successfully, outputting nothing.

## Actual Behavior

The lookup fails:

```
bastille% raku golf.raku
===SORRY!=== Error while compiling /home/morfent/Documents/ra-Trait-Traced/golf.raku
Undeclared routine:
    it used at line 9
```

But `&WithOurSub::it()` succeeds.

## Steps to Reproduce

Run the problem script.

## Environment
* Operating system:
OpenBSD bastille.kennel.qt 6.8 GENERIC.MP#285 amd64
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to Rakudo(tm) v2020.12-64-ge7a46bc09.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12-86-gb625fbc3d.

**Comment by lizmat** [comment]
I think this is not a bug.  Observe:

``` raku
use v6; 
use MONKEY-TYPING;

class WithOurSub {
    our sub it(| --> Nil) { } 
}   

our sub it() { say "the other" }
augment class WithOurSub {
    method call-it(::?CLASS:_:) { &::it() }
}   

WithOurSub.call-it;  # the other
```

The `&::it` syntax refers to `OUR::` namespace in the compilation unit.  That is *NOT* the `OUR::` of `WithOurSub`.  Hence you *must* call it fully qualified.

**Comment by jnthn** [comment]
> The &::it syntax refers to OUR:: namespace in the compilation unit.

`&::it()` is not doing a stash lookup at all; it's just a lexical lookup, thus why it fails in the original example and finds the outer `sub` declaration in that given by @lizmat. 

> That is NOT the OUR:: of WithOurSub

If we write `OUR` at this point, it *is* referring to `WithOurSub`, and so one can fix the code as follows:

```
use v6;
use MONKEY-TYPING;

class WithOurSub {
    our sub it(| --> Nil) { }
}

augment class WithOurSub {
    method call-it(::?CLASS:_:) { &OUR::it() }
}

WithOurSub.call-it;
```

I don't believe there's any precedent for leading `::` implying a stash lookup; when we see it in cases like `::?CLASS` then it's also a lexical resolution. Thus I agree there's not a bug here.
