### ISSUE TITLE
mysterious True at the end of array returned by $*KERNEL.signals

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#4180]
$ raku
> $*KERNEL.signals
[(Any) SIGHUP SIGINT SIGQUIT SIGILL SIGTRAP SIGABRT SIGEMT SIGFPE SIGKILL SIGBUS SIGSEGV SIGSYS SIGPIPE SIGALRM SIGTERM SIGURG SIGSTOP SIGTSTP SIGCONT SIGCHLD SIGTTIN SIGTTOU SIGIO SIGXCPU SIGXFSZ SIGVTALRM SIGPROF SIGWINCH SIGINFO SIGUSR1 SIGUSR2 True]

$*KERNEL.signals gives the list of available signals on a given platform, which are denoted in C by consecutive
constant integers starting from 1.
In raku the integer for a given signal is otherwise irrelevant,  but the  "starting from 1"  explains the (Any) in the beginning of the returned array.
On the other hand the trailing True is a mystery.

**Comment by salortiz** [comment]
I think that I solved the mystery, please see https://github.com/rakudo/rakudo/blob/master/src/core.c/Kernel.pm6#L133-L134
IMO, those trailing commas are a bug. If so, I have a trivial PR ready.
