### ISSUE TITLE
[JVM] Creating DateTime objects from positional arguments is busted

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4187]
## The Problem
Creating a DateTime object from positional arguments fails with a NullPointerException on the JVM backend:
```
$ ./rakudo-j --ll-exception -e 'dd DateTime.new(2021,1,3,0,0,0)'
java.lang.NullPointerException
  in new-from-positional (gen/jvm/CORE.c.setting:58237)
  in new (gen/jvm/CORE.c.setting:58261)
  in new (gen/jvm/CORE.c.setting:58260)
  in <unit> (-e:1)
  in <unit-outer> (-e:1)
  in eval (gen/jvm/stage2/NQPHLL.nqp:1216)
  in <anon> (gen/jvm/stage2/NQPHLL.nqp:1328)
  in command_eval (gen/jvm/stage2/NQPHLL.nqp:1325)
  in command_eval (gen/jvm/Compiler.nqp:119)
  in command_line (gen/jvm/stage2/NQPHLL.nqp:1309)
  in MAIN (gen/jvm/rakudo.nqp:133)
  in <mainline> (gen/jvm/rakudo.nqp:121)
  in <anon> (gen/jvm/rakudo.nqp)
```

The problem goes away if 0c8d238a8c is reverted.

A golfed version of the problem
```
$ ./rakudo-j -e 'use nqp; sub foo(Int() $x) { nqp::islt_I($x, 0) }; say foo(7)'
java.lang.NullPointerException
  in sub foo at -e line 1
  in block <unit> at -e line 1
```

As far as I can see there is a problem with using coercion to Int (```Int() $n```) together with NQP ops for bigints. This one also fails:
```
$ ./perl6-j -e 'use nqp; sub foo(Int() $x) { nqp::isbig_I($x) }; say foo(7)'
java.lang.NullPointerException
  in sub foo at -e line 1
  in block <unit> at -e line 1
```

I'm not sure if this needs a fix in Rakudo or in NQP. (If it is the latter, commit https://github.com/Raku/nqp/commit/7190914a19 might be relevant. The NPE happens in https://github.com/Raku/nqp/blob/master/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java#L6763, because the result from ```((P6OpaqueREPRData) type.st.REPRData).flattenedSTables[hint]``` is null.)

## Environment
Compiler version (`perl6 -v` or `raku -v`):
```
$ ./rakudo-j --version
Welcome to Rakudo(tm) v2020.12-102-gf2e324d51.
Implementing the Raku(tm) programming language v6.d.
Built on JVM.
```

**Comment by lizmat** [comment]
Aha, that makes *much* more sense!  Will revert the bandaid commit and fix it accordingly after finishing the RWN.

**Comment by lizmat** [comment]
Done in 0f5272cdc882b5f1bded , closing this now
