### ISSUE TITLE
tools/build/binary-release/build-windows.ps1 fails on Win10 (Pro)

### ISSUE THREAD

**Issue by AntonOks** [rakudo/rakudo#4188]
## The Problem
`tools/build/binary-release/build-windows.ps1` fails

1. I've cloned this repo on my Win10 Pro workstation
2. started `Developer PowerShell for VS 2019`
3. created the following `$Env:*` variables
  1. VERSION='2020.12'
  2. REVISION='01'
  3. RELEASE_URL="https://rakudo.org/dl/rakudo/rakudo-${VERSION}.tar.gz"
4. changed into the cloned directory, in my case `C:\Temp\Git\rakudo\tools\build\binary-release`
5. started `build-windows.ps1`

## Expected Behavior
The `build-windows.ps1` runs successfully and results in a https://github.com/rakudo/rakudo/blob/f2e324d51eb46436a5eecc1bb3c7cf66a471fa83/tools/build/binary-release/build-windows.ps1#L69 `rakudo-win.zip` archive

## Actual Behavior
`build-windows.ps1` dies at https://github.com/rakudo/rakudo/blob/f2e324d51eb46436a5eecc1bb3c7cf66a471fa83/tools/build/binary-release/build-windows.ps1#L50
because the previous command https://github.com/rakudo/rakudo/blob/f2e324d51eb46436a5eecc1bb3c7cf66a471fa83/tools/build/binary-release/build-windows.ps1#L49
returns with `Result: FAIL`, see the `Test Summary Report` below

```
Test Summary Report
-------------------
t/02-rakudo/08-slangs.t                                       (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/02-rakudo/10-nqp-ops.t                                      (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/02-rakudo/11-deprecated.t                                   (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
t/02-rakudo/14-revisions.t                                    (Wstat: 1024 Tests: 4 Failed: 4)
  Failed tests:  1-4
  Non-zero exit status: 4
t/02-rakudo/99-misc.t                                         (Wstat: 512 Tests: 11 Failed: 2)
  Failed tests:  1, 8
  Non-zero exit status: 2
t/02-rakudo/dd.t                                              (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
t/04-nativecall/00-misc.t                                     (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
t/04-nativecall/11-cpp.t                                      (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 22 tests but ran 1.
t/04-nativecall/13-cpp-mangling.t                             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 26 tests but ran 0.
t/05-messages/01-errors.t                                     (Wstat: 768 Tests: 51 Failed: 3)
  Failed tests:  10, 12, 48
  Non-zero exit status: 3
t/05-messages/02-errors.t                                     (Wstat: 3584 Tests: 47 Failed: 14)
  Failed tests:  1, 5, 10-14, 16-17, 32, 35-37, 43
  Non-zero exit status: 14
t/05-messages/03-errors.t                                     (Wstat: 1280 Tests: 25 Failed: 5)
  Failed tests:  6, 10, 16, 22, 25
  Non-zero exit status: 5
t/05-messages/10-warnings.t                                   (Wstat: 1536 Tests: 9 Failed: 6)
  Failed tests:  4-9
  Non-zero exit status: 6
t/05-messages/moar/01-errors.t                                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/06-telemetry/01-basic.t                                     (Wstat: 256 Tests: 42 Failed: 1)
  Failed test:  42
  Non-zero exit status: 1
t/09-moar/00-misc.t                                           (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/09-moar/01-profilers.t                                      (Wstat: 3072 Tests: 12 Failed: 12)
  Failed tests:  1-12
  Non-zero exit status: 12
Files=111, Tests=1786, 236 wallclock secs ( 0.69 usr +  0.33 sys =  1.02 CPU)
Result: FAIL
```
## Steps to Reproduce

See `The Problem`

1. clone this repo on a Win10 (Pro) system
2. start `Developer PowerShell for VS 2019`
3. create the following variables
  * `$Env:VERSION='2020.12'`
  * `$Env:REVISION='01'`
  * `$Env:RELEASE_URL="https://rakudo.org/dl/rakudo/rakudo-${VERSION}.tar.gz"`
4. change into the cloned directory, i.e. `C:\Temp\Git\rakudo\tools\build\binary-release`
5. start `build-windows.ps1`

## Environment
* Operating system:
  * OS Name:                   Microsoft Windows 10 Pro
  * OS Version:                10.0.19042 N/A Build 19042

**Comment by patrickbkr** [comment]
The script you used to run is part of the automation to create the compiled releases offered on rakudo.org and was not really intended to be used otherwise. Nonetheless it looks like you called it correctly and it should not fail!
The question is: What in your setup triggers all those errors? (The release process worked correctly for the 2020.12 release, so something specific to your system must be involved.)

It seems that all the failed tests use the [`is-run` helper](https://github.com/rakudo/rakudo/blob/master/t/packages/Test/Helpers.pm6#L17) (I checked the first few). So I suspect something is wrong there...

Could you maybe try to narrow the error down by manually reproducing what `is-run` does in one of the failed tests?

**Comment by AntonOks** [comment]
@patrickbkr Thanks for your feedback, Partick!

> The script you used to run is part of the automation to create the compiled releases offered on rakudo.org and was not really intended to be used otherwise. Nonetheless it looks like you called it correctly and it should not fail!

I know and this was my hope / expectation, too.... 
I thought I look into getting the [STAR bundles](https://rakudo.org/star) going again (at least the Windows bundle ;) ), but whatever I tried in the past weeks, everything is broken... so I thought I start with the obviously working "basis" and start from the "windows.zip", but.... 

> The question is: What in your setup triggers all those errors? (The release process worked correctly for the 2020.12 release, so something specific to your system must be involved.)
> 
> It seems that all the failed tests use the [`is-run` helper](https://github.com/rakudo/rakudo/blob/master/t/packages/Test/Helpers.pm6#L17) (I checked the first few). So I suspect something is wrong there...
> 
> Could you maybe try to narrow the error down by manually reproducing what `is-run` does in one of the failed tests?

Well, sure, can try once I find a bit of time again / for it...

**Comment by AntonOks** [comment]
@patrickbkr 

....seems like it was an issue with my Visual Studio / BuildTools installation.

Thanks a lot for looking into it!
