### ISSUE TITLE
[JVM] Make 'make test' usable again

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4191]
## The Problem
Currently ```make test``` isn't usable on the JVM backend. The primary problem is that ```t/harness5``` uses the EvalServer -- and the EvalServer heavily leaks threads and memory: https://github.com/Raku/old-issue-tracker/issues/6527.
I'm pretty sure that there are other problems, since very likely no-one has tried to run Rakudo's tests on the JVM backend for a long time.

Some ideas how to make ```make test``` usable again:
* Don't use the EvalServer, but run the test files one by one (in the same way as it is done on moar). This could be done by adding an option ```--evalserver``` to ```t/harness5``` and avoid the EvalServer unless that option is used.
* It should be possible to run ```make test```before ```make install```. There is an old issue about that: https://github.com/Raku/old-issue-tracker/issues/6524.
* Make sure the correct test files are run (requires a change to the generated Makefile). 
* Look at the fallout and fudge failing tests. (Very likely there is still a major problem with nativecall tests: https://github.com/Raku/old-issue-tracker/issues/6525.)

**Comment by patrickbkr** [comment]
Can you give a guesstimate of how much runtime of `make test` would drop when dumping the EvalServer?

**Comment by usev6** [comment]
Well, I'd expect the tests to run for more than one hour, but hopefully less than two hours (that is with ```TESTS_JOBS_1```). There seems to be one hanging test at the moment -- that would need fixing first.

Comparing with the status quo isn't really possible, because the EvalServer stops to work (due to the memory/thread leaks) after a couple of test files.

**Comment by usev6** [comment]
Another failing test should be fixed with https://github.com/rakudo/rakudo/pull/4268

**Comment by usev6** [comment]
A couple of tests fail because the JVM backend emits a slightly different error message when throwing X::Bind or X::Delete for native arrays. Since there are other inconsistencies for those error messages (and some tests) I've opened a separate issue: https://github.com/rakudo/rakudo/issues/4269

**Comment by usev6** [comment]
All tests for NativeCall are failing. See
* https://github.com/rakudo/rakudo/issues/3043
* https://github.com/Raku/old-issue-tracker/issues/6525

**Comment by usev6** [comment]
All test files for Telemetry are exploding. See https://github.com/rakudo/rakudo/issues/4354

**Comment by usev6** [comment]
Just to add an update here: Most of the tests for Telemetry are passing now (https://github.com/rakudo/rakudo/issues/4354 has been resolved).

**Comment by usev6** [comment]
Another update: Some of the nativecall tests are passing now (since https://github.com/Raku/nqp/pull/710 has been merged).

**Comment by usev6** [comment]
With https://github.com/rakudo/rakudo/pull/4355 merged one can now use ```make test``` (or ```gmake test```) on the JVM backend again.

On a virtual machine (with 2 cores of a Xeon E3-1271 v3) I've measured around 42 min for running the tests.

I'm not in favour of trying to run the tests in the CI (that's disabled right now: https://github.com/rakudo/rakudo/blob/d301860e50/azure-pipelines.yml#L203). It would make the CI runs much slower and feels like a waste of CPU cycles.

I'm closing this issue now. (I'll try to look at the fudged tests and create separate issues where appropriate.)
