### ISSUE TITLE
Stale variable in body of for loop

### ISSUE THREAD

**Issue by bluebear94** [rakudo/rakudo#4193]
## The Problem

The following code produces incorrect output:

``` raku
for (1, 2, 3, 4, 5) -> $n { (say $n for ^5) xx 2 }
```

## Expected Behavior

It should output 10 lines with `1`, 10 lines with `2`, 10 lines with `3`, 10 lines with `4`, and 10 lines with `5`.

## Actual Behavior

All 50 lines in the output contain `1`.

## Steps to Reproduce

Run the code above anywhere (REPL, `perl6 -e`, etc.).

## Environment
* Operating system: Linux
    ```
    $ uname -a
    Linux elyundite 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64 GNU/Linux
    ```
* Compiler version (`perl6 -v` or `raku -v`):
    ```
    Welcome to Rakudo(tm) v2020.12.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2020.12.
    ````

**Comment by MasterDuke17** [comment]
FWIW, `for (1, 2, 3, 4, 5) -> $n { (say $n for ^5) }` and `for (1, 2, 3, 4, 5) -> $n { (say $n) xx 2 }` all output as expected, it appears to be the combination of `for` and `xx` that's the problem.

**Comment by salortiz** [comment]
And `for (1, 2, 3, 4, 5) -> $n { ({say $n} for ^5) xx 2 }` works as expected.

**Comment by lizmat** [comment]
Test added with https://github.com/rakudo/rakudo/commit/ea5a74d24d
