### ISSUE TITLE
postcircumfix{;} does not rebind

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#4203]
```
use v6.e.PREVIEW;

my @a = <a b>;
my %b;
%b{||@a} = 42;
@a = <a b c>;
%b{||@a} = 42; # line 7

# OUTPUT: Type Int does not support associative indexing.
#           in block <unit> at /home/dex/projects/raku/rakudobug/tmp2.raku line 7
```

Looks like a FETCH happens where a bindpos should.

(can be found in gist https://gist.github.com/gfldex/0e59383ece1aba3aa710d1913c354b2f)

## Environment
* Operating system: Linux dexhome 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2020.12-102-gf2e324d51. Implementing the Raku(tm) programming language v6.d. Built on MoarVM version 2020.12-85-g2d9899c72.

**Comment by lizmat** [comment]
I think this *may* be a case of an LTA error message.  But this error is no different from:

    my %h;
    %h<a><b> = 42;
    %h<a><b><c> = 666;  # Type Int does not support associative indexing.

which is a long way of saying:

    my $b = 42;
    $b<c> = 666;  # Type Int does not support associative indexing.

So this becomes a basic question of what to do when trying to associatively index onto a container that does *not* contain something `Associative`.  Which is more a problem-solving issue than a problem that warrants an issue here.  So I'm closing this issue.
