### ISSUE TITLE
Starting multiple busy threads blocks new threads

### ISSUE THREAD

**Issue by jmaslak** [rakudo/rakudo#4206]
## The Problem

In my foot warmer application (App::Heater), I found that if I just started a bunch of threads that simply looped, only 8 threads would start.  The rest would not start.

## Expected Behavior

I would expect one thread to start every time I had a "start" block.

## Actual Behavior

Only 8 threads start.

## Steps to Reproduce

Using this program:

```#!/usr/bin/env raku
use v6.d;

for ^10 {
    say "PRE-START: $_";
    start { say "STARTED: $_"; loop {} }
}
sleep 1;
```

I expect the output to output 10 "PRE-START" lines and 10 "STARTED" lines.  I also expect the program to terminate.  It only prints 8 "STARTED" lines and never terminates.

Actual output:
```
PRE-START: 0
STARTED: 0
PRE-START: 1
PRE-START: 2
PRE-START: 3
PRE-START: 4
PRE-START: 5
PRE-START: 6
PRE-START: 7
PRE-START: 8
PRE-START: 9
STARTED: 1
STARTED: 2
STARTED: 3
STARTED: 4
STARTED: 5
STARTED: 6
STARTED: 7
```

(and never terminates)

If I change the sleep to something like "sleep 10" and add a "sleep 1" before each thread's say, so it looks like this, it does execute as expected (and terminates):

```#!/usr/bin/env raku
use v6.d;

for ^10 {
    say "PRE-START: $_";
    start { sleep 1; say "STARTED: $_"; loop {} }
}
sleep 10;
```

## Environment
* Operating system: Ubuntu 20.10
* Compiler version (`perl6 -v` or `raku -v`):

**Comment by jmaslak** [comment]
Raku version 2020.12.

**Comment by niner** [comment]
start blocks do not start new threads. They merely schedule the block to run 
on one of the worker threads. The ThreadpoolScheduler keeps track of how much 
work its got and starts these worker threads as needed. It defaults to 
starting at most as many threads as there are CPU cores available. So your 
demonstration shows behaviour as intended.

Seems like the docs for start blocks at
https://docs.raku.org/language/control#start should mention this but doesn't.

**Comment by jmaslak** [comment]
That makes sense, but I think it's still missing things.

1) The CPU I tested this on has 12 cores, which I would think would be enough to start 10 threads, but I could be missing some reserved threads.
2) The final sleep command never returns in this code (I do see the "PRE-SLEEP" output, but it never gets to "POST-SLEEP":

```#!/usr/bin/env raku
use v6.d;

say "CPU Cores: " ~ $*KERNEL.cpu-cores;
for ^10 {
    say "PRE-START: $_";
    start { say "STARTED: $_"; loop {} }
}
say "PRE-SLEEP";
sleep 2;
say "POST-SLEEP";
```

Output:

```CPU Cores: 12
PRE-START: 0
STARTED: 0
PRE-START: 1
PRE-START: 2
PRE-START: 3
PRE-START: 4
PRE-START: 5
PRE-START: 6
PRE-START: 7
PRE-START: 8
PRE-START: 9
PRE-SLEEP
STARTED: 1
STARTED: 2
STARTED: 3
STARTED: 4
STARTED: 5
STARTED: 6
STARTED: 7
```

(never returns)

**Comment by vrurg** [comment]
BTW, on both my 16 cores macbooks and 56 cores linux server the behavior is 100% the same. The script blocks with 8 threads started.

Aside of this, I'm confused by the fact that even if I would need more threads than CPU cores there is no way to get them.

**Comment by jnthn** [comment]
I believe it's a case of https://github.com/MoarVM/MoarVM/issues/1230.

**Comment by jonathanstowe** [comment]
If you put a `sleep` of any duration (.0001 say,) in the loop { } it will work as expected.

**Comment by jonathanstowe** [comment]
Or indeed a short sleep prior to starting the loop.

**Comment by lizmat** [comment]
Pretty sure that this is no longer an issue with the default disabling of the expression JIT.

@jmaslak could you confirm and close if so?  Winter time is coming again  :-)

**Comment by jmaslak** [comment]
Yes, looks fixed!  I'll close.
