### ISSUE TITLE
In a slice, a lazy iterable as part of a non-lazy list of indexes, will fail to stop

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#4216]
This seems to be a regression from 2020.12

Golfed by Lizmat++ to 

    dd (1..10).map(~*)[1,4..6,8..Inf]

Bisected by Alexdaniel++ to

 https://github.com/rakudo/rakudo/commit/ca7bc91e71afe9373b57cd629215f843e8026df1

**Comment by lizmat** [comment]
When you break it, you should fix it :-)

**Comment by lizmat** [comment]
I believe this can be closed now

**Comment by Altai-man** [comment]
I'll close it after a point.

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/58c316de27

**Comment by Altai-man** [comment]
Closing this as the point is released.

**Comment by lizmat** [comment]
Thank you for the point release!
