### ISSUE TITLE
Why does raku's division operation only retain 6 decimal places by default?

### ISSUE THREAD

**Issue by fenginsc** [rakudo/rakudo#4224]
If I enter 207/1828 in the REPL, the result is 0.113239, and the result in Perl5 is 0.113238512035011.
The results in javascript, python, ruby are all 0.113238512035011.
Why is Raku inconsistent with most languages, and is there any plan to fix this?
Thanks.

**Comment by niner** [comment]
The division operation is fine. In fact it works with arbitrary precision as 207/1828 creates a rational number:

> say (207/1828).raku
<207/1828>

 It's just the default stringification of rational numbers that restricts to 6 decimal places:

> (207/1828)*1000000000000000000
113238512035010940.919037
> sprintf("%.15f", 207/1828)
0.113238512035011

**Comment by fenginsc** [comment]
@niner Thank you, can I change the number of digits in the default stringification?

**Comment by lizmat** [comment]
Alas, no.

**Comment by jonathanstowe** [comment]
You can however use `printf` to render it with the precision you want:

     printf "%.20f",207/182

**Comment by pmichaud** [comment]
Or even use .fmt to get a string representation with more digits after the
decimal:

   (207/1828).fmt("%.20f")

Pm

**Comment by fenginsc** [comment]
I found that formatting to retain 20 decimal places does not work. In fact, the effective number of digits is still 15 digits.
`
(207/1828).fmt("%.20f")
printf "%.20f",207/1823
`
The result is 0.11354909489851900000, and the actual result should be 0.11354909489851892484.
In other words, it is not arbitrary precision? In this case, why keep stringification by default and only keep 6 decimal places? Can it be modified by default to keep 15 bits consistent with other languages, thank you.

**Comment by jnthn** [comment]
> Can it be modified to retain 15 decimal places by default, just like other languages?

The semantics of `207/1828` already vary across languages. The two mostly commonly found are:

* Truncating integer division, in which case you'll get `0` (Raku makes these semantics available under the operator `div`)
* Promotion of both to a floating point number, followed by floating point division, which seems to be what you're expecting. This can be made to happen by forcing either of the operands to be floating point (for example, `207e0/1828`). If the output of *this* is too inconsistent with other languages, that's certainly a legitimate issue to explore.

Raku is one of the few languages to define division of two integers as a constructor of a rational number. This is a deliberate design choice, and is considered a better default for many kinds of programming (for example, dealing with currency calculations). It does, however, shift the burden to those doing continuous math to opt in to floating point - while in other languages those doing things like financial calculations have to instead choose to use a decimal representation. (Or they don't know they should, and then they get rounding errors when calculating insurance on a multi-billion dollar nuclear reactor...)

There's not really a right or wrong here so far as the language goes; different number representations optimize for different things, and the Raku designers felt that the things a rational representation optimizes for are the right choice more often than the things a floating point representation does.

**Comment by niner** [comment]
A note on only getting 15 decimal places. While 207/1828 creates a rational 
number and any calculations with this number will have arbitrary precision, 
stringifying this number will first convert it to a floating point number wir 
limited precision and then stringify that.

I'm not sure if this is by design or an implementation artifact though.

**Comment by jnthn** [comment]
> I'm not sure if this is by design or an implementation artifact though.

My recollection is that `Rat.Str` takes an epsilon parameter so you can decide that. It's a cost/precision trade-off, so far as I understand it.

**Comment by lizmat** [comment]
Not seeing that epsilon parameter (anymore anyway).

**Comment by jnthn** [comment]
> Not seeing that epsilon parameter (anymore anyway).

Turns out I had completely misremembered. The epsilon parameter is on `Num.Rat`. Sorry for the noise.

**Comment by MasterDuke17** [comment]
Some relevant comments here
https://github.com/rakudo/rakudo/blob/master/src/core.c/Rational.pm6#L130-L141

**Comment by jnthn** [comment]
Looks more like a design indecision. :-) So I guess the questions are:

1. Can we get it to ~15 digits?
2. How much does it cost?
3. Should we make it configurable?
4. Is a stringification that lets you pretend you're in float land for longer even a good idea, or is the current limitation actually a good cue for people to ask if they are using the correct number type?

**Comment by fenginsc** [comment]
In the case of almost no impact on performance, can you consider retaining ~15 digits by default, thank you.

**Comment by alabamenhu** [comment]
> Alas, no.

Actually, I think it could be done (if someone wants to have it for all stringification in their script)

```raku
Rat.^find_method('Str').wrap( method { self.fmt: "%.15f" } );
say (207/1828).raku # 0.113238512035011
```

Of course, it would globally affect stringification so any module used that depends on 6-digit stringification might have problems (probably not an issue as long as you stay outputting numbers, but if you outputed `zero point one one three…` it might be problematic)
