### ISSUE TITLE
eefc785e0 seems to have broken YAMLish

### ISSUE THREAD

**Issue by japhb** [rakudo/rakudo#4237]
## The Problem

Unable to install YAMLish module on rakudo HEAD.

## Expected Behavior

Normal test and install using `zef install YAMLish`.

## Actual Behavior

```
===> Testing: YAMLish:ver<0.0.5>
[YAMLish] # Failed test 'Original YAML::Tiny test should parse'
[YAMLish] # at t/test-harness.t line 496
[YAMLish] (HANDLED) Couldn't parse YAML: Cannot modify an immutable Map (Map.new(()))
[YAMLish]   in sub load-yaml at .../.zef/store/yamlish.git/d49a2e85ecc7300d7966b2b30909443ce751bcca/lib/YAMLish.pm6 (YAMLish) line 948
[YAMLish]   in block <unit> at t/test-harness.t line 489
[YAMLish] # You failed 1 test of 41
===> Testing [FAIL]: YAMLish:ver<0.0.5>
Aborting due to test failure: YAMLish:ver<0.0.5> (use --force-test to override)
```

## Steps to Reproduce

Install **works** fine at:

* `rakudo-moar-2021.02.1-13-g17c7c1889`
* `rakudo-moar-2021.02.1-24-g18612841f`

Install **BROKEN** at:

* `rakudo-moar-2021.02.1-26-geefc785e0`
* `rakudo-moar-2021.02.1-29-gaffdd0583`

I therefore believe the merge at eefc785e0 to be at fault.

## Environment

```
$ raku -e 'say $*DISTRO'
linuxmint (20.1.Ulyssa)

$ raku -v  # Last working version
Welcome to Rakudo(tm) v2021.02.1-24-g18612841f.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.02-3-g4ae157c33.
```

**Comment by lizmat** [comment]
Ok, it turns out that calling `.nodemap` on a `Map` used to return a `Hash`, **not** a `Map`.  And `Match.hash` returns a `Map`.
