### ISSUE TITLE
The ".abs" method on "-1.5e0" fails

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4242]
See the following code:

~~~
$ raku
> say -1.5e0.Int
-1
> say -1.5e0.abs
-1.5
~~~

I expected:

~~~
> say -1.5e0.abs
1.5
~~~

## Environment

* Operating system: Debian 10 (Buster)

$ raku -v
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12

**Comment by pmichaud** [comment]
Likely a parsing thing, because:

> say (-1.5e0).abs
1.5
> 

Pm

**Comment by pmichaud** [comment]
In fact, I suspect it parses as   -(1.5e0.abs), since  "Symbolic unary" is lower precedence than "Method postfix".   See https://docs.raku.org/language/operators#Operator_precedence .

In particular, we expect  ```-$x.abs``` and ```!$x.foo``` to parse as

   -($x.abs)    !($x.foo)

and not

   (-$x).abs    (!$x).foo

Pm

**Comment by labster** [comment]
> -1.5e0.abs
-1.5
> -1.5e0 .abs
1.5

Use the space, Luke.

**Comment by tbrowder** [comment]
Okay, thanks. Closing this non-issue.
