### ISSUE TITLE
Destructured multis in roles are broken

### ISSUE THREAD

**Issue by raydiak** [rakudo/rakudo#4258]
```
$ raku -e 'role A { multi method a ([]) { 0 }; multi method a (@) { 1 } }; say A.a([1]);'
Cannot resolve caller a(A:U: Array:D); none of these signatures match:
    (A: @ (), *%_)
  in block <unit> at -e line 1
```

There is only one candidate in the list no matter how many multis are defined for the same list of parameter sigils, regardless of destructuring differences. This bug also occurs for associative parameters. "where" clauses do not seem to participate in the erroneous behavior. It only manifests in roles, not classes. It does manifest in classes which compose affected roles in addition to the autopunned roles themselves.

bisectable indicates that every version of rakudo since 2016.03 contains this bug. That release includes several commits mentioning parameter work and optimizations, largely by @lizmat++

**Comment by lizmat** [comment]
Some research, when A is a class:

````raku
class A {
    multi method a ([]) { 0 }
    multi method a (@) { 1 }
}
dd $_ for A.^find_method("a").candidates;
# Method a = multi method a (A: @ (), *%_) { #`(Method|140216749135344) ... }
# Method a = multi method a (A: @, *%_) { #`(Method|140216749147440) ... }
````

However, the punned role version only shows **1** candidate:

````raku
class A {
    multi method a ([]) { 0 }
    multi method a (@) { 1 }
}
dd $_ for A.^pun.^find_method("a").candidates;
# Method a = multi method a (A: @ (), *%_) { #`(Method|140283460130000) ... }
````

Switching the order of the candidates:

````raku
class A {
    multi method a (@) { 1 }
    multi method a ([]) { 0 }
}
dd $_ for A.^pun.^find_method("a").candidates;
# Method a = multi method a (A: @, *%_) { #`(Method|140276615025872) ... }
````

shows that the other candidate is retained, which is actually the working candidate:

````
$ raku -e 'role A { multi method a (@) { 1 }; multi method a ([]) { 0 } }; say A.a([1])'
1
````

So it looks like the role to class applier doesn't see the difference in signatures and drops one candidate on the floor.

**Comment by vrurg** [comment]
`RoleToClassApplier` is not guilty. Basically, the bug golfs down to the following:

```raku
say :([]) eqv :(@); # True
```

And even further, to `Parameter` `eqv` where code would be longer, but it is the core of the problem:

```raku
say :([]).params[0] eqv :(@).params[0]; # True
```

What exactly happens is that `[]` is treated not as an empty array but as a destructuring construct, akin to `sub foo([$first, *@rest]) {}`. In the end we have two parameters where one has `$!sub_signature` set to a value, and the other has it set to `VMNull`. `Parameter` `eqv` op doesn't test this attribute and results in a false positive.

**Comment by vrurg** [comment]
It wasn't planned, but I already have a fix. @lizmat, PR will be submitted in a few minutes, as soon, as I get a spectest too.
