### ISSUE TITLE
LTA message: $a instead of $_

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#4273]
When fooling around, I commited a brain fart. That uncovered a LTA message. The message is about $a instead of $_.
Thx to raydiak on #raku-dev.

Probably the use of $_ in a loop *and* in enclosing code should trigger a warning in a linter.
But that would be too much to ask from a compiler.
On the other hand is it possible to indicate $_ was implicitly bound readonly in the loop ?

The golfed code and the error message
```
$_='toto'; $_++ for 0..1
Cannot resolve caller postfix:<++>(Int:D); the following candidates
match the type but require mutable arguments:
    (Mu:D $a is rw)
    (Int:D $a is rw --> Int:D)

The following do not match for other reasons:
    (Bool:D $a is rw)
    (Bool:U $a is rw --> Bool::False)
    (Mu:U $a is rw)
    (Num:D $a is rw)
    (Num:U $a is rw --> 0e0)
    (int $a is rw --> int)
    (num $a is rw --> num)
  in block <unit> at <unknown file> line 1

```

**Comment by lizmat** [comment]
The message is just introspecting the candidates:

````
.signature.say for &postfix:<++>.candidates;
####
(Mu:D $a is rw)
(Mu:U $a is rw)
(Int:D $a is rw --> Int:D)
(int $a is rw --> int)
(Bool:U $a is rw --> Bool::False)
(Bool:D $a is rw)
(Num:D $a is rw)
(Num:U $a is rw --> 0e0)
(num $a is rw --> num)
````
And if you look at the code, the name of the variable accepting the argument *is* actually `$a`.

Now one could argue a better name could have been used in the code.

**Comment by jnthn** [comment]
In principle the compiler knows that:

* Iterating a range produces immutable `Int` values, at least if `..` is not overridden
* The `Int` candidate for `postfix:<++>` needs something that `is rw` (again, overrides aside)

So this could be reported at compile time.

**Comment by cognominal** [comment]
> The message is just introspecting the candidates:
> 
> ```
> .signature.say for &postfix:<++>.candidates;
> ####
> (Mu:D $a is rw)
> (Mu:U $a is rw)
> (Int:D $a is rw --> Int:D)
> (int $a is rw --> int)
> (Bool:U $a is rw --> Bool::False)
> (Bool:D $a is rw)
> (Num:D $a is rw)
> (Num:U $a is rw --> 0e0)
> (num $a is rw --> num)
> ```
> 
> And if you look at the code, the name of the variable accepting the argument _is_ actually `$a`.
> 
> Now one could argue a better name could have been used in the code.

A better name needed in *my* code, no doubt about that.
In  the rakudo compiler, I am not the one to judge except if it leaks to the user like that.

**Comment by lizmat** [comment]
Perhaps it would be better if we remove the variable names from the signature?  So that it would show:
```
$_='toto'; $_++ for 0..1
Cannot resolve caller postfix:<++>(Int:D); the following candidates
match the type but require mutable arguments:
    (Mu:D $ is rw)
    (Int:D $ is rw --> Int:D)

The following do not match for other reasons:
    (Bool:D $ is rw)
    (Bool:U $ is rw --> Bool::False)
    (Mu:U $ is rw)
    (Num:D $ is rw)
    (Num:U $ is rw --> 0e0)
    (int $ is rw --> int)
    (num $ is rw --> num)
  in block <unit> at <unknown file> line 1
```

**Comment by lizmat** [comment]
PR added with https://github.com/rakudo/rakudo/pull/5663

Closing this because if the PR is not merged, there is no other solution either.
