### ISSUE TITLE
The Dateish.daycount value should be a real number if intended to be the MJD

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4279]
## The Problem

The docs describe the *Dateish.daycount* method as the *Modified Julian Date* (MJD), and further describe it to be the "number of days from the epoch Nov. 17, 1858 to the day of the invocant."

The problem is that would-be users of the MJD probably expect the value to be a real number with the fractional part being the part of the 24-hour day since the day's beginning (midnight of the previous day). 

## Proposed Solution

1. Revise the docs to ensure the description is complete and advise the user that the 'daycount' is not exactly the astronomer's expected MJD.
2. Add the *juliandate* and the *mjd* methods to the DateTime class to properly provide the expected values.
3. For testing purposes, one good source of date and Julian date pairs is the US NASA JPL [Time Conversion Tool](https://ssd.jpl.nasa.gov/tc.cgi) website. (**NOTE**: the OP already has a working script, courtesy of Curt Tilmes, that can extract desired data from the JPL website.)
4. Deprecate the *daycount* method in the Dateish class.

**Comment by lizmat** [comment]
Please note that the daycount attribute is considered to be an implementation detail.  It is **not** tested for, and it is not documented.

A lot of calculations involving dates, internally use the daycount value.  If this is going to be a real number or a Rat, then this will probably mean that the `Date` and `DateTime` classes will not be able to share the `Dateish` role for a significant part.

Having said that: what about creating an `mjd` method that would be based on the daycount + calculate the fraction given timezone and hh:mm:ss data?  Basically 3600 * hour + 60 * minute + seconds / 86400 ?

**Comment by tbrowder** [comment]
I do see the description in the docs for DateTime and also Dateish, so that is user visible.

@lizmat, I can live with your suggestion, but I will not try to do much at all before I get an implementation of the "true" algorithm to add the *mjd* method. Also, I would like to be able to make some statement about the error boundaries of the calculation as well as adding tests for the calcs (perhaps based on the JLP site).

When I get my DateTime::Julian module working as I see all this, then I can look at adding the *mjd* (and *juliandate*) methods.

**Comment by tbrowder** [comment]
Another accidental closing :-(

**Comment by lizmat** [comment]
I wonder what the behaviour should be on dates with leap-seconds.  Should it divide by 86401 instead of 86400 ?

**Comment by tbrowder** [comment]
For now I have:

1. Updated the docs to improve the description of daycount.
2. Prepared a PR for Rakudo that adds three methods to class DateTime:
    1. day-fraction
    2. mjd
    3. juliandate
4. Prepared a test suite for the PR that successfully tests the integral *and fractional* values against the JPL values for dates from years 2000, 3000, and 4000.

So any internal changes to handle earlier dates can await more of a need.

**Comment by tbrowder** [comment]
@lizmat added the necessary tests, and the proposed new methods have been added to Rakudo.
