### ISSUE TITLE
Raku architecture document is obsolete

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4281]
It even says so in the header. Shouldn't it be deleted directly? Or moved to another "archived-and-forgotten" repository...

https://github.com/rakudo/rakudo/blob/09d27c32165d939544d4030844c9477c3affdb00/docs/architecture.html#L3

(Also: might be a good idea to update it)

**Comment by lizmat** [comment]
Some parts may be salvageable, that's why I didn't delete it when I added the OBSOLETE header :-)

**Comment by Altai-man** [comment]
Maybe it's a good idea to just update it with fresh info rather than removing?

**Comment by MasterDuke17** [comment]
https://github.com/rakudo/rakudo/blob/master/docs/compiler_overview.pod is also pretty outdated.

**Comment by lizmat** [comment]
Dupe of #4245
