### ISSUE TITLE
Role mixins are mixed up

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4282]
## The Problem

When a variable has, itself, more than one role, trying to print one aspect of it gets mixed up. Example:

```
my $foo = 3 but "bar";
say $foo.Int;    # OUTPUT: «bar␤» 
say $foo.Num; # OUTPUT: «3␤»
```

## Expected Behavior

Well, it should behave as expected, returning an Int via coercion, maybe. In [this chat](https://colabti.org/irclogger/irclogger_log/raku?date=2021-03-31#l209) @lizmat says it seems right, in which case this would be a matter of documenting it better, but anyway making `$foo.Int` return a string is a bit WAT, and it should be DWIM.

## Actual Behavior

It looks like there's an "offset by one" error with printing the content.

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

That would be Camelia on the IRC channel, `2021.02.25.g.726.a.75.e.24`

**Comment by lizmat** [comment]
But that's not what's happening!  Calling `.Int` on an `Int` returns the invocant.  So that's unchanged (and the mixed in version).  *Then* `say` calls `.gist` on that.  And `Int.gist` falls back to `Int.Str`, and `method Str(--> "bar") { }` was mixed in with `but "bar"`.

**Comment by JJ** [comment]
In that case, it's probably in need of a better documentation. It keeps being a WAT.

**Comment by lizmat** [comment]
Or we could add a specific `gist` method to `Int`, that doesn't fall back to `Str`.  Possibly for all `Cool` objects, really.

**Comment by jnthn** [comment]
Coercions (correctly) respect sub-typing. When we do a mixin, we're creating an anonymous subclass of the original type. So `1 ~~ Int` and `1 but "bar" ~~ Int` are both true. Since the type already is an `Int`, then the coercion is a no-op.

**Comment by lizmat** [comment]
I think this issue can be closed?

**Comment by JJ** [comment]
Right. Might be a documentation issue, but we have enough of those.
