### ISSUE TITLE
Suggestions on release announcements

### ISSUE THREAD

**Issue by Prince213** [rakudo/rakudo#4314]
## Current

<img width="563" alt="1" src="https://user-images.githubusercontent.com/25235514/114296968-a23a1780-9ae0-11eb-88d2-82a6671a1813.png">
<img width="198" alt="2" src="https://user-images.githubusercontent.com/25235514/114296970-a403db00-9ae0-11eb-96ef-fc40b025fff5.png">

## Suggestion

```md
the Raku<sup>[1]</sup> language

[1]: https://raku.org/
```
It will look like this:
<img width="147" alt="3" src="https://user-images.githubusercontent.com/25235514/114297074-2db3a880-9ae1-11eb-8693-9489b6c243f0.png">

## References
https://github.github.com/gfm/#shortcut-reference-link

**Comment by Altai-man** [comment]
It looks to me like a github-only markdown's syntax, I wonder if we want to use something like this.
What we have now (`[^1]` syntax) is suggested at https://www.markdownguide.org/extended-syntax/#footnotes and I am not sure if we should change it to something so github-specific, what are the reasons to prefer one specific convention over another specific convention?

**Comment by Prince213** [comment]
> what are the reasons to prefer one specific convention over another specific convention?

Well, Rakudo is being actively developed **at GitHub**, and GFM is supported by many editors.

**Comment by Altai-man** [comment]
I guess this is a small change, let's make it into a release and then see if anyone objects.

**Comment by k-mx** [comment]
Yes. I better undo url changes and keep only backticks. Okay?
