### ISSUE TITLE
Split string numeric coercions fail on some numeric operations

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#4315]
## The Problem

It seems like some *Str to numeric coercions aren't successful after some of the recent Str.split refactoring.

Causing failures in some modules. 

Golf:

    my ($whole, $frac) = < -1000.1 >.split('.'); say $whole.abs;

## Expected Behavior

    1000

## Actual Behavior

    Can only perform big integer operations on concrete objects␤  in block <unit> at <tmp> line 1

## Steps to Reproduce

As above.

See:  https://gist.github.com/b3b9b96e65699227dd11d95402b81b44

https://github.com/rakudo/rakudo/commit/c5057e86adc17c3fcdf400edc6df9d5be3877e87

## Environment
* Operating system: Linux Mint 20.1 Cinnamon
* Compiler version (`perl6 -v` or `raku -v`): Bleed HEAD

    raku -v
> Welcome to Rakudo(tm) v2021.03-158-gda80b57cf.
> Implementing the Raku(tm) programming language v6.d.
> Built on MoarVM version 2021.03-39-gba124ad12.

**Comment by thundergnat** [comment]
Another recent change in behavior which is not as easy to run through bisectable:

trim() sometimes doesn't return the correct numeric value.  

Not sure if it is related but the change appeared about the same time.

A specific command is now failing for me which never used to. I haven't been able to golf it to different bisectable command.  

    echo 4 | raku -e'my $r = trim prompt; say $r.abs'

returns

    0

but (no trim)

    echo 4 | raku -e'my $r = prompt; say $r.abs'

returns

    4

Both used to return <code>4</cpde>

**Comment by dogbert17** [comment]
The offending commit seems to be https://github.com/rakudo/rakudo/commit/ffcda8457dd502babfa006691bade2c3854308da
