### ISSUE TITLE
Combination of trim and numeric coercion sometimes fails

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#4316]
## The Problem

It seems like some of the recent refactoring to .trim causes some issues with numeric coercion.
 
    my $r = trim < 4 >; say $r.abs

## Expected Behavior

    4

## Actual Behavior

    0

## Steps to Reproduce

    bisect: old=2021.02 new=HEAD my $r = trim < 4 >; say $r.abs
> <bisectable6> thundergnat, Bisecting by output (old=2021.02 new=a68d257) because on both starting points the exit code is 0
> <bisectable6> thundergnat, bisect log: https://gist.github.com/84dcdd2ed8d2689b968eaf5ecb08198b
> <bisectable6> thundergnat, (2021-04-10) https://github.com/rakudo/rakudo/commit/ffcda8457dd502babfa006691bade2c3854308da

## Environment
* Operating system: Linux Mint 20.1 Cinnamon
* Compiler version (`perl6 -v` or `raku -v`):

     raku -v

> Welcome to Rakudo(tm) v2021.03-158-gda80b57cf.
> Implementing the Raku(tm) programming language v6.d.
> Built on MoarVM version 2021.03-39-gba124ad12.

**Comment by thundergnat** [comment]
I rather suspect that this and issue #4315 have uncovered an problem with .abs that was not apparent before the refactor since it seems to be a key component of both failures.

**Comment by lizmat** [comment]
Golfed to:

    dd trim val("4\n");  # IntStr.new(0, "4"), should be just "4"

**Comment by lizmat** [comment]
FWIW, all `Str` methods need testing of how subclasses of `Str` are handled if they return anything `Str` like, especially in combination with allomorphs.  I intend to dedicate a whole new test file for that shortly, probably before the release.
