### ISSUE TITLE
Problem with sprintf on an Enum

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4321]
## The Problem

The following is currently failing on Rakudo blead:

```
enum Str ( :Free<f>, :Inuse<n> );
note "ok %s".sprintf: Free;

```

Noticed in PDF module, PDF::IO::Writer class.

## Expected Behavior

output: ` ok f`

## Actual Behavior

```
elems requires a concrete object (got a VMNull type object instead)
   at SETTING::src/core.c/Rakudo/Internals.pm6:1450  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:HANDLE-NQP-SPRINTF-ERRORS)
 from SETTING::src/core.c/Cool.pm6:528  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Cool.pm6:527  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Cool.pm6:523  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Cool.pm6:532  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:sprintf)
 from SETTING::src/core.c/Cool.pm6:521  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:sprintf)
 from SETTING::src/core.c/Cool.pm6:386  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:sprintf)
 from /tmp/tst.raku:2  (<ephemeral file>:<unit>)
 from /tmp/tst.raku:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1946  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2151  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2111  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:109  (/home/david/git/rakudo/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2036  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<entry>)
```

## Steps to Reproduce
`raku --ll-exception tst.raku` 

## Environment
* Operating system: Linux toshiba 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2021.03-170-gb1556cbad.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.03-39-gba124ad12.

**Comment by lizmat** [comment]
Is there a particular reason why you'd want to name that enum `Str`?  Naming it something else will at least provide a workaround.

**Comment by dwarring** [comment]
@lizmat 
Oops didn't twig, I'd done that. Happy to change the name.

**Comment by dwarring** [comment]
I'd written `enum Str ( :Free<f>, :Inuse<n> );` when I intended to write something like `my Str enum ObjectType ( :Free<f>, :Inuse<n> );`, which I just changed it to now, which is fine.

So 'user error' I guess :)

**Comment by lizmat** [comment]
Well, it does expose an exotic failure mode, so I'm going to spend some more time on that :-)

**Comment by Altai-man** [comment]
Bisected to https://github.com/rakudo/rakudo/commit/a68d2579f2b3ac295d34d1daa63a3b59a3df9ff1

**Comment by lizmat** [comment]
Removed the BLOCKER label, as this problem only appears to occur if something else called `Str` is in scope.  Nonetheless, I'll probably have this fixed before the release.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/11bab01313a2c82d360ac0539a8d9f931bbf3b68
