### ISSUE TITLE
Build failure error msgs are LTA

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4328]
## The Problem

When building Rakudo and a parse error is found, a cascading set of error messages are shown that give little help for debugging. Today I had such a problem and the opening message gave a brief hint of a symbol and a line number, but no specific pointer to the actual source file.

Thanks to help from @lizmat, who suggested looking at file 'gen/moar/CORE.c.setting', I was able to see the code I recognized and could fix the error. As it turned out, the line number from the error message was exactly correct for that file.

In addition, if I had been paying more attention, I would have seen that the errors were immediately following a line that said 'Compiling gen/moar/CORE.c.setting', but that was overshadowed by the following messages.

...TO BE COMPLETED WITH MORE DETAILS...

**Comment by lizmat** [comment]
FWIW, I think this is part of the torture of the core developers for the fun and profit of the users.  Welcome to the core team  :-)

Seriously, bootstrapping is hard.  And I welcome anybody who would be able to provide better error messages.  But I'm not going to get into that anymore  :-)

**Comment by tbrowder** [comment]
Well, I have helped improve the dev docs in the past, and I just found again a big missing piece of the puzzle. See my last web-editor change.

The *make --trace* is what is not really obvious dependng on what one's build routine is.
