### ISSUE TITLE
`grab` on an empty `SetHash` dies (but only if it had content at some point)

### ISSUE THREAD

**Issue by jnthn** [rakudo/rakudo#4332]
# The Problem

I wrote this:

```
‌‌my %unmakred is SetHash = @all-nodes;
while %unmakred.grab -> $n {
    visit($n);
}
```

And it died with `Iteration past end of iterator`. The most obvious golf was:

```
my %unmakred is SetHash;
while %unmakred.grab -> $n {
}
```

But curiously, that doesn't exhibit the problem; there had to be something in there previously. So this is the minimal golf:

```
my %unmakred is SetHash = 1, 2;
while %unmakred.grab -> $n {
    say $n;
}
```

## Expected Behavior

```
2
1
```

Or:

```
1
2
```

## Actual Behavior

```
2
1
Iteration past end of iterator
  in block <unit> at REPL evaluation line 1
```

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v` or `raku -v`): v2021.03-31-g932685f50

**Comment by jnthn** [comment]
> Expected Behavior

I guess I could say more about how I expect that. Probably it's a bit like `shift`, we I expect a `Failure`, which then gets disarmed by the boolean test done by the `while`.

If that's decided upon and implemented, it'd be good to add it to the docs also (or make a docs issue so that can happen); they currently don't opine on this.

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/dffc2a4cec

**Comment by lizmat** [comment]
For a number of years now, it has been returning `Nil`, at least for the `BagHash` and `MixHash` case.  So I'm a bit reluctant to start changing that to a `Failure` now.

**Comment by jnthn** [comment]
That's an unfortunate inconsistency, but I agree any such change needs to be carefully planned and perhaps language versioned (and we don't yet have the infrastructure to do that with methods).

**Comment by lizmat** [comment]
I'm not sure it is an inconsistency.  Things in general are a bit different with `QuantHash`es.  If anything, you could argue we need another "meta" value, as we can't grab `Nil` from a `SetHash` currently (well, we could, but we'd think it would be empty).
