### ISSUE TITLE
SlippyIterator.is-deterministic() fails on fresh instance

### ISSUE THREAD

**Issue by b2gills** [rakudo/rakudo#4335]
## The Problem

```raku
(1..100).map(*+2).iterator.is-deterministic;
# No such method 'is-deterministic' for invocant of type 'Any'
#   in block <unit> at <unknown file> line 1
```

The `Iterator` in that case is `Any::IterateOneWithoutPhasers` which gets its `.is-deterministic()` from `Rakudo::SlippyIterator`

```raku
say (1..100).map(*+2).iterator.^name;
# Any::IterateOneWithoutPhasers
say (1..100).map(*+2).iterator.can('is-deterministic').head.package.^name;
# Rakudo::SlippyIterator
```

The cause is that `$!slip-iter` is not defined until `.start-slip($)` is called at least once.

Even ignoring that, `.slip-one()` will eventually set `$!slip-iter` to `nqp::null`.

I'm not sure what a _correct_ fix would be.

A simple fix would be for `.is-deterministic()` to check that `$!slip-iter` is defined first.

```raku
    method is-deterministic(--> Bool:D) { defined $!slip-iter ?? $!slip-iter.is-deterministic !! ??? }
```

Where `???` is replaced by a sensible value.

## Environment
* Compiler version (`perl6 -v` or `raku -v`):
    ```
    Welcome to Rakudo(tm) v2021.03-183-g600bb6b06.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2021.03-50-g948128995.
    ```

**Comment by lizmat** [comment]
After thinking some more about this, I think the only sensible thing is to return `False`, as multiple slips can be done by the same iterator object.  And the "outside" needs to know in *advance* whether it is deterministic or not.  But it cannot know that for sure, so we cannot know whether the produced values will be deterministic.

**Comment by lizmat** [comment]
Since the SlippyIterator is an implementation detail, I don't think roast will need tests for this.

**Comment by jnthn** [comment]
> Since the SlippyIterator is an implementation detail, I don't think roast will need tests for this.

Indeed, the `Iterator` role is spec, but not concrete implementations of it are (and normal language use should never see somebody coming across a concrete instance of it anyway, given we always pass `Seq` around).
