### ISSUE TITLE
Blin 2021.04, round 2

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#4339]
[Blin](https://github.com/Raku/Blin) results between 2021.03 ([5816696](https://github.com/rakudo/rakudo/commit/581669614a34d8c1cdaec5ff2ebd9a1004f3cd7c)) and HEAD ([ea10288](https://github.com/rakudo/rakudo/commit/ea102883d2c8033380964f5897465df9fdaaca15)):

* [ ] [GTK::Simple](https://modules.raku.org/dist/GTK::Simple) – Fail, Bisected: [4e4c485](https://github.com/rakudo/rakudo/commit/4e4c485660d302ce5ea1d799a8455bc260d1f8ed)
  <details><Summary>Old Output</summary>

  ```
  ===> Searching for: GTK::Simple
  ===> Found: GTK::Simple:ver<0.1.14> [via Zef::Repository::LocalCache]
  ===> Building: GTK::Simple:ver<0.1.14>
  [GTK::Simple] Command: /tmp/whateverable/rakudo-moar/581669614a34d8c1cdaec5ff2ebd9a1004f3cd7c/bin/rakudo-m -e require '/home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536/Build.pm'; ::('Build').new.build('/home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536') ?? exit(0) !! exit(1);
  [GTK::Simple] Found system gtk library.
  ===> Building [OK] for GTK::Simple:ver<0.1.14>
  ===> Testing: GTK::Simple:ver<0.1.14>
  [GTK::Simple] t/01-sanity.t ....... skipped: (no reason given)
  [GTK::Simple] t/99-author-meta.t .. ok
  [GTK::Simple] All tests successful.
  [GTK::Simple] Files=2, Tests=1, 123 wallclock secs ( 0.03 usr  0.01 sys + 101.34 cusr  8.83 csys = 110.21 CPU)
  [GTK::Simple] Result: PASS
  ===> Testing [OK] for GTK::Simple:ver<0.1.14>
  ===> Installing: GTK::Simple:ver<0.1.14>
  ===> Install [OK] for GTK::Simple:ver<0.1.14>

  ```
  </details>
  <details>
  <summary>New Output</summary>

  ```
  ===> Searching for: GTK::Simple
  [31m===[0mSORRY![31m===[0m Error while compiling /home/vrurg/src/Raku/Blin/installed/GTK::Simple_0.1.14/sources/50B47329D2090162A6668228DFB55E6996716FF2 (GTK::Simple)
  ===SORRY!===
  Arg count 2 doesn't equal required operand count 1 for op 'hllize'

  at /home/vrurg/src/Raku/Blin/installed/GTK::Simple_0.1.14/sources/50B47329D2090162A6668228DFB55E6996716FF2 (GTK::Simple):8

  ===> Found: GTK::Simple:ver<0.1.14> [via Zef::Repository::Ecosystems<p6c>]
  ===> Fetching [OK]: GTK::Simple:ver<0.1.14> to /home/vrurg/src/Raku/Blin/data/zef-data/tmp/1619220087.366644.4062.798437092895/GTK-Simple.git
  ===> Extraction [OK]: GTK::Simple to /home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git
  ===> Building: GTK::Simple:ver<0.1.14>
  [GTK::Simple] Command: /tmp/whateverable/rakudo-moar/ea102883d2c8033380964f5897465df9fdaaca15/bin/rakudo-m -e require '/home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536/Build.pm'; ::('Build').new.build('/home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536') ?? exit(0) !! exit(1);
  [GTK::Simple] Found system gtk library.
  ===> Building [OK] for GTK::Simple:ver<0.1.14>
  ===> Testing: GTK::Simple:ver<0.1.14>
  [GTK::Simple] [31m===[0mSORRY![31m===[0m Error while compiling /home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536/t/01-sanity.t
  [GTK::Simple] [31m===[0mSORRY![31m===[0m Error while compiling /home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536/lib/GTK/Simple.pm6 (GTK::Simple)
  [GTK::Simple] ===SORRY!===
  [GTK::Simple] Arg count 2 doesn't equal required operand count 1 for op 'hllize'
  [GTK::Simple] at /home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536/lib/GTK/Simple.pm6 (GTK::Simple):8
  [GTK::Simple] at /home/vrurg/src/Raku/Blin/data/zef-data/store/GTK-Simple.git/a3a4fc3adafc872dbfc07caa08d11486f551f536/t/01-sanity.t:4
  [GTK::Simple] t/01-sanity.t ....... 
  [GTK::Simple] Dubious, test returned 1 (wstat 256, 0x100)
  [GTK::Simple] No subtests run 
  [GTK::Simple] t/99-author-meta.t .. ok
  [GTK::Simple] Test Summary Report
  [GTK::Simple] -------------------
  [GTK::Simple] t/01-sanity.t     (Wstat: 256 Tests: 0 Failed: 0)
  [GTK::Simple]   Non-zero exit status: 1
  [GTK::Simple]   Parse errors: No plan found in TAP output
  [GTK::Simple] Files=2, Tests=1, 61 wallclock secs ( 0.03 usr  0.01 sys + 48.18 cusr  2.70 csys = 50.92 CPU)
  [GTK::Simple] Result: FAIL
  ===> Testing [FAIL]: GTK::Simple:ver<0.1.14>
  [GTK::Simple] Failed to get passing tests, but continuing with --force-test
  ===> Installing: GTK::Simple:ver<0.1.14>
  ===> Install [FAIL] for GTK::Simple:ver<0.1.14>: [31m===[0mSORRY![31m===[0m Error while compiling /home/vrurg/src/Raku/Blin/installed/GTK::Simple_0.1.14/sources/50B47329D2090162A6668228DFB55E6996716FF2 (GTK::Simple)
  ===SORRY!===
  Arg count 2 doesn't equal required operand count 1 for op 'hllize'

  at /home/vrurg/src/Raku/Blin/installed/GTK::Simple_0.1.14/sources/50B47329D2090162A6668228DFB55E6996716FF2 (GTK::Simple):8


  ```
  </details>
* [ ] [November](https://modules.raku.org/dist/November) – Fail, Bisected: [ea10288](https://github.com/rakudo/rakudo/commit/ea102883d2c8033380964f5897465df9fdaaca15)
  <details><Summary>Old Output</summary>

  ```
  ===> Searching for: November
  WARNINGS for /tmp/6Pq7B_P33E/sources/8A0D556DF8BB38DEC211C8C73A146D81B16143FD (November::Tags):
  Useless use of "-        " in expression "-        $fh.say( $index.perl )" in sink context (line 116)
  ===> Found: November [via Zef::Repository::LocalCache]
  ===> Installing: November
  ===> Install [OK] for November

  1 bin/ script [generate-password.pl] installed to:
  /tmp/6Pq7B_P33E/bin
  WARNINGS for /tmp/6Pq7B_P33E/sources/54F73AF46D559A480D4D2FCB6A96C373DCA347D6 (Test::InputOutput):
  Useless use of $expected in sink context (line 25)
  Useless use of $input in sink context (line 25)

  ```
  </details>
  <details>
  <summary>New Output</summary>

  ```
  ===> Searching for: November
  WARNINGS for /home/vrurg/src/Raku/Blin/installed/November_*/sources/8A0D556DF8BB38DEC211C8C73A146D81B16143FD (November::Tags):
  Useless use of "-        " in expression "-        $fh.say( $index.perl )" in sink context (line 116)
  The following packages were stubbed but not defined:
      November

  ===> Found: November [via Zef::Repository::Ecosystems<p6c>]
  ===> Fetching [OK]: November to /home/vrurg/src/Raku/Blin/data/zef-data/tmp/1619217905.256146.1360.3779474704436/november.git
  ===> Extraction [OK]: November to /home/vrurg/src/Raku/Blin/data/zef-data/store/november.git
  ===> Installing: November
  ===> Install [FAIL] for November: WARNINGS for /home/vrurg/src/Raku/Blin/installed/November_*/sources/8A0D556DF8BB38DEC211C8C73A146D81B16143FD (November::Tags):
  Useless use of "-        " in expression "-        $fh.say( $index.perl )" in sink context (line 116)
  The following packages were stubbed but not defined:
      November


  ```
  </details>

| Status                    | Count |          Modules          |
| :------------------------ | :---: | :------------------------ |
| UnhandledException        |     1 | [Foo::Foo](https://modules.raku.org/dist/Foo::Foo) |
| Flapper                   |     1 | [Smack](https://modules.raku.org/dist/Smack) |
| Fail                      |     2 | [GTK::Simple](https://modules.raku.org/dist/GTK::Simple) [November](https://modules.raku.org/dist/November) |
| MissingDependency         |     6 | [DBIx::NamedQueries](https://modules.raku.org/dist/DBIx::NamedQueries) [HTTP::Server::Router::YAML](https://modules.raku.org/dist/HTTP::Server::Router::YAML) [Intl::Fluent](https://modules.raku.org/dist/Intl::Fluent) [META6::Query](https://modules.raku.org/dist/META6::Query) [Task::Galaxy](https://modules.raku.org/dist/Task::Galaxy) [Web::App::MVC](https://modules.raku.org/dist/Web::App::MVC) |
| ZefFailure                |     7 | [Cro::SSL](https://modules.raku.org/dist/Cro::SSL) [DB::Pg](https://modules.raku.org/dist/DB::Pg) [DateTime::TimeZone](https://modules.raku.org/dist/DateTime::TimeZone) [Games::BubbleBreaker](https://modules.raku.org/dist/Games::BubbleBreaker) [SOAP::Client](https://modules.raku.org/dist/SOAP::Client) [Test::Time](https://modules.raku.org/dist/Test::Time) [Web::Scraper](https://modules.raku.org/dist/Web::Scraper) |
| InstallableButUntested    |     8 | [HTTP::Server::Async](https://modules.raku.org/dist/HTTP::Server::Async) [IO::Socket::Async::SSL](https://modules.raku.org/dist/IO::Socket::Async::SSL) [IRC::Client](https://modules.raku.org/dist/IRC::Client) [Log::Minimal](https://modules.raku.org/dist/Log::Minimal) [MoarVM::Remote](https://modules.raku.org/dist/MoarVM::Remote) [Time::Duration](https://modules.raku.org/dist/Time::Duration) [Toaster](https://modules.raku.org/dist/Toaster) [Uzu](https://modules.raku.org/dist/Uzu) |
| CyclicDependency          |    10 | [Algorithm::HierarchicalPAM](https://modules.raku.org/dist/Algorithm::HierarchicalPAM) [Algorithm::LBFGS](https://modules.raku.org/dist/Algorithm::LBFGS) [Algorithm::LDA](https://modules.raku.org/dist/Algorithm::LDA) [Algorithm::LibSVM](https://modules.raku.org/dist/Algorithm::LibSVM) [Chart::Gnuplot](https://modules.raku.org/dist/Chart::Gnuplot) [Foo::Dependencies::A-on-B](https://modules.raku.org/dist/Foo::Dependencies::A-on-B) [Foo::Dependencies::B-on-A](https://modules.raku.org/dist/Foo::Dependencies::B-on-A) [Foo::Dependencies::Self](https://modules.raku.org/dist/Foo::Dependencies::Self) [Geo::Hash](https://modules.raku.org/dist/Geo::Hash) [MeCab](https://modules.raku.org/dist/MeCab) |
| AlwaysFail                |   318 | ⋯                         |
| OK                        |  1274 | ⋯                         |

This run started on 2021-04-24T00:39:47Z and finished in ≈2 hours.

**Comment by Altai-man** [comment]
It was decided `GTK::Simple` is wrong and relies on internals, a patch was done, and `November` is a known false positive broken years ago.
