### ISSUE TITLE
some minor issue with the 2021.04 version?

### ISSUE THREAD

**Issue by wtwt5237** [rakudo/rakudo#4346]
I successfully installed the 2021.04 version. It works for the most part. But I noticed one thing. When I type "raku" in the command line to go into the interactive mode, some random characters appeared on the screen:

[twang6@Nucleus005 ~]$ raku
Welcome to 痧黏甬皎?
                    ?v2021.04.
Implementing the 痧黏甬?
                        ?programming language v6.d.
Built on MoarVM version 2021.04.

^[[?1;2c^[[?1;2cTo exit type 'exit' or '^D'
> 1;2c1;2c

My environment: 

* Operating system:
[twang6@Nucleus005 zef]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

* Compiler version (`perl6 -v` or `raku -v`):
[twang6@Nucleus005 zef]$ raku -v 
Welcome to Rakudo(tm) v2021.04.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.

**Comment by jonathanstowe** [comment]
It looks like the terminal isn't handling unicode characters very well.

Could you past the output of:

```
echo LANG=$LANG && echo TERM=$TERM
```
?

**Comment by wtwt5237** [comment]
@jonathanstowe Thanks a lot! 

The output is: 

[twang6@Nucleus005 ~]$ echo LANG=$LANG && echo TERM=$TERM
LANG=en_US.UTF-8
TERM=xterm

My terminal works very well with the prior versions of raku

Tao

**Comment by vrurg** [comment]
@wtwt5237 looks weird as there is really no changes were committed which would affect the output. Can you try rakudo 2021.03 and tell if there is difference? Just to make sure that it's same terminal, same environment and only rakudo versions are different.

**Comment by jonathanstowe** [comment]
Also is there any chance that you are running this in e.g. `tmux` or `screen` as they don't seem to handle it very well either.

**Comment by wtwt5237** [comment]
@vrurg, I just tried 21.03 and found the same problem.

I am sure there is one prior version which didn't have this problem. I tested the interactive mode when I installed that version. But I cannot remember which one. But I really do not have time to look into this now. I am really sorry

Tao

**Comment by vrurg** [comment]
@wtwt5237 Then my wild guess would be that you talk about a version prior to the one where the unicode chars were introduced. If you never seen it like this before:

```
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.04.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
```

then we talk here about the setup of your terminal. Locale is unlikely to have any impact on what you see because it only tells Rakudo that it can use unicode in its output. But it is up to the terminal itself how to interpret and display it. My other wild guess would be that yours interpret UTF8 in favor of multi-byte hieroglyphs.

**Comment by lizmat** [comment]
Probably fixed with https://github.com/rakudo/rakudo/commit/5e1c97bae6  Closing issue now, please re-open if this didn't fix.
