### ISSUE TITLE
Test in t/02-rakudo/reproducible-builds.t passes unsupported named argument 'bin' to spurt

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4362]
## The Problem
The test for sameness of checksums of two precompilations in https://github.com/rakudo/rakudo/blob/816281b915/t/02-rakudo/reproducible-builds.t#L46 passes the named argument ```bin``` to ```spurt```.  If that code path is hit, it dies with
```
Unexpected named argument 'bin' passed
   at SETTING::src/core.c/io_operators.pm6:177  (/path/to/rakudo/blib/CORE.c.setting.moarvm:spurt)
 from SETTING::src/core.c/io_operators.pm6:161  (/path/to/rakudo/blib/CORE.c.setting.moarvm:spurt)
 from t/02-rakudo/reproducible-builds.t:46  (<ephemeral file>:)
 from t/02-rakudo/reproducible-builds.t:43  (<ephemeral file>:)
 from t/02-rakudo/reproducible-builds.t:41  (<ephemeral file>:<unit>)
 from t/02-rakudo/reproducible-builds.t:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1946  (/path/to/rakudo_installdir/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2151  (/path/to/rakudo_installdir/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2111  (/path/to/rakudo_installdir/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:109  (/path/to/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2036  (/path/to/rakudo_installdir/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/path/to/rakudo/rakudo.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/path/to/rakudo/rakudo.moarvm:<mainline>)
 from <unknown>:1  (/path/to/rakudo/rakudo.moarvm:<main>)
 from <unknown>:1  (/path/to/rakudo/rakudo.moarvm:<entry>)
```

(I cheated and changed ```or do {``` to ```and do {``` to easily get the failure mode. But the problem would pop up if the test fails for real.)

Probably there was an earlier version of ```spurt``` that supported ```:bin```. I'm not sure what the correct invocation should be nowadays.

## Environment
* Operating system: FreeBSD 11.3-RELEASE-p6
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2021.04-25-g8d37210ee.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04-45-g799afa7cb.

**Comment by lizmat** [comment]
```
method bytecode(--> Buf:D) { ... }
```

So, `.bytecode` is supposed to return a `Buf`, so `spurt` will do the right thing already, so the `:bin` can just go (it was previously just ignored in the `sub spurt` case).
