### ISSUE TITLE
Copying an empty shaped array results in a null object

### ISSUE THREAD

**Issue by raydiak** [rakudo/rakudo#4363]
```
raku -e 'my @a[1]; my @b[1]; @a = @b; dd @a'
Cannot call method 'raku' on a null object
  in block <unit> at -e line 1
```

This bug manifests regardless of the number or size of dimensions. Bisected to a1d8e9385b727ad06196c85dd4fc8569246719c6 in 2016.11

**Comment by lizmat** [comment]
```
$ raku -e 'my str @a[1]; my str @b[1]; @a = @b; say @a'
MultiDimArray: atpos expected string register
```

Another manifestation.  Does not seem to happen with native `int` and `num` arrays, but I guess that's because they *do* have the memory completely allocated on creation already.

**Comment by lizmat** [comment]
The latter turned out to be a thinko in the native shaped array generator script.

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/eebf73bb88
