### ISSUE TITLE
method substr-rw on allomorph types does not seem to be working

### ISSUE THREAD

**Issue by stoned** [rakudo/rakudo#4369]
## The Problem

With a current rakudo the substr-rw method on allomorph types does not seem to be working.

## Expected Behavior
```
$ raku -e 'my $s = <42>; $s.substr-rw(0,1) = "3"; say $s'
32
```

## Actual Behavior

```
$ raku -e 'my $s = <42>; $s.substr-rw(0,1) = "3"; say $s'
Too many positionals passed; expected 1 to 3 arguments but got 4
  in block <unit> at -e line 1
```

## Environment
* Operating system: Fedora 33 x86_64
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo(tm) v2021.04-34-g8e933613c.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04-61-geaccd19ae.
```

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/1d8d05f5bc

**Comment by Altai-man** [comment]
It seems the commit had a typo and referred to wrong ID, closing.
