### ISSUE TITLE
Blin 2021.05, round 1

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#4375]
[Blin](https://github.com/Raku/Blin) results between 2021.04 ([33c589c](https://github.com/rakudo/rakudo/commit/33c589c682123a9bd60ad04752bbdaa4e8beb2d0)) and HEAD ([face292](https://github.com/rakudo/rakudo/commit/face292a07f2ceffc00ce5c5f4350297b9e60316)):

* [ ] [Cro::HTTP](https://modules.raku.org/dist/Cro::HTTP) – Fail, Bisected: [face292](https://github.com/rakudo/rakudo/commit/face292a07f2ceffc00ce5c5f4350297b9e60316)
  <details><Summary>Old Output</summary>

  ```
  ===> Searching for: Cro::HTTP
  ===> Found: Cro::HTTP:ver<0.8.5> [via Zef::Repository::LocalCache]
  ===> Testing: Cro::HTTP:ver<0.8.5>
  [Cro::HTTP] t/http-auth-basic-with-session.t .. ok
  [Cro::HTTP] t/http-auth-basic.t ............... ok
  [Cro::HTTP] t/http-auth-webtoken-bearer.t ..... ok
  [Cro::HTTP] t/http-auth-webtoken-cookie.t ..... ok
  [Cro::HTTP] t/http-client.t ................... ok
  [Cro::HTTP] t/http-cookie.t ................... ok
  [Cro::HTTP] t/http-cookiejar.t ................ ok
  [Cro::HTTP] t/http-custom-methods.t ........... ok
  [Cro::HTTP] t/http-log-file.t ................. ok
  [Cro::HTTP] t/http-middleware.t ............... ok
  [Cro::HTTP] t/http-rawbodyparserselector.t .... ok
  [Cro::HTTP] t/http-request-parser.t ........... ok
  [Cro::HTTP] t/http-request-serializer.t ....... ok
  [Cro::HTTP] t/http-request.t .................. ok
  [Cro::HTTP] t/http-response-parser.t .......... ok
  [Cro::HTTP] t/http-response-serializer.t ...... ok
  [Cro::HTTP] t/http-response.t ................. ok
  [Cro::HTTP] t/http-router.t ................... ok
  [Cro::HTTP] t/http-server.t ................... ok
  [Cro::HTTP] t/http-session-inmemory.t ......... ok
  [Cro::HTTP] t/http-session-persistent.t ....... ok
  [Cro::HTTP] address already in use
  [Cro::HTTP] t/http2-client.t .................. ok
  [Cro::HTTP] t/http2-frame-parser.t ............ ok
  [Cro::HTTP] t/http2-frame-serializer.t ........ ok
  [Cro::HTTP] t/http2-frame.t ................... ok
  [Cro::HTTP] t/http2-push-promise.t ............ ok
  [Cro::HTTP] t/http2-request-parser.t .......... ok
  [Cro::HTTP] t/http2-request-serializer.t ...... ok
  [Cro::HTTP] t/http2-response-parser.t ......... ok
  [Cro::HTTP] t/http2-response-serializer.t ..... ok
  [Cro::HTTP] t/http2.t ......................... ok
  [Cro::HTTP] t/router-auth.t ................... ok
  [Cro::HTTP] t/uri-http.t ...................... ok
  [Cro::HTTP] All tests successful.
  [Cro::HTTP] Files=33, Tests=1645, 422 wallclock secs ( 0.58 usr  0.08 sys + 377.06 cusr 28.39 csys = 406.11 CPU)
  [Cro::HTTP] Result: PASS
  ===> Testing [OK] for Cro::HTTP:ver<0.8.5>
  ===> Installing: Cro::HTTP:ver<0.8.5>
  ===> Install [OK] for Cro::HTTP:ver<0.8.5>

  ```
  </details>
  <details>
  <summary>New Output</summary>

  ```
  ===> Searching for: Cro::HTTP
  ===> Found: Cro::HTTP:ver<0.8.5> [via Zef::Repository::Ecosystems<cpan>]
  ===> Fetching [OK]: Cro::HTTP:ver<0.8.5> to /home/vrurg/src/Raku/Blin/data/zef-data/tmp/1621607062.1142997.6566.90667098055/cro-http-0.8.5.tar.gz
  ===> Extraction [OK]: Cro::HTTP to /home/vrurg/src/Raku/Blin/data/zef-data/store/cro-http-0.8.5.tar.gz
  ===> Testing: Cro::HTTP:ver<0.8.5>
  [Cro::HTTP] t/http-auth-basic-with-session.t .. ok
  [Cro::HTTP] t/http-auth-basic.t ............... ok
  [Cro::HTTP] t/http-auth-webtoken-bearer.t ..... ok
  [Cro::HTTP] t/http-auth-webtoken-cookie.t ..... ok
  [Cro::HTTP] t/http-client.t ................... ok
  [Cro::HTTP] t/http-cookie.t ................... ok
  [Cro::HTTP] t/http-cookiejar.t ................ ok
  [Cro::HTTP] t/http-custom-methods.t ........... ok
  [Cro::HTTP] t/http-log-file.t ................. ok
  [Cro::HTTP] t/http-middleware.t ............... ok
  [Cro::HTTP] t/http-rawbodyparserselector.t .... ok
  [Cro::HTTP] t/http-request-parser.t ........... ok
  [Cro::HTTP] t/http-request-serializer.t ....... ok
  [Cro::HTTP] t/http-request.t .................. ok
  [Cro::HTTP] t/http-response-parser.t .......... ok
  [Cro::HTTP] t/http-response-serializer.t ...... ok
  [Cro::HTTP] t/http-response.t ................. ok
  [Cro::HTTP] t/http-router.t ................... ok
  [Cro::HTTP] t/http-server.t ................... ok
  [Cro::HTTP] t/http-session-inmemory.t ......... ok
  [Cro::HTTP] t/http-session-persistent.t ....... ok
  [Cro::HTTP] address already in use
  [Cro::HTTP] t/http2-client.t .................. ok
  [Cro::HTTP] t/http2-frame-parser.t ............ ok
  [Cro::HTTP] t/http2-frame-serializer.t ........ ok
  [Cro::HTTP] t/http2-frame.t ................... ok
  [Cro::HTTP] # Failed test 'Got the expected 1 push promise'
  [Cro::HTTP] # at t/http2-push-promise.t line 47
  [Cro::HTTP] # expected: '1'
  [Cro::HTTP] #      got: '0'
  [Cro::HTTP] No such method 'target' for invocant of type 'Any'
  [Cro::HTTP]   in block  at t/http2-push-promise.t line 48
  [Cro::HTTP]   in block <unit> at t/http2-push-promise.t line 8
  [Cro::HTTP] t/http2-push-promise.t ............ 
  [Cro::HTTP] Dubious, test returned 1 (wstat 256, 0x100)
  [Cro::HTTP] Failed 1/1 subtests 
  [Cro::HTTP] t/http2-request-parser.t .......... ok
  [Cro::HTTP] t/http2-request-serializer.t ...... ok
  [Cro::HTTP] t/http2-response-parser.t ......... ok
  [Cro::HTTP] t/http2-response-serializer.t ..... ok
  [Cro::HTTP] t/http2.t ......................... ok
  [Cro::HTTP] t/router-auth.t ................... ok
  [Cro::HTTP] t/uri-http.t ...................... ok
  [Cro::HTTP] Test Summary Report
  [Cro::HTTP] -------------------
  [Cro::HTTP] t/http2-push-promise.t          (Wstat: 256 Tests: 1 Failed: 1)
  [Cro::HTTP]   Failed test:  1
  [Cro::HTTP]   Non-zero exit status: 1
  [Cro::HTTP]   Parse errors: No plan found in TAP output
  [Cro::HTTP] Files=33, Tests=1640, 341 wallclock secs ( 0.63 usr  0.05 sys + 300.66 cusr 20.31 csys = 321.65 CPU)
  [Cro::HTTP] Result: FAIL
  ===> Testing [FAIL]: Cro::HTTP:ver<0.8.5>
  [Cro::HTTP] Failed to get passing tests, but continuing with --force-test
  ===> Installing: Cro::HTTP:ver<0.8.5>
  ===> Install [OK] for Cro::HTTP:ver<0.8.5>

  ```
  </details>
* [ ] [November](https://modules.raku.org/dist/November) – Fail, Bisected: [face292](https://github.com/rakudo/rakudo/commit/face292a07f2ceffc00ce5c5f4350297b9e60316)
  <details><Summary>Old Output</summary>

  ```
  ===> Searching for: November
  WARNINGS for /tmp/iA7IA2hqrI/sources/8A0D556DF8BB38DEC211C8C73A146D81B16143FD (November::Tags):
  Useless use of "-        " in expression "-        $fh.say( $index.perl )" in sink context (line 116)
  ===> Found: November [via Zef::Repository::LocalCache]
  ===> Installing: November
  ===> Install [OK] for November

  1 bin/ script [generate-password.pl] installed to:
  /tmp/iA7IA2hqrI/bin
  WARNINGS for /tmp/iA7IA2hqrI/sources/54F73AF46D559A480D4D2FCB6A96C373DCA347D6 (Test::InputOutput):
  Useless use of $expected in sink context (line 25)
  Useless use of $input in sink context (line 25)

  ```
  </details>
  <details>
  <summary>New Output</summary>

  ```
  ===> Searching for: November
  WARNINGS for /home/vrurg/src/Raku/Blin/installed/November_*/sources/8A0D556DF8BB38DEC211C8C73A146D81B16143FD (November::Tags):
  Useless use of "-        " in expression "-        $fh.say( $index.perl )" in sink context (line 116)
  The following packages were stubbed but not defined:
      November

  ===> Found: November [via Zef::Repository::Ecosystems<p6c>]
  ===> Fetching [OK]: November to /home/vrurg/src/Raku/Blin/data/zef-data/tmp/1621605881.1074610.9887.274018836424/november.git
  ===> Extraction [OK]: November to /home/vrurg/src/Raku/Blin/data/zef-data/store/november.git
  ===> Installing: November
  ===> Install [FAIL] for November: WARNINGS for /home/vrurg/src/Raku/Blin/installed/November_*/sources/8A0D556DF8BB38DEC211C8C73A146D81B16143FD (November::Tags):
  Useless use of "-        " in expression "-        $fh.say( $index.perl )" in sink context (line 116)
  The following packages were stubbed but not defined:
      November


  ```
  </details>

| Status                    | Count |          Modules          |
| :------------------------ | :---: | :------------------------ |
| UnhandledException        |     1 | [Foo::Foo](https://modules.raku.org/dist/Foo::Foo) |
| Fail                      |     2 | [Cro::HTTP](https://modules.raku.org/dist/Cro::HTTP) [November](https://modules.raku.org/dist/November) |
| Flapper                   |     3 | [IO::Handle::Rollover](https://modules.raku.org/dist/IO::Handle::Rollover) [Shell::Piping](https://modules.raku.org/dist/Shell::Piping) [Smack](https://modules.raku.org/dist/Smack) |
| MissingDependency         |     6 | [DBIx::NamedQueries](https://modules.raku.org/dist/DBIx::NamedQueries) [HTTP::Server::Router::YAML](https://modules.raku.org/dist/HTTP::Server::Router::YAML) [Intl::Fluent](https://modules.raku.org/dist/Intl::Fluent) [META6::Query](https://modules.raku.org/dist/META6::Query) [Task::Galaxy](https://modules.raku.org/dist/Task::Galaxy) [Web::App::MVC](https://modules.raku.org/dist/Web::App::MVC) |
| ZefFailure                |     7 | [Concurrent::BoundedChannel](https://modules.raku.org/dist/Concurrent::BoundedChannel) [DB::Pg](https://modules.raku.org/dist/DB::Pg) [DateTime::TimeZone](https://modules.raku.org/dist/DateTime::TimeZone) [Games::BubbleBreaker](https://modules.raku.org/dist/Games::BubbleBreaker) [SOAP::Client](https://modules.raku.org/dist/SOAP::Client) [Test::Time](https://modules.raku.org/dist/Test::Time) [Web::Scraper](https://modules.raku.org/dist/Web::Scraper) |
| InstallableButUntested    |     8 | [HTTP::Server::Async](https://modules.raku.org/dist/HTTP::Server::Async) [IO::Socket::Async::SSL](https://modules.raku.org/dist/IO::Socket::Async::SSL) [IRC::Client](https://modules.raku.org/dist/IRC::Client) [Log::Minimal](https://modules.raku.org/dist/Log::Minimal) [MoarVM::Remote](https://modules.raku.org/dist/MoarVM::Remote) [Time::Duration](https://modules.raku.org/dist/Time::Duration) [Toaster](https://modules.raku.org/dist/Toaster) [Uzu](https://modules.raku.org/dist/Uzu) |
| CyclicDependency          |    10 | [Algorithm::HierarchicalPAM](https://modules.raku.org/dist/Algorithm::HierarchicalPAM) [Algorithm::LBFGS](https://modules.raku.org/dist/Algorithm::LBFGS) [Algorithm::LDA](https://modules.raku.org/dist/Algorithm::LDA) [Algorithm::LibSVM](https://modules.raku.org/dist/Algorithm::LibSVM) [Chart::Gnuplot](https://modules.raku.org/dist/Chart::Gnuplot) [Foo::Dependencies::A-on-B](https://modules.raku.org/dist/Foo::Dependencies::A-on-B) [Foo::Dependencies::B-on-A](https://modules.raku.org/dist/Foo::Dependencies::B-on-A) [Foo::Dependencies::Self](https://modules.raku.org/dist/Foo::Dependencies::Self) [Geo::Hash](https://modules.raku.org/dist/Geo::Hash) [MeCab](https://modules.raku.org/dist/MeCab) |
| AlwaysFail                |   314 | ⋯                         |
| OK                        |  1294 | ⋯                         |

This run started on 2021-05-21T16:21:08Z and finished in ≈2 hours.

**Comment by lizmat** [comment]
`[Cro::HTTP] address already in use`   that feels like a testing artefact?

**Comment by Altai-man** [comment]
I am sure Cro case is a false positive, given it bisects to innocent HEAD (though I'll check it manually, of course).
As expected, there are no new serious issues, given we don't have a great deal of commits this time. Thanks for your efforts!
