### ISSUE TITLE
`Git for Bash` has no TTY, so raku opens in "non-interactive" mode

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#4378]
## The Problem

running "raku" inside git bash hangs - the REPL never appears

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

```
$ raku --version
Welcome to Rakudo(tm) v2021.04-22-g87d019f07.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.
```

**Comment by lizmat** [comment]
What does `raku -e 'say $*IN.t'` say?

**Comment by raiph** [comment]
Similar problem for `cygwin` on Windows 8. For some further details, see [my comment about this on SO](https://stackoverflow.com/questions/67744623/raku-repl-appears-unresponsive-on-cygwin-under-windows-8#comment119761746_67744623).

**Comment by leobm** [comment]
Hi @coke @lizmat, 
what I found interestingly is that if I use as git bash as terminal in Visual studio code, raku runs without problems. Then even the unicode character set is displayed correctly.


```
{
    "terminal.integrated.shell.windows": "D:\Program Files\Git\bin\bash.exe",
}
```

**Comment by sumanstats** [comment]
Even typing `python` in the git bash won't bring `python` interpreter. And `Ctrl+C` won't exit the repl. We have to explicitly close the git bash. So I think its not a `raku` specific issue.
![raku](https://user-images.githubusercontent.com/8075886/125487169-038ebc87-2bdc-47ca-be15-94097fbee6ef.gif)

**Comment by lizmat** [comment]
Has anybody tried running with `--repl-mode=interactive` ?

**Comment by ab5tract** [comment]
> It seems this is an issue in Git Bash. If it actually is, then I think we shouldn't try to implement bandaids on our side.

Agreed. However, we should probably throw an exception explaining that the repl cannot run in the current environment instead of hanging.

**Comment by patrickbkr** [comment]
Do I understand correctly, that the REPL has a non-interactive mode that is active when we don't have a terminal attached? (I'd be curious what the use case is for that.)
If so and if we want to keep that functionality, then I think we'll have a hard time differentiating the broken Git Bash situation from a legitimate non-interactive REPL situation.

**Comment by raiph** [comment]
@lizmat:

> Has anybody tried running with --repl-mode=interactive ?

I presume this is [ a repeat of and/or you haven't forgotten ] the comments under your answer to the SO "[raku REPL appears unresponsive on `cygwin` under WIndows 8](https://stackoverflow.com/questions/67744623/raku-repl-appears-unresponsive-on-cygwin-under-windows-8)" from 2021:

> @ikegami: The issue to which you linked is about the "git bash" environment, which is MSYS (or MSYS2?) This is a unix-emulation environment very similar to Cygwin. **It's not surprising the issue affects both**.

> Right, but why do I need to press enter twice do get the result of `1+1` or even `1` when executed with `raku --repl-mode=interactive` ?

> @ikegami: Probably related.

**Comment by ab5tract** [comment]
This appears to be a well-documented problem with "Bash for Git". The recommended solution is to run under `winpty`.

> Do I understand correctly, that the REPL has a non-interactive mode that is active when we don't have a terminal attached? (I'd be curious what the use case is for that.)
If so and if we want to keep that functionality, then I think we'll have a hard time differentiating the broken Git Bash situation from a legitimate non-interactive REPL situation.

Assuming that a flag is required for a non-interactive mode, there is no problem in distinguishing. But looking at the REPL code, I don't see any obvious mentions of a non-interactive mode anyway.

**Comment by ab5tract** [comment]
This is a common issue with `Git for Bash`. The options are:

- Invoke `raku` via `winpty`, ie `winpty raku`
- Re-install `Git for Bah` and enable the option to wrap a "real" Windows terminal

There is no buggy behavior here, either. **`raku` is not "hanging"**, it is in 'non-interactive' mode and waiting for input and an `EOF`. Upon `EOF` the input will be compiled and run. That's the mode that `raku` starts in when it's started outside of a TTY.

**Comment by ikegami** [comment]
> There's no clean way to detect the difference between `echo "say 'hello'" | raku` and running `raku` in a sub-functional `Git for Bash` console.

Really? Because you definitely can in Cygwin.

```
$ perl -Mv5.14 -e'say -t STDIN ? 1 : 0'
1

$ echo foo | perl -Mv5.14 -e'say -t STDIN ? 1 : 0'
0
```

So people could start using that instead. Or WSL. WSL2 is a full Linux virtual machine that runs on Windows.

**Comment by ab5tract** [comment]
@ikegami Both of your examples are using `perl -e`.

**Comment by ikegami** [comment]
It doesn't matter what program I used. My example shows that it it's trivially possible in Cygwin--it's just a call it `isatty`-- so it's surprising that it's not possible in "Git bash" (which uses the similar MSYS, or maybe MSYS2 now). But it at least provides a workaround.

**Comment by ab5tract** [comment]
> My post was about "`$*IN.t` will be `False` [...] in Git for Bash's console"
> 
> It doesn't matter what program I used. My example shows that it it's trivially possible in Cygwin--it's just a call it `isatty`-- so it's surprising that it's not possible in "Git bash" (which uses the similar MSYS, or maybe MSYS2 now). But it at least provides a workaround.

You're correct, the program doesn't matter and your example shows the return from calling `isatty` (naturally, this is the same as `$*IN.t`). But it's not exactly saying what you 

The issue is that `Git for Bash` is not a true TTY. `$*IN.` will be `False`. But we can't do anything to correct this or print out a message about using `winpty` because there is no way to distinguish the difference between:

```
# Git for Bash (or anywhere that isn't a TTY)
> raku
```

(this opens in the same behavior as `perl` without `-e`, waiting for EOF..`$*IN.t` will be `False` because `raku` only opens in this mode when `isatty` is falsey),
and: 

```
# Everywhere
> echo 'say $*IN.t' | raku
False
```

Thus we cannot distingusih between this corner case in `Git for Bash` because it matches the expected behavior of `raku` when it is started where `isatty` is false.

**Comment by ikegami** [comment]
I take back what I said, Cygwin has the same issue when you run bash from a command console. It's not really a workaround, except that it makes it easy to use a "proper" terminal

**Comment by ikegami** [comment]
I deleted the post I just made. It was incorrect.

**Comment by ikegami** [comment]
> Thus we cannot distingusih this corner case in Git for Bash because it matches the expected behavior of raku when it is started where isatty is false.

I know. I just said it's weird that it is the case for MSYS and not for Cygwin.
