### ISSUE TITLE
raku REPL doesn't display unicode "welcome to rakudo"

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#4379]
## The Problem

in cmd and powershell prompts, running the REPL doesn't display the unicode welcome message.

## Actual Behavior

Before setting ```chcp 65001```, we get mojibake. After setting the codepage, we get missing character glyph for the unicode characters.

Unable to find a system font that works. 

Either need to provide directions to windows users with recommended fonts, or potentially avoid use of unicode in the REPL announcement.

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):
* 
```
$ raku --version
Welcome to Rakudo(tm) v2021.04-22-g87d019f07.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.
```

**Comment by lizmat** [comment]
How could we recognize Windows when in pure nqp?

**Comment by ugexe** [comment]
a terrible way would be to create a file using an illegal name (like `NUL`) containing at least one byte and then slurping it to see if it contains what is expected

**Comment by leobm** [comment]
> ## The Problem
> in cmd and powershell prompts, running the REPL doesn't display the unicode welcome message.
> 
> ## Actual Behavior
> Before setting `chcp 65001`, we get mojibake. After setting the codepage, we get missing character glyph for the unicode characters.
> 
> Unable to find a system font that works.
> 
> Either need to provide directions to windows users with recommended fonts, or potentially avoid use of unicode in the REPL announcement.
> 
> ## Environment
> * Operating system:
> * Compiler version (`perl6 -v` or `raku -v`):
> 
> ```
> $ raku --version
> Welcome to Rakudo(tm) v2021.04-22-g87d019f07.
> Implementing the Raku(tm) programming language v6.d.
> Built on MoarVM version 2021.04.
> ```
Hi, 
I see this here in my windows Terminal:
![raku](https://user-images.githubusercontent.com/25712/121401818-7ceb4d80-c959-11eb-8968-639b1ffcfde6.png)

I have also tried different fonts. The font in the terminal is called "DejaVu Sans Mono". The font is actually a unicode font as far as I know.

**Comment by patrickbkr** [comment]
@lizmat Do you have any concrete plan of attack?

**Comment by leobm** [comment]
@lizmat I don't know if this helps you. interestingly, when I open a terminal in Visual studio code, in my case Powershell, then the Unicode characters are displayed correctly. Oh, if I open normal raku in PowerShell (so not out of VS Code), then strangely still is displayed incorrectly. So somehow VS code still does something different with the standard output.
![raku2](https://user-images.githubusercontent.com/25712/121559590-001ea900-ca17-11eb-93b2-970ebdea7767.png)

**Comment by lizmat** [comment]
Should be fixed with https://github.com/rakudo/rakudo/commit/5e1c97bae6 .  Closing now, please re-open if you think there's something wrong still.
