### ISSUE TITLE
Mismatch between "?(any(...) ~~ value)" and "given (any(...)) {when (value)...}"

### ISSUE THREAD

**Issue by fecundf** [rakudo/rakudo#4386]
## The Problem

A junction on the left side doesn't match a value in "when", even when it matches with a simple ?( ... ~~ ...) check.
Example-

> ? (any(4,3) ~~ 3)
True
> given any(4,3) { when 3 {say '3'}; say 'nope'}
nope

## Expected Behavior

Last line should say '3' matching the '?(any(4,3) ~~ 3)' return value

## Steps to Reproduce
Code snippet at the top of this request, plus environment below, should suffice.

There's a full discussion at https://www.nntp.perl.org/group/perl.perl6.users/2021/05/msg9961.html

Bruce Gray's comment "This looks very version dependent, and I would not have expected it to be version dependent at all" makes me think adding this case to Rakudo's test suite is a good idea.

## Environment
* Operating system: macOS 11.4
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to Rakudo(tm) v2021.04.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.

**Comment by raiph** [comment]
cf Raku/problem-solving#297

**Comment by vrurg** [comment]
Addressed by #4698
