### ISSUE TITLE
[not a bug] Is it normal that <!space> matches empty string but not word characters ?

### ISSUE THREAD

**Issue by florian-pe** [rakudo/rakudo#4388]
## The Problem

I am not sure this is a bug, maybe I just misinterpreted the semantics, but this is still unexpected.

<!space> doesn't have the same semantics as Perl5 \S  (non whitespace)

<!space> matches an empty string
raku -e 'say "" ~~ /<!space>/'
｢｣
<!space> matches but doesn't capture
raku -e 'say "abc" ~~ /<!space>/'
｢｣

## Expected Behavior

It shouldn't match an empty string, and capture "abc", right ?

## Environment
* Operating system: 

Linux archlinux 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux

* Compiler version (`perl6 -v` or `raku -v`):

Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.

**Comment by pmichaud** [comment]
In a regex, any angle bracket expression that begins with a punctuation symbol is non-capturing.  Thus ```<!space>``` doesn't capture.

Since the first character of "abc" isn't a space character, the request for ```<!space>``` succeeds, and the regex succeeds having not matched any characters.

It's correct to say that ```<!space>``` doesn't have the same semantics as Perl 5's ```\S``` expression (nor does it have the same semantics as Perl 6's ```\S``` expression either).

I suggest closing this tick as "not a bug".

Pm

**Comment by florian-pe** [comment]
Ah yes, thank you for clarifying, I forgot the non-capturing behavior
Florian

**Comment by florian-pe** [comment]
By the way, I listened a FLOSS podcast (#140) 3 days ago where you were interviewed about Perl6, and it was awesome ! Great work that you did.

**Comment by jnthn** [comment]
> Thus `<!space>` doesn't capture.

Furthermore, it also is zero width. I think `<-space>` is maybe what was wanted here (well, other than `\S`); that doesn't create a named capture `space`, but it does consume a character if `space` doesn't match at that point.

**Comment by florian-pe** [comment]
Yes it does, thanks ! I "verified" it. I wrote a little script that goes through the main ascii characters and color those that match, so that I can check the syntax of character class, and \S and <-space> does color the same sets of characters.

There is also something that I failed to mention, doing this

raku -e 'say "abc" ~~ /<!space>*/'
or this
raku -e 'say "abc" ~~ /<!space>+/

make an INFINITE LOOP

**Comment by jnthn** [comment]
> makes an INFINITE LOOP

Is that a surprise? It's a zero width assertion, meaning it makes no progress through the string, and it will always match; is the regex equivalent of writing `my $pos = 0; while $pos < 3 { }` or some such. It may warrant a warning..

**Comment by florian-pe** [comment]
I opened a new issue specific to that problem
https://github.com/rakudo/rakudo/issues/4390

But frankly there many little things that I don't understand about the syntax like
if <!space> is a zero-width assertion, is is a negative look behind or a negative look ahead ?

And whatever that is, why the regex doesn't do the same as the equivalent (I think) perl regex.

RAKU (does not end)
```
raku -e 'say "abc" ~~ /<!space>*/'
```

PERL (ends properly)
```
$ perl -le 'if ("abc" =~ /(?!\s)*/) {print "true"} else {print "false"}'
true

$ perl -le 'if ("abc" =~ /(?<!\s)*/) {print "true"} else {print "false"}'
true
```

**Comment by pmichaud** [comment]
> But frankly there many little things that I don't understand about the syntax like
> if <!space> is a zero-width assertion, is it a negative look behind or a negative look ahead ?
> [...]
> And as I explain in the other issue that I opened, I am really confused by what it means generally when 
> you put an exclamation point after an opening angle bracket.

Technically the ```!``` doesn't imply lookahead or lookbehind (or even "lookaround" semantics) -- the expression ```<!subrule>``` simply means "<subrule> doesn't match/succeed at this position".  It's up to ```<subrule>``` to decide what matching means at the current position in the pattern match.  It can do that by looking ahead, looking behind, or even ignoring the current target altogether and using some other criteria to decide whether to match at that point.

Pm
