### ISSUE TITLE
Unintuitive range behaviour for '12'..'24'

### ISSUE THREAD

**Issue by rassoc** [rakudo/rakudo#4401]
## Expected Behavior

```raku
('12'..'24').Array # => [12 13 14 15 16 17 18 19 20 21 22 23 24]
```

given these:

```raku
'12'.succ.succ.succ                   # => 15 and not 22
('12', '13' ... '24')                 # => (12 13 14 15 16 17 18 19 20 21 22 23 24)
(<12> .. <24>).Array                  # => [12 13 14 15 16 17 18 19 20 21 22 23 24]
"a12b24c" ~~ m:g/\d+/; ($0..$1).Array # => [12 13 14 15 16 17 18 19 20 21 22 23 24]
```
## Actual Behavior
```raku
('12'..'24').Array # => [12 13 14 22 23 24]
```

#### Perl
```perl
print join ' ', '12'..'24' # => 12 13 14 15 16 17 18 19 20 21 22 23 24
```
#### Ruby
```ruby
('12'..'24').to_a # => ["12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24"]
```

## Environment
* Operating system: Linux, Fedora 33
* Compiler version: `2020.07, 6.d`

**Comment by jonathanstowe** [comment]
Because the range is bounded by two _strings_ it is incrementing each character in turn until it reaches the right bound.  This is probably clearer if you consider:

```
raku -e 'say ("ab" .. "cd").list.perl'
("ab", "ac", "ad", "bb", "bc", "bd", "cb", "cc", "cd")
```

What it _doesn't_ do is coerce those string representations of numbers to numbers, which it would appears those other languages do.

Incidentally, and for teh removal of any doubt, in the `(<12> .. <24>)` it is creating a `Range` bounded by two `IntStr` _allomorphs_ and will use the `Int`  values to bound the expanded list.

**Comment by rassoc** [comment]
> until it reaches the right bound

What about this then?
```raku
('a'..'aa').Array # => [a]
```

Perl and Ruby both produce `[a b c d e f g h i j k l m n o p q r s t u v w x y z aa]`.

**Comment by lizmat** [comment]
Larry decided that magic increment would only work on strings of equal length.  Otherwise alphabetic order applies, and `'b'` is greater than `'aa'`.

**Comment by jonathanstowe** [comment]
It's also worth pointing out that in Raku `..` is basically a constructor for a `Range` object, unlike those other languages, if you disagree with the builtin behaviour for certain data types you can define your own.

**Comment by Altai-man** [comment]
Why not just
```
> (12 .. 24).Array
[12 13 14 15 16 17 18 19 20 21 22 23 24]
```
?

**Comment by rassoc** [comment]
While refactoring a non-trivial piece of code, I ended up with something along the lines of this contrived example:

```raku
my ($a, $b) = "a12b24c".comb(/\d+/); # missing .map(*.Int)
my @arr;
@arr[$a..$b]»++;
say @arr; # => [(Any) (Any) (Any) (Any) (Any) (Any) (Any) (Any) (Any) (Any) (Any) (Any) 1 1 1 (Any) (Any) (Any) (Any) (Any) (Any) (Any) 1 1 1]
```

This didn't fail and introduced a not so obvious bug. In this specific case, other languages either complain (at compile-time) or deliver on the DWIM promise.

**Comment by lizmat** [comment]
Using types here would have worked:

``` raku
my Int ($a, $b) = "a12b24c".comb(/\d+/);
# Type check failed in assignment to $a; expected Int but got Str ("12")
```

You can actually have it coerce to int nowadays:

``` raku
my Int() ($a, $b) = "a12b24c".comb(/\d+/);  # automatic coercion to Int
```

**Comment by rassoc** [comment]
Interesting! While browsing rosettacode and stumbling upon the [range expansion example](https://rosettacode.org/wiki/Range_expansion#Raku), I realized that [ranges already handle matches](https://github.com/rakudo/rakudo/blob/cd4a72b6a76f01702663ba03fe6a16c7a6adb219/src/core.c/Range.pm6#L76) and coerce them as one would expect.

```raku
"a12b24c" ~~ m:g/\d+/; ($0..$1).Array.say # => [12 13 14 15 16 17 18 19 20 21 22 23 24]
```

Doesn't this warrant a change regarding the above behaviour?

**Comment by 2colours** [comment]
@rassoc ranges of `Match` objects work at the cost of only supporting numbers. Wanting the same behavior for `Str`s basically means "let's eliminate `Str` ranges altogether and always coerce to numbers". Which would be an option but I'm not sure there is a consensus, or even significant support for a change like this.
