### ISSUE TITLE
Don't exit REPL on Control-C

### ISSUE THREAD

**Issue by dantecatalfamo** [rakudo/rakudo#4402]
## The Problem

In most programming REPLs, pressing CTRL-C will do something like throw an exception or abort the main thread, and create a new line.

In python for example, it raises a `KeyboardInterrupt`. I use this feature all the time when working on interactively. It comes in handy when accidentally creating a loop without an exit condition or unintentionally invoking a long-running function.

## Expected Behavior

Upon hitting CTRL-C raku will raise an exception in the REPL thread or unwind the stack in some way and return to the top level. Then present the user with a new input prompt.

## Actual Behavior

Raku exits immediately

## Steps to Reproduce

Open a `raku` REPL
Hit `ctrl-c`

## Environment
* Operating system: Fedora 34
* Compiler version (`perl6 -v` or `raku -v`):
`This is Rakudo version 2020.07 built on MoarVM version 2020.07`

**Comment by coke** [comment]
in 2022.07, I'm seeing this behavior:

```
$ raku
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.

To exit type 'exit' or '^D'
[0] > say 3
3
[0] > ^CPressed CTRL-c, press CTRL-c again to exit
[0] >
```
Which may be a result of having an optional module installed

**Comment by Altai-man** [comment]
I think the issue is not about it not being immediate, but more about interrupting the currently running code, which is currently NYI.
