### ISSUE TITLE
set-env.sh is failing with whitespaces in $PATH

### ISSUE THREAD

**Issue by itgenie98** [rakudo/rakudo#4419]
## The Problem
The `set-env.sh` script does not work in the WSL (but I think this bug effects any distro that uses whitespaces in paths in $PATH).

## Expected Behavior
That `$(scripts/set-env.sh)` works on WSL based linux distros

## Actual Behavior
`$(scripts/set-env.sh)` exits with following error: `export: not valid in this context: (x86)/Common`

## Steps to Reproduce
- open a WSL shell
- make sure your current $PATH contains an path with whitespaces like `/mnt/d/Program Files/Microsoft VS Code/bin`
- go into the rakudo folder
- execute `$(scripts/set-env.sh)`

## Environment
* Operating system: Debian Buster WSL - Windows 10

**Comment by patrickbkr** [comment]
@itgenie98 Can you please give the `set-env.sh` scipt here a try? https://github.com/patrickbkr/rakudo/blob/fix-4419/tools/build/binary-release/Linux/scripts/set-env.sh

**Comment by itgenie98** [comment]
@patrickbkr sure ^^

sadly it dosnt work.
Shell is bash 5.0.3(1); also dosnt work under zsh 5.7.1

$PATH is `/root/.nimble/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/d/Python39/Scripts/:/mnt/d/Python39/:/mnt/d/Python27/:/mnt/d/Python27/Scripts:/mnt/d/VulkanSDK/1.1.114.0/Bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/d/Program Files/Java/jdk1.8.0_181:/mnt/d/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/d/Program Files/Git/cmd:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/`

Error output (from bash): 
```
root@localhost:/opt/raku/rakudo-moar-2021.05-01# $(scripts/set-env.sh)
bash: export: `(x86)/Common': not a valid identifier
bash: export: `Files/Oracle/Java/javapath:/mnt/d/Python39/Scripts/:/mnt/d/Python39/:/mnt/d/Python27/:/mnt/d/Python27/Scripts:/mnt/d/VulkanSDK/1.1.114.0/Bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/d/Program': not a valid identifier
bash: export: `Files/Java/jdk1.8.0_181:/mnt/d/Program': not a valid identifier
bash: export: `Files/Microsoft': not a valid identifier
bash: export: `Code/bin:/mnt/c/Program': not a valid identifier
bash: export: `(x86)/NVIDIA': not a valid identifier
bash: export: `Corporation/PhysX/Common:/mnt/d/Program': not a valid identifier
bash: export: `Files/Git/cmd:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/"': not a valid identifier
```

**Comment by patrickbkr** [comment]
@itgenie98 I did some digging. I think the way to call that script needs to change. Can you check if `eval $(set-env.sh)` works for you with the script I linked above? (There is a change in that script since my previous post, so make sure you redownload.)

**Comment by itgenie98** [comment]
@patrickbkr Tested it and it works like intended. With `eval $(./scripts/set-env.sh)` everything works now, thanks a lot!
