### ISSUE TITLE
reduce metaoperator and code blocks

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#4423]
Roast specifies that the reduction metaoperator can take a named binary sub instead of an operator with the syntax:

```raku
[[&foo]] <a b c>
```

[S13-overloading](https://github.com/Raku/roast/blob/master/S13-overloading/metaoperators.t#L40-L43).

It does not explicitly state whether the reduction metaoperator can take an inline code block, however.  The current behavior is that a code block works if and only if it's in a function context and it contains **no internal whitespace**.  Thus

```
[[&({$^a+$^b})]] ^9 # OUTPUT: «36»
[[&({$^a + $^b})]] ^9 # --dies--
```
As @raydiak pointed out on IRC, this behavior is caused by [line 3,874](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Grammar.nqp#L3874) in the grammar, which specifies that the reduction metaoperator cannot contain whitespace.

After a fairly lengthy [conversation on IRC](https://colabti.org/irclogger/irclogger_log/raku?date=2021-06-21#l389), I am not sure whether metaoperators are _intended_ to take code blocks.  I believe they are, but I admit that Roast isn't explicit on the matter.  Currently, all metaoperators seem to accept code blocks inside `&()`, and all but reduce seem to allow internal whitespace.  (I say "seem" because I tested a few but not exhaustively).

Thus I believe that the bug is that the reduce metaoperator rejects code blocks that contain internal whitespace.  If so, we should fix that bug and add tests to Roast to clarify that metaoperators should allow code blocks.

In the alternative, if metaoperators shouldn't take code blocks, then the fact that most/all do is the bug (though fixing it could theoretically break code, if anyone is using that feature).

output from Rakudo v2021.05

**Comment by jnthn** [comment]
In general, anything that uses the `variable` rule will accept a contextualizer, which opens the door to sneaking in arbitrary expressions. Thus why one can do things like `"The answer is $(40 + 2)"` and have it work out. It's sometimes a useful escape hatch, and is quite consistently available.

The reduce meta-operator is distinctive in that it shows up in term position, bringing it into conflict with terms, and then is in direct conflict with an array composer. Note the whitespace rule:

```
    regex term:sym<reduce> {
        :my $*IN_REDUCE := 1;
        :my $op;
        <?before '['\S+']'>
```

Is the very first thing that happens, and is how LTM decides whether to consider this term as a potential reduction operator. This does at least bound our lookahead to the number of chars before the next whitespace, which is not too interesting in a theoretical sense, but in a practical one is probably quite effective. The trouble is that loosening it can make things that are not treated as a reduction operator today suddenly become one.

Note that:

> all metaoperators seem to accept code blocks inside &()

May suggest they explicitly do so, but all infix meta-operators can be used with a bracketed infix, which parses a variable inside, which in turn permits a contextualizer, and inside of a contextualizer we accept any term. It's relatively indirect.

**Comment by b2gills** [comment]
The reduce meta op takes an infix operator

```raku
[×] 1..5

1 × 2 × 3 × 4 × 5
```

A subroutine can be used as an infix op if you use `&` and surround it with `[…]`

```raku
sub mult (\l,\r) { l × r }

1 [&mult] 2 [&mult] 3 [&mult] 4 [&mult] 5
```

So obviously you can also use it with the reduce meta op

```raku
[[&mult]] 1..5
```

You know what else you can use as an infix op, anything that can be callable

```raku
my $func = anon sub mult (\l,\r){l×r};

1 [&($func)] 2 [&($func)] 3 [&($func)] 4 [&($func)] 5

[[&($func)]] 1..5
```

A block is something that is Callable

```raku
1 [&({$^a×$^b})] 2 [&({$^a×$^b})] 3 [&({$^a×$^b})] 4 [&({$^a×$^b})] 5
```

So obviously you can use a block in a meta reduce operator

```raku
[[&({$^a×$^b})]] 1..5
```

---

The only reason that it isn't tested is because it is [or should be] obvious that it works.

If you are thinking about traditional languages, then it might not be obvious.

The thing is that Raku is built upon simple composable pieces.  
Which means that we would need to test every single Permutation of the compatible pieces.

It would actually be a special case for it to not work. (One of the goals of the design was to reduce the number of special cases.)

All of which means that it didn't need to be an intended feature by any person, because it was an intended feature by the overarching design.

---

It might be worth testing it so that implementations in the future don't try to go without implementing the language properly.

**Comment by codesections** [comment]
I gave this issue a bit more thought after I [brought it up earlier today on StackOverflow](https://stackoverflow.com/a/69016800/10173009).

@b2gills wrote:
> So obviously you can use a block in a meta reduce operator
> ```raku
> [[&({$^a×$^b})]] 1..5
> ```
> The only reason that it isn't tested is because it is [or should be] obvious that it works.

I tend to agree.  But the exact same logic argues that `[[&({$^a × $^b})]] 1..5` should work, too – but it currently doesn't.  Upon further thought, this feels like a bug rather than a design choice.

On the other hand, I think that @jnthn makes a good point:

>Note the whitespace rule:
```raku
    regex term:sym<reduce> {
        :my $*IN_REDUCE := 1;
        :my $op;
        <?before '['\S+']'>
```
> Is the very first thing that happens, and is how LTM decides whether to consider this term as a potential reduction operator. This does at least bound our lookahead to the number of chars before the next whitespace, which is not too interesting in a theoretical sense, but in a practical one is probably quite effective. The trouble is that loosening it can make things that are not treated as a reduction operator today suddenly become one.

So, is there a way to fix the (imo) bug of disallowing whitespace without slowing parsing too much or breaking existing code?  I have an idea, but I'd like to get feedback on it before opening a PR.

What if we changed `<?before '[' \S+ ']'>` in the rule above to something like `<?before '[' \S+ | [\S* '&' '(' ~ ')' <sequence> \S*] ']' >` ?  That is, a `[ ]` operator is allowed to contain whitespace only if it uses the `&( )` contextualizer.  (Note, I haven't tested that code – it's not (yet) a PR).

That seems like it would allow whitespace in the `[ ]` operator without any of the drawbacks discussed above and thus make Raku just a little more consistent.  On the other hand, the stakes here are very low – we're pretty much talking about, for the example above, being able to write `[[&(* × *)]] 1..5` instead of `reduce(* × *, 1..5)`, which is hardly a dramatic change.  Any thoughts?

**Comment by raiph** [comment]
Fwiw, I recall Larry making comments on IRC making it clear he was aware of this "no spaces" limitation and deliberately accepted it. I don't have time to search the logs right now, indeed won't till next week at the earliest (and can't offhand think of a way to figure out suitable search strings), but it might be worth a few minutes using Liz's awesome new log archive searching features (including Raku regexes!) to find his comments about it.

**Comment by codesections** [comment]
Ah, good memory @raiph.  Here's the relevant bit from the [IRC log](https://logs.liz.nl/perl6/2016-08-02.html#18:19) (cross-talk and line-breaks omitted and for clarity):

```txt
 <pochi>      m: say [&infix:<*>] 1,2,3
 <camelia>    rakudo-moar e1c772: OUTPUT«===SORRY!=== Error while compiling <tmp>␤Two terms in a row␤at […]»
 <TimToady>   m: say [[&infix:<*>]] 1,2,3
 <camelia>    rakudo-moar e1c772: OUTPUT«6␤»
 <pochi>      aha
 <TimToady>   you can't make the [] do two different things.  note also that you can't extend this to any 
              arbitrary lambda because reductions don't allow internal spaces (to help distinguish them 
              from [1, 2, 3] and such
 <unmatched}> TimToady: so that's by design? I saw a ticket last night saying disallowed whitespace is a bug
 <TimToady>   nope
 <perlpilot>  TimToady: what about that earlier [RXZXZR[&say]XXXXXZZZZR~]  ?  It looks like [&whatever] 
              messes up the metas.  Should that be?
 <TimToady>   [&say] is not a meta
 * TimToady channels MJD
 <unmatched}> m: say [RXZXZRXXXXXZZZZR[&say]] <foo bar>
 <camelia>    rakudo-moar e1c772: OUTPUT«barfoo␤(((((((((((((True)))))))))))))␤»
 <TimToady>   yes, the real operator can only come when you're done with the metas
```

So it looks like the prohibition of whitespace is intentional – but the only reason is to prevent confusion with Arrays.  I'm still of the opinion that allowing `&( )` wouldn't risk confusion with Arrays and would make Raku more consistent overall – it's odd that the whitespace in `[[&(* + *)]]` isn't allowed, since whitespace is allowed around `+` in every other context.  And it's downright  bizarre that the whitespace in `[[&(*~" "~*)]]` isn't allowed – I can't think of a single other time where Raku makes a parsing decision based on the whitespace in a _string_.

All that said, given that IRC transcript, I'll probably hold off on a PR until/unless I hear that someone else is also bothered by the whitespace sensitivity.

**Comment by jubilatious1** [comment]
Not a fan of whitespace within metaoperators. Seems there are already other ways to write that code.
