### ISSUE TITLE
No exception handler located for warn

### ISSUE THREAD

**Issue by MARTIMM** [rakudo/rakudo#4430]
## The Problem
The exception `No exception handler located for warn` is thrown when some error takes place such as outputting an undefined variable in an event handler called from a C-Library.  The line number in the stack dump is only pointing to the start of the block wherein the error takes place. Placing a `CATCH {}` block inside just shows the error twice.

## Expected Behavior
Show the proper error on the proper location like
```
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in  at method received at /home/marcel/Languages/Raku/Projects/question-answer/lib/QA/Gui/QAImage.pm6 (QA::Gui::QAImage) line 326.
```

## Actual Behavior
See 'problem' above

## Steps to Reproduce

Cannot golf it down because it disappears when it is simplified. Tried to get more info with `--ll-exception` option to no avail. 

## Environment
* Operating system (uname -a): Linux media-server 5.11.22-100.fc32.x86_64 # 1 SMP Wed May 19 18:58:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2021.05-3-gf83e55116. Implementing the Raku(tm) programming language v6.d. Built on MoarVM version 2021.05.

**Comment by niner** [comment]
FWIW in my callbacks I have blocks like these:
```
CONTROL { 
    when CX::Warn {
        note $_.gist;
        $_.resume;
    }
}
```

**Comment by MARTIMM** [comment]
Thanks very much. It helps to get the proper error and line number
