### ISSUE TITLE
`.split(/<ws>+/)` hangs till out of memory

### ISSUE THREAD

**Issue by rassoc** [rakudo/rakudo#4438]
## The Problem

`say ''.split(/<ws>+/)` hangs till the backend runs out of memory. Both in the REPL and as a file.

Running it in the irc channel yields: `«MoarVM panic: Memory allocation failed; could not allocate 104187424 bytes␤»`

## Expected Behavior

Similar behaviour to `''.split(/<ws>/)`.

## Environment
* Operating system: `Fedora 33`
* Compiler version: `2020.07`

**Comment by colomon** [comment]
Not saying this isn't a bug, but I think that <ws> consumes an arbitrary amount of whitespace on its own, without the + quantifier?

**Comment by rassoc** [comment]
Sure, but it's an easy mistake to make. And the following doesn't cause any problems either:

```raku
> my regex foo { \d+ }
> "10 20 30".comb(/<foo>/)
(10 20 30)
> "10 20 30".comb(/<foo>+/)
(10 20 30)
```

**Comment by colomon** [comment]
That's because \d+ always requires at least one digit, so the first <foo> consumes the entire number and the second <foo> fails right away.  Change foo to \d* and you'll see the same thing happen.

**Comment by rassoc** [comment]
Oh, interesting, thanks for bringing that up.

**Comment by colomon** [comment]
I've been playing around with it, and <ws> has some funky properties. 

```
> "th           is" ~~ /^ "th" <ws><ws><ws> "is" $/
｢th           is｣
 ws => ｢           ｣
 ws => ｢｣
 ws => ｢｣
```

**Comment by colomon** [comment]
Just realized all my `<ws>` in text were consumed, which couldn't have made my explanations easy to read!

**Comment by colomon** [comment]
(Mind you, I'm still inclined to see this as Not A Good Thing -- it's an easy mistake to make, and fails very awkwardly.  But at least if you know what's happening it's easy for you to fix in your code.)

**Comment by pmichaud** [comment]
This is just a reminder that <ws> is allowed to match zero characters,
so quantifying it can indeed result in an infinite loop.

   "The default ws matches zero or more whitespace characters, as long as
   [the current position] is not within a word."  

So, in my book, this is clearly "not a bug" -- it's possible to endless loop
anytime a zero-width assertion gets quantified.

Pm

**Comment by vrurg** [comment]
> (ie the first consumes all the whitespace, and the next two consume none at all.)

Apparently, this is [how greediness works](https://docs.raku.org/language/regexes#Greedy_versus_frugal_quantifiers:_?) .

> I mean, `<ws>` may need to be defined that way, but maybe we could detect that a pattern with an infinite quantifier is repeatedly consuming nothing and die quickly?

I'm afraid this kind of heuristics are way too unreliable. How many times it should repeat before we decide it's time to die? 1000? 10000? But what if user code took some precautions and will take measure to get out of the loop on 10001st repetition?

Similar case was discussed in #4390 quite recently with interesting references to some earlier cases.

For now I think this one can be closed.

**Comment by pmichaud** [comment]
This particular anti-pattern has been discussed many times before, and in many senses I agree that "segfault" isn't the correct behavioral response.

I wouldn't be opposed to heuristic methods of detecting zero-width quantification, provided there's a way to disable the heuristic (or to enable the infinite repeat, or select a different heuristic).

My first heuristic suggestion for discussion would be that any quantifier construct no longer repeats after its sub-expression results in a zero width match.  It would be interesting to implement this in a branch and see how it affects roast.

If this belongs in another ticket or repository, let me know and I'll happily repost it there.

Pm

**Comment by vrurg** [comment]
@pmichaud to me it sounds like a subject for problem-solving because this kind of change to quantifiers behavior might have side effects, possibly – undesirable ones.
