### ISSUE TITLE
Label lost with spesh enabled

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4456]
https://github.com/rakudo/rakudo/commit/d8281722dbf86c3e58378579ca076b8fe3a89fa3 seems to have uncovered a spesh bug (or at least made it easier to reach) related to a labeled `next` and `last` related to `gather`, golfed to:

````raku
for ^475 { gather L: for ^1 { next L } }
````

Necessary parts to make this happen:
- on my hardware, the error occurs reliably from values 475 and up
- `gather` is needed
- the label / labelled `next` or `last` are needed
- does **not** occur with MVM_SPESH_DISABLE=1

**Comment by lizmat** [comment]
Note that https://github.com/rakudo/rakudo/commit/d8281722dbf86c3e58378579ca076b8fe3a89fa3 can be reverted without any problem, as it was only a minor performance change.  But in order to find the issue, I suggest leaving this in until it is necessary to revert the commit for a release.

**Comment by lizmat** [comment]
I think the difference in the d828172 commit, is that it removed an extra level of `nqp::while` structure (which was the point of this change).  So now there's only an `nqp::until` with a `:nohandler`.

So I *think* that before, it was (incorrectly) seeing the other `nqp::until` (which did *not* have a `:nohandler`) for a loop construct.  So I wonder if it was actually doing the right thing before.  It was just not bombing, looks like.

**Comment by ugexe** [comment]
> Note that d828172 can be reverted without any problem, as it was only a minor performance change. But in order to find the issue, I suggest leaving this in until it is necessary to revert the commit for a release.

Note that I reverted the commit last night.

**Comment by lizmat** [comment]
FWIW, to be 100% clear:  I don't think the commit itself is wrong (but please enlighten me if you think it is).  It exposes a problem with spesh more clearly. The golfed code is otherwise (probably) working for the wrong reason.  So I'm a bit disappointed that the commit got reverted.

**Comment by ugexe** [comment]
While everything you say is correct, you are also disregarding the impact of this specific regression

**Comment by lizmat** [comment]
I'm not disregarding the impact, I don't think.  We're still a week away from a release.  And I specifically indicated that it *can* be reverted without any problem.  I was just hoping that someone would have a look at it before the release.  Chances of that happening now, have significantly diminished :-(

**Comment by patrickbkr** [comment]
I think ugexe is concerned about devs on master being unable to install things.

**Comment by ugexe** [comment]
> I think ugexe is concerned about devs on master being unable to install things.

Correct. CI systems and tooling e.g. Blin as well

**Comment by ugexe** [comment]
I've made a minor change to those loops in zef to avoid the issue. This means it should be ok to reintroduce the problem commit as long as we to remember to revert the commit before the release (if it is not otherwise fixed).

**Comment by usev6** [comment]
For the record, there are a couple of tests in S04-statements/for.t for crashes of labeled next in for/map. They were added by @zoffixznet back in 2017-06: https://github.com/Raku/roast/commit/9f418777bc

The comment added with the tests notes that optimizations seem to play a role, so different versions were added. The file looks like a good place to add the new golf(s).

There is a (closed) issue about the problem (https://github.com/Raku/old-issue-tracker/issues/6336) with a (no longer working) to a discussion in #perl6-dev. The discussion seems to start at https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2017-06-13#l47, but there are many related comments from that day.

**Comment by Altai-man** [comment]
As I got it, the offending commit was reverted, so the blocker label can be removed now as well?

**Comment by lizmat** [comment]
The blocker label should be kept, but can be ignored for the 2021.07 release.  I plan on reverting the revert after the release, to make sure that we fix this for the 2021.08 release.

**Comment by lizmat** [comment]
Removed the blocker label now, will add again after the revert of the revert :-)

**Comment by Altai-man** [comment]
Thanks!

**Comment by lizmat** [comment]
Revert reverted.

**Comment by MasterDuke17** [comment]
Fixed by https://github.com/MoarVM/MoarVM/pull/1522

**Comment by 2colours** [comment]
What would it take for this issue to be closable?

**Comment by patrickbkr** [comment]
@2colours I guess adding some tests is the blocker. Quoting usev6:

> For the record, there are a couple of tests in S04-statements/for.t for crashes of labeled next in for/map. They were added by @zoffixznet back in 2017-06: [Raku/roast@9f418777bc](https://github.com/Raku/roast/commit/9f418777bc)
> 
> The comment added with the tests notes that optimizations seem to play a role, so different versions were added. The file looks like a good place to add the new golf(s).

**Comment by lizmat** [comment]
Test added with https://github.com/Raku/roast/commit/9178a972fc
