### ISSUE TITLE
Unexpected unicode character conversion

### ISSUE THREAD

**Issue by mykhal** [rakudo/rakudo#4457]
## The Problem
Some unicode characters are unexpectedly converted to similar ones with different codepoint.

## Expected Behavior
```raku
"\x2329".ord == 0x2329
"\x2329".uniname == "LEFT-POINTING ANGLE BRACKET"
```

## Actual Behavior
```raku
"\x2329".ord == 0x3008
"\x2329".uniname == "LEFT ANGLE BRACKET"
```

## Steps to Reproduce
run the provided examples in raku shell or script

## Environment
* Operating system: Linux
* Compiler version:
  * rakudo MoarVM 2021.06
  * rakudo MoarVM r2021.06.72.g.7.f.5.f.60.e.85

**Comment by mykhal** [comment]
(A bug was found during my occasional Raku documentation verification, see [Raku issue #3917](https://github.com/Raku/doc/issues/3917))

**Comment by mykhal** [comment]
```raku
for (0..0x10FFFF) -> $x {
  next if 0xD800 <= $x <= 0xDFFF; # skip invalid surrogates
  my $y = $x.chr.ord;
  say sprintf("\\x%X => \\x%X", $x, $y) if $x != $y;
}
```

The list is very long, so is it a feature ?

**Comment by jnthn** [comment]
This is correct behavior. The `Str` type uses the [NFG representation](https://docs.raku.org/language/glossary#NFG), the normalization taking place at string construction time. Please open a [docs issue](https://github.com/Raku/doc/issues) noting where you'd have expected to find information on this.

**Comment by mykhal** [comment]
@jnthn : interesting. There are links to chat and blog, direct link to language core spec would be nicer (if it is not written after implementation).

Btw, that conversions do not seem to be 100% correct:

```raku
> "\x2ADC".comb.map({$_.ord.base(16)})
(2ADD)
```

should be 
```
(2ADD 338)
```

but that would be for another issue request.

**Comment by jnthn** [comment]
@mykhal `ord` always returns the first codepoint; I think you're looking for `ords`:

```
> "\x2ADC".ords.map(*.base(16))
(2ADD 338)
```

You won't get it split up using `comb` because it's one grapheme.

**Comment by mykhal** [comment]
There seem to be already existing doc issue: [Raku #3258 No mention of NFG in the docs?](https://github.com/Raku/doc/issues/3258)
