### ISSUE TITLE
New regression: silent failure when attempting to write to a read-only attribute returned from a method

### ISSUE THREAD

**Issue by raydiak** [rakudo/rakudo#4463]
```raku
class C {
    has $.a;
    method b is raw { $.a }
};

my $o = C.new;
$o.b = 42;
say $o.a;
```

This failed with the error `Cannot modify an immutable 'Any' type object` under 2021.06 and earlier, but on master simply prints `(Any)` with no error. Bisectable is a little unclear but I think it my be suggesting dba9f56afa95ef078a5d0e.

**Comment by jnthn** [comment]
dba9f56 should be reverted. Contextualizers should not introduce mutability; it will lead to all manner of confusion (like this issue). Mutability is a risky thing; I consider it a good property of Raku that mutable things tend to come with a sigil to mark them out, thus aiding program comprehension.

The commit aims to make it easier to end up with a symbol without a sigil referring to mutable state. However, that's an ungoal; when `my \foo = ...` was first introduced, the variables declared this way were informally known as "SSA vars" - a name taken from compiler terminology, meaning static single assignment - that is, they are only ever assigned to in one place in the program. It's a little unfortunate that this was erased when they got a simpler name ("sigilless variables"). While Raku having first-class l-values means that one can indeed end up with such a symbol pointing at an l-value, I consider that poor style; I'm certainly not keen to see it made easier.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/dba9f56afa95ef078a5d0eb1cadd516e098d3987 has been reverted.  Closing this now.
