### ISSUE TITLE
how to install in termux aarch64?

### ISSUE THREAD

**Issue by A91K3C1l** [rakudo/rakudo#4481]
how to install in termux aarch64?
I have tried all possible ways the way you are about to give works in my termux, thank you
 Please help me

**Comment by hungrydonkey** [comment]
Please see https://github.com/rakudo/rakudo/issues/3505, it maybe help you:)

**Comment by hungrydonkey** [comment]
> how to install in termux aarch64?
> I have tried all possible ways the way you are about to give works in my termux, thank you
> Please help me

Please see https://github.com/rakudo/rakudo/issues/3505, it maybe help you:)
