### ISSUE TITLE
`{ let @foo = Nil }` doesn't restore `@foo`

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#4499]
# Actual behaviour
```
my $foo = 42;
{ let $foo = Nil }
say $foo;              # 42

my @foo = 42;
{ let @foo = Nil }
say @foo;              # [(Any)]
```

# Expected behaviour

```
my $foo = 42;
{ let $foo = Nil }
say $foo;              # 42

my @foo = 42;
{ let @foo = Nil }
say @foo;              # [42]
```

(See also #1433.)

**Comment by vrurg** [comment]
The behavior should not be expected:

```raku
my @foo;
say (@foo = Nil).defined; # True
```

Basically, the assignment is not necessary as `@foo` is always an `Array` instance in this case.

You get what's expected with:

```raku
my @foo = 42;
{
    let @foo = Nil;
    Nil
}
say @foo; # [42]
```

This irresistible magic of `Nil` enchanted me too for a while until I inserted a `say` statement after the assignment and needed that extra `Nil` to be returned to let the `let` do its work. :)

**Comment by vrurg** [comment]
Closing. #1433 is still of some interest though.

**Comment by raiph** [comment]
Duh! Sorry. And thanks. :)
