### ISSUE TITLE
Negation metaoperator and the custom factorial operator conflict (Raku Documentation snippet)

### ISSUE THREAD

**Issue by georgy7** [rakudo/rakudo#4509]
## The Problem

There is an example of creation the factorial operator in the [docs](https://docs.raku.org/language/optut).

    sub postfix:<!>( Int $num where * >= 0 ) { [*] 1..$num }

## Expected Behavior

    say 5!;            # OUTPUT: «120␤» 

## Actual Behavior

```
===SORRY!=== Error while compiling:
Negation metaoperator not followed by valid infix
at line 3
------> say 5!⏏;
    expecting any of:
        infix
        infix stopper
```

## Steps to Reproduce

Using the interactive Rakudo mode:

```
~ $ rakudo
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
> sub postfix:<!>( Int $num where * >= 0 ) { [*] 1..$num }
&postfix:<!>
> say 5!;
===SORRY!=== Error while compiling:
Negation metaoperator not followed by valid infix
------> say 5!⏏;
    expecting any of:
        infix
        infix stopper
> 
```

## Environment

```
~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

~ $ rakudo -v
This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.
```

**Comment by JJ** [comment]
This is most likely a documentation issue. Let me check, and maybe reopen it there (mentioning you if that's the case). Thanks anyway for the report.

**Comment by JJ** [comment]
OK, I just checked and it works as expected. Is it possible that you're doing this as two different lines in the REPL? This works, as I say:

```raku
sub postfix:<!>( Int $num where * >= 0 ) { [*] 1..$num }; say 5!
```

It should work in the same way in a program (this checked with 2021.07, BTW as well as 2019.11).

**Comment by georgy7** [comment]
Thanks for the quick response.
It really works in one line.
I just can't get used to the fact that it affects.

**Comment by JJ** [comment]
It's due to the default scope of subs, I think.
