### ISSUE TITLE
'map' with side effects not executed

### ISSUE THREAD

**Issue by moon-chilled** [rakudo/rakudo#4514]
```
$ raku -e '[^100].map({$_ ==> map(&say.assuming("a", "b"))})'
(no output)
```

Side-note: if I actually make that execute, it runs _really_ slowly.  This seems to be the fault of `.assuming`?

**Comment by lizmat** [comment]
`.assuming` is notoriously slow because it uses `EVAL` internally.  This should improve much when RakuAST lands.

**Comment by jubilatious1** [comment]
Expected output, please?

**Comment by jubilatious1** [comment]
In the REPL (MoarVM 2023.05):
```perl6
[0] > [^5].map({$_ ==> map(&say.assuming("a", "b"))})
ab0
ab1
ab2
ab3
ab4
((True) (True) (True) (True) (True))
[1] >
