### ISSUE TITLE
Different version control compatibility issues fg yyyy-mm--dd

### ISSUE THREAD

**Issue by ccworld1000** [rakudo/rakudo#4515]
## The Problem
Different version control compatibility issues fg: Date.today.yyyy-mm-dd("/")

## Expected Behavior
Different version control compatibility problems, document comments, or reminders

## Actual Behavior
// error
CC # /Applications/Rakudo/bin/perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

// OK
CC #  /Applications/rakudo-moar-2021.08-01-macos-x86_64-clang/bin/perl6 -v
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.08.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.08.

**Comment by coke** [comment]
Running bisectable on this code snippet points to 

https://github.com/rakudo/rakudo/commit/3017cfea50683beb5765bde2285118059a8507e3

So this was an intentional change; closing ticket.
