### ISSUE TITLE
Why is the bitwise negation of an unsigned integer a signed integer ?

### ISSUE THREAD

**Issue by grondilu** [rakudo/rakudo#4526]
Maybe it's me not understanding integer representations, but anyway :

```
$ raku --version
This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.
$ raku -e 'say +^my uint8 $ = 1'
-2
```

I mean wth.

PS.  ~~Ok apparently C behaves the same~~ (no, see PS#2) :

```
#include "stdio.h"

int main() {
   unsigned char n = 1;
   printf("%d\n", ~n);
   return 0;
}
```

I guess it really is me not understanding what's happening here.  I'll leave this issue opened for a bit in case someone wants to explain stuff.

PS#2.  My bad again, of course with the %d flag it will convert to signed integer, so this is not relevant.

**Comment by niner** [comment]
This is now fixed:
```
> ./rakudo-m -e 'say +^my uint8 $ = 1'
18446744073709551614
```

Would you please be so kind to add a test to roast for this?

**Comment by grondilu** [comment]
fixed, so closing.
