### ISSUE TITLE
Different behavior of applying a role containing `CALL-ME` method in new dispatch

### ISSUE THREAD

**Issue by CIAvash** [rakudo/rakudo#4543]
## The Problem

I tried the latest commit with the new dispatch mechanism on a module I'm working on and some of my tests failed. I golfed it down to the applying a role which has a `CALL-ME` method.

When I add a role which has `CALL-ME` method to a function and call that function, the `CALL-ME` method is not invoked.

## Expected Behavior

The `CALL-ME` method should be invoked. (at least that's the old behavior)

## Actual Behavior

The `CALL-ME` method does not get invoked. (with new dispatch)

## Steps to Reproduce
```raku
&grep does role :: {
    method CALL-ME (|) {
        say 'Got a call';
    }
}

grep(Str);
```

Output in Rakudo 2021.09: Got a call
There is no output with commit dd2b274 (new dispatch)

## Environment
* Operating system: Arch Linux (Linux v5.10.68-1-lts)
* Compiler version (`perl6 -v` or `raku -v`):
Latest commit installed with rakubrew:
Welcome to Rakudo™ v2021.09-228-gdd2b274fd.
Implementing the Raku™ programming language v6.d.
Built on MoarVM version 2021.09-585-gc33111fd6.
and
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.09.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.09.

**Comment by jnthn** [comment]
In the case of the `Routine` being a `proto`, the dispatcher would go ahead with multiple dispatch, regardless of the `CALL-ME` mixin. I've tweaked it to respect the `CALL-ME` mixin now, and added a test in https://github.com/Raku/roast/commit/ca8b1747f4d628b3e9cec9dc2ccf87ad636bb3c1.

Please note that there is no obligation for any program locations that previously called `grep` before you mixed into it to honor the mixin. In general, declarational lexpad entries are considered immutable beyond `CHECK` time; the functionality is being reinstated on the basis that it is fine to, for example, do such a mixin in a trait being applied to a `Routine`.
