### ISSUE TITLE
round() produces incorrect result

### ISSUE THREAD

**Issue by p6steve** [rakudo/rakudo#4546]
## The Problem
round() produces incorrect result

## Expected Behavior
say 12.500000000000002.round(1e-5); #12.5

## Actual Behavior
say 12.500000000000002.round(1e-5); #12.500000000000002

## Steps to Reproduce
in repl (also in raku scripts)
> Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.04.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.04.

To exit type 'exit' or '^D'
> say 12.500000000000002.round(1e-5);
12.500000000000002
> say 12.500000000000002.round(0.001);
12.5
> say 12.500000000000002.round(1e0);
13
> say 12.500000000000002.round(1e-1);
12.5
> say 12.500000000000002.round(1e-2);
12.5
> say 12.500000000000002.round(1e-3);
12.5
> say 12.500000000000002.round(1e-4);
12.5
> say 12.500000000000002.round(1e-5);
12.500000000000002
> say 12.500000000000002.round(1e-6);
12.5

## Environment
* Operating system: M1 MacOS BigSur

**Comment by coke** [comment]
I don't think this is a bug, I think this is normal floating point issues. You're giving a Num to the round function, so it's rounding to a Num, and that you are subject to this issue.

If you instead round to ``0.00001``, you get a Rat back, which does respect the precision.

```
[1] > 12.500000000000002.round(0.00001)
12.5
[2] > 12.500000000000002.round(.00001).^name
Rat
```
