### ISSUE TITLE
Suboptimal typo suggestions

### ISSUE THREAD

**Issue by moon-chilled** [rakudo/rakudo#4552]
```
$ raku -e '"42".matc(/\d/)'
No such method 'matc' for invocant of type 'Str'.  Did you mean any of
these: 'batch', 'Date', 'map', 'Map'?
  in block <unit> at -e line 1
```

I expect for 'match' to be suggested; it seems closer to 'matc' than all the other suggestions (and was in fact what I intended to type).

**Comment by lizmat** [comment]
Thanks for noticing that and reporting it!
