### ISSUE TITLE
Error while compiling "No Such Method 'EXISTS-KEY'" on second instance of use Inline::Python

### ISSUE THREAD

**Issue by ggoebel** [rakudo/rakudo#4557]
## The Problem

Rakudo fails to compile a module when more than one of its sub-modules contains "use Inline::Python".

Golfed down to [this gist](https://gist.github.com/ggoebel/7831a0b2269fce57c4cd366c84e7e164)

Note: if Inline::Python is replaced with Inline::Perl5, then the error goes away.

## Expected Behavior

compile successfully

## Actual Behavior

$ raku -MFoo -I./lib -e 'say "ok"'
===SORRY!=== Error while compiling -e
===SORRY!=== Error while compiling /home/ggoebel/git/test/lib/Foo.rakumod (Foo)
===SORRY!=== Error while compiling /home/ggoebel/git/test/lib/Baz.rakumod (Baz)
No such method 'EXISTS-KEY' for invocant of type 'BOOTHash'.  Did you
mean any of these: 'EXISTS-KEY', 'EXISTS-POS'?
at /home/ggoebel/git/test/lib/Baz.rakumod (Baz):2

at /home/ggoebel/git/test/lib/Foo.rakumod (Foo):3

at -e:1

## Steps to Reproduce

Golfed down to [this gist](https://gist.github.com/ggoebel/7831a0b2269fce57c4cd366c84e7e164)

## Environment
* Operating system: arch linux
* Compiler version: v2021.09-251-gff6951f59

**Comment by lizmat** [comment]
BTW, the minimal golf is:

-------------


Foo.rakumod:
--------------
use Bar;
use Baz;

Bar.rakumod
-------------
use Inline::Python;

Baz.rakumod
-------------
use Inline::Python;

-------------

and doing:

`raku --ll-exception -I. -MFoo -e ''`

**Comment by vrurg** [comment]
I think #4566 fixes the problem.

**Comment by vrurg** [comment]
After re-considering the outcomes of the PR I realized that they're quite expected with the current Rakudo model. So, PR is merged and the issue is, hopefully, resolved.

**Comment by lizmat** [comment]
@ggoebel I think this warrants a new issue in the `Inline::Python` repo, as I think it is something else, most likely an issue in `Inline::Python` itself.
