### ISSUE TITLE
Rakudo SegFaullt in v2021.09-251-gff6951f59

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#4570]
## The Problem

I am attempting to compile code that was working earlier this morning. Made some changes and now I am running into segmentation faults during the Parse phases, which almost certainly indicates something sour in the compiler.

Yes, I am known for making large, inter-project bug reports, but I beg your patience on this one. The repetition steps should cover reproduction of the issue.

At least it's not p6-GLib

## Steps to Reproduce

1) Create directory to house issue
2) Change into this directory
3) git clone https://github.com/Xliff/cro-webapp
4) unzip cro-webapp/BAS.zip
5) cd BizzellAppServer/app
6) raku --stagestats -I ../../cro-webapp/lib -Ilib -e 'use Bizzell::Inventory::Instance'
7) Wait for crash during compilation of Bizzell::Inventory::Instance

## Environment
* Hardware 
- AMD Threadripper 5950x on a B550 Aorus Master
* Operating system:
- uname -a: Linux InfinityV 5.11.0-37-generic 41-Ubuntu SMP Mon Sep 20 16:39:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to Rakudo™ v2021.09-251-gff6951f59.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.09-624-ge733aef88.

**Comment by dogbert17** [comment]
I probably made some mistake but after following the clone repo step I'm unable to find the file BAS.zip. Was it forgotten or is there a step missing in the repro instructions?

**Comment by Xliff** [comment]
*Updated* - I can make the segfault go away by commenting out the contents of the Bizzell::Operators compunit. I don't see why that code is causing a SEGV when it didn't use to, but this means that I can move forward until a better solution can be found.

**Comment by jnthn** [comment]
Fixed with merge of https://github.com/MoarVM/MoarVM/pull/1564.
