### ISSUE TITLE
raku 2021.10 recompiles Grammar every time it is invoked on a new string. 

### ISSUE THREAD

**Issue by wimvanderbauwhede** [rakudo/rakudo#4593]
## The Problem

My [Haku language](https://codeberg.org/wimvanderbauwhede/haku) has a complex Grammar which takes about 60s to compile. When I run a Haku program, the source code is converted into a Raku module which is `require`d. That results in running the program.
Execution times for a set of 13 examples have increased from 70s for 2021.08 and 2021.09 to 993s for 2021.10. 
In 2021.09, on average each example takes about 6s to compile and run, and with 2021.10 it takes about 66s. 

So it looks like the Grammar is recompiled every time a new example is run, even though it has not changed and there is no need to recompile it (and indeed 2021.09 does not recompile it, nor does 2021.08)

## Expected Behavior

Grammar is compiled  only when source has changed

## Actual Behavior

Grammar is compiled every time it is invoked on a new string.

## Steps to Reproduce

- Pull my Haku repo and check out the devel branch:
[https://codeberg.org/wimvanderbauwhede/haku](https://codeberg.org/wimvanderbauwhede/haku)

`% git clone https://codeberg.org/wimvanderbauwhede/haku.git`
`% cd haku`
`% git checkout devel`

- Select the raku version:
`% rakubrew shell moar-2021.10`

- In the main repo folder, run 
`% time ./run-all-examples.sh`

I get the following:
For 2021.10:
```
% rakubrew shell moar-2021.10
% time ./run-all-examples.sh 
Nil
((1 2 3 4 5) (7 8) (11) (13) (16 17))
魄から楽まで
7188
557188
{}
{四十二 => 42}
記憶に心を奪われて
((1 2 3 4 5) (7 8) (11) (13) (16 17))
42
42
忘れられない あの冬の the new fallen snow
大丈夫
42
25
55
55
./run-all-examples.sh  992.54s user 46.72s system 107% cpu 16:07.06 total
```

For 2021.09:
```
% rakubrew shell moar-2021.09
% time ./run-all-examples.sh 
[... omitted ...]
./run-all-examples.sh  69.91s user 12.22s system 112% cpu 1:12.69 total
```

## Environment
* Operating system: macos 11.6
* Compiler version (`perl6 -v` or `raku -v`): 
```
[haku]% raku -v
Welcome to Rakudo™ v2021.10.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10.

[haku]% rakubrew shell moar-2021.09
[haku]% raku -v                    
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.09.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.09.
```

**Comment by MasterDuke17** [comment]
I believe this is actually fixed now. @wimvanderbauwhede can you confirm?

**Comment by lizmat** [comment]
@wimvanderbauwhede closing this issue, assuming this is now fixed.  Please re-open if not.
