### ISSUE TITLE
$/ leaks to outer context

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4601]
Make sure that `words` is a symlink to your words file.

````raku
unit sub MAIN(:$degree = 16, :$batch = 128);

my atomicint $tries = 0;
my atomicint $fails = 0;
"words".IO.lines.race(:$degree, :$batch).map: -> $word {
    my $string := "foo:auth<$word>:bar";
    my $match  := $string.match(/ ':auth<' <( <-[>]>+ /);
    if $match ne $word {
        say "$word -> $match";
        $fails⚛++;
    }
    $tries⚛++;
}
my $percentage := (100 * $fails / $tries).fmt("%.2f");
say "Found $fails failures in $tries tries ($percentage%)";
````

Run this script and you will see a lot of lines with different strings, and typically around 4% failures.

Then run this script with `--degree=1`.  Then there will be no failures.

I have **NO** idea whether this is new-disp related or not.  It could well be that this is an older bug.

**Comment by lizmat** [comment]
Turns out this can be golfed to:

````raku
 for ^10 { $/++ }
say $/;  # 10
````
Apparently, the scope in the `for` loop does **NOT** get its own `$/`.  I'm unclear as to whether that is intended or not, as a bisect shows this behaviour exists since before Christmas 2015.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/1d0a903a88 at least fixes the original example of this issue, as `.match` now returns the match result value, rather than a deconted version of `$/`.

**Comment by jnthn** [comment]
> Apparently, the scope in the for loop does NOT get its own $/.

This is intended behavior: only subroutines get a fresh `$/`. Were blocks to get one too, `if /f(.)/ { say $0 }` would not work, for example.

**Comment by lizmat** [comment]
Closing with documentation patches https://github.com/Raku/doc/commit/c867f164ba and https://github.com/Raku/doc/commit/9b7d8fedc0
