### ISSUE TITLE
regression: interpolating params in heredocs in hashes

### ISSUE THREAD

**Issue by bduggan** [rakudo/rakudo#4614]
## The Problem
```
my %h = a_key => -> $param { %(a => Q:s:to/DONE/); }
this string has $param
DONE
```

The code above -- which makes a hash that has a value which is a function that returns a hash that has a value that's a heredoc that interpolates its parameter -- does not compile on moar-2021.10.  It did compile on 2021.06

## Expected Behavior
```
$ cat bug.raku
my %h = a_key => -> $param { %(a => Q:s:to/DONE/); }

this string has $param

DONE

$ raku -v
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.06.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.06.
$ raku bug.raku
$ 
```
## Actual Behavior
```
$ raku -v
Welcome to Rakudo™ v2021.10.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10.
$ raku bug.raku
===SORRY!=== Error while compiling /Users/bduggan/raku/bug.raku
Variable '$param' is not declared
at /Users/bduggan/raku/bug.raku:3
------> this string has ⏏$param
```
## Steps to Reproduce

Run the code above

## Environment
* Operating system: OS/X
* Compiler version (`perl6 -v` or `raku -v`):
 2021.10

**Comment by jnthn** [comment]
This was a bug fix; see https://github.com/rakudo/rakudo/issues/4539 for details. Nowhere else in Raku are variables visible beyond the closing `}` of the block in which they are declared; heredocs violating that was an implementation accident.

**Comment by bduggan** [comment]
got it!  Thanks for the clarification.
