### ISSUE TITLE
spurt-string throws Failure

### ISSUE THREAD

**Issue by wbiker** [rakudo/rakudo#4619]
## The Problem
Trying to spurt a file in an directory without the proper rights leads to an exception. Handling this exception is not possible with an `or die "message"` or in a `unless` clause. The Failure object is thrown and `or ...`  and `unless ...` are ignored.

## Expected Behavior
In the example below an exception "Hello exception" is expected.

## Actual Behavior
The Failure object is thrown:
```
Failed to open file /test: Permission denied
  in block <unit> at test.raku line 2
```

## Steps to Reproduce
`spurt "/test", "file content test" or die "Hello exception";`
`unless spurt "/test", "file content test" { die "Hello exception" }`

## Environment
* Operating system:
NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

* Compiler version (`perl6 -v` or `raku -v`):
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.08.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.08.

**Comment by lizmat** [comment]
OOC, why the `--> True` signature in `bar`?   That makes the `foo` in `bar` be in sink context.  Remove that signature, and it does what you want.

**Comment by niner** [comment]
@lizmat that's exactly the right question. The issue is actually about spurt-string which contains the `--> True` in its signature, causing failures to explode. The reporter updated the issue to reflect the actual problem.

**Comment by lizmat** [comment]
Aaahh... duh.  Ok, fixing.

**Comment by ab5tract** [comment]
Tests have been add to [roast @ 36dadc1753](https://github.com/Raku/roast/commit/36dadc1753).
