### ISSUE TITLE
IO::Socket::Async.write method is limited to write only 65535 chars

### ISSUE THREAD

**Issue by ramiroencinas** [rakudo/rakudo#4628]
Tested with Debian and Alpine Linux - Rakudo version 2021.10 6.d

**Comment by jonathanstowe** [comment]
It would be good to have some example code that reproduces this.

**Comment by ramiroencinas** [comment]
server.raku:
```raku
react {
  whenever IO::Socket::Async.listen('0.0.0.0',3000) -> $conn {
    whenever $conn.Supply(:bin) -> $data-in {
      my $response = '';
      for 1..66000 {$response = $response ~ 'a';}
      $conn.write: $response.encode('UTF-8'); 
      $conn.close;
    }
  }
}
```
client.raku:
```raku
await IO::Socket::Async.connect('127.0.0.1', 3000).then( -> $promise {
  given $promise.result {
    .print("test\n");
        react {
            whenever .Supply() -> $v {
                say $v.chars;
                done;
            }
        }
        .close;
    }
});
```
```bash
# raku server.raku &
# raku client.raku
# 65535
```

**Comment by jnthn** [comment]
All of the data is being sent by `write`; the problem is that the client is incorrectly implemented here:

```
            whenever .Supply() -> $v {
                say $v.chars;
                done;
            }
```

The `done` here means that the client stops receiving after the first packet. Correcting it so that it receives the entire response:

```
await IO::Socket::Async.connect('127.0.0.1', 3000).then( -> $promise {
  given $promise.result {
    .print("test\n");
        my $resp = '';
        react {
            whenever .Supply() -> $v {
                $resp ~= $v;
            }
        }
        say $resp.chars;
        .close;
    }
});
```

Outputs 66000, as desired.

**Comment by jnthn** [comment]
Ah, I should have also mentioned why this happens: there is a maximum packet size, and anything larger than that will be transmitted over the network as multiple packets.

**Comment by ramiroencinas** [comment]
Thanks jnthn, works fine!, but when I tried to use the server script to response with a http message that exceeds the packet size (I guess 65535 chars) to a web browser client, the problem persists and the web browser client only receive 65535 chars. I think I will need to rethink the server script to response with all the response packets to the web browser client.

**Comment by jnthn** [comment]
Ah, I notice also:

```
      $conn.write: $response.encode('UTF-8'); 
      $conn.close;
```

But `write` is an async operation, so needs an `await` or `whenever`:

```
      whenever $conn.write: $response.encode('UTF-8') {
          $conn.close;
    }
```

**Comment by ramiroencinas** [comment]
Thanks @jnthn!, the http server send all the packets using 
```raku
whenever $conn.write: $response.encode('UTF-8') -> $x { $conn.close; }
```
and the web browser client receives all the packets sended by the server.

I think the documentation at https://docs.raku.org/type/IO::Socket::Async can be improved with this aspect in the server code.

**Comment by jnthn** [comment]
Ouch, yes, it can indeed; please make a [docs issue](https://github.com/Raku/doc/issues/new).
