### ISSUE TITLE
Zef not working on macOS Monterey M1

### ISSUE THREAD

**Issue by librasteve** [rakudo/rakudo#4637]
## The Problem

Hi - I have installed rakudo-moar-2021.10-01-macos-arm64-clang.tar.gz on my 100% clean factory reset Monterey and run eval "$(/Users/stephenroe/rakudo/rakudo-moar-2021.10-01-macos-arm64-clang/scripts/set-env.sh)" successfully

## Expected Behavior

I now expect zef to install some basic things

## Actual Behavior

zef install File::Which --verbose
===> Searching for: File::Which
===> Found: File::Which:ver<1.0.1> [via Zef::Repository::LocalCache]
===> Testing: File::Which:ver<1.0.1>

zef install XML::Writer --verbose
===> Searching for: XML::Writer
===> Found: XML::Writer [via Zef::Repository::LocalCache]
===> Testing: XML::Writer

both of the above commands hang

## Environment
* Operating system: macOS Monterey
* Compiler version (`perl6 -v` or `raku -v`):

Welcome to Rakudo™ v2021.10.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10.

**Comment by ugexe** [comment]
I don't have a M1 on Monterey (so I can't debug this) but it certainly works fine on Big Sur. Honestly I'd be quiet surprised if it has anything to do with zef and not either `prove` or `raku` itself since its getting to the testing just fine.

**Comment by p6steve** [comment]
ah - well all was fine before my Big Sur to Monterey upgrade

I have tried the various flags you recommend - very helpful thanks!

the upshot is "sometimes it works, sometimes it doesn't" - (about 50/50) - my guess is that there is some realtime rakudo dependency on Monterey that is not on Big Sur (eg. race condition) ... sorry I can't be more specific/helpful ... 

I am happy for you to decide to close this issue ... but I will move on to vftools + ubuntu/docker

**Comment by zjmarlow** [comment]
I don't know if this is the right place to note this but `make test` for Rakudo itself is also hanging on Monterey M1.  The few test cases that I looked at that were hanging were using Raku's `run`.  After some playing with one-liners, I found that `raku -e 'run "echo", "hi", :out'` occasionally hangs.  That command seems to run fine in my Debian environment.

**Comment by atroxaper** [comment]
Actually, I have zef hang on Monterey on x86. And it is not only about zef but about any scripts - randomly hang. Probably it is not because of M1.

**Comment by p6steve** [comment]
Oh - I had been **guessing** something like "BigSur = rosetta set to run all dynamic libs called from Terminal.app child processes" to "Monterey = rosetta must be enabled in Terminal.app GetInfo otherwise will just run everything as a binary"

I suppose that's still possible, but less likely, cause if it also impacts Intel Monterey.

But maybe it's more like "compiler shipped with Xcode no longer has xxx headers" or "compiler shipped with Xcode needs these flag settings"

(Obviously) I have no actual idea what I'm talking about!

**Comment by jonathanstowe** [comment]
It's not something like the version of `libuv` needs bumping to play nicely with the new version of MacOS?  There seem to have been several Darwin/MacOS related changes since the `v1.35.0` that is used by moarvm.

**Comment by atroxaper** [comment]
I've tried to update `libuv` to `v1.42.0` (master MoarVM uses `v1.39.0` for now). Unfortunately, the issue does not disappear yet. Maybe it hangs not so frequently, but anyway is it unacceptable often.

**Comment by zjmarlow** [comment]
FWIW, zef seems to be working with Rakudo version 2021.10-129.  Please let me know if I can provide any more information / help verify anything.

**Comment by coke** [comment]
on os x 12.6 on an M2 chip, I'm not seeing these issues.

**Comment by coke** [comment]
Based on latest comments, closing this ticket.
