### ISSUE TITLE
`Type check failed in binding to parameter` for a named param that has not been passed

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#4647]
## The Problem

    sub s(Str :@l, Str :$a) { }; s(:a(1));

## Actual Behavior

    Type check failed in binding to parameter '@l'; expected Positional[Str] but got Array ([])

## Expected Behavior

   Type check failed in binding to parameter '$a'; expected Str but got Int (1)

## Environment
* Compiler version (`perl6 -v` or `raku -v`): v2021.10-91-g4c238bdc9

**Comment by jnthn** [comment]
I believe this needs an matching change in `lower_signature` in `Perl6::Actions`, otherwise it won't fix any of the compiled cases (and thus probably not the original issue).

**Comment by vrurg** [comment]
@jnthn guess, you should've commented on the PR?

**Comment by jnthn** [comment]
@vrurg You are right! Thanks, will add it there.
