### ISSUE TITLE
Feature request: add Module.^dist method

### ISSUE THREAD

**Issue by skaji** [rakudo/rakudo#4656]
## The Problem

Let's say we use `Module` in our script:

```raku
use Module;

my $mod = Module.new;
...
```

Sometimes we want to inspect the distribution which `Module` belongs to,
but currently there is no easy way to do it, I think (please correct me if I'm wrong).

## Expected Behavior

We can easily inspect distributions.

Because we already can touch the distribution information in `Module.rakumod`
by CompUnit::Repository::Distribution `$?DISTRIBUTION`,
how about adding `Module.^dist` method which actually returns `$?DISTRIBUTION` of Module?

## Actual Behavior

There is no easy way to inspect distributions.

## Environment
* Operating system: macOS 10.15.7
* Compiler version (`perl6 -v` or `raku -v`): v2021.10

**Comment by JJ** [comment]
Can you please raise the issue in the [problem solving](https://github.com/Raku/problem-solving) repo? I can move it there if you want. Generally, feature requests and that kind of things to through there first.

**Comment by skaji** [comment]
> Generally, feature requests and that kind of things to through there first.

I should have known that, sorry.

> Can you please raise the issue in the problem solving repo?

Sure.

**Comment by skaji** [comment]
done https://github.com/Raku/problem-solving/issues/306
