### ISSUE TITLE
`shell` / `run` isn't working on macOS Monterey

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#4657]
## The Problem

`raku -e 'shell("ls")'` (with and without variations of `:out`,`:err`,`:!out`,`:!err`) appears stuck 90% of the times I run it (no output, never finishes running) when using macOS Monterey. `run` behaves a bit better in that `run("ls")` always seems to work but `my $p = run("ls", :out); $p.out.close` does occasionally freeze up as well. Because precompilation and the build process use `shell`/`run` it also means installing rakudo can become stuck during the later parts of the installation process.

[This callback](https://github.com/rakudo/rakudo/blob/10c3dbb940290c67af33dfc617b2f8ce6a21df28/src/core.c/Proc/Async.pm6#L357) is not getting fired in the problematic cases.

## Expected Behavior

`raku -e 'shell("ls")'` should consistently show the output of the `ls` command

## Actual Behavior

10% of the time I see the output of the `ls` command. 90% of the time I see nothing and the program never finishes running.

## Environment

* Operating system: MacOS Monterey

* Compiler version (`perl6 -v` or `raku -v`): various

**Comment by ugexe** [comment]
Also see https://github.com/rakudo/rakudo/issues/4637

**Comment by jnthn** [comment]
Based on the stack trace posted on #moarvm earlier, I'm curious:

1. Does `raku -e 'use nqp; say nqp::cpucores'` hang?
2. If not, does the patch below help?

```
diff --git a/src/core.c/ThreadPoolScheduler.pm6 b/src/core.c/ThreadPoolScheduler.pm6
index 929652e..4a1aa1f 100644
--- a/src/core.c/ThreadPoolScheduler.pm6
+++ b/src/core.c/ThreadPoolScheduler.pm6
@@ -534,6 +534,7 @@ my class ThreadPoolScheduler does Scheduler {
     my constant NUM_SAMPLES           = 5;
     my constant NUM_SAMPLES_NUM       = 5e0;
     my constant EXHAUSTED_RETRY_AFTER = 100;
+    my int $cpu-cores = max(nqp::cpucores() - 1,1);
     method !maybe-start-supervisor(--> Nil) {
         unless $!supervisor.DEFINITE {
             $!supervisor = Thread.start(:app_lifetime, :name<Supervisor>, {
@@ -579,7 +580,6 @@ my class ThreadPoolScheduler does Scheduler {
                     + nqp::atpos_i(@rusage, nqp::const::RUSAGE_STIME_MSEC);
 
                 my num @last-utils = 0e0 xx NUM_SAMPLES;
-                my int $cpu-cores = max(nqp::cpucores() - 1,1);
 
                 # These definitions used to live inside the supervisor loop.
                 # Moving them out of the loop does not improve CPU usage
```

**Comment by ugexe** [comment]
> Does raku -e 'use nqp; say nqp::cpucores' hang?

No

> If not, does the patch below help?

Yes

**Comment by melezhik** [comment]
same issue for me. all previously installed `bin/` scripts now hang after upgrade to Monterey.

**Comment by lizmat** [comment]
Then I suggest we merge https://github.com/rakudo/rakudo/pull/4659 before the release.

**Comment by lizmat** [comment]
In the mean time, I have pushed https://github.com/rakudo/rakudo/commit/f029ac8330

**Comment by hughsimpson** [comment]
Same issue for me. Fix works. Thank goodness, thanks for figuring that one out

**Comment by lizmat** [comment]
Could you all check on master just to be 100% sure: it has a slightly adapted version of jnthn's patch.

**Comment by atroxaper** [comment]
I do not see any difference between jnthn's patch and `f029ac8`...

**Comment by lizmat** [comment]
The change is subtle, I agree.

In jnthn's patch, `nqp::cpucores` is always executed at startup.  In my version, it is only executed whenever a supervisor thread is about to be started.  Scripts that do not have any asyncness, then don't have to execute the relatively expensive `nqp::cpucores`.

**Comment by atroxaper** [comment]
I've successfully checked master version on cases:
* `for i in {1..20}; do raku -e 'shell("ls")'; done`
* `for i in {1..20}; do raku -e 'run("ls", :out)'; done`
* `zef install Documentable` (with all dependencies and tests). Release version stucks 100% there.

**Comment by hughsimpson** [comment]
Yep, master also working for me - no longer any weird hanging

**Comment by melezhik** [comment]
can I use homebrew to install master on mac, I guess not?

**Comment by jnthn** [comment]
> In my version, it is only executed whenever a supervisor thread is about to be started.

Are we absolutely sure that this will be executed before any process spawning can take place?

**Comment by atroxaper** [comment]
> can I use homebrew to install master on mac, I guess not?

You can use rakubrew `rakubrew build moar master`

**Comment by lizmat** [comment]
@jnthn Well, no, not 100%: if someone would do an explicit `Thread.start` themselves before doing a `start`, then it would be called after that.

**Comment by lizmat** [comment]
@jnthn: then would making `Kernel.cpu-cores` be lazy and static for the duration of the process be a solution then?  If someone would need to know if anything really has changed, they could use `nqp::cpucores`.  Or we could make a module that would do that, that people could use.

In any case, then make sure that `Thread.start` does a `Kernel.cpu-cores` to make 100% sure it would get called before any thread is started?

**Comment by jonathanstowe** [comment]
> If someone would need to know if anything really has changed

Does rakudo even run on an architecture where the number of cpu cores is dynamic?  (except perhaps for some migration of a running VM between host hardware in say VMWare, I think of this as classic mainframe capability.)

**Comment by niner** [comment]
> Does rakudo even run on an architecture where the number of cpu cores is
> dynamic?  (except perhaps for some migration of a running VM between host
> hardware in say VMWare, I think of this as classic mainframe capability.)

One can turn off (and back on) CPU cores at runtime on Linux. It's as simple 
as echo 0 > /sys/bus/cpu/devices/cpu14/online
I have used this for example to slow my system down when trying to reproduce 
some timing issue.

While the most common use case for CPU hotplug itself is surely VMs these 
days, the Linux capability was developed for actual hardware CPU hotplug. Such 
machines do exist.

**Comment by lizmat** [comment]
Ok, then maybe `Kernel.cpu-cores` should be lazy and static by default (with `Thread.start` doing a `Kernel.cpu-cores` to make sure it is done **before** any thread is started), and a `Kernel.cpu-cores(:refresh)` candidate that **would** always do a `nqp::cpucores` and update the statically kept info?

**Comment by atroxaper** [comment]
I would prefer leave `Kernel.cpu-cores()` as is and add `Kernel.cpu-cores(:last-value)` options to get last evaluated cached value. Then the public API will not be broken but expanded.

**Comment by lizmat** [comment]
`Kernel.cpu-cores(:cached)` would then be more descriptive, I guess?

**Comment by lizmat** [comment]
Implemented as such with https://github.com/rakudo/rakudo/commit/27f8cc5788

**Comment by ugexe** [comment]
I think I’m missing the point of the flag vs just caching the original method return value in a local variable, maybe using an e.g. INIT phaser. I’m assuming this method caching is needed to work around the deadlock for some reason, but if not maybe let’s avoid adding new public api without thinking through if it makes sense outside of this one specific problem we are facing at this one specific moment (no one has ever requested this functionality after all).

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/7c10225bba

**Comment by lizmat** [comment]
FWIW, I know think we're gone through all the possible permutations for a fix, and I think this PR is now finally ready for merge :-)

**Comment by ab5tract** [comment]
This appears to be fixed for quite a while now.
