### ISSUE TITLE
Grep fails with more than 2 args [Regression]

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#4660]
## The Problem

The `grep` routine accepts multiple args.

There appears to have been a recent regression with using more than 2 args.

## Expected Behavior

```raku
> (1..30).pick(*).grep(*>*>*).defined
True
```

## Actual Behavior

```raku
> (1..30).pick(*).grep(*>*>*).defined
Too few positionals passed; expected 5 arguments but got 4
```

## Steps to Reproduce
Bisectable identifies commit bb09bbb8581364f7323ff1f17ab4d84dffbe798c when the issue started, so presumable builds after this commit can reproduce the issue.

## Environment
* Operating system: Ubuntu, Centos
* Compiler version (`perl6 -v` or `raku -v`): v2021.10

**Comment by lizmat** [comment]
This is not a blocker IMHO, as this has been the case since 2021.07: https://github.com/rakudo/rakudo/commit/bb09bbb8581364f7323ff1f17ab4d84dffbe798c
