### ISSUE TITLE
is cached behaves incorrectly when recursion by samewith is used

### ISSUE THREAD

**Issue by lavirlifiliol** [rakudo/rakudo#4665]
## The Problem
this program demostrates the lack of caching when using samewith, presumably in a way the compiler can't optimise.
```
use experimental :cached;

my $calls = 0;
sub pow2($a) is cached {
  $calls++;
  if ($a == 0) {1}
  else {pow2($a - 1) + pow2($a - 1)}
}

my $samewith-calls = 0;
sub pow2-samewith($a) is cached {
  $samewith-calls++;
  if ($a == 0) {1}
  else {samewith($a - 1) + samewith($a - 1)}
}

my $count-calls = 0;
sub count-to($a) is cached {
  $count-calls++;
  if ($a == 0) {1}
  else {samewith($a - 1) + 1}
}


say pow2(10);
say pow2(10);
say "pow2 calls:$calls";
say pow2-samewith(10);
say pow2-samewith(10);
say "pow2-samewith calls:$samewith-calls";
say count-to(1000);
say count-to(1000);
say "count-to calls:$count-calls";
```

## Expected Behavior
`pow2-samewith` should be called about the same number of times as `pow2`, as both are cached. count-to behaves as expected, even though it also uses samewith. expected output is 
```
1024
1024
pow2 calls:11
1024
1024
pow2-samewith calls:11
1001
1001
count-to calls:1001
````
## Actual Behavior
```
1024
1024
pow2 calls:11
1024
1024
pow2-samewith calls:2047 # <-- this differs
1001
1001
count-to calls:1001
```
## Steps to Reproduce
run the program from the first section.
## Environment
* Operating system: arch linux, also happens on windows
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo™ v2021.10-143-gb405d417a.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10-126-g83c53580a.
```
(also tested on v2021.08 and v2021.03)

**Comment by ab5tract** [comment]
The output is the same for base, but in RakuAST I see something interesting:

```
> set-rakuast; ./rakudo-m -Ilib issues/r4665.raku
1024
1024
pow2 calls:0
1024
1024
pow2-samewith calls:0
1001
1001
count-to calls:0

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-120-g7a682d7f9.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-7-gfe2080ac3.
```

**Comment by lizmat** [comment]
There are no plans on trying to fix "is cached".  Most likely, it will be deprecated from the core.

The ecosystem provides several solutions: https://raku.land/?q=cache
