### ISSUE TITLE
Sub cannot access dynamic variables when used in a "return"ed map

### ISSUE THREAD

**Issue by juliodcs** [rakudo/rakudo#4680]
## The Problem
A sub cannot access dynamic variables when it is used inside a map and the whole map is "return"ed.

Please, see example for better clarification.

## Expected Behavior
Sub should be able to access dynamic variables whether the sub is used in a map or not and whether the map is returned or not

## Actual Behavior
Sub can access dynamic variables only when not using a map or the map is not returned

## Steps to Reproduce
I've created a raku sniplet here:

https://glot.io/snippets/g5byjhbd2b

This is the source code:

    sub start {
        my $*something = 'foobar';
        
        # WORKS
        say 'first say-something:';
        say-something;
        
        # WORKS
        say 'mapped say-something, no return:';
        my @foo = (^2).map({say-something});
        
        # ERROR: Dynamic variable $*something not found
        say 'mapped say-something, with return:';
        return (^2).map({say-something});
    }

    sub say-something {
        say $*something;
        1
    }

    start;

## Environment
* Operating system: mswin32 (10.0.17763.529) and linux (glot.io)
* Compiler version (`perl6 -v` or `raku -v`): 2021.10 (windows)

**Comment by jnthn** [comment]
`map` is lazy, so the block is not run until after `start` has returned. Thus the dynamic variable is already out of scope. You can force the `map` to happen eagerly by adding `.eager` (`return (^2).map({say-something}).eager;`).

**Comment by juliodcs** [comment]
Thanks! My fault, I didn't know about this. 

I'm going to open a SO question for my "future me" and other people, I think it would be worth it
