### ISSUE TITLE
compile time signature check does not respect .wrap

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#4682]
Rakudo does not take into account the dynamic nature of wrapped subs when checking signatures at compile time.

```
sub rakudoconfuser(Str $) {};
&rakudoconfuser.wrap: sub (Int $) {};
rakudoconfuser(42);
# OUTPUT:
# Calling rakudoconfuser(Int) will never work with declared signature (Str)
# at 2021-03-08.raku:1044
# ------> ; &rakudoconfuser.wrap: sub (Int $) {}; ⏏rakudoconfuser(42);
```
expected:
```
sub rakudoconfuser(Str $) {}; 
&rakudoconfuser.wrap: sub (Int $) {}; 
::("&rakudoconfuser").(42);
# OUTPUT:
```

Further, the assumtion that calling a sub will work can be false, as one can wrap a function so the call becomes impossile. I don't see a solution here, besides removing the check. We have to expect the occasionally evil genius who likes a good monkey. Turning this into a warning could pollute output of tests, so that seems undesireable too.

**Comment by jnthn** [comment]
> Rakudo does not take into account the dynamic nature of wrapped subs when checking signatures at compile time.

I expect one would have to declare `use soft` in order to suppress such checks. It is a bug that, even with `use soft`, it still reports the error.

> Further, the assumtion that calling a sub will work can be false, as one can wrap a function so the call becomes impossile. 

Then it just fails at runtime. It'd only be a problem if any runtime checks about the call were eliminated by the static optimizer, but I don't believe they are.
