### ISSUE TITLE
raku --doc=Foo is calling Pod::To::Foo.render twice

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4690]
## The Problem

I've noticed this if I add tracing to the `render()` method of a pod class. For example

```
$ mkdir -p /tmp/lib/Pod/To
$ echo 'class Pod::To::Foo { method render(|) { warn; "render" } }' > /tmp/lib/Pod/To/Foo.pm6
$ echo '=para test pod' > /tmp/tst.pod6
$ raku -I /tmp/lib/ --doc=Foo /tmp/tst.pod6
```
Produces:
```
Warning: something's wrong
  in method render at /tmp/lib/Pod/To/Foo.pm6 (Pod::To::Foo) line 1
Warning: something's wrong
  in method render at /tmp/lib/Pod/To/Foo.pm6 (Pod::To::Foo) line 1
render
```
I've tried on latest Rakudo, and back as far as Raku 2020.06, which also has the problem.

## Environment
* Operating system: `Linux toshiba 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): `Welcome to Rakudo™ v2021.12-25-g560868695.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.`

**Comment by tbrowder** [comment]
I think you are seeing the optimization step.

**Comment by finanalyst** [comment]
This is a very old problem. I have reported it years ago, but nothing happened.
I have tried looking in the Rakudo code base as to why this happens, but I have not been able to find it.
The hack to avoid the problem is use a state variable in render, for example in my HTML2.pm6 module in my raku-pod-render distribution. 
Basically:
```
#| render is a class method that is called by the raku compiler
    method render($pod-tree) {
        state $rv;
        return $rv with $rv;
        # Some implementations of raku/perl6 called the classes render method twice,
        # so it's necessary to prevent the same work being done repeatedly

        # code to create the required output, here this is done by a call on $pp object set up elsewhere in the module.
        $rv = $pp.source-wrap;
        # and store response so its not re-calculated
    }
```

**Comment by dwarring** [comment]
@finanalyst. Thanks, I found your ticket https://github.com/rakudo/rakudo/issues/2588. I'll close this as a duplicate.
