### ISSUE TITLE
Negated smartmatching with pair as matcher gives wrong result (due to optimizing)

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4693]
## The Problem
Given a subdirectory "nqp" in the current working directory, the following two commands both print ```True```.
```
$ ./rakudo-m -e 'say so "nqp".IO ~~ :d'
True
$ ./rakudo-m -e 'say so "nqp".IO !~~ :d'
True
```

## Expected Behavior
The second command should print ```False```.

## Details
The output changes with decreasing the optimizer level to 1 ```--optimize=1```:
```
$ ./rakudo-m --optimize=1 -e 'say so "nqp".IO ~~ :d'
True
$ ./rakudo-m --optimize=1 -e 'say so "nqp".IO !~~ :d'
False
```

The problem also goes away with https://github.com/rakudo/rakudo/commit/7554d73322 reverted.

On the JVM backend the mentioned problem even leads to spectest failures in S16-filehandles/filetest.t
```
S16-filehandles/filetest.rakudo.jvm 14 - ~~:d returns false on non-existent directories
S16-filehandles/filetest.rakudo.jvm 15 - ~~:r returns false on non-existent directories
S16-filehandles/filetest.rakudo.jvm 16 - ~~:w returns false on non-existent directories
S16-filehandles/filetest.rakudo.jvm 17 - ~~:x returns false on non-existent directories
S16-filehandles/filetest.rakudo.jvm 18 - ~~:f returns false on non-existent directories
S16-filehandles/filetest.rakudo.jvm aborted 96 test(s)
```
(The tests for this file are passing on MoarVM.)

## Environment
* Operating system: FreeBSD 12.3-RELEASE
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo™ v2021.12-27-gd80fb897e.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.

**Comment by usev6** [comment]
I looks like this is not related to file test operators at all:
```
14:27 < bartolin> committable6: 2021.12, HEAD say so 7 !~~ :is-prime
14:27 < committable6> bartolin, ¦2021.12: «False␤» ¦HEAD(45510b4): «True␤»
```

**Comment by vrurg** [comment]
@usev6 Thanks! Will take care of this. As a matter of fact, it looked familiar to me immediately. And, true, I have a fix locally, but it's not ready for publishing yet.

In the meantime `"nqp".IO ~~ :!d'` works as expected.
