### ISSUE TITLE
Pod parse failure with # comment following =begin/=end comment block

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4694]
## The Problem

Given the following code:

    sub foo {
    =begin comment
    =end comment
    # comment
    }

## Expected Behavior

The code should parse okay.

## Actual Behavior

The code throws an error.

# UPDATE

The simple code above does not throw. I am trying to reduce the 
problem code (which is still causing problems) to something smaller
if possible (and I may have made a mistake somewhere else).

## Environment
* Operating system: Debian 10 (Buster), amd64
* Compiler version: Rakudo 2021.10

**Comment by lizmat** [comment]
Superseded by RakuDoc v2.0
