### ISSUE TITLE
Missed objection on PR #4689

### ISSUE THREAD

**Issue by japhb** [rakudo/rakudo#4697]
I objected to PR #4689 in [#raku-dev](https://logs.liz.nl/raku-dev/2021-12-29.html#00:08), but forgot to add my objection to the PR:

```
japhb | MasterDuke, lizmat: I don't think that's correct.
As moon-child pointed out earlier, ~& and +& are doing
bitwise/ordwise operations, so it truly is ambiguous
which parenthization is correct, and they aren't iffy
(it just happens that +&'s result can be treated a
zero/non-zero in boolean context).  ?& is legit iffy
though.
```

For context, [moon-child's comment](https://logs.liz.nl/raku-dev/2021-12-28.html#22:15):

```
moon-child | +& is a case where you could conceivably want it either way
```

I think the case in question is:

```raku
$foo +& $bar ?? $baz !! $quux
```

for which the intended parenthesization (either around the `+&` or the ternary) is not inherently obvious.

I think the PR should be backed out.

**Comment by lizmat** [comment]
The PR has been backed out before the 2022.02 release, so closing.
