### ISSUE TITLE
HyperSeq ignores last

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#4712]
```
 (^∞).hyper.map({ last });
```

This does not terminate. If this is by design, please file an ENODOC in `/type/HyperSeq` for `.map` and `.grep`.

## Environment
Linux dexhome 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64 GNU/Linux

Welcome to Rakudo™ v2021.12-27-gd80fb897e.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.

**Comment by jnthn** [comment]
Just an NYI, I expect.

**Comment by jnthn** [comment]
Ah, and to implement it, we'd need to settle on semantics.

For `HyperSeq`, given output order is relative to input order, I think it's fairly clear that we:

1. Don't schedule any more batches
2. Don't process this batch any further, and set some "`last` happened" flag on it
3. In the collector, make sure to include results from earlier batches, but discard results from later ones (we'll have done some throw-away work, of course).

As an optimization we might signal to other works to not schedule any further work on later batches.

For `race`, I think we can:

1. Don't schedule any more batches
2. Don't process this patch any earlier and set some `last` happened flag on it
3. In the collector, as soon as we see a batch that has the flag set, stop consuming any further batches.

As an optimization, the same signaling mechanism could b used to indicate that all other workers need not produce any further elements.

**Comment by lizmat** [comment]
Also: https://raku.land/zef:lizmat/ParaSeq
