### ISSUE TITLE
Allow WHY formatting to be set at runtime

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#4718]
Pod text typically has its whitespace squeezed (adjacent whitespace becomes one ` `) but uses can disable whitespace squeezing for leading declarator blocks (the ones declared with `#|`) by providing the `RAKUDO_POD_DECL_BLOCK_USER_FORMAT` environmental variable at compile time.

However, setting this at compile makes this an all-or-nothing decision and means that the results of `.WHY` depend on a setting from when a module was (pre) compiled.  Would there be any problem to storing the raw text of the declarator block at compile time and then whitespace squeezing it (or not) at runtime based on the lexical value of `RAKUDO_POD_DECL_BLOCK_USER_FORMAT`?

**Comment by lizmat** [comment]
Superseded by RakuDoc v2.0
