### ISSUE TITLE
[2021.12] t/02-rakudo/repl.t: test fails on debian sid

### ISSUE THREAD

**Issue by cdluminate** [rakudo/rakudo#4726]
## The Problem

Test fails in `repl.t`:

```
t/02-rakudo/repl.t .............................................. 
1..47
# Subtest: sanity check; load without tweaking line editor
    1..3
    ok 1 - result of code is on STDOUT
    not ok 2 - no STDERR output
    # Failed test 'no STDERR output'
    # at t/02-rakudo/repl.t line 29
    # expected: '0'
    #      got: '586'
    ok 3 - successful exit code
    # You failed 1 test of 3
not ok 1 - sanity check; load without tweaking line editor
# Failed test 'sanity check; load without tweaking line editor'
# at t/02-rakudo/repl.t line 23
# Subtest: can use native typed variable on subsequent lines (1)
    1..2
    ok 1 - stdout is correct
    ok 2 - stderr is correct
ok 2 - can use native typed variable on subsequent lines (1)
# Subtest: indented code parses correctly
    1..4
    # Subtest: uncuddled else is parsed correctly
        1..2
        not ok 1 - stdout is correct # TODO indent styles don't parse right
        # Failed test 'stdout is correct'
        # at t/02-rakudo/repl.t line 42
        # expected: ':)
        # '
        #      got: '()
        # ===SORRY!=== Error while compiling:
        # Undeclared routine:
        #     else used at line 1
        # 
        # '
        ok 2 - stderr is correct
    not ok 1 - uncuddled else is parsed correctly # TODO indent styles don't parse right
    # Failed test 'uncuddled else is parsed correctly'
    # at t/02-rakudo/repl.t line 42
    # Subtest: open brace on next line is parsed correctly
        1..2
        not ok 1 - stdout is correct # TODO indent styles don't parse right
        # Failed test 'stdout is correct'
        # at t/02-rakudo/repl.t line 52
        # expected: ':)
        # '
        #      got: '()
        # ===SORRY!=== Error while compiling:
        # Undeclared routine:
        #     else used at line 1
        # 
        # :)
        # '
        ok 2 - stderr is correct
    not ok 2 - open brace on next line is parsed correctly # TODO indent styles don't parse right
    # Failed test 'open brace on next line is parsed correctly'
    # at t/02-rakudo/repl.t line 52
    # Subtest: partially-cuddled else is parsed correctly
        1..2
        not ok 1 - stdout is correct # TODO indent styles don't parse right
        # Failed test 'stdout is correct'
        # at t/02-rakudo/repl.t line 64
        # expected: ':)
        # '
        #      got: '()
        # ===SORRY!=== Error while compiling:
        # Undeclared routine:
        #     else used at line 1
        # 
        # '
        ok 2 - stderr is correct
    not ok 3 - partially-cuddled else is parsed correctly # TODO indent styles don't parse right
    # Failed test 'partially-cuddled else is parsed correctly'
    # at t/02-rakudo/repl.t line 64
    # Subtest: cuddled else
        1..2
        ok 1 - stdout is correct
        ok 2 - stderr is correct
    ok 4 - cuddled else
```

Full buildlog:
[rakudo_2021.12-1_amd64-2022-01-18T16:04:29Z.build.txt](https://github.com/rakudo/rakudo/files/7890675/rakudo_2021.12-1_amd64-2022-01-18T16.04.29Z.build.txt)

## Steps to Reproduce

Build these debian packages from git repo: (all updated to 2021.12)

https://salsa.debian.org/perl6-team/moarvm
https://salsa.debian.org/perl6-team/nqp
https://salsa.debian.org/perl6-team/rakudo

## Environment
* Operating system: Debian sid
* Compiler version (`perl6 -v` or `raku -v`): 2021.12

**Comment by MasterDuke17** [comment]
I've seen t/02-rakudo/repl.t flap (i.e., only fail sometimes on repeated runs), is it always failing for you?

**Comment by cdluminate** [comment]
Yes. This is always failing. (`sbuild` builds packages within a minimal chroot. maybe some system configuration or missing package is rendering this?)

**Comment by usev6** [comment]
If I read the output correctly, the only problem is that the STDERR output of the sanity check (first test in t/02-rakudo/repl.t) isn't empty:

> \# Subtest: sanity check; load without tweaking line editor
>     1..3
>     ok 1 - result of code is on STDOUT
>     not ok 2 - no STDERR output
>     # Failed test 'no STDERR output'
>     # at t/02-rakudo/repl.t line 29
>     # expected: '0'
>     #      got: '586'
>     ok 3 - successful exit code
>     # You failed 1 test of 3
> not ok 1 - sanity check; load without tweaking line editor
> \# Failed test 'sanity check; load without tweaking line editor'
> \# at t/02-rakudo/repl.t line 23

All the other output is about todo'ed tests.

It would be interesting to know what 586 characters are appearing on stderr there.
Maybe the following command would suffice to see the unexpected error message:
```
$ echo "133742.flip.say" | ./rakudo-m --repl-mode=interactive >/dev/null
```

I'll try if I can reproduce the problem

**Comment by usev6** [comment]
Sorry, I wasn't able to reproduce. Could you maybe try to run the mentioned command and capture the output on stderr before running ```make test```? (E.g. here:  https://salsa.debian.org/perl6-team/rakudo/-/blob/50443b1b26/debian/rules#L68)
