### ISSUE TITLE
put method fails to print junctions 

### ISSUE THREAD

**Issue by GrayJoKing** [rakudo/rakudo#4742]
## The Problem

`put` as a method call results in an error when taking a Junction.

## Expected Behavior
```raku
(1|2).put;
put 1|2:;
(1|2).&put;
put 1|2;
```
All of the above should be identical, outputting `1` and `2` on separate lines.

## Actual Behavior
The first two lines result in 
```
This type cannot unbox to a native string: P6opaque, Junction
```
However the next two work fine. Interesting that `.&` works even though it supposedly "calls ... with method syntax", though perhaps this is special cased differently?

## Steps to Reproduce
``` raku -e "put 1|2:"```

## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo v2021.12.
Implementing the Raku Programming Language v6.d.
Built on MoarVM version 2021.12.
```

A note that this is a regression, since this same code at least worked in 2018.12

**Comment by vrurg** [comment]
@GrayJoKing thanks for the report!
