### ISSUE TITLE
Can't help to ask to get the explanation on regex pattern group

### ISSUE THREAD

**Issue by abdulbadii** [rakudo/rakudo#4745]
So apologize if not suitable enough, but really can't get the explanation on regex pattern group for  backreferring it in any active Raku site and book

So please anyone is willing sincerely to explain or spread the knowledge on this, even the slightest guidance will be invaluable to me. Thanks in advance.

**Comment by jonathanstowe** [comment]
I suspect, if you are unable to find the information you require, that this is a documentation issue rather than of Rakudo itself and properly raised at https://github.com/Raku/doc/issues

**Comment by abdulbadii** [comment]
Correct. Thanks
