### ISSUE TITLE
<same> character class returns match longer that input string

### ISSUE THREAD

**Issue by jubilatious1** [rakudo/rakudo#4752]
## The Problem

Intuitively, one might imagine that `n` consecutive identical characters will match a `<same>` zero-width assertion **`n-1`** times, _because the match is  between each  pair of identical characters_. However `<same>` matches can continue far beyond the number of characters in the input string. 

## Expected Behavior

1. This works as expected:  five zeros as LHS input to a smartmatch matches a `^` start-of-string, initial `｢0｣`, and consequential `<same>` regex tokens out to 4 `<same>` assertions:
```
~$ raku
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.06.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.06.

To exit type 'exit' or '^D'
> say $/ if '00000' ~~ m{^ 0<same>**2..4}; #five zeros on LHS
｢0｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
```

## Actual Behavior

2. This doesn't work as expected:  five zeros as LHS input to a smartmatch matches a `^` start-of-string, initial `｢0｣`, and consequential `<same>` regex tokens **BEYOND** 4 `<same>` assertions:
```
> say $/ if '00000' ~~ m{^ 0<same>**2..5}; #five zeros on LHS
｢0｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
```

3. Doesn't work (an extreme example), input string is 5 characters but smartmatching returns 200 `same => ｢｣` matches:
```
> say $/ if '00000' ~~ m{^ 0<same>**2..200}; #five zeros on LHS
｢0｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
>
```

## Steps to Reproduce / Environment
Tested in REPL:
```
~$ raku
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.06.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.06.
```
* Operating system: `MacOS 10.11.6 (El Capitan)`

## Related?

#2791

**Comment by jubilatious1** [comment]
## Quick Addendum: 

Grouping regex atoms within the RHS of the smartmatch achieves the desired result (four <same> matches for an input string of 5 identical characters):

```
> say $/ if '00000' ~~ m{^ [0<same>]**2..20}; #five zeros on LHS
｢0000｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
 same => ｢｣
>
```

1. Maybe add this in the docs somewhere?

2. Still, it's not clear to me that the example above returning 200 `same => ｢｣` matches is correct, or whether the programmer should receive some sort of error message, e.g. `end-of-regex <same> assertion without grouping/capturing can propagate infinitely.`

**Comment by vrurg** [comment]
With the second comment you basically answered the question. You apply the repeater to an atom which is, in the first case, `<same>`, not `0<same>`. To illustrate this you can insert a space between `0` and `<same>`. 

So, in fact, your first example winds down to 'match the first 0, then match as many zero-width atoms as you can'. A case of angels on the head of a pin. :)

This behavior is actually documented.

**Comment by jubilatious1** [comment]
You're explanation would seem sound, and one might expect to see similar behaviour when requesting matches to 'as many zero-width atoms as you can' as regards the `$` end-of-string zero-width assertion.

So why not have multiple end-of-line regexes with quantified <same> tokens throw the same error as the `$` end-of-string zero-width assertion (below)?

```
> say $/ if '00000worldworld' ~~ m{ world $  };
｢world｣
> say $/ if '00000worldworld' ~~ m{ world $+  };
===SORRY!=== Error while compiling:
Can only quantify a construct that produces a match
------> $/ if '00000worldworld' ~~ m{ world $+  ⏏};
> say $/ if '00000worldworld' ~~ m{ world $**1..20  };
===SORRY!=== Error while compiling:
Can only quantify a construct that produces a match
------> '00000worldworld' ~~ m{ world $**1..20  ⏏};
```

**Comment by vrurg** [comment]
Look at the problem from a few different perspectives.

First, as a matter of fact, `<same>` does produce a match. It is empty, but it has a meaning.

Second, `$`, `$$`, `^`, and `^^` are hard-coded anchors which really don't produce a match.

And the last, consider this:

```raku
my regex same {\d\d};
say '00000' ~~ m{^ 0<same>**2..4};
```

As a matter of fact, the compiler cannot know when a subrule is a zero-match. Since subrules are normally code objects, compiler can't know what would they produce. Therefore no assumption is made about `<subrule>` semantics.

**Comment by jubilatious1** [comment]
Can someone explain why this issue was closed? Thank you.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/issues/4752#issuecomment-1027311963 says: "This behavior is actually documented." ?

**Comment by lizmat** [comment]
@vrurg: where did you say this was documented  :-)
