### ISSUE TITLE
DateTime.new('2015-02-27T00:00:00').later(:5foo) should be a syntax error.

### ISSUE THREAD

**Issue by ohmycloud** [rakudo/rakudo#4756]
## The Problem

```
DateTime.new('2015-02-27T00:00:00').later(:5foo)  #  Output: 2015-02-27T00:00:00Z
```

## Expected Behavior

DateTime.new('2015-02-27T00:00:00').later(:5foo) should be a syntax error.

## Environment
* Operating system: macOS Monterey 12.1
* Compiler version (`perl6 -v` or `raku -v`): v2021.12

**Comment by lizmat** [comment]
It cannot be a syntax error as unexpected named arguments are ignored on methods in Raku.  So closing this issue.
