### ISSUE TITLE
[JVM] Unicode glyphs silently treated as zero values in numeric operations

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#4760]
## The Problem
In one special case (superscripts for exponentiation) JVM handles Unicode as one expects, which gets your hopes up,
but otherwise silently treats the various kinds of Unicode 'numbers' as zero values, thus dashing them.

## Expected vs Actual Behavior
MoarVM does what you'd naively expect with these statements, but  JVM only works for the 1st line:

```
say 2²;     # 4 - OK
say 2**²;   # 1 - no
say ²;      # 0 - no
say ⅓;      # 0 - no
say 3 * ⅓;  # 0 - no
```
## Maybe a Warning?

This is perhaps more a LTA situation than a straight-ahead bug, and NYI is a fact of life (see also #4291), but...
Any chance of a warning? "You keep using that number. I do not think it means what you think it means." 

Something analogous to the compile-time warning JVM gives for non-ASCII variable names:

```
Name must begin with alphabetic character
------>     my $⏏𝑣
```
e.g. when '⅓' occurs in a numeric context:

```
Non-numeric treated as zero-valued:
------>     say 3 *⏏⅓
```
## Environment

Seen in all recent versions of JVM.

**Comment by lizmat** [comment]
What does `say ⅓.unival` say on the JVM ?

**Comment by SqrtNegInf** [comment]
In JVM 2021.12:

`Too many positionals passed; expected 1 arguments but got 2`

**Comment by usev6** [comment]
With https://github.com/Raku/nqp/pull/779 merged and NQP bumped (https://github.com/rakudo/rakudo/commit/4a51b15214) the situation should be substantially better:
```
$ ./rakudo-j 
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on JVM.

You may want to `zef install Readline`, `zef install Linenoise`, or `zef install Terminal::LineEditor` or use rlwrap for a line editor

To exit type 'exit' or '^D'
[0] > say 2²;
4
[0] > say 2**²;
4
[0] > say ²;
2
[0] > say ⅓; 
0.333333
[0] > say 3 * ⅓;
1
```

I was able to unfudge some tests in roast, that are now passing (https://github.com/Raku/roast/commit/51b19bcb1c). So I'd think that we don't need additional tests here.

Thanks for bringing this up! Your report gave me the nudge to look at the implementation -- and improving support for unicode numbers wasn't as complicated as I thought.
