### ISSUE TITLE
An empty variable is valued issue

### ISSUE THREAD

**Issue by abdulbadii** [rakudo/rakudo#4762]
## The Problem
An empty variable is evaluated with a value by Raku

## Expected Behavior
all empty variable behaviors
## Actual Behavior
It indeed does result in TRUE condition / boolean

## Steps to Reproduce
the script is to run to using sample data of which prepared in attachement

the `$range` variable is empty as the regex fillout selectively not supplying it
but  it is TRUE in

`if $range { say "\nr =$range="}`
## OUTPUT
`r ==
`
## Environment
* Operating system: MoarVM on Arch
* Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.
[rmHTMLement.raku.txt](https://github.com/rakudo/rakudo/files/8011881/rmHTMLement.raku.txt)
[Gui.html.txt](https://github.com/rakudo/rakudo/files/8011884/Gui.html.txt)

**Comment by vrurg** [comment]
It would be nice if you provide a golfed down version of your problem in a comment to this issue. But I'm pretty sure that there is no bug to be fixed but a misconception on your side.

You mention a regex what leads me to a conclusion that you've got a `Match` object in your `$range` which represents an empty string. The point is that the object actually represents a match found, even though it is zero-length, which is a `True` case. Let's consider an example:

```raku
my $r = ("aaa" ~~ /\d*?/);
say $r.Bool; # True
say $r.Str.Bool; # False
```

The regex is about matching 0 or more digits in a string meaning that no digits is ok too. But stringified it results in `""` which is `False` in boolean context.

**Comment by abdulbadii** [comment]
YES. CORRECT !
Although different and not the actual case of regex, it is really the same mechanism that is actually happening..
Thanks much !
