### ISSUE TITLE
.prec is an implementation detail but not marked `implementation-detail`

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#4776]
Being able to introspect into the precedence and/or associativity of an operator is very useful, and the `.prec` method does exactly that.  I noticed that this (imo) very useful method isn't in the docs, and thought that I'd add it.

Before doing so, however, I checked Roast and discovered that `.prec` isn't mentioned anywhere.  In particular, [S03-operators/precedence.t](https://github.com/Raku/roast/blob/master/S03-operators/precedence.t) tests operator precedence extensively without using any form of introspection.  On the other hand, @jnthn added `.prec` [9 years ago](https://github.com/rakudo/rakudo/commit/503d19c8b3d599ea46ae649490ac743a7aca7d44) and its API hasn't seen any changes since @lizmat added a direct-lookup interface [5 years ago](https://github.com/rakudo/rakudo/commit/caba0d346a1f3fd92084db93f226ee83f94f145e).  So it _seems_ stable enough that it either is part of Raku or ought to be.

Thus, I'm opening this issue to determine whether `.prec` is part of Raku and should be added to the docs (and maybe Roast).   If it's not, is there sufficient consensus to add `.prec` with its current API?  Or is `.prec` a Rakudo implementation detail that shouldn't become part of Raku?  If so, it should remain undocumented (and probably be marked as an `implementation-detail`). 

I'm hoping that there's consensus that `.prec` is or should be a part of Raku, but I want to check.  (If it isn't, I'd like to investigate adding an introspection method for precedence/associativity.)

**Comment by vrurg** [comment]
Since there is a way to set it, there must be a way to introspect it. I think it must be in Roast.

**Comment by jnthn** [comment]
There should be a way to introspect these things, but I'd not support specifying `prec`, as:

1. I don't think a hash is the right thing to return here. (It raises all kinds of questions. Like, can you mutate the hash to change the precedence? :-))
2. It's a bit odd that getting the precedence level is `.prec<prec>`. We're using the word to mean everything related to precedence *and* to the level.

A further design issue in Rakudo today is that operator precedence properties are duplicated in multiple places: in the grammar and then also for introspection via `.prec`. That's not really ideal. In the `rakuast` branch (work thanks to @lizmat) there is an `OperatorProperties` object, along with some shortcut methods that delegate to it. I think that would be a better API to spec.

**Comment by lizmat** [comment]
The `.prec` method will be removed when the Raku grammar is the default grammar
