### ISSUE TITLE
Issue in 0 width insertion repetition

### ISSUE THREAD

**Issue by abdulbadii** [rakudo/rakudo#4782]
## The Problem
this'd be regex bug in 0 width repetition ?
```

> 'abc' ~~ / [z?]+ /
^CPressed CTRL-c, press CTRL-c again to exit

```
or 

> 'abc' ~~ / [z?]* /
^CPressed CTRL-c, press CTRL-c again to exit

it's hanging

## Expected Behavior
return with fail/false boolen result at once

## Actual Behavior
it's hanging

## Steps to Reproduce
it was on Problem
on REPL

## Environment
* Operating system: MoarVM on Arc

* Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d

**Comment by codesections** [comment]
I believe this is the same issue as #4468 (which itself may have been a duplicate; I recall asking about a [similar issue in 2020](http://irclogs.raku.org/raku/2020-07-13.html#14:05) and being told that it was "well known".  (Shame that it's been well known for so long and doesn't at least throw a better error, though!)
