### ISSUE TITLE
The `:` in `my :($a, $b)` should be *optional* but is forbidden

### ISSUE THREAD

**Issue by codesections** [rakudo/rakudo#4789]
Normally, the syntax for declaring a [Signature literal](https://docs.raku.org/type/Signature#Signature_literals) is to use a colon: `my $sig = :($a, $b)`.

[S02 - Signature objects](https://design.raku.org/S02.html#Signature_objects) states that

> Declarators generally make the colon optional:
> 
>     my ($a,$b,$c);      # parsed as signature

However, it currently appears that the colon isn't **optional**, it's forbidden:

```raku
my :($a, $b, $c); 
# OUTPUT: ===SORRY!=== Error while compiling /home/runner/.code.tio
# Malformed my
```

And, [according to bisectable](http://irclogs.raku.org/raku-dev/2022-02-14.html#16:55), it looks like we never allowed the `my :(…)` form.

I can see two benfits in allowing the `:(…)` form: First (and less importantly) it help emphasize that the LHS gets destructuring semantics rather than list assignment semantics, which might be useful for some users/in some contexts.  Maybe this would help with the Raku/problem-solving#307?  More importantly (imo), I think this would be nice for pedagogical/documentation reasons: it would be easier to teach/document `my ($a, $b) := (42, 47)` as a shorthand for `my :($a, $b) := (42, 47)` – but it's only a shorhand if the longhand form works!

(I *think* that allowing this behavior may be as easy as adding a `':'?` in the [`variable_declarator` token](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Grammar.nqp#L2355), though I haven't tested that yet)

**Comment by jnthn** [comment]
> First (and less importantly) it help emphasize that the LHS gets destructuring semantics rather than list assignment semantics

Only if the `:=` initializer is used, though. What would it means in the case `=` is used?

**Comment by codesections** [comment]
> First (and less importantly) it help emphasize that the LHS gets destructuring semantics rather than list assignment semantics

Well, the following throws a "Cannot modify an immutable Signature" error, so I'd think using `=` in a declaration should too:

```raku
my ($a, $b); :($a, $b) = (42, 47); 
```

**Comment by vrurg** [comment]
> Only if the `:=` initializer is used, though. What would it means in the case `=` is used?

Perhaps, similarly to `my \foo = 42`, `my :(...) = ...` can imply binding semantics?
