### ISSUE TITLE
Mu method clone does not TWEAK

### ISSUE THREAD

**Issue by scovit** [rakudo/rakudo#4798]
Cloning is a variation of object construction, as such I would expect the method TWEAK to be called in order to check things or modify attributes after object construction.

## Expected Behavior

```
class Weird {
    has $.not-two = 0;

    submethod TWEAK {
         $!not-two += 1 if $!not-two == 2
    }
}

say (Weird.new: :not-two(2)).not-two;
say (Weird.new.clone: :not-two(2)).not-two;
```

Outputs:
```
3
3
```

## Actual Behavior

Outputs:
```
3
2
```

**Comment by vrurg** [comment]
This is by design. Cloning doesn't involve construction stage. This is what makes it valuable: it is generally faster, in part due to construction submethods are avoided.

You could override the `clone` method and initiate post-clone checks after delegating to parent's `clone`.

**Comment by scovit** [comment]
Are you sure that this is meant by design? The Synopsis does not mention `TWEAK`, but `clone` is included in the Construction and Initialization section. The behavior of clone in relation to TWEAK is not tested

**Comment by scovit** [comment]
I understand that in most of the cases when `clone` is used re-running `TWEAKS` in superfluous and would impact performances
