### ISSUE TITLE
Problem calling ^mixin from within a role

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4801]
## The Problem

I'm wanting to mix-in a role to objects from within a role. But encountering issues as follows:

```
role MyRole {
    method mix-from-meth(::?ROLE $role: $obj is raw) {
        return $obj.^mixin: $role;
    }
}

class C {}

# this works in Rakudo
my $obj1 = C.new;
$obj1.^mixin: MyRole;

note "alive";

# this doesn't
my $obj2 = C.new;
MyRole.mix-from-meth: $obj2;
```

## Expected Behavior

That both the above mix-in the role to the object.

## Actual Behavior

```
$ raku /tmp/tst.raku 
alive
Cannot find method 'specialize' on object of type Perl6::Metamodel::ClassHOW
  in method mix-from-meth at /tmp/tst.raku line 3
  in block <unit> at /tmp/tst.raku line 17
```

## Environment
* Operating system: `Linux box 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): `Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.`

**Comment by vrurg** [comment]
This is because you cannot invoke a method on a role. Raku implicitly puns a role for you:

```raku
(role { method foo { say self.HOW.^name } }).foo
```

You don't need to have `$role` in your method. `::?ROLE` will do.

**Comment by dwarring** [comment]
Thanks

**Comment by dwarring** [comment]
FWIW, I solved this using the `pun_source()` and  `is_pun()` methods from `Perl6::Metamodel::ClassHOW`:
```
    method mix-from-meth(::?ROLE: $obj is raw) {
        return $obj.^mixin: self.^pun_source
            if self.^is_pun;
    }
}

class C {}
my $obj2 = C.new;
say $obj2.HOW.raku;
say $obj2.does(MyRole);
MyRole.mix-from-meth: $obj2;
say $obj2.does(MyRole);
```
output:
```
Perl6::Metamodel::ClassHOW.new
False
True
```
