### ISSUE TITLE
Function isn't invoked when an enum is defined

### ISSUE THREAD

**Issue by demanuel** [rakudo/rakudo#4806]
The script:

```
my %*SUB-MAIN-OPTS = :named-anywhere;

enum Databases <db1 db2 db3 db4 db5>;
subset database of Str where {$_.lc eq 'db1'|'db2'|'db3'|'db4'|'db5'};


multi sub MAIN(
    'run-query',
    Str $query, #= SQL query to be executed
    database :$db, #= Database name. One of db1, db2, db3, db4, db5
    Bool :$show-hidden = False, #= Show the query results that are hidden
    Bool :$print-query = True, #= Print the query above the results. Good for copy pasting.
){
    say "RUN ME";
}

```

doesn't run when invoked:
```
$ raku apagar.raku run-query 'select 1+1 from dual' --db='db2' --show-hidden --print-query
Usage:
  apagar.raku run-query <query> [--db=<database>] [--show-hidden] [--print-query]

    <query>            SQL query to be executed
    --db=<database>    Database name. One of db1, db2, db3, db4, db5
    --show-hidden      Show the query results that are hidden [default: False]
    --print-query      Print the query above the results. Good for copy pasting. [default: True]

```

However if i remove the line containing "enum Databases <db1 db2 db3 db4 db5>;" it runs:

```
 raku apagar.raku run-query 'select 1+1 from dual' --db='db2' --show-hidden --print-query
RUN ME

```

$ raku --version
Welcome to Rakudo™ v2022.02-83-g028828ac8.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02-5-gec9fcaae2.

**Comment by wukgdu** [comment]
The arguement `--db='db2'` is `&thevalue`d, and then MAIN gets `Databases::db2` instead of 'db2' when `enum Databases <db1 db2 db3 db4 db5>` (which is `Map.new((db1 => 0, db2 => 1, db3 => 2, db4 => 3, db5 => 4))`) is defined. `Databases::db2` (value: 1) is not `subset database`.

`enum Databases ('db1' => 'db1', 'db2' => 'db2', 'db3' => 'db3', 'db4' => 'db4', 'db5' => 'db5');` will work. `Databases::db2` (value: 'db2') is `subset database`.

See: https://github.com/rakudo/rakudo/blob/master/src/core.c/Main.pm6 L74-78 (`&thevalue`), L91-153

**Comment by demanuel** [comment]
Thanks for the workaround, but it still looks to me, that it's a bug...

**Comment by wukgdu** [comment]
I found the commit introducing the specially-treated enum in MAIN https://github.com/rakudo/rakudo/commit/546dbd99b18425a42c8a280155f599a02ce103cc.
Maybe it's a feature with strange behavior and potential bug? (I don't know that history

Current version:
https://github.com/rakudo/rakudo/blob/6d04cc395b0135d703414643047acd733c49b99e/src/core.c/Main.pm6#L74-L78

**Comment by patrickbkr** [comment]
@lizmat: Can you shed some light on this?

**Comment by lizmat** [comment]
Drop the `subset`, use the `enum` as the constraint, and everything works.
````raku
my %*SUB-MAIN-OPTS = :named-anywhere;

enum Databases <db1 db2 db3 db4 db5>;

multi sub MAIN(
    'run-query',
    Str $query, #= SQL query to be executed
    Databases :$db, #= Database name. One of db1, db2, db3, db4, db5
    Bool :$show-hidden = False, #= Show the query results that are hidden
    Bool :$print-query = True, #= Print the query above the results. Good for copy pasting.
){
    say "RUN ME";
}
````
I suggest we close this issue.

**Comment by vrurg** [comment]
@demanuel Not in this case. We convert from a user-specified string into internal datatypes. It only a matter of choosing one approach over another.
