### ISSUE TITLE
POD Declarators are unstructured

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4812]
Consider, this example, slightly adapted from [documentation on Declaration Blocks](https://docs.raku.org/language/pod#Declarator_blocks):

```raku
#| Base class for magicians 
class Magician {
  has Int $.level;
  has Str @.spells;

  #| wave a wand in a particular direction
  sub wave(Complex $direction) { }

  #| cast a spell
  method cast(Int $s) {}
}
 
#| Fight mechanics 
sub duel(Magician $a, Magician $b) {
}
#= Magicians only, no mortals. 

dd $=pod;

```

## The Problem

This just gives us a flat list of declarator POD objects (slightly formatted);
```
[Pod::Block::Declarator.new(WHEREFORE => Magician, config => {}, contents => []),
 Pod::Block::Declarator.new(WHEREFORE => sub wave (Complex $direction) { #`(Sub|2888030377416) ... }, config => {}, contents => []),
 Pod::Block::Declarator.new(WHEREFORE => method cast (Magician: Int $s, *%_) { #`(Method|2888030381136) ... }, config => {}, contents => []),
 Pod::Block::Declarator.new(WHEREFORE => sub duel (Magician $a, Magician $b) { #`(Sub|2888030381256) ... }, config => {}, contents => [])
]
```

The POD tree contains a list of declarators that doesn't contain structural information. For example that `sub wave` is scoped to `Magician` and `duel` isn't.

## Expected Behavior

some way of indicating the overall structure of declarator blocks, such as:

*  nesting them in the `contents` tree.
* adding a  `level()` method, similar to header blocks.

## Environment
* Operating system: `Linux box 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo™ v2022.02-91-g0831a3b5f.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02-34-geb4480d88.

**Comment by lizmat** [comment]
Superseded by RakuDoc v2.0
