### ISSUE TITLE
%?RESOURCES error with a module using `NativeCall` when installed via CompUnit::Repository::Staging

### ISSUE THREAD

**Issue by hythm7** [rakudo/rakudo#4819]
## The Problem
When installing a distribution (that  uses NativeCall) via `CompUnit::Repository::Staging`, the installed distribution tries to access the `Staging` repo `%?RESOURCES` instead of the target repo. The error looks like this:

```
Some exceptions were thrown in END blocks:
  X::AdHoc: Failed to open file /tmp/stage/dist/B1B2BA852BB5BC0168E34C21E2FB54DC4A1AB543: No such file or directory
      in sub guess_library_name at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 218

```

## Steps to Reproduce

1 - Create a module contains the below:
#file lib/Curl.rakumod
```
use NativeCall;
constant  LIB = %?RESOURCES<libcurl.so>;

sub curl_global_init( long --> uint32 ) is native( LIB ) is export { * }
sub curl_global_cleanup( ) is native( LIB ) { * }

INIT { curl_global_init( 3 ) }
END  { curl_global_cleanup( ) }
```
2- create install script
#file bin/install.raku

```raku
#!/usr/bin/env raku
 
use Curl;

use CompUnit::Repository::Staging;

sub MAIN(:from(:$dist-prefix) = '.', :to(:$repo-prefix)!, :for(:$repo-name)!, Bool :$build = True) {
    my $meta-file = $dist-prefix.IO.add: 'META6.json';
    my $dist      = Distribution::Path.new($dist-prefix.IO, :$meta-file);

    my $target-repo-prefix = CompUnit::RepositoryRegistry.repository-for-name($repo-name).prefix;

    CompUnit::Repository::Staging.new(
        :prefix($repo-prefix),
        :next-repo(CompUnit::RepositoryRegistry.repository-for-name($repo-name)),
        :name($repo-name),
    ).install($dist, :force);

    $_.unlink for <repo.lock precomp/.lock>.map: {$repo-prefix.IO.child($_)};

    run "cp", "-r", "$repo-prefix/.", $target-repo-prefix;
}

```

3- make sure resources directory contains `libcurl.so`

So now the module structure should look like this:
```
.
├── bin
│   └── install.raku
├── lib
│   └── Curl.rakumod
├── META6.json
├── resources
│   └── libcurl.so
└── t
```
4-  install the dist
```sh
raku -I. bin/install.raku --for=home --from=. --to=/tmp/stage
```
4- remove the staging repo
```sh
rm -rf /tmp/stage;
```

5- now use the installed `install.raku` script to install any local distribution
```sh
~/.raku/bin/install.raku --for=home --from=local/module --to=/tmp/stage
```
when run the above command we get the error (if we installing for the same repo "home" )
if installing to another repo it works fine, for example no error when install to "site"
```sh
~/.raku/bin/install.raku --for=site --from=local/module --to=/tmp/stage
```

Full error:
```
Some exceptions were thrown in END blocks:
  X::AdHoc: Failed to open file /tmp/stage/dist/B1B2BA852BB5BC0168E34C21E2FB54DC4A1AB543: No such file or directory
      in sub guess_library_name at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 218
      in method setup at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 305
      in method setup at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 366
      in sub raku-nativecall at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/core/sources/07D7A4E6581D1C9421412E7D2A0586F9FED3D9B5 (NativeCall::Dispatcher) line 46
      in block  at /home/hythm/.raku/sources/56635E670421770BC454BC9EEB5BECBD2812EA99 (Curl) line 9
      in any <main> at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm line 1
      in any <entry> at /home/hythm/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm line 1

```

## Environment
* Operating system: Linux
* Compiler version:

```
Welcome to Rakudo™ v2022.02-99-g907243814.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02-38-g588e00d60.
```

**Comment by hythm7** [comment]
I think what happens is: when running the install script with `--for=home` (after installation), the temporary new prefix  for `home` repository points the `Staging` prefix, and since the install script itself is installed in `home`, It looks for it's resources in the updated `home` prefix (which is the `Staging` prefix. Anyway closing this issue as  its clearly not a bug in `%?RESOURCES`.

**Comment by niner** [comment]
I have just followed your excellent steps to reproduce and... I cannot 
reproduce. It works just fine. I added a dd LIB; to Curl.rakumod and I can run 
the command just fine:

```
***@***.***:~/.raku> ~/.raku/bin/install.raku
IO::Path.new("/home/nine/.raku/resources/
F86EBE7F7FB6A660320FDCEA8ECC2C3FC9BA32C9.so", :SPEC(IO::Spec::Unix), :CWD("/
home/nine/.raku"))
Usage:
  /home/nine/.raku/bin/install.raku --to|--repo-prefix[=Any] --for|--repo-
name[=Any] [--from|--dist-prefix[=Any]] [--build]
***@***.***:~/test/gh4819> ~/.raku/bin/install.raku --for=site --from=. --to=/
tmp/stage
IO::Path.new("/home/nine/.raku/resources/
F86EBE7F7FB6A660320FDCEA8ECC2C3FC9BA32C9.so", :SPEC(IO::Spec::Unix), :CWD("/
home/nine/test/gh4819"))
```

I also don't see anything standing out that looks wrong.

The one thing that your steps are missing is the contents of META6.json. So I 
copied one of mine and edited it to what I think it should read:
```
{
    "meta-version": 1,
    "name"          : "Curl",
    "version"       : "0.1",
    "perl"          : "6.c",
    "auth"          : "github:niner",
    "authors"       : [ "Stefan Seifert" ],
    "description"   : "Curl",
    "depends" : {
    },
    "provides"      : {
        "Curl":  "lib/Curl.rakumod"
    },
    "resources"      : [
        "libcurl.so"
    ]
}
```

Is there any significant difference to yours?

**Comment by hythm7** [comment]
may be this step? `~/.raku/bin/install.raku --for=site --from=. --to=/`
I didn't explain well but I meant to try to install any other local module, not the Curl module again:
``` 
~/.raku/bin/install.raku --for=home --from=local/module --to=/tmp/stage
```
the local module need to be installed to the same repo of `Curl` repo, so if `Curl` is installed with `--for=home`, then the local module should be installed with `--for=home` as well.


Please note my comment [here](https://github.com/rakudo/rakudo/issues/4819#issuecomment-1072751711) as I think that explains the issue I'm seeing:

**Comment by hythm7** [comment]
from this step `~/.raku/bin/install.raku --for=site --from=. --to=/tmp/stage`
It looks like you installed the `Curl` sample module to `home` repo and trying to install again to `site` repo. so no errors,

to reproduce:

 1- I install the curl module first with:
```
raku -I. bin/install.raku --for=home --from=. --to=/tmp/stage
```
2- remove the staging dir `rm -rf /tmp/stage;`

3- I install any local module I have (to the `home` repo as well)
```
# This gives the error
~/.raku/bin/install.raku --for=home --from=local/module --to=/tmp/stage
```

**Comment by niner** [comment]
Ah, yes, indeed. It must be a different module. Otherwise at the point where it's looking up that file it will already have been installed to the staging repo again.

The thing I missed is that it's not actually failing to find libcurl.so but its own dist file. I think this is a genuine bug in the staging repo. Here you see that it already covers looking for source files in the underlying repo: https://github.com/rakudo/rakudo/blob/master/lib/CompUnit/Repository/Staging.rakumod#L18
I think it has to do the same with resources and dist files.

**Comment by hythm7** [comment]
confirming adding `resource` method like below to `CompUnit::Repository::Staging` fixes the issue, but this needs duplicating private methods from `CompUnit::Repository::Installation` like `!resources-dir`, `!dist-dir`, `!repository-version`, `$!version`, etc... which I think there should be a better way to do that.

```raku
method resource($dist-id, $key) {
       my $dist-file = self!dist-dir.add($dist-id);

       if $dist-file.e {

         my $meta = Rakudo::Internals::JSON.from-json(self!dist-dir.add($dist-id).slurp);
        # need to strip the leading resources/ on old repositories

        return self!resources-dir.add($meta<files>{$key});
       }
       else {
         self.next-repo.resource($dist-id, $key)
       }

}

```

**Comment by niner** [comment]
Indeed, there is a better way :) Pushed the fix to rakudo.

I wouldn't mind if you kept me up-to-date with your experiments. I am curious about where they will lead.

**Comment by hythm7** [comment]
I can open a new issue but I think the below is extension of the same behavior, so would prefer to re-open.

The problem:
`%?RESOURCES` of an installed module is not available as long as `CURS` is registering the name of  the `CURI` that contains the `%?RESOURCES`

To reporoduce:

* have a dist structure like the below:

```sh
.
├── lib
│   └── MyModule.rakumod
├── META6.json
└── resources
    └── resource
```
* Contents of `MyModule.rakumod`
```raku
unit class MyModule;

method get-resource() { %?RESOURCES<resource> }
```
*  Content of `META6.json`
```json
{"depends":[],"meta-version":"1","version":"0.0.1","description":"MyModule","api":"0","perl":"6.d","provides":{"MyModule":"lib/MyModule.rakumod"},"license":"Artistic-2.0","release-date":"2022-02-07","source-url":"something.tar.gz","authors":["Some Author"],"raku":"6.d","tags":[],"resources":["resource"],"auth":"some-author","build-depends":[],"name":"MyModule","test-depends":[]}
```
* Install the module to `site` repo

* Run
```sh
raku -I'CompUnit::Repository::Staging#name(site)#/tmp/staging' -e 'use MyModule; say MyModule.get-resource.slurp.so'
False # no resource has been returned 
```
* No issue if run the same command again with `CURS` registering different name than the repo contains the `%?RERSOURCES` 

```sh
raku -I'CompUnit::Repository::Staging#name(home)#/tmp/staging' -e 'use MyModule; say MyModule.get-resource.slurp.so'
True # resource has been returned
```

looks like it fails when The `unless` statement [here](https://github.com/rakudo/rakudo/blob/master/src/core.c/Distribution/Resources.pm6#L11) is executed, and succeeds when not executed.

**Comment by hythm7** [comment]
The issue described in previous comment is because [this](https://github.com/rakudo/rakudo/blob/master/lib/CompUnit/Repository/Staging.rakumod#L27) line needs parens.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/16bac0c64a  .  Thanks for your resource and spotting the thinko!
