### ISSUE TITLE
Regression in error message

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#4823]
## The Problem
The error message for a particular case isn't as good as it used to be. Bisected to https://github.com/rakudo/rakudo/commit/73d5e74d96197312da62509058a0970668913bc8 (ping @usev6). If you give the variable passed to the function an explicit type at declaration the error is ok, e.g., `my Int $a = 2;` results in `Calling foo(Int) will [...]`

## Expected Behavior
```
$ raku -e 'multi foo (int $i) { $i + $i }; my $a = 2; say foo $a'
===SORRY!=== Error while compiling -e
Calling foo(Int:D) will never work with any of these multi signatures:
    (int $i)
at -e:1
------> oo (int $i) { $i + $i }; my $a = 2; say ⏏foo $a
```

## Actual Behavior
```
$ raku -e 'multi foo (int $i) { $i + $i }; my $a = 2; say foo $a'
===SORRY!=== Error while compiling -e
Calling foo(Mu) will never work with any of these multi signatures:
    (int $i)
at -e:1
------> oo (int $i) { $i + $i }; my $a = 2; say ⏏foo $a
```

## Environment
* Operating system: arch linux
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo™ v2022.02-120-g3f10f7daa.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02-42-gc935e681b.
```

**Comment by usev6** [comment]
As [shortly discussed via IRC](https://logs.liz.nl/raku-dev/2022-03-20.html#16:36) the old error (before https://github.com/rakudo/rakudo/commit/73d5e74d96) was a runtime error:
```
17:36 < bartolin> committable6: fae105b070bb multi foo (int $i) { $i + $i }; my $a = 2; say foo $a
17:36 < committable6> bartolin, ¦fae105b: «Cannot resolve caller foo(Int:D); none of these signatures match:␤    (int $i)␤  in block <unit> at /tmp/ayhfcbRR8w line 1␤␤ «exit code = 1»»
```

I'm pretty sure I did that change because I considered the compile time error a good thing to have.

As you pointed out a specified type for ```$a``` is reported. I have no idea how the error message could be improved for untyped objects, though.

**Comment by lizmat** [comment]
FWIW, I think the `Calling foo(Mu) will never work` really shows why you cannot use natives with multis.  If we could get **that** to work, we would have one compilation error less to worry about.

**Comment by jnthn** [comment]
> really shows why you cannot use natives with multis

Huh? If you declare a `multi` taking a natively typed value and you pass a natively typed value, it dispatches just fine:

```
$ raku -e 'multi foo (int $i) { $i + $i }; my int $a = 2; say foo $a'
4
```

I don't really see how we can do the analysis here at compile time *and* not know the type of the container, though. Multiple dispatch is a runtime decision; either we have in your hands all of the things that will be known at runtime and can optimize it (such as that it will be an `Int` in an `rw` container), or we don't and should not be attempting to. One most certainly can *not* decide the dispatch based upon the declared non-native type of a `Scalar`.

**Comment by lizmat** [comment]
@jnthn so you're saying that https://github.com/rakudo/rakudo/commit/73d5e74d96 should be reverted?

**Comment by MasterDuke17** [comment]
I think what's surprising is:
```
$ raku -e 'multi foo (int $i) { $i + $i }; say foo 2'
Cannot resolve caller foo(Int:D); none of these signatures matches:
    (int $i)
  in block <unit> at -e line 1
```
At compile time rakudo can know that the literal fits within the native min/max but still doesn't allow it.

**Comment by jnthn** [comment]
> so you're saying that https://github.com/rakudo/rakudo/commit/73d5e74d96 should be reverted?

Given it's not doing enough to be able to give an appropriate error messages, yes.

**Comment by usev6** [comment]
Thanks for finding this mistake of mine and for the discussion! The erroneous commit is reverted now.

**Comment by MasterDuke17** [comment]
Closed by https://github.com/rakudo/rakudo/pull/4829
