### ISSUE TITLE
[LTA] MAIN without sub

### ISSUE THREAD

**Issue by habere-et-dispertire** [rakudo/rakudo#4827]
## The Problem

If I forget to `sub` my `MAIN`, the error message misleads into thinking there is something awry with the variable definition (which is fine). The real issue comes earlier with the declaration of `MAIN`:

```
MAIN (
    Bool :$verbose = True,
) {
#    say $verbose;
}

```

Perhaps subroutines with special names (like `MAIN`), can be checked for missing syntax, and a suggestion made about adding it?

## Actual Behavior
===SORRY!=== Error while compiling
```
Variable '$verbose' is not declared
------>     Bool :⏏$verbose = True,
```

## Environment

* Operating system: macOS
* Compiler version: 2022.02 (6.d)

**Comment by lizmat** [comment]
Added mention of `sub` being potentially missing in https://github.com/rakudo/rakudo/commit/a56d239d0c .

Please close this issue if you think this is enough :-)

**Comment by habere-et-dispertire** [comment]
@lizmat, thank you so much! Much better now. :)
