### ISSUE TITLE
Update issue template

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4836]
![Captura de pantalla de 2022-03-30 12-21-07](https://user-images.githubusercontent.com/500/160809980-db405d83-ee25-4aee-9597-cf5266112b4b.png)

Apparently the issue template workflows have changed. I got this alert today when I checked it.

**Comment by AbhishekMohanKr** [comment]
Hi @JJ, 
May I work on that problem??

**Comment by JJ** [comment]
> Hi @JJ, May I work on that problem??

Please go ahead.
