### ISSUE TITLE
Strange behaviour of <<!=>>

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#4838]
## The Problem
From https://stackoverflow.com/questions/71690554/strange-behavior-of-a-hyperoperator
````raku
say 0 != 0;                 # False

my @a = 0, 0, 0;
say @a «==» @a;             # [True True True]
say @a «!=» @a;             # [True True True] <--- why?
say @a «!==» @a;            # [False False False]
````

## Expected Behavior
````raku
say @a «!=» @a;             # [False False False]
````

## Actual Behavior
````raku
say @a «!=» @a;             # [True True True] <--- why?
````

This is on Rakudo HEAD.

**Comment by lizmat** [comment]
The problem appears to be in the codegen of `«!=»`, as a direct call to `METAOP_HYPER` yields the correct result:
````raku
my @a = 0, 0, 0;
say METAOP_HYPER(&infix:<<!=>>)(@a,@a);  # [False False False]
````
This seems to be caused by the decision at https://github.com/rakudo/rakudo/blob/master/src/Perl6/Actions.nqp#L8121 to go for the given AST, rather than generating the proper call to `&infix:<!=>`.

Making that code always generate the call to `&infix:<!=>` makes the above code produce the correct result.  But breaks spec tests, so there is more to it.

**Comment by lizmat** [comment]
Turns out it was all wrong to begin with:
````raku
my @a = 1,2,3;
my @b = 4,5,6;
say @a >>!=<< @b;
say @a;  # [False False False]
say @b;  # [4 5 6]
````
So it actually created a meta-op using assignment.  As can be seen with:
````raku
say (1,2) >>!=<< (3,4);
# Cannot modify an immutable Int (1)
````
@jnthn++ for noting.  Fixed for now with the PR, should have special attention in the RakuAST branch in the future.

**Comment by raiph** [comment]
cf https://github.com/Raku/old-issue-tracker/issues/3322
