### ISSUE TITLE
Method defined in role is not returning expected results

### ISSUE THREAD

**Issue by ldav1s** [rakudo/rakudo#4841]
## The Problem
When I define a method in a `role` that returns an `Array`, the returned `Array` has the wrong number of elements, but
the expected data seems to exist, since it'll print out.

If I replicate the same piece of code and put it in a `sub` or a method in a `class`, I seem to get what I'm expecting.

## Steps to Reproduce

```
#!/usr/bin/env raku
use v6;
role Node {
    method ptp(Str $cond) returns Array of Str {
        Array[Str].new('a', 'b', 'c', 'd', 'e', $cond, 'g', 'h');
    }
}

sub ptp2(Str $cond) returns Array of Str {
    Array[Str].new('a', 'b', 'c', 'd', 'e', $cond, 'g', 'h');
}

class Thing does Node {
    method sc() returns Str {
        'thing' ~ ' and ' ~ 'another and ' ~ 'the last';
    }
    method test() {
        my @p = $.ptp($.sc);
        say "ptp: @p.elems: " ~ @p.elems;
        say "" ~ @p;
    }
    method ptp3(Str $cond) returns Array of Str {
        Array[Str].new('a', 'b', 'c', 'd', 'e', $cond, 'g', 'h');
    }
}

sub MAIN() {
    my $t = Thing.new;
    $t.test;
    my @p2 = ptp2($t.sc);
    say "ptp2: @p2.elems: " ~ @p2.elems;
    say "" ~ @p2;
    my @p3 = $t.ptp3($t.sc);
    say "ptp3: @p3.elems: " ~ @p3.elems;
    say "" ~ @p3;
}
```

Output:

```
$ ./bin/bug.raku 
ptp: @p.elems: 1
a b c d e thing and another and the last g h
ptp2: @p2.elems: 8
a b c d e thing and another and the last g h
ptp3: @p3.elems: 8
a b c d e thing and another and the last g h
```
I'm expecting 8 elements in the array.  As the output demonstrates, the `ptp` method (defined in the `role`) returns only an `Array` with 1 element.  The `ptp2` function (defined as a `sub`) and the `ptp3` method both return `Array`s of 8 elements.

Changing the declared return type of `ptp` or removing it altogether doesn't seem to matter.  The less fancy `ptp` implementation:

```
role Node {
    method ptp($cond) {
        ['a', 'b', 'c', 'd', 'e', $cond, 'g', 'h'];
    }
}
```
fails similarly.

## Environment
* Operating system: Ubuntu 20.04.4 LTS
```
$ cat /proc/version
Linux version 5.11.0-46-generic (buildd@lgw01-amd64-010) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022
```
* Compiler version (`perl6 -v` or `raku -v`):
```
$ raku -v
Welcome to Rakudo™ v2022.03.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.03.
```

**Comment by lizmat** [comment]
The problem you're seeing is in the line:
```raku
my @p = $.ptp($.sc);
```
`$.ptp(...)` is short for `self.ptp(...).item`.  In other words, the `Array` that is being returned by the `ptp` method is turned into a single item, and this becomes 1 element in `@p`.  But it's still there.

So this has nothing to do with being defined in a role!

You could either use `@.ptp(...)` (which is short for `self.ptp(...).list`) or `self.ptp(...)`.

**Comment by ldav1s** [comment]
OK.  Thanks for finding my bug.
