### ISSUE TITLE
Custom SubsetHOW not working

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#4846]
## The Problem
Trying using a custom subset keyword dies with:
```
===SORRY!===
Required named parameter 'refinee' not passed
```

## Expected Behavior
to work

## Actual Behavior
dies with the error above

## Steps to Reproduce

```raku
# ../bla/CustomSubset.pm6
my package EXPORTHOW {
  package DECLARE {
    constant submodel = Metamodel::SubsetHOW; # Using the original one just for testing
  }
}
```

```raku
# ../bla/main.p6
use CustomSubset;

submodel Bla of Int where * %% 2;
```

## Environment
Mac OS

```
Welcome to Rakudo™ v2022.02.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02.
```

**Comment by jnthn** [comment]
The `EXPORTHOW::DECLARE` mechanism was only intended for declarations with the standard package syntax. Anything else is probably for a matter for slangs.

**Comment by FCO** [comment]
But isn't a subset declaration?

**Comment by FCO** [comment]
Thanks
