### ISSUE TITLE
Topicalized smartmatch optimisation has caused a regression

### ISSUE THREAD

**Issue by 0racle** [rakudo/rakudo#4850]
## The Problem

I found this broke sometime between 2021.12 and 2022.02, and bisectable narrowed it down the commit to [96a481d - Implement optimization of topicalized smartmatches](https://github.com/rakudo/rakudo/commit/91ec1bbf601f2b9060a3ffc481407508296a481d)

Here's a snippet of code that reproduces the issue

```raku
my %h;
given 'one'.comb {
    when 3 { %h{.[0]} = { .[1] } }
}
say %h<o>().raku;
```

On v2021.12 (and all releases prior), it produces the output `"n"`.

On the v2022.02 release, the output is `Any`

Issue appears to be triggered by the use of the `when` block, which invokes smartmatching and aligns with the subject of that commit.

**Comment by lizmat** [comment]
ping @vrurg

**Comment by vrurg** [comment]
Will try looking into when get some time for it.
