### ISSUE TITLE
WARNING: unhandled Failure detected in DESTROY. No such symbol '<class 'numpy.int64'>'

### ISSUE THREAD

**Issue by librasteve** [rakudo/rakudo#4852]
## The Problem

I am developing raku::Dan::Pandas on ubuntu and getting an unwanted WARNING apparently from the GC

This is a block to getting that module working (I'm about 80% done after 4 months effort) - and also impacts the active promotion of raku::Dan since Python compatibility is an important aspect for interworking with Python workflows and providing a fully featured raku alternative.

Please help!
~p6steve

## Expected Behavior

/raku-Dan-Pandas/bin/synopsis-dan-pandas.raku runs without error

Please note that the module is being build "in context" with deps such as Inline::Python on the jupyter scipy-notebook image via Dockerfile.

Yes, <class 'numpy.int64'> is a Python symbol. I am happy to take any fix over to a PR for Inline::Python if you can tell me what to do.

I have found some prior art on this issue:
[](https://github.com/Raku/old-issue-tracker/issues/6097)
[](https://github.com/Raku/old-issue-tracker/issues/6480)
[](https://github.com/rakudo/rakudo/issues/1332)
[](https://github.com/ugexe/zef/issues/293)

## Actual Behavior

WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol '<class 'numpy.int64'>'
  in block  at /home/jovyan/raku-Dan-Pandas/bin/../lib/Dan/Pandas.rakumod (Dan::Pandas) line 587
  in block  at /home/jovyan/raku-Dan-Pandas/bin/../lib/Dan/Pandas.rakumod (Dan::Pandas) line 585
  in block  at /home/jovyan/raku-Dan-Pandas/bin/../lib/Dan/Pandas.rakumod (Dan::Pandas) line 582
  in method TWEAK at /home/jovyan/raku-Dan-Pandas/bin/../lib/Dan/Pandas.rakumod (Dan::Pandas) line 568
  in method new at /home/jovyan/raku-Dan-Pandas/bin/../lib/Dan/Pandas.rakumod (Dan::Pandas) line 426
  in block <unit> at ./synopsis-dan-pandas.raku line 140

## Steps to Reproduce
git clone https://github.com/p6steve/raku-Dan-Pandas.git@GC-issue     [note this branch made to freeze at this bug state]
docker build -it p6steve/raku-dan:pandas-2022.02-arm64    [1]
docker run -it p6steve/raku-dan:pandas-2022.02-arm64
./raku-Dan-Pandas/bin/synopsis-dan-pandas.raku 

It happens on every run on my setup. Commenting out the line below stops it.
145         E => Categorical.new(<test train test train>),

[1] adjust to amd64 by changing Dockerfile first line to ```FROM --platform=linux/amd64 jupyter/scipy-notebook```]

## Environment
* Operating system: ubuntu
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to Rakudo™ v2022.02.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02.

**Comment by grondilu** [comment]
I also get a similar annoying warning. 
```
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
```
The indicated failure is consistent with a method call, but I have no idea why that method would be called upon destruction of the object.  Also, this method call is inside a try block so I really don't get why the compiler would complained about an unhandled failure.

I can't reliably reproduce it, nor can I figure out a way to golf it.  Sorry, I know this is not helpful, I'm just bumping this issue.

**Comment by p6steve** [comment]
ho hum

**Comment by librasteve** [comment]
timo: thanks for the help - I guess I need to be more careful about stuff I pass to `::($name)`

Happy to go fix my own code and to close this issue.

**Comment by lizmat** [comment]
> The indicated failure is consistent with a method call, but I have no idea why that method would be called upon destruction of the object
The error is caused by a `Failure` object that is being created at some point during execution, but which was never throws or handled (by calling `.Bool` or `.defined` on it).

Then, when there's no path to the `Failure` object anymore, the GC will at some point decide it's time to throw the object away and calls `.DESTROY` on that `Failure` object.  And *then* produces the warning.

There's only one remedy really: make sure the `Failure` is handled, or make sure the `Failure` object isn't created in the first place.
