### ISSUE TITLE
Mixing supplies, channels and promises makes the code hang or throwing exceptions

### ISSUE THREAD

**Issue by demanuel** [rakudo/rakudo#4853]
The code:

```
my $p1 = Supply.interval(5);
my $p2 = Supply.interval(2);
my Channel $ch = Channel.new;

my $prom = start react {
     whenever $p1 -> $interval {
         say "5";
     }

     whenever $p2 -> $interval {
         say 2;
     }

     whenever $ch.closed {
         done;
     }

     whenever $ch -> $data {
         say "Data: $data";
     }
}

my $prom2 = start react {
     whenever $p1 -> $interval {
         $ch.send("5.2");
         $ch.close;
     }
     whenever $ch.closed {
         done;
     }
}

my @proms = ($prom, $prom2);
await Promise.allof(@proms);
```

doesn't work.
This code produces the following outcomes randomly:

1. Runs fine
2. Hangs
3. Throws exception. There are two types of exceptions:
  3.1. Unhandled exception in code scheduled on thread 4
  3.2. Or throws the following stack:

> No exception handler located for catch
>    at SETTING::src/core.c/Exception.pm6:62  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:throw)
>  from SETTING::src/core.c/Failure.pm6:63  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:throw)
>  from SETTING::src/core.c/Failure.pm6:125  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:CALL-ME)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:118  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:teardown)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:133  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-done)
>  from <unknown>:1  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/control.pm6:20  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:THROW-NIL)
>  from SETTING::src/core.c/control.pm6:236  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:done)
>  from SETTING::src/core.c/Channel.pm6:162  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:233  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:244  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Lock/Async.pm6:204  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-under-recursion-list)
>  from SETTING::src/core.c/Lock/Async.pm6:183  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-with-updated-recursion-list)
>  from SETTING::src/core.c/Lock/Async.pm6:146  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:protect-or-queue-on-recursion)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:242  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-supply-code)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:232  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:tap)
>  from SETTING::src/core.c/Supply.pm6:94  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:tap)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:178  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:23  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:267  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:266  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:263  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:261  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-add-whenever-awaits)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:256  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-supply-code)
>  from SETTING::src/core.c/Rakudo/Supply.pm6:232  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:tap)
>  from SETTING::src/core.c/Supply.pm6:94  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:tap)
>  from SETTING::src/core.d/await.pm6:70  (/usr/share/perl6/runtime/CORE.d.setting.moarvm:subscribe-awaiter)
>  from SETTING::src/core.c/ThreadPoolScheduler.pm6:64  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/ThreadPoolScheduler.pm6:242  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-one)
>  from SETTING::src/core.c/ThreadPoolScheduler.pm6:284  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
>  from SETTING::src/core.c/Thread.pm6:58  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:THREAD-ENTRY)

All these outcomes happen in a randomly way so it's better to run this script in a loop:

`bash$ for i in $(seq 100); do raku test.raku; done `

The outcomes 2 and 3 should never happen.

> raku --version
Welcome to Rakudo™ v2022.03-130-g8f7cc0847.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.03-13-ga3476e286.

Note: I asked for help in the perl6 mailing list, and several people confirmed the issue:
https://www.nntp.perl.org/group/perl.perl6.users/2022/04/msg10474.html

**Comment by lizmat** [comment]
Thanks for your report.  This will be available in the next release 2022.04.

**Comment by demanuel** [comment]
That was QUICK! :-D

Thanks!

**Comment by lizmat** [comment]
The problem description and backtrace were *very* helpful :-)
