### ISSUE TITLE
`$a .= uc.lc` is inconsistent

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#4863]
On current Rakudo (2022.03):

```
> my $a = "a"; say $a ~= "b" ~ "c"; say $a;
abc
abc
> my $a = 0; say $a += 1 + 2; say $a;
3
3
> my $a = "AbCd"; say $a .= uc.lc; say $a;
abcd
ABCD
```

This is inconsistent.

From the above it seems that `$a .= uc.lc` is equivalent to `($a = $a.uc).lc`.
I would have expected it to be equivalent to `$a = $a.uc.lc`.

I have not been able to find any test in roast covering this behavior.

If this is intended behaviour we should add a test to roast and add some documentation, possibly to the *Traps* section.

**Comment by gfldex** [comment]
To me the following is desireable:

```
# spectest:
$a .= uc .= lc;

# demand:
($a .= uc).lc;

#fail as ambiguous for
$a .= uc.lc;
```

**Comment by salortiz** [comment]
The problem may be that the *composed* `<op>=` operators are all synthetized with the same precedence that item assignment operator `=`, while the mutator method call special operator `.=` has much higher precedence (the same of other `dottyop`s).

So `$a.=uc.lc` should be read as "mutate `$a` calling `uc` then call `lc`"

**Comment by 2colours** [comment]
For the record: https://docs.raku.org/language/traps#Infix_operator_assignment

> For any given infix operator op, L op= R is equivalent to L = L op R (where L and R are the left and right arguments, respectively). This means that the following code may not behave as expected:

I also think the behavior is undesirable and the documented way is desirable - but if we cannot make that reality, the traps section of all places shouldn't spread misinformation.
