### ISSUE TITLE
Buggy `$=pod` construction of POD attribute declarators

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4866]
## The Problem

Consider:
```
unit class C;

#| leading decl
has $.a;
#= trailing decl

has $.b;
#= trailing decl

dd $=pod;
```

## Expected Behavior

Both declarators to attach to there respective attributes.

```
[Pod::Block::Declarator.new(WHEREFORE => Attribute.new, config => {}, contents => []),
Pod::Block::Declarator.new(WHEREFORE => Attribute.new, config => {}, contents => [])]
```

## Actual Behavior

The second after-declaration isn't attaching
```
[Pod::Block::Declarator.new(WHEREFORE => Attribute.new, config => {}, contents => []),
Pod::Block::Declarator.new(WHEREFORE => Any, config => {}, contents => [])]
```

However,  if I first call the .WHY method on attributes, It fixes the document structure:

```
unit class C;

#| leading decl
has $.a;
#= trailing decl

has $.b;
#= trailing decl

for C.^attributes(:local) {
  .WHY;
}

dd $=pod;

```

Produces:
```
[Pod::Block::Declarator.new(WHEREFORE => Attribute.new, config => {}, contents => []),
Pod::Block::Declarator.new(WHEREFORE => Attribute.new, config => {}, contents => [])]
```

Possibly related to https://github.com/rakudo/rakudo/issues/4036

## Environment
* Operating system: `Linux box 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): `Welcome to Rakudo™ v2022.03-204-g77b6a84a3.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.03-17-g794e1d589.`

**Comment by dwarring** [comment]
This might be the reason, or a contributing factor to `Pod::To::Text` omitting attributes that have only a trailing declaration only.
When I run `raku --doc ....` on the above example, `$!a` is documented, but not `$!b`:
```
attribute Mu $!a
leading decl
trailing decl
```

**Comment by dwarring** [comment]
I withdrew PR #4902  Instead added fudged tests https://github.com/Raku/roast/commit/404b5649ca48549a6af508bb1e1d74bfe7b62556. which demonstrate the issue

**Comment by tbrowder** [comment]
David, I'm glad you're tackling this and other pod issues.

**Comment by dwarring** [comment]
Thanks Tom. I think my simple PR didn't work on classes, because they haven't been composed yet.

**Comment by lizmat** [comment]
See https://github.com/Raku/problem-solving/issues/438

In any case, superseded by RakuDoc v2.0
