### ISSUE TITLE
libmoar.so: undefined reference to `uv__cloexec_ioctl'

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#4867]
## The Problem
I am having some trouble trying to compile commit `167588f90932ad634c78fabb6e57c1d9e604a5eb`, latest at the time of this writing. 

The compilation stops with the error noted in the title:
```
libmoar.so: undefined reference to `uv__cloexec_ioctl'
```
The full output to the command 
```
perl Configure.pl --gen-moar --gen-nqp --backends=moar
```
is available [here](https://termbin.com/6gdm).
## Expected Behavior
Successful compilation

## Actual Behavior
See above: error while compiling

## Steps to Reproduce

- clone this repo (specifically, I'm on commit `167588f90932ad634c78fabb6e57c1d9e604a5eb`)
- `cd` to it
- run 
```
perl Configure.pl --gen-moar --gen-nqp --backends=moar
```
## Environment
* Operating system: `Ubuntu 20.04.4 LTS`
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo™ v2022.02-117-g8d284d8c1.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02-42-gc935e681b.
```

**Comment by MasterDuke17** [comment]
This is a known problem occurring after a recent libuv bump. Sometimes a `make realclean` in the MoarVM directory (e.g., something like `rakudo/nqp/MoarVM`) will fix it, but if not, just delete the MoarVM directory and let `--gen-moar` re-clone it.

**Comment by stuart-little** [comment]
That was it, thank you!

To clarify: simply deleting `<path-to-repo>/nqp/MoarVM` and then running the build as usual worked just fine (several times, on several machines).
