### ISSUE TITLE
Missing column from both JSON and text error output

### ISSUE THREAD

**Issue by CIAvash** [rakudo/rakudo#4887]
## The Problem

Rakudo text error messages contain only line numbers: `file:ln`.
JSON error output has `pos`(for most errors) and `line` data, but column field is `null`.

## Expected Behavior

Column number should be included in error outputs.
text: `file:ln:cn`
JSON: `"column": n`

## Actual Behavior

No column number in text error messages and `null` value in JSON output's column field.

## Steps to Reproduce

Text error message:
Run `raku -e 'my Int:D $a'`. Only line in the message, no column.

JSON error output:
Run `RAKU_EXCEPTIONS_HANDLER=JSON raku -e 'my Int:D $a'`. Column field is `null`.

## Environment
* Operating system: Arch Linux (Linux 5.17.3-arch1-1)
* Compiler version (`perl6 -v` or `raku -v`):
    ```
    Welcome to Rakudo™ v2022.03.
    Implementing the Raku® Programming Language v6.d.
    Built on MoarVM version 2022.03.
    ```

**Comment by lizmat** [comment]
The JSON output:
```
{
  "X::Syntax::Variable::MissingInitializer":{
    "post":"<EOL>",
    "maybe":0,
    "line":1,
    "type":"Int:D",
    "implicit":0,
    "directive-filename":null,
    "filename":"-e",
    "modules":[],
    "what":"variable",
    "is-compile-time":1,
    "column":null,
    "message":"Variable definition of type Int:D needs to be given an initializer",
    "pos":11,
    "highexpect":["constraint"],
    "pre":"my Int:D $a"
  }
}
```
I think you need to look a the "pre", "post" and "pos" fields.
