### ISSUE TITLE
Inconsistency in error outputs

### ISSUE THREAD

**Issue by CIAvash** [rakudo/rakudo#4888]
## The Problem

1. Some error messages have the format of `message␤at {file_name}:{line_number}`. Some others are grouped together and have the format of `error message:␤specific message at line {line_number}`
2. Some error messages have their own field in JSON output, but when combined with another error, they are put into the `panic` field as a string
3. Some error messages don't have any filename, line number, ... information
4. When run with `-c` flag for syntax checking, some codes show error message/warning but also `Syntax OK` is printed
5. Exception messages have the format of `message␤in block {unit} at {file_name} line {line_number}`
6. Then there is #2327

## Expected Behavior

Consistent error messages.

## Steps to Reproduce
Order corresponds to the numbers above.

1. Run:
    - `raku -e 'my Int:D $a'`
        ```
        ===SORRY!=== Error while compiling -e
        Variable definition of type Int:D needs to be given an initializer
        at -e:1
        ------> my Int:D $a⏏<EOL>
            expecting any of:
                constraint
        ```
    - `raku -e 'something; another'`
        ```
        ===SORRY!=== Error while compiling -e
        Undeclared routines:
            another used at line 1
            something used at line 1
        ```
2. JSON output
    - Single: `RAKU_EXCEPTIONS_HANDLER=JSON raku -e 'something'`
        ```json
        {"X::Undeclared::Symbols":{"post_types":{},"message":"Undeclared routine:\n    something used at line 1\n","routine_suggestion":{"something":[]},"is-compile-time":1,"highexpect":["statement end","statement modifier","statement modifier loop"],"modules":[],"pre":"something","unk_types":{},"filename":"-e","pos":9,"post":"<EOL>","column":null,"line":1,"type_suggestion":{},"unk_routines":{"something":[1]}}}
        ```
    - Two: `RAKU_EXCEPTIONS_HANDLER=JSON raku -e 'something; another'`
        ```json
        {"X::Undeclared::Symbols":{"type_suggestion":{},"pre":"something; another","message":"Undeclared routines:\n    another used at line 1\n    something used at line 1\n","pos":18,"highexpect":["statement end","statement modifier","statement modifier loop"],"unk_routines":{"something":[1],"another":[1]},"column":null,"modules":[],"unk_types":{},"line":1,"filename":"-e","post_types":{},"is-compile-time":1,"post":"<EOL>","routine_suggestion":{"another":[],"something":[]}}}
        ```
    - Combined with other errors: `RAKU_EXCEPTIONS_HANDLER=JSON raku -e 'something; another; my Int:D $a'`
        ```json
        {"X::Comp::Group":{"panic":"Undeclared routines:\n    another used at line 1\n    something used at line 1\n","worries":[],"message":"Variable definition of type Int:D needs to be given an initializer\nUndeclared routines:\n    another used at line 1\n    something used at line 1\n","sorrows":[{"X::Syntax::Variable::MissingInitializer":{"is-compile-time":1,"type":"Int:D","filename":"-e","post":"<EOL>","message":"Variable definition of type Int:D needs to be given an initializer","column":null,"highexpect":["constraint"],"implicit":0,"pre":"something; another; my Int:D $a","pos":31,"maybe":0,"line":1,"what":"variable","modules":[]}}]}}
        ```
3. An example: `raku -e 'use Test:<>' ` 
    ```
    Use of Nil in string context
    Malformed UTF-8 near bytes 00 00 88
    ```
4. `raku -c -e 'my $a; my $a'` (no JSON output for this one)
    ```
    Potential difficulties:
        Redeclaration of symbol '$a'.
        at -e:1
        ------> my $a; my $a⏏<EOL>
    Syntax OK
    ```
5.
    - `raku -e 'die'`
        ```
        Died
          in block <unit> at -e line 1
        ```
    - No line number for JSON: `RAKU_EXCEPTIONS_HANDLER=JSON raku -e 'die'`
        ```
        {"X::AdHoc":{"payload":"Died","message":"Died"}}
        ```

## Environment
* Operating system: Arch Linux (Linux 5.17.3-arch1-1)
* Compiler version (`perl6 -v` or `raku -v`):
    ```
    Welcome to Rakudo™ v2022.03.
    Implementing the Raku® Programming Language v6.d.
    Built on MoarVM version 2022.03.
    ```

**Comment by lizmat** [comment]
The JSON just represents whatever it is given.  The handler is really just:
```raku
my class Exceptions::JSON {
    method process($ex) {
        $*ERR.print: Rakudo::Internals::JSON.to-json($ex);
        False  # done processing
    }         
}
```
Exceptions are not consistent at the moment.  That is going to be another big project altogether.  And another issue.
