### ISSUE TITLE
Provide a Date.now class method similar to the DateTime.now method

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#4910]
## The Problem

If I want the date now I have to do this:

    > say DateTime.now.Date
    2022-04-27

## Expected Behavior

    > say Date.now
    2022-04-27

## Actual Behavior

    > say Date.now
    No such method 'now' for invocant...

## Environment
* Operating system: Debian 11
* Compiler version: Rakudo v2022.03

**Comment by jonathanstowe** [comment]
There's already a `Date.today`  which gives just that.

**Comment by lizmat** [comment]
Related: https://raku.land/zef:lizmat/Today

**Comment by 2colours** [comment]
@tbrowder can this be closed now? `Date.today` sounds convincing in my opinion.

**Comment by tbrowder** [comment]
Yes, of course. I don’t remember seeing that method because I was expecting something symmetrical with DateTime’s .now, but I see “now” Date.today is symmetrical: DateTime at this moment is an instant (i.e., now) and Date at this moment is a day (i.e., today).

Sorry for the bandwidth waste.
