### ISSUE TITLE
Inconsistent dispatch to method defined in role

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#4916]
## The Problem

A method may accept a _raw_ invocant, meaning that the invocant parameter is bound to the container if the method is called on a scalar container. Such a method can replace the thing stored inside the container, which can be useful.

A method that accepts a raw invocant can be defined inside a role, and it will work fine if called on a class that `does` the role. However, if called on a pun, the invocant parameter appears to be bound to the thing _inside_ the container, rather than to the container it is stored in, as demonstrated by the following code:

```raku
role Golfy {
    has @.values;
    multi method golf(Golfy:U \SELF: **@values) {
        SELF = SELF.new(:@values);
    }
}

class Golf does Golfy {}

my Golf $var;
try $var.golf(42);
say $! ?? $!.message !! $var.raku;

my Golfy $var2;
try $var2.golf(42);
say $! ?? $!.message !! $var2.raku;
```

## Expected Output

```
Golf.new(values => [42])
Golfy.new(values => [42])
```

## Actual Output

```
Golf.new(values => [42])
Cannot modify an immutable 'Golfy' type object
```

## Environment
* Operating system: Windows 10
* Compiler version (`raku -v`):  
```
Welcome to Rakudo™ v2022.04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.04.

**Comment by vrurg** [comment]
This is totally consistent behavior. `Golfy` gets punned when a method is invoked upon it. We cannot expect pun to care about the containerization status of the typeobject it is invoked upon. In other words, we cannot ask it to:

1. Take the container in `$v`.
2. Pull the role out of it.
3. Pun it into a class.
4. Put the class back into the container.
5. Invoke the `.golf` method on that container.

Starting step 4 we definitely go the wrong way. So, the method is invoked upon the class we got at step 3 which is, apparently, is immutable.

**Comment by dumarchie** [comment]
You may find the current behavior understandable or even acceptable, but it is not consistent. Consistency means that the method behaves the same in the two cases (implicit pun vs. explicit class).

I don't think the inconsistency is acceptable. The root cause appears to be that the [current implementation](https://github.com/rakudo/rakudo/blob/dd2b274fd59f18584171451457b15a699f7bc76e/src/Perl6/Metamodel/RolePunning.nqp#L73) does _not_ call the method on the original (raw) invocant. I have an idea about how to fix this, though, so please don't feel obliged to invest time in this issue.

**Comment by vrurg** [comment]
> You may find the current behavior understandable or even acceptable, but it is not consistent. Consistency means that the method behaves the same in the two cases (implicit pun vs. explicit class).

I disagree. The consistency means same behavior under the same circumstances. But using a role make the circumstances different. It's not even about roles as such, but about the type used to be instantiable – which role is not.

But I'd be interested to see your solution anyway. :)

**Comment by dumarchie** [comment]
@vrurg, please see  https://github.com/rakudo/rakudo/pull/4924 for my solution.

**Comment by dumarchie** [comment]
This ceases to be an issue once it's clearly documented that auto-punning is implemented in terms of delegation and hence the invocant argument is _replaced_.
