### ISSUE TITLE
Regex error message should be detected during the parsing stage

### ISSUE THREAD

**Issue by florian-pe** [rakudo/rakudo#4927]
When executing this command `raku -e '"123456" ~~ m/ ^ $<.digit>=(\d)+/'` we get back the following error message
```
bindkey_o requires a concrete object (got a VMNull type object instead)
  in block <unit> at -e line 1
```
This look like a VM error message while the actual error actually looks like an illegal syntactic or semantic regex. If that is the case, then the exception should be done during the parsing of the regex, and the error message associated should be more useful.

In constrast, here is the error message associated with `raku -e '"123456" ~~ m/ ^ <digit>=(\d)+/'`
```
===SORRY!===
Unrecognized regex metacharacter = (must be quoted to match literally)
at -e:1
------> "123456" ~~ m/ ^ <digit>⏏=(\d)+/
Couldn't find terminator / (corresponding / was at line 1)
at -e:1
------> "123456" ~~ m/ ^ <digit>=⏏(\d)+/
    expecting any of:
        /

```

**Comment by lizmat** [comment]
Thanks for your report.  Fixed with https://github.com/rakudo/rakudo/commit/da65a5f5135f453fbf1bb9013287d1682231e79a

Since it is technically not illegal code, a compilation error would not be appropriate.

Please re-open if you disagree.
