### ISSUE TITLE
No way to quiet leading-0 error message

### ISSUE THREAD

**Issue by markjreed** [rakudo/rakudo#4940]
## The Problem
Even when running under `quietly`, any attempt to use a numeric literal with a leading 0 emits a "Potential difficulties" warning.

## Expected Behavior
No warnings when `quietly` is set.

## Actual Behavior
Warnings.

## Steps to Reproduce
    `quietly do { 02 + 02 }`

## Environment
* Operating system: macOS  12.4
* Compiler version (`perl6 -v` or `raku -v`): Rakudo™ v2022.02.

**Comment by lizmat** [comment]
Hmmm...  that's because the `02 + 02` is a compile time warning, and `quietly` is a run-time catcher of warnings.

To quench the compile time warnings, use `no worries`:

````raku
do { no worries; 02 + 02 }
````
Since it's going to be very hard to let the block know that it is being run inside a `quietly`, this will take at least until RakuAST before this can get fixed (if at all).  So closing for now.

**Comment by pmichaud** [comment]
I also suggest considering the (sometimes shorter) 0d prefix:

```say 0d02+0d02;```

It allows keeping leading zeros while making it explicit (to the compiler and any subsequent readers) that it's intended to be decimal and not octal.

Pm

**Comment by melezhik** [comment]
> Hmmm... that's because the `02 + 02` is a compile time warning, and `quietly` is a run-time catcher of warnings.
> 
> To quench the compile time warnings, use `no worries`:
> 
> ```raku
> do { no worries; 02 + 02 }
> ```

Sorry @lizmat  do you mean in the this example should not be any warning at all? For some fresh Rakudo commits I do see warnings:

```
Julias-MacBook-Pro:r3tool alex$ tomty 4940
load configuration from /Users/alex/projects/r3tool/.tomty/env/config.system.pl6
index updated from https://sparrowhub.io/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/4940]
==================================================
cat $root_dir/task.bash

$RAKUBIN -v

$RAKUBIN -e 'do { no worries; 02 + 02 }' 2>&1
Welcome to Rakudo™ v2022.06.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.06.
WARNINGS for -e:
Useless use of "+" in expression "02 + 02" in sink context (line 1)
```

**Comment by lizmat** [comment]
Hmmm.... look like the "useless use" is not a worry?  hmm...

but `do { no worries; say 02 + 02 }` *is* without any warnings :-)

**Comment by melezhik** [comment]
> but do { no worries; say 02 + 02 } is without any warnings :-)

because you _say()_ that, ha-ha ,  😀

**Comment by lizmat** [comment]
Good question :-)
