### ISSUE TITLE
Error when pushing a uint8 to a Buf

### ISSUE THREAD

**Issue by hjxkyw** [rakudo/rakudo#4954]
I'm opening this issue as suggested in SO.
https://stackoverflow.com/questions/72584903/pushing-elements-to-buf/72585409#72585409

Shouldn't this just work ?

    use v6;

    my $data1 = Buf.new(1, 2, 3);
    my Buf $data2;

    my $n = $data1.bytes;

    for ^$n
    {
      my $ch = $data1.shift;
      $data2.push($ch)
    }             

I'm getting

    $ raku bufpush.raku
    Cannot resolve caller push(Buf:U: Int:D); none of these signatures matches:
        (Buf:D: int $got, *%_)
        (Buf:D: Int:D $got, *%_)
        (Buf:D: Mu:D $got, *%_)
        (Buf:D: Blob:D $buf, *%_)
        (Buf:D: **@values, *%_)
      in block <unit> at bufpush.raku line 11

Version

      $ raku -v
      Welcome to RakudoÔäó v2022.04.
      Implementing the Raku┬« Programming Language v6.d.
      Built on MoarVM version 2022.04.

OS

      $ ver
      Microsoft Windows [Version 10.0.22000.675]

**Comment by patrickbkr** [comment]
I think the problem is that $data2 is a type object (i.e. it's not initialized). The `Buf:U` bit in the error message hints that the object is *U*ndefined (the opposite would be `Buf:D`).
Writing `my Buf $data2 .= new;` seems to make this work.
Can you verify?

**Comment by patrickbkr** [comment]
One more bit of info: In signatures the thingy before the `:` specifies the object the method can be invoked on. It can be left out and defaults to the object the method is defined for. It's most often used to specify whether the method is only allowed to be called on type objects (e.g. [Blob.allocate](https://docs.raku.org/type/Blob#method_allocate)) or on concrete objects (e.g. [Blob.gist](https://docs.raku.org/type/Blob#method_gist)).

**Comment by hjxkyw** [comment]
Hi, it works, thanks.

My background is C++, then for me `my Buf data2` would invoke the "default constructor" for Buf. It seems that's not the case.
