### ISSUE TITLE
Empty CStruct disallowed

### ISSUE THREAD

**Issue by iacore** [rakudo/rakudo#4961]
## The Problem
Rakudo cannot compile empty C struct. It is valid in C though.
```
use NativeCall;
class VrDeviceInfo is repr('CStruct') is export {}
```
## Expected Behavior
This should work.

## Actual Behavior
```
===SORRY!=== Error while compiling .../ex empty struct.raku
Class VrDeviceInfo has no attributes, which is illegal with the CStruct representation.
at .../ex empty struct.raku:2
```

## Environment
* Compiler version: Raku v6.d:

**Comment by Xliff** [comment]
@locriacyber : For an empty CStruct, it might be better to make it a `repr<CPointer>`. I know this isn't the solution you want, but it is a viable workaround for the time being.

**Comment by ab5tract** [comment]
Still not working:

```
> set-base; ./rakudo-m -Ilib issues/r4961.raku
===SORRY!=== Error while compiling /Users/longwalker/code/raku/z.others/direct/rakudo/issues/r4961.raku
Class VrDeviceInfo has no attributes, which is illegal with the CStruct representation.
at /Users/longwalker/code/raku/z.others/direct/rakudo/issues/r4961.raku:2

> set-rakuast; ./rakudo-m -Ilib issues/r4961.raku
===SORRY!===
Class VrDeviceInfo has no attributes, which is illegal with the CStruct representation.

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-96-ge3ad75a69.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```

But I'm not entirely sure that the logic "it works in C" should necessarily map 100% to "it should work in NativeCall". Someone with more knowledge of both is welcome to weigh in.

**Comment by lizmat** [comment]
Closing as apparently unfixable
