### ISSUE TITLE
TakeUint8 fails on Solaris Sparc

### ISSUE THREAD

**Issue by vlmarek** [rakudo/rakudo#4962]
The TakeUint8 test fails. 

git clone
gmake
gmake install
gmake test

During compilation I can see that dyncall_callvm_sparc64.c is compiled

$ gmake test
...
t/04-nativecall/02-simple-args.t ................................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/21 subtests 
        (less 1 skipped subtest: 19 okay)
...

$ HARNESS_VERBOSE=1 '/usr/perl5/5.32/bin/perl' -I'/builds/vmarek/rakudo/rakudo/tools/lib' -I'/builds/vmarek/rakudo/rakudo/3rdparty/nqp-configure/lib' t/harness5 --moar t/04-nativecall/02-simple-args.t
...
not ok 14 - passed uint8 0xFE
...

I did edit t/04-nativecall/02-simple-args.c and placed abort() ta the top

DLLEXPORT int TakeUint8(unsigned char x)
{
    abort();
    if (x == 0xFE)
        return 10;
    return 0;
}

$ mdb core
> $C
ffffffff7fffd291 libc.so.1`__lwp_sigqueue+8(6?, ffffffff7fffdb30?, 5?, 5?, 0?, 0?)
ffffffff7fffd341 libc.so.1`abort+0xf4()
ffffffff7fffd421 lib02-simple-args.so`TakeUint8+4(fffffffffffffffe?, 100b6700?, 0?, 100b3b10?, 0?, 0?)
ffffffff7fffd4d1 0x7fffcff19914(7fffce801634?, ffffffffffffffd8?, 100105060?, ffffffffffffff40?, 7fffff2247c0?, ffffffff68000000?)
ffffffff7fffd591 libmoar.so`dcCallInt+0x10(100105040?, 7fffce801634?, 7fffcfbe22e0?, 5?, 1?, ffffffff780300c0?)

I believe that TakeUint8 receives fffffffffffffffe as an argument.

Looking at sparc assembly manual
https://docs.oracle.com/cd/E26502_01/html/E28387/gentextid-2734.html#scrolltoc

Integer data types smaller then a slot are passed in the lower part of that slot. For 64-bit code, where a smaller integer type (int, short, char) parameter is passed in a register, the caller must sign extend or zero extend the value to the full 64-bit slot width. Similarly, in 64-bit code where a smaller integer type is returned in a register, the callee must sign extend or zero extend the value to the full 64-bit slot width. In 32-bit code, there is no requirement for sign or zero extensions, and only the lower bits of the values should be used.

I have traced it a bit and I can see that `dc_callvm_argChar_v9` is getting 0xfffffffffffffffe as second argument. Here I am not sure whether it should already get 0xfe only or whether it should maybe trim the 64bit value to single char?

**Comment by lizmat** [comment]
Assuming this is no longer an issue after @niner 's work on uints
