### ISSUE TITLE
$?FILE.IO.parent(2).add("lib");   does not recognize dot-dir as noise

### ISSUE THREAD

**Issue by 0rir** [rakudo/rakudo#4963]
`$?FILE.IO.parent` does not understand that `./filename` is equivalent to `filename` if `$*SPEC eq  Unix`.

**Comment by vrurg** [comment]
It actually does exactly what it is designed for. Consider this quote from the documentation: "Note that no actual filesystem access is made". Therefore "." is what is expected. What you possibly need is `$?FILE.IO.absolute.IO.parent`.

**Comment by 0rir** [comment]
@vrurg, the problem seems to be that my script's `$?FILE` is derived from `$*PROGRAM`.   This shows because `raku run-me`  and `raku ./run-me`  look in different places when I
`use lib $FILE.IO.parent(2).add("lib");`.

**Comment by 0rir** [comment]
@vrurg,  Hopefully this is clearer.
  
Since `$?FILE.IO.CWD` is correct initially in the two runs below, it seems clear from the docs that `parent(2)` is not working consistently.   And that `parent()` has no need to add a dot here.

```
Script started on 2022-07-18 11:50:03-04:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="25"]
                                                                               
➜ ~ cat p.raku
#!/usr/bin/env raku
use v6.d;
say "\$*CWD:   $*CWD";
say "\$?FILE.IO.CWD:   $?FILE.IO.CWD()";
say "\$?FILE.IO.parent(2):  $?FILE.IO.parent(2)";
say "\$?FILE.IO.parent():  $?FILE.IO.parent()";

➜ ~ p.raku
$*CWD:  /home/rir
$?FILE.IO.CWD:  /home/rir
$?FILE.IO.parent(2): /home
$?FILE.IO.parent(): /home/rir

➜ ~ ./p.raku
$*CWD:  /home/rir
$?FILE.IO.CWD:  /home/rir
$?FILE.IO.parent(2): /home/rir
$?FILE.IO.parent(): /home/rir/.

➜ ~ exit
Script done on 2022-07-18 11:50:29-04:00 [COMMAND_EXIT_CODE="0"]
```

Thanks again.
