### ISSUE TITLE
Mutable map

### ISSUE THREAD

**Issue by MadcapJake** [rakudo/rakudo#4971]
## The Problem

I'm not sure if this is an issue with how I am creating the map or something else but I believe this should be an error.

## Expected Behavior

```
(Map)
->  { #`(Block|5639166738224) ... }
Cannot change key 'alpha' in an immutable Map
  in block <unit> at <unknown file> line 6
```

## Actual Behavior

```
(Map)
->  { #`(Block|5796558428088) ... }
foo
```

## Steps to Reproduce

```raku
class A { has $.name; has &.block; submethod BUILD(:$!name, :&!block) {} };
my %as = alpha => A.new :name<alpha> :block(->{}), beta => A.new :name<beta> :block(->{});
my Map $m := Map.new(%as.values>>.name Z %as.values>>.block);
$m.WHAT.say;
$m<alpha>.say;
$m<alpha> = 'foo';
$m<alpha>.say;
```

## Environment

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS > raku -v
Welcome to RakudoΓäó v2022.06.
Implementing the Raku┬« Programming Language v6.d.
Built on MoarVM version 2022.06.
PS >
```

Same results on home environment and bot

**Comment by Kaiepi** [comment]
If I add:

```raku
say %as.values.map({ .VAR.^name });
say %as.values».block.map({ .VAR.^name });
say map *.map({ .VAR.^name }), slip %as.values».name Z %as.values».block;
say $m.values.map({ .VAR.^name });
```

I get:

```
(Scalar Scalar)
(Block Block)
((Str Block) (Str Block))
(Scalar Scalar)
```

Indicating the container that's allowing for this to happen doesn't appear until `Map.new`. I get the error if I change `Z` to `Z=>`, but I'm not sure why it's happening with the kv case specifically.

**Comment by lizmat** [comment]
A `Map` is immutable with regards to its keys, just as a `List` is immutable with regards to its indices.

However, if a value in a `Map` is a container, then it *is* possible to change it, just as with `List`.  And this is the very reason that `List` and `Map` are not value types, sadly.
````raku
my %m is Map = a => my $ = 42;
dd %m<a> = 666;  # 666 
````
If you want to have full immutability now for Associatives, check out [ValueMap](https://raku.land/zef:lizmat/ValueMap).

I think this issue can be closed.
