### ISSUE TITLE
'subset' lacking restriction can hang program

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#4980]
## The Problem
Certain <code>subset</code> definitions can cause a program to hang (and consume huge amounts of memory).

## Steps to Reproduce
As written, this code never returns from the subroutine call (add the <code>where</code> restriction and things are fine).
```
subset Boo of Int; # where * > 0;  
sub foo() returns Boo { 42 }
say foo();
```
## Environment
First noticed the issue with build v2022.06-46-g934f9895e, on macOS and Ubuntu.

## Related?
With the same Raku build, Rosetta-code programs using the HTTP::Useragent module started to exhibit the same behavior.

**Comment by lizmat** [comment]
Confirmed on HEAD.  @vrurg

**Comment by vrurg** [comment]
Who told you it's mine? 😉

Ok, confirmed too. Shouldn't be a big deal.

**Comment by vrurg** [comment]
@SqrtNegInf thanks for reporting!
