### ISSUE TITLE
A tight loop doesn't let a Promise to complete in a parallel thread

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#4989]
## The Problem

If a tight loop is started in one thread and timed `Promise` in another (`sleep` or `Promise.in`) then there are very high risk of the timed promise to deadlock.

## Steps to Reproduce

The following code is likely to never print "OK".

```raku
start loop {};

await start {
    sleep 1;
    note "OK";
}
```

Tested on Linux and macOS.

**Comment by vrurg** [comment]
Rough release-level bisection points out at a commit between 2021.09 and 2021.10. Bisectable failed to find the exact commit but I hope to locate it by bisecting locally.

**Comment by lizmat** [comment]
I can't get this to hang.  Test added with https://github.com/Raku/roast/commit/d1a798be60
