### ISSUE TITLE
map function trips over  newline

### ISSUE THREAD

**Issue by 0rir** [rakudo/rakudo#4998]
Is this intended?

```
raku -e 'map { $_=> $_ }   
            , < a b >;'
```
^[[31m===^[[0mSORRY!^[[31m===^[[0m Error while compiling /home/rir/2rr
Missing comma after block argument to map
at /home/rir/2rr:3
------> ^[[32msay map { $_=> $_ }^[[33m⏏^[[31m<EOL>^[[0m

**Comment by jnthn** [comment]
Yes. A `}` followed by horizontal whitespace (including line comments) is always considered to be a statement terminator.
