### ISSUE TITLE
Precompilation is now recompiling already precompiled modules.

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#5009]
## The Problem

I am noticing that Rakudo is recompiling modules  that have already been precompiled.

## Expected Behavior

I should be getting much lower times in my weekly compile tests. 

## Actual Behavior

Instead, I am noticing that one project is recompiling modules that have already been precompiled.

## Steps to Reproduce

- zef install Cairo
- Create temp directory: `mkdir p6GLibSuite`
- cd p6GLibSuite
- git clone https://github.com/Xliff/p6-GLib.git
- git clone https://github.com/Xliff/p6-ATK.git
- git clone https://github.com/Xliff/p6-GIO.git
- git clone https://github.com/Xliff/p6-Pango.git
- git clone https://github.com/Xliff/p6-GtkPlus.git
- git clone https://github.com/Xliff/p6-Handy.git
- `p6-GLib/install-prereqs.sh`
- `for a in GLib ATK GIO Pango GtkPlus Handy; do (cd p6-$a; scripts/dependency-build.sh); done
- The buildlog should be in p6-Handy/LastBuildResults

Here is the [log from my latest build attempt](https://github.com/Xliff/p6-Handy/blob/main/stats/ParallelBuildResults-20220731).

## Environment
* Operating system: 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

Linux InfinityV 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo™ v2022.06-71-gb9c90bc79.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.06-9-gced366862.
```

**Comment by Xliff** [comment]
To put the log file in perspective, there should be no recompilation of Pango, GDK, or GtkPlus modules in there, as they were already completed in the previous steps of the build process.

**Comment by patrickbkr** [comment]
Has this possibly been fixed by https://github.com/rakudo/rakudo/commit/cc7193d0a6d95bd580a4b2783795d082a56d8e6d ?

**Comment by Xliff** [comment]
@patrickbkr - I usually do my compiles on Sunday. I will let you know, then.

**Comment by Xliff** [comment]
@patrickbr - Timings have verified that this issue has been fixed. Not sure about which commit did it, though.

Thanks for asking!
