### ISSUE TITLE
Add 'ask' as an alias for 'prompt'

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#5022]
## The Problem

I can never remember the Raku routine name for prompting for user input. I and at least one other Rakuun think 'ask' is easier to remember than 'prompt'.

**Comment by Altai-man** [comment]
>I can never remember the Raku routine name for prompting for user input

But a routine for prompting for user input is literally "prompt".

**Comment by lizmat** [comment]
@Altai-man agree

@tbrowder doesn't `ask` always imply a question to which an answer is needed?  What if we're prompting the user to ask a question?  I think `prompt` is more neutral.

Also, if you really want to use `ask`, then:

````raku
my constant &ask = &prompt;
````
anywhere in your code, will do the job.

If you'd like to have a set of aliases, maybe create a module that should just contain:

````raku
sub EXPORT() {
    Map.new: (
        '&ask'  => &prompt,
        '&find' => &grep,
        # etc etc
    )
}
````

**Comment by tbrowder** [comment]
In my scripts, I’m ‘ask’ing for user input, prompting can meant get one’s attention. I can’t think, in my domain at least, when I’m not ‘ask’ing for something.

**Comment by Altai-man** [comment]
Renaming a CORE thing is a very bad practice, and adding aliases is something that probably shouldn't be done too.

As it's easy tweaked for local projects as shown above, I believe this can be closed as a wontfix. Please, re-open if disagree.

**Comment by tbrowder** [comment]
At least one core dev gave a +1 for the idea. I think it appropriate to ask for a vote on \#raku or \#raku-dev or at least get some other opinions. Remember when we changed several routine names not so many years ago, so it's not like the language is carved in stone. 

Also, note recently how newcomers on IRC discuss confusing Raku naming. I love the the idea of adding appropriate aliases for our 100 year language--especially since the common US English grammmar seems to be changing rapidly.

**Comment by melezhik** [comment]
I second `ask` - it's short and it asks for a user input, what exactly happens during prompt.
From other hand I do understand a certain level of tentativeness of brining new names into a core.

**Comment by tbrowder** [comment]
I am about to release a new version of my Text::Utils, which I use often, and it exports alias 'ask' for routine 'prompt' by default.

**Comment by lizmat** [comment]
A shorter name should only be used for something that is used a lot.

Admittedly, that would be true for *some* users of Raku.  But even then, I'd argue that in a CLI script that prompts a user for input, the input taking part is usually the smallest part of the program.

And yes, it is only one line in the core.  But that line includes also adding tests for it.  And does require documentation.  This is also something that should be taken into consideration.

I'm still leaning to creating a module for it, for `ask` alone, or for any other esoteric names such as `grep`.

**Comment by tbrowder** [comment]
I have created 'ask' in one of my modules just published yesterday. What would you suggest naming a single purpose module? Maybe *RakuAliases* or just *Ask*?

**Comment by lizmat** [comment]
`use ask` seems to be the right way to load such a module.  So "ask"  :-)

**Comment by tbrowder** [comment]
That is close to DIY (do it yourself):

    constant &ask = &prompt;

except ^^^ uses more chars by my count.

**Comment by tbrowder** [comment]
> `use ask` seems to be the right way to load such a module. So "ask" :-)

You do like lower-case module names, don't you? But that would probably be better because it would seem closer to a built-in (maybe that's been the motivation for yours).

So be it: you 'ask'ed for it and you'll get it!

**Comment by 2colours** [comment]
After some pondering, I decided to "ping" this issue as a part of my voluntary "garbage collector" activity... If I understand correctly, the participants have reached an agreement that `ask` will not get added to the core language, however @tbrowder 's own [Ask module](https://raku.land/zef:tbrowder/Ask) can be used to provide the proposed alias in a lightweight way.

Can this issue be closed now?

**Comment by lizmat** [comment]
Yes
