### ISSUE TITLE
Support asynchronous unix domain sockets

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#5024]
## The Problem

Currently we support asynchronous IP sockets (`IO::Socket::Async`), but not asynchronous unix domain sockets.

We should add support for this.

This is a Rakudo problem that needs a [MoarVM](https://github.com/MoarVM/MoarVM/issues/1734) solution.

**Comment by Kaiepi** [comment]
This is something I wanted to do a while back, but I'm caught in a long-winded MOP tangent to get the type system complete enough for abstractions to do with the `ProtocolFamily`/`SocketType`/`ProtocolType` enums that would ultimately define `IO::Socket`'s behaviour across backends to be possible to implement. A few notes:

- Windows has [UNIX sockets](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) nowadays.
- This can be implemented on the JVM, but requires [JDK 17](https://openjdk.org/jeps/380) (16 is not LTS).
- If purely a networking issue, we're left with UNIX sockets only usable with socket ops.
- A more complete implementation would consider I/O ops on file descriptors as well.
