### ISSUE TITLE
A sigilles symbol declared withing a list context is incorrectly treated as a type object

### ISSUE THREAD

**Issue by wimvanderbauwhede** [rakudo/rakudo#5027]
## The Problem

According to the spec, `:exists` doesn't autovivify. However, given this code:

```perl6
use v6;
my ( Map \labels,\_) = reduce(
                -> List \acc_, Int \token_ {
                    my ( Map \labels_,  Int \prev_token_ ) = acc_;
                    if labels_{prev_token_}:exists
                    {
                        [labels_,token_]
                    } else {
                        [Map.new(labels_.list,Pair.new(token_,token_)),token_]
                    }
                },
                [Map.new,0],
                |(1 .. 10)
            );
say labels.raku;
```
I get the error

*"Autovivifying object closures not yet implemented. Sorry."*

## Expected Behavior

The expected behaviour is that the `:exists` does not attempt to autovivify, so there should be no error

There is a simple workaround

```perl6
use v6;
my ( Map \labels,\_) = reduce(
                -> List \acc_, Int \token_ {
                    my ( Map \labels_,  Int \prev_token_ ) = acc_;
                    my Map \dummy_for_test = Map.new(labels_.list); 
                    if dummy_for_test{prev_token_}:exists
                    {
                        [labels_,token_]
                    } else {
                        [Map.new(labels_.list,Pair.new(token_,token_)),token_]
                    }
                },
                [Map.new,0],
                |(1 .. 10)
            );
say labels.raku;
```
and this produces the expected behaviour

## Actual Behavior

See above

## Steps to Reproduce

Run the above program.

## Cause of the error

The cause of the error seems to be that the `Map` is wrapped in a list for the accumulator. The following works just fine (but does of course not what I want):

```perl6
use v6;
my  Map \labels = reduce(
                -> Map \labels_, Int \token_ {
                    if
                        labels_{token_}:exists
                    {
                        labels_
                    } else {
                        Map.new(labels_.list,Pair.new(token_,token_))
                    }
                },
                Map.new,
                |(1 .. 10)
            );
say labels.raku;
```

## Environment
* Operating system: tested on MacOS and Linux
* Compiler version (`perl6 -v` or `raku -v`): v2022.06

**Comment by niner** [comment]
I think it's a mis-parse, so the error message may just be misleading. Shouldn't there be a space between `Int \token_` and the `{`?

**Comment by wimvanderbauwhede** [comment]
No, the workaround and the simplified version both work without that space. I added a space to make sure, still same problem. Will edit the code to reflect that.

**Comment by wimvanderbauwhede** [comment]
It works with that dot added, but my workaround does not have a dot and works too. If it was a mis-parsing, should it not fail too? And the simplified example in "Cause of the error", which also works, does not have a dot either, but does not fail.

**Comment by vrurg** [comment]
I wouldn't tell without checking out the grammar code. But the error comes from it, not from `Map`. Moreover, there is no way it could be produced `Map`. After all, it's not event `Map` job to deal with closures.

**Comment by lizmat** [comment]
The rules for adverbs are still a bit misty to me, I must admit.
````raku
say 1 + 4 :foobar
# Cannot resolve caller infix:<+>(Int:D, Int:D, :foobar); none of these signatures matches:
````
Note that the adverb applies to the op, so you could create your own infix op with `:foobar`.  I'm pretty sure you somehow got bitten by that feature.

**Comment by vrurg** [comment]
The whole thing golfs down to this:

```raku
my (Map \foo) = Map.new;
foo{1};
```

Turns out that the compiler interprets `foo` as a type object with all the consequences. Fix is upcoming and it is likely to resolve a couple of related bugs.
