### ISSUE TITLE
Multi method dispatcher doesn't correctly priorize mandatory named arguments in methods

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#5038]
## The Problem

This code
```
class Foo {
    multi method foo(Any :$type) {
        say 1;
    }
    multi method foo(Any :$default!) {
        say 2;
    }
}

Foo.foo(:42default);
```
Will print `1`, instead of the expected `2`. Unlike the non-method equivalent:
```
multi foo(Any :$type) {
    say 1;
}
multi foo(Any :$default!) {
    say 2;
}
foo(:42default);
```
that does print `2` as one would expect.

Making `$type` also mandatory fixes it, but I'm at a loss why it priorized it in the first place

## Environment
```
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
```

**Comment by jnthn** [comment]
Multiple dispatch as specified in S12 [does not consider named parameters](https://design.raku.org/S12.html#Multisub_Resolution) as an explicit part of the candidate selection process. Named parameters may play a tie-breaking role, by the same mechanism that `where` clauses and signature unpacking do: the candidates that nominally match are tried in order until one of them has a signature that binds.

Methods have an implicit `*%_` argument for interface compatibility, so `foo(Any :$type)` - the first candidate - will match by virtue of the provided named argument being slurped up. This is not the case for `sub`s, thus the first candidate doesn't match. (This can be verified by declaring `class Foo is hidden { ... }` to suppress production of the implicit `*%_`).

What's written in S12 certainly doesn't rule out a language change in the future that more explicitly includes named parameters and the new dispatch mechanism would allow for it to be decently performant. I'd imagine such a change would have to be introduced at a language version boundary.

Either way, Rakudo is, best I can tell, working as intended in this regard.

**Comment by Leont** [comment]
> Multiple dispatch as specified in S12 [does not consider named parameters](https://design.raku.org/S12.html#Multisub_Resolution) as an explicit part of the candidate selection process. Named

> Methods have an implicit *%_ argument for interface compatibility,

That is a rather unfortunate interaction between two features that do make sense individually.

> This can be verified by declaring class Foo is hidden { ... } to suppress production of the implicit *%_

That suggests that this behavior could be accessed without hiding the entire class?

> What's written in S12 certainly doesn't rule out a language change in the future that more explicitly includes named parameters and the new dispatch mechanism would allow for it to be decently performant.

That would be awesome, but I can imagine writing such a dispatcher is rather non-trivial.
