### ISSUE TITLE
Inconsistency using "with" chained with "for"

### ISSUE THREAD

**Issue by frithnanth** [rakudo/rakudo#5049]
## The Problem

I noticed this behavior, demonstrated here using the REPL, but it works the same as a regular program:

```
[0] > my @a = <a b c d e>
[a b c d e]
[1] > .say with $_ for @a
()
[2] > .say if .defined for @a
a
b
c
d
e
[3] > (.say with $_) for @a
a
b
c
d
e
[4] > (.say if .defined) for @a
a
b
c
d
e
```

## Expected Behavior

I was expecting that the line marked as [1] would emit the same output as the other statements.

## Actual Behavior

Apparently "with" works only as a statement modifier while "if" works both ways.

## Environment
* Operating system: Debian sid
* Compiler version (`perl6 -v` or `raku -v`): v2022.07

**Comment by 2colours** [comment]
Yes, it's interesting the least to say.

I still don't understand what happpens exactly but I have another related pair:

`.say if 1 for <a b c>˙ versus `.say with 1 for <a b c>`. The former will produce all 3 letters on new lines, the latter only produces `1`. It almost seems like the latter is not a loop and the `for` part is lost altogether.  
Further evidence to support this idea: `.say with .say for @a` and `.say with .say` produce the same output: `(Any)` (the default value of $_) followed by `True` (the return value of &say).
