### ISSUE TITLE
IO::Notification appears not be working in 2022.07

### ISSUE THREAD

**Issue by jonathanstowe** [rakudo/rakudo#5050]
This comes as somewhat of a surprise to me, but:

```
raku -e 'react { whenever IO::Notification.watch-path("META6.json") -> $c { say $c } }'
A react block:
  in block <unit> at -e line 1

Died because of the exception:
    file watch target queue must have ConcBlockingQueue REPR
      in block <unit> at -e line 1
```
It is the same with the `watch` method on an `IO::Path`:

```
raku -e 'react { whenever "META6.json".IO.watch -> $c { say $c } }'
```

With:

```
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
```

It works fine if `use v6.c;`  is provided explicitly.  As far as I can see there is nothing in the code that suggests there should be a version specific difference.

**Comment by jonathanstowe** [comment]
Another data point it *does* work fine with

```
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.07-11-g2c0343b5b.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.07-8-g860cc6550.
```

With or without specifying the raku version.  Not in a position to bisect better at the moment.

**Comment by ugexe** [comment]
It works on 2022.03

**Comment by 2colours** [comment]
Bisects to: https://github.com/rakudo/rakudo/commit/64317c4eedf27df7c411413e7029b86c26cbd232 @lizmat do you have any idea why this might be?

**Comment by jonathanstowe** [comment]
> Bisects to: [64317c4](https://github.com/rakudo/rakudo/commit/64317c4eedf27df7c411413e7029b86c26cbd232) 

Looking at the change I can't see how that could be the offending commit, as far as I can see it doesn't touch anything that the IO::Notification uses, plus it definitely doesn't explain the version specific thing.

**Comment by lizmat** [comment]
Yeah, that had me puzzled as well.

**Comment by lizmat** [comment]
First of all, reverting the bisected commit *does* fix this issue.

Secondlyl, put the IO::Notification code into a script, and it just works (with minor, non-essential tweaks).

However, the example code fails using the core functionality.

So this is getting very weird.

At https://github.com/rakudo/rakudo/blob/master/src/core.c/IO/Notification.pm6#L29 the return value of $scheduler.queue is a `ForeignCode` object.  But https://github.com/rakudo/rakudo/blob/master/src/core.c/ThreadPoolScheduler.pm6#L301 returns a `ThreadPoolScheduler::Queue`.  I don't see anything between it that could screw up.

**Comment by lizmat** [comment]
Going to close this one now.  I don't have the energy to find out what it was that exactly caused this issue.  And the performance win was marginal at best.

**Comment by Marcool04** [comment]
Thanks @lizmat for finding a fast solution to the IO::Notification issue!
