### ISSUE TITLE
Inconsistent behavior of returning `Empty` value using `map` sub on `Supply` and plain `Array`.

### ISSUE THREAD

**Issue by ohmycloud** [rakudo/rakudo#5053]
## The Problem

The behavior of returning `Empty` value using `map` sub on `Supply` and plain `Array` is inconsistent.

For more information, please refer [this stackoverflow question](https://stackoverflow.com/questions/73564945/inconsistent-behavior-of-map-function-with-empty-value-in-supply-and-plain-array).

## Expected Behavior

The behavior of returning `Empty` value using `map` sub on `Supply` and plain `Array`  should be consistent.

## Actual Behavior

Returning `Empty` value using `map` sub on `Supply` will return empty  parentheses when something goes wrong.

## Steps to Reproduce

```perl
my @strings = ["a", "1.24", "3", "def", "45", "0.23"];
my Supply $supply = Supply.from-list(@strings);
my Supply $compact = $supply.map(-> $value {
  try { Num($value) }
  if $! { Empty } else { Num($value) }
 }); 

$compact.tap( &say);
```

Output:

```
()
1.24
3
()
45
0.23
```

However, when return the `Empty` value using `map` on plain Array, It doesn't output empty parentheses:

```perl
my @strings = ["a", "1.24", "3", "def", "45", "0.23"];

my @compacted = @strings.map(-> $value {
    try { Num($value) }
    if $! { Empty } else { Num($value) }
});

.say for @compacted;
```

Output:

```
1.24
3
45
0.23
```

## Environment

* Operating system: Win11
* Compiler version (`perl6 -v` or `raku -v`):  Rakudo™ v2022.07.

**Comment by jnthn** [comment]
The design rationale for why it was done this way: a `Slip` is very much a list-y concept (it even inherits from `List`, as does `Array`); just as a `Supply` would just be a single value when doing flattening-related operations in list space, so any kind of list is a single value when doing operations in supply space.

**Comment by Leont** [comment]
Another place where a flatmap would be most welcome.

**Comment by ohmycloud** [comment]
> Another place where a flatmap would be most welcome.

maybe a `filter_map` would be most welcome.
