### ISSUE TITLE
Traits `is hidden-from-backtrace` and `is DEPRECATED` conflict

### ISSUE THREAD

**Issue by rbt** [rakudo/rakudo#5055]
The line number of the deprecation is reported incorrectly when these 2 traits are used together.

This code block reports the internal END phaser code location instead of the location where f() is called.

```
#!/usr/bin/env raku

sub f() is hidden-from-backtrace is DEPRECATED('the literal 42') { 42 }

END {
	say f();
}
```

```
42
Saw 1 occurrence of deprecated code.
================================================================================
Method protect (from Lock) seen at:
  SETTING::src/core.c/Rakudo/Internals.pm6, line 1777
Please use the literal 42 instead.
```

This can be seen on 2022.03 and 2022.07.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/43a6575b2d
