### ISSUE TITLE
repl can't find / recognize readline lib (macos)

### ISSUE THREAD

**Issue by masukomi** [rakudo/rakudo#5058]
## The Problem
REPL doesn't recognize that readline has been installed via Homebrew as instructed

## Expected Behavior
silently use repl from homebrew

## Actual Behavior
```
I ran into a problem while trying to set up Readline: ===SORRY!===
On macOS Perl6::Readline requires installing Readline via Homebrew
```

## Steps to Reproduce
* readline 8.1.2 - installed via homebrew
* Rakudo™ v2022.07. Built on MoarVM version 2022.07.

launch with 
* `raku`
* or ` rlwrap --always-readline raku`

## Environment
* Operating system: macOS 12.5.1 (Monterey)
* Compiler version
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.

**Comment by vrurg** [comment]
Have you tried with `Readline` module installed?

Otherwise, I just have tested with `rlwrap` installed via MacPorts and the history is there, even the persistent one.

**Comment by masukomi** [comment]
> Have you tried with Readline module installed?


`zef uninstall Readline` results in 
```
 ===SORRY!=== Error while compiling /Users/masukomi/workspace/GitWork/vendor#sources/2968BBAF455A193E8CBE3E6C35152729BE48F82D (Terminal::LineEditor::RawTerminalInput)
```
which makes me think it probably _was_ installed because i wasn't seeing errors about that and that seems like something that would be required for the REPL to work.

I can't say if it was or wasn't installed, but that result makes me think it must have been. It _is_ installed now and it _is_ working but i can't say what exactly fixed it.
I can't currently replicate the problem anymore.

**Comment by masukomi** [comment]
> I just have tested with rlwrap installed via MacPorts and the history is there, even the persistent one.

i'm not sure how the preservation of history is relevant to an error about trying to set up Readline.
