### ISSUE TITLE
Misleading error message when trying to feed shaped array on declaration

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5061]
## The Problem
Fixed-dimension arrays can say "Cannot append a fixed-dimension array" when trying to feed them with <==. However, when they are just created, they not only still cannot be fed but say the very generic and vague "Only routine calls or variables that can '.push' may appear on either side of feed operators." message.
## Expected Behavior
Either the feeding should succeed - or an error message referring to fixed-dimension arrays should show up, like when fed later after the declaration.
## Actual Behavior
Compilation error, saying "Only routine calls or variables that can '.push' may appear on either side of feed operators."
## Steps to Reproduce

```
raku -e 'my @array[3,3] <== [0..8]'
```

## Environment
* Operating system: Ubuntu 20.04 in WSL2 ("Linux 5.10.102.1-microsoft-standard-WSL2 # 1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux")
* Compiler version (`perl6 -v` or `raku -v`): Rakudo™ v2022.04, built on MoarVM version 2022.04.

**Comment by lizmat** [comment]
Thanks for the report. https://github.com/rakudo/rakudo/commit/2070ceebbdc04c2853aca83c392570785c6a0a8d changed this to:
````
$ raku -e 'my @array[3,3] <== [0..8]'
===SORRY!=== Error while compiling -e
Cannot feed into shaped arrays, as one cannot '.append' to them.
````
