### ISSUE TITLE
$*USER and $*GROUP are Any on windows.

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#5066]
## The Problem
```
$ raku -e 'dd $*USER, $*GROUP'
Any
Any
```
## Expected Behavior
Something including my windows userid

## Environment
```
$ sw_vers.bat

C:\sandbox\rakudo>systeminfo   | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19044 N/A Build 19044

$ raku --version
Welcome to Rakudo™ v2022.04-42-ge9de06b85e.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.04.
```

**Comment by coke** [comment]
Windows has 'whoami' which gives probably more information than is needed; %*ENV<USERNAME> gives the basic userid. I don't think there's a numeric equivalent to the id; there is a SID that is alphanumeric, but then we can't use that ID in the numeric context.

I would recommend either making this object smarter than an IntStr or splitting the ID and Str versions into two separate variables to track support on multiple OSes.

**Comment by lizmat** [comment]
If someone with Windows access could provide me with the correct `whoami` invocation and sample output, I could give a stab at this

**Comment by coke** [comment]
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/whoami - the plain whomai *just* outputs the username - I get something like `some_domain\coke` and I'd expect the whole thing to be included in `$*USER`

For groups, please see 

https://stackoverflow.com/questions/63839718/how-do-you-get-to-compare-the-output-of-whoami-groups-to-check-whether-a-certai

- There is a lot of output (and I don't want to share $DAYJOB groups here), but the CSV output should be pretty easily parseable - if you use the CSV output, the first row is headings, groups begin on row 2. if GROUP is just the primary group, I'm not sure windows has an exact correspondence to that - I assume that picking the first row of data in this output is best, and it'll be the first column. It also always appears to be wrapped in quotes, even if it's not strictly necessary.

so something like:

```
"Group Name","Type","SID","Attributes"
"Some Group","...","<guid>","<attributes>
```

And from this you can extract `Some Group`

**Comment by patrickbkr** [comment]
This is what I see on my Windows 11 machine:

```
PS C:\data\repos\install> .\bin\raku.exe -e 'dd $*USER, $*GROUP'
"taurus-win\\patrick"
"Everyone"
```

**Comment by lizmat** [comment]
Then I consider this one fixed!  @patrickbkr thanks for checking!
