### ISSUE TITLE
IteratorEnd as user input can truncate iterators

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#5068]
## The Problem

While working on `List.STORE`, I stumbled on an ugly edge case:

```raku
say [1, IterationEnd, 2];
say (1, IterationEnd, 2);
say gather { # Careful not to listify here.
    take 1;
    take IterationEnd;
    take 2;
};
```

## Expected Behavior

Should output:
```
[1 IterationEnd 2]
(1 IterationEnd 2)
(1 IterationEnd 2)
```

## Actual Behavior

Outputs:
```
[1 IterationEnd 2]
(1)
(1)
```

`Array` and its subtypes are probably not afflicted by virtue of its containers as a default. I have no idea how widespread a problem this is in core beyond constructors for `Seq` and `List` themselves.

## Steps to Reproduce

Run the golf.

## Environment
* Operating system:
```
Linux LAPTOP-7I9RCT0C 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
```
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo™ v2022.07-40-g2070ceebb.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07-10-g4575c4745.
```

**Comment by Kaiepi** [comment]
The `Seq` case has a deceptive `gist` apparently:

```raku
say (gather take IterationEnd)[0]; # OUTPUT:
# IterationEnd
```

**Comment by jnthn** [comment]
`IterationEnd`'s entire purpose is to be a value that signals the end of an iteration.

**Comment by 2colours** [comment]
Following the sentiment of @jnthn , I think the current behavior might be wrong "in the opposite direction", that is, Array also should truncate, if List and Seq do.

**Comment by lizmat** [comment]
It's not a sentiment by @jnthn, it's a design fact!

**Comment by Kaiepi** [comment]
If a `List` containing an intermediate `IterationEnd` is incalculable via `Iterable` to the point of breaking core methods like `gist`, then I think it should terminate the reification so more C-ish `AT-POS`-based algorithms can be consistent about it and so the gist matches the reality. I'm having a difficult time accepting what I thought was our equivalent to `void *` behaving like a C string though.

**Comment by lizmat** [comment]
````
$ raku -f 'say CORE::.keys.elems for ^5'
703
703
703
703
703
$ raku -e 'say CORE::.values.elems for ^5'
105
210
365
415
476
````
This is because one of the values in `CORE::` **is** `IterationEnd`, and hash randomisation makes the moment at which it is encountered random.

**Comment by lizmat** [comment]
@Kaiepi: I think a list with `IterationEnd` as one of its values, is a case of DIHWIDT.  Although `IterationEnd` **is** a HLL feature, it is also documented as:

> The only valid use of the sentinel value IterationEnd in a program is identity comparison (using [=:=](https://docs.raku.org/routine/=:=)) with the result of a method in the iterator API. Any other behavior is undefined and implementation dependent. For instance, using it as part of a list that's going to be iterated over might result in the loop ending, or not.

See https://docs.raku.org/type/Iterator#IterationEnd

**Comment by lizmat** [comment]
I'm inclined to close this issue.

**Comment by Kaiepi** [comment]
The input has to come from somewhere, I guess. Coercers doing it would also be undefined.

**Comment by lizmat** [comment]
The use of the word "sentiment".

<img width="337" alt="image" src="https://user-images.githubusercontent.com/2229339/192317978-17317dc7-57e6-43a2-8d70-cf87e7489aad.png">

I wanted to make sure that you understood that @jnthn, as the designer of that particular interface, was not stating an opinion, but a fact.

**Comment by 2colours** [comment]
Perhaps I just shouldn't try to use C2 words, then. It's a bit hard with a foreign language that you use too much to tell apart what you know for sure and what you just think you know. :)

I had something in mind that probably works better with "approach" or "presumption"; something that could be a fact or an opinion but most importantly it has consequences. If IterationEnd signals the end value, then that would have an impact on the expected result.

But in the end, this particular behavior does seem to be documentedly a corner case that should never reasonably happen. 👍
