### ISSUE TITLE
[JVM] X::TypeCheck::Assignment when assigning a sub returning Int:D to correspondingly typed variable

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#5069]
## The Problem
With commit https://github.com/Raku/roast/commit/36cc3ad363 I had to fudge a couple of new failing spectests for the JVM backend.

One of those is the following: https://github.com/Raku/roast/blob/36cc3ad363/MISC/misc-6.d.t#L140-L143.

The assignment to ```&foo``` now blows up as follows:
```
$ ./rakudo-j -e 'my Int:D &foo = sub (--> Int:D) {}'
Type check failed in assignment to &foo; expected Callable[Int:D] but got Sub+{Callable[Int:D]} (sub ( --> Int:D) { #...)
  in block <unit> at -e line 1
```

## Expected Behavior
```
./rakudo-m -e ''my Int:D &foo = sub (--> Int:D) {}; say &foo.of'
(Int:D)
```

## More details
I bisected the problem to https://github.com/rakudo/rakudo/commit/71de22321d. (Which caused more trouble for the JVM backend -- see https://github.com/rakudo/rakudo/issues/5037.)

The underlying problem seems to be that ```nqp::istype()``` in https://github.com/rakudo/rakudo/blob/71de22321d/src/Perl6/bootstrap.c/BOOTSTRAP.nqp#L1794 no longer returns ```1``` after that commit.

old behaviour (before https://github.com/rakudo/rakudo/commit/71de22321d):
```
$ ./rakudo-j -e 'use nqp; my Int:D &foo; my &bar := sub (--> Int:D) {}; my $desc := nqp::getattr(&foo, Scalar, "\$!descriptor"); my $type := $desc.of; say nqp::istype(&bar, $type)'
1
```

new behaviour (on https://github.com/rakudo/rakudo/commit/71de22321d):
```
$ ./rakudo-j -e 'use nqp; my Int:D &foo; my &bar := sub (--> Int:D) {}; my $desc := nqp::getattr(&foo, Scalar, "\$!descriptor"); my $type := $desc.of; say nqp::istype(&bar, $type)'
0
```

I don't grasp the details yet, but it looks like the ```type``` passed in to ```istype_nd``` doesn't find a matching type in the ```TypeCheckCache```: https://github.com/Raku/nqp/blob/c25f65458b/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java#L2653-L2655 (It did find a match at index 1, before.)

Either the wrong ```TypeCheckCache``` is used, or there was a different type at index 1 when the cache was set up (in https://github.com/Raku/nqp/blob/c25f65458b/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java#L2606).

**Comment by usev6** [comment]
I think, I'm now very close to the underlying problem.

In the past, the following two pieces of code resulted in a call to ```nqp::parameterizetype``` (https://github.com/Raku/nqp/blob/bddcbca4b7/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java#L3603) with two identical ```params```:
```my Int:D &foo```
```my &bar := sub (--> Int:D) {}```

As a result, for the second call to ```nqp::parameterizetype``` the lookup in the parameterization array returned an existing result. https://github.com/Raku/nqp/blob/bddcbca4b7/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java#L3628

Starting with 71de22321d there is a third element in ```params``` when ```nqp::parameterizetype``` is called.

This third element is the new ```$archetypes_idx``` from https://github.com/rakudo/rakudo/blob/30a9d3a40a/src/Perl6/Metamodel/DefiniteHOW.nqp. It is computed in https://github.com/rakudo/rakudo/blob/30a9d3a40a/src/Perl6/Metamodel/DefiniteHOW.nqp#L23-L25.

Now my debugging revealed that this third element in ```params``` is an instance of P6int with the value of 0 for both, ```my Int:D &foo``` and ```my &bar := sub (--> Int:D) {}```.
**But**, those two instances of P6int are not "the same thing" from the perspective of the JVM backend. And therefore this condition becomes true for the second call to ```nqp::parameterizetype``` and as a result a new object is created after the for loop: https://github.com/Raku/nqp/blob/bddcbca4b7/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java#L3622

With the following patch the code from the original report started to work again:
```
diff --git a/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java b/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
index fb1d4bdc9..dd1f6378f 100644
--- a/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
+++ b/src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
@@ -3620,8 +3620,14 @@ public final class Ops {
                     SixModelObject got = compare.at_pos_boxed(tc, j);
                     /* XXX More cases to consider here. */
                     if (want != got) {
-                        match = false;
-                        break;
+                        if (isconcrete(want, tc) == 1 && isint(want, tc) == 1
+                                && isconcrete(got, tc) == 1 && isint(got, tc) == 1
+                                && decont(want, tc).get_int(tc) == decont(got, tc).get_int(tc)) {
+                            continue;
+                        } else {
+                            match = false;
+                            break;
+                        }
                     }
                 }
                 if (match)
```

I'm not totally sure, but I think the underlying reasons for the differing behaviour is, that native long, string or double values returned from Java methods into NQP code always lead to the creation of new objects.
With MoarVM it looks like at least the numbers from 0 to 14 behave somehow different. Probably that's not relevant for the case of ```nqp::parameterizetype```, but still:
```
$ ./nqp-m -e 'say(nqp::eqaddr(nqp::bitor_i(0, 0), 0))'
1
$ ./nqp-m -e 'say(nqp::eqaddr(nqp::bitor_i(1, 0), 1))'
1
$ ./nqp-m -e 'say(nqp::eqaddr(nqp::bitor_i(14, 0), 14))'
1
$ ./nqp-m -e 'say(nqp::eqaddr(nqp::bitor_i(15, 0), 15))'
0
```

For the JVM backend all of the above evaluations give a ```0```.

**Comment by niner** [comment]
Yes, MoarVM has a cache for small integers. Since Ints are immutable (actually 
they are not -> mixins), it's supposedly safe to re-use objects. If something 
is relying on this object re-use, I'd call it a bug though.

**Comment by usev6** [comment]
[A short discussion on raku-dev yesterday](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2022-10-05#l104) made it clear that ```nqp::parameterize``` should compare the values of integers (or strings or floating-point numbers), not just if they are the same object.

**Comment by jnthn** [comment]
When I originally implemented `nqp::parameterizetype` I only had parameterization by type objects, not by concrete values, in mind (effectively, only type operators, not dependent types). One might choose to extend it, but at some point the question will then come up: why only certain built-in types are identical, but not other things that are `===` or `eqv` in Raku? At which point a lot of aspects of the current implementation will need revisiting, because they were only intended to deal in pointer identity.

**Comment by usev6** [comment]
For the record: The other day I stumbled upon commit 4b60df8f84 from 2017 where ```Definite``` and ```NotDefinite``` were introduced. The commit message is directly related to the discussion above.

> Parameterize using type objects instead of native ints
> 
> Native int pointer equality in parameterization depends on int caches
> and as such is fragile.

**Comment by usev6** [comment]
Tests are active again: https://github.com/Raku/roast/commit/1e784bfed6
