### ISSUE TITLE
CLI cannot take enums with the name of built-ins

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5090]
## The Problem
Enums can generally shadow built-in names that aren't keywords - however, if the enum is used as the type of a MAIN argument, dispatch will fail for the enum values that collide with a built-in name.
## Expected Behavior
The provided CLI input is succesfully parsed into enum value.
## Actual Behavior
The usage message is generated, indicating that the dispatch failed.
## Steps to Reproduce
`raku -e 'enum BatchCategory<Label Issue>; sub MAIN(BatchCategory $c) { say Label.WHAT; }; @*ARGS = "Label"; '`
**Note**: if "Issue" is passed, we can witness that `Label` refers to the enum value inside the program. If we change the word "Label" to "Label1", it will also work.

## Environment
* Operating system: `5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): v2022.07 with MoarVM 2022.07.

**Comment by ab5tract** [comment]
Fully addressed as of f521883.
