### ISSUE TITLE
Clarity in type errors for List and Map variables

### ISSUE THREAD

**Issue by michaelruigrok** [rakudo/rakudo#5110]
I would like type error messages to have more information when a type error occurs inside a List or Map.

For the type error `my Map %map = foo => "bar";`, instead of "Type check failed in assignment to %map; expected Map but got Str ("bar")", I propose the following possible changes:

- expected Map of Map but got Map of Str ("bar")
- Type check failed in assignment within %map
- expected element Map but got Str ("bar")

Even better, in the case of a type error concerning a Map-typed Map, or a List-typed List, "Map/List types refer to their contents, not the Map/List itself". And then a link to the docs, https://docs.raku.org/language/list#Typing.

## Reasoning

I found myself in a situation where I didn't understand how map typing works (I had searched for type parameterisation but didn't find results). Due to this, I had misled myself into something like the following:

```raku
class X {
    ....
    has Map %map; # supposed to contain many types
    
    submethod BUILD(:%map, *%and-other-stuff) {
        %!map = Map.new(%map);
        ...
    }
}
X.new(map => %(foo => 'bar'));
# Type check failed in assignment to %map; expected Map but got Str ("bar")
```

Given the Raku container type syntax was unknown and alien to me, I came up with all sorts of wild theories to explain this error. Maybe it was interpreting my inner hash as a named argument? Or maybe it was being interpreted as a pair? Was I misusing BUILD? Maybe assigning to an immutable Map class field is not allowed? Can I even assign a new object in this context? On and on.

My point being, if I had just a little extra information hinting at how the type was being interpreted, I may have figured it out.

I think most of my confusion came from 'failed in assignment to %map' part. This seems to imply that my problem was with the map itself, not the contents. This was compounded that when the docs discuss map assignment, it's in the context of assigning a whole map to a variable: https://docs.raku.org/language/hashmap#Hash_assignment.

(Issue description edited for clarity)

**Comment by vrurg** [comment]
If you try a very simple `my Map %h; say %h.raku` it would explain the mistake to you: `(my Map %)`. In other words, you defined the type of values of your hash.

To change the base type of a non-scalar container `is` trait must be used: `my %h is Map; say %h.raku`. Though in this case you would still not get what you want because `Map` itself is not a container and you cannot assign into it, only bind.

**Comment by MasterDuke17** [comment]
I'm not sure why this was closed, those seem like reasonable suggestions. I'll admit about half the time I don't remember the exact syntax to specify the type of both keys and values of a `Hash`/`Map`.

**Comment by michaelruigrok** [comment]
I think I might have too flowery when writing my proposal. I'll be more direct about my issue's intent next time :)

**Comment by MasterDuke17** [comment]
@michaelruigrok does https://github.com/rakudo/rakudo/pull/5112 improve the situation enough to close this?

**Comment by 2colours** [comment]
As "moral of the story":

> To change the base type of a non-scalar container is trait must be used: my %h is Map; say %h.raku. Though in this case you would still not get what you want because Map itself is not a container and you cannot assign into it, only bind.

I don't know from the top of my head how much this is documented - check; seems it's [somewhat documented](https://docs.raku.org/language/traps#Typed_array_parameters) but maybe we could do better, mentioning it more generally and pointing towards the traits.

Where I'm getting is that this sort of feedback is definitely valuable - especially for a beginner - however, hastily dropping arguments and prematurely closing issues can get disheartening pretty fast. Trust me, I know, and this is something I admittedly preach a lot about. Fortunately, this issue had kind of a happy ending.

I'd like to particularly point out the contradiction between the error messages in Raku in general, [as described by Carl Mäsak](http://strangelyconsistent.org/blog/error-messages-epoq-diary-011), and the borderline user-blaming attitude that shows up every now and then on Github. Trust me, I can imagine that for some of you guys, it's connected to a lot of hard work and emotional involvement but I don't think it's an attack on anyone to recognize and admit that neither Raku, nor Rakudo is perfect (like all other technologies), and that with reasonable motives, many things can be improved, or would at least be desirable to change, even if not feasible.
