### ISSUE TITLE
dd misreports array items

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5130]
## The Problem
The dd function can prepend the name of the logged variable which can come really handy; however, it confusingly misreports any item of an Array. I understand that there is no foolproof way when bindings come into play but it shouldn't collapse this easily. The confusion might be the worst when the item of the Array is an Array itself.
## Expected Behavior
Several acceptable options:
- report the index as well
- say "inside of ..." or something along those lines
- don't report the name at all
## Actual Behavior
Reports the item as `Array @a = ...`
## Steps to Reproduce
```raku
my @a;
@a[0].push: (3, 4);
@a[1] = 12;
dd @a[0], @a[1]
```

## Environment
* Operating system: `5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): `v2022.12 with MoarVM`

**Comment by 2colours** [comment]
The name comes from here in v6.d with Rakudo [v2022.12](https://github.com/rakudo/rakudo/blob/704a05b934ba10f3240e8764827bbfd7fe089cdf/src/core.c/Any.pm6#L597). I would think that it should either be possible to reach back to the array from the item (in which case it could be compared against the item some way) - or, if it's not, the item shouldn't downright get the name of the array that contains it.

**Comment by ab5tract** [comment]
Fixed via  e1bd3ff
