### ISSUE TITLE
classify shouldn't reject classification on self

### ISSUE THREAD

**Issue by markjreed** [rakudo/rakudo#5134]
## The Problem
`.classify(*)` doesn't work.

## Expected Behavior
Should be identical to `.classify( { $_ } )`, which does work and constitutes a viable workaround.

## Actual Behavior
Generates error "Doesn't make sense to classify with itself". 

In fact it can make sense, depending on the problem; while all the elements in each category of such a classification are necessarily identical, the number of elements per category still depends on the input. It's not the most efficient way to generate a histogram, but I don't see a reason to reject it out of hand.

## Steps to Reproduce
`'abracadabra'.comb.classify(*)`

## Environment
* Operating system: macOS Monterey 12.6.
* Compiler version (`perl6 -v` or `raku -v`): Rakudo™ v2022.12.

**Comment by 2colours** [comment]
@markjreed 

I don't know if you know this already but actually, `.classify(*)` is far from equivalent to `.classify( { $_ } )` - the former is a plain `Whatever` (not `WhateverCode`, mind you) while the latter is a `Block`. So long story short, `*` is not the identity function there, and it's a hand-written (misleading) error message that you get for it, added here: https://github.com/rakudo/rakudo/commit/bfbf8335b6769cf71aa8a1bceb295722bdec53af

So yes, I think what you are pushing towards makes at least as much sense as the current error message, and it's definitely feasible. However, I'm not sure if the change should be something that fosters this misunderstanding that the `*` is an identity function there - and it seems pretty hard to consistently fake `*` to be the identity function, at this point.

What do you think about keeping the main behavior but changing the error message to something like "`Whatever` got where a `Callable` was expected - for classifying by self, use { $_ }, *<> or *.self"?

**Comment by lizmat** [comment]
There are other cases where a bare `Whatever` has a special meaning.  I don't see a reason why `*` couldn't be handled as meaning the identity function for `classify`

**Comment by 2colours** [comment]
Special meaning yes but a special meaning that fosters a potential misunderstanding? I have mixed feelings about this. Think `^*` versus `1..^*`.

**Comment by markjreed** [comment]
Yup, I totally thought `*` worked an identity function when supplied where a Block is expected. Why is that hard to "fake", and why does it need to be faked instead of just working that way? 

Certainly `classify` is not alone in rejecting it, but its error message could be improved. As for `map: *`, that returns 'Cannot map a (collection type goes here) using '*'` and further asks `Did a * (Whatever) get absorbed by a list?`.  Is that (absorbed by a list) actually what's happening?

**Comment by 2colours** [comment]
We might be 15-20 years late to examine that. @raiph often recites historical materials about certain design decisions - to be frank, I wouldn't be willing to spend time on looking up Apocalypses and Synopses of Raku (Perl 6 at the time) to figure out how `Whatever` and `WhateverCode` came to be.

https://docs.raku.org/type/Whatever

The way I understand it - when you write `*`, you get a `Whatever` value and it's completely up to the context in which it appears to decide how to handle it.

Most of the time (but not quite always... I suppose there are fairly arbitrary rules for this), when this "whatever star" appears as a part of an expression (more accurately: as an operand), the whole expression gets wrapped into a kind of Code object (`WhateverCode`) that has different parameters for all occurances of the star. This means, `* + *` is one way to create an `x + y` kind of adder which takes two parameters.

In the case of `.map(*)` or `.classify(*)`, it's clear that `*` is not an operand so it's passed into the methods "as it is", as a `Whatever` object.

Some examples where `*` has very different semantics from an identity function:
```raku
(1, 2) ~~ (1, *) # True - placeholder value in lists, can be used for smartmatching
my @demo = lazy 1, 1, * + * ... * > 100; @demo[*].raku # (1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144) - fetches all the indices
for 1..* {} # infinite loop starting from 1 - in ranges, * acts like the maximum/minimum possible value
```

The point is: `Whatever` is an extensible feature in the language and even though it can be extended into "identity function" in certain scenarios, it definitely couldn't be _always_ that, without breaking a lot of existing idiomatic Raku code.

And then I wonder: is there a point in going through all higher-order functions and try to fake the `Whatever` type as an identity function? One could really just write `+ *` for a "numeric identity function", `*<>` for a "decontainerizing identity function" and so on. It wouldn't be that much longer - in return, one wouldn't stick to the misunderstanding that `*` is magically a function.

**Comment by 0racle** [comment]
FWIW, I suggested this feature over 5 years ago and didn't get much support, so it's interesting to see this idea pop up again and get rapidly implemented. See comments to issue #1281 for more context.

**Comment by lizmat** [comment]
FWIW, it's not implemented, it's a PR  :-)

**Comment by 2colours** [comment]
@0racle interesting indeed - by the way, thank you for sharing because there have been great points made that I can 100% agree with.

I could quote  [the whole comment](https://github.com/rakudo/rakudo/issues/1281#issuecomment-379463573) of @smls, let me just highlight the summary:

> Just please don't start adding special-cased overloads to individual callback-accepting methods, without thinking this through.

By the way, as you can see, @lizmat already supported "WhateverStar for identity function" around that time so not many things have changed, mainly just the proactivity. :P This is something that involves more thought than technical difficulties.

@zoffixznet also raised a number of good points - what I would personally add is that I'm more okay with the identity function as the default than the identity function as the WhateverStar - it's much more transparent that a special case is being handled and therefore it doesn't spread further misconceptions. Anyway, I _do_ think adding a default value does no harm, if it's only remotely useful.

**Comment by lizmat** [comment]
Closing since PR was merged
