### ISSUE TITLE
Request to deprecate untwigiled attributes

### ISSUE THREAD

**Issue by p6steve** [rakudo/rakudo#5139]
Coming in from this [reddit post](https://www.reddit.com/r/rakulang/comments/znf103/day_16_santa_claws_part_2_steve_roe/) and raising a new Problem Solving issue here as suggested:

---
I am reflecting a comment on my post made by Tom Browder here, since I think it covers an important topic that is worthy of wider discussion:

December 16, 2022 at 1:45 am  
Great article pair, thanks. But, according to my reading of the docs in “Object orientation,” a class created using ‘has $attr’ is the same as ‘has $!attr’, i.e., private attributes; then the docs get a little muddy to me in the next paragraph, which I think needs a bit of work.

Now, I checked the docs and (not surprisingly) Tom is right. I also checked the repl and yes, it matches the docs.

BUT when I learned raku (from Think Raku) there were only two options:

```
has $.x;   # public attribute
has $!y;   # private attribute
```

So, it seems to me that the un-twigiled variant ```has $z; # private attribute``` has crept in without my noticing.

So, why am I agitated? The way I see it, raku has two gears (at least) for OO:

First gear is for "making the easy stuff easy". Just like in languages such as Python, you use the dot twigil (.), get all the accessors you want for free and can then use dot notation to access the attr. 

```
class C {
    has $.x = 42;
}

my $c = C.new;
say $c.x;  # 42
$c.x = 666;
say $c.x;  # 666
```

Second gear is for "making the hard stuff possible". Just like in languages such as Java and C++, use the bang twigil (!) and this attribute requires getter/setter methods to be employed and is a key tool to enforce encapsulation.

```
class D {
    has $!y = 42;

    multi method y           { $!y }          #getter
    multi method y( $value ) { $!y = $value } #setter
}

my $d = D.new;
say $d.y;           # 42
$d.y = 666;         # error - need a proxy for this
$d.y: 666;
say $d.y;           # 666
```

[Larry did many good things - but this use of the colon to create a cognitive triplet of ```=```, ```:=``` and ```:``` was IMO the best of the lot]

So, IN MY OPNION, the third way of the untwigil is a MISSTEP in language features since it is at the same time easier to write and harder to use (than the dot twigil). If this was consistent, then the easy thing to write ```has $z;``` should also be the easy thing to use by being bound to the dot twigil variant. But then IMO that makes it too easy to get stuck in gear one.

A further negative to the untwigil is that the symmetric options ```$.``` and ```$!``` are easy to remember and impossible to forget, adding a third option creates more complexity for the coder and the maintainer.

So I have two questions:
1. Is the untwigiled variant now part of the language?
2. If yes, then do we think it SHOULD be in the language?

**Comment by jnthn** [comment]
> Is the untwigiled variant now part of the language?

Now? :-) I believe has been for a decade or longer. It's [mentioned in S12](https://design.raku.org/S12.html#Attributes), and Rakudo implements it as described there (`has $foo` actually declares `has $!foo` and then makes `$foo` an alias to it).

> If yes, then do we think it SHOULD be in the language?

It's tempting to point out that it's a mild nuisance for the compiler to handle, but by that reasoning a lot of the language would be on the chopping block. :-)

I can't find mention of it now, but I think the syntax was once described as a sop to those who don't like twigils. However, I suspect the number of folks who are consider twigils on attributes their only dealbreaker for using Raku is pretty small - if nothing else because I can't remember the last time I saw this form in the wild!

**Comment by p6steve** [comment]
Well, I learned raku from [Think Raku](https://greenteapress.com/wp/think-perl-6/) and read the raku docs Classes and Objects [section](https://docs.raku.org/language/classtut). So it never dawned on me that there was the untwigil sop.

No doubt some will want to add to the docs (so that the docs match the spectest) - but far better to improve the language I reckon.

**Comment by 2colours** [comment]
I think from repo purism point of view, this issue might have a better place at [Raku/Problem-solving](https://github.com/Raku/problem-solving). 

Anyway, my two cents: if something already works with really low "maintenance cost", think twice before removing it. Raku is not a minimalistic language either way and we cannot have a discourse with potential users in the future who could miss it.

**Comment by lizmat** [comment]
This would go through a deprecation cycle, so it won't be gone until at least 6.f or 6.g, or whatever we will call it then.

**Comment by lizmat** [comment]
@2colours Sadly, it appears to be impossible to transfer the issue to raku/problem-solving

**Comment by p6steve** [comment]
@2colours - quiote right, I have created this issue in the right place https://github.com/Raku/problem-solving/issues/358

and cc'ed the material comments over there...

closing this.
