### ISSUE TITLE
`gather`-`take` leaks memory

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#5144]
```
raku -e 'use Telemetry; my @s = lazy gather loop { take rand x 1024 }; for @s { say T{"max-rss"} }'
```

It looks like taken values are not disposed properly - the bigger the values the bigger memory leak.

```
# raku -v
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
```

**Comment by bbkr** [comment]
Same for 2022.12, but the leak seems to be slower here.

**Comment by ab5tract** [comment]
Memory usage is stable when using `$s :=` instead of `@s =`:

```
> r 'use Telemetry; my $s := lazy gather loop { take rand x 1024 }; for $s { say T{"max-rss"} }'
146
...
146
```

Not sure whether that classifies this into DIHWIDT territory or not...
