### ISSUE TITLE
Parameterised hashes implementation detail sometimes leaks out

### ISSUE THREAD

**Issue by cfa** [rakudo/rakudo#5165]
## The Problem
Parameterised hashes are not stored as expected (under certain circumstances).

## Expected Behaviour
Behaviour consistent with normal hashes.

```raku
my %h1      = :foo, :bar; say %(%h1,);  # OUTPUT: «{bar => True, foo => True}␤»
my %h2{Any} = :foo, :bar; say %(%h2,);  # OUTPUT: «{Str|bar => bar => True, Str|foo => foo => True}␤»
```

In the case of `%h2`, keys are apparently produced via `.WHICH`, with hash values consisting of the source hash pairs.

## Steps to Reproduce
The above examples hopefully provide a minimally reproducible case. The issue originally arose when working with hashes created from sets, e.g.

```raku
say %(<foo bar>.Set.Hash, :baz);        # OUTPUT: «{Str|bar => bar => True, Str|foo => foo => True, baz => True}␤»
```

where `<foo bar>.Set.Hash.WHAT` is `(Hash[Any,Any])`.

[This](https://gist.github.com/Whateverable/83607b0e8760cf60f18b694cf9ef2529) bisection suggests that problem may have been introduced in commit ecfb956bcf92488106a85f9462731095db11dfed.

## Environment
* Operating system: macOS 13.1.
* Compiler version (`perl6 -v` or `raku -v`): Rakudo™ v2022.12 .
* Bisection suggests that the issue has been present since Rakudo 2016.07.01.

**Comment by 2colours** [comment]
We have investigated it quite a lot yesterday, however I think the direction wasn't completely right yet.

Most of behavior comes from [here](https://github.com/rakudo/rakudo/blob/main/src/core.c/Hash/Object.pm6) or [here](https://github.com/rakudo/rakudo/blob/main/src/core.c/Hash/Typed.pm6) and these files provide good examples how typed hashes can work. Their underlying `$!storage` is a bit tricky, therefore 
```raku
self.STORE_AT_KEY(iterkey_s($iter),nqp::iterval($iter))
```
is not sufficient for copying an element of the Hash.

**Comment by 2colours** [comment]
This seems to be the only location where the internal STORE_AT_KEY method is used with low-level representations of a key-value pair so I think it's a good idea to change this call to something else that takes the $iter itself and different Hash implementation can figure out what they need to do with it.

**Comment by cfa** [comment]
> _But_ , in order to get the result you want, I'd expect to have to "flatten" the original Hash like:
> 
> ```
> raku -e 'my %h2{Any} = :foo, :bar; say %(|%h2, :zub).raku;'
> {:bar(Bool::True), :foo(Bool::True), :zub(Bool::True)}
> ```

Sorry, I forgot to mention that I did essentially this in the upstream code—but not before I ran into the issue outlined above.

Nevertheless, we observe auto-flattening when performing list assignment to hashes:

```raku
my %h1 = :foo, :bar;
my %h2 = :baz;
my %h3 = %h1, %h2, :qux;

say %h3;                  # OUTPUT: «{bar => True, baz => True, foo => True, qux => True}␤»
```

so it's unclear what the expectation should be. (And again, the issue here seems to be the inconsistent behaviour of parameterised hashes.)

**Comment by 2colours** [comment]
So it seems I do have a fix, will need a test and review. :)

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/932df924f8

**Comment by 2colours** [comment]
Shouldn't have hard-wired it to the main branch, at least...
