### ISSUE TITLE
Feature: warn on assigning a Block to a Hash

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5170]
It's a typical newbie mistake to use the superfluous brackets when assigning to a `Hash`, and it can easily turn into a `Block` (use of semicolon, `$_` etc.). It is almost certainly a mistake. It would be good to warn the user about it.

It can either be handled in the core as a dispatch for STORE or caught on the RakuAST level.

**Comment by lizmat** [comment]
Could you give an example of code that should warn?

**Comment by 2colours** [comment]
Inspired by [this discussion](https://irclogs.raku.org/raku-beginner/2023-01-25.html#14:15) - this is the output on Rakudo v2022.12:

```
Useless use of "=>" in expression "' ' => '<space>'" in sink context (line 4)
Odd number of elements found where hash initializer expected:
Only saw: -> ;; $_? is raw = OUTER::<$_> { #`(Block|2227340887624) ... }
  in sub dispatch at /tmp/demo.raku line 3
  in block <unit> at /tmp/demo.raku line 10
  ```

So one can kind of see something went wrong but you need to know what actually happened in order to understand it.

**Comment by lizmat** [comment]
Ok, so the "odd number of elements" needs to check further if there's only 1 argument and its a `Hash`?

**Comment by vrurg** [comment]
More like it's a block. Though it's clearly not a run-time warning as it may create even more confusion than solve the existing problem. Rather the compiler must check if LHS of an assignment is an `Associative` and RHS is a block and raise a flag.

Apparently, this is more complicated than just an assignment as we have routine parameters, for example. But the overall point remains the same: I wouldn't be happy seeing a warning coming from the depths of object construction and trying to figure out WTH is going on down there.

**Comment by 2colours** [comment]
Either way, it should be better to not dig too deep and handle it on the surface: if it's an assignment to a `%var` and the right handside is a `Block` (or frankly, any `{}` style literal), "you probably don't want that".

I'd have thought that it's possible to catch an assignment like this as a `STORE` with a `Block` argument, on `Hash` at least. That doesn't sound like "a warning coming from the depths of object construction", any more than `Mu.new` having a candidate only to warn you that you shouldn't be passing positionals to it.

**Comment by lizmat** [comment]
As I said, it could be done as a further refinement in the "Odd number" handling

**Comment by vrurg** [comment]
```raku
sub foo($v) { my %h = $v; }
foo({:a; :b}); # Warning
```

Do you want _this_ to produce a warning? Me wouldn't. If possible, I'd rather see the following complaining:

```raku
sub foo(%v) { }
foo({:a; :b});
```

**Comment by 2colours** [comment]
I for one wouldn't mind the former warning - of course the latter warning would also be welcome.

**Comment by vrurg** [comment]
You wouldn't mind it while it is an apparent and easy to spot cause. There are much less apparent cases where a warning would do a bad job of misleading a developer.

Either way, I tend to use `%(...)` more and more often lately due to its unambiguity.
