### ISSUE TITLE
[+] does not behave like the other [binop]s on single Iterables

### ISSUE THREAD

**Issue by markjreed** [rakudo/rakudo#5205]
## The Problem
Given a single scalarized Iterable, `[+]` reduces its elements.

## Expected Behavior
`[+]` should behave like the other reduced arithmetic operators.

## Actual Behavior
`[+]` appears to decontainerize a single Iterable, reducing across its elements. This seems to be because it uses Array.sum when available, instead of just doing an actual reduce with `+`. 

## Steps to Reproduce
    say [+] $(1,2,3)
    # result: 6
    # expected result: 3
   # Note that replacing `+` with any of the other three arithmetic ops here does produce 3.

## Environment
* Operating system: macOS 13.0
* Compiler version (`perl6 -v` or `raku -v`): 
    Welcome to Rakudo™ v2022.12.
    Implementing the Raku® Programming Language v6.d.
    Built on MoarVM version 2022.12.

**Comment by lizmat** [comment]
Thanks for the report!

**Comment by thundergnat** [comment]
Actually, due to single argument, I would expect this to produce 6. A stronger case could be made that `say [+] $(1,2,3),` (note trailing comma) should return 3.

**Comment by lizmat** [comment]
Yeah, but they have been exposing this behaviour for a *long* time already.  So fixing would probably need to be done at a language level.

**Comment by markjreed** [comment]
@thundergnat I agree that it would at least be more useful for the other operators to behave like [+] in this regard. It should be consistent either way, though.

@lizmat So for those of us keeping score at home, you tried to fix this, it broke other stuff, so the fix was reverted. Right?

**Comment by lizmat** [comment]
Yes, the fix was reverted, in the sense that `[+]` no longer uses `sum` internally, so it now works just like the other meta infix ops, and so should have the same semantics.  So if you're using `[+]`, the fix is still there.

**Comment by thundergnat** [comment]
Well, I am _mildly_ of the opinion that the meta reduce binops should follow the single argument rule, for consistency if nothing else, but also think that it is a relatively minor issue in general and that core devs time may be better spent on more critical things. 

And, like lizmat said, they have been that way for some time; changing them should at least be discussed in problem-solving, with maybe some input from jnthn or even (wistfully) Timtoady.
