### ISSUE TITLE
Recent commit broke summing lists in scalar containers

### ISSUE THREAD

**Issue by thundergnat** [rakudo/rakudo#5209]
## The Problem

Lists in scalar containers now require to be specifically decontainerized before summing.

`my @S = (1,), { (0, |@^l) »+« (|(@^l »*« @^l.keys), 0) } … *;  say @S.head(10); say @S.head(10).map: *.sum;`

## Expected Behavior

`((1) (0 1) (0 1 1) (0 1 3 1) (0 1 7 6 1) (0 1 15 25 10 1) (0 1 31 90 65 15 1) (0 1 63 301 350 140 21 1) (0 1 127 966 1701 1050 266 28 1) (0 1 255 3025 7770 6951 2646 462 36 1))␤(1 1 2 5 15 52 203 877 4140 21147)`

## Actual Behavior

`((1) (0 1) (0 1 1) (0 1 3 1) (0 1 7 6 1) (0 1 15 25 10 1) (0 1 31 90 65 15 1) (0 1 63 301 350 140 21 1) (0 1 127 966 1701 1050 266 28 1) (0 1 255 3025 7770 6951 2646 462 36 1))␤(1 2 3 4 5 6 7 8 9 10)`

Effectively `.map: *.sum` is returning the count instead of the sum.

`my @S = (1,), { (0, |@^l) »+« (|(@^l »*« @^l.keys), 0) } … *; say @S.head(10); say @S.head(10).map: {sum |$_};`
works but requires explicit decontainerization.

Affecting several long standing entries on Rosetta Code.

https://rosettacode.org/wiki/Abundant_odd_numbers#Raku
https://rosettacode.org/wiki/Bell_numbers#via_Stirling_sums_2
https://rosettacode.org/wiki/Collect_and_sort_square_numbers_in_ascending_order_from_three_lists#Raku
https://rosettacode.org/wiki/Zumkeller_numbers#Raku

among others.

See [chat logs](https://colabti.org/irclogger/irclogger_log/raku?date=2023-02-16#l151), [bisectable log](https://gist.github.com/Whateverable/1245502310c2d38f19e874e5c5121d4d), and [commit](https://github.com/rakudo/rakudo/commit/5c66515d46c7ab4299d0913d81745e9fcee57ad4)

Oddly enough, it seems to work ok in some cases.

`my @l = {(^++$)} ... *; say @l.map(*.sum)[^10];`

works as expected, and it is theoretically using the same mechanism.

## Environment
* Operating system: All
* Compiler version (`perl6 -v` or `raku -v`): HEAD (main)

**Comment by lizmat** [comment]
See also https://github.com/rakudo/rakudo/issues/5205

**Comment by lizmat** [comment]
@thundergnat could you confirm this fixes the issue?

**Comment by SqrtNegInf** [comment]
I updated to v2022.12-1210-g6b6c0ec8a6 and can confirm that the examples that @thundergnat listed are fixed.

However there may still be issues, for example not getting the correct answer here:
[https://rosettacode.org/wiki/Rare_numbers#Raku](url)

Running all my RC and PWC tests, but takes a while...

**Comment by SqrtNegInf** [comment]
Similar problem, but involving the '[+]' form:

```
my @fib = 1, 2, * + *  ... ^ * >= 89;
for @fib.combinations -> $s { put $s if 89 == [+] $s } # works if 'sum' used, or '|$s'
```
Should produce:
```
89
34 55
13 21 55
5 8 21 55
2 3 8 21 55
```

**Comment by lizmat** [comment]
No, that is correct.  `$s` is an itemized scalar, so it doesn't iterate, so it takes the number of elements in `$s`.  You should use a `@s`:

```
$ raku -e 'my @fib = 1, 2, * + *  ... ^ * >= 89; for @fib.combinations -> @s { put @s if 89 == [+] @s }'
89
34 55
13 21 55
5 8 21 55
2 3 8 21 55
```

**Comment by thundergnat** [comment]
@lizmat, sorry for the delayed reply, SqrtNegInf++ for being more on top of things; Yes. It appears that that fixed the issue I reported. I still have minor twitchy feelings about the meta reduce binops but that's a separate thing.

**Comment by SqrtNegInf** [comment]
OK, some code has been getting away with sketchy stuff, and should be revised. _Gradus ad Parnassum_, and all that...

But what about this pair of PWC solutions by @gfldex, meant to be identical except for the addition of concurrency:

[gfldex.wordpress.com/2022/05/21/writing-it-down/](https://gfldex.wordpress.com/2022/05/21/writing-it-down/)

Excerpting the relevant lines:
```
# 1st version
my \xy = @points[*;0] »*« @points[*;1];
my \Σxy = [+] xy;

# 2nd version, amended
my \xy = delayed { @points[*;0] »*« @points[*;1] };
my \Σxy = delayed { sum xy };
#my \Σxy = delayed { [+] xy };  # no, because  xy = $(List)
```
If it's the case that ``sum`` and ``[+]`` cannot always interchangeable, so be it. We may sometimes need to think (O the horror!) about the structure of the data we're using.  But 17 ``theweeklychallenge.org`` tasks had to be modified ([here](https://github.com/SqrtNegInf/PWC/search?q=GH5209)) so there's a bit of DWIM that people have been counting on...

**Comment by lizmat** [comment]
Well, if that's the case, then I guess we need to make the change in the behaviour of `[+]` depend on a language version (aka, in `v6.e`)
