### ISSUE TITLE
Display failures with rationals

### ISSUE THREAD

**Issue by SqrtNegInf** [rakudo/rakudo#5225]
## The Problem

Display of rationals is incorrect, or fails.

## Actual Behavior

```
say 1.0000000000000000000;  # 1                     OK
say 1.000000000000001;      # 1.000000000000001     OK
say 1.0000000000000001;     # 2                     should be 1.0000000000000001
say 2.0000000000000000001;  # 2.0000000000000000001 OK
say 2.00000000000000000001; # ERROR:                should be 2.00000000000000000001
                            # Type check failed in binding to parameter '$fract'; expected Rational but got Num (1e-20)
```

## Environment
Same behavior seen on macOS, Ubuntu with:

Welcome to Rakudo™ v2023.02-27-g66f7afed1.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.02-3-g6adfc376c.

**Comment by lizmat** [comment]
I can not reproduce this on MacOS M1.

**Comment by SqrtNegInf** [comment]
Hmmm...  A freshly installed `moar-blead` on another (newer) macOS failed the same way for me, don't have access to M1 hardware.  On IRC evalable6 showed the problem.

**Comment by lizmat** [comment]
It seems that this issue only occurred on Intel hardware.

Fixed with https://github.com/rakudo/rakudo/commit/3bd73896f9

**Comment by lizmat** [comment]
Thanks for the spot.  Please close if fix is confirmed.

**Comment by SqrtNegInf** [comment]
Unfortunately,  updating to v2023.02-28-g3bd73896f did not result in any change, e.g. `raku -e 'say 1.0000000000000001'` still gives an answer of 2

**Comment by lizmat** [comment]
Hopefully fixed with https://github.com/rakudo/rakudo/commit/7dac0a7c40

**Comment by SqrtNegInf** [comment]
Yes, all good now!
