### ISSUE TITLE
` (List,).flat` hangs

### ISSUE THREAD

**Issue by tony-o** [rakudo/rakudo#5229]
## The Problem

`Array` behaves strangely when `.Set` is called

## Expected Behavior

`Array.Set` either returns equiv `Set.new(Array)`

## Actual Behavior

`.Set` -> hangs indefinitely

## Steps to Reproduce
```
$ raku -e 'Array.Set' # hangs
```

## Environment
* Operating system:
Distro macos = Distro.new(release => "22A380", path-sep => ":", name => "macos", auth => "Apple Inc.", version => v13.0, signature => Blob, desc => "unknown")
* Compiler version (`perl6 -v` or `raku -v`):
Welcome to Rakudo™ v2022.12-1-gd52342eb0.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.12.

**Comment by lizmat** [comment]
Golfed to:
```raku
sub a(*@p) { }
a Array.list
```

**Comment by lizmat** [comment]
Further golfed to: `(List,).flat`

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/2e52d828cd
