### ISSUE TITLE
:from<Perl5> breaks with v6.e.PREVIEW

### ISSUE THREAD

**Issue by andinus** [rakudo/rakudo#5230]
## The Problem

Using Perl 5 modules with `Inline::Perl5` breaks with `use v6.e.PREVIEW`.

```
raku -e 'use v6.e.PREVIEW; use Template::Nest:from<Perl5>;'

===SORRY!=== Error while compiling -e                                                         
No such method 'with-export' for invocant of type                                             
'CompUnit::Handle+{<anon|1>}'
at -e:1
```

## Environment
* Operating system: CentOS Linux release 8.5.2111
* Compiler version (`perl6 -v` or `raku -v`): 2023-02

**Comment by vrurg** [comment]
The cause of the error is `Inline::Perl5` itself gets compiled using `6.e` version, even when I specifically try to use `use v6.d;` for it.

@ugexe, @niner do you have any idea why does it happen?

**Comment by lizmat** [comment]
FWIW, this is still an issue and only happens if the module is actually available in Perl.

**Comment by coke** [comment]
See also #4681
