### ISSUE TITLE
Several type objects throw when `.elems` is called on them

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5256]
Inspired by https://github.com/rakudo/rakudo/issues/5254

## The Problem

Some type objects throw (usually `X::Parameter::InvalidConcreteness`) when `.elems` is called on them (`Setty`, `Set`, `Map`, `Hash`, `Range`, `Uni`, `IterationBuffer`) while most of them don't (`List`, `Array`, `Iterable`, `Buf`, `Positional`, `Associative`, `Baggy` and basically everything that doesn't have a reason to care about elements).

## Expected Behavior

Consistency. If the intention is to count them as one element, as indicated by [the implementation for Any:U](https://github.com/rakudo/rakudo/blob/6235256a5684534ced38c0cf094b3684a49ffac6/src/core.c/Any.pm6#L87), then one shouldn't have to worry that it can explode for certain, seemingly arbitrary types.

## Actual Behavior

This is more the analysis than the behavior: the common thing seems to be in the problematic methods that they don't dispatch as intended. There are two cases:
- in most cases, the type added an `only method` (as opposed to a `multi method`) with a `DEFINITE` type smiley and therefore instead of redispatching towards ancestor classes, the method call will just fail
- in some other cases (`IterationBuffer`, `Range`), the overloading candidate had no type smiley at all, therefore the dispatch succeeded (and probably would have succeeded the same way with `multi` as well?), however the implementation silently assumed a concrete instance when calling into NQP and therefore `X::AdHoc` was thrown

## Steps to Reproduce
```raku
for (IterationBuffer, Setty, Set, Map, Hash, Range, Uni, IterationBuffer, List, Array, Iterable, Buf, Positional, Associative, Baggy, Int, Cool, IO) {
  print "Type under test: {.^name}\n.elems call produced: ";
  try {
    my $elems = .elems;
    say $elems;
  }
  $! andthen .^name.say;
}
```

## Environment
* Operating system: Ubuntu 20.04.5 running in WSL2 
* Compiler version (`perl6 -v` or `raku -v`): Rakudo v2022.12 on MoarVM.

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/4bbeaf6387
