### ISSUE TITLE
building on Android 11 fails: src/6model/containers.c:117:5: error: incompatible function pointer types

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#5263]
I have also appended a comment to this [other](https://github.com/rakudo/rakudo/issues/3505) issue mentioning the problem, but it seems different enough to warrant a separate issue.

## The Problem

I am trying to build tag `2023.04-94-gc14084ecd` on `Android 11`, following the recipe we settled on in [this](https://github.com/rakudo/rakudo/issues/3505) other issue:

```
git fetch origin && git pull
export MAKEFLAGS="-j8"
export MVM_SPESH_DISABLE=1 && perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --moar-option='--os=linux' --gen-nqp --backends=moar
```
You can see the [full output](https://termbin.com/83yx), including the errors that finally choke it: something about incompatible pointer types, which `src/6model/containers.c` screams about, as in 

```
src/6model/containers.c:117:5: error: incompatible function pointer types initializing 'void (*)(MVMThreadContext *, MVMObject *, MVMuint64)' (aka 'void (*)(struct MVMThreadContext *, struct MVMObject *, unsigned long)') with an expression of type 'void (MVMThreadContext *, MVMObject *, MVMint64)' (aka 'void (struct MVMThreadContext *, struct MVMObject *, long)') [-Wincompatible-function-pointer-types]
    code_pair_store_i, /* FIXME need a code_pair_store_u but lacking tests showing this need */
    ^~~~~~~~~~~~~~~~~
```

## Expected Behavior

Successful compilation.

## Actual Behavior

Error (see above).

## Steps to Reproduce

In a cloned copy of this repo:

```
git fetch origin && git pull
export MAKEFLAGS="-j8"
export MVM_SPESH_DISABLE=1 && perl Configure.pl --gen-moar --moar-option='--compiler=clang' --moar-option='--pkgconfig=/data/data/com.termux/files/usr/bin/pkg-config' --moar-option='--has-libuv' --moar-option='--os=linux' --gen-nqp --backends=moar
```

## Environment
* Operating system: 
```
$ uname -a
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Nov 26 00:10:21 CST 2021 aarch64 Android
```
* Compiler version (`perl6 -v` or `raku -v`): N/A: I am trying to build `rakudo`, so do not have it yet (I made a new, clean copy of the repo).

**Comment by colomon** [comment]
Back in April I got this same error trying to build MoarVM on Android 10: https://wandering.shop/@colomon/110289229955476609

    $ uname -a
    Linux localhost 4.9.186-22990479 #1 SMP PREEMPT Thu Mar 31 15:49:59 KST 2022 aarch64 Android

    $ clang --version
    clang version 16.0.2
    Target: aarch64-unknown-linux-android24
    Thread model: posix
    InstalledDir: /data/data/com.termux/files/usr/bin

**Comment by stuart-little** [comment]
I think we're good! As the first reply suggests in that discussion you linked @colomon, this is apparently due to `clang 16`'s having [promoted](https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html) `-Wincompatible-function-pointer-types` to an error (search for `Wincompatible-function-pointer-types` on that page).

Following [this](https://stackoverflow.com/a/71432342) suggestion, for instance, I made my `clang` executable

```
/data/data/com.termux/files/usr/bin/clang
```
a symlink to the shell script
```
#!/data/data/com.termux/files/usr/bin/sh

/data/data/com.termux/files/usr/bin/clang-16 -Wno-incompatible-function-pointer-types "$@"
```
I'm in the middle of the compilation right now, because it's taking its sweet rime, but it certainly went well past the error point. So this specific issue, at least, was indeed due to the `clang` upgrade.

**Comment by niner** [comment]
Should be solvabe with a simple cast to the correct pointer type. We know that it works like it is.

**Comment by lizmat** [comment]
Assuming this has been fixed.  Please re-open if this assumption was incorrect
