### ISSUE TITLE
IO::Path incorrectly handles Unicode combining characters

### ISSUE THREAD

**Issue by van-de-bugger** [rakudo/rakudo#5297]
## The Problem

`IO::Path` incorrectly handles Unicode combining characters. If a file name contains Unicode combining characters, the file name is stringified to a string containing garbage/mojibake.

## Steps to Reproduce

`$` in the beginning of a line denotes shell prompt, `#` denotes comments.

```
# Create test directory:
$ mkdir test

# Create helper C program:
$ cat <<'EOF' > test.c
#include <stdio.h>
#include <fcntl.h>
#include <dirent.h>
int main() {
    open( "test/\xC3\xA9",  O_CREAT, 0664 ); // U+00E9 LATIN SMALL LETTER E WITH ACUTE
    open( "test/e\xCC\x81", O_CREAT, 0664 ); // e and U+0301 COMBINING ACUTE ACCENT
    DIR * dir = opendir( "test" );
    struct dirent * entry = NULL;
    while ( ( entry = readdir( dir ) ) ) {
        printf( "%s \"", entry->d_name );
        char const * p = entry->d_name;
        while ( * p ) {
            printf( "\\x%02X", * (unsigned char const *) p );
            ++ p;
        };
        printf( "\"\n" );
    };
    return 0;
};
EOF

# Compile and run program:
$ gcc -Wall test.c
$ ./a.out
. "\x2E"
.. "\x2E\x2E"
é "\xC3\xA9"
é "\x65\xCC\x81"
# The program created two files, their names look the same, but actually they differ:
# One file name is U+00E9 LATIN SMALL LETTER E WITH ACUTE (aka "precomposed letter"),
# another is U+0065 LATIN SMALL LETTER E and U+0301 COMBINING ACUTE ACCENT.

# One more test:
$ ls test
é  é
# Output looks good.

# Now create Raku program:
$ cat <<'EOF' > test.raku
#!/usr/bin/raku
use v6;
sub MAIN() {
    for "test".IO.dir() {
        say $_.Str;
    };
};
EOF

# And run it to see how file names are interpreted by Raku:
$ raku ./test.raku
test/é
test/e􏿽xCC􏿽x81
# Precomposed file name looks good,
# but file name with combining character contains mojibake. 
```

## Expected Behavior

The last two lines of `test.raku` output are expected to look as:

```
test/é
test/é
```

## Environment

Fedora 38 @ x86_64

Welcome to Rakudo™ v2023.05.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.05.

**Comment by jubilatious1** [comment]
According to the docs, "Filenames are the only text not normalized by default."


_

> [All text is normalized by default](https://docs.raku.org/language/traps#Traps_to_avoid)
> 
> Raku normalizes all text into Unicode NFC form (Normalization Form Canonical). Filenames are the only text not normalized by default. If you are expecting your strings to maintain a byte for byte representation as the original, you need to use [UTF8-C8](https://docs.raku.org/language/unicode#UTF8-C8) when reading or writing to any filehandles.

_
