### ISSUE TITLE
The REPL msg should suggest 'Linenoise' only until 'Readline' is working

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#5311]
## The Problem

Readline is broken and its author has passed from this Earth. Until it is working again, it should not be mentioned unless there is also a message about needing a volunteer to fix it.

## Environment
* Operating system:
* Compiler version (`perl6 -v` or `raku -v`):

**Comment by coke** [comment]
https://github.com/lathropd/perl6-readline is the current owner, and I don't see any issues there that readline is broken.

**Comment by coke** [comment]
The original repo DOES have issues, but no indication the new owner has them.

**Comment by tbrowder** [comment]
Done.
