### ISSUE TITLE
Duodecimal unicode chars are not recognised.

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#5315]
The numerical unicode characters ↊ and ↋ are not recognised as numbers.

see:
https://en.wikipedia.org/wiki/Number_Forms#List_of_characters
https://en.wikipedia.org/wiki/Duodecimal#Notations_and_pronunciations

```
my $a = ↊; say $a == 10; my $b = ↋; say $b == 11;

# OUTPUT:
# ===SORRY!=== Error while compiling -e
# Malformed initializer
# at -e:1
# ------> my $a =⏏ ↊; say $a == 10; my $b = ↋; say $b == 1
#     expecting any of:
#        prefix
#         term

# EXPECTED:
# True
# True
```

## Environment
* Operating system: `Linux dexhome 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): `Welcome to Rakudo™ v2023.06-25-g0e0aae376. Implementing the Raku® Programming Language v6.d. Built on MoarVM version 2023.06.`

**Comment by 2colours** [comment]
https://www.compart.com/en/unicode/U+218A

This is a "Unicode bug", if anything, not a Rakudo bug - even though this character resides in the "number forms" block, it belongs to the "other symbols" category, therefore it doesn't count as a numeric character at all. As much as I understand, no regex engine that works based on unicode properties (usually denoted \p{...}) will accept these two characters as numeric; Rubular definitely does not.

**Comment by coke** [comment]
Rejecting, based on @2colours's analysis.
