### ISSUE TITLE
LTA error when programmer uses the wrong keyword to exit the Raku interpreter

### ISSUE THREAD

**Issue by jeffgazso** [rakudo/rakudo#5322]
## The Problem

Raku uses `exit` to leave the interpreter. Muscle memory is a powerful thing and depending upon the language the programmer is coming from he may be used to `q`, `quit`, or `bye` instead.

## Expected Behavior

If an undeclared `q`, `quit` or `bye` is called, remind the programmer that the correct keyword is `exit`. It's a small change, but it helps reinforce the correct keyword in the programmer's mind.

## Actual Behavior

```
===SORRY!=== Error while compiling:
Undeclared routine:
    quit used at line XX
```
## Environment
* Operating system: Linux
* Compiler version (`perl6 -v` or `raku -v`): MoarVM version 2023.06

**Comment by lizmat** [comment]
Added "quit" as an alternative to "exit" in error message with 391e3b507d71307e104.

The output is now:
```
% raku   
Welcome to Rakudo™ v2024.09.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.09.

To exit type 'exit' or '^D'
[0] > quit
===SORRY!=== Error while compiling:
Undeclared routine:
    quit used at line 1 (in Raku please use 'exit' instead)

[0] > 
```
which should help adjusting your muscle memory.
