### ISSUE TITLE
Piped stdout behaving weird (cannot write to piped stdout)

### ISSUE THREAD

**Issue by dontlaugh** [rakudo/rakudo#5332]
## The Problem

This program has its stdout redirected to a file. One line is written to the file.

```
raku -e 'while True {sleep-until(now+2); say "{now}"}' > out.txt
```

_Note: ^^ try this command for ~10 seconds to see if you can reproduce_

Since this in an infinite loop, I'd expect a line to be written every two seconds, forever.

I used strace to get a lower-level look at what's going on. Here are two files.

### strace test 1

Command:

```
strace -o strace.txt ./bin/raku -e 'while True {sleep-until(now+2); say "{now}"}' > out.txt
```

I let this run for about 6 seconds. Then I sent SIGINT with Ctrl+C

[strace.txt](https://github.com/rakudo/rakudo/files/12262517/strace.txt)

### strace test 2

Command: 

```
strace -o strace2.txt ./bin/raku -e 'while True {sleep-until(now+2); say "{now}"}' > out.txt
```

I let this command run longer. Perhaps 30 seconds. Then I sent SIGINT with Ctrl+C

[strace2.txt](https://github.com/rakudo/rakudo/files/12262547/strace2.txt)

-----

In both tests, the out.txt is always something like

```
Instant:1691165147.342319315
```

And in each of the strace outputs, we do see exactly one `write` to stdout towards the end of the file.

### strace test 3 (stdout is a tty)

The output does NOT hang if stdout is a terminal. 

Command, output, Ctrl+C invoked:

```
% strace -o strace3.txt ./bin/raku -e 'while True {sleep-until(now+2); say "{now}"}'         
Instant:1691166011.603691959
Instant:1691166013.606848737
Instant:1691166015.607673921
Instant:1691166017.608562657
^C
```

[strace3.txt](https://github.com/rakudo/rakudo/files/12262617/strace3.txt)

## Environment
* Operating system: Ubunbu 22.04

```
% raku -v
Welcome to Rakudo™ v2023.05.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.05.
```

**Comment by jnthn** [comment]
It's very likely [output buffering](https://docs.raku.org/routine/out-buffer); you can disable it if you want the writes to happen immediately.

**Comment by jubilatious1** [comment]
Is pipe the correct term here? Piping is known to have issues with buffering, e.g.:

https://unix.stackexchange.com/questions/25372/turn-off-buffering-in-pipe

But I suspect you mean redirection?

https://www.gnu.org/software/bash/manual/html_node/Redirections.html
