### ISSUE TITLE
WhateverStar dodges range sanity check

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5340]
## The Problem
`-Inf .. 'Z'` isn't constructible as a `Range` - except if you write `* .. 'Z'`, in which case it will be created.

## Expected Behavior
An error; either the same one as with literally typing `-Inf .. 'Z'`, or one that states that the WhateverStar cannot be used as the starting point of a `Range` of strings
## Actual Behavior
`-Inf .. 'Z'` is created as a `Range`

## Environment
* Operating system: `Linux ... 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): `v2023.06. on MoarVM`

**Comment by 2colours** [comment]
I tried to implement it, the principle is pretty simple but the unexplained multi dispatch ordering got in the way.

In https://github.com/rakudo/rakudo/blob/main/src/core.c/Range.rakumod, there are multi candidates for the `new` method of `Range`. They take care of the behavior of the `&infix:<..>˙ operator.

The reason `-Inf .. 'Z` throws is quite banal: the dispatch succeeds for [this candidate](https://github.com/rakudo/rakudo/blob/81d2aa6fc2b6f69e184d8286e858c9cfda7602a6/src/core.c/Range.rakumod#L65) but `$max` holds a `Failure` that explodes [when trying to calculate infinite-ness](https://github.com/rakudo/rakudo/blob/81d2aa6fc2b6f69e184d8286e858c9cfda7602a6/src/core.c/Range.rakumod#L68).

I thought, simple enough, let's add constraints for the two candidates with `Whatever` as one of the endpoints, and then make them explode if the coercion fails. However, for some reason, this has messed up the order of candidates and now suddenly, if you have something like `10 .. ^20`, [this earlier mentioned candidate triggers](https://github.com/rakudo/rakudo/blob/81d2aa6fc2b6f69e184d8286e858c9cfda7602a6/src/core.c/Range.rakumod#L65), instead of the previous state where [this candidate triggered](https://github.com/rakudo/rakudo/blob/81d2aa6fc2b6f69e184d8286e858c9cfda7602a6/src/core.c/Range.rakumod#L41) (rightly).

How touching two candidates that play no role in the dispatch of `10 .. ^20` could reorder a completely different pair of multi candidates is completely beyond me; I'd say the fact that something like this can happen is a bug in itself.

Anyway, I will have another go where I just ignore the type constraints and produce the error straight in the function body.

**Comment by MasterDuke17** [comment]
It might be playing with fire, but have you tried adding an `is default` somewhere?

**Comment by 2colours** [comment]
I don't want to walk down on that path, honestly. I can only hope that there is somebody at least who knows how the multi candidate resolution works, and they will some day compile this knowledge somewhere where mere users can learn it. It's a fundamental part of the high-level language, after all.

For now, I just want to solve this issue by any means available to me. Correct behavior now trumps super-duper-optimal behavior one day.

**Comment by lizmat** [comment]
There appears to be a subtle difference in meaning between `*` and `-Inf` as a starting point and `Inf` as an endpoint, according to several spectests.

`*..foo` basically allows the range to be used as an "anything below foo" check.
`bar..*` allows the range to be used as an "anything above" check.

Note that "foo" and "bar" can be any type of object, even non-core ones, as long as they have `before` and `after` semantics.

The `Inf` cases assume numerical context, and as such fail if the other endpoint can *not* be coerced to a numerical value.

Therefore closing this issue as "not a problem, but a feature".

**Comment by 2colours** [comment]
> `*..foo` basically allows the range to be used as an "anything below foo" check.
> `bar..*` allows the range to be used as an "anything above" check.

They actually create `-Inf..'foo'` and `'bar'..Inf` ranges so I cannot expect this reasoning.

Opening a problem-solving issue.
