### ISSUE TITLE
Buglet with dd

### ISSUE THREAD

**Issue by librasteve** [rakudo/rakudo#5344]
## The Problem

```
my Int @a = [^10]; dd @a;
#Array[Int @a = Array[Int].new(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
         ^ - missing right square bracket ']'
```

## Expected Behavior

```
my Int @a = [^10]; dd @a;
#Array[Int] @a = Array[Int].new(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
          ^ - NOT missing right square bracket ']'
```

## Environment
* Operating system: macOS & on discord irc m: xxx
* Compiler version (`rakudo -v` or `raku -v`):

Welcome to Rakudo™ v2023.06.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.06.

**Comment by 2colours** [comment]
Related issue: https://github.com/rakudo/rakudo/issues/5130 They might boil down to the same code but this (for the typed array) seems more concrete and perhaps easier to get right.

**Comment by 2colours** [comment]
https://github.com/rakudo/rakudo/commit/4960802167dd63eda69b9c33899edd0503e2d3e2

This is the commit that explicitly creates this "choppy" behavior. @lizmat do you remember the motive for it?

**Comment by lizmat** [comment]
```
$ raku -e 'my IO::Path @a; dd @a;' 
Path @a = Array[IO::Path].new()
```
