### ISSUE TITLE
Inconsistent behaviour wrt native ints and uints and under/overflow

### ISSUE THREAD

**Issue by gdncc** [rakudo/rakudo#5349]
## The Problem

The following code attempts to store the maximum possible uint64 value in the third position of a buf64 object, and then to make this value wraps around 0 after an addition:

raku -e 'my $bufb = buf64.new(3, 1, 18446744073709551615); $bufb[2] = $bufb[2] + 1;'

However, the code returns an error.

## Expected Behavior

The code should not return an error. Furthermore, the third element value should be 0 after the update.

## Actual Behavior

The error:

Cannot unbox 65 bit wide bigint into native integer
  in block <unit> at -e line 1

## Steps to Reproduce
raku --ll-exception -e 'my $bufb = buf64.new(3, 1, 18446744073709551615); $bufb[2] = $bufb[2] + 1;'
Cannot unbox 65 bit wide bigint into native integer
   at SETTING::src/core.c/Buf.pm6:1053  (/usr/local/Cellar/rakudo/2023.05/share/perl6/runtime/CORE.c.setting.moarvm:ASSIGN-POS)
 from SETTING::src/core.c/array_slice.pm6:17  (/usr/local/Cellar/rakudo/2023.05/share/perl6/runtime/CORE.c.setting.moarvm:postcircumfix:<[ ]>)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from NQP::src/HLL/Compiler.nqp:196  (/usr/local/Cellar/nqp/2023.05/share/nqp/lib/NQPHLL.moarvm:eval)
 from NQP::src/HLL/Compiler.nqp:309  (/usr/local/Cellar/nqp/2023.05/share/nqp/lib/NQPHLL.moarvm:)
 from NQP::src/HLL/Compiler.nqp:364  (/usr/local/Cellar/nqp/2023.05/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:233  (/usr/local/Cellar/rakudo/2023.05/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from NQP::src/HLL/Compiler.nqp:289  (/usr/local/Cellar/nqp/2023.05/share/nqp/lib/NQPHLL.moarvm:command_line)
 from src/main.nqp:81  (/usr/local/Cellar/rakudo/2023.05/share/perl6/runtime/perl6.moarvm:MAIN)
 from src/main.nqp:63  (/usr/local/Cellar/rakudo/2023.05/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/usr/local/Cellar/rakudo/2023.05/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/usr/local/Cellar/rakudo/2023.05/share/perl6/runtime/perl6.moarvm:<entry>)

## Environment
* Operating system: macOS
* Compiler version (`rakudo -v` or `raku -v`):

raku -v
Welcome to Rakudo™ v2023.05.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.05.

**Comment by lizmat** [comment]
The actual cause of this error is:
```raku
my uint $a = 18446744073709551616;
Cannot unbox 65 bit wide bigint into native integer
```
and relatedly:
```
my uint $a = 18446744073709551615;
say ++$a;   # 0
--$a;
say $a;     #  18446744073709551615
```
but:
```raku
$a += 1;
Cannot unbox 65 bit wide bigint into native integer
```
The problem with `Buf` is just one of the symptoms.

**Comment by niner** [comment]
This looks quite correct? You all it to put a number into a 64 bit variable but the number is too large for that and it correctly refuses.

**Comment by MasterDuke17** [comment]
> This looks quite correct? You all it to put a number into a 64 bit variable but the number is too large for that and it correctly refuses.

Sure, but the fast that this is somehow different from `++` is a source of frequent confusion.

**Comment by lizmat** [comment]
Also: [`Native::Overflow`](https://raku.land/zef:lizmat/Native::Overflow)
