### ISSUE TITLE
cross and zip subs do not accept a WhateverCode as a named "with" parameter

### ISSUE THREAD

**Issue by grimnebulin** [rakudo/rakudo#5351]
## The Problem

The built-in cross and zip functions do not allow any kind of Callable object as their named "with" parameter.

## Expected Behavior

Any Callable should be allowed as the "with" parameter for those subroutines.  At any rate, the documentation doesn't suggest anything otherwise to me.

## Actual Behavior

The subroutines appear to only accept Blocks as a valid value for their named "with" parameter.  They reject WhateverCode objects with a "Type check failed" error.

## Steps to Reproduce

At the console:

    [0] > cross((1, 2, 3), (4, 5, 6), with => (* + *))
    Type check failed in binding to parameter '<anon>'; expected Block but got WhateverCode (WhateverCode.new)
      in block <unit> at <unknown file> line 1

    [0] > zip((1, 2, 3), (4, 5, 6), with => (* + *))
    Type check failed in binding to parameter '<anon>'; expected Block but got WhateverCode (WhateverCode.new)
      in block <unit> at <unknown file> line 1

Replacing `(* + *)` with `{ $^x + $^y }` in both cases produces the expected results.

## Environment
* Operating system:  MacOS
* Compiler version (`rakudo -v` or `raku -v`):  2023.06

**Comment by lizmat** [comment]
The problem was caused by incorrect signatures at https://github.com/rakudo/rakudo/blob/main/src/core.c/Code.pm6#L14-L17

**Comment by lizmat** [comment]
Thanks!
