### ISSUE TITLE
Document listen-path and connect-path in IO::Socket::Async.

### ISSUE THREAD

**Issue by amano-kenji** [rakudo/rakudo#5354]
## The Problem

listen-path and connect-path landed in IO::Socket::Async, but they are not documented.

I don't know how to use them.

Do they distinguish stream sockets and datagram sockets?

**Comment by coke** [comment]
This is a documentation issue, and belongs in the raku/doc repository. I can't transfer it with tools, so copying manually.

**Comment by coke** [comment]
linked new ticket, please subscribe for updates there.
