### ISSUE TITLE
$*IN.close breaks shell/run on macOS

### ISSUE THREAD

**Issue by ugexe** [rakudo/rakudo#5357]
## The Problem

On macOS closing stdin can lead to `shell` and `run` failing in an unexpected way:

```
$ raku -e 'say so shell("ls", :!err, :!out)'
True
```
```
$ raku -e '$*IN.close; say so shell("ls", :!err, :!out)'
False
```

On linux these both show `True`, which is what I would expect.

**Comment by jubilatious1** [comment]
Reproduced with both `bash` and `zsh`; MacOS Ventura 13.5.1

**Comment by lizmat** [comment]
Would it make sense to add ":in" to the parameters on MacOS if $*IN is closed?

**Comment by ugexe** [comment]
It does not make sense to make the user have to be aware of that case. It also does not make sense for core rakudo to try and work around the issue by checking if the handle is closed due to race conditions. The appropriate course of action will require changes in either moarvm or libuv.

**Comment by lizmat** [comment]
Closing in lieu of https://github.com/MoarVM/MoarVM/issues/1846
