### ISSUE TITLE
Reopening and closing a file removes its lock

### ISSUE THREAD

**Issue by Demayl** [rakudo/rakudo#5368]
## The Problem
After acquiring a file lock when the same file is opened for a second time, the lock is missing.
Note that the W flag from `lsof` command is missing
## Expected Behavior
```
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
raku    105569 root    3wW  REG   8,38        0 15349102 file.lock
sh      105575 root    3w   REG   8,38        0 15349102 file.lock

COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
raku    105569 root    3wW   REG   8,38        0 15349102 file.lock
sh      105748 root    3w   REG   8,38        0 15349102 file.lock
```
## Actual Behavior
```
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
raku    105569 root    3wW  REG   8,38        0 15349102 file.lock
sh      105575 root    3w   REG   8,38        0 15349102 file.lock

COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
raku    105569 root    3w   REG   8,38        0 15349102 file.lock
sh      105748 root    3w   REG   8,38        0 15349102 file.lock
```
## Steps to Reproduce
```raku
#!/usr/bin/env raku

my $lock-file = "file.lock";

my $fh = $lock-file.IO.open: :w;
$fh.lock;
say qqx{lsof $lock-file}; # Here we got the W flag enabled
'file.lock'.IO.open(:r).close;
say qqx{lsof $lock-file}; # W flag is missing

$fh.unlock;
$fh.close;
```

## Perl alternative
Here the lock is not removed
```perl
#!/usr/bin/env perl
use strict;
use warnings;
use feature 'say';
use Fcntl ':flock';

my $file = 'file-perl.lock';

open(my $fh, '+>', $file) or die "Could not open '$file' - $!";
flock($fh, LOCK_EX) or die "Could not lock '$file' - $!";
say `lsof $file`;

open(my $fh2, '<', $file) or die "Could not open '$file' - $!";
my $a = <$fh2>;
close $fh2;
say `lsof $file`;

close($fh) or die "Could not write '$file' - $!";
```

## Environment
* Operating system: Ubuntu 23.04 6.2.0-26-generic x86_64
* Compiler version: 
 `Welcome to Rakudo™ v2023.08.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.08.`

**Comment by 2colours** [comment]
For me, that Perl script only reports `Could not open 'file-perl.lock' - No such file or directory at /tmp/demo.pl line 9.`

It's really hard to say anything useful as I have zero clue how these locks are used - what I do find interesting, though, is that if you obtain a second, read-only handle to that file, and try to lock to that, an exception will be thrown (closing this handle removes the lock, as you pointed out) - HOWEVER, if your second handle is also a write handle, it will succeed no problem, obtaining the lock, and then removing the other lock as well when closed.

**Comment by Demayl** [comment]
@2colours I just fixed the Perl example. It seems that the filehandle is shared when opened for second time

**Comment by Demayl** [comment]
Well for me the root of the the issue is the same for both cases, but yes this is not ok as well. I found this when i was writing a PID to a locked file and after that in a separate function i opened it again to read the PID it and surprice :D

**Comment by vrurg** [comment]
Comparing to Perl's behavior wouldn't be correct here. Best if tested against C/Rust code where it maps more or less directly into OS calls. Raku, in this case, is very likely to rely upon libuv implementation.

**Comment by Demayl** [comment]
After a bit research, i found that Perl uses POSIX flock to do the job and Raku uses fcntl F_SETLKW which has the side effect of releasing the lock when a descriptor to the same file is closed.
Raku doesn't unlock the file at all, so maybe it's case closed.
