### ISSUE TITLE
Feature request: allow to set a global directory for precompilation

### ISSUE THREAD

**Issue by juanfra684** [rakudo/rakudo#5386]
I would like something like `PYTHONPYCACHEPREFIX`, `ZIG_GLOBAL_CACHE_DIR` or `DENO_DIR` for Raku, i.e. allow the users to set a global directory for the precompilation caches. This would allow me to move all the caches to a faster disk/partition with no backups. And no more `.precomp` directories in my `RAKULIB` or when I use `use lib "."`. Also, it would be easier to clean the cache from time to time.

**Comment by niner** [comment]
You should already be able to do this by simply ensuring that the desired directory is at the front of the repository chain, i.e. run rakudo with `rakudo -I/your/precomp/directory foo.raku` or `RAKULIB=/your/precomp/directory foo.raku`

We store precomp files in the first writable precomp directory we find.

**Comment by ugexe** [comment]
Because you are using `use lib "..."`, which would be ahead of what you pass with `-I`:
```
raku -Ifoo -e 'use lib "bar"; say $*REPO.repo-chain.join("\n")'
/Users/nlogan/repos/rakudo/bar
/Users/nlogan/repos/rakudo/foo
/Users/nlogan/.raku
/Users/nlogan/.rakubrew/versions/moar-2023.08/install/share/perl6/site
/Users/nlogan/.rakubrew/versions/moar-2023.08/install/share/perl6/vendor
/Users/nlogan/.rakubrew/versions/moar-2023.08/install/share/perl6/core
CompUnit::Repository::AbsolutePath<3235450667256>
CompUnit::Repository::NQP<3235449411160>
CompUnit::Repository::Perl5<3235449411200>
```
I would suggest not using `use lib "..."` and instead pass whatever library paths you want in via `-I` or `RAKULIB`

**Comment by lizmat** [comment]
Each repo impementation is responsible for how they produce the necessary bytecode when it is required.  If you use `-Ixxx`, you make sure that the repo that you specify there, will be handling the production of bytecode.  How it does that, is completely opaque.

Therefore the request of a global directory for precompilation can not be satisfied as such.
