### ISSUE TITLE
`use variables :D;` doesn't allow use of native variables in its scope

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#5391]
## The Problem

I encountered this when writing code for a comment:
```
use variables :D;

...

my int $foo = 42;
```
displays
```
Type check failed in assignment to $foo; expected int:D but got Int (42)
```

## Expected Behavior

Well, I half expected what I got, but it seems LTA!

**Comment by 2colours** [comment]
I suppose `:D` doesn't make sense for native variables but then it should be just ignored, rather than break stuff...

**Comment by lizmat** [comment]
Test added with https://github.com/rakudo/rakudo/commit/b167026846

**Comment by raiph** [comment]
Hi @lizmat 

Technically speaking this issue covered two problems, not one.

Your new test shows that one _can_ declare a native variable in the scope of `use variables :d;` in the latest RAST. That solves a literal interpretation of the title of this issue. So perhaps that's why you closed this issue.

But the test does _not_ show the example in the body working:
```
use variables :D;
my int $foo = 42; # Type check failed in assignment to $foo; expected int:D but ...
```
i.e. the case where the variable declaration _does_ include an explicit initialization. With the old front end this shows a run time error (which error does _not_ appear with the old front end if `use variables :D;` is _not_ in effect).

Have you _also_ fixed that aspect? If you have, then maybe add another test something like:
```
   lives-ok { 'use variables :D; my int $a = 42'.EVAL },
      'native integers can accept an initializer with variables:D';
```

Conversely, if you have _not_ fixed that then I'd be happy to file a new issue to cover just the `use variables :D; my int $foo = 42;` case.

**Comment by lizmat** [comment]
It is also fixed in RakuAST: test added with https://github.com/rakudo/rakudo/commit/4d6458989a
