### ISSUE TITLE
sub MAIN( $a ) { } with no args errors instead of displaying usage

### ISSUE THREAD

**Issue by zjhmoss** [rakudo/rakudo#5445]
## The Problem
main.raku with
`sub MAIN( $a ) { }`
errors:

> rindex search target requires a concrete string, but got null

instead of displaying usage when run with no arguments

### `raku --ll-exception main.raku`
```
raku --ll-exception main.raku
rindex search target requires a concrete string, but got null
   at 'SETTING::'src/core.c/IO/Path.rakumod:911  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime/CORE.c.setting.moarvm:x)
 from 'SETTING::'src/core.c/Main.rakumod:173  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime/CORE.c.setting.moarvm:)
 from 'SETTING::'src/core.c/Main.rakumod:171  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime/CORE.c.setting.moarvm:strip_path_prefix)
 from 'SETTING::'src/core.c/Main.rakumod:184  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime/CORE.c.setting.moarvm:default-generate-usage)
 from 'SETTING::'src/core.c/Main.rakumod:443  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime/CORE.c.setting.moarvm:RUN-MAIN)
 from min-main.raku:1  (<ephemeral file>:<unit>)
 from min-main.raku:1  (<ephemeral file>:<unit-outer>)
 from NQP::src\HLL\Compiler.nqp:196  (C:\Program Files\Rakudo\bin\..\share\nqp\lib/NQPHLL.moarvm:eval)
 from NQP::src\HLL\Compiler.nqp:441  (C:\Program Files\Rakudo\bin\..\share\nqp\lib/NQPHLL.moarvm:evalfiles)
 from NQP::src\HLL\Compiler.nqp:364  (C:\Program Files\Rakudo\bin\..\share\nqp\lib/NQPHLL.moarvm:command_eval)
 from src\Perl6\Compiler.nqp:229  (C:\Program Files\Rakudo\bin\..\share\perl6\lib/Perl6/Compiler.moarvm:command_eval)
 from NQP::src\HLL\Compiler.nqp:289  (C:\Program Files\Rakudo\bin\..\share\nqp\lib/NQPHLL.moarvm:command_line)
 from src\main.nqp:81  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime\perl6.moarvm:MAIN)
 from src\main.nqp:63  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime\perl6.moarvm:<mainline>)
 from <unknown>:1  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime\perl6.moarvm:<main>)
 from <unknown>:1  (C:\Program Files\Rakudo\bin\..\share\perl6\runtime\perl6.moarvm:<entry>)
```

## Environment
* Operating system: Windows 11
* Compiler version (`rakudo -v` or `raku -v`): v2023.10, v6.d, MoarVM 2023.10.

**Comment by lizmat** [comment]
This appears to be Windows specific, cannot reproduce on  macOS

**Comment by lizmat** [comment]
@MasterDuke appears to be related to recent stat changes

**Comment by melezhik** [comment]
I run for a list of Rakudos versions - https://sparky.sparrowhub.io/report/rakubug/20517 - got the same result:

```
Usage:
  code.raku <a>
```

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by zjhmoss** [comment]
> Is this still an issue?

yes

v2024.09
v6.d
MoarVM 2024.09

**Comment by melezhik** [comment]
I can't reproduce the issue for the latest rakudo - https://sparky.sparrowhub.io/report/gh-melezhik-r3tool/22839

**Comment by igb-ppp** [comment]
Problem still happens on Windows 11
`PS C:\Users\bla\eigene_programme\raku\test> raku .\autotime.raku
rindex search target requires a concrete string, but got null
  in method x at 'SETTING::'src/core.c/IO/Path.rakumod line 908
  in sub strip_path_prefix at 'SETTING::'src/core.c/Main.rakumod line 189
  in sub default-generate-usage at 'SETTING::'src/core.c/Main.rakumod line 200
  in sub RUN-MAIN at 'SETTING::'src/core.c/Main.rakumod line 460
  in block <unit> at .\autotime.raku line 1

PS C:\Users\bla\eigene_programme\raku\test> raku --version
Welcome to RakudoÔäó Star v2024.10.
Implementing the Raku┬« Programming Language v6.d.
Built on MoarVM version 2024.10.`

**Comment by ugexe** [comment]
I don’t see what rindex would have to do with stat. If anything it would make sense for it to involve one of the two calls to rindex.

**Comment by igb-ppp** [comment]
This seems to be a Windows (maybe just Win11, I'll try on a Win10 machine) problem only. It happens on all 3 machines where I've tried this out. The same program on the same machine, but in Ubuntu (WSL) runs fine. Is there anything that I coud trace or contribute?

**Comment by ugexe** [comment]
If you are comfortable adding some print debugging I'd add some around this line to see what the paths/variables it is choking on are:
https://github.com/rakudo/rakudo/blob/a82696a1af755a36ea39530106be136171812222/src/core.c/Main.rakumod#L205

My impression is the issue is related to one of the rindex calls in [IO::Spec::Win32](https://github.com/rakudo/rakudo/blob/a82696a1af755a36ea39530106be136171812222/src/core.c/IO/Spec/Win32.rakumod) such as the one `canonpath` can ultimately hit in `!canon-path` [here](https://github.com/rakudo/rakudo/blob/a82696a1af755a36ea39530106be136171812222/src/core.c/IO/Spec/Win32.rakumod#L286).

**Comment by igb-ppp** [comment]
I played around and found that the error happens _only_ if I the script I want to execute is in the current directory. 
Then I added some trace as recommended. Basially the error happens in the loop over all PATH elements for path element ".". 
$file is then
`$file = IO::Path.new(".\\autotime.raku", :SPEC(IO::Spec::Win32), :CWD("C:\\...\\raku\\test"))`
(note: CWD truncated, thus the ellipsis) and
`$file.x`
fails while
`$file.f`
works.
This can be verified with a small program test.raku:
```
my $file = '.\test.raku'.IO;
say $file.f;
say $file.x;

```
Output is
```
True
rindex search target requires a concrete string, but got null
  in method x at 'SETTING::'src/core.c/IO/Path.rakumod line 909
  in block <unit> at test.raku line 6
```

I added line
`next if $elem eq ".";`
to Main.rakumod after line 202 (as first line within the loop over all PATH elements). At least for me this works as a workaround, but I guess method x should be fixed on Windows.

**Comment by lizmat** [comment]
Ah, looks like jnthn already put code in for that in 2014: bc7efa382f80cc85343b603

**Comment by hjxkyw** [comment]
I think that's the same error (Windows 11)

$ raku --version
Welcome to Rakudo™ Star v2026.06.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2026.06.

$ raku test.raku --help
rindex search target requires a concrete string, but got null
  in block <unit> at client-for-broker-http.raku line 6
