### ISSUE TITLE
Token proto definitions do not work

### ISSUE THREAD

**Issue by ab5tract** [rakudo/rakudo#5446]
## The Problem

Token proto definitions do not work in RakuAST

## Expected Behavior

```
> RAKUDO_RAKUAST=1 ./rakudo-m -e 'my proto token foo() {*}'
```

compiles.

## Actual Behavior

```
> RAKUDO_RAKUAST=1 ./rakudo-m -e 'my proto token foo() {*}'
Missing block
   at SETTING::src/core.c/Exception.rakumod:65  (/Users/longwalker/code/raku/z.others/rakudo
```

## Environment
* Operating system: macOS
* Compiler version (`rakudo -v` or `raku -v`): v2023.10-29-g7fcbfd657

**Comment by lizmat** [comment]
This appears fixed
