### ISSUE TITLE
Rakudo crashes when using many promises / nested promise

### ISSUE THREAD

**Issue by Zer0-Tolerance** [rakudo/rakudo#5458]
## The Problem
Rakudo is crashing randomly due to this weird error:
```
Unhandled exception in code scheduled on thread 11
Too many positionals passed; expected 3 to 5 arguments but got 6
   in block  at SETTING::src/core.c/IO/Socket/Async.rakumod line 99
  in block  at /Users/user/.rakubrew/versions/moar-2023.09/bin/../share/perl6/runtime/CORE.c.setting.moarvm line 1
  in block  at /Users/user/.rakubrew/versions/moar-2023.09/bin/../share/perl6/runtime/CORE.c.setting.moarvm line 1
  in method run-one at SETTING::src/core.c/ThreadPoolScheduler.rakumod line 244
  in block  at SETTING::src/core.c/ThreadPoolScheduler.rakumod line 308
  in sub THREAD-ENTRY at SETTING::src/core.c/Thread.rakumod line 69
```
it seems the args passed to this piece of code is node always passing the right number of args sometime too many sometime not enough. 
```
$!scheduler.queue(:hint-affinity),
                    -> Mu \seq, Mu \data, Mu \err, Mu \hostname = Str, Mu \port = Int {
                        $lock.protect: 
```
## Expected Behavior
the number of args passed should be stable or at least between 3 & 5 
## Actual Behavior
This number can get higher than the expected number but I've no idea why. 
## Steps to Reproduce
not easy as my code is quite large but I'm using a lot of promises with IO::Socket::Async Cro::HTTP::Client
pattern is as follow:
```
IO::Socket::Async.connect($host, $port,:enc('latin1')).then(-> $promise {
  try {
    my $ua = Cro::HTTP::Client.new(:!persistent,:http<1.1>);
    $ua.get($url, ca => { :insecure }).then(-> $promise {
    ....
    }
  }

```
## Environment
* Operating system: OSX 
* Compiler version (`rakudo -v` or `raku -v`):
```
Welcome to Rakudo™ v2023.09.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.09.
```

**Comment by Zer0-Tolerance** [comment]
Second flavor of this issue:
```
Unhandled exception in code scheduled on thread 8
Too many positionals passed; expected 0 or 1 arguments but got 3
  in block  at SETTING::src/core.c/Promise.rakumod line 347
  in block  at SETTING::src/core.c/ThreadPoolScheduler.rakumod line 263
```
I don't always get the same error on every crash.

**Comment by ab5tract** [comment]
I have also seen this, though at this time I can't find the code that could be used to recreate the issue.

I have a feeling that this is related somehow to the new dispatch mechanism.

**Comment by patrickbkr** [comment]
@Zer0-Tolerance Can you try to put together a script that fires against a local nginx/apache/whatever and manages to trigger this error when run long / often enough?

**Comment by Zer0-Tolerance** [comment]
Hi @patrickbkr, sure thing  I'm on it.

**Comment by Zer0-Tolerance** [comment]
@patrickbkr  Please find the snippet called `crash3.raku` below , it should trigger the crash when you run it 4 or 5 time in a row. Let me know if this works, this is running against a mojolicious server on port 3000 using SSL `perl hello.pl daemon -l "https://*:3000"`. 
Mojo App snippet:
```
use Mojolicious::Lite;
get '/' => {data => 'Hello World!'};
app->start;
```
Raku code 
```
#!/usr/bin/env raku
use Cro::HTTP::Client;
use HTTP::UserAgent;
use Terminal::ANSIColor;
my $urlq=Channel.new;
my $promiseq=Channel.new;

sub MAIN (
  Str :u($url) is required,#= url to query 
	Str :m($method)='get',#= HTTP Method to use 
	Bool :$h=False, #= Show Headers
	Bool :$tls=True, #= Use TLS
	Int :$th=2, #= Threads to run in // 
	Int :$t=5, #= HTTP Timeout 
	Int :$pt=10, #= Promise Timeout 
	Bool :$b=False, #= Show Body 
	Bool :$d=False, #= Debug 
	Bool :$v=False, #= Verbose 
) {
  my $p;
  my $body;
  my $hdr;
  my $ua = Cro::HTTP::Client.new(:!persistent,:http<1.1>,:timeout($t));
  my @u;
  if $url.IO ~~ :r {
    $url.IO.lines.map({
      if $_ ~~ /:i ^http/ {
        $urlq.send: $_;
      }
      else {
        $urlq.send: "https://$_" if $tls;
        $urlq.send: "http://$_" if !$tls;
      }
    });
  }
  else {
    $urlq.send: $url;
  }
  my @webp;
  my @p;
  @webp.push: Promise.start({
    while (my $lurl = $urlq.poll) {
      my ($host,$port)=$lurl.split(':');
      $lurl ~~ /https?\:\/\/(.+)\:(\d+)/;
      say $lurl if $v;
      my $tlsp=IO::Socket::Async::SSL.connect($0,$1,:insecure(1), :enc('latin1'));
      my $webp;
      given $method {
        $webp=$ua.get($lurl, ca => { :insecure },headers => $hdr,body => $body) when 'get';
      }
      $promiseq.send: Promise.anyof(Promise.in($pt),getTLS($tlsp,$lurl,$h,$hdr,$b,$t,$v,$d));
      $promiseq.send: Promise.anyof(Promise.in($pt),croGet($webp,$lurl,$h,$hdr,$b,$t,$v,$d));
    }
  }) for ^$th;
  sleep $t;
  while (my $lp = $promiseq.poll) {
    await $lp if ($lp.WHAT.^name eq 'Promise');
  }
  await @webp;
  say 'end';
}

sub getTLS ($p,$url,$h,$hdr,$b,$t,$v,$d) {
  $p.then: -> $promise {
    if $promise.status ~~ Kept {
      if $promise.result {
        say "TLS: $url\t\tStatus: [",color('green'),'OK',RESET,"]";
      }
    }
  };
}

sub croGet ($p,$url,$h,$hdr,$b,$t,$v,$d) {
  $p.then: -> $promise {
    try {
      $promise.result;
      if ($promise.status ~~ Kept) {
        my $res = $promise.result;
        say "Url: $url\t\tStatus: [",color('green'),$res.status,RESET,"]";
      }
      CATCH {
        when X::Cro::HTTP::Error {
          say "Url: $url\t\tStatus: [",color('yellow'),.response.status,RESET,"]";
        }
        default {
          # say .^name, 'msg: ', .Str;
        }
      }
    }
  };
}
```
You have to generate the input file like this: `spurt('/tmp/a.txt', "127.0.0.1:3000" ~ "\n",:append) for ^1000` then run with : 
`raku crash3.raku -u /tmp/a.txt -tls -th=2 -t=4`

**Comment by Zer0-Tolerance** [comment]
@patrickbkr are you able to trigger the crash ? Any update ?

**Comment by patrickbkr** [comment]
@Zer0-Tolerance: I will pick this up. I'm on an epic quest to get Cro::HTTP::Client to one day work reliably, this bug is one to be squashed in the process. I am currently still working on a different misbehavior and would like to finish that first. So it will take some time (measured in weeks) before I'll get to this issue.

**Comment by Zer0-Tolerance** [comment]
thanks for the update, and let me know if I can be of any help for Cro::HTTP::Client bug as I'm trying to use it in my various projects but I got so many crashes all related to concurrency mostly I would say. I also got many issue `MoarVM oops: MVM_str_hash_fetch_nocheck called with a stale hashtable pointer` with `Net::DNS` or even `HTTP::UserAgent` when using many promises.

**Comment by lizmat** [comment]
> MoarVM oops: MVM_str_hash_fetch_nocheck called with a stale hashtable pointer

That indicates somewhere something is changing a hash from multiple threads simultaneously.

Could be in `Net::DNS` or `HTTP::UserAgent` itself, or in your code.  A golf:
```
$ raku -e 'my %h; (^Inf).race(:1batch).map: { %h{$_}++ }'
MoarVM oops: MVM_str_hash_fetch_nocheck called with a stale hashtable pointer
```

**Comment by Zer0-Tolerance** [comment]
thanks @lizmat  but how can one create a raku script without being worried all the time about concurrency issue ? I run into trouble everytime I'm trying something new with promises. If modules are not promise safe / thread safe it should be clear.

**Comment by lizmat** [comment]
@Zer0-Tolerance Perhaps https://6guts.wordpress.com/2014/04/17/racing-to-writeness-to-wrongness-leads/ would be good reading at this time :-)

**Comment by patrickbkr** [comment]
@Zer0-Tolerance Did you notice https://github.com/raku-community-modules/URI/commit/9df401bedacb52aa45441949a09207c17aef5758? Could this be the issue and fix to your problems?

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by patrickbkr** [comment]
Given I've hit the same problem and found it solved by https://github.com/raku-community-modules/URI/commit/9df401bedacb52aa45441949a09207c17aef5758, I believe this is actually done.
