### ISSUE TITLE
NativeCall is completely broken

### ISSUE THREAD

**Issue by ab5tract** [rakudo/rakudo#5461]
## The Problem

```
RAKUDO_RAKUAST=1 ./rakudo-m -Ilib -e 'use NativeCall';
No such method 'new' for invocant of type 'VMNull'.  Found 'new' on
type 'Mu'
```

## Notes

* This happened due to a4a2bbd24e, which initializes a lock inside of an `INIT` phaser.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/237469d21a
