### ISSUE TITLE
Invocant of method 'match' must be a type object of type 'Any'

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#5464]
Originally reported here: https://github.com/Raku/whateverable/issues/388#issuecomment-1737363873

Many of the whateverable bots were unable to run because of this issue:
```
Invocant of method 'match' must be a type object of type 'Any', not an
object instance of type 'IRC::Client::Message::Privmsg::Channel'.  Did
you forget a 'multi'?
```
* https://irclogs.raku.org/raku/2023-09-27.html#12:54-0001
* To me it looks like a Rakudo regression. Why would something be something that is other than “Any”?

Note that in Whateverable I had to apply this workaround to make things work: https://github.com/AlexDaniel/whateverable/commit/633616a3232a54baeb3fb445b8aea44d23537968

**Comment by ab5tract** [comment]
A minimal example, thanks to @dakkar ([source](https://gist.github.com/dakkar/3b5d54bf3830ea1ca1f4ae0e25c326d9))

```
use v6.d;

class Thing {
    has $.text;
    method Str { "thing: $!text" }
}

sub foo($t where { m/^thing:/ }) {
    print $t;
}

sub bar($t where { "$t" ~~ m/^thing:/ }) {
    print $t;
}

# this works
bar(Thing.new(:text<abc>));

# this says `Invocant of method 'match' must be a type object of type
# 'Any', not an object instance of type 'Thing'.  Did you forget a
# 'multi'?`
foo(Thing.new(:text<abc>));
```

**Comment by ab5tract** [comment]
With `RAKUDO_RAKUAST=1`, we get a failure even with the call to `bar`:

```
This type cannot unbox to a native integer: P6opaque, Match
   at /tmp/any.raku:12  (<ephemeral file>:bar)
```

**Comment by ab5tract** [comment]
Unsurprisingly, this also affects subsets:

```
raku -e 'subset S where { m/"aaa"/ }; class C { method Str { "aaa" } }; my S $s = C.new'
Invocant of method 'match' must be a type object of type 'Any', not an
object instance of type 'C'.  Did you forget a 'multi'?
```

**Comment by ab5tract** [comment]
While the original code in Whateverable must have worked at some point in the past, Bisectable is unable to pinpoint a release of Rakudo that doesn't produce an error ([signature](https://gist.github.com/Whateverable/f3b6a8c215e5e09bea0197b04280c45f) and [subset](https://gist.github.com/Whateverable/7f26ff8bb1cde01e32c1ca1b89e494d1)). Granted, only post-2015 releases are covered, so perhaps things were working at some point.

The relevant code from `Any.rakumod` is, frankly, baffling:

```
method match(Any:U: |) { self.Str; nqp::getlexcaller('$/') = Nil }
```

Intentionally triggering this code path fails at `self.Str`, as one would naturally expect.

**Comment by jnthn** [comment]
> The relevant code from Any.rakumod is, frankly, baffling:

I think its purpose is to trigger the standard warning issued for trying to stringify a type object, but if a class does `method Str() { ... }` instead of `multi method Str(::?CLASS:U:) { ... }` then it will suppress that warning.
