### ISSUE TITLE
RakuAST: DEPARSE appears to attempt to compile content of code blocks

### ISSUE THREAD

**Issue by vrurg** [rakudo/rakudo#5470]
## The Problem

The following example produces a warning about using `Nil` in string context.

```
my $doc = q:to/DOC/;
=begin pod
=begin code
class Foo {
    method foo is some-trait { }
}
=end code
=end pod
DOC
say my $doc2 = $doc.AST.DEPARSE;
```

**Comment by vrurg** [comment]
The problem in this particular case is the application of `is` trait which is not there. Turns out, `DEPARSE` tries to parse the code and ends up with begin-time attempting to apply the trait.

I'm afraid this is a potential landmine lying out there as the code block content may have nothing to do with Raku, nor with any code at all.

**Comment by lizmat** [comment]
Just to confirm that the AST generated is just a doc block:
````
RakuAST::StatementList.new(
  RakuAST::Doc::Block.new(
    type       => "pod",
    paragraphs => (
      RakuAST::Doc::Block.new(
        type       => "code",
        paragraphs => (
          "class Foo \{\n    method foo is some-trait \{ }\n}\n",
        )
      ),
    )
  )
)
````
