### ISSUE TITLE
Bad warning about .pm files

### ISSUE THREAD

**Issue by DarthGandalf** [rakudo/rakudo#5482]
## The Problem

Because the selection of packages at Raku Land is so limited, I wanted to reuse some Perl5 code from CPAN via Inline::Perl5. To avoid polluting system directories, I installed it via `cpanm -L . Foo::Bar`.

## Expected Behavior

No warning

## Actual Behavior

```
Saw 1 occurrence of deprecated code.
================================================================================
.pm file extension in raku library path seen at:
  file#/var/tmp/foo, line 0
Please use the .rakumod extension for raku modules, or include a META6.json file that explicitly declares each raku module file instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
```

## Steps to Reproduce

1. `echo "use lib '.';" > a.raku;`
2. `touch B.rakumod`
3. `echo "use B;" >> a.raku`
4. `mkdir -p c/d/e`
5. `touch c/d/e/unrelated.pm`
6. `raku a.raku`

Note that mere existence of a .pm file shows this warning, even if it's in a deep subdir like `./perl5lib`

## Environment
* Operating system: Gentoo Linux
* Compiler version (`rakudo -v` or `raku -v`): v2023.10.

**Comment by ugexe** [comment]
The directory you provide to lib isn’t for Perl modules, and this everything under it is counted as part of the same raku distribution.

**Comment by ugexe** [comment]
Note that in the future when rakudo no longer treats .pm files as Raku modules this deprecation message will go away, and things will work the way you want.

**Comment by DarthGandalf** [comment]
> The directory you provide to lib isn’t for Perl modules

I know. The goal was to use it with `use lib:from<Perl5> '.';` but the warning happens regardless of that line

**Comment by niner** [comment]
I would put those modules into a sub directory called p5lib and then just `use lib:from<Perl5> 'p5lib';`

Actually I would do neither and instead declare those modules as dependencies in your META6.json: `"depends": [{"name": "Foo::Bar", "from": "Perl5"}]`. That will make it clear what your code needs and allow for the user to install those modules in their preferred way. E.g. at my former work place we generated RPM packages for Raku modules and those Perl dependencies were automatically translated to RPM dependencies and the Perl packages installed that way. Note that you can always use the PERLLIB environment variable to point Perl at some manually installed packages.

**Comment by DarthGandalf** [comment]
> I would put those modules into a sub directory called p5lib

That still triggers the warning

Re translation to RPM, interesting idea. Too heavy for my use case though. Even META6.json is a bit heavy... But if it's the common practice in Raku for modules which are not going to be distributed, except that merely pushing the code to github for posterity, to have META6.json file, that should work then.

**Comment by 2colours** [comment]
This is kind of a recurring topic, I would say, that `use lib` is not really meant for anything serious:
1. it eagerly builds the given folder into a compilation unit repository, meaning that the larger the folder, the slower it is for you to start up your script that does `use lib`
2. if you were to do `use lib` in a module to cross-share code between your own modules, that module cannot be precompiled any longer

For your use case, the former seems more concerning. I remember discussions about the latter more, and with that, the conclusion really seemed to be that it's largely unsalvageable.

**Comment by DarthGandalf** [comment]
Yeah, I didn't have a separate subdir for lib/. But having p5lib in ../ silences it.

**Comment by 2colours** [comment]
@DarthGandalf what do you think about this issue now? I'm not sure if it's still an issue - at least not the issue that was opened?

**Comment by DarthGandalf** [comment]
That's up to you. If you wish to close it, or to change the way how it warns, I don't mind either way.

**Comment by 0rir** [comment]
The only information I could find is from the commit 4d5f6ff9:

   We need to know when raku source files have changed for the purposes
    of precompilation. However, when a user includes a library path
    (i.e. -Ilib, -I/home/foo) that does not contain a META6.json file
    we might end up erroneously considering perl module files (which
    also use .pm) as raku files. While this is mostly harmless, it
    does waste some cpu and io. This adds a deprecation message when
    this ambiguous situation occurs so that in the future we might be
    able to remove support for the .pm extension altogether.

I presume @ugexe  is correct that `.pm` files will someday  be treated  like other cruft in a libdir.

So unless there are other harms than wasting 'some cpu and io', perhaps this deprecation report is just not helpful.  Particularly so if `.pm` files will again be allowed to exist in Raku's libdirs.

The hard coded message of who to contact regarding the matter is misleading.  The author of the triggering code may have nothing to do with problematic `.pm` files.

Consider backing out the commit.

**Comment by lizmat** [comment]
Closing in light of https://github.com/rakudo/rakudo/pull/5669 .  Either that PR gets merged, or not.
