### ISSUE TITLE
Use of lookbehind assertions in .trans hangs rakudo

### ISSUE THREAD

**Issue by drudgesentinel** [rakudo/rakudo#5488]
## Expected Behavior
Given the following:

```
sub translate-lines ($line) {
  $line.trans([
    /<?after o>ne/,
    "two", 
    "three", 
    "four", 
    "five", 
    "six", 
    "seven", 
    /<?after e>ight/, 
    "nine"
  ] => [
    1, 2, 3, 4, 5, 6, 7, 8, 9
  ]);
}
```
Simple cases translate correctly:
`my $working-example = "onetwo3"; #o123`

Cases with overlap hang `raku`:
`my $gotcha = "twone"; # ctrl + C after 1 minutes`

## Steps to Reproduce
`'twone'.trans((/<?after o>ne/, 'two') => (1, 2))`

## Environment
* Operating system: Ubuntu LTS
```
Welcome to Rakudo™ v2023.11.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.11.
```

**Comment by lizmat** [comment]
This is going to need a good looking at the LSM module inside the Str class.  Which is one oldest pieces of code still in core: 01ac0d821b (2011).

**Comment by lizmat** [comment]
Added test with https://github.com/Raku/roast/commit/e58d0bb861
