### ISSUE TITLE
RakuAST expression condition modifier issue

### ISSUE THREAD

**Issue by hythm7** [rakudo/rakudo#5496]
## The Problem

This is parsed correctly:

```sh
raku -e 'my $a = q[my $foo = "foo" if True].AST; say $a.DEPARSE';
my $foo = "foo"
 if True
```

However, adding another statement, looks like the condition modifier is now part of the new statement not the previous one:

```sh
raku -e 'my $a = q[my $foo = "foo" if True; $foo].AST; say $a.DEPARSE';
my $foo = "foo";
 if True$foo
```

## Expected Behavior

I t should parse as:

```sh
 my $foo = "foo" if True;
 $foo;
```

## Actual Behavior

```sh
my $foo = "foo";
 if True$foo
```

## Environment
* Operating system: Linux
* Compiler version (`rakudo -v` or `raku -v`):
```sh
raku -v
Welcome to Rakudo™ v2023.11-74-g5606fb657.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.11-1-gbe03e26fc.
```

**Comment by lizmat** [comment]
Thanks for the report!
