### ISSUE TITLE
Array.splice insists on flattening the replacement

### ISSUE THREAD

**Issue by DarthGandalf** [rakudo/rakudo#5500]
## The Problem
I have a 2d array (array of arrays), and I want to insert a new row to it.

```raku
my @map = [[11, 12], [31,32]];
my @newrow = [21, 22];
@map.splice(1, 0, @newrow);
```

## Expected Behavior
I want `@map` to look like this:
```
[
    [11, 12],
    [21, 22],
    [31, 32]
]
```

## Actual Behavior
`@map` will now look like this:
```
[
    [11, 12],
    21,
    22,
    [31, 32]
]
```

I tried to pass `[[[[@newrow]]]]` to .splice(), tried to pass `$@newrow`, without any difference. The only workaround I found is this:
```raku
@map.splice(1, 0, 'dummy');
@map[1] = @newrow;
```

## Environment
* Operating system: Gentoo Linux, amd64
* Compiler version (`rakudo -v` or `raku -v`): v2023.10

**Comment by ab5tract** [comment]
It took a minute (longer than it should have, in retrospect) but I think I have a way to resolve this without breaking any existing `splice` contracts.

```
my @a = [1, 2, 3];
@a.splice(1, 1, [2, 2]) :preserve;
dd @a; # [1, [2, 2], 3
```

**Comment by ab5tract** [comment]
It took a bit longer than expected, but this is finally available in `HEAD`:

   > use v6.e.PREVIEW; # only works in versions 6.e+
   > my @a = 1,2,3;
   > @a.splice(1,1,$[7,8])
   > dd @a
   # [1,[7,8],3]
