### ISSUE TITLE
`$*VM.config<ld>`  is sometimes equal to `gcc`

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#5529]
## The Problem

From the process of solution to [this issue](https://github.com/retupmoca/P6-LibraryMake/issues/51), it transpires that apparently almost everywhere the value in that variable is `gcc`, except in NixOS (don't know, probably in others) when it's equal to `ld`.

## Expected Behavior

Well, probably the NixOS behavior should be the one.

## Actual Behavior

The probably in LibraryMake is that the code using it was expecting it to behave the "usual" way, so it broke when used in NixOS

## Steps to Reproduce

You can probably use something like [this GitHub action](https://github.com/retupmoca/P6-LibraryMake/blob/master/.github/workflows/nixos.yml) (provided by @rcmlz) to check its value. In my desktop system (ubuntu)

```
 raku -e 'say $*VM.config<ld>'                                                                                                                             
gcc
```

`$*VM` does not seem to work on the Mac

**Comment by lizmat** [comment]
On Sonoma 14.2.1:
```
% raku -e 'dd $*VM.config<ld>'
"clang"
```

**Comment by JJ** [comment]
> On Sonoma 14.2.1:
> 
> ```
> % raku -e 'dd $*VM.config<ld>'
> "clang"
> ```
Not the main point of the issue, but it must be due to the different ways it's compiled or created. At any rate, what this shows it that it returns the compiler, not the linker (although I don't really know what would be the equivalent linked in this case)

**Comment by lizmat** [comment]
I think `clang` also links.  From `man clang`:
```
       Linker This stage runs the target linker to merge multiple object files
              into an executable or dynamic library. The output of this stage
              is typically called an "a.out", ".dylib" or ".so" file.
```

**Comment by JJ** [comment]
`gcc` too, it calls the linker underneath.

**Comment by patrickbkr** [comment]
I believe this is actually correct, it uses gcc / clang as linker.

**Comment by patrickbkr** [comment]
I wonder where that "ld" comes from in the first place. It's not to be found in MoarVMs [build/setup.pm](https://github.com/MoarVM/MoarVM/blob/main/build/setup.pm).

**Comment by JJ** [comment]
Well, `ld` is `undef` there

https://github.com/MoarVM/MoarVM/blob/edbd26473128c7c7275e5645ccb1cfab22326287/build/setup.pm#L335

**Comment by patrickbkr** [comment]
Nothing in [the Nix package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/rakudo/moarvm.nix) either.

**Comment by JJ** [comment]
I would say the issue is somewhere in Configure.PL. When the value is undefined, something unexpected happens. I have looked at the generated Makefile and it does have `ld` defined as `gcc` The thing is probably the Makefiles used in MoarVM do use `$(M_LD)` in a way that's compatible with both `gcc`  and `ld`  (or any other value it might obtain); other random makefiles might not.

**Comment by JJ** [comment]
And here it is:

https://github.com/MoarVM/MoarVM/blob/edbd26473128c7c7275e5645ccb1cfab22326287/Configure.pl#L159

Digging so deep into MoarVM configuration I guess makes this something that should get documented, not "fixed" (for any meaning of the word)

**Comment by patrickbkr** [comment]
Hm. But where the "ld" came from is still unknown.

**Comment by patrickbkr** [comment]
> I would say the issue is somewhere in Configure.PL. When the value is undefined, something unexpected happens. I have looked at the generated Makefile and it does have `ld` defined as `gcc` The thing is probably the Makefiles used in MoarVM do use `$(M_LD)` in a way that's compatible with both `gcc` and `ld` (or any other value it might obtain); other random makefiles might not.

I think the idea is that setup.pm provides a consistent set of options that will work ($ld, $ldflags, ...). It shouldn't matter to the consumer what's in $ld as long as it's a consistent, working set of options.
The issue I see, is that something overwrote $ld, making it incompatible with the rest of the configuration.

**Comment by JJ** [comment]
> > I would say the issue is somewhere in Configure.PL. When the value is undefined, something unexpected happens. I have looked at the generated Makefile and it does have `ld` defined as `gcc` The thing is probably the Makefiles used in MoarVM do use `$(M_LD)` in a way that's compatible with both `gcc` and `ld` (or any other value it might obtain); other random makefiles might not.
> 
> I think the idea is that setup.pm provides a consistent set of options that will work ($ld, $ldflags, ...). It shouldn't matter to the consumer what's in $ld as long as it's a consistent, working set of options. The issue I see, is that something overwrote $ld, making it incompatible with the rest of the configuration.

As long as it's going to be consumed, it really does, because the flag syntax is going to be different for `gcc`  and for `ld`, even doing the same function; `ld` is simply not plug-compatible with `gcc` (the rest of the compilers might have similar problems). So a clarification along the lines of "Hey, this variable is going to contain what Moar used for linking, which might or might not be an actual linker" will help people understand what they should use in LibraryMake or anywhere else they might want to use it. Besides, this is a dire need, because if something fails, it's going to be incredibly complicated where the error came from.

**Comment by patrickbkr** [comment]
But different linkers have different and incompatible flags as well. `gcc` is not the one odd man out taking different flags. Seen this way "gcc" *is* a totally fine linker. One just needs to call it the way it wants to be called. The same is true for "link", "clang", "ld" or any other program that can work as a linker. Fundamentally one can't just use `%LD%` and assume it's some specific linker. That's what `%LDSHARED%`, `%LDFLAGS%` and `%LDOUT%` are for. They specify how to call the linker given in `%LD%`. In the issue we are observing here, the moar's setup.pm provided a working set of options, where `%LD%` had "gcc" and the other flags matched that. The issue only arises after something overrides `%LD%` with "ld" causing the failure, because the "ld" linker doesn't understand the "gcc" linker flags.

So if we document this, then the doc should state something like: "Do not assume %LD% is some specific linker. Use %LD%, %LDSHARED%, %LDFLAGS% and %LDOUT% to generate a working command."

The problem causing the issue of this report is not yet found though. Something changes `%LD%` to "ld", but fails to change `%LDSHARED%`, `%LDFLAGS%` and `%LDOUT%` at the same time.

I wonder if moar actually managed to be built with "ld" or if something changed that value somewhere down the line.

**Comment by niner** [comment]
This is true for all these values. All they mean is "these tools were used when compiling MoarVM". This does not in any way imply that they are usable for other purposes. There is no requirement at all that someone has to use the same tools as were used for MoarVM. They may not even be available if MoarVM was compiled on a different host and e.g. installed from a package.

`$*VM<config>` tells you exactly that - the VM's config. It does not tell you in any way shape or form what you should do with your own modules.

**Comment by JJ** [comment]
We can all agree that it does what it does. However, the issue still stands, because what those configuration variables mean, if we want them to be useful, should be documented for what they are expected to hold.
At any rate, this is either a documentation bug, a MoarVM WAT, or something that people will not find unless they work with LibraryMake, where the issue has been solved. So let the issue itself serve as document just in case people come here when searching. Closing. Thanks for the feedback.

**Comment by patrickbkr** [comment]
This leaves the question open of how to best look for a build toolchain for modules that need one. Currently `Distribution::Builder::MakeFromJSON`, `Native::Compile` and `LibraryMake` all just rely on `$*VM<config>`.

Following through with the idea that `$*VM<config>` is purely informational, one would need a tool to search the environment for available build toolchains (possibly preferring the one Moar was using), pick one and provide a set of usable command templates. I believe we currently don't have such a thing. Is there prior art out there?

**Comment by vrurg** [comment]
> This leaves the question open of how to best look for a build toolchain

Best in the sense of "most commonly used in the future" would be to have an autoconf-like module. Otherwise there is no silver bullet for the task. What if the underlying lib requires a specific toolchain? Or even non-C language?

**Comment by patrickbkr** [comment]
@vrurg Did you notice my request for feedback? I'd love to hear from you.

**Comment by vrurg** [comment]
@patrickbkr Sorry, so little free time I have that even forgot to reply. Aside of that, I'm not a big specialist in toolchains too. So, just gonna trust you on this. :)
