### ISSUE TITLE
Race condition in REA Harvester (redux)

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#5551]
This is a followup of #5444 with all of my findings so far.  And theories.

This all started seeing the REA harvester crash every 1/20 times or so with what is now this stacktrace:

MRO got set after waiting .1 second
   at [NQP::src/how/NQPClassHOW.nqp:867](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L906)  (rakudo/install/share/nqp/lib/nqpmo.moarvm:find_method)
 from [NQP::src/core/dispatchers.nqp:26](https://github.com/Raku/nqp/blob/main/src/core/dispatchers.nqp#L27)  (rakudo/install/share/nqp/lib/NQPCORE.setting.moarvm:)
 from [src/vm/moar/dispatchers.nqp:2200](https://github.com/rakudo/rakudo/blob/main/src/vm/moar/dispatchers.nqp#L2194)  (rakudo/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:raku-multi-plan)
 from [src/vm/moar/dispatchers.nqp:2688](https://github.com/rakudo/rakudo/blob/main/src/vm/moar/dispatchers.nqp#L2688)  (rakudo/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from [SETTING::src/core.c/IO/Pipe.rakumod:19](https://github.com/rakudo/rakudo/blob/main/src/core.c/IO/Pipe.rakumod#L19)

1. First of all, the actual line numbers in NQP are about 30 lines off.  I've put in links to the actual source locations.

2. The line in `IO::Pipe` is special, because it refers to `$.nl-in`, which is a [method in `IO::Handle`](https://github.com/rakudo/rakudo/blob/main/src/core.c/IO/Handle.rakumod#L212) returning a `Proxy`.

3. Because this is a proxy, the dispatcher calls `MultiDispatchNonScalar.new`, which causes an [NQP method dispatch](https://github.com/Raku/nqp/blob/main/src/core/dispatchers.nqp#L6) to happen.  Which then ultimately results in a [call to NQPClassHOW.find_method](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L898).

4. Once in `find_method`, it tries to access its `$!mro`, only to find it to be `nqp::null` and crashing.  Now, with the snitch code in place, we actually see that .1 second later, it **is** correctly set.

5. How can this be?  Looking at the [`NQPClassHOW.new` method](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L78) it should be clear that a. [`$!mro` should at least be an `nqp::list`](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L91).  And b. that the `NQPClassHOW` instance isn't "published" until it is returned by `new`.

So far the facts as far as I have been able to deduce them

**Comment by lizmat** [comment]
Some background:

1. If the REA harvester runs in a single thread, there is no crash.
2. The REA harvester is basically a front-end for pretty massively async calls to `curl` with `run`, which explains the `IO::Pipe`.
3. There is some garbage in the ecosystem (not sure where exactly, as the warnings only point to `JSON::Fast`, and that's being called in quite a few places in the REA harvester).
4. The warnings are issued by [`Nil.Str`](https://github.com/rakudo/rakudo/blob/main/src/core.c/Nil.rakumod#L70) because of the `Str()` in the call to [`from-json`](https://github.com/timo/json_fast/blob/master/lib/JSON/Fast.pm6#L1002)

**Comment by lizmat** [comment]
Question: how can `$!mro` even become `nqp::null` when all of the bindings ([1](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L91), [2](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L250), [3](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L333)) are atomic?

Possible answer: Maybe `$!foo := subcall()` isn't atomic after all?   That would explain a lot.  But also would be a deep gremlin waiting to strike at any heavily async program.

Question: perhaps [`compute_c3_mro`](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L509) returns an `nqp::null`?

Answer: looking at the code, I don't see how that could happen, as the only return from it is at the [end](https://github.com/Raku/nqp/blob/main/src/how/NQPClassHOW.nqp#L539), and we're doing an `nqp::unshift(@result, $class)` just before that.  If `@result` would be `nqp::null`, then it would already crash then and there.

Question: perhaps the warnings have something to do with it?

Answer: that's the only reasonable lead I've been able to come up with at this stage.  As I did notice that all successful runs have 4 warnings, and the runs that crash do not show any warning at all.  So I'm really starting to wonder whether some type of incorrect resumption is somehow wreaking havoc here.

**Comment by lizmat** [comment]
Hoping for more eyes / suggestions from @jnthn @niner @vrurg @ab5tract @Xliff @ugexe @tony-o @japhb @jonathanstowe

**Comment by lizmat** [comment]
One scary thought: if this *is* about an incorrect resumption from a control message, then this would also apply to `next`, `last`, `return`, etc. which are also control messages.

**Comment by lizmat** [comment]
I was just realizing that the `NQPClassHOW` of the `MultiDispatchNonScalar` class **should** have been precompiled already.

A thought that just occurred to me: the `nqp::loadbytecode` as far as I understand, just sets up mapping of the bytecode file, to lazily load what actual bytecode it needs.

What if the race condition is in the lazy loading of the `MultiDispatchNonScalar.HOW`: Thread 1 decides it needs it, starts to load it and then starts initializing its attributes.  Thread 2 at the same time needs it also, but decides it's already loaded and starts using it **while** thread one is still initializing the attributes?  @jnthn @MasterDuke17

**Comment by MasterDuke17** [comment]
https://github.com/MoarVM/MoarVM/blob/f2220d93d976c6ff915761c01f006012c410b874/src/core/loadbytecode.c#L96 has some locking, but I have no idea if it’s sufficient.Sent from my iPhoneOn Apr 13, 2024, at 8:18 AM, Elizabeth Mattijsen ***@***.***> wrote:﻿
I was just realizing that the NQPClassHOW of the MultiDispatchNonScalar class should have been precompiled already.
A thought that just occurred to me: the nqp::loadbytecode as far as I understand, just sets up mapping of the bytecode file, to lazily load what actual bytecode it needs.
What if the race condition is in the lazy loading of the MultiDispatchNonScalar.HOW: Thread 1 decides it needs it, starts to load it and then starts initializing its attributes.  Thread 2 at the same time needs it also, but decides it's already loaded and starts using it while thread one is still initializing the attributes?  @jnthn @MasterDuke17

**Comment by lizmat** [comment]
Hopefully https://github.com/MoarVM/MoarVM/commit/d5dafa9b47 is the fix.

This is running in the REA harvester now.

**Comment by lizmat** [comment]
REA harvester has been running without problems in 150+ runs now.  Considering this bug fixed.
