### ISSUE TITLE
`-n` doesn't work naturally with WhateverCodes

### ISSUE THREAD

**Issue by ab5tract** [rakudo/rakudo#5557]
## The Problem

It would be nice to be able to provide `WhateverCode` expressions to `raku -ne`.

## Expected Behavior

```
> echo "word" | raku -ne '* ~~ /\w+/ ==> say()'
｢word｣
```

## Actual Behavior

```
> echo "word" | raku -ne '* ~~ /\w+/ ==> say()'
WhateverCode.new
```

This works, but is hardly ergonomic:

```
> echo "word" | raku -ne '(* ~~ /\w+/)($_) ==> say()'
｢word｣
```

## Environment
* Operating system: macOS 14.4
* Compiler version (`rakudo -v` or `raku -v`): v2024.03-208-g3af6b3664

**Comment by jubilatious1** [comment]
Works fine with `Rakudo 2023.05` under `MacOS Ventura 13.6.7`:

zsh shell:
```perl6
~% echo "word" | raku -ne '$_ ~~ /\w+/ ==> say()'
｢word｣
```

Although I tend to shy away from the feed operator:
```perl6
 ~ % echo "word" | raku -ne '$_ ~~ /\w+/ andthen .say'
｢word｣
wmichels@MacBook-Pro ~ % echo "word" | raku -ne '$/.say if $_ ~~ /\w+/'
｢word｣
wmichels@MacBook-Pro ~ % echo "word" | raku -ne '$/.say with $_ ~~ /\w+/'
｢word｣
```

HTH.

**Comment by ab5tract** [comment]
It looks like I had a typo in my original post. The behavior of the topic variable is indeed working 100%, as your examples (and my typo) demonstrate.

What this issue raises is that primed expressions are not called automatically. This actually makes total sense because:

```
* eq "foo"
```

is (roughly) equivalent to

```
{ $_ eq "foo" }
```

but **not** equivalent to

```
$_ eq "foo"
```

For that reason I'm closing this issue now.

**Comment by jubilatious1** [comment]
I see your typo now. Thanks.

Does anything below help? FYI, I'm pleasantly surprised to see that `m/.../` and `/.../` give different returns (presumably the `m/.../` form sets the `$/` value?):

```perl6
~ % echo "word" | raku -ne 'say $_ eq /\w+/;'
Regex object coerced to string (please use .gist or .raku to do that)
  in block  at -e line 1
False
~ % echo "word" | raku -ne 'say $_ eq m/\w+/;'
True
~ % echo "word" | raku -ne 'say $_ ~~ m/\w+/;'
｢word｣
~ % echo "word" | raku -ne 'say * ~~ m/\w+/;'
WhateverCode.new
```

I read over the Docs, and tried the code below. Maybe `.ACCEPTS(*)` is the code you want?
```perl6
~ % echo "word" | raku -ne 'say m/\w+/.ACCEPTS($_);'
｢word｣
~ % echo "word" | raku -ne 'say m/\w+/.ACCEPTS(*);'
｢word｣
~ % echo "word" | raku -ne 'say m/\w+/.ACCEPTS(Whatever);'
｢word｣
~ % echo "word" | raku -ne 'say /\w+/.ACCEPTS(*);'
Nil
```

But this (note deliberate `m/\d+/` change):
```perl6
~ % echo "word" | raku -ne 'say m/\d+/.ACCEPTS($_);'
False
wmichels@MacBook-Pro ~ % echo "word" | raku -ne 'say m/\d+/.ACCEPTS(*);'
False
wmichels@MacBook-Pro ~ % echo "word" | raku -ne 'say m/\d+/.ACCEPTS(Whatever);'
False
wmichels@MacBook-Pro ~ % echo "word" | raku -ne 'say m/\d+/.ACCEPTS(Nil);'
True
wmichels@MacBook-Pro ~ % echo "word" | raku -ne 'say m/\d+/.ACCEPTS();'
Cannot resolve caller ACCEPTS(Nil:U: ); none of these signatures matches:
    (Mu:U: Mu \topic, *%_)
    (Mu:U \SELF: Junction:D \topic, *%_)
    (Any:D: Mu:U, *%_ --> Bool::False)
    (Any:D: Mu:D \topic, *%_)
  in block <unit> at -e line 1
```

HTH.

https://docs.raku.org/routine/ACCEPTS
