### ISSUE TITLE
New type Block for List is not a mixin type

### ISSUE THREAD

**Issue by demanuel** [rakudo/rakudo#5563]
Just updated raku to latest main. Now zef doesn't work.

```
> zef
===SORRY!=== Error while compiling /usr/bin/zef
New type Block for List is not a mixin type
at /usr/bin/zef:3

> 
```

## Expected Behavior

zef should work

## Environment
* Operating system: Linux archlinux 6.8.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000 x86_64 GNU/Linux

* Compiler version (`rakudo -v` or `raku -v`): Latest main:
Welcome to Rakudo™ v2024.04-78-gb6028f9da.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-4-gc1eedd502.

**Comment by demanuel** [comment]
Now lots of modules either throw the error `New type Block for List is not a mixin type` or just sigsegv:

```
demanuel@archlinux ~/P/R/App-Feeds (master)> raku
Welcome to Rakudo™ v2024.04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04.

To exit type 'exit' or '^D'
[0] > **use Zef::CLI;**
===SORRY!=== Error while compiling:
New type Block for List is not a mixin type
[0] > 
demanuel@archlinux ~/P/R/App-Feeds (master)> raku
Welcome to Rakudo™ v2024.04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04.

To exit type 'exit' or '^D'
[0] > **use DBIish;**
===SORRY!=== Error while compiling:
New type Block for List is not a mixin type
[0] > use rak
fish: Job 1, 'raku' terminated by signal SIGSEGV (Address boundary error)
demanuel@archlinux ~/P/R/App-Feeds (master) [SIGSEGV]> raku
Welcome to Rakudo™ v2024.04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04.

To exit type 'exit' or '^D'
[0] > **use Cro::HTTP::Client**
**fish: Job 1, 'raku' terminated by signal SIGSEGV (Address boundary error)**
demanuel@archlinux ~/P/R/App-Feeds (master) [SIGSEGV]> raku
Welcome to Rakudo™ v2024.04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04.

To exit type 'exit' or '^D'
[0] > use JSON::Fast
Nil
[1] > **use HTML::EscapeUtils**
===SORRY!=== Error while compiling:
New type Block for List is not a mixin type
[1] > 

```

**Comment by lizmat** [comment]
This feels like your rakudo installation somehow got corrupted.

Could you try remove the "install" directory and build Rakudo from scratch?  **NOTE**: you will have to re-install any modules that you have installed if you do that.  Which is kinda the point of this action: to make sure there's no interference from stuff that has been left behind.

**Comment by demanuel** [comment]
Deleted the folder `~/.raku` and rebuilded it from scratch. zef is now working. However now DBIish isn't installing

- DBIish:
  demanuel@archlinux ~> zef install DBIish
zef install DBIish
===> Searching for: DBIish
===> Searching for missing dependencies: NativeLibs:ver<0.0.9+>:auth<github:salortiz>, NativeCall::TypeDiag
===> Staging NativeLibs:ver<0.0.9>:auth<github:salortiz>
===> Staging [OK] for NativeLibs:ver<0.0.9>:auth<github:salortiz>
===> Staging NativeCall::TypeDiag
===> Staging [OK] for NativeCall::TypeDiag
===> Staging DBIish:ver<0.6.6>:auth<zef:raku-community-modules>:api<1>
===SORRY!=== Error while compiling /home/demanuel/home#sources/E9B6C1346DB98B31BECB4AD754F69C020E092B67 (DBDish::mysql)
Undeclared name:
    Pointer used at lines 59, 59



I checked the commits in the DBIish repo and there's only this change: https://github.com/raku-community-modules/DBIish/commit/c078719f70b4c0273634f7b443eeef17fcba7aa2

**Comment by lizmat** [comment]
Found the underlying issue (same as with #5567).  Thinking of a proper solution.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/46a8f32472

**Comment by demanuel** [comment]
Thanks!
