### ISSUE TITLE
Error in LibCurl with v2024.04-82-gecd2dd469.

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#5567]
## The Problem
got
 ===SORRY!=== Error while compiling /home/richard/development/raku-collection-plugin-development/home#sources/4C3E08F15178D3444F73775C0B6BADC1E61100A6 (LibCurl::EasyHandle)
Undeclared routine:
    ssize_t used at line 5

## Expected Behavior
LibCurl should compile without error
## Environment
* Operating system: Ubuntu
* Compiler version (`rakudo -v` or `raku -v`):
* richard@ged:~/development/rakuast-rakudoc-render$ raku -v
Welcome to Rakudo™ v2024.04-82-gecd2dd469.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-4-gc1eedd502.

**Comment by lizmat** [comment]
I've located the issue: now on to thinking of a proper solution.

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/46a8f32472
