### ISSUE TITLE
`[Numeric, 42].are` # No such method 'mro'

### ISSUE THREAD

**Issue by raiph** [rakudo/rakudo#5568]
## Expected Behavior
```
say [42, Numeric].are; # (Numeric)
say [Numeric, 42].are; # (Numeric)
```
## Actual Behavior
```
say [42, Numeric].are; # (Numeric)
say [Numeric, 42].are; # No such method 'mro' for invocant of type 'Perl6::Metamodel::ParametricRoleGroupHOW'
```
Version: rakudo-moar 46a8f3247: OUTPUT: «v2024.04.85.g.46.a.8.f.3247␤»

Presumably the algorithm for `.are` is assuming that it can call `.^mro` on a role.

[This code at the start of `method !slow-infer`](https://github.com/rakudo/rakudo/blob/46a8f32472ea1d158b1642c9fe61d92d1cf18645/src/core.c/Any-iterable-methods.rakumod#L2139-L2142) is presumably the problem?

**Comment by lizmat** [comment]
Thanks for the report!

Fixed with https://github.com/rakudo/rakudo/commit/e227a4f29c , test added with https://github.com/Raku/roast/commit/05945b94b5
