### ISSUE TITLE
leave not implemented

### ISSUE THREAD

**Issue by wayland** [rakudo/rakudo#5577]
## The Problem

The `leave` keyword isn't implemented

## Previous ticket

[leave](https://github.com/Raku/old-issue-tracker/issues/4112)

**Comment by wayland** [comment]
I also made a list of old label-related tickets (excluding a few that seem to be fixed).  I made this for my own purposes, but thought I'd post it here in case it's useful (ie. if someone wants to kill multiple birds with one stone or something).  

*   [leave](https://github.com/Raku/old-issue-tracker/issues/4112) NYI -- this is something I'd use on the regular
*   [do statement is not fully considered to be a loop](https://github.com/Raku/old-issue-tracker/issues/6475) -- ran into this while I was trying to work around the absence of "leave"
*   [Label.goto() not yet implemented](https://github.com/Raku/old-issue-tracker/issues/6297) -- this would also allow me to work around the absence of "leave"
*   [error message with misspelled labels](https://github.com/Raku/old-issue-tracker/issues/4595)
*   [error message on illegally post-declared label in Rakudo](https://github.com/Raku/old-issue-tracker/issues/4411)
*   [Can't 'last' from the first label in a multi-labeled loop in Rakudo](https://github.com/Raku/old-issue-tracker/issues/3391)

**Comment by wayland** [comment]
What's the blocker here?  Is it:
- We'd first need to implement labels on all blocks, not just loops?  This doesn't throw an error, but I'm not sure it's functional either
- Something to do with multithreading
- Something else I haven't thought of

**Comment by lizmat** [comment]
The issue with `leave` is really that it would a. introduce a lot more complexity in hot code, b. while the absence of it can be fixed pretty easily by changing a block into a `sub` and using `return`.

**Comment by lizmat** [comment]
Closing as it is 99.9% certain that "leave" will never be implemented.
