### ISSUE TITLE
REPL Version `2023.05` fails to blank out `$/` prior to running  a new incoming `.match(...)` statement entry. 

### ISSUE THREAD

**Issue by jubilatious1** [rakudo/rakudo#5583]
### REPL Version `2023.05` fails to blank out (i.e. `Nil`) a previously-set `$/` prior to running  a new incoming (`.match`) statement entry. 

Can someone check with a more recent REPL Version, please?

### The Problem 
[ NOTE:  REPL statement entries below have been renumbered ]:

```perl6
~ % raku
Welcome to Rakudo™ v2023.05.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.05.

To exit type 'exit' or '^D'
[1] > say $/ if "cow cow">>.match(:global, /co(.)/);
Nil
[2] > say $/ if "cow cow">>.match(:global, /co(.)/);
Nil
[3] > say $/ if "cow cow".match(:global, /co(.)/);
(｢cow｣
 0 => ｢w｣ ｢cow｣
 0 => ｢w｣)
[4] > say $/ if "cow cow">>.match(:global, /co(.)/);
(｢cow｣
 0 => ｢w｣ ｢cow｣
 0 => ｢w｣)
[5] > say $/ if "cow cow">>.match(:global, /co(t)/);
(｢cow｣
 0 => ｢w｣ ｢cow｣
 0 => ｢w｣)
```
### Expected Behavior

 - The first two REPL statement entries are identical (`:global` match attempts). 

 - For each of the first 2 statements a `>>` hyper is attempted , and `Nil` is returned (as the value of `$/`).

- Identical statements should give identical returns, so this is consistent behavior so far (consistent, but disappointing).

 - The third statement removes the `>>` hyper call but is otherwise identical to the first two statements.

 - [FINALLY] the REPL correctly returns the expected two `$/` matches (and `$0` submatches) .

 - The fourth statement restores  the `>>` hyper call, making the fourth statement identical to the first two.

- Now we see that the fourth statement simply spits out the previously-recorded `$/` value, indicating that `$/` has not been properly `Nil`ed prior to running the `.match` statement.

### Actual Behavior

 - This problem is driven home in statement FIVE (5).

 - The input text `"cow cow"` should never match the `:global` regex ` /co(t)/`, but the previously recorded `cow` match (_et al_) is returned:
```perl6
(｢cow｣
 0 => ｢w｣ ｢cow｣
 0 => ｢w｣)
```

### Environment
* Operating system: `MacOS Ventura 13.6.7`
* Compiler version: `Rakudo™ v2023.05.`

@doomvox 
@Util 
@fecundf 
@0rir

**Comment by jubilatious1** [comment]
FYI, running the five statements above in a Raku script gives the same (erroneous) return as in the REPL:

```perl6
say $/ if "cow cow">>.match(:global, /co(.)/);
say $/ if "cow cow">>.match(:global, /co(.)/);
say $/ if "cow cow".match(:global, /co(.)/);
say $/ if "cow cow">>.match(:global, /co(.)/);
say $/ if "cow cow">>.match(:global, /co(t)/);
```

**Comment by ab5tract** [comment]
Using `>>` creates a `List`, so you need to adjust how you check it for truthiness:

```
say "true?" if [False]
# true?

say "true? if && [False]
# (No Output)
```

As to `$/` being set to `Nil` even after a successful (hyper-ed) match, I'm not sure what is going on there exactly. I do know that there has been quite some discussion about this special variable over the years. My first assumption is that it is being set in the scope of the hyper call and is not propagated back up to the callsite scope. If that's the case I would expect that doing any such propagation would probably be quite messy and cause a fair amount of WATs.

Hopefully someone who is more familiar with the curious corners of `$/` can chime in.

**Comment by jubilatious1** [comment]
@ab5tract wrote:
> Using `>> `creates a `List`, so you need to adjust how you check it for truthiness:

Technically, I think it's the `:global` named-argument that determines if a `List` is returned or not. Nary a `>>` below:
```perl6
say $/.WHAT if "cow cow".match(:global, /co(.)/); #(List)
say $/.WHAT if "cow cow".match(/co(.)/); #(Match)
```

But maybe you've hit the nail on the head? Add the hyper back and you lose the `(List)` return:
```perl6
say $/.WHAT if "cow cow">>.match(:global, /co(.)/); #(Match)
say $/.WHAT if "cow cow">>.match(/co(.)/); #(Match)
```

**Comment by ab5tract** [comment]
I think you've missed the point I was making:

```
> say $/ if [False]
# Nil
> "foo" ~~ /(\w+)/
｢foo｣
 0 => ｢foo｣
> say $/ if [False]
｢foo｣
 0 => ｢foo｣
 ```

When you are doing `say $/ if "example of not a match">>.match/(\d+)/)`, it's not printing the previous `$/` because the match erroneously succeeded. The match did not succeed. It's printing because you are asking a list for it's truthiness and it has > 0 elements.

**Comment by lizmat** [comment]
This is actually not a `REPL` issue, but an issue with `>>.match`.

```
$ raku -e '$/ = 42; say "cow cow">>.match(:global, /co(.)/); say $/'
((｢cow｣
 0 => ｢w｣ ｢cow｣
 0 => ｢w｣))
42
```
As you can see, the `>>.match` **does** return a `Match` object, but does **not** set `$/`.

Closing this in favour of #5694
