### ISSUE TITLE
Rakudo 2024.07 is not supported on 'windows-latest'

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#5619]
## The Problem

In the github runner for Rakudo 'latest' and 'windows-latest' I get the following:

    WARNING: OS mswin32 not supported, please file an issue

and the test run eventually fails when running 'pdftotext' in a shell process.

I'll try to rerun with the suggested raku command later add more information.

**Comment by ugexe** [comment]
As mentioned in another issue, that warning is being generated by code you have written, i.e. you are the one in control of that error condition happening or not
https://github.com/tbrowder/QueryOS/blob/cc97fdf78232a484c7931ac345321af7cb7c7854/lib/QueryOS.rakumod#L96-L99
