### ISSUE TITLE
Highlighting of undeclared sub

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#5628]
## The Problem
Highlighting of undeclared subs does not raise an error, but does not highlight.
## Expected Behavior
Either a compile time error that can be trapped, or a highlighted string.

Although the default for a Raku program is for warnings to be strict, thus causing compile time errors to fail, maybe the default for highlighting should turn off strict warnings?
## Actual Behavior
Highlight string:
`say foo`

## Steps to Reproduce
```
use experimental :rakuast;
use RakuAST::Deparse::Highlight;
my @warnings;
my $source = $=finish;
my $hilited;
try {
    $hilited = highlight($source, 'HTML');
}
with $! {
    @warnings.push( 'Error when highlighting ｢' ~
        ( $source.chars > 200
            ?? ($source.substr(200) ~ ' ... ')
            !! $source.trim ) ~
        '｣' ~ "\nbecause\n" ~ .message );
}
#say 'error: ',$!.raku, "\nmess:\n",$!.message;
say "highlighted:\n", $hilited;
if +@warnings {
    say "Warnings generated:"
    .say for @warnings;
}
else { say "No warnings" }
=finish
say foo
```
Output:
```
$ raku hilite.raku
highlighted:

No warnings
```
Modifying the program to change the highlight string to
```
=finish
my &foo = {...};
say foo
```
yields:
```
$ raku hilite.raku
highlighted:
<span style="color:magenta;">my</span> <span style="color:cyan;">&foo</span> <span style="color:yellow;">=</span> {
    <span style="color:none;">...</span> 
}<span style="color:blue;"></span>
<span style="color:yellow;">say</span> <span style="color:yellow;">foo</span>

No warnings
```

## Environment
* Operating system: Ubuntu
* Compiler version (`rakudo -v` or `raku -v`):

Welcome to Rakudo™ v2024.07-106-g06d11b591.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.07-9-g2d0e2453a.

**Comment by lizmat** [comment]
The `highlight` sub will return a `Failure` if the compilation of the given code failed.  It has the original `Exception` wrapped.  To be able to get at the actual error message, you first call the `exception` method on the `Failure` to get the `Exception`, and then call the `.message` method on that.
```raku
use RakuAST::Deparse::Highlight;
my @messages;

my $hilited = highlight("say foo", 'Text');
if $hilited {
    say $hilited;
}
else {
    @messages.push: $hilited.exception.message;
}
```
Instead of the `with $! {`, you could do `without $hilited {` instead, and use `$hilited.exception.message` instead of `.message`.

Does that make sense?

**Comment by lizmat** [comment]
Cannot reproduce:  on HEAD (2024.07-210-gc1520df7c) I get:
```
highlighted:
<span style="color:yellow;">say</span> <span style="color:yellow;">foo</span>
```

**Comment by lizmat** [comment]
I believe this is now fixed, please close if confirmed.

**Comment by finanalyst** [comment]
closing as resolved
