### ISSUE TITLE
Post comments fail, pre comments highlight

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#5629]
## The Problem
The placing of comments in a highlight string affect whether the string compiles

## Expected Behavior
Order should not affect highlighting

## Actual Behavior

```
my $var = 2;
# here is a comment
```
does not highlight.

Meanwhile 
```
# here is a comment
my $var = 2;
```
highlights to:
```
<span style="color:blue;"># here is a comment</span>
<span style="color:magenta;">my</span> <span style="color:cyan;">$var</span> <span style="color:yellow;">=</span> <span style="color:red;">2</span>
```

## Steps to Reproduce

Test code:
```
use experimental :rakuast;
use RakuAST::Deparse::Highlight;
my $source = $=finish;
my $hilited = highlight($source, 'HTML');
if $hilited {
    say "highlighted:\n", $hilited;
}
else {
    say "Warnings generated:\n",
    $hilited.exception.message;
}
=finish
my $var = 2;
# here is a comment
```
produces
```
$ raku hilite.raku
Warnings generated:
Unable to call postcircumfix @!soc[ Nil ] with a type object
Indexing requires a defined object
```

## Environment Ubuntu
* Operating system:
* Compiler version (`rakudo -v` or `raku -v`):
$ raku -v
Welcome to Rakudo™ v2024.07-208-ge1ffa0fe1.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.07-9-g2d0e2453a.

**Comment by lizmat** [comment]
I believe this is now fixed, please close if confirmed.

**Comment by finanalyst** [comment]
closing as resolved
