### ISSUE TITLE
[rakuast-highlight] problems with =finish

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#5633]
Two errors encountered with =finish

- Test 1 
```
B<V<=>finish
{ "key1": "a string value", "key2": "another value" }>
```
generates the following from the test framework below
```
========== highlighting ==========
B<V<=>finish
{ "key1": "a string value", "key2": "another value" }>

---------- generates errors ----------
Two terms in a row

```
It is expected that anything after `=finish` would be a string, and so not compiled.

- Test 2
```
B<=finish
{ "key1": "a string value", "key2": "another value" }>
```
generates
```
========== highlighting ==========
B<=finish
{ "key1": "a string value", "key2": "another value" }>

---------- highlights to ----------
<span style="color:green;">=finish</span>
<span style="color:magenta;">{ "key1": "a string value", "key2": "another value" }
```
1. The callable for B in %allow has not been used,
2. The final `span` has not been ended with `</span>`

# Test framework
```
use experimental :rakuast;
use RakuAST::Deparse::Highlight;
my %allow =
  B => { '<span class="basis">' ~ .atoms ~ '</span>' },
  V => { say 'verbatim is:',.atoms ; .atoms }
;
my $source = $=finish;
my $hilited = highlight($source, 'HTML', :%allow, :unsafe);
say '=' x 10, ' highlighting ' , '=' x 10, "\n", $source;
if $hilited {
    say '-' x 10, ' highlights to ', '-' x 10, "\n", $hilited;
}
else {
    say '-' x 10, ' generates errors ', '-' x 10, "\n", $hilited.exception.message;
}
=finish
B<V<=>finish
{ "key1": "a string value", "key2": "another value" }>
```
The full RakuDoc source is:
```
=begin code :allow< V B > :lang<raku>
    use JSON::Fast;
    my %h = from-json( B<$=finish> );
    say %h.raku;
    # more lines of code

    B<V<=>finish
    { "key1": "a string value", "key2": "another value" }>
=end code
```
# Environment
Ubuntu
Raku
```
$ raku -v
Welcome to Rakudo™ v2024.07-216-g09a96033c.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.07-13-g5e52422f4.
```

**Comment by finanalyst** [comment]
I've just discovered that 'magenta' ending is failing in the existing tests. So this is a known problem.

**Comment by lizmat** [comment]
I'm confused about this test.

Is it supposed to be part of a rakudoc sequence?  From the example, it looks like it's not.  In which case it's invalid code?

**Comment by lizmat** [comment]
nvm, I understand the cause now....

**Comment by lizmat** [comment]
Ok, this is turning into quite a brain-breaker.

The problem is really that:
1. need to remove markup from string to get compileable code
2. but remember where the markup was in the code
3. we could leave "invisible" markers in the code with **#`(...)** but a. there is no guarantee they will not cause compilation errors, and b. they disappear from the AST
4. so my approach was to look for the content strings
5. but that breaks with `V<=>` as the `=` occurs in the `<span style="...">`

Continuing to mull....

**Comment by lizmat** [comment]
@finanalyst I'm getting closer to the point where I will say: "sorry, recursive markup is not allowed inside code examples".  Comments?
