### ISSUE TITLE
Redirection instead of comparison in set-env.ps1

### ISSUE THREAD

**Issue by pullrich** [rakudo/rakudo#5636]
## The Problem

1. set-env.ps1 (in C:\Program Files\Rakudo\scripts) reports an error when more than one version of "MS Build tools" is installed.

## Expected Behavior
The set-env.ps1 script should select the most current installed version.

## Actual Behavior
(The line number is off because of my Write-Host-debugging 😄.)
It produces the error:
```
Out-File: C:\Program Files\Rakudo\scripts\set-env.ps1:20
Line |
  20 |              if ($cim.Version > $chosen_cim.Version) {
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path 'C:\Program Files\Rakudo\scripts\15.9.28307.2094' is denied.
```

## Steps to Reproduce
Well to reproduce it one would have to install multiple versions of the "MS Build tools" and run the script. But as can be seen in the error message an understandable but wrong operator choice has been made.
The script can be changed to:
```
if ($cim.Version -gt $chosen_cim.Version) {
```
... otherwise a redirection (">") to a file is tried and this fails because Raku is installed in an Administrator owned directory.

## Environment
* Operating system: Windows 10
* Windows PowerShell
```
echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.4780
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4780
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
* PowerShell
```
echo $psversiontable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
* Installed MS Build tools
  * MSFT_VSInstance: Visual Studio Community 2017 (IdentifyingNumber = "913b96aa", Name = "Visual Studio Community 2017", Vendor = "Microsoft Corporation", Version = "15.9.28307.2094")
  * MSFT_VSInstance: Visual Studio Build Tools 2022 (IdentifyingNumber = "dcc15434", Name = "Visual Studio Build Tools 2022", Vendor = "Microsoft Corporation", Version = "17.11.35222.181")

**Comment by patrickbkr** [comment]
Thanks for the report and fix!
