### ISSUE TITLE
rakudo optimizer changes behaviour of `$_ ~~ Mu:U`

### ISSUE THREAD

**Issue by timo** [rakudo/rakudo#5644]
## The Problem

I randomly stumbled upon this when looking for a good piece of code to suggest for "does this variable have a type object in it?":

```
rakudo -e '$_ = Int; say $_ ~~ Mu:U; $_ = 99; say $_ ~~ Mu:U'
rakudo --optimize=off -e '$_ = Int; say $_ ~~ Mu:U; $_ = 99; say $_ ~~ Mu:U'
```

## Expected Behavior

```
True
False

True
False
```

## Actual Behavior

```
True
True

True
False
```

## Environment

```
Welcome to Rakudo™ v2024.08-87-g067cd6f3e.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.08-10-g571effbd4.

Distributor ID: Fedora
Description:    Fedora Linux 40.20240911.0 (Kinoite)
```

## Bisect

I bisected the commit where with `$_ = 99` the result of `say $_ ~~ Mu:U` switched from False to True:

https://github.com/rakudo/rakudo/commit/91ec1bbf60

This is what I think is the relevant part of the `--target=optimize` output. with `--optimize=` off or 1 it emits a regular call to `&infix:<~~>` instead.
```
- QAST::Op(if)  :smartmatch_optimized<?>
  - QAST::Op(if) 
    - QAST::Op(istype) 
      - QAST::Var(local __lowered_lex_1) <wanted> $_
      - QAST::WVal(Junction) 
    - QAST::Op(isconcrete) 
      - QAST::Var(local __lowered_lex_1) <wanted> $_
  - QAST::Op(callmethod BOOLIFY-ACCEPTS) 
    - QAST::Var(local __lowered_lex_1) <wanted> $_
    - QAST::WVal(Mu:U) <wanted> Mu:U
    - QAST::WVal(Bool) 
  - QAST::WVal(Bool) 
```

**Comment by lizmat** [comment]
This appears fixed (as in perhaps: not yet broken again) in RakuAST

**Comment by ab5tract** [comment]
A fix that works locally is just to reject the optimization when LHS is `$_`.

But I'll look into why its working in the RHS to see if I can come up something less brutal.

**Comment by vrurg** [comment]
> A fix that works locally is just to reject the optimization when LHS is `$_`.
> EDIT: Also curious why it works fine in (all?) other cases on the LHS.

Actually, not all. Any variable on LHS, not topic alone, results in the same behavior. This part of the optimizer is likely to be my fault and for one very simple reason: this particular case of `Mu:U` is an oversight. Most of the time presence of `Mu` in RHS means "it's just `True`". 

Of the QAST above the only relevant line to the case is the last one – i.e. the Bool constant. It means the optimizer found a compile-time available value on RHS, found out that it's `Mu` and suggested that the entire expression is likely to be `True` (unless LHS is a `Junction` which is to be checked at the run-time). So, if anybody is brave enough to try fixing it, best is to find all `maybe_respect_junctions` calls in Optimizer.nqp and see what methods calling them are doing.

**Comment by ab5tract** [comment]
I believe the linked MR to be in reviewable state now. Thanks for pointing out that this applies beyond $_, @vrurg.

**Comment by ab5tract** [comment]
Fix has been merged.
