### ISSUE TITLE
Performance regression since 2024.09: integration/advent2012-day21.t from roast hogs up all memory

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#5665]
## The Problem
Running `integration/advent2012-day21.t` from roast hogs up all memory.

## Expected Behavior
The tests from that file should pass without memory shortages.

## Actual Behavior
As described in https://github.com/Raku/roast/pull/864#issuecomment-2415585504 processes get killed due to memory shortage

## Steps to Reproduce
```
$ raku integration/advent2012-day21.t
```
or alternatively
```
$ make stresstest
```

## Environment
I'm seeing this with 
* Operating system: FreeBSD 14.1-RELEASE-p5
* Compiler version (`rakudo -v` or `raku -v`): Welcome to Rakudo™ v2024.09-80-gd2f12f352.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.09-5-g174aa1ba9.

But I guess it's not specific to FreeBSD.

**Comment by MasterDuke17** [comment]
Using linux and getting the same behavior. It can be shortened to at least:
```raku
my @numbers = flat 1..3;
 
sub collatz-length(Int $start) {
    +($start, { when * %% 2 { $_ / 2 }; when * !%% 2 { 3 * $_ + 1 }; } ... 1);
}
my $expected-output = @numbers.map( -> $n {"$n: " ~ collatz-length($n)}).join("\n") ~ "\n";
say $expected-output;
```

The numbers don't seem to matter too much, as long as one triggers the length to be greater than 2.

**Comment by usev6** [comment]
Oh, nice to have a shorter version.

I bisected the problematic behavior to https://github.com/rakudo/rakudo/commit/0f5d54d238.
Reverting that commit makes the tests pass again.

**Comment by lizmat** [comment]
Reverted with https://github.com/rakudo/rakudo/commit/4b53990c2b
