### ISSUE TITLE
[RakuDoc] =for and =begin act differently with content of =config

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#5723]
## The Problem
The following should AFAIK be the same
```
=begin code :lang<RakuDoc>
    =config * :!error
=end code
Some text
```
and
```
=for code :lang<RakuDoc>
    =config * :!error

Some text
```

Update: Same happens with implicit code, eg.
```
blah blah

   =config code :allow<B>

blah blah
```
## Expected Behavior
The `=begin code` sequence yields the following AST fragment
```
RakuAST::Doc::Block.new(
  type       => "code",
  config     => ${:lang(RakuAST::QuotedString.new(
    processors => <words val>,
    segments   => (
      RakuAST::StrLiteral.new("RakuDoc"),
    )
  ))},
  paragraphs => (
    "=config * :!error\n",
  )
),,
"some text\n"
```
The `=for code` should give  a similar AST (except the for flag would be True)

## Actual Behavior
The `=for code` sequence generates a block for `=config`
```
RakuAST::Doc::Block.new(
  type   => "code",
  for    => True,
  config => ${:lang(RakuAST::QuotedString.new(
    processors => <words val>,
    segments   => (
      RakuAST::StrLiteral.new("RakuDoc"),
    )
  ))}
),
RakuAST::Doc::Block.new(
  type       => "config",
  directive  => True,
  config     => ${:error(RakuAST::Term::Name.new(
    RakuAST::Name.from-identifier("False")
  ))},
  paragraphs => (
    "*",
  )
),
"some text\n\n",
```
## Environment
* Operating system:
* Compiler version (`rakudo -v` or `raku -v`):

**Comment by jubilatious1** [comment]
Is `=for` here the problem? Is this the same as the `=formula` issue, thus ready to close?

**Comment by finanalyst** [comment]
@jubilatious1 this is definitely not the same as the formula issue. The issue is not so much about `=for` as about how `=config` works in combination with `=for`.
Actually, its not even about `=for` per se, but about `=for code` & `=config` in the scope of the `=for`.

**Comment by finanalyst** [comment]
This may not be an error. Referring back to Issue #63 of Raku/RakuDoc-GAMMA

**Comment by finanalyst** [comment]
The parser is correct and I am not. Closing as resolved
