### ISSUE TITLE
[RakuDoc] DEPARSE of code block adds extra new line

### ISSUE THREAD

**Issue by finanalyst** [rakudo/rakudo#5724]
## The Problem
The DEPARSE of an AST for `=begin code` adds an extra new line after the code block when deparsing
## Expected Behavior
For a simple code block, the original RakuDoc and the DEPARSE of the AST should be the same

## Actual Behavior
Output from short program:
```
Original:
｢=begin code :lang<RakuDoc>
=config * :!error
=end code
｣
AST:
RakuAST::Doc::Block.new(
  type       => "rakudoc",
  paragraphs => (
    RakuAST::Doc::Block.new(
      type       => "code",
      config     => ${:lang(RakuAST::QuotedString.new(
        processors => <words val>,
        segments   => (
          RakuAST::StrLiteral.new("RakuDoc"),
        )
      ))},
      paragraphs => (
        "=config * :!error\n",
      )
    ),
  )
)
Deparsed differs from original, deparsed:
｢=begin rakudoc

=begin code :lang<RakuDoc>

=config * :!error
=end code

=end rakudoc

｣
```
The extra blank line after the `=begin` statement is unexpected

## Steps to Reproduce
Raku program is
```
use experimental :rakuast;

my $rakudoc = q:to/SRC/;
    =begin code :lang<RakuDoc>
    =config * :!error
    =end code
    SRC
my $ast = "=begin rakudoc\n$rakudoc\n=end rakudoc".AST.rakudoc.head;
say "Original:\n｢$rakudoc｣";
say "AST:\n", $ast;
say "Deparsed differs from original, deparsed:\n｢",$ast.DEPARSE,'｣'
    unless $ast eq $ast.DEPARSE
```
## Environment
* Operating system:  Ubuntu
* Compiler version (`rakudo -v` or `raku -v`):$ raku -v
Welcome to Rakudo™ v2024.10-50-gad05b8e04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.10-22-g385827cff.

**Comment by lizmat** [comment]
This is actually a broader issue, because leading whitespace is not significant.

The real question is: if the deparsed doc is parsed again, does it generate a different AST.  If it does, then there is a real issue.

**Comment by finanalyst** [comment]
Since content of a code block tends to be syntax highlighted, the leading whitespace is significant.
I think the problem is leading vertical whitespace, rather than leading horizontal whitespace on a line that otherwise contains content.
Suppose the content of the code block is a language in which leading whitespace is significant.

**Comment by lizmat** [comment]
> Suppose the content of the code block is a language in which leading whitespace is significant.

Then RakuDoc is not the documentation language to use.

**Comment by finanalyst** [comment]
Fair enough. Will rethink issue.

**Comment by lizmat** [comment]
I'm not saying there isn't a bug, it's just that:
```raku
=begin foo
bar
=end foo
```
and
```raku
=begin foo


bar
=end foo
```
create the same AST because leading whitespace is to be ignored as per spec.

**Comment by lizmat** [comment]
Closing as the AST from the .DEPARSE yields the same AST.
